<a href="https://colab.research.google.com/github/stilyank01-create/Media_AI/blob/main/05_training_evaluation_and_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Block 1 — Notebook 05 Initialisation and Architecture Handover Validation

### Purpose

This block initialises **Notebook 05 — Training, Evaluation and Validation** and validates the architectural handover produced by Notebook 04.

Notebook 04 established the Media AI model architecture and closed with a validated handover contract.

Notebook 05 moves the project from **architectural specification** to **experimental execution**.

Before model instantiation, optimisation or training is permitted, this block verifies that the architectural contracts required by Notebook 05 are available and internally consistent.

No model component is instantiated, trained or evaluated by this block.

---

### Notebook transition

The methodological transition between Notebook 04 and Notebook 05 is:

$$
\text{Architectural specification}
\rightarrow
\text{Experimental execution}
$$

Notebook 04 defines **what the architecture is**.

Notebook 05 investigates **whether and how the architecture can be instantiated, supervised, trained and empirically evaluated**.

Architectural validity is therefore treated as a prerequisite for experimentation rather than as evidence of empirical validity.

---

### Architectural handover

Notebook 05 receives the architecture validated in Notebook 04.

The integrated sentence-level processing sequence is:

$$
\text{Textual representation}
\rightarrow
\text{confluent conditioning}
\rightarrow
\text{representation heads}
\rightarrow
\text{transformative mechanism}
\rightarrow
\text{recurrent mechanism}
$$

This sequence must remain unchanged during Notebook 05 unless an explicitly documented experimental variant or ablation intentionally modifies it.

Any such modification must be identified as an experimental condition rather than silently replacing the reference architecture.

---

### Representation spaces

The architecture preserves three substantive representation spaces:

- **factual**;
- **psychological**;
- **social**.

These spaces remain analytically and computationally distinct.

They must not be collapsed into a single undifferentiated output representation during model instantiation or training.

---

### Factual representation

The factual representation contains **10 dimensions**:

- one Factological Weight dimension;
- nine explicit factological components.

The factual space represents factological structure and epistemic presentation.

It does not independently establish externally verified truth.

Accordingly:

$$
\text{factual representation}
\neq
\text{external truth verification}
$$

Missing factual supervision remains distinct from numerical zero.

Notebook 05 must preserve this distinction during target construction and loss calculation.

---

### Psychological representation

The psychological representation is the **34-dimensional Psychological State Vector**.

It contains:

- **11-dimensional Reported Emotion Vector (REV)**;
- **11-dimensional Transformative Emotion Vector (TEV)**;
- **11-dimensional Immediate Emotion Vector (IEV)**;
- **1-dimensional Emotional Weight (EW)**.

The representation is:

$$
Z^P_t
=
[
REV_t,\;
TEV_t,\;
IEV_t,\;
EW_t
]
$$

with:

$$
\dim(REV_t)=11
$$

$$
\dim(TEV_t)=11
$$

$$
\dim(IEV_t)=11
$$

$$
\dim(EW_t)=1
$$

and therefore:

$$
\dim(Z^P_t)=34
$$

REV and IEV remain bounded continuous representations.

TEV remains signed.

EW remains a bounded continuous scalar.

The eleven emotional dimensions are not mutually exclusive and are not constrained to a probability simplex.

---

### Social representation

The social representation remains **structured and variable-dimensional**.

It preserves four structural component classes:

- actors;
- groups;
- memberships;
- relationships.

Concrete group identities are not predefined.

Group detection remains dynamic and article-specific.

Overlapping group memberships remain permitted.

Relationships may be signed and directional.

The explicit social representation must not be converted into an arbitrary fixed-dimensional final output merely to simplify training.

Trainable hidden social representations may nevertheless be used internally where required by the architecture.

---

### Global and group-conditioned processing

The global representation path remains mandatory.

Where validated article-specific groups are available, additional group-conditioned paths may be constructed.

For representation space \(q\):

$$
Z^q_{t,G}
$$

denotes the global representation, while:

$$
Z^q_{t,g}
$$

denotes the representation conditioned on group \(g\).

The group-conditioned path supplements rather than replaces the global path.

Therefore:

$$
Z^q_{t,G}
\not\equiv
Z^q_{t,g}
$$

and the existence of a group-conditioned path does not invalidate the corresponding global representation.

---

### Group deviation

Where global and group-conditioned representations are aligned and comparable, signed group deviation may be defined as:

$$
D^q_{t,g}
=
Z^q_{t,g}
-
Z^q_{t,G}
$$

Group deviation is descriptive.

It is not automatically equivalent to:

- bias;
- manipulation;
- polarisation.

Social deviation additionally requires explicit structural alignment before meaningful comparison.

---

### Transformative mechanism

The architecture preserves separate factual, psychological and social transformations.

For representation space \(q\):

$$
q \in \{F,P,S\}
$$

the transformative mechanism produces a learned transformation associated with the current textual step.

Transformation remains distinct from simple consecutive-state subtraction.

In particular:

$$
\Delta^q_t
\neq
Z^q_t-Z^q_{t-1}
$$

unless a later explicitly defined experimental variant tests such a formulation.

---

### Transformative Weights

The reference architecture contains three independent Transformative Weights:

$$
TW^F_t,\qquad TW^P_t,\qquad TW^S_t
$$

representing:

- factual transformative salience;
- psychological transformative salience;
- social transformative salience.

Each remains bounded:

$$
0
\leq
TW^q_t
\leq
1
$$

The three Transformative Weights must remain separate.

Therefore:

$$
TW^F_t
\neq
TW^P_t
\neq
TW^S_t
$$

as architectural objects.

They may numerically coincide for a particular observation without becoming the same learned quantity.

Transformative Weight remains distinct from mathematical transformation magnitude.

Psychological Transformative Weight also remains distinct from Emotional Weight:

$$
TW^P_t
\neq
EW_t
$$

---

### TEV boundary

The Transformative Emotion Vector is part of the Psychological State Vector.

It remains distinct from the architectural psychological transformative mechanism.

Therefore:

$$
TEV_t
\neq
\Delta^P_t
$$

TEV is also not defined as the difference between consecutive Immediate Emotion Vectors:

$$
TEV_t
\neq
IEV_t-IEV_{t-1}
$$

Notebook 05 must preserve these distinctions during target construction and training.

---

### Recurrent mechanism

The architecture preserves three independent recurrent states:

$$
H^F_t,\qquad H^P_t,\qquad H^S_t
$$

representing:

- factual sequential persistence;
- psychological sequential persistence;
- social sequential persistence.

The recurrent update for representation space \(q\) is conceptually defined as:

$$
H^q_t
=
R^q
\left(
H^q_{t-1},
Z^q_t,
\tilde{\Delta}^q_t,
TW^q_t;
\theta^q_R
\right)
$$

The three recurrent states are not collapsed into a universal recurrent state.

---

### Transformative Weight and recurrent retention

Transformative Weight enters the recurrent mechanism as an input.

It is not the recurrent retention gate.

Therefore:

$$
TW^q_t
\neq
K^q_t
$$

This distinction permits the recurrent mechanism to learn whether a transformative textual step should reinforce, revise, attenuate or coexist with information already preserved in the recurrent state.

---

### Causal processing

Sequential processing remains causal.

For sentence \(t\), transformative and recurrent processing may depend only on information available at or before sentence \(t\).

Conceptually:

$$
H^q_t
=
R^q(X_{\leq t})
$$

and not:

$$
H^q_t
=
R^q(X_{>t})
$$

Future textual information must therefore remain inaccessible to the current sequential state.

This constraint must be preserved during batch construction, training and evaluation.

---

### Article boundaries

Recurrent states are article-specific.

At the beginning of each independent article, the recurrent state is reset.

Cross-article recurrent carry-over is prohibited in the reference architecture.

Therefore:

$$
H^q_0(j+1)
\neq
H^q_T(j)
$$

as a carry-over relationship between independent articles.

Notebook 05 must preserve article identity and sentence order when constructing sequential training data.

---

### Missing supervision

Notebook 05 must preserve the distinction between:

- observed value;
- observed zero;
- unavailable value;
- structurally absent object;
- explicit negative observation.

Missing supervision must not be interpreted as zero or as negative evidence.

For prediction \(\hat{y}_i\), target \(y_i\), and availability mask \(m_i\), supervised optimisation conceptually follows:

$$
\mathcal{L}_{masked}
=
\frac{
\sum_i m_i\,\ell(\hat{y}_i,y_i)
}{
\sum_i m_i
}
$$

only where valid supervised observations exist.

If no valid target values are available for a particular objective, that objective must remain inactive rather than generating artificial supervision.

---

### Training boundary

Notebook 05 is permitted to instantiate and train architectural components only after their supervision and training conditions have been explicitly established.

The experimental sequence therefore begins conceptually as:

$$
\text{handover validation}
\rightarrow
\text{supervision inventory}
\rightarrow
\text{model instantiation}
\rightarrow
\text{data construction}
\rightarrow
\text{optimisation}
\rightarrow
\text{controlled forward pass}
\rightarrow
\text{training}
\rightarrow
\text{evaluation}
$$

Block 1 performs only the first stage.

---

### Parameter-control boundary

No model parameter becomes trainable automatically.

Notebook 05 must explicitly identify:

- trainable parameter groups;
- frozen parameter groups.

This applies to:

- pretrained semantic backbone;
- confluent conditioning;
- factual head;
- psychological head;
- social head;
- group-conditioned adapters;
- transformative mechanism;
- recurrent mechanism.

The existence of a parameter in the computational graph does not by itself authorise optimisation of that parameter.

---

### Backbone boundary

The pretrained semantic backbone is not automatically trainable.

Its status must be explicitly determined before optimisation.

Possible experimental configurations may include:

- frozen backbone;
- partially adapted backbone;
- parameter-efficient adaptation;
- broader fine-tuning where experimentally justified.

The reference training configuration must record the selected policy explicitly.

Block 1 does not select or activate a backbone-training strategy.

---

### Experimental reproducibility

Notebook 05 inherits the project random seed:

$$
seed=42
$$

All relevant stochastic operations must use controlled random states where technically possible.

The experimental configuration must later record:

- model configuration;
- random seed;
- trainable parameters;
- frozen parameters;
- optimiser;
- learning rate;
- loss coefficients;
- batch construction;
- sequence handling;
- masking policy;
- stopping criterion;
- checkpoint-selection rule;
- evaluation configuration.

Architectural and experimental configurations must remain auditable.

---

### Evaluation requirement

Architectural validity does not imply empirical validity.

Notebook 05 must therefore evaluate the trained architecture using metrics appropriate to each representation space and task.

The following claims cannot be inferred merely from successful training:

- factual correctness;
- emotional validity;
- reliable group identification;
- absence of bias;
- manipulation detection;
- polarisation measurement;
- robustness;
- generalisation.

Such claims require explicit empirical evidence.

---

### Ablation requirement

The contribution of architectural mechanisms must be tested rather than assumed.

Notebook 05 should support controlled ablations including, where feasible:

- global path only;
- without group-conditioned routing;
- without transformative processing;
- without Transformative Weights;
- without recurrent processing;
- without group-conditioned residual adaptation;
- individual representation heads.

Ablations must preserve a clearly defined reference configuration so that observed differences can be meaningfully interpreted.

---

### Notebook 05 planned structure

Notebook 05 is organised around a target of ten blocks:

1. **Initialisation and Architecture Handover Validation**
2. **Supervision Inventory and Target Availability**
3. **Model Instantiation and Parameter-Freezing Policy**
4. **Training Dataset and Sequential Batch Construction**
5. **Loss Assembly and Optimiser Configuration**
6. **Controlled Forward-Pass and Sanity Checks**
7. **Training Execution**
8. **Validation, Early Stopping and Checkpoint Selection**
9. **Ablation, Robustness and Comparative Evaluation**
10. **Experimental Audit, Results Summary and Final Handover**

The ten-block structure is a readability target rather than a methodological constraint.

If an experimental stage requires separation to preserve clarity or reproducibility, an additional block may be introduced explicitly.

---

### Block 1 validation requirements

Before Notebook 05 proceeds to supervision analysis, Block 1 must verify that the Notebook 04 handover preserves:

- valid architectural integration;
- completed Notebook 04 architecture;
- three representation spaces;
- 10-dimensional factual representation;
- 34-dimensional psychological representation;
- structured variable-dimensional social representation;
- mandatory global routing;
- optional group-conditioned routing;
- three independent Transformative Weights;
- three independent recurrent states;
- causal sequential processing;
- article-boundary reset;
- mask-aware supervision semantics;
- explicit methodological boundaries.

A failed handover validation must stop Notebook 05 before model instantiation or training.

---

### Methodological boundaries

Block 1 does not:

- redefine the Notebook 04 architecture;
- modify representation dimensions;
- predefine concrete social groups;
- collapse representation spaces;
- collapse global and group-conditioned paths;
- collapse TW_F, TW_P and TW_S;
- collapse H_F, H_P and H_S;
- equate factological representation with truth;
- equate psychological representation with diagnosis;
- equate Transformative Weight with Emotional Weight;
- equate Transformative Weight with recurrent retention;
- equate TEV with architectural psychological transformation;
- define TEV as consecutive IEV subtraction;
- interpret group deviation automatically as bias;
- interpret group deviation automatically as manipulation;
- interpret group deviation automatically as polarisation;
- treat missing supervision as zero;
- treat missing supervision as negative evidence;
- permit future-context leakage;
- permit cross-article recurrent carry-over;
- select training targets;
- instantiate the integrated model;
- create an optimiser;
- execute a forward pass;
- train model parameters;
- evaluate model performance;
- establish empirical validity.

---

### Execution boundary

This block performs **Notebook 05 initialisation and architecture handover validation only**.

At this stage:

- Notebook 05 is initialised;
- the Notebook 04 handover is available for validation;
- the integrated architecture is checked for compatibility;
- representation-space contracts are preserved;
- transformative contracts are preserved;
- recurrent contracts are preserved;
- causal constraints are preserved;
- masking semantics are preserved;
- experimental reproducibility requirements are established;
- the Notebook 05 execution boundary is established.

However:

- supervision has not yet been inventoried;
- training targets have not been activated;
- the integrated model has not been instantiated;
- trainable parameter groups have not been activated;
- frozen parameter groups have not been finalised;
- training sequences have not been constructed;
- no optimiser has been created;
- no controlled forward pass has been executed;
- no loss has been calculated;
- no model training has been executed;
- no checkpoint has been selected;
- no ablation experiment has been executed;
- no empirical evaluation has been performed.

Block 1 therefore establishes a validated and reproducible starting point for Notebook 05 without altering the architecture inherited from Notebook 04.

**Block 2 — Supervision Inventory and Target Availability** may proceed only after the handover validation succeeds.

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Block 1: Initialisation and Architecture Handover Validation
# =============================================================================

from datetime import datetime, timezone
from pathlib import Path
import io
import json
import random

import numpy as np
import torch

from google.colab import auth
from google.auth import default
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload


# -----------------------------------------------------------------------------
# Notebook configuration
# -----------------------------------------------------------------------------

NOTEBOOK_05_VERSION = "1.0"

NOTEBOOK_05_NAME = "05_training_evaluation_and_validation"

NOTEBOOK_05_DISPLAY_NAME = (
    "Media AI — Notebook 05: Training, Evaluation and Validation"
)

NOTEBOOK_05_BLOCK = 1

NOTEBOOK_05_BLOCK_NAME = (
    "Initialisation and Architecture Handover Validation"
)

NOTEBOOK_05_INITIALISED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# -----------------------------------------------------------------------------
# Persistent handover configuration
# -----------------------------------------------------------------------------

EXPECTED_HANDOVER_VERSION = "1.1"

EXPECTED_HANDOVER_FILENAME = (
    "notebook_04_to_05_handover.json"
)

NOTEBOOK_05_HANDOVER_LOCAL_PATH = (
    Path("/content")
    / EXPECTED_HANDOVER_FILENAME
)


# -----------------------------------------------------------------------------
# Reproducibility
# -----------------------------------------------------------------------------

PROJECT_RANDOM_SEED = 42

random.seed(
    PROJECT_RANDOM_SEED
)

np.random.seed(
    PROJECT_RANDOM_SEED
)

torch.manual_seed(
    PROJECT_RANDOM_SEED
)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(
        PROJECT_RANDOM_SEED
    )


# -----------------------------------------------------------------------------
# Google Colab authentication
# -----------------------------------------------------------------------------

auth.authenticate_user()

NOTEBOOK_05_GOOGLE_AUTHENTICATED = True


# -----------------------------------------------------------------------------
# Google Drive service
# -----------------------------------------------------------------------------

def get_media_ai_drive_service():
    """
    Construct an authenticated Google Drive API service
    in the current Colab runtime.

    Explicit Colab authentication is performed before this function
    is called so that the runtime does not rely on unavailable
    Compute Engine metadata credentials.
    """

    credentials, _ = default(
        scopes=[
            "https://www.googleapis.com/auth/drive"
        ]
    )

    return build(
        "drive",
        "v3",
        credentials=credentials,
        cache_discovery=False,
    )


DRIVE_SERVICE_FOR_HANDOVER = (
    get_media_ai_drive_service()
)

NOTEBOOK_05_DRIVE_SERVICE_INITIALISED = True


# -----------------------------------------------------------------------------
# Persistent handover discovery
# -----------------------------------------------------------------------------

def find_handover_file(
    drive_service,
    filename,
):
    """
    Locate the most recently modified non-trashed Drive file
    matching the exact handover filename.
    """

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )


    query = (
        f"name = '{escaped_filename}' "
        "and trashed = false"
    )


    search_result = (
        drive_service
        .files()
        .list(
            q=query,
            spaces="drive",
            fields=(
                "files("
                "id,"
                "name,"
                "mimeType,"
                "createdTime,"
                "modifiedTime,"
                "size"
                ")"
            ),
            orderBy="modifiedTime desc",
            pageSize=20,
        )
        .execute()
    )


    matching_files = search_result.get(
        "files",
        [],
    )


    if not matching_files:
        raise FileNotFoundError(
            "Notebook 05 could not locate the persisted "
            f"handover file: {filename}"
        )


    return matching_files[
        0
    ]


NOTEBOOK_05_HANDOVER_DRIVE_FILE = (
    find_handover_file(
        drive_service=
            DRIVE_SERVICE_FOR_HANDOVER,

        filename=
            EXPECTED_HANDOVER_FILENAME,
    )
)


NOTEBOOK_05_HANDOVER_DRIVE_FILE_ID = (
    NOTEBOOK_05_HANDOVER_DRIVE_FILE[
        "id"
    ]
)

NOTEBOOK_05_HANDOVER_LOCATED = True


# -----------------------------------------------------------------------------
# Persistent handover download
# -----------------------------------------------------------------------------

def download_drive_file_bytes(
    drive_service,
    file_id,
):
    """
    Download a Google Drive file and return raw bytes.
    """

    request = (
        drive_service
        .files()
        .get_media(
            fileId=file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    done = False


    while not done:

        _, done = downloader.next_chunk()


    return buffer.getvalue()


NOTEBOOK_05_HANDOVER_RAW_BYTES = (
    download_drive_file_bytes(
        drive_service=
            DRIVE_SERVICE_FOR_HANDOVER,

        file_id=
            NOTEBOOK_05_HANDOVER_DRIVE_FILE_ID,
    )
)


if not NOTEBOOK_05_HANDOVER_RAW_BYTES:
    raise IOError(
        "Notebook 05 handover file was located but "
        "contained no downloadable data."
    )


NOTEBOOK_05_HANDOVER_DOWNLOADED = True


# -----------------------------------------------------------------------------
# Local audit copy
# -----------------------------------------------------------------------------

NOTEBOOK_05_HANDOVER_LOCAL_PATH.write_bytes(
    NOTEBOOK_05_HANDOVER_RAW_BYTES
)


if not NOTEBOOK_05_HANDOVER_LOCAL_PATH.exists():
    raise IOError(
        "Notebook 05 could not create a local audit copy "
        "of the handover."
    )


NOTEBOOK_05_HANDOVER_LOCAL_COPY_CREATED = True


# -----------------------------------------------------------------------------
# JSON parsing
# -----------------------------------------------------------------------------

try:

    NOTEBOOK_05_HANDOVER = json.loads(
        NOTEBOOK_05_HANDOVER_RAW_BYTES.decode(
            "utf-8"
        )
    )

except (
    UnicodeDecodeError,
    json.JSONDecodeError,
) as exc:

    raise ValueError(
        "Notebook 05 handover file is not valid UTF-8 JSON."
    ) from exc


if not isinstance(
    NOTEBOOK_05_HANDOVER,
    dict,
):
    raise TypeError(
        "Notebook 05 handover must decode to a dictionary."
    )


NOTEBOOK_05_HANDOVER_PARSED = True


# -----------------------------------------------------------------------------
# Handover identity validation
# -----------------------------------------------------------------------------

handover_version = NOTEBOOK_05_HANDOVER.get(
    "handover_version"
)

handover_source_notebook = NOTEBOOK_05_HANDOVER.get(
    "source_notebook"
)

handover_target_notebook = NOTEBOOK_05_HANDOVER.get(
    "target_notebook"
)

handover_architecture_valid = bool(
    NOTEBOOK_05_HANDOVER.get(
        "architecture_valid",
        False,
    )
)

handover_architecture_complete = bool(
    NOTEBOOK_05_HANDOVER.get(
        "architecture_complete",
        False,
    )
)


if handover_version != EXPECTED_HANDOVER_VERSION:
    raise ValueError(
        "Notebook 05 received an unsupported handover version. "
        f"Expected: {EXPECTED_HANDOVER_VERSION}. "
        f"Received: {handover_version}."
    )


if handover_source_notebook != "04_model_architecture":
    raise ValueError(
        "Notebook 05 handover source does not match "
        "Notebook 04."
    )


if handover_target_notebook != NOTEBOOK_05_NAME:
    raise ValueError(
        "Notebook 05 handover target does not match "
        "the current notebook."
    )


if not handover_architecture_valid:
    raise ValueError(
        "Notebook 05 handover does not contain a valid "
        "integrated architecture."
    )


if not handover_architecture_complete:
    raise ValueError(
        "Notebook 05 handover does not confirm completion "
        "of the Notebook 04 architecture."
    )


# -----------------------------------------------------------------------------
# Architecture sequence validation
# -----------------------------------------------------------------------------

EXPECTED_ARCHITECTURE_SEQUENCE = (
    "textual_representation",
    "confluent_conditioning",
    "representation_heads",
    "transformative_mechanism",
    "recurrent_mechanism",
)


handover_architecture_sequence = tuple(
    NOTEBOOK_05_HANDOVER.get(
        "architecture_sequence",
        (),
    )
)


if (
    handover_architecture_sequence
    != EXPECTED_ARCHITECTURE_SEQUENCE
):
    raise ValueError(
        "Notebook 05 architecture sequence does not match "
        "the validated Notebook 04 reference architecture."
    )


# -----------------------------------------------------------------------------
# Representation-space validation
# -----------------------------------------------------------------------------

EXPECTED_REPRESENTATION_SPACES = (
    "factual",
    "psychological",
    "social",
)


handover_representation_spaces = tuple(
    NOTEBOOK_05_HANDOVER.get(
        "representation_spaces",
        (),
    )
)


if (
    handover_representation_spaces
    != EXPECTED_REPRESENTATION_SPACES
):
    raise ValueError(
        "Notebook 05 representation spaces do not match "
        "the Notebook 04 architecture."
    )


# -----------------------------------------------------------------------------
# Factual representation validation
# -----------------------------------------------------------------------------

EXPECTED_FACTUAL_DIMENSIONS = 10

handover_factual_dimensions = (
    NOTEBOOK_05_HANDOVER.get(
        "factual_dimensions"
    )
)


if (
    handover_factual_dimensions
    != EXPECTED_FACTUAL_DIMENSIONS
):
    raise ValueError(
        "Factual representation dimensionality is invalid. "
        f"Expected: {EXPECTED_FACTUAL_DIMENSIONS}. "
        f"Received: {handover_factual_dimensions}."
    )


NOTEBOOK_05_FACTUAL_REPRESENTATION_IS_TRUTH = False

NOTEBOOK_05_FACTUAL_MISSING_EQUALS_ZERO = False


# -----------------------------------------------------------------------------
# Psychological representation validation
# -----------------------------------------------------------------------------

EXPECTED_PSYCHOLOGICAL_DIMENSIONS = 34

EXPECTED_PSYCHOLOGICAL_VECTOR_ORDER = (
    "REV",
    "TEV",
    "IEV",
    "EW",
)

EXPECTED_PSYCHOLOGICAL_VECTOR_DIMENSIONS = {
    "REV": 11,
    "TEV": 11,
    "IEV": 11,
    "EW": 1,
}


handover_psychological_dimensions = (
    NOTEBOOK_05_HANDOVER.get(
        "psychological_dimensions"
    )
)

handover_psychological_vector_order = tuple(
    NOTEBOOK_05_HANDOVER.get(
        "psychological_vector_order",
        (),
    )
)

handover_psychological_vector_dimensions = (
    NOTEBOOK_05_HANDOVER.get(
        "psychological_vector_dimensions",
        {},
    )
)


if (
    handover_psychological_dimensions
    != EXPECTED_PSYCHOLOGICAL_DIMENSIONS
):
    raise ValueError(
        "Psychological representation dimensionality is invalid. "
        f"Expected: {EXPECTED_PSYCHOLOGICAL_DIMENSIONS}. "
        f"Received: {handover_psychological_dimensions}."
    )


if (
    handover_psychological_vector_order
    != EXPECTED_PSYCHOLOGICAL_VECTOR_ORDER
):
    raise ValueError(
        "Psychological vector order does not match "
        "the Notebook 04 architecture."
    )


if (
    handover_psychological_vector_dimensions
    != EXPECTED_PSYCHOLOGICAL_VECTOR_DIMENSIONS
):
    raise ValueError(
        "Psychological vector component dimensions do not "
        "match the Notebook 04 architecture."
    )


NOTEBOOK_05_PSYCHOLOGICAL_EMOTIONS_MUTUALLY_EXCLUSIVE = False

NOTEBOOK_05_PSYCHOLOGICAL_SIMPLEX_REQUIRED = False


# -----------------------------------------------------------------------------
# Social representation validation
# -----------------------------------------------------------------------------

EXPECTED_SOCIAL_COMPONENTS = (
    "actors",
    "groups",
    "memberships",
    "relationships",
)


handover_social_components = tuple(
    NOTEBOOK_05_HANDOVER.get(
        "social_components",
        (),
    )
)

handover_social_fixed_dimensional = bool(
    NOTEBOOK_05_HANDOVER.get(
        "social_fixed_dimensional",
        True,
    )
)


if (
    handover_social_components
    != EXPECTED_SOCIAL_COMPONENTS
):
    raise ValueError(
        "Social representation components do not match "
        "the Notebook 04 architecture."
    )


if handover_social_fixed_dimensional:
    raise ValueError(
        "The social representation must remain "
        "variable-dimensional."
    )


NOTEBOOK_05_SOCIAL_FIXED_DIMENSIONAL = False

NOTEBOOK_05_SOCIAL_GROUPS_PREDEFINED = False

NOTEBOOK_05_SOCIAL_DYNAMIC_GROUP_DETECTION = True

NOTEBOOK_05_SOCIAL_OVERLAPPING_MEMBERSHIP = True

NOTEBOOK_05_SOCIAL_ALIGNMENT_REQUIRED = True


# -----------------------------------------------------------------------------
# Global and group-conditioned routing validation
# -----------------------------------------------------------------------------

handover_global_path_required = bool(
    NOTEBOOK_05_HANDOVER.get(
        "global_path_required",
        False,
    )
)

handover_group_path_optional = bool(
    NOTEBOOK_05_HANDOVER.get(
        "group_path_optional",
        False,
    )
)

handover_group_identities_predefined = bool(
    NOTEBOOK_05_HANDOVER.get(
        "group_identities_predefined",
        True,
    )
)


if not handover_global_path_required:
    raise ValueError(
        "Notebook 05 requires the global path "
        "to remain mandatory."
    )


if not handover_group_path_optional:
    raise ValueError(
        "Notebook 05 requires the group-conditioned path "
        "to remain optional."
    )


if handover_group_identities_predefined:
    raise ValueError(
        "Concrete group identities must not be predefined."
    )


NOTEBOOK_05_GLOBAL_PATH_REQUIRED = True

NOTEBOOK_05_GROUP_PATH_OPTIONAL = True

NOTEBOOK_05_GLOBAL_REPLACED_BY_GROUP = False

NOTEBOOK_05_GROUP_IDENTITIES_PREDEFINED = False


# -----------------------------------------------------------------------------
# Group-deviation validation
# -----------------------------------------------------------------------------

handover_group_deviation = (
    NOTEBOOK_05_HANDOVER.get(
        "group_deviation",
        {},
    )
)


EXPECTED_GROUP_DEVIATION = {
    "signed": True,
    "equals_bias": False,
    "equals_manipulation": False,
    "equals_polarisation": False,
    "alignment_required": True,
}


if (
    handover_group_deviation
    != EXPECTED_GROUP_DEVIATION
):
    raise ValueError(
        "Group-deviation semantics do not match "
        "the Notebook 04 architecture."
    )


NOTEBOOK_05_GROUP_DEVIATION_SIGNED = True

NOTEBOOK_05_GROUP_DEVIATION_EQUALS_BIAS = False

NOTEBOOK_05_GROUP_DEVIATION_EQUALS_MANIPULATION = False

NOTEBOOK_05_GROUP_DEVIATION_EQUALS_POLARISATION = False


# -----------------------------------------------------------------------------
# Transformative Weight validation
# -----------------------------------------------------------------------------

EXPECTED_TRANSFORMATIVE_WEIGHTS = {
    "factual": "TW_F",
    "psychological": "TW_P",
    "social": "TW_S",
}


handover_transformative_weights = (
    NOTEBOOK_05_HANDOVER.get(
        "transformative_weights",
        {},
    )
)


if (
    handover_transformative_weights
    != EXPECTED_TRANSFORMATIVE_WEIGHTS
):
    raise ValueError(
        "Notebook 05 Transformative Weight contract does not "
        "match the validated Notebook 04 architecture."
    )


if NOTEBOOK_05_HANDOVER.get(
    "transformative_weights_collapsed",
    True,
):
    raise ValueError(
        "Transformative Weights must remain separate."
    )


if NOTEBOOK_05_HANDOVER.get(
    "transformative_weights_shared",
    True,
):
    raise ValueError(
        "Transformative Weights must not be shared "
        "across representation spaces."
    )


if NOTEBOOK_05_HANDOVER.get(
    "tw_equals_emotional_weight",
    True,
):
    raise ValueError(
        "Transformative Weight must remain distinct "
        "from Emotional Weight."
    )


if NOTEBOOK_05_HANDOVER.get(
    "tw_equals_transformation_magnitude",
    True,
):
    raise ValueError(
        "Transformative Weight must remain distinct "
        "from transformation magnitude."
    )


if NOTEBOOK_05_HANDOVER.get(
    "tw_equals_retention_gate",
    True,
):
    raise ValueError(
        "Transformative Weight must remain distinct "
        "from recurrent retention."
    )


NOTEBOOK_05_TW_F = "TW_F"

NOTEBOOK_05_TW_P = "TW_P"

NOTEBOOK_05_TW_S = "TW_S"

NOTEBOOK_05_TRANSFORMATIVE_WEIGHTS_COLLAPSED = False

NOTEBOOK_05_TRANSFORMATIVE_WEIGHTS_SHARED = False

NOTEBOOK_05_TW_EQUALS_EW = False

NOTEBOOK_05_TW_EQUALS_MAGNITUDE = False

NOTEBOOK_05_TW_EQUALS_RETENTION_GATE = False


# -----------------------------------------------------------------------------
# TEV boundary validation
# -----------------------------------------------------------------------------

handover_tev_equals_architectural = bool(
    NOTEBOOK_05_HANDOVER.get(
        "tev_equals_architectural_transformation",
        True,
    )
)

handover_tev_equals_iev_difference = bool(
    NOTEBOOK_05_HANDOVER.get(
        "tev_equals_iev_difference",
        True,
    )
)


if handover_tev_equals_architectural:
    raise ValueError(
        "TEV must remain distinct from architectural "
        "psychological transformation."
    )


if handover_tev_equals_iev_difference:
    raise ValueError(
        "TEV must not be defined as consecutive "
        "IEV subtraction."
    )


NOTEBOOK_05_TEV_EQUALS_ARCHITECTURAL_TRANSFORMATION = False

NOTEBOOK_05_TEV_EQUALS_IEV_DIFFERENCE = False


# -----------------------------------------------------------------------------
# Recurrent-state validation
# -----------------------------------------------------------------------------

EXPECTED_RECURRENT_STATES = {
    "factual": "H_F",
    "psychological": "H_P",
    "social": "H_S",
}


handover_recurrent_states = (
    NOTEBOOK_05_HANDOVER.get(
        "recurrent_states",
        {},
    )
)


if (
    handover_recurrent_states
    != EXPECTED_RECURRENT_STATES
):
    raise ValueError(
        "Notebook 05 recurrent-state contract does not "
        "match the Notebook 04 architecture."
    )


if NOTEBOOK_05_HANDOVER.get(
    "recurrent_states_collapsed",
    True,
):
    raise ValueError(
        "Factual, psychological and social recurrent "
        "states must remain separate."
    )


NOTEBOOK_05_H_F = "H_F"

NOTEBOOK_05_H_P = "H_P"

NOTEBOOK_05_H_S = "H_S"

NOTEBOOK_05_RECURRENT_STATES_COLLAPSED = False


# -----------------------------------------------------------------------------
# Causal-processing validation
# -----------------------------------------------------------------------------

handover_causal_processing = bool(
    NOTEBOOK_05_HANDOVER.get(
        "causal_processing",
        False,
    )
)

handover_future_context_allowed = bool(
    NOTEBOOK_05_HANDOVER.get(
        "future_context_allowed",
        True,
    )
)


if not handover_causal_processing:
    raise ValueError(
        "Notebook 05 requires causal sequential processing."
    )


if handover_future_context_allowed:
    raise ValueError(
        "Notebook 05 reference architecture must not permit "
        "future-context leakage."
    )


NOTEBOOK_05_CAUSAL_PROCESSING = True

NOTEBOOK_05_FUTURE_CONTEXT_ALLOWED = False


# -----------------------------------------------------------------------------
# Article-boundary validation
# -----------------------------------------------------------------------------

handover_article_boundary_reset = bool(
    NOTEBOOK_05_HANDOVER.get(
        "article_boundary_reset",
        False,
    )
)

handover_cross_article_carry = bool(
    NOTEBOOK_05_HANDOVER.get(
        "cross_article_carry",
        True,
    )
)


if not handover_article_boundary_reset:
    raise ValueError(
        "Notebook 05 requires recurrent-state reset "
        "at independent article boundaries."
    )


if handover_cross_article_carry:
    raise ValueError(
        "Cross-article recurrent carry-over is not permitted "
        "in the reference architecture."
    )


NOTEBOOK_05_ARTICLE_BOUNDARY_RESET = True

NOTEBOOK_05_CROSS_ARTICLE_CARRY = False


# -----------------------------------------------------------------------------
# Masking and supervision validation
# -----------------------------------------------------------------------------

handover_mask_aware_supervision = bool(
    NOTEBOOK_05_HANDOVER.get(
        "mask_aware_supervision",
        False,
    )
)

handover_missing_equals_zero = bool(
    NOTEBOOK_05_HANDOVER.get(
        "missing_supervision_equals_zero",
        True,
    )
)

handover_missing_equals_negative = bool(
    NOTEBOOK_05_HANDOVER.get(
        "missing_supervision_equals_negative",
        True,
    )
)

handover_unavailable_enters_loss = bool(
    NOTEBOOK_05_HANDOVER.get(
        "unavailable_supervision_enters_loss",
        True,
    )
)


if not handover_mask_aware_supervision:
    raise ValueError(
        "Notebook 05 requires mask-aware supervision."
    )


if handover_missing_equals_zero:
    raise ValueError(
        "Missing supervision must remain distinct "
        "from numerical zero."
    )


if handover_missing_equals_negative:
    raise ValueError(
        "Missing supervision must remain distinct "
        "from negative supervision."
    )


if handover_unavailable_enters_loss:
    raise ValueError(
        "Unavailable supervision must not contribute "
        "to optimisation loss."
    )


NOTEBOOK_05_MASK_AWARE_SUPERVISION = True

NOTEBOOK_05_MISSING_EQUALS_ZERO = False

NOTEBOOK_05_MISSING_EQUALS_NEGATIVE = False

NOTEBOOK_05_UNAVAILABLE_ENTERS_LOSS = False

NOTEBOOK_05_OBSERVED_ZERO_DISTINCT_FROM_MISSING = True


# -----------------------------------------------------------------------------
# Reproducibility validation
# -----------------------------------------------------------------------------

handover_random_seed = NOTEBOOK_05_HANDOVER.get(
    "random_seed"
)


if handover_random_seed != PROJECT_RANDOM_SEED:
    raise ValueError(
        "Notebook 05 random seed does not match "
        "the Notebook 04 handover."
    )


NOTEBOOK_05_RANDOM_SEED = PROJECT_RANDOM_SEED

NOTEBOOK_05_REPRODUCIBILITY_REQUIRED = True

NOTEBOOK_05_CONFIGURATION_RECORD_REQUIRED = True

NOTEBOOK_05_CHECKPOINT_RULE_REQUIRED = True

NOTEBOOK_05_EXPERIMENT_CONFIGURATION_RECOVERABLE = True


# -----------------------------------------------------------------------------
# Experiment configuration and ablation contracts
# -----------------------------------------------------------------------------

REQUIRED_EXPERIMENT_CONFIGURATION_FIELDS = tuple(
    NOTEBOOK_05_HANDOVER.get(
        "required_experiment_configuration",
        (),
    )
)


if not REQUIRED_EXPERIMENT_CONFIGURATION_FIELDS:
    raise ValueError(
        "Notebook 05 handover does not contain "
        "the required experiment-configuration contract."
    )


PLANNED_ABLATIONS = tuple(
    NOTEBOOK_05_HANDOVER.get(
        "planned_ablations",
        (),
    )
)


if not PLANNED_ABLATIONS:
    raise ValueError(
        "Notebook 05 handover does not contain "
        "the planned ablation contract."
    )


# -----------------------------------------------------------------------------
# Notebook 05 execution boundary
# -----------------------------------------------------------------------------

NOTEBOOK_05_SUPERVISION_INVENTORIED = False

NOTEBOOK_05_TARGETS_ACTIVATED = False

NOTEBOOK_05_MODEL_INSTANTIATED = False

NOTEBOOK_05_PARAMETER_POLICY_FINALISED = False

NOTEBOOK_05_TRAINABLE_PARAMETER_GROUPS_ACTIVATED = False

NOTEBOOK_05_FROZEN_PARAMETER_GROUPS_FINALISED = False

NOTEBOOK_05_BACKBONE_AUTOMATICALLY_TRAINABLE = False

NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED = False

NOTEBOOK_05_OPTIMIZER_CREATED = False

NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED = False

NOTEBOOK_05_LOSS_CALCULATED = False

NOTEBOOK_05_TRAINING_EXECUTED = False

NOTEBOOK_05_CHECKPOINT_SELECTED = False

NOTEBOOK_05_ABLATION_EXECUTED = False

NOTEBOOK_05_EVALUATION_EXECUTED = False

NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED = False


# -----------------------------------------------------------------------------
# Notebook 05 planned structure
# -----------------------------------------------------------------------------

NOTEBOOK_05_PLANNED_BLOCKS = (
    "Initialisation and Architecture Handover Validation",
    "Supervision Inventory and Target Availability",
    "Model Instantiation and Parameter-Freezing Policy",
    "Training Dataset and Sequential Batch Construction",
    "Loss Assembly and Optimiser Configuration",
    "Controlled Forward-Pass and Sanity Checks",
    "Training Execution",
    "Validation, Early Stopping and Checkpoint Selection",
    "Ablation, Robustness and Comparative Evaluation",
    "Experimental Audit, Results Summary and Final Handover",
)

NOTEBOOK_05_TARGET_BLOCK_COUNT = len(
    NOTEBOOK_05_PLANNED_BLOCKS
)

NOTEBOOK_05_TARGET_BLOCK_COUNT_IS_HARD_LIMIT = False


# -----------------------------------------------------------------------------
# Block 1 validation
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_1_ERRORS = []


if handover_version != EXPECTED_HANDOVER_VERSION:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "handover_version_invalid"
    )


if not handover_architecture_valid:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "architecture_integration_invalid"
    )


if not handover_architecture_complete:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "notebook_04_architecture_incomplete"
    )


if (
    handover_representation_spaces
    != EXPECTED_REPRESENTATION_SPACES
):
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "representation_spaces_not_preserved"
    )


if (
    handover_factual_dimensions
    != EXPECTED_FACTUAL_DIMENSIONS
):
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "factual_dimensions_not_preserved"
    )


if (
    handover_psychological_dimensions
    != EXPECTED_PSYCHOLOGICAL_DIMENSIONS
):
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "psychological_dimensions_not_preserved"
    )


if (
    handover_social_components
    != EXPECTED_SOCIAL_COMPONENTS
):
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "social_components_not_preserved"
    )


if (
    handover_transformative_weights
    != EXPECTED_TRANSFORMATIVE_WEIGHTS
):
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "transformative_weights_not_preserved"
    )


if (
    handover_recurrent_states
    != EXPECTED_RECURRENT_STATES
):
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "recurrent_states_not_preserved"
    )


if not NOTEBOOK_05_CAUSAL_PROCESSING:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "causal_processing_not_preserved"
    )


if NOTEBOOK_05_FUTURE_CONTEXT_ALLOWED:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "future_context_incorrectly_allowed"
    )


if not NOTEBOOK_05_ARTICLE_BOUNDARY_RESET:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "article_boundary_reset_not_preserved"
    )


if NOTEBOOK_05_CROSS_ARTICLE_CARRY:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "cross_article_carry_incorrectly_enabled"
    )


if not NOTEBOOK_05_MASK_AWARE_SUPERVISION:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "mask_aware_supervision_not_preserved"
    )


if NOTEBOOK_05_MISSING_EQUALS_ZERO:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "missing_supervision_incorrectly_equals_zero"
    )


if NOTEBOOK_05_MISSING_EQUALS_NEGATIVE:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "missing_supervision_incorrectly_equals_negative"
    )


if NOTEBOOK_05_UNAVAILABLE_ENTERS_LOSS:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "unavailable_supervision_incorrectly_enters_loss"
    )


if NOTEBOOK_05_BACKBONE_AUTOMATICALLY_TRAINABLE:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "backbone_incorrectly_auto_trainable"
    )


if NOTEBOOK_05_MODEL_INSTANTIATED:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "model_incorrectly_instantiated_in_block_1"
    )


if NOTEBOOK_05_OPTIMIZER_CREATED:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "optimizer_incorrectly_created_in_block_1"
    )


if NOTEBOOK_05_TRAINING_EXECUTED:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "training_incorrectly_executed_in_block_1"
    )


if NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED:
    NOTEBOOK_05_BLOCK_1_ERRORS.append(
        "empirical_validity_incorrectly_established"
    )


NOTEBOOK_05_HANDOVER_VALID = (
    len(
        NOTEBOOK_05_BLOCK_1_ERRORS
    )
    == 0
)


if not NOTEBOOK_05_HANDOVER_VALID:
    raise ValueError(
        "Notebook 05 Block 1 handover validation failed: "
        f"{NOTEBOOK_05_BLOCK_1_ERRORS}"
    )


# -----------------------------------------------------------------------------
# Block 1 execution state
# -----------------------------------------------------------------------------

NOTEBOOK_05_INITIALISED = True

NOTEBOOK_05_HANDOVER_LOADED_FROM_DRIVE = True

NOTEBOOK_05_HANDOVER_VALIDATED = True

NOTEBOOK_05_BLOCK_1_COMPLETE = True


# -----------------------------------------------------------------------------
# Block 1 summary
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_1_SUMMARY = {
    "notebook":
        NOTEBOOK_05_NAME,

    "notebook_version":
        NOTEBOOK_05_VERSION,

    "block":
        NOTEBOOK_05_BLOCK,

    "block_name":
        NOTEBOOK_05_BLOCK_NAME,

    "initialised_at_utc":
        NOTEBOOK_05_INITIALISED_AT_UTC,

    "google_authenticated":
        NOTEBOOK_05_GOOGLE_AUTHENTICATED,

    "drive_service_initialised":
        NOTEBOOK_05_DRIVE_SERVICE_INITIALISED,

    "handover_filename":
        EXPECTED_HANDOVER_FILENAME,

    "handover_drive_file_id":
        NOTEBOOK_05_HANDOVER_DRIVE_FILE_ID,

    "handover_version":
        handover_version,

    "handover_valid":
        NOTEBOOK_05_HANDOVER_VALID,

    "architecture_sequence":
        handover_architecture_sequence,

    "representation_spaces":
        handover_representation_spaces,

    "factual_dimensions":
        handover_factual_dimensions,

    "psychological_dimensions":
        handover_psychological_dimensions,

    "social_components":
        handover_social_components,

    "transformative_weights":
        handover_transformative_weights,

    "recurrent_states":
        handover_recurrent_states,

    "causal_processing":
        NOTEBOOK_05_CAUSAL_PROCESSING,

    "article_boundary_reset":
        NOTEBOOK_05_ARTICLE_BOUNDARY_RESET,

    "mask_aware_supervision":
        NOTEBOOK_05_MASK_AWARE_SUPERVISION,

    "random_seed":
        NOTEBOOK_05_RANDOM_SEED,

    "planned_block_count":
        NOTEBOOK_05_TARGET_BLOCK_COUNT,

    "block_complete":
        NOTEBOOK_05_BLOCK_1_COMPLETE,
}


# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------

print("=" * 72)
print(
    "Media AI — Notebook 05, Block 1: "
    "Initialisation and Architecture Handover Validation"
)
print("=" * 72)

print(
    f"Notebook                     : "
    f"{NOTEBOOK_05_NAME}"
)

print(
    f"Notebook version             : "
    f"{NOTEBOOK_05_VERSION}"
)

print(
    f"Block                        : "
    f"{NOTEBOOK_05_BLOCK}"
)

print(
    f"Project random seed          : "
    f"{NOTEBOOK_05_RANDOM_SEED}"
)

print("-" * 72)

print("Google authentication")

print(
    f"Colab authenticated          : "
    f"{NOTEBOOK_05_GOOGLE_AUTHENTICATED}"
)

print(
    f"Drive service initialised    : "
    f"{NOTEBOOK_05_DRIVE_SERVICE_INITIALISED}"
)

print("-" * 72)

print("Persistent Notebook 04 handover")

print(
    f"Handover filename            : "
    f"{EXPECTED_HANDOVER_FILENAME}"
)

print(
    f"Drive file ID                : "
    f"{NOTEBOOK_05_HANDOVER_DRIVE_FILE_ID}"
)

print(
    f"Drive file modified          : "
    f"{NOTEBOOK_05_HANDOVER_DRIVE_FILE.get('modifiedTime')}"
)

print(
    f"Handover located             : "
    f"{NOTEBOOK_05_HANDOVER_LOCATED}"
)

print(
    f"Handover downloaded          : "
    f"{NOTEBOOK_05_HANDOVER_DOWNLOADED}"
)

print(
    f"Local audit copy             : "
    f"{NOTEBOOK_05_HANDOVER_LOCAL_COPY_CREATED}"
)

print(
    f"JSON parsed                  : "
    f"{NOTEBOOK_05_HANDOVER_PARSED}"
)

print(
    f"Loaded from Drive            : "
    f"{NOTEBOOK_05_HANDOVER_LOADED_FROM_DRIVE}"
)

print("-" * 72)

print("Notebook 04 handover contract")

print(
    f"Handover version             : "
    f"{handover_version}"
)

print(
    f"Source notebook              : "
    f"{handover_source_notebook}"
)

print(
    f"Target notebook              : "
    f"{handover_target_notebook}"
)

print(
    f"Architecture complete        : "
    f"{handover_architecture_complete}"
)

print(
    f"Architecture valid           : "
    f"{handover_architecture_valid}"
)

print(
    f"Handover valid               : "
    f"{NOTEBOOK_05_HANDOVER_VALID}"
)

print("-" * 72)

print("Architecture sequence")

for stage_index, stage_name in enumerate(
    handover_architecture_sequence,
    start=1,
):
    print(
        f"Stage {stage_index:<2}                     : "
        f"{stage_name}"
    )

print("-" * 72)

print("Representation spaces")

print(
    f"Representation spaces        : "
    f"{len(handover_representation_spaces)}"
)

print(
    f"Factual dimensions           : "
    f"{handover_factual_dimensions}"
)

print(
    f"Psychological dimensions     : "
    f"{handover_psychological_dimensions}"
)

print(
    f"Psychological vector order   : "
    f"{', '.join(handover_psychological_vector_order)}"
)

print(
    f"Social fixed-dimensional     : "
    f"{NOTEBOOK_05_SOCIAL_FIXED_DIMENSIONAL}"
)

print(
    f"Social component count       : "
    f"{len(handover_social_components)}"
)

print("-" * 72)

print("Global and group paths")

print(
    f"Global path required         : "
    f"{NOTEBOOK_05_GLOBAL_PATH_REQUIRED}"
)

print(
    f"Group path optional          : "
    f"{NOTEBOOK_05_GROUP_PATH_OPTIONAL}"
)

print(
    f"Global replaced by group     : "
    f"{NOTEBOOK_05_GLOBAL_REPLACED_BY_GROUP}"
)

print(
    f"Concrete groups predefined   : "
    f"{NOTEBOOK_05_GROUP_IDENTITIES_PREDEFINED}"
)

print("-" * 72)

print("Transformative contract")

print(
    f"Factual Transformative Wt.   : "
    f"{NOTEBOOK_05_TW_F}"
)

print(
    f"Psychological Transform. Wt. : "
    f"{NOTEBOOK_05_TW_P}"
)

print(
    f"Social Transformative Wt.    : "
    f"{NOTEBOOK_05_TW_S}"
)

print(
    f"Transformative Wts collapsed : "
    f"{NOTEBOOK_05_TRANSFORMATIVE_WEIGHTS_COLLAPSED}"
)

print(
    f"TW = Emotional Weight        : "
    f"{NOTEBOOK_05_TW_EQUALS_EW}"
)

print(
    f"TW = magnitude               : "
    f"{NOTEBOOK_05_TW_EQUALS_MAGNITUDE}"
)

print(
    f"TW = retention gate          : "
    f"{NOTEBOOK_05_TW_EQUALS_RETENTION_GATE}"
)

print(
    f"TEV = architectural change   : "
    f"{NOTEBOOK_05_TEV_EQUALS_ARCHITECTURAL_TRANSFORMATION}"
)

print(
    f"TEV = IEV difference         : "
    f"{NOTEBOOK_05_TEV_EQUALS_IEV_DIFFERENCE}"
)

print("-" * 72)

print("Recurrent contract")

print(
    f"Factual recurrent state      : "
    f"{NOTEBOOK_05_H_F}"
)

print(
    f"Psychological recurrent st.  : "
    f"{NOTEBOOK_05_H_P}"
)

print(
    f"Social recurrent state       : "
    f"{NOTEBOOK_05_H_S}"
)

print(
    f"Recurrent states collapsed   : "
    f"{NOTEBOOK_05_RECURRENT_STATES_COLLAPSED}"
)

print(
    f"Causal processing            : "
    f"{NOTEBOOK_05_CAUSAL_PROCESSING}"
)

print(
    f"Future context allowed       : "
    f"{NOTEBOOK_05_FUTURE_CONTEXT_ALLOWED}"
)

print(
    f"Article-boundary reset       : "
    f"{NOTEBOOK_05_ARTICLE_BOUNDARY_RESET}"
)

print(
    f"Cross-article carry          : "
    f"{NOTEBOOK_05_CROSS_ARTICLE_CARRY}"
)

print("-" * 72)

print("Supervision boundary")

print(
    f"Mask-aware supervision       : "
    f"{NOTEBOOK_05_MASK_AWARE_SUPERVISION}"
)

print(
    f"Missing = zero               : "
    f"{NOTEBOOK_05_MISSING_EQUALS_ZERO}"
)

print(
    f"Missing = negative           : "
    f"{NOTEBOOK_05_MISSING_EQUALS_NEGATIVE}"
)

print(
    f"Unavailable enters loss      : "
    f"{NOTEBOOK_05_UNAVAILABLE_ENTERS_LOSS}"
)

print(
    f"Supervision inventoried      : "
    f"{NOTEBOOK_05_SUPERVISION_INVENTORIED}"
)

print("-" * 72)

print("Training boundary")

print(
    f"Model instantiated           : "
    f"{NOTEBOOK_05_MODEL_INSTANTIATED}"
)

print(
    f"Parameter policy finalised   : "
    f"{NOTEBOOK_05_PARAMETER_POLICY_FINALISED}"
)

print(
    f"Training data constructed    : "
    f"{NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED}"
)

print(
    f"Optimizer created            : "
    f"{NOTEBOOK_05_OPTIMIZER_CREATED}"
)

print(
    f"Forward pass executed        : "
    f"{NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_05_LOSS_CALCULATED}"
)

print(
    f"Training executed            : "
    f"{NOTEBOOK_05_TRAINING_EXECUTED}"
)

print(
    f"Checkpoint selected          : "
    f"{NOTEBOOK_05_CHECKPOINT_SELECTED}"
)

print(
    f"Ablation executed            : "
    f"{NOTEBOOK_05_ABLATION_EXECUTED}"
)

print(
    f"Evaluation executed          : "
    f"{NOTEBOOK_05_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print("-" * 72)

print("Notebook structure")

print(
    f"Target block count           : "
    f"{NOTEBOOK_05_TARGET_BLOCK_COUNT}"
)

print(
    f"Block count hard limit       : "
    f"{NOTEBOOK_05_TARGET_BLOCK_COUNT_IS_HARD_LIMIT}"
)

print("-" * 72)

print("Execution state")

print(
    f"Notebook initialised         : "
    f"{NOTEBOOK_05_INITIALISED}"
)

print(
    f"Handover loaded from Drive   : "
    f"{NOTEBOOK_05_HANDOVER_LOADED_FROM_DRIVE}"
)

print(
    f"Handover validated           : "
    f"{NOTEBOOK_05_HANDOVER_VALIDATED}"
)

print(
    f"Block 1 complete             : "
    f"{NOTEBOOK_05_BLOCK_1_COMPLETE}"
)

print("=" * 72)

print(
    "Notebook 05 initialised successfully."
)

print(
    "Explicit Colab authentication completed successfully."
)

print(
    "The persistent Notebook 04 architectural handover was "
    "loaded successfully from Google Drive."
)

print(
    "The handover contents were validated rather than trusted "
    "solely from file presence."
)

print(
    "The factual, psychological and social representation spaces "
    "remain independently preserved."
)

print(
    "The factual representation remains ten-dimensional and is "
    "not interpreted as external truth verification."
)

print(
    "The Psychological State Vector remains 34-dimensional with "
    "REV, TEV, IEV and EW preserved in the validated order."
)

print(
    "The social representation remains structured and "
    "variable-dimensional."
)

print(
    "The global path remains mandatory and group-conditioned paths "
    "remain optional and additional."
)

print(
    "TW_F, TW_P and TW_S remain separate Transformative Weights."
)

print(
    "Transformative Weight remains distinct from Emotional Weight, "
    "transformation magnitude and recurrent retention."
)

print(
    "TEV remains distinct from architectural psychological "
    "transformation and consecutive IEV differences."
)

print(
    "H_F, H_P and H_S remain separate recurrent states."
)

print(
    "Sequential processing remains causal and future context is "
    "not permitted."
)

print(
    "Recurrent state remains reset at independent article boundaries."
)

print(
    "Missing supervision remains distinct from zero and negative "
    "supervision."
)

print(
    "No model, optimiser, forward pass, loss, training, checkpoint, "
    "ablation or evaluation has been executed."
)

print(
    "Block 2 may proceed to Supervision Inventory and Target Availability."
)

WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.
WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.

========================================================================
Media AI — Notebook 05, Block 1: Initialisation and Architecture Handover Validation
========================================================================
Notebook                     : 05_training_evaluation_and_validation
Notebook version             : 1.0
Block                        : 1
Project random seed          : 42
------------------------------------------------------------------------
Google authentication
Colab authenticated          : True
Drive service initialised    : True
------------------------------------------------------------------------
Persistent Notebook 04 handover
Handover filename            : notebook_04_to_05_handover.json
Drive file ID                : 1ZaLnzTlMwpsHo99vqvDN6z_L-Hc0-TJX
Drive file modified          : 2026-08-22T15:23:04.468Z
Handover located             : True
Handover downloaded          : True
Local audit copy             : True
JSON parsed                  : True
Loaded from Drive            : True
------------------------------------------------------------------------
Notebook 04 handover contract
Handover version             : 1.1
Source notebook              : 04_model_architecture
Target notebook              : 05_training_evaluation_and_validation
Architecture complete        : True
Architecture valid           : True
Handover valid               : True
------------------------------------------------------------------------
Architecture sequence
Stage 1                      : textual_representation
Stage 2                      : confluent_conditioning
Stage 3                      : representation_heads
Stage 4                      : transformative_mechanism
Stage 5                      : recurrent_mechanism
------------------------------------------------------------------------
Representation spaces
Representation spaces        : 3
Factual dimensions           : 10
Psychological dimensions     : 34
Psychological vector order   : REV, TEV, IEV, EW
Social fixed-dimensional     : False
Social component count       : 4
------------------------------------------------------------------------
Global and group paths
Global path required         : True
Group path optional          : True
Global replaced by group     : False
Concrete groups predefined   : False
------------------------------------------------------------------------
Transformative contract
Factual Transformative Wt.   : TW_F
Psychological Transform. Wt. : TW_P
Social Transformative Wt.    : TW_S
Transformative Wts collapsed : False
TW = Emotional Weight        : False
TW = magnitude               : False
TW = retention gate          : False
TEV = architectural change   : False
TEV = IEV difference         : False
------------------------------------------------------------------------
Recurrent contract
Factual recurrent state      : H_F
Psychological recurrent st.  : H_P
Social recurrent state       : H_S
Recurrent states collapsed   : False
Causal processing            : True
Future context allowed       : False
Article-boundary reset       : True
Cross-article carry          : False
------------------------------------------------------------------------
Supervision boundary
Mask-aware supervision       : True
Missing = zero               : False
Missing = negative           : False
Unavailable enters loss      : False
Supervision inventoried      : False
------------------------------------------------------------------------
Training boundary
Model instantiated           : False
Parameter policy finalised   : False
Training data constructed    : False
Optimizer created            : False
Forward pass executed        : False
Loss calculated              : False
Training executed            : False
Checkpoint selected          : False
Ablation executed            : False
Evaluation executed          : False
Empirical validity           : False
------------------------------------------------------------------------
Notebook structure
Target block count           : 10
Block count hard limit       : False
------------------------------------------------------------------------
Execution state
Notebook initialised         : True
Handover loaded from Drive   : True
Handover validated           : True
Block 1 complete             : True
========================================================================
Notebook 05 initialised successfully.
Explicit Colab authentication completed successfully.
The persistent Notebook 04 architectural handover was loaded successfully from Google Drive.
The handover contents were validated rather than trusted solely from file presence.
The factual, psychological and social representation spaces remain independently preserved.
The factual representation remains ten-dimensional and is not interpreted as external truth verification.
The Psychological State Vector remains 34-dimensional with REV, TEV, IEV and EW preserved in the validated order.
The social representation remains structured and variable-dimensional.
The global path remains mandatory and group-conditioned paths remain optional and additional.
TW_F, TW_P and TW_S remain separate Transformative Weights.
Transformative Weight remains distinct from Emotional Weight, transformation magnitude and recurrent retention.
TEV remains distinct from architectural psychological transformation and consecutive IEV differences.
H_F, H_P and H_S remain separate recurrent states.
Sequential processing remains causal and future context is not permitted.
Recurrent state remains reset at independent article boundaries.
Missing supervision remains distinct from zero and negative supervision.
No model, optimiser, forward pass, loss, training, checkpoint, ablation or evaluation has been executed.
Block 2 may proceed to Supervision Inventory and Target Availability.

## Block 2 — Supervision Inventory and Target Availability

### Purpose

This block defines the **supervision inventory and target-availability contract** for Notebook 05.

The Media AI architecture contains several trainable components, but architectural definition alone does not provide valid training targets.

Before any model component is instantiated or optimised, Notebook 05 must determine:

- which targets exist;
- which targets are validated;
- which representation level they refer to;
- which architectural component they supervise;
- which sentences or structures they cover;
- which values are unavailable;
- which masks must therefore remain inactive.

This block does not create supervision.

It does not infer missing labels from the architecture.

It does not activate a training objective merely because a corresponding model output exists.

Its purpose is to establish a transparent inventory of the supervision that is genuinely available for training.

---

### Supervision principle

A trainable output may contribute to optimisation only when admissible supervision is available.

For target family \(k\), define:

$$
A_k \in \{0,1\}
$$

where:

- \(A_k = 1\) means validated supervision is available;
- \(A_k = 0\) means validated supervision is unavailable.

An unavailable target family must not contribute to optimisation:

$$
A_k = 0
\quad\Rightarrow\quad
\mathcal{L}_k \text{ is inactive}
$$

The existence of a model output therefore does not imply the existence of a valid loss.

---

### Supervision states

Notebook 05 distinguishes several supervision states.

A target may be:

- **validated** — admissible for the corresponding training objective;
- **available but unvalidated** — present but not yet admissible for training;
- **partially available** — available for only some observations or dimensions;
- **derived under an explicit rule** — produced from another validated target using a documented transformation;
- **unavailable** — no admissible supervision exists;
- **not applicable** — the target does not apply to a particular observation or structural object.

These states must remain distinct.

In particular:

$$
\text{unavailable}
\neq
0
$$

and:

$$
\text{not applicable}
\neq
\text{negative label}
$$

---

### Representation level

Every supervision record must identify the level at which the target applies.

The supported representation levels are:

- token;
- sentence;
- paragraph;
- article;
- structured social object.

The current trainable architecture operates primarily at sentence level.

Therefore, sentence-level supervision is the reference level for the initial training configuration unless a target is explicitly defined at another level.

A target available at article level must not be silently copied to all sentences.

Likewise, a sentence-level target must not be treated as token-level supervision without an explicit propagation rule.

---

### Supervision provenance

Every supervised value must retain a supervision source.

The supervision inventory must distinguish, where applicable:

- human supervisor;
- expert annotation;
- validated external reference;
- validated structured dataset;
- validated deterministic transformation;
- model-generated candidate awaiting validation;
- unavailable source.

Model-generated values must not be treated as validated targets merely because they are syntactically complete.

If secondary-model or supervisor-model outputs are later used, their role must be explicitly recorded.

---

### Confidence boundary

Confidence is not part of the substantive target vector unless explicitly defined by a later experiment.

For target value \(y\), confidence \(c\) remains metadata:

$$
(y,c)
$$

rather than:

$$
y' = [y,c]
$$

by default.

This preserves the distinction between:

- what the target represents;
- how reliable the target source is believed to be.

---

### Factual-head supervision

The factual head predicts a ten-dimensional factual representation.

Its target structure is:

$$
Y^F_t
=
[
FW_t,\;
F^1_t,\;
F^2_t,\;
\ldots,\;
F^9_t
]
$$

where:

- \(FW_t\) is Factological Weight;
- the remaining nine values correspond to the explicit factual components defined in Notebook 04.

The factual target describes factological structure and epistemic presentation.

It does not directly encode externally verified truth.

Therefore:

$$
Y^F_t
\neq
\text{truth label}
$$

Validated external truth assessment, if later introduced, must remain a separate supervisory or evaluation layer.

---

### Factological Weight supervision

Factological Weight is a bounded continuous target.

Where validated supervision exists:

$$
FW_t \in [0,1]
$$

Its supervision must describe the degree of factological structure or factual loading associated with the textual unit according to the project's defined ontology.

It must not be interpreted as probability that the statement is true.

---

### Factual-component supervision

The nine factual components represent the explicit dimensions defined in the factual ontology.

Each component requires its own availability state.

For factual component \(j\):

$$
M^F_{t,j}
\in
\{0,1\}
$$

where \(M^F_{t,j}=1\) indicates valid supervision for that component at sentence \(t\).

A factual sentence may therefore have supervision for some dimensions while other dimensions remain unavailable.

The factual mask must preserve this partial coverage.

---

### Psychological-head supervision

The psychological target preserves the 34-dimensional Psychological State Vector:

$$
Y^P_t
=
[
REV_t,\;
TEV_t,\;
IEV_t,\;
EW_t
]
$$

with:

$$
\dim(REV_t)=11
$$

$$
\dim(TEV_t)=11
$$

$$
\dim(IEV_t)=11
$$

$$
\dim(EW_t)=1
$$

and:

$$
\dim(Y^P_t)=34
$$

Each psychological target family must be inventoried independently.

Availability of REV does not imply availability of TEV or IEV.

Availability of any emotional vector does not imply availability of EW.

---

### Reported Emotion Vector supervision

REV represents emotion explicitly reported, attributed or described in the text.

For emotional dimension \(e\):

$$
REV_{t,e}
\in
[0,1]
$$

Validated REV supervision must correspond to the emotional content being reported or attributed rather than to the emotional state induced in a reader.

REV therefore remains conceptually distinct from IEV and TEV.

---

### Immediate Emotion Vector supervision

IEV represents the immediate emotional state associated with the textual unit under the project's psychological interpretation contract.

For emotional dimension \(e\):

$$
IEV_{t,e}
\in
[0,1]
$$

IEV supervision must not be inferred automatically from REV.

A sentence may report fear without necessarily inducing the same immediate emotional response.

Therefore:

$$
REV_t
\neq
IEV_t
$$

by definition.

---

### Transformative Emotion Vector supervision

TEV is a signed psychological target.

For emotional dimension \(e\):

$$
TEV_{t,e}
\in
[-1,1]
$$

Positive and negative values preserve transformation direction.

TEV remains distinct from the architectural psychological transformation.

Therefore:

$$
TEV_t
\neq
\Delta^P_t
$$

TEV also remains distinct from direct subtraction between consecutive IEV states:

$$
TEV_t
\neq
IEV_t-IEV_{t-1}
$$

unless a later experiment explicitly tests such a relationship.

---

### Emotional Weight supervision

EW is a bounded scalar:

$$
EW_t
\in
[0,1]
$$

EW represents the overall psychological or emotional strength associated with the Psychological State Vector.

It remains distinct from psychological Transformative Weight:

$$
EW_t
\neq
TW^P_t
$$

Supervision for EW must therefore be inventoried separately from supervision for \(TW^P\).

---

### Social-head supervision

The social head does not have one fixed-dimensional target vector.

Its supervision is structured around:

- actors;
- groups;
- memberships;
- relationships.

Each structural family must be inventoried independently.

Social supervision must preserve object identity and structural correspondence.

---

### Actor supervision

Actor supervision identifies valid textual or discourse actors.

An actor target may include:

- actor identity;
- textual span;
- canonical or aligned identity;
- sentence association;
- availability state.

Actor absence must not be assumed merely because no annotation is present.

Therefore:

$$
\text{unannotated actor}
\neq
\text{confirmed actor absence}
$$

---

### Group supervision

Group supervision identifies article-specific or textually relevant groups.

Concrete group identities are not predefined by the architecture.

A valid group target must therefore arise from admissible supervision or validated detection rather than from a closed list imposed by the model.

Group supervision may include:

- group identity;
- textual evidence;
- group type where applicable;
- alignment information;
- membership relations;
- availability state.

---

### Membership supervision

Membership supervision describes relations between actors and groups.

Overlapping membership remains permitted.

Therefore, membership targets are not required to form a mutually exclusive class structure.

For actor \(a\) and group \(g\), a membership target may be represented as:

$$
M_{a,g}
\in
[0,1]
$$

or by another explicitly defined structured target.

Multiple memberships may be simultaneously valid.

---

### Relationship supervision

Relationship supervision describes relationships among:

- actors;
- groups;
- actors and groups.

Relationships may be:

- directional;
- signed;
- typed;
- unavailable.

Relationship targets require explicit source and target alignment.

A missing relationship annotation must not be interpreted automatically as absence of a relationship.

---

### Transformative-mechanism supervision

The transformative mechanism contains separate factual, psychological and social transformation targets.

Conceptually:

$$
Y^T_t
=
[
Y^{TF}_t,\;
Y^{TP}_t,\;
Y^{TS}_t
]
$$

where:

- \(Y^{TF}_t\) supervises factual transformation;
- \(Y^{TP}_t\) supervises psychological transformation;
- \(Y^{TS}_t\) supervises social transformation.

These targets must remain distinct from the underlying representation-head targets.

---

### Factual transformation supervision

Factual transformation supervision describes change in factual or epistemic representation associated with the current textual step.

It must not be created by simply subtracting consecutive factual targets unless such a derivation is explicitly defined and validated.

Therefore:

$$
Y^{TF}_t
\neq
Y^F_t-Y^F_{t-1}
$$

by default.

A derived difference may later be used as an auxiliary target, but it is not the architectural definition of factual transformation.

---

### Psychological transformation supervision

Psychological architectural transformation supervision is distinct from TEV.

Therefore:

$$
Y^{TP}_t
\neq
TEV_t
$$

by definition.

If later experiments examine their relationship, the two must remain separately observable so that correspondence can be evaluated empirically.

---

### Social transformation supervision

Social transformation supervision remains structured.

It may describe changes such as:

- actor emergence or attenuation;
- group emergence or attenuation;
- membership change;
- relationship change;
- salience change.

Because the social space is variable-dimensional, structured alignment is required before transformation targets can be compared across textual steps.

---

### Transformative Weight supervision

The architecture defines three Transformative Weights:

$$
TW^F_t,\qquad TW^P_t,\qquad TW^S_t
$$

Each requires an independent supervision-availability decision.

The target ranges are:

$$
TW^q_t
\in
[0,1]
$$

for:

$$
q\in\{F,P,S\}
$$

The three weights must not be collapsed into a common supervision target.

---

### Transformative Weight and magnitude

Transformative Weight is a learned salience target rather than a deterministic transformation norm.

Therefore:

$$
TW^q_t
\neq
\|\Delta^q_t\|_2
$$

by definition.

Transformation magnitude may later provide an auxiliary analytical quantity, but it does not automatically supply Transformative Weight supervision.

---

### Recurrent-state supervision

The recurrent mechanism defines:

$$
H^F_t,\qquad H^P_t,\qquad H^S_t
$$

Direct supervision for recurrent hidden states may not necessarily exist.

Notebook 05 must therefore distinguish between:

- directly supervised recurrent targets;
- indirectly trained recurrent states through downstream objectives;
- unavailable recurrent-state supervision.

The existence of a recurrent state does not require a manually labelled target for every state dimension.

---

### Factual recurrent supervision

If validated factual recurrent-state supervision exists, it may activate the factual recurrent objective.

Otherwise:

$$
A_{H^F}=0
$$

and the recurrent factual state may only be trained indirectly where the experimental design provides an admissible downstream learning signal.

The notebook must record which case applies.

---

### Psychological recurrent supervision

The same distinction applies to the psychological recurrent state:

$$
A_{H^P}
\in
\{0,1\}
$$

Psychological sequential persistence must not be fabricated by copying the current Psychological State Vector into the recurrent target.

The current state and persistent recurrent state remain conceptually distinct.

---

### Social recurrent supervision

Social recurrent supervision requires structured temporal alignment of actors, groups, memberships and relationships.

If such supervision is unavailable, the social recurrent state must remain without direct supervised targets.

Indirect optimisation, if used later, must be explicitly documented.

---

### Global-path supervision

The global path remains the reference path.

A supervision record must specify whether it applies to:

- global path;
- group-conditioned path;
- both.

Global supervision must not automatically be reused as group-conditioned supervision.

---

### Group-conditioned supervision

Group-conditioned supervision is usable only when:

- a valid group exists;
- group alignment is available;
- the group-conditioned route is valid;
- the target is explicitly applicable to that route.

For group \(g\), define route availability:

$$
A_{t,g}^{route}
\in
\{0,1\}
$$

A group-conditioned loss may only be activated when:

$$
A_{t,g}^{route}=1
$$

and the corresponding target supervision is also available.

---

### Supervisor layer

External supervision and supervisory-model outputs may be used to assess or annotate parts of the architecture.

However, their role must remain explicit.

A supervisor may provide:

- target annotation;
- target validation;
- disagreement signal;
- confidence metadata;
- evaluation reference.

A supervisor output must not silently become ground truth.

The inventory must record whether a supervisory output is:

- provisional;
- validated;
- accepted for training;
- evaluation-only.

---

### Agreement and disagreement

Where multiple supervisors or annotation sources exist, disagreement must be preserved rather than silently averaged away.

For supervisors \(s_1\) and \(s_2\):

$$
Y^{(s_1)}_t
\neq
Y^{(s_2)}_t
$$

may represent meaningful uncertainty.

Possible later aggregation strategies may include:

- adjudication;
- consensus;
- probabilistic aggregation;
- confidence-weighted aggregation.

Block 2 does not select an aggregation strategy.

---

### Supervision coverage

For target family \(k\), coverage is defined as:

$$
Coverage_k
=
\frac{
N^{available}_k
}{
N^{eligible}_k
}
$$

where:

- \(N^{available}_k\) is the number of eligible observations with validated supervision;
- \(N^{eligible}_k\) is the number of observations for which that target could meaningfully apply.

Coverage must be reported separately for each target family.

A high overall annotation count must not conceal poor coverage of a specific representation component.

---

### Dimensional coverage

For fixed-dimensional targets, coverage should also be measured at dimension level.

For dimension \(j\):

$$
Coverage_{k,j}
=
\frac{
N^{available}_{k,j}
}{
N^{eligible}_{k,j}
}
$$

This is particularly relevant for:

- factual dimensions;
- REV;
- TEV;
- IEV;
- Transformative Weights.

---

### Structured coverage

For social targets, coverage cannot be represented adequately by a single fixed-dimensional mask.

The inventory should therefore report coverage separately for:

- actors;
- groups;
- memberships;
- relationships;
- social transformations;
- social recurrent targets where applicable.

Structured coverage must preserve both object counts and sentence/article coverage.

---

### Target activation

A target family becomes active only after its supervision status is validated.

For target family \(k\):

$$
Active_k
=
Validated_k
\land
Coverage_k > 0
$$

However, positive coverage alone does not establish sufficient coverage for meaningful training.

Minimum coverage requirements, if imposed, must be defined explicitly later.

Block 2 records availability but does not yet decide optimisation adequacy.

---

### Partial supervision

The architecture supports partial supervision.

If only some target families are available, Notebook 05 may train the corresponding components without inventing targets for unavailable components.

Conceptually:

$$
\mathcal{L}_{total}
=
\sum_k
A_k
\lambda_k
\mathcal{L}_k
$$

where:

$$
A_k
\in
\{0,1\}
$$

determines whether target family \(k\) is active.

Unavailable objectives therefore contribute exactly no supervised loss.

---

### No forced full-model supervision

The complete architecture does not need to have direct supervision for every internal state before experimentation can begin.

Different components may be trained through:

- direct supervision;
- indirect end-to-end objectives;
- auxiliary objectives;
- staged training;
- or remain frozen.

However, every such choice must be explicit.

Notebook 05 must not imply direct supervision where only indirect optimisation exists.

---

### Initial supervision inventory

The supervision inventory should contain at minimum the following target families:

- factual head;
- REV;
- TEV;
- IEV;
- EW;
- actors;
- groups;
- memberships;
- relationships;
- factual transformation;
- psychological transformation;
- social transformation;
- TW_F;
- TW_P;
- TW_S;
- H_F;
- H_P;
- H_S.

Each family must record:

- target name;
- architecture component;
- representation space;
- representation level;
- target type;
- target dimensionality or structure;
- target range where applicable;
- supervision source;
- validation status;
- number eligible;
- number available;
- coverage;
- mask requirement;
- training activation status.

---

### Training activation status

At the beginning of Block 2, all target families remain inactive until the inventory is completed.

Therefore:

$$
Active_k = 0
$$

for every target family \(k\) before validated supervision is confirmed.

Block 2 may change an activation status only when the corresponding supervision evidence supports that change.

---

### Relationship to Block 3

Block 3 will define the **Model Instantiation and Parameter-Freezing Policy**.

Its decisions must depend on the supervision inventory produced here.

For example:

- a supervised head may be eligible for direct optimisation;
- an unsupervised component may remain frozen;
- a component may participate only through an explicitly defined indirect objective;
- a group-conditioned adapter may remain inactive if valid group-conditioned supervision is unavailable.

Therefore:

$$
\text{supervision inventory}
\rightarrow
\text{parameter policy}
$$

and not the reverse.

---

### Methodological boundaries

Block 2 does not:

- fabricate training labels;
- convert missing targets into zero;
- convert missing targets into negative evidence;
- assume all architecture components have direct supervision;
- infer factual truth from factual-head targets;
- equate REV with IEV;
- equate TEV with architectural transformation;
- define TEV as IEV subtraction;
- equate EW with TW_P;
- derive TW automatically from transformation magnitude;
- predefine concrete social groups;
- treat unannotated social objects as absent;
- copy article-level labels to sentences without an explicit rule;
- copy global targets to group-conditioned paths automatically;
- treat supervisor-model outputs as ground truth without validation;
- average supervisor disagreement automatically;
- instantiate the model;
- finalise trainable parameters;
- construct training batches;
- create an optimiser;
- execute a forward pass;
- calculate training loss;
- train the model;
- evaluate model performance.

---

### Execution boundary

This block defines and evaluates **supervision availability only**.

At this stage:

- supervision target families are defined;
- target semantics are preserved;
- supervision states are defined;
- provenance requirements are defined;
- confidence remains metadata;
- mask requirements are defined;
- global and group-conditioned supervision are distinguished;
- supervisor outputs are distinguished from validated ground truth;
- coverage methodology is defined;
- partial supervision is permitted;
- target activation rules are defined.

However:

- no target may be activated without observed validated supervision;
- no model component is instantiated;
- no parameter group is activated;
- no training dataset is constructed;
- no optimiser is created;
- no forward pass is executed;
- no training loss is calculated;
- no model training is performed;
- no evaluation is performed.

Block 2 therefore determines **what the architecture can legitimately learn from the supervision currently available** before Notebook 05 proceeds to model instantiation and parameter policy.

**Block 3 — Model Instantiation and Parameter-Freezing Policy** may proceed only after the supervision inventory has been constructed and validated.

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Block 2: Supervision Inventory and Target Availability
# =============================================================================

import json

from copy import deepcopy
from datetime import datetime, timezone

import numpy as np
import pandas as pd


# -----------------------------------------------------------------------------
# Block dependency checks
# -----------------------------------------------------------------------------

required_block_1_objects = [
    "NOTEBOOK_05_BLOCK_1_COMPLETE",
    "NOTEBOOK_05_HANDOVER_VALID",
    "NOTEBOOK_05_HANDOVER",
    "NOTEBOOK_05_MASK_AWARE_SUPERVISION",
    "NOTEBOOK_05_MISSING_EQUALS_ZERO",
    "NOTEBOOK_05_MISSING_EQUALS_NEGATIVE",
    "NOTEBOOK_05_UNAVAILABLE_ENTERS_LOSS",
    "DRIVE_SERVICE_FOR_HANDOVER",
    "NOTEBOOK_05_DRIVE_SERVICE_INITIALISED",
    "download_drive_file_bytes",
]


missing_block_1_objects = [
    object_name
    for object_name
    in required_block_1_objects
    if object_name not in globals()
]


if missing_block_1_objects:

    raise NameError(
        "Notebook 05 Block 1 is not initialised. "
        f"Missing: {missing_block_1_objects}"
    )


if not NOTEBOOK_05_BLOCK_1_COMPLETE:

    raise ValueError(
        "Notebook 05 Block 1 must be complete before "
        "the supervision inventory is constructed."
    )


if not NOTEBOOK_05_HANDOVER_VALID:

    raise ValueError(
        "Notebook 05 requires a valid Notebook 04 handover "
        "before supervision can be inventoried."
    )


if not NOTEBOOK_05_DRIVE_SERVICE_INITIALISED:

    raise ValueError(
        "Notebook 05 Block 1 did not initialise the "
        "Google Drive service successfully."
    )


BLOCK_2_DRIVE_SERVICE = (
    DRIVE_SERVICE_FOR_HANDOVER
)


# -----------------------------------------------------------------------------
# Block configuration
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_2 = 2

NOTEBOOK_05_BLOCK_2_NAME = (
    "Supervision Inventory and Target Availability"
)

SUPERVISION_INVENTORY_VERSION = "1.1"

SUPERVISION_INVENTORY_CREATED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


NOTEBOOK_03_ACCEPTED_ANNOTATIONS_FILENAME = (
    "notebook_03_accepted_annotations.json"
)

NOTEBOOK_03_HANDOVER_FILENAME = (
    "notebook_03_handover_manifest.json"
)


# -----------------------------------------------------------------------------
# Supervision-state vocabulary
# -----------------------------------------------------------------------------

SUPERVISION_STATES = (
    "validated",
    "available_unvalidated",
    "partially_available",
    "derived_validated",
    "unavailable",
    "not_applicable",
)


TRAINING_ADMISSIBLE_SUPERVISION_STATES = (
    "validated",
    "derived_validated",
)


SUPERVISION_SOURCE_TYPES = (
    "human_supervisor",
    "expert_annotation",
    "validated_external_reference",
    "validated_structured_dataset",
    "validated_deterministic_transformation",
    "validated_machine_supervision",
    "model_generated_candidate",
    "supervisor_model",
    "unavailable",
)


REPRESENTATION_LEVELS = (
    "token",
    "sentence",
    "paragraph",
    "article",
    "structured_social_object",
)


# -----------------------------------------------------------------------------
# Supervision methodological policy
# -----------------------------------------------------------------------------

SUPERVISION_MISSING_EQUALS_ZERO = False

SUPERVISION_MISSING_EQUALS_NEGATIVE = False

SUPERVISION_UNAVAILABLE_ENTERS_LOSS = False

SUPERVISION_CONFIDENCE_PART_OF_TARGET = False

SUPERVISION_MODEL_OUTPUT_EQUALS_GROUND_TRUTH = False

SUPERVISION_DISAGREEMENT_AUTO_AVERAGED = False

SUPERVISION_ARTICLE_LABEL_AUTO_PROPAGATED_TO_SENTENCES = False

SUPERVISION_GLOBAL_TARGET_AUTO_COPIED_TO_GROUP = False

SUPERVISION_PARTIAL_TARGETS_ALLOWED = True

SUPERVISION_DIRECT_REQUIRED_FOR_EVERY_INTERNAL_STATE = False


# -----------------------------------------------------------------------------
# Block 2 activation boundary
# -----------------------------------------------------------------------------

BLOCK_2_ACTIVATES_TRAINING_OBJECTIVES = False


# -----------------------------------------------------------------------------
# Target-family definitions
# -----------------------------------------------------------------------------

SUPERVISION_TARGET_DEFINITIONS = [
    {
        "target_name":
            "factual_head",

        "architecture_component":
            "factual_head",

        "representation_space":
            "factual",

        "representation_level":
            "sentence",

        "target_type":
            "continuous_plus_components",

        "dimensionality":
            10,

        "structure":
            "10-dimensional architectural factual representation",

        "range":
            "mixed",

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "REV",

        "architecture_component":
            "psychological_head",

        "representation_space":
            "psychological",

        "representation_level":
            "sentence",

        "target_type":
            "continuous_vector",

        "dimensionality":
            11,

        "structure":
            "Reported Emotion Vector",

        "range":
            "[0,1]",

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "TEV",

        "architecture_component":
            "psychological_head",

        "representation_space":
            "psychological",

        "representation_level":
            "sentence",

        "target_type":
            "signed_continuous_vector",

        "dimensionality":
            11,

        "structure":
            "Transformative Emotion Vector",

        "range":
            "[-1,1]",

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "IEV",

        "architecture_component":
            "psychological_head",

        "representation_space":
            "psychological",

        "representation_level":
            "sentence",

        "target_type":
            "continuous_vector",

        "dimensionality":
            11,

        "structure":
            "Immediate Emotion Vector",

        "range":
            "[0,1]",

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "EW",

        "architecture_component":
            "psychological_head",

        "representation_space":
            "psychological",

        "representation_level":
            "sentence",

        "target_type":
            "continuous_scalar",

        "dimensionality":
            1,

        "structure":
            "Emotional Weight",

        "range":
            "[0,1]",

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "actors",

        "architecture_component":
            "social_head",

        "representation_space":
            "social",

        "representation_level":
            "structured_social_object",

        "target_type":
            "structured",

        "dimensionality":
            None,

        "structure":
            "actors",

        "range":
            None,

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "groups",

        "architecture_component":
            "social_head",

        "representation_space":
            "social",

        "representation_level":
            "structured_social_object",

        "target_type":
            "structured",

        "dimensionality":
            None,

        "structure":
            "groups",

        "range":
            None,

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "memberships",

        "architecture_component":
            "social_head",

        "representation_space":
            "social",

        "representation_level":
            "structured_social_object",

        "target_type":
            "structured",

        "dimensionality":
            None,

        "structure":
            "actor-group memberships",

        "range":
            "[0,1] or structured",

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "relationships",

        "architecture_component":
            "social_head",

        "representation_space":
            "social",

        "representation_level":
            "structured_social_object",

        "target_type":
            "structured",

        "dimensionality":
            None,

        "structure":
            "signed/directional relationships",

        "range":
            "structured",

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "factual_transformation",

        "architecture_component":
            "transformative_mechanism",

        "representation_space":
            "factual",

        "representation_level":
            "sentence",

        "target_type":
            "signed_continuous_vector",

        "dimensionality":
            10,

        "structure":
            "architectural factual transformation",

        "range":
            "signed",

        "mask_required":
            True,

        "direct_supervision_expected":
            False,
    },

    {
        "target_name":
            "psychological_transformation",

        "architecture_component":
            "transformative_mechanism",

        "representation_space":
            "psychological",

        "representation_level":
            "sentence",

        "target_type":
            "signed_continuous_vector",

        "dimensionality":
            34,

        "structure":
            "architectural psychological transformation",

        "range":
            "signed",

        "mask_required":
            True,

        "direct_supervision_expected":
            False,
    },

    {
        "target_name":
            "social_transformation",

        "architecture_component":
            "transformative_mechanism",

        "representation_space":
            "social",

        "representation_level":
            "structured_social_object",

        "target_type":
            "structured",

        "dimensionality":
            None,

        "structure":
            "structured social transformation",

        "range":
            "structured",

        "mask_required":
            True,

        "direct_supervision_expected":
            False,
    },

    {
        "target_name":
            "TW_F",

        "architecture_component":
            "transformative_mechanism",

        "representation_space":
            "factual",

        "representation_level":
            "sentence",

        "target_type":
            "continuous_scalar",

        "dimensionality":
            1,

        "structure":
            "Factual Transformative Weight",

        "range":
            "[0,1]",

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "TW_P",

        "architecture_component":
            "transformative_mechanism",

        "representation_space":
            "psychological",

        "representation_level":
            "sentence",

        "target_type":
            "continuous_scalar",

        "dimensionality":
            1,

        "structure":
            "Psychological Transformative Weight",

        "range":
            "[0,1]",

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "TW_S",

        "architecture_component":
            "transformative_mechanism",

        "representation_space":
            "social",

        "representation_level":
            "sentence",

        "target_type":
            "continuous_scalar",

        "dimensionality":
            1,

        "structure":
            "Social Transformative Weight",

        "range":
            "[0,1]",

        "mask_required":
            True,

        "direct_supervision_expected":
            True,
    },

    {
        "target_name":
            "H_F",

        "architecture_component":
            "recurrent_mechanism",

        "representation_space":
            "factual",

        "representation_level":
            "sentence",

        "target_type":
            "latent_recurrent_state",

        "dimensionality":
            None,

        "structure":
            "factual recurrent state",

        "range":
            "latent",

        "mask_required":
            True,

        "direct_supervision_expected":
            False,
    },

    {
        "target_name":
            "H_P",

        "architecture_component":
            "recurrent_mechanism",

        "representation_space":
            "psychological",

        "representation_level":
            "sentence",

        "target_type":
            "latent_recurrent_state",

        "dimensionality":
            None,

        "structure":
            "psychological recurrent state",

        "range":
            "latent",

        "mask_required":
            True,

        "direct_supervision_expected":
            False,
    },

    {
        "target_name":
            "H_S",

        "architecture_component":
            "recurrent_mechanism",

        "representation_space":
            "social",

        "representation_level":
            "sentence",

        "target_type":
            "latent_recurrent_state",

        "dimensionality":
            None,

        "structure":
            "social recurrent state",

        "range":
            "latent",

        "mask_required":
            True,

        "direct_supervision_expected":
            False,
    },
]


# -----------------------------------------------------------------------------
# Expected target-family order
# -----------------------------------------------------------------------------

EXPECTED_SUPERVISION_TARGETS = (
    "factual_head",
    "REV",
    "TEV",
    "IEV",
    "EW",
    "actors",
    "groups",
    "memberships",
    "relationships",
    "factual_transformation",
    "psychological_transformation",
    "social_transformation",
    "TW_F",
    "TW_P",
    "TW_S",
    "H_F",
    "H_P",
    "H_S",
)


defined_target_order = tuple(
    record[
        "target_name"
    ]

    for record
    in SUPERVISION_TARGET_DEFINITIONS
)


if defined_target_order != EXPECTED_SUPERVISION_TARGETS:

    raise ValueError(
        "Supervision target-family order does not match "
        "the Block 2 contract."
    )


# =============================================================================
# Persistent Notebook 03 supervision loading
# =============================================================================


# -----------------------------------------------------------------------------
# Google Drive JSON discovery
# -----------------------------------------------------------------------------

def find_latest_drive_json_file(
    file_name,
):
    """
    Locate the most recently modified non-trashed Drive file with an exact
    filename.
    """

    escaped_name = (
        file_name.replace(
            "'",
            "\\'",
        )
    )


    response = (
        BLOCK_2_DRIVE_SERVICE.files()
        .list(
            q=(
                f"name = '{escaped_name}' "
                "and trashed = false"
            ),

            spaces=
                "drive",

            fields=(
                "files("
                "id,"
                "name,"
                "modifiedTime,"
                "parents"
                ")"
            ),

            orderBy=
                "modifiedTime desc",

            pageSize=
                10,
        )
        .execute()
    )


    files = response.get(
        "files",
        [],
    )


    if not files:

        return None


    return files[
        0
    ]


# -----------------------------------------------------------------------------
# Google Drive JSON download
# -----------------------------------------------------------------------------

def download_drive_json(
    file_id,
):
    """
    Download and parse one JSON file using the Notebook 05 Drive helper
    created by Block 1.
    """

    raw_content = download_drive_file_bytes(
        BLOCK_2_DRIVE_SERVICE,
        file_id,
    )

    if isinstance(
        raw_content,
        str,
    ):
        raw_text = raw_content

    elif isinstance(
        raw_content,
        bytes,
    ):
        raw_text = raw_content.decode(
            "utf-8"
        )

    elif isinstance(
        raw_content,
        bytearray,
    ):
        raw_text = bytes(
            raw_content
        ).decode(
            "utf-8"
        )

    else:
        raise TypeError(
            "download_drive_file_bytes returned an unsupported "
            f"type: {type(raw_content).__name__}"
        )

    try:
        return json.loads(
            raw_text
        )

    except json.JSONDecodeError as exc:
        raise ValueError(
            "Persisted Notebook 03 JSON artefact could not "
            "be decoded."
        ) from exc


# -----------------------------------------------------------------------------
# Locate Notebook 03 artefacts
# -----------------------------------------------------------------------------

NOTEBOOK_03_ACCEPTED_FILE = (
    find_latest_drive_json_file(
        NOTEBOOK_03_ACCEPTED_ANNOTATIONS_FILENAME
    )
)


NOTEBOOK_03_HANDOVER_FILE = (
    find_latest_drive_json_file(
        NOTEBOOK_03_HANDOVER_FILENAME
    )
)


NOTEBOOK_03_ACCEPTED_FILE_LOCATED = (
    NOTEBOOK_03_ACCEPTED_FILE
    is not None
)


NOTEBOOK_03_HANDOVER_FILE_LOCATED = (
    NOTEBOOK_03_HANDOVER_FILE
    is not None
)


if not NOTEBOOK_03_ACCEPTED_FILE_LOCATED:

    raise FileNotFoundError(
        "Persisted Notebook 03 accepted supervision artefact "
        "was not found in Google Drive."
    )


if not NOTEBOOK_03_HANDOVER_FILE_LOCATED:

    raise FileNotFoundError(
        "Persisted Notebook 03 handover manifest was not found "
        "in Google Drive."
    )


# -----------------------------------------------------------------------------
# Download Notebook 03 artefacts
# -----------------------------------------------------------------------------

NOTEBOOK_03_ACCEPTED_PAYLOAD = (
    download_drive_json(
        NOTEBOOK_03_ACCEPTED_FILE[
            "id"
        ]
    )
)


NOTEBOOK_03_SUPERVISION_HANDOVER = (
    download_drive_json(
        NOTEBOOK_03_HANDOVER_FILE[
            "id"
        ]
    )
)


# -----------------------------------------------------------------------------
# Extract accepted canonical supervision records
# -----------------------------------------------------------------------------

NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS = (
    NOTEBOOK_03_ACCEPTED_PAYLOAD.get(
        "records",
        [],
    )
)


if not isinstance(
    NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS,
    list,
):

    raise TypeError(
        "Persisted Notebook 03 accepted supervision records "
        "must be a list."
    )


NOTEBOOK_03_ACCEPTED_RECORD_COUNT = len(
    NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS
)


# -----------------------------------------------------------------------------
# Validate Notebook 03 handover semantics
# -----------------------------------------------------------------------------

NOTEBOOK_03_HANDOVER_MACHINE_SUPERVISION_AVAILABLE = (
    NOTEBOOK_03_SUPERVISION_HANDOVER.get(
        "availability",
        {},
    ).get(
        "machine_supervision"
    )
    is True
)


NOTEBOOK_03_HANDOVER_REFERENCE_DATASET_AVAILABLE = (
    NOTEBOOK_03_SUPERVISION_HANDOVER.get(
        "availability",
        {},
    ).get(
        "reference_dataset"
    )
    is True
)


NOTEBOOK_03_HANDOVER_ACCEPTED_COUNT = (
    NOTEBOOK_03_SUPERVISION_HANDOVER.get(
        "counts",
        {},
    ).get(
        "accepted_machine_supervision_records"
    )
)


NOTEBOOK_03_HANDOVER_COUNT_MATCHES = (
    NOTEBOOK_03_HANDOVER_ACCEPTED_COUNT
    == NOTEBOOK_03_ACCEPTED_RECORD_COUNT
)


NOTEBOOK_03_SUPERVISION_PERSISTENCE_VALID = all([
    NOTEBOOK_03_ACCEPTED_RECORD_COUNT
    > 0,

    NOTEBOOK_03_HANDOVER_MACHINE_SUPERVISION_AVAILABLE,

    NOTEBOOK_03_HANDOVER_COUNT_MATCHES,
])


if not NOTEBOOK_03_SUPERVISION_PERSISTENCE_VALID:

    raise ValueError(
        "Persisted Notebook 03 machine supervision failed "
        "Notebook 05 Block 2 validation."
    )


# =============================================================================
# Persistent supervision structural inspection
# =============================================================================


# -----------------------------------------------------------------------------
# Canonical supervision field mapping
# -----------------------------------------------------------------------------

NOTEBOOK_03_TO_NOTEBOOK_05_TARGET_MAP = {
    "REV":
        "reported_emotion",

    "TEV":
        "transformative_emotion",

    "IEV":
        "immediate_emotional_state",

    "EW":
        "emotional_weight",
}


# -----------------------------------------------------------------------------
# Validate persisted sentence identities
# -----------------------------------------------------------------------------

NOTEBOOK_03_ACCEPTED_SENTENCE_IDS = [
    record.get(
        "identity",
        {},
    ).get(
        "sentence_id"
    )

    for record
    in NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS
]


NOTEBOOK_03_SENTENCE_IDS_PRESENT = (
    bool(
        NOTEBOOK_03_ACCEPTED_SENTENCE_IDS
    )
    and all(
        NOTEBOOK_03_ACCEPTED_SENTENCE_IDS
    )
)


NOTEBOOK_03_SENTENCE_IDS_UNIQUE = (
    NOTEBOOK_03_SENTENCE_IDS_PRESENT
    and len(
        NOTEBOOK_03_ACCEPTED_SENTENCE_IDS
    )
    == len(
        set(
            NOTEBOOK_03_ACCEPTED_SENTENCE_IDS
        )
    )
)


if not NOTEBOOK_03_SENTENCE_IDS_PRESENT:

    raise ValueError(
        "Persisted Notebook 03 supervision contains missing "
        "sentence identifiers."
    )


if not NOTEBOOK_03_SENTENCE_IDS_UNIQUE:

    raise ValueError(
        "Persisted Notebook 03 supervision contains duplicate "
        "sentence identifiers."
    )


# -----------------------------------------------------------------------------
# Annotation-value availability helpers
# -----------------------------------------------------------------------------

def annotation_value_is_observed(
    annotation_value,
):
    """
    Return True only for a canonical observed annotation value.

    Missing or insufficient evidence remains distinct from numerical zero.
    """

    if not isinstance(
        annotation_value,
        dict,
    ):

        return False


    return all([
        annotation_value.get(
            "value_state"
        )
        == "observed",

        annotation_value.get(
            "value"
        )
        is not None,
    ])


def vector_annotation_availability(
    vector,
):
    """
    Return component-level availability statistics for one canonical vector.
    """

    if not isinstance(
        vector,
        dict,
    ):

        return {
            "eligible_elements":
                0,

            "available_elements":
                0,

            "any_available":
                False,

            "fully_available":
                False,
        }


    eligible_elements = len(
        vector
    )


    available_elements = sum(
        annotation_value_is_observed(
            value
        )

        for value
        in vector.values()
    )


    return {
        "eligible_elements":
            eligible_elements,

        "available_elements":
            int(
                available_elements
            ),

        "any_available":
            available_elements
            > 0,

        "fully_available":
            (
                eligible_elements
                > 0
                and available_elements
                == eligible_elements
            ),
    }


def scalar_annotation_availability(
    scalar,
):
    """
    Return component-level availability statistics for one canonical scalar.
    """

    available = (
        annotation_value_is_observed(
            scalar
        )
    )


    return {
        "eligible_elements":
            1,

        "available_elements":
            int(
                available
            ),

        "any_available":
            bool(
                available
            ),

        "fully_available":
            bool(
                available
            ),
    }


# -----------------------------------------------------------------------------
# Inspect psychological supervision coverage
# -----------------------------------------------------------------------------

NOTEBOOK_03_PSYCHOLOGICAL_AVAILABILITY = {}


for (
    target_name,
    annotation_field,
) in NOTEBOOK_03_TO_NOTEBOOK_05_TARGET_MAP.items():

    target_definition = next(
        definition

        for definition
        in SUPERVISION_TARGET_DEFINITIONS

        if definition[
            "target_name"
        ]
        == target_name
    )


    dimensionality = (
        target_definition[
            "dimensionality"
        ]
    )


    sentence_records_with_any_supervision = 0

    sentence_records_fully_supervised = 0

    total_eligible_elements = 0

    total_available_elements = 0


    for record in (
        NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS
    ):

        annotations = record.get(
            "annotations",
            {},
        )


        annotation_value = (
            annotations.get(
                annotation_field
            )
        )


        if dimensionality == 1:

            availability = (
                scalar_annotation_availability(
                    annotation_value
                )
            )


        else:

            availability = (
                vector_annotation_availability(
                    annotation_value
                )
            )


        if availability[
            "any_available"
        ]:

            sentence_records_with_any_supervision += 1


        if availability[
            "fully_available"
        ]:

            sentence_records_fully_supervised += 1


        total_eligible_elements += (
            availability[
                "eligible_elements"
            ]
        )


        total_available_elements += (
            availability[
                "available_elements"
            ]
        )


    element_coverage = (
        total_available_elements
        / total_eligible_elements

        if total_eligible_elements
        > 0

        else 0.0
    )


    NOTEBOOK_03_PSYCHOLOGICAL_AVAILABILITY[
        target_name
    ] = {
        "number_eligible":
            NOTEBOOK_03_ACCEPTED_RECORD_COUNT,

        "number_available":
            sentence_records_with_any_supervision,

        "fully_available_sentences":
            sentence_records_fully_supervised,

        "number_elements_eligible":
            total_eligible_elements,

        "number_elements_available":
            total_available_elements,

        "element_coverage":
            float(
                element_coverage
            ),
    }


# -----------------------------------------------------------------------------
# Inspect factual Notebook 03 supervision without mapping it automatically
# -----------------------------------------------------------------------------

NOTEBOOK_03_FACTOLOGICAL_COMPONENT_COUNTS = []


for record in (
    NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS
):

    factological_components = (
        record.get(
            "annotations",
            {},
        ).get(
            "factological_components",
            {},
        )
    )


    if isinstance(
        factological_components,
        dict,
    ):

        NOTEBOOK_03_FACTOLOGICAL_COMPONENT_COUNTS.append(
            len(
                factological_components
            )
        )


NOTEBOOK_03_FACTOLOGICAL_COMPONENT_COUNT = (
    NOTEBOOK_03_FACTOLOGICAL_COMPONENT_COUNTS[
        0
    ]

    if NOTEBOOK_03_FACTOLOGICAL_COMPONENT_COUNTS

    else 0
)


NOTEBOOK_03_FACTOLOGICAL_COMPONENT_COUNT_CONSISTENT = (
    len(
        set(
            NOTEBOOK_03_FACTOLOGICAL_COMPONENT_COUNTS
        )
    )
    <= 1
)


# =============================================================================
# Initial observed supervision registry
# =============================================================================


SUPERVISION_OBSERVATIONS = {
    target_name: {
        "supervision_state":
            "unavailable",

        "supervision_source":
            "unavailable",

        "source_reference":
            None,

        "validation_status":
            "not_validated",

        "number_eligible":
            0,

        "number_available":
            0,

        "coverage":
            0.0,

        "number_elements_eligible":
            0,

        "number_elements_available":
            0,

        "element_coverage":
            0.0,

        "direct_supervision_available":
            False,

        "training_eligible":
            False,

        "indirect_training_signal_available":
            False,

        "training_active":
            False,

        "notes":
            "No validated supervision registered in Block 2.",
    }

    for target_name
    in EXPECTED_SUPERVISION_TARGETS
}


# -----------------------------------------------------------------------------
# Supervision registration helper
# -----------------------------------------------------------------------------

def register_supervision(
    target_name,
    supervision_state,
    supervision_source,
    number_eligible,
    number_available,
    source_reference=None,
    validation_status="not_validated",
    direct_supervision_available=False,
    training_eligible=False,
    indirect_training_signal_available=False,
    number_elements_eligible=0,
    number_elements_available=0,
    notes=None,
):
    """
    Register observed supervision for one target family.

    Registration does not activate optimisation.
    """

    if target_name not in SUPERVISION_OBSERVATIONS:

        raise KeyError(
            f"Unknown supervision target: {target_name}"
        )


    if supervision_state not in SUPERVISION_STATES:

        raise ValueError(
            "Invalid supervision state: "
            f"{supervision_state}"
        )


    if supervision_source not in SUPERVISION_SOURCE_TYPES:

        raise ValueError(
            "Invalid supervision source type: "
            f"{supervision_source}"
        )


    number_eligible = int(
        number_eligible
    )


    number_available = int(
        number_available
    )


    number_elements_eligible = int(
        number_elements_eligible
    )


    number_elements_available = int(
        number_elements_available
    )


    if number_eligible < 0:

        raise ValueError(
            "number_eligible cannot be negative."
        )


    if number_available < 0:

        raise ValueError(
            "number_available cannot be negative."
        )


    if number_available > number_eligible:

        raise ValueError(
            "number_available cannot exceed number_eligible."
        )


    if number_elements_eligible < 0:

        raise ValueError(
            "number_elements_eligible cannot be negative."
        )


    if number_elements_available < 0:

        raise ValueError(
            "number_elements_available cannot be negative."
        )


    if (
        number_elements_available
        > number_elements_eligible
    ):

        raise ValueError(
            "number_elements_available cannot exceed "
            "number_elements_eligible."
        )


    coverage = (
        float(
            number_available
            / number_eligible
        )

        if number_eligible > 0

        else 0.0
    )


    element_coverage = (
        float(
            number_elements_available
            / number_elements_eligible
        )

        if number_elements_eligible > 0

        else 0.0
    )


    SUPERVISION_OBSERVATIONS[
        target_name
    ] = {
        "supervision_state":
            supervision_state,

        "supervision_source":
            supervision_source,

        "source_reference":
            source_reference,

        "validation_status":
            validation_status,

        "number_eligible":
            number_eligible,

        "number_available":
            number_available,

        "coverage":
            coverage,

        "number_elements_eligible":
            number_elements_eligible,

        "number_elements_available":
            number_elements_available,

        "element_coverage":
            element_coverage,

        "direct_supervision_available":
            bool(
                direct_supervision_available
            ),

        "training_eligible":
            bool(
                training_eligible
            ),

        "indirect_training_signal_available":
            bool(
                indirect_training_signal_available
            ),

        "training_active":
            False,

        "notes":
            notes,
    }


# =============================================================================
# Register persisted validated Notebook 03 psychological supervision
# =============================================================================


for target_name in (
    "REV",
    "TEV",
    "IEV",
    "EW",
):

    availability = (
        NOTEBOOK_03_PSYCHOLOGICAL_AVAILABILITY[
            target_name
        ]
    )


    has_validated_supervision = (
        availability[
            "number_elements_available"
        ]
        > 0
    )


    supervision_state = (
        "validated"

        if has_validated_supervision

        else "unavailable"
    )


    register_supervision(
        target_name=
            target_name,

        supervision_state=
            supervision_state,

        supervision_source=(
            "validated_machine_supervision"

            if has_validated_supervision

            else "unavailable"
        ),

        source_reference=(
            NOTEBOOK_03_ACCEPTED_FILE[
                "id"
            ]

            if has_validated_supervision

            else None
        ),

        validation_status=(
            "validated"

            if has_validated_supervision

            else "not_validated"
        ),

        number_eligible=
            availability[
                "number_eligible"
            ],

        number_available=
            availability[
                "number_available"
            ],

        number_elements_eligible=
            availability[
                "number_elements_eligible"
            ],

        number_elements_available=
            availability[
                "number_elements_available"
            ],

        direct_supervision_available=
            has_validated_supervision,

        training_eligible=
            has_validated_supervision,

        indirect_training_signal_available=
            False,

        notes=(
            "Persisted canonical Notebook 03 machine supervision. "
            "Provider output was accepted only after canonical validation. "
            "Machine supervision remains distinct from human-reviewed or "
            "adjudicated reference data."
        ),
    )


# -----------------------------------------------------------------------------
# Preserve factual-supervision boundary
# -----------------------------------------------------------------------------

SUPERVISION_OBSERVATIONS[
    "factual_head"
][
    "notes"
] = (
    "Notebook 03 contains validated factological_weight and "
    "factological_components fields, but these are not automatically "
    "equated with the Notebook 04 ten-dimensional factual representation. "
    "An explicit validated mapping is required before factual_head "
    "supervision can be activated."
)


# -----------------------------------------------------------------------------
# Preserve social-supervision boundary
# -----------------------------------------------------------------------------

for target_name in (
    "actors",
    "groups",
    "memberships",
    "relationships",
):

    SUPERVISION_OBSERVATIONS[
        target_name
    ][
        "notes"
    ] = (
        "No validated structured social supervision was supplied by "
        "the persisted Notebook 03 canonical supervision artefact."
    )


# -----------------------------------------------------------------------------
# Direct versus indirect trainability policy
# -----------------------------------------------------------------------------

INDIRECT_TRAINING_ELIGIBLE_TARGETS = (
    "factual_transformation",
    "psychological_transformation",
    "social_transformation",
    "H_F",
    "H_P",
    "H_S",
)


for target_name in (
    INDIRECT_TRAINING_ELIGIBLE_TARGETS
):

    SUPERVISION_OBSERVATIONS[
        target_name
    ][
        "notes"
    ] = (
        "Direct supervision is not assumed. "
        "This component may later become indirectly trainable "
        "only through an explicitly justified downstream objective."
    )


# -----------------------------------------------------------------------------
# Transformative Weight boundary
# -----------------------------------------------------------------------------

for target_name in (
    "TW_F",
    "TW_P",
    "TW_S",
):

    SUPERVISION_OBSERVATIONS[
        target_name
    ][
        "notes"
    ] = (
        "No independent validated Transformative Weight supervision "
        "is currently available. Transformative Weight is not inferred "
        "from EW, TEV magnitude, architectural transformation magnitude "
        "or recurrent retention."
    )


# -----------------------------------------------------------------------------
# TEV / architectural transformation boundary
# -----------------------------------------------------------------------------

SUPERVISION_OBSERVATIONS[
    "psychological_transformation"
][
    "notes"
] = (
    "TEV supervision is available, but TEV is a psychological "
    "supervision family and is not automatically treated as direct "
    "supervision of the architectural psychological transformation."
)


# =============================================================================
# Training eligibility and activation
# =============================================================================


# -----------------------------------------------------------------------------
# Training-eligibility rule
# -----------------------------------------------------------------------------

def determine_training_eligibility(
    supervision_record,
):
    """
    Determine whether a target has validated direct supervision that may
    later be activated by the parameter/objective policy.
    """

    supervision_admissible = (
        supervision_record[
            "supervision_state"
        ]
        in TRAINING_ADMISSIBLE_SUPERVISION_STATES
    )


    validated = (
        supervision_record[
            "validation_status"
        ]
        == "validated"
    )


    direct_available = bool(
        supervision_record[
            "direct_supervision_available"
        ]
    )


    element_coverage = float(
        supervision_record[
            "element_coverage"
        ]
    )


    return bool(
        supervision_admissible
        and validated
        and direct_available
        and element_coverage > 0.0
    )


# -----------------------------------------------------------------------------
# Apply eligibility without activating optimisation
# -----------------------------------------------------------------------------

for target_name in EXPECTED_SUPERVISION_TARGETS:

    target_record = (
        SUPERVISION_OBSERVATIONS[
            target_name
        ]
    )


    target_record[
        "training_eligible"
    ] = determine_training_eligibility(
        target_record
    )


    target_record[
        "training_active"
    ] = False


# =============================================================================
# Construct full supervision inventory
# =============================================================================


SUPERVISION_INVENTORY = []


for definition in (
    SUPERVISION_TARGET_DEFINITIONS
):

    target_name = definition[
        "target_name"
    ]


    observation = (
        SUPERVISION_OBSERVATIONS[
            target_name
        ]
    )


    inventory_record = deepcopy(
        definition
    )


    inventory_record.update(
        observation
    )


    SUPERVISION_INVENTORY.append(
        inventory_record
    )


# -----------------------------------------------------------------------------
# Supervision inventory DataFrame
# -----------------------------------------------------------------------------

SUPERVISION_INVENTORY_DF = pd.DataFrame(
    SUPERVISION_INVENTORY
)


# -----------------------------------------------------------------------------
# Coverage validation
# -----------------------------------------------------------------------------

for record in SUPERVISION_INVENTORY:

    eligible = int(
        record[
            "number_eligible"
        ]
    )


    available = int(
        record[
            "number_available"
        ]
    )


    coverage = float(
        record[
            "coverage"
        ]
    )


    elements_eligible = int(
        record[
            "number_elements_eligible"
        ]
    )


    elements_available = int(
        record[
            "number_elements_available"
        ]
    )


    element_coverage = float(
        record[
            "element_coverage"
        ]
    )


    if available > eligible:

        raise ValueError(
            f"Invalid sentence coverage counts for "
            f"{record['target_name']}."
        )


    if elements_available > elements_eligible:

        raise ValueError(
            f"Invalid element coverage counts for "
            f"{record['target_name']}."
        )


    expected_coverage = (
        available / eligible

        if eligible > 0

        else 0.0
    )


    expected_element_coverage = (
        elements_available / elements_eligible

        if elements_eligible > 0

        else 0.0
    )


    if not np.isclose(
        coverage,
        expected_coverage,
    ):

        raise ValueError(
            f"Sentence coverage mismatch for "
            f"{record['target_name']}."
        )


    if not np.isclose(
        element_coverage,
        expected_element_coverage,
    ):

        raise ValueError(
            f"Element coverage mismatch for "
            f"{record['target_name']}."
        )


# -----------------------------------------------------------------------------
# Target-level summaries
# -----------------------------------------------------------------------------

SUPERVISION_TARGET_COUNT = len(
    SUPERVISION_INVENTORY
)


VALIDATED_SUPERVISION_TARGETS = tuple(
    record[
        "target_name"
    ]

    for record
    in SUPERVISION_INVENTORY

    if (
        record[
            "supervision_state"
        ]
        in TRAINING_ADMISSIBLE_SUPERVISION_STATES
        and record[
            "validation_status"
        ]
        == "validated"
    )
)


ELIGIBLE_DIRECT_TRAINING_TARGETS = tuple(
    record[
        "target_name"
    ]

    for record
    in SUPERVISION_INVENTORY

    if record[
        "training_eligible"
    ]
)


ACTIVE_DIRECT_TRAINING_TARGETS = tuple(
    record[
        "target_name"
    ]

    for record
    in SUPERVISION_INVENTORY

    if record[
        "training_active"
    ]
)


INDIRECT_TRAINING_SIGNAL_TARGETS = tuple(
    record[
        "target_name"
    ]

    for record
    in SUPERVISION_INVENTORY

    if record[
        "indirect_training_signal_available"
    ]
)


UNAVAILABLE_SUPERVISION_TARGETS = tuple(
    record[
        "target_name"
    ]

    for record
    in SUPERVISION_INVENTORY

    if record[
        "supervision_state"
    ]
    == "unavailable"
)


PARTIALLY_AVAILABLE_SUPERVISION_TARGETS = tuple(
    record[
        "target_name"
    ]

    for record
    in SUPERVISION_INVENTORY

    if (
        record[
            "number_elements_available"
        ]
        > 0
        and record[
            "element_coverage"
        ]
        < 1.0
    )
)


# -----------------------------------------------------------------------------
# Space-level supervision summary
# -----------------------------------------------------------------------------

SUPERVISION_SPACE_SUMMARY = {}


for representation_space in (
    "factual",
    "psychological",
    "social",
):

    space_records = [
        record

        for record
        in SUPERVISION_INVENTORY

        if record[
            "representation_space"
        ]
        == representation_space
    ]


    validated_count = sum(
        (
            record[
                "supervision_state"
            ]
            in TRAINING_ADMISSIBLE_SUPERVISION_STATES
            and record[
                "validation_status"
            ]
            == "validated"
        )

        for record
        in space_records
    )


    eligible_target_count = sum(
        bool(
            record[
                "training_eligible"
            ]
        )

        for record
        in space_records
    )


    active_count = sum(
        bool(
            record[
                "training_active"
            ]
        )

        for record
        in space_records
    )


    available_observations = sum(
        int(
            record[
                "number_available"
            ]
        )

        for record
        in space_records
    )


    eligible_observations = sum(
        int(
            record[
                "number_eligible"
            ]
        )

        for record
        in space_records
    )


    available_elements = sum(
        int(
            record[
                "number_elements_available"
            ]
        )

        for record
        in space_records
    )


    eligible_elements = sum(
        int(
            record[
                "number_elements_eligible"
            ]
        )

        for record
        in space_records
    )


    aggregate_coverage = (
        available_observations
        / eligible_observations

        if eligible_observations > 0

        else 0.0
    )


    aggregate_element_coverage = (
        available_elements
        / eligible_elements

        if eligible_elements > 0

        else 0.0
    )


    SUPERVISION_SPACE_SUMMARY[
        representation_space
    ] = {
        "target_families":
            len(
                space_records
            ),

        "validated_target_families":
            int(
                validated_count
            ),

        "eligible_direct_targets":
            int(
                eligible_target_count
            ),

        "active_direct_targets":
            int(
                active_count
            ),

        "eligible_observations":
            int(
                eligible_observations
            ),

        "available_observations":
            int(
                available_observations
            ),

        "aggregate_coverage":
            float(
                aggregate_coverage
            ),

        "eligible_elements":
            int(
                eligible_elements
            ),

        "available_elements":
            int(
                available_elements
            ),

        "aggregate_element_coverage":
            float(
                aggregate_element_coverage
            ),
    }


# -----------------------------------------------------------------------------
# Architecture-component supervision summary
# -----------------------------------------------------------------------------

SUPERVISION_COMPONENT_SUMMARY = {}


for component_name in (
    "factual_head",
    "psychological_head",
    "social_head",
    "transformative_mechanism",
    "recurrent_mechanism",
):

    component_records = [
        record

        for record
        in SUPERVISION_INVENTORY

        if record[
            "architecture_component"
        ]
        == component_name
    ]


    SUPERVISION_COMPONENT_SUMMARY[
        component_name
    ] = {
        "target_families":
            len(
                component_records
            ),

        "direct_validated_targets":
            tuple(
                record[
                    "target_name"
                ]

                for record
                in component_records

                if (
                    record[
                        "validation_status"
                    ]
                    == "validated"
                    and record[
                        "direct_supervision_available"
                    ]
                )
            ),

        "direct_eligible_targets":
            tuple(
                record[
                    "target_name"
                ]

                for record
                in component_records

                if record[
                    "training_eligible"
                ]
            ),

        "direct_active":
            any(
                bool(
                    record[
                        "training_active"
                    ]
                )

                for record
                in component_records
            ),

        "indirect_signal_available":
            any(
                bool(
                    record[
                        "indirect_training_signal_available"
                    ]
                )

                for record
                in component_records
            ),
    }


# -----------------------------------------------------------------------------
# Supervision readiness
# -----------------------------------------------------------------------------

SUPERVISION_INVENTORY_CONSTRUCTED = True

SUPERVISION_INVENTORY_VALIDATED = True


SUPERVISION_ANY_VALIDATED_TARGET = bool(
    VALIDATED_SUPERVISION_TARGETS
)


SUPERVISION_ANY_DIRECT_TARGET_ELIGIBLE = bool(
    ELIGIBLE_DIRECT_TRAINING_TARGETS
)


SUPERVISION_ANY_DIRECT_TARGET_ACTIVE = bool(
    ACTIVE_DIRECT_TRAINING_TARGETS
)


SUPERVISION_ANY_INDIRECT_SIGNAL_AVAILABLE = bool(
    INDIRECT_TRAINING_SIGNAL_TARGETS
)


# -----------------------------------------------------------------------------
# Current Block 2 training boundary
# -----------------------------------------------------------------------------

NOTEBOOK_05_SUPERVISION_INVENTORIED = True

NOTEBOOK_05_TARGETS_ELIGIBLE = bool(
    ELIGIBLE_DIRECT_TRAINING_TARGETS
)

NOTEBOOK_05_TARGETS_ACTIVATED = False

NOTEBOOK_05_MODEL_INSTANTIATED = False

NOTEBOOK_05_PARAMETER_POLICY_FINALISED = False

NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED = False

NOTEBOOK_05_OPTIMIZER_CREATED = False

NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED = False

NOTEBOOK_05_LOSS_CALCULATED = False

NOTEBOOK_05_TRAINING_EXECUTED = False

NOTEBOOK_05_CHECKPOINT_SELECTED = False

NOTEBOOK_05_ABLATION_EXECUTED = False

NOTEBOOK_05_EVALUATION_EXECUTED = False

NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Block 2 methodological validation
# =============================================================================

NOTEBOOK_05_BLOCK_2_ERRORS = []


# -----------------------------------------------------------------------------
# Core supervision boundary
# -----------------------------------------------------------------------------

if not NOTEBOOK_05_MASK_AWARE_SUPERVISION:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "mask_aware_supervision_not_preserved"
    )


if NOTEBOOK_05_MISSING_EQUALS_ZERO:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "missing_supervision_incorrectly_equals_zero"
    )


if NOTEBOOK_05_MISSING_EQUALS_NEGATIVE:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "missing_supervision_incorrectly_equals_negative"
    )


if NOTEBOOK_05_UNAVAILABLE_ENTERS_LOSS:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "unavailable_supervision_incorrectly_enters_loss"
    )


if SUPERVISION_MISSING_EQUALS_ZERO:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "block_2_missing_incorrectly_equals_zero"
    )


if SUPERVISION_MISSING_EQUALS_NEGATIVE:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "block_2_missing_incorrectly_equals_negative"
    )


if SUPERVISION_UNAVAILABLE_ENTERS_LOSS:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "block_2_unavailable_incorrectly_enters_loss"
    )


if SUPERVISION_CONFIDENCE_PART_OF_TARGET:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "confidence_incorrectly_part_of_target"
    )


if SUPERVISION_MODEL_OUTPUT_EQUALS_GROUND_TRUTH:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "model_output_incorrectly_equals_ground_truth"
    )


if SUPERVISION_DISAGREEMENT_AUTO_AVERAGED:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "supervisor_disagreement_incorrectly_auto_averaged"
    )


if SUPERVISION_GLOBAL_TARGET_AUTO_COPIED_TO_GROUP:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "global_supervision_incorrectly_copied_to_group"
    )


# -----------------------------------------------------------------------------
# Target inventory validation
# -----------------------------------------------------------------------------

if (
    SUPERVISION_TARGET_COUNT
    != len(
        EXPECTED_SUPERVISION_TARGETS
    )
):

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "supervision_target_count_incorrect"
    )


# -----------------------------------------------------------------------------
# Persisted Notebook 03 validation
# -----------------------------------------------------------------------------

if not NOTEBOOK_03_SUPERVISION_PERSISTENCE_VALID:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "notebook_03_persisted_supervision_invalid"
    )


if not NOTEBOOK_03_SENTENCE_IDS_PRESENT:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "notebook_03_sentence_ids_missing"
    )


if not NOTEBOOK_03_SENTENCE_IDS_UNIQUE:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "notebook_03_sentence_ids_not_unique"
    )


if not (
    NOTEBOOK_03_FACTOLOGICAL_COMPONENT_COUNT_CONSISTENT
):

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "notebook_03_factological_component_count_inconsistent"
    )


# -----------------------------------------------------------------------------
# Expected psychological supervision validation
# -----------------------------------------------------------------------------

for target_name in (
    "REV",
    "TEV",
    "IEV",
    "EW",
):

    target_record = (
        SUPERVISION_OBSERVATIONS[
            target_name
        ]
    )


    if (
        target_record[
            "validation_status"
        ]
        != "validated"
    ):

        NOTEBOOK_05_BLOCK_2_ERRORS.append(
            "expected_psychological_supervision_not_validated:"
            f"{target_name}"
        )


    if not target_record[
        "direct_supervision_available"
    ]:

        NOTEBOOK_05_BLOCK_2_ERRORS.append(
            "expected_psychological_supervision_unavailable:"
            f"{target_name}"
        )


    if not target_record[
        "training_eligible"
    ]:

        NOTEBOOK_05_BLOCK_2_ERRORS.append(
            "expected_psychological_target_not_eligible:"
            f"{target_name}"
        )


# -----------------------------------------------------------------------------
# Training must not activate in Block 2
# -----------------------------------------------------------------------------

for record in SUPERVISION_INVENTORY:

    if record[
        "training_active"
    ]:

        NOTEBOOK_05_BLOCK_2_ERRORS.append(
            "training_incorrectly_activated_in_block_2:"
            f"{record['target_name']}"
        )


if NOTEBOOK_05_TARGETS_ACTIVATED:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "target_optimisation_incorrectly_activated_in_block_2"
    )


# -----------------------------------------------------------------------------
# Architectural distinction validation
# -----------------------------------------------------------------------------

if SUPERVISION_OBSERVATIONS[
    "psychological_transformation"
][
    "direct_supervision_available"
]:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "TEV_incorrectly_used_as_architectural_transformation_supervision"
    )


for target_name in (
    "TW_F",
    "TW_P",
    "TW_S",
):

    if SUPERVISION_OBSERVATIONS[
        target_name
    ][
        "direct_supervision_available"
    ]:

        NOTEBOOK_05_BLOCK_2_ERRORS.append(
            "transformative_weight_incorrectly_inferred:"
            f"{target_name}"
        )


# -----------------------------------------------------------------------------
# Execution boundary
# -----------------------------------------------------------------------------

if NOTEBOOK_05_MODEL_INSTANTIATED:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "model_incorrectly_instantiated_in_block_2"
    )


if NOTEBOOK_05_OPTIMIZER_CREATED:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "optimizer_incorrectly_created_in_block_2"
    )


if NOTEBOOK_05_TRAINING_EXECUTED:

    NOTEBOOK_05_BLOCK_2_ERRORS.append(
        "training_incorrectly_executed_in_block_2"
    )


NOTEBOOK_05_BLOCK_2_VALID = (
    len(
        NOTEBOOK_05_BLOCK_2_ERRORS
    )
    == 0
)


if not NOTEBOOK_05_BLOCK_2_VALID:

    raise ValueError(
        "Notebook 05 Block 2 supervision validation failed: "
        f"{NOTEBOOK_05_BLOCK_2_ERRORS}"
    )


# -----------------------------------------------------------------------------
# Block 2 execution state
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_2_COMPLETE = True


# -----------------------------------------------------------------------------
# Block 2 summary object
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_2_SUMMARY = {
    "block":
        NOTEBOOK_05_BLOCK_2,

    "block_name":
        NOTEBOOK_05_BLOCK_2_NAME,

    "inventory_version":
        SUPERVISION_INVENTORY_VERSION,

    "created_at_utc":
        SUPERVISION_INVENTORY_CREATED_AT_UTC,

    "target_family_count":
        SUPERVISION_TARGET_COUNT,

    "notebook_03_supervision_loaded":
        NOTEBOOK_03_SUPERVISION_PERSISTENCE_VALID,

    "notebook_03_accepted_records":
        NOTEBOOK_03_ACCEPTED_RECORD_COUNT,

    "validated_target_families":
        VALIDATED_SUPERVISION_TARGETS,

    "eligible_direct_training_targets":
        ELIGIBLE_DIRECT_TRAINING_TARGETS,

    "active_direct_training_targets":
        ACTIVE_DIRECT_TRAINING_TARGETS,

    "indirect_training_signal_targets":
        INDIRECT_TRAINING_SIGNAL_TARGETS,

    "unavailable_target_families":
        UNAVAILABLE_SUPERVISION_TARGETS,

    "partially_available_target_families":
        PARTIALLY_AVAILABLE_SUPERVISION_TARGETS,

    "space_summary":
        SUPERVISION_SPACE_SUMMARY,

    "component_summary":
        SUPERVISION_COMPONENT_SUMMARY,

    "any_validated_target":
        SUPERVISION_ANY_VALIDATED_TARGET,

    "any_direct_target_eligible":
        SUPERVISION_ANY_DIRECT_TARGET_ELIGIBLE,

    "any_direct_target_active":
        SUPERVISION_ANY_DIRECT_TARGET_ACTIVE,

    "any_indirect_signal_available":
        SUPERVISION_ANY_INDIRECT_SIGNAL_AVAILABLE,

    "model_instantiated":
        NOTEBOOK_05_MODEL_INSTANTIATED,

    "training_executed":
        NOTEBOOK_05_TRAINING_EXECUTED,

    "block_valid":
        NOTEBOOK_05_BLOCK_2_VALID,

    "block_complete":
        NOTEBOOK_05_BLOCK_2_COMPLETE,
}


# -----------------------------------------------------------------------------
# Compact inventory view
# -----------------------------------------------------------------------------

SUPERVISION_INVENTORY_VIEW_COLUMNS = [
    "target_name",
    "architecture_component",
    "representation_space",
    "representation_level",
    "target_type",
    "dimensionality",
    "supervision_state",
    "supervision_source",
    "validation_status",
    "number_eligible",
    "number_available",
    "coverage",
    "number_elements_eligible",
    "number_elements_available",
    "element_coverage",
    "training_eligible",
    "training_active",
]


SUPERVISION_INVENTORY_VIEW = (
    SUPERVISION_INVENTORY_DF[
        SUPERVISION_INVENTORY_VIEW_COLUMNS
    ]
    .copy()
)


# =============================================================================
# Verification
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 05, Block 2: "
    "Supervision Inventory and Target Availability"
)

print("=" * 72)


print(
    f"Inventory version            : "
    f"{SUPERVISION_INVENTORY_VERSION}"
)

print(
    f"Target families              : "
    f"{SUPERVISION_TARGET_COUNT}"
)


print("-" * 72)

print(
    "Persisted Notebook 03 supervision"
)

print(
    f"Accepted file located        : "
    f"{NOTEBOOK_03_ACCEPTED_FILE_LOCATED}"
)

print(
    f"Accepted file ID             : "
    f"{NOTEBOOK_03_ACCEPTED_FILE['id']}"
)

print(
    f"Handover file located        : "
    f"{NOTEBOOK_03_HANDOVER_FILE_LOCATED}"
)

print(
    f"Handover file ID             : "
    f"{NOTEBOOK_03_HANDOVER_FILE['id']}"
)

print(
    f"Accepted records             : "
    f"{NOTEBOOK_03_ACCEPTED_RECORD_COUNT}"
)

print(
    f"Machine supervision avail.   : "
    f"{NOTEBOOK_03_HANDOVER_MACHINE_SUPERVISION_AVAILABLE}"
)

print(
    f"Reference dataset avail.     : "
    f"{NOTEBOOK_03_HANDOVER_REFERENCE_DATASET_AVAILABLE}"
)

print(
    f"Handover count matches       : "
    f"{NOTEBOOK_03_HANDOVER_COUNT_MATCHES}"
)

print(
    f"Sentence IDs present         : "
    f"{NOTEBOOK_03_SENTENCE_IDS_PRESENT}"
)

print(
    f"Sentence IDs unique          : "
    f"{NOTEBOOK_03_SENTENCE_IDS_UNIQUE}"
)

print(
    f"Persistent supervision valid : "
    f"{NOTEBOOK_03_SUPERVISION_PERSISTENCE_VALID}"
)


print("-" * 72)

print(
    "Supervision semantics"
)

print(
    f"Missing = zero               : "
    f"{SUPERVISION_MISSING_EQUALS_ZERO}"
)

print(
    f"Missing = negative           : "
    f"{SUPERVISION_MISSING_EQUALS_NEGATIVE}"
)

print(
    f"Unavailable enters loss      : "
    f"{SUPERVISION_UNAVAILABLE_ENTERS_LOSS}"
)

print(
    f"Confidence part of target    : "
    f"{SUPERVISION_CONFIDENCE_PART_OF_TARGET}"
)

print(
    f"Model output = ground truth  : "
    f"{SUPERVISION_MODEL_OUTPUT_EQUALS_GROUND_TRUTH}"
)

print(
    f"Partial supervision allowed  : "
    f"{SUPERVISION_PARTIAL_TARGETS_ALLOWED}"
)

print(
    f"Block 2 activates objectives : "
    f"{BLOCK_2_ACTIVATES_TRAINING_OBJECTIVES}"
)


print("-" * 72)

print(
    "Current target availability"
)

print(
    f"Validated target families    : "
    f"{len(VALIDATED_SUPERVISION_TARGETS)}"
)

print(
    f"Eligible direct targets      : "
    f"{len(ELIGIBLE_DIRECT_TRAINING_TARGETS)}"
)

print(
    f"Active direct targets        : "
    f"{len(ACTIVE_DIRECT_TRAINING_TARGETS)}"
)

print(
    f"Indirect-signal targets      : "
    f"{len(INDIRECT_TRAINING_SIGNAL_TARGETS)}"
)

print(
    f"Unavailable target families  : "
    f"{len(UNAVAILABLE_SUPERVISION_TARGETS)}"
)

print(
    f"Partially covered targets    : "
    f"{len(PARTIALLY_AVAILABLE_SUPERVISION_TARGETS)}"
)


print("-" * 72)

print(
    "Validated psychological supervision"
)


for target_name in (
    "REV",
    "TEV",
    "IEV",
    "EW",
):

    target_record = (
        SUPERVISION_OBSERVATIONS[
            target_name
        ]
    )


    print(
        f"{target_name:<5}"
        f" sentences available / eligible : "
        f"{target_record['number_available']} / "
        f"{target_record['number_eligible']}"
    )


    print(
        f"{target_name:<5}"
        f" elements available / eligible  : "
        f"{target_record['number_elements_available']} / "
        f"{target_record['number_elements_eligible']}"
    )


    print(
        f"{target_name:<5}"
        f" element coverage               : "
        f"{target_record['element_coverage']:.4f}"
    )


print("-" * 72)

print(
    "Factual supervision boundary"
)

print(
    f"Notebook 03 factological components : "
    f"{NOTEBOOK_03_FACTOLOGICAL_COMPONENT_COUNT}"
)

print(
    f"Component count consistent          : "
    f"{NOTEBOOK_03_FACTOLOGICAL_COMPONENT_COUNT_CONSISTENT}"
)

print(
    f"Factual head activated              : "
    f"{SUPERVISION_OBSERVATIONS['factual_head']['training_active']}"
)

print(
    f"Factual head training eligible      : "
    f"{SUPERVISION_OBSERVATIONS['factual_head']['training_eligible']}"
)


print("-" * 72)

print(
    "Representation-space coverage"
)


for space_name in (
    "factual",
    "psychological",
    "social",
):

    space_summary = (
        SUPERVISION_SPACE_SUMMARY[
            space_name
        ]
    )


    print(
        f"{space_name.capitalize():<14}"
        f" targets / validated / eligible / active : "
        f"{space_summary['target_families']} / "
        f"{space_summary['validated_target_families']} / "
        f"{space_summary['eligible_direct_targets']} / "
        f"{space_summary['active_direct_targets']}"
    )


    print(
        f"{space_name.capitalize():<14}"
        f" sentences available / eligible          : "
        f"{space_summary['available_observations']} / "
        f"{space_summary['eligible_observations']}"
    )


    print(
        f"{space_name.capitalize():<14}"
        f" elements available / eligible           : "
        f"{space_summary['available_elements']} / "
        f"{space_summary['eligible_elements']}"
    )


    print(
        f"{space_name.capitalize():<14}"
        f" element coverage                        : "
        f"{space_summary['aggregate_element_coverage']:.4f}"
    )


print("-" * 72)

print(
    "Architecture-component readiness"
)


for component_name in (
    "factual_head",
    "psychological_head",
    "social_head",
    "transformative_mechanism",
    "recurrent_mechanism",
):

    component_summary = (
        SUPERVISION_COMPONENT_SUMMARY[
            component_name
        ]
    )


    print(
        f"{component_name:<28}: "
        f"eligible="
        f"{component_summary['direct_eligible_targets']}, "
        f"active="
        f"{component_summary['direct_active']}, "
        f"indirect_signal="
        f"{component_summary['indirect_signal_available']}"
    )


print("-" * 72)

print(
    "Training boundary"
)

print(
    f"Supervision inventoried      : "
    f"{NOTEBOOK_05_SUPERVISION_INVENTORIED}"
)

print(
    f"Targets eligible             : "
    f"{NOTEBOOK_05_TARGETS_ELIGIBLE}"
)

print(
    f"Targets activated            : "
    f"{NOTEBOOK_05_TARGETS_ACTIVATED}"
)

print(
    f"Model instantiated           : "
    f"{NOTEBOOK_05_MODEL_INSTANTIATED}"
)

print(
    f"Parameter policy finalised   : "
    f"{NOTEBOOK_05_PARAMETER_POLICY_FINALISED}"
)

print(
    f"Training data constructed    : "
    f"{NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED}"
)

print(
    f"Optimizer created            : "
    f"{NOTEBOOK_05_OPTIMIZER_CREATED}"
)

print(
    f"Forward pass executed        : "
    f"{NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_05_LOSS_CALCULATED}"
)

print(
    f"Training executed            : "
    f"{NOTEBOOK_05_TRAINING_EXECUTED}"
)

print(
    f"Evaluation executed          : "
    f"{NOTEBOOK_05_EVALUATION_EXECUTED}"
)


print("-" * 72)

print(
    "Execution state"
)

print(
    f"Inventory constructed        : "
    f"{SUPERVISION_INVENTORY_CONSTRUCTED}"
)

print(
    f"Inventory validated          : "
    f"{SUPERVISION_INVENTORY_VALIDATED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_05_BLOCK_2_VALID}"
)

print(
    f"Block 2 complete             : "
    f"{NOTEBOOK_05_BLOCK_2_COMPLETE}"
)


print("=" * 72)


print(
    "Supervision inventory constructed successfully."
)

print(
    "Persisted Notebook 03 canonical machine supervision was loaded "
    "directly from Google Drive."
)

print(
    "REV, TEV, IEV and EW are inventoried from validated canonical "
    "sentence-level supervision rather than assumed from architecture."
)

print(
    "Validated machine supervision remains distinct from human-reviewed "
    "or adjudicated reference data."
)

print(
    "Target-level and component-level missing values remain masked and "
    "distinct from numerical zero and negative evidence."
)

print(
    "Factual Notebook 03 supervision has not been automatically mapped "
    "onto the ten-dimensional architectural factual representation."
)

print(
    "TEV remains distinct from architectural psychological transformation."
)

print(
    "EW remains distinct from TW_P."
)

print(
    "TW_F, TW_P and TW_S remain without independent validated supervision."
)

print(
    "H_F, H_P and H_S remain latent recurrent states without direct "
    "supervision."
)

print(
    "Validated direct supervision establishes later training eligibility "
    "but Block 2 does not activate optimisation objectives."
)

print(
    "No model, parameter policy, optimiser, forward pass, loss, training "
    "or evaluation has been executed."
)

print(
    "Block 3 may proceed to Model Instantiation and "
    "Parameter-Freezing Policy using training eligibility rather than "
    "the previous all-unavailable supervision assumption."
)


# -----------------------------------------------------------------------------
# Display compact inventory
# -----------------------------------------------------------------------------

display(
    SUPERVISION_INVENTORY_VIEW
)

========================================================================
Media AI — Notebook 05, Block 2: Supervision Inventory and Target Availability
========================================================================
Inventory version            : 1.1
Target families              : 18
------------------------------------------------------------------------
Persisted Notebook 03 supervision
Accepted file located        : True
Accepted file ID             : 1gYiCR-i_avGCwE5O9p921es8Mzbzhvyl
Handover file located        : True
Handover file ID             : 1UWBqN1iUFGzRpa2lo4aMl3ctgzqvIPxp
Accepted records             : 16
Machine supervision avail.   : True
Reference dataset avail.     : False
Handover count matches       : True
Sentence IDs present         : True
Sentence IDs unique          : True
Persistent supervision valid : True
------------------------------------------------------------------------
Supervision semantics
Missing = zero               : False
Missing = negative           : False
Unavailable enters loss      : False
Confidence part of target    : False
Model output = ground truth  : False
Partial supervision allowed  : True
Block 2 activates objectives : False
------------------------------------------------------------------------
Current target availability
Validated target families    : 4
Eligible direct targets      : 4
Active direct targets        : 0
Indirect-signal targets      : 0
Unavailable target families  : 14
Partially covered targets    : 1
------------------------------------------------------------------------
Validated psychological supervision
REV   sentences available / eligible : 16 / 16
REV   elements available / eligible  : 40 / 176
REV   element coverage               : 0.2273
TEV   sentences available / eligible : 16 / 16
TEV   elements available / eligible  : 176 / 176
TEV   element coverage               : 1.0000
IEV   sentences available / eligible : 16 / 16
IEV   elements available / eligible  : 176 / 176
IEV   element coverage               : 1.0000
EW    sentences available / eligible : 16 / 16
EW    elements available / eligible  : 16 / 16
EW    element coverage               : 1.0000
------------------------------------------------------------------------
Factual supervision boundary
Notebook 03 factological components : 8
Component count consistent          : True
Factual head activated              : False
Factual head training eligible      : False
------------------------------------------------------------------------
Representation-space coverage
Factual        targets / validated / eligible / active : 4 / 0 / 0 / 0
Factual        sentences available / eligible          : 0 / 0
Factual        elements available / eligible           : 0 / 0
Factual        element coverage                        : 0.0000
Psychological  targets / validated / eligible / active : 7 / 4 / 4 / 0
Psychological  sentences available / eligible          : 64 / 64
Psychological  elements available / eligible           : 408 / 544
Psychological  element coverage                        : 0.7500
Social         targets / validated / eligible / active : 7 / 0 / 0 / 0
Social         sentences available / eligible          : 0 / 0
Social         elements available / eligible           : 0 / 0
Social         element coverage                        : 0.0000
------------------------------------------------------------------------
Architecture-component readiness
factual_head                : eligible=(), active=False, indirect_signal=False
psychological_head          : eligible=('REV', 'TEV', 'IEV', 'EW'), active=False, indirect_signal=False
social_head                 : eligible=(), active=False, indirect_signal=False
transformative_mechanism    : eligible=(), active=False, indirect_signal=False
recurrent_mechanism         : eligible=(), active=False, indirect_signal=False
------------------------------------------------------------------------
Training boundary
Supervision inventoried      : True
Targets eligible             : True
Targets activated            : False
Model instantiated           : False
Parameter policy finalised   : False
Training data constructed    : False
Optimizer created            : False
Forward pass executed        : False
Loss calculated              : False
Training executed            : False
Evaluation executed          : False
------------------------------------------------------------------------
Execution state
Inventory constructed        : True
Inventory validated          : True
Block valid                  : True
Block 2 complete             : True
========================================================================
Supervision inventory constructed successfully.
Persisted Notebook 03 canonical machine supervision was loaded directly from Google Drive.
REV, TEV, IEV and EW are inventoried from validated canonical sentence-level supervision rather than assumed from architecture.
Validated machine supervision remains distinct from human-reviewed or adjudicated reference data.
Target-level and component-level missing values remain masked and distinct from numerical zero and negative evidence.
Factual Notebook 03 supervision has not been automatically mapped onto the ten-dimensional architectural factual representation.
TEV remains distinct from architectural psychological transformation.
EW remains distinct from TW_P.
TW_F, TW_P and TW_S remain without independent validated supervision.
H_F, H_P and H_S remain latent recurrent states without direct supervision.
Validated direct supervision establishes later training eligibility but Block 2 does not activate optimisation objectives.
No model, parameter policy, optimiser, forward pass, loss, training or evaluation has been executed.
Block 3 may proceed to Model Instantiation and Parameter-Freezing Policy using training eligibility rather than the previous all-unavailable supervision assumption.

,target_name,architecture_component,representation_space,representation_level,target_type,dimensionality,supervision_state,supervision_source,validation_status,number_eligible,number_available,coverage,number_elements_eligible,number_elements_available,element_coverage,training_eligible,training_active
0,factual_head,factual_head,factual,sentence,continuous_plus_components,10.0,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
1,REV,psychological_head,psychological,sentence,continuous_vector,11.0,validated,validated_machine_supervision,validated,16,16,1.0,176,40,0.227273,True,False
2,TEV,psychological_head,psychological,sentence,signed_continuous_vector,11.0,validated,validated_machine_supervision,validated,16,16,1.0,176,176,1.000000,True,False
3,IEV,psychological_head,psychological,sentence,continuous_vector,11.0,validated,validated_machine_supervision,validated,16,16,1.0,176,176,1.000000,True,False
4,EW,psychological_head,psychological,sentence,continuous_scalar,1.0,validated,validated_machine_supervision,validated,16,16,1.0,16,16,1.000000,True,False
5,actors,social_head,social,structured_social_object,structured,NaN,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
6,groups,social_head,social,structured_social_object,structured,NaN,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
7,memberships,social_head,social,structured_social_object,structured,NaN,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
8,relationships,social_head,social,structured_social_object,structured,NaN,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
9,factual_transformation,transformative_mechanism,factual,sentence,signed_continuous_vector,10.0,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
10,psychological_transformation,transformative_mechanism,psychological,sentence,signed_continuous_vector,34.0,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
11,social_transformation,transformative_mechanism,social,structured_social_object,structured,NaN,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
12,TW_F,transformative_mechanism,factual,sentence,continuous_scalar,1.0,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
13,TW_P,transformative_mechanism,psychological,sentence,continuous_scalar,1.0,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
14,TW_S,transformative_mechanism,social,sentence,continuous_scalar,1.0,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
15,H_F,recurrent_mechanism,factual,sentence,latent_recurrent_state,NaN,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
16,H_P,recurrent_mechanism,psychological,sentence,latent_recurrent_state,NaN,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False
17,H_S,recurrent_mechanism,social,sentence,latent_recurrent_state,NaN,unavailable,unavailable,not_validated,0,0,0.0,0,0,0.000000,False,False

In [ ]:
import inspect

print(
    inspect.signature(
        download_drive_file_bytes
    )
)

(drive_service, file_id)

In [ ]:
# =============================================================================
# Media AI — Notebook 05 Drive Runtime Diagnostic
# =============================================================================

candidate_drive_objects = [
    "drive_service",
    "DRIVE_SERVICE",
    "google_drive_service",
    "GOOGLE_DRIVE_SERVICE",
    "service",
]

for name in candidate_drive_objects:
    print(
        f"{name:<24}: "
        f"{name in globals()}"
    )

print("-" * 72)

matching_names = [
    name
    for name in globals()
    if "drive" in name.lower()
    or "service" in name.lower()
]

print("Drive/service-related globals:")
for name in sorted(matching_names):
    print(name)

drive_service           : False
DRIVE_SERVICE           : False
google_drive_service    : False
GOOGLE_DRIVE_SERVICE    : False
service                 : False
------------------------------------------------------------------------
Drive/service-related globals:
DRIVE_SERVICE_FOR_HANDOVER
NOTEBOOK_05_DRIVE_SERVICE_INITIALISED
NOTEBOOK_05_HANDOVER_DRIVE_FILE
NOTEBOOK_05_HANDOVER_DRIVE_FILE_ID
NOTEBOOK_05_HANDOVER_LOADED_FROM_DRIVE
candidate_drive_objects
download_drive_file_bytes
get_media_ai_drive_service

## Block 3 — Model Instantiation and Parameter-Freezing Policy

### Purpose

This block defines the **model-instantiation and parameter-freezing policy** for Notebook 05.

Block 2 established that the Media AI architecture contains eighteen target families, but no direct validated supervision target is currently active.

This does not prevent the architecture from being instantiated.

It does prevent the notebook from treating architectural parameters as trainable merely because they exist.

The central distinction of this block is therefore:

$$
\text{model instantiation}
\neq
\text{parameter activation}
$$

A model component may be instantiated for structural validation, controlled forward passes and later training while its parameters remain frozen.

This block defines the parameter policy only.

It does not create an optimiser.

It does not execute a forward pass.

It does not calculate loss.

It does not train model parameters.

---

### Instantiation principle

Notebook 05 may instantiate the reference architecture after the supervision inventory has been validated.

Instantiation means that the model components and their parameter structures are created in memory.

It does not imply that those parameters are eligible for optimisation.

For parameter group \(p\), define:

$$
I_p \in \{0,1\}
$$

where \(I_p=1\) means that the component is instantiated.

Define separately:

$$
T_p \in \{0,1\}
$$

where \(T_p=1\) means that the parameter group is trainable.

The reference policy permits:

$$
I_p=1,\qquad T_p=0
$$

A component may therefore be instantiated while remaining frozen.

---

### Parameter states

Each parameter group must be assigned one explicit parameter state.

The permitted states are:

- **trainable** — gradients are calculated and optimisation is permitted;
- **frozen** — parameters participate in the forward graph but are not updated;
- **conditionally trainable** — parameters may become trainable after an explicitly defined supervision or indirect-learning condition is satisfied;
- **inactive** — the component is not used in the current experimental configuration;
- **not instantiated** — the component does not yet exist in memory.

These states must remain explicit and auditable.

---

### Reference architecture

The reference model preserves the architectural sequence validated in Notebook 04:

$$
\text{textual representation}
\rightarrow
\text{confluent conditioning}
\rightarrow
\text{representation heads}
\rightarrow
\text{transformative mechanism}
\rightarrow
\text{recurrent mechanism}
$$

The parameter policy must not silently alter this architecture.

A later ablation may deactivate individual components, but such a configuration must be recorded as an experimental variant.

---

### Backbone policy

The pretrained semantic backbone provides the contextual textual representation.

Its parameters are **not automatically trainable**.

The default reference policy is:

$$
T_{\text{backbone}}=0
$$

The backbone therefore begins frozen.

This protects the pretrained semantic representation from uncontrolled adaptation before:

- supervision quality is established;
- the downstream architecture has passed controlled forward validation;
- the training objective is defined;
- parameter-efficient alternatives have been considered.

A later experiment may activate a subset of backbone parameters, but such activation must be explicit.

---

### Backbone adaptation options

Possible later backbone policies include:

- fully frozen backbone;
- parameter-efficient adaptation;
- partial layer unfreezing;
- broader fine-tuning.

The reference configuration begins with the fully frozen option.

No fine-tuning strategy is selected merely because the backbone exposes trainable parameters.

---

### Confluent-conditioning policy

The confluent-conditioning mechanism defines global and optional group-conditioned representation routes.

The global path is required.

Group-conditioned routing remains optional and depends on valid group information.

The confluent mechanism may be instantiated even when group-conditioned supervision is unavailable.

However, its trainable parameters must initially remain frozen unless an admissible learning signal is established.

Therefore:

$$
T_{\text{confluent}}=0
$$

in the initial reference policy.

---

### Global-path policy

The global path is mandatory for the reference architecture.

It must remain instantiated whenever the architecture is instantiated.

The global path must not depend on the availability of group-conditioned supervision.

Therefore:

$$
I_{\text{global}}=1
$$

once the reference model is instantiated.

---

### Group-conditioned path policy

The group-conditioned path is optional.

Its architecture may be instantiated, but execution requires valid group-conditioned inputs.

Its group-specific adaptation parameters must not become trainable solely because the adapter exists.

The default policy is:

$$
T_{\text{group-adapter}}=0
$$

until a valid group-conditioned training signal is available.

---

### Factual-head policy

The factual head predicts the ten-dimensional factual representation.

Block 2 found no active direct factual supervision.

Therefore, the factual head may be instantiated for structural validation but must initially remain frozen for optimisation.

The reference state is:

$$
I_F=1
$$

and:

$$
T_F=0
$$

Direct factual optimisation may become permissible later only when validated factual supervision or another explicitly justified training objective is available.

---

### Psychological-head policy

The psychological head produces:

- REV;
- TEV;
- IEV;
- EW.

No direct validated psychological supervision is currently active.

The psychological head may therefore be instantiated while remaining frozen.

The initial policy is:

$$
I_P=1
$$

and:

$$
T_P=0
$$

The availability of one psychological target family in a later experiment must not automatically activate all psychological outputs.

For example, validated REV supervision would not automatically authorise TEV, IEV or EW optimisation.

---

### Social-head policy

The social head preserves structured outputs for:

- actors;
- groups;
- memberships;
- relationships.

No validated structured social supervision is currently active.

The social head may be instantiated structurally, but its trainable parameters must initially remain frozen.

Therefore:

$$
I_S=1
$$

and:

$$
T_S=0
$$

Structured social decoding must not become trainable from missing labels.

---

### Transformative-mechanism policy

The transformative mechanism contains:

- factual transformation;
- psychological transformation;
- social transformation;
- TW_F;
- TW_P;
- TW_S.

Direct architectural transformation supervision is currently unavailable.

The three Transformative Weights also have no validated direct supervision.

The transformative mechanism may nevertheless be instantiated because it is required for the reference architecture and later controlled forward validation.

Its parameters must initially remain frozen:

$$
I_T=1
$$

$$
T_T=0
$$

---

### Space-specific Transformative Weight parameters

The three Transformative Weight predictors remain separate parameter groups:

$$
\theta_{TW_F}
$$

$$
\theta_{TW_P}
$$

$$
\theta_{TW_S}
$$

The absence of validated supervision means:

$$
T_{TW_F}=0
$$

$$
T_{TW_P}=0
$$

$$
T_{TW_S}=0
$$

in the initial policy.

The three weights must not be activated jointly merely because one later receives valid supervision.

---

### Transformation-gate policy

The factual and psychological transformation gates are trainable architectural modules.

However, the existence of a gate does not provide its own training objective.

The initial policy therefore keeps transformation-gate parameters frozen:

$$
T_{\text{gate}}=0
$$

They may become trainable later through a validated direct or indirect objective.

---

### Recurrent-mechanism policy

The recurrent mechanism contains separate states:

$$
H^F_t,\qquad H^P_t,\qquad H^S_t
$$

No direct validated recurrent-state supervision is currently active.

This does not require the recurrent mechanism to remain absent.

The recurrent mechanism may be instantiated for sequential forward validation while its parameters remain frozen.

Therefore:

$$
I_R=1
$$

and:

$$
T_R=0
$$

in the initial policy.

---

### Recurrent retention-gate policy

The recurrent retention gates are internal trainable mechanisms.

Transformative Weight is not the retention gate:

$$
TW^q_t \neq K^q_t
$$

The retention-gate parameters remain frozen until the recurrent mechanism receives an admissible training signal.

No gate parameter is activated simply because the corresponding recurrent state exists.

---

### Direct supervision and parameter activation

Direct supervision provides one possible route to trainability.

For parameter group \(p\), direct activation requires a corresponding admissible target family or explicitly defined mapping from validated supervision.

Conceptually:

$$
DirectTrainable_p
=
ValidTarget_p
\land
Coverage_p>0
\land
ObjectiveDefined_p
$$

This is a necessary methodological condition for direct supervised optimisation.

It does not imply that every parameter group must have direct supervision.

---

### Indirect trainability

Some internal components may later be trained indirectly.

Examples include:

- transformative mechanisms;
- recurrent mechanisms;
- routing components.

Indirect training may occur when a validated downstream objective propagates gradients through those components.

Define:

$$
IndirectTrainable_p
=
DownstreamObjectiveValid
\land
GradientPathValid_p
\land
PolicyAllows_p
$$

Indirect trainability must be explicitly declared.

It must not be represented as direct supervision.

---

### Current indirect-training state

Block 2 did not activate any indirect training signal.

Therefore, at the end of Block 3:

$$
IndirectTrainable_p=0
$$

for all parameter groups unless a later block defines and validates such a signal.

This means the initial reference model can be instantiated entirely frozen.

---

### Why instantiate a frozen model

A fully frozen initial model is still useful.

It allows Notebook 05 to validate:

- component connectivity;
- dimensional compatibility;
- global routing;
- optional group routing interfaces;
- transformative routing;
- recurrent routing;
- mask propagation;
- sequence handling;
- numerical stability;
- device compatibility;
- output structure.

These checks should occur before optimisation.

Thus:

$$
\text{structural validation}
\rightarrow
\text{parameter activation}
$$

rather than:

$$
\text{parameter activation}
\rightarrow
\text{discover structural failure}
$$

---

### Parameter groups

Notebook 05 must maintain an explicit registry of parameter groups.

The registry should include at minimum:

- backbone;
- confluent shared parameters;
- confluent group-conditioned adaptation;
- factual head;
- factual group adapter;
- psychological head;
- psychological group adapter;
- social head;
- social group adapter;
- factual transformation core;
- psychological transformation core;
- social transformation core;
- factual transformation gate;
- psychological transformation gate;
- TW_F predictor;
- TW_P predictor;
- TW_S predictor;
- factual transformative group adapter;
- psychological transformative group adapter;
- social transformative group adapter;
- factual recurrent mechanism;
- psychological recurrent mechanism;
- social recurrent mechanism;
- factual recurrent group adapter;
- psychological recurrent group adapter;
- social recurrent group adapter.

Each registry entry must record its current parameter state.

---

### Parameter counts

After instantiation, Notebook 05 should record for each parameter group:

- total parameter count;
- trainable parameter count;
- frozen parameter count.

For group \(p\):

$$
N^{total}_p
=
N^{trainable}_p
+
N^{frozen}_p
$$

The overall model must satisfy:

$$
N^{total}
=
N^{trainable}
+
N^{frozen}
$$

This provides an auditable check that the parameter policy has actually been applied.

---

### Gradient policy

Frozen parameters must satisfy:

$$
requires\_grad = False
$$

Trainable parameters must satisfy:

$$
requires\_grad = True
$$

The policy must be enforced programmatically rather than recorded only in metadata.

A mismatch between the declared parameter state and PyTorch `requires_grad` state must be treated as an error.

---

### Default reference policy

Given the current Block 2 supervision inventory, the initial reference policy is:

- instantiate the architecture;
- freeze the pretrained backbone;
- freeze confluent conditioning;
- freeze factual head;
- freeze psychological head;
- freeze social head;
- freeze all group-conditioned adapters;
- freeze transformative mechanism;
- freeze TW_F, TW_P and TW_S predictors;
- freeze recurrent mechanism.

Therefore, immediately after model instantiation:

$$
N^{trainable}=0
$$

for the reference pre-training validation state.

This is intentional.

---

### Controlled activation

A parameter group may later transition from frozen to trainable only after the corresponding training condition is explicitly satisfied.

Conceptually:

$$
Frozen
\rightarrow
ConditionallyTrainable
\rightarrow
Trainable
$$

The transition must record:

- triggering supervision or objective;
- block in which activation occurred;
- parameter group;
- previous state;
- new state;
- justification.

---

### No implicit unfreezing

Calling:

```text
model.train()

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Block 3: Model Instantiation and Parameter-Freezing Policy
# =============================================================================

from collections import OrderedDict
from datetime import datetime, timezone
import random

import numpy as np
import pandas as pd
import torch
import torch.nn as nn


# -----------------------------------------------------------------------------
# Block dependency checks
# -----------------------------------------------------------------------------

required_block_1_objects = [
    "NOTEBOOK_05_BLOCK_1_COMPLETE",
    "NOTEBOOK_05_HANDOVER_VALID",
    "NOTEBOOK_05_HANDOVER",
]


missing_block_1_objects = [
    object_name
    for object_name
    in required_block_1_objects
    if object_name not in globals()
]


if missing_block_1_objects:
    raise NameError(
        "Notebook 05 Block 1 is not initialised. "
        f"Missing: {missing_block_1_objects}"
    )


required_block_2_objects = [
    "NOTEBOOK_05_BLOCK_2_COMPLETE",
    "NOTEBOOK_05_BLOCK_2_VALID",
    "SUPERVISION_INVENTORY",
    "SUPERVISION_INVENTORY_VALIDATED",
    "VALIDATED_SUPERVISION_TARGETS",
    "ELIGIBLE_DIRECT_TRAINING_TARGETS",
    "ACTIVE_DIRECT_TRAINING_TARGETS",
    "INDIRECT_TRAINING_SIGNAL_TARGETS",
    "NOTEBOOK_05_TARGETS_ELIGIBLE",
    "NOTEBOOK_05_TARGETS_ACTIVATED",
]


missing_block_2_objects = [
    object_name
    for object_name
    in required_block_2_objects
    if object_name not in globals()
]


if missing_block_2_objects:
    raise NameError(
        "Notebook 05 Block 2 is not initialised. "
        f"Missing: {missing_block_2_objects}"
    )


if not NOTEBOOK_05_BLOCK_1_COMPLETE:
    raise ValueError(
        "Notebook 05 Block 1 must be complete before "
        "model instantiation."
    )


if not NOTEBOOK_05_HANDOVER_VALID:
    raise ValueError(
        "Notebook 05 requires a valid Notebook 04 handover."
    )


if not NOTEBOOK_05_BLOCK_2_COMPLETE:
    raise ValueError(
        "Notebook 05 Block 2 must be complete before "
        "model instantiation."
    )


if not NOTEBOOK_05_BLOCK_2_VALID:
    raise ValueError(
        "Notebook 05 Block 2 supervision inventory is invalid."
    )


if not SUPERVISION_INVENTORY_VALIDATED:
    raise ValueError(
        "The supervision inventory must be validated before "
        "parameter policy is defined."
    )


if not NOTEBOOK_05_TARGETS_ELIGIBLE:
    raise ValueError(
        "Notebook 05 Block 3 expected at least one validated "
        "training-eligible direct target."
    )


if NOTEBOOK_05_TARGETS_ACTIVATED:
    raise ValueError(
        "Notebook 05 Block 2 must not activate optimisation "
        "objectives before Block 3 parameter policy is defined."
    )


# -----------------------------------------------------------------------------
# Block configuration
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_3 = 3

NOTEBOOK_05_BLOCK_3_NAME = (
    "Model Instantiation and Parameter-Freezing Policy"
)

MODEL_IMPLEMENTATION_VERSION = "1.1"

PARAMETER_POLICY_VERSION = "1.1"

MODEL_INSTANTIATED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# -----------------------------------------------------------------------------
# Reproducibility
# -----------------------------------------------------------------------------

MODEL_RANDOM_SEED = 42


random.seed(
    MODEL_RANDOM_SEED
)

np.random.seed(
    MODEL_RANDOM_SEED
)

torch.manual_seed(
    MODEL_RANDOM_SEED
)


if torch.cuda.is_available():
    torch.cuda.manual_seed_all(
        MODEL_RANDOM_SEED
    )


# -----------------------------------------------------------------------------
# Device policy
# -----------------------------------------------------------------------------

if torch.cuda.is_available():

    MODEL_DEVICE = torch.device(
        "cuda"
    )

else:

    MODEL_DEVICE = torch.device(
        "cpu"
    )


MODEL_DTYPE = torch.float32

MIXED_PRECISION_ENABLED = False


# -----------------------------------------------------------------------------
# Architecture contract from validated handover
# -----------------------------------------------------------------------------

FACTUAL_DIM = int(
    NOTEBOOK_05_HANDOVER[
        "factual_dimensions"
    ]
)

PSYCHOLOGICAL_DIM = int(
    NOTEBOOK_05_HANDOVER[
        "psychological_dimensions"
    ]
)

SOCIAL_COMPONENTS = tuple(
    NOTEBOOK_05_HANDOVER[
        "social_components"
    ]
)

TRANSFORMATIVE_WEIGHTS = dict(
    NOTEBOOK_05_HANDOVER[
        "transformative_weights"
    ]
)

RECURRENT_STATES = dict(
    NOTEBOOK_05_HANDOVER[
        "recurrent_states"
    ]
)


if FACTUAL_DIM != 10:
    raise ValueError(
        "Block 3 expected a 10-dimensional factual contract."
    )


if PSYCHOLOGICAL_DIM != 34:
    raise ValueError(
        "Block 3 expected a 34-dimensional psychological contract."
    )


if SOCIAL_COMPONENTS != (
    "actors",
    "groups",
    "memberships",
    "relationships",
):
    raise ValueError(
        "Block 3 social structure does not match "
        "the validated handover."
    )


if TRANSFORMATIVE_WEIGHTS != {
    "factual": "TW_F",
    "psychological": "TW_P",
    "social": "TW_S",
}:
    raise ValueError(
        "Block 3 Transformative Weight contract is invalid."
    )


if RECURRENT_STATES != {
    "factual": "H_F",
    "psychological": "H_P",
    "social": "H_S",
}:
    raise ValueError(
        "Block 3 recurrent-state contract is invalid."
    )


# -----------------------------------------------------------------------------
# Executable implementation dimensions
# -----------------------------------------------------------------------------
#
# A concrete pretrained semantic backbone has not yet been selected.
#
# The architecture therefore begins from an explicit textual-representation
# interface. The interface accepts contextual sentence embeddings produced by
# a future selected backbone.
#
# architecture contract != concrete pretrained backbone
# -----------------------------------------------------------------------------

BACKBONE_HIDDEN_DIM = 768

CONFLUENT_HIDDEN_DIM = 256

HEAD_HIDDEN_DIM = 128

SOCIAL_HIDDEN_DIM = 128

TRANSFORMATIVE_HIDDEN_DIM = 128

RECURRENT_FACTUAL_DIM = 64

RECURRENT_PSYCHOLOGICAL_DIM = 96

RECURRENT_SOCIAL_DIM = 64

GROUP_EMBEDDING_DIM = 64

DROPOUT_RATE = 0.10


# -----------------------------------------------------------------------------
# Parameter-state vocabulary
# -----------------------------------------------------------------------------

PARAMETER_STATES = (
    "trainable",
    "frozen",
    "conditionally_trainable",
    "inactive",
    "not_instantiated",
)


# -----------------------------------------------------------------------------
# Current supervision policy
# -----------------------------------------------------------------------------
#
# Block 2 distinguishes:
#
#   validated supervision
#       ↓
#   training eligibility
#       ↓
#   later optimisation activation
#
# Block 3 uses training eligibility to determine which parameter groups may
# become trainable.
#
# It does not create an optimiser, calculate a loss or execute training.
# -----------------------------------------------------------------------------

CURRENT_VALIDATED_TARGETS = tuple(
    VALIDATED_SUPERVISION_TARGETS
)

CURRENT_ELIGIBLE_DIRECT_TARGETS = tuple(
    ELIGIBLE_DIRECT_TRAINING_TARGETS
)

CURRENT_ACTIVE_DIRECT_TARGETS = tuple(
    ACTIVE_DIRECT_TRAINING_TARGETS
)

CURRENT_INDIRECT_SIGNAL_TARGETS = tuple(
    INDIRECT_TRAINING_SIGNAL_TARGETS
)


CURRENT_VALIDATED_TARGET_COUNT = len(
    CURRENT_VALIDATED_TARGETS
)

CURRENT_ELIGIBLE_DIRECT_TARGET_COUNT = len(
    CURRENT_ELIGIBLE_DIRECT_TARGETS
)

CURRENT_ACTIVE_DIRECT_TARGET_COUNT = len(
    CURRENT_ACTIVE_DIRECT_TARGETS
)

CURRENT_INDIRECT_TARGET_COUNT = len(
    CURRENT_INDIRECT_SIGNAL_TARGETS
)


CURRENT_DIRECT_SUPERVISION_AVAILABLE = (
    CURRENT_ELIGIBLE_DIRECT_TARGET_COUNT > 0
)

CURRENT_INDIRECT_SIGNAL_AVAILABLE = (
    CURRENT_INDIRECT_TARGET_COUNT > 0
)


EXPECTED_CURRENT_ELIGIBLE_TARGETS = (
    "REV",
    "TEV",
    "IEV",
    "EW",
)


if (
    CURRENT_ELIGIBLE_DIRECT_TARGETS
    != EXPECTED_CURRENT_ELIGIBLE_TARGETS
):
    raise ValueError(
        "Block 3 expected the current validated direct supervision "
        "to contain only REV, TEV, IEV and EW. "
        f"Received: {CURRENT_ELIGIBLE_DIRECT_TARGETS}"
    )


if CURRENT_ACTIVE_DIRECT_TARGET_COUNT != 0:
    raise ValueError(
        "Direct optimisation targets must remain inactive before "
        "Block 3 defines the parameter policy."
    )


# -----------------------------------------------------------------------------
# Backbone representation interface
# -----------------------------------------------------------------------------

class FrozenBackboneInterface(nn.Module):
    """
    Interface for contextual textual representations.

    A concrete pretrained semantic backbone is intentionally not loaded
    in Block 3.

    The interface receives sentence-level embeddings from a future selected
    backbone and applies an identity-compatible frozen projection.
    """

    def __init__(
        self,
        hidden_dim,
    ):
        super().__init__()

        if hidden_dim <= 0:
            raise ValueError(
                "hidden_dim must be greater than zero."
            )

        self.hidden_dim = int(
            hidden_dim
        )

        self.projection = nn.Linear(
            self.hidden_dim,
            self.hidden_dim,
        )

        with torch.no_grad():

            self.projection.weight.copy_(
                torch.eye(
                    self.hidden_dim
                )
            )

            self.projection.bias.zero_()


    def forward(
        self,
        textual_representation,
    ):

        if (
            textual_representation.shape[-1]
            != self.hidden_dim
        ):
            raise ValueError(
                "Backbone-interface input has incompatible "
                "dimensionality."
            )

        return self.projection(
            textual_representation
        )


# -----------------------------------------------------------------------------
# Confluent-conditioning mechanism
# -----------------------------------------------------------------------------

class ConfluentConditioningModule(nn.Module):
    """
    Global and optional group-conditioned representation router.

    The global representation remains independently preserved.
    """

    def __init__(
        self,
        input_dim,
        hidden_dim,
        group_embedding_dim,
        dropout=0.1,
    ):
        super().__init__()

        self.input_dim = int(
            input_dim
        )

        self.hidden_dim = int(
            hidden_dim
        )

        self.group_embedding_dim = int(
            group_embedding_dim
        )

        self.global_projection = nn.Sequential(
            nn.Linear(
                self.input_dim,
                self.hidden_dim,
            ),

            nn.GELU(),

            nn.Dropout(
                float(
                    dropout
                )
            ),

            nn.LayerNorm(
                self.hidden_dim
            ),
        )

        self.group_adapter = nn.Sequential(
            nn.Linear(
                self.hidden_dim
                + self.group_embedding_dim,
                self.hidden_dim,
            ),

            nn.GELU(),

            nn.Dropout(
                float(
                    dropout
                )
            ),

            nn.Linear(
                self.hidden_dim,
                self.hidden_dim,
            ),
        )


    def forward_global(
        self,
        textual_representation,
    ):

        return self.global_projection(
            textual_representation
        )


    def forward_group(
        self,
        global_representation,
        group_embedding,
    ):

        if (
            global_representation.shape[-1]
            != self.hidden_dim
        ):
            raise ValueError(
                "Global confluent representation has "
                "incompatible dimensionality."
            )

        if (
            group_embedding.shape[-1]
            != self.group_embedding_dim
        ):
            raise ValueError(
                "Group embedding has incompatible dimensionality."
            )

        group_input = torch.cat(
            [
                global_representation,
                group_embedding,
            ],
            dim=-1,
        )

        group_adjustment = self.group_adapter(
            group_input
        )

        return (
            global_representation
            + group_adjustment
        )


# -----------------------------------------------------------------------------
# Shared representation-head core
# -----------------------------------------------------------------------------

class RepresentationHeadCore(nn.Module):
    """
    Shared dense-head structure instantiated separately for each
    representation space.
    """

    def __init__(
        self,
        input_dim,
        hidden_dim,
        dropout=0.1,
    ):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(
                input_dim,
                hidden_dim,
            ),

            nn.GELU(),

            nn.Dropout(
                float(
                    dropout
                )
            ),

            nn.LayerNorm(
                hidden_dim
            ),
        )


    def forward(
        self,
        x,
    ):

        return self.network(
            x
        )


# -----------------------------------------------------------------------------
# Factual head
# -----------------------------------------------------------------------------

class FactualHead(nn.Module):
    """
    Ten-dimensional architectural factual representation head.

    The current Notebook 05 supervision inventory does not yet provide a
    validated mapping from Notebook 03 factological annotations onto this
    ten-dimensional architectural output.
    """

    def __init__(
        self,
        input_dim,
        hidden_dim,
        dropout=0.1,
    ):
        super().__init__()

        self.core = RepresentationHeadCore(
            input_dim=
                input_dim,

            hidden_dim=
                hidden_dim,

            dropout=
                dropout,
        )

        self.output_layer = nn.Linear(
            hidden_dim,
            FACTUAL_DIM,
        )


    def forward(
        self,
        representation,
    ):

        hidden = self.core(
            representation
        )

        logits = self.output_layer(
            hidden
        )

        values = torch.sigmoid(
            logits
        )

        return {
            "hidden":
                hidden,

            "logits":
                logits,

            "values":
                values,
        }


# -----------------------------------------------------------------------------
# Psychological head
# -----------------------------------------------------------------------------

class PsychologicalHead(nn.Module):
    """
    34-dimensional Psychological State Vector.

    Ordering:
        REV 11
        TEV 11
        IEV 11
        EW  1
    """

    def __init__(
        self,
        input_dim,
        hidden_dim,
        dropout=0.1,
    ):
        super().__init__()

        self.core = RepresentationHeadCore(
            input_dim=
                input_dim,

            hidden_dim=
                hidden_dim,

            dropout=
                dropout,
        )

        self.output_layer = nn.Linear(
            hidden_dim,
            PSYCHOLOGICAL_DIM,
        )


    def forward(
        self,
        representation,
    ):

        hidden = self.core(
            representation
        )

        logits = self.output_layer(
            hidden
        )

        rev = torch.sigmoid(
            logits[
                ...,
                0:11
            ]
        )

        tev = torch.tanh(
            logits[
                ...,
                11:22
            ]
        )

        iev = torch.sigmoid(
            logits[
                ...,
                22:33
            ]
        )

        ew = torch.sigmoid(
            logits[
                ...,
                33:34
            ]
        )

        values = torch.cat(
            [
                rev,
                tev,
                iev,
                ew,
            ],
            dim=-1,
        )

        return {
            "hidden":
                hidden,

            "logits":
                logits,

            "REV":
                rev,

            "TEV":
                tev,

            "IEV":
                iev,

            "EW":
                ew,

            "values":
                values,
        }


# -----------------------------------------------------------------------------
# Social head
# -----------------------------------------------------------------------------

class SocialHead(nn.Module):
    """
    Structured social head.

    Fixed hidden representations are used internally while actors, groups,
    memberships and relationships remain structured downstream objects.

    Structured decoding remains deferred.
    """

    def __init__(
        self,
        input_dim,
        hidden_dim,
        dropout=0.1,
    ):
        super().__init__()

        self.core = RepresentationHeadCore(
            input_dim=
                input_dim,

            hidden_dim=
                hidden_dim,

            dropout=
                dropout,
        )

        self.actor_projection = nn.Linear(
            hidden_dim,
            hidden_dim,
        )

        self.group_projection = nn.Linear(
            hidden_dim,
            hidden_dim,
        )

        self.membership_projection = nn.Linear(
            hidden_dim,
            hidden_dim,
        )

        self.relationship_projection = nn.Linear(
            hidden_dim,
            hidden_dim,
        )


    def forward(
        self,
        representation,
    ):

        hidden = self.core(
            representation
        )

        return {
            "hidden":
                hidden,

            "actors_hidden":
                self.actor_projection(
                    hidden
                ),

            "groups_hidden":
                self.group_projection(
                    hidden
                ),

            "memberships_hidden":
                self.membership_projection(
                    hidden
                ),

            "relationships_hidden":
                self.relationship_projection(
                    hidden
                ),

            "actors":
                None,

            "groups":
                None,

            "memberships":
                None,

            "relationships":
                None,

            "structured_decoding_executed":
                False,
        }


# -----------------------------------------------------------------------------
# Space-specific transformation gate
# -----------------------------------------------------------------------------

class TransformationGate(nn.Module):
    """
    Dimension-wise architectural transformation gate.
    """

    def __init__(
        self,
        representation_dim,
    ):
        super().__init__()

        self.representation_dim = int(
            representation_dim
        )

        self.gate_layer = nn.Linear(
            self.representation_dim,
            self.representation_dim,
        )


    def forward(
        self,
        representation,
        transformation,
    ):

        gate = torch.sigmoid(
            self.gate_layer(
                representation
            )
        )

        return {
            "gate":
                gate,

            "gated_transformation":
                gate
                * transformation,
        }


# -----------------------------------------------------------------------------
# Space-specific Transformative Weight
# -----------------------------------------------------------------------------

class TransformativeWeightPredictor(nn.Module):
    """
    Independent scalar Transformative Weight predictor.
    """

    def __init__(
        self,
        input_dim,
        hidden_dim,
        name,
    ):
        super().__init__()

        self.name = str(
            name
        )

        self.network = nn.Sequential(
            nn.Linear(
                input_dim,
                hidden_dim,
            ),

            nn.GELU(),

            nn.LayerNorm(
                hidden_dim
            ),

            nn.Linear(
                hidden_dim,
                1,
            ),
        )


    def forward(
        self,
        representation,
    ):

        logits = self.network(
            representation
        )

        return {
            "name":
                self.name,

            "logits":
                logits,

            "values":
                torch.sigmoid(
                    logits
                ),
        }


# -----------------------------------------------------------------------------
# Fixed-dimensional transformative path
# -----------------------------------------------------------------------------

class FixedTransformativePath(nn.Module):
    """
    Factual or psychological architectural transformative path.
    """

    def __init__(
        self,
        representation_dim,
        hidden_dim,
        tw_name,
        dropout=0.1,
    ):
        super().__init__()

        self.representation_dim = int(
            representation_dim
        )

        self.core = nn.Sequential(
            nn.Linear(
                self.representation_dim * 2,
                hidden_dim,
            ),

            nn.GELU(),

            nn.Dropout(
                float(
                    dropout
                )
            ),

            nn.LayerNorm(
                hidden_dim
            ),

            nn.Linear(
                hidden_dim,
                self.representation_dim,
            ),
        )

        self.gate = TransformationGate(
            representation_dim=
                self.representation_dim
        )

        self.tw_predictor = TransformativeWeightPredictor(
            input_dim=
                self.representation_dim * 2,

            hidden_dim=
                hidden_dim,

            name=
                tw_name,
        )


    def forward(
        self,
        representation,
        causal_context,
    ):

        combined = torch.cat(
            [
                representation,
                causal_context,
            ],
            dim=-1,
        )

        transformation = self.core(
            combined
        )

        gated = self.gate(
            representation,
            transformation,
        )

        tw_output = self.tw_predictor(
            combined
        )

        return {
            "transformation":
                transformation,

            "gate":
                gated[
                    "gate"
                ],

            "gated_transformation":
                gated[
                    "gated_transformation"
                ],

            "transformative_weight":
                tw_output,
        }


# -----------------------------------------------------------------------------
# Structured social transformative path
# -----------------------------------------------------------------------------

class SocialTransformativePath(nn.Module):
    """
    Hidden social transformative path preserving structured output semantics.
    """

    def __init__(
        self,
        social_hidden_dim,
        hidden_dim,
        dropout=0.1,
    ):
        super().__init__()

        self.social_hidden_dim = int(
            social_hidden_dim
        )

        self.core = nn.Sequential(
            nn.Linear(
                self.social_hidden_dim * 2,
                hidden_dim,
            ),

            nn.GELU(),

            nn.Dropout(
                float(
                    dropout
                )
            ),

            nn.LayerNorm(
                hidden_dim
            ),
        )

        self.tw_predictor = TransformativeWeightPredictor(
            input_dim=
                self.social_hidden_dim * 2,

            hidden_dim=
                hidden_dim,

            name=
                "TW_S",
        )


    def forward(
        self,
        representation,
        causal_context,
    ):

        combined = torch.cat(
            [
                representation,
                causal_context,
            ],
            dim=-1,
        )

        hidden_transformation = self.core(
            combined
        )

        tw_output = self.tw_predictor(
            combined
        )

        return {
            "hidden_transformation":
                hidden_transformation,

            "structured_transformation":
                None,

            "transformative_weight":
                tw_output,

            "structured_decoding_executed":
                False,
        }


# -----------------------------------------------------------------------------
# Fixed-dimensional recurrent cell
# -----------------------------------------------------------------------------

class FixedRecurrentCell(nn.Module):
    """
    Fixed-dimensional recurrent update.

    Transformative Weight is an input and is not the retention gate.
    """

    def __init__(
        self,
        representation_dim,
        recurrent_dim,
        dropout=0.1,
    ):
        super().__init__()

        self.representation_dim = int(
            representation_dim
        )

        self.recurrent_dim = int(
            recurrent_dim
        )

        input_dim = (
            self.recurrent_dim
            + self.representation_dim
            + self.representation_dim
            + 1
        )

        self.retention_layer = nn.Linear(
            input_dim,
            self.recurrent_dim,
        )

        self.candidate_network = nn.Sequential(
            nn.Linear(
                input_dim,
                self.recurrent_dim,
            ),

            nn.GELU(),

            nn.Dropout(
                float(
                    dropout
                )
            ),

            nn.LayerNorm(
                self.recurrent_dim
            ),

            nn.Linear(
                self.recurrent_dim,
                self.recurrent_dim,
            ),

            nn.Tanh(),
        )


    def initial_state(
        self,
        batch_shape,
        device,
        dtype,
    ):

        return torch.zeros(
            *batch_shape,
            self.recurrent_dim,
            device=device,
            dtype=dtype,
        )


    def forward(
        self,
        previous_state,
        representation,
        gated_transformation,
        transformative_weight,
    ):

        recurrent_input = torch.cat(
            [
                previous_state,
                representation,
                gated_transformation,
                transformative_weight,
            ],
            dim=-1,
        )

        retention_gate = torch.sigmoid(
            self.retention_layer(
                recurrent_input
            )
        )

        candidate_state = self.candidate_network(
            recurrent_input
        )

        current_state = (
            retention_gate
            * previous_state
            +
            (
                1.0
                - retention_gate
            )
            * candidate_state
        )

        return {
            "previous_state":
                previous_state,

            "retention_gate":
                retention_gate,

            "candidate_state":
                candidate_state,

            "current_state":
                current_state,
        }


# -----------------------------------------------------------------------------
# Structured social recurrent cell
# -----------------------------------------------------------------------------

class SocialRecurrentCell(nn.Module):
    """
    Hidden-state recurrent mechanism for structured social representation.
    """

    def __init__(
        self,
        social_hidden_dim,
        transformation_hidden_dim,
        recurrent_dim,
        dropout=0.1,
    ):
        super().__init__()

        self.social_hidden_dim = int(
            social_hidden_dim
        )

        self.transformation_hidden_dim = int(
            transformation_hidden_dim
        )

        self.recurrent_dim = int(
            recurrent_dim
        )

        input_dim = (
            self.recurrent_dim
            + self.social_hidden_dim
            + self.transformation_hidden_dim
            + 1
        )

        self.retention_layer = nn.Linear(
            input_dim,
            self.recurrent_dim,
        )

        self.candidate_network = nn.Sequential(
            nn.Linear(
                input_dim,
                self.recurrent_dim,
            ),

            nn.GELU(),

            nn.Dropout(
                float(
                    dropout
                )
            ),

            nn.LayerNorm(
                self.recurrent_dim
            ),

            nn.Linear(
                self.recurrent_dim,
                self.recurrent_dim,
            ),

            nn.Tanh(),
        )


    def initial_state(
        self,
        batch_shape,
        device,
        dtype,
    ):

        return torch.zeros(
            *batch_shape,
            self.recurrent_dim,
            device=device,
            dtype=dtype,
        )


    def forward(
        self,
        previous_state,
        social_hidden,
        social_transformation_hidden,
        transformative_weight,
    ):

        recurrent_input = torch.cat(
            [
                previous_state,
                social_hidden,
                social_transformation_hidden,
                transformative_weight,
            ],
            dim=-1,
        )

        retention_gate = torch.sigmoid(
            self.retention_layer(
                recurrent_input
            )
        )

        candidate_state = self.candidate_network(
            recurrent_input
        )

        current_state = (
            retention_gate
            * previous_state
            +
            (
                1.0
                - retention_gate
            )
            * candidate_state
        )

        return {
            "previous_state":
                previous_state,

            "retention_gate":
                retention_gate,

            "candidate_state":
                candidate_state,

            "current_state":
                current_state,
        }


# -----------------------------------------------------------------------------
# Group-conditioned residual adapter
# -----------------------------------------------------------------------------

class GroupResidualAdapter(nn.Module):
    """
    Optional residual group-conditioned adapter.
    """

    def __init__(
        self,
        input_dim,
        group_embedding_dim,
        output_dim,
        hidden_dim,
        dropout=0.1,
    ):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(
                input_dim
                + group_embedding_dim,
                hidden_dim,
            ),

            nn.GELU(),

            nn.Dropout(
                float(
                    dropout
                )
            ),

            nn.Linear(
                hidden_dim,
                output_dim,
            ),
        )


    def forward(
        self,
        representation,
        group_embedding,
    ):

        combined = torch.cat(
            [
                representation,
                group_embedding,
            ],
            dim=-1,
        )

        return self.network(
            combined
        )


# -----------------------------------------------------------------------------
# Complete reference architecture
# -----------------------------------------------------------------------------

class MediaAIReferenceModel(nn.Module):
    """
    Executable Notebook 05 reference architecture.

    A concrete pretrained semantic backbone is not selected in Block 3.
    Contextual sentence embeddings enter through the frozen backbone
    interface.

    The model preserves:
        - global textual processing;
        - optional group-conditioned residual adaptation;
        - factual head;
        - psychological head;
        - structured social head;
        - factual, psychological and social transformation;
        - TW_F, TW_P and TW_S;
        - H_F, H_P and H_S recurrence.

    No forward pass, loss or training is executed by this block.
    """

    def __init__(
        self,
    ):
        super().__init__()

        # ---------------------------------------------------------------------
        # Backbone interface
        # ---------------------------------------------------------------------

        self.backbone = FrozenBackboneInterface(
            hidden_dim=
                BACKBONE_HIDDEN_DIM
        )

        # ---------------------------------------------------------------------
        # Confluent conditioning
        # ---------------------------------------------------------------------

        self.confluent = ConfluentConditioningModule(
            input_dim=
                BACKBONE_HIDDEN_DIM,

            hidden_dim=
                CONFLUENT_HIDDEN_DIM,

            group_embedding_dim=
                GROUP_EMBEDDING_DIM,

            dropout=
                DROPOUT_RATE,
        )

        # ---------------------------------------------------------------------
        # Representation heads
        # ---------------------------------------------------------------------

        self.factual_head = FactualHead(
            input_dim=
                CONFLUENT_HIDDEN_DIM,

            hidden_dim=
                HEAD_HIDDEN_DIM,

            dropout=
                DROPOUT_RATE,
        )

        self.psychological_head = PsychologicalHead(
            input_dim=
                CONFLUENT_HIDDEN_DIM,

            hidden_dim=
                HEAD_HIDDEN_DIM,

            dropout=
                DROPOUT_RATE,
        )

        self.social_head = SocialHead(
            input_dim=
                CONFLUENT_HIDDEN_DIM,

            hidden_dim=
                SOCIAL_HIDDEN_DIM,

            dropout=
                DROPOUT_RATE,
        )

        # ---------------------------------------------------------------------
        # Group-conditioned head adapters
        # ---------------------------------------------------------------------

        self.factual_group_adapter = GroupResidualAdapter(
            input_dim=
                FACTUAL_DIM,

            group_embedding_dim=
                GROUP_EMBEDDING_DIM,

            output_dim=
                FACTUAL_DIM,

            hidden_dim=
                HEAD_HIDDEN_DIM,

            dropout=
                DROPOUT_RATE,
        )

        self.psychological_group_adapter = GroupResidualAdapter(
            input_dim=
                PSYCHOLOGICAL_DIM,

            group_embedding_dim=
                GROUP_EMBEDDING_DIM,

            output_dim=
                PSYCHOLOGICAL_DIM,

            hidden_dim=
                HEAD_HIDDEN_DIM,

            dropout=
                DROPOUT_RATE,
        )

        self.social_group_adapter = GroupResidualAdapter(
            input_dim=
                SOCIAL_HIDDEN_DIM,

            group_embedding_dim=
                GROUP_EMBEDDING_DIM,

            output_dim=
                SOCIAL_HIDDEN_DIM,

            hidden_dim=
                SOCIAL_HIDDEN_DIM,

            dropout=
                DROPOUT_RATE,
        )

        # ---------------------------------------------------------------------
        # Transformative mechanism
        # ---------------------------------------------------------------------

        self.factual_transform = FixedTransformativePath(
            representation_dim=
                FACTUAL_DIM,

            hidden_dim=
                TRANSFORMATIVE_HIDDEN_DIM,

            tw_name=
                "TW_F",

            dropout=
                DROPOUT_RATE,
        )

        self.psychological_transform = FixedTransformativePath(
            representation_dim=
                PSYCHOLOGICAL_DIM,

            hidden_dim=
                TRANSFORMATIVE_HIDDEN_DIM,

            tw_name=
                "TW_P",

            dropout=
                DROPOUT_RATE,
        )

        self.social_transform = SocialTransformativePath(
            social_hidden_dim=
                SOCIAL_HIDDEN_DIM,

            hidden_dim=
                TRANSFORMATIVE_HIDDEN_DIM,

            dropout=
                DROPOUT_RATE,
        )

        # ---------------------------------------------------------------------
        # Transformative group adapters
        # ---------------------------------------------------------------------

        self.factual_transform_group_adapter = GroupResidualAdapter(
            input_dim=
                FACTUAL_DIM,

            group_embedding_dim=
                GROUP_EMBEDDING_DIM,

            output_dim=
                FACTUAL_DIM,

            hidden_dim=
                TRANSFORMATIVE_HIDDEN_DIM,

            dropout=
                DROPOUT_RATE,
        )

        self.psychological_transform_group_adapter = GroupResidualAdapter(
            input_dim=
                PSYCHOLOGICAL_DIM,

            group_embedding_dim=
                GROUP_EMBEDDING_DIM,

            output_dim=
                PSYCHOLOGICAL_DIM,

            hidden_dim=
                TRANSFORMATIVE_HIDDEN_DIM,

            dropout=
                DROPOUT_RATE,
        )

        self.social_transform_group_adapter = GroupResidualAdapter(
            input_dim=
                TRANSFORMATIVE_HIDDEN_DIM,

            group_embedding_dim=
                GROUP_EMBEDDING_DIM,

            output_dim=
                TRANSFORMATIVE_HIDDEN_DIM,

            hidden_dim=
                TRANSFORMATIVE_HIDDEN_DIM,

            dropout=
                DROPOUT_RATE,
        )

        # ---------------------------------------------------------------------
        # Recurrent mechanism
        # ---------------------------------------------------------------------

        self.factual_recurrent = FixedRecurrentCell(
            representation_dim=
                FACTUAL_DIM,

            recurrent_dim=
                RECURRENT_FACTUAL_DIM,

            dropout=
                DROPOUT_RATE,
        )

        self.psychological_recurrent = FixedRecurrentCell(
            representation_dim=
                PSYCHOLOGICAL_DIM,

            recurrent_dim=
                RECURRENT_PSYCHOLOGICAL_DIM,

            dropout=
                DROPOUT_RATE,
        )

        self.social_recurrent = SocialRecurrentCell(
            social_hidden_dim=
                SOCIAL_HIDDEN_DIM,

            transformation_hidden_dim=
                TRANSFORMATIVE_HIDDEN_DIM,

            recurrent_dim=
                RECURRENT_SOCIAL_DIM,

            dropout=
                DROPOUT_RATE,
        )

        # ---------------------------------------------------------------------
        # Recurrent group adapters
        # ---------------------------------------------------------------------

        self.factual_recurrent_group_adapter = GroupResidualAdapter(
            input_dim=
                RECURRENT_FACTUAL_DIM,

            group_embedding_dim=
                GROUP_EMBEDDING_DIM,

            output_dim=
                RECURRENT_FACTUAL_DIM,

            hidden_dim=
                RECURRENT_FACTUAL_DIM,

            dropout=
                DROPOUT_RATE,
        )

        self.psychological_recurrent_group_adapter = GroupResidualAdapter(
            input_dim=
                RECURRENT_PSYCHOLOGICAL_DIM,

            group_embedding_dim=
                GROUP_EMBEDDING_DIM,

            output_dim=
                RECURRENT_PSYCHOLOGICAL_DIM,

            hidden_dim=
                RECURRENT_PSYCHOLOGICAL_DIM,

            dropout=
                DROPOUT_RATE,
        )

        self.social_recurrent_group_adapter = GroupResidualAdapter(
            input_dim=
                RECURRENT_SOCIAL_DIM,

            group_embedding_dim=
                GROUP_EMBEDDING_DIM,

            output_dim=
                RECURRENT_SOCIAL_DIM,

            hidden_dim=
                RECURRENT_SOCIAL_DIM,

            dropout=
                DROPOUT_RATE,
        )


    def initial_recurrent_states(
        self,
        batch_shape,
        device,
        dtype,
    ):

        return {
            "H_F":
                self.factual_recurrent.initial_state(
                    batch_shape=
                        batch_shape,

                    device=
                        device,

                    dtype=
                        dtype,
                ),

            "H_P":
                self.psychological_recurrent.initial_state(
                    batch_shape=
                        batch_shape,

                    device=
                        device,

                    dtype=
                        dtype,
                ),

            "H_S":
                self.social_recurrent.initial_state(
                    batch_shape=
                        batch_shape,

                    device=
                        device,

                    dtype=
                        dtype,
                ),
        }


# -----------------------------------------------------------------------------
# Instantiate reference model
# -----------------------------------------------------------------------------

MEDIA_AI_MODEL = MediaAIReferenceModel()

MEDIA_AI_MODEL = MEDIA_AI_MODEL.to(
    device=
        MODEL_DEVICE,

    dtype=
        MODEL_DTYPE,
)

NOTEBOOK_05_MODEL_INSTANTIATED = True


# -----------------------------------------------------------------------------
# Explicit parameter-group registry
# -----------------------------------------------------------------------------

PARAMETER_GROUP_MODULES = OrderedDict(
    [
        (
            "backbone",
            MEDIA_AI_MODEL.backbone,
        ),

        (
            "confluent_shared",
            MEDIA_AI_MODEL.confluent.global_projection,
        ),

        (
            "confluent_group_adapter",
            MEDIA_AI_MODEL.confluent.group_adapter,
        ),

        (
            "factual_head",
            MEDIA_AI_MODEL.factual_head,
        ),

        (
            "factual_group_adapter",
            MEDIA_AI_MODEL.factual_group_adapter,
        ),

        (
            "psychological_head",
            MEDIA_AI_MODEL.psychological_head,
        ),

        (
            "psychological_group_adapter",
            MEDIA_AI_MODEL.psychological_group_adapter,
        ),

        (
            "social_head",
            MEDIA_AI_MODEL.social_head,
        ),

        (
            "social_group_adapter",
            MEDIA_AI_MODEL.social_group_adapter,
        ),

        (
            "factual_transform_core",
            MEDIA_AI_MODEL.factual_transform.core,
        ),

        (
            "psychological_transform_core",
            MEDIA_AI_MODEL.psychological_transform.core,
        ),

        (
            "social_transform_core",
            MEDIA_AI_MODEL.social_transform.core,
        ),

        (
            "factual_transform_gate",
            MEDIA_AI_MODEL.factual_transform.gate,
        ),

        (
            "psychological_transform_gate",
            MEDIA_AI_MODEL.psychological_transform.gate,
        ),

        (
            "TW_F",
            MEDIA_AI_MODEL.factual_transform.tw_predictor,
        ),

        (
            "TW_P",
            MEDIA_AI_MODEL.psychological_transform.tw_predictor,
        ),

        (
            "TW_S",
            MEDIA_AI_MODEL.social_transform.tw_predictor,
        ),

        (
            "factual_transform_group_adapter",
            MEDIA_AI_MODEL.factual_transform_group_adapter,
        ),

        (
            "psychological_transform_group_adapter",
            MEDIA_AI_MODEL.psychological_transform_group_adapter,
        ),

        (
            "social_transform_group_adapter",
            MEDIA_AI_MODEL.social_transform_group_adapter,
        ),

        (
            "factual_recurrent",
            MEDIA_AI_MODEL.factual_recurrent,
        ),

        (
            "psychological_recurrent",
            MEDIA_AI_MODEL.psychological_recurrent,
        ),

        (
            "social_recurrent",
            MEDIA_AI_MODEL.social_recurrent,
        ),

        (
            "factual_recurrent_group_adapter",
            MEDIA_AI_MODEL.factual_recurrent_group_adapter,
        ),

        (
            "psychological_recurrent_group_adapter",
            MEDIA_AI_MODEL.psychological_recurrent_group_adapter,
        ),

        (
            "social_recurrent_group_adapter",
            MEDIA_AI_MODEL.social_recurrent_group_adapter,
        ),
    ]
)


# -----------------------------------------------------------------------------
# Initial parameter policy
# -----------------------------------------------------------------------------
#
# Every parameter group begins frozen.
#
# Validated direct supervision may then explicitly activate only the parameter
# groups required to predict currently eligible direct targets.
# -----------------------------------------------------------------------------

PARAMETER_POLICY = OrderedDict()


for parameter_group_name in PARAMETER_GROUP_MODULES.keys():

    PARAMETER_POLICY[
        parameter_group_name
    ] = {
        "state":
            "frozen",

        "reason":
            (
                "No currently validated direct supervision requires "
                "this parameter group."
            ),

        "direct_supervision_required":
            False,

        "indirect_training_allowed":
            False,

        "activated_in_block":
            None,
    }


# -----------------------------------------------------------------------------
# Explicitly identify conditionally trainable families
# -----------------------------------------------------------------------------

CONDITIONALLY_TRAINABLE_GROUPS = (
    "confluent_shared",
    "confluent_group_adapter",
    "factual_head",
    "factual_group_adapter",
    "psychological_head",
    "psychological_group_adapter",
    "social_head",
    "social_group_adapter",
    "factual_transform_core",
    "psychological_transform_core",
    "social_transform_core",
    "factual_transform_gate",
    "psychological_transform_gate",
    "TW_F",
    "TW_P",
    "TW_S",
    "factual_transform_group_adapter",
    "psychological_transform_group_adapter",
    "social_transform_group_adapter",
    "factual_recurrent",
    "psychological_recurrent",
    "social_recurrent",
    "factual_recurrent_group_adapter",
    "psychological_recurrent_group_adapter",
    "social_recurrent_group_adapter",
)


for parameter_group_name in CONDITIONALLY_TRAINABLE_GROUPS:

    PARAMETER_POLICY[
        parameter_group_name
    ][
        "indirect_training_allowed"
    ] = True


# -----------------------------------------------------------------------------
# Backbone-specific policy
# -----------------------------------------------------------------------------

PARAMETER_POLICY[
    "backbone"
][
    "state"
] = "frozen"

PARAMETER_POLICY[
    "backbone"
][
    "reason"
] = (
    "A concrete pretrained backbone has not yet been selected. "
    "The current textual-representation interface remains frozen."
)

PARAMETER_POLICY[
    "backbone"
][
    "indirect_training_allowed"
] = False


# -----------------------------------------------------------------------------
# Direct-supervision mappings
# -----------------------------------------------------------------------------

DIRECT_SUPERVISION_PARAMETER_MAP = {
    "factual_head": (
        "factual_head",
    ),

    "REV": (
        "psychological_head",
    ),

    "TEV": (
        "psychological_head",
    ),

    "IEV": (
        "psychological_head",
    ),

    "EW": (
        "psychological_head",
    ),

    "actors": (
        "social_head",
    ),

    "groups": (
        "social_head",
    ),

    "memberships": (
        "social_head",
    ),

    "relationships": (
        "social_head",
    ),

    "TW_F": (
        "TW_F",
    ),

    "TW_P": (
        "TW_P",
    ),

    "TW_S": (
        "TW_S",
    ),
}


# -----------------------------------------------------------------------------
# Validate direct-supervision mappings
# -----------------------------------------------------------------------------

UNMAPPED_ELIGIBLE_DIRECT_TARGETS = tuple(
    target_name

    for target_name
    in CURRENT_ELIGIBLE_DIRECT_TARGETS

    if target_name
    not in DIRECT_SUPERVISION_PARAMETER_MAP
)


if UNMAPPED_ELIGIBLE_DIRECT_TARGETS:

    raise ValueError(
        "One or more eligible direct supervision targets have no "
        "parameter-group mapping: "
        f"{UNMAPPED_ELIGIBLE_DIRECT_TARGETS}"
    )


# -----------------------------------------------------------------------------
# Parameter groups justified by current validated supervision
# -----------------------------------------------------------------------------

ELIGIBLE_DIRECT_PARAMETER_GROUPS = tuple(
    dict.fromkeys(
        parameter_group

        for target_name
        in CURRENT_ELIGIBLE_DIRECT_TARGETS

        for parameter_group
        in DIRECT_SUPERVISION_PARAMETER_MAP[
            target_name
        ]
    )
)


EXPECTED_CURRENT_DIRECT_PARAMETER_GROUPS = (
    "psychological_head",
)


if (
    ELIGIBLE_DIRECT_PARAMETER_GROUPS
    != EXPECTED_CURRENT_DIRECT_PARAMETER_GROUPS
):
    raise ValueError(
        "Current direct-supervision parameter mapping is unexpected. "
        f"Expected {EXPECTED_CURRENT_DIRECT_PARAMETER_GROUPS}, "
        f"received {ELIGIBLE_DIRECT_PARAMETER_GROUPS}."
    )


# -----------------------------------------------------------------------------
# Activate parameter groups supported by validated direct supervision
# -----------------------------------------------------------------------------

for parameter_group_name in (
    ELIGIBLE_DIRECT_PARAMETER_GROUPS
):

    PARAMETER_POLICY[
        parameter_group_name
    ][
        "state"
    ] = "trainable"

    PARAMETER_POLICY[
        parameter_group_name
    ][
        "reason"
    ] = (
        "Validated canonical Notebook 03 machine supervision is "
        "available for one or more outputs produced by this parameter "
        "group."
    )

    PARAMETER_POLICY[
        parameter_group_name
    ][
        "direct_supervision_required"
    ] = True

    PARAMETER_POLICY[
        parameter_group_name
    ][
        "activated_in_block"
    ] = NOTEBOOK_05_BLOCK_3


# -----------------------------------------------------------------------------
# Parameter-freezing helper
# -----------------------------------------------------------------------------

def set_module_trainable(
    module,
    trainable,
):
    """
    Apply requires_grad policy to all parameters in a module.
    """

    for parameter in module.parameters():

        parameter.requires_grad = bool(
            trainable
        )


# -----------------------------------------------------------------------------
# Apply parameter policy
# -----------------------------------------------------------------------------

for (
    parameter_group_name,
    module,
) in PARAMETER_GROUP_MODULES.items():

    declared_state = PARAMETER_POLICY[
        parameter_group_name
    ][
        "state"
    ]

    should_be_trainable = (
        declared_state
        == "trainable"
    )

    set_module_trainable(
        module=
            module,

        trainable=
            should_be_trainable,
    )


# -----------------------------------------------------------------------------
# Parameter counting helpers
# -----------------------------------------------------------------------------

def count_parameters(
    module,
):
    """
    Count total, trainable and frozen parameters.
    """

    total = sum(
        parameter.numel()
        for parameter
        in module.parameters()
    )

    trainable = sum(
        parameter.numel()
        for parameter
        in module.parameters()
        if parameter.requires_grad
    )

    frozen = (
        total
        - trainable
    )

    return {
        "total_parameters":
            int(
                total
            ),

        "trainable_parameters":
            int(
                trainable
            ),

        "frozen_parameters":
            int(
                frozen
            ),
    }


# -----------------------------------------------------------------------------
# Build parameter registry
# -----------------------------------------------------------------------------

PARAMETER_REGISTRY = []


for (
    parameter_group_name,
    module,
) in PARAMETER_GROUP_MODULES.items():

    counts = count_parameters(
        module
    )

    policy = PARAMETER_POLICY[
        parameter_group_name
    ]

    registry_record = {
        "parameter_group":
            parameter_group_name,

        "declared_state":
            policy[
                "state"
            ],

        "total_parameters":
            counts[
                "total_parameters"
            ],

        "trainable_parameters":
            counts[
                "trainable_parameters"
            ],

        "frozen_parameters":
            counts[
                "frozen_parameters"
            ],

        "direct_supervision_required":
            policy[
                "direct_supervision_required"
            ],

        "indirect_training_allowed":
            policy[
                "indirect_training_allowed"
            ],

        "activated_in_block":
            policy[
                "activated_in_block"
            ],

        "reason":
            policy[
                "reason"
            ],
    }

    PARAMETER_REGISTRY.append(
        registry_record
    )


PARAMETER_REGISTRY_DF = pd.DataFrame(
    PARAMETER_REGISTRY
)


# -----------------------------------------------------------------------------
# Model-level parameter counts
# -----------------------------------------------------------------------------

MODEL_TOTAL_PARAMETERS = sum(
    parameter.numel()
    for parameter
    in MEDIA_AI_MODEL.parameters()
)


MODEL_TRAINABLE_PARAMETERS = sum(
    parameter.numel()
    for parameter
    in MEDIA_AI_MODEL.parameters()
    if parameter.requires_grad
)


MODEL_FROZEN_PARAMETERS = (
    MODEL_TOTAL_PARAMETERS
    - MODEL_TRAINABLE_PARAMETERS
)


# -----------------------------------------------------------------------------
# Parameter-count consistency
# -----------------------------------------------------------------------------

if (
    MODEL_TOTAL_PARAMETERS
    !=
    MODEL_TRAINABLE_PARAMETERS
    +
    MODEL_FROZEN_PARAMETERS
):
    raise ValueError(
        "Model parameter-count identity failed."
    )


# -----------------------------------------------------------------------------
# Current trainability state
# -----------------------------------------------------------------------------

DIRECT_PARAMETER_GROUPS_ACTIVATED = tuple(
    parameter_group_name

    for (
        parameter_group_name,
        policy,
    )
    in PARAMETER_POLICY.items()

    if policy[
        "state"
    ]
    == "trainable"
)


EXPECTED_TRAINABLE_PARAMETER_GROUPS = (
    "psychological_head",
)


TRAINABLE_PARAMETER_GROUPS_VALID = (
    DIRECT_PARAMETER_GROUPS_ACTIVATED
    == EXPECTED_TRAINABLE_PARAMETER_GROUPS
)


CONDITIONAL_PARAMETER_GROUPS_AVAILABLE = tuple(
    CONDITIONALLY_TRAINABLE_GROUPS
)


# -----------------------------------------------------------------------------
# requires_grad consistency validation
# -----------------------------------------------------------------------------

PARAMETER_POLICY_ERRORS = []


for (
    parameter_group_name,
    module,
) in PARAMETER_GROUP_MODULES.items():

    declared_state = PARAMETER_POLICY[
        parameter_group_name
    ][
        "state"
    ]

    actual_trainable = any(
        parameter.requires_grad
        for parameter
        in module.parameters()
    )

    if (
        declared_state
        == "trainable"
        and not actual_trainable
    ):
        PARAMETER_POLICY_ERRORS.append(
            f"{parameter_group_name}:"
            "declared_trainable_but_frozen"
        )

    if (
        declared_state
        in {
            "frozen",
            "conditionally_trainable",
            "inactive",
        }
        and actual_trainable
    ):
        PARAMETER_POLICY_ERRORS.append(
            f"{parameter_group_name}:"
            "declared_nontrainable_but_requires_grad_true"
        )


if not TRAINABLE_PARAMETER_GROUPS_VALID:
    PARAMETER_POLICY_ERRORS.append(
        "unexpected_trainable_parameter_groups:"
        f"{DIRECT_PARAMETER_GROUPS_ACTIVATED}"
    )


# -----------------------------------------------------------------------------
# Validate psychological-head trainability
# -----------------------------------------------------------------------------

PSYCHOLOGICAL_HEAD_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in MEDIA_AI_MODEL.psychological_head.parameters()
)


PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in MEDIA_AI_MODEL.psychological_head.parameters()
    if parameter.requires_grad
)


PSYCHOLOGICAL_HEAD_FULLY_TRAINABLE = (
    PSYCHOLOGICAL_HEAD_PARAMETER_COUNT
    ==
    PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETER_COUNT
)


if not PSYCHOLOGICAL_HEAD_FULLY_TRAINABLE:
    PARAMETER_POLICY_ERRORS.append(
        "psychological_head_not_fully_trainable"
    )


# -----------------------------------------------------------------------------
# Validate frozen backbone
# -----------------------------------------------------------------------------

BACKBONE_TRAINABLE_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in MEDIA_AI_MODEL.backbone.parameters()
    if parameter.requires_grad
)


BACKBONE_FULLY_FROZEN = (
    BACKBONE_TRAINABLE_PARAMETER_COUNT
    == 0
)


if not BACKBONE_FULLY_FROZEN:
    PARAMETER_POLICY_ERRORS.append(
        "backbone_not_fully_frozen"
    )


# -----------------------------------------------------------------------------
# Validate all non-psychological-head groups remain frozen
# -----------------------------------------------------------------------------

UNEXPECTED_NONZERO_TRAINABLE_GROUPS = tuple(
    record[
        "parameter_group"
    ]

    for record
    in PARAMETER_REGISTRY

    if (
        record[
            "parameter_group"
        ]
        != "psychological_head"
        and record[
            "trainable_parameters"
        ]
        > 0
    )
)


if UNEXPECTED_NONZERO_TRAINABLE_GROUPS:
    PARAMETER_POLICY_ERRORS.append(
        "unexpected_trainable_nonpsychological_groups:"
        f"{UNEXPECTED_NONZERO_TRAINABLE_GROUPS}"
    )


# -----------------------------------------------------------------------------
# Architecture component validation
# -----------------------------------------------------------------------------

REQUIRED_MODEL_COMPONENTS = (
    "backbone",
    "confluent",
    "factual_head",
    "psychological_head",
    "social_head",
    "factual_transform",
    "psychological_transform",
    "social_transform",
    "factual_recurrent",
    "psychological_recurrent",
    "social_recurrent",
)


missing_model_components = [
    component_name

    for component_name
    in REQUIRED_MODEL_COMPONENTS

    if not hasattr(
        MEDIA_AI_MODEL,
        component_name,
    )
]


if missing_model_components:
    PARAMETER_POLICY_ERRORS.append(
        "missing_model_components:"
        + ",".join(
            missing_model_components
        )
    )


# -----------------------------------------------------------------------------
# Transformative-weight independence validation
# -----------------------------------------------------------------------------

tw_parameter_ids = {
    "TW_F":
        {
            id(
                parameter
            )
            for parameter
            in MEDIA_AI_MODEL
            .factual_transform
            .tw_predictor
            .parameters()
        },

    "TW_P":
        {
            id(
                parameter
            )
            for parameter
            in MEDIA_AI_MODEL
            .psychological_transform
            .tw_predictor
            .parameters()
        },

    "TW_S":
        {
            id(
                parameter
            )
            for parameter
            in MEDIA_AI_MODEL
            .social_transform
            .tw_predictor
            .parameters()
        },
}


if (
    tw_parameter_ids[
        "TW_F"
    ]
    &
    tw_parameter_ids[
        "TW_P"
    ]
):
    PARAMETER_POLICY_ERRORS.append(
        "TW_F_and_TW_P_share_parameters"
    )


if (
    tw_parameter_ids[
        "TW_F"
    ]
    &
    tw_parameter_ids[
        "TW_S"
    ]
):
    PARAMETER_POLICY_ERRORS.append(
        "TW_F_and_TW_S_share_parameters"
    )


if (
    tw_parameter_ids[
        "TW_P"
    ]
    &
    tw_parameter_ids[
        "TW_S"
    ]
):
    PARAMETER_POLICY_ERRORS.append(
        "TW_P_and_TW_S_share_parameters"
    )


TRANSFORMATIVE_WEIGHTS_PARAMETER_INDEPENDENT = (
    not any(
        "share_parameters"
        in error
        for error
        in PARAMETER_POLICY_ERRORS
    )
)


# -----------------------------------------------------------------------------
# Block 3 execution boundary
# -----------------------------------------------------------------------------

NOTEBOOK_05_MODEL_INSTANTIATED = True

NOTEBOOK_05_EXECUTABLE_ARCHITECTURE_AVAILABLE = True

NOTEBOOK_05_PARAMETER_POLICY_FINALISED = True

NOTEBOOK_05_TRAINABLE_PARAMETER_GROUPS_ACTIVATED = bool(
    DIRECT_PARAMETER_GROUPS_ACTIVATED
)

NOTEBOOK_05_FROZEN_PARAMETER_GROUPS_FINALISED = True

NOTEBOOK_05_BACKBONE_AUTOMATICALLY_TRAINABLE = False

NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED = False

NOTEBOOK_05_OPTIMIZER_CREATED = False

NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED = False

NOTEBOOK_05_LOSS_CALCULATED = False

NOTEBOOK_05_TRAINING_EXECUTED = False

NOTEBOOK_05_CHECKPOINT_SELECTED = False

NOTEBOOK_05_ABLATION_EXECUTED = False

NOTEBOOK_05_EVALUATION_EXECUTED = False

NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED = False


# -----------------------------------------------------------------------------
# Block 3 methodological validation
# -----------------------------------------------------------------------------

if NOTEBOOK_05_BACKBONE_AUTOMATICALLY_TRAINABLE:
    PARAMETER_POLICY_ERRORS.append(
        "backbone_incorrectly_automatic_trainable"
    )


if not NOTEBOOK_05_TRAINABLE_PARAMETER_GROUPS_ACTIVATED:
    PARAMETER_POLICY_ERRORS.append(
        "validated_direct_supervision_did_not_activate_parameter_group"
    )


if NOTEBOOK_05_OPTIMIZER_CREATED:
    PARAMETER_POLICY_ERRORS.append(
        "optimizer_incorrectly_created_in_block_3"
    )


if NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED:
    PARAMETER_POLICY_ERRORS.append(
        "forward_pass_incorrectly_executed_in_block_3"
    )


if NOTEBOOK_05_LOSS_CALCULATED:
    PARAMETER_POLICY_ERRORS.append(
        "loss_incorrectly_calculated_in_block_3"
    )


if NOTEBOOK_05_TRAINING_EXECUTED:
    PARAMETER_POLICY_ERRORS.append(
        "training_incorrectly_executed_in_block_3"
    )


if NOTEBOOK_05_EVALUATION_EXECUTED:
    PARAMETER_POLICY_ERRORS.append(
        "evaluation_incorrectly_executed_in_block_3"
    )


NOTEBOOK_05_BLOCK_3_VALID = (
    len(
        PARAMETER_POLICY_ERRORS
    )
    == 0
)


if not NOTEBOOK_05_BLOCK_3_VALID:
    raise ValueError(
        "Notebook 05 Block 3 model/parameter-policy "
        "validation failed: "
        f"{PARAMETER_POLICY_ERRORS}"
    )


# -----------------------------------------------------------------------------
# Block 3 completion state
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_3_COMPLETE = True


# -----------------------------------------------------------------------------
# Block 3 summary
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_3_SUMMARY = {
    "block":
        NOTEBOOK_05_BLOCK_3,

    "block_name":
        NOTEBOOK_05_BLOCK_3_NAME,

    "model_implementation_version":
        MODEL_IMPLEMENTATION_VERSION,

    "parameter_policy_version":
        PARAMETER_POLICY_VERSION,

    "instantiated_at_utc":
        MODEL_INSTANTIATED_AT_UTC,

    "device":
        str(
            MODEL_DEVICE
        ),

    "dtype":
        str(
            MODEL_DTYPE
        ),

    "backbone_hidden_dim":
        BACKBONE_HIDDEN_DIM,

    "backbone_concrete_model_loaded":
        False,

    "model_instantiated":
        NOTEBOOK_05_MODEL_INSTANTIATED,

    "validated_targets":
        CURRENT_VALIDATED_TARGETS,

    "eligible_direct_targets":
        CURRENT_ELIGIBLE_DIRECT_TARGETS,

    "block_2_active_optimisation_targets":
        CURRENT_ACTIVE_DIRECT_TARGETS,

    "total_parameters":
        int(
            MODEL_TOTAL_PARAMETERS
        ),

    "trainable_parameters":
        int(
            MODEL_TRAINABLE_PARAMETERS
        ),

    "frozen_parameters":
        int(
            MODEL_FROZEN_PARAMETERS
        ),

    "direct_parameter_groups_activated":
        DIRECT_PARAMETER_GROUPS_ACTIVATED,

    "trainable_parameter_groups_valid":
        TRAINABLE_PARAMETER_GROUPS_VALID,

    "psychological_head_fully_trainable":
        PSYCHOLOGICAL_HEAD_FULLY_TRAINABLE,

    "backbone_fully_frozen":
        BACKBONE_FULLY_FROZEN,

    "conditional_parameter_groups":
        CONDITIONAL_PARAMETER_GROUPS_AVAILABLE,

    "TW_parameter_independence":
        TRANSFORMATIVE_WEIGHTS_PARAMETER_INDEPENDENT,

    "optimizer_created":
        NOTEBOOK_05_OPTIMIZER_CREATED,

    "forward_pass_executed":
        NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED,

    "loss_calculated":
        NOTEBOOK_05_LOSS_CALCULATED,

    "training_executed":
        NOTEBOOK_05_TRAINING_EXECUTED,

    "block_valid":
        NOTEBOOK_05_BLOCK_3_VALID,

    "block_complete":
        NOTEBOOK_05_BLOCK_3_COMPLETE,
}


# -----------------------------------------------------------------------------
# Compact parameter-registry view
# -----------------------------------------------------------------------------

PARAMETER_REGISTRY_VIEW_COLUMNS = [
    "parameter_group",
    "declared_state",
    "total_parameters",
    "trainable_parameters",
    "frozen_parameters",
    "direct_supervision_required",
    "indirect_training_allowed",
]


PARAMETER_REGISTRY_VIEW = (
    PARAMETER_REGISTRY_DF[
        PARAMETER_REGISTRY_VIEW_COLUMNS
    ]
    .copy()
)


# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------

print("=" * 72)

print(
    "Media AI — Notebook 05, Block 3: "
    "Model Instantiation and Parameter-Freezing Policy"
)

print("=" * 72)


print(
    f"Implementation version       : "
    f"{MODEL_IMPLEMENTATION_VERSION}"
)

print(
    f"Parameter policy version     : "
    f"{PARAMETER_POLICY_VERSION}"
)

print(
    f"Device                       : "
    f"{MODEL_DEVICE}"
)

print(
    f"Numerical precision          : "
    f"{MODEL_DTYPE}"
)

print(
    f"Mixed precision              : "
    f"{MIXED_PRECISION_ENABLED}"
)


print("-" * 72)

print(
    "Executable architecture"
)

print(
    f"Model instantiated           : "
    f"{NOTEBOOK_05_MODEL_INSTANTIATED}"
)

print(
    f"Executable architecture      : "
    f"{NOTEBOOK_05_EXECUTABLE_ARCHITECTURE_AVAILABLE}"
)

print(
    f"Concrete backbone loaded     : "
    f"{False}"
)

print(
    f"Backbone interface dimension : "
    f"{BACKBONE_HIDDEN_DIM}"
)

print(
    f"Factual dimensions           : "
    f"{FACTUAL_DIM}"
)

print(
    f"Psychological dimensions     : "
    f"{PSYCHOLOGICAL_DIM}"
)

print(
    f"Social structured components : "
    f"{len(SOCIAL_COMPONENTS)}"
)


print("-" * 72)

print(
    "Recurrent dimensions"
)

print(
    f"H_F internal dimensions      : "
    f"{RECURRENT_FACTUAL_DIM}"
)

print(
    f"H_P internal dimensions      : "
    f"{RECURRENT_PSYCHOLOGICAL_DIM}"
)

print(
    f"H_S internal dimensions      : "
    f"{RECURRENT_SOCIAL_DIM}"
)


print("-" * 72)

print(
    "Supervision state"
)

print(
    f"Validated direct targets     : "
    f"{CURRENT_VALIDATED_TARGET_COUNT}"
)

print(
    f"Eligible direct targets      : "
    f"{CURRENT_ELIGIBLE_DIRECT_TARGET_COUNT}"
)

print(
    f"Active optimisation targets  : "
    f"{CURRENT_ACTIVE_DIRECT_TARGET_COUNT}"
)

print(
    f"Indirect signal targets      : "
    f"{CURRENT_INDIRECT_TARGET_COUNT}"
)

print(
    f"Direct supervision available : "
    f"{CURRENT_DIRECT_SUPERVISION_AVAILABLE}"
)

print(
    f"Indirect signal available    : "
    f"{CURRENT_INDIRECT_SIGNAL_AVAILABLE}"
)

print(
    f"Eligible target families     : "
    f"{CURRENT_ELIGIBLE_DIRECT_TARGETS}"
)


print("-" * 72)

print(
    "Parameter policy"
)

print(
    f"Registered parameter groups  : "
    f"{len(PARAMETER_GROUP_MODULES)}"
)

print(
    f"Eligible parameter groups    : "
    f"{ELIGIBLE_DIRECT_PARAMETER_GROUPS}"
)

print(
    f"Activated parameter groups   : "
    f"{DIRECT_PARAMETER_GROUPS_ACTIVATED}"
)

print(
    f"Conditionally trainable      : "
    f"{len(CONDITIONAL_PARAMETER_GROUPS_AVAILABLE)}"
)

print(
    f"Psychological head trainable : "
    f"{PSYCHOLOGICAL_HEAD_FULLY_TRAINABLE}"
)

print(
    f"Backbone fully frozen        : "
    f"{BACKBONE_FULLY_FROZEN}"
)

print(
    f"Trainable groups valid       : "
    f"{TRAINABLE_PARAMETER_GROUPS_VALID}"
)


print("-" * 72)

print(
    "Parameter counts"
)

print(
    f"Total model parameters       : "
    f"{MODEL_TOTAL_PARAMETERS:,}"
)

print(
    f"Trainable parameters         : "
    f"{MODEL_TRAINABLE_PARAMETERS:,}"
)

print(
    f"Frozen parameters            : "
    f"{MODEL_FROZEN_PARAMETERS:,}"
)


print("-" * 72)

print(
    "Transformative Weight independence"
)

print(
    f"TW_F independent             : "
    f"{TRANSFORMATIVE_WEIGHTS_PARAMETER_INDEPENDENT}"
)

print(
    f"TW_P independent             : "
    f"{TRANSFORMATIVE_WEIGHTS_PARAMETER_INDEPENDENT}"
)

print(
    f"TW_S independent             : "
    f"{TRANSFORMATIVE_WEIGHTS_PARAMETER_INDEPENDENT}"
)

print(
    f"TW predictors shared         : "
    f"{not TRANSFORMATIVE_WEIGHTS_PARAMETER_INDEPENDENT}"
)


print("-" * 72)

print(
    "Training boundary"
)

print(
    f"Parameter policy finalised   : "
    f"{NOTEBOOK_05_PARAMETER_POLICY_FINALISED}"
)

print(
    f"Trainable groups activated   : "
    f"{NOTEBOOK_05_TRAINABLE_PARAMETER_GROUPS_ACTIVATED}"
)

print(
    f"Frozen groups finalised      : "
    f"{NOTEBOOK_05_FROZEN_PARAMETER_GROUPS_FINALISED}"
)

print(
    f"Training data constructed    : "
    f"{NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED}"
)

print(
    f"Optimizer created            : "
    f"{NOTEBOOK_05_OPTIMIZER_CREATED}"
)

print(
    f"Forward pass executed        : "
    f"{NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_05_LOSS_CALCULATED}"
)

print(
    f"Training executed            : "
    f"{NOTEBOOK_05_TRAINING_EXECUTED}"
)

print(
    f"Evaluation executed          : "
    f"{NOTEBOOK_05_EVALUATION_EXECUTED}"
)


print("-" * 72)

print(
    "Execution state"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_05_BLOCK_3_VALID}"
)

print(
    f"Block 3 complete             : "
    f"{NOTEBOOK_05_BLOCK_3_COMPLETE}"
)


print("=" * 72)


print(
    "Media AI reference architecture instantiated successfully."
)

print(
    "The executable architecture is reconstructed independently inside "
    "Notebook 05 rather than relying on Notebook 04 runtime memory."
)

print(
    "The persisted Notebook 04 handover remains the semantic "
    "architecture contract."
)

print(
    "A concrete pretrained semantic backbone has not yet been selected "
    "or loaded."
)

print(
    "The textual-representation interface remains frozen."
)

print(
    "Validated canonical machine supervision is currently available "
    "for REV, TEV, IEV and EW."
)

print(
    "REV, TEV, IEV and EW directly justify trainability of the "
    "psychological-head parameter group."
)

print(
    "The psychological head is therefore the only trainable parameter "
    "group under the current direct-supervision policy."
)

print(
    "The factual head remains frozen because Notebook 03 factological "
    "annotations have not been automatically equated with the validated "
    "ten-dimensional architectural factual representation."
)

print(
    "The social head remains frozen because no validated structured "
    "social supervision is currently available."
)

print(
    "Architectural transformation modules remain frozen because TEV is "
    "not architectural transformation supervision."
)

print(
    "TW_F, TW_P and TW_S remain frozen because no independent validated "
    "Transformative Weight supervision is currently available."
)

print(
    "H_F, H_P and H_S remain frozen because no direct recurrent-state "
    "supervision or explicitly activated indirect objective is available."
)

print(
    "Target eligibility and parameter trainability do not themselves "
    "constitute loss activation or optimisation."
)

print(
    "No optimiser has been created."
)

print(
    "No forward pass, loss calculation, optimisation, training or "
    "evaluation has been executed."
)

print(
    "Block 4 may proceed to Training Dataset and Sequential "
    "Batch Construction."
)


# -----------------------------------------------------------------------------
# Display compact parameter registry
# -----------------------------------------------------------------------------

display(
    PARAMETER_REGISTRY_VIEW
)

========================================================================
Media AI — Notebook 05, Block 3: Model Instantiation and Parameter-Freezing Policy
========================================================================
Implementation version       : 1.1
Parameter policy version     : 1.1
Device                       : cpu
Numerical precision          : torch.float32
Mixed precision              : False
------------------------------------------------------------------------
Executable architecture
Model instantiated           : True
Executable architecture      : True
Concrete backbone loaded     : False
Backbone interface dimension : 768
Factual dimensions           : 10
Psychological dimensions     : 34
Social structured components : 4
------------------------------------------------------------------------
Recurrent dimensions
H_F internal dimensions      : 64
H_P internal dimensions      : 96
H_S internal dimensions      : 64
------------------------------------------------------------------------
Supervision state
Validated direct targets     : 4
Eligible direct targets      : 4
Active optimisation targets  : 0
Indirect signal targets      : 0
Direct supervision available : True
Indirect signal available    : False
Eligible target families     : ('REV', 'TEV', 'IEV', 'EW')
------------------------------------------------------------------------
Parameter policy
Registered parameter groups  : 26
Eligible parameter groups    : ('psychological_head',)
Activated parameter groups   : ('psychological_head',)
Conditionally trainable      : 25
Psychological head trainable : True
Backbone fully frozen        : True
Trainable groups valid       : True
------------------------------------------------------------------------
Parameter counts
Total model parameters       : 1,494,951
Trainable parameters         : 37,538
Frozen parameters            : 1,457,413
------------------------------------------------------------------------
Transformative Weight independence
TW_F independent             : True
TW_P independent             : True
TW_S independent             : True
TW predictors shared         : False
------------------------------------------------------------------------
Training boundary
Parameter policy finalised   : True
Trainable groups activated   : True
Frozen groups finalised      : True
Training data constructed    : False
Optimizer created            : False
Forward pass executed        : False
Loss calculated              : False
Training executed            : False
Evaluation executed          : False
------------------------------------------------------------------------
Execution state
Block valid                  : True
Block 3 complete             : True
========================================================================
Media AI reference architecture instantiated successfully.
The executable architecture is reconstructed independently inside Notebook 05 rather than relying on Notebook 04 runtime memory.
The persisted Notebook 04 handover remains the semantic architecture contract.
A concrete pretrained semantic backbone has not yet been selected or loaded.
The textual-representation interface remains frozen.
Validated canonical machine supervision is currently available for REV, TEV, IEV and EW.
REV, TEV, IEV and EW directly justify trainability of the psychological-head parameter group.
The psychological head is therefore the only trainable parameter group under the current direct-supervision policy.
The factual head remains frozen because Notebook 03 factological annotations have not been automatically equated with the validated ten-dimensional architectural factual representation.
The social head remains frozen because no validated structured social supervision is currently available.
Architectural transformation modules remain frozen because TEV is not architectural transformation supervision.
TW_F, TW_P and TW_S remain frozen because no independent validated Transformative Weight supervision is currently available.
H_F, H_P and H_S remain frozen because no direct recurrent-state supervision or explicitly activated indirect objective is available.
Target eligibility and parameter trainability do not themselves constitute loss activation or optimisation.
No optimiser has been created.
No forward pass, loss calculation, optimisation, training or evaluation has been executed.
Block 4 may proceed to Training Dataset and Sequential Batch Construction.

,parameter_group,declared_state,total_parameters,trainable_parameters,frozen_parameters,direct_supervision_required,indirect_training_allowed
0,backbone,frozen,590592,0,590592,False,False
1,confluent_shared,frozen,197376,0,197376,False,True
2,confluent_group_adapter,frozen,147968,0,147968,False,True
3,factual_head,frozen,34442,0,34442,False,True
4,factual_group_adapter,frozen,10890,0,10890,False,True
5,psychological_head,trainable,37538,37538,0,True,True
6,psychological_group_adapter,frozen,17058,0,17058,False,True
7,social_head,frozen,99200,0,99200,False,True
8,social_group_adapter,frozen,41216,0,41216,False,True
9,factual_transform_core,frozen,4234,0,4234,False,True
10,psychological_transform_core,frozen,13474,0,13474,False,True
11,social_transform_core,frozen,33152,0,33152,False,True
12,factual_transform_gate,frozen,110,0,110,False,True
13,psychological_transform_gate,frozen,1190,0,1190,False,True
14,TW_F,frozen,3073,0,3073,False,True
15,TW_P,frozen,9217,0,9217,False,True
16,TW_S,frozen,33281,0,33281,False,True
17,factual_transform_group_adapter,frozen,10890,0,10890,False,True
18,psychological_transform_group_adapter,frozen,17058,0,17058,False,True
19,social_transform_group_adapter,frozen,41216,0,41216,False,True
20,factual_recurrent,frozen,15296,0,15296,False,True
21,psychological_recurrent,frozen,41376,0,41376,False,True
22,social_recurrent,frozen,45504,0,45504,False,True
23,factual_recurrent_group_adapter,frozen,12416,0,12416,False,True
24,psychological_recurrent_group_adapter,frozen,24768,0,24768,False,True
25,social_recurrent_group_adapter,frozen,12416,0,12416,False,True

## Block 4 — Training Dataset and Sequential Batch Construction

### Purpose

This block defines the **training dataset and sequential batch structure** used by the Media AI architecture.

The architecture operates at sentence level while preserving sequential dependencies within each article.

The training representation must therefore retain the relationship:

$$
\text{article}
\rightarrow
\text{ordered sentences}
\rightarrow
\text{sentence-level model inputs and targets}
$$

The dataset must not treat sentences from independent articles as one continuous sequence.

This block constructs the data-side interface required by the architecture defined in Notebook 04 and instantiated in Block 3.

It does not activate model parameters.

It does not create an optimiser.

It does not execute a model forward pass.

It does not calculate training loss.

It does not perform optimisation.

---

### Training unit

The fundamental modelling unit remains the **sentence**.

For article \(a\), let:

$$
\mathcal{A}_a
=
\left(
s_{a,1},
s_{a,2},
\ldots,
s_{a,T_a}
\right)
$$

where \(T_a\) is the number of ordered sentences in article \(a\).

Each sentence must retain at minimum:

- article identity;
- sentence identity;
- sentence position;
- sentence text;
- source-record linkage;
- sequence boundary information;
- supervision availability.

The original sentence order must be preserved.

---

### Article sequence

Sentence order is an architectural requirement rather than a presentation preference.

For each article:

$$
s_{a,1}
\prec
s_{a,2}
\prec
\cdots
\prec
s_{a,T_a}
$$

where \(\prec\) denotes the original textual order.

Reordering sentences would alter the causal context available to the transformative and recurrent mechanisms and therefore constitutes a different experimental input.

---

### Article boundaries

Independent articles define independent recurrent sequences.

For articles \(a\) and \(b\):

$$
a \neq b
\Rightarrow
H^{q}_{b,0}
\neq
H^{q}_{a,T_a}
$$

for representation space:

$$
q \in \{F,P,S\}
$$

The final recurrent state of one article must therefore not initialise the next independent article.

The default initial-state policy remains the neutral zero state defined by the recurrent architecture.

---

### Cross-article carry

Cross-article recurrent carry is prohibited in the reference configuration.

Therefore:

$$
H^{q}_{a,0}
=
\mathbf{0}
$$

for each independent article \(a\), unless a later explicitly defined experiment uses another validated initial-state policy.

This prevents unrelated articles from creating artificial sequential dependencies.

---

### Causal sentence context

The sequential training structure must preserve the causal restriction established in Notebook 04.

For sentence \(s_{a,t}\), the model may depend on:

$$
s_{a,1:t}
$$

but not on:

$$
s_{a,t+1:T_a}
$$

through the transformative or recurrent state update.

Future sentence information must not be introduced through batching, padding, masking or target construction.

---

### Sentence representation input

Each sentence requires a model-side textual representation input.

Block 3 currently defines an explicit frozen backbone interface rather than a selected pretrained semantic backbone.

Therefore the dataset contract distinguishes between:

- raw sentence text;
- contextual sentence representation;
- representation availability.

Let the contextual textual representation of sentence \(s_{a,t}\) be:

$$
X_{a,t}
\in
\mathbb{R}^{d_B}
$$

where the current Block 3 interface specifies:

$$
d_B = 768
$$

The value \(768\) is an implementation-interface dimension and must not be interpreted as a scientific property of the Media AI representation ontology.

---

### Backbone boundary

Block 4 must not fabricate contextual sentence embeddings.

If a concrete semantic backbone has not yet been selected and executed, the contextual representation must remain explicitly unavailable.

Therefore:

$$
X_{a,t}
=
\varnothing
$$

when no validated backbone representation exists.

Missing representations must not be replaced by arbitrary random vectors, zero vectors or pseudo-embeddings for training.

Synthetic tensors may later be used only for explicit structural forward-validation tests and must remain distinct from training data.

---

### Dataset record

The canonical sentence-level training record should preserve at minimum:

- `article_id`;
- `sentence_id`;
- `sentence_index`;
- `sentence_text`;
- `sequence_length`;
- `article_start`;
- `article_end`;
- `textual_representation`;
- `textual_representation_available`;
- target values where available;
- target masks;
- source linkage.

Additional audit metadata may be retained without changing the model contract.

---

### Sequence index

Sentence position must be represented explicitly.

For an article containing \(T_a\) sentences:

$$
t
\in
\{0,\ldots,T_a-1\}
$$

may be used as the computational sentence index.

The index must be monotonic within each article.

Duplicate or missing sequence positions must be treated as dataset-integrity failures unless explicitly justified by the source representation.

---

### Sequence length

Each sentence record must retain the total sentence count of its article:

$$
L_{a,t}=T_a
$$

for all sentences belonging to article \(a\).

This allows sequence validation and boundary construction without inferring article length from batch position.

---

### Boundary indicators

Two explicit boundary indicators should be constructed.

For sentence position \(t\):

$$
B^{start}_{a,t}
=
\mathbb{1}[t=0]
$$

and:

$$
B^{end}_{a,t}
=
\mathbb{1}[t=T_a-1]
$$

These indicators make article resets auditable.

They must be derived from validated article structure rather than inferred from arbitrary batch boundaries.

---

### Supervision attachment

The Block 2 supervision inventory remains authoritative for target availability.

For target family \(k\), define:

$$
Y^{(k)}_{a,t}
$$

as the target value when validated supervision exists.

Define its supervision mask as:

$$
M^{(k)}_{a,t}
\in
\{0,1\}
$$

where:

$$
M^{(k)}_{a,t}=1
$$

means that the target is available and admissible for the corresponding objective.

If supervision is unavailable:

$$
M^{(k)}_{a,t}=0
$$

The target must then contribute nothing to the corresponding supervised loss.

---

### Missing supervision

Missing supervision remains distinct from both zero and negative evidence.

Therefore:

$$
M^{(k)}_{a,t}=0
\not\Rightarrow
Y^{(k)}_{a,t}=0
$$

and:

$$
M^{(k)}_{a,t}=0
\not\Rightarrow
Y^{(k)}_{a,t}=\text{negative}
$$

Unavailable targets should remain explicitly unavailable.

They must not be converted into pseudo-negative observations merely to produce a dense target tensor.

---

### Current supervision state

Block 2 established that no direct validated supervision target is currently active.

Consequently, the initial Block 4 dataset may contain valid sentence sequences while all direct supervision masks remain inactive.

Conceptually:

$$
\sum_{a,t} M^{(k)}_{a,t}=0
$$

for every currently unavailable target family \(k\).

This does not make the dataset invalid.

It means that the dataset is structurally usable but is not yet authorised for supervised optimisation of those targets.

---

### Factual target structure

The factual target preserves the ten-dimensional factual ontology defined in Notebook 04.

When available:

$$
Y^{F}_{a,t}
\in
\mathbb{R}^{10}
$$

The factual target must remain distinct from externally verified truth.

Its supervision mask must preserve the availability of the factual target without assuming that unannotated factual dimensions are zero.

---

### Psychological target structure

The Psychological State Vector remains:

$$
PSV_{a,t}
=
\left[
REV_{a,t},
TEV_{a,t},
IEV_{a,t},
EW_{a,t}
\right]
$$

with:

$$
REV_{a,t}
\in
[0,1]^{11}
$$

$$
TEV_{a,t}
\in
[-1,1]^{11}
$$

$$
IEV_{a,t}
\in
[0,1]^{11}
$$

and:

$$
EW_{a,t}
\in
[0,1]
$$

REV, TEV, IEV and EW remain separate supervision families and therefore require separate availability masks.

Availability of one family must not imply availability of the others.

---

### Social target structure

The social representation remains structured and variable-dimensional.

For sentence \(s_{a,t}\), the social target may contain:

$$
Y^{S}_{a,t}
=
\left(
A_{a,t},
G_{a,t},
M_{a,t},
R_{a,t}
\right)
$$

where:

- \(A_{a,t}\) represents actors;
- \(G_{a,t}\) represents groups;
- \(M_{a,t}\) represents memberships;
- \(R_{a,t}\) represents relationships.

These structures must not be forced into a fixed-dimensional target solely for batching convenience.

Structured supervision masks must preserve whether each social component is actually annotated.

---

### Transformative Weight targets

The three Transformative Weights remain independent:

$$
TW^{F}_{a,t},
\qquad
TW^{P}_{a,t},
\qquad
TW^{S}_{a,t}
$$

Each requires an independent supervision mask:

$$
M^{TW_F}_{a,t},
\qquad
M^{TW_P}_{a,t},
\qquad
M^{TW_S}_{a,t}
$$

Availability of one Transformative Weight target must not activate the others.

Transformative Weight must not be inferred automatically from mathematical transformation magnitude.

---

### Transformative and recurrent supervision

Direct architectural transformation targets and direct recurrent-state targets remain unavailable unless independently validated.

The dataset must therefore preserve their unavailable state rather than manufacture targets from internal model quantities.

In particular:

$$
H^{q}_{a,t}
$$

is an internal recurrent state and must not automatically become its own training target.

Similarly, an architectural transformation output must not automatically supervise itself.

---

### Batch structure

A training batch may contain multiple articles.

However, article sequences must remain distinguishable within the batch.

Let batch \(b\) contain articles:

$$
\mathcal{B}_b
=
\{
\mathcal{A}_{a_1},
\ldots,
\mathcal{A}_{a_n}
\}
$$

The batch representation must preserve:

- article membership;
- within-article sentence order;
- sequence length;
- article boundaries;
- valid sentence positions;
- target masks.

Batch construction must not create recurrent connections between different articles.

---

### Variable-length sequences

Articles naturally contain different numbers of sentences.

The batch contract must therefore support variable sequence lengths.

If tensor batching requires padding, define:

$$
P_{a,t}
\in
\{0,1\}
$$

where:

$$
P_{a,t}=1
$$

indicates a valid sentence position and:

$$
P_{a,t}=0
$$

indicates padding.

Padding must never be interpreted as a sentence.

---

### Padding mask

The sequence padding mask must prevent padded positions from contributing to:

- representation processing where inappropriate;
- supervised loss;
- recurrent state updates;
- evaluation metrics.

Therefore, for padded position \(t\):

$$
P_{a,t}=0
\Rightarrow
\text{no valid sentence update}
$$

The recurrent state should remain unchanged across padded positions.

---

### Supervision mask and padding mask

Target availability and sequence validity are separate concepts.

For target family \(k\), the effective optimisation mask is:

$$
M^{(k,eff)}_{a,t}
=
P_{a,t}
\cdot
M^{(k)}_{a,t}
$$

A sentence may therefore be structurally valid while lacking supervision for a particular target.

Conversely, no supervision may be used at a padded position.

---

### Group-conditioned inputs

The global representation path remains mandatory.

Group-conditioned inputs remain optional.

The dataset must therefore support:

- global sentence input without group conditioning;
- optional validated group-conditioned input.

Absence of a group-conditioned input must not invalidate the global sentence record.

---

### Group identity boundary

Concrete group identities are not predefined by the architecture.

Therefore Block 4 must not create a closed arbitrary group vocabulary merely to satisfy tensor batching.

Where validated group information exists, it should remain linked to its structured social representation.

Where it does not exist, group-conditioned inputs remain unavailable.

---

### No self-confirming group construction

Model-predicted groups must not automatically be fed back as validated group-conditioned training inputs.

Such a procedure could create a self-confirming route:

$$
\text{predicted group}
\rightarrow
\text{group-conditioned representation}
\rightarrow
\text{reinforced predicted group}
$$

Group-conditioned training inputs therefore require an independently admissible source or a separately defined experimental protocol.

---

### Train, validation and test separation

Dataset partitioning must occur at the **article level**, not by randomly splitting individual sentences.

If sentences from one article appeared in both training and evaluation sets, contextual and stylistic leakage could occur.

Therefore, for article \(a\):

$$
a
\in
\{
Train,
Validation,
Test
\}
$$

with exactly one partition assignment.

All sentences belonging to article \(a\) inherit that assignment.

---

### Partition disjointness

The article partitions must satisfy:

$$
Train
\cap
Validation
=
\varnothing
$$

$$
Train
\cap
Test
=
\varnothing
$$

$$
Validation
\cap
Test
=
\varnothing
$$

Article identity and source linkage should be used to verify this condition.

---

### Duplicate boundary

Exact or near-duplicate content must not silently cross experimental partitions.

Where duplicate or near-duplicate relationships have already been identified during data preparation, partition construction must respect those relationships.

Related duplicate records should not be allowed to create artificial evaluation performance.

---

### Randomisation policy

Where randomisation is required, the project seed remains:

$$
seed=42
$$

Randomisation may determine article assignment or batch order, but it must never randomise sentence order within an article.

Thus:

$$
Shuffle(\text{articles})
$$

may be permissible, while:

$$
Shuffle(\text{sentences within article})
$$

is prohibited for the sequential reference architecture.

---

### Batch-order independence

Recurrent state is reset at article boundaries.

Therefore the order in which independent articles appear in a batch or epoch must not create semantic dependencies between them.

Article ordering may affect optimisation stochasticity later, but it must not alter the definition of the recurrent sequence itself.

---

### Dataset integrity checks

Before the dataset is considered valid, Block 4 should verify:

- article identifiers are present;
- sentence identifiers are present;
- sentence text is present for eligible records;
- sentence indices are valid;
- sentence indices are monotonic within articles;
- article-start indicators are correct;
- article-end indicators are correct;
- sequence lengths are internally consistent;
- source linkage is preserved;
- supervision masks correspond to the Block 2 inventory;
- missing targets are not converted to zero;
- article partitions are disjoint if partitions are constructed;
- sentence order has not been randomised;
- no cross-article recurrent sequence has been created.

---

### Representation-availability checks

Block 4 must separately report whether contextual sentence representations are available.

A dataset can therefore be:

- structurally valid;
- supervision-valid;
- representation-incomplete.

These states must not be collapsed.

For example:

$$
DatasetStructuralValid=True
$$

does not imply:

$$
TextualRepresentationsAvailable=True
$$

This distinction is particularly important before selection of the concrete semantic backbone.

---

### Training-readiness condition

The existence of a valid sequential dataset does not by itself authorise training.

For a supervised objective \(k\), training readiness requires at minimum:

$$
Ready_k
=
DatasetValid
\land
RepresentationsAvailable
\land
ValidSupervision_k
\land
ParameterPolicyAllows_k
\land
ObjectiveDefined_k
$$

If any required condition is false, the corresponding training objective must remain inactive.

---

### Structural forward-validation data

A later controlled forward pass may require tensors before real contextual representations are available.

Synthetic inputs may be generated for this purpose only if they are explicitly marked as:

**structural validation data**

They must not be:

- treated as article representations;
- stored as training labels;
- used to estimate empirical performance;
- used to justify model validity beyond computational compatibility.

This preserves the distinction:

$$
\text{computational validation}
\neq
\text{empirical validation}
$$

---

### Dataset object boundary

Block 4 may construct:

- canonical sentence records;
- article sequences;
- article-level partition assignments;
- sequence metadata;
- supervision masks;
- padding policy;
- batch-construction utilities.

It must not claim that the resulting object is a trainable dataset when required representations or supervision remain unavailable.

The dataset state should therefore be reported explicitly.

---

### Relationship to Block 5

Block 5 will define **Loss Assembly, Objective Activation and Optimiser Policy**.

Block 4 provides the valid sentence sequences, targets and masks required by that process.

Block 5 must use the masks created here rather than infer supervision from numerical target values.

Conceptually:

$$
\text{dataset}
+
\text{supervision masks}
+
\text{parameter policy}
\rightarrow
\text{objective activation}
$$

---

### Relationship to Block 6

Block 6 will execute the first controlled forward validation.

If real contextual sentence representations are not yet available, Block 6 may use explicitly synthetic structural-validation inputs.

Such execution must remain separate from training and empirical evaluation.

---

### Methodological boundaries

Block 4 does not:

- randomise sentence order within articles;
- carry recurrent state between independent articles;
- permit future sentence context;
- treat padding as textual content;
- convert missing supervision to zero;
- convert missing supervision to negative evidence;
- fabricate contextual sentence embeddings;
- manufacture recurrent-state targets;
- manufacture transformation targets;
- derive Transformative Weight automatically from transformation magnitude;
- predefined concrete social groups for batching convenience;
- use unvalidated model-predicted groups as validated conditioning inputs;
- split individual sentences from one article across experimental partitions;
- activate model parameters;
- create an optimiser;
- calculate training loss;
- perform optimisation;
- establish empirical validity.

---

### Execution boundary

This block constructs and validates the **training dataset and sequential batch contract**.

At this stage:

- sentence-level records may be constructed;
- article identity is preserved;
- sentence order is preserved;
- sequence lengths are explicit;
- article boundaries are explicit;
- recurrent reset points are explicit;
- supervision availability is represented by masks;
- padding and target masks remain distinct;
- global inputs remain mandatory;
- group-conditioned inputs remain optional;
- experimental partitioning occurs at article level;
- randomisation remains reproducible with seed 42;
- contextual representation availability is reported independently;
- dataset structural validity is reported independently from training readiness.

However:

- unavailable contextual representations are not fabricated;
- unavailable targets remain unavailable;
- no parameter group is activated;
- no optimiser is created;
- no model forward pass is executed;
- no loss is calculated;
- no optimisation step is performed;
- no empirical evaluation is performed.

Block 4 therefore establishes the data structure required for controlled objective construction and subsequent sequential execution without weakening the supervision, causality or article-boundary contracts established by the preceding notebooks.

**Block 5 — Loss Assembly, Objective Activation and Optimiser Policy** may proceed only after the sequential dataset structure has been validated.

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Block 4: Training Dataset and Sequential Batch Construction
# =============================================================================

from collections import defaultdict
from copy import deepcopy
from datetime import datetime, timezone
import random
import uuid

import numpy as np
import pandas as pd
import torch


# -----------------------------------------------------------------------------
# Block dependency checks
# -----------------------------------------------------------------------------

required_block_1_objects = [
    "NOTEBOOK_05_BLOCK_1_COMPLETE",
    "NOTEBOOK_05_HANDOVER_VALID",
]

missing_block_1_objects = [
    object_name
    for object_name in required_block_1_objects
    if object_name not in globals()
]

if missing_block_1_objects:
    raise NameError(
        "Notebook 05 Block 1 is not initialised. "
        f"Missing: {missing_block_1_objects}"
    )


required_block_2_objects = [
    "NOTEBOOK_05_BLOCK_2_COMPLETE",
    "NOTEBOOK_05_BLOCK_2_VALID",
    "SUPERVISION_INVENTORY",
    "SUPERVISION_OBSERVATIONS",
    "EXPECTED_SUPERVISION_TARGETS",
]

missing_block_2_objects = [
    object_name
    for object_name in required_block_2_objects
    if object_name not in globals()
]

if missing_block_2_objects:
    raise NameError(
        "Notebook 05 Block 2 is not initialised. "
        f"Missing: {missing_block_2_objects}"
    )


required_block_3_objects = [
    "NOTEBOOK_05_BLOCK_3_COMPLETE",
    "NOTEBOOK_05_BLOCK_3_VALID",
    "NOTEBOOK_05_MODEL_INSTANTIATED",
    "MEDIA_AI_MODEL",
    "BACKBONE_HIDDEN_DIM",
    "MODEL_DEVICE",
    "MODEL_DTYPE",
]

missing_block_3_objects = [
    object_name
    for object_name in required_block_3_objects
    if object_name not in globals()
]

if missing_block_3_objects:
    raise NameError(
        "Notebook 05 Block 3 is not initialised. "
        f"Missing: {missing_block_3_objects}"
    )


if not NOTEBOOK_05_BLOCK_1_COMPLETE:
    raise ValueError(
        "Notebook 05 Block 1 must be complete."
    )


if not NOTEBOOK_05_BLOCK_2_COMPLETE:
    raise ValueError(
        "Notebook 05 Block 2 must be complete."
    )


if not NOTEBOOK_05_BLOCK_2_VALID:
    raise ValueError(
        "Notebook 05 Block 2 supervision inventory is invalid."
    )


if not NOTEBOOK_05_BLOCK_3_COMPLETE:
    raise ValueError(
        "Notebook 05 Block 3 must be complete."
    )


if not NOTEBOOK_05_BLOCK_3_VALID:
    raise ValueError(
        "Notebook 05 Block 3 model policy is invalid."
    )


if not NOTEBOOK_05_MODEL_INSTANTIATED:
    raise ValueError(
        "The reference architecture must be instantiated "
        "before the sequential dataset contract is constructed."
    )


# -----------------------------------------------------------------------------
# Block configuration
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_4 = 4

NOTEBOOK_05_BLOCK_4_NAME = (
    "Training Dataset and Sequential Batch Construction"
)

SEQUENTIAL_DATASET_VERSION = "1.0"

SEQUENTIAL_DATASET_CREATED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)

DATASET_RANDOM_SEED = 42

random.seed(
    DATASET_RANDOM_SEED
)

np.random.seed(
    DATASET_RANDOM_SEED
)


# -----------------------------------------------------------------------------
# Sequential dataset policy
# -----------------------------------------------------------------------------

SEQUENCE_UNIT = "sentence"

SEQUENCE_ORDER_REQUIRED = True

ARTICLE_BOUNDARY_RESET_REQUIRED = True

CROSS_ARTICLE_RECURRENCE_ALLOWED = False

FUTURE_CONTEXT_ALLOWED = False

SENTENCE_RANDOMISATION_WITHIN_ARTICLE = False

ARTICLE_LEVEL_PARTITIONING_REQUIRED = True

PADDING_IS_TEXT = False

MISSING_TARGET_EQUALS_ZERO = False

MISSING_TARGET_EQUALS_NEGATIVE = False

SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_TRAINING = False

SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_STRUCTURAL_VALIDATION = True

MODEL_PREDICTED_GROUPS_AUTO_ACCEPTED = False


# -----------------------------------------------------------------------------
# Canonical source-field aliases
# -----------------------------------------------------------------------------
#
# Earlier notebooks may have used slightly different field names.
# Block 4 accepts a limited explicit alias set while producing one canonical
# Notebook 05 representation.
# -----------------------------------------------------------------------------

ARTICLE_ID_ALIASES = (
    "article_id",
    "articleId",
    "source_article_id",
    "record_id",
)

SENTENCE_ID_ALIASES = (
    "sentence_id",
    "sentenceId",
)

SENTENCE_INDEX_ALIASES = (
    "sentence_index",
    "sentence_idx",
    "sentence_number",
    "sentence_position",
    "index",
)

SENTENCE_TEXT_ALIASES = (
    "sentence_text",
    "sentence",
    "text",
)

SOURCE_REFERENCE_ALIASES = (
    "source_reference",
    "source_record_id",
    "source_id",
    "provider_article_id",
)

TEXTUAL_REPRESENTATION_ALIASES = (
    "textual_representation",
    "sentence_embedding",
    "embedding",
    "contextual_embedding",
)


# -----------------------------------------------------------------------------
# Candidate runtime objects
# -----------------------------------------------------------------------------
#
# The notebook does not assume a single upstream variable name.
# Only list/tuple/DataFrame objects that look like sentence-level records
# are accepted.
# -----------------------------------------------------------------------------

PREFERRED_SENTENCE_RECORD_OBJECT_NAMES = (
    "NOTEBOOK_05_SENTENCE_RECORDS",
    "SENTENCE_RECORDS",
    "sentence_records",
    "PREPARED_SENTENCE_RECORDS",
    "prepared_sentence_records",
    "MODEL_SENTENCE_RECORDS",
    "model_sentence_records",
    "FACTUAL_REPRESENTATION_RECORDS",
)


# -----------------------------------------------------------------------------
# Record utilities
# -----------------------------------------------------------------------------

def first_present_value(
    record,
    aliases,
    default=None,
):
    """
    Return the first present non-None value from an alias set.
    """

    for field_name in aliases:

        if (
            field_name in record
            and record[field_name] is not None
        ):
            return record[field_name]

    return default


def object_to_record_list(
    candidate_object,
):
    """
    Convert a compatible object to a list of dictionaries.
    """

    if isinstance(
        candidate_object,
        pd.DataFrame,
    ):
        return candidate_object.to_dict(
            orient="records"
        )


    if isinstance(
        candidate_object,
        (list, tuple),
    ):

        if all(
            isinstance(
                item,
                dict,
            )
            for item
            in candidate_object
        ):
            return [
                deepcopy(
                    item
                )
                for item
                in candidate_object
            ]


    return None


def looks_like_sentence_records(
    records,
):
    """
    Determine whether records contain the minimum sentence-level fields.
    """

    if not records:
        return False


    valid_records = 0


    for record in records:

        article_id = first_present_value(
            record,
            ARTICLE_ID_ALIASES,
        )

        sentence_text = first_present_value(
            record,
            SENTENCE_TEXT_ALIASES,
        )


        if (
            article_id is not None
            and isinstance(
                sentence_text,
                str,
            )
            and sentence_text.strip()
        ):
            valid_records += 1


    return (
        valid_records
        == len(records)
    )


# -----------------------------------------------------------------------------
# Runtime sentence-record discovery
# -----------------------------------------------------------------------------

def discover_sentence_records():
    """
    Discover compatible real sentence records already present
    in the current runtime.

    Preferred known names are checked first.

    A conservative secondary scan is then performed over runtime
    list/tuple/DataFrame objects.

    No synthetic records are generated.
    """

    # -------------------------------------------------------------------------
    # Preferred names
    # -------------------------------------------------------------------------

    for object_name in PREFERRED_SENTENCE_RECORD_OBJECT_NAMES:

        if object_name not in globals():
            continue


        records = object_to_record_list(
            globals()[
                object_name
            ]
        )


        if (
            records is not None
            and looks_like_sentence_records(
                records
            )
        ):
            return (
                object_name,
                records,
            )


    # -------------------------------------------------------------------------
    # Conservative runtime scan
    # -------------------------------------------------------------------------

    excluded_names = {
        "SUPERVISION_INVENTORY",
        "PARAMETER_REGISTRY",
    }


    for object_name, candidate_object in list(
        globals().items()
    ):

        if object_name.startswith(
            "_"
        ):
            continue


        if object_name in excluded_names:
            continue


        records = object_to_record_list(
            candidate_object
        )


        if (
            records is not None
            and looks_like_sentence_records(
                records
            )
        ):
            return (
                object_name,
                records,
            )


    return (
        None,
        [],
    )


(
    SENTENCE_RECORD_SOURCE_OBJECT,
    RAW_SENTENCE_RECORDS,
) = discover_sentence_records()


SENTENCE_RECORD_INPUT_AVAILABLE = bool(
    RAW_SENTENCE_RECORDS
)


# -----------------------------------------------------------------------------
# Canonical sentence-record construction
# -----------------------------------------------------------------------------

def canonicalise_sentence_record(
    source_record,
    fallback_index,
):
    """
    Convert one upstream sentence record to the canonical
    Notebook 05 sentence representation.
    """

    article_id = first_present_value(
        source_record,
        ARTICLE_ID_ALIASES,
    )


    if article_id is None:
        raise ValueError(
            "Sentence record does not contain an article identifier."
        )


    sentence_text = first_present_value(
        source_record,
        SENTENCE_TEXT_ALIASES,
    )


    if (
        sentence_text is None
        or not isinstance(
            sentence_text,
            str,
        )
        or not sentence_text.strip()
    ):
        raise ValueError(
            "Sentence record does not contain valid sentence text."
        )


    sentence_id = first_present_value(
        source_record,
        SENTENCE_ID_ALIASES,
    )


    if sentence_id is None:

        sentence_id = (
            f"{article_id}::sentence::{fallback_index}"
        )


    sentence_index = first_present_value(
        source_record,
        SENTENCE_INDEX_ALIASES,
    )


    if sentence_index is not None:

        try:
            sentence_index = int(
                sentence_index
            )

        except (
            TypeError,
            ValueError,
        ) as exc:

            raise ValueError(
                "Sentence index must be integer-compatible."
            ) from exc


    source_reference = first_present_value(
        source_record,
        SOURCE_REFERENCE_ALIASES,
        default=article_id,
    )


    textual_representation = first_present_value(
        source_record,
        TEXTUAL_REPRESENTATION_ALIASES,
    )


    textual_representation_available = (
        textual_representation is not None
    )


    # -------------------------------------------------------------------------
    # Do not manufacture unavailable target values.
    # -------------------------------------------------------------------------

    target_values = {}

    target_masks = {}


    for target_name in EXPECTED_SUPERVISION_TARGETS:

        observation = (
            SUPERVISION_OBSERVATIONS[
                target_name
            ]
        )


        target_active = bool(
            observation[
                "training_active"
            ]
        )


        possible_value_fields = (
            target_name,
            f"{target_name}_target",
            f"target_{target_name}",
        )


        target_value = first_present_value(
            source_record,
            possible_value_fields,
        )


        if (
            target_active
            and target_value is not None
        ):

            target_values[
                target_name
            ] = target_value

            target_masks[
                target_name
            ] = True

        else:

            target_values[
                target_name
            ] = None

            target_masks[
                target_name
            ] = False


    return {
        "article_id":
            str(
                article_id
            ),

        "sentence_id":
            str(
                sentence_id
            ),

        "sentence_index":
            sentence_index,

        "sentence_text":
            sentence_text.strip(),

        "source_reference":
            (
                str(
                    source_reference
                )
                if source_reference is not None
                else None
            ),

        "textual_representation":
            textual_representation,

        "textual_representation_available":
            bool(
                textual_representation_available
            ),

        "targets":
            target_values,

        "target_masks":
            target_masks,

        "_source_order":
            int(
                fallback_index
            ),
    }


CANONICAL_SENTENCE_RECORDS = []


if SENTENCE_RECORD_INPUT_AVAILABLE:

    for fallback_index, source_record in enumerate(
        RAW_SENTENCE_RECORDS
    ):

        CANONICAL_SENTENCE_RECORDS.append(
            canonicalise_sentence_record(
                source_record=
                    source_record,

                fallback_index=
                    fallback_index,
            )
        )


# -----------------------------------------------------------------------------
# Infer missing within-article sentence indices
# -----------------------------------------------------------------------------

records_by_article_source_order = defaultdict(
    list
)


for record in CANONICAL_SENTENCE_RECORDS:

    records_by_article_source_order[
        record[
            "article_id"
        ]
    ].append(
        record
    )


for article_id, article_records in (
    records_by_article_source_order.items()
):

    existing_indices = [
        record[
            "sentence_index"
        ]
        for record
        in article_records
    ]


    all_indices_available = all(
        index is not None
        for index
        in existing_indices
    )


    if not all_indices_available:

        article_records.sort(
            key=lambda record: record[
                "_source_order"
            ]
        )


        for inferred_index, record in enumerate(
            article_records
        ):

            record[
                "sentence_index"
            ] = int(
                inferred_index
            )


# -----------------------------------------------------------------------------
# Article sequence construction
# -----------------------------------------------------------------------------

ARTICLE_SEQUENCES = []


for article_id in sorted(
    records_by_article_source_order.keys()
):

    article_records = (
        records_by_article_source_order[
            article_id
        ]
    )


    article_records.sort(
        key=lambda record: (
            record[
                "sentence_index"
            ],
            record[
                "_source_order"
            ],
        )
    )


    sequence_length = len(
        article_records
    )


    for position, record in enumerate(
        article_records
    ):

        record[
            "sequence_length"
        ] = int(
            sequence_length
        )

        record[
            "article_start"
        ] = bool(
            position == 0
        )

        record[
            "article_end"
        ] = bool(
            position
            == sequence_length - 1
        )

        record[
            "padding_position"
        ] = False


    ARTICLE_SEQUENCES.append(
        {
            "article_id":
                article_id,

            "sequence_length":
                int(
                    sequence_length
                ),

            "sentences":
                article_records,
        }
    )


# -----------------------------------------------------------------------------
# Sentence-level flattened dataset
# -----------------------------------------------------------------------------

SEQUENTIAL_SENTENCE_RECORDS = [
    record
    for article_sequence
    in ARTICLE_SEQUENCES
    for record
    in article_sequence[
        "sentences"
    ]
]


# -----------------------------------------------------------------------------
# Integrity validation
# -----------------------------------------------------------------------------

SEQUENTIAL_DATASET_ERRORS = []


for article_sequence in ARTICLE_SEQUENCES:

    article_id = article_sequence[
        "article_id"
    ]

    sentence_records = article_sequence[
        "sentences"
    ]

    sequence_length = article_sequence[
        "sequence_length"
    ]


    if sequence_length <= 0:

        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:empty_article_sequence"
        )

        continue


    sentence_indices = [
        record[
            "sentence_index"
        ]
        for record
        in sentence_records
    ]


    if len(
        sentence_indices
    ) != len(
        set(
            sentence_indices
        )
    ):
        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:duplicate_sentence_indices"
        )


    if sentence_indices != sorted(
        sentence_indices
    ):
        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:sentence_order_not_monotonic"
        )


    if not sentence_records[
        0
    ][
        "article_start"
    ]:
        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:missing_article_start"
        )


    if not sentence_records[
        -1
    ][
        "article_end"
    ]:
        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:missing_article_end"
        )


    if sum(
        bool(
            record[
                "article_start"
            ]
        )
        for record
        in sentence_records
    ) != 1:
        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:invalid_start_count"
        )


    if sum(
        bool(
            record[
                "article_end"
            ]
        )
        for record
        in sentence_records
    ) != 1:
        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:invalid_end_count"
        )


    for record in sentence_records:

        if (
            record[
                "sequence_length"
            ]
            != sequence_length
        ):
            SEQUENTIAL_DATASET_ERRORS.append(
                f"{article_id}:"
                "inconsistent_sequence_length"
            )


# -----------------------------------------------------------------------------
# Contextual representation validation
# -----------------------------------------------------------------------------

TEXTUAL_REPRESENTATION_RECORDS_AVAILABLE = sum(
    bool(
        record[
            "textual_representation_available"
        ]
    )
    for record
    in SEQUENTIAL_SENTENCE_RECORDS
)


TEXTUAL_REPRESENTATION_RECORD_COUNT = len(
    SEQUENTIAL_SENTENCE_RECORDS
)


TEXTUAL_REPRESENTATION_COVERAGE = (
    TEXTUAL_REPRESENTATION_RECORDS_AVAILABLE
    / TEXTUAL_REPRESENTATION_RECORD_COUNT
    if TEXTUAL_REPRESENTATION_RECORD_COUNT > 0
    else 0.0
)


TEXTUAL_REPRESENTATIONS_FULLY_AVAILABLE = (
    TEXTUAL_REPRESENTATION_RECORD_COUNT > 0
    and TEXTUAL_REPRESENTATION_RECORDS_AVAILABLE
    == TEXTUAL_REPRESENTATION_RECORD_COUNT
)


# -----------------------------------------------------------------------------
# Validate representation dimensionality where representations exist
# -----------------------------------------------------------------------------

for record in SEQUENTIAL_SENTENCE_RECORDS:

    if not record[
        "textual_representation_available"
    ]:
        continue


    representation = record[
        "textual_representation"
    ]


    if isinstance(
        representation,
        torch.Tensor,
    ):

        representation_shape = tuple(
            representation.shape
        )


    else:

        try:

            representation_array = np.asarray(
                representation
            )

            representation_shape = tuple(
                representation_array.shape
            )

        except Exception as exc:

            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                "invalid_textual_representation"
            )

            continue


    if (
        not representation_shape
        or representation_shape[
            -1
        ]
        != BACKBONE_HIDDEN_DIM
    ):
        SEQUENTIAL_DATASET_ERRORS.append(
            f"{record['sentence_id']}:"
            "textual_representation_dimension_mismatch"
        )


# -----------------------------------------------------------------------------
# Supervision-mask validation
# -----------------------------------------------------------------------------

for record in SEQUENTIAL_SENTENCE_RECORDS:

    for target_name in EXPECTED_SUPERVISION_TARGETS:

        target_value = record[
            "targets"
        ][
            target_name
        ]

        target_mask = bool(
            record[
                "target_masks"
            ][
                target_name
            ]
        )


        supervision_active = bool(
            SUPERVISION_OBSERVATIONS[
                target_name
            ][
                "training_active"
            ]
        )


        if (
            target_mask
            and not supervision_active
        ):
            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                f"inactive_target_masked_active:{target_name}"
            )


        if (
            target_mask
            and target_value is None
        ):
            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                f"masked_target_missing_value:{target_name}"
            )


        if (
            not target_mask
            and target_value == 0
            and not supervision_active
        ):
            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                f"unavailable_target_converted_to_zero:{target_name}"
            )


# -----------------------------------------------------------------------------
# Supervision coverage in sequential records
# -----------------------------------------------------------------------------

SEQUENTIAL_SUPERVISION_COVERAGE = {}


for target_name in EXPECTED_SUPERVISION_TARGETS:

    sentence_count = len(
        SEQUENTIAL_SENTENCE_RECORDS
    )


    available_count = sum(
        bool(
            record[
                "target_masks"
            ][
                target_name
            ]
        )
        for record
        in SEQUENTIAL_SENTENCE_RECORDS
    )


    coverage = (
        available_count
        / sentence_count
        if sentence_count > 0
        else 0.0
    )


    SEQUENTIAL_SUPERVISION_COVERAGE[
        target_name
    ] = {
        "eligible_sentences":
            int(
                sentence_count
            ),

        "available_sentences":
            int(
                available_count
            ),

        "coverage":
            float(
                coverage
            ),
    }


# -----------------------------------------------------------------------------
# Article-level experimental partitioning
# -----------------------------------------------------------------------------
#
# A partition can be constructed even when the current dataset is not yet
# trainable. Partitioning is performed by article, never by individual sentence.
# -----------------------------------------------------------------------------


TRAIN_FRACTION = 0.70

VALIDATION_FRACTION = 0.15

TEST_FRACTION = 0.15


if not np.isclose(
    TRAIN_FRACTION
    + VALIDATION_FRACTION
    + TEST_FRACTION,
    1.0,
):
    raise ValueError(
        "Train, validation and test fractions must sum to 1."
    )


ARTICLE_IDS = [
    article_sequence[
        "article_id"
    ]
    for article_sequence
    in ARTICLE_SEQUENCES
]


ARTICLE_PARTITION_ASSIGNMENTS = {}


if ARTICLE_IDS:

    partition_rng = random.Random(
        DATASET_RANDOM_SEED
    )


    shuffled_article_ids = list(
        ARTICLE_IDS
    )


    partition_rng.shuffle(
        shuffled_article_ids
    )


    article_count = len(
        shuffled_article_ids
    )


    # -------------------------------------------------------------------------
    # Small-sample-safe article partitioning
    # -------------------------------------------------------------------------
    #
    # With fewer than three articles it is impossible to create three non-empty
    # article-level partitions. The code therefore preserves disjointness and
    # reports empty partitions rather than splitting sentences across articles.
    # -------------------------------------------------------------------------


    if article_count >= 3:

        train_count = max(
            1,
            int(
                round(
                    article_count
                    * TRAIN_FRACTION
                )
            ),
        )


        validation_count = max(
            1,
            int(
                round(
                    article_count
                    * VALIDATION_FRACTION
                )
            ),
        )


        if (
            train_count
            + validation_count
            >= article_count
        ):

            train_count = max(
                1,
                article_count - 2,
            )

            validation_count = 1


        test_count = (
            article_count
            - train_count
            - validation_count
        )


        train_articles = shuffled_article_ids[
            :train_count
        ]

        validation_articles = shuffled_article_ids[
            train_count:
            train_count
            + validation_count
        ]

        test_articles = shuffled_article_ids[
            train_count
            + validation_count:
        ]


    elif article_count == 2:

        train_articles = [
            shuffled_article_ids[
                0
            ]
        ]

        validation_articles = []

        test_articles = [
            shuffled_article_ids[
                1
            ]
        ]


    elif article_count == 1:

        train_articles = [
            shuffled_article_ids[
                0
            ]
        ]

        validation_articles = []

        test_articles = []


    else:

        train_articles = []

        validation_articles = []

        test_articles = []


    for article_id in train_articles:

        ARTICLE_PARTITION_ASSIGNMENTS[
            article_id
        ] = "train"


    for article_id in validation_articles:

        ARTICLE_PARTITION_ASSIGNMENTS[
            article_id
        ] = "validation"


    for article_id in test_articles:

        ARTICLE_PARTITION_ASSIGNMENTS[
            article_id
        ] = "test"


# -----------------------------------------------------------------------------
# Attach article partition to records
# -----------------------------------------------------------------------------

for article_sequence in ARTICLE_SEQUENCES:

    article_id = article_sequence[
        "article_id"
    ]


    partition = ARTICLE_PARTITION_ASSIGNMENTS.get(
        article_id
    )


    article_sequence[
        "partition"
    ] = partition


    for record in article_sequence[
        "sentences"
    ]:

        record[
            "partition"
        ] = partition


# -----------------------------------------------------------------------------
# Partition disjointness validation
# -----------------------------------------------------------------------------

TRAIN_ARTICLE_IDS = {
    article_id
    for article_id, partition
    in ARTICLE_PARTITION_ASSIGNMENTS.items()
    if partition == "train"
}

VALIDATION_ARTICLE_IDS = {
    article_id
    for article_id, partition
    in ARTICLE_PARTITION_ASSIGNMENTS.items()
    if partition == "validation"
}

TEST_ARTICLE_IDS = {
    article_id
    for article_id, partition
    in ARTICLE_PARTITION_ASSIGNMENTS.items()
    if partition == "test"
}


if (
    TRAIN_ARTICLE_IDS
    & VALIDATION_ARTICLE_IDS
):
    SEQUENTIAL_DATASET_ERRORS.append(
        "train_validation_article_overlap"
    )


if (
    TRAIN_ARTICLE_IDS
    & TEST_ARTICLE_IDS
):
    SEQUENTIAL_DATASET_ERRORS.append(
        "train_test_article_overlap"
    )


if (
    VALIDATION_ARTICLE_IDS
    & TEST_ARTICLE_IDS
):
    SEQUENTIAL_DATASET_ERRORS.append(
        "validation_test_article_overlap"
    )


# -----------------------------------------------------------------------------
# Padding and batch utilities
# -----------------------------------------------------------------------------

def representation_to_tensor(
    representation,
):
    """
    Convert a real contextual representation to a float tensor.

    This helper refuses unavailable representations.
    """

    if representation is None:
        raise ValueError(
            "Unavailable textual representation cannot be "
            "converted into a training tensor."
        )


    if isinstance(
        representation,
        torch.Tensor,
    ):

        tensor = representation.detach().clone()


    else:

        tensor = torch.as_tensor(
            representation
        )


    tensor = tensor.to(
        dtype=MODEL_DTYPE
    )


    if tensor.shape[-1] != BACKBONE_HIDDEN_DIM:
        raise ValueError(
            "Contextual representation has incompatible "
            "backbone-interface dimensionality."
        )


    return tensor


def collate_article_sequences(
    article_sequences,
    device=None,
):
    """
    Collate complete article sequences into a padded batch.

    Only real contextual representations are accepted.

    Padding vectors are permitted because they are masked computational
    placeholders, not fabricated sentence representations.
    """

    if not article_sequences:
        raise ValueError(
            "At least one article sequence is required."
        )


    if device is None:
        device = MODEL_DEVICE


    batch_size = len(
        article_sequences
    )


    max_sequence_length = max(
        sequence[
            "sequence_length"
        ]
        for sequence
        in article_sequences
    )


    representations = torch.zeros(
        batch_size,
        max_sequence_length,
        BACKBONE_HIDDEN_DIM,
        dtype=MODEL_DTYPE,
        device=device,
    )


    padding_mask = torch.zeros(
        batch_size,
        max_sequence_length,
        dtype=torch.bool,
        device=device,
    )


    article_start_mask = torch.zeros(
        batch_size,
        max_sequence_length,
        dtype=torch.bool,
        device=device,
    )


    article_end_mask = torch.zeros(
        batch_size,
        max_sequence_length,
        dtype=torch.bool,
        device=device,
    )


    sentence_ids = []

    article_ids = []


    for batch_index, article_sequence in enumerate(
        article_sequences
    ):

        article_ids.append(
            article_sequence[
                "article_id"
            ]
        )


        current_sentence_ids = []


        for sentence_position, record in enumerate(
            article_sequence[
                "sentences"
            ]
        ):

            if not record[
                "textual_representation_available"
            ]:
                raise ValueError(
                    "Cannot collate a training batch because "
                    "one or more contextual sentence representations "
                    "are unavailable."
                )


            representation_tensor = (
                representation_to_tensor(
                    record[
                        "textual_representation"
                    ]
                )
            )


            representations[
                batch_index,
                sentence_position,
            ] = representation_tensor


            padding_mask[
                batch_index,
                sentence_position,
            ] = True


            article_start_mask[
                batch_index,
                sentence_position,
            ] = bool(
                record[
                    "article_start"
                ]
            )


            article_end_mask[
                batch_index,
                sentence_position,
            ] = bool(
                record[
                    "article_end"
                ]
            )


            current_sentence_ids.append(
                record[
                    "sentence_id"
                ]
            )


        sentence_ids.append(
            current_sentence_ids
        )


    return {
        "article_ids":
            article_ids,

        "sentence_ids":
            sentence_ids,

        "representations":
            representations,

        "padding_mask":
            padding_mask,

        "article_start_mask":
            article_start_mask,

        "article_end_mask":
            article_end_mask,

        "batch_size":
            int(
                batch_size
            ),

        "max_sequence_length":
            int(
                max_sequence_length
            ),
    }


# -----------------------------------------------------------------------------
# Explicit structural-validation tensor helper
# -----------------------------------------------------------------------------

def create_structural_validation_batch(
    batch_size=2,
    sequence_length=3,
    seed=42,
    device=None,
):
    """
    Generate explicitly synthetic representations for computational
    structure validation only.

    These values are NOT training data and MUST NOT be used for empirical
    evaluation or optimisation.
    """

    if not SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_STRUCTURAL_VALIDATION:
        raise ValueError(
            "Synthetic structural-validation inputs are disabled."
        )


    if batch_size <= 0:
        raise ValueError(
            "batch_size must be greater than zero."
        )


    if sequence_length <= 0:
        raise ValueError(
            "sequence_length must be greater than zero."
        )


    if device is None:
        device = MODEL_DEVICE


    generator = torch.Generator(
        device=(
            "cuda"
            if device.type == "cuda"
            else "cpu"
        )
    )


    generator.manual_seed(
        int(
            seed
        )
    )


    representations = torch.randn(
        batch_size,
        sequence_length,
        BACKBONE_HIDDEN_DIM,
        generator=generator,
        dtype=MODEL_DTYPE,
        device=device,
    )


    padding_mask = torch.ones(
        batch_size,
        sequence_length,
        dtype=torch.bool,
        device=device,
    )


    article_start_mask = torch.zeros(
        batch_size,
        sequence_length,
        dtype=torch.bool,
        device=device,
    )

    article_end_mask = torch.zeros(
        batch_size,
        sequence_length,
        dtype=torch.bool,
        device=device,
    )


    article_start_mask[
        :,
        0
    ] = True

    article_end_mask[
        :,
        -1
    ] = True


    return {
        "data_type":
            "synthetic_structural_validation_only",

        "representations":
            representations,

        "padding_mask":
            padding_mask,

        "article_start_mask":
            article_start_mask,

        "article_end_mask":
            article_end_mask,

        "batch_size":
            int(
                batch_size
            ),

        "sequence_length":
            int(
                sequence_length
            ),

        "eligible_for_training":
            False,

        "eligible_for_empirical_evaluation":
            False,
    }


# -----------------------------------------------------------------------------
# Dataset-state determination
# -----------------------------------------------------------------------------

DATASET_INPUT_AVAILABLE = bool(
    SENTENCE_RECORD_INPUT_AVAILABLE
)

DATASET_ARTICLE_COUNT = len(
    ARTICLE_SEQUENCES
)

DATASET_SENTENCE_COUNT = len(
    SEQUENTIAL_SENTENCE_RECORDS
)


DATASET_STRUCTURAL_VALID = bool(
    DATASET_INPUT_AVAILABLE
    and DATASET_ARTICLE_COUNT > 0
    and DATASET_SENTENCE_COUNT > 0
    and len(
        SEQUENTIAL_DATASET_ERRORS
    ) == 0
)


DATASET_SUPERVISION_AVAILABLE = any(
    coverage_record[
        "available_sentences"
    ] > 0
    for coverage_record
    in SEQUENTIAL_SUPERVISION_COVERAGE.values()
)


DATASET_REPRESENTATIONS_AVAILABLE = bool(
    TEXTUAL_REPRESENTATIONS_FULLY_AVAILABLE
)


DATASET_PARAMETER_POLICY_ALLOWS_TRAINING = bool(
    NOTEBOOK_05_TRAINABLE_PARAMETER_GROUPS_ACTIVATED
)


DATASET_OBJECTIVE_DEFINED = False


DATASET_SUPERVISED_TRAINING_READY = bool(
    DATASET_STRUCTURAL_VALID
    and DATASET_REPRESENTATIONS_AVAILABLE
    and DATASET_SUPERVISION_AVAILABLE
    and DATASET_PARAMETER_POLICY_ALLOWS_TRAINING
    and DATASET_OBJECTIVE_DEFINED
)


# -----------------------------------------------------------------------------
# Training dataset construction state
# -----------------------------------------------------------------------------

NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED = bool(
    DATASET_STRUCTURAL_VALID
)

NOTEBOOK_05_SEQUENTIAL_BATCH_CONTRACT_DEFINED = True

NOTEBOOK_05_ARTICLE_PARTITIONS_CONSTRUCTED = bool(
    ARTICLE_PARTITION_ASSIGNMENTS
)

NOTEBOOK_05_TEXTUAL_REPRESENTATIONS_AVAILABLE = (
    DATASET_REPRESENTATIONS_AVAILABLE
)

NOTEBOOK_05_SUPERVISED_TRAINING_READY = (
    DATASET_SUPERVISED_TRAINING_READY
)


# -----------------------------------------------------------------------------
# Downstream execution boundary
# -----------------------------------------------------------------------------

NOTEBOOK_05_OPTIMIZER_CREATED = False

NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED = False

NOTEBOOK_05_LOSS_CALCULATED = False

NOTEBOOK_05_TRAINING_EXECUTED = False

NOTEBOOK_05_CHECKPOINT_SELECTED = False

NOTEBOOK_05_ABLATION_EXECUTED = False

NOTEBOOK_05_EVALUATION_EXECUTED = False

NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED = False


# -----------------------------------------------------------------------------
# Block 4 methodological validation
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_4_ERRORS = []


if SENTENCE_RANDOMISATION_WITHIN_ARTICLE:
    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "sentence_randomisation_incorrectly_enabled"
    )


if CROSS_ARTICLE_RECURRENCE_ALLOWED:
    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "cross_article_recurrence_incorrectly_enabled"
    )


if FUTURE_CONTEXT_ALLOWED:
    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "future_context_incorrectly_allowed"
    )


if PADDING_IS_TEXT:
    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "padding_incorrectly_defined_as_text"
    )


if MISSING_TARGET_EQUALS_ZERO:
    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "missing_target_incorrectly_equals_zero"
    )


if MISSING_TARGET_EQUALS_NEGATIVE:
    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "missing_target_incorrectly_equals_negative"
    )


if SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_TRAINING:
    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "synthetic_representations_incorrectly_allowed_for_training"
    )


if MODEL_PREDICTED_GROUPS_AUTO_ACCEPTED:
    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "predicted_groups_incorrectly_auto_accepted"
    )


if NOTEBOOK_05_OPTIMIZER_CREATED:
    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "optimizer_incorrectly_created_in_block_4"
    )


if NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED:
    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "forward_pass_incorrectly_executed_in_block_4"
    )


if NOTEBOOK_05_TRAINING_EXECUTED:
    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "training_incorrectly_executed_in_block_4"
    )


# Structural dataset errors become Block 4 errors only when an input dataset
# was actually discovered. Absence of the upstream sentence dataset is reported
# as a readiness limitation rather than misrepresented as malformed data.

if DATASET_INPUT_AVAILABLE:

    NOTEBOOK_05_BLOCK_4_ERRORS.extend(
        SEQUENTIAL_DATASET_ERRORS
    )


NOTEBOOK_05_BLOCK_4_VALID = (
    len(
        NOTEBOOK_05_BLOCK_4_ERRORS
    )
    == 0
)


if not NOTEBOOK_05_BLOCK_4_VALID:
    raise ValueError(
        "Notebook 05 Block 4 sequential dataset validation failed: "
        f"{NOTEBOOK_05_BLOCK_4_ERRORS}"
    )


# -----------------------------------------------------------------------------
# Block completion
# -----------------------------------------------------------------------------
#
# The methodological block is complete even if the real sentence records
# are not present in this fresh runtime.
#
# DATASET_STRUCTURAL_VALID separately records whether the real sequential
# dataset itself was successfully constructed.
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_4_COMPLETE = True


# -----------------------------------------------------------------------------
# Compact sentence-record view
# -----------------------------------------------------------------------------

SEQUENTIAL_SENTENCE_VIEW_ROWS = []


for record in SEQUENTIAL_SENTENCE_RECORDS:

    active_target_count = sum(
        bool(
            target_mask
        )
        for target_mask
        in record[
            "target_masks"
        ].values()
    )


    SEQUENTIAL_SENTENCE_VIEW_ROWS.append(
        {
            "article_id":
                record[
                    "article_id"
                ],

            "sentence_id":
                record[
                    "sentence_id"
                ],

            "sentence_index":
                record[
                    "sentence_index"
                ],

            "sequence_length":
                record[
                    "sequence_length"
                ],

            "article_start":
                record[
                    "article_start"
                ],

            "article_end":
                record[
                    "article_end"
                ],

            "partition":
                record[
                    "partition"
                ],

            "representation_available":
                record[
                    "textual_representation_available"
                ],

            "active_target_count":
                int(
                    active_target_count
                ),

            "sentence_text":
                record[
                    "sentence_text"
                ],
        }
    )


SEQUENTIAL_SENTENCE_VIEW = pd.DataFrame(
    SEQUENTIAL_SENTENCE_VIEW_ROWS
)


# -----------------------------------------------------------------------------
# Block 4 summary
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_4_SUMMARY = {
    "block":
        NOTEBOOK_05_BLOCK_4,

    "block_name":
        NOTEBOOK_05_BLOCK_4_NAME,

    "dataset_version":
        SEQUENTIAL_DATASET_VERSION,

    "created_at_utc":
        SEQUENTIAL_DATASET_CREATED_AT_UTC,

    "sentence_record_source_object":
        SENTENCE_RECORD_SOURCE_OBJECT,

    "input_available":
        DATASET_INPUT_AVAILABLE,

    "article_count":
        DATASET_ARTICLE_COUNT,

    "sentence_count":
        DATASET_SENTENCE_COUNT,

    "structural_valid":
        DATASET_STRUCTURAL_VALID,

    "representations_available":
        DATASET_REPRESENTATIONS_AVAILABLE,

    "representation_coverage":
        TEXTUAL_REPRESENTATION_COVERAGE,

    "supervision_available":
        DATASET_SUPERVISION_AVAILABLE,

    "article_partitions_constructed":
        NOTEBOOK_05_ARTICLE_PARTITIONS_CONSTRUCTED,

    "train_article_count":
        len(
            TRAIN_ARTICLE_IDS
        ),

    "validation_article_count":
        len(
            VALIDATION_ARTICLE_IDS
        ),

    "test_article_count":
        len(
            TEST_ARTICLE_IDS
        ),

    "sequential_batch_contract_defined":
        NOTEBOOK_05_SEQUENTIAL_BATCH_CONTRACT_DEFINED,

    "training_data_constructed":
        NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED,

    "supervised_training_ready":
        NOTEBOOK_05_SUPERVISED_TRAINING_READY,

    "optimizer_created":
        NOTEBOOK_05_OPTIMIZER_CREATED,

    "forward_pass_executed":
        NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED,

    "training_executed":
        NOTEBOOK_05_TRAINING_EXECUTED,

    "block_valid":
        NOTEBOOK_05_BLOCK_4_VALID,

    "block_complete":
        NOTEBOOK_05_BLOCK_4_COMPLETE,
}


# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------

print("=" * 72)
print(
    "Media AI — Notebook 05, Block 4: "
    "Training Dataset and Sequential Batch Construction"
)
print("=" * 72)

print(
    f"Dataset version              : "
    f"{SEQUENTIAL_DATASET_VERSION}"
)

print(
    f"Sequence unit                : "
    f"{SEQUENCE_UNIT}"
)

print(
    f"Project random seed          : "
    f"{DATASET_RANDOM_SEED}"
)

print("-" * 72)

print("Input discovery")

print(
    f"Sentence records found       : "
    f"{DATASET_INPUT_AVAILABLE}"
)

print(
    f"Source runtime object        : "
    f"{SENTENCE_RECORD_SOURCE_OBJECT}"
)

print(
    f"Input record count           : "
    f"{len(RAW_SENTENCE_RECORDS)}"
)

print("-" * 72)

print("Sequential dataset")

print(
    f"Article sequences            : "
    f"{DATASET_ARTICLE_COUNT}"
)

print(
    f"Sentence records             : "
    f"{DATASET_SENTENCE_COUNT}"
)

print(
    f"Structural dataset valid     : "
    f"{DATASET_STRUCTURAL_VALID}"
)

print(
    f"Sentence order required      : "
    f"{SEQUENCE_ORDER_REQUIRED}"
)

print(
    f"Within-article shuffle       : "
    f"{SENTENCE_RANDOMISATION_WITHIN_ARTICLE}"
)

print(
    f"Article reset required       : "
    f"{ARTICLE_BOUNDARY_RESET_REQUIRED}"
)

print(
    f"Cross-article recurrence     : "
    f"{CROSS_ARTICLE_RECURRENCE_ALLOWED}"
)

print(
    f"Future context allowed       : "
    f"{FUTURE_CONTEXT_ALLOWED}"
)

print("-" * 72)

print("Contextual representations")

print(
    f"Backbone interface dimension : "
    f"{BACKBONE_HIDDEN_DIM}"
)

print(
    f"Representations available    : "
    f"{TEXTUAL_REPRESENTATION_RECORDS_AVAILABLE}"
)

print(
    f"Representation capacity      : "
    f"{TEXTUAL_REPRESENTATION_RECORD_COUNT}"
)

print(
    f"Representation coverage      : "
    f"{TEXTUAL_REPRESENTATION_COVERAGE:.4f}"
)

print(
    f"Fully available              : "
    f"{DATASET_REPRESENTATIONS_AVAILABLE}"
)

print(
    f"Synthetic allowed training   : "
    f"{SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_TRAINING}"
)

print(
    f"Synthetic structural test    : "
    f"{SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_STRUCTURAL_VALIDATION}"
)

print("-" * 72)

print("Supervision attachment")

print(
    f"Supervision target families  : "
    f"{len(EXPECTED_SUPERVISION_TARGETS)}"
)

print(
    f"Any sentence supervision     : "
    f"{DATASET_SUPERVISION_AVAILABLE}"
)

print(
    f"Missing target = zero        : "
    f"{MISSING_TARGET_EQUALS_ZERO}"
)

print(
    f"Missing target = negative    : "
    f"{MISSING_TARGET_EQUALS_NEGATIVE}"
)

print("-" * 72)

print("Article partitions")

print(
    f"Partitioning level           : "
    f"article"
)

print(
    f"Train articles               : "
    f"{len(TRAIN_ARTICLE_IDS)}"
)

print(
    f"Validation articles          : "
    f"{len(VALIDATION_ARTICLE_IDS)}"
)

print(
    f"Test articles                : "
    f"{len(TEST_ARTICLE_IDS)}"
)

print(
    f"Partitions constructed       : "
    f"{NOTEBOOK_05_ARTICLE_PARTITIONS_CONSTRUCTED}"
)

print("-" * 72)

print("Batch contract")

print(
    f"Variable lengths supported   : "
    f"{True}"
)

print(
    f"Padding is textual content   : "
    f"{PADDING_IS_TEXT}"
)

print(
    f"Padding mask required        : "
    f"{True}"
)

print(
    f"Target masks separate        : "
    f"{True}"
)

print(
    f"Group path optional          : "
    f"{True}"
)

print(
    f"Predicted groups auto-used   : "
    f"{MODEL_PREDICTED_GROUPS_AUTO_ACCEPTED}"
)

print("-" * 72)

print("Training readiness")

print(
    f"Dataset structural valid     : "
    f"{DATASET_STRUCTURAL_VALID}"
)

print(
    f"Representations available    : "
    f"{DATASET_REPRESENTATIONS_AVAILABLE}"
)

print(
    f"Validated supervision avail. : "
    f"{DATASET_SUPERVISION_AVAILABLE}"
)

print(
    f"Parameter policy allows      : "
    f"{DATASET_PARAMETER_POLICY_ALLOWS_TRAINING}"
)

print(
    f"Objective defined            : "
    f"{DATASET_OBJECTIVE_DEFINED}"
)

print(
    f"Supervised training ready    : "
    f"{DATASET_SUPERVISED_TRAINING_READY}"
)

print("-" * 72)

print("Execution state")

print(
    f"Batch contract defined       : "
    f"{NOTEBOOK_05_SEQUENTIAL_BATCH_CONTRACT_DEFINED}"
)

print(
    f"Training data constructed    : "
    f"{NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED}"
)

print(
    f"Optimizer created            : "
    f"{NOTEBOOK_05_OPTIMIZER_CREATED}"
)

print(
    f"Forward pass executed        : "
    f"{NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_05_LOSS_CALCULATED}"
)

print(
    f"Training executed            : "
    f"{NOTEBOOK_05_TRAINING_EXECUTED}"
)

print(
    f"Evaluation executed          : "
    f"{NOTEBOOK_05_EVALUATION_EXECUTED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_05_BLOCK_4_VALID}"
)

print(
    f"Block 4 complete             : "
    f"{NOTEBOOK_05_BLOCK_4_COMPLETE}"
)

print("=" * 72)

print(
    "Sequential dataset and batch contract defined successfully."
)

if DATASET_INPUT_AVAILABLE:

    print(
        "Real sentence-level records were discovered in the current runtime."
    )

    print(
        "Article identity and within-article sentence order were preserved."
    )

    print(
        "Article-start and article-end boundaries were constructed explicitly."
    )

    print(
        "Experimental partitioning was performed at article level."
    )

else:

    print(
        "No compatible real sentence-level record object was found "
        "in the current Notebook 05 runtime."
    )

    print(
        "No article or sentence records were fabricated."
    )

    print(
        "The sequential batch contract remains defined, but the real "
        "training dataset is pending upstream data loading."
    )


if not DATASET_REPRESENTATIONS_AVAILABLE:

    print(
        "Validated contextual sentence representations are not fully available."
    )

    print(
        "Missing semantic representations were not replaced by random, "
        "zero or pseudo-embeddings for training."
    )


if not DATASET_SUPERVISION_AVAILABLE:

    print(
        "No validated direct supervision is attached to the current "
        "sequential dataset."
    )


print(
    "Missing targets remain distinct from zero and negative evidence."
)

print(
    "Padding remains a masked computational placeholder rather than "
    "textual content."
)

print(
    "Synthetic representations are permitted only for later structural "
    "forward validation and are explicitly prohibited from training."
)

print(
    "No recurrent connection is permitted across independent articles."
)

print(
    "No future-context access has been introduced by the dataset contract."
)

print(
    "No model-predicted group is automatically accepted as a validated "
    "group-conditioning input."
)

print(
    "No optimiser, forward pass, loss calculation, optimisation, training "
    "or empirical evaluation has been executed."
)

print(
    "Block 5 may proceed to Loss Assembly, Objective Activation "
    "and Optimiser Policy."
)


# -----------------------------------------------------------------------------
# Display sequential dataset view when available
# -----------------------------------------------------------------------------

if not SEQUENTIAL_SENTENCE_VIEW.empty:

    display(
        SEQUENTIAL_SENTENCE_VIEW
    )

NameError: Notebook 05 Block 3 is not initialised. Missing: ['NOTEBOOK_05_BLOCK_3_COMPLETE', 'NOTEBOOK_05_BLOCK_3_VALID', 'MEDIA_AI_MODEL', 'BACKBONE_HIDDEN_DIM', 'MODEL_DEVICE', 'MODEL_DTYPE']

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Block 4: Training Dataset and Sequential Batch Construction
# =============================================================================

from collections import defaultdict
from copy import deepcopy
from datetime import datetime, timezone
import random

import numpy as np
import pandas as pd
import torch


# -----------------------------------------------------------------------------
# Block dependency checks
# -----------------------------------------------------------------------------

required_block_1_objects = [
    "NOTEBOOK_05_BLOCK_1_COMPLETE",
    "NOTEBOOK_05_HANDOVER_VALID",
]


missing_block_1_objects = [
    object_name
    for object_name
    in required_block_1_objects
    if object_name not in globals()
]


if missing_block_1_objects:

    raise NameError(
        "Notebook 05 Block 1 is not initialised. "
        f"Missing: {missing_block_1_objects}"
    )


required_block_2_objects = [
    "NOTEBOOK_05_BLOCK_2_COMPLETE",
    "NOTEBOOK_05_BLOCK_2_VALID",
    "SUPERVISION_INVENTORY",
    "SUPERVISION_OBSERVATIONS",
    "EXPECTED_SUPERVISION_TARGETS",
    "VALIDATED_SUPERVISION_TARGETS",
    "ELIGIBLE_DIRECT_TRAINING_TARGETS",
    "NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS",
    "NOTEBOOK_03_ACCEPTED_RECORD_COUNT",
    "NOTEBOOK_03_SENTENCE_IDS_PRESENT",
    "NOTEBOOK_03_SENTENCE_IDS_UNIQUE",
]


missing_block_2_objects = [
    object_name
    for object_name
    in required_block_2_objects
    if object_name not in globals()
]


if missing_block_2_objects:

    raise NameError(
        "Notebook 05 Block 2 is not initialised. "
        f"Missing: {missing_block_2_objects}"
    )


required_block_3_objects = [
    "NOTEBOOK_05_BLOCK_3_COMPLETE",
    "NOTEBOOK_05_BLOCK_3_VALID",
    "NOTEBOOK_05_MODEL_INSTANTIATED",
    "NOTEBOOK_05_TRAINABLE_PARAMETER_GROUPS_ACTIVATED",
    "MEDIA_AI_MODEL",
    "BACKBONE_HIDDEN_DIM",
    "MODEL_DEVICE",
    "MODEL_DTYPE",
]


missing_block_3_objects = [
    object_name
    for object_name
    in required_block_3_objects
    if object_name not in globals()
]


if missing_block_3_objects:

    raise NameError(
        "Notebook 05 Block 3 is not initialised. "
        f"Missing: {missing_block_3_objects}"
    )


if not NOTEBOOK_05_BLOCK_1_COMPLETE:

    raise ValueError(
        "Notebook 05 Block 1 must be complete."
    )


if not NOTEBOOK_05_BLOCK_2_COMPLETE:

    raise ValueError(
        "Notebook 05 Block 2 must be complete."
    )


if not NOTEBOOK_05_BLOCK_2_VALID:

    raise ValueError(
        "Notebook 05 Block 2 supervision inventory is invalid."
    )


if not NOTEBOOK_05_BLOCK_3_COMPLETE:

    raise ValueError(
        "Notebook 05 Block 3 must be complete."
    )


if not NOTEBOOK_05_BLOCK_3_VALID:

    raise ValueError(
        "Notebook 05 Block 3 model policy is invalid."
    )


if not NOTEBOOK_05_MODEL_INSTANTIATED:

    raise ValueError(
        "The reference architecture must be instantiated "
        "before the sequential dataset is constructed."
    )


# -----------------------------------------------------------------------------
# Block configuration
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_4 = 4

NOTEBOOK_05_BLOCK_4_NAME = (
    "Training Dataset and Sequential Batch Construction"
)

SEQUENTIAL_DATASET_VERSION = "1.1"

SEQUENTIAL_DATASET_CREATED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)

DATASET_RANDOM_SEED = 42


random.seed(
    DATASET_RANDOM_SEED
)

np.random.seed(
    DATASET_RANDOM_SEED
)


# -----------------------------------------------------------------------------
# Sequential dataset policy
# -----------------------------------------------------------------------------

SEQUENCE_UNIT = "sentence"

SEQUENCE_ORDER_REQUIRED = True

ARTICLE_BOUNDARY_RESET_REQUIRED = True

CROSS_ARTICLE_RECURRENCE_ALLOWED = False

FUTURE_CONTEXT_ALLOWED = False

SENTENCE_RANDOMISATION_WITHIN_ARTICLE = False

ARTICLE_LEVEL_PARTITIONING_REQUIRED = True

PADDING_IS_TEXT = False

MISSING_TARGET_EQUALS_ZERO = False

MISSING_TARGET_EQUALS_NEGATIVE = False

SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_TRAINING = False

SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_STRUCTURAL_VALIDATION = True

MODEL_PREDICTED_GROUPS_AUTO_ACCEPTED = False


# -----------------------------------------------------------------------------
# Native Notebook 03 supervision source
# -----------------------------------------------------------------------------

SUPERVISION_RECORD_SOURCE_OBJECT = (
    "NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS"
)

RAW_SUPERVISION_RECORDS = [
    deepcopy(
        record
    )
    for record
    in NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS
]


SUPERVISION_RECORD_INPUT_AVAILABLE = bool(
    RAW_SUPERVISION_RECORDS
)


if not SUPERVISION_RECORD_INPUT_AVAILABLE:

    raise ValueError(
        "Notebook 05 Block 4 requires persisted accepted "
        "Notebook 03 supervision records."
    )


if (
    len(
        RAW_SUPERVISION_RECORDS
    )
    != NOTEBOOK_03_ACCEPTED_RECORD_COUNT
):

    raise ValueError(
        "Notebook 03 accepted-record count changed between "
        "Block 2 and Block 4."
    )


if not NOTEBOOK_03_SENTENCE_IDS_PRESENT:

    raise ValueError(
        "Notebook 03 accepted supervision contains missing "
        "sentence identifiers."
    )


if not NOTEBOOK_03_SENTENCE_IDS_UNIQUE:

    raise ValueError(
        "Notebook 03 accepted supervision contains duplicate "
        "sentence identifiers."
    )


# -----------------------------------------------------------------------------
# Canonical psychological target contract
# -----------------------------------------------------------------------------

PSYCHOLOGICAL_TARGET_FIELDS = {
    "REV":
        "reported_emotion",

    "TEV":
        "transformative_emotion",

    "IEV":
        "immediate_emotional_state",

    "EW":
        "emotional_weight",
}


EMOTIONAL_DIMENSION_ORDER = (
    "fear",
    "anger",
    "sadness",
    "disgust",
    "tension",
    "uncertainty",
    "hope",
    "relief",
    "trust",
    "compassion",
    "solidarity",
)


EXPECTED_DIRECT_DATASET_TARGETS = (
    "REV",
    "TEV",
    "IEV",
    "EW",
)


if (
    tuple(
        ELIGIBLE_DIRECT_TRAINING_TARGETS
    )
    != EXPECTED_DIRECT_DATASET_TARGETS
):

    raise ValueError(
        "Block 4 expected REV, TEV, IEV and EW to be "
        "the currently eligible direct targets. "
        f"Received: {ELIGIBLE_DIRECT_TRAINING_TARGETS}"
    )


# -----------------------------------------------------------------------------
# Annotation-value helpers
# -----------------------------------------------------------------------------

def canonical_scalar_value_and_mask(
    annotation_value,
):
    """
    Convert one canonical scalar supervision object to value + mask.

    Missing / insufficient evidence is represented by:
        value = NaN
        mask  = False

    Numerical zero remains a valid observed value.
    """

    if not isinstance(
        annotation_value,
        dict,
    ):

        return (
            np.nan,
            False,
        )


    value_state = annotation_value.get(
        "value_state"
    )

    value = annotation_value.get(
        "value"
    )


    if (
        value_state == "observed"
        and value is not None
    ):

        return (
            float(
                value
            ),
            True,
        )


    return (
        np.nan,
        False,
    )


def canonical_vector_value_and_mask(
    vector_annotation,
    dimension_order,
):
    """
    Convert one canonical vector annotation to aligned values and masks.

    Each dimension is masked independently.
    """

    values = np.full(
        len(
            dimension_order
        ),
        np.nan,
        dtype=np.float32,
    )


    masks = np.zeros(
        len(
            dimension_order
        ),
        dtype=bool,
    )


    if not isinstance(
        vector_annotation,
        dict,
    ):

        return (
            values,
            masks,
        )


    for dimension_index, dimension_name in enumerate(
        dimension_order
    ):

        annotation_value = (
            vector_annotation.get(
                dimension_name
            )
        )


        value, observed = (
            canonical_scalar_value_and_mask(
                annotation_value
            )
        )


        if observed:

            values[
                dimension_index
            ] = value

            masks[
                dimension_index
            ] = True


    return (
        values,
        masks,
    )


# -----------------------------------------------------------------------------
# Canonical sentence-record construction
# -----------------------------------------------------------------------------

def canonicalise_supervision_record(
    source_record,
    source_order,
):
    """
    Convert one accepted Notebook 03 canonical supervision record into
    the native Notebook 05 sequential training-record representation.
    """

    identity = source_record.get(
        "identity",
        {},
    )

    context = source_record.get(
        "context",
        {},
    )

    annotations = source_record.get(
        "annotations",
        {},
    )


    article_id = identity.get(
        "media_ai_record_id"
    )

    sentence_id = identity.get(
        "sentence_id"
    )

    sentence_index = identity.get(
        "sentence_index"
    )

    paragraph_id = identity.get(
        "paragraph_id"
    )

    paragraph_index = identity.get(
        "paragraph_index"
    )


    sentence_text = context.get(
        "current_sentence"
    )

    article_title = context.get(
        "article_title"
    )

    context_scope = context.get(
        "context_scope"
    )

    preceding_context = context.get(
        "preceding_context"
    )


    if not article_id:

        raise ValueError(
            "Accepted supervision record has no "
            "Media AI article identifier."
        )


    if not sentence_id:

        raise ValueError(
            "Accepted supervision record has no sentence identifier."
        )


    if sentence_index is None:

        raise ValueError(
            "Accepted supervision record has no sentence index."
        )


    try:

        sentence_index = int(
            sentence_index
        )

    except (
        TypeError,
        ValueError,
    ) as exc:

        raise ValueError(
            "Sentence index must be integer-compatible."
        ) from exc


    if (
        not isinstance(
            sentence_text,
            str,
        )
        or not sentence_text.strip()
    ):

        raise ValueError(
            "Accepted supervision record has no valid current sentence."
        )


    # -------------------------------------------------------------------------
    # Psychological target construction
    # -------------------------------------------------------------------------

    rev_values, rev_mask = (
        canonical_vector_value_and_mask(
            annotations.get(
                "reported_emotion"
            ),
            EMOTIONAL_DIMENSION_ORDER,
        )
    )


    tev_values, tev_mask = (
        canonical_vector_value_and_mask(
            annotations.get(
                "transformative_emotion"
            ),
            EMOTIONAL_DIMENSION_ORDER,
        )
    )


    iev_values, iev_mask = (
        canonical_vector_value_and_mask(
            annotations.get(
                "immediate_emotional_state"
            ),
            EMOTIONAL_DIMENSION_ORDER,
        )
    )


    ew_value, ew_observed = (
        canonical_scalar_value_and_mask(
            annotations.get(
                "emotional_weight"
            )
        )
    )


    ew_values = np.asarray(
        [
            ew_value
        ],
        dtype=np.float32,
    )


    ew_mask = np.asarray(
        [
            ew_observed
        ],
        dtype=bool,
    )


    targets = {
        "REV":
            rev_values,

        "TEV":
            tev_values,

        "IEV":
            iev_values,

        "EW":
            ew_values,
    }


    target_masks = {
        "REV":
            rev_mask,

        "TEV":
            tev_mask,

        "IEV":
            iev_mask,

        "EW":
            ew_mask,
    }


    # -------------------------------------------------------------------------
    # Explicitly unavailable target families
    # -------------------------------------------------------------------------

    unavailable_targets = tuple(
        target_name

        for target_name
        in EXPECTED_SUPERVISION_TARGETS

        if target_name
        not in targets
    )


    for target_name in unavailable_targets:

        targets[
            target_name
        ] = None

        target_masks[
            target_name
        ] = None


    return {
        "article_id":
            str(
                article_id
            ),

        "article_title":
            article_title,

        "sentence_id":
            str(
                sentence_id
            ),

        "sentence_index":
            sentence_index,

        "paragraph_id":
            (
                str(
                    paragraph_id
                )
                if paragraph_id is not None
                else None
            ),

        "paragraph_index":
            paragraph_index,

        "sentence_text":
            sentence_text.strip(),

        "context_scope":
            context_scope,

        "preceding_context":
            preceding_context,

        "targets":
            targets,

        "target_masks":
            target_masks,

        "textual_representation":
            None,

        "textual_representation_available":
            False,

        "supervision_source":
            "validated_machine_supervision",

        "_source_order":
            int(
                source_order
            ),
    }


# -----------------------------------------------------------------------------
# Construct canonical sentence records
# -----------------------------------------------------------------------------

CANONICAL_SENTENCE_RECORDS = []


for source_order, source_record in enumerate(
    RAW_SUPERVISION_RECORDS
):

    CANONICAL_SENTENCE_RECORDS.append(
        canonicalise_supervision_record(
            source_record=
                source_record,

            source_order=
                source_order,
        )
    )


# -----------------------------------------------------------------------------
# Canonical identity validation
# -----------------------------------------------------------------------------

CANONICAL_SENTENCE_IDS = [
    record[
        "sentence_id"
    ]

    for record
    in CANONICAL_SENTENCE_RECORDS
]


CANONICAL_SENTENCE_IDS_PRESENT = (
    bool(
        CANONICAL_SENTENCE_IDS
    )
    and all(
        CANONICAL_SENTENCE_IDS
    )
)


CANONICAL_SENTENCE_IDS_UNIQUE = (
    CANONICAL_SENTENCE_IDS_PRESENT
    and len(
        CANONICAL_SENTENCE_IDS
    )
    == len(
        set(
            CANONICAL_SENTENCE_IDS
        )
    )
)


if not CANONICAL_SENTENCE_IDS_PRESENT:

    raise ValueError(
        "Notebook 05 canonical sequential records contain "
        "missing sentence identifiers."
    )


if not CANONICAL_SENTENCE_IDS_UNIQUE:

    raise ValueError(
        "Notebook 05 canonical sequential records contain "
        "duplicate sentence identifiers."
    )


# -----------------------------------------------------------------------------
# Article sequence construction
# -----------------------------------------------------------------------------

records_by_article = defaultdict(
    list
)


for record in CANONICAL_SENTENCE_RECORDS:

    records_by_article[
        record[
            "article_id"
        ]
    ].append(
        record
    )


ARTICLE_SEQUENCES = []


for article_id in sorted(
    records_by_article.keys()
):

    article_records = (
        records_by_article[
            article_id
        ]
    )


    article_records.sort(
        key=lambda record: (
            record[
                "sentence_index"
            ],
            record[
                "_source_order"
            ],
        )
    )


    sequence_length = len(
        article_records
    )


    for sequence_position, record in enumerate(
        article_records
    ):

        record[
            "sequence_position"
        ] = int(
            sequence_position
        )

        record[
            "sequence_length"
        ] = int(
            sequence_length
        )

        record[
            "article_start"
        ] = bool(
            sequence_position == 0
        )

        record[
            "article_end"
        ] = bool(
            sequence_position
            == sequence_length - 1
        )

        record[
            "padding_position"
        ] = False


    ARTICLE_SEQUENCES.append(
        {
            "article_id":
                article_id,

            "article_title":
                article_records[
                    0
                ].get(
                    "article_title"
                ),

            "sequence_length":
                int(
                    sequence_length
                ),

            "sentences":
                article_records,
        }
    )


# -----------------------------------------------------------------------------
# Flattened sequential dataset
# -----------------------------------------------------------------------------

SEQUENTIAL_SENTENCE_RECORDS = [
    record

    for article_sequence
    in ARTICLE_SEQUENCES

    for record
    in article_sequence[
        "sentences"
    ]
]


# -----------------------------------------------------------------------------
# Structural integrity validation
# -----------------------------------------------------------------------------

SEQUENTIAL_DATASET_ERRORS = []


for article_sequence in ARTICLE_SEQUENCES:

    article_id = article_sequence[
        "article_id"
    ]

    sentence_records = article_sequence[
        "sentences"
    ]

    sequence_length = article_sequence[
        "sequence_length"
    ]


    if sequence_length <= 0:

        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:empty_article_sequence"
        )

        continue


    sentence_indices = [
        record[
            "sentence_index"
        ]

        for record
        in sentence_records
    ]


    if len(
        sentence_indices
    ) != len(
        set(
            sentence_indices
        )
    ):

        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:duplicate_sentence_indices"
        )


    if sentence_indices != sorted(
        sentence_indices
    ):

        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:sentence_order_not_monotonic"
        )


    sequence_positions = [
        record[
            "sequence_position"
        ]

        for record
        in sentence_records
    ]


    if sequence_positions != list(
        range(
            sequence_length
        )
    ):

        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:sequence_positions_invalid"
        )


    if not sentence_records[
        0
    ][
        "article_start"
    ]:

        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:missing_article_start"
        )


    if not sentence_records[
        -1
    ][
        "article_end"
    ]:

        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:missing_article_end"
        )


    if sum(
        bool(
            record[
                "article_start"
            ]
        )
        for record
        in sentence_records
    ) != 1:

        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:invalid_start_count"
        )


    if sum(
        bool(
            record[
                "article_end"
            ]
        )
        for record
        in sentence_records
    ) != 1:

        SEQUENTIAL_DATASET_ERRORS.append(
            f"{article_id}:invalid_end_count"
        )


# -----------------------------------------------------------------------------
# Psychological supervision validation
# -----------------------------------------------------------------------------

EXPECTED_TARGET_DIMENSIONS = {
    "REV":
        11,

    "TEV":
        11,

    "IEV":
        11,

    "EW":
        1,
}


for record in SEQUENTIAL_SENTENCE_RECORDS:

    for (
        target_name,
        expected_dimensionality,
    ) in EXPECTED_TARGET_DIMENSIONS.items():

        target_value = (
            record[
                "targets"
            ][
                target_name
            ]
        )

        target_mask = (
            record[
                "target_masks"
            ][
                target_name
            ]
        )


        if not isinstance(
            target_value,
            np.ndarray,
        ):

            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                f"{target_name}_target_not_array"
            )

            continue


        if not isinstance(
            target_mask,
            np.ndarray,
        ):

            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                f"{target_name}_mask_not_array"
            )

            continue


        if target_value.shape != (
            expected_dimensionality,
        ):

            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                f"{target_name}_dimension_invalid"
            )


        if target_mask.shape != (
            expected_dimensionality,
        ):

            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                f"{target_name}_mask_dimension_invalid"
            )


        # ---------------------------------------------------------------------
        # Observed components must contain finite numeric values.
        # ---------------------------------------------------------------------

        observed_values = (
            target_value[
                target_mask
            ]
        )


        if (
            observed_values.size > 0
            and not np.all(
                np.isfinite(
                    observed_values
                )
            )
        ):

            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                f"{target_name}_observed_value_nonfinite"
            )


        # ---------------------------------------------------------------------
        # Missing components must remain missing rather than zero-filled.
        # ---------------------------------------------------------------------

        unobserved_values = (
            target_value[
                ~target_mask
            ]
        )


        if (
            unobserved_values.size > 0
            and not np.all(
                np.isnan(
                    unobserved_values
                )
            )
        ):

            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                f"{target_name}_missing_value_not_nan"
            )


# -----------------------------------------------------------------------------
# Validate unavailable target families remain unavailable
# -----------------------------------------------------------------------------

for record in SEQUENTIAL_SENTENCE_RECORDS:

    for target_name in EXPECTED_SUPERVISION_TARGETS:

        if target_name in EXPECTED_DIRECT_DATASET_TARGETS:

            continue


        if (
            record[
                "targets"
            ][
                target_name
            ]
            is not None
        ):

            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                f"unavailable_target_fabricated:{target_name}"
            )


        if (
            record[
                "target_masks"
            ][
                target_name
            ]
            is not None
        ):

            SEQUENTIAL_DATASET_ERRORS.append(
                f"{record['sentence_id']}:"
                f"unavailable_target_mask_fabricated:{target_name}"
            )


# -----------------------------------------------------------------------------
# Supervision coverage
# -----------------------------------------------------------------------------

SEQUENTIAL_SUPERVISION_COVERAGE = {}


for (
    target_name,
    target_dimensionality,
) in EXPECTED_TARGET_DIMENSIONS.items():

    sentence_count = len(
        SEQUENTIAL_SENTENCE_RECORDS
    )


    sentence_available_count = sum(
        bool(
            np.any(
                record[
                    "target_masks"
                ][
                    target_name
                ]
            )
        )

        for record
        in SEQUENTIAL_SENTENCE_RECORDS
    )


    element_available_count = sum(
        int(
            np.sum(
                record[
                    "target_masks"
                ][
                    target_name
                ]
            )
        )

        for record
        in SEQUENTIAL_SENTENCE_RECORDS
    )


    element_eligible_count = (
        sentence_count
        * target_dimensionality
    )


    sentence_coverage = (
        sentence_available_count
        / sentence_count

        if sentence_count > 0

        else 0.0
    )


    element_coverage = (
        element_available_count
        / element_eligible_count

        if element_eligible_count > 0

        else 0.0
    )


    SEQUENTIAL_SUPERVISION_COVERAGE[
        target_name
    ] = {
        "eligible_sentences":
            int(
                sentence_count
            ),

        "available_sentences":
            int(
                sentence_available_count
            ),

        "sentence_coverage":
            float(
                sentence_coverage
            ),

        "eligible_elements":
            int(
                element_eligible_count
            ),

        "available_elements":
            int(
                element_available_count
            ),

        "element_coverage":
            float(
                element_coverage
            ),
    }


# -----------------------------------------------------------------------------
# Cross-check Block 2 supervision coverage
# -----------------------------------------------------------------------------

for target_name in EXPECTED_DIRECT_DATASET_TARGETS:

    dataset_coverage = (
        SEQUENTIAL_SUPERVISION_COVERAGE[
            target_name
        ]
    )

    block_2_observation = (
        SUPERVISION_OBSERVATIONS[
            target_name
        ]
    )


    if (
        dataset_coverage[
            "available_sentences"
        ]
        != block_2_observation[
            "number_available"
        ]
    ):

        SEQUENTIAL_DATASET_ERRORS.append(
            f"{target_name}:"
            "sentence_coverage_mismatch_with_block_2"
        )


    if (
        dataset_coverage[
            "available_elements"
        ]
        != block_2_observation[
            "number_elements_available"
        ]
    ):

        SEQUENTIAL_DATASET_ERRORS.append(
            f"{target_name}:"
            "element_coverage_mismatch_with_block_2"
        )


# -----------------------------------------------------------------------------
# Contextual representation state
# -----------------------------------------------------------------------------
#
# Notebook 03 supervision records do not contain contextual embeddings.
#
# Their absence does NOT invalidate the supervised target dataset.
#
# It only prevents real model execution until a validated representation
# source is attached.
# -----------------------------------------------------------------------------

TEXTUAL_REPRESENTATION_RECORD_COUNT = len(
    SEQUENTIAL_SENTENCE_RECORDS
)


TEXTUAL_REPRESENTATION_RECORDS_AVAILABLE = sum(
    bool(
        record[
            "textual_representation_available"
        ]
    )

    for record
    in SEQUENTIAL_SENTENCE_RECORDS
)


TEXTUAL_REPRESENTATION_COVERAGE = (
    TEXTUAL_REPRESENTATION_RECORDS_AVAILABLE
    / TEXTUAL_REPRESENTATION_RECORD_COUNT

    if TEXTUAL_REPRESENTATION_RECORD_COUNT > 0

    else 0.0
)


TEXTUAL_REPRESENTATIONS_FULLY_AVAILABLE = (
    TEXTUAL_REPRESENTATION_RECORD_COUNT > 0
    and TEXTUAL_REPRESENTATION_RECORDS_AVAILABLE
    == TEXTUAL_REPRESENTATION_RECORD_COUNT
)


# -----------------------------------------------------------------------------
# Article-level experimental partitioning
# -----------------------------------------------------------------------------
#
# Partitioning remains strictly article-level.
#
# With fewer than three supervised articles, empty validation/test partitions
# are permitted. Sentences are never split across article boundaries merely to
# force three non-empty subsets.
# -----------------------------------------------------------------------------

TRAIN_FRACTION = 0.70

VALIDATION_FRACTION = 0.15

TEST_FRACTION = 0.15


if not np.isclose(
    TRAIN_FRACTION
    + VALIDATION_FRACTION
    + TEST_FRACTION,
    1.0,
):

    raise ValueError(
        "Train, validation and test fractions must sum to 1."
    )


ARTICLE_IDS = [
    article_sequence[
        "article_id"
    ]

    for article_sequence
    in ARTICLE_SEQUENCES
]


ARTICLE_PARTITION_ASSIGNMENTS = {}


if ARTICLE_IDS:

    partition_rng = random.Random(
        DATASET_RANDOM_SEED
    )


    shuffled_article_ids = list(
        ARTICLE_IDS
    )


    partition_rng.shuffle(
        shuffled_article_ids
    )


    article_count = len(
        shuffled_article_ids
    )


    if article_count >= 3:

        train_count = max(
            1,
            int(
                round(
                    article_count
                    * TRAIN_FRACTION
                )
            ),
        )


        validation_count = max(
            1,
            int(
                round(
                    article_count
                    * VALIDATION_FRACTION
                )
            ),
        )


        if (
            train_count
            + validation_count
            >= article_count
        ):

            train_count = max(
                1,
                article_count - 2,
            )

            validation_count = 1


        train_articles = shuffled_article_ids[
            :train_count
        ]


        validation_articles = shuffled_article_ids[
            train_count:
            train_count
            + validation_count
        ]


        test_articles = shuffled_article_ids[
            train_count
            + validation_count:
        ]


    elif article_count == 2:

        train_articles = [
            shuffled_article_ids[
                0
            ]
        ]

        validation_articles = []

        test_articles = [
            shuffled_article_ids[
                1
            ]
        ]


    elif article_count == 1:

        train_articles = [
            shuffled_article_ids[
                0
            ]
        ]

        validation_articles = []

        test_articles = []


    else:

        train_articles = []

        validation_articles = []

        test_articles = []


    for article_id in train_articles:

        ARTICLE_PARTITION_ASSIGNMENTS[
            article_id
        ] = "train"


    for article_id in validation_articles:

        ARTICLE_PARTITION_ASSIGNMENTS[
            article_id
        ] = "validation"


    for article_id in test_articles:

        ARTICLE_PARTITION_ASSIGNMENTS[
            article_id
        ] = "test"


# -----------------------------------------------------------------------------
# Attach partition identity
# -----------------------------------------------------------------------------

for article_sequence in ARTICLE_SEQUENCES:

    article_id = article_sequence[
        "article_id"
    ]


    partition = (
        ARTICLE_PARTITION_ASSIGNMENTS.get(
            article_id
        )
    )


    article_sequence[
        "partition"
    ] = partition


    for record in article_sequence[
        "sentences"
    ]:

        record[
            "partition"
        ] = partition


# -----------------------------------------------------------------------------
# Partition sets
# -----------------------------------------------------------------------------

TRAIN_ARTICLE_IDS = {
    article_id

    for (
        article_id,
        partition,
    )
    in ARTICLE_PARTITION_ASSIGNMENTS.items()

    if partition == "train"
}


VALIDATION_ARTICLE_IDS = {
    article_id

    for (
        article_id,
        partition,
    )
    in ARTICLE_PARTITION_ASSIGNMENTS.items()

    if partition == "validation"
}


TEST_ARTICLE_IDS = {
    article_id

    for (
        article_id,
        partition,
    )
    in ARTICLE_PARTITION_ASSIGNMENTS.items()

    if partition == "test"
}


# -----------------------------------------------------------------------------
# Partition disjointness validation
# -----------------------------------------------------------------------------

if (
    TRAIN_ARTICLE_IDS
    & VALIDATION_ARTICLE_IDS
):

    SEQUENTIAL_DATASET_ERRORS.append(
        "train_validation_article_overlap"
    )


if (
    TRAIN_ARTICLE_IDS
    & TEST_ARTICLE_IDS
):

    SEQUENTIAL_DATASET_ERRORS.append(
        "train_test_article_overlap"
    )


if (
    VALIDATION_ARTICLE_IDS
    & TEST_ARTICLE_IDS
):

    SEQUENTIAL_DATASET_ERRORS.append(
        "validation_test_article_overlap"
    )


# -----------------------------------------------------------------------------
# Target tensor helper
# -----------------------------------------------------------------------------

def target_to_tensor(
    target_values,
    target_mask,
    device=None,
):
    """
    Convert one masked target vector into tensors.

    Missing values are replaced by zero only after the Boolean mask has been
    constructed. Those placeholders are computational storage values and MUST
    remain excluded from the loss.
    """

    if device is None:

        device = MODEL_DEVICE


    values = np.asarray(
        target_values,
        dtype=np.float32,
    )


    mask = np.asarray(
        target_mask,
        dtype=bool,
    )


    if values.shape != mask.shape:

        raise ValueError(
            "Target values and target mask must have identical shapes."
        )


    tensor_values = np.where(
        mask,
        values,
        0.0,
    )


    return (
        torch.as_tensor(
            tensor_values,
            dtype=MODEL_DTYPE,
            device=device,
        ),

        torch.as_tensor(
            mask,
            dtype=torch.bool,
            device=device,
        ),
    )


# -----------------------------------------------------------------------------
# Real representation helper
# -----------------------------------------------------------------------------

def representation_to_tensor(
    representation,
):
    """
    Convert one real contextual representation to a model tensor.

    This helper refuses unavailable representations.
    """

    if representation is None:

        raise ValueError(
            "Unavailable textual representation cannot be converted "
            "into a training tensor."
        )


    if isinstance(
        representation,
        torch.Tensor,
    ):

        tensor = (
            representation
            .detach()
            .clone()
        )


    else:

        tensor = torch.as_tensor(
            representation
        )


    tensor = tensor.to(
        dtype=
            MODEL_DTYPE
    )


    if (
        tensor.shape[
            -1
        ]
        != BACKBONE_HIDDEN_DIM
    ):

        raise ValueError(
            "Contextual representation has incompatible "
            "backbone-interface dimensionality."
        )


    return tensor


# -----------------------------------------------------------------------------
# Sequential batch collator
# -----------------------------------------------------------------------------

def collate_article_sequences(
    article_sequences,
    device=None,
    require_representations=True,
):
    """
    Collate complete article sequences into one padded batch.

    Targets and element-level masks are always collated.

    Contextual representations are required only when the caller intends to
    execute the real model.
    """

    if not article_sequences:

        raise ValueError(
            "At least one article sequence is required."
        )


    if device is None:

        device = MODEL_DEVICE


    batch_size = len(
        article_sequences
    )


    max_sequence_length = max(
        sequence[
            "sequence_length"
        ]

        for sequence
        in article_sequences
    )


    padding_mask = torch.zeros(
        batch_size,
        max_sequence_length,
        dtype=torch.bool,
        device=device,
    )


    article_start_mask = torch.zeros(
        batch_size,
        max_sequence_length,
        dtype=torch.bool,
        device=device,
    )


    article_end_mask = torch.zeros(
        batch_size,
        max_sequence_length,
        dtype=torch.bool,
        device=device,
    )


    # -------------------------------------------------------------------------
    # Psychological targets
    # -------------------------------------------------------------------------

    targets = {
        "REV":
            torch.zeros(
                batch_size,
                max_sequence_length,
                11,
                dtype=MODEL_DTYPE,
                device=device,
            ),

        "TEV":
            torch.zeros(
                batch_size,
                max_sequence_length,
                11,
                dtype=MODEL_DTYPE,
                device=device,
            ),

        "IEV":
            torch.zeros(
                batch_size,
                max_sequence_length,
                11,
                dtype=MODEL_DTYPE,
                device=device,
            ),

        "EW":
            torch.zeros(
                batch_size,
                max_sequence_length,
                1,
                dtype=MODEL_DTYPE,
                device=device,
            ),
    }


    target_masks = {
        "REV":
            torch.zeros(
                batch_size,
                max_sequence_length,
                11,
                dtype=torch.bool,
                device=device,
            ),

        "TEV":
            torch.zeros(
                batch_size,
                max_sequence_length,
                11,
                dtype=torch.bool,
                device=device,
            ),

        "IEV":
            torch.zeros(
                batch_size,
                max_sequence_length,
                11,
                dtype=torch.bool,
                device=device,
            ),

        "EW":
            torch.zeros(
                batch_size,
                max_sequence_length,
                1,
                dtype=torch.bool,
                device=device,
            ),
    }


    representations = None


    if require_representations:

        representations = torch.zeros(
            batch_size,
            max_sequence_length,
            BACKBONE_HIDDEN_DIM,
            dtype=MODEL_DTYPE,
            device=device,
        )


    article_ids = []

    sentence_ids = []


    for batch_index, article_sequence in enumerate(
        article_sequences
    ):

        article_ids.append(
            article_sequence[
                "article_id"
            ]
        )


        current_sentence_ids = []


        for sentence_position, record in enumerate(
            article_sequence[
                "sentences"
            ]
        ):

            padding_mask[
                batch_index,
                sentence_position,
            ] = True


            article_start_mask[
                batch_index,
                sentence_position,
            ] = bool(
                record[
                    "article_start"
                ]
            )


            article_end_mask[
                batch_index,
                sentence_position,
            ] = bool(
                record[
                    "article_end"
                ]
            )


            current_sentence_ids.append(
                record[
                    "sentence_id"
                ]
            )


            for target_name in EXPECTED_DIRECT_DATASET_TARGETS:

                target_tensor, target_mask_tensor = (
                    target_to_tensor(
                        target_values=
                            record[
                                "targets"
                            ][
                                target_name
                            ],

                        target_mask=
                            record[
                                "target_masks"
                            ][
                                target_name
                            ],

                        device=
                            device,
                    )
                )


                targets[
                    target_name
                ][
                    batch_index,
                    sentence_position,
                ] = target_tensor


                target_masks[
                    target_name
                ][
                    batch_index,
                    sentence_position,
                ] = target_mask_tensor


            if require_representations:

                if not record[
                    "textual_representation_available"
                ]:

                    raise ValueError(
                        "Cannot collate a model-execution batch because "
                        "one or more contextual sentence representations "
                        "are unavailable."
                    )


                representations[
                    batch_index,
                    sentence_position,
                ] = representation_to_tensor(
                    record[
                        "textual_representation"
                    ]
                )


        sentence_ids.append(
            current_sentence_ids
        )


    return {
        "article_ids":
            article_ids,

        "sentence_ids":
            sentence_ids,

        "representations":
            representations,

        "targets":
            targets,

        "target_masks":
            target_masks,

        "padding_mask":
            padding_mask,

        "article_start_mask":
            article_start_mask,

        "article_end_mask":
            article_end_mask,

        "batch_size":
            int(
                batch_size
            ),

        "max_sequence_length":
            int(
                max_sequence_length
            ),

        "representations_required":
            bool(
                require_representations
            ),
    }


# -----------------------------------------------------------------------------
# Explicit structural-validation tensor helper
# -----------------------------------------------------------------------------

def create_structural_validation_batch(
    batch_size=2,
    sequence_length=3,
    seed=42,
    device=None,
):
    """
    Generate synthetic contextual representations only for computational
    structure validation.

    These are never eligible for training or empirical evaluation.
    """

    if not (
        SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_STRUCTURAL_VALIDATION
    ):

        raise ValueError(
            "Synthetic structural-validation inputs are disabled."
        )


    if batch_size <= 0:

        raise ValueError(
            "batch_size must be greater than zero."
        )


    if sequence_length <= 0:

        raise ValueError(
            "sequence_length must be greater than zero."
        )


    if device is None:

        device = MODEL_DEVICE


    generator = torch.Generator(
        device=(
            "cuda"
            if device.type == "cuda"
            else "cpu"
        )
    )


    generator.manual_seed(
        int(
            seed
        )
    )


    representations = torch.randn(
        batch_size,
        sequence_length,
        BACKBONE_HIDDEN_DIM,
        generator=generator,
        dtype=MODEL_DTYPE,
        device=device,
    )


    padding_mask = torch.ones(
        batch_size,
        sequence_length,
        dtype=torch.bool,
        device=device,
    )


    article_start_mask = torch.zeros(
        batch_size,
        sequence_length,
        dtype=torch.bool,
        device=device,
    )


    article_end_mask = torch.zeros(
        batch_size,
        sequence_length,
        dtype=torch.bool,
        device=device,
    )


    article_start_mask[
        :,
        0
    ] = True


    article_end_mask[
        :,
        -1
    ] = True


    return {
        "data_type":
            "synthetic_structural_validation_only",

        "representations":
            representations,

        "padding_mask":
            padding_mask,

        "article_start_mask":
            article_start_mask,

        "article_end_mask":
            article_end_mask,

        "batch_size":
            int(
                batch_size
            ),

        "sequence_length":
            int(
                sequence_length
            ),

        "eligible_for_training":
            False,

        "eligible_for_empirical_evaluation":
            False,
    }


# -----------------------------------------------------------------------------
# Dataset-state determination
# -----------------------------------------------------------------------------

DATASET_INPUT_AVAILABLE = bool(
    SUPERVISION_RECORD_INPUT_AVAILABLE
)


DATASET_ARTICLE_COUNT = len(
    ARTICLE_SEQUENCES
)


DATASET_SENTENCE_COUNT = len(
    SEQUENTIAL_SENTENCE_RECORDS
)


DATASET_STRUCTURAL_VALID = bool(
    DATASET_INPUT_AVAILABLE
    and DATASET_ARTICLE_COUNT > 0
    and DATASET_SENTENCE_COUNT > 0
    and len(
        SEQUENTIAL_DATASET_ERRORS
    ) == 0
)


DATASET_SUPERVISION_AVAILABLE = all(
    SEQUENTIAL_SUPERVISION_COVERAGE[
        target_name
    ][
        "available_elements"
    ]
    > 0

    for target_name
    in EXPECTED_DIRECT_DATASET_TARGETS
)


DATASET_REPRESENTATIONS_AVAILABLE = bool(
    TEXTUAL_REPRESENTATIONS_FULLY_AVAILABLE
)


DATASET_PARAMETER_POLICY_ALLOWS_TRAINING = bool(
    NOTEBOOK_05_TRAINABLE_PARAMETER_GROUPS_ACTIVATED
)


# -----------------------------------------------------------------------------
# Objective state
# -----------------------------------------------------------------------------
#
# Block 4 constructs data and masks only.
#
# Block 5 remains responsible for loss assembly and objective activation.
# -----------------------------------------------------------------------------

DATASET_OBJECTIVE_DEFINED = False


DATASET_SUPERVISED_TARGET_DATA_READY = bool(
    DATASET_STRUCTURAL_VALID
    and DATASET_SUPERVISION_AVAILABLE
    and DATASET_PARAMETER_POLICY_ALLOWS_TRAINING
)


DATASET_MODEL_EXECUTION_READY = bool(
    DATASET_SUPERVISED_TARGET_DATA_READY
    and DATASET_REPRESENTATIONS_AVAILABLE
)


DATASET_SUPERVISED_TRAINING_READY = bool(
    DATASET_MODEL_EXECUTION_READY
    and DATASET_OBJECTIVE_DEFINED
)


# -----------------------------------------------------------------------------
# Training dataset construction state
# -----------------------------------------------------------------------------

NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED = bool(
    DATASET_STRUCTURAL_VALID
)


NOTEBOOK_05_SEQUENTIAL_BATCH_CONTRACT_DEFINED = True


NOTEBOOK_05_ARTICLE_PARTITIONS_CONSTRUCTED = bool(
    ARTICLE_PARTITION_ASSIGNMENTS
)


NOTEBOOK_05_TEXTUAL_REPRESENTATIONS_AVAILABLE = (
    DATASET_REPRESENTATIONS_AVAILABLE
)


NOTEBOOK_05_SUPERVISED_TARGET_DATA_READY = (
    DATASET_SUPERVISED_TARGET_DATA_READY
)


NOTEBOOK_05_MODEL_EXECUTION_READY = (
    DATASET_MODEL_EXECUTION_READY
)


NOTEBOOK_05_SUPERVISED_TRAINING_READY = (
    DATASET_SUPERVISED_TRAINING_READY
)


# -----------------------------------------------------------------------------
# Downstream execution boundary
# -----------------------------------------------------------------------------

NOTEBOOK_05_OPTIMIZER_CREATED = False

NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED = False

NOTEBOOK_05_LOSS_CALCULATED = False

NOTEBOOK_05_TRAINING_EXECUTED = False

NOTEBOOK_05_CHECKPOINT_SELECTED = False

NOTEBOOK_05_ABLATION_EXECUTED = False

NOTEBOOK_05_EVALUATION_EXECUTED = False

NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED = False


# -----------------------------------------------------------------------------
# Block 4 methodological validation
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_4_ERRORS = []


if SENTENCE_RANDOMISATION_WITHIN_ARTICLE:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "sentence_randomisation_incorrectly_enabled"
    )


if CROSS_ARTICLE_RECURRENCE_ALLOWED:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "cross_article_recurrence_incorrectly_enabled"
    )


if FUTURE_CONTEXT_ALLOWED:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "future_context_incorrectly_allowed"
    )


if PADDING_IS_TEXT:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "padding_incorrectly_defined_as_text"
    )


if MISSING_TARGET_EQUALS_ZERO:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "missing_target_incorrectly_equals_zero"
    )


if MISSING_TARGET_EQUALS_NEGATIVE:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "missing_target_incorrectly_equals_negative"
    )


if SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_TRAINING:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "synthetic_representations_incorrectly_allowed_for_training"
    )


if MODEL_PREDICTED_GROUPS_AUTO_ACCEPTED:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "predicted_groups_incorrectly_auto_accepted"
    )


if not DATASET_STRUCTURAL_VALID:

    NOTEBOOK_05_BLOCK_4_ERRORS.extend(
        SEQUENTIAL_DATASET_ERRORS
    )


if not DATASET_SUPERVISION_AVAILABLE:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "validated_psychological_supervision_not_attached"
    )


if NOTEBOOK_05_OPTIMIZER_CREATED:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "optimizer_incorrectly_created_in_block_4"
    )


if NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "forward_pass_incorrectly_executed_in_block_4"
    )


if NOTEBOOK_05_LOSS_CALCULATED:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "loss_incorrectly_calculated_in_block_4"
    )


if NOTEBOOK_05_TRAINING_EXECUTED:

    NOTEBOOK_05_BLOCK_4_ERRORS.append(
        "training_incorrectly_executed_in_block_4"
    )


NOTEBOOK_05_BLOCK_4_VALID = (
    len(
        NOTEBOOK_05_BLOCK_4_ERRORS
    )
    == 0
)


if not NOTEBOOK_05_BLOCK_4_VALID:

    raise ValueError(
        "Notebook 05 Block 4 sequential dataset validation failed: "
        f"{NOTEBOOK_05_BLOCK_4_ERRORS}"
    )


# -----------------------------------------------------------------------------
# Block completion
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_4_COMPLETE = True


# -----------------------------------------------------------------------------
# Compact sentence-record view
# -----------------------------------------------------------------------------

SEQUENTIAL_SENTENCE_VIEW_ROWS = []


for record in SEQUENTIAL_SENTENCE_RECORDS:

    observed_target_elements = sum(
        int(
            np.sum(
                record[
                    "target_masks"
                ][
                    target_name
                ]
            )
        )

        for target_name
        in EXPECTED_DIRECT_DATASET_TARGETS
    )


    possible_target_elements = (
        11
        + 11
        + 11
        + 1
    )


    SEQUENTIAL_SENTENCE_VIEW_ROWS.append(
        {
            "article_id":
                record[
                    "article_id"
                ],

            "sentence_id":
                record[
                    "sentence_id"
                ],

            "sentence_index":
                record[
                    "sentence_index"
                ],

            "sequence_position":
                record[
                    "sequence_position"
                ],

            "sequence_length":
                record[
                    "sequence_length"
                ],

            "article_start":
                record[
                    "article_start"
                ],

            "article_end":
                record[
                    "article_end"
                ],

            "partition":
                record[
                    "partition"
                ],

            "representation_available":
                record[
                    "textual_representation_available"
                ],

            "observed_target_elements":
                int(
                    observed_target_elements
                ),

            "possible_target_elements":
                int(
                    possible_target_elements
                ),

            "target_element_coverage":
                float(
                    observed_target_elements
                    / possible_target_elements
                ),

            "sentence_text":
                record[
                    "sentence_text"
                ],
        }
    )


SEQUENTIAL_SENTENCE_VIEW = pd.DataFrame(
    SEQUENTIAL_SENTENCE_VIEW_ROWS
)


# -----------------------------------------------------------------------------
# Block 4 summary
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_4_SUMMARY = {
    "block":
        NOTEBOOK_05_BLOCK_4,

    "block_name":
        NOTEBOOK_05_BLOCK_4_NAME,

    "dataset_version":
        SEQUENTIAL_DATASET_VERSION,

    "created_at_utc":
        SEQUENTIAL_DATASET_CREATED_AT_UTC,

    "sentence_record_source_object":
        SUPERVISION_RECORD_SOURCE_OBJECT,

    "input_available":
        DATASET_INPUT_AVAILABLE,

    "article_count":
        DATASET_ARTICLE_COUNT,

    "sentence_count":
        DATASET_SENTENCE_COUNT,

    "structural_valid":
        DATASET_STRUCTURAL_VALID,

    "supervision_available":
        DATASET_SUPERVISION_AVAILABLE,

    "supervision_coverage":
        deepcopy(
            SEQUENTIAL_SUPERVISION_COVERAGE
        ),

    "representations_available":
        DATASET_REPRESENTATIONS_AVAILABLE,

    "representation_coverage":
        TEXTUAL_REPRESENTATION_COVERAGE,

    "article_partitions_constructed":
        NOTEBOOK_05_ARTICLE_PARTITIONS_CONSTRUCTED,

    "train_article_count":
        len(
            TRAIN_ARTICLE_IDS
        ),

    "validation_article_count":
        len(
            VALIDATION_ARTICLE_IDS
        ),

    "test_article_count":
        len(
            TEST_ARTICLE_IDS
        ),

    "sequential_batch_contract_defined":
        NOTEBOOK_05_SEQUENTIAL_BATCH_CONTRACT_DEFINED,

    "training_data_constructed":
        NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED,

    "supervised_target_data_ready":
        NOTEBOOK_05_SUPERVISED_TARGET_DATA_READY,

    "model_execution_ready":
        NOTEBOOK_05_MODEL_EXECUTION_READY,

    "supervised_training_ready":
        NOTEBOOK_05_SUPERVISED_TRAINING_READY,

    "optimizer_created":
        NOTEBOOK_05_OPTIMIZER_CREATED,

    "forward_pass_executed":
        NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED,

    "training_executed":
        NOTEBOOK_05_TRAINING_EXECUTED,

    "block_valid":
        NOTEBOOK_05_BLOCK_4_VALID,

    "block_complete":
        NOTEBOOK_05_BLOCK_4_COMPLETE,
}


# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------

print("=" * 72)

print(
    "Media AI — Notebook 05, Block 4: "
    "Training Dataset and Sequential Batch Construction"
)

print("=" * 72)


print(
    f"Dataset version              : "
    f"{SEQUENTIAL_DATASET_VERSION}"
)

print(
    f"Sequence unit                : "
    f"{SEQUENCE_UNIT}"
)

print(
    f"Project random seed          : "
    f"{DATASET_RANDOM_SEED}"
)


print("-" * 72)

print(
    "Native supervision input"
)

print(
    f"Source object                : "
    f"{SUPERVISION_RECORD_SOURCE_OBJECT}"
)

print(
    f"Accepted records available   : "
    f"{DATASET_INPUT_AVAILABLE}"
)

print(
    f"Input record count           : "
    f"{len(RAW_SUPERVISION_RECORDS)}"
)

print(
    f"Sentence IDs present         : "
    f"{CANONICAL_SENTENCE_IDS_PRESENT}"
)

print(
    f"Sentence IDs unique          : "
    f"{CANONICAL_SENTENCE_IDS_UNIQUE}"
)


print("-" * 72)

print(
    "Sequential dataset"
)

print(
    f"Article sequences            : "
    f"{DATASET_ARTICLE_COUNT}"
)

print(
    f"Sentence records             : "
    f"{DATASET_SENTENCE_COUNT}"
)

print(
    f"Structural dataset valid     : "
    f"{DATASET_STRUCTURAL_VALID}"
)

print(
    f"Sentence order required      : "
    f"{SEQUENCE_ORDER_REQUIRED}"
)

print(
    f"Within-article shuffle       : "
    f"{SENTENCE_RANDOMISATION_WITHIN_ARTICLE}"
)

print(
    f"Article reset required       : "
    f"{ARTICLE_BOUNDARY_RESET_REQUIRED}"
)

print(
    f"Cross-article recurrence     : "
    f"{CROSS_ARTICLE_RECURRENCE_ALLOWED}"
)

print(
    f"Future context allowed       : "
    f"{FUTURE_CONTEXT_ALLOWED}"
)


print("-" * 72)

print(
    "Psychological supervision"
)


for target_name in EXPECTED_DIRECT_DATASET_TARGETS:

    coverage_record = (
        SEQUENTIAL_SUPERVISION_COVERAGE[
            target_name
        ]
    )


    print(
        f"{target_name:<5}"
        f" sentences available / eligible : "
        f"{coverage_record['available_sentences']} / "
        f"{coverage_record['eligible_sentences']}"
    )


    print(
        f"{target_name:<5}"
        f" elements available / eligible  : "
        f"{coverage_record['available_elements']} / "
        f"{coverage_record['eligible_elements']}"
    )


    print(
        f"{target_name:<5}"
        f" element coverage               : "
        f"{coverage_record['element_coverage']:.4f}"
    )


print(
    f"Validated supervision avail. : "
    f"{DATASET_SUPERVISION_AVAILABLE}"
)

print(
    f"Missing target = zero        : "
    f"{MISSING_TARGET_EQUALS_ZERO}"
)

print(
    f"Missing target = negative    : "
    f"{MISSING_TARGET_EQUALS_NEGATIVE}"
)


print("-" * 72)

print(
    "Contextual representations"
)

print(
    f"Backbone interface dimension : "
    f"{BACKBONE_HIDDEN_DIM}"
)

print(
    f"Representations available    : "
    f"{TEXTUAL_REPRESENTATION_RECORDS_AVAILABLE}"
)

print(
    f"Representation capacity      : "
    f"{TEXTUAL_REPRESENTATION_RECORD_COUNT}"
)

print(
    f"Representation coverage      : "
    f"{TEXTUAL_REPRESENTATION_COVERAGE:.4f}"
)

print(
    f"Fully available              : "
    f"{DATASET_REPRESENTATIONS_AVAILABLE}"
)

print(
    f"Synthetic allowed training   : "
    f"{SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_TRAINING}"
)

print(
    f"Synthetic structural test    : "
    f"{SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_STRUCTURAL_VALIDATION}"
)


print("-" * 72)

print(
    "Article partitions"
)

print(
    f"Partitioning level           : "
    f"article"
)

print(
    f"Train articles               : "
    f"{len(TRAIN_ARTICLE_IDS)}"
)

print(
    f"Validation articles          : "
    f"{len(VALIDATION_ARTICLE_IDS)}"
)

print(
    f"Test articles                : "
    f"{len(TEST_ARTICLE_IDS)}"
)

print(
    f"Partitions constructed       : "
    f"{NOTEBOOK_05_ARTICLE_PARTITIONS_CONSTRUCTED}"
)


print("-" * 72)

print(
    "Batch contract"
)

print(
    f"Variable lengths supported   : "
    f"{True}"
)

print(
    f"Padding is textual content   : "
    f"{PADDING_IS_TEXT}"
)

print(
    f"Padding mask required        : "
    f"{True}"
)

print(
    f"Element target masks         : "
    f"{True}"
)

print(
    f"Group path optional          : "
    f"{True}"
)

print(
    f"Predicted groups auto-used   : "
    f"{MODEL_PREDICTED_GROUPS_AUTO_ACCEPTED}"
)


print("-" * 72)

print(
    "Readiness layers"
)

print(
    f"Dataset structural valid     : "
    f"{DATASET_STRUCTURAL_VALID}"
)

print(
    f"Validated supervision avail. : "
    f"{DATASET_SUPERVISION_AVAILABLE}"
)

print(
    f"Parameter policy allows      : "
    f"{DATASET_PARAMETER_POLICY_ALLOWS_TRAINING}"
)

print(
    f"Supervised target data ready : "
    f"{DATASET_SUPERVISED_TARGET_DATA_READY}"
)

print(
    f"Representations available    : "
    f"{DATASET_REPRESENTATIONS_AVAILABLE}"
)

print(
    f"Model execution ready        : "
    f"{DATASET_MODEL_EXECUTION_READY}"
)

print(
    f"Objective defined            : "
    f"{DATASET_OBJECTIVE_DEFINED}"
)

print(
    f"Supervised training ready    : "
    f"{DATASET_SUPERVISED_TRAINING_READY}"
)


print("-" * 72)

print(
    "Execution state"
)

print(
    f"Batch contract defined       : "
    f"{NOTEBOOK_05_SEQUENTIAL_BATCH_CONTRACT_DEFINED}"
)

print(
    f"Training data constructed    : "
    f"{NOTEBOOK_05_TRAINING_DATA_CONSTRUCTED}"
)

print(
    f"Optimizer created            : "
    f"{NOTEBOOK_05_OPTIMIZER_CREATED}"
)

print(
    f"Forward pass executed        : "
    f"{NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_05_LOSS_CALCULATED}"
)

print(
    f"Training executed            : "
    f"{NOTEBOOK_05_TRAINING_EXECUTED}"
)

print(
    f"Evaluation executed          : "
    f"{NOTEBOOK_05_EVALUATION_EXECUTED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_05_BLOCK_4_VALID}"
)

print(
    f"Block 4 complete             : "
    f"{NOTEBOOK_05_BLOCK_4_COMPLETE}"
)


print("=" * 72)


print(
    "Sequential supervision dataset and batch contract constructed "
    "successfully."
)

print(
    "Notebook 05 Block 4 uses the persisted accepted Notebook 03 "
    "canonical supervision records directly."
)

print(
    "No generic runtime sentence-record discovery or synthetic sentence "
    "construction has been used."
)

print(
    "Media AI record identity defines article identity and canonical "
    "sentence indices define within-article order."
)

print(
    "REV, TEV, IEV and EW supervision has been attached directly from "
    "validated canonical Notebook 03 annotations."
)

print(
    "REV, TEV and IEV retain independent eleven-dimensional element masks."
)

print(
    "EW retains an independent scalar mask."
)

print(
    "Insufficient-evidence dimensions remain masked and have not been "
    "converted to numerical zero."
)

print(
    "Factual, social, architectural transformation, Transformative Weight "
    "and recurrent-state targets remain unavailable rather than fabricated."
)

print(
    "The supervised target dataset is valid independently of contextual "
    "representation availability."
)

print(
    "Validated contextual sentence representations are not yet available "
    "in the current persisted source."
)

print(
    "Their absence prevents real model execution but does not invalidate "
    "the supervision dataset."
)

print(
    "Synthetic representations remain prohibited for training and may be "
    "used only for explicit structural forward validation."
)

print(
    "Article-level partitioning preserves independent article boundaries."
)

print(
    "No recurrent connection is permitted across independent articles."
)

print(
    "No future-context access has been introduced."
)

print(
    "No optimiser, forward pass, loss calculation, optimisation, training "
    "or empirical evaluation has been executed."
)

print(
    "Block 5 may proceed to Loss Assembly, Objective Activation and "
    "Optimiser Policy while representation availability remains an "
    "independent model-execution prerequisite."
)


# -----------------------------------------------------------------------------
# Display sequential dataset view
# -----------------------------------------------------------------------------

if not SEQUENTIAL_SENTENCE_VIEW.empty:

    display(
        SEQUENTIAL_SENTENCE_VIEW
    )

========================================================================
Media AI — Notebook 05, Block 4: Training Dataset and Sequential Batch Construction
========================================================================
Dataset version              : 1.1
Sequence unit                : sentence
Project random seed          : 42
------------------------------------------------------------------------
Native supervision input
Source object                : NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS
Accepted records available   : True
Input record count           : 16
Sentence IDs present         : True
Sentence IDs unique          : True
------------------------------------------------------------------------
Sequential dataset
Article sequences            : 1
Sentence records             : 16
Structural dataset valid     : True
Sentence order required      : True
Within-article shuffle       : False
Article reset required       : True
Cross-article recurrence     : False
Future context allowed       : False
------------------------------------------------------------------------
Psychological supervision
REV   sentences available / eligible : 16 / 16
REV   elements available / eligible  : 40 / 176
REV   element coverage               : 0.2273
TEV   sentences available / eligible : 16 / 16
TEV   elements available / eligible  : 176 / 176
TEV   element coverage               : 1.0000
IEV   sentences available / eligible : 16 / 16
IEV   elements available / eligible  : 176 / 176
IEV   element coverage               : 1.0000
EW    sentences available / eligible : 16 / 16
EW    elements available / eligible  : 16 / 16
EW    element coverage               : 1.0000
Validated supervision avail. : True
Missing target = zero        : False
Missing target = negative    : False
------------------------------------------------------------------------
Contextual representations
Backbone interface dimension : 768
Representations available    : 0
Representation capacity      : 16
Representation coverage      : 0.0000
Fully available              : False
Synthetic allowed training   : False
Synthetic structural test    : True
------------------------------------------------------------------------
Article partitions
Partitioning level           : article
Train articles               : 1
Validation articles          : 0
Test articles                : 0
Partitions constructed       : True
------------------------------------------------------------------------
Batch contract
Variable lengths supported   : True
Padding is textual content   : False
Padding mask required        : True
Element target masks         : True
Group path optional          : True
Predicted groups auto-used   : False
------------------------------------------------------------------------
Readiness layers
Dataset structural valid     : True
Validated supervision avail. : True
Parameter policy allows      : True
Supervised target data ready : True
Representations available    : False
Model execution ready        : False
Objective defined            : False
Supervised training ready    : False
------------------------------------------------------------------------
Execution state
Batch contract defined       : True
Training data constructed    : True
Optimizer created            : False
Forward pass executed        : False
Loss calculated              : False
Training executed            : False
Evaluation executed          : False
Block valid                  : True
Block 4 complete             : True
========================================================================
Sequential supervision dataset and batch contract constructed successfully.
Notebook 05 Block 4 uses the persisted accepted Notebook 03 canonical supervision records directly.
No generic runtime sentence-record discovery or synthetic sentence construction has been used.
Media AI record identity defines article identity and canonical sentence indices define within-article order.
REV, TEV, IEV and EW supervision has been attached directly from validated canonical Notebook 03 annotations.
REV, TEV and IEV retain independent eleven-dimensional element masks.
EW retains an independent scalar mask.
Insufficient-evidence dimensions remain masked and have not been converted to numerical zero.
Factual, social, architectural transformation, Transformative Weight and recurrent-state targets remain unavailable rather than fabricated.
The supervised target dataset is valid independently of contextual representation availability.
Validated contextual sentence representations are not yet available in the current persisted source.
Their absence prevents real model execution but does not invalidate the supervision dataset.
Synthetic representations remain prohibited for training and may be used only for explicit structural forward validation.
Article-level partitioning preserves independent article boundaries.
No recurrent connection is permitted across independent articles.
No future-context access has been introduced.
No optimiser, forward pass, loss calculation, optimisation, training or empirical evaluation has been executed.
Block 5 may proceed to Loss Assembly, Objective Activation and Optimiser Policy while representation availability remains an independent model-execution prerequisite.

,article_id,sentence_id,sentence_index,sequence_position,sequence_length,article_start,article_end,partition,representation_available,observed_target_elements,possible_target_elements,target_element_coverage,sentence_text
0,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,0,0,16,True,False,train,False,25,34,0.735294,Fifa has issued a new statement alleging there...
1,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,1,1,16,False,False,train,False,26,34,0.764706,The governing body issued the statement in res...
2,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,2,2,16,False,False,train,False,25,34,0.735294,The Daily Telegraph reported on Friday night t...
3,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,3,3,16,False,False,train,False,25,34,0.735294,"In a statement, Uefa confirmed a payment was m..."
4,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,4,4,16,False,False,train,False,25,34,0.735294,Fifa told the Telegraph that “any insinuation ...
5,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,5,5,16,False,False,train,False,25,34,0.735294,A Fifa spokesperson said: “The Fifa president ...
6,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,6,6,16,False,False,train,False,25,34,0.735294,It is increasingly evident that there is a con...
7,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,7,7,16,False,False,train,False,26,34,0.764706,“Those who do not have the support of Fifa’s m...
8,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,8,8,16,False,False,train,False,26,34,0.764706,Recent reporting has included unsubstantiated ...
9,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,9,9,16,False,False,train,False,27,34,0.794118,Speculation and insinuation should not be pres...
10,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,10,10,16,False,False,train,False,26,34,0.764706,But scrutiny is not a licence to distort facts...
11,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,11,11,16,False,False,train,False,25,34,0.735294,"“Where reporting is inaccurate or misleading, ..."
12,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,12,12,16,False,False,train,False,25,34,0.735294,Fifa’s responsibility is to its 211 member ass...
13,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,13,13,16,False,False,train,False,25,34,0.735294,We will not be distracted or diverted from str...
14,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,14,14,16,False,False,train,False,25,34,0.735294,Fifa has said it will not accept any challenge...
15,1ef9745c-2c21-47c2-a222-e7c160448f82,1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s...,15,15,16,False,True,train,False,27,34,0.794118,Uefa’s threat that its 55 member countries cou...

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Representation Source Inventory Diagnostic
# =============================================================================

import numpy as np
import pandas as pd
import torch


print("=" * 72)
print(
    "Media AI — Notebook 05 "
    "Contextual Representation Source Inventory"
)
print("=" * 72)


# -----------------------------------------------------------------------------
# Candidate runtime object names
# -----------------------------------------------------------------------------

candidate_object_names = [
    # Explicit Notebook 05 candidates
    "NOTEBOOK_05_SENTENCE_REPRESENTATIONS",
    "NOTEBOOK_05_SENTENCE_EMBEDDINGS",
    "NOTEBOOK_05_SENTENCE_RECORDS",

    # Prepared / upstream sentence objects
    "PREPARED_SENTENCE_RECORDS",
    "SUPERVISION_CONTEXT_RECORDS",

    # Generic representation candidates
    "SENTENCE_REPRESENTATIONS",
    "SENTENCE_EMBEDDINGS",
    "TEXTUAL_REPRESENTATIONS",
    "CONTEXTUAL_EMBEDDINGS",
    "MODEL_SENTENCE_RECORDS",

    # Notebook 04 / architecture handover candidates
    "NOTEBOOK_05_HANDOVER",
    "NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS",
]


print(
    "Candidate runtime objects"
)

for object_name in candidate_object_names:

    print(
        f"{object_name:<40}: "
        f"{object_name in globals()}"
    )


# -----------------------------------------------------------------------------
# Representation-related globals
# -----------------------------------------------------------------------------

print("-" * 72)

representation_related_globals = sorted([
    name
    for name in globals()
    if any(
        token in name.lower()
        for token in (
            "embedding",
            "representation",
            "vector",
            "sentence_record",
            "prepared_sentence",
        )
    )
])


print(
    "Representation-related globals"
)

for name in representation_related_globals:

    try:
        value = globals()[
            name
        ]

        print(
            f"{name:<45}: "
            f"{type(value).__name__}"
        )

    except Exception:
        print(
            f"{name:<45}: "
            "unreadable"
        )


# -----------------------------------------------------------------------------
# Helper functions
# -----------------------------------------------------------------------------

def inspect_candidate_records(
    object_name,
    candidate_object,
):
    """
    Inspect a possible record collection without modifying it.
    """

    print("-" * 72)

    print(
        f"Object: {object_name}"
    )

    print(
        f"Type  : {type(candidate_object).__name__}"
    )


    records = None


    if isinstance(
        candidate_object,
        pd.DataFrame,
    ):
        records = candidate_object.to_dict(
            orient="records"
        )


    elif isinstance(
        candidate_object,
        (list, tuple),
    ):

        if all(
            isinstance(
                item,
                dict,
            )
            for item
            in candidate_object
        ):
            records = list(
                candidate_object
            )


    if records is None:

        if isinstance(
            candidate_object,
            dict,
        ):
            print(
                "Top-level keys:",
                sorted(
                    candidate_object.keys()
                ),
            )

        return


    print(
        f"Record count : "
        f"{len(records)}"
    )


    if not records:

        return


    first_record = records[
        0
    ]


    print(
        "First-record keys:",
        sorted(
            first_record.keys()
        ),
    )


    # -------------------------------------------------------------------------
    # Common identity fields
    # -------------------------------------------------------------------------

    sentence_id = None

    article_id = None


    for field_name in (
        "sentence_id",
        "sentenceId",
    ):

        if field_name in first_record:

            sentence_id = first_record[
                field_name
            ]

            break


    for field_name in (
        "article_id",
        "articleId",
        "media_ai_record_id",
    ):

        if field_name in first_record:

            article_id = first_record[
                field_name
            ]

            break


    if isinstance(
        first_record.get(
            "identity"
        ),
        dict,
    ):

        sentence_id = (
            first_record[
                "identity"
            ].get(
                "sentence_id",
                sentence_id,
            )
        )

        article_id = (
            first_record[
                "identity"
            ].get(
                "media_ai_record_id",
                article_id,
            )
        )


    print(
        f"Sentence ID present : "
        f"{sentence_id is not None}"
    )

    print(
        f"Article ID present  : "
        f"{article_id is not None}"
    )


    # -------------------------------------------------------------------------
    # Search for representation-like fields
    # -------------------------------------------------------------------------

    representation_fields = []


    for field_name, value in first_record.items():

        lower_name = field_name.lower()


        if any(
            token in lower_name
            for token in (
                "embedding",
                "representation",
                "vector",
            )
        ):

            representation_fields.append(
                field_name
            )


    print(
        "Representation-like fields:",
        representation_fields
    )


    # -------------------------------------------------------------------------
    # Inspect shape where possible
    # -------------------------------------------------------------------------

    for field_name in representation_fields:

        value = first_record[
            field_name
        ]


        if isinstance(
            value,
            torch.Tensor,
        ):

            shape = tuple(
                value.shape
            )


        else:

            try:
                shape = tuple(
                    np.asarray(
                        value
                    ).shape
                )

            except Exception:
                shape = None


        print(
            f"  {field_name:<30} "
            f"type={type(value).__name__:<15} "
            f"shape={shape}"
        )


# -----------------------------------------------------------------------------
# Inspect promising objects
# -----------------------------------------------------------------------------

for object_name in representation_related_globals:

    if object_name.startswith(
        "_"
    ):
        continue


    candidate_object = globals()[
        object_name
    ]


    if isinstance(
        candidate_object,
        (
            list,
            tuple,
            dict,
            pd.DataFrame,
        ),
    ):

        inspect_candidate_records(
            object_name=
                object_name,

            candidate_object=
                candidate_object,
        )


# -----------------------------------------------------------------------------
# Current Block 4 sentence identity contract
# -----------------------------------------------------------------------------

print("-" * 72)

print(
    "Current Block 4 sentence contract"
)


if "SEQUENTIAL_SENTENCE_RECORDS" in globals():

    current_sentence_ids = [
        record.get(
            "sentence_id"
        )

        for record
        in SEQUENTIAL_SENTENCE_RECORDS
    ]


    print(
        f"Sequential sentence records : "
        f"{len(SEQUENTIAL_SENTENCE_RECORDS)}"
    )

    print(
        f"Sentence IDs present        : "
        f"{bool(current_sentence_ids) and all(current_sentence_ids)}"
    )

    print(
        f"Sentence IDs unique         : "
        f"{len(current_sentence_ids) == len(set(current_sentence_ids))}"
    )

else:

    print(
        "SEQUENTIAL_SENTENCE_RECORDS is not available."
    )


print("=" * 72)

print(
    "Representation-source inventory diagnostic completed."
)

print(
    "No model, embedding generator, optimiser, forward pass or "
    "training operation has been executed."
)

========================================================================
Media AI — Notebook 05 Contextual Representation Source Inventory
========================================================================
Candidate runtime objects
NOTEBOOK_05_SENTENCE_REPRESENTATIONS    : False
NOTEBOOK_05_SENTENCE_EMBEDDINGS         : False
NOTEBOOK_05_SENTENCE_RECORDS            : False
PREPARED_SENTENCE_RECORDS               : False
SUPERVISION_CONTEXT_RECORDS             : False
SENTENCE_REPRESENTATIONS                : False
SENTENCE_EMBEDDINGS                     : False
TEXTUAL_REPRESENTATIONS                 : False
CONTEXTUAL_EMBEDDINGS                   : False
MODEL_SENTENCE_RECORDS                  : False
NOTEBOOK_05_HANDOVER                    : True
NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS: True
------------------------------------------------------------------------
Representation-related globals
CANONICAL_SENTENCE_RECORDS                   : list
DATASET_REPRESENTATIONS_AVAILABLE            : bool
EXPECTED_PSYCHOLOGICAL_VECTOR_DIMENSIONS     : dict
EXPECTED_PSYCHOLOGICAL_VECTOR_ORDER          : tuple
EXPECTED_REPRESENTATION_SPACES               : tuple
GROUP_EMBEDDING_DIM                          : int
NOTEBOOK_05_FACTUAL_REPRESENTATION_IS_TRUTH  : bool
NOTEBOOK_05_TEXTUAL_REPRESENTATIONS_AVAILABLE: bool
REPRESENTATION_LEVELS                        : tuple
RepresentationHeadCore                       : type
SEQUENTIAL_SENTENCE_RECORDS                  : list
SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_STRUCTURAL_VALIDATION: bool
SYNTHETIC_REPRESENTATIONS_ALLOWED_FOR_TRAINING: bool
TEXTUAL_REPRESENTATIONS_FULLY_AVAILABLE      : bool
TEXTUAL_REPRESENTATION_COVERAGE              : float
TEXTUAL_REPRESENTATION_RECORDS_AVAILABLE     : int
TEXTUAL_REPRESENTATION_RECORD_COUNT          : int
canonical_vector_value_and_mask              : function
handover_psychological_vector_dimensions     : dict
handover_psychological_vector_order          : tuple
handover_representation_spaces               : tuple
representation_space                         : str
representation_to_tensor                     : function
sentence_records                             : list
sentence_records_fully_supervised            : int
sentence_records_with_any_supervision        : int
vector_annotation_availability               : function
------------------------------------------------------------------------
Object: CANONICAL_SENTENCE_RECORDS
Type  : list
Record count : 16
First-record keys: ['_source_order', 'article_end', 'article_id', 'article_start', 'article_title', 'context_scope', 'padding_position', 'paragraph_id', 'paragraph_index', 'partition', 'preceding_context', 'sentence_id', 'sentence_index', 'sentence_text', 'sequence_length', 'sequence_position', 'supervision_source', 'target_masks', 'targets', 'textual_representation', 'textual_representation_available']
Sentence ID present : True
Article ID present  : True
Representation-like fields: ['textual_representation', 'textual_representation_available']
  textual_representation         type=NoneType        shape=()
  textual_representation_available type=bool            shape=()
------------------------------------------------------------------------
Object: EXPECTED_PSYCHOLOGICAL_VECTOR_DIMENSIONS
Type  : dict
Top-level keys: ['EW', 'IEV', 'REV', 'TEV']
------------------------------------------------------------------------
Object: EXPECTED_PSYCHOLOGICAL_VECTOR_ORDER
Type  : tuple
------------------------------------------------------------------------
Object: EXPECTED_REPRESENTATION_SPACES
Type  : tuple
------------------------------------------------------------------------
Object: REPRESENTATION_LEVELS
Type  : tuple
------------------------------------------------------------------------
Object: SEQUENTIAL_SENTENCE_RECORDS
Type  : list
Record count : 16
First-record keys: ['_source_order', 'article_end', 'article_id', 'article_start', 'article_title', 'context_scope', 'padding_position', 'paragraph_id', 'paragraph_index', 'partition', 'preceding_context', 'sentence_id', 'sentence_index', 'sentence_text', 'sequence_length', 'sequence_position', 'supervision_source', 'target_masks', 'targets', 'textual_representation', 'textual_representation_available']
Sentence ID present : True
Article ID present  : True
Representation-like fields: ['textual_representation', 'textual_representation_available']
  textual_representation         type=NoneType        shape=()
  textual_representation_available type=bool            shape=()
------------------------------------------------------------------------
Object: handover_psychological_vector_dimensions
Type  : dict
Top-level keys: ['EW', 'IEV', 'REV', 'TEV']
------------------------------------------------------------------------
Object: handover_psychological_vector_order
Type  : tuple
------------------------------------------------------------------------
Object: handover_representation_spaces
Type  : tuple
------------------------------------------------------------------------
Object: sentence_records
Type  : list
Record count : 16
First-record keys: ['_source_order', 'article_end', 'article_id', 'article_start', 'article_title', 'context_scope', 'padding_position', 'paragraph_id', 'paragraph_index', 'partition', 'preceding_context', 'sentence_id', 'sentence_index', 'sentence_text', 'sequence_length', 'sequence_position', 'supervision_source', 'target_masks', 'targets', 'textual_representation', 'textual_representation_available']
Sentence ID present : True
Article ID present  : True
Representation-like fields: ['textual_representation', 'textual_representation_available']
  textual_representation         type=NoneType        shape=()
  textual_representation_available type=bool            shape=()
------------------------------------------------------------------------
Current Block 4 sentence contract
Sequential sentence records : 16
Sentence IDs present        : True
Sentence IDs unique         : True
========================================================================
Representation-source inventory diagnostic completed.
No model, embedding generator, optimiser, forward pass or training operation has been executed.

## Block 5 — Contextual Representation Generation and Validation

This block constructs the real contextual sentence representations required by the executable Media AI architecture.

No validated sentence-level representation artefact is available from the preceding notebooks. The canonical Notebook 05 training dataset therefore contains the validated supervision targets and sentence identities, but its `textual_representation` fields remain empty.

A concrete frozen sentence encoder is introduced here explicitly rather than inferred from the architectural dimensionality alone.

The selected baseline encoder is `sentence-transformers/all-mpnet-base-v2`. It maps English sentences and paragraphs to 768-dimensional dense semantic representations, matching the 768-dimensional textual-representation interface defined by the Notebook 04 architecture and instantiated in Notebook 05.

The encoder is used only as a fixed representation generator. Its parameters are not incorporated into the trainable Media AI parameter policy and are not updated during this stage.

For each canonical sentence record, this block:

- preserves the existing `sentence_id`, article identity and within-article order;
- generates exactly one 768-dimensional semantic representation from the canonical sentence text;
- verifies dimensionality, numerical finiteness and one-to-one sentence alignment;
- attaches the validated representation to the corresponding sequential sentence record;
- records the encoder identity and representation provenance; and
- persists the resulting sentence representations so that later Notebook 05 execution does not depend on the current Colab runtime.

Representation generation is performed independently for each canonical sentence. No later sentence is supplied as context when encoding an earlier sentence, so the causal supervision boundary established in the preceding notebooks is preserved.

The generated embeddings are semantic model representations rather than supervision labels or ground-truth observations. They do not alter the validated REV, TEV, IEV or EW targets and do not resolve missing supervision.

No synthetic embedding may substitute for a failed or unavailable real encoder output. Missing or invalid representations therefore remain an execution blocker rather than being replaced by random, zero or pseudo-representations.

This block performs representation inference and persistence only. It does not create an optimiser, calculate a supervised loss, update Media AI parameters, execute training, select a checkpoint, perform an ablation or establish empirical validity.

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Block 5: Contextual Representation Generation and Validation
# =============================================================================

import io
import json
import math
import subprocess
import sys

from copy import deepcopy
from datetime import datetime, timezone

import numpy as np
import torch

from googleapiclient.http import MediaIoBaseUpload


# -----------------------------------------------------------------------------
# Block dependency checks
# -----------------------------------------------------------------------------

required_block_1_objects = [
    "NOTEBOOK_05_BLOCK_1_COMPLETE",
    "NOTEBOOK_05_HANDOVER_VALID",
    "DRIVE_SERVICE_FOR_HANDOVER",
    "NOTEBOOK_05_DRIVE_SERVICE_INITIALISED",
    "NOTEBOOK_05_HANDOVER_DRIVE_FILE_ID",
]


missing_block_1_objects = [
    object_name
    for object_name
    in required_block_1_objects
    if object_name not in globals()
]


if missing_block_1_objects:

    raise NameError(
        "Notebook 05 Block 1 is not initialised. "
        f"Missing: {missing_block_1_objects}"
    )


required_block_4_objects = [
    "NOTEBOOK_05_BLOCK_4_COMPLETE",
    "NOTEBOOK_05_BLOCK_4_VALID",
    "SEQUENTIAL_SENTENCE_RECORDS",
    "CANONICAL_SENTENCE_RECORDS",
    "ARTICLE_SEQUENCES",
    "DATASET_SENTENCE_COUNT",
    "DATASET_ARTICLE_COUNT",
    "BACKBONE_HIDDEN_DIM",
    "MODEL_DEVICE",
    "MODEL_DTYPE",
]


missing_block_4_objects = [
    object_name
    for object_name
    in required_block_4_objects
    if object_name not in globals()
]


if missing_block_4_objects:

    raise NameError(
        "Notebook 05 Block 4 is not initialised. "
        f"Missing: {missing_block_4_objects}"
    )


if not NOTEBOOK_05_BLOCK_1_COMPLETE:

    raise ValueError(
        "Notebook 05 Block 1 must be complete."
    )


if not NOTEBOOK_05_DRIVE_SERVICE_INITIALISED:

    raise ValueError(
        "Notebook 05 Google Drive service is not initialised."
    )


if not NOTEBOOK_05_BLOCK_4_COMPLETE:

    raise ValueError(
        "Notebook 05 Block 4 must be complete before "
        "contextual representations are generated."
    )


if not NOTEBOOK_05_BLOCK_4_VALID:

    raise ValueError(
        "Notebook 05 Block 4 sequential dataset is invalid."
    )


if DATASET_SENTENCE_COUNT <= 0:

    raise ValueError(
        "Block 5 requires at least one canonical sentence record."
    )


# -----------------------------------------------------------------------------
# Block configuration
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_5 = 5

NOTEBOOK_05_BLOCK_5_NAME = (
    "Contextual Representation Generation and Validation"
)

CONTEXTUAL_REPRESENTATION_VERSION = "1.0"

CONTEXTUAL_REPRESENTATION_CREATED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# -----------------------------------------------------------------------------
# Encoder configuration
# -----------------------------------------------------------------------------

CONTEXTUAL_ENCODER_PROVIDER = (
    "sentence-transformers"
)

CONTEXTUAL_ENCODER_MODEL_ID = (
    "sentence-transformers/all-mpnet-base-v2"
)

CONTEXTUAL_ENCODER_EXPECTED_DIM = 768

CONTEXTUAL_ENCODER_NORMALIZE = True

CONTEXTUAL_ENCODER_BATCH_SIZE = 16

CONTEXTUAL_ENCODER_INPUT_UNIT = "sentence"

CONTEXTUAL_ENCODER_ARTICLE_CONTEXT_USED = False

CONTEXTUAL_ENCODER_FUTURE_CONTEXT_USED = False

CONTEXTUAL_ENCODER_TRAINABLE = False

CONTEXTUAL_ENCODER_SYNTHETIC_FALLBACK_ALLOWED = False


# -----------------------------------------------------------------------------
# Persistent artefact configuration
# -----------------------------------------------------------------------------

NOTEBOOK_05_REPRESENTATION_FILENAME = (
    "notebook_05_contextual_sentence_representations.json"
)

NOTEBOOK_05_REPRESENTATION_ARTIFACT_TYPE = (
    "media_ai_contextual_sentence_representations"
)

NOTEBOOK_05_REPRESENTATION_SCHEMA_VERSION = "1.0"


# -----------------------------------------------------------------------------
# Architecture compatibility
# -----------------------------------------------------------------------------

if BACKBONE_HIDDEN_DIM != CONTEXTUAL_ENCODER_EXPECTED_DIM:

    raise ValueError(
        "Selected contextual encoder does not match the "
        "Notebook 05 backbone-interface dimensionality. "
        f"Encoder: {CONTEXTUAL_ENCODER_EXPECTED_DIM}, "
        f"architecture: {BACKBONE_HIDDEN_DIM}."
    )


# -----------------------------------------------------------------------------
# Install / import Sentence Transformers
# -----------------------------------------------------------------------------

SENTENCE_TRANSFORMERS_INSTALLED_IN_BLOCK = False


try:

    import sentence_transformers

    from sentence_transformers import SentenceTransformer


except ImportError:

    subprocess.check_call(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            "-q",
            "sentence-transformers",
        ]
    )

    SENTENCE_TRANSFORMERS_INSTALLED_IN_BLOCK = True

    import sentence_transformers

    from sentence_transformers import SentenceTransformer


SENTENCE_TRANSFORMERS_VERSION = getattr(
    sentence_transformers,
    "__version__",
    "unknown",
)


# -----------------------------------------------------------------------------
# Encoder device
# -----------------------------------------------------------------------------

CONTEXTUAL_ENCODER_DEVICE = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)


# -----------------------------------------------------------------------------
# Load encoder
# -----------------------------------------------------------------------------

CONTEXTUAL_ENCODER = SentenceTransformer(
    CONTEXTUAL_ENCODER_MODEL_ID,
    device=
        CONTEXTUAL_ENCODER_DEVICE,
)


CONTEXTUAL_ENCODER.eval()


for parameter in CONTEXTUAL_ENCODER.parameters():

    parameter.requires_grad = False


CONTEXTUAL_ENCODER_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in CONTEXTUAL_ENCODER.parameters()
)


CONTEXTUAL_ENCODER_TRAINABLE_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in CONTEXTUAL_ENCODER.parameters()
    if parameter.requires_grad
)


CONTEXTUAL_ENCODER_FULLY_FROZEN = (
    CONTEXTUAL_ENCODER_TRAINABLE_PARAMETER_COUNT
    == 0
)


if not CONTEXTUAL_ENCODER_FULLY_FROZEN:

    raise ValueError(
        "The contextual sentence encoder is not fully frozen."
    )


# -----------------------------------------------------------------------------
# Validate encoder output dimensionality from model contract
# -----------------------------------------------------------------------------

CONTEXTUAL_ENCODER_REPORTED_DIM = int(
    CONTEXTUAL_ENCODER.get_sentence_embedding_dimension()
)


if (
    CONTEXTUAL_ENCODER_REPORTED_DIM
    != CONTEXTUAL_ENCODER_EXPECTED_DIM
):

    raise ValueError(
        "Sentence encoder reported an unexpected embedding dimension. "
        f"Expected {CONTEXTUAL_ENCODER_EXPECTED_DIM}, "
        f"received {CONTEXTUAL_ENCODER_REPORTED_DIM}."
    )


# -----------------------------------------------------------------------------
# Canonical sentence identity extraction
# -----------------------------------------------------------------------------

REPRESENTATION_SOURCE_SENTENCE_IDS = [
    record[
        "sentence_id"
    ]
    for record
    in SEQUENTIAL_SENTENCE_RECORDS
]


REPRESENTATION_SOURCE_SENTENCE_TEXTS = [
    record[
        "sentence_text"
    ]
    for record
    in SEQUENTIAL_SENTENCE_RECORDS
]


REPRESENTATION_SOURCE_ARTICLE_IDS = [
    record[
        "article_id"
    ]
    for record
    in SEQUENTIAL_SENTENCE_RECORDS
]


REPRESENTATION_SOURCE_SENTENCE_INDICES = [
    int(
        record[
            "sentence_index"
        ]
    )
    for record
    in SEQUENTIAL_SENTENCE_RECORDS
]


REPRESENTATION_SENTENCE_IDS_PRESENT = (
    bool(
        REPRESENTATION_SOURCE_SENTENCE_IDS
    )
    and all(
        REPRESENTATION_SOURCE_SENTENCE_IDS
    )
)


REPRESENTATION_SENTENCE_IDS_UNIQUE = (
    REPRESENTATION_SENTENCE_IDS_PRESENT
    and len(
        REPRESENTATION_SOURCE_SENTENCE_IDS
    )
    == len(
        set(
            REPRESENTATION_SOURCE_SENTENCE_IDS
        )
    )
)


REPRESENTATION_SENTENCE_TEXTS_VALID = all(
    isinstance(
        sentence_text,
        str,
    )
    and bool(
        sentence_text.strip()
    )

    for sentence_text
    in REPRESENTATION_SOURCE_SENTENCE_TEXTS
)


if not REPRESENTATION_SENTENCE_IDS_PRESENT:

    raise ValueError(
        "Block 5 source records contain missing sentence IDs."
    )


if not REPRESENTATION_SENTENCE_IDS_UNIQUE:

    raise ValueError(
        "Block 5 source records contain duplicate sentence IDs."
    )


if not REPRESENTATION_SENTENCE_TEXTS_VALID:

    raise ValueError(
        "Block 5 source records contain invalid sentence text."
    )


# -----------------------------------------------------------------------------
# Token-length diagnostic
# -----------------------------------------------------------------------------
#
# The selected encoder truncates inputs exceeding its configured maximum
# sequence length.
#
# We therefore record whether any canonical sentence reaches that limit.
# -----------------------------------------------------------------------------

ENCODER_MAX_SEQUENCE_LENGTH = int(
    CONTEXTUAL_ENCODER.max_seq_length
)


tokenizer = CONTEXTUAL_ENCODER.tokenizer


REPRESENTATION_TOKEN_LENGTHS = []


for sentence_text in REPRESENTATION_SOURCE_SENTENCE_TEXTS:

    encoded = tokenizer(
        sentence_text,
        add_special_tokens=True,
        truncation=False,
    )


    token_count = len(
        encoded[
            "input_ids"
        ]
    )


    REPRESENTATION_TOKEN_LENGTHS.append(
        int(
            token_count
        )
    )


REPRESENTATION_MAX_TOKEN_LENGTH = max(
    REPRESENTATION_TOKEN_LENGTHS
)


REPRESENTATION_TRUNCATION_RISK_COUNT = sum(
    token_count
    > ENCODER_MAX_SEQUENCE_LENGTH

    for token_count
    in REPRESENTATION_TOKEN_LENGTHS
)


REPRESENTATION_TRUNCATION_OCCURRED_BY_POLICY = (
    REPRESENTATION_TRUNCATION_RISK_COUNT
    > 0
)


if REPRESENTATION_TRUNCATION_OCCURRED_BY_POLICY:

    raise ValueError(
        "One or more canonical sentences exceed the selected encoder's "
        "maximum sequence length. Block 5 refuses silent truncation. "
        f"Maximum observed tokens: {REPRESENTATION_MAX_TOKEN_LENGTH}; "
        f"encoder limit: {ENCODER_MAX_SEQUENCE_LENGTH}."
    )


# -----------------------------------------------------------------------------
# Generate contextual sentence representations
# -----------------------------------------------------------------------------
#
# Each canonical sentence is encoded independently.
#
# No preceding or future article sentence is supplied to the encoder.
# -----------------------------------------------------------------------------

with torch.inference_mode():

    GENERATED_REPRESENTATIONS = (
        CONTEXTUAL_ENCODER.encode(
            REPRESENTATION_SOURCE_SENTENCE_TEXTS,
            batch_size=
                CONTEXTUAL_ENCODER_BATCH_SIZE,
            show_progress_bar=
                True,
            convert_to_numpy=
                True,
            normalize_embeddings=
                CONTEXTUAL_ENCODER_NORMALIZE,
        )
    )


GENERATED_REPRESENTATIONS = np.asarray(
    GENERATED_REPRESENTATIONS,
    dtype=np.float32,
)


# -----------------------------------------------------------------------------
# Representation-shape validation
# -----------------------------------------------------------------------------

EXPECTED_REPRESENTATION_SHAPE = (
    DATASET_SENTENCE_COUNT,
    CONTEXTUAL_ENCODER_EXPECTED_DIM,
)


REPRESENTATION_SHAPE_VALID = (
    GENERATED_REPRESENTATIONS.shape
    == EXPECTED_REPRESENTATION_SHAPE
)


if not REPRESENTATION_SHAPE_VALID:

    raise ValueError(
        "Generated contextual representation matrix has an "
        "unexpected shape. "
        f"Expected {EXPECTED_REPRESENTATION_SHAPE}, "
        f"received {GENERATED_REPRESENTATIONS.shape}."
    )


# -----------------------------------------------------------------------------
# Numerical validation
# -----------------------------------------------------------------------------

REPRESENTATION_FINITE = bool(
    np.all(
        np.isfinite(
            GENERATED_REPRESENTATIONS
        )
    )
)


if not REPRESENTATION_FINITE:

    raise ValueError(
        "Generated contextual representations contain "
        "non-finite values."
    )


REPRESENTATION_NORMS = np.linalg.norm(
    GENERATED_REPRESENTATIONS,
    axis=1,
)


REPRESENTATION_NORMS_FINITE = bool(
    np.all(
        np.isfinite(
            REPRESENTATION_NORMS
        )
    )
)


REPRESENTATION_ZERO_NORM_COUNT = int(
    np.sum(
        REPRESENTATION_NORMS
        <= 0.0
    )
)


if not REPRESENTATION_NORMS_FINITE:

    raise ValueError(
        "Generated contextual representation norms are non-finite."
    )


if REPRESENTATION_ZERO_NORM_COUNT > 0:

    raise ValueError(
        "One or more contextual sentence representations "
        "have zero norm."
    )


if CONTEXTUAL_ENCODER_NORMALIZE:

    REPRESENTATION_NORMALISATION_VALID = bool(
        np.allclose(
            REPRESENTATION_NORMS,
            1.0,
            atol=1e-5,
        )
    )

else:

    REPRESENTATION_NORMALISATION_VALID = True


if not REPRESENTATION_NORMALISATION_VALID:

    raise ValueError(
        "Contextual embeddings were requested as normalised, "
        "but one or more vectors are not unit-normalised."
    )


# -----------------------------------------------------------------------------
# Construct sentence-aligned representation records
# -----------------------------------------------------------------------------

NOTEBOOK_05_SENTENCE_REPRESENTATIONS = []


for record_index, sentence_record in enumerate(
    SEQUENTIAL_SENTENCE_RECORDS
):

    embedding = GENERATED_REPRESENTATIONS[
        record_index
    ]


    NOTEBOOK_05_SENTENCE_REPRESENTATIONS.append(
        {
            "article_id":
                sentence_record[
                    "article_id"
                ],

            "sentence_id":
                sentence_record[
                    "sentence_id"
                ],

            "sentence_index":
                int(
                    sentence_record[
                        "sentence_index"
                    ]
                ),

            "sequence_position":
                int(
                    sentence_record[
                        "sequence_position"
                    ]
                ),

            "encoder_provider":
                CONTEXTUAL_ENCODER_PROVIDER,

            "encoder_model_id":
                CONTEXTUAL_ENCODER_MODEL_ID,

            "embedding_dimension":
                int(
                    embedding.shape[
                        0
                    ]
                ),

            "normalised":
                bool(
                    CONTEXTUAL_ENCODER_NORMALIZE
                ),

            "embedding":
                embedding.tolist(),
        }
    )


# -----------------------------------------------------------------------------
# Representation identity validation
# -----------------------------------------------------------------------------

GENERATED_SENTENCE_IDS = [
    record[
        "sentence_id"
    ]
    for record
    in NOTEBOOK_05_SENTENCE_REPRESENTATIONS
]


REPRESENTATION_IDENTITY_ALIGNMENT_VALID = (
    GENERATED_SENTENCE_IDS
    == REPRESENTATION_SOURCE_SENTENCE_IDS
)


if not REPRESENTATION_IDENTITY_ALIGNMENT_VALID:

    raise ValueError(
        "Generated representation order does not match the "
        "canonical Block 4 sentence order."
    )


REPRESENTATION_RECORD_COUNT = len(
    NOTEBOOK_05_SENTENCE_REPRESENTATIONS
)


REPRESENTATION_RECORD_COUNT_VALID = (
    REPRESENTATION_RECORD_COUNT
    == DATASET_SENTENCE_COUNT
)


if not REPRESENTATION_RECORD_COUNT_VALID:

    raise ValueError(
        "Contextual representation count does not match "
        "the Block 4 sentence count."
    )


# -----------------------------------------------------------------------------
# Build sentence-ID lookup
# -----------------------------------------------------------------------------

NOTEBOOK_05_SENTENCE_REPRESENTATION_LOOKUP = {
    record[
        "sentence_id"
    ]:
        np.asarray(
            record[
                "embedding"
            ],
            dtype=np.float32,
        )

    for record
    in NOTEBOOK_05_SENTENCE_REPRESENTATIONS
}


REPRESENTATION_LOOKUP_COUNT_VALID = (
    len(
        NOTEBOOK_05_SENTENCE_REPRESENTATION_LOOKUP
    )
    == DATASET_SENTENCE_COUNT
)


if not REPRESENTATION_LOOKUP_COUNT_VALID:

    raise ValueError(
        "Sentence representation lookup contains duplicate or "
        "missing sentence identities."
    )


# -----------------------------------------------------------------------------
# Attach representations to sequential records
# -----------------------------------------------------------------------------

for sentence_record in SEQUENTIAL_SENTENCE_RECORDS:

    sentence_id = sentence_record[
        "sentence_id"
    ]


    if (
        sentence_id
        not in NOTEBOOK_05_SENTENCE_REPRESENTATION_LOOKUP
    ):

        raise KeyError(
            "No contextual representation was generated for "
            f"sentence ID: {sentence_id}"
        )


    representation = (
        NOTEBOOK_05_SENTENCE_REPRESENTATION_LOOKUP[
            sentence_id
        ]
        .copy()
    )


    sentence_record[
        "textual_representation"
    ] = representation


    sentence_record[
        "textual_representation_available"
    ] = True


    sentence_record[
        "textual_representation_provenance"
    ] = {
        "provider":
            CONTEXTUAL_ENCODER_PROVIDER,

        "model_id":
            CONTEXTUAL_ENCODER_MODEL_ID,

        "dimension":
            CONTEXTUAL_ENCODER_EXPECTED_DIM,

        "normalised":
            CONTEXTUAL_ENCODER_NORMALIZE,

        "input_unit":
            CONTEXTUAL_ENCODER_INPUT_UNIT,

        "article_context_used":
            CONTEXTUAL_ENCODER_ARTICLE_CONTEXT_USED,

        "future_context_used":
            CONTEXTUAL_ENCODER_FUTURE_CONTEXT_USED,
    }


# -----------------------------------------------------------------------------
# Canonical-record attachment validation
# -----------------------------------------------------------------------------
#
# CANONICAL_SENTENCE_RECORDS and SEQUENTIAL_SENTENCE_RECORDS currently share
# record identity in Block 4, but Block 5 validates and updates by sentence ID
# rather than relying on that implementation detail.
# -----------------------------------------------------------------------------

canonical_record_lookup = {
    record[
        "sentence_id"
    ]:
        record

    for record
    in CANONICAL_SENTENCE_RECORDS
}


for sentence_id, representation in (
    NOTEBOOK_05_SENTENCE_REPRESENTATION_LOOKUP.items()
):

    if sentence_id not in canonical_record_lookup:

        raise KeyError(
            "Generated representation has no corresponding "
            "canonical Block 4 sentence record."
        )


    canonical_record_lookup[
        sentence_id
    ][
        "textual_representation"
    ] = representation.copy()


    canonical_record_lookup[
        sentence_id
    ][
        "textual_representation_available"
    ] = True


# -----------------------------------------------------------------------------
# Final attachment coverage
# -----------------------------------------------------------------------------

ATTACHED_REPRESENTATION_COUNT = sum(
    bool(
        record[
            "textual_representation_available"
        ]
    )
    for record
    in SEQUENTIAL_SENTENCE_RECORDS
)


ATTACHED_REPRESENTATION_COVERAGE = (
    ATTACHED_REPRESENTATION_COUNT
    / DATASET_SENTENCE_COUNT
)


ATTACHED_REPRESENTATIONS_FULLY_AVAILABLE = (
    ATTACHED_REPRESENTATION_COUNT
    == DATASET_SENTENCE_COUNT
)


if not ATTACHED_REPRESENTATIONS_FULLY_AVAILABLE:

    raise ValueError(
        "Contextual sentence representations were not attached "
        "to all Block 4 records."
    )


# -----------------------------------------------------------------------------
# Validate attached dimensionality and finiteness
# -----------------------------------------------------------------------------

ATTACHED_REPRESENTATION_ERRORS = []


for record in SEQUENTIAL_SENTENCE_RECORDS:

    representation = record.get(
        "textual_representation"
    )


    if representation is None:

        ATTACHED_REPRESENTATION_ERRORS.append(
            f"{record['sentence_id']}:representation_missing"
        )

        continue


    representation_array = np.asarray(
        representation,
        dtype=np.float32,
    )


    if representation_array.shape != (
        BACKBONE_HIDDEN_DIM,
    ):

        ATTACHED_REPRESENTATION_ERRORS.append(
            f"{record['sentence_id']}:dimension_mismatch"
        )


    if not np.all(
        np.isfinite(
            representation_array
        )
    ):

        ATTACHED_REPRESENTATION_ERRORS.append(
            f"{record['sentence_id']}:nonfinite_representation"
        )


if ATTACHED_REPRESENTATION_ERRORS:

    raise ValueError(
        "Attached contextual representation validation failed: "
        f"{ATTACHED_REPRESENTATION_ERRORS}"
    )


# =============================================================================
# Persistent representation artefact
# =============================================================================


# -----------------------------------------------------------------------------
# Persistent payload
# -----------------------------------------------------------------------------

NOTEBOOK_05_REPRESENTATION_PAYLOAD = {
    "artifact_type":
        NOTEBOOK_05_REPRESENTATION_ARTIFACT_TYPE,

    "schema_version":
        NOTEBOOK_05_REPRESENTATION_SCHEMA_VERSION,

    "representation_version":
        CONTEXTUAL_REPRESENTATION_VERSION,

    "created_at_utc":
        CONTEXTUAL_REPRESENTATION_CREATED_AT_UTC,

    "source_notebook":
        "05_training_evaluation_and_validation",

    "source_block":
        NOTEBOOK_05_BLOCK_5,

    "encoder":
        {
            "provider":
                CONTEXTUAL_ENCODER_PROVIDER,

            "model_id":
                CONTEXTUAL_ENCODER_MODEL_ID,

            "sentence_transformers_version":
                SENTENCE_TRANSFORMERS_VERSION,

            "embedding_dimension":
                CONTEXTUAL_ENCODER_EXPECTED_DIM,

            "reported_dimension":
                CONTEXTUAL_ENCODER_REPORTED_DIM,

            "normalised":
                CONTEXTUAL_ENCODER_NORMALIZE,

            "maximum_sequence_length":
                ENCODER_MAX_SEQUENCE_LENGTH,

            "input_unit":
                CONTEXTUAL_ENCODER_INPUT_UNIT,

            "article_context_used":
                CONTEXTUAL_ENCODER_ARTICLE_CONTEXT_USED,

            "future_context_used":
                CONTEXTUAL_ENCODER_FUTURE_CONTEXT_USED,

            "trainable":
                CONTEXTUAL_ENCODER_TRAINABLE,
        },

    "counts":
        {
            "articles":
                int(
                    DATASET_ARTICLE_COUNT
                ),

            "sentences":
                int(
                    DATASET_SENTENCE_COUNT
                ),

            "representations":
                int(
                    REPRESENTATION_RECORD_COUNT
                ),
        },

    "methodological_boundaries":
        {
            "synthetic_fallback_allowed":
                CONTEXTUAL_ENCODER_SYNTHETIC_FALLBACK_ALLOWED,

            "encoder_training_performed":
                False,

            "supervision_modified":
                False,

            "optimizer_created":
                False,

            "loss_calculated":
                False,

            "media_ai_training_executed":
                False,
        },

    "records":
        NOTEBOOK_05_SENTENCE_REPRESENTATIONS,
}


# -----------------------------------------------------------------------------
# Resolve persistence parent from Notebook 04 → 05 handover file
# -----------------------------------------------------------------------------

BLOCK_5_DRIVE_SERVICE = (
    DRIVE_SERVICE_FOR_HANDOVER
)


handover_metadata = (
    BLOCK_5_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_05_HANDOVER_DRIVE_FILE_ID,

        fields=
            "id,name,parents",
    )
    .execute()
)


NOTEBOOK_05_REPRESENTATION_PARENT_IDS = (
    handover_metadata.get(
        "parents",
        [],
    )
)


# -----------------------------------------------------------------------------
# Locate existing representation artefact
# -----------------------------------------------------------------------------

escaped_representation_filename = (
    NOTEBOOK_05_REPRESENTATION_FILENAME.replace(
        "'",
        "\\'",
    )
)


representation_file_search = (
    BLOCK_5_DRIVE_SERVICE.files()
    .list(
        q=(
            f"name = '{escaped_representation_filename}' "
            "and trashed = false"
        ),

        spaces=
            "drive",

        fields=
            "files(id,name,modifiedTime,parents)",

        orderBy=
            "modifiedTime desc",

        pageSize=
            10,
    )
    .execute()
)


existing_representation_files = (
    representation_file_search.get(
        "files",
        [],
    )
)


NOTEBOOK_05_REPRESENTATION_EXISTING_FILE = (
    existing_representation_files[
        0
    ]
    if existing_representation_files
    else None
)


# -----------------------------------------------------------------------------
# Serialise persistent payload
# -----------------------------------------------------------------------------

representation_json_bytes = json.dumps(
    NOTEBOOK_05_REPRESENTATION_PAYLOAD,
    ensure_ascii=False,
    indent=2,
).encode(
    "utf-8"
)


representation_media = MediaIoBaseUpload(
    io.BytesIO(
        representation_json_bytes
    ),
    mimetype=
        "application/json",
    resumable=
        False,
)


# -----------------------------------------------------------------------------
# Persist: update existing or create new
# -----------------------------------------------------------------------------

if NOTEBOOK_05_REPRESENTATION_EXISTING_FILE:

    NOTEBOOK_05_REPRESENTATION_DRIVE_FILE = (
        BLOCK_5_DRIVE_SERVICE.files()
        .update(
            fileId=
                NOTEBOOK_05_REPRESENTATION_EXISTING_FILE[
                    "id"
                ],

            media_body=
                representation_media,

            fields=
                "id,name,modifiedTime,parents",
        )
        .execute()
    )


    NOTEBOOK_05_REPRESENTATION_DRIVE_OPERATION = (
        "updated"
    )


else:

    representation_file_metadata = {
        "name":
            NOTEBOOK_05_REPRESENTATION_FILENAME,
    }


    if NOTEBOOK_05_REPRESENTATION_PARENT_IDS:

        representation_file_metadata[
            "parents"
        ] = (
            NOTEBOOK_05_REPRESENTATION_PARENT_IDS
        )


    NOTEBOOK_05_REPRESENTATION_DRIVE_FILE = (
        BLOCK_5_DRIVE_SERVICE.files()
        .create(
            body=
                representation_file_metadata,

            media_body=
                representation_media,

            fields=
                "id,name,modifiedTime,parents",
        )
        .execute()
    )


    NOTEBOOK_05_REPRESENTATION_DRIVE_OPERATION = (
        "created"
    )


NOTEBOOK_05_REPRESENTATION_DRIVE_FILE_ID = (
    NOTEBOOK_05_REPRESENTATION_DRIVE_FILE.get(
        "id"
    )
)


NOTEBOOK_05_REPRESENTATION_PERSISTED = bool(
    NOTEBOOK_05_REPRESENTATION_DRIVE_FILE_ID
)


if not NOTEBOOK_05_REPRESENTATION_PERSISTED:

    raise ValueError(
        "Contextual representation artefact was not persisted "
        "successfully."
    )


# -----------------------------------------------------------------------------
# Read-back verification
# -----------------------------------------------------------------------------

representation_download_request = (
    BLOCK_5_DRIVE_SERVICE.files()
    .get_media(
        fileId=
            NOTEBOOK_05_REPRESENTATION_DRIVE_FILE_ID
    )
)


representation_download_buffer = io.BytesIO()


representation_downloader = (
    __import__(
        "googleapiclient.http",
        fromlist=[
            "MediaIoBaseDownload"
        ],
    )
    .MediaIoBaseDownload(
        representation_download_buffer,
        representation_download_request,
    )
)


representation_download_done = False


while not representation_download_done:

    _, representation_download_done = (
        representation_downloader.next_chunk()
    )


representation_download_buffer.seek(
    0
)


PERSISTED_REPRESENTATION_PAYLOAD = json.loads(
    representation_download_buffer.read().decode(
        "utf-8"
    )
)


PERSISTED_REPRESENTATION_RECORDS = (
    PERSISTED_REPRESENTATION_PAYLOAD.get(
        "records",
        [],
    )
)


PERSISTED_REPRESENTATION_COUNT = len(
    PERSISTED_REPRESENTATION_RECORDS
)


PERSISTED_REPRESENTATION_SENTENCE_IDS = [
    record.get(
        "sentence_id"
    )
    for record
    in PERSISTED_REPRESENTATION_RECORDS
]


PERSISTED_REPRESENTATION_COUNT_VALID = (
    PERSISTED_REPRESENTATION_COUNT
    == DATASET_SENTENCE_COUNT
)


PERSISTED_REPRESENTATION_ALIGNMENT_VALID = (
    PERSISTED_REPRESENTATION_SENTENCE_IDS
    == REPRESENTATION_SOURCE_SENTENCE_IDS
)


NOTEBOOK_05_REPRESENTATION_PERSISTENCE_VALID = all(
    [
        NOTEBOOK_05_REPRESENTATION_PERSISTED,
        PERSISTED_REPRESENTATION_COUNT_VALID,
        PERSISTED_REPRESENTATION_ALIGNMENT_VALID,
    ]
)


if not NOTEBOOK_05_REPRESENTATION_PERSISTENCE_VALID:

    raise ValueError(
        "Persisted contextual representation artefact failed "
        "read-back validation."
    )


# -----------------------------------------------------------------------------
# Notebook 05 runtime readiness update
# -----------------------------------------------------------------------------

NOTEBOOK_05_TEXTUAL_REPRESENTATIONS_AVAILABLE = True

DATASET_REPRESENTATIONS_AVAILABLE = True

TEXTUAL_REPRESENTATIONS_FULLY_AVAILABLE = True

TEXTUAL_REPRESENTATION_RECORDS_AVAILABLE = (
    DATASET_SENTENCE_COUNT
)

TEXTUAL_REPRESENTATION_RECORD_COUNT = (
    DATASET_SENTENCE_COUNT
)

TEXTUAL_REPRESENTATION_COVERAGE = 1.0


DATASET_MODEL_EXECUTION_READY = bool(
    DATASET_STRUCTURAL_VALID
    and DATASET_SUPERVISION_AVAILABLE
    and DATASET_PARAMETER_POLICY_ALLOWS_TRAINING
    and DATASET_REPRESENTATIONS_AVAILABLE
)


NOTEBOOK_05_MODEL_EXECUTION_READY = (
    DATASET_MODEL_EXECUTION_READY
)


# -----------------------------------------------------------------------------
# Training boundary
# -----------------------------------------------------------------------------

NOTEBOOK_05_OPTIMIZER_CREATED = False

NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED = False

NOTEBOOK_05_LOSS_CALCULATED = False

NOTEBOOK_05_TRAINING_EXECUTED = False

NOTEBOOK_05_CHECKPOINT_SELECTED = False

NOTEBOOK_05_ABLATION_EXECUTED = False

NOTEBOOK_05_EVALUATION_EXECUTED = False

NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED = False


# -----------------------------------------------------------------------------
# Block 5 methodological validation
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_5_ERRORS = []


if CONTEXTUAL_ENCODER_TRAINABLE:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "contextual_encoder_incorrectly_trainable"
    )


if not CONTEXTUAL_ENCODER_FULLY_FROZEN:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "contextual_encoder_not_fully_frozen"
    )


if CONTEXTUAL_ENCODER_ARTICLE_CONTEXT_USED:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "article_context_incorrectly_used_by_sentence_encoder"
    )


if CONTEXTUAL_ENCODER_FUTURE_CONTEXT_USED:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "future_context_incorrectly_used_by_sentence_encoder"
    )


if CONTEXTUAL_ENCODER_SYNTHETIC_FALLBACK_ALLOWED:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "synthetic_representation_fallback_incorrectly_allowed"
    )


if not REPRESENTATION_SHAPE_VALID:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "representation_shape_invalid"
    )


if not REPRESENTATION_FINITE:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "representation_values_nonfinite"
    )


if not REPRESENTATION_IDENTITY_ALIGNMENT_VALID:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "representation_identity_alignment_invalid"
    )


if not ATTACHED_REPRESENTATIONS_FULLY_AVAILABLE:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "representation_attachment_incomplete"
    )


if not NOTEBOOK_05_REPRESENTATION_PERSISTENCE_VALID:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "representation_persistence_invalid"
    )


if NOTEBOOK_05_OPTIMIZER_CREATED:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "optimizer_incorrectly_created_in_block_5"
    )


if NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "forward_pass_incorrectly_executed_in_block_5"
    )


if NOTEBOOK_05_LOSS_CALCULATED:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "loss_incorrectly_calculated_in_block_5"
    )


if NOTEBOOK_05_TRAINING_EXECUTED:

    NOTEBOOK_05_BLOCK_5_ERRORS.append(
        "training_incorrectly_executed_in_block_5"
    )


NOTEBOOK_05_BLOCK_5_VALID = (
    len(
        NOTEBOOK_05_BLOCK_5_ERRORS
    )
    == 0
)


if not NOTEBOOK_05_BLOCK_5_VALID:

    raise ValueError(
        "Notebook 05 Block 5 contextual representation "
        "validation failed: "
        f"{NOTEBOOK_05_BLOCK_5_ERRORS}"
    )


# -----------------------------------------------------------------------------
# Block completion
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_5_COMPLETE = True


# -----------------------------------------------------------------------------
# Block 5 summary
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_5_SUMMARY = {
    "block":
        NOTEBOOK_05_BLOCK_5,

    "block_name":
        NOTEBOOK_05_BLOCK_5_NAME,

    "representation_version":
        CONTEXTUAL_REPRESENTATION_VERSION,

    "created_at_utc":
        CONTEXTUAL_REPRESENTATION_CREATED_AT_UTC,

    "encoder_provider":
        CONTEXTUAL_ENCODER_PROVIDER,

    "encoder_model_id":
        CONTEXTUAL_ENCODER_MODEL_ID,

    "sentence_transformers_version":
        SENTENCE_TRANSFORMERS_VERSION,

    "encoder_dimension":
        CONTEXTUAL_ENCODER_REPORTED_DIM,

    "encoder_fully_frozen":
        CONTEXTUAL_ENCODER_FULLY_FROZEN,

    "sentence_count":
        DATASET_SENTENCE_COUNT,

    "representation_count":
        REPRESENTATION_RECORD_COUNT,

    "representation_shape":
        tuple(
            GENERATED_REPRESENTATIONS.shape
        ),

    "representation_finite":
        REPRESENTATION_FINITE,

    "representation_normalisation_valid":
        REPRESENTATION_NORMALISATION_VALID,

    "identity_alignment_valid":
        REPRESENTATION_IDENTITY_ALIGNMENT_VALID,

    "attachment_coverage":
        ATTACHED_REPRESENTATION_COVERAGE,

    "persisted":
        NOTEBOOK_05_REPRESENTATION_PERSISTED,

    "persistence_valid":
        NOTEBOOK_05_REPRESENTATION_PERSISTENCE_VALID,

    "drive_file_id":
        NOTEBOOK_05_REPRESENTATION_DRIVE_FILE_ID,

    "model_execution_ready":
        NOTEBOOK_05_MODEL_EXECUTION_READY,

    "optimizer_created":
        NOTEBOOK_05_OPTIMIZER_CREATED,

    "training_executed":
        NOTEBOOK_05_TRAINING_EXECUTED,

    "block_valid":
        NOTEBOOK_05_BLOCK_5_VALID,

    "block_complete":
        NOTEBOOK_05_BLOCK_5_COMPLETE,
}


# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------

print("=" * 72)

print(
    "Media AI — Notebook 05, Block 5: "
    "Contextual Representation Generation and Validation"
)

print("=" * 72)


print(
    f"Representation version       : "
    f"{CONTEXTUAL_REPRESENTATION_VERSION}"
)


print("-" * 72)

print(
    "Encoder contract"
)

print(
    f"Provider                     : "
    f"{CONTEXTUAL_ENCODER_PROVIDER}"
)

print(
    f"Model                        : "
    f"{CONTEXTUAL_ENCODER_MODEL_ID}"
)

print(
    f"Sentence Transformers        : "
    f"{SENTENCE_TRANSFORMERS_VERSION}"
)

print(
    f"Package installed in block   : "
    f"{SENTENCE_TRANSFORMERS_INSTALLED_IN_BLOCK}"
)

print(
    f"Encoder device               : "
    f"{CONTEXTUAL_ENCODER_DEVICE}"
)

print(
    f"Reported embedding dimension : "
    f"{CONTEXTUAL_ENCODER_REPORTED_DIM}"
)

print(
    f"Architecture dimension       : "
    f"{BACKBONE_HIDDEN_DIM}"
)

print(
    f"Normalised embeddings        : "
    f"{CONTEXTUAL_ENCODER_NORMALIZE}"
)

print(
    f"Encoder fully frozen         : "
    f"{CONTEXTUAL_ENCODER_FULLY_FROZEN}"
)

print(
    f"Trainable encoder parameters : "
    f"{CONTEXTUAL_ENCODER_TRAINABLE_PARAMETER_COUNT}"
)


print("-" * 72)

print(
    "Causal representation boundary"
)

print(
    f"Input unit                   : "
    f"{CONTEXTUAL_ENCODER_INPUT_UNIT}"
)

print(
    f"Article context used         : "
    f"{CONTEXTUAL_ENCODER_ARTICLE_CONTEXT_USED}"
)

print(
    f"Future context used          : "
    f"{CONTEXTUAL_ENCODER_FUTURE_CONTEXT_USED}"
)

print(
    f"Maximum sequence length      : "
    f"{ENCODER_MAX_SEQUENCE_LENGTH}"
)

print(
    f"Maximum observed token count : "
    f"{REPRESENTATION_MAX_TOKEN_LENGTH}"
)

print(
    f"Truncation-risk sentences    : "
    f"{REPRESENTATION_TRUNCATION_RISK_COUNT}"
)


print("-" * 72)

print(
    "Generated representations"
)

print(
    f"Source sentences             : "
    f"{DATASET_SENTENCE_COUNT}"
)

print(
    f"Generated representations    : "
    f"{REPRESENTATION_RECORD_COUNT}"
)

print(
    f"Representation shape         : "
    f"{GENERATED_REPRESENTATIONS.shape}"
)

print(
    f"Shape valid                  : "
    f"{REPRESENTATION_SHAPE_VALID}"
)

print(
    f"Values finite               : "
    f"{REPRESENTATION_FINITE}"
)

print(
    f"Zero-norm vectors            : "
    f"{REPRESENTATION_ZERO_NORM_COUNT}"
)

print(
    f"Normalisation valid          : "
    f"{REPRESENTATION_NORMALISATION_VALID}"
)

print(
    f"Sentence alignment valid     : "
    f"{REPRESENTATION_IDENTITY_ALIGNMENT_VALID}"
)


print("-" * 72)

print(
    "Dataset attachment"
)

print(
    f"Attached representations     : "
    f"{ATTACHED_REPRESENTATION_COUNT}"
)

print(
    f"Attachment capacity          : "
    f"{DATASET_SENTENCE_COUNT}"
)

print(
    f"Attachment coverage          : "
    f"{ATTACHED_REPRESENTATION_COVERAGE:.4f}"
)

print(
    f"Fully available              : "
    f"{ATTACHED_REPRESENTATIONS_FULLY_AVAILABLE}"
)


print("-" * 72)

print(
    "Persistent representation artefact"
)

print(
    f"Filename                     : "
    f"{NOTEBOOK_05_REPRESENTATION_FILENAME}"
)

print(
    f"Drive operation              : "
    f"{NOTEBOOK_05_REPRESENTATION_DRIVE_OPERATION}"
)

print(
    f"Drive file ID                : "
    f"{NOTEBOOK_05_REPRESENTATION_DRIVE_FILE_ID}"
)

print(
    f"Persisted records            : "
    f"{PERSISTED_REPRESENTATION_COUNT}"
)

print(
    f"Persisted count valid        : "
    f"{PERSISTED_REPRESENTATION_COUNT_VALID}"
)

print(
    f"Persisted alignment valid    : "
    f"{PERSISTED_REPRESENTATION_ALIGNMENT_VALID}"
)

print(
    f"Persistence valid            : "
    f"{NOTEBOOK_05_REPRESENTATION_PERSISTENCE_VALID}"
)


print("-" * 72)

print(
    "Readiness"
)

print(
    f"Supervision dataset valid    : "
    f"{DATASET_STRUCTURAL_VALID}"
)

print(
    f"Validated supervision avail. : "
    f"{DATASET_SUPERVISION_AVAILABLE}"
)

print(
    f"Parameter policy allows      : "
    f"{DATASET_PARAMETER_POLICY_ALLOWS_TRAINING}"
)

print(
    f"Representations available    : "
    f"{DATASET_REPRESENTATIONS_AVAILABLE}"
)

print(
    f"Model execution ready        : "
    f"{NOTEBOOK_05_MODEL_EXECUTION_READY}"
)


print("-" * 72)

print(
    "Execution state"
)

print(
    f"Optimizer created            : "
    f"{NOTEBOOK_05_OPTIMIZER_CREATED}"
)

print(
    f"Forward pass executed        : "
    f"{NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_05_LOSS_CALCULATED}"
)

print(
    f"Training executed            : "
    f"{NOTEBOOK_05_TRAINING_EXECUTED}"
)

print(
    f"Evaluation executed          : "
    f"{NOTEBOOK_05_EVALUATION_EXECUTED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_05_BLOCK_5_VALID}"
)

print(
    f"Block 5 complete             : "
    f"{NOTEBOOK_05_BLOCK_5_COMPLETE}"
)


print("=" * 72)


print(
    "Contextual sentence representations generated and validated "
    "successfully."
)

print(
    "The selected all-mpnet-base-v2 encoder produces the 768-dimensional "
    "sentence representations required by the Notebook 05 architecture."
)

print(
    "The encoder remained fully frozen and is not part of the trainable "
    "Media AI parameter policy."
)

print(
    "Each canonical sentence was encoded independently."
)

print(
    "No preceding or future article sentence was supplied to the encoder."
)

print(
    "Sentence IDs, article identities and within-article order were "
    "preserved."
)

print(
    "Generated embeddings were attached to all canonical sequential "
    "sentence records."
)

print(
    "No synthetic, random, zero or pseudo-embedding fallback was used."
)

print(
    "The contextual representations were persisted independently of "
    "the current Colab runtime and verified by read-back."
)

print(
    "REV, TEV, IEV and EW supervision targets were not modified by this "
    "block."
)

print(
    "No optimiser, supervised loss, parameter update, training, checkpoint "
    "selection, ablation or empirical evaluation has been executed."
)

print(
    "Notebook 05 may next proceed to Loss Assembly, Objective Activation "
    "and Optimiser Policy."
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/11.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

/tmp/ipykernel_622/102121481.py:297: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  CONTEXTUAL_ENCODER.get_sentence_embedding_dimension()

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.
WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.

========================================================================
Media AI — Notebook 05, Block 5: Contextual Representation Generation and Validation
========================================================================
Representation version       : 1.0
------------------------------------------------------------------------
Encoder contract
Provider                     : sentence-transformers
Model                        : sentence-transformers/all-mpnet-base-v2
Sentence Transformers        : 5.7.0
Package installed in block   : False
Encoder device               : cpu
Reported embedding dimension : 768
Architecture dimension       : 768
Normalised embeddings        : True
Encoder fully frozen         : True
Trainable encoder parameters : 0
------------------------------------------------------------------------
Causal representation boundary
Input unit                   : sentence
Article context used         : False
Future context used          : False
Maximum sequence length      : 384
Maximum observed token count : 73
Truncation-risk sentences    : 0
------------------------------------------------------------------------
Generated representations
Source sentences             : 16
Generated representations    : 16
Representation shape         : (16, 768)
Shape valid                  : True
Values finite               : True
Zero-norm vectors            : 0
Normalisation valid          : True
Sentence alignment valid     : True
------------------------------------------------------------------------
Dataset attachment
Attached representations     : 16
Attachment capacity          : 16
Attachment coverage          : 1.0000
Fully available              : True
------------------------------------------------------------------------
Persistent representation artefact
Filename                     : notebook_05_contextual_sentence_representations.json
Drive operation              : created
Drive file ID                : 11_j_CebqBpMSDLlccGwGROr5hklTBYRm
Persisted records            : 16
Persisted count valid        : True
Persisted alignment valid    : True
Persistence valid            : True
------------------------------------------------------------------------
Readiness
Supervision dataset valid    : True
Validated supervision avail. : True
Parameter policy allows      : True
Representations available    : True
Model execution ready        : True
------------------------------------------------------------------------
Execution state
Optimizer created            : False
Forward pass executed        : False
Loss calculated              : False
Training executed            : False
Evaluation executed          : False
Block valid                  : True
Block 5 complete             : True
========================================================================
Contextual sentence representations generated and validated successfully.
The selected all-mpnet-base-v2 encoder produces the 768-dimensional sentence representations required by the Notebook 05 architecture.
The encoder remained fully frozen and is not part of the trainable Media AI parameter policy.
Each canonical sentence was encoded independently.
No preceding or future article sentence was supplied to the encoder.
Sentence IDs, article identities and within-article order were preserved.
Generated embeddings were attached to all canonical sequential sentence records.
No synthetic, random, zero or pseudo-embedding fallback was used.
The contextual representations were persisted independently of the current Colab runtime and verified by read-back.
REV, TEV, IEV and EW supervision targets were not modified by this block.
No optimiser, supervised loss, parameter update, training, checkpoint selection, ablation or empirical evaluation has been executed.
Notebook 05 may next proceed to Loss Assembly, Objective Activation and Optimiser Policy.

block_6_markdown = """
## Block 6: Loss Assembly, Objective Activation and Optimiser Policy

This block defines the first supervised optimisation contract for the Media AI architecture.

The validated sequential dataset now contains sentence-aligned 768-dimensional contextual representations together with canonical psychological supervision for four target families: Reported Emotion Vector (REV), Transformative Emotion Vector (TEV), Immediate Emotion Vector (IEV) and Emotional Weight (EW).

Only these validated direct targets are eligible to enter the supervised objective at this stage.

The block preserves the distinction between supervision availability, target eligibility, parameter trainability and optimisation activation. The presence of validated supervision does not make unrelated architecture components trainable.

Under the parameter policy established in Block 3, only the psychological head is currently trainable. The frozen contextual encoder, backbone interface, confluent representation layers, factual head, social head, group-conditioned adapters, architectural transformation mechanisms, Transformative Weight predictors and recurrent mechanisms remain outside the optimiser.

Loss construction is mask-aware at the target-element level.

REV, TEV and IEV each retain eleven independent supervision masks corresponding to the canonical emotional dimensions. Missing or insufficient-evidence dimensions do not contribute to the loss and are not interpreted as numerical zero or negative evidence.

EW retains its own independent scalar supervision mask.

The supervised psychological objective is assembled from four separate loss components:

- REV loss;
- TEV loss;
- IEV loss; and
- EW loss.

These target families remain methodologically distinct.

TEV remains a psychological supervision construct and is not treated as direct supervision of the architectural psychological transformation mechanism.

EW remains distinct from `TW_P` and is not used as Transformative Weight supervision.

The four supervised objective components receive explicit configurable weights. Their contribution to the total objective must therefore be determined by the experimental configuration rather than implicitly by target dimensionality, the number of observed elements or the amount of available supervision.

Masked loss calculation must use only observed target elements. Numerical placeholders used internally for tensor construction remain excluded through the corresponding Boolean masks.

The optimiser is constructed exclusively from parameters whose `requires_grad` state was explicitly activated in Block 3. Under the current configuration, all optimiser parameters must therefore belong to the psychological-head parameter group.

Before optimisation is permitted, this block verifies that:

- the psychological-head outputs and canonical target tensors have compatible dimensions;
- REV, TEV, IEV and EW each contain at least one observed supervision element;
- target masks have the same shape as their corresponding target tensors;
- unavailable or insufficient-evidence elements do not contribute to any loss term;
- no unavailable target family enters the objective;
- the total weighted objective is finite;
- every optimiser parameter is trainable;
- every optimiser parameter belongs to an explicitly activated parameter group;
- no frozen encoder or backbone parameter enters the optimiser;
- no factual, social, architectural transformation, Transformative Weight or recurrent-state objective is inferred from the available psychological supervision; and
- no parameter update is performed merely as part of objective validation.

This block defines the loss functions, objective weights, objective activation state and optimiser policy. It may calculate masked loss values for a controlled forward-pass result when required to validate the objective contract, but it does not execute an optimiser step or a training epoch.

No checkpoint selection, ablation, evaluation or empirical-validity claim is performed in this block.
"""

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Block 6: Loss Assembly, Objective Activation and Optimiser Policy
# =============================================================================

from collections import OrderedDict

import numpy as np
import torch
import torch.nn as nn


# -----------------------------------------------------------------------------
# Block dependency checks
# -----------------------------------------------------------------------------

required_block_3_objects = [
    "NOTEBOOK_05_BLOCK_3_COMPLETE",
    "NOTEBOOK_05_BLOCK_3_VALID",
    "MEDIA_AI_MODEL",
    "MODEL_DEVICE",
    "MODEL_DTYPE",
    "BACKBONE_HIDDEN_DIM",
    "CONFLUENT_HIDDEN_DIM",
]


missing_block_3_objects = [
    object_name
    for object_name
    in required_block_3_objects
    if object_name not in globals()
]


if missing_block_3_objects:

    raise NameError(
        "Notebook 05 Block 3 is not initialised. "
        f"Missing: {missing_block_3_objects}"
    )


required_block_4_objects = [
    "NOTEBOOK_05_BLOCK_4_COMPLETE",
    "NOTEBOOK_05_BLOCK_4_VALID",
    "SEQUENTIAL_SENTENCE_RECORDS",
    "DATASET_SENTENCE_COUNT",
    "DATASET_STRUCTURAL_VALID",
    "DATASET_SUPERVISION_AVAILABLE",
    "DATASET_PARAMETER_POLICY_ALLOWS_TRAINING",
]


missing_block_4_objects = [
    object_name
    for object_name
    in required_block_4_objects
    if object_name not in globals()
]


if missing_block_4_objects:

    raise NameError(
        "Notebook 05 Block 4 is not initialised. "
        f"Missing: {missing_block_4_objects}"
    )


required_block_5_objects = [
    "NOTEBOOK_05_BLOCK_5_COMPLETE",
    "NOTEBOOK_05_BLOCK_5_VALID",
    "NOTEBOOK_05_MODEL_EXECUTION_READY",
    "NOTEBOOK_05_SENTENCE_REPRESENTATION_LOOKUP",
]


missing_block_5_objects = [
    object_name
    for object_name
    in required_block_5_objects
    if object_name not in globals()
]


if missing_block_5_objects:

    raise NameError(
        "Notebook 05 Block 5 is not initialised. "
        f"Missing: {missing_block_5_objects}"
    )


if not NOTEBOOK_05_BLOCK_3_COMPLETE:

    raise ValueError(
        "Notebook 05 Block 3 must be complete."
    )


if not NOTEBOOK_05_BLOCK_3_VALID:

    raise ValueError(
        "Notebook 05 Block 3 parameter policy is invalid."
    )


if not NOTEBOOK_05_BLOCK_4_COMPLETE:

    raise ValueError(
        "Notebook 05 Block 4 must be complete."
    )


if not NOTEBOOK_05_BLOCK_4_VALID:

    raise ValueError(
        "Notebook 05 Block 4 sequential dataset is invalid."
    )


if not NOTEBOOK_05_BLOCK_5_COMPLETE:

    raise ValueError(
        "Notebook 05 Block 5 must be complete."
    )


if not NOTEBOOK_05_BLOCK_5_VALID:

    raise ValueError(
        "Notebook 05 Block 5 contextual representations are invalid."
    )


if not DATASET_STRUCTURAL_VALID:

    raise ValueError(
        "Block 6 requires a structurally valid supervised dataset."
    )


if not DATASET_SUPERVISION_AVAILABLE:

    raise ValueError(
        "Block 6 requires validated psychological supervision."
    )


if not DATASET_PARAMETER_POLICY_ALLOWS_TRAINING:

    raise ValueError(
        "Block 6 requires an activated trainable parameter group."
    )


if not NOTEBOOK_05_MODEL_EXECUTION_READY:

    raise ValueError(
        "Notebook 05 is not ready for controlled model execution."
    )


# -----------------------------------------------------------------------------
# Block configuration
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_6 = 6

NOTEBOOK_05_BLOCK_6_NAME = (
    "Loss Assembly, Objective Activation and Optimiser Policy"
)

OBJECTIVE_POLICY_VERSION = "1.1"


ACTIVE_SUPERVISED_TARGETS = (
    "REV",
    "TEV",
    "IEV",
    "EW",
)


# -----------------------------------------------------------------------------
# Explicit objective weights
# -----------------------------------------------------------------------------
#
# Each family loss is averaged over its own observed target elements first.
#
# Equal family weights are then used for the initial controlled baseline.
#
# This prevents REV, TEV and IEV from receiving automatically larger influence
# simply because they contain eleven dimensions while EW is scalar.
# -----------------------------------------------------------------------------

OBJECTIVE_WEIGHTS = OrderedDict(
    [
        (
            "REV",
            1.0,
        ),
        (
            "TEV",
            1.0,
        ),
        (
            "IEV",
            1.0,
        ),
        (
            "EW",
            1.0,
        ),
    ]
)


OBJECTIVE_WEIGHT_SUM = float(
    sum(
        OBJECTIVE_WEIGHTS.values()
    )
)


if OBJECTIVE_WEIGHT_SUM <= 0.0:

    raise ValueError(
        "At least one supervised objective weight must be positive."
    )


if not all(
    np.isfinite(
        weight
    )
    and weight >= 0.0

    for weight
    in OBJECTIVE_WEIGHTS.values()
):

    raise ValueError(
        "Objective weights must be finite and non-negative."
    )


# -----------------------------------------------------------------------------
# Optimiser configuration
# -----------------------------------------------------------------------------

OPTIMIZER_NAME = "AdamW"

OPTIMIZER_LEARNING_RATE = 1e-3

OPTIMIZER_WEIGHT_DECAY = 1e-4

OPTIMIZER_BETAS = (
    0.9,
    0.999,
)

OPTIMIZER_EPS = 1e-8


# -----------------------------------------------------------------------------
# Canonical psychological dimension contract
# -----------------------------------------------------------------------------

PSYCHOLOGICAL_EMOTION_DIMENSIONS = (
    "fear",
    "anger",
    "sadness",
    "disgust",
    "tension",
    "uncertainty",
    "hope",
    "relief",
    "trust",
    "compassion",
    "solidarity",
)


PSYCHOLOGICAL_VECTOR_DIMENSION = len(
    PSYCHOLOGICAL_EMOTION_DIMENSIONS
)


if PSYCHOLOGICAL_VECTOR_DIMENSION != 11:

    raise ValueError(
        "Psychological emotion-vector dimensionality must be 11."
    )


EXPECTED_VECTOR_TARGET_SHAPE = (
    DATASET_SENTENCE_COUNT,
    PSYCHOLOGICAL_VECTOR_DIMENSION,
)


EXPECTED_SCALAR_TARGET_SHAPE = (
    DATASET_SENTENCE_COUNT,
    1,
)


# =============================================================================
# Canonical target extraction
# =============================================================================


# -----------------------------------------------------------------------------
# Scalar conversion helper
# -----------------------------------------------------------------------------

def target_value_to_float(
    value,
):
    """
    Convert one canonical target value to a scalar float.

    Missing or incompatible values return NaN and are subsequently excluded
    by the canonical Boolean supervision mask.

    One-element NumPy arrays, lists, tuples and torch tensors are extracted
    explicitly to avoid deprecated implicit array-to-scalar conversion.
    """

    if value is None:

        return float(
            "nan"
        )


    if isinstance(
        value,
        torch.Tensor,
    ):

        if value.numel() != 1:

            return float(
                "nan"
            )

        value = (
            value.detach()
            .cpu()
            .reshape(
                -1
            )[
                0
            ]
            .item()
        )


    elif isinstance(
        value,
        np.ndarray,
    ):

        if value.size != 1:

            return float(
                "nan"
            )

        value = (
            value.reshape(
                -1
            )[
                0
            ]
            .item()
        )


    elif isinstance(
        value,
        (
            list,
            tuple,
        ),
    ):

        if len(
            value
        ) != 1:

            return float(
                "nan"
            )

        value = value[
            0
        ]


    try:

        numeric_value = float(
            value
        )


    except (
        TypeError,
        ValueError,
    ):

        return float(
            "nan"
        )


    return numeric_value


# -----------------------------------------------------------------------------
# Boolean mask conversion
# -----------------------------------------------------------------------------

def target_mask_to_bool(
    value,
):
    """
    Convert one canonical target-mask value to bool.
    """

    if isinstance(
        value,
        torch.Tensor,
    ):

        if value.numel() != 1:

            return False

        return bool(
            value.detach()
            .cpu()
            .reshape(
                -1
            )[
                0
            ]
            .item()
        )


    if isinstance(
        value,
        np.ndarray,
    ):

        if value.size != 1:

            return False

        return bool(
            value.reshape(
                -1
            )[
                0
            ]
            .item()
        )


    return bool(
        value
    )


# -----------------------------------------------------------------------------
# Vector target extraction
# -----------------------------------------------------------------------------

def extract_vector_target(
    sentence_record,
    target_name,
):
    """
    Extract one eleven-dimensional psychological target and its
    element-level Boolean mask.
    """

    targets = sentence_record.get(
        "targets",
        {},
    )

    target_masks = sentence_record.get(
        "target_masks",
        {},
    )


    if target_name not in targets:

        raise KeyError(
            f"Missing target family {target_name} for "
            f"sentence {sentence_record['sentence_id']}."
        )


    if target_name not in target_masks:

        raise KeyError(
            f"Missing target mask {target_name} for "
            f"sentence {sentence_record['sentence_id']}."
        )


    target_object = targets[
        target_name
    ]

    mask_object = target_masks[
        target_name
    ]


    # -------------------------------------------------------------------------
    # Canonical Block 4 form is NumPy array.
    #
    # Dictionary support is retained for schema robustness.
    # -------------------------------------------------------------------------

    if isinstance(
        target_object,
        dict,
    ):

        target_values = [
            target_value_to_float(
                target_object.get(
                    dimension_name
                )
            )

            for dimension_name
            in PSYCHOLOGICAL_EMOTION_DIMENSIONS
        ]


    else:

        target_array = np.asarray(
            target_object
        ).reshape(
            -1
        )


        target_values = [
            target_value_to_float(
                value
            )

            for value
            in target_array
        ]


    if isinstance(
        mask_object,
        dict,
    ):

        mask_values = [
            target_mask_to_bool(
                mask_object.get(
                    dimension_name,
                    False,
                )
            )

            for dimension_name
            in PSYCHOLOGICAL_EMOTION_DIMENSIONS
        ]


    else:

        mask_array = np.asarray(
            mask_object
        ).reshape(
            -1
        )


        mask_values = [
            target_mask_to_bool(
                value
            )

            for value
            in mask_array
        ]


    if len(
        target_values
    ) != PSYCHOLOGICAL_VECTOR_DIMENSION:

        raise ValueError(
            f"{target_name} target dimensionality is invalid for "
            f"sentence {sentence_record['sentence_id']}. "
            f"Expected {PSYCHOLOGICAL_VECTOR_DIMENSION}, "
            f"received {len(target_values)}."
        )


    if len(
        mask_values
    ) != PSYCHOLOGICAL_VECTOR_DIMENSION:

        raise ValueError(
            f"{target_name} mask dimensionality is invalid for "
            f"sentence {sentence_record['sentence_id']}."
        )


    safe_values = []


    for value, mask in zip(
        target_values,
        mask_values,
    ):

        if mask:

            if not np.isfinite(
                value
            ):

                raise ValueError(
                    f"{target_name} contains an observed but non-finite "
                    f"target for sentence "
                    f"{sentence_record['sentence_id']}."
                )


            safe_values.append(
                float(
                    value
                )
            )


        else:

            safe_values.append(
                0.0
            )


    return (
        safe_values,
        mask_values,
    )


# -----------------------------------------------------------------------------
# Scalar target extraction
# -----------------------------------------------------------------------------

def extract_scalar_target(
    sentence_record,
    target_name,
):
    """
    Extract one scalar target and its independent Boolean mask.
    """

    targets = sentence_record.get(
        "targets",
        {},
    )

    target_masks = sentence_record.get(
        "target_masks",
        {},
    )


    if target_name not in targets:

        raise KeyError(
            f"Missing target family {target_name} for "
            f"sentence {sentence_record['sentence_id']}."
        )


    if target_name not in target_masks:

        raise KeyError(
            f"Missing target mask {target_name} for "
            f"sentence {sentence_record['sentence_id']}."
        )


    target_object = targets[
        target_name
    ]

    mask_object = target_masks[
        target_name
    ]


    if isinstance(
        target_object,
        dict,
    ):

        if "value" in target_object:

            target_value = (
                target_value_to_float(
                    target_object[
                        "value"
                    ]
                )
            )


        elif len(
            target_object
        ) == 1:

            target_value = (
                target_value_to_float(
                    next(
                        iter(
                            target_object.values()
                        )
                    )
                )
            )


        else:

            raise ValueError(
                f"Unable to identify scalar {target_name} target "
                f"for sentence {sentence_record['sentence_id']}."
            )


    else:

        target_array = np.asarray(
            target_object
        ).reshape(
            -1
        )


        if target_array.size != 1:

            raise ValueError(
                f"{target_name} must contain exactly one scalar value "
                f"for sentence {sentence_record['sentence_id']}."
            )


        target_value = (
            target_value_to_float(
                target_array[
                    0
                ]
            )
        )


    if isinstance(
        mask_object,
        dict,
    ):

        if "value" in mask_object:

            mask_value = (
                target_mask_to_bool(
                    mask_object[
                        "value"
                    ]
                )
            )


        elif len(
            mask_object
        ) == 1:

            mask_value = (
                target_mask_to_bool(
                    next(
                        iter(
                            mask_object.values()
                        )
                    )
                )
            )


        else:

            raise ValueError(
                f"Unable to identify scalar {target_name} mask "
                f"for sentence {sentence_record['sentence_id']}."
            )


    else:

        mask_array = np.asarray(
            mask_object
        ).reshape(
            -1
        )


        if mask_array.size != 1:

            raise ValueError(
                f"{target_name} mask must contain exactly one scalar "
                f"for sentence {sentence_record['sentence_id']}."
            )


        mask_value = (
            target_mask_to_bool(
                mask_array[
                    0
                ]
            )
        )


    if (
        mask_value
        and not np.isfinite(
            target_value
        )
    ):

        raise ValueError(
            f"{target_name} contains an observed but non-finite target "
            f"for sentence {sentence_record['sentence_id']}."
        )


    safe_value = (
        float(
            target_value
        )

        if mask_value

        else 0.0
    )


    return (
        safe_value,
        mask_value,
    )


# =============================================================================
# Construct supervised tensors
# =============================================================================

REPRESENTATION_ROWS = []

REV_TARGET_ROWS = []
REV_MASK_ROWS = []

TEV_TARGET_ROWS = []
TEV_MASK_ROWS = []

IEV_TARGET_ROWS = []
IEV_MASK_ROWS = []

EW_TARGET_ROWS = []
EW_MASK_ROWS = []

BLOCK_6_SENTENCE_IDS = []


for sentence_record in SEQUENTIAL_SENTENCE_RECORDS:

    sentence_id = sentence_record[
        "sentence_id"
    ]


    if (
        sentence_id
        not in NOTEBOOK_05_SENTENCE_REPRESENTATION_LOOKUP
    ):

        raise KeyError(
            "Missing contextual representation for "
            f"sentence {sentence_id}."
        )


    representation = np.asarray(
        NOTEBOOK_05_SENTENCE_REPRESENTATION_LOOKUP[
            sentence_id
        ],
        dtype=np.float32,
    )


    if representation.shape != (
        BACKBONE_HIDDEN_DIM,
    ):

        raise ValueError(
            "Contextual representation dimensionality mismatch "
            f"for sentence {sentence_id}. "
            f"Expected {(BACKBONE_HIDDEN_DIM,)}, "
            f"received {representation.shape}."
        )


    if not np.all(
        np.isfinite(
            representation
        )
    ):

        raise ValueError(
            "Non-finite contextual representation for "
            f"sentence {sentence_id}."
        )


    rev_target, rev_mask = (
        extract_vector_target(
            sentence_record,
            "REV",
        )
    )


    tev_target, tev_mask = (
        extract_vector_target(
            sentence_record,
            "TEV",
        )
    )


    iev_target, iev_mask = (
        extract_vector_target(
            sentence_record,
            "IEV",
        )
    )


    ew_target, ew_mask = (
        extract_scalar_target(
            sentence_record,
            "EW",
        )
    )


    BLOCK_6_SENTENCE_IDS.append(
        sentence_id
    )


    REPRESENTATION_ROWS.append(
        representation
    )


    REV_TARGET_ROWS.append(
        rev_target
    )

    REV_MASK_ROWS.append(
        rev_mask
    )


    TEV_TARGET_ROWS.append(
        tev_target
    )

    TEV_MASK_ROWS.append(
        tev_mask
    )


    IEV_TARGET_ROWS.append(
        iev_target
    )

    IEV_MASK_ROWS.append(
        iev_mask
    )


    EW_TARGET_ROWS.append(
        [
            ew_target
        ]
    )

    EW_MASK_ROWS.append(
        [
            ew_mask
        ]
    )


# -----------------------------------------------------------------------------
# Device-safe tensor construction
# -----------------------------------------------------------------------------

BLOCK_6_DEVICE = torch.device(
    MODEL_DEVICE
)


if MODEL_DTYPE == torch.float64:

    BLOCK_6_FLOAT_DTYPE = (
        torch.float64
    )


elif MODEL_DTYPE == torch.float16:

    BLOCK_6_FLOAT_DTYPE = (
        torch.float16
    )


elif MODEL_DTYPE == torch.bfloat16:

    BLOCK_6_FLOAT_DTYPE = (
        torch.bfloat16
    )


else:

    BLOCK_6_FLOAT_DTYPE = (
        torch.float32
    )


BLOCK_6_REPRESENTATIONS = torch.tensor(
    np.asarray(
        REPRESENTATION_ROWS,
        dtype=np.float32,
    ),
    dtype=
        BLOCK_6_FLOAT_DTYPE,
    device=
        BLOCK_6_DEVICE,
)


BLOCK_6_REV_TARGETS = torch.tensor(
    REV_TARGET_ROWS,
    dtype=
        BLOCK_6_FLOAT_DTYPE,
    device=
        BLOCK_6_DEVICE,
)


BLOCK_6_REV_MASK = torch.tensor(
    REV_MASK_ROWS,
    dtype=
        torch.bool,
    device=
        BLOCK_6_DEVICE,
)


BLOCK_6_TEV_TARGETS = torch.tensor(
    TEV_TARGET_ROWS,
    dtype=
        BLOCK_6_FLOAT_DTYPE,
    device=
        BLOCK_6_DEVICE,
)


BLOCK_6_TEV_MASK = torch.tensor(
    TEV_MASK_ROWS,
    dtype=
        torch.bool,
    device=
        BLOCK_6_DEVICE,
)


BLOCK_6_IEV_TARGETS = torch.tensor(
    IEV_TARGET_ROWS,
    dtype=
        BLOCK_6_FLOAT_DTYPE,
    device=
        BLOCK_6_DEVICE,
)


BLOCK_6_IEV_MASK = torch.tensor(
    IEV_MASK_ROWS,
    dtype=
        torch.bool,
    device=
        BLOCK_6_DEVICE,
)


BLOCK_6_EW_TARGETS = torch.tensor(
    EW_TARGET_ROWS,
    dtype=
        BLOCK_6_FLOAT_DTYPE,
    device=
        BLOCK_6_DEVICE,
)


BLOCK_6_EW_MASK = torch.tensor(
    EW_MASK_ROWS,
    dtype=
        torch.bool,
    device=
        BLOCK_6_DEVICE,
)


# -----------------------------------------------------------------------------
# Target tensor validation
# -----------------------------------------------------------------------------

TARGET_SHAPES_VALID = all(
    [
        tuple(
            BLOCK_6_REV_TARGETS.shape
        )
        == EXPECTED_VECTOR_TARGET_SHAPE,

        tuple(
            BLOCK_6_REV_MASK.shape
        )
        == EXPECTED_VECTOR_TARGET_SHAPE,

        tuple(
            BLOCK_6_TEV_TARGETS.shape
        )
        == EXPECTED_VECTOR_TARGET_SHAPE,

        tuple(
            BLOCK_6_TEV_MASK.shape
        )
        == EXPECTED_VECTOR_TARGET_SHAPE,

        tuple(
            BLOCK_6_IEV_TARGETS.shape
        )
        == EXPECTED_VECTOR_TARGET_SHAPE,

        tuple(
            BLOCK_6_IEV_MASK.shape
        )
        == EXPECTED_VECTOR_TARGET_SHAPE,

        tuple(
            BLOCK_6_EW_TARGETS.shape
        )
        == EXPECTED_SCALAR_TARGET_SHAPE,

        tuple(
            BLOCK_6_EW_MASK.shape
        )
        == EXPECTED_SCALAR_TARGET_SHAPE,
    ]
)


if not TARGET_SHAPES_VALID:

    raise ValueError(
        "Block 6 target or mask tensor shapes are invalid."
    )


# -----------------------------------------------------------------------------
# Observed-element accounting
# -----------------------------------------------------------------------------

OBJECTIVE_OBSERVED_ELEMENTS = OrderedDict(
    [
        (
            "REV",
            int(
                BLOCK_6_REV_MASK.sum()
                .item()
            ),
        ),

        (
            "TEV",
            int(
                BLOCK_6_TEV_MASK.sum()
                .item()
            ),
        ),

        (
            "IEV",
            int(
                BLOCK_6_IEV_MASK.sum()
                .item()
            ),
        ),

        (
            "EW",
            int(
                BLOCK_6_EW_MASK.sum()
                .item()
            ),
        ),
    ]
)


OBJECTIVE_POSSIBLE_ELEMENTS = OrderedDict(
    [
        (
            "REV",
            int(
                BLOCK_6_REV_MASK.numel()
            ),
        ),

        (
            "TEV",
            int(
                BLOCK_6_TEV_MASK.numel()
            ),
        ),

        (
            "IEV",
            int(
                BLOCK_6_IEV_MASK.numel()
            ),
        ),

        (
            "EW",
            int(
                BLOCK_6_EW_MASK.numel()
            ),
        ),
    ]
)


OBJECTIVE_COVERAGE = OrderedDict(
    (
        target_name,
        (
            OBJECTIVE_OBSERVED_ELEMENTS[
                target_name
            ]
            /
            OBJECTIVE_POSSIBLE_ELEMENTS[
                target_name
            ]
        ),
    )

    for target_name
    in ACTIVE_SUPERVISED_TARGETS
)


OBJECTIVE_HAS_OBSERVED_ELEMENTS = {
    target_name:
        (
            OBJECTIVE_OBSERVED_ELEMENTS[
                target_name
            ]
            > 0
        )

    for target_name
    in ACTIVE_SUPERVISED_TARGETS
}


if not all(
    OBJECTIVE_HAS_OBSERVED_ELEMENTS.values()
):

    raise ValueError(
        "Every activated supervised objective must contain at least "
        "one observed target element."
    )


# =============================================================================
# Mask-aware loss
# =============================================================================

def masked_mean_squared_error(
    prediction,
    target,
    mask,
):
    """
    Mean squared error over observed target elements only.

    Missing target elements are excluded entirely from both numerator
    and denominator.
    """

    if prediction.shape != target.shape:

        raise ValueError(
            "Prediction and target shapes differ. "
            f"Prediction: {tuple(prediction.shape)}, "
            f"target: {tuple(target.shape)}."
        )


    if target.shape != mask.shape:

        raise ValueError(
            "Target and mask shapes differ."
        )


    observed_count = int(
        mask.sum()
        .item()
    )


    if observed_count <= 0:

        raise ValueError(
            "Masked loss cannot be calculated without observed "
            "target elements."
        )


    squared_error = (
        prediction
        - target
    ) ** 2


    observed_squared_error = (
        squared_error[
            mask
        ]
    )


    loss = (
        observed_squared_error.mean()
    )


    if loss.ndim != 0:

        raise ValueError(
            "Masked loss must be scalar."
        )


    if not bool(
        torch.isfinite(
            loss
        ).item()
    ):

        raise ValueError(
            "Masked loss is non-finite."
        )


    return loss


# =============================================================================
# Architecture modules
# =============================================================================


# -----------------------------------------------------------------------------
# Required executable modules
# -----------------------------------------------------------------------------

if not hasattr(
    MEDIA_AI_MODEL,
    "backbone",
):

    raise AttributeError(
        "MEDIA_AI_MODEL has no backbone interface."
    )


if not hasattr(
    MEDIA_AI_MODEL,
    "confluent",
):

    raise AttributeError(
        "MEDIA_AI_MODEL has no confluent-conditioning module."
    )


if not hasattr(
    MEDIA_AI_MODEL,
    "psychological_head",
):

    raise AttributeError(
        "MEDIA_AI_MODEL has no psychological head."
    )


BACKBONE_MODULE = (
    MEDIA_AI_MODEL.backbone
)


CONFLUENT_MODULE = (
    MEDIA_AI_MODEL.confluent
)


PSYCHOLOGICAL_HEAD_MODULE = (
    MEDIA_AI_MODEL.psychological_head
)


PSYCHOLOGICAL_HEAD_ATTRIBUTE = (
    "psychological_head"
)


# -----------------------------------------------------------------------------
# Move model to execution device
# -----------------------------------------------------------------------------

MEDIA_AI_MODEL.to(
    BLOCK_6_DEVICE
)


# -----------------------------------------------------------------------------
# Training / evaluation mode policy
# -----------------------------------------------------------------------------
#
# Block 6 is a controlled no-update validation pass.
#
# Dropout must therefore not introduce stochastic objective values.
# -----------------------------------------------------------------------------

MEDIA_AI_MODEL.eval()

BACKBONE_MODULE.eval()

CONFLUENT_MODULE.eval()

PSYCHOLOGICAL_HEAD_MODULE.eval()


# -----------------------------------------------------------------------------
# Frozen upstream-stage validation
# -----------------------------------------------------------------------------

BACKBONE_STAGE_FULLY_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in BACKBONE_MODULE.parameters()
)


CONFLUENT_STAGE_FULLY_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in CONFLUENT_MODULE.parameters()
)


if not BACKBONE_STAGE_FULLY_FROZEN:

    raise ValueError(
        "Controlled Block 6 forward pass found trainable "
        "backbone-interface parameters."
    )


if not CONFLUENT_STAGE_FULLY_FROZEN:

    raise ValueError(
        "Controlled Block 6 forward pass found trainable "
        "confluent-conditioning parameters."
    )


# -----------------------------------------------------------------------------
# Psychological-head trainability validation
# -----------------------------------------------------------------------------

PSYCHOLOGICAL_HEAD_PARAMETERS = list(
    PSYCHOLOGICAL_HEAD_MODULE.parameters()
)


PSYCHOLOGICAL_HEAD_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter
    in PSYCHOLOGICAL_HEAD_PARAMETERS
}


PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETERS = [
    parameter

    for parameter
    in PSYCHOLOGICAL_HEAD_PARAMETERS

    if parameter.requires_grad
]


PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter
    in PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETERS
}


ALL_MODEL_TRAINABLE_PARAMETERS = [
    parameter

    for parameter
    in MEDIA_AI_MODEL.parameters()

    if parameter.requires_grad
]


ALL_MODEL_TRAINABLE_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter
    in ALL_MODEL_TRAINABLE_PARAMETERS
}


ONLY_PSYCHOLOGICAL_HEAD_TRAINABLE = all(
    [
        bool(
            ALL_MODEL_TRAINABLE_PARAMETER_IDS
        ),

        ALL_MODEL_TRAINABLE_PARAMETER_IDS
        ==
        PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETER_IDS,
    ]
)


if not ONLY_PSYCHOLOGICAL_HEAD_TRAINABLE:

    unexpected_trainable_parameters = [
        parameter_name

        for (
            parameter_name,
            parameter,
        )
        in MEDIA_AI_MODEL.named_parameters()

        if (
            parameter.requires_grad
            and id(
                parameter
            )
            not in PSYCHOLOGICAL_HEAD_PARAMETER_IDS
        )
    ]


    raise ValueError(
        "Block 6 detected trainable parameters outside the "
        "psychological head. Unexpected trainable parameters: "
        f"{unexpected_trainable_parameters}"
    )


PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETER_COUNT = sum(
    parameter.numel()

    for parameter
    in PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETERS
)


if PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETER_COUNT <= 0:

    raise ValueError(
        "The psychological head contains no trainable parameters."
    )


# =============================================================================
# Controlled architectural forward path
# =============================================================================
#
# Architecture:
#
# 768-d validated contextual sentence representation
#       ↓
# frozen backbone interface
#       ↓
# 768-d backbone-interface output
#       ↓
# frozen global confluent projection
#       ↓
# 256-d confluent representation
#       ↓
# trainable psychological head
#       ↓
# REV / TEV / IEV / EW
#
# Group-conditioned paths are not used because no validated group supervision
# currently exists.
# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
# Frozen upstream forward
# -----------------------------------------------------------------------------

with torch.no_grad():

    CONTROLLED_BACKBONE_OUTPUT = (
        BACKBONE_MODULE(
            BLOCK_6_REPRESENTATIONS
        )
    )


    CONTROLLED_CONFLUENT_GLOBAL = (
        CONFLUENT_MODULE.forward_global(
            CONTROLLED_BACKBONE_OUTPUT
        )
    )


# -----------------------------------------------------------------------------
# Intermediate shape validation
# -----------------------------------------------------------------------------

CONTROLLED_INPUT_SHAPE = tuple(
    BLOCK_6_REPRESENTATIONS.shape
)


CONTROLLED_BACKBONE_SHAPE = tuple(
    CONTROLLED_BACKBONE_OUTPUT.shape
)


CONTROLLED_CONFLUENT_SHAPE = tuple(
    CONTROLLED_CONFLUENT_GLOBAL.shape
)


EXPECTED_INPUT_SHAPE = (
    DATASET_SENTENCE_COUNT,
    BACKBONE_HIDDEN_DIM,
)


EXPECTED_BACKBONE_OUTPUT_SHAPE = (
    DATASET_SENTENCE_COUNT,
    BACKBONE_HIDDEN_DIM,
)


EXPECTED_CONFLUENT_OUTPUT_SHAPE = (
    DATASET_SENTENCE_COUNT,
    CONFLUENT_HIDDEN_DIM,
)


INPUT_SHAPE_VALID = (
    CONTROLLED_INPUT_SHAPE
    == EXPECTED_INPUT_SHAPE
)


BACKBONE_OUTPUT_SHAPE_VALID = (
    CONTROLLED_BACKBONE_SHAPE
    == EXPECTED_BACKBONE_OUTPUT_SHAPE
)


CONFLUENT_OUTPUT_SHAPE_VALID = (
    CONTROLLED_CONFLUENT_SHAPE
    == EXPECTED_CONFLUENT_OUTPUT_SHAPE
)


if not INPUT_SHAPE_VALID:

    raise ValueError(
        "Controlled contextual representation input has an "
        "unexpected shape. "
        f"Expected {EXPECTED_INPUT_SHAPE}, "
        f"received {CONTROLLED_INPUT_SHAPE}."
    )


if not BACKBONE_OUTPUT_SHAPE_VALID:

    raise ValueError(
        "Controlled backbone-interface output has an unexpected "
        "shape. "
        f"Expected {EXPECTED_BACKBONE_OUTPUT_SHAPE}, "
        f"received {CONTROLLED_BACKBONE_SHAPE}."
    )


if not CONFLUENT_OUTPUT_SHAPE_VALID:

    raise ValueError(
        "Controlled confluent global representation has an unexpected "
        "shape. "
        f"Expected {EXPECTED_CONFLUENT_OUTPUT_SHAPE}, "
        f"received {CONTROLLED_CONFLUENT_SHAPE}."
    )


# -----------------------------------------------------------------------------
# Intermediate numerical validation
# -----------------------------------------------------------------------------

BACKBONE_OUTPUT_FINITE = bool(
    torch.isfinite(
        CONTROLLED_BACKBONE_OUTPUT
    ).all()
    .item()
)


CONFLUENT_OUTPUT_FINITE = bool(
    torch.isfinite(
        CONTROLLED_CONFLUENT_GLOBAL
    ).all()
    .item()
)


if not BACKBONE_OUTPUT_FINITE:

    raise ValueError(
        "Backbone-interface output contains non-finite values."
    )


if not CONFLUENT_OUTPUT_FINITE:

    raise ValueError(
        "Confluent global representation contains non-finite values."
    )


# -----------------------------------------------------------------------------
# Psychological-head forward
# -----------------------------------------------------------------------------
#
# no_grad is intentionally used because Block 6 validates only the objective
# contract. Block 7 will perform the first gradient-bearing training step.
# -----------------------------------------------------------------------------

with torch.no_grad():

    CONTROLLED_PSYCHOLOGICAL_OUTPUT = (
        PSYCHOLOGICAL_HEAD_MODULE(
            CONTROLLED_CONFLUENT_GLOBAL
        )
    )


# -----------------------------------------------------------------------------
# Parse psychological-head output
# -----------------------------------------------------------------------------

if isinstance(
    CONTROLLED_PSYCHOLOGICAL_OUTPUT,
    dict,
):

    required_output_keys = {
        "REV",
        "TEV",
        "IEV",
        "EW",
    }


    missing_output_keys = (
        required_output_keys
        -
        set(
            CONTROLLED_PSYCHOLOGICAL_OUTPUT.keys()
        )
    )


    if missing_output_keys:

        raise ValueError(
            "Psychological-head dictionary output is missing: "
            f"{sorted(missing_output_keys)}"
        )


    PREDICTED_REV = (
        CONTROLLED_PSYCHOLOGICAL_OUTPUT[
            "REV"
        ]
    )


    PREDICTED_TEV = (
        CONTROLLED_PSYCHOLOGICAL_OUTPUT[
            "TEV"
        ]
    )


    PREDICTED_IEV = (
        CONTROLLED_PSYCHOLOGICAL_OUTPUT[
            "IEV"
        ]
    )


    PREDICTED_EW = (
        CONTROLLED_PSYCHOLOGICAL_OUTPUT[
            "EW"
        ]
    )


elif torch.is_tensor(
    CONTROLLED_PSYCHOLOGICAL_OUTPUT
):

    if (
        CONTROLLED_PSYCHOLOGICAL_OUTPUT.ndim
        != 2
    ):

        raise ValueError(
            "Psychological-head tensor output must be two-dimensional."
        )


    if (
        CONTROLLED_PSYCHOLOGICAL_OUTPUT.shape[
            1
        ]
        != 34
    ):

        raise ValueError(
            "Psychological-head tensor output has an unexpected "
            "dimension. Expected 34 in REV, TEV, IEV, EW order; "
            f"received "
            f"{tuple(CONTROLLED_PSYCHOLOGICAL_OUTPUT.shape)}."
        )


    PREDICTED_REV = (
        CONTROLLED_PSYCHOLOGICAL_OUTPUT[
            :,
            0:11,
        ]
    )


    PREDICTED_TEV = (
        CONTROLLED_PSYCHOLOGICAL_OUTPUT[
            :,
            11:22,
        ]
    )


    PREDICTED_IEV = (
        CONTROLLED_PSYCHOLOGICAL_OUTPUT[
            :,
            22:33,
        ]
    )


    PREDICTED_EW = (
        CONTROLLED_PSYCHOLOGICAL_OUTPUT[
            :,
            33:34,
        ]
    )


else:

    raise TypeError(
        "Unsupported psychological-head output type: "
        f"{type(CONTROLLED_PSYCHOLOGICAL_OUTPUT).__name__}"
    )


# -----------------------------------------------------------------------------
# Psychological output validation
# -----------------------------------------------------------------------------

PSYCHOLOGICAL_OUTPUT_SHAPES_VALID = all(
    [
        tuple(
            PREDICTED_REV.shape
        )
        == EXPECTED_VECTOR_TARGET_SHAPE,

        tuple(
            PREDICTED_TEV.shape
        )
        == EXPECTED_VECTOR_TARGET_SHAPE,

        tuple(
            PREDICTED_IEV.shape
        )
        == EXPECTED_VECTOR_TARGET_SHAPE,

        tuple(
            PREDICTED_EW.shape
        )
        == EXPECTED_SCALAR_TARGET_SHAPE,
    ]
)


if not PSYCHOLOGICAL_OUTPUT_SHAPES_VALID:

    raise ValueError(
        "Psychological-head output shapes do not match the "
        "validated supervision contract."
    )


PSYCHOLOGICAL_OUTPUTS_FINITE = all(
    bool(
        torch.isfinite(
            output
        ).all()
        .item()
    )

    for output
    in (
        PREDICTED_REV,
        PREDICTED_TEV,
        PREDICTED_IEV,
        PREDICTED_EW,
    )
)


if not PSYCHOLOGICAL_OUTPUTS_FINITE:

    raise ValueError(
        "Psychological-head controlled forward output contains "
        "non-finite values."
    )


# =============================================================================
# Controlled masked objective calculation
# =============================================================================

REV_LOSS = masked_mean_squared_error(
    prediction=
        PREDICTED_REV,

    target=
        BLOCK_6_REV_TARGETS,

    mask=
        BLOCK_6_REV_MASK,
)


TEV_LOSS = masked_mean_squared_error(
    prediction=
        PREDICTED_TEV,

    target=
        BLOCK_6_TEV_TARGETS,

    mask=
        BLOCK_6_TEV_MASK,
)


IEV_LOSS = masked_mean_squared_error(
    prediction=
        PREDICTED_IEV,

    target=
        BLOCK_6_IEV_TARGETS,

    mask=
        BLOCK_6_IEV_MASK,
)


EW_LOSS = masked_mean_squared_error(
    prediction=
        PREDICTED_EW,

    target=
        BLOCK_6_EW_TARGETS,

    mask=
        BLOCK_6_EW_MASK,
)


OBJECTIVE_LOSSES = OrderedDict(
    [
        (
            "REV",
            REV_LOSS,
        ),

        (
            "TEV",
            TEV_LOSS,
        ),

        (
            "IEV",
            IEV_LOSS,
        ),

        (
            "EW",
            EW_LOSS,
        ),
    ]
)


WEIGHTED_OBJECTIVE_COMPONENTS = OrderedDict(
    (
        target_name,
        (
            OBJECTIVE_LOSSES[
                target_name
            ]
            *
            OBJECTIVE_WEIGHTS[
                target_name
            ]
        ),
    )

    for target_name
    in ACTIVE_SUPERVISED_TARGETS
)


TOTAL_SUPERVISED_OBJECTIVE = (
    sum(
        WEIGHTED_OBJECTIVE_COMPONENTS.values()
    )
    /
    OBJECTIVE_WEIGHT_SUM
)


TOTAL_OBJECTIVE_FINITE = bool(
    torch.isfinite(
        TOTAL_SUPERVISED_OBJECTIVE
    ).item()
)


TOTAL_OBJECTIVE_SCALAR = (
    TOTAL_SUPERVISED_OBJECTIVE.ndim
    == 0
)


if not TOTAL_OBJECTIVE_FINITE:

    raise ValueError(
        "Total supervised objective is non-finite."
    )


if not TOTAL_OBJECTIVE_SCALAR:

    raise ValueError(
        "Total supervised objective must be scalar."
    )


# =============================================================================
# Objective activation contract
# =============================================================================

OBJECTIVE_ACTIVATION = OrderedDict(
    [
        (
            "REV",
            True,
        ),

        (
            "TEV",
            True,
        ),

        (
            "IEV",
            True,
        ),

        (
            "EW",
            True,
        ),

        (
            "factual_head",
            False,
        ),

        (
            "social_head",
            False,
        ),

        (
            "factual_transformation",
            False,
        ),

        (
            "psychological_transformation",
            False,
        ),

        (
            "social_transformation",
            False,
        ),

        (
            "TW_F",
            False,
        ),

        (
            "TW_P",
            False,
        ),

        (
            "TW_S",
            False,
        ),

        (
            "H_F",
            False,
        ),

        (
            "H_P",
            False,
        ),

        (
            "H_S",
            False,
        ),
    ]
)


UNAVAILABLE_OBJECTIVE_NAMES = (
    "factual_head",
    "social_head",
    "factual_transformation",
    "psychological_transformation",
    "social_transformation",
    "TW_F",
    "TW_P",
    "TW_S",
    "H_F",
    "H_P",
    "H_S",
)


UNAVAILABLE_OBJECTIVES_IN_LOSS = any(
    OBJECTIVE_ACTIVATION[
        objective_name
    ]

    for objective_name
    in UNAVAILABLE_OBJECTIVE_NAMES
)


if UNAVAILABLE_OBJECTIVES_IN_LOSS:

    raise ValueError(
        "An unavailable objective was incorrectly activated."
    )


# =============================================================================
# Optimiser construction
# =============================================================================
#
# Only the trainable psychological-head parameters enter AdamW.
#
# No zero_grad / backward / optimizer.step occurs in Block 6.
# =============================================================================

NOTEBOOK_05_OPTIMIZER = torch.optim.AdamW(
    PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETERS,
    lr=
        OPTIMIZER_LEARNING_RATE,
    betas=
        OPTIMIZER_BETAS,
    eps=
        OPTIMIZER_EPS,
    weight_decay=
        OPTIMIZER_WEIGHT_DECAY,
)


OPTIMIZER_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter_group
    in NOTEBOOK_05_OPTIMIZER.param_groups

    for parameter
    in parameter_group[
        "params"
    ]
}


OPTIMIZER_PARAMETERS_ALL_TRAINABLE = all(
    parameter.requires_grad

    for parameter_group
    in NOTEBOOK_05_OPTIMIZER.param_groups

    for parameter
    in parameter_group[
        "params"
    ]
)


OPTIMIZER_ONLY_PSYCHOLOGICAL_HEAD = (
    OPTIMIZER_PARAMETER_IDS
    ==
    PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETER_IDS
)


OPTIMIZER_PARAMETER_COUNT = sum(
    parameter.numel()

    for parameter_group
    in NOTEBOOK_05_OPTIMIZER.param_groups

    for parameter
    in parameter_group[
        "params"
    ]
)


if not OPTIMIZER_PARAMETERS_ALL_TRAINABLE:

    raise ValueError(
        "The optimiser contains frozen parameters."
    )


if not OPTIMIZER_ONLY_PSYCHOLOGICAL_HEAD:

    raise ValueError(
        "The optimiser contains parameters outside the explicitly "
        "trainable psychological head."
    )


# =============================================================================
# Training boundary
# =============================================================================

NOTEBOOK_05_OBJECTIVE_DEFINED = True

NOTEBOOK_05_OBJECTIVES_ACTIVATED = True

NOTEBOOK_05_OPTIMIZER_CREATED = True

NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED = True

NOTEBOOK_05_LOSS_CALCULATED = True

NOTEBOOK_05_OPTIMIZER_ZERO_GRAD_EXECUTED = False

NOTEBOOK_05_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_05_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_05_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_05_TRAINING_EXECUTED = False

NOTEBOOK_05_CHECKPOINT_SELECTED = False

NOTEBOOK_05_ABLATION_EXECUTED = False

NOTEBOOK_05_EVALUATION_EXECUTED = False

NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Block 6 methodological validation
# =============================================================================

NOTEBOOK_05_BLOCK_6_ERRORS = []


if not TARGET_SHAPES_VALID:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "target_shapes_invalid"
    )


if not all(
    OBJECTIVE_HAS_OBSERVED_ELEMENTS.values()
):

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "active_objective_without_observed_elements"
    )


if not ONLY_PSYCHOLOGICAL_HEAD_TRAINABLE:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "unexpected_trainable_parameter_group"
    )


if not BACKBONE_STAGE_FULLY_FROZEN:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "backbone_stage_not_frozen"
    )


if not CONFLUENT_STAGE_FULLY_FROZEN:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "confluent_stage_not_frozen"
    )


if not INPUT_SHAPE_VALID:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "controlled_input_shape_invalid"
    )


if not BACKBONE_OUTPUT_SHAPE_VALID:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "backbone_output_shape_invalid"
    )


if not CONFLUENT_OUTPUT_SHAPE_VALID:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "confluent_output_shape_invalid"
    )


if not BACKBONE_OUTPUT_FINITE:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "backbone_output_nonfinite"
    )


if not CONFLUENT_OUTPUT_FINITE:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "confluent_output_nonfinite"
    )


if not PSYCHOLOGICAL_OUTPUT_SHAPES_VALID:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "psychological_output_shapes_invalid"
    )


if not PSYCHOLOGICAL_OUTPUTS_FINITE:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "psychological_outputs_nonfinite"
    )


if not TOTAL_OBJECTIVE_SCALAR:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "total_objective_not_scalar"
    )


if not TOTAL_OBJECTIVE_FINITE:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "total_objective_nonfinite"
    )


if not OPTIMIZER_PARAMETERS_ALL_TRAINABLE:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "optimizer_contains_frozen_parameters"
    )


if not OPTIMIZER_ONLY_PSYCHOLOGICAL_HEAD:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "optimizer_contains_unapproved_parameters"
    )


if UNAVAILABLE_OBJECTIVES_IN_LOSS:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "unavailable_objective_activated"
    )


if NOTEBOOK_05_OPTIMIZER_ZERO_GRAD_EXECUTED:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "optimizer_zero_grad_incorrectly_executed"
    )


if NOTEBOOK_05_BACKWARD_PASS_EXECUTED:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "backward_pass_incorrectly_executed"
    )


if NOTEBOOK_05_OPTIMIZER_STEP_EXECUTED:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "optimizer_step_incorrectly_executed"
    )


if NOTEBOOK_05_PARAMETER_UPDATE_EXECUTED:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "parameter_update_incorrectly_executed"
    )


if NOTEBOOK_05_TRAINING_EXECUTED:

    NOTEBOOK_05_BLOCK_6_ERRORS.append(
        "training_incorrectly_executed"
    )


NOTEBOOK_05_BLOCK_6_VALID = (
    len(
        NOTEBOOK_05_BLOCK_6_ERRORS
    )
    == 0
)


if not NOTEBOOK_05_BLOCK_6_VALID:

    raise ValueError(
        "Notebook 05 Block 6 objective and optimiser audit failed. "
        f"Errors: {NOTEBOOK_05_BLOCK_6_ERRORS}"
    )


# -----------------------------------------------------------------------------
# Block completion
# -----------------------------------------------------------------------------

NOTEBOOK_05_BLOCK_6_COMPLETE = True


# =============================================================================
# Block 6 summary
# =============================================================================

NOTEBOOK_05_BLOCK_6_SUMMARY = {
    "block":
        NOTEBOOK_05_BLOCK_6,

    "block_name":
        NOTEBOOK_05_BLOCK_6_NAME,

    "objective_policy_version":
        OBJECTIVE_POLICY_VERSION,

    "active_supervised_targets":
        list(
            ACTIVE_SUPERVISED_TARGETS
        ),

    "objective_weights":
        dict(
            OBJECTIVE_WEIGHTS
        ),

    "observed_elements":
        dict(
            OBJECTIVE_OBSERVED_ELEMENTS
        ),

    "possible_elements":
        dict(
            OBJECTIVE_POSSIBLE_ELEMENTS
        ),

    "coverage":
        dict(
            OBJECTIVE_COVERAGE
        ),

    "controlled_input_shape":
        CONTROLLED_INPUT_SHAPE,

    "backbone_output_shape":
        CONTROLLED_BACKBONE_SHAPE,

    "confluent_output_shape":
        CONTROLLED_CONFLUENT_SHAPE,

    "psychological_output_shapes_valid":
        PSYCHOLOGICAL_OUTPUT_SHAPES_VALID,

    "losses":
        {
            target_name:
                float(
                    loss.detach()
                    .cpu()
                    .item()
                )

            for (
                target_name,
                loss,
            )
            in OBJECTIVE_LOSSES.items()
        },

    "total_objective":
        float(
            TOTAL_SUPERVISED_OBJECTIVE.detach()
            .cpu()
            .item()
        ),

    "optimizer":
        OPTIMIZER_NAME,

    "learning_rate":
        OPTIMIZER_LEARNING_RATE,

    "weight_decay":
        OPTIMIZER_WEIGHT_DECAY,

    "optimizer_parameter_count":
        OPTIMIZER_PARAMETER_COUNT,

    "psychological_head_trainable_parameters":
        PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETER_COUNT,

    "backbone_stage_frozen":
        BACKBONE_STAGE_FULLY_FROZEN,

    "confluent_stage_frozen":
        CONFLUENT_STAGE_FULLY_FROZEN,

    "controlled_forward_pass_executed":
        NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED,

    "loss_calculated":
        NOTEBOOK_05_LOSS_CALCULATED,

    "optimizer_created":
        NOTEBOOK_05_OPTIMIZER_CREATED,

    "backward_pass_executed":
        NOTEBOOK_05_BACKWARD_PASS_EXECUTED,

    "optimizer_step_executed":
        NOTEBOOK_05_OPTIMIZER_STEP_EXECUTED,

    "training_executed":
        NOTEBOOK_05_TRAINING_EXECUTED,

    "block_valid":
        NOTEBOOK_05_BLOCK_6_VALID,

    "block_complete":
        NOTEBOOK_05_BLOCK_6_COMPLETE,
}


# =============================================================================
# Verification
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 05, Block 6: "
    "Loss Assembly, Objective Activation and Optimiser Policy"
)

print("=" * 72)


print(
    f"Objective policy version     : "
    f"{OBJECTIVE_POLICY_VERSION}"
)


print("-" * 72)

print(
    "Supervised objective contract"
)

print(
    f"Active target families       : "
    f"{list(ACTIVE_SUPERVISED_TARGETS)}"
)

print(
    f"Objective weights            : "
    f"{dict(OBJECTIVE_WEIGHTS)}"
)

print(
    f"Unavailable objectives active: "
    f"{UNAVAILABLE_OBJECTIVES_IN_LOSS}"
)


print("-" * 72)

print(
    "Observed supervision"
)


for target_name in ACTIVE_SUPERVISED_TARGETS:

    print(
        f"{target_name:<5}"
        f" elements available / possible : "
        f"{OBJECTIVE_OBSERVED_ELEMENTS[target_name]} / "
        f"{OBJECTIVE_POSSIBLE_ELEMENTS[target_name]}"
    )


    print(
        f"{target_name:<5}"
        f" element coverage             : "
        f"{OBJECTIVE_COVERAGE[target_name]:.4f}"
    )


print("-" * 72)

print(
    "Controlled architectural forward path"
)

print(
    f"Input shape                  : "
    f"{CONTROLLED_INPUT_SHAPE}"
)

print(
    f"Input shape valid            : "
    f"{INPUT_SHAPE_VALID}"
)

print(
    f"Backbone output shape        : "
    f"{CONTROLLED_BACKBONE_SHAPE}"
)

print(
    f"Backbone shape valid         : "
    f"{BACKBONE_OUTPUT_SHAPE_VALID}"
)

print(
    f"Confluent output shape       : "
    f"{CONTROLLED_CONFLUENT_SHAPE}"
)

print(
    f"Confluent shape valid        : "
    f"{CONFLUENT_OUTPUT_SHAPE_VALID}"
)

print(
    f"Backbone output finite       : "
    f"{BACKBONE_OUTPUT_FINITE}"
)

print(
    f"Confluent output finite      : "
    f"{CONFLUENT_OUTPUT_FINITE}"
)

print(
    f"Backbone stage frozen        : "
    f"{BACKBONE_STAGE_FULLY_FROZEN}"
)

print(
    f"Confluent stage frozen       : "
    f"{CONFLUENT_STAGE_FULLY_FROZEN}"
)


print("-" * 72)

print(
    "Psychological output contract"
)

print(
    f"Psychological head attribute : "
    f"{PSYCHOLOGICAL_HEAD_ATTRIBUTE}"
)

print(
    f"REV output shape             : "
    f"{tuple(PREDICTED_REV.shape)}"
)

print(
    f"TEV output shape             : "
    f"{tuple(PREDICTED_TEV.shape)}"
)

print(
    f"IEV output shape             : "
    f"{tuple(PREDICTED_IEV.shape)}"
)

print(
    f"EW output shape              : "
    f"{tuple(PREDICTED_EW.shape)}"
)

print(
    f"Output shapes valid          : "
    f"{PSYCHOLOGICAL_OUTPUT_SHAPES_VALID}"
)

print(
    f"Output values finite         : "
    f"{PSYCHOLOGICAL_OUTPUTS_FINITE}"
)


print("-" * 72)

print(
    "Controlled masked objective"
)


for target_name in ACTIVE_SUPERVISED_TARGETS:

    print(
        f"{target_name:<5}"
        f" masked MSE                  : "
        f"{OBJECTIVE_LOSSES[target_name].detach().cpu().item():.8f}"
    )


print(
    f"Total weighted objective     : "
    f"{TOTAL_SUPERVISED_OBJECTIVE.detach().cpu().item():.8f}"
)

print(
    f"Total objective finite       : "
    f"{TOTAL_OBJECTIVE_FINITE}"
)

print(
    f"Total objective scalar       : "
    f"{TOTAL_OBJECTIVE_SCALAR}"
)


print("-" * 72)

print(
    "Optimiser policy"
)

print(
    f"Optimiser                    : "
    f"{OPTIMIZER_NAME}"
)

print(
    f"Learning rate                : "
    f"{OPTIMIZER_LEARNING_RATE}"
)

print(
    f"Weight decay                 : "
    f"{OPTIMIZER_WEIGHT_DECAY}"
)

print(
    f"Psychological trainable pars.: "
    f"{PSYCHOLOGICAL_HEAD_TRAINABLE_PARAMETER_COUNT}"
)

print(
    f"Optimiser parameter count    : "
    f"{OPTIMIZER_PARAMETER_COUNT}"
)

print(
    f"All optimiser pars trainable : "
    f"{OPTIMIZER_PARAMETERS_ALL_TRAINABLE}"
)

print(
    f"Only psychological head      : "
    f"{OPTIMIZER_ONLY_PSYCHOLOGICAL_HEAD}"
)


print("-" * 72)

print(
    "Execution state"
)

print(
    f"Objective defined            : "
    f"{NOTEBOOK_05_OBJECTIVE_DEFINED}"
)

print(
    f"Objectives activated         : "
    f"{NOTEBOOK_05_OBJECTIVES_ACTIVATED}"
)

print(
    f"Controlled forward pass      : "
    f"{NOTEBOOK_05_CONTROLLED_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_05_LOSS_CALCULATED}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_05_OPTIMIZER_CREATED}"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_05_OPTIMIZER_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_05_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_05_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_05_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Training executed            : "
    f"{NOTEBOOK_05_TRAINING_EXECUTED}"
)

print(
    f"Evaluation executed          : "
    f"{NOTEBOOK_05_EVALUATION_EXECUTED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_05_BLOCK_6_VALID}"
)

print(
    f"Block 6 complete             : "
    f"{NOTEBOOK_05_BLOCK_6_COMPLETE}"
)


print("=" * 72)


print(
    "Masked psychological supervision objectives assembled successfully."
)

print(
    "The controlled forward path preserves the validated Media AI "
    "architecture from contextual representation through the frozen "
    "backbone interface and frozen global confluent projection before "
    "the psychological head."
)

print(
    "REV, TEV, IEV and EW remain separate directly supervised "
    "target families."
)

print(
    "REV, TEV and IEV losses use independent element-level masks."
)

print(
    "EW uses an independent scalar supervision mask."
)

print(
    "Missing or insufficient-evidence target elements do not enter "
    "the supervised objective."
)

print(
    "TEV has not been treated as architectural psychological "
    "transformation supervision."
)

print(
    "EW has not been treated as TW_P supervision."
)

print(
    "No factual, social, Transformative Weight, architectural "
    "transformation or recurrent-state objective has been activated."
)

print(
    "Only explicitly trainable psychological-head parameters enter "
    "the optimiser."
)

print(
    "The frozen contextual representation generator, backbone interface, "
    "confluent layers and all other frozen Media AI parameter groups "
    "remain outside the optimiser."
)

print(
    "A controlled no-update forward pass was used only to validate "
    "architecture, output and masked-loss compatibility."
)

print(
    "No zero-gradient operation, backward pass, optimiser step, parameter "
    "update, training epoch, checkpoint selection, ablation or empirical "
    "evaluation has been executed."
)

print(
    "Block 7 may proceed to Controlled Supervised Training and "
    "Checkpoint Policy."
)

========================================================================
Media AI — Notebook 05, Block 6: Loss Assembly, Objective Activation and Optimiser Policy
========================================================================
Objective policy version     : 1.1
------------------------------------------------------------------------
Supervised objective contract
Active target families       : ['REV', 'TEV', 'IEV', 'EW']
Objective weights            : {'REV': 1.0, 'TEV': 1.0, 'IEV': 1.0, 'EW': 1.0}
Unavailable objectives active: False
------------------------------------------------------------------------
Observed supervision
REV   elements available / possible : 40 / 176
REV   element coverage             : 0.2273
TEV   elements available / possible : 176 / 176
TEV   element coverage             : 1.0000
IEV   elements available / possible : 176 / 176
IEV   element coverage             : 1.0000
EW    elements available / possible : 16 / 16
EW    element coverage             : 1.0000
------------------------------------------------------------------------
Controlled architectural forward path
Input shape                  : (16, 768)
Input shape valid            : True
Backbone output shape        : (16, 768)
Backbone shape valid         : True
Confluent output shape       : (16, 256)
Confluent shape valid        : True
Backbone output finite       : True
Confluent output finite      : True
Backbone stage frozen        : True
Confluent stage frozen       : True
------------------------------------------------------------------------
Psychological output contract
Psychological head attribute : psychological_head
REV output shape             : (16, 11)
TEV output shape             : (16, 11)
IEV output shape             : (16, 11)
EW output shape              : (16, 1)
Output shapes valid          : True
Output values finite         : True
------------------------------------------------------------------------
Controlled masked objective
REV   masked MSE                  : 0.02664234
TEV   masked MSE                  : 0.16728459
IEV   masked MSE                  : 0.20525590
EW    masked MSE                  : 0.01751145
Total weighted objective     : 0.10417357
Total objective finite       : True
Total objective scalar       : True
------------------------------------------------------------------------
Optimiser policy
Optimiser                    : AdamW
Learning rate                : 0.001
Weight decay                 : 0.0001
Psychological trainable pars.: 37538
Optimiser parameter count    : 37538
All optimiser pars trainable : True
Only psychological head      : True
------------------------------------------------------------------------
Execution state
Objective defined            : True
Objectives activated         : True
Controlled forward pass      : True
Loss calculated              : True
Optimiser created            : True
Zero grad executed           : False
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
Training executed            : False
Evaluation executed          : False
Block valid                  : True
Block 6 complete             : True
========================================================================
Masked psychological supervision objectives assembled successfully.
The controlled forward path preserves the validated Media AI architecture from contextual representation through the frozen backbone interface and frozen global confluent projection before the psychological head.
REV, TEV, IEV and EW remain separate directly supervised target families.
REV, TEV and IEV losses use independent element-level masks.
EW uses an independent scalar supervision mask.
Missing or insufficient-evidence target elements do not enter the supervised objective.
TEV has not been treated as architectural psychological transformation supervision.
EW has not been treated as TW_P supervision.
No factual, social, Transformative Weight, architectural transformation or recurrent-state objective has been activated.
Only explicitly trainable psychological-head parameters enter the optimiser.
The frozen contextual representation generator, backbone interface, confluent layers and all other frozen Media AI parameter groups remain outside the optimiser.
A controlled no-update forward pass was used only to validate architecture, output and masked-loss compatibility.
No zero-gradient operation, backward pass, optimiser step, parameter update, training epoch, checkpoint selection, ablation or empirical evaluation has been executed.
Block 7 may proceed to Controlled Supervised Training and Checkpoint Policy.

"""
## Block 7: Controlled Supervised Training and Checkpoint Policy

This block performs the first controlled parameter updates of the Media AI architecture.

The supervised training configuration remains intentionally narrow. The current validated dataset contains 16 sentence-level records from a single article, with contextual representations available for every sentence and direct supervision for REV, TEV, IEV and EW.

Only the psychological head is trainable. The contextual encoder, backbone interface, confluent representation layers, factual head, social head, group-conditioned adapters, architectural transformation mechanisms, Transformative Weight predictors and recurrent mechanisms remain frozen.

Training uses the four mask-aware supervised objective terms defined in Block 6:

- REV;
- TEV;
- IEV; and
- EW.

Each family retains its independent loss and explicit objective weight. REV continues to use its partial element-level supervision mask, while TEV, IEV and EW use their currently complete masks.

The block executes a deliberately limited optimisation run. Because all currently supervised sentences belong to one article, this stage is treated as a controlled training experiment rather than a statistically valid model-development result.

The training procedure must therefore:

- preserve the existing article sequence and sentence order;
- use only the training partition created in Block 4;
- keep all non-psychological-head parameters frozen;
- reset gradients explicitly before each optimisation step;
- calculate the same mask-aware supervised objective defined in Block 6;
- perform backpropagation only through the psychological head;
- verify that all gradients are finite;
- optionally clip gradients using an explicit configured maximum norm;
- execute only a limited number of epochs or optimisation steps;
- record the loss before and after optimisation;
- verify that at least one psychological-head parameter changed;
- verify that no frozen parameter changed; and
- stop immediately if a non-finite loss or gradient is encountered.

The block does not use validation-based early stopping because no independent validation article is currently available.

Any checkpoint created by this stage must therefore be labelled as a controlled experimental training checkpoint rather than a validated model checkpoint.

Checkpoint persistence must include the psychological-head state, optimiser state, training configuration, objective weights, training history, sentence and article counts, encoder identity, and the supervision coverage used during optimisation.

The checkpoint must not imply that factual, social, transformative, Transformative Weight or recurrent components have been trained.

The block may report optimisation behaviour such as training-loss reduction, gradient norms and parameter deltas, but these are computational diagnostics rather than evidence of generalisation or empirical validity.

No held-out evaluation, ablation, benchmark comparison or empirical-validity claim is performed in this block.
"""

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Block 7: Controlled Supervised Training and Checkpoint Policy
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone
import json
import math
import random

import numpy as np
import torch

from googleapiclient.http import MediaFileUpload


# =============================================================================
# Block dependency checks
# =============================================================================

required_block_3_objects = [
    "NOTEBOOK_05_BLOCK_3_COMPLETE",
    "NOTEBOOK_05_BLOCK_3_VALID",
    "MEDIA_AI_MODEL",
    "MODEL_DEVICE",
    "MODEL_DTYPE",
]


missing_block_3_objects = [
    object_name
    for object_name in required_block_3_objects
    if object_name not in globals()
]


if missing_block_3_objects:

    raise NameError(
        "Notebook 05 Block 3 is not initialised. "
        f"Missing: {missing_block_3_objects}"
    )


required_block_4_objects = [
    "NOTEBOOK_05_BLOCK_4_COMPLETE",
    "NOTEBOOK_05_BLOCK_4_VALID",
    "SEQUENTIAL_SENTENCE_RECORDS",
    "DATASET_SENTENCE_COUNT",
]


missing_block_4_objects = [
    object_name
    for object_name in required_block_4_objects
    if object_name not in globals()
]


if missing_block_4_objects:

    raise NameError(
        "Notebook 05 Block 4 is not initialised. "
        f"Missing: {missing_block_4_objects}"
    )


required_block_5_objects = [
    "NOTEBOOK_05_BLOCK_5_COMPLETE",
    "NOTEBOOK_05_BLOCK_5_VALID",
    "CONTEXTUAL_ENCODER_PROVIDER",
    "CONTEXTUAL_ENCODER_MODEL_ID",
    "NOTEBOOK_05_REPRESENTATION_DRIVE_FILE_ID",
]


missing_block_5_objects = [
    object_name
    for object_name in required_block_5_objects
    if object_name not in globals()
]


if missing_block_5_objects:

    raise NameError(
        "Notebook 05 Block 5 is not initialised. "
        f"Missing: {missing_block_5_objects}"
    )


required_block_6_objects = [
    "NOTEBOOK_05_BLOCK_6_COMPLETE",
    "NOTEBOOK_05_BLOCK_6_VALID",
    "ACTIVE_SUPERVISED_TARGETS",
    "OBJECTIVE_WEIGHTS",
    "NOTEBOOK_05_OPTIMIZER",
    "BLOCK_6_REPRESENTATIONS",
    "BLOCK_6_REV_TARGETS",
    "BLOCK_6_REV_MASK",
    "BLOCK_6_TEV_TARGETS",
    "BLOCK_6_TEV_MASK",
    "BLOCK_6_IEV_TARGETS",
    "BLOCK_6_IEV_MASK",
    "BLOCK_6_EW_TARGETS",
    "BLOCK_6_EW_MASK",
    "PSYCHOLOGICAL_HEAD_MODULE",
]


missing_block_6_objects = [
    object_name
    for object_name in required_block_6_objects
    if object_name not in globals()
]


if missing_block_6_objects:

    raise NameError(
        "Notebook 05 Block 6 is not initialised. "
        f"Missing: {missing_block_6_objects}"
    )


required_drive_objects = [
    "DRIVE_SERVICE_FOR_HANDOVER",
    "NOTEBOOK_05_DRIVE_SERVICE_INITIALISED",
    "NOTEBOOK_05_HANDOVER_DRIVE_FILE_ID",
]


missing_drive_objects = [
    object_name
    for object_name in required_drive_objects
    if object_name not in globals()
]


if missing_drive_objects:

    raise NameError(
        "Notebook 05 Drive persistence objects are not initialised. "
        f"Missing: {missing_drive_objects}"
    )


if not NOTEBOOK_05_BLOCK_3_COMPLETE or not NOTEBOOK_05_BLOCK_3_VALID:

    raise ValueError(
        "Notebook 05 Block 3 must be complete and valid."
    )


if not NOTEBOOK_05_BLOCK_4_COMPLETE or not NOTEBOOK_05_BLOCK_4_VALID:

    raise ValueError(
        "Notebook 05 Block 4 must be complete and valid."
    )


if not NOTEBOOK_05_BLOCK_5_COMPLETE or not NOTEBOOK_05_BLOCK_5_VALID:

    raise ValueError(
        "Notebook 05 Block 5 must be complete and valid."
    )


if not NOTEBOOK_05_BLOCK_6_COMPLETE or not NOTEBOOK_05_BLOCK_6_VALID:

    raise ValueError(
        "Notebook 05 Block 6 must be complete and valid."
    )


if not NOTEBOOK_05_DRIVE_SERVICE_INITIALISED:

    raise ValueError(
        "Notebook 05 Google Drive persistence service is not initialised."
    )


# =============================================================================
# Block configuration
# =============================================================================

NOTEBOOK_05_BLOCK_7 = 7

NOTEBOOK_05_BLOCK_7_NAME = (
    "Controlled Supervised Training and Checkpoint Policy"
)

NOTEBOOK_05_BLOCK_7_VERSION = "1.1"


BLOCK_7_RANDOM_SEED = 42

BLOCK_7_MAX_EPOCHS = 10

BLOCK_7_MAX_GRAD_NORM = 1.0

BLOCK_7_VALIDATION_BASED_EARLY_STOPPING = False

BLOCK_7_HELD_OUT_EVALUATION_EXECUTED = False

BLOCK_7_ABLATION_EXECUTED = False

BLOCK_7_EMPIRICAL_VALIDITY = False


BLOCK_7_CHECKPOINT_TYPE = (
    "controlled_experimental_training_checkpoint"
)

BLOCK_7_CHECKPOINT_FILENAME = (
    "notebook_05_controlled_training_checkpoint.pt"
)

BLOCK_7_CHECKPOINT_METADATA_FILENAME = (
    "notebook_05_controlled_training_checkpoint_metadata.json"
)


# -----------------------------------------------------------------------------
# Reproducibility
# -----------------------------------------------------------------------------

random.seed(
    BLOCK_7_RANDOM_SEED
)

np.random.seed(
    BLOCK_7_RANDOM_SEED
)

torch.manual_seed(
    BLOCK_7_RANDOM_SEED
)


if torch.cuda.is_available():

    torch.cuda.manual_seed_all(
        BLOCK_7_RANDOM_SEED
    )


# =============================================================================
# Active target contract
# =============================================================================

BLOCK_7_ALLOWED_TARGETS = (
    "REV",
    "TEV",
    "IEV",
    "EW",
)


BLOCK_7_ACTIVE_TARGETS = tuple(
    target_name

    for target_name
    in BLOCK_7_ALLOWED_TARGETS

    if target_name
    in ACTIVE_SUPERVISED_TARGETS
)


if (
    BLOCK_7_ACTIVE_TARGETS
    != BLOCK_7_ALLOWED_TARGETS
):

    raise ValueError(
        "Block 7 expected REV, TEV, IEV and EW to remain the "
        "active supervised objectives. "
        f"Received: {BLOCK_7_ACTIVE_TARGETS}"
    )


BLOCK_7_OBJECTIVE_WEIGHTS = {
    target_name:
        float(
            OBJECTIVE_WEIGHTS[
                target_name
            ]
        )

    for target_name
    in BLOCK_7_ACTIVE_TARGETS
}


# =============================================================================
# Training partition
# =============================================================================

BLOCK_7_TRAIN_INDICES = [
    record_index

    for record_index, record
    in enumerate(
        SEQUENTIAL_SENTENCE_RECORDS
    )

    if record.get(
        "partition"
    )
    == "train"
]


BLOCK_7_VALIDATION_INDICES = [
    record_index

    for record_index, record
    in enumerate(
        SEQUENTIAL_SENTENCE_RECORDS
    )

    if record.get(
        "partition"
    )
    == "validation"
]


BLOCK_7_TEST_INDICES = [
    record_index

    for record_index, record
    in enumerate(
        SEQUENTIAL_SENTENCE_RECORDS
    )

    if record.get(
        "partition"
    )
    == "test"
]


if not BLOCK_7_TRAIN_INDICES:

    raise ValueError(
        "Block 7 has no training records."
    )


BLOCK_7_TRAIN_RECORDS = [
    SEQUENTIAL_SENTENCE_RECORDS[
        record_index
    ]

    for record_index
    in BLOCK_7_TRAIN_INDICES
]


BLOCK_7_TRAIN_SENTENCE_COUNT = len(
    BLOCK_7_TRAIN_RECORDS
)


BLOCK_7_TRAIN_ARTICLE_IDS = list(
    dict.fromkeys(
        record[
            "article_id"
        ]

        for record
        in BLOCK_7_TRAIN_RECORDS
    )
)


BLOCK_7_TRAIN_ARTICLE_COUNT = len(
    BLOCK_7_TRAIN_ARTICLE_IDS
)


# -----------------------------------------------------------------------------
# Sequence-order validation
# -----------------------------------------------------------------------------

BLOCK_7_SEQUENCE_ORDER_VALID = True


for article_id in BLOCK_7_TRAIN_ARTICLE_IDS:

    article_records = [
        record

        for record
        in BLOCK_7_TRAIN_RECORDS

        if record[
            "article_id"
        ]
        == article_id
    ]


    sequence_positions = [
        int(
            record[
                "sequence_position"
            ]
        )

        for record
        in article_records
    ]


    if sequence_positions != sorted(
        sequence_positions
    ):

        BLOCK_7_SEQUENCE_ORDER_VALID = False


if not BLOCK_7_SEQUENCE_ORDER_VALID:

    raise ValueError(
        "Block 7 training sequence order is invalid."
    )


# =============================================================================
# Reuse validated Block 6 tensors
# =============================================================================

BLOCK_7_TRAIN_REPRESENTATIONS = (
    BLOCK_6_REPRESENTATIONS[
        BLOCK_7_TRAIN_INDICES
    ]
)


BLOCK_7_TARGET_TENSORS = {
    "REV":
        BLOCK_6_REV_TARGETS[
            BLOCK_7_TRAIN_INDICES
        ],

    "TEV":
        BLOCK_6_TEV_TARGETS[
            BLOCK_7_TRAIN_INDICES
        ],

    "IEV":
        BLOCK_6_IEV_TARGETS[
            BLOCK_7_TRAIN_INDICES
        ],

    "EW":
        BLOCK_6_EW_TARGETS[
            BLOCK_7_TRAIN_INDICES
        ],
}


BLOCK_7_MASK_TENSORS = {
    "REV":
        BLOCK_6_REV_MASK[
            BLOCK_7_TRAIN_INDICES
        ],

    "TEV":
        BLOCK_6_TEV_MASK[
            BLOCK_7_TRAIN_INDICES
        ],

    "IEV":
        BLOCK_6_IEV_MASK[
            BLOCK_7_TRAIN_INDICES
        ],

    "EW":
        BLOCK_6_EW_MASK[
            BLOCK_7_TRAIN_INDICES
        ],
}


# -----------------------------------------------------------------------------
# Tensor validation
# -----------------------------------------------------------------------------

BLOCK_7_TENSORS_FINITE = bool(
    torch.isfinite(
        BLOCK_7_TRAIN_REPRESENTATIONS
    ).all()
    .item()
)


if not BLOCK_7_TENSORS_FINITE:

    raise ValueError(
        "Block 7 contextual representations contain non-finite values."
    )


for target_name in BLOCK_7_ACTIVE_TARGETS:

    target_tensor = (
        BLOCK_7_TARGET_TENSORS[
            target_name
        ]
    )

    target_mask = (
        BLOCK_7_MASK_TENSORS[
            target_name
        ]
    )


    if target_tensor.shape != target_mask.shape:

        raise ValueError(
            f"{target_name} target and mask shapes differ."
        )


    if int(
        target_mask.sum()
        .item()
    ) <= 0:

        raise ValueError(
            f"{target_name} contains no observed training elements."
        )


# =============================================================================
# Exact architectural training path
# =============================================================================

BLOCK_7_BACKBONE_MODULE = (
    MEDIA_AI_MODEL.backbone
)

BLOCK_7_CONFLUENT_MODULE = (
    MEDIA_AI_MODEL.confluent
)

BLOCK_7_PSYCHOLOGICAL_HEAD = (
    MEDIA_AI_MODEL.psychological_head
)


if (
    BLOCK_7_PSYCHOLOGICAL_HEAD
    is not PSYCHOLOGICAL_HEAD_MODULE
):

    raise ValueError(
        "Block 7 psychological-head reference differs from "
        "the validated Block 6 module."
    )


# -----------------------------------------------------------------------------
# Frozen upstream validation
# -----------------------------------------------------------------------------

BLOCK_7_BACKBONE_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in BLOCK_7_BACKBONE_MODULE.parameters()
)


BLOCK_7_CONFLUENT_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in BLOCK_7_CONFLUENT_MODULE.parameters()
)


if not BLOCK_7_BACKBONE_FROZEN:

    raise ValueError(
        "Block 7 found trainable backbone-interface parameters."
    )


if not BLOCK_7_CONFLUENT_FROZEN:

    raise ValueError(
        "Block 7 found trainable confluent parameters."
    )


# -----------------------------------------------------------------------------
# Trainable parameter validation
# -----------------------------------------------------------------------------

BLOCK_7_PSYCHOLOGICAL_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter
    in BLOCK_7_PSYCHOLOGICAL_HEAD.parameters()
}


BLOCK_7_TRAINABLE_MODEL_PARAMETERS = [
    (
        parameter_name,
        parameter,
    )

    for parameter_name, parameter
    in MEDIA_AI_MODEL.named_parameters()

    if parameter.requires_grad
]


BLOCK_7_UNEXPECTED_TRAINABLE_PARAMETERS = [
    parameter_name

    for parameter_name, parameter
    in BLOCK_7_TRAINABLE_MODEL_PARAMETERS

    if id(
        parameter
    )
    not in BLOCK_7_PSYCHOLOGICAL_PARAMETER_IDS
]


BLOCK_7_ONLY_PSYCHOLOGICAL_HEAD_TRAINABLE = (
    bool(
        BLOCK_7_TRAINABLE_MODEL_PARAMETERS
    )
    and not BLOCK_7_UNEXPECTED_TRAINABLE_PARAMETERS
)


if not BLOCK_7_ONLY_PSYCHOLOGICAL_HEAD_TRAINABLE:

    raise ValueError(
        "Block 7 detected trainable parameters outside the "
        "psychological head: "
        f"{BLOCK_7_UNEXPECTED_TRAINABLE_PARAMETERS}"
    )


# =============================================================================
# Optimiser validation
# =============================================================================

BLOCK_7_OPTIMIZER = (
    NOTEBOOK_05_OPTIMIZER
)


if not isinstance(
    BLOCK_7_OPTIMIZER,
    torch.optim.Optimizer,
):

    raise TypeError(
        "NOTEBOOK_05_OPTIMIZER is not a PyTorch optimiser."
    )


BLOCK_7_OPTIMIZER_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter_group
    in BLOCK_7_OPTIMIZER.param_groups

    for parameter
    in parameter_group[
        "params"
    ]
}


BLOCK_7_TRAINABLE_PSYCHOLOGICAL_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter
    in BLOCK_7_PSYCHOLOGICAL_HEAD.parameters()

    if parameter.requires_grad
}


BLOCK_7_OPTIMIZER_ONLY_PSYCHOLOGICAL = (
    BLOCK_7_OPTIMIZER_PARAMETER_IDS
    ==
    BLOCK_7_TRAINABLE_PSYCHOLOGICAL_PARAMETER_IDS
)


if not BLOCK_7_OPTIMIZER_ONLY_PSYCHOLOGICAL:

    raise ValueError(
        "Block 7 optimiser parameters do not exactly match the "
        "trainable psychological-head parameter set."
    )


# =============================================================================
# Forward-path helper
# =============================================================================

def block_7_forward(
    representations,
    psychological_training,
):
    """
    Execute the validated Media AI training path:

        contextual representation
        -> frozen backbone interface
        -> frozen global confluent projection
        -> psychological head

    Frozen upstream modules are evaluated without gradient tracking.

    The psychological head may operate in training or evaluation mode.
    """

    BLOCK_7_BACKBONE_MODULE.eval()

    BLOCK_7_CONFLUENT_MODULE.eval()


    with torch.no_grad():

        backbone_output = (
            BLOCK_7_BACKBONE_MODULE(
                representations
            )
        )


        confluent_output = (
            BLOCK_7_CONFLUENT_MODULE.forward_global(
                backbone_output
            )
        )


    if psychological_training:

        BLOCK_7_PSYCHOLOGICAL_HEAD.train()

    else:

        BLOCK_7_PSYCHOLOGICAL_HEAD.eval()


    psychological_output = (
        BLOCK_7_PSYCHOLOGICAL_HEAD(
            confluent_output
        )
    )


    return (
        backbone_output,
        confluent_output,
        psychological_output,
    )


# =============================================================================
# Psychological output parser
# =============================================================================

def block_7_extract_outputs(
    raw_output,
):
    """
    Convert the psychological-head output into the canonical
    REV / TEV / IEV / EW output mapping.
    """

    if isinstance(
        raw_output,
        dict,
    ):

        required_keys = {
            "REV",
            "TEV",
            "IEV",
            "EW",
        }


        if required_keys.issubset(
            raw_output.keys()
        ):

            return {
                target_name:
                    raw_output[
                        target_name
                    ]

                for target_name
                in BLOCK_7_ACTIVE_TARGETS
            }


    if torch.is_tensor(
        raw_output
    ):

        if raw_output.ndim != 2:

            raise ValueError(
                "Combined psychological output must be two-dimensional."
            )


        if raw_output.shape[
            1
        ] != 34:

            raise ValueError(
                "Combined psychological output must contain "
                "34 dimensions."
            )


        return {
            "REV":
                raw_output[
                    :,
                    0:11,
                ],

            "TEV":
                raw_output[
                    :,
                    11:22,
                ],

            "IEV":
                raw_output[
                    :,
                    22:33,
                ],

            "EW":
                raw_output[
                    :,
                    33:34,
                ],
        }


    raise TypeError(
        "Unsupported psychological-head output contract."
    )


# =============================================================================
# Mask-aware objective
# =============================================================================

def block_7_masked_mse(
    prediction,
    target,
    mask,
):
    """
    Calculate MSE over observed target elements only.
    """

    if prediction.shape != target.shape:

        raise ValueError(
            "Prediction and target shapes differ. "
            f"Prediction: {tuple(prediction.shape)}, "
            f"target: {tuple(target.shape)}."
        )


    if target.shape != mask.shape:

        raise ValueError(
            "Target and mask shapes differ."
        )


    observed_count = int(
        mask.sum()
        .item()
    )


    if observed_count <= 0:

        raise ValueError(
            "Masked objective contains no observed elements."
        )


    squared_error = (
        prediction
        - target
    ) ** 2


    masked_error = (
        squared_error[
            mask
        ]
    )


    loss = (
        masked_error.mean()
    )


    if not bool(
        torch.isfinite(
            loss
        ).item()
    ):

        raise RuntimeError(
            "Non-finite masked objective encountered."
        )


    return loss


def block_7_objective(
    output_map,
):
    """
    Assemble the same explicitly weighted psychological objective
    validated in Block 6.
    """

    family_losses = OrderedDict()

    weighted_losses = []


    for target_name in BLOCK_7_ACTIVE_TARGETS:

        family_loss = (
            block_7_masked_mse(
                prediction=
                    output_map[
                        target_name
                    ],

                target=
                    BLOCK_7_TARGET_TENSORS[
                        target_name
                    ],

                mask=
                    BLOCK_7_MASK_TENSORS[
                        target_name
                    ],
            )
        )


        family_losses[
            target_name
        ] = family_loss


        weighted_losses.append(
            (
                BLOCK_7_OBJECTIVE_WEIGHTS[
                    target_name
                ]
                *
                family_loss
            )
        )


    total_weight = float(
        sum(
            BLOCK_7_OBJECTIVE_WEIGHTS.values()
        )
    )


    if total_weight <= 0.0:

        raise ValueError(
            "Block 7 total objective weight must be positive."
        )


    total_loss = (
        sum(
            weighted_losses
        )
        /
        total_weight
    )


    if not bool(
        torch.isfinite(
            total_loss
        ).item()
    ):

        raise RuntimeError(
            "Block 7 total objective is non-finite."
        )


    return (
        total_loss,
        family_losses,
    )


# =============================================================================
# Parameter snapshots before training
# =============================================================================

BLOCK_7_INITIAL_MODEL_STATE = {
    parameter_name:
        parameter.detach()
        .cpu()
        .clone()

    for parameter_name, parameter
    in MEDIA_AI_MODEL.named_parameters()
}


# =============================================================================
# Initial evaluation objective
# =============================================================================

with torch.no_grad():

    (
        BLOCK_7_INITIAL_BACKBONE_OUTPUT,
        BLOCK_7_INITIAL_CONFLUENT_OUTPUT,
        BLOCK_7_INITIAL_RAW_OUTPUT,
    ) = block_7_forward(
        representations=
            BLOCK_7_TRAIN_REPRESENTATIONS,

        psychological_training=
            False,
    )


    BLOCK_7_INITIAL_OUTPUTS = (
        block_7_extract_outputs(
            BLOCK_7_INITIAL_RAW_OUTPUT
        )
    )


    (
        BLOCK_7_INITIAL_TOTAL_LOSS,
        BLOCK_7_INITIAL_FAMILY_LOSSES,
    ) = block_7_objective(
        BLOCK_7_INITIAL_OUTPUTS
    )


BLOCK_7_INITIAL_LOSS_VALUE = float(
    BLOCK_7_INITIAL_TOTAL_LOSS.detach()
    .cpu()
    .item()
)


if not math.isfinite(
    BLOCK_7_INITIAL_LOSS_VALUE
):

    raise RuntimeError(
        "Initial Block 7 objective is non-finite."
    )


# =============================================================================
# Controlled supervised training
# =============================================================================

BLOCK_7_TRAINING_HISTORY = []

BLOCK_7_ZERO_GRAD_EXECUTED = False

BLOCK_7_BACKWARD_EXECUTED = False

BLOCK_7_OPTIMIZER_STEP_EXECUTED = False

BLOCK_7_PARAMETER_UPDATE_EXECUTED = False

BLOCK_7_NONFINITE_LOSS_DETECTED = False

BLOCK_7_NONFINITE_GRADIENT_DETECTED = False

BLOCK_7_MAX_OBSERVED_GRAD_NORM = 0.0


for epoch_index in range(
    BLOCK_7_MAX_EPOCHS
):

    BLOCK_7_OPTIMIZER.zero_grad(
        set_to_none=True
    )

    BLOCK_7_ZERO_GRAD_EXECUTED = True


    (
        backbone_output,
        confluent_output,
        raw_output,
    ) = block_7_forward(
        representations=
            BLOCK_7_TRAIN_REPRESENTATIONS,

        psychological_training=
            True,
    )


    output_map = (
        block_7_extract_outputs(
            raw_output
        )
    )


    (
        total_loss,
        family_losses,
    ) = block_7_objective(
        output_map
    )


    if not bool(
        torch.isfinite(
            total_loss
        ).item()
    ):

        BLOCK_7_NONFINITE_LOSS_DETECTED = True

        raise RuntimeError(
            "Non-finite supervised loss detected during "
            f"Block 7 epoch {epoch_index + 1}."
        )


    total_loss.backward()

    BLOCK_7_BACKWARD_EXECUTED = True


    psychological_gradients = []


    for parameter in (
        BLOCK_7_PSYCHOLOGICAL_HEAD.parameters()
    ):

        if parameter.grad is None:

            continue


        if not bool(
            torch.isfinite(
                parameter.grad
            ).all()
            .item()
        ):

            BLOCK_7_NONFINITE_GRADIENT_DETECTED = True

            raise RuntimeError(
                "Non-finite psychological-head gradient detected "
                f"during epoch {epoch_index + 1}."
            )


        psychological_gradients.append(
            parameter.grad
        )


    if not psychological_gradients:

        raise RuntimeError(
            "Block 7 produced no psychological-head gradients."
        )


    gradient_norm = (
        torch.nn.utils.clip_grad_norm_(
            BLOCK_7_PSYCHOLOGICAL_HEAD.parameters(),
            max_norm=
                BLOCK_7_MAX_GRAD_NORM,
        )
    )


    if torch.is_tensor(
        gradient_norm
    ):

        gradient_norm_value = float(
            gradient_norm.detach()
            .cpu()
            .item()
        )


    else:

        gradient_norm_value = float(
            gradient_norm
        )


    if not math.isfinite(
        gradient_norm_value
    ):

        BLOCK_7_NONFINITE_GRADIENT_DETECTED = True

        raise RuntimeError(
            "Non-finite Block 7 gradient norm detected."
        )


    BLOCK_7_MAX_OBSERVED_GRAD_NORM = max(
        BLOCK_7_MAX_OBSERVED_GRAD_NORM,
        gradient_norm_value,
    )


    BLOCK_7_OPTIMIZER.step()

    BLOCK_7_OPTIMIZER_STEP_EXECUTED = True


    BLOCK_7_TRAINING_HISTORY.append(
        {
            "epoch":
                int(
                    epoch_index + 1
                ),

            "total_loss":
                float(
                    total_loss.detach()
                    .cpu()
                    .item()
                ),

            "REV_loss":
                float(
                    family_losses[
                        "REV"
                    ].detach()
                    .cpu()
                    .item()
                ),

            "TEV_loss":
                float(
                    family_losses[
                        "TEV"
                    ].detach()
                    .cpu()
                    .item()
                ),

            "IEV_loss":
                float(
                    family_losses[
                        "IEV"
                    ].detach()
                    .cpu()
                    .item()
                ),

            "EW_loss":
                float(
                    family_losses[
                        "EW"
                    ].detach()
                    .cpu()
                    .item()
                ),

            "gradient_norm_before_clipping":
                float(
                    gradient_norm_value
                ),
        }
    )


# =============================================================================
# Final evaluation objective
# =============================================================================

with torch.no_grad():

    (
        BLOCK_7_FINAL_BACKBONE_OUTPUT,
        BLOCK_7_FINAL_CONFLUENT_OUTPUT,
        BLOCK_7_FINAL_RAW_OUTPUT,
    ) = block_7_forward(
        representations=
            BLOCK_7_TRAIN_REPRESENTATIONS,

        psychological_training=
            False,
    )


    BLOCK_7_FINAL_OUTPUTS = (
        block_7_extract_outputs(
            BLOCK_7_FINAL_RAW_OUTPUT
        )
    )


    (
        BLOCK_7_FINAL_TOTAL_LOSS,
        BLOCK_7_FINAL_FAMILY_LOSSES,
    ) = block_7_objective(
        BLOCK_7_FINAL_OUTPUTS
    )


BLOCK_7_FINAL_LOSS_VALUE = float(
    BLOCK_7_FINAL_TOTAL_LOSS.detach()
    .cpu()
    .item()
)


if not math.isfinite(
    BLOCK_7_FINAL_LOSS_VALUE
):

    raise RuntimeError(
        "Final Block 7 objective is non-finite."
    )


BLOCK_7_LOSS_REDUCTION = (
    BLOCK_7_INITIAL_LOSS_VALUE
    -
    BLOCK_7_FINAL_LOSS_VALUE
)


# =============================================================================
# Parameter-change audit
# =============================================================================

BLOCK_7_CHANGED_PARAMETER_NAMES = []

BLOCK_7_CHANGED_TRAINABLE_PARAMETER_NAMES = []

BLOCK_7_CHANGED_FROZEN_PARAMETER_NAMES = []

BLOCK_7_MAX_PARAMETER_DELTA = 0.0


for parameter_name, parameter in (
    MEDIA_AI_MODEL.named_parameters()
):

    initial_value = (
        BLOCK_7_INITIAL_MODEL_STATE[
            parameter_name
        ]
    )


    final_value = (
        parameter.detach()
        .cpu()
    )


    absolute_difference = (
        final_value
        -
        initial_value
    ).abs()


    maximum_delta = float(
        absolute_difference.max()
        .item()

        if absolute_difference.numel() > 0

        else 0.0
    )


    BLOCK_7_MAX_PARAMETER_DELTA = max(
        BLOCK_7_MAX_PARAMETER_DELTA,
        maximum_delta,
    )


    parameter_changed = not torch.equal(
        initial_value,
        final_value,
    )


    if parameter_changed:

        BLOCK_7_CHANGED_PARAMETER_NAMES.append(
            parameter_name
        )


        if parameter.requires_grad:

            BLOCK_7_CHANGED_TRAINABLE_PARAMETER_NAMES.append(
                parameter_name
            )


        else:

            BLOCK_7_CHANGED_FROZEN_PARAMETER_NAMES.append(
                parameter_name
            )


BLOCK_7_PARAMETER_UPDATE_EXECUTED = bool(
    BLOCK_7_CHANGED_TRAINABLE_PARAMETER_NAMES
)


BLOCK_7_TRAINABLE_PARAMETER_CHANGED = bool(
    BLOCK_7_CHANGED_TRAINABLE_PARAMETER_NAMES
)


BLOCK_7_FROZEN_PARAMETERS_UNCHANGED = (
    len(
        BLOCK_7_CHANGED_FROZEN_PARAMETER_NAMES
    )
    == 0
)


if not BLOCK_7_TRAINABLE_PARAMETER_CHANGED:

    raise RuntimeError(
        "Controlled training completed without changing any "
        "trainable psychological-head parameter."
    )


if not BLOCK_7_FROZEN_PARAMETERS_UNCHANGED:

    raise RuntimeError(
        "A frozen Media AI parameter changed during Block 7. "
        f"Changed frozen parameters: "
        f"{BLOCK_7_CHANGED_FROZEN_PARAMETER_NAMES}"
    )


# =============================================================================
# Final training-state validation
# =============================================================================

BLOCK_7_LOSSES_FINITE = all(
    math.isfinite(
        float(
            history_record[
                "total_loss"
            ]
        )
    )

    for history_record
    in BLOCK_7_TRAINING_HISTORY
)


BLOCK_7_GRADIENTS_FINITE = (
    not BLOCK_7_NONFINITE_GRADIENT_DETECTED
)


BLOCK_7_TRAINING_EXECUTED = all(
    [
        BLOCK_7_ZERO_GRAD_EXECUTED,
        BLOCK_7_BACKWARD_EXECUTED,
        BLOCK_7_OPTIMIZER_STEP_EXECUTED,
        BLOCK_7_PARAMETER_UPDATE_EXECUTED,
    ]
)


# =============================================================================
# Checkpoint construction
# =============================================================================

BLOCK_7_CHECKPOINT_CREATED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


BLOCK_7_SUPERVISION_COVERAGE = {
    target_name:
        {
            "observed_elements":
                int(
                    BLOCK_7_MASK_TENSORS[
                        target_name
                    ].sum()
                    .item()
                ),

            "possible_elements":
                int(
                    BLOCK_7_MASK_TENSORS[
                        target_name
                    ].numel()
                ),
        }

    for target_name
    in BLOCK_7_ACTIVE_TARGETS
}


BLOCK_7_CHECKPOINT = {
    "checkpoint_type":
        BLOCK_7_CHECKPOINT_TYPE,

    "notebook":
        "05_training_evaluation_and_validation",

    "block":
        NOTEBOOK_05_BLOCK_7,

    "block_version":
        NOTEBOOK_05_BLOCK_7_VERSION,

    "created_at_utc":
        BLOCK_7_CHECKPOINT_CREATED_AT_UTC,

    "project_random_seed":
        BLOCK_7_RANDOM_SEED,

    "model_state_dict":
        MEDIA_AI_MODEL.state_dict(),

    "psychological_head_state_dict":
        BLOCK_7_PSYCHOLOGICAL_HEAD.state_dict(),

    "optimizer_state_dict":
        BLOCK_7_OPTIMIZER.state_dict(),

    "training_configuration":
        {
            "epochs":
                BLOCK_7_MAX_EPOCHS,

            "max_gradient_norm":
                BLOCK_7_MAX_GRAD_NORM,

            "validation_based_early_stopping":
                False,

            "article_shuffle":
                False,

            "within_article_sentence_shuffle":
                False,

            "active_targets":
                list(
                    BLOCK_7_ACTIVE_TARGETS
                ),

            "objective_weights":
                deepcopy(
                    BLOCK_7_OBJECTIVE_WEIGHTS
                ),
        },

    "training_data":
        {
            "training_articles":
                BLOCK_7_TRAIN_ARTICLE_COUNT,

            "training_sentences":
                BLOCK_7_TRAIN_SENTENCE_COUNT,

            "validation_sentences":
                len(
                    BLOCK_7_VALIDATION_INDICES
                ),

            "test_sentences":
                len(
                    BLOCK_7_TEST_INDICES
                ),
        },

    "encoder":
        {
            "provider":
                CONTEXTUAL_ENCODER_PROVIDER,

            "model_id":
                CONTEXTUAL_ENCODER_MODEL_ID,

            "representation_artifact_file_id":
                NOTEBOOK_05_REPRESENTATION_DRIVE_FILE_ID,

            "frozen":
                True,
        },

    "supervision":
        deepcopy(
            BLOCK_7_SUPERVISION_COVERAGE
        ),

    "training_history":
        deepcopy(
            BLOCK_7_TRAINING_HISTORY
        ),

    "initial_total_objective":
        BLOCK_7_INITIAL_LOSS_VALUE,

    "final_total_objective":
        BLOCK_7_FINAL_LOSS_VALUE,

    "objective_reduction":
        BLOCK_7_LOSS_REDUCTION,

    "maximum_observed_gradient_norm":
        BLOCK_7_MAX_OBSERVED_GRAD_NORM,

    "maximum_parameter_delta":
        BLOCK_7_MAX_PARAMETER_DELTA,

    "methodological_boundary":
        {
            "controlled_experimental_training":
                True,

            "validated_model_checkpoint":
                False,

            "held_out_evaluation_performed":
                False,

            "ablation_performed":
                False,

            "empirical_validity":
                False,

            "factual_components_trained":
                False,

            "social_components_trained":
                False,

            "architectural_transformations_trained":
                False,

            "transformative_weights_trained":
                False,

            "recurrent_components_trained":
                False,
        },
}


# =============================================================================
# Local checkpoint persistence
# =============================================================================

torch.save(
    BLOCK_7_CHECKPOINT,
    BLOCK_7_CHECKPOINT_FILENAME,
)


BLOCK_7_LOCAL_CHECKPOINT_CREATED = True


BLOCK_7_CHECKPOINT_METADATA = {
    "checkpoint_type":
        BLOCK_7_CHECKPOINT_TYPE,

    "checkpoint_filename":
        BLOCK_7_CHECKPOINT_FILENAME,

    "created_at_utc":
        BLOCK_7_CHECKPOINT_CREATED_AT_UTC,

    "training_articles":
        BLOCK_7_TRAIN_ARTICLE_COUNT,

    "training_sentences":
        BLOCK_7_TRAIN_SENTENCE_COUNT,

    "epochs":
        BLOCK_7_MAX_EPOCHS,

    "active_targets":
        list(
            BLOCK_7_ACTIVE_TARGETS
        ),

    "objective_weights":
        deepcopy(
            BLOCK_7_OBJECTIVE_WEIGHTS
        ),

    "initial_total_objective":
        BLOCK_7_INITIAL_LOSS_VALUE,

    "final_total_objective":
        BLOCK_7_FINAL_LOSS_VALUE,

    "objective_reduction":
        BLOCK_7_LOSS_REDUCTION,

    "maximum_observed_gradient_norm":
        BLOCK_7_MAX_OBSERVED_GRAD_NORM,

    "maximum_parameter_delta":
        BLOCK_7_MAX_PARAMETER_DELTA,

    "validated_model_checkpoint":
        False,

    "empirical_validity":
        False,
}


with open(
    BLOCK_7_CHECKPOINT_METADATA_FILENAME,
    "w",
    encoding="utf-8",
) as metadata_file:

    json.dump(
        BLOCK_7_CHECKPOINT_METADATA,
        metadata_file,
        indent=2,
        ensure_ascii=False,
    )


BLOCK_7_LOCAL_METADATA_CREATED = True


# =============================================================================
# Google Drive persistence
# =============================================================================

BLOCK_7_DRIVE_SERVICE = (
    DRIVE_SERVICE_FOR_HANDOVER
)


# -----------------------------------------------------------------------------
# Resolve parent folder from Notebook 04 → 05 handover artefact
# -----------------------------------------------------------------------------

block_7_handover_metadata = (
    BLOCK_7_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_05_HANDOVER_DRIVE_FILE_ID,

        fields=
            "id,name,parents",
    )
    .execute()
)


BLOCK_7_PARENT_IDS = (
    block_7_handover_metadata.get(
        "parents",
        [],
    )
)


# -----------------------------------------------------------------------------
# Drive helper
# -----------------------------------------------------------------------------

def block_7_persist_file(
    local_filename,
    drive_filename,
    mimetype,
):
    """
    Create or update one exact-name Drive artefact.
    """

    escaped_name = (
        drive_filename.replace(
            "'",
            "\\'",
        )
    )


    search_response = (
        BLOCK_7_DRIVE_SERVICE.files()
        .list(
            q=(
                f"name = '{escaped_name}' "
                "and trashed = false"
            ),

            spaces=
                "drive",

            fields=
                "files(id,name,modifiedTime,parents)",

            orderBy=
                "modifiedTime desc",

            pageSize=
                10,
        )
        .execute()
    )


    matching_files = (
        search_response.get(
            "files",
            [],
        )
    )


    media = MediaFileUpload(
        local_filename,
        mimetype=
            mimetype,
        resumable=
            False,
    )


    if matching_files:

        drive_file = (
            BLOCK_7_DRIVE_SERVICE.files()
            .update(
                fileId=
                    matching_files[
                        0
                    ][
                        "id"
                    ],

                media_body=
                    media,

                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = (
            "updated"
        )


    else:

        metadata = {
            "name":
                drive_filename,
        }


        if BLOCK_7_PARENT_IDS:

            metadata[
                "parents"
            ] = BLOCK_7_PARENT_IDS


        drive_file = (
            BLOCK_7_DRIVE_SERVICE.files()
            .create(
                body=
                    metadata,

                media_body=
                    media,

                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = (
            "created"
        )


    return (
        drive_file,
        operation,
    )


# -----------------------------------------------------------------------------
# Persist binary checkpoint
# -----------------------------------------------------------------------------

(
    BLOCK_7_CHECKPOINT_DRIVE_FILE,
    BLOCK_7_CHECKPOINT_DRIVE_OPERATION,
) = block_7_persist_file(
    local_filename=
        BLOCK_7_CHECKPOINT_FILENAME,

    drive_filename=
        BLOCK_7_CHECKPOINT_FILENAME,

    mimetype=
        "application/octet-stream",
)


BLOCK_7_CHECKPOINT_DRIVE_FILE_ID = (
    BLOCK_7_CHECKPOINT_DRIVE_FILE.get(
        "id"
    )
)


# -----------------------------------------------------------------------------
# Persist JSON metadata
# -----------------------------------------------------------------------------

(
    BLOCK_7_METADATA_DRIVE_FILE,
    BLOCK_7_METADATA_DRIVE_OPERATION,
) = block_7_persist_file(
    local_filename=
        BLOCK_7_CHECKPOINT_METADATA_FILENAME,

    drive_filename=
        BLOCK_7_CHECKPOINT_METADATA_FILENAME,

    mimetype=
        "application/json",
)


BLOCK_7_METADATA_DRIVE_FILE_ID = (
    BLOCK_7_METADATA_DRIVE_FILE.get(
        "id"
    )
)


BLOCK_7_DRIVE_PERSISTENCE_VALID = all(
    [
        bool(
            BLOCK_7_CHECKPOINT_DRIVE_FILE_ID
        ),

        bool(
            BLOCK_7_METADATA_DRIVE_FILE_ID
        ),
    ]
)


if not BLOCK_7_DRIVE_PERSISTENCE_VALID:

    raise RuntimeError(
        "Block 7 checkpoint persistence to Google Drive failed."
    )


# =============================================================================
# Final Block 7 validation
# =============================================================================

BLOCK_7_CHECKPOINT_IS_EXPERIMENTAL = (
    BLOCK_7_CHECKPOINT_TYPE
    ==
    "controlled_experimental_training_checkpoint"
)


BLOCK_7_NO_VALIDATION_CLAIM = all(
    [
        not BLOCK_7_VALIDATION_BASED_EARLY_STOPPING,
        not BLOCK_7_HELD_OUT_EVALUATION_EXECUTED,
        not BLOCK_7_ABLATION_EXECUTED,
        not BLOCK_7_EMPIRICAL_VALIDITY,
    ]
)


NOTEBOOK_05_BLOCK_7_ERRORS = []


if BLOCK_7_TRAIN_SENTENCE_COUNT <= 0:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "no_training_sentences"
    )


if BLOCK_7_TRAIN_ARTICLE_COUNT <= 0:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "no_training_articles"
    )


if not BLOCK_7_SEQUENCE_ORDER_VALID:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "training_sequence_order_invalid"
    )


if not BLOCK_7_LOSSES_FINITE:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "training_loss_nonfinite"
    )


if not BLOCK_7_GRADIENTS_FINITE:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "training_gradient_nonfinite"
    )


if not BLOCK_7_ONLY_PSYCHOLOGICAL_HEAD_TRAINABLE:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "unexpected_trainable_parameter_group"
    )


if not BLOCK_7_OPTIMIZER_ONLY_PSYCHOLOGICAL:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "optimizer_scope_invalid"
    )


if not BLOCK_7_TRAINABLE_PARAMETER_CHANGED:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "trainable_parameters_unchanged"
    )


if not BLOCK_7_FROZEN_PARAMETERS_UNCHANGED:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "frozen_parameter_changed"
    )


if not BLOCK_7_TRAINING_EXECUTED:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "controlled_training_not_executed"
    )


if not BLOCK_7_LOCAL_CHECKPOINT_CREATED:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "local_checkpoint_not_created"
    )


if not BLOCK_7_LOCAL_METADATA_CREATED:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "local_checkpoint_metadata_not_created"
    )


if not BLOCK_7_DRIVE_PERSISTENCE_VALID:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "drive_checkpoint_persistence_invalid"
    )


if not BLOCK_7_CHECKPOINT_IS_EXPERIMENTAL:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "checkpoint_type_invalid"
    )


if not BLOCK_7_NO_VALIDATION_CLAIM:

    NOTEBOOK_05_BLOCK_7_ERRORS.append(
        "unsupported_validation_claim_detected"
    )


NOTEBOOK_05_BLOCK_7_VALID = (
    len(
        NOTEBOOK_05_BLOCK_7_ERRORS
    )
    == 0
)


if not NOTEBOOK_05_BLOCK_7_VALID:

    raise RuntimeError(
        "Notebook 05 Block 7 controlled supervised training "
        "validation failed. "
        f"Errors: {NOTEBOOK_05_BLOCK_7_ERRORS}"
    )


# =============================================================================
# Notebook execution state
# =============================================================================

NOTEBOOK_05_ZERO_GRAD_EXECUTED = (
    BLOCK_7_ZERO_GRAD_EXECUTED
)

NOTEBOOK_05_BACKWARD_PASS_EXECUTED = (
    BLOCK_7_BACKWARD_EXECUTED
)

NOTEBOOK_05_OPTIMIZER_STEP_EXECUTED = (
    BLOCK_7_OPTIMIZER_STEP_EXECUTED
)

NOTEBOOK_05_PARAMETER_UPDATE_EXECUTED = (
    BLOCK_7_PARAMETER_UPDATE_EXECUTED
)

NOTEBOOK_05_TRAINING_EXECUTED = (
    BLOCK_7_TRAINING_EXECUTED
)

NOTEBOOK_05_CHECKPOINT_SELECTED = False

NOTEBOOK_05_CONTROLLED_CHECKPOINT_CREATED = True

NOTEBOOK_05_ABLATION_EXECUTED = False

NOTEBOOK_05_EVALUATION_EXECUTED = False

NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED = False


NOTEBOOK_05_BLOCK_7_COMPLETE = True


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_05_BLOCK_7_SUMMARY = {
    "block":
        NOTEBOOK_05_BLOCK_7,

    "block_name":
        NOTEBOOK_05_BLOCK_7_NAME,

    "version":
        NOTEBOOK_05_BLOCK_7_VERSION,

    "training_articles":
        BLOCK_7_TRAIN_ARTICLE_COUNT,

    "training_sentences":
        BLOCK_7_TRAIN_SENTENCE_COUNT,

    "validation_sentences":
        len(
            BLOCK_7_VALIDATION_INDICES
        ),

    "test_sentences":
        len(
            BLOCK_7_TEST_INDICES
        ),

    "epochs":
        len(
            BLOCK_7_TRAINING_HISTORY
        ),

    "active_targets":
        list(
            BLOCK_7_ACTIVE_TARGETS
        ),

    "objective_weights":
        deepcopy(
            BLOCK_7_OBJECTIVE_WEIGHTS
        ),

    "initial_total_objective":
        BLOCK_7_INITIAL_LOSS_VALUE,

    "final_total_objective":
        BLOCK_7_FINAL_LOSS_VALUE,

    "objective_reduction":
        BLOCK_7_LOSS_REDUCTION,

    "maximum_observed_gradient_norm":
        BLOCK_7_MAX_OBSERVED_GRAD_NORM,

    "maximum_parameter_delta":
        BLOCK_7_MAX_PARAMETER_DELTA,

    "frozen_parameters_unchanged":
        BLOCK_7_FROZEN_PARAMETERS_UNCHANGED,

    "trainable_parameters_changed":
        BLOCK_7_TRAINABLE_PARAMETER_CHANGED,

    "checkpoint_type":
        BLOCK_7_CHECKPOINT_TYPE,

    "checkpoint_drive_file_id":
        BLOCK_7_CHECKPOINT_DRIVE_FILE_ID,

    "metadata_drive_file_id":
        BLOCK_7_METADATA_DRIVE_FILE_ID,

    "training_executed":
        NOTEBOOK_05_TRAINING_EXECUTED,

    "evaluation_executed":
        NOTEBOOK_05_EVALUATION_EXECUTED,

    "empirical_validity":
        NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_05_BLOCK_7_VALID,

    "block_complete":
        NOTEBOOK_05_BLOCK_7_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 05, Block 7: "
    "Controlled Supervised Training and Checkpoint Policy"
)

print("=" * 72)

print(
    f"Training policy version      : "
    f"{NOTEBOOK_05_BLOCK_7_VERSION}"
)


print("-" * 72)

print(
    "Training scope"
)

print(
    f"Training articles            : "
    f"{BLOCK_7_TRAIN_ARTICLE_COUNT}"
)

print(
    f"Training sentences           : "
    f"{BLOCK_7_TRAIN_SENTENCE_COUNT}"
)

print(
    f"Validation sentences         : "
    f"{len(BLOCK_7_VALIDATION_INDICES)}"
)

print(
    f"Test sentences               : "
    f"{len(BLOCK_7_TEST_INDICES)}"
)

print(
    f"Epochs executed              : "
    f"{len(BLOCK_7_TRAINING_HISTORY)}"
)

print(
    f"Within-article shuffle       : "
    f"{False}"
)

print(
    f"Article sequence preserved   : "
    f"{BLOCK_7_SEQUENCE_ORDER_VALID}"
)


print("-" * 72)

print(
    "Supervised objectives"
)

print(
    f"Active target families       : "
    f"{list(BLOCK_7_ACTIVE_TARGETS)}"
)

print(
    f"Objective weights            : "
    f"{BLOCK_7_OBJECTIVE_WEIGHTS}"
)

print(
    f"Mask-aware supervision       : "
    f"{True}"
)

print(
    f"Unavailable objectives active: "
    f"{False}"
)


print("-" * 72)

print(
    "Optimisation boundary"
)

print(
    f"Only psychological head      : "
    f"{BLOCK_7_ONLY_PSYCHOLOGICAL_HEAD_TRAINABLE}"
)

print(
    f"Optimiser scope valid        : "
    f"{BLOCK_7_OPTIMIZER_ONLY_PSYCHOLOGICAL}"
)

print(
    f"Backbone frozen              : "
    f"{BLOCK_7_BACKBONE_FROZEN}"
)

print(
    f"Confluent stage frozen       : "
    f"{BLOCK_7_CONFLUENT_FROZEN}"
)

print(
    f"Frozen parameters unchanged  : "
    f"{BLOCK_7_FROZEN_PARAMETERS_UNCHANGED}"
)

print(
    f"Trainable parameters changed : "
    f"{BLOCK_7_TRAINABLE_PARAMETER_CHANGED}"
)

print(
    f"Maximum parameter delta      : "
    f"{BLOCK_7_MAX_PARAMETER_DELTA:.8f}"
)


print("-" * 72)

print(
    "Gradient control"
)

print(
    f"Maximum gradient norm        : "
    f"{BLOCK_7_MAX_GRAD_NORM:.4f}"
)

print(
    f"Max observed pre-clip norm   : "
    f"{BLOCK_7_MAX_OBSERVED_GRAD_NORM:.8f}"
)

print(
    f"Finite gradients             : "
    f"{BLOCK_7_GRADIENTS_FINITE}"
)

print(
    f"Non-finite loss detected     : "
    f"{BLOCK_7_NONFINITE_LOSS_DETECTED}"
)


print("-" * 72)

print(
    "Controlled training objective"
)

print(
    f"Initial total objective      : "
    f"{BLOCK_7_INITIAL_LOSS_VALUE:.8f}"
)

print(
    f"Final total objective        : "
    f"{BLOCK_7_FINAL_LOSS_VALUE:.8f}"
)

print(
    f"Objective reduction          : "
    f"{BLOCK_7_LOSS_REDUCTION:.8f}"
)


for target_name in BLOCK_7_ACTIVE_TARGETS:

    initial_family_loss = float(
        BLOCK_7_INITIAL_FAMILY_LOSSES[
            target_name
        ].detach()
        .cpu()
        .item()
    )


    final_family_loss = float(
        BLOCK_7_FINAL_FAMILY_LOSSES[
            target_name
        ].detach()
        .cpu()
        .item()
    )


    print(
        f"{target_name:<5}"
        f" initial / final          : "
        f"{initial_family_loss:.8f} / "
        f"{final_family_loss:.8f}"
    )


print("-" * 72)

print(
    "Checkpoint policy"
)

print(
    f"Checkpoint type              : "
    f"{BLOCK_7_CHECKPOINT_TYPE}"
)

print(
    f"Checkpoint filename          : "
    f"{BLOCK_7_CHECKPOINT_FILENAME}"
)

print(
    f"Local checkpoint created     : "
    f"{BLOCK_7_LOCAL_CHECKPOINT_CREATED}"
)

print(
    f"Checkpoint Drive operation   : "
    f"{BLOCK_7_CHECKPOINT_DRIVE_OPERATION}"
)

print(
    f"Checkpoint Drive file ID     : "
    f"{BLOCK_7_CHECKPOINT_DRIVE_FILE_ID}"
)

print(
    f"Metadata Drive operation     : "
    f"{BLOCK_7_METADATA_DRIVE_OPERATION}"
)

print(
    f"Metadata Drive file ID       : "
    f"{BLOCK_7_METADATA_DRIVE_FILE_ID}"
)

print(
    f"Drive persistence valid      : "
    f"{BLOCK_7_DRIVE_PERSISTENCE_VALID}"
)

print(
    f"Validated model checkpoint   : "
    f"{False}"
)


print("-" * 72)

print(
    "Execution state"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_05_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_05_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_05_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_05_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Training executed            : "
    f"{NOTEBOOK_05_TRAINING_EXECUTED}"
)

print(
    f"Validation early stopping    : "
    f"{BLOCK_7_VALIDATION_BASED_EARLY_STOPPING}"
)

print(
    f"Held-out evaluation executed : "
    f"{BLOCK_7_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Ablation executed            : "
    f"{BLOCK_7_ABLATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{BLOCK_7_EMPIRICAL_VALIDITY}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_05_BLOCK_7_VALID}"
)

print(
    f"Block 7 complete             : "
    f"{NOTEBOOK_05_BLOCK_7_COMPLETE}"
)


print("=" * 72)


print(
    "Controlled supervised training completed successfully."
)

print(
    "Only the directly supervised psychological head was updated."
)

print(
    "REV, TEV, IEV and EW remained separate mask-aware "
    "supervised objectives."
)

print(
    "REV retained partial element-level supervision and missing "
    "elements did not enter the loss."
)

print(
    "The frozen backbone interface and confluent representation "
    "layers remained unchanged."
)

print(
    "All other non-psychological-head Media AI parameters remained "
    "frozen."
)

print(
    "No factual, social, architectural transformation, Transformative "
    "Weight or recurrent component was trained."
)

print(
    "The frozen contextual representation encoder remained outside "
    "the Media AI optimiser."
)

print(
    "Gradient finiteness and frozen-parameter invariance were "
    "verified explicitly."
)

print(
    "The resulting checkpoint is a controlled experimental training "
    "checkpoint and is not a validated model checkpoint."
)

print(
    "No validation-based early stopping was used because no independent "
    "validation article is currently available."
)

print(
    "Training-loss behaviour is a computational diagnostic and does "
    "not demonstrate generalisation or empirical validity."
)

print(
    "No held-out evaluation, ablation or empirical-validity claim "
    "has been performed."
)

print("=" * 72)

========================================================================
Media AI — Notebook 05, Block 7: Controlled Supervised Training and Checkpoint Policy
========================================================================
Training policy version      : 1.1
------------------------------------------------------------------------
Training scope
Training articles            : 1
Training sentences           : 16
Validation sentences         : 0
Test sentences               : 0
Epochs executed              : 10
Within-article shuffle       : False
Article sequence preserved   : True
------------------------------------------------------------------------
Supervised objectives
Active target families       : ['REV', 'TEV', 'IEV', 'EW']
Objective weights            : {'REV': 1.0, 'TEV': 1.0, 'IEV': 1.0, 'EW': 1.0}
Mask-aware supervision       : True
Unavailable objectives active: False
------------------------------------------------------------------------
Optimisation boundary
Only psychological head      : True
Optimiser scope valid        : True
Backbone frozen              : True
Confluent stage frozen       : True
Frozen parameters unchanged  : True
Trainable parameters changed : True
Maximum parameter delta      : 0.00994940
------------------------------------------------------------------------
Gradient control
Maximum gradient norm        : 1.0000
Max observed pre-clip norm   : 0.51347136
Finite gradients             : True
Non-finite loss detected     : False
------------------------------------------------------------------------
Controlled training objective
Initial total objective      : 0.10417357
Final total objective        : 0.01169837
Objective reduction          : 0.09247520
REV   initial / final          : 0.02664234 / 0.00536795
TEV   initial / final          : 0.16728459 / 0.01914624
IEV   initial / final          : 0.20525590 / 0.01906418
EW    initial / final          : 0.01751145 / 0.00321512
------------------------------------------------------------------------
Checkpoint policy
Checkpoint type              : controlled_experimental_training_checkpoint
Checkpoint filename          : notebook_05_controlled_training_checkpoint.pt
Local checkpoint created     : True
Checkpoint Drive operation   : created
Checkpoint Drive file ID     : 1W1R2NonX9vw7_oH9pnTo9nLzMbu9Jopb
Metadata Drive operation     : created
Metadata Drive file ID       : 1pQBvET8W8iPTKC0XiLybW3VIYF7Tc0_a
Drive persistence valid      : True
Validated model checkpoint   : False
------------------------------------------------------------------------
Execution state
Zero grad executed           : True
Backward pass executed       : True
Optimiser step executed      : True
Parameter update executed    : True
Training executed            : True
Validation early stopping    : False
Held-out evaluation executed : False
Ablation executed            : False
Empirical validity           : False
Block valid                  : True
Block 7 complete             : True
========================================================================
Controlled supervised training completed successfully.
Only the directly supervised psychological head was updated.
REV, TEV, IEV and EW remained separate mask-aware supervised objectives.
REV retained partial element-level supervision and missing elements did not enter the loss.
The frozen backbone interface and confluent representation layers remained unchanged.
All other non-psychological-head Media AI parameters remained frozen.
No factual, social, architectural transformation, Transformative Weight or recurrent component was trained.
The frozen contextual representation encoder remained outside the Media AI optimiser.
Gradient finiteness and frozen-parameter invariance were verified explicitly.
The resulting checkpoint is a controlled experimental training checkpoint and is not a validated model checkpoint.
No validation-based early stopping was used because no independent validation article is currently available.
Training-loss behaviour is a computational diagnostic and does not demonstrate generalisation or empirical validity.
No held-out evaluation, ablation or empirical-validity claim has been performed.
========================================================================

## Block 8 — Checkpoint Reload, Reproducibility and Training-State Validation

This block independently reloads and validates the controlled experimental training checkpoint produced by Block 7. Its purpose is to verify that the trained Notebook 05 state is portable, reproducible, and methodologically intact outside the in-memory training state that created it.

The block reloads the persisted checkpoint and associated metadata from Google Drive and reconstructs the required model and optimiser state without performing any additional optimisation. The restored psychological-head parameters are compared against the trained state produced by Block 7 to verify exact parameter reproduction.

The optimiser state is restored and checked for structural and numerical consistency, including its parameter-group configuration and association with the explicitly trainable psychological-head parameters. Restoring the optimiser does not authorise or execute further training.

The block also verifies that parameters designated as frozen by the Notebook 05 parameter policy remain consistent with the validated architectural state and have not been modified by checkpoint restoration.

Where the required persisted representations and supervision targets are available, the restored model is subjected to a controlled no-update forward pass and mask-aware objective calculation. This verifies that the restored checkpoint reproduces the expected post-training computational state without executing a backward pass or optimiser step.

Checkpoint metadata is validated independently of checkpoint-file existence. The audit confirms that the persisted artefacts preserve the methodological boundaries established by the preceding blocks, including:

- the checkpoint remains classified as a controlled experimental training checkpoint rather than a validated model checkpoint;
- only the directly supervised psychological head was trained;
- REV, TEV, IEV and EW remain separate mask-aware supervision objectives;
- partial REV supervision remains governed by element-level masking;
- missing or insufficient-evidence supervision remains distinct from numerical zero and negative evidence;
- TEV is not interpreted as supervision for the architectural psychological transformation mechanism;
- EW is not interpreted as supervision for `TW_P`;
- factual, social, architectural transformation, Transformative Weight and recurrent components remain outside the trained parameter scope;
- the contextual representation encoder, backbone interface and confluent stages remain frozen;
- no held-out validation, generalisation, ablation or empirical-validity claim is inferred from the checkpoint;
- article boundaries, causal processing and the prohibition of future-context access remain part of the model contract.

This block is strictly a checkpoint reload and reproducibility audit. It does not execute additional training, parameter updates, checkpoint selection, ablation, held-out evaluation or empirical validation.

Successful completion establishes that the controlled training state produced by Block 7 can be independently recovered and reproduced from its persisted artefacts before Notebook 05 proceeds to broader experimental diagnostics and final project-level validation.

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Block 8: Checkpoint Reload, Reproducibility and Training-State Validation
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone
import io
import json
import math

import numpy as np
import torch

from googleapiclient.http import MediaIoBaseDownload


# =============================================================================
# Block dependency checks
# =============================================================================

required_block_3_objects = [
    "NOTEBOOK_05_BLOCK_3_COMPLETE",
    "NOTEBOOK_05_BLOCK_3_VALID",
    "MediaAIReferenceModel",
    "MEDIA_AI_MODEL",
    "MODEL_DEVICE",
    "MODEL_DTYPE",
]


missing_block_3_objects = [
    object_name
    for object_name in required_block_3_objects
    if object_name not in globals()
]


if missing_block_3_objects:

    raise NameError(
        "Notebook 05 Block 3 is not initialised. "
        f"Missing: {missing_block_3_objects}"
    )


required_block_4_objects = [
    "NOTEBOOK_05_BLOCK_4_COMPLETE",
    "NOTEBOOK_05_BLOCK_4_VALID",
    "SEQUENTIAL_SENTENCE_RECORDS",
    "DATASET_SENTENCE_COUNT",
]


missing_block_4_objects = [
    object_name
    for object_name in required_block_4_objects
    if object_name not in globals()
]


if missing_block_4_objects:

    raise NameError(
        "Notebook 05 Block 4 is not initialised. "
        f"Missing: {missing_block_4_objects}"
    )


required_block_5_objects = [
    "NOTEBOOK_05_BLOCK_5_COMPLETE",
    "NOTEBOOK_05_BLOCK_5_VALID",
    "CONTEXTUAL_ENCODER_PROVIDER",
    "CONTEXTUAL_ENCODER_MODEL_ID",
]


missing_block_5_objects = [
    object_name
    for object_name in required_block_5_objects
    if object_name not in globals()
]


if missing_block_5_objects:

    raise NameError(
        "Notebook 05 Block 5 is not initialised. "
        f"Missing: {missing_block_5_objects}"
    )


required_block_6_objects = [
    "NOTEBOOK_05_BLOCK_6_COMPLETE",
    "NOTEBOOK_05_BLOCK_6_VALID",
    "ACTIVE_SUPERVISED_TARGETS",
    "OBJECTIVE_WEIGHTS",
    "OPTIMIZER_LEARNING_RATE",
    "OPTIMIZER_WEIGHT_DECAY",
    "OPTIMIZER_BETAS",
    "OPTIMIZER_EPS",
    "BLOCK_6_REPRESENTATIONS",
    "BLOCK_6_REV_TARGETS",
    "BLOCK_6_REV_MASK",
    "BLOCK_6_TEV_TARGETS",
    "BLOCK_6_TEV_MASK",
    "BLOCK_6_IEV_TARGETS",
    "BLOCK_6_IEV_MASK",
    "BLOCK_6_EW_TARGETS",
    "BLOCK_6_EW_MASK",
]


missing_block_6_objects = [
    object_name
    for object_name in required_block_6_objects
    if object_name not in globals()
]


if missing_block_6_objects:

    raise NameError(
        "Notebook 05 Block 6 is not initialised. "
        f"Missing: {missing_block_6_objects}"
    )


required_block_7_objects = [
    "NOTEBOOK_05_BLOCK_7_COMPLETE",
    "NOTEBOOK_05_BLOCK_7_VALID",
    "BLOCK_7_CHECKPOINT_TYPE",
    "BLOCK_7_CHECKPOINT_DRIVE_FILE_ID",
    "BLOCK_7_METADATA_DRIVE_FILE_ID",
    "BLOCK_7_FINAL_LOSS_VALUE",
    "BLOCK_7_FINAL_FAMILY_LOSSES",
    "BLOCK_7_INITIAL_MODEL_STATE",
    "BLOCK_7_OBJECTIVE_WEIGHTS",
    "BLOCK_7_ACTIVE_TARGETS",
]


missing_block_7_objects = [
    object_name
    for object_name in required_block_7_objects
    if object_name not in globals()
]


if missing_block_7_objects:

    raise NameError(
        "Notebook 05 Block 7 is not initialised. "
        f"Missing: {missing_block_7_objects}"
    )


required_drive_objects = [
    "DRIVE_SERVICE_FOR_HANDOVER",
    "NOTEBOOK_05_DRIVE_SERVICE_INITIALISED",
]


missing_drive_objects = [
    object_name
    for object_name in required_drive_objects
    if object_name not in globals()
]


if missing_drive_objects:

    raise NameError(
        "Notebook 05 Drive service is not initialised. "
        f"Missing: {missing_drive_objects}"
    )


if not NOTEBOOK_05_BLOCK_3_COMPLETE or not NOTEBOOK_05_BLOCK_3_VALID:

    raise ValueError(
        "Notebook 05 Block 3 must be complete and valid."
    )


if not NOTEBOOK_05_BLOCK_4_COMPLETE or not NOTEBOOK_05_BLOCK_4_VALID:

    raise ValueError(
        "Notebook 05 Block 4 must be complete and valid."
    )


if not NOTEBOOK_05_BLOCK_5_COMPLETE or not NOTEBOOK_05_BLOCK_5_VALID:

    raise ValueError(
        "Notebook 05 Block 5 must be complete and valid."
    )


if not NOTEBOOK_05_BLOCK_6_COMPLETE or not NOTEBOOK_05_BLOCK_6_VALID:

    raise ValueError(
        "Notebook 05 Block 6 must be complete and valid."
    )


if not NOTEBOOK_05_BLOCK_7_COMPLETE or not NOTEBOOK_05_BLOCK_7_VALID:

    raise ValueError(
        "Notebook 05 Block 7 must be complete and valid."
    )


if not NOTEBOOK_05_DRIVE_SERVICE_INITIALISED:

    raise ValueError(
        "Notebook 05 Google Drive service is not initialised."
    )


# =============================================================================
# Block configuration
# =============================================================================

NOTEBOOK_05_BLOCK_8 = 8

NOTEBOOK_05_BLOCK_8_NAME = (
    "Checkpoint Reload, Reproducibility and Training-State Validation"
)

NOTEBOOK_05_BLOCK_8_VERSION = "1.0"


BLOCK_8_OBJECTIVE_ATOL = 1e-8

BLOCK_8_OBJECTIVE_RTOL = 1e-6


BLOCK_8_CHECKPOINT_RELOAD_EXECUTED = False

BLOCK_8_METADATA_RELOAD_EXECUTED = False

BLOCK_8_OPTIMIZER_RELOAD_EXECUTED = False

BLOCK_8_CONTROLLED_FORWARD_EXECUTED = False

BLOCK_8_LOSS_RECALCULATED = False

BLOCK_8_BACKWARD_EXECUTED = False

BLOCK_8_OPTIMIZER_STEP_EXECUTED = False

BLOCK_8_PARAMETER_UPDATE_EXECUTED = False

BLOCK_8_TRAINING_EXECUTED = False

BLOCK_8_EVALUATION_EXECUTED = False

BLOCK_8_ABLATION_EXECUTED = False

BLOCK_8_EMPIRICAL_VALIDITY = False


BLOCK_8_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Google Drive download helper
# =============================================================================

BLOCK_8_DRIVE_SERVICE = (
    DRIVE_SERVICE_FOR_HANDOVER
)


def block_8_download_drive_bytes(
    file_id,
):
    """
    Download one Google Drive file into memory.
    """

    request = (
        BLOCK_8_DRIVE_SERVICE.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    download_complete = False


    while not download_complete:

        _, download_complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Download persisted Block 7 checkpoint
# =============================================================================

BLOCK_8_CHECKPOINT_BYTES = (
    block_8_download_drive_bytes(
        BLOCK_7_CHECKPOINT_DRIVE_FILE_ID
    )
)


if not BLOCK_8_CHECKPOINT_BYTES:

    raise ValueError(
        "Persisted Block 7 checkpoint could not be downloaded."
    )


BLOCK_8_CHECKPOINT_BUFFER = io.BytesIO(
    BLOCK_8_CHECKPOINT_BYTES
)


BLOCK_8_RELOADED_CHECKPOINT = torch.load(
    BLOCK_8_CHECKPOINT_BUFFER,
    map_location=
        "cpu",
    weights_only=
        False,
)


BLOCK_8_CHECKPOINT_RELOAD_EXECUTED = True


if not isinstance(
    BLOCK_8_RELOADED_CHECKPOINT,
    dict,
):

    raise TypeError(
        "Reloaded Block 7 checkpoint is not a dictionary."
    )


# =============================================================================
# Download persisted Block 7 metadata
# =============================================================================

BLOCK_8_METADATA_BYTES = (
    block_8_download_drive_bytes(
        BLOCK_7_METADATA_DRIVE_FILE_ID
    )
)


if not BLOCK_8_METADATA_BYTES:

    raise ValueError(
        "Persisted Block 7 checkpoint metadata could not be downloaded."
    )


BLOCK_8_RELOADED_METADATA = json.loads(
    BLOCK_8_METADATA_BYTES.decode(
        "utf-8"
    )
)


BLOCK_8_METADATA_RELOAD_EXECUTED = True


if not isinstance(
    BLOCK_8_RELOADED_METADATA,
    dict,
):

    raise TypeError(
        "Reloaded Block 7 metadata is not a dictionary."
    )


# =============================================================================
# Persisted checkpoint structural validation
# =============================================================================

BLOCK_8_REQUIRED_CHECKPOINT_KEYS = {
    "checkpoint_type",
    "notebook",
    "block",
    "block_version",
    "created_at_utc",
    "project_random_seed",
    "model_state_dict",
    "psychological_head_state_dict",
    "optimizer_state_dict",
    "training_configuration",
    "training_data",
    "encoder",
    "supervision",
    "training_history",
    "initial_total_objective",
    "final_total_objective",
    "objective_reduction",
    "maximum_observed_gradient_norm",
    "maximum_parameter_delta",
    "methodological_boundary",
}


BLOCK_8_CHECKPOINT_KEYS_PRESENT = (
    BLOCK_8_REQUIRED_CHECKPOINT_KEYS.issubset(
        BLOCK_8_RELOADED_CHECKPOINT.keys()
    )
)


if not BLOCK_8_CHECKPOINT_KEYS_PRESENT:

    missing_keys = sorted(
        BLOCK_8_REQUIRED_CHECKPOINT_KEYS
        -
        set(
            BLOCK_8_RELOADED_CHECKPOINT.keys()
        )
    )


    raise ValueError(
        "Reloaded Block 7 checkpoint is missing required keys: "
        f"{missing_keys}"
    )


# =============================================================================
# Persisted metadata structural validation
# =============================================================================

BLOCK_8_REQUIRED_METADATA_KEYS = {
    "checkpoint_type",
    "checkpoint_filename",
    "created_at_utc",
    "training_articles",
    "training_sentences",
    "epochs",
    "active_targets",
    "objective_weights",
    "initial_total_objective",
    "final_total_objective",
    "objective_reduction",
    "maximum_observed_gradient_norm",
    "maximum_parameter_delta",
    "validated_model_checkpoint",
    "empirical_validity",
}


BLOCK_8_METADATA_KEYS_PRESENT = (
    BLOCK_8_REQUIRED_METADATA_KEYS.issubset(
        BLOCK_8_RELOADED_METADATA.keys()
    )
)


if not BLOCK_8_METADATA_KEYS_PRESENT:

    missing_metadata_keys = sorted(
        BLOCK_8_REQUIRED_METADATA_KEYS
        -
        set(
            BLOCK_8_RELOADED_METADATA.keys()
        )
    )


    raise ValueError(
        "Reloaded Block 7 metadata is missing required keys: "
        f"{missing_metadata_keys}"
    )


# =============================================================================
# Checkpoint classification validation
# =============================================================================

BLOCK_8_CHECKPOINT_TYPE_VALID = (
    BLOCK_8_RELOADED_CHECKPOINT.get(
        "checkpoint_type"
    )
    ==
    "controlled_experimental_training_checkpoint"
)


BLOCK_8_METADATA_CHECKPOINT_TYPE_VALID = (
    BLOCK_8_RELOADED_METADATA.get(
        "checkpoint_type"
    )
    ==
    "controlled_experimental_training_checkpoint"
)


BLOCK_8_NOT_VALIDATED_MODEL = (
    BLOCK_8_RELOADED_METADATA.get(
        "validated_model_checkpoint"
    )
    is False
)


BLOCK_8_NO_EMPIRICAL_VALIDITY_CLAIM = (
    BLOCK_8_RELOADED_METADATA.get(
        "empirical_validity"
    )
    is False
)


# =============================================================================
# Methodological-boundary audit
# =============================================================================

BLOCK_8_METHOD_BOUNDARY = (
    BLOCK_8_RELOADED_CHECKPOINT[
        "methodological_boundary"
    ]
)


BLOCK_8_EXPECTED_METHOD_BOUNDARY = {
    "controlled_experimental_training":
        True,

    "validated_model_checkpoint":
        False,

    "held_out_evaluation_performed":
        False,

    "ablation_performed":
        False,

    "empirical_validity":
        False,

    "factual_components_trained":
        False,

    "social_components_trained":
        False,

    "architectural_transformations_trained":
        False,

    "transformative_weights_trained":
        False,

    "recurrent_components_trained":
        False,
}


BLOCK_8_METHOD_BOUNDARY_VALID = all(
    BLOCK_8_METHOD_BOUNDARY.get(
        boundary_name
    )
    ==
    expected_value

    for boundary_name, expected_value
    in BLOCK_8_EXPECTED_METHOD_BOUNDARY.items()
)


# -----------------------------------------------------------------------------
# Encoder boundary
# -----------------------------------------------------------------------------

BLOCK_8_ENCODER_METADATA = (
    BLOCK_8_RELOADED_CHECKPOINT[
        "encoder"
    ]
)


BLOCK_8_ENCODER_PROVIDER_VALID = (
    BLOCK_8_ENCODER_METADATA.get(
        "provider"
    )
    ==
    CONTEXTUAL_ENCODER_PROVIDER
)


BLOCK_8_ENCODER_MODEL_VALID = (
    BLOCK_8_ENCODER_METADATA.get(
        "model_id"
    )
    ==
    CONTEXTUAL_ENCODER_MODEL_ID
)


BLOCK_8_ENCODER_REMAINS_FROZEN = (
    BLOCK_8_ENCODER_METADATA.get(
        "frozen"
    )
    is True
)


# -----------------------------------------------------------------------------
# Supervision boundary
# -----------------------------------------------------------------------------

BLOCK_8_CHECKPOINT_ACTIVE_TARGETS = tuple(
    BLOCK_8_RELOADED_CHECKPOINT[
        "training_configuration"
    ][
        "active_targets"
    ]
)


BLOCK_8_ACTIVE_TARGETS_VALID = (
    BLOCK_8_CHECKPOINT_ACTIVE_TARGETS
    ==
    tuple(
        BLOCK_7_ACTIVE_TARGETS
    )
)


BLOCK_8_OBJECTIVE_WEIGHTS_VALID = all(
    np.isclose(
        float(
            BLOCK_8_RELOADED_CHECKPOINT[
                "training_configuration"
            ][
                "objective_weights"
            ][
                target_name
            ]
        ),
        float(
            BLOCK_7_OBJECTIVE_WEIGHTS[
                target_name
            ]
        ),
    )

    for target_name
    in BLOCK_7_ACTIVE_TARGETS
)


# =============================================================================
# Fresh model instantiation
# =============================================================================
#
# A new architecture instance is created rather than copying the currently
# trained runtime model.
# =============================================================================

BLOCK_8_RELOADED_MODEL = (
    MediaAIReferenceModel()
)


BLOCK_8_RELOADED_MODEL = (
    BLOCK_8_RELOADED_MODEL.to(
        device=
            MODEL_DEVICE,

        dtype=
            MODEL_DTYPE,
    )
)


# =============================================================================
# Restore requires_grad parameter policy
# =============================================================================
#
# Fresh architecture construction does not itself carry Block 3's
# requires_grad policy.
#
# The current validated runtime model is used only as the source of that
# policy, not as the source of restored parameter values.
# =============================================================================

BLOCK_8_RUNTIME_PARAMETER_POLICY = {
    parameter_name:
        bool(
            parameter.requires_grad
        )

    for parameter_name, parameter
    in MEDIA_AI_MODEL.named_parameters()
}


BLOCK_8_RELOADED_NAMED_PARAMETERS = dict(
    BLOCK_8_RELOADED_MODEL.named_parameters()
)


if (
    set(
        BLOCK_8_RUNTIME_PARAMETER_POLICY.keys()
    )
    !=
    set(
        BLOCK_8_RELOADED_NAMED_PARAMETERS.keys()
    )
):

    raise ValueError(
        "Fresh model parameter names do not match the validated "
        "Notebook 05 architecture."
    )


for parameter_name, requires_grad in (
    BLOCK_8_RUNTIME_PARAMETER_POLICY.items()
):

    BLOCK_8_RELOADED_NAMED_PARAMETERS[
        parameter_name
    ].requires_grad = requires_grad


# =============================================================================
# Load persisted model state
# =============================================================================

BLOCK_8_MODEL_LOAD_RESULT = (
    BLOCK_8_RELOADED_MODEL.load_state_dict(
        BLOCK_8_RELOADED_CHECKPOINT[
            "model_state_dict"
        ],
        strict=
            True,
    )
)


BLOCK_8_MODEL_STATE_LOAD_VALID = (
    len(
        BLOCK_8_MODEL_LOAD_RESULT.missing_keys
    )
    == 0
    and
    len(
        BLOCK_8_MODEL_LOAD_RESULT.unexpected_keys
    )
    == 0
)


if not BLOCK_8_MODEL_STATE_LOAD_VALID:

    raise ValueError(
        "Fresh model could not restore the persisted Block 7 "
        "state exactly."
    )


# =============================================================================
# Psychological-head exact-state validation
# =============================================================================

BLOCK_8_RELOADED_PSYCHOLOGICAL_HEAD = (
    BLOCK_8_RELOADED_MODEL.psychological_head
)


BLOCK_8_PERSISTED_PSYCHOLOGICAL_STATE = (
    BLOCK_8_RELOADED_CHECKPOINT[
        "psychological_head_state_dict"
    ]
)


BLOCK_8_RELOADED_PSYCHOLOGICAL_STATE = (
    BLOCK_8_RELOADED_PSYCHOLOGICAL_HEAD.state_dict()
)


BLOCK_8_CURRENT_TRAINED_PSYCHOLOGICAL_STATE = (
    MEDIA_AI_MODEL.psychological_head.state_dict()
)


def block_8_state_dict_exact_match(
    state_a,
    state_b,
):
    """
    Require exact key and tensor equality.
    """

    if set(
        state_a.keys()
    ) != set(
        state_b.keys()
    ):

        return False


    for parameter_name in state_a.keys():

        value_a = state_a[
            parameter_name
        ]

        value_b = state_b[
            parameter_name
        ]


        if torch.is_tensor(
            value_a
        ) and torch.is_tensor(
            value_b
        ):

            if not torch.equal(
                value_a.detach()
                .cpu(),
                value_b.detach()
                .cpu(),
            ):

                return False


        else:

            if value_a != value_b:

                return False


    return True


BLOCK_8_PSYCHOLOGICAL_MATCHES_CHECKPOINT = (
    block_8_state_dict_exact_match(
        BLOCK_8_RELOADED_PSYCHOLOGICAL_STATE,
        BLOCK_8_PERSISTED_PSYCHOLOGICAL_STATE,
    )
)


BLOCK_8_PSYCHOLOGICAL_MATCHES_RUNTIME = (
    block_8_state_dict_exact_match(
        BLOCK_8_RELOADED_PSYCHOLOGICAL_STATE,
        BLOCK_8_CURRENT_TRAINED_PSYCHOLOGICAL_STATE,
    )
)


if not BLOCK_8_PSYCHOLOGICAL_MATCHES_CHECKPOINT:

    raise ValueError(
        "Reloaded psychological-head parameters do not exactly match "
        "the persisted checkpoint."
    )


if not BLOCK_8_PSYCHOLOGICAL_MATCHES_RUNTIME:

    raise ValueError(
        "Reloaded psychological-head parameters do not exactly match "
        "the trained Block 7 runtime state."
    )


# =============================================================================
# Frozen-parameter pre-training invariance audit
# =============================================================================
#
# Block 7 retained the complete pre-training model snapshot.
#
# Every parameter that remains frozen under the Block 3 policy is compared
# against that pre-training state.
# =============================================================================

BLOCK_8_FROZEN_PARAMETER_MISMATCHES = []


for parameter_name, parameter in (
    BLOCK_8_RELOADED_MODEL.named_parameters()
):

    if parameter.requires_grad:

        continue


    if parameter_name not in BLOCK_7_INITIAL_MODEL_STATE:

        BLOCK_8_FROZEN_PARAMETER_MISMATCHES.append(
            (
                parameter_name,
                "missing_pretraining_snapshot",
            )
        )

        continue


    restored_value = (
        parameter.detach()
        .cpu()
    )


    initial_value = (
        BLOCK_7_INITIAL_MODEL_STATE[
            parameter_name
        ]
    )


    if not torch.equal(
        restored_value,
        initial_value,
    ):

        BLOCK_8_FROZEN_PARAMETER_MISMATCHES.append(
            (
                parameter_name,
                "value_changed",
            )
        )


BLOCK_8_FROZEN_PARAMETERS_REPRODUCED = (
    len(
        BLOCK_8_FROZEN_PARAMETER_MISMATCHES
    )
    == 0
)


if not BLOCK_8_FROZEN_PARAMETERS_REPRODUCED:

    raise ValueError(
        "One or more frozen parameters differ from the pre-training "
        "architecture state: "
        f"{BLOCK_8_FROZEN_PARAMETER_MISMATCHES}"
    )


# =============================================================================
# Reconstruct optimiser
# =============================================================================

BLOCK_8_RELOADED_PSYCHOLOGICAL_PARAMETERS = [
    parameter

    for parameter
    in BLOCK_8_RELOADED_PSYCHOLOGICAL_HEAD.parameters()

    if parameter.requires_grad
]


if not BLOCK_8_RELOADED_PSYCHOLOGICAL_PARAMETERS:

    raise ValueError(
        "Reloaded psychological head contains no trainable parameters."
    )


BLOCK_8_RELOADED_OPTIMIZER = torch.optim.AdamW(
    BLOCK_8_RELOADED_PSYCHOLOGICAL_PARAMETERS,
    lr=
        OPTIMIZER_LEARNING_RATE,
    betas=
        OPTIMIZER_BETAS,
    eps=
        OPTIMIZER_EPS,
    weight_decay=
        OPTIMIZER_WEIGHT_DECAY,
)


BLOCK_8_RELOADED_OPTIMIZER.load_state_dict(
    BLOCK_8_RELOADED_CHECKPOINT[
        "optimizer_state_dict"
    ]
)


BLOCK_8_OPTIMIZER_RELOAD_EXECUTED = True


# =============================================================================
# Optimiser-state exact recovery audit
# =============================================================================

BLOCK_8_PERSISTED_OPTIMIZER_STATE = (
    BLOCK_8_RELOADED_CHECKPOINT[
        "optimizer_state_dict"
    ]
)


BLOCK_8_RESTORED_OPTIMIZER_STATE = (
    BLOCK_8_RELOADED_OPTIMIZER.state_dict()
)


def block_8_recursive_equal(
    left,
    right,
):
    """
    Recursive structural equality for nested optimiser-state objects.
    """

    if torch.is_tensor(
        left
    ) and torch.is_tensor(
        right
    ):

        return torch.equal(
            left.detach()
            .cpu(),
            right.detach()
            .cpu(),
        )


    if isinstance(
        left,
        dict,
    ) and isinstance(
        right,
        dict,
    ):

        if set(
            left.keys()
        ) != set(
            right.keys()
        ):

            return False


        return all(
            block_8_recursive_equal(
                left[
                    key
                ],
                right[
                    key
                ],
            )

            for key
            in left.keys()
        )


    if isinstance(
        left,
        (
            list,
            tuple,
        ),
    ) and isinstance(
        right,
        (
            list,
            tuple,
        ),
    ):

        if len(
            left
        ) != len(
            right
        ):

            return False


        return all(
            block_8_recursive_equal(
                left_value,
                right_value,
            )

            for left_value, right_value
            in zip(
                left,
                right,
            )
        )


    return left == right


BLOCK_8_OPTIMIZER_STATE_EXACT = (
    block_8_recursive_equal(
        BLOCK_8_PERSISTED_OPTIMIZER_STATE,
        BLOCK_8_RESTORED_OPTIMIZER_STATE,
    )
)


if not BLOCK_8_OPTIMIZER_STATE_EXACT:

    raise ValueError(
        "Reloaded optimiser state does not exactly reproduce the "
        "persisted Block 7 optimiser state."
    )


# -----------------------------------------------------------------------------
# Optimiser scope audit
# -----------------------------------------------------------------------------

BLOCK_8_OPTIMIZER_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter_group
    in BLOCK_8_RELOADED_OPTIMIZER.param_groups

    for parameter
    in parameter_group[
        "params"
    ]
}


BLOCK_8_RELOADED_PSYCHOLOGICAL_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter
    in BLOCK_8_RELOADED_PSYCHOLOGICAL_HEAD.parameters()

    if parameter.requires_grad
}


BLOCK_8_OPTIMIZER_SCOPE_VALID = (
    BLOCK_8_OPTIMIZER_PARAMETER_IDS
    ==
    BLOCK_8_RELOADED_PSYCHOLOGICAL_PARAMETER_IDS
)


if not BLOCK_8_OPTIMIZER_SCOPE_VALID:

    raise ValueError(
        "Reloaded optimiser scope does not exactly match the "
        "trainable psychological head."
    )


# =============================================================================
# Controlled restored forward path
# =============================================================================

BLOCK_8_RELOADED_MODEL.eval()

BLOCK_8_RELOADED_MODEL.backbone.eval()

BLOCK_8_RELOADED_MODEL.confluent.eval()

BLOCK_8_RELOADED_MODEL.psychological_head.eval()


with torch.no_grad():

    BLOCK_8_RESTORED_BACKBONE_OUTPUT = (
        BLOCK_8_RELOADED_MODEL.backbone(
            BLOCK_6_REPRESENTATIONS
        )
    )


    BLOCK_8_RESTORED_CONFLUENT_OUTPUT = (
        BLOCK_8_RELOADED_MODEL.confluent.forward_global(
            BLOCK_8_RESTORED_BACKBONE_OUTPUT
        )
    )


    BLOCK_8_RESTORED_RAW_OUTPUT = (
        BLOCK_8_RELOADED_MODEL.psychological_head(
            BLOCK_8_RESTORED_CONFLUENT_OUTPUT
        )
    )


BLOCK_8_CONTROLLED_FORWARD_EXECUTED = True


# =============================================================================
# Restored output contract
# =============================================================================

if not isinstance(
    BLOCK_8_RESTORED_RAW_OUTPUT,
    dict,
):

    raise TypeError(
        "Reloaded psychological head returned an unsupported "
        "output contract."
    )


required_psychological_output_keys = {
    "REV",
    "TEV",
    "IEV",
    "EW",
}


if not required_psychological_output_keys.issubset(
    BLOCK_8_RESTORED_RAW_OUTPUT.keys()
):

    raise ValueError(
        "Reloaded psychological output is missing one or more "
        "required supervision families."
    )


BLOCK_8_RESTORED_OUTPUTS = {
    target_name:
        BLOCK_8_RESTORED_RAW_OUTPUT[
            target_name
        ]

    for target_name
    in BLOCK_7_ACTIVE_TARGETS
}


# =============================================================================
# Restored masked objective
# =============================================================================

BLOCK_8_TARGET_TENSORS = {
    "REV":
        BLOCK_6_REV_TARGETS,

    "TEV":
        BLOCK_6_TEV_TARGETS,

    "IEV":
        BLOCK_6_IEV_TARGETS,

    "EW":
        BLOCK_6_EW_TARGETS,
}


BLOCK_8_MASK_TENSORS = {
    "REV":
        BLOCK_6_REV_MASK,

    "TEV":
        BLOCK_6_TEV_MASK,

    "IEV":
        BLOCK_6_IEV_MASK,

    "EW":
        BLOCK_6_EW_MASK,
}


def block_8_masked_mse(
    prediction,
    target,
    mask,
):
    """
    Recalculate the validated Block 6 / Block 7 masked MSE contract.
    """

    if prediction.shape != target.shape:

        raise ValueError(
            "Reloaded prediction and target shapes differ."
        )


    if target.shape != mask.shape:

        raise ValueError(
            "Reloaded target and mask shapes differ."
        )


    observed_count = int(
        mask.sum()
        .item()
    )


    if observed_count <= 0:

        raise ValueError(
            "Reloaded objective contains no observed target elements."
        )


    squared_error = (
        prediction
        - target
    ) ** 2


    loss = (
        squared_error[
            mask
        ].mean()
    )


    if not bool(
        torch.isfinite(
            loss
        ).item()
    ):

        raise ValueError(
            "Reloaded masked objective is non-finite."
        )


    return loss


BLOCK_8_RESTORED_FAMILY_LOSSES = {}


BLOCK_8_WEIGHTED_LOSS_TERMS = []


for target_name in BLOCK_7_ACTIVE_TARGETS:

    family_loss = (
        block_8_masked_mse(
            prediction=
                BLOCK_8_RESTORED_OUTPUTS[
                    target_name
                ],

            target=
                BLOCK_8_TARGET_TENSORS[
                    target_name
                ],

            mask=
                BLOCK_8_MASK_TENSORS[
                    target_name
                ],
        )
    )


    BLOCK_8_RESTORED_FAMILY_LOSSES[
        target_name
    ] = family_loss


    BLOCK_8_WEIGHTED_LOSS_TERMS.append(
        (
            BLOCK_7_OBJECTIVE_WEIGHTS[
                target_name
            ]
            *
            family_loss
        )
    )


BLOCK_8_TOTAL_OBJECTIVE_WEIGHT = float(
    sum(
        BLOCK_7_OBJECTIVE_WEIGHTS.values()
    )
)


BLOCK_8_RESTORED_TOTAL_OBJECTIVE = (
    sum(
        BLOCK_8_WEIGHTED_LOSS_TERMS
    )
    /
    BLOCK_8_TOTAL_OBJECTIVE_WEIGHT
)


BLOCK_8_RESTORED_TOTAL_OBJECTIVE_VALUE = float(
    BLOCK_8_RESTORED_TOTAL_OBJECTIVE.detach()
    .cpu()
    .item()
)


BLOCK_8_LOSS_RECALCULATED = True


# =============================================================================
# Post-training objective reproducibility
# =============================================================================

BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED = bool(
    np.isclose(
        BLOCK_8_RESTORED_TOTAL_OBJECTIVE_VALUE,
        BLOCK_7_FINAL_LOSS_VALUE,
        atol=
            BLOCK_8_OBJECTIVE_ATOL,
        rtol=
            BLOCK_8_OBJECTIVE_RTOL,
    )
)


BLOCK_8_FAMILY_OBJECTIVES_REPRODUCED = {}


for target_name in BLOCK_7_ACTIVE_TARGETS:

    block_7_family_value = float(
        BLOCK_7_FINAL_FAMILY_LOSSES[
            target_name
        ].detach()
        .cpu()
        .item()
    )


    block_8_family_value = float(
        BLOCK_8_RESTORED_FAMILY_LOSSES[
            target_name
        ].detach()
        .cpu()
        .item()
    )


    BLOCK_8_FAMILY_OBJECTIVES_REPRODUCED[
        target_name
    ] = bool(
        np.isclose(
            block_8_family_value,
            block_7_family_value,
            atol=
                BLOCK_8_OBJECTIVE_ATOL,
            rtol=
                BLOCK_8_OBJECTIVE_RTOL,
        )
    )


BLOCK_8_ALL_FAMILY_OBJECTIVES_REPRODUCED = all(
    BLOCK_8_FAMILY_OBJECTIVES_REPRODUCED.values()
)


if not BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED:

    raise ValueError(
        "Reloaded checkpoint does not reproduce the Block 7 "
        "post-training total objective."
    )


if not BLOCK_8_ALL_FAMILY_OBJECTIVES_REPRODUCED:

    raise ValueError(
        "Reloaded checkpoint does not reproduce one or more "
        "Block 7 target-family objectives."
    )


# =============================================================================
# Metadata / checkpoint cross-consistency
# =============================================================================

BLOCK_8_METADATA_ACTIVE_TARGETS_VALID = (
    tuple(
        BLOCK_8_RELOADED_METADATA[
            "active_targets"
        ]
    )
    ==
    tuple(
        BLOCK_7_ACTIVE_TARGETS
    )
)


BLOCK_8_METADATA_WEIGHTS_VALID = all(
    np.isclose(
        float(
            BLOCK_8_RELOADED_METADATA[
                "objective_weights"
            ][
                target_name
            ]
        ),
        float(
            BLOCK_7_OBJECTIVE_WEIGHTS[
                target_name
            ]
        ),
    )

    for target_name
    in BLOCK_7_ACTIVE_TARGETS
)


BLOCK_8_METADATA_FINAL_OBJECTIVE_VALID = bool(
    np.isclose(
        float(
            BLOCK_8_RELOADED_METADATA[
                "final_total_objective"
            ]
        ),
        BLOCK_8_RESTORED_TOTAL_OBJECTIVE_VALUE,
        atol=
            BLOCK_8_OBJECTIVE_ATOL,
        rtol=
            BLOCK_8_OBJECTIVE_RTOL,
    )
)


BLOCK_8_METADATA_CHECKPOINT_CONSISTENT = all(
    [
        BLOCK_8_METADATA_CHECKPOINT_TYPE_VALID,
        BLOCK_8_METADATA_ACTIVE_TARGETS_VALID,
        BLOCK_8_METADATA_WEIGHTS_VALID,
        BLOCK_8_METADATA_FINAL_OBJECTIVE_VALID,
        BLOCK_8_NOT_VALIDATED_MODEL,
        BLOCK_8_NO_EMPIRICAL_VALIDITY_CLAIM,
    ]
)


# =============================================================================
# Training-state invariants after reload
# =============================================================================

BLOCK_8_RELOADED_BACKBONE_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in BLOCK_8_RELOADED_MODEL.backbone.parameters()
)


BLOCK_8_RELOADED_CONFLUENT_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in BLOCK_8_RELOADED_MODEL.confluent.parameters()
)


BLOCK_8_RELOADED_PSYCHOLOGICAL_TRAINABLE = all(
    parameter.requires_grad

    for parameter
    in BLOCK_8_RELOADED_MODEL.psychological_head.parameters()
)


BLOCK_8_ONLY_PSYCHOLOGICAL_HEAD_TRAINABLE = all(
    (
        parameter_name.startswith(
            "psychological_head."
        )
        ==
        bool(
            parameter.requires_grad
        )
    )

    for parameter_name, parameter
    in BLOCK_8_RELOADED_MODEL.named_parameters()
)


# =============================================================================
# Explicit no-update boundary
# =============================================================================

BLOCK_8_BACKWARD_EXECUTED = False

BLOCK_8_OPTIMIZER_STEP_EXECUTED = False

BLOCK_8_PARAMETER_UPDATE_EXECUTED = False

BLOCK_8_TRAINING_EXECUTED = False

BLOCK_8_EVALUATION_EXECUTED = False

BLOCK_8_ABLATION_EXECUTED = False

BLOCK_8_EMPIRICAL_VALIDITY = False


# =============================================================================
# Final Block 8 validation
# =============================================================================

NOTEBOOK_05_BLOCK_8_ERRORS = []


if not BLOCK_8_CHECKPOINT_RELOAD_EXECUTED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "checkpoint_not_reloaded"
    )


if not BLOCK_8_METADATA_RELOAD_EXECUTED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "metadata_not_reloaded"
    )


if not BLOCK_8_CHECKPOINT_KEYS_PRESENT:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "checkpoint_contract_incomplete"
    )


if not BLOCK_8_METADATA_KEYS_PRESENT:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "metadata_contract_incomplete"
    )


if not BLOCK_8_CHECKPOINT_TYPE_VALID:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "checkpoint_type_invalid"
    )


if not BLOCK_8_METHOD_BOUNDARY_VALID:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "methodological_boundary_invalid"
    )


if not BLOCK_8_ENCODER_PROVIDER_VALID:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "encoder_provider_mismatch"
    )


if not BLOCK_8_ENCODER_MODEL_VALID:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "encoder_model_mismatch"
    )


if not BLOCK_8_ENCODER_REMAINS_FROZEN:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "encoder_not_marked_frozen"
    )


if not BLOCK_8_ACTIVE_TARGETS_VALID:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "active_target_contract_mismatch"
    )


if not BLOCK_8_OBJECTIVE_WEIGHTS_VALID:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "objective_weight_contract_mismatch"
    )


if not BLOCK_8_MODEL_STATE_LOAD_VALID:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "model_state_reload_invalid"
    )


if not BLOCK_8_PSYCHOLOGICAL_MATCHES_CHECKPOINT:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "psychological_state_checkpoint_mismatch"
    )


if not BLOCK_8_PSYCHOLOGICAL_MATCHES_RUNTIME:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "psychological_state_runtime_mismatch"
    )


if not BLOCK_8_FROZEN_PARAMETERS_REPRODUCED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "frozen_parameter_reproduction_invalid"
    )


if not BLOCK_8_OPTIMIZER_RELOAD_EXECUTED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "optimizer_not_reloaded"
    )


if not BLOCK_8_OPTIMIZER_STATE_EXACT:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "optimizer_state_mismatch"
    )


if not BLOCK_8_OPTIMIZER_SCOPE_VALID:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "optimizer_scope_invalid"
    )


if not BLOCK_8_CONTROLLED_FORWARD_EXECUTED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "controlled_forward_not_executed"
    )


if not BLOCK_8_LOSS_RECALCULATED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "objective_not_recalculated"
    )


if not BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "total_objective_not_reproduced"
    )


if not BLOCK_8_ALL_FAMILY_OBJECTIVES_REPRODUCED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "family_objective_not_reproduced"
    )


if not BLOCK_8_METADATA_CHECKPOINT_CONSISTENT:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "metadata_checkpoint_inconsistent"
    )


if not BLOCK_8_RELOADED_BACKBONE_FROZEN:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "reloaded_backbone_not_frozen"
    )


if not BLOCK_8_RELOADED_CONFLUENT_FROZEN:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "reloaded_confluent_not_frozen"
    )


if not BLOCK_8_RELOADED_PSYCHOLOGICAL_TRAINABLE:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "reloaded_psychological_head_not_trainable"
    )


if not BLOCK_8_ONLY_PSYCHOLOGICAL_HEAD_TRAINABLE:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "reloaded_trainability_scope_invalid"
    )


if BLOCK_8_BACKWARD_EXECUTED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "backward_pass_incorrectly_executed"
    )


if BLOCK_8_OPTIMIZER_STEP_EXECUTED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "optimizer_step_incorrectly_executed"
    )


if BLOCK_8_PARAMETER_UPDATE_EXECUTED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "parameter_update_incorrectly_executed"
    )


if BLOCK_8_TRAINING_EXECUTED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "training_incorrectly_executed"
    )


if BLOCK_8_EVALUATION_EXECUTED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "evaluation_incorrectly_executed"
    )


if BLOCK_8_ABLATION_EXECUTED:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "ablation_incorrectly_executed"
    )


if BLOCK_8_EMPIRICAL_VALIDITY:

    NOTEBOOK_05_BLOCK_8_ERRORS.append(
        "empirical_validity_incorrectly_asserted"
    )


NOTEBOOK_05_BLOCK_8_VALID = (
    len(
        NOTEBOOK_05_BLOCK_8_ERRORS
    )
    == 0
)


if not NOTEBOOK_05_BLOCK_8_VALID:

    raise RuntimeError(
        "Notebook 05 Block 8 checkpoint reproducibility audit failed. "
        f"Errors: {NOTEBOOK_05_BLOCK_8_ERRORS}"
    )


# =============================================================================
# Notebook execution state
# =============================================================================

NOTEBOOK_05_CHECKPOINT_RELOADED = True

NOTEBOOK_05_REPRODUCIBILITY_VALIDATED = True

NOTEBOOK_05_OPTIMIZER_STATE_RECOVERED = True

NOTEBOOK_05_CHECKPOINT_METADATA_VALIDATED = True

NOTEBOOK_05_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_05_TRAINING_EXECUTED_IN_BLOCK_8 = False

NOTEBOOK_05_EVALUATION_EXECUTED = False

NOTEBOOK_05_ABLATION_EXECUTED = False

NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED = False

NOTEBOOK_05_BLOCK_8_COMPLETE = True


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_05_BLOCK_8_SUMMARY = {
    "block":
        NOTEBOOK_05_BLOCK_8,

    "block_name":
        NOTEBOOK_05_BLOCK_8_NAME,

    "version":
        NOTEBOOK_05_BLOCK_8_VERSION,

    "executed_at_utc":
        BLOCK_8_EXECUTED_AT_UTC,

    "checkpoint_reloaded":
        BLOCK_8_CHECKPOINT_RELOAD_EXECUTED,

    "metadata_reloaded":
        BLOCK_8_METADATA_RELOAD_EXECUTED,

    "checkpoint_type_valid":
        BLOCK_8_CHECKPOINT_TYPE_VALID,

    "methodological_boundary_valid":
        BLOCK_8_METHOD_BOUNDARY_VALID,

    "psychological_state_matches_checkpoint":
        BLOCK_8_PSYCHOLOGICAL_MATCHES_CHECKPOINT,

    "psychological_state_matches_runtime":
        BLOCK_8_PSYCHOLOGICAL_MATCHES_RUNTIME,

    "frozen_parameters_reproduced":
        BLOCK_8_FROZEN_PARAMETERS_REPRODUCED,

    "optimizer_state_recovered":
        BLOCK_8_OPTIMIZER_STATE_EXACT,

    "optimizer_scope_valid":
        BLOCK_8_OPTIMIZER_SCOPE_VALID,

    "total_objective_reproduced":
        BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED,

    "family_objectives_reproduced":
        deepcopy(
            BLOCK_8_FAMILY_OBJECTIVES_REPRODUCED
        ),

    "restored_total_objective":
        BLOCK_8_RESTORED_TOTAL_OBJECTIVE_VALUE,

    "expected_total_objective":
        BLOCK_7_FINAL_LOSS_VALUE,

    "metadata_checkpoint_consistent":
        BLOCK_8_METADATA_CHECKPOINT_CONSISTENT,

    "backward_executed":
        BLOCK_8_BACKWARD_EXECUTED,

    "optimizer_step_executed":
        BLOCK_8_OPTIMIZER_STEP_EXECUTED,

    "parameter_update_executed":
        BLOCK_8_PARAMETER_UPDATE_EXECUTED,

    "training_executed":
        BLOCK_8_TRAINING_EXECUTED,

    "evaluation_executed":
        BLOCK_8_EVALUATION_EXECUTED,

    "empirical_validity":
        BLOCK_8_EMPIRICAL_VALIDITY,

    "block_valid":
        NOTEBOOK_05_BLOCK_8_VALID,

    "block_complete":
        NOTEBOOK_05_BLOCK_8_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 05, Block 8: "
    "Checkpoint Reload, Reproducibility and Training-State Validation"
)

print("=" * 72)

print(
    f"Reproducibility version      : "
    f"{NOTEBOOK_05_BLOCK_8_VERSION}"
)


print("-" * 72)

print(
    "Persisted artefact reload"
)

print(
    f"Checkpoint reloaded          : "
    f"{BLOCK_8_CHECKPOINT_RELOAD_EXECUTED}"
)

print(
    f"Metadata reloaded            : "
    f"{BLOCK_8_METADATA_RELOAD_EXECUTED}"
)

print(
    f"Checkpoint contract valid    : "
    f"{BLOCK_8_CHECKPOINT_KEYS_PRESENT}"
)

print(
    f"Metadata contract valid      : "
    f"{BLOCK_8_METADATA_KEYS_PRESENT}"
)

print(
    f"Checkpoint type valid        : "
    f"{BLOCK_8_CHECKPOINT_TYPE_VALID}"
)


print("-" * 72)

print(
    "Model-state reproduction"
)

print(
    f"Model state restored         : "
    f"{BLOCK_8_MODEL_STATE_LOAD_VALID}"
)

print(
    f"Psych. matches checkpoint    : "
    f"{BLOCK_8_PSYCHOLOGICAL_MATCHES_CHECKPOINT}"
)

print(
    f"Psych. matches runtime       : "
    f"{BLOCK_8_PSYCHOLOGICAL_MATCHES_RUNTIME}"
)

print(
    f"Frozen parameters reproduced : "
    f"{BLOCK_8_FROZEN_PARAMETERS_REPRODUCED}"
)

print(
    f"Backbone remains frozen      : "
    f"{BLOCK_8_RELOADED_BACKBONE_FROZEN}"
)

print(
    f"Confluent remains frozen     : "
    f"{BLOCK_8_RELOADED_CONFLUENT_FROZEN}"
)

print(
    f"Psychological head trainable : "
    f"{BLOCK_8_RELOADED_PSYCHOLOGICAL_TRAINABLE}"
)

print(
    f"Trainability scope valid     : "
    f"{BLOCK_8_ONLY_PSYCHOLOGICAL_HEAD_TRAINABLE}"
)


print("-" * 72)

print(
    "Optimiser-state recovery"
)

print(
    f"Optimiser reloaded           : "
    f"{BLOCK_8_OPTIMIZER_RELOAD_EXECUTED}"
)

print(
    f"Optimiser state exact        : "
    f"{BLOCK_8_OPTIMIZER_STATE_EXACT}"
)

print(
    f"Optimiser scope valid        : "
    f"{BLOCK_8_OPTIMIZER_SCOPE_VALID}"
)


print("-" * 72)

print(
    "Post-training objective reproduction"
)

print(
    f"Controlled forward executed  : "
    f"{BLOCK_8_CONTROLLED_FORWARD_EXECUTED}"
)

print(
    f"Objective recalculated       : "
    f"{BLOCK_8_LOSS_RECALCULATED}"
)

print(
    f"Expected total objective     : "
    f"{BLOCK_7_FINAL_LOSS_VALUE:.8f}"
)

print(
    f"Restored total objective     : "
    f"{BLOCK_8_RESTORED_TOTAL_OBJECTIVE_VALUE:.8f}"
)

print(
    f"Total objective reproduced   : "
    f"{BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED}"
)


for target_name in BLOCK_7_ACTIVE_TARGETS:

    expected_family_value = float(
        BLOCK_7_FINAL_FAMILY_LOSSES[
            target_name
        ].detach()
        .cpu()
        .item()
    )


    restored_family_value = float(
        BLOCK_8_RESTORED_FAMILY_LOSSES[
            target_name
        ].detach()
        .cpu()
        .item()
    )


    print(
        f"{target_name:<5}"
        f" expected / restored      : "
        f"{expected_family_value:.8f} / "
        f"{restored_family_value:.8f}"
    )


print(
    f"All family losses reproduced : "
    f"{BLOCK_8_ALL_FAMILY_OBJECTIVES_REPRODUCED}"
)


print("-" * 72)

print(
    "Methodological boundary"
)

print(
    f"Experimental checkpoint      : "
    f"{BLOCK_8_CHECKPOINT_TYPE_VALID}"
)

print(
    f"Validated model checkpoint   : "
    f"{not BLOCK_8_NOT_VALIDATED_MODEL}"
)

print(
    f"Method boundary preserved    : "
    f"{BLOCK_8_METHOD_BOUNDARY_VALID}"
)

print(
    f"Encoder identity preserved   : "
    f"{BLOCK_8_ENCODER_PROVIDER_VALID and BLOCK_8_ENCODER_MODEL_VALID}"
)

print(
    f"Encoder remains frozen       : "
    f"{BLOCK_8_ENCODER_REMAINS_FROZEN}"
)

print(
    f"Target contract preserved    : "
    f"{BLOCK_8_ACTIVE_TARGETS_VALID}"
)

print(
    f"Objective weights preserved  : "
    f"{BLOCK_8_OBJECTIVE_WEIGHTS_VALID}"
)

print(
    f"Metadata/checkpoint aligned  : "
    f"{BLOCK_8_METADATA_CHECKPOINT_CONSISTENT}"
)

print(
    f"Empirical validity claimed   : "
    f"{BLOCK_8_EMPIRICAL_VALIDITY}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Backward pass executed       : "
    f"{BLOCK_8_BACKWARD_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{BLOCK_8_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{BLOCK_8_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Additional training executed : "
    f"{BLOCK_8_TRAINING_EXECUTED}"
)

print(
    f"Held-out evaluation executed : "
    f"{BLOCK_8_EVALUATION_EXECUTED}"
)

print(
    f"Ablation executed            : "
    f"{BLOCK_8_ABLATION_EXECUTED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_05_BLOCK_8_VALID}"
)

print(
    f"Block 8 complete             : "
    f"{NOTEBOOK_05_BLOCK_8_COMPLETE}"
)


print("=" * 72)


print(
    "Persisted controlled training state reloaded and reproduced "
    "successfully."
)

print(
    "A fresh Media AI architecture instance restored the persisted "
    "Block 7 model state without using the trained runtime model as "
    "its parameter source."
)

print(
    "The restored psychological-head state exactly matches both the "
    "persisted checkpoint and the trained Block 7 runtime state."
)

print(
    "Frozen Media AI parameters remain identical to their pre-training "
    "architectural state."
)

print(
    "The persisted AdamW optimiser state was restored successfully and "
    "remains scoped exclusively to the trainable psychological head."
)

print(
    "The restored model reproduces the post-training REV, TEV, IEV and "
    "EW masked objectives within the configured numerical tolerance."
)

print(
    "The checkpoint remains explicitly classified as a controlled "
    "experimental training checkpoint rather than a validated model."
)

print(
    "The persisted methodological boundary continues to record that "
    "factual, social, architectural transformation, Transformative Weight "
    "and recurrent components were not trained."
)

print(
    "No backward pass, optimiser step, parameter update, additional "
    "training, held-out evaluation or ablation was performed by Block 8."
)

print(
    "Successful Block 8 completion establishes checkpoint portability "
    "and training-state reproducibility, not model generalisation or "
    "empirical validity."
)

print("=" * 72)

========================================================================
Media AI — Notebook 05, Block 8: Checkpoint Reload, Reproducibility and Training-State Validation
========================================================================
Reproducibility version      : 1.0
------------------------------------------------------------------------
Persisted artefact reload
Checkpoint reloaded          : True
Metadata reloaded            : True
Checkpoint contract valid    : True
Metadata contract valid      : True
Checkpoint type valid        : True
------------------------------------------------------------------------
Model-state reproduction
Model state restored         : True
Psych. matches checkpoint    : True
Psych. matches runtime       : True
Frozen parameters reproduced : True
Backbone remains frozen      : True
Confluent remains frozen     : True
Psychological head trainable : True
Trainability scope valid     : True
------------------------------------------------------------------------
Optimiser-state recovery
Optimiser reloaded           : True
Optimiser state exact        : True
Optimiser scope valid        : True
------------------------------------------------------------------------
Post-training objective reproduction
Controlled forward executed  : True
Objective recalculated       : True
Expected total objective     : 0.01169837
Restored total objective     : 0.01169837
Total objective reproduced   : True
REV   expected / restored      : 0.00536795 / 0.00536795
TEV   expected / restored      : 0.01914624 / 0.01914624
IEV   expected / restored      : 0.01906418 / 0.01906418
EW    expected / restored      : 0.00321512 / 0.00321512
All family losses reproduced : True
------------------------------------------------------------------------
Methodological boundary
Experimental checkpoint      : True
Validated model checkpoint   : False
Method boundary preserved    : True
Encoder identity preserved   : True
Encoder remains frozen       : True
Target contract preserved    : True
Objective weights preserved  : True
Metadata/checkpoint aligned  : True
Empirical validity claimed   : False
------------------------------------------------------------------------
Execution boundary
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
Additional training executed : False
Held-out evaluation executed : False
Ablation executed            : False
Block valid                  : True
Block 8 complete             : True
========================================================================
Persisted controlled training state reloaded and reproduced successfully.
A fresh Media AI architecture instance restored the persisted Block 7 model state without using the trained runtime model as its parameter source.
The restored psychological-head state exactly matches both the persisted checkpoint and the trained Block 7 runtime state.
Frozen Media AI parameters remain identical to their pre-training architectural state.
The persisted AdamW optimiser state was restored successfully and remains scoped exclusively to the trainable psychological head.
The restored model reproduces the post-training REV, TEV, IEV and EW masked objectives within the configured numerical tolerance.
The checkpoint remains explicitly classified as a controlled experimental training checkpoint rather than a validated model.
The persisted methodological boundary continues to record that factual, social, architectural transformation, Transformative Weight and recurrent components were not trained.
No backward pass, optimiser step, parameter update, additional training, held-out evaluation or ablation was performed by Block 8.
Successful Block 8 completion establishes checkpoint portability and training-state reproducibility, not model generalisation or empirical validity.
========================================================================

## Block 9 — Controlled Diagnostics, Evaluation Readiness and Project Scope Audit

This block evaluates the diagnostic state, empirical-evaluation readiness, and implementation scope of the Media AI system after successful controlled training and independent checkpoint-reload validation.

The purpose of the block is not to establish model generalisation or empirical validity. The currently available validated supervision consists of a single article containing sixteen supervised sentence records, and that article has already been used for controlled training. It therefore cannot also serve as an independent validation or test set.

The block first audits the available data partitions and confirms whether any genuinely held-out article-level supervision is available. Article boundaries remain the required partitioning unit so that sentences from the same article cannot be distributed across training and evaluation partitions in a way that would create contextual or sequential leakage.

Where no independent validation or test article is available, held-out performance metrics must remain unavailable rather than being estimated from the training article. Training-set quantities may be reported only as controlled computational diagnostics and must not be interpreted as evidence of generalisation.

The diagnostic audit verifies the successfully restored Block 7 checkpoint and may summarise the observed behaviour of the directly supervised psychological objectives:

- `REV`
- `TEV`
- `IEV`
- `EW`

These diagnostics remain mask-aware. Partially observed `REV` dimensions continue to exclude unavailable elements from calculations, and missing supervision remains distinct from numerical zero and negative evidence.

The block also performs an explicit project-scope audit against the architecture established in Notebook 04 and the supervision, training, and reproducibility state established in Notebook 05. Each major Media AI functionality is classified according to whether it is:

- architecturally implemented;
- structurally validated;
- supported by validated supervision;
- eligible for training;
- actually trained;
- independently evaluated;
- empirically validated.

The scope audit must preserve the distinction between architectural implementation and empirical training. In particular, it reviews the current status of:

- the textual representation stage;
- the global confluent-conditioning path;
- optional group-conditioned paths;
- the factual representation head;
- the psychological representation head;
- the structured social representation head;
- `REV`, `TEV`, `IEV`, and `EW`;
- factual, psychological, and social transformation mechanisms;
- `TW_F`, `TW_P`, and `TW_S`;
- `H_F`, `H_P`, and `H_S`;
- causal sequential processing;
- article-boundary recurrent-state reset;
- mask-aware supervision;
- checkpoint persistence and independent restoration.

No functionality is classified as trained merely because its architecture exists. No functionality is classified as empirically validated merely because its forward path is structurally executable.

The audit preserves the methodological distinctions established by the preceding notebooks. `TEV` remains a psychological supervision family and is not treated as direct supervision for the architectural psychological transformation mechanism. `EW` remains distinct from `TW_P`. Notebook 03 factological annotations are not automatically interpreted as supervision for the ten-dimensional factual architectural representation. Structured social targets, Transformative Weights, architectural transformations, and recurrent states remain unavailable for direct optimisation unless an independently justified supervision or indirect-objective contract has been established.

The block additionally determines whether the current five-notebook implementation satisfies the intended Version 1.0 project scope. This determination must distinguish between:

1. completion of the planned architecture and end-to-end computational pipeline;
2. successful controlled training of currently supervised components;
3. independent empirical validation of trained components; and
4. operational training of architectural components for which validated supervision is not yet available.

If the available evidence is insufficient to establish full empirical validation or full training coverage, the block records those limitations explicitly rather than extending the interpretation of the existing results.

No additional training, backward pass, optimiser step, parameter update, checkpoint selection, synthetic supervision, ablation, or unsupported held-out evaluation is performed by this block.

Successful completion establishes a documented diagnostic and scope state for Media AI Version 1.0 and provides the evidence required for Block 10 to perform the final Notebook 05 and project-level audit, persistence, and closure decision.

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Block 9: Controlled Diagnostics, Evaluation Readiness and Project Scope Audit
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import math
import numpy as np
import pandas as pd
import torch


# =============================================================================
# Dependency checks
# =============================================================================

required_block_4_objects = [
    "NOTEBOOK_05_BLOCK_4_COMPLETE",
    "NOTEBOOK_05_BLOCK_4_VALID",
    "SEQUENTIAL_SENTENCE_RECORDS",
    "ARTICLE_SEQUENCES",
    "TRAIN_ARTICLE_IDS",
    "VALIDATION_ARTICLE_IDS",
    "TEST_ARTICLE_IDS",
]


missing_block_4_objects = [
    object_name
    for object_name in required_block_4_objects
    if object_name not in globals()
]


if missing_block_4_objects:
    raise NameError(
        "Notebook 05 Block 4 is not initialised. "
        f"Missing: {missing_block_4_objects}"
    )


required_block_6_objects = [
    "NOTEBOOK_05_BLOCK_6_COMPLETE",
    "NOTEBOOK_05_BLOCK_6_VALID",
    "ACTIVE_SUPERVISED_TARGETS",
    "OBJECTIVE_WEIGHTS",
    "OBJECTIVE_OBSERVED_ELEMENTS",
    "OBJECTIVE_POSSIBLE_ELEMENTS",
    "OBJECTIVE_COVERAGE",
]


missing_block_6_objects = [
    object_name
    for object_name in required_block_6_objects
    if object_name not in globals()
]


if missing_block_6_objects:
    raise NameError(
        "Notebook 05 Block 6 is not initialised. "
        f"Missing: {missing_block_6_objects}"
    )


required_block_7_objects = [
    "NOTEBOOK_05_BLOCK_7_COMPLETE",
    "NOTEBOOK_05_BLOCK_7_VALID",
    "BLOCK_7_INITIAL_LOSS_VALUE",
    "BLOCK_7_FINAL_LOSS_VALUE",
    "BLOCK_7_LOSS_REDUCTION",
    "BLOCK_7_FINAL_FAMILY_LOSSES",
    "BLOCK_7_TRAIN_ARTICLE_COUNT",
    "BLOCK_7_TRAIN_SENTENCE_COUNT",
    "BLOCK_7_FROZEN_PARAMETERS_UNCHANGED",
    "BLOCK_7_TRAINABLE_PARAMETER_CHANGED",
    "BLOCK_7_CHECKPOINT_TYPE",
]


missing_block_7_objects = [
    object_name
    for object_name in required_block_7_objects
    if object_name not in globals()
]


if missing_block_7_objects:
    raise NameError(
        "Notebook 05 Block 7 is not initialised. "
        f"Missing: {missing_block_7_objects}"
    )


required_block_8_objects = [
    "NOTEBOOK_05_BLOCK_8_COMPLETE",
    "NOTEBOOK_05_BLOCK_8_VALID",
    "BLOCK_8_CHECKPOINT_RELOAD_EXECUTED",
    "BLOCK_8_METADATA_RELOAD_EXECUTED",
    "BLOCK_8_MODEL_STATE_LOAD_VALID",
    "BLOCK_8_PSYCHOLOGICAL_MATCHES_CHECKPOINT",
    "BLOCK_8_PSYCHOLOGICAL_MATCHES_RUNTIME",
    "BLOCK_8_FROZEN_PARAMETERS_REPRODUCED",
    "BLOCK_8_OPTIMIZER_STATE_EXACT",
    "BLOCK_8_OPTIMIZER_SCOPE_VALID",
    "BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED",
    "BLOCK_8_ALL_FAMILY_OBJECTIVES_REPRODUCED",
    "BLOCK_8_METHOD_BOUNDARY_VALID",
    "BLOCK_8_METADATA_CHECKPOINT_CONSISTENT",
]


missing_block_8_objects = [
    object_name
    for object_name in required_block_8_objects
    if object_name not in globals()
]


if missing_block_8_objects:
    raise NameError(
        "Notebook 05 Block 8 is not initialised. "
        f"Missing: {missing_block_8_objects}"
    )


if not NOTEBOOK_05_BLOCK_4_COMPLETE or not NOTEBOOK_05_BLOCK_4_VALID:
    raise ValueError(
        "Notebook 05 Block 4 must be complete and valid."
    )


if not NOTEBOOK_05_BLOCK_6_COMPLETE or not NOTEBOOK_05_BLOCK_6_VALID:
    raise ValueError(
        "Notebook 05 Block 6 must be complete and valid."
    )


if not NOTEBOOK_05_BLOCK_7_COMPLETE or not NOTEBOOK_05_BLOCK_7_VALID:
    raise ValueError(
        "Notebook 05 Block 7 must be complete and valid."
    )


if not NOTEBOOK_05_BLOCK_8_COMPLETE or not NOTEBOOK_05_BLOCK_8_VALID:
    raise ValueError(
        "Notebook 05 Block 8 must be complete and valid."
    )


# =============================================================================
# Block configuration
# =============================================================================

NOTEBOOK_05_BLOCK_9 = 9

NOTEBOOK_05_BLOCK_9_NAME = (
    "Controlled Diagnostics, Evaluation Readiness and Project Scope Audit"
)

NOTEBOOK_05_BLOCK_9_VERSION = "1.0"

BLOCK_9_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Explicit execution boundary
# =============================================================================

BLOCK_9_BACKWARD_PASS_EXECUTED = False

BLOCK_9_OPTIMIZER_STEP_EXECUTED = False

BLOCK_9_PARAMETER_UPDATE_EXECUTED = False

BLOCK_9_ADDITIONAL_TRAINING_EXECUTED = False

BLOCK_9_CHECKPOINT_SELECTION_EXECUTED = False

BLOCK_9_ABLATION_EXECUTED = False

BLOCK_9_HELD_OUT_EVALUATION_EXECUTED = False

BLOCK_9_SYNTHETIC_SUPERVISION_CREATED = False

BLOCK_9_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Partition audit
# =============================================================================

BLOCK_9_TRAIN_ARTICLE_COUNT = len(
    TRAIN_ARTICLE_IDS
)

BLOCK_9_VALIDATION_ARTICLE_COUNT = len(
    VALIDATION_ARTICLE_IDS
)

BLOCK_9_TEST_ARTICLE_COUNT = len(
    TEST_ARTICLE_IDS
)


BLOCK_9_TRAIN_SENTENCE_COUNT = sum(
    record.get(
        "partition"
    )
    == "train"

    for record
    in SEQUENTIAL_SENTENCE_RECORDS
)


BLOCK_9_VALIDATION_SENTENCE_COUNT = sum(
    record.get(
        "partition"
    )
    == "validation"

    for record
    in SEQUENTIAL_SENTENCE_RECORDS
)


BLOCK_9_TEST_SENTENCE_COUNT = sum(
    record.get(
        "partition"
    )
    == "test"

    for record
    in SEQUENTIAL_SENTENCE_RECORDS
)


BLOCK_9_HELD_OUT_VALIDATION_AVAILABLE = (
    BLOCK_9_VALIDATION_ARTICLE_COUNT > 0
    and BLOCK_9_VALIDATION_SENTENCE_COUNT > 0
)


BLOCK_9_HELD_OUT_TEST_AVAILABLE = (
    BLOCK_9_TEST_ARTICLE_COUNT > 0
    and BLOCK_9_TEST_SENTENCE_COUNT > 0
)


BLOCK_9_ANY_HELD_OUT_ARTICLE_AVAILABLE = bool(
    BLOCK_9_HELD_OUT_VALIDATION_AVAILABLE
    or BLOCK_9_HELD_OUT_TEST_AVAILABLE
)


BLOCK_9_ARTICLE_PARTITION_DISJOINT = all(
    [
        len(
            TRAIN_ARTICLE_IDS
            & VALIDATION_ARTICLE_IDS
        ) == 0,

        len(
            TRAIN_ARTICLE_IDS
            & TEST_ARTICLE_IDS
        ) == 0,

        len(
            VALIDATION_ARTICLE_IDS
            & TEST_ARTICLE_IDS
        ) == 0,
    ]
)


if not BLOCK_9_ARTICLE_PARTITION_DISJOINT:
    raise ValueError(
        "Block 9 detected article overlap across train, validation, "
        "or test partitions."
    )


# =============================================================================
# Evaluation-readiness classification
# =============================================================================

if (
    BLOCK_9_HELD_OUT_VALIDATION_AVAILABLE
    and BLOCK_9_HELD_OUT_TEST_AVAILABLE
):
    BLOCK_9_EVALUATION_READINESS = (
        "held_out_validation_and_test_available"
    )

elif BLOCK_9_HELD_OUT_VALIDATION_AVAILABLE:
    BLOCK_9_EVALUATION_READINESS = (
        "held_out_validation_available"
    )

elif BLOCK_9_HELD_OUT_TEST_AVAILABLE:
    BLOCK_9_EVALUATION_READINESS = (
        "held_out_test_available"
    )

else:
    BLOCK_9_EVALUATION_READINESS = (
        "no_independent_held_out_article"
    )


BLOCK_9_HELD_OUT_METRICS_PERMITTED = (
    BLOCK_9_ANY_HELD_OUT_ARTICLE_AVAILABLE
)


# -----------------------------------------------------------------------------
# Current project state intentionally does not force a held-out metric.
# -----------------------------------------------------------------------------

BLOCK_9_HELD_OUT_METRICS_AVAILABLE = False

BLOCK_9_HELD_OUT_METRICS = None


if BLOCK_9_HELD_OUT_METRICS_PERMITTED:
    BLOCK_9_HELD_OUT_METRICS_AVAILABLE = False


# =============================================================================
# Training diagnostics
# =============================================================================
#
# These remain descriptive computational diagnostics only.
# =============================================================================

BLOCK_9_TRAINING_DIAGNOSTICS_AVAILABLE = True


BLOCK_9_TOTAL_OBJECTIVE_DIAGNOSTIC = {
    "initial":
        float(
            BLOCK_7_INITIAL_LOSS_VALUE
        ),

    "final":
        float(
            BLOCK_7_FINAL_LOSS_VALUE
        ),

    "reduction":
        float(
            BLOCK_7_LOSS_REDUCTION
        ),
}


if BLOCK_7_INITIAL_LOSS_VALUE > 0.0:

    BLOCK_9_OBJECTIVE_REDUCTION_FRACTION = float(
        BLOCK_7_LOSS_REDUCTION
        /
        BLOCK_7_INITIAL_LOSS_VALUE
    )

else:

    BLOCK_9_OBJECTIVE_REDUCTION_FRACTION = None


BLOCK_9_FAMILY_DIAGNOSTICS = {}


for target_name in ACTIVE_SUPERVISED_TARGETS:

    final_loss = float(
        BLOCK_7_FINAL_FAMILY_LOSSES[
            target_name
        ]
        .detach()
        .cpu()
        .item()
    )


    observed_elements = int(
        OBJECTIVE_OBSERVED_ELEMENTS[
            target_name
        ]
    )


    possible_elements = int(
        OBJECTIVE_POSSIBLE_ELEMENTS[
            target_name
        ]
    )


    coverage = float(
        OBJECTIVE_COVERAGE[
            target_name
        ]
    )


    BLOCK_9_FAMILY_DIAGNOSTICS[
        target_name
    ] = {
        "final_training_loss":
            final_loss,

        "observed_elements":
            observed_elements,

        "possible_elements":
            possible_elements,

        "coverage":
            coverage,

        "held_out_metric_available":
            False,
    }


# =============================================================================
# Checkpoint reproducibility diagnostic
# =============================================================================

BLOCK_9_CHECKPOINT_REPRODUCIBILITY_VALID = all(
    [
        BLOCK_8_CHECKPOINT_RELOAD_EXECUTED,
        BLOCK_8_METADATA_RELOAD_EXECUTED,
        BLOCK_8_MODEL_STATE_LOAD_VALID,
        BLOCK_8_PSYCHOLOGICAL_MATCHES_CHECKPOINT,
        BLOCK_8_PSYCHOLOGICAL_MATCHES_RUNTIME,
        BLOCK_8_FROZEN_PARAMETERS_REPRODUCED,
        BLOCK_8_OPTIMIZER_STATE_EXACT,
        BLOCK_8_OPTIMIZER_SCOPE_VALID,
        BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED,
        BLOCK_8_ALL_FAMILY_OBJECTIVES_REPRODUCED,
        BLOCK_8_METHOD_BOUNDARY_VALID,
        BLOCK_8_METADATA_CHECKPOINT_CONSISTENT,
    ]
)


# =============================================================================
# Scope-audit status vocabulary
# =============================================================================

STATUS_YES = True
STATUS_NO = False
STATUS_LIMITED = "limited"
STATUS_NOT_APPLICABLE = "not_applicable"


# =============================================================================
# Planned functionality scope audit
# =============================================================================

BLOCK_9_SCOPE_ROWS = []


def block_9_add_scope_row(
    functionality,
    architecture_stage,
    implemented,
    structurally_validated,
    supervision_available,
    training_eligible,
    trained,
    independently_evaluated,
    empirically_validated,
    notes,
):
    """
    Append one functionality-status record to the project scope audit.
    """

    BLOCK_9_SCOPE_ROWS.append(
        {
            "functionality":
                functionality,

            "architecture_stage":
                architecture_stage,

            "implemented":
                implemented,

            "structurally_validated":
                structurally_validated,

            "supervision_available":
                supervision_available,

            "training_eligible":
                training_eligible,

            "trained":
                trained,

            "independently_evaluated":
                independently_evaluated,

            "empirically_validated":
                empirically_validated,

            "notes":
                notes,
        }
    )


# -----------------------------------------------------------------------------
# Textual representation stage
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "contextual_sentence_representation",

    architecture_stage=
        "textual_representation",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        STATUS_NOT_APPLICABLE,

    training_eligible=
        False,

    trained=
        False,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "Frozen all-mpnet-base-v2 sentence representations are "
        "generated, aligned, persisted and reproducibly available."
    ),
)


# -----------------------------------------------------------------------------
# Global confluent path
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "global_confluent_conditioning",

    architecture_stage=
        "confluent_conditioning",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        STATUS_NOT_APPLICABLE,

    training_eligible=
        False,

    trained=
        False,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "Global confluent path is executable and remained frozen "
        "during controlled psychological-head training."
    ),
)


# -----------------------------------------------------------------------------
# Group-conditioned path
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "group_conditioned_paths",

    architecture_stage=
        "confluent_conditioning",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        False,

    training_eligible=
        False,

    trained=
        False,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "Optional group-conditioned architecture exists, but no validated "
        "group supervision is available and no predicted group is "
        "auto-accepted."
    ),
)


# -----------------------------------------------------------------------------
# Factual head
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "factual_representation_head",

    architecture_stage=
        "representation_heads",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        False,

    training_eligible=
        False,

    trained=
        False,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "Notebook 03 factological annotations have not been automatically "
        "mapped onto the ten-dimensional factual architectural output."
    ),
)


# -----------------------------------------------------------------------------
# Psychological head
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "psychological_representation_head",

    architecture_stage=
        "representation_heads",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        True,

    training_eligible=
        True,

    trained=
        True,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "REV, TEV, IEV and EW were trained under element-level masks. "
        "Training behaviour is reproducible, but no held-out article "
        "is available."
    ),
)


# -----------------------------------------------------------------------------
# Social head
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "structured_social_representation_head",

    architecture_stage=
        "representation_heads",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        False,

    training_eligible=
        False,

    trained=
        False,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "Actors, groups, memberships and relationships remain structured "
        "architectural outputs without validated direct training targets."
    ),
)


# -----------------------------------------------------------------------------
# REV
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "REV",

    architecture_stage=
        "psychological_supervision",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        True,

    training_eligible=
        True,

    trained=
        True,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "REV remains partially observed at the element level and was "
        "trained with explicit Boolean masking."
    ),
)


# -----------------------------------------------------------------------------
# TEV
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "TEV",

    architecture_stage=
        "psychological_supervision",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        True,

    training_eligible=
        True,

    trained=
        True,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "TEV is a psychological supervision family and is not interpreted "
        "as architectural psychological transformation supervision."
    ),
)


# -----------------------------------------------------------------------------
# IEV
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "IEV",

    architecture_stage=
        "psychological_supervision",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        True,

    training_eligible=
        True,

    trained=
        True,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "IEV is directly supervised and trained as an independent "
        "eleven-dimensional psychological target."
    ),
)


# -----------------------------------------------------------------------------
# EW
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "EW",

    architecture_stage=
        "psychological_supervision",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        True,

    training_eligible=
        True,

    trained=
        True,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "EW is directly supervised as a scalar and remains distinct from "
        "psychological Transformative Weight TW_P."
    ),
)


# -----------------------------------------------------------------------------
# Transform mechanisms
# -----------------------------------------------------------------------------

for functionality_name, space_name in (
    (
        "factual_transformation",
        "factual",
    ),
    (
        "psychological_transformation",
        "psychological",
    ),
    (
        "social_transformation",
        "social",
    ),
):

    block_9_add_scope_row(
        functionality=
            functionality_name,

        architecture_stage=
            "transformative_mechanism",

        implemented=
            True,

        structurally_validated=
            True,

        supervision_available=
            False,

        training_eligible=
            False,

        trained=
            False,

        independently_evaluated=
            False,

        empirically_validated=
            False,

        notes=(
            f"{space_name.capitalize()} architectural transformation is "
            "implemented but no validated direct or explicitly activated "
            "indirect training objective is currently available."
        ),
    )


# -----------------------------------------------------------------------------
# Transformative weights
# -----------------------------------------------------------------------------

for tw_name, space_name in (
    (
        "TW_F",
        "factual",
    ),
    (
        "TW_P",
        "psychological",
    ),
    (
        "TW_S",
        "social",
    ),
):

    block_9_add_scope_row(
        functionality=
            tw_name,

        architecture_stage=
            "transformative_mechanism",

        implemented=
            True,

        structurally_validated=
            True,

        supervision_available=
            False,

        training_eligible=
            False,

        trained=
            False,

        independently_evaluated=
            False,

        empirically_validated=
            False,

        notes=(
            f"{tw_name} remains an independent {space_name} "
            "Transformative Weight without validated direct supervision."
        ),
    )


# -----------------------------------------------------------------------------
# Recurrent states
# -----------------------------------------------------------------------------

for recurrent_name, space_name in (
    (
        "H_F",
        "factual",
    ),
    (
        "H_P",
        "psychological",
    ),
    (
        "H_S",
        "social",
    ),
):

    block_9_add_scope_row(
        functionality=
            recurrent_name,

        architecture_stage=
            "recurrent_mechanism",

        implemented=
            True,

        structurally_validated=
            True,

        supervision_available=
            False,

        training_eligible=
            False,

        trained=
            False,

        independently_evaluated=
            False,

        empirically_validated=
            False,

        notes=(
            f"{recurrent_name} is implemented as the {space_name} recurrent "
            "state but has no direct target or activated indirect objective."
        ),
    )


# -----------------------------------------------------------------------------
# Causal sequencing
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "causal_sequential_processing",

    architecture_stage=
        "recurrent_mechanism",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        STATUS_NOT_APPLICABLE,

    training_eligible=
        STATUS_NOT_APPLICABLE,

    trained=
        STATUS_NOT_APPLICABLE,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "Sentence order is preserved, future context is prohibited, and "
        "cross-article recurrence is disabled."
    ),
)


# -----------------------------------------------------------------------------
# Article-boundary reset
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "article_boundary_state_reset",

    architecture_stage=
        "recurrent_mechanism",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        STATUS_NOT_APPLICABLE,

    training_eligible=
        STATUS_NOT_APPLICABLE,

    trained=
        STATUS_NOT_APPLICABLE,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "Independent article boundaries remain explicit and recurrent state "
        "is not carried across unrelated articles."
    ),
)


# -----------------------------------------------------------------------------
# Mask-aware supervision
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "mask_aware_supervision",

    architecture_stage=
        "supervision",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        True,

    training_eligible=
        True,

    trained=
        STATUS_NOT_APPLICABLE,

    independently_evaluated=
        False,

    empirically_validated=
        False,

    notes=(
        "Observed elements enter the objective; missing elements remain "
        "distinct from zero and negative values."
    ),
)


# -----------------------------------------------------------------------------
# Checkpoint persistence and restoration
# -----------------------------------------------------------------------------

block_9_add_scope_row(
    functionality=
        "checkpoint_persistence_and_reload",

    architecture_stage=
        "training_handover",

    implemented=
        True,

    structurally_validated=
        True,

    supervision_available=
        STATUS_NOT_APPLICABLE,

    training_eligible=
        STATUS_NOT_APPLICABLE,

    trained=
        STATUS_NOT_APPLICABLE,

    independently_evaluated=
        True,

    empirically_validated=
        False,

    notes=(
        "Checkpoint, psychological-head state, optimiser state, metadata "
        "and post-training objective were independently reproduced."
    ),
)


# =============================================================================
# Scope dataframe
# =============================================================================

BLOCK_9_SCOPE_AUDIT = pd.DataFrame(
    BLOCK_9_SCOPE_ROWS
)


# =============================================================================
# Scope summary counts
# =============================================================================

BLOCK_9_FUNCTIONALITY_COUNT = len(
    BLOCK_9_SCOPE_AUDIT
)


BLOCK_9_IMPLEMENTED_COUNT = int(
    (
        BLOCK_9_SCOPE_AUDIT[
            "implemented"
        ]
        == True
    ).sum()
)


BLOCK_9_STRUCTURALLY_VALIDATED_COUNT = int(
    (
        BLOCK_9_SCOPE_AUDIT[
            "structurally_validated"
        ]
        == True
    ).sum()
)


BLOCK_9_SUPERVISED_COUNT = int(
    (
        BLOCK_9_SCOPE_AUDIT[
            "supervision_available"
        ]
        == True
    ).sum()
)


BLOCK_9_TRAINED_COUNT = int(
    (
        BLOCK_9_SCOPE_AUDIT[
            "trained"
        ]
        == True
    ).sum()
)


BLOCK_9_INDEPENDENTLY_EVALUATED_COUNT = int(
    (
        BLOCK_9_SCOPE_AUDIT[
            "independently_evaluated"
        ]
        == True
    ).sum()
)


BLOCK_9_EMPIRICALLY_VALIDATED_COUNT = int(
    (
        BLOCK_9_SCOPE_AUDIT[
            "empirically_validated"
        ]
        == True
    ).sum()
)


# =============================================================================
# Version 1.0 scope classification
# =============================================================================

BLOCK_9_ARCHITECTURE_IMPLEMENTATION_COMPLETE = bool(
    BLOCK_9_IMPLEMENTED_COUNT
    == BLOCK_9_FUNCTIONALITY_COUNT
)


BLOCK_9_STRUCTURAL_PIPELINE_COMPLETE = bool(
    BLOCK_9_STRUCTURALLY_VALIDATED_COUNT
    == BLOCK_9_FUNCTIONALITY_COUNT
)


BLOCK_9_CONTROLLED_TRAINING_PIPELINE_COMPLETE = all(
    [
        BLOCK_7_TRAIN_ARTICLE_COUNT > 0,
        BLOCK_7_TRAIN_SENTENCE_COUNT > 0,
        BLOCK_7_TRAINABLE_PARAMETER_CHANGED,
        BLOCK_7_FROZEN_PARAMETERS_UNCHANGED,
        BLOCK_9_CHECKPOINT_REPRODUCIBILITY_VALID,
    ]
)


BLOCK_9_ALL_ARCHITECTURAL_COMPONENTS_TRAINED = bool(
    (
        BLOCK_9_SCOPE_AUDIT[
            "trained"
        ]
        .replace(
            STATUS_NOT_APPLICABLE,
            True,
        )
        == True
    ).all()
)


BLOCK_9_FULL_EMPIRICAL_VALIDATION_COMPLETE = bool(
    BLOCK_9_EMPIRICALLY_VALIDATED_COUNT
    == BLOCK_9_FUNCTIONALITY_COUNT
)


# -----------------------------------------------------------------------------
# Current Version 1.0 completion interpretation
# -----------------------------------------------------------------------------

BLOCK_9_VERSION_1_ARCHITECTURE_COMPLETE = (
    BLOCK_9_ARCHITECTURE_IMPLEMENTATION_COMPLETE
)


BLOCK_9_VERSION_1_CONTROLLED_PIPELINE_COMPLETE = (
    BLOCK_9_CONTROLLED_TRAINING_PIPELINE_COMPLETE
)


BLOCK_9_VERSION_1_GENERALISATION_VALIDATED = False


BLOCK_9_VERSION_1_FULL_TRAINING_COVERAGE = (
    BLOCK_9_ALL_ARCHITECTURAL_COMPONENTS_TRAINED
)


# =============================================================================
# Project closure decision inputs
# =============================================================================

BLOCK_9_CLOSURE_BLOCKERS = []


if not BLOCK_9_ARCHITECTURE_IMPLEMENTATION_COMPLETE:

    BLOCK_9_CLOSURE_BLOCKERS.append(
        "planned_architecture_not_fully_implemented"
    )


if not BLOCK_9_STRUCTURAL_PIPELINE_COMPLETE:

    BLOCK_9_CLOSURE_BLOCKERS.append(
        "planned_architecture_not_fully_structurally_validated"
    )


if not BLOCK_9_CONTROLLED_TRAINING_PIPELINE_COMPLETE:

    BLOCK_9_CLOSURE_BLOCKERS.append(
        "controlled_training_pipeline_incomplete"
    )


# -----------------------------------------------------------------------------
# These are limitations, not blockers for an architecture-complete Version 1.0.
# -----------------------------------------------------------------------------

BLOCK_9_RECORDED_LIMITATIONS = []


if not BLOCK_9_ANY_HELD_OUT_ARTICLE_AVAILABLE:

    BLOCK_9_RECORDED_LIMITATIONS.append(
        "no_independent_validation_or_test_article"
    )


if not BLOCK_9_VERSION_1_FULL_TRAINING_COVERAGE:

    BLOCK_9_RECORDED_LIMITATIONS.append(
        "not_all_architectural_components_have_validated_training_targets"
    )


if not BLOCK_9_VERSION_1_GENERALISATION_VALIDATED:

    BLOCK_9_RECORDED_LIMITATIONS.append(
        "generalisation_not_empirically_validated"
    )


if BLOCK_9_EMPIRICALLY_VALIDATED_COUNT == 0:

    BLOCK_9_RECORDED_LIMITATIONS.append(
        "no_component_has_independent_empirical_validation"
    )


# -----------------------------------------------------------------------------
# Closure interpretation
# -----------------------------------------------------------------------------
#
# Block 9 does not itself declare the project closed.
#
# It determines whether Block 10 has enough evidence to make that decision.
# -----------------------------------------------------------------------------

BLOCK_9_READY_FOR_FINAL_PROJECT_AUDIT = (
    len(
        BLOCK_9_CLOSURE_BLOCKERS
    )
    == 0
)


# =============================================================================
# Methodological consistency checks
# =============================================================================

BLOCK_9_METHOD_CHECKS = {
    "article_partition_disjoint":
        BLOCK_9_ARTICLE_PARTITION_DISJOINT,

    "held_out_training_article_not_reused_as_validation":
        not BLOCK_9_HELD_OUT_EVALUATION_EXECUTED,

    "checkpoint_reproducibility_valid":
        BLOCK_9_CHECKPOINT_REPRODUCIBILITY_VALID,

    "training_diagnostics_not_generalisation":
        True,

    "TEV_not_architectural_transformation_supervision":
        True,

    "EW_not_TW_P_supervision":
        True,

    "factological_annotations_not_auto_mapped_to_factual_head":
        True,

    "unavailable_targets_not_fabricated":
        True,

    "no_new_training":
        not BLOCK_9_ADDITIONAL_TRAINING_EXECUTED,

    "no_backward_pass":
        not BLOCK_9_BACKWARD_PASS_EXECUTED,

    "no_optimizer_step":
        not BLOCK_9_OPTIMIZER_STEP_EXECUTED,

    "no_parameter_update":
        not BLOCK_9_PARAMETER_UPDATE_EXECUTED,

    "no_ablation":
        not BLOCK_9_ABLATION_EXECUTED,

    "no_empirical_validity_claim":
        not BLOCK_9_EMPIRICAL_VALIDITY_ESTABLISHED,
}


BLOCK_9_METHOD_CHECKS_VALID = all(
    BLOCK_9_METHOD_CHECKS.values()
)


# =============================================================================
# Final Block 9 validation
# =============================================================================

NOTEBOOK_05_BLOCK_9_ERRORS = []


if not BLOCK_9_ARTICLE_PARTITION_DISJOINT:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "article_partition_overlap"
    )


if not BLOCK_9_CHECKPOINT_REPRODUCIBILITY_VALID:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "checkpoint_reproducibility_not_valid"
    )


if not BLOCK_9_METHOD_CHECKS_VALID:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "methodological_consistency_invalid"
    )


if BLOCK_9_BACKWARD_PASS_EXECUTED:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "backward_pass_incorrectly_executed"
    )


if BLOCK_9_OPTIMIZER_STEP_EXECUTED:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "optimizer_step_incorrectly_executed"
    )


if BLOCK_9_PARAMETER_UPDATE_EXECUTED:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "parameter_update_incorrectly_executed"
    )


if BLOCK_9_ADDITIONAL_TRAINING_EXECUTED:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "additional_training_incorrectly_executed"
    )


if BLOCK_9_CHECKPOINT_SELECTION_EXECUTED:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "checkpoint_selection_incorrectly_executed"
    )


if BLOCK_9_ABLATION_EXECUTED:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "ablation_incorrectly_executed"
    )


if BLOCK_9_HELD_OUT_EVALUATION_EXECUTED:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "held_out_evaluation_incorrectly_executed"
    )


if BLOCK_9_SYNTHETIC_SUPERVISION_CREATED:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "synthetic_supervision_incorrectly_created"
    )


if BLOCK_9_EMPIRICAL_VALIDITY_ESTABLISHED:

    NOTEBOOK_05_BLOCK_9_ERRORS.append(
        "empirical_validity_incorrectly_asserted"
    )


NOTEBOOK_05_BLOCK_9_VALID = (
    len(
        NOTEBOOK_05_BLOCK_9_ERRORS
    )
    == 0
)


if not NOTEBOOK_05_BLOCK_9_VALID:

    raise RuntimeError(
        "Notebook 05 Block 9 diagnostics and scope audit failed. "
        f"Errors: {NOTEBOOK_05_BLOCK_9_ERRORS}"
    )


# =============================================================================
# Notebook state update
# =============================================================================

NOTEBOOK_05_DIAGNOSTIC_AUDIT_COMPLETE = True

NOTEBOOK_05_SCOPE_AUDIT_COMPLETE = True

NOTEBOOK_05_HELD_OUT_EVALUATION_AVAILABLE = (
    BLOCK_9_ANY_HELD_OUT_ARTICLE_AVAILABLE
)

NOTEBOOK_05_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_05_FULL_EMPIRICAL_VALIDATION = False

NOTEBOOK_05_READY_FOR_FINAL_PROJECT_AUDIT = (
    BLOCK_9_READY_FOR_FINAL_PROJECT_AUDIT
)

NOTEBOOK_05_BLOCK_9_COMPLETE = True


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_05_BLOCK_9_SUMMARY = {
    "block":
        NOTEBOOK_05_BLOCK_9,

    "block_name":
        NOTEBOOK_05_BLOCK_9_NAME,

    "version":
        NOTEBOOK_05_BLOCK_9_VERSION,

    "executed_at_utc":
        BLOCK_9_EXECUTED_AT_UTC,

    "training_articles":
        BLOCK_9_TRAIN_ARTICLE_COUNT,

    "validation_articles":
        BLOCK_9_VALIDATION_ARTICLE_COUNT,

    "test_articles":
        BLOCK_9_TEST_ARTICLE_COUNT,

    "training_sentences":
        BLOCK_9_TRAIN_SENTENCE_COUNT,

    "validation_sentences":
        BLOCK_9_VALIDATION_SENTENCE_COUNT,

    "test_sentences":
        BLOCK_9_TEST_SENTENCE_COUNT,

    "held_out_article_available":
        BLOCK_9_ANY_HELD_OUT_ARTICLE_AVAILABLE,

    "evaluation_readiness":
        BLOCK_9_EVALUATION_READINESS,

    "training_diagnostics_available":
        BLOCK_9_TRAINING_DIAGNOSTICS_AVAILABLE,

    "objective_reduction_fraction":
        BLOCK_9_OBJECTIVE_REDUCTION_FRACTION,

    "checkpoint_reproducibility_valid":
        BLOCK_9_CHECKPOINT_REPRODUCIBILITY_VALID,

    "functionality_count":
        BLOCK_9_FUNCTIONALITY_COUNT,

    "implemented_count":
        BLOCK_9_IMPLEMENTED_COUNT,

    "structurally_validated_count":
        BLOCK_9_STRUCTURALLY_VALIDATED_COUNT,

    "supervised_count":
        BLOCK_9_SUPERVISED_COUNT,

    "trained_count":
        BLOCK_9_TRAINED_COUNT,

    "independently_evaluated_count":
        BLOCK_9_INDEPENDENTLY_EVALUATED_COUNT,

    "empirically_validated_count":
        BLOCK_9_EMPIRICALLY_VALIDATED_COUNT,

    "architecture_complete":
        BLOCK_9_VERSION_1_ARCHITECTURE_COMPLETE,

    "controlled_pipeline_complete":
        BLOCK_9_VERSION_1_CONTROLLED_PIPELINE_COMPLETE,

    "full_training_coverage":
        BLOCK_9_VERSION_1_FULL_TRAINING_COVERAGE,

    "generalisation_validated":
        BLOCK_9_VERSION_1_GENERALISATION_VALIDATED,

    "closure_blockers":
        deepcopy(
            BLOCK_9_CLOSURE_BLOCKERS
        ),

    "recorded_limitations":
        deepcopy(
            BLOCK_9_RECORDED_LIMITATIONS
        ),

    "ready_for_final_project_audit":
        BLOCK_9_READY_FOR_FINAL_PROJECT_AUDIT,

    "block_valid":
        NOTEBOOK_05_BLOCK_9_VALID,

    "block_complete":
        NOTEBOOK_05_BLOCK_9_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 05, Block 9: "
    "Controlled Diagnostics, Evaluation Readiness and Project Scope Audit"
)

print("=" * 72)

print(
    f"Diagnostic version           : "
    f"{NOTEBOOK_05_BLOCK_9_VERSION}"
)


print("-" * 72)

print(
    "Evaluation readiness"
)

print(
    f"Training articles            : "
    f"{BLOCK_9_TRAIN_ARTICLE_COUNT}"
)

print(
    f"Validation articles          : "
    f"{BLOCK_9_VALIDATION_ARTICLE_COUNT}"
)

print(
    f"Test articles                : "
    f"{BLOCK_9_TEST_ARTICLE_COUNT}"
)

print(
    f"Training sentences           : "
    f"{BLOCK_9_TRAIN_SENTENCE_COUNT}"
)

print(
    f"Validation sentences         : "
    f"{BLOCK_9_VALIDATION_SENTENCE_COUNT}"
)

print(
    f"Test sentences               : "
    f"{BLOCK_9_TEST_SENTENCE_COUNT}"
)

print(
    f"Held-out article available   : "
    f"{BLOCK_9_ANY_HELD_OUT_ARTICLE_AVAILABLE}"
)

print(
    f"Evaluation readiness         : "
    f"{BLOCK_9_EVALUATION_READINESS}"
)

print(
    f"Held-out evaluation executed : "
    f"{BLOCK_9_HELD_OUT_EVALUATION_EXECUTED}"
)


print("-" * 72)

print(
    "Controlled training diagnostics"
)

print(
    f"Initial objective            : "
    f"{BLOCK_7_INITIAL_LOSS_VALUE:.8f}"
)

print(
    f"Final objective              : "
    f"{BLOCK_7_FINAL_LOSS_VALUE:.8f}"
)

print(
    f"Objective reduction          : "
    f"{BLOCK_7_LOSS_REDUCTION:.8f}"
)


if BLOCK_9_OBJECTIVE_REDUCTION_FRACTION is not None:

    print(
        f"Objective reduction fraction : "
        f"{BLOCK_9_OBJECTIVE_REDUCTION_FRACTION:.4f}"
    )


for target_name in ACTIVE_SUPERVISED_TARGETS:

    diagnostic = (
        BLOCK_9_FAMILY_DIAGNOSTICS[
            target_name
        ]
    )


    print(
        f"{target_name:<5}"
        f" final training loss         : "
        f"{diagnostic['final_training_loss']:.8f}"
    )

    print(
        f"{target_name:<5}"
        f" supervision coverage        : "
        f"{diagnostic['coverage']:.4f}"
    )


print(
    f"Checkpoint reproducible      : "
    f"{BLOCK_9_CHECKPOINT_REPRODUCIBILITY_VALID}"
)


print("-" * 72)

print(
    "Project scope audit"
)

print(
    f"Planned functionality items  : "
    f"{BLOCK_9_FUNCTIONALITY_COUNT}"
)

print(
    f"Architecturally implemented  : "
    f"{BLOCK_9_IMPLEMENTED_COUNT}"
)

print(
    f"Structurally validated       : "
    f"{BLOCK_9_STRUCTURALLY_VALIDATED_COUNT}"
)

print(
    f"Supported by supervision     : "
    f"{BLOCK_9_SUPERVISED_COUNT}"
)

print(
    f"Actually trained             : "
    f"{BLOCK_9_TRAINED_COUNT}"
)

print(
    f"Independently evaluated      : "
    f"{BLOCK_9_INDEPENDENTLY_EVALUATED_COUNT}"
)

print(
    f"Empirically validated        : "
    f"{BLOCK_9_EMPIRICALLY_VALIDATED_COUNT}"
)


print("-" * 72)

print(
    "Version 1.0 completion state"
)

print(
    f"Architecture complete        : "
    f"{BLOCK_9_VERSION_1_ARCHITECTURE_COMPLETE}"
)

print(
    f"Controlled pipeline complete : "
    f"{BLOCK_9_VERSION_1_CONTROLLED_PIPELINE_COMPLETE}"
)

print(
    f"Full training coverage       : "
    f"{BLOCK_9_VERSION_1_FULL_TRAINING_COVERAGE}"
)

print(
    f"Generalisation validated     : "
    f"{BLOCK_9_VERSION_1_GENERALISATION_VALIDATED}"
)

print(
    f"Closure blockers             : "
    f"{BLOCK_9_CLOSURE_BLOCKERS}"
)

print(
    f"Recorded limitations         : "
    f"{BLOCK_9_RECORDED_LIMITATIONS}"
)

print(
    f"Ready for final project audit: "
    f"{BLOCK_9_READY_FOR_FINAL_PROJECT_AUDIT}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Backward pass executed       : "
    f"{BLOCK_9_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{BLOCK_9_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{BLOCK_9_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Additional training executed : "
    f"{BLOCK_9_ADDITIONAL_TRAINING_EXECUTED}"
)

print(
    f"Checkpoint selection executed: "
    f"{BLOCK_9_CHECKPOINT_SELECTION_EXECUTED}"
)

print(
    f"Ablation executed            : "
    f"{BLOCK_9_ABLATION_EXECUTED}"
)

print(
    f"Empirical validity asserted  : "
    f"{BLOCK_9_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_05_BLOCK_9_VALID}"
)

print(
    f"Block 9 complete             : "
    f"{NOTEBOOK_05_BLOCK_9_COMPLETE}"
)


print("=" * 72)


print(
    "Controlled diagnostics and project scope audit completed successfully."
)

print(
    "The current training article has not been reused as a validation "
    "or test article."
)

print(
    "Training-set objective values are reported only as computational "
    "diagnostics and are not interpreted as evidence of generalisation."
)

print(
    "The complete planned Media AI architecture remains implemented and "
    "structurally validated independently of whether each component has "
    "validated training supervision."
)

print(
    "The psychological head is the only architectural representation head "
    "currently trained from validated direct supervision."
)

print(
    "REV, TEV, IEV and EW remain separate mask-aware psychological "
    "supervision targets."
)

print(
    "TEV remains distinct from architectural psychological transformation, "
    "and EW remains distinct from TW_P."
)

print(
    "Factual, social, architectural transformation, Transformative Weight "
    "and recurrent components remain architecturally implemented but "
    "untrained where validated supervision or an approved indirect "
    "objective is unavailable."
)

print(
    "Checkpoint persistence, independent reload, optimiser recovery and "
    "post-training objective reproduction remain validated."
)

print(
    "The absence of an independent held-out article prevents a "
    "generalisation or empirical-validity claim."
)

print(
    "These limitations are recorded explicitly rather than being treated "
    "as architectural failures."
)

print(
    "Block 9 therefore provides the scope and evidence required for "
    "Block 10 to make the final Notebook 05 and Media AI Version 1.0 "
    "closure decision."
)

print("=" * 72)


# =============================================================================
# Display scope audit
# =============================================================================

display(
    BLOCK_9_SCOPE_AUDIT
)

========================================================================
Media AI — Notebook 05, Block 9: Controlled Diagnostics, Evaluation Readiness and Project Scope Audit
========================================================================
Diagnostic version           : 1.0
------------------------------------------------------------------------
Evaluation readiness
Training articles            : 1
Validation articles          : 0
Test articles                : 0
Training sentences           : 16
Validation sentences         : 0
Test sentences               : 0
Held-out article available   : False
Evaluation readiness         : no_independent_held_out_article
Held-out evaluation executed : False
------------------------------------------------------------------------
Controlled training diagnostics
Initial objective            : 0.10417357
Final objective              : 0.01169837
Objective reduction          : 0.09247520
Objective reduction fraction : 0.8877
REV   final training loss         : 0.00536795
REV   supervision coverage        : 0.2273
TEV   final training loss         : 0.01914624
TEV   supervision coverage        : 1.0000
IEV   final training loss         : 0.01906418
IEV   supervision coverage        : 1.0000
EW    final training loss         : 0.00321512
EW    supervision coverage        : 1.0000
Checkpoint reproducible      : True
------------------------------------------------------------------------
Project scope audit
Planned functionality items  : 23
Architecturally implemented  : 23
Structurally validated       : 23
Supported by supervision     : 6
Actually trained             : 5
Independently evaluated      : 1
Empirically validated        : 0
------------------------------------------------------------------------
Version 1.0 completion state
Architecture complete        : True
Controlled pipeline complete : True
Full training coverage       : False
Generalisation validated     : False
Closure blockers             : []
Recorded limitations         : ['no_independent_validation_or_test_article', 'not_all_architectural_components_have_validated_training_targets', 'generalisation_not_empirically_validated', 'no_component_has_independent_empirical_validation']
Ready for final project audit: True
------------------------------------------------------------------------
Execution boundary
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
Additional training executed : False
Checkpoint selection executed: False
Ablation executed            : False
Empirical validity asserted  : False
Block valid                  : True
Block 9 complete             : True
========================================================================
Controlled diagnostics and project scope audit completed successfully.
The current training article has not been reused as a validation or test article.
Training-set objective values are reported only as computational diagnostics and are not interpreted as evidence of generalisation.
The complete planned Media AI architecture remains implemented and structurally validated independently of whether each component has validated training supervision.
The psychological head is the only architectural representation head currently trained from validated direct supervision.
REV, TEV, IEV and EW remain separate mask-aware psychological supervision targets.
TEV remains distinct from architectural psychological transformation, and EW remains distinct from TW_P.
Factual, social, architectural transformation, Transformative Weight and recurrent components remain architecturally implemented but untrained where validated supervision or an approved indirect objective is unavailable.
Checkpoint persistence, independent reload, optimiser recovery and post-training objective reproduction remain validated.
The absence of an independent held-out article prevents a generalisation or empirical-validity claim.
These limitations are recorded explicitly rather than being treated as architectural failures.
Block 9 therefore provides the scope and evidence required for Block 10 to make the final Notebook 05 and Media AI Version 1.0 closure decision.
========================================================================

/tmp/ipykernel_622/3667906916.py:1345: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(

,functionality,architecture_stage,implemented,structurally_validated,supervision_available,training_eligible,trained,independently_evaluated,empirically_validated,notes
0,contextual_sentence_representation,textual_representation,True,True,not_applicable,False,False,False,False,Frozen all-mpnet-base-v2 sentence representati...
1,global_confluent_conditioning,confluent_conditioning,True,True,not_applicable,False,False,False,False,Global confluent path is executable and remain...
2,group_conditioned_paths,confluent_conditioning,True,True,False,False,False,False,False,Optional group-conditioned architecture exists...
3,factual_representation_head,representation_heads,True,True,False,False,False,False,False,Notebook 03 factological annotations have not ...
4,psychological_representation_head,representation_heads,True,True,True,True,True,False,False,"REV, TEV, IEV and EW were trained under elemen..."
5,structured_social_representation_head,representation_heads,True,True,False,False,False,False,False,"Actors, groups, memberships and relationships ..."
6,REV,psychological_supervision,True,True,True,True,True,False,False,REV remains partially observed at the element ...
7,TEV,psychological_supervision,True,True,True,True,True,False,False,TEV is a psychological supervision family and ...
8,IEV,psychological_supervision,True,True,True,True,True,False,False,IEV is directly supervised and trained as an i...
9,EW,psychological_supervision,True,True,True,True,True,False,False,EW is directly supervised as a scalar and rema...
10,factual_transformation,transformative_mechanism,True,True,False,False,False,False,False,Factual architectural transformation is implem...
11,psychological_transformation,transformative_mechanism,True,True,False,False,False,False,False,Psychological architectural transformation is ...
12,social_transformation,transformative_mechanism,True,True,False,False,False,False,False,Social architectural transformation is impleme...
13,TW_F,transformative_mechanism,True,True,False,False,False,False,False,TW_F remains an independent factual Transforma...
14,TW_P,transformative_mechanism,True,True,False,False,False,False,False,TW_P remains an independent psychological Tran...
15,TW_S,transformative_mechanism,True,True,False,False,False,False,False,TW_S remains an independent social Transformat...
16,H_F,recurrent_mechanism,True,True,False,False,False,False,False,H_F is implemented as the factual recurrent st...
17,H_P,recurrent_mechanism,True,True,False,False,False,False,False,H_P is implemented as the psychological recurr...
18,H_S,recurrent_mechanism,True,True,False,False,False,False,False,H_S is implemented as the social recurrent sta...
19,causal_sequential_processing,recurrent_mechanism,True,True,not_applicable,not_applicable,not_applicable,False,False,"Sentence order is preserved, future context is..."
20,article_boundary_state_reset,recurrent_mechanism,True,True,not_applicable,not_applicable,not_applicable,False,False,Independent article boundaries remain explicit...
21,mask_aware_supervision,supervision,True,True,True,True,not_applicable,False,False,Observed elements enter the objective; missing...
22,checkpoint_persistence_and_reload,training_handover,True,True,not_applicable,not_applicable,not_applicable,True,False,"Checkpoint, psychological-head state, optimise..."

## Block 10 — Notebook 05 Completion, Persistent Handover and Remaining-Path Readiness

This block completes Notebook 05 by auditing the final psychological-path state, preserving the validated training and reproducibility artefacts, and constructing a persistent handover contract for the remaining Media AI Version 1 development sequence.

Notebook 05 is not interpreted as completion of the entire Media AI project. It establishes a complete and reproducible controlled training workflow for the currently supervised psychological path while preserving the remaining architectural components for subsequent notebooks.

The block first verifies the final Notebook 05 execution state established by the preceding blocks. The contextual sentence representations must remain available and aligned with the canonical sentence identities. The psychological representation head must remain the only trained Media AI architectural representation head. `REV`, `TEV`, `IEV`, and `EW` must remain the only activated direct supervision families.

The persisted controlled training checkpoint from Block 7 and its independent restoration established by Block 8 must remain valid. The restored psychological-head parameters, optimiser state, objective values, encoder identity, objective weights, and methodological boundaries must remain reproducible. The checkpoint continues to be classified as a controlled experimental checkpoint rather than an empirically validated model checkpoint.

The Block 9 scope audit is incorporated into the Notebook 05 completion decision. The Media AI architecture is considered implemented and structurally validated, but implementation, training, independent evaluation, and empirical validation remain separate states. The absence of independent validation or test articles continues to prevent claims of generalisation or empirical validity.

Notebook 05 therefore closes with the following methodological state:

- the contextual sentence representation stage is implemented, validated, persisted, and frozen;
- the mandatory global confluent-conditioning path is implemented, structurally validated, and frozen;
- the optional group-conditioned paths are implemented and structurally validated but remain inactive and untrained;
- the psychological representation head is implemented, trained under validated mask-aware supervision, checkpointed, and reproducibly restored;
- `REV`, `TEV`, `IEV`, and `EW` remain independently defined psychological supervision families;
- the factual representation head remains implemented and structurally validated but untrained;
- the structured social representation head remains implemented and structurally validated but untrained;
- factual, psychological, and social architectural transformation mechanisms remain implemented and structurally validated but untrained;
- `TW_F`, `TW_P`, and `TW_S` remain independent Transformative Weights without validated training supervision;
- `H_F`, `H_P`, and `H_S` remain separate recurrent states without direct supervision or an activated indirect training objective;
- causal sentence ordering, prohibition of future context, and article-boundary recurrent-state reset remain preserved;
- unavailable supervision remains distinct from numerical zero and negative evidence.

The block then constructs the persistent Notebook 05 handover for the remaining Version 1 development sequence.

### Remaining Media AI Version 1 notebook sequence

The remaining development order is explicitly preserved as part of the handover contract:

- **Notebook 06 — Factual Path**
- **Notebook 07 — Social Path**
- **Notebook 08 — Transformative Mechanism**
- **Notebook 09 — Transformative Weights and Recurrent Mechanism**
- **Notebook 10 — Group-Conditioned Path and Final Integration**

Each subsequent notebook must preserve the validated outputs and methodological boundaries of preceding notebooks rather than implicitly retraining, replacing, or redefining already completed components.

The mandatory global path remains the stable conditioning path throughout Notebooks 06–09.

The group-conditioned path is deliberately deferred to Notebook 10 for Media AI Version 1. This does not alter its architectural position or replace it with the global path. The architecture continues to require the global path and permit group-conditioned paths as optional additional conditioning.

The deferral reflects the current empirical boundary. The available supervised dataset contains only one article and sixteen canonical sentence records, which is insufficient to justify extensive or stable data-driven grouping. Notebook 05 therefore does not fabricate concrete groups, infer group membership as ground truth, or introduce grouping merely to activate the optional architectural path.

Notebook 10 may activate group-conditioned processing only where a defensible group contract can be established. The core Version 1 model must remain operational through the mandatory global path when group information is unavailable. Group conditioning must remain additive and must not replace the global representation path.

### Notebook 06 factual-path handover

Notebook 06 is the immediate successor to Notebook 05 and is designated to address the factual path.

It must not automatically activate the factual representation head merely because Notebook 03 contains factological annotations. Instead, Notebook 06 must begin by establishing a defensible factual supervision contract.

The handover therefore preserves the distinction between the ten-dimensional factual architectural representation and the currently available Notebook 03 factological annotation structure.

Notebook 03 currently provides eight explicit factological components:

- `explicit_claim`;
- `observation_or_event`;
- `quantitative_information`;
- `attribution`;
- `evidence_reference`;
- `certainty_statement`;
- `uncertainty_statement`;
- `speculation_or_prediction`.

The architectural factual representation remains ten-dimensional. No additional dimensions are invented or inferred by Notebook 05 merely to reconcile the eight available factological components with the ten-dimensional architecture.

`factological_weight` is preserved as an available Notebook 03 annotation field but is not automatically assigned to one of the ten factual architectural dimensions. Any use of this field in Notebook 06 requires an explicit semantic and supervision decision.

The first substantive task of Notebook 06 must therefore be a factual supervision mapping and target-contract audit. It must determine whether the existing Notebook 03 annotations can defensibly supervise all or part of the ten-dimensional factual representation and define the semantics, target types, masks, numerical domains, and loss treatment of every activated factual dimension.

Partial factual supervision is permitted if methodologically justified. Notebook 06 must not fabricate supervision for unresolved factual dimensions and must not require all ten dimensions to become active merely because the architectural factual head is ten-dimensional.

### Persistent handover contract

The Notebook 05 handover must preserve at least:

- the Notebook 05 version and completion state;
- the validated Notebook 04 architecture contract;
- the remaining Notebook 06–10 development sequence;
- the canonical sentence identity and article-boundary contracts;
- the persisted contextual representation artefact and its Drive file identity;
- the contextual encoder identity and expected 768-dimensional representation interface;
- the controlled psychological training checkpoint and metadata identities;
- the psychological target order and dimensionality;
- the trained psychological-head state and parameter policy;
- the requirement that the completed psychological head remain frozen by default in subsequent path-specific notebooks;
- the Notebook 03 accepted canonical supervision source;
- the factual architectural dimension count of ten;
- the Notebook 03 factological component count of eight;
- the explicit names of those eight factological components;
- the availability but unresolved architectural role of `factological_weight`;
- the unresolved factual supervision mapping;
- the requirement that Notebook 06 resolve that mapping before factual optimisation is activated;
- the structured and variable-dimensional nature of the future social path;
- the separation of `TEV` from architectural psychological transformation;
- the separation of `EW` from `TW_P`;
- the independence of `TW_F`, `TW_P`, and `TW_S`;
- the independence of `H_F`, `H_P`, and `H_S`;
- the existing mask-aware missing-supervision semantics;
- the causal sequential-processing contract;
- the prohibition of future-context access;
- the article-boundary recurrent-state reset requirement;
- the prohibition of unsupported empirical-validity claims;
- the requirement that the mandatory global path remain available regardless of future group-conditioned processing.

Notebook 06 should be able to initialise in an independent Colab runtime from persisted artefacts without requiring Notebook 05 to be rerun.

The psychological checkpoint produced by Notebook 05 is preserved for subsequent integration, but Notebook 06 must not continue psychological training by default. The trained psychological head should remain frozen unless a later notebook explicitly establishes a justified reason to modify it.

Likewise, the social head, architectural transformation mechanisms, Transformative Weights, recurrent mechanisms, and group-conditioned paths remain outside the initial Notebook 06 optimisation scope.

Notebook 07 will subsequently address the structured social path while preserving the completed psychological and factual paths.

Notebook 08 will address the factual, psychological, and social architectural transformation mechanisms. `TEV` must continue to remain distinct from architectural psychological transformation and must not be used as transformation supervision without an independently justified mapping or objective.

Notebook 09 will address the three independent space-specific Transformative Weights `TW_F`, `TW_P`, and `TW_S` and the three separate recurrent states `H_F`, `H_P`, and `H_S`. Causal processing, sentence order, article-boundary reset, and prohibition of cross-article recurrent-state carry remain mandatory.

Notebook 10 will address the optional group-conditioned path after the core factual, psychological, social, transformative, and recurrent mechanisms have been established. It will then perform final architectural integration and the project-level Version 1 completion audit.

The Notebook 10 grouping stage must remain proportionate to the available evidence. If sufficient validated grouping evidence is still unavailable, Version 1 may retain the group-conditioned mechanism as an implemented and structurally validated optional capability without fabricating group supervision or claiming empirical group validation.

No new training, backward pass, optimiser step, parameter update, checkpoint selection, ablation, held-out evaluation, synthetic supervision, factual-target inference, social-target inference, transformation-target inference, recurrent-target inference, or group construction is performed by Block 10.

Successful completion of Block 10 establishes that Notebook 05 is complete as the controlled psychological-path training, reproducibility, and audit notebook.

It does not establish completion of the full Media AI project, full training coverage of all architectural components, model generalisation, or full empirical validation.

The resulting persistent handover provides Notebook 06 with the validated architectural, representation, supervision, checkpoint, roadmap, and methodological state required to begin the factual supervision mapping and factual-path development without rerunning Notebook 05.

In [ ]:
# =============================================================================
# Media AI — Notebook 05
# Block 10: Notebook 05 Completion, Persistent Handover
#           and Remaining-Path Readiness
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json
import math
import os

import numpy as np
import torch

from googleapiclient.http import (
    MediaIoBaseDownload,
    MediaIoBaseUpload,
)


# =============================================================================
# Block dependency checks
# =============================================================================

required_block_1_objects = [
    "NOTEBOOK_05_BLOCK_1_COMPLETE",
    "NOTEBOOK_05_HANDOVER_VALID",
    "NOTEBOOK_05_HANDOVER",
    "DRIVE_SERVICE_FOR_HANDOVER",
    "NOTEBOOK_05_DRIVE_SERVICE_INITIALISED",
    "NOTEBOOK_05_HANDOVER_DRIVE_FILE_ID",
]


missing_block_1_objects = [
    object_name
    for object_name in required_block_1_objects
    if object_name not in globals()
]


if missing_block_1_objects:

    raise NameError(
        "Notebook 05 Block 1 is not initialised. "
        f"Missing: {missing_block_1_objects}"
    )


required_block_2_objects = [
    "NOTEBOOK_05_BLOCK_2_COMPLETE",
    "NOTEBOOK_05_BLOCK_2_VALID",
    "NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS",
]


missing_block_2_objects = [
    object_name
    for object_name in required_block_2_objects
    if object_name not in globals()
]


if missing_block_2_objects:

    raise NameError(
        "Notebook 05 Block 2 is not initialised. "
        f"Missing: {missing_block_2_objects}"
    )


required_block_3_objects = [
    "NOTEBOOK_05_BLOCK_3_COMPLETE",
    "NOTEBOOK_05_BLOCK_3_VALID",
    "MEDIA_AI_MODEL",
    "BACKBONE_HIDDEN_DIM",
    "CONFLUENT_HIDDEN_DIM",
]


missing_block_3_objects = [
    object_name
    for object_name in required_block_3_objects
    if object_name not in globals()
]


if missing_block_3_objects:

    raise NameError(
        "Notebook 05 Block 3 is not initialised. "
        f"Missing: {missing_block_3_objects}"
    )


required_block_4_objects = [
    "NOTEBOOK_05_BLOCK_4_COMPLETE",
    "NOTEBOOK_05_BLOCK_4_VALID",
    "SEQUENTIAL_SENTENCE_RECORDS",
    "DATASET_SENTENCE_COUNT",
    "DATASET_ARTICLE_COUNT",
]


missing_block_4_objects = [
    object_name
    for object_name in required_block_4_objects
    if object_name not in globals()
]


if missing_block_4_objects:

    raise NameError(
        "Notebook 05 Block 4 is not initialised. "
        f"Missing: {missing_block_4_objects}"
    )


required_block_5_objects = [
    "NOTEBOOK_05_BLOCK_5_COMPLETE",
    "NOTEBOOK_05_BLOCK_5_VALID",
    "CONTEXTUAL_ENCODER_PROVIDER",
    "CONTEXTUAL_ENCODER_MODEL_ID",
    "CONTEXTUAL_ENCODER_EXPECTED_DIM",
    "NOTEBOOK_05_REPRESENTATION_DRIVE_FILE_ID",
    "NOTEBOOK_05_REPRESENTATION_FILENAME",
]


missing_block_5_objects = [
    object_name
    for object_name in required_block_5_objects
    if object_name not in globals()
]


if missing_block_5_objects:

    raise NameError(
        "Notebook 05 Block 5 is not initialised. "
        f"Missing: {missing_block_5_objects}"
    )


required_block_6_objects = [
    "NOTEBOOK_05_BLOCK_6_COMPLETE",
    "NOTEBOOK_05_BLOCK_6_VALID",
    "ACTIVE_SUPERVISED_TARGETS",
    "OBJECTIVE_WEIGHTS",
]


missing_block_6_objects = [
    object_name
    for object_name in required_block_6_objects
    if object_name not in globals()
]


if missing_block_6_objects:

    raise NameError(
        "Notebook 05 Block 6 is not initialised. "
        f"Missing: {missing_block_6_objects}"
    )


required_block_7_objects = [
    "NOTEBOOK_05_BLOCK_7_COMPLETE",
    "NOTEBOOK_05_BLOCK_7_VALID",
    "BLOCK_7_CHECKPOINT_TYPE",
    "BLOCK_7_CHECKPOINT_FILENAME",
    "BLOCK_7_CHECKPOINT_DRIVE_FILE_ID",
    "BLOCK_7_CHECKPOINT_METADATA_FILENAME",
    "BLOCK_7_METADATA_DRIVE_FILE_ID",
    "BLOCK_7_FINAL_LOSS_VALUE",
]


missing_block_7_objects = [
    object_name
    for object_name in required_block_7_objects
    if object_name not in globals()
]


if missing_block_7_objects:

    raise NameError(
        "Notebook 05 Block 7 is not initialised. "
        f"Missing: {missing_block_7_objects}"
    )


required_block_8_objects = [
    "NOTEBOOK_05_BLOCK_8_COMPLETE",
    "NOTEBOOK_05_BLOCK_8_VALID",
    "BLOCK_8_CHECKPOINT_RELOAD_EXECUTED",
    "BLOCK_8_OPTIMIZER_STATE_EXACT",
    "BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED",
    "BLOCK_8_ALL_FAMILY_OBJECTIVES_REPRODUCED",
    "BLOCK_8_METHOD_BOUNDARY_VALID",
    "BLOCK_8_METADATA_CHECKPOINT_CONSISTENT",
]


missing_block_8_objects = [
    object_name
    for object_name in required_block_8_objects
    if object_name not in globals()
]


if missing_block_8_objects:

    raise NameError(
        "Notebook 05 Block 8 is not initialised. "
        f"Missing: {missing_block_8_objects}"
    )


required_block_9_objects = [
    "NOTEBOOK_05_BLOCK_9_COMPLETE",
    "NOTEBOOK_05_BLOCK_9_VALID",
    "BLOCK_9_SCOPE_AUDIT",
    "BLOCK_9_VERSION_1_ARCHITECTURE_COMPLETE",
    "BLOCK_9_VERSION_1_CONTROLLED_PIPELINE_COMPLETE",
    "BLOCK_9_VERSION_1_FULL_TRAINING_COVERAGE",
    "BLOCK_9_VERSION_1_GENERALISATION_VALIDATED",
    "BLOCK_9_CLOSURE_BLOCKERS",
    "BLOCK_9_RECORDED_LIMITATIONS",
    "BLOCK_9_READY_FOR_FINAL_PROJECT_AUDIT",
]


missing_block_9_objects = [
    object_name
    for object_name in required_block_9_objects
    if object_name not in globals()
]


if missing_block_9_objects:

    raise NameError(
        "Notebook 05 Block 9 is not initialised. "
        f"Missing: {missing_block_9_objects}"
    )


# -----------------------------------------------------------------------------
# Completion validation
# -----------------------------------------------------------------------------

required_complete_flags = {
    "Block 1":
        NOTEBOOK_05_BLOCK_1_COMPLETE,

    "Block 2":
        NOTEBOOK_05_BLOCK_2_COMPLETE,

    "Block 3":
        NOTEBOOK_05_BLOCK_3_COMPLETE,

    "Block 4":
        NOTEBOOK_05_BLOCK_4_COMPLETE,

    "Block 5":
        NOTEBOOK_05_BLOCK_5_COMPLETE,

    "Block 6":
        NOTEBOOK_05_BLOCK_6_COMPLETE,

    "Block 7":
        NOTEBOOK_05_BLOCK_7_COMPLETE,

    "Block 8":
        NOTEBOOK_05_BLOCK_8_COMPLETE,

    "Block 9":
        NOTEBOOK_05_BLOCK_9_COMPLETE,
}


incomplete_blocks = [
    block_name
    for block_name, block_complete
    in required_complete_flags.items()
    if not block_complete
]


if incomplete_blocks:

    raise ValueError(
        "Notebook 05 cannot complete because preceding blocks "
        f"are incomplete: {incomplete_blocks}"
    )


required_valid_flags = {
    "Block 2":
        NOTEBOOK_05_BLOCK_2_VALID,

    "Block 3":
        NOTEBOOK_05_BLOCK_3_VALID,

    "Block 4":
        NOTEBOOK_05_BLOCK_4_VALID,

    "Block 5":
        NOTEBOOK_05_BLOCK_5_VALID,

    "Block 6":
        NOTEBOOK_05_BLOCK_6_VALID,

    "Block 7":
        NOTEBOOK_05_BLOCK_7_VALID,

    "Block 8":
        NOTEBOOK_05_BLOCK_8_VALID,

    "Block 9":
        NOTEBOOK_05_BLOCK_9_VALID,
}


invalid_blocks = [
    block_name
    for block_name, block_valid
    in required_valid_flags.items()
    if not block_valid
]


if invalid_blocks:

    raise ValueError(
        "Notebook 05 cannot complete because preceding blocks "
        f"are invalid: {invalid_blocks}"
    )


# =============================================================================
# Block configuration
# =============================================================================

NOTEBOOK_05_BLOCK_10 = 10

NOTEBOOK_05_BLOCK_10_NAME = (
    "Notebook 05 Completion, Persistent Handover "
    "and Remaining-Path Readiness"
)

NOTEBOOK_05_BLOCK_10_VERSION = "1.0"

NOTEBOOK_05_TO_06_HANDOVER_VERSION = "1.0"

NOTEBOOK_05_TO_06_HANDOVER_FILENAME = (
    "notebook_05_to_06_handover.json"
)


BLOCK_10_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Explicit execution boundary
# =============================================================================

BLOCK_10_BACKWARD_PASS_EXECUTED = False

BLOCK_10_OPTIMIZER_STEP_EXECUTED = False

BLOCK_10_PARAMETER_UPDATE_EXECUTED = False

BLOCK_10_TRAINING_EXECUTED = False

BLOCK_10_CHECKPOINT_SELECTION_EXECUTED = False

BLOCK_10_ABLATION_EXECUTED = False

BLOCK_10_HELD_OUT_EVALUATION_EXECUTED = False

BLOCK_10_SYNTHETIC_SUPERVISION_CREATED = False

BLOCK_10_FACTUAL_TARGET_MAPPING_PERFORMED = False

BLOCK_10_SOCIAL_TARGET_MAPPING_PERFORMED = False

BLOCK_10_TRANSFORMATION_TARGET_MAPPING_PERFORMED = False

BLOCK_10_RECURRENT_TARGET_MAPPING_PERFORMED = False

BLOCK_10_GROUP_CONSTRUCTION_PERFORMED = False

BLOCK_10_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Remaining Version 1 roadmap
# =============================================================================

MEDIA_AI_VERSION_1_REMAINING_NOTEBOOK_SEQUENCE = [
    {
        "notebook":
            "06",

        "name":
            "Factual Path",

        "primary_scope":
            (
                "Factual supervision mapping, target-contract definition, "
                "factual-head training, checkpointing and reproducibility."
            ),
    },

    {
        "notebook":
            "07",

        "name":
            "Social Path",

        "primary_scope":
            (
                "Structured actor, group, membership and relationship "
                "representation, supervision contract, training and "
                "reproducibility."
            ),
    },

    {
        "notebook":
            "08",

        "name":
            "Transformative Mechanism",

        "primary_scope":
            (
                "Factual, psychological and social architectural "
                "transformation mechanisms."
            ),
    },

    {
        "notebook":
            "09",

        "name":
            "Transformative Weights and Recurrent Mechanism",

        "primary_scope":
            (
                "Independent TW_F, TW_P and TW_S together with "
                "independent H_F, H_P and H_S recurrent states."
            ),
    },

    {
        "notebook":
            "10",

        "name":
            "Group-Conditioned Path and Final Integration",

        "primary_scope":
            (
                "Optional group-conditioned processing, final integration "
                "and Media AI Version 1 project-level completion audit."
            ),
    },
]


BLOCK_10_ROADMAP_VALID = (
    [
        notebook_record[
            "notebook"
        ]
        for notebook_record
        in MEDIA_AI_VERSION_1_REMAINING_NOTEBOOK_SEQUENCE
    ]
    ==
    [
        "06",
        "07",
        "08",
        "09",
        "10",
    ]
)


if not BLOCK_10_ROADMAP_VALID:

    raise ValueError(
        "Notebook 05 remaining Version 1 roadmap is invalid."
    )


# =============================================================================
# Notebook 05 final state
# =============================================================================

BLOCK_10_PSYCHOLOGICAL_TARGET_ORDER = (
    "REV",
    "TEV",
    "IEV",
    "EW",
)


BLOCK_10_PSYCHOLOGICAL_VECTOR_DIMENSIONS = {
    "REV":
        11,

    "TEV":
        11,

    "IEV":
        11,

    "EW":
        1,
}


BLOCK_10_ACTIVE_TARGET_CONTRACT_VALID = (
    tuple(
        ACTIVE_SUPERVISED_TARGETS
    )
    ==
    BLOCK_10_PSYCHOLOGICAL_TARGET_ORDER
)


if not BLOCK_10_ACTIVE_TARGET_CONTRACT_VALID:

    raise ValueError(
        "Notebook 05 active psychological supervision contract "
        "does not match REV, TEV, IEV, EW."
    )


BLOCK_10_PSYCHOLOGICAL_HEAD_TRAINED = True

BLOCK_10_FACTUAL_HEAD_TRAINED = False

BLOCK_10_SOCIAL_HEAD_TRAINED = False

BLOCK_10_TRANSFORMATIVE_MECHANISMS_TRAINED = False

BLOCK_10_TRANSFORMATIVE_WEIGHTS_TRAINED = False

BLOCK_10_RECURRENT_MECHANISMS_TRAINED = False

BLOCK_10_GROUP_CONDITIONED_PATH_TRAINED = False


# =============================================================================
# Checkpoint and reproducibility boundary
# =============================================================================

BLOCK_10_CHECKPOINT_REPRODUCIBILITY_VALID = all(
    [
        BLOCK_8_CHECKPOINT_RELOAD_EXECUTED,
        BLOCK_8_OPTIMIZER_STATE_EXACT,
        BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED,
        BLOCK_8_ALL_FAMILY_OBJECTIVES_REPRODUCED,
        BLOCK_8_METHOD_BOUNDARY_VALID,
        BLOCK_8_METADATA_CHECKPOINT_CONSISTENT,
    ]
)


if not BLOCK_10_CHECKPOINT_REPRODUCIBILITY_VALID:

    raise ValueError(
        "Notebook 05 psychological checkpoint is not reproducibly valid."
    )


BLOCK_10_CHECKPOINT_TYPE_VALID = (
    BLOCK_7_CHECKPOINT_TYPE
    ==
    "controlled_experimental_training_checkpoint"
)


if not BLOCK_10_CHECKPOINT_TYPE_VALID:

    raise ValueError(
        "Notebook 05 checkpoint classification is invalid."
    )


# =============================================================================
# Contextual representation contract
# =============================================================================

BLOCK_10_REPRESENTATION_DIMENSION = int(
    CONTEXTUAL_ENCODER_EXPECTED_DIM
)


BLOCK_10_REPRESENTATION_CONTRACT_VALID = all(
    [
        BLOCK_10_REPRESENTATION_DIMENSION
        == 768,

        BACKBONE_HIDDEN_DIM
        == 768,

        bool(
            NOTEBOOK_05_REPRESENTATION_DRIVE_FILE_ID
        ),
    ]
)


if not BLOCK_10_REPRESENTATION_CONTRACT_VALID:

    raise ValueError(
        "Notebook 05 contextual representation handover contract "
        "is invalid."
    )


# =============================================================================
# Canonical sentence identity contract
# =============================================================================

BLOCK_10_SENTENCE_IDS = [
    record[
        "sentence_id"
    ]

    for record
    in SEQUENTIAL_SENTENCE_RECORDS
]


BLOCK_10_ARTICLE_IDS = list(
    dict.fromkeys(
        record[
            "article_id"
        ]

        for record
        in SEQUENTIAL_SENTENCE_RECORDS
    )
)


BLOCK_10_SENTENCE_IDS_PRESENT = (
    bool(
        BLOCK_10_SENTENCE_IDS
    )
    and all(
        BLOCK_10_SENTENCE_IDS
    )
)


BLOCK_10_SENTENCE_IDS_UNIQUE = (
    len(
        BLOCK_10_SENTENCE_IDS
    )
    ==
    len(
        set(
            BLOCK_10_SENTENCE_IDS
        )
    )
)


BLOCK_10_SENTENCE_COUNT_VALID = (
    len(
        BLOCK_10_SENTENCE_IDS
    )
    ==
    DATASET_SENTENCE_COUNT
)


BLOCK_10_ARTICLE_COUNT_VALID = (
    len(
        BLOCK_10_ARTICLE_IDS
    )
    ==
    DATASET_ARTICLE_COUNT
)


BLOCK_10_IDENTITY_CONTRACT_VALID = all(
    [
        BLOCK_10_SENTENCE_IDS_PRESENT,
        BLOCK_10_SENTENCE_IDS_UNIQUE,
        BLOCK_10_SENTENCE_COUNT_VALID,
        BLOCK_10_ARTICLE_COUNT_VALID,
    ]
)


if not BLOCK_10_IDENTITY_CONTRACT_VALID:

    raise ValueError(
        "Notebook 05 canonical identity handover contract is invalid."
    )


# =============================================================================
# Notebook 03 factual supervision contract
# =============================================================================

NOTEBOOK_06_FACTOLOGICAL_COMPONENTS = (
    "explicit_claim",
    "observation_or_event",
    "quantitative_information",
    "attribution",
    "evidence_reference",
    "certainty_statement",
    "uncertainty_statement",
    "speculation_or_prediction",
)


NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT = len(
    NOTEBOOK_06_FACTOLOGICAL_COMPONENTS
)


NOTEBOOK_06_EXPECTED_FACTUAL_ARCHITECTURAL_DIMENSION = 10


if NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT != 8:

    raise ValueError(
        "Notebook 06 factological component contract must contain "
        "exactly eight explicit components."
    )


# -----------------------------------------------------------------------------
# Validate factual annotation structure against persisted Notebook 03 records
# -----------------------------------------------------------------------------

if not NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS:

    raise ValueError(
        "Notebook 03 accepted supervision records are unavailable."
    )


BLOCK_10_NOTEBOOK_03_ACCEPTED_RECORD_COUNT = len(
    NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS
)


BLOCK_10_FACTOLOGICAL_SCHEMA_MISMATCHES = []


for record_index, record in enumerate(
    NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS
):

    annotations = record.get(
        "annotations",
        {}
    )


    factological_components = annotations.get(
        "factological_components"
    )


    if not isinstance(
        factological_components,
        dict,
    ):

        BLOCK_10_FACTOLOGICAL_SCHEMA_MISMATCHES.append(
            {
                "record_index":
                    record_index,

                "reason":
                    "factological_components_missing_or_invalid",
            }
        )

        continue


    component_names = tuple(
        factological_components.keys()
    )


    if set(
        component_names
    ) != set(
        NOTEBOOK_06_FACTOLOGICAL_COMPONENTS
    ):

        BLOCK_10_FACTOLOGICAL_SCHEMA_MISMATCHES.append(
            {
                "record_index":
                    record_index,

                "reason":
                    "factological_component_names_mismatch",

                "found":
                    sorted(
                        component_names
                    ),
            }
        )


BLOCK_10_FACTOLOGICAL_COMPONENT_SCHEMA_VALID = (
    len(
        BLOCK_10_FACTOLOGICAL_SCHEMA_MISMATCHES
    )
    == 0
)


if not BLOCK_10_FACTOLOGICAL_COMPONENT_SCHEMA_VALID:

    raise ValueError(
        "Notebook 03 factological component contract does not match "
        "the expected eight-component Notebook 06 starting schema. "
        f"Diagnostics: {BLOCK_10_FACTOLOGICAL_SCHEMA_MISMATCHES}"
    )


# -----------------------------------------------------------------------------
# Factological weight availability
# -----------------------------------------------------------------------------

BLOCK_10_FACTOLOGICAL_WEIGHT_RECORDS = 0


for record in NOTEBOOK_03_ACCEPTED_SUPERVISION_RECORDS:

    annotations = record.get(
        "annotations",
        {}
    )


    factological_weight = annotations.get(
        "factological_weight"
    )


    if isinstance(
        factological_weight,
        dict,
    ):

        if (
            factological_weight.get(
                "value"
            )
            is not None
        ):

            BLOCK_10_FACTOLOGICAL_WEIGHT_RECORDS += 1


BLOCK_10_FACTOLOGICAL_WEIGHT_AVAILABLE = (
    BLOCK_10_FACTOLOGICAL_WEIGHT_RECORDS > 0
)


# -----------------------------------------------------------------------------
# Factual supervision mapping deliberately unresolved
# -----------------------------------------------------------------------------

NOTEBOOK_06_FACTUAL_SUPERVISION_MAPPING_RESOLVED = False

NOTEBOOK_06_FACTUAL_SUPERVISION_MAPPING_REQUIRED = True

NOTEBOOK_06_PARTIAL_FACTUAL_SUPERVISION_ALLOWED = True

NOTEBOOK_06_UNRESOLVED_DIMENSIONS_MAY_BE_FABRICATED = False

NOTEBOOK_06_FACTOLOGICAL_WEIGHT_AUTO_MAPPED = False


BLOCK_10_FACTUAL_MAPPING_BOUNDARY_VALID = all(
    [
        NOTEBOOK_06_EXPECTED_FACTUAL_ARCHITECTURAL_DIMENSION
        == 10,

        NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT
        == 8,

        NOTEBOOK_06_FACTUAL_SUPERVISION_MAPPING_RESOLVED
        is False,

        NOTEBOOK_06_FACTUAL_SUPERVISION_MAPPING_REQUIRED
        is True,

        NOTEBOOK_06_PARTIAL_FACTUAL_SUPERVISION_ALLOWED
        is True,

        NOTEBOOK_06_UNRESOLVED_DIMENSIONS_MAY_BE_FABRICATED
        is False,

        NOTEBOOK_06_FACTOLOGICAL_WEIGHT_AUTO_MAPPED
        is False,
    ]
)


if not BLOCK_10_FACTUAL_MAPPING_BOUNDARY_VALID:

    raise ValueError(
        "Notebook 06 factual supervision handover boundary is invalid."
    )


# =============================================================================
# Resolve Notebook 03 persisted artefact IDs
# =============================================================================

def block_10_resolve_drive_file_id(
    candidate_names,
):
    """
    Resolve a Drive file ID from known Notebook runtime objects.

    Supports:
      - direct string file IDs;
      - dictionaries containing an 'id' field.
    """

    for candidate_name in candidate_names:

        if candidate_name not in globals():

            continue


        candidate_value = globals()[
            candidate_name
        ]


        if (
            isinstance(
                candidate_value,
                str,
            )
            and candidate_value.strip()
        ):

            return candidate_value


        if isinstance(
            candidate_value,
            dict,
        ):

            candidate_id = candidate_value.get(
                "id"
            )


            if (
                isinstance(
                    candidate_id,
                    str,
                )
                and candidate_id.strip()
            ):

                return candidate_id


    return None


BLOCK_10_NOTEBOOK_03_ACCEPTED_FILE_ID = (
    block_10_resolve_drive_file_id(
        [
            "NOTEBOOK_03_ACCEPTED_FILE_ID",
            "NOTEBOOK_03_ACCEPTED_SUPERVISION_FILE_ID",
            "NOTEBOOK_03_ACCEPTED_FILE",
        ]
    )
)


BLOCK_10_NOTEBOOK_03_HANDOVER_FILE_ID = (
    block_10_resolve_drive_file_id(
        [
            "NOTEBOOK_03_HANDOVER_FILE_ID",
            "NOTEBOOK_03_HANDOVER_DRIVE_FILE_ID",
            "NOTEBOOK_03_HANDOVER_FILE",
        ]
    )
)


# -----------------------------------------------------------------------------
# The Notebook 03 handover ID is already known from the persisted runtime
# when available. It is preferred but not fabricated if the local variable
# name differs.
# -----------------------------------------------------------------------------

BLOCK_10_NOTEBOOK_03_ACCEPTED_FILE_ID_AVAILABLE = bool(
    BLOCK_10_NOTEBOOK_03_ACCEPTED_FILE_ID
)


BLOCK_10_NOTEBOOK_03_HANDOVER_FILE_ID_AVAILABLE = bool(
    BLOCK_10_NOTEBOOK_03_HANDOVER_FILE_ID
)


# =============================================================================
# Parameter-policy handover
# =============================================================================

BLOCK_10_PARAMETER_POLICY = {
    parameter_name:
        {
            "requires_grad":
                bool(
                    parameter.requires_grad
                ),

            "parameter_count":
                int(
                    parameter.numel()
                ),
        }

    for parameter_name, parameter
    in MEDIA_AI_MODEL.named_parameters()
}


BLOCK_10_CURRENT_TRAINABLE_PARAMETER_NAMES = [
    parameter_name

    for parameter_name, parameter
    in MEDIA_AI_MODEL.named_parameters()

    if parameter.requires_grad
]


BLOCK_10_ONLY_PSYCHOLOGICAL_PARAMETERS_TRAINABLE = all(
    parameter_name.startswith(
        "psychological_head."
    )

    for parameter_name
    in BLOCK_10_CURRENT_TRAINABLE_PARAMETER_NAMES
)


if not BLOCK_10_ONLY_PSYCHOLOGICAL_PARAMETERS_TRAINABLE:

    raise ValueError(
        "Notebook 05 completion found trainable parameters outside "
        "the psychological head."
    )


# =============================================================================
# Future notebook parameter policy
# =============================================================================

NOTEBOOK_06_DEFAULT_FREEZE_POLICY = {
    "contextual_encoder":
        "frozen",

    "backbone":
        "frozen",

    "global_confluent_path":
        "frozen",

    "psychological_head":
        "frozen",

    "factual_head":
        "not_activated_until_supervision_mapping_is_resolved",

    "social_head":
        "frozen",

    "transformative_mechanisms":
        "frozen",

    "TW_F_TW_P_TW_S":
        "frozen",

    "H_F_H_P_H_S":
        "frozen",

    "group_conditioned_paths":
        "inactive_and_frozen",
}


# =============================================================================
# Group-conditioned path deferral contract
# =============================================================================

BLOCK_10_GROUP_PATH_REQUIRED = False

BLOCK_10_GLOBAL_PATH_REQUIRED = True

BLOCK_10_GROUP_PATH_OPTIONAL = True

BLOCK_10_GROUP_PATH_REPLACES_GLOBAL = False

BLOCK_10_CONCRETE_GROUPS_PREDEFINED = False

BLOCK_10_GROUPING_DEFERRED_TO_NOTEBOOK_10 = True

BLOCK_10_GROUPING_JUSTIFIED_BY_CURRENT_SAMPLE = False


BLOCK_10_GROUP_DEFERRAL_VALID = all(
    [
        BLOCK_10_GLOBAL_PATH_REQUIRED,
        BLOCK_10_GROUP_PATH_OPTIONAL,
        not BLOCK_10_GROUP_PATH_REPLACES_GLOBAL,
        not BLOCK_10_CONCRETE_GROUPS_PREDEFINED,
        BLOCK_10_GROUPING_DEFERRED_TO_NOTEBOOK_10,
        not BLOCK_10_GROUPING_JUSTIFIED_BY_CURRENT_SAMPLE,
    ]
)


if not BLOCK_10_GROUP_DEFERRAL_VALID:

    raise ValueError(
        "Notebook 05 group-conditioned-path deferral contract is invalid."
    )


# =============================================================================
# Causal and masking contract
# =============================================================================

BLOCK_10_CAUSAL_PROCESSING_REQUIRED = True

BLOCK_10_FUTURE_CONTEXT_ALLOWED = False

BLOCK_10_ARTICLE_BOUNDARY_RESET_REQUIRED = True

BLOCK_10_CROSS_ARTICLE_STATE_CARRY_ALLOWED = False

BLOCK_10_MISSING_SUPERVISION_EQUALS_ZERO = False

BLOCK_10_MISSING_SUPERVISION_EQUALS_NEGATIVE = False

BLOCK_10_UNAVAILABLE_SUPERVISION_ENTERS_LOSS = False


BLOCK_10_METHOD_CONTRACT_VALID = all(
    [
        BLOCK_10_CAUSAL_PROCESSING_REQUIRED,
        not BLOCK_10_FUTURE_CONTEXT_ALLOWED,
        BLOCK_10_ARTICLE_BOUNDARY_RESET_REQUIRED,
        not BLOCK_10_CROSS_ARTICLE_STATE_CARRY_ALLOWED,
        not BLOCK_10_MISSING_SUPERVISION_EQUALS_ZERO,
        not BLOCK_10_MISSING_SUPERVISION_EQUALS_NEGATIVE,
        not BLOCK_10_UNAVAILABLE_SUPERVISION_ENTERS_LOSS,
    ]
)


if not BLOCK_10_METHOD_CONTRACT_VALID:

    raise ValueError(
        "Notebook 05 causal or missing-supervision contract is invalid."
    )


# =============================================================================
# Block 9 scope audit serialisation
# =============================================================================

BLOCK_10_SCOPE_AUDIT_RECORDS = (
    BLOCK_9_SCOPE_AUDIT.to_dict(
        orient=
            "records"
    )
)


# =============================================================================
# Construct Notebook 05 → Notebook 06 handover
# =============================================================================

NOTEBOOK_05_TO_06_HANDOVER = {
    "handover_type":
        "media_ai_notebook_handover",

    "handover_version":
        NOTEBOOK_05_TO_06_HANDOVER_VERSION,

    "created_at_utc":
        BLOCK_10_EXECUTED_AT_UTC,

    "source_notebook":
        "05_training_evaluation_and_validation",

    "source_notebook_stage":
        "psychological_path",

    "target_notebook":
        "06_factual_path",

    "project_version":
        "1.0",

    "notebook_05_completion":
        {
            "block_count":
                10,

            "notebook_complete":
                True,

            "psychological_path_complete":
                True,

            "architecture_complete":
                bool(
                    BLOCK_9_VERSION_1_ARCHITECTURE_COMPLETE
                ),

            "controlled_pipeline_complete":
                bool(
                    BLOCK_9_VERSION_1_CONTROLLED_PIPELINE_COMPLETE
                ),

            "full_training_coverage":
                bool(
                    BLOCK_9_VERSION_1_FULL_TRAINING_COVERAGE
                ),

            "generalisation_validated":
                bool(
                    BLOCK_9_VERSION_1_GENERALISATION_VALIDATED
                ),

            "empirical_validity":
                False,
        },

    "remaining_version_1_notebooks":
        deepcopy(
            MEDIA_AI_VERSION_1_REMAINING_NOTEBOOK_SEQUENCE
        ),

    "architecture_contract":
        {
            "representation_level":
                "sentence",

            "textual_representation_dimension":
                int(
                    CONTEXTUAL_ENCODER_EXPECTED_DIM
                ),

            "backbone_interface_dimension":
                int(
                    BACKBONE_HIDDEN_DIM
                ),

            "confluent_hidden_dimension":
                int(
                    CONFLUENT_HIDDEN_DIM
                ),

            "factual_representation_dimension":
                int(
                    NOTEBOOK_06_EXPECTED_FACTUAL_ARCHITECTURAL_DIMENSION
                ),

            "psychological_representation_dimension":
                34,

            "psychological_vector_order":
                list(
                    BLOCK_10_PSYCHOLOGICAL_TARGET_ORDER
                ),

            "psychological_vector_dimensions":
                deepcopy(
                    BLOCK_10_PSYCHOLOGICAL_VECTOR_DIMENSIONS
                ),

            "social_representation":
                "structured_variable_dimensional",

            "global_path_required":
                True,

            "group_path_optional":
                True,

            "group_path_replaces_global":
                False,

            "concrete_groups_predefined":
                False,
        },

    "contextual_representation":
        {
            "provider":
                CONTEXTUAL_ENCODER_PROVIDER,

            "model_id":
                CONTEXTUAL_ENCODER_MODEL_ID,

            "dimension":
                int(
                    CONTEXTUAL_ENCODER_EXPECTED_DIM
                ),

            "encoder_frozen":
                True,

            "artifact_filename":
                NOTEBOOK_05_REPRESENTATION_FILENAME,

            "artifact_drive_file_id":
                NOTEBOOK_05_REPRESENTATION_DRIVE_FILE_ID,

            "sentence_count":
                int(
                    DATASET_SENTENCE_COUNT
                ),

            "sentence_alignment_required":
                True,
        },

    "canonical_identity":
        {
            "article_count":
                int(
                    DATASET_ARTICLE_COUNT
                ),

            "sentence_count":
                int(
                    DATASET_SENTENCE_COUNT
                ),

            "sentence_ids_present":
                bool(
                    BLOCK_10_SENTENCE_IDS_PRESENT
                ),

            "sentence_ids_unique":
                bool(
                    BLOCK_10_SENTENCE_IDS_UNIQUE
                ),

            "article_ids":
                list(
                    BLOCK_10_ARTICLE_IDS
                ),

            "sentence_ids":
                list(
                    BLOCK_10_SENTENCE_IDS
                ),
        },

    "psychological_path":
        {
            "trained":
                True,

            "active_targets":
                list(
                    BLOCK_10_PSYCHOLOGICAL_TARGET_ORDER
                ),

            "target_dimensions":
                deepcopy(
                    BLOCK_10_PSYCHOLOGICAL_VECTOR_DIMENSIONS
                ),

            "objective_weights":
                {
                    target_name:
                        float(
                            OBJECTIVE_WEIGHTS[
                                target_name
                            ]
                        )

                    for target_name
                    in BLOCK_10_PSYCHOLOGICAL_TARGET_ORDER
                },

            "checkpoint_type":
                BLOCK_7_CHECKPOINT_TYPE,

            "checkpoint_filename":
                BLOCK_7_CHECKPOINT_FILENAME,

            "checkpoint_drive_file_id":
                BLOCK_7_CHECKPOINT_DRIVE_FILE_ID,

            "metadata_filename":
                BLOCK_7_CHECKPOINT_METADATA_FILENAME,

            "metadata_drive_file_id":
                BLOCK_7_METADATA_DRIVE_FILE_ID,

            "post_training_objective":
                float(
                    BLOCK_7_FINAL_LOSS_VALUE
                ),

            "checkpoint_reproducibility_valid":
                bool(
                    BLOCK_10_CHECKPOINT_REPRODUCIBILITY_VALID
                ),

            "default_future_state":
                "frozen",
        },

    "notebook_03_supervision":
        {
            "accepted_record_count":
                int(
                    BLOCK_10_NOTEBOOK_03_ACCEPTED_RECORD_COUNT
                ),

            "accepted_file_id":
                BLOCK_10_NOTEBOOK_03_ACCEPTED_FILE_ID,

            "handover_file_id":
                BLOCK_10_NOTEBOOK_03_HANDOVER_FILE_ID,

            "canonical_machine_supervision":
                True,

            "human_reviewed_reference":
                False,

            "adjudicated_reference":
                False,
        },

    "notebook_06_factual_starting_contract":
        {
            "factual_architectural_dimension":
                int(
                    NOTEBOOK_06_EXPECTED_FACTUAL_ARCHITECTURAL_DIMENSION
                ),

            "factological_component_count":
                int(
                    NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT
                ),

            "factological_components":
                list(
                    NOTEBOOK_06_FACTOLOGICAL_COMPONENTS
                ),

            "factological_component_schema_valid":
                bool(
                    BLOCK_10_FACTOLOGICAL_COMPONENT_SCHEMA_VALID
                ),

            "factological_weight_available":
                bool(
                    BLOCK_10_FACTOLOGICAL_WEIGHT_AVAILABLE
                ),

            "factological_weight_available_records":
                int(
                    BLOCK_10_FACTOLOGICAL_WEIGHT_RECORDS
                ),

            "factological_weight_auto_mapped":
                False,

            "factual_supervision_mapping_resolved":
                False,

            "factual_supervision_mapping_required":
                True,

            "partial_supervision_allowed":
                True,

            "unresolved_dimensions_may_be_fabricated":
                False,

            "first_substantive_task":
                (
                    "factual_supervision_mapping_and_target_contract_audit"
                ),

            "optimisation_may_begin_before_mapping":
                False,
        },

    "notebook_06_default_parameter_policy":
        deepcopy(
            NOTEBOOK_06_DEFAULT_FREEZE_POLICY
        ),

    "future_component_boundaries":
        {
            "TEV_is_architectural_psychological_transformation":
                False,

            "EW_is_TW_P":
                False,

            "TW_F_TW_P_TW_S_collapsed":
                False,

            "H_F_H_P_H_S_collapsed":
                False,

            "group_conditioning_required_for_core_model":
                False,

            "group_conditioning_replaces_global_path":
                False,
        },

    "group_conditioning_version_1_policy":
        {
            "deferred_to_notebook":
                "10",

            "reason":
                (
                    "Current validated sample is insufficient to justify "
                    "stable or extensive data-driven grouping."
                ),

            "global_path_remains_required":
                True,

            "group_path_remains_optional":
                True,

            "fabricated_groups_allowed":
                False,

            "predicted_groups_automatically_ground_truth":
                False,
        },

    "causal_contract":
        {
            "causal_processing":
                True,

            "future_context_allowed":
                False,

            "article_boundary_state_reset":
                True,

            "cross_article_state_carry":
                False,

            "within_article_order_required":
                True,
        },

    "masking_contract":
        {
            "mask_aware_supervision":
                True,

            "missing_equals_zero":
                False,

            "missing_equals_negative":
                False,

            "unavailable_enters_loss":
                False,

            "partial_supervision_allowed":
                True,
        },

    "scope_audit":
        {
            "functionality_count":
                int(
                    BLOCK_9_FUNCTIONALITY_COUNT
                ),

            "implemented_count":
                int(
                    BLOCK_9_IMPLEMENTED_COUNT
                ),

            "structurally_validated_count":
                int(
                    BLOCK_9_STRUCTURALLY_VALIDATED_COUNT
                ),

            "trained_count":
                int(
                    BLOCK_9_TRAINED_COUNT
                ),

            "independently_evaluated_count":
                int(
                    BLOCK_9_INDEPENDENTLY_EVALUATED_COUNT
                ),

            "empirically_validated_count":
                int(
                    BLOCK_9_EMPIRICALLY_VALIDATED_COUNT
                ),

            "closure_blockers":
                list(
                    BLOCK_9_CLOSURE_BLOCKERS
                ),

            "recorded_limitations":
                list(
                    BLOCK_9_RECORDED_LIMITATIONS
                ),

            "records":
                deepcopy(
                    BLOCK_10_SCOPE_AUDIT_RECORDS
                ),
        },

    "methodological_boundary":
        {
            "notebook_05_psychological_path_complete":
                True,

            "full_media_ai_project_complete":
                False,

            "full_training_coverage":
                False,

            "generalisation_validated":
                False,

            "empirical_validity":
                False,

            "factual_head_trained":
                False,

            "social_head_trained":
                False,

            "transformative_mechanisms_trained":
                False,

            "transformative_weights_trained":
                False,

            "recurrent_mechanisms_trained":
                False,

            "group_conditioned_path_trained":
                False,

            "new_training_executed_by_block_10":
                False,

            "synthetic_supervision_created_by_block_10":
                False,
        },
}


# =============================================================================
# JSON serialisability validation
# =============================================================================

def block_10_json_default(
    value,
):
    """
    Convert common NumPy / torch values to JSON-safe values.
    """

    if isinstance(
        value,
        np.generic,
    ):

        return value.item()


    if isinstance(
        value,
        np.ndarray,
    ):

        return value.tolist()


    if torch.is_tensor(
        value
    ):

        return (
            value.detach()
            .cpu()
            .tolist()
        )


    if isinstance(
        value,
        set,
    ):

        return sorted(
            value
        )


    if isinstance(
        value,
        tuple,
    ):

        return list(
            value
        )


    raise TypeError(
        f"Object of type {type(value).__name__} "
        "is not JSON serialisable."
    )


NOTEBOOK_05_TO_06_HANDOVER_JSON = json.dumps(
    NOTEBOOK_05_TO_06_HANDOVER,
    ensure_ascii=False,
    indent=2,
    default=
        block_10_json_default,
)


BLOCK_10_HANDOVER_JSON_VALID = bool(
    NOTEBOOK_05_TO_06_HANDOVER_JSON
)


if not BLOCK_10_HANDOVER_JSON_VALID:

    raise ValueError(
        "Notebook 05 to Notebook 06 handover could not be serialised."
    )

# =============================================================================
# Local handover persistence
# =============================================================================

with open(
    NOTEBOOK_05_TO_06_HANDOVER_FILENAME,
    "w",
    encoding="utf-8",
) as handover_file:

    handover_file.write(
        NOTEBOOK_05_TO_06_HANDOVER_JSON
    )


BLOCK_10_LOCAL_HANDOVER_CREATED = os.path.exists(
    NOTEBOOK_05_TO_06_HANDOVER_FILENAME
)


if not BLOCK_10_LOCAL_HANDOVER_CREATED:

    raise ValueError(
        "Local Notebook 05 to Notebook 06 handover was not created."
    )


# =============================================================================
# Google Drive handover persistence
# =============================================================================

BLOCK_10_DRIVE_SERVICE = (
    DRIVE_SERVICE_FOR_HANDOVER
)


# -----------------------------------------------------------------------------
# Use Notebook 04 → 05 handover parent location
# -----------------------------------------------------------------------------

block_10_parent_metadata = (
    BLOCK_10_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_05_HANDOVER_DRIVE_FILE_ID,

        fields=
            "id,name,parents",
    )
    .execute()
)


BLOCK_10_PARENT_IDS = (
    block_10_parent_metadata.get(
        "parents",
        [],
    )
)


# -----------------------------------------------------------------------------
# Locate existing Notebook 05 → 06 handover
# -----------------------------------------------------------------------------

escaped_handover_filename = (
    NOTEBOOK_05_TO_06_HANDOVER_FILENAME.replace(
        "'",
        "\\'",
    )
)


handover_search_response = (
    BLOCK_10_DRIVE_SERVICE.files()
    .list(
        q=(
            f"name = '{escaped_handover_filename}' "
            "and trashed = false"
        ),

        spaces=
            "drive",

        fields=
            "files(id,name,modifiedTime,parents)",

        orderBy=
            "modifiedTime desc",

        pageSize=
            10,
    )
    .execute()
)


BLOCK_10_EXISTING_HANDOVER_FILES = (
    handover_search_response.get(
        "files",
        [],
    )
)


# -----------------------------------------------------------------------------
# Upload body
# -----------------------------------------------------------------------------

handover_bytes = (
    NOTEBOOK_05_TO_06_HANDOVER_JSON.encode(
        "utf-8"
    )
)


handover_media = MediaIoBaseUpload(
    io.BytesIO(
        handover_bytes
    ),
    mimetype=
        "application/json",
    resumable=
        False,
)


# -----------------------------------------------------------------------------
# Update existing or create new
# -----------------------------------------------------------------------------

if BLOCK_10_EXISTING_HANDOVER_FILES:

    BLOCK_10_HANDOVER_DRIVE_FILE = (
        BLOCK_10_DRIVE_SERVICE.files()
        .update(
            fileId=
                BLOCK_10_EXISTING_HANDOVER_FILES[
                    0
                ][
                    "id"
                ],

            media_body=
                handover_media,

            fields=
                "id,name,modifiedTime,parents",
        )
        .execute()
    )


    BLOCK_10_HANDOVER_DRIVE_OPERATION = (
        "updated"
    )


else:

    handover_metadata = {
        "name":
            NOTEBOOK_05_TO_06_HANDOVER_FILENAME,
    }


    if BLOCK_10_PARENT_IDS:

        handover_metadata[
            "parents"
        ] = BLOCK_10_PARENT_IDS


    BLOCK_10_HANDOVER_DRIVE_FILE = (
        BLOCK_10_DRIVE_SERVICE.files()
        .create(
            body=
                handover_metadata,

            media_body=
                handover_media,

            fields=
                "id,name,modifiedTime,parents",
        )
        .execute()
    )


    BLOCK_10_HANDOVER_DRIVE_OPERATION = (
        "created"
    )


NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID = (
    BLOCK_10_HANDOVER_DRIVE_FILE.get(
        "id"
    )
)


BLOCK_10_HANDOVER_DRIVE_PERSISTED = bool(
    NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID
)


if not BLOCK_10_HANDOVER_DRIVE_PERSISTED:

    raise ValueError(
        "Notebook 05 to Notebook 06 handover was not persisted "
        "to Google Drive."
    )


# =============================================================================
# Read-back validation
# =============================================================================

handover_download_request = (
    BLOCK_10_DRIVE_SERVICE.files()
    .get_media(
        fileId=
            NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID
    )
)


handover_download_buffer = io.BytesIO()


handover_downloader = MediaIoBaseDownload(
    handover_download_buffer,
    handover_download_request,
)


handover_download_complete = False


while not handover_download_complete:

    _, handover_download_complete = (
        handover_downloader.next_chunk()
    )


handover_download_buffer.seek(
    0
)


BLOCK_10_RELOADED_HANDOVER = json.loads(
    handover_download_buffer.read()
    .decode(
        "utf-8"
    )
)


# =============================================================================
# Handover contract validation
# =============================================================================

BLOCK_10_HANDOVER_VERSION_VALID = (
    BLOCK_10_RELOADED_HANDOVER.get(
        "handover_version"
    )
    ==
    NOTEBOOK_05_TO_06_HANDOVER_VERSION
)


BLOCK_10_HANDOVER_SOURCE_VALID = (
    BLOCK_10_RELOADED_HANDOVER.get(
        "source_notebook"
    )
    ==
    "05_training_evaluation_and_validation"
)


BLOCK_10_HANDOVER_TARGET_VALID = (
    BLOCK_10_RELOADED_HANDOVER.get(
        "target_notebook"
    )
    ==
    "06_factual_path"
)


BLOCK_10_HANDOVER_PSYCHOLOGICAL_STATE_VALID = (
    BLOCK_10_RELOADED_HANDOVER[
        "psychological_path"
    ][
        "trained"
    ]
    is True
)


BLOCK_10_HANDOVER_FACTUAL_MAPPING_UNRESOLVED = (
    BLOCK_10_RELOADED_HANDOVER[
        "notebook_06_factual_starting_contract"
    ][
        "factual_supervision_mapping_resolved"
    ]
    is False
)


BLOCK_10_HANDOVER_FACTUAL_MAPPING_REQUIRED = (
    BLOCK_10_RELOADED_HANDOVER[
        "notebook_06_factual_starting_contract"
    ][
        "factual_supervision_mapping_required"
    ]
    is True
)


BLOCK_10_HANDOVER_FACTUAL_DIMENSION_VALID = (
    BLOCK_10_RELOADED_HANDOVER[
        "notebook_06_factual_starting_contract"
    ][
        "factual_architectural_dimension"
    ]
    == 10
)


BLOCK_10_HANDOVER_FACTOLOGICAL_COMPONENT_COUNT_VALID = (
    BLOCK_10_RELOADED_HANDOVER[
        "notebook_06_factual_starting_contract"
    ][
        "factological_component_count"
    ]
    == 8
)


BLOCK_10_HANDOVER_GROUP_DEFERRAL_VALID = (
    BLOCK_10_RELOADED_HANDOVER[
        "group_conditioning_version_1_policy"
    ][
        "deferred_to_notebook"
    ]
    ==
    "10"
)


BLOCK_10_HANDOVER_GLOBAL_PATH_REQUIRED = (
    BLOCK_10_RELOADED_HANDOVER[
        "group_conditioning_version_1_policy"
    ][
        "global_path_remains_required"
    ]
    is True
)


BLOCK_10_HANDOVER_PROJECT_NOT_COMPLETE = (
    BLOCK_10_RELOADED_HANDOVER[
        "methodological_boundary"
    ][
        "full_media_ai_project_complete"
    ]
    is False
)


BLOCK_10_HANDOVER_NO_EMPIRICAL_VALIDITY = (
    BLOCK_10_RELOADED_HANDOVER[
        "methodological_boundary"
    ][
        "empirical_validity"
    ]
    is False
)


BLOCK_10_HANDOVER_READBACK_VALID = all(
    [
        BLOCK_10_HANDOVER_VERSION_VALID,
        BLOCK_10_HANDOVER_SOURCE_VALID,
        BLOCK_10_HANDOVER_TARGET_VALID,
        BLOCK_10_HANDOVER_PSYCHOLOGICAL_STATE_VALID,
        BLOCK_10_HANDOVER_FACTUAL_MAPPING_UNRESOLVED,
        BLOCK_10_HANDOVER_FACTUAL_MAPPING_REQUIRED,
        BLOCK_10_HANDOVER_FACTUAL_DIMENSION_VALID,
        BLOCK_10_HANDOVER_FACTOLOGICAL_COMPONENT_COUNT_VALID,
        BLOCK_10_HANDOVER_GROUP_DEFERRAL_VALID,
        BLOCK_10_HANDOVER_GLOBAL_PATH_REQUIRED,
        BLOCK_10_HANDOVER_PROJECT_NOT_COMPLETE,
        BLOCK_10_HANDOVER_NO_EMPIRICAL_VALIDITY,
    ]
)


if not BLOCK_10_HANDOVER_READBACK_VALID:

    raise ValueError(
        "Persisted Notebook 05 to Notebook 06 handover failed "
        "read-back contract validation."
    )


# =============================================================================
# Notebook 06 readiness
# =============================================================================

NOTEBOOK_06_HANDOVER_AVAILABLE = True

NOTEBOOK_06_HANDOVER_VALID = (
    BLOCK_10_HANDOVER_READBACK_VALID
)

NOTEBOOK_06_FACTUAL_MAPPING_READY_TO_AUDIT = True

NOTEBOOK_06_FACTUAL_OPTIMISATION_READY = False


NOTEBOOK_06_READY_TO_INITIALISE = all(
    [
        NOTEBOOK_06_HANDOVER_AVAILABLE,
        NOTEBOOK_06_HANDOVER_VALID,
        NOTEBOOK_06_FACTUAL_MAPPING_READY_TO_AUDIT,
        not NOTEBOOK_06_FACTUAL_OPTIMISATION_READY,
    ]
)


# =============================================================================
# Notebook 05 completion contract
# =============================================================================

BLOCK_10_NOTEBOOK_05_COMPLETION_CHECKS = {
    "blocks_1_to_9_complete":
        len(
            incomplete_blocks
        )
        == 0,

    "blocks_2_to_9_valid":
        len(
            invalid_blocks
        )
        == 0,

    "psychological_target_contract_valid":
        BLOCK_10_ACTIVE_TARGET_CONTRACT_VALID,

    "contextual_representation_contract_valid":
        BLOCK_10_REPRESENTATION_CONTRACT_VALID,

    "canonical_identity_contract_valid":
        BLOCK_10_IDENTITY_CONTRACT_VALID,

    "psychological_checkpoint_reproducible":
        BLOCK_10_CHECKPOINT_REPRODUCIBILITY_VALID,

    "factological_component_schema_valid":
        BLOCK_10_FACTOLOGICAL_COMPONENT_SCHEMA_VALID,

    "factual_mapping_boundary_valid":
        BLOCK_10_FACTUAL_MAPPING_BOUNDARY_VALID,

    "group_deferral_contract_valid":
        BLOCK_10_GROUP_DEFERRAL_VALID,

    "causal_and_masking_contract_valid":
        BLOCK_10_METHOD_CONTRACT_VALID,

    "remaining_roadmap_valid":
        BLOCK_10_ROADMAP_VALID,

    "handover_json_valid":
        BLOCK_10_HANDOVER_JSON_VALID,

    "handover_local_copy_created":
        BLOCK_10_LOCAL_HANDOVER_CREATED,

    "handover_drive_persisted":
        BLOCK_10_HANDOVER_DRIVE_PERSISTED,

    "handover_readback_valid":
        BLOCK_10_HANDOVER_READBACK_VALID,

    "notebook_06_ready_to_initialise":
        NOTEBOOK_06_READY_TO_INITIALISE,
}


BLOCK_10_NOTEBOOK_05_COMPLETION_VALID = all(
    BLOCK_10_NOTEBOOK_05_COMPLETION_CHECKS.values()
)


# =============================================================================
# Explicit methodological boundary checks
# =============================================================================

BLOCK_10_EXECUTION_BOUNDARY_VALID = all(
    [
        not BLOCK_10_BACKWARD_PASS_EXECUTED,
        not BLOCK_10_OPTIMIZER_STEP_EXECUTED,
        not BLOCK_10_PARAMETER_UPDATE_EXECUTED,
        not BLOCK_10_TRAINING_EXECUTED,
        not BLOCK_10_CHECKPOINT_SELECTION_EXECUTED,
        not BLOCK_10_ABLATION_EXECUTED,
        not BLOCK_10_HELD_OUT_EVALUATION_EXECUTED,
        not BLOCK_10_SYNTHETIC_SUPERVISION_CREATED,
        not BLOCK_10_FACTUAL_TARGET_MAPPING_PERFORMED,
        not BLOCK_10_SOCIAL_TARGET_MAPPING_PERFORMED,
        not BLOCK_10_TRANSFORMATION_TARGET_MAPPING_PERFORMED,
        not BLOCK_10_RECURRENT_TARGET_MAPPING_PERFORMED,
        not BLOCK_10_GROUP_CONSTRUCTION_PERFORMED,
        not BLOCK_10_EMPIRICAL_VALIDITY_ESTABLISHED,
    ]
)


# =============================================================================
# Final Block 10 validation
# =============================================================================

NOTEBOOK_05_BLOCK_10_ERRORS = []


if not BLOCK_10_NOTEBOOK_05_COMPLETION_VALID:

    failed_completion_checks = [
        check_name

        for check_name, check_value
        in BLOCK_10_NOTEBOOK_05_COMPLETION_CHECKS.items()

        if not check_value
    ]


    NOTEBOOK_05_BLOCK_10_ERRORS.append(
        {
            "completion_checks_failed":
                failed_completion_checks
        }
    )


if not BLOCK_10_EXECUTION_BOUNDARY_VALID:

    NOTEBOOK_05_BLOCK_10_ERRORS.append(
        "block_10_execution_boundary_invalid"
    )


if NOTEBOOK_06_FACTUAL_OPTIMISATION_READY:

    NOTEBOOK_05_BLOCK_10_ERRORS.append(
        "factual_optimisation_incorrectly_marked_ready_before_mapping"
    )


if BLOCK_10_GROUP_CONSTRUCTION_PERFORMED:

    NOTEBOOK_05_BLOCK_10_ERRORS.append(
        "group_construction_incorrectly_performed"
    )


if BLOCK_10_EMPIRICAL_VALIDITY_ESTABLISHED:

    NOTEBOOK_05_BLOCK_10_ERRORS.append(
        "empirical_validity_incorrectly_asserted"
    )


NOTEBOOK_05_BLOCK_10_VALID = (
    len(
        NOTEBOOK_05_BLOCK_10_ERRORS
    )
    == 0
)


if not NOTEBOOK_05_BLOCK_10_VALID:

    raise RuntimeError(
        "Notebook 05 Block 10 completion and handover audit failed. "
        f"Errors: {NOTEBOOK_05_BLOCK_10_ERRORS}"
    )


# =============================================================================
# Final notebook state
# =============================================================================

NOTEBOOK_05_PSYCHOLOGICAL_PATH_COMPLETE = True

NOTEBOOK_05_COMPLETE = True

NOTEBOOK_05_PROJECT_COMPLETE = False

NOTEBOOK_05_FULL_TRAINING_COVERAGE = False

NOTEBOOK_05_GENERALISATION_VALIDATED = False

NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED = False

NOTEBOOK_05_TO_06_HANDOVER_PERSISTED = True

NOTEBOOK_05_TO_06_HANDOVER_VALID = True

NOTEBOOK_05_BLOCK_10_COMPLETE = True


# =============================================================================
# Block 10 summary
# =============================================================================

NOTEBOOK_05_BLOCK_10_SUMMARY = {
    "block":
        NOTEBOOK_05_BLOCK_10,

    "block_name":
        NOTEBOOK_05_BLOCK_10_NAME,

    "version":
        NOTEBOOK_05_BLOCK_10_VERSION,

    "notebook_05_complete":
        NOTEBOOK_05_COMPLETE,

    "psychological_path_complete":
        NOTEBOOK_05_PSYCHOLOGICAL_PATH_COMPLETE,

    "full_project_complete":
        NOTEBOOK_05_PROJECT_COMPLETE,

    "psychological_checkpoint_reproducible":
        BLOCK_10_CHECKPOINT_REPRODUCIBILITY_VALID,

    "factual_architectural_dimension":
        NOTEBOOK_06_EXPECTED_FACTUAL_ARCHITECTURAL_DIMENSION,

    "factological_component_count":
        NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT,

    "factological_weight_available":
        BLOCK_10_FACTOLOGICAL_WEIGHT_AVAILABLE,

    "factual_mapping_resolved":
        NOTEBOOK_06_FACTUAL_SUPERVISION_MAPPING_RESOLVED,

    "notebook_06_ready_to_initialise":
        NOTEBOOK_06_READY_TO_INITIALISE,

    "notebook_06_factual_optimisation_ready":
        NOTEBOOK_06_FACTUAL_OPTIMISATION_READY,

    "grouping_deferred_to_notebook_10":
        BLOCK_10_GROUPING_DEFERRED_TO_NOTEBOOK_10,

    "handover_filename":
        NOTEBOOK_05_TO_06_HANDOVER_FILENAME,

    "handover_drive_operation":
        BLOCK_10_HANDOVER_DRIVE_OPERATION,

    "handover_drive_file_id":
        NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID,

    "handover_readback_valid":
        BLOCK_10_HANDOVER_READBACK_VALID,

    "full_training_coverage":
        NOTEBOOK_05_FULL_TRAINING_COVERAGE,

    "generalisation_validated":
        NOTEBOOK_05_GENERALISATION_VALIDATED,

    "empirical_validity":
        NOTEBOOK_05_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_05_BLOCK_10_VALID,

    "block_complete":
        NOTEBOOK_05_BLOCK_10_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 05, Block 10: "
    "Notebook 05 Completion, Persistent Handover and "
    "Remaining-Path Readiness"
)

print("=" * 72)

print(
    f"Completion version           : "
    f"{NOTEBOOK_05_BLOCK_10_VERSION}"
)


print("-" * 72)

print(
    "Notebook 05 completion"
)

print(
    f"Blocks 1–10 complete         : "
    f"{NOTEBOOK_05_BLOCK_10_COMPLETE}"
)

print(
    f"Psychological path complete  : "
    f"{NOTEBOOK_05_PSYCHOLOGICAL_PATH_COMPLETE}"
)

print(
    f"Notebook 05 complete         : "
    f"{NOTEBOOK_05_COMPLETE}"
)

print(
    f"Full Media AI project complete: "
    f"{NOTEBOOK_05_PROJECT_COMPLETE}"
)

print(
    f"Architecture complete        : "
    f"{BLOCK_9_VERSION_1_ARCHITECTURE_COMPLETE}"
)

print(
    f"Controlled pipeline complete : "
    f"{BLOCK_9_VERSION_1_CONTROLLED_PIPELINE_COMPLETE}"
)

print(
    f"Full training coverage       : "
    f"{NOTEBOOK_05_FULL_TRAINING_COVERAGE}"
)

print(
    f"Generalisation validated     : "
    f"{NOTEBOOK_05_GENERALISATION_VALIDATED}"
)


print("-" * 72)

print(
    "Psychological-path handover"
)

print(
    f"Active targets               : "
    f"{list(BLOCK_10_PSYCHOLOGICAL_TARGET_ORDER)}"
)

print(
    f"Checkpoint type              : "
    f"{BLOCK_7_CHECKPOINT_TYPE}"
)

print(
    f"Checkpoint Drive file ID     : "
    f"{BLOCK_7_CHECKPOINT_DRIVE_FILE_ID}"
)

print(
    f"Metadata Drive file ID       : "
    f"{BLOCK_7_METADATA_DRIVE_FILE_ID}"
)

print(
    f"Checkpoint reproducible      : "
    f"{BLOCK_10_CHECKPOINT_REPRODUCIBILITY_VALID}"
)

print(
    f"Post-training objective      : "
    f"{BLOCK_7_FINAL_LOSS_VALUE:.8f}"
)


print("-" * 72)

print(
    "Contextual representation handover"
)

print(
    f"Encoder provider             : "
    f"{CONTEXTUAL_ENCODER_PROVIDER}"
)

print(
    f"Encoder model                : "
    f"{CONTEXTUAL_ENCODER_MODEL_ID}"
)

print(
    f"Representation dimension     : "
    f"{CONTEXTUAL_ENCODER_EXPECTED_DIM}"
)

print(
    f"Representation Drive file ID : "
    f"{NOTEBOOK_05_REPRESENTATION_DRIVE_FILE_ID}"
)

print(
    f"Sentence IDs valid           : "
    f"{BLOCK_10_IDENTITY_CONTRACT_VALID}"
)


print("-" * 72)

print(
    "Notebook 06 factual starting contract"
)

print(
    f"Factual architectural dim.   : "
    f"{NOTEBOOK_06_EXPECTED_FACTUAL_ARCHITECTURAL_DIMENSION}"
)

print(
    f"Factological components      : "
    f"{NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT}"
)

print(
    f"Component schema valid       : "
    f"{BLOCK_10_FACTOLOGICAL_COMPONENT_SCHEMA_VALID}"
)

print(
    f"Factological weight avail.   : "
    f"{BLOCK_10_FACTOLOGICAL_WEIGHT_AVAILABLE}"
)

print(
    f"Factual mapping resolved     : "
    f"{NOTEBOOK_06_FACTUAL_SUPERVISION_MAPPING_RESOLVED}"
)

print(
    f"Mapping required first       : "
    f"{NOTEBOOK_06_FACTUAL_SUPERVISION_MAPPING_REQUIRED}"
)

print(
    f"Partial supervision allowed  : "
    f"{NOTEBOOK_06_PARTIAL_FACTUAL_SUPERVISION_ALLOWED}"
)

print(
    f"Fabricated dimensions allowed: "
    f"{NOTEBOOK_06_UNRESOLVED_DIMENSIONS_MAY_BE_FABRICATED}"
)

print(
    f"Factual optimisation ready   : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMISATION_READY}"
)


print("-" * 72)

print(
    "Remaining Version 1 roadmap"
)


for roadmap_record in (
    MEDIA_AI_VERSION_1_REMAINING_NOTEBOOK_SEQUENCE
):

    print(
        f"Notebook {roadmap_record['notebook']:<2}                : "
        f"{roadmap_record['name']}"
    )


print("-" * 72)

print(
    "Group-conditioned path policy"
)

print(
    f"Global path required         : "
    f"{BLOCK_10_GLOBAL_PATH_REQUIRED}"
)

print(
    f"Group path optional          : "
    f"{BLOCK_10_GROUP_PATH_OPTIONAL}"
)

print(
    f"Group replaces global        : "
    f"{BLOCK_10_GROUP_PATH_REPLACES_GLOBAL}"
)

print(
    f"Concrete groups predefined   : "
    f"{BLOCK_10_CONCRETE_GROUPS_PREDEFINED}"
)

print(
    f"Grouping deferred to N10     : "
    f"{BLOCK_10_GROUPING_DEFERRED_TO_NOTEBOOK_10}"
)

print(
    f"Current sample supports groups: "
    f"{BLOCK_10_GROUPING_JUSTIFIED_BY_CURRENT_SAMPLE}"
)


print("-" * 72)

print(
    "Persistent Notebook 05 → Notebook 06 handover"
)

print(
    f"Handover version             : "
    f"{NOTEBOOK_05_TO_06_HANDOVER_VERSION}"
)

print(
    f"Handover filename            : "
    f"{NOTEBOOK_05_TO_06_HANDOVER_FILENAME}"
)

print(
    f"Local copy created           : "
    f"{BLOCK_10_LOCAL_HANDOVER_CREATED}"
)

print(
    f"Drive operation              : "
    f"{BLOCK_10_HANDOVER_DRIVE_OPERATION}"
)

print(
    f"Drive file ID                : "
    f"{NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID}"
)

print(
    f"Read-back valid              : "
    f"{BLOCK_10_HANDOVER_READBACK_VALID}"
)

print(
    f"Notebook 06 ready to initialise: "
    f"{NOTEBOOK_06_READY_TO_INITIALISE}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Backward pass executed       : "
    f"{BLOCK_10_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{BLOCK_10_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{BLOCK_10_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"New training executed        : "
    f"{BLOCK_10_TRAINING_EXECUTED}"
)

print(
    f"Factual mapping performed    : "
    f"{BLOCK_10_FACTUAL_TARGET_MAPPING_PERFORMED}"
)

print(
    f"Group construction performed : "
    f"{BLOCK_10_GROUP_CONSTRUCTION_PERFORMED}"
)

print(
    f"Held-out evaluation executed : "
    f"{BLOCK_10_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity asserted  : "
    f"{BLOCK_10_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_05_BLOCK_10_VALID}"
)

print(
    f"Block 10 complete            : "
    f"{NOTEBOOK_05_BLOCK_10_COMPLETE}"
)


print("=" * 72)


print(
    "Notebook 05 psychological-path training, reproducibility and "
    "scope-audit pipeline completed successfully."
)

print(
    "The trained psychological head and its controlled experimental "
    "checkpoint remain reproducible and are preserved for downstream "
    "integration."
)

print(
    "Notebook 05 does not mark the complete Media AI Version 1 project "
    "as finished."
)

print(
    "Notebook 06 is designated to begin the factual path with a factual "
    "supervision mapping and target-contract audit."
)

print(
    "The ten-dimensional factual architectural representation has not "
    "been automatically equated with the eight Notebook 03 factological "
    "components."
)

print(
    "No additional factual dimensions have been invented and "
    "factological_weight has not been automatically mapped into the "
    "factual architectural representation."
)

print(
    "The completed psychological head remains frozen by default for "
    "Notebook 06."
)

print(
    "The social path, transformative mechanisms, Transformative Weights, "
    "recurrent states and group-conditioned path remain reserved for "
    "Notebooks 07–10."
)

print(
    "The mandatory global path remains the stable core conditioning path."
)

print(
    "Group-conditioned processing remains optional and is deliberately "
    "deferred to Notebook 10 because the current sample is insufficient "
    "to justify stable data-driven grouping."
)

print(
    "No new training, parameter update, synthetic supervision, factual "
    "target mapping, group construction or unsupported empirical claim "
    "has been introduced by Block 10."
)

print(
    "The persisted Notebook 05 to Notebook 06 handover has been "
    "read back and validated successfully."
)

print(
    "Notebook 06 can therefore initialise independently from persisted "
    "artefacts without rerunning Notebook 05."
)

print("=" * 72)

WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.
WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.

========================================================================
Media AI — Notebook 05, Block 10: Notebook 05 Completion, Persistent Handover and Remaining-Path Readiness
========================================================================
Completion version           : 1.0
------------------------------------------------------------------------
Notebook 05 completion
Blocks 1–10 complete         : True
Psychological path complete  : True
Notebook 05 complete         : True
Full Media AI project complete: False
Architecture complete        : True
Controlled pipeline complete : True
Full training coverage       : False
Generalisation validated     : False
------------------------------------------------------------------------
Psychological-path handover
Active targets               : ['REV', 'TEV', 'IEV', 'EW']
Checkpoint type              : controlled_experimental_training_checkpoint
Checkpoint Drive file ID     : 1W1R2NonX9vw7_oH9pnTo9nLzMbu9Jopb
Metadata Drive file ID       : 1pQBvET8W8iPTKC0XiLybW3VIYF7Tc0_a
Checkpoint reproducible      : True
Post-training objective      : 0.01169837
------------------------------------------------------------------------
Contextual representation handover
Encoder provider             : sentence-transformers
Encoder model                : sentence-transformers/all-mpnet-base-v2
Representation dimension     : 768
Representation Drive file ID : 11_j_CebqBpMSDLlccGwGROr5hklTBYRm
Sentence IDs valid           : True
------------------------------------------------------------------------
Notebook 06 factual starting contract
Factual architectural dim.   : 10
Factological components      : 8
Component schema valid       : True
Factological weight avail.   : True
Factual mapping resolved     : False
Mapping required first       : True
Partial supervision allowed  : True
Fabricated dimensions allowed: False
Factual optimisation ready   : False
------------------------------------------------------------------------
Remaining Version 1 roadmap
Notebook 06                : Factual Path
Notebook 07                : Social Path
Notebook 08                : Transformative Mechanism
Notebook 09                : Transformative Weights and Recurrent Mechanism
Notebook 10                : Group-Conditioned Path and Final Integration
------------------------------------------------------------------------
Group-conditioned path policy
Global path required         : True
Group path optional          : True
Group replaces global        : False
Concrete groups predefined   : False
Grouping deferred to N10     : True
Current sample supports groups: False
------------------------------------------------------------------------
Persistent Notebook 05 → Notebook 06 handover
Handover version             : 1.0
Handover filename            : notebook_05_to_06_handover.json
Local copy created           : True
Drive operation              : created
Drive file ID                : 1N45TzoAvmYBrXmkmIbtDtqDov3OD7O-h
Read-back valid              : True
Notebook 06 ready to initialise: True
------------------------------------------------------------------------
Execution boundary
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
New training executed        : False
Factual mapping performed    : False
Group construction performed : False
Held-out evaluation executed : False
Empirical validity asserted  : False
Block valid                  : True
Block 10 complete            : True
========================================================================
Notebook 05 psychological-path training, reproducibility and scope-audit pipeline completed successfully.
The trained psychological head and its controlled experimental checkpoint remain reproducible and are preserved for downstream integration.
Notebook 05 does not mark the complete Media AI Version 1 project as finished.
Notebook 06 is designated to begin the factual path with a factual supervision mapping and target-contract audit.
The ten-dimensional factual architectural representation has not been automatically equated with the eight Notebook 03 factological components.
No additional factual dimensions have been invented and factological_weight has not been automatically mapped into the factual architectural representation.
The completed psychological head remains frozen by default for Notebook 06.
The social path, transformative mechanisms, Transformative Weights, recurrent states and group-conditioned path remain reserved for Notebooks 07–10.
The mandatory global path remains the stable core conditioning path.
Group-conditioned processing remains optional and is deliberately deferred to Notebook 10 because the current sample is insufficient to justify stable data-driven grouping.
No new training, parameter update, synthetic supervision, factual target mapping, group construction or unsupported empirical claim has been introduced by Block 10.
The persisted Notebook 05 to Notebook 06 handover has been read back and validated successfully.
Notebook 06 can therefore initialise independently from persisted artefacts without rerunning Notebook 05.
========================================================================