<a href="https://colab.research.google.com/github/stilyank01-create/Media_AI/blob/main/06_factual_path.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Media AI — Notebook 06: Factual Path

## Purpose

This notebook develops, validates and trains the **factual path** of the Media AI architecture.

Notebook 05 completed the controlled psychological path and established a persistent, independently reloadable handover state. Notebook 06 continues from that persisted state without redefining or retraining the completed psychological path.

The central task of this notebook is to establish a methodologically valid relationship between the factual supervision available from Notebook 03 and the ten-dimensional factual representation defined by the Media AI architecture.

The existing Notebook 03 factual supervision contains eight explicit factological components together with an independently defined factological weight. These supervision signals must not be assumed to be equivalent to the ten-dimensional architectural factual representation. Their relationship must first be inspected, defined and validated before factual optimisation is permitted.

## Factual supervision boundary

The canonical Notebook 03 factological components are:

- `explicit_claim`
- `observation_or_event`
- `quantitative_information`
- `attribution`
- `evidence_reference`
- `certainty_statement`
- `uncertainty_statement`
- `speculation_or_prediction`

Notebook 03 additionally provides `factological_weight` as a separate supervision signal.

The Media AI factual representation has an architectural dimensionality of **10**.

Notebook 06 therefore begins with a factual supervision mapping and target-contract audit. No missing architectural dimensions may be invented, inferred from dimensionality alone, or populated with synthetic supervision.

`factological_weight` must remain conceptually distinct unless an explicit and validated mapping into the factual architecture is established.

Partial supervision is permitted where justified. Missing or unavailable supervision remains masked and must not be interpreted as numerical zero or negative evidence.

## Architectural boundary

Notebook 06 operates within the Media AI architecture established by the preceding notebooks.

The following components remain fixed by default:

- the frozen contextual sentence encoder;
- the validated 768-dimensional contextual sentence representations;
- the frozen backbone interface;
- the frozen global confluent conditioning path;
- the completed psychological head;
- the social path;
- architectural transformation mechanisms;
- `TW_F`, `TW_P` and `TW_S`;
- `H_F`, `H_P` and `H_S`;
- optional group-conditioned paths.

The factual head may become trainable only after its supervision contract has been explicitly validated.

Notebook 06 must not use psychological supervision as factual ground truth and must not activate later architectural mechanisms merely because they are structurally available.

## Sequential and causal contract

Canonical sentence identity and article structure established by the preceding notebooks are preserved.

Within each article:

- sentence order is preserved;
- future sentence context is prohibited;
- article boundaries remain explicit;
- recurrent state, where later activated, must reset between independent articles;
- cross-article state carry is prohibited.

The persisted contextual representations remain aligned by canonical sentence identity.

## Training and validation policy

Notebook 06 separates four questions that must not be conflated:

1. whether factual supervision exists;
2. whether that supervision can be mapped validly to the factual architecture;
3. whether the corresponding factual parameters are eligible for optimisation;
4. whether trained factual behaviour has been independently validated.

Training eligibility does not itself activate an objective.

Structural execution does not establish empirical validity.

Reduction of training loss does not demonstrate generalisation.

Any factual checkpoint produced before independent held-out evaluation remains a **controlled experimental training checkpoint**, not a validated model checkpoint.

## Relationship to the remaining Media AI Version 1 roadmap

Notebook 06 covers the **Factual Path**.

The remaining planned notebooks are:

- **Notebook 07 — Social Path**
- **Notebook 08 — Transformative Mechanism**
- **Notebook 09 — Transformative Weights and Recurrent Mechanism**
- **Notebook 10 — Group-Conditioned Path and Final Integration**

Group-conditioned processing remains optional for Media AI Version 1 and is deliberately deferred to Notebook 10. The current validated sample is too small to justify extensive or stable data-driven grouping.

The global confluent path therefore remains the mandatory core conditioning path.

## Notebook completion criterion

Notebook 06 is complete only when the factual supervision contract has been explicitly resolved, all activated factual objectives are mask-aware and methodologically justified, the permitted factual parameters have been trained under a controlled optimisation policy, and the resulting state has been persisted and independently reproduced.

If the available supervision does not justify all ten factual architectural dimensions, the unresolved dimensions must remain unsupervised rather than being fabricated.

Completion of Notebook 06 establishes the controlled factual path. It does not by itself establish full Media AI training coverage, generalisation, or project-level empirical validity.

## Block 1 — Initialisation and Notebook 05 Handover Validation

### Purpose

This block initialises the Media AI factual-path notebook from the persistent state produced by Notebook 05.

Its purpose is to establish that Notebook 06 can begin independently from persisted artefacts without requiring the Notebook 05 runtime to remain active.

The block loads and validates the Notebook 05 → Notebook 06 handover, verifies the artefact references and methodological contracts required by the factual path, and reconstructs the factual-path starting state.

No factual supervision mapping, objective activation, optimisation or training is performed in this block.

### Persistent handover source

Notebook 05 completed the controlled psychological path and persisted the handover artefact:

`notebook_05_to_06_handover.json`

The handover is expected to preserve the information required to initialise Notebook 06, including:

- canonical article and sentence identity;
- contextual representation provenance and dimensionality;
- the persisted contextual-representation artefact;
- the completed psychological-path checkpoint and metadata;
- the psychological supervision contract;
- the factual architectural dimensionality;
- the canonical Notebook 03 factological supervision schema;
- parameter-freezing expectations;
- causal and masking contracts;
- unresolved methodological boundaries;
- the remaining Media AI Version 1 notebook roadmap.

The handover must be loaded from persistent storage rather than reconstructed from assumptions about the previous runtime.

### Handover validation

The persisted handover must be validated before it is accepted as the Notebook 06 starting state.

Validation includes confirmation that:

- the artefact is explicitly a Media AI notebook handover;
- its source is Notebook 05;
- its target is Notebook 06;
- the handover version is supported;
- Notebook 05 is recorded as complete;
- the psychological path is recorded as complete;
- the full Media AI project is not incorrectly recorded as complete;
- the contextual representation dimension remains 768;
- the factual architectural representation remains ten-dimensional;
- canonical sentence identities are present and unique;
- the completed psychological path remains reproducibly checkpointed;
- factual supervision mapping remains unresolved;
- factual optimisation remains blocked until that mapping is resolved;
- group-conditioned processing remains optional and deferred;
- no unsupported empirical-validity claim is present.

A handover that violates these boundaries must not be silently repaired or accepted.

### Contextual representation contract

Notebook 06 reuses the contextual sentence representations generated and persisted by Notebook 05.

The expected representation source remains the frozen sentence-transformers encoder:

`sentence-transformers/all-mpnet-base-v2`

The expected contextual representation dimensionality is **768**.

The persisted representation artefact must remain aligned to canonical sentence IDs. Representation order alone must not be treated as sufficient evidence of alignment.

The contextual encoder remains frozen and outside the Notebook 06 optimisation policy.

Notebook 06 does not regenerate contextual representations unless a later explicit recovery procedure demonstrates that the persisted artefact is unavailable or invalid.

### Completed psychological-path boundary

The psychological path completed in Notebook 05 is treated as an upstream trained component.

Its directly supervised target families remain:

- `REV`
- `TEV`
- `IEV`
- `EW`

The persisted psychological checkpoint remains classified as a **controlled experimental training checkpoint**.

Notebook 06 must preserve this state without retraining the psychological head as part of factual-path optimisation.

The psychological head therefore begins Notebook 06 frozen by default.

Its outputs may later participate in explicitly defined architectural interactions, but psychological supervision must not be repurposed as factual ground truth.

### Factual-path starting contract

The Media AI architecture defines a factual representation with dimensionality **10**.

The canonical Notebook 03 supervision currently provides eight explicit factological components:

- `explicit_claim`
- `observation_or_event`
- `quantitative_information`
- `attribution`
- `evidence_reference`
- `certainty_statement`
- `uncertainty_statement`
- `speculation_or_prediction`

Notebook 03 also provides `factological_weight` as a separate supervision signal.

Block 1 validates only that these persisted factual supervision sources and their schema are available.

It does **not** establish how the eight components and `factological_weight` map onto the ten-dimensional factual architecture.

In particular:

- the eight components must not automatically be equated with eight of the ten architectural dimensions;
- `factological_weight` must not automatically become a ninth or tenth factual dimension;
- missing architectural dimensions must not be invented;
- unavailable supervision must not be replaced by synthetic targets;
- partial factual supervision remains permissible if later justified explicitly.

Resolving this relationship is a subsequent factual supervision and target-contract task.

### Parameter boundary

At Notebook 06 initialisation, no new component becomes trainable merely because the notebook has started.

The default state preserves:

- contextual encoder — frozen;
- backbone — frozen;
- global confluent conditioning path — frozen;
- psychological head — frozen;
- factual head — not yet activated for training;
- social head — frozen;
- architectural transformation mechanisms — frozen;
- `TW_F`, `TW_P` and `TW_S` — frozen;
- `H_F`, `H_P` and `H_S` — frozen;
- group-conditioned paths — inactive and frozen.

The factual head may become trainable only after the factual supervision mapping and target contract have been explicitly resolved and validated.

### Causal and masking boundary

The sequential and causal contracts established by the preceding notebooks remain unchanged.

Notebook 06 preserves:

- canonical sentence order within each article;
- explicit article boundaries;
- prohibition of future-context access;
- prohibition of recurrent state carry across independent articles;
- article-boundary state reset where recurrent processing is later activated;
- element-level masking of unavailable supervision;
- distinction between missing values, numerical zero and negative evidence.

Unavailable factual supervision must not enter a loss function.

### Execution boundary

Block 1 is an initialisation and validation block only.

It must not:

- construct a factual target mapping;
- activate factual objectives;
- create an optimiser;
- execute a supervised factual forward pass for loss calculation;
- calculate a factual training loss;
- execute a backward pass;
- update model parameters;
- train the factual head;
- construct social supervision;
- activate architectural transformations;
- activate Transformative Weights;
- activate recurrent states;
- construct data-driven groups;
- perform held-out evaluation;
- claim empirical validity.

### Block completion criterion

Block 1 is complete only when the persisted Notebook 05 → Notebook 06 handover has been loaded and validated, the required persistent artefact references are available, canonical identity and contextual-representation contracts are intact, the completed psychological path is preserved, and the unresolved factual supervision boundary is reproduced exactly.

Successful completion establishes that Notebook 06 is **ready for factual supervision mapping and target-contract analysis**.

It does not establish that the factual head is ready for optimisation.

In [2]:
# =============================================================================
# Media AI — Notebook 06
# Block 1: Initialisation and Notebook 05 Handover Validation
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone
import io
import json

import numpy as np
import torch

from google.colab import auth
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload


# =============================================================================
# Block configuration
# =============================================================================

NOTEBOOK_06 = "06_factual_path"

NOTEBOOK_06_VERSION = "1.0"

NOTEBOOK_06_BLOCK_1 = 1

NOTEBOOK_06_BLOCK_1_NAME = (
    "Initialisation and Notebook 05 Handover Validation"
)

NOTEBOOK_06_BLOCK_1_VERSION = "1.0"

PROJECT_RANDOM_SEED = 42


NOTEBOOK_05_TO_06_HANDOVER_FILENAME = (
    "notebook_05_to_06_handover.json"
)


# -----------------------------------------------------------------------------
# Persisted Notebook 05 → 06 handover Drive file ID
# -----------------------------------------------------------------------------

NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID = (
    "1N45TzoAvmYBrXmkmIbtDtqDov3OD7O-h"
)


BLOCK_1_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Reproducibility
# =============================================================================

np.random.seed(
    PROJECT_RANDOM_SEED
)

torch.manual_seed(
    PROJECT_RANDOM_SEED
)


if torch.cuda.is_available():

    torch.cuda.manual_seed_all(
        PROJECT_RANDOM_SEED
    )


# =============================================================================
# Google authentication
# =============================================================================

auth.authenticate_user()


NOTEBOOK_06_COLAB_AUTHENTICATED = True


NOTEBOOK_06_DRIVE_SERVICE = build(
    "drive",
    "v3",
)


NOTEBOOK_06_DRIVE_SERVICE_INITIALISED = (
    NOTEBOOK_06_DRIVE_SERVICE
    is not None
)


if not NOTEBOOK_06_DRIVE_SERVICE_INITIALISED:

    raise RuntimeError(
        "Notebook 06 Google Drive service could not be initialised."
    )


# =============================================================================
# Google Drive download helper
# =============================================================================

def download_drive_file_bytes(
    drive_service,
    file_id,
):
    """
    Download one Google Drive file and return raw bytes.
    """

    request = (
        drive_service.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    download_complete = False


    while not download_complete:

        _, download_complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Locate persisted Notebook 05 handover
# =============================================================================

NOTEBOOK_06_HANDOVER_DRIVE_FILE = (
    NOTEBOOK_06_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID,

        fields=
            "id,name,modifiedTime,parents,size,mimeType",
    )
    .execute()
)


NOTEBOOK_06_HANDOVER_LOCATED = all(
    [
        bool(
            NOTEBOOK_06_HANDOVER_DRIVE_FILE.get(
                "id"
            )
        ),

        NOTEBOOK_06_HANDOVER_DRIVE_FILE.get(
            "name"
        )
        ==
        NOTEBOOK_05_TO_06_HANDOVER_FILENAME,
    ]
)


if not NOTEBOOK_06_HANDOVER_LOCATED:

    raise ValueError(
        "The persisted Notebook 05 → Notebook 06 handover "
        "could not be located or has an unexpected filename."
    )


# =============================================================================
# Download and parse handover
# =============================================================================

NOTEBOOK_06_HANDOVER_BYTES = (
    download_drive_file_bytes(
        NOTEBOOK_06_DRIVE_SERVICE,
        NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID,
    )
)


NOTEBOOK_06_HANDOVER_DOWNLOADED = bool(
    NOTEBOOK_06_HANDOVER_BYTES
)


if not NOTEBOOK_06_HANDOVER_DOWNLOADED:

    raise ValueError(
        "Notebook 05 → Notebook 06 handover could not be downloaded."
    )


NOTEBOOK_06_HANDOVER = json.loads(
    NOTEBOOK_06_HANDOVER_BYTES.decode(
        "utf-8"
    )
)


NOTEBOOK_06_HANDOVER_JSON_PARSED = isinstance(
    NOTEBOOK_06_HANDOVER,
    dict,
)


if not NOTEBOOK_06_HANDOVER_JSON_PARSED:

    raise TypeError(
        "Notebook 05 → Notebook 06 handover is not a JSON object."
    )


# -----------------------------------------------------------------------------
# Local audit copy
# -----------------------------------------------------------------------------

with open(
    NOTEBOOK_05_TO_06_HANDOVER_FILENAME,
    "w",
    encoding="utf-8",
) as handover_file:

    json.dump(
        NOTEBOOK_06_HANDOVER,
        handover_file,
        indent=2,
        ensure_ascii=False,
    )


NOTEBOOK_06_LOCAL_HANDOVER_COPY_CREATED = True


# =============================================================================
# Top-level handover contract
# =============================================================================

NOTEBOOK_06_EXPECTED_HANDOVER_TYPE = (
    "media_ai_notebook_handover"
)

NOTEBOOK_06_EXPECTED_HANDOVER_VERSION = (
    "1.0"
)

NOTEBOOK_06_EXPECTED_SOURCE_NOTEBOOK = (
    "05_training_evaluation_and_validation"
)

NOTEBOOK_06_EXPECTED_TARGET_NOTEBOOK = (
    "06_factual_path"
)


NOTEBOOK_06_HANDOVER_TYPE_VALID = (
    NOTEBOOK_06_HANDOVER.get(
        "handover_type"
    )
    ==
    NOTEBOOK_06_EXPECTED_HANDOVER_TYPE
)


NOTEBOOK_06_HANDOVER_VERSION_VALID = (
    NOTEBOOK_06_HANDOVER.get(
        "handover_version"
    )
    ==
    NOTEBOOK_06_EXPECTED_HANDOVER_VERSION
)


NOTEBOOK_06_HANDOVER_SOURCE_VALID = (
    NOTEBOOK_06_HANDOVER.get(
        "source_notebook"
    )
    ==
    NOTEBOOK_06_EXPECTED_SOURCE_NOTEBOOK
)


NOTEBOOK_06_HANDOVER_TARGET_VALID = (
    NOTEBOOK_06_HANDOVER.get(
        "target_notebook"
    )
    ==
    NOTEBOOK_06_EXPECTED_TARGET_NOTEBOOK
)


# =============================================================================
# Notebook 05 completion contract
# =============================================================================

NOTEBOOK_06_SOURCE_COMPLETION = (
    NOTEBOOK_06_HANDOVER.get(
        "notebook_05_completion",
        {},
    )
)


NOTEBOOK_06_NOTEBOOK_05_COMPLETE = (
    NOTEBOOK_06_SOURCE_COMPLETION.get(
        "notebook_complete"
    )
    is True
)


NOTEBOOK_06_PSYCHOLOGICAL_PATH_COMPLETE = (
    NOTEBOOK_06_SOURCE_COMPLETION.get(
        "psychological_path_complete"
    )
    is True
)


NOTEBOOK_06_ARCHITECTURE_COMPLETE = (
    NOTEBOOK_06_SOURCE_COMPLETION.get(
        "architecture_complete"
    )
    is True
)


NOTEBOOK_06_CONTROLLED_PIPELINE_COMPLETE = (
    NOTEBOOK_06_SOURCE_COMPLETION.get(
        "controlled_pipeline_complete"
    )
    is True
)


NOTEBOOK_06_FULL_PROJECT_COMPLETE = (
    NOTEBOOK_06_HANDOVER.get(
        "methodological_boundary",
        {},
    ).get(
        "full_media_ai_project_complete"
    )
    is True
)


NOTEBOOK_06_PROJECT_CORRECTLY_REMAINS_OPEN = (
    not NOTEBOOK_06_FULL_PROJECT_COMPLETE
)


# =============================================================================
# Remaining roadmap validation
# =============================================================================

NOTEBOOK_06_REMAINING_ROADMAP = (
    NOTEBOOK_06_HANDOVER.get(
        "remaining_version_1_notebooks",
        [],
    )
)


NOTEBOOK_06_EXPECTED_REMAINING_SEQUENCE = [
    "06",
    "07",
    "08",
    "09",
    "10",
]


NOTEBOOK_06_ROADMAP_SEQUENCE = [
    str(
        roadmap_record.get(
            "notebook"
        )
    )

    for roadmap_record
    in NOTEBOOK_06_REMAINING_ROADMAP
]


NOTEBOOK_06_REMAINING_ROADMAP_VALID = (
    NOTEBOOK_06_ROADMAP_SEQUENCE
    ==
    NOTEBOOK_06_EXPECTED_REMAINING_SEQUENCE
)


# =============================================================================
# Architecture contract
# =============================================================================

NOTEBOOK_06_ARCHITECTURE_CONTRACT = (
    NOTEBOOK_06_HANDOVER.get(
        "architecture_contract",
        {},
    )
)


NOTEBOOK_06_REPRESENTATION_LEVEL = (
    NOTEBOOK_06_ARCHITECTURE_CONTRACT.get(
        "representation_level"
    )
)


NOTEBOOK_06_TEXTUAL_REPRESENTATION_DIM = int(
    NOTEBOOK_06_ARCHITECTURE_CONTRACT.get(
        "textual_representation_dimension",
        -1,
    )
)


NOTEBOOK_06_BACKBONE_INTERFACE_DIM = int(
    NOTEBOOK_06_ARCHITECTURE_CONTRACT.get(
        "backbone_interface_dimension",
        -1,
    )
)


NOTEBOOK_06_CONFLUENT_HIDDEN_DIM = int(
    NOTEBOOK_06_ARCHITECTURE_CONTRACT.get(
        "confluent_hidden_dimension",
        -1,
    )
)


NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM = int(
    NOTEBOOK_06_ARCHITECTURE_CONTRACT.get(
        "factual_representation_dimension",
        -1,
    )
)


NOTEBOOK_06_PSYCHOLOGICAL_ARCHITECTURAL_DIM = int(
    NOTEBOOK_06_ARCHITECTURE_CONTRACT.get(
        "psychological_representation_dimension",
        -1,
    )
)


NOTEBOOK_06_GLOBAL_PATH_REQUIRED = (
    NOTEBOOK_06_ARCHITECTURE_CONTRACT.get(
        "global_path_required"
    )
    is True
)


NOTEBOOK_06_GROUP_PATH_OPTIONAL = (
    NOTEBOOK_06_ARCHITECTURE_CONTRACT.get(
        "group_path_optional"
    )
    is True
)


NOTEBOOK_06_GROUP_PATH_REPLACES_GLOBAL = (
    NOTEBOOK_06_ARCHITECTURE_CONTRACT.get(
        "group_path_replaces_global"
    )
    is True
)


NOTEBOOK_06_CONCRETE_GROUPS_PREDEFINED = (
    NOTEBOOK_06_ARCHITECTURE_CONTRACT.get(
        "concrete_groups_predefined"
    )
    is True
)


NOTEBOOK_06_ARCHITECTURE_CONTRACT_VALID = all(
    [
        NOTEBOOK_06_REPRESENTATION_LEVEL
        == "sentence",

        NOTEBOOK_06_TEXTUAL_REPRESENTATION_DIM
        == 768,

        NOTEBOOK_06_BACKBONE_INTERFACE_DIM
        == 768,

        NOTEBOOK_06_CONFLUENT_HIDDEN_DIM
        == 256,

        NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM
        == 10,

        NOTEBOOK_06_PSYCHOLOGICAL_ARCHITECTURAL_DIM
        == 34,

        NOTEBOOK_06_GLOBAL_PATH_REQUIRED,

        NOTEBOOK_06_GROUP_PATH_OPTIONAL,

        not NOTEBOOK_06_GROUP_PATH_REPLACES_GLOBAL,

        not NOTEBOOK_06_CONCRETE_GROUPS_PREDEFINED,
    ]
)


if not NOTEBOOK_06_ARCHITECTURE_CONTRACT_VALID:

    raise ValueError(
        "Notebook 05 → Notebook 06 architecture contract is invalid."
    )


# =============================================================================
# Contextual representation contract
# =============================================================================

NOTEBOOK_06_CONTEXTUAL_REPRESENTATION = (
    NOTEBOOK_06_HANDOVER.get(
        "contextual_representation",
        {},
    )
)


NOTEBOOK_06_ENCODER_PROVIDER = (
    NOTEBOOK_06_CONTEXTUAL_REPRESENTATION.get(
        "provider"
    )
)


NOTEBOOK_06_ENCODER_MODEL_ID = (
    NOTEBOOK_06_CONTEXTUAL_REPRESENTATION.get(
        "model_id"
    )
)


NOTEBOOK_06_CONTEXTUAL_REPRESENTATION_DIM = int(
    NOTEBOOK_06_CONTEXTUAL_REPRESENTATION.get(
        "dimension",
        -1,
    )
)


NOTEBOOK_06_CONTEXTUAL_ENCODER_FROZEN = (
    NOTEBOOK_06_CONTEXTUAL_REPRESENTATION.get(
        "encoder_frozen"
    )
    is True
)


NOTEBOOK_06_REPRESENTATION_FILENAME = (
    NOTEBOOK_06_CONTEXTUAL_REPRESENTATION.get(
        "artifact_filename"
    )
)


NOTEBOOK_06_REPRESENTATION_DRIVE_FILE_ID = (
    NOTEBOOK_06_CONTEXTUAL_REPRESENTATION.get(
        "artifact_drive_file_id"
    )
)


NOTEBOOK_06_REPRESENTATION_SENTENCE_COUNT = int(
    NOTEBOOK_06_CONTEXTUAL_REPRESENTATION.get(
        "sentence_count",
        -1,
    )
)


NOTEBOOK_06_REPRESENTATION_ALIGNMENT_REQUIRED = (
    NOTEBOOK_06_CONTEXTUAL_REPRESENTATION.get(
        "sentence_alignment_required"
    )
    is True
)


NOTEBOOK_06_CONTEXTUAL_REPRESENTATION_CONTRACT_VALID = all(
    [
        NOTEBOOK_06_ENCODER_PROVIDER
        == "sentence-transformers",

        NOTEBOOK_06_ENCODER_MODEL_ID
        ==
        "sentence-transformers/all-mpnet-base-v2",

        NOTEBOOK_06_CONTEXTUAL_REPRESENTATION_DIM
        == 768,

        NOTEBOOK_06_CONTEXTUAL_ENCODER_FROZEN,

        bool(
            NOTEBOOK_06_REPRESENTATION_FILENAME
        ),

        bool(
            NOTEBOOK_06_REPRESENTATION_DRIVE_FILE_ID
        ),

        NOTEBOOK_06_REPRESENTATION_SENTENCE_COUNT > 0,

        NOTEBOOK_06_REPRESENTATION_ALIGNMENT_REQUIRED,
    ]
)


if not NOTEBOOK_06_CONTEXTUAL_REPRESENTATION_CONTRACT_VALID:

    raise ValueError(
        "Notebook 06 contextual representation handover contract "
        "is invalid."
    )


# =============================================================================
# Verify representation artefact reference
# =============================================================================

NOTEBOOK_06_REPRESENTATION_DRIVE_FILE = (
    NOTEBOOK_06_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_06_REPRESENTATION_DRIVE_FILE_ID,

        fields=
            "id,name,modifiedTime,size,mimeType",
    )
    .execute()
)


NOTEBOOK_06_REPRESENTATION_ARTEFACT_AVAILABLE = all(
    [
        bool(
            NOTEBOOK_06_REPRESENTATION_DRIVE_FILE.get(
                "id"
            )
        ),

        NOTEBOOK_06_REPRESENTATION_DRIVE_FILE.get(
            "name"
        )
        ==
        NOTEBOOK_06_REPRESENTATION_FILENAME,
    ]
)


if not NOTEBOOK_06_REPRESENTATION_ARTEFACT_AVAILABLE:

    raise ValueError(
        "Notebook 06 contextual representation artefact is unavailable "
        "or does not match the persisted filename."
    )


# =============================================================================
# Canonical identity contract
# =============================================================================

NOTEBOOK_06_CANONICAL_IDENTITY = (
    NOTEBOOK_06_HANDOVER.get(
        "canonical_identity",
        {},
    )
)


NOTEBOOK_06_ARTICLE_COUNT = int(
    NOTEBOOK_06_CANONICAL_IDENTITY.get(
        "article_count",
        -1,
    )
)


NOTEBOOK_06_SENTENCE_COUNT = int(
    NOTEBOOK_06_CANONICAL_IDENTITY.get(
        "sentence_count",
        -1,
    )
)


NOTEBOOK_06_ARTICLE_IDS = list(
    NOTEBOOK_06_CANONICAL_IDENTITY.get(
        "article_ids",
        [],
    )
)


NOTEBOOK_06_SENTENCE_IDS = list(
    NOTEBOOK_06_CANONICAL_IDENTITY.get(
        "sentence_ids",
        [],
    )
)


NOTEBOOK_06_SENTENCE_IDS_PRESENT = (
    NOTEBOOK_06_CANONICAL_IDENTITY.get(
        "sentence_ids_present"
    )
    is True
)


NOTEBOOK_06_SENTENCE_IDS_UNIQUE = (
    NOTEBOOK_06_CANONICAL_IDENTITY.get(
        "sentence_ids_unique"
    )
    is True
)


NOTEBOOK_06_IDENTITY_COUNTS_VALID = all(
    [
        NOTEBOOK_06_ARTICLE_COUNT
        ==
        len(
            NOTEBOOK_06_ARTICLE_IDS
        ),

        NOTEBOOK_06_SENTENCE_COUNT
        ==
        len(
            NOTEBOOK_06_SENTENCE_IDS
        ),

        NOTEBOOK_06_SENTENCE_COUNT
        ==
        NOTEBOOK_06_REPRESENTATION_SENTENCE_COUNT,
    ]
)


NOTEBOOK_06_RUNTIME_SENTENCE_IDS_UNIQUE = (
    len(
        NOTEBOOK_06_SENTENCE_IDS
    )
    ==
    len(
        set(
            NOTEBOOK_06_SENTENCE_IDS
        )
    )
)


NOTEBOOK_06_CANONICAL_IDENTITY_VALID = all(
    [
        NOTEBOOK_06_ARTICLE_COUNT > 0,
        NOTEBOOK_06_SENTENCE_COUNT > 0,
        NOTEBOOK_06_SENTENCE_IDS_PRESENT,
        NOTEBOOK_06_SENTENCE_IDS_UNIQUE,
        NOTEBOOK_06_RUNTIME_SENTENCE_IDS_UNIQUE,
        NOTEBOOK_06_IDENTITY_COUNTS_VALID,
    ]
)


if not NOTEBOOK_06_CANONICAL_IDENTITY_VALID:

    raise ValueError(
        "Notebook 06 canonical sentence identity contract is invalid."
    )


# =============================================================================
# Completed psychological-path contract
# =============================================================================

NOTEBOOK_06_PSYCHOLOGICAL_PATH = (
    NOTEBOOK_06_HANDOVER.get(
        "psychological_path",
        {},
    )
)


NOTEBOOK_06_PSYCHOLOGICAL_PATH_TRAINED = (
    NOTEBOOK_06_PSYCHOLOGICAL_PATH.get(
        "trained"
    )
    is True
)


NOTEBOOK_06_PSYCHOLOGICAL_ACTIVE_TARGETS = tuple(
    NOTEBOOK_06_PSYCHOLOGICAL_PATH.get(
        "active_targets",
        [],
    )
)


NOTEBOOK_06_EXPECTED_PSYCHOLOGICAL_TARGETS = (
    "REV",
    "TEV",
    "IEV",
    "EW",
)


NOTEBOOK_06_PSYCHOLOGICAL_TARGET_CONTRACT_VALID = (
    NOTEBOOK_06_PSYCHOLOGICAL_ACTIVE_TARGETS
    ==
    NOTEBOOK_06_EXPECTED_PSYCHOLOGICAL_TARGETS
)


NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_TYPE = (
    NOTEBOOK_06_PSYCHOLOGICAL_PATH.get(
        "checkpoint_type"
    )
)


NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_DRIVE_FILE_ID = (
    NOTEBOOK_06_PSYCHOLOGICAL_PATH.get(
        "checkpoint_drive_file_id"
    )
)


NOTEBOOK_06_PSYCHOLOGICAL_METADATA_DRIVE_FILE_ID = (
    NOTEBOOK_06_PSYCHOLOGICAL_PATH.get(
        "metadata_drive_file_id"
    )
)


NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_REPRODUCIBLE = (
    NOTEBOOK_06_PSYCHOLOGICAL_PATH.get(
        "checkpoint_reproducibility_valid"
    )
    is True
)


NOTEBOOK_06_PSYCHOLOGICAL_DEFAULT_STATE = (
    NOTEBOOK_06_PSYCHOLOGICAL_PATH.get(
        "default_future_state"
    )
)


NOTEBOOK_06_PSYCHOLOGICAL_PATH_CONTRACT_VALID = all(
    [
        NOTEBOOK_06_PSYCHOLOGICAL_PATH_TRAINED,

        NOTEBOOK_06_PSYCHOLOGICAL_TARGET_CONTRACT_VALID,

        NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_TYPE
        ==
        "controlled_experimental_training_checkpoint",

        bool(
            NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_DRIVE_FILE_ID
        ),

        bool(
            NOTEBOOK_06_PSYCHOLOGICAL_METADATA_DRIVE_FILE_ID
        ),

        NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_REPRODUCIBLE,

        NOTEBOOK_06_PSYCHOLOGICAL_DEFAULT_STATE
        ==
        "frozen",
    ]
)


if not NOTEBOOK_06_PSYCHOLOGICAL_PATH_CONTRACT_VALID:

    raise ValueError(
        "Notebook 06 psychological-path preservation contract is invalid."
    )


# =============================================================================
# Verify psychological checkpoint artefact references
# =============================================================================

NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_DRIVE_FILE = (
    NOTEBOOK_06_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_DRIVE_FILE_ID,

        fields=
            "id,name,modifiedTime,size,mimeType",
    )
    .execute()
)


NOTEBOOK_06_PSYCHOLOGICAL_METADATA_DRIVE_FILE = (
    NOTEBOOK_06_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_06_PSYCHOLOGICAL_METADATA_DRIVE_FILE_ID,

        fields=
            "id,name,modifiedTime,size,mimeType",
    )
    .execute()
)


NOTEBOOK_06_PSYCHOLOGICAL_ARTEFACTS_AVAILABLE = all(
    [
        bool(
            NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_DRIVE_FILE.get(
                "id"
            )
        ),

        bool(
            NOTEBOOK_06_PSYCHOLOGICAL_METADATA_DRIVE_FILE.get(
                "id"
            )
        ),
    ]
)


if not NOTEBOOK_06_PSYCHOLOGICAL_ARTEFACTS_AVAILABLE:

    raise ValueError(
        "Notebook 06 psychological-path persisted artefacts "
        "are unavailable."
    )


# =============================================================================
# Notebook 03 supervision reference
# =============================================================================

NOTEBOOK_06_NOTEBOOK_03_SUPERVISION = (
    NOTEBOOK_06_HANDOVER.get(
        "notebook_03_supervision",
        {},
    )
)


NOTEBOOK_06_NOTEBOOK_03_ACCEPTED_RECORD_COUNT = int(
    NOTEBOOK_06_NOTEBOOK_03_SUPERVISION.get(
        "accepted_record_count",
        0,
    )
)


NOTEBOOK_06_NOTEBOOK_03_ACCEPTED_FILE_ID = (
    NOTEBOOK_06_NOTEBOOK_03_SUPERVISION.get(
        "accepted_file_id"
    )
)


NOTEBOOK_06_NOTEBOOK_03_HANDOVER_FILE_ID = (
    NOTEBOOK_06_NOTEBOOK_03_SUPERVISION.get(
        "handover_file_id"
    )
)


NOTEBOOK_06_MACHINE_SUPERVISION_CANONICAL = (
    NOTEBOOK_06_NOTEBOOK_03_SUPERVISION.get(
        "canonical_machine_supervision"
    )
    is True
)


NOTEBOOK_06_HUMAN_REVIEWED_REFERENCE = (
    NOTEBOOK_06_NOTEBOOK_03_SUPERVISION.get(
        "human_reviewed_reference"
    )
    is True
)


NOTEBOOK_06_ADJUDICATED_REFERENCE = (
    NOTEBOOK_06_NOTEBOOK_03_SUPERVISION.get(
        "adjudicated_reference"
    )
    is True
)


NOTEBOOK_06_NOTEBOOK_03_BOUNDARY_VALID = all(
    [
        NOTEBOOK_06_NOTEBOOK_03_ACCEPTED_RECORD_COUNT > 0,

        NOTEBOOK_06_MACHINE_SUPERVISION_CANONICAL,

        not NOTEBOOK_06_HUMAN_REVIEWED_REFERENCE,

        not NOTEBOOK_06_ADJUDICATED_REFERENCE,
    ]
)


if not NOTEBOOK_06_NOTEBOOK_03_BOUNDARY_VALID:

    raise ValueError(
        "Notebook 06 Notebook 03 supervision boundary is invalid."
    )


# =============================================================================
# Factual starting contract
# =============================================================================

NOTEBOOK_06_FACTUAL_STARTING_CONTRACT = (
    NOTEBOOK_06_HANDOVER.get(
        "notebook_06_factual_starting_contract",
        {},
    )
)


NOTEBOOK_06_FACTOLOGICAL_COMPONENTS = tuple(
    NOTEBOOK_06_FACTUAL_STARTING_CONTRACT.get(
        "factological_components",
        [],
    )
)


NOTEBOOK_06_EXPECTED_FACTOLOGICAL_COMPONENTS = (
    "explicit_claim",
    "observation_or_event",
    "quantitative_information",
    "attribution",
    "evidence_reference",
    "certainty_statement",
    "uncertainty_statement",
    "speculation_or_prediction",
)


NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT = int(
    NOTEBOOK_06_FACTUAL_STARTING_CONTRACT.get(
        "factological_component_count",
        -1,
    )
)


NOTEBOOK_06_FACTOLOGICAL_SCHEMA_VALID = (
    NOTEBOOK_06_FACTUAL_STARTING_CONTRACT.get(
        "factological_component_schema_valid"
    )
    is True
)


NOTEBOOK_06_FACTOLOGICAL_WEIGHT_AVAILABLE = (
    NOTEBOOK_06_FACTUAL_STARTING_CONTRACT.get(
        "factological_weight_available"
    )
    is True
)


NOTEBOOK_06_FACTOLOGICAL_WEIGHT_AVAILABLE_RECORDS = int(
    NOTEBOOK_06_FACTUAL_STARTING_CONTRACT.get(
        "factological_weight_available_records",
        0,
    )
)


NOTEBOOK_06_FACTOLOGICAL_WEIGHT_AUTO_MAPPED = (
    NOTEBOOK_06_FACTUAL_STARTING_CONTRACT.get(
        "factological_weight_auto_mapped"
    )
    is True
)


NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED = (
    NOTEBOOK_06_FACTUAL_STARTING_CONTRACT.get(
        "factual_supervision_mapping_resolved"
    )
    is True
)


NOTEBOOK_06_FACTUAL_MAPPING_REQUIRED = (
    NOTEBOOK_06_FACTUAL_STARTING_CONTRACT.get(
        "factual_supervision_mapping_required"
    )
    is True
)


NOTEBOOK_06_PARTIAL_FACTUAL_SUPERVISION_ALLOWED = (
    NOTEBOOK_06_FACTUAL_STARTING_CONTRACT.get(
        "partial_supervision_allowed"
    )
    is True
)


NOTEBOOK_06_UNRESOLVED_DIMENSIONS_MAY_BE_FABRICATED = (
    NOTEBOOK_06_FACTUAL_STARTING_CONTRACT.get(
        "unresolved_dimensions_may_be_fabricated"
    )
    is True
)


NOTEBOOK_06_FACTUAL_OPTIMISATION_ALLOWED_BEFORE_MAPPING = (
    NOTEBOOK_06_FACTUAL_STARTING_CONTRACT.get(
        "optimisation_may_begin_before_mapping"
    )
    is True
)


NOTEBOOK_06_FACTUAL_STARTING_CONTRACT_VALID = all(
    [
        NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM
        == 10,

        NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT
        == 8,

        NOTEBOOK_06_FACTOLOGICAL_COMPONENTS
        ==
        NOTEBOOK_06_EXPECTED_FACTOLOGICAL_COMPONENTS,

        NOTEBOOK_06_FACTOLOGICAL_SCHEMA_VALID,

        not NOTEBOOK_06_FACTOLOGICAL_WEIGHT_AUTO_MAPPED,

        not NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED,

        NOTEBOOK_06_FACTUAL_MAPPING_REQUIRED,

        NOTEBOOK_06_PARTIAL_FACTUAL_SUPERVISION_ALLOWED,

        not NOTEBOOK_06_UNRESOLVED_DIMENSIONS_MAY_BE_FABRICATED,

        not NOTEBOOK_06_FACTUAL_OPTIMISATION_ALLOWED_BEFORE_MAPPING,
    ]
)


if not NOTEBOOK_06_FACTUAL_STARTING_CONTRACT_VALID:

    raise ValueError(
        "Notebook 06 factual starting contract is invalid."
    )


# =============================================================================
# Default parameter policy
# =============================================================================

NOTEBOOK_06_DEFAULT_PARAMETER_POLICY = (
    NOTEBOOK_06_HANDOVER.get(
        "notebook_06_default_parameter_policy",
        {},
    )
)


NOTEBOOK_06_EXPECTED_DEFAULT_PARAMETER_POLICY = {
    "contextual_encoder":
        "frozen",

    "backbone":
        "frozen",

    "global_confluent_path":
        "frozen",

    "psychological_head":
        "frozen",

    "factual_head":
        "not_activated_until_supervision_mapping_is_resolved",

    "social_head":
        "frozen",

    "transformative_mechanisms":
        "frozen",

    "TW_F_TW_P_TW_S":
        "frozen",

    "H_F_H_P_H_S":
        "frozen",

    "group_conditioned_paths":
        "inactive_and_frozen",
}


NOTEBOOK_06_DEFAULT_PARAMETER_POLICY_VALID = (
    NOTEBOOK_06_DEFAULT_PARAMETER_POLICY
    ==
    NOTEBOOK_06_EXPECTED_DEFAULT_PARAMETER_POLICY
)


if not NOTEBOOK_06_DEFAULT_PARAMETER_POLICY_VALID:

    raise ValueError(
        "Notebook 06 default parameter policy does not match "
        "the persisted Notebook 05 handover."
    )


# =============================================================================
# Future component boundaries
# =============================================================================

NOTEBOOK_06_FUTURE_COMPONENT_BOUNDARIES = (
    NOTEBOOK_06_HANDOVER.get(
        "future_component_boundaries",
        {},
    )
)


NOTEBOOK_06_TEV_IS_ARCHITECTURAL_TRANSFORMATION = (
    NOTEBOOK_06_FUTURE_COMPONENT_BOUNDARIES.get(
        "TEV_is_architectural_psychological_transformation"
    )
    is True
)


NOTEBOOK_06_EW_IS_TW_P = (
    NOTEBOOK_06_FUTURE_COMPONENT_BOUNDARIES.get(
        "EW_is_TW_P"
    )
    is True
)


NOTEBOOK_06_TW_COLLAPSED = (
    NOTEBOOK_06_FUTURE_COMPONENT_BOUNDARIES.get(
        "TW_F_TW_P_TW_S_collapsed"
    )
    is True
)


NOTEBOOK_06_RECURRENT_STATES_COLLAPSED = (
    NOTEBOOK_06_FUTURE_COMPONENT_BOUNDARIES.get(
        "H_F_H_P_H_S_collapsed"
    )
    is True
)


NOTEBOOK_06_FUTURE_COMPONENT_BOUNDARY_VALID = all(
    [
        not NOTEBOOK_06_TEV_IS_ARCHITECTURAL_TRANSFORMATION,
        not NOTEBOOK_06_EW_IS_TW_P,
        not NOTEBOOK_06_TW_COLLAPSED,
        not NOTEBOOK_06_RECURRENT_STATES_COLLAPSED,
    ]
)


if not NOTEBOOK_06_FUTURE_COMPONENT_BOUNDARY_VALID:

    raise ValueError(
        "Notebook 06 future component boundary is invalid."
    )


# =============================================================================
# Group-conditioned path policy
# =============================================================================

NOTEBOOK_06_GROUP_POLICY = (
    NOTEBOOK_06_HANDOVER.get(
        "group_conditioning_version_1_policy",
        {},
    )
)


NOTEBOOK_06_GROUP_DEFERRED_TO_NOTEBOOK = (
    str(
        NOTEBOOK_06_GROUP_POLICY.get(
            "deferred_to_notebook"
        )
    )
)


NOTEBOOK_06_GROUP_GLOBAL_PATH_REQUIRED = (
    NOTEBOOK_06_GROUP_POLICY.get(
        "global_path_remains_required"
    )
    is True
)


NOTEBOOK_06_GROUP_PATH_REMAINS_OPTIONAL = (
    NOTEBOOK_06_GROUP_POLICY.get(
        "group_path_remains_optional"
    )
    is True
)


NOTEBOOK_06_FABRICATED_GROUPS_ALLOWED = (
    NOTEBOOK_06_GROUP_POLICY.get(
        "fabricated_groups_allowed"
    )
    is True
)


NOTEBOOK_06_PREDICTED_GROUPS_ARE_GROUND_TRUTH = (
    NOTEBOOK_06_GROUP_POLICY.get(
        "predicted_groups_automatically_ground_truth"
    )
    is True
)


NOTEBOOK_06_GROUP_POLICY_VALID = all(
    [
        NOTEBOOK_06_GROUP_DEFERRED_TO_NOTEBOOK
        == "10",

        NOTEBOOK_06_GROUP_GLOBAL_PATH_REQUIRED,

        NOTEBOOK_06_GROUP_PATH_REMAINS_OPTIONAL,

        not NOTEBOOK_06_FABRICATED_GROUPS_ALLOWED,

        not NOTEBOOK_06_PREDICTED_GROUPS_ARE_GROUND_TRUTH,
    ]
)


if not NOTEBOOK_06_GROUP_POLICY_VALID:

    raise ValueError(
        "Notebook 06 group-conditioned-path policy is invalid."
    )


# =============================================================================
# Causal contract
# =============================================================================

NOTEBOOK_06_CAUSAL_CONTRACT = (
    NOTEBOOK_06_HANDOVER.get(
        "causal_contract",
        {},
    )
)


NOTEBOOK_06_CAUSAL_PROCESSING = (
    NOTEBOOK_06_CAUSAL_CONTRACT.get(
        "causal_processing"
    )
    is True
)


NOTEBOOK_06_FUTURE_CONTEXT_ALLOWED = (
    NOTEBOOK_06_CAUSAL_CONTRACT.get(
        "future_context_allowed"
    )
    is True
)


NOTEBOOK_06_ARTICLE_BOUNDARY_RESET = (
    NOTEBOOK_06_CAUSAL_CONTRACT.get(
        "article_boundary_state_reset"
    )
    is True
)


NOTEBOOK_06_CROSS_ARTICLE_STATE_CARRY = (
    NOTEBOOK_06_CAUSAL_CONTRACT.get(
        "cross_article_state_carry"
    )
    is True
)


NOTEBOOK_06_WITHIN_ARTICLE_ORDER_REQUIRED = (
    NOTEBOOK_06_CAUSAL_CONTRACT.get(
        "within_article_order_required"
    )
    is True
)


NOTEBOOK_06_CAUSAL_CONTRACT_VALID = all(
    [
        NOTEBOOK_06_CAUSAL_PROCESSING,
        not NOTEBOOK_06_FUTURE_CONTEXT_ALLOWED,
        NOTEBOOK_06_ARTICLE_BOUNDARY_RESET,
        not NOTEBOOK_06_CROSS_ARTICLE_STATE_CARRY,
        NOTEBOOK_06_WITHIN_ARTICLE_ORDER_REQUIRED,
    ]
)


if not NOTEBOOK_06_CAUSAL_CONTRACT_VALID:

    raise ValueError(
        "Notebook 06 causal handover contract is invalid."
    )


# =============================================================================
# Masking contract
# =============================================================================

NOTEBOOK_06_MASKING_CONTRACT = (
    NOTEBOOK_06_HANDOVER.get(
        "masking_contract",
        {},
    )
)


NOTEBOOK_06_MASK_AWARE_SUPERVISION = (
    NOTEBOOK_06_MASKING_CONTRACT.get(
        "mask_aware_supervision"
    )
    is True
)


NOTEBOOK_06_MISSING_EQUALS_ZERO = (
    NOTEBOOK_06_MASKING_CONTRACT.get(
        "missing_equals_zero"
    )
    is True
)


NOTEBOOK_06_MISSING_EQUALS_NEGATIVE = (
    NOTEBOOK_06_MASKING_CONTRACT.get(
        "missing_equals_negative"
    )
    is True
)


NOTEBOOK_06_UNAVAILABLE_ENTERS_LOSS = (
    NOTEBOOK_06_MASKING_CONTRACT.get(
        "unavailable_enters_loss"
    )
    is True
)


NOTEBOOK_06_PARTIAL_SUPERVISION_ALLOWED = (
    NOTEBOOK_06_MASKING_CONTRACT.get(
        "partial_supervision_allowed"
    )
    is True
)


NOTEBOOK_06_MASKING_CONTRACT_VALID = all(
    [
        NOTEBOOK_06_MASK_AWARE_SUPERVISION,
        not NOTEBOOK_06_MISSING_EQUALS_ZERO,
        not NOTEBOOK_06_MISSING_EQUALS_NEGATIVE,
        not NOTEBOOK_06_UNAVAILABLE_ENTERS_LOSS,
        NOTEBOOK_06_PARTIAL_SUPERVISION_ALLOWED,
    ]
)


if not NOTEBOOK_06_MASKING_CONTRACT_VALID:

    raise ValueError(
        "Notebook 06 masking handover contract is invalid."
    )


# =============================================================================
# Methodological boundary
# =============================================================================

NOTEBOOK_06_METHOD_BOUNDARY = (
    NOTEBOOK_06_HANDOVER.get(
        "methodological_boundary",
        {},
    )
)


NOTEBOOK_06_SOURCE_PSYCHOLOGICAL_COMPLETE = (
    NOTEBOOK_06_METHOD_BOUNDARY.get(
        "notebook_05_psychological_path_complete"
    )
    is True
)


NOTEBOOK_06_FULL_TRAINING_COVERAGE = (
    NOTEBOOK_06_METHOD_BOUNDARY.get(
        "full_training_coverage"
    )
    is True
)


NOTEBOOK_06_GENERALISATION_VALIDATED = (
    NOTEBOOK_06_METHOD_BOUNDARY.get(
        "generalisation_validated"
    )
    is True
)


NOTEBOOK_06_EMPIRICAL_VALIDITY = (
    NOTEBOOK_06_METHOD_BOUNDARY.get(
        "empirical_validity"
    )
    is True
)


NOTEBOOK_06_FACTUAL_HEAD_ALREADY_TRAINED = (
    NOTEBOOK_06_METHOD_BOUNDARY.get(
        "factual_head_trained"
    )
    is True
)


NOTEBOOK_06_SOCIAL_HEAD_ALREADY_TRAINED = (
    NOTEBOOK_06_METHOD_BOUNDARY.get(
        "social_head_trained"
    )
    is True
)


NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ALREADY_TRAINED = (
    NOTEBOOK_06_METHOD_BOUNDARY.get(
        "transformative_mechanisms_trained"
    )
    is True
)


NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ALREADY_TRAINED = (
    NOTEBOOK_06_METHOD_BOUNDARY.get(
        "transformative_weights_trained"
    )
    is True
)


NOTEBOOK_06_RECURRENT_MECHANISMS_ALREADY_TRAINED = (
    NOTEBOOK_06_METHOD_BOUNDARY.get(
        "recurrent_mechanisms_trained"
    )
    is True
)


NOTEBOOK_06_GROUP_PATH_ALREADY_TRAINED = (
    NOTEBOOK_06_METHOD_BOUNDARY.get(
        "group_conditioned_path_trained"
    )
    is True
)


NOTEBOOK_06_METHOD_BOUNDARY_VALID = all(
    [
        NOTEBOOK_06_SOURCE_PSYCHOLOGICAL_COMPLETE,

        not NOTEBOOK_06_FULL_TRAINING_COVERAGE,

        not NOTEBOOK_06_GENERALISATION_VALIDATED,

        not NOTEBOOK_06_EMPIRICAL_VALIDITY,

        not NOTEBOOK_06_FACTUAL_HEAD_ALREADY_TRAINED,

        not NOTEBOOK_06_SOCIAL_HEAD_ALREADY_TRAINED,

        not NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ALREADY_TRAINED,

        not NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ALREADY_TRAINED,

        not NOTEBOOK_06_RECURRENT_MECHANISMS_ALREADY_TRAINED,

        not NOTEBOOK_06_GROUP_PATH_ALREADY_TRAINED,
    ]
)


if not NOTEBOOK_06_METHOD_BOUNDARY_VALID:

    raise ValueError(
        "Notebook 06 methodological starting boundary is invalid."
    )


# =============================================================================
# Block 1 execution boundary
# =============================================================================

NOTEBOOK_06_FACTUAL_MAPPING_PERFORMED = False

NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED = False

NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED = False

NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED = False

NOTEBOOK_06_FACTUAL_LOSS_CALCULATED = False

NOTEBOOK_06_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_06_SOCIAL_SUPERVISION_CONSTRUCTED = False

NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ACTIVATED = False

NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ACTIVATED = False

NOTEBOOK_06_RECURRENT_STATES_ACTIVATED = False

NOTEBOOK_06_GROUPS_CONSTRUCTED = False

NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Factual-path readiness state
# =============================================================================

NOTEBOOK_06_HANDOVER_VALID = all(
    [
        NOTEBOOK_06_HANDOVER_TYPE_VALID,
        NOTEBOOK_06_HANDOVER_VERSION_VALID,
        NOTEBOOK_06_HANDOVER_SOURCE_VALID,
        NOTEBOOK_06_HANDOVER_TARGET_VALID,
        NOTEBOOK_06_NOTEBOOK_05_COMPLETE,
        NOTEBOOK_06_PSYCHOLOGICAL_PATH_COMPLETE,
        NOTEBOOK_06_ARCHITECTURE_COMPLETE,
        NOTEBOOK_06_CONTROLLED_PIPELINE_COMPLETE,
        NOTEBOOK_06_PROJECT_CORRECTLY_REMAINS_OPEN,
        NOTEBOOK_06_REMAINING_ROADMAP_VALID,
        NOTEBOOK_06_ARCHITECTURE_CONTRACT_VALID,
        NOTEBOOK_06_CONTEXTUAL_REPRESENTATION_CONTRACT_VALID,
        NOTEBOOK_06_REPRESENTATION_ARTEFACT_AVAILABLE,
        NOTEBOOK_06_CANONICAL_IDENTITY_VALID,
        NOTEBOOK_06_PSYCHOLOGICAL_PATH_CONTRACT_VALID,
        NOTEBOOK_06_PSYCHOLOGICAL_ARTEFACTS_AVAILABLE,
        NOTEBOOK_06_NOTEBOOK_03_BOUNDARY_VALID,
        NOTEBOOK_06_FACTUAL_STARTING_CONTRACT_VALID,
        NOTEBOOK_06_DEFAULT_PARAMETER_POLICY_VALID,
        NOTEBOOK_06_FUTURE_COMPONENT_BOUNDARY_VALID,
        NOTEBOOK_06_GROUP_POLICY_VALID,
        NOTEBOOK_06_CAUSAL_CONTRACT_VALID,
        NOTEBOOK_06_MASKING_CONTRACT_VALID,
        NOTEBOOK_06_METHOD_BOUNDARY_VALID,
    ]
)


NOTEBOOK_06_READY_FOR_FACTUAL_MAPPING = (
    NOTEBOOK_06_HANDOVER_VALID
    and NOTEBOOK_06_FACTUAL_MAPPING_REQUIRED
    and not NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED
)


NOTEBOOK_06_FACTUAL_OPTIMISATION_READY = False


# =============================================================================
# Final Block 1 validation
# =============================================================================

NOTEBOOK_06_BLOCK_1_ERRORS = []


if not NOTEBOOK_06_HANDOVER_VALID:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "notebook_05_handover_invalid"
    )


if not NOTEBOOK_06_READY_FOR_FACTUAL_MAPPING:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "factual_mapping_not_ready"
    )


if NOTEBOOK_06_FACTUAL_OPTIMISATION_READY:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "factual_optimisation_incorrectly_marked_ready"
    )


if NOTEBOOK_06_FACTUAL_MAPPING_PERFORMED:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "factual_mapping_incorrectly_performed"
    )


if NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "factual_objectives_incorrectly_activated"
    )


if NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "factual_optimizer_incorrectly_created"
    )


if NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "factual_forward_pass_incorrectly_executed"
    )


if NOTEBOOK_06_FACTUAL_LOSS_CALCULATED:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "factual_loss_incorrectly_calculated"
    )


if NOTEBOOK_06_BACKWARD_PASS_EXECUTED:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "backward_pass_incorrectly_executed"
    )


if NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "parameter_update_incorrectly_executed"
    )


if NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "factual_training_incorrectly_executed"
    )


if NOTEBOOK_06_GROUPS_CONSTRUCTED:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "groups_incorrectly_constructed"
    )


if NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "held_out_evaluation_incorrectly_executed"
    )


if NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED:

    NOTEBOOK_06_BLOCK_1_ERRORS.append(
        "empirical_validity_incorrectly_asserted"
    )


NOTEBOOK_06_BLOCK_1_VALID = (
    len(
        NOTEBOOK_06_BLOCK_1_ERRORS
    )
    == 0
)


if not NOTEBOOK_06_BLOCK_1_VALID:

    raise RuntimeError(
        "Notebook 06 Block 1 initialisation and handover audit failed. "
        f"Errors: {NOTEBOOK_06_BLOCK_1_ERRORS}"
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_06_INITIALISED = True

NOTEBOOK_06_HANDOVER_LOADED_FROM_DRIVE = True

NOTEBOOK_06_BLOCK_1_COMPLETE = True


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_06_BLOCK_1_SUMMARY = {
    "block":
        NOTEBOOK_06_BLOCK_1,

    "block_name":
        NOTEBOOK_06_BLOCK_1_NAME,

    "version":
        NOTEBOOK_06_BLOCK_1_VERSION,

    "executed_at_utc":
        BLOCK_1_EXECUTED_AT_UTC,

    "handover_drive_file_id":
        NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID,

    "handover_loaded":
        NOTEBOOK_06_HANDOVER_LOADED_FROM_DRIVE,

    "handover_valid":
        NOTEBOOK_06_HANDOVER_VALID,

    "representation_artifact_available":
        NOTEBOOK_06_REPRESENTATION_ARTEFACT_AVAILABLE,

    "psychological_artifacts_available":
        NOTEBOOK_06_PSYCHOLOGICAL_ARTEFACTS_AVAILABLE,

    "canonical_identity_valid":
        NOTEBOOK_06_CANONICAL_IDENTITY_VALID,

    "factual_architectural_dimension":
        NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM,

    "factological_component_count":
        NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT,

    "factological_weight_available":
        NOTEBOOK_06_FACTOLOGICAL_WEIGHT_AVAILABLE,

    "factual_mapping_resolved":
        NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED,

    "factual_mapping_required":
        NOTEBOOK_06_FACTUAL_MAPPING_REQUIRED,

    "ready_for_factual_mapping":
        NOTEBOOK_06_READY_FOR_FACTUAL_MAPPING,

    "factual_optimisation_ready":
        NOTEBOOK_06_FACTUAL_OPTIMISATION_READY,

    "psychological_path_frozen":
        (
            NOTEBOOK_06_PSYCHOLOGICAL_DEFAULT_STATE
            == "frozen"
        ),

    "grouping_deferred_to_notebook":
        NOTEBOOK_06_GROUP_DEFERRED_TO_NOTEBOOK,

    "empirical_validity":
        NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_06_BLOCK_1_VALID,

    "block_complete":
        NOTEBOOK_06_BLOCK_1_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 06, Block 1: "
    "Initialisation and Notebook 05 Handover Validation"
)

print("=" * 72)

print(
    f"Notebook                     : "
    f"{NOTEBOOK_06}"
)

print(
    f"Notebook version             : "
    f"{NOTEBOOK_06_VERSION}"
)

print(
    f"Block                        : "
    f"{NOTEBOOK_06_BLOCK_1}"
)

print(
    f"Block version                : "
    f"{NOTEBOOK_06_BLOCK_1_VERSION}"
)

print(
    f"Project random seed          : "
    f"{PROJECT_RANDOM_SEED}"
)


print("-" * 72)

print(
    "Google authentication"
)

print(
    f"Colab authenticated          : "
    f"{NOTEBOOK_06_COLAB_AUTHENTICATED}"
)

print(
    f"Drive service initialised    : "
    f"{NOTEBOOK_06_DRIVE_SERVICE_INITIALISED}"
)


print("-" * 72)

print(
    "Persistent Notebook 05 handover"
)

print(
    f"Handover filename            : "
    f"{NOTEBOOK_05_TO_06_HANDOVER_FILENAME}"
)

print(
    f"Drive file ID                : "
    f"{NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID}"
)

print(
    f"Drive file modified          : "
    f"{NOTEBOOK_06_HANDOVER_DRIVE_FILE.get('modifiedTime')}"
)

print(
    f"Handover located             : "
    f"{NOTEBOOK_06_HANDOVER_LOCATED}"
)

print(
    f"Handover downloaded          : "
    f"{NOTEBOOK_06_HANDOVER_DOWNLOADED}"
)

print(
    f"Local audit copy             : "
    f"{NOTEBOOK_06_LOCAL_HANDOVER_COPY_CREATED}"
)

print(
    f"JSON parsed                  : "
    f"{NOTEBOOK_06_HANDOVER_JSON_PARSED}"
)

print(
    f"Handover valid               : "
    f"{NOTEBOOK_06_HANDOVER_VALID}"
)


print("-" * 72)

print(
    "Notebook 05 source state"
)

print(
    f"Notebook 05 complete         : "
    f"{NOTEBOOK_06_NOTEBOOK_05_COMPLETE}"
)

print(
    f"Psychological path complete  : "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_PATH_COMPLETE}"
)

print(
    f"Architecture complete        : "
    f"{NOTEBOOK_06_ARCHITECTURE_COMPLETE}"
)

print(
    f"Controlled pipeline complete : "
    f"{NOTEBOOK_06_CONTROLLED_PIPELINE_COMPLETE}"
)

print(
    f"Full project complete        : "
    f"{NOTEBOOK_06_FULL_PROJECT_COMPLETE}"
)


print("-" * 72)

print(
    "Architecture contract"
)

print(
    f"Representation level         : "
    f"{NOTEBOOK_06_REPRESENTATION_LEVEL}"
)

print(
    f"Textual representation dim.  : "
    f"{NOTEBOOK_06_TEXTUAL_REPRESENTATION_DIM}"
)

print(
    f"Backbone interface dim.      : "
    f"{NOTEBOOK_06_BACKBONE_INTERFACE_DIM}"
)

print(
    f"Confluent hidden dim.        : "
    f"{NOTEBOOK_06_CONFLUENT_HIDDEN_DIM}"
)

print(
    f"Factual representation dim.  : "
    f"{NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM}"
)

print(
    f"Psychological repr. dim.     : "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_ARCHITECTURAL_DIM}"
)

print(
    f"Global path required         : "
    f"{NOTEBOOK_06_GLOBAL_PATH_REQUIRED}"
)

print(
    f"Group path optional          : "
    f"{NOTEBOOK_06_GROUP_PATH_OPTIONAL}"
)


print("-" * 72)

print(
    "Contextual representation"
)

print(
    f"Encoder provider             : "
    f"{NOTEBOOK_06_ENCODER_PROVIDER}"
)

print(
    f"Encoder model                : "
    f"{NOTEBOOK_06_ENCODER_MODEL_ID}"
)

print(
    f"Representation dimension     : "
    f"{NOTEBOOK_06_CONTEXTUAL_REPRESENTATION_DIM}"
)

print(
    f"Encoder frozen               : "
    f"{NOTEBOOK_06_CONTEXTUAL_ENCODER_FROZEN}"
)

print(
    f"Representation artefact      : "
    f"{NOTEBOOK_06_REPRESENTATION_FILENAME}"
)

print(
    f"Representation Drive file ID : "
    f"{NOTEBOOK_06_REPRESENTATION_DRIVE_FILE_ID}"
)

print(
    f"Representation available     : "
    f"{NOTEBOOK_06_REPRESENTATION_ARTEFACT_AVAILABLE}"
)


print("-" * 72)

print(
    "Canonical identity"
)

print(
    f"Articles                     : "
    f"{NOTEBOOK_06_ARTICLE_COUNT}"
)

print(
    f"Sentences                    : "
    f"{NOTEBOOK_06_SENTENCE_COUNT}"
)

print(
    f"Sentence IDs present         : "
    f"{NOTEBOOK_06_SENTENCE_IDS_PRESENT}"
)

print(
    f"Sentence IDs unique          : "
    f"{NOTEBOOK_06_RUNTIME_SENTENCE_IDS_UNIQUE}"
)

print(
    f"Identity contract valid      : "
    f"{NOTEBOOK_06_CANONICAL_IDENTITY_VALID}"
)


print("-" * 72)

print(
    "Completed psychological path"
)

print(
    f"Psychological path trained   : "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_PATH_TRAINED}"
)

print(
    f"Targets                      : "
    f"{list(NOTEBOOK_06_PSYCHOLOGICAL_ACTIVE_TARGETS)}"
)

print(
    f"Checkpoint type              : "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_TYPE}"
)

print(
    f"Checkpoint reproducible      : "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_REPRODUCIBLE}"
)

print(
    f"Psychological path state     : "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_DEFAULT_STATE}"
)

print(
    f"Persisted artefacts available: "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_ARTEFACTS_AVAILABLE}"
)


print("-" * 72)

print(
    "Notebook 06 factual starting contract"
)

print(
    f"Factual architectural dim.   : "
    f"{NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM}"
)

print(
    f"Factological components      : "
    f"{NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT}"
)

print(
    f"Component schema valid       : "
    f"{NOTEBOOK_06_FACTOLOGICAL_SCHEMA_VALID}"
)

print(
    f"Factological weight avail.   : "
    f"{NOTEBOOK_06_FACTOLOGICAL_WEIGHT_AVAILABLE}"
)

print(
    f"Weight available records     : "
    f"{NOTEBOOK_06_FACTOLOGICAL_WEIGHT_AVAILABLE_RECORDS}"
)

print(
    f"Weight auto-mapped           : "
    f"{NOTEBOOK_06_FACTOLOGICAL_WEIGHT_AUTO_MAPPED}"
)

print(
    f"Factual mapping resolved     : "
    f"{NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED}"
)

print(
    f"Mapping required             : "
    f"{NOTEBOOK_06_FACTUAL_MAPPING_REQUIRED}"
)

print(
    f"Partial supervision allowed  : "
    f"{NOTEBOOK_06_PARTIAL_FACTUAL_SUPERVISION_ALLOWED}"
)

print(
    f"Fabricated dimensions allowed: "
    f"{NOTEBOOK_06_UNRESOLVED_DIMENSIONS_MAY_BE_FABRICATED}"
)

print(
    f"Optimisation ready           : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMISATION_READY}"
)


print("-" * 72)

print(
    "Remaining Version 1 roadmap"
)


for roadmap_record in NOTEBOOK_06_REMAINING_ROADMAP:

    print(
        f"Notebook {str(roadmap_record['notebook']):<2}                : "
        f"{roadmap_record['name']}"
    )


print("-" * 72)

print(
    "Group-conditioned path policy"
)

print(
    f"Deferred to Notebook         : "
    f"{NOTEBOOK_06_GROUP_DEFERRED_TO_NOTEBOOK}"
)

print(
    f"Global path remains required : "
    f"{NOTEBOOK_06_GROUP_GLOBAL_PATH_REQUIRED}"
)

print(
    f"Group path remains optional  : "
    f"{NOTEBOOK_06_GROUP_PATH_REMAINS_OPTIONAL}"
)

print(
    f"Fabricated groups allowed    : "
    f"{NOTEBOOK_06_FABRICATED_GROUPS_ALLOWED}"
)


print("-" * 72)

print(
    "Causal and masking boundary"
)

print(
    f"Causal processing            : "
    f"{NOTEBOOK_06_CAUSAL_PROCESSING}"
)

print(
    f"Future context allowed       : "
    f"{NOTEBOOK_06_FUTURE_CONTEXT_ALLOWED}"
)

print(
    f"Article-boundary reset       : "
    f"{NOTEBOOK_06_ARTICLE_BOUNDARY_RESET}"
)

print(
    f"Cross-article carry          : "
    f"{NOTEBOOK_06_CROSS_ARTICLE_STATE_CARRY}"
)

print(
    f"Mask-aware supervision       : "
    f"{NOTEBOOK_06_MASK_AWARE_SUPERVISION}"
)

print(
    f"Missing = zero               : "
    f"{NOTEBOOK_06_MISSING_EQUALS_ZERO}"
)

print(
    f"Missing = negative           : "
    f"{NOTEBOOK_06_MISSING_EQUALS_NEGATIVE}"
)

print(
    f"Unavailable enters loss      : "
    f"{NOTEBOOK_06_UNAVAILABLE_ENTERS_LOSS}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Factual mapping performed    : "
    f"{NOTEBOOK_06_FACTUAL_MAPPING_PERFORMED}"
)

print(
    f"Factual objectives activated : "
    f"{NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED}"
)

print(
    f"Factual optimiser created    : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED}"
)

print(
    f"Factual forward pass         : "
    f"{NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED}"
)

print(
    f"Factual loss calculated      : "
    f"{NOTEBOOK_06_FACTUAL_LOSS_CALCULATED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_06_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Factual training executed    : "
    f"{NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Groups constructed           : "
    f"{NOTEBOOK_06_GROUPS_CONSTRUCTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED}"
)


print("-" * 72)

print(
    "Readiness"
)

print(
    f"Notebook 06 initialised      : "
    f"{NOTEBOOK_06_INITIALISED}"
)

print(
    f"Handover loaded from Drive   : "
    f"{NOTEBOOK_06_HANDOVER_LOADED_FROM_DRIVE}"
)

print(
    f"Handover validated           : "
    f"{NOTEBOOK_06_HANDOVER_VALID}"
)

print(
    f"Ready for factual mapping    : "
    f"{NOTEBOOK_06_READY_FOR_FACTUAL_MAPPING}"
)

print(
    f"Factual optimisation ready   : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMISATION_READY}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_06_BLOCK_1_VALID}"
)

print(
    f"Block 1 complete             : "
    f"{NOTEBOOK_06_BLOCK_1_COMPLETE}"
)


print("=" * 72)


print(
    "Notebook 06 initialised successfully from the persistent "
    "Notebook 05 handover."
)

print(
    "The Notebook 05 psychological path remains complete, persisted, "
    "reproducible and frozen by default."
)

print(
    "The persisted 768-dimensional contextual sentence representation "
    "contract remains available and aligned to canonical sentence identity."
)

print(
    "The factual architecture remains ten-dimensional while the canonical "
    "Notebook 03 supervision exposes eight explicit factological components."
)

print(
    "Factological weight remains available as a separate supervision signal "
    "and has not been automatically mapped into the factual representation."
)

print(
    "No unresolved factual dimension has been fabricated."
)

print(
    "Factual optimisation remains blocked until the supervision mapping "
    "and target contract are explicitly resolved."
)

print(
    "The social path, transformative mechanisms, Transformative Weights, "
    "recurrent states and group-conditioned path remain outside the current "
    "optimisation scope."
)

print(
    "Group-conditioned processing remains optional and deferred to "
    "Notebook 10."
)

print(
    "No factual target mapping, objective activation, optimiser creation, "
    "loss calculation, backward pass, parameter update, training, grouping "
    "or empirical evaluation has been performed by Block 1."
)

print(
    "Block 2 may proceed to Factual Supervision Mapping and "
    "Target-Contract Audit."
)

print("=" * 72)

WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.
WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.

========================================================================
Media AI — Notebook 06, Block 1: Initialisation and Notebook 05 Handover Validation
========================================================================
Notebook                     : 06_factual_path
Notebook version             : 1.0
Block                        : 1
Block version                : 1.0
Project random seed          : 42
------------------------------------------------------------------------
Google authentication
Colab authenticated          : True
Drive service initialised    : True
------------------------------------------------------------------------
Persistent Notebook 05 handover
Handover filename            : notebook_05_to_06_handover.json
Drive file ID                : 1N45TzoAvmYBrXmkmIbtDtqDov3OD7O-h
Drive file modified          : 2026-08-24T20:07:45.619Z
Handover located             : True
Handover downloaded          : True
Local audit copy             : True
JSON parsed                  : True
Handover valid               : True
------------------------------------------------------------------------
Notebook 05 source state
Notebook 05 complete         : True
Psychological path complete  : True
Architecture complete        : True
Controlled pipeline complete : True
Full project complete        : False
------------------------------------------------------------------------
Architecture contract
Representation level         : sentence
Textual representation dim.  : 768
Backbone interface dim.      : 768
Confluent hidden dim.        : 256
Factual representation dim.  : 10
Psychological repr. dim.     : 34
Global path required         : True
Group path optional          : True
------------------------------------------------------------------------
Contextual representation
Encoder provider             : sentence-transformers
Encoder model                : sentence-transformers/all-mpnet-base-v2
Representation dimension     : 768
Encoder frozen               : True
Representation artefact      : notebook_05_contextual_sentence_representations.json
Representation Drive file ID : 11_j_CebqBpMSDLlccGwGROr5hklTBYRm
Representation available     : True
------------------------------------------------------------------------
Canonical identity
Articles                     : 3
Sentences                    : 54
Sentence IDs present         : True
Sentence IDs unique          : True
Identity contract valid      : True
------------------------------------------------------------------------
Completed psychological path
Psychological path trained   : True
Targets                      : ['REV', 'TEV', 'IEV', 'EW']
Checkpoint type              : controlled_experimental_training_checkpoint
Checkpoint reproducible      : True
Psychological path state     : frozen
Persisted artefacts available: True
------------------------------------------------------------------------
Notebook 06 factual starting contract
Factual architectural dim.   : 10
Factological components      : 8
Component schema valid       : True
Factological weight avail.   : True
Weight available records     : 54
Weight auto-mapped           : False
Factual mapping resolved     : False
Mapping required             : True
Partial supervision allowed  : True
Fabricated dimensions allowed: False
Optimisation ready           : False
------------------------------------------------------------------------
Remaining Version 1 roadmap
Notebook 06                : Factual Path
Notebook 07                : Social Path
Notebook 08                : Transformative Mechanism
Notebook 09                : Transformative Weights and Recurrent Mechanism
Notebook 10                : Group-Conditioned Path and Final Integration
------------------------------------------------------------------------
Group-conditioned path policy
Deferred to Notebook         : 10
Global path remains required : True
Group path remains optional  : True
Fabricated groups allowed    : False
------------------------------------------------------------------------
Causal and masking boundary
Causal processing            : True
Future context allowed       : False
Article-boundary reset       : True
Cross-article carry          : False
Mask-aware supervision       : True
Missing = zero               : False
Missing = negative           : False
Unavailable enters loss      : False
------------------------------------------------------------------------
Execution boundary
Factual mapping performed    : False
Factual objectives activated : False
Factual optimiser created    : False
Factual forward pass         : False
Factual loss calculated      : False
Backward pass executed       : False
Parameter update executed    : False
Factual training executed    : False
Groups constructed           : False
Empirical validity           : False
------------------------------------------------------------------------
Readiness
Notebook 06 initialised      : True
Handover loaded from Drive   : True
Handover validated           : True
Ready for factual mapping    : True
Factual optimisation ready   : False
Block valid                  : True
Block 1 complete             : True
========================================================================
Notebook 06 initialised successfully from the persistent Notebook 05 handover.
The Notebook 05 psychological path remains complete, persisted, reproducible and frozen by default.
The persisted 768-dimensional contextual sentence representation contract remains available and aligned to canonical sentence identity.
The factual architecture remains ten-dimensional while the canonical Notebook 03 supervision exposes eight explicit factological components.
Factological weight remains available as a separate supervision signal and has not been automatically mapped into the factual representation.
No unresolved factual dimension has been fabricated.
Factual optimisation remains blocked until the supervision mapping and target contract are explicitly resolved.
The social path, transformative mechanisms, Transformative Weights, recurrent states and group-conditioned path remain outside the current optimisation scope.
Group-conditioned processing remains optional and deferred to Notebook 10.
No factual target mapping, objective activation, optimiser creation, loss calculation, backward pass, parameter update, training, grouping or empirical evaluation has been performed by Block 1.
Block 2 may proceed to Factual Supervision Mapping and Target-Contract Audit.
========================================================================

## Block 2 — Factual Supervision Mapping and Target-Contract Audit

### Purpose

This block resolves the semantic relationship between the canonical factual supervision produced by Notebook 03 and the ten-dimensional factual representation defined by the Media AI architecture.

Notebook 03 provides eight canonical factological components together with a separate `factological_weight` field.

Notebook 06 refines this source supervision into the ten-dimensional factual target space required by the architecture.

The refinement is performed explicitly and prospectively in Notebook 06. It does not modify, overwrite or retroactively reinterpret the persisted Notebook 03 canonical records.

This block establishes the factual target contract and validates whether each target element can be derived from the available canonical supervision.

No factual optimisation or parameter update is performed.

### Canonical Notebook 03 factual supervision

The persisted Notebook 03 canonical supervision remains the authoritative source annotation layer.

Its eight factological components are:

- `explicit_claim`
- `observation_or_event`
- `quantitative_information`
- `attribution`
- `evidence_reference`
- `certainty_statement`
- `uncertainty_statement`
- `speculation_or_prediction`

Notebook 03 additionally provides:

- `factological_weight`

These source fields remain unchanged.

Notebook 06 must preserve their original values, masks, provenance and canonical sentence identities.

### Ten-dimensional factual representation

Notebook 06 resolves the factual architectural representation as:

| Dimension | Factual target |
|---|---|
| `F1` | `explicit_claim` |
| `F2` | `observation_or_event` |
| `F3` | `quantitative_information` |
| `F4` | `attribution` |
| `F5` | `evidence_reference` |
| `F6` | `certainty_statement` |
| `F7` | `uncertainty_statement` |
| `F8` | `speculation` |
| `F9` | `prediction` |
| `F10` | `factological_weight` |

This mapping resolves all ten architectural factual dimensions without introducing an unrelated synthetic dimension.

The first seven dimensions preserve their corresponding Notebook 03 factological concepts directly.

`F8` and `F9` are a semantic refinement of the original combined `speculation_or_prediction` source construct.

`F10` incorporates the existing Notebook 03 `factological_weight` supervision as an explicit dimension of the factual representation.

### Directly mapped factual dimensions

The following Notebook 03 components map directly onto the factual architecture:

- `explicit_claim` → `F1`
- `observation_or_event` → `F2`
- `quantitative_information` → `F3`
- `attribution` → `F4`
- `evidence_reference` → `F5`
- `certainty_statement` → `F6`
- `uncertainty_statement` → `F7`

Their original supervision semantics must be preserved.

Missing or insufficient-evidence values remain masked.

The mapping must not convert missing supervision into numerical zero or negative evidence.

### Refinement of speculation and prediction

Notebook 03 contains the combined source construct:

`speculation_or_prediction`

Notebook 06 refines this construct into two architecturally distinct dimensions:

- `F8` — `speculation`
- `F9` — `prediction`

For the factual target contract:

**Speculation** represents a proposition framed as possible, hypothetical, conjectural or insufficiently established without requiring that the proposition concern a future event.

**Prediction** represents a proposition that forecasts, anticipates or asserts a possible future event, state or outcome.

The distinction is semantic rather than merely numerical.

A source value for `speculation_or_prediction` must therefore not be copied automatically into both `F8` and `F9`.

### Split-resolution policy

The original `speculation_or_prediction` annotation acts as the source eligibility boundary for the refined dimensions.

Where the source component is unavailable or masked, both `speculation` and `prediction` remain unavailable.

Where the source component contains evidence, Notebook 06 may resolve the refined dimensions only from the canonical sentence text and its permitted canonical context under an explicit deterministic classification contract.

The refinement must not use future article context.

A sentence may support:

- speculation without prediction;
- prediction without broader speculation;
- both, when both meanings are independently supported;
- neither, when the original combined source signal cannot be resolved reliably into either refined construct.

The two dimensions are therefore not assumed to be mutually exclusive.

If the distinction cannot be established reliably for a particular sentence, the unresolved refined target element must remain masked rather than inferred arbitrarily.

### Refinement provenance

Every resolved `speculation` or `prediction` target must preserve provenance showing that:

- the canonical source field was `speculation_or_prediction`;
- the refined target was produced in Notebook 06;
- the original Notebook 03 annotation was not modified;
- the canonical sentence identity was preserved;
- the refinement rule used to resolve the target is identifiable.

Notebook 06 refinement must therefore remain distinguishable from original Notebook 03 machine supervision.

The resulting ten-dimensional factual target must not be represented as though Notebook 03 originally contained ten independently annotated factual dimensions.

### Factological weight mapping

Notebook 03 provides `factological_weight` independently from the eight factological components.

Notebook 06 explicitly maps this existing signal to:

`F10` — `factological_weight`

This is an architectural mapping decision introduced in Notebook 06.

It does not imply that Notebook 03 originally defined `factological_weight` as the tenth architectural factual dimension.

The persisted source value and its availability state must be preserved.

A missing `factological_weight` value must remain masked.

No default or synthetic weight may be inserted.

### Target-type contract

The factual target space contains conceptually different forms of supervision.

`F1`–`F9` represent factual-content dimensions derived from factological annotations and their Notebook 06 refinement.

`F10` represents factual weight.

The block must inspect and preserve the numerical semantics of the canonical source fields before any later loss function is selected.

The existence of a ten-dimensional target vector does not imply that every dimension must use the same loss function, activation function or numerical interpretation.

Loss semantics are therefore not established merely by completing the dimensional mapping.

### Element-level target masks

Each of the ten factual dimensions requires an independent element-level availability mask.

For each canonical sentence, the factual target contract therefore consists of:

- a ten-dimensional target vector;
- a ten-dimensional target mask;
- canonical sentence identity;
- source provenance;
- refinement provenance where applicable.

An unavailable element must have a false target mask and must not participate in a later supervised objective.

Availability in one factual dimension must not imply availability in another.

### Partial factual supervision

Partial factual supervision remains valid.

A sentence does not need all ten factual dimensions to be available in order to contribute factual supervision later.

Likewise, the factual path does not require every dimension to have identical dataset coverage.

The block must report:

- sentence-level factual supervision availability;
- element-level factual supervision availability;
- coverage for each factual dimension;
- total factual target coverage;
- coverage of the refined `speculation` dimension;
- coverage of the refined `prediction` dimension;
- coverage of `factological_weight`.

This coverage audit must occur before factual objective activation.

### Preservation of previous notebooks

Notebook 06 does not modify persisted Notebook 03, Notebook 04 or Notebook 05 artefacts.

In particular:

- Notebook 03 remains the canonical source annotation layer;
- the original `speculation_or_prediction` field remains intact;
- Notebook 04's ten-dimensional factual architectural capacity remains unchanged;
- Notebook 05 correctly remains a record of the state in which factual mapping was unresolved;
- the Notebook 05 → Notebook 06 handover remains unchanged.

The resolution performed by this block becomes a new Notebook 06 factual-path artefact and methodological decision.

### Psychological-path boundary

The completed psychological path remains frozen.

`REV`, `TEV`, `IEV` and `EW` are not used as factual target values.

`TEV` remains distinct from architectural transformation supervision.

`EW` remains distinct from `TW_P`.

No psychological target is repurposed to complete or augment the factual representation.

### Parameter and optimisation boundary

Resolving the factual target semantics does not itself train the factual head.

During this block:

- the contextual encoder remains frozen;
- the backbone remains frozen;
- the global confluent path remains frozen;
- the psychological head remains frozen;
- the factual head remains unoptimised;
- the social head remains frozen;
- transformation modules remain frozen;
- `TW_F`, `TW_P` and `TW_S` remain frozen;
- `H_F`, `H_P` and `H_S` remain frozen;
- group-conditioned paths remain inactive and frozen.

No parameter becomes trainable merely because its corresponding target has been semantically resolved.

### Execution boundary

Block 2 may:

- load the canonical factual supervision;
- inspect source value and mask semantics;
- define the ten-dimensional factual target contract;
- map the first seven direct factual components;
- resolve `speculation_or_prediction` into `speculation` and `prediction` under the explicit refinement policy;
- map `factological_weight` to `F10`;
- construct factual target vectors and masks;
- audit target coverage;
- validate provenance and canonical sentence alignment;
- persist the resolved Notebook 06 factual target contract if validation succeeds.

Block 2 must not:

- modify Notebook 03 canonical supervision;
- duplicate `speculation_or_prediction` blindly into both refined dimensions;
- fabricate unresolved target values;
- activate a factual training objective;
- select a loss merely because the target is ten-dimensional;
- create a factual optimiser;
- execute a training backward pass;
- update model parameters;
- retrain the psychological path;
- activate the social path;
- activate architectural transformations;
- activate Transformative Weights;
- activate recurrent states;
- construct data-driven groups;
- perform held-out evaluation;
- claim factual-path empirical validity.

### Block completion criterion

Block 2 is complete only when the ten-dimensional factual representation has an explicit validated semantic contract, every factual dimension has a defined provenance path, `speculation` and `prediction` have been distinguished without modifying the original combined Notebook 03 annotation, `factological_weight` has been explicitly mapped to `F10`, and independent element-level masks preserve all unresolved or unavailable supervision.

Successful completion should establish:

- factual architectural dimensionality = 10;
- factual semantic dimensions resolved = 10;
- direct Notebook 03 component mappings = 7;
- refined dimensions from `speculation_or_prediction` = 2;
- `factological_weight` architectural mappings = 1;
- fabricated factual dimensions = 0;
- original Notebook 03 records modified = false;
- factual target contract valid = true;
- factual supervision dataset constructible = true.

Successful completion of Block 2 establishes the factual supervision contract required by the next stage.

It does not by itself establish that the factual head has been trained or empirically validated.

In [3]:
# =============================================================================
# Media AI — Notebook 06
# Block 2: Factual Supervision Mapping and Target-Contract Audit
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json
import math
import re

import numpy as np
import pandas as pd

from googleapiclient.http import (
    MediaIoBaseDownload,
    MediaIoBaseUpload,
)


# =============================================================================
# Dependency checks
# =============================================================================

required_block_1_objects = [
    "NOTEBOOK_06_BLOCK_1_COMPLETE",
    "NOTEBOOK_06_BLOCK_1_VALID",
    "NOTEBOOK_06_DRIVE_SERVICE",
    "NOTEBOOK_06_HANDOVER",
    "NOTEBOOK_06_SENTENCE_IDS",
    "NOTEBOOK_06_SENTENCE_COUNT",
    "NOTEBOOK_06_ARTICLE_COUNT",
    "NOTEBOOK_06_NOTEBOOK_03_ACCEPTED_RECORD_COUNT",
    "NOTEBOOK_06_NOTEBOOK_03_ACCEPTED_FILE_ID",
    "NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM",
    "NOTEBOOK_06_FACTOLOGICAL_COMPONENTS",
    "NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT",
    "NOTEBOOK_06_FACTOLOGICAL_WEIGHT_AVAILABLE",
    "NOTEBOOK_06_FACTUAL_MAPPING_REQUIRED",
    "NOTEBOOK_06_PARTIAL_FACTUAL_SUPERVISION_ALLOWED",
    "NOTEBOOK_06_MASK_AWARE_SUPERVISION",
    "NOTEBOOK_06_MISSING_EQUALS_ZERO",
    "NOTEBOOK_06_MISSING_EQUALS_NEGATIVE",
    "NOTEBOOK_06_UNAVAILABLE_ENTERS_LOSS",
]


missing_block_1_objects = [
    object_name
    for object_name in required_block_1_objects
    if object_name not in globals()
]


if missing_block_1_objects:

    raise NameError(
        "Notebook 06 Block 1 is not initialised. "
        f"Missing: {missing_block_1_objects}"
    )


if not NOTEBOOK_06_BLOCK_1_COMPLETE:

    raise ValueError(
        "Notebook 06 Block 1 must be complete before Block 2."
    )


if not NOTEBOOK_06_BLOCK_1_VALID:

    raise ValueError(
        "Notebook 06 Block 1 must be valid before Block 2."
    )


if NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM != 10:

    raise ValueError(
        "Block 2 requires the validated ten-dimensional factual "
        "architectural representation."
    )


if NOTEBOOK_06_FACTOLOGICAL_COMPONENT_COUNT != 8:

    raise ValueError(
        "Block 2 expected eight canonical Notebook 03 "
        "factological components."
    )


if not NOTEBOOK_06_FACTUAL_MAPPING_REQUIRED:

    raise ValueError(
        "Block 1 does not indicate that factual mapping is required."
    )


# =============================================================================
# Block configuration
# =============================================================================

NOTEBOOK_06_BLOCK_2 = 2

NOTEBOOK_06_BLOCK_2_NAME = (
    "Factual Supervision Mapping and Target-Contract Audit"
)

NOTEBOOK_06_BLOCK_2_VERSION = "1.0"

NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VERSION = "1.0"

NOTEBOOK_06_FACTUAL_TARGET_FILENAME = (
    "notebook_06_factual_target_contract.json"
)

NOTEBOOK_06_FACTUAL_TARGET_DIMENSION = 10


BLOCK_2_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Execution boundary
# =============================================================================

NOTEBOOK_06_FACTUAL_TARGET_MAPPING_PERFORMED = False

NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED = False

NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED = False

NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED = False

NOTEBOOK_06_FACTUAL_LOSS_CALCULATED = False

NOTEBOOK_06_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_SOCIAL_PATH_ACTIVATED = False

NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ACTIVATED = False

NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ACTIVATED = False

NOTEBOOK_06_RECURRENT_STATES_ACTIVATED = False

NOTEBOOK_06_GROUPS_CONSTRUCTED = False

NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED = False

NOTEBOOK_06_PREVIOUS_NOTEBOOK_ARTEFACTS_MODIFIED = False


# =============================================================================
# Canonical factual source filename
# =============================================================================

NOTEBOOK_03_ACCEPTED_ANNOTATIONS_FILENAME = (
    "notebook_03_accepted_annotations.json"
)


# =============================================================================
# Resolve Notebook 03 accepted-supervision artefact
# =============================================================================

def block_2_locate_drive_file(
    drive_service,
    filename,
):
    """
    Locate the most recently modified exact-name Google Drive file.
    """

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )


    response = (
        drive_service.files()
        .list(
            q=(
                f"name = '{escaped_filename}' "
                "and trashed = false"
            ),
            spaces="drive",
            fields="files(id,name,modifiedTime,parents,size,mimeType)",
            orderBy="modifiedTime desc",
            pageSize=20,
        )
        .execute()
    )


    files = response.get(
        "files",
        [],
    )


    if not files:

        return None


    return files[0]


# -----------------------------------------------------------------------------
# Prefer explicit file ID from handover where available
# -----------------------------------------------------------------------------

BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID = (
    NOTEBOOK_06_NOTEBOOK_03_ACCEPTED_FILE_ID
)


BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE = None


if BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID:

    BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE = (
        NOTEBOOK_06_DRIVE_SERVICE.files()
        .get(
            fileId=
                BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID,
            fields=
                "id,name,modifiedTime,parents,size,mimeType",
        )
        .execute()
    )


# -----------------------------------------------------------------------------
# Fallback to exact-name Drive discovery
# -----------------------------------------------------------------------------

if BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE is None:

    BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE = (
        block_2_locate_drive_file(
            NOTEBOOK_06_DRIVE_SERVICE,
            NOTEBOOK_03_ACCEPTED_ANNOTATIONS_FILENAME,
        )
    )


if BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE is None:

    raise FileNotFoundError(
        "Notebook 03 accepted canonical supervision artefact "
        "could not be located in Google Drive."
    )


BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID = (
    BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE[
        "id"
    ]
)


BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_LOCATED = True


# =============================================================================
# Download helper
# =============================================================================

def block_2_download_drive_bytes(
    drive_service,
    file_id,
):
    """
    Download one Google Drive file and return raw bytes.
    """

    request = (
        drive_service.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Load canonical Notebook 03 supervision
# =============================================================================

BLOCK_2_NOTEBOOK_03_ACCEPTED_BYTES = (
    block_2_download_drive_bytes(
        NOTEBOOK_06_DRIVE_SERVICE,
        BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID,
    )
)


if not BLOCK_2_NOTEBOOK_03_ACCEPTED_BYTES:

    raise ValueError(
        "Notebook 03 accepted supervision artefact was empty."
    )


BLOCK_2_NOTEBOOK_03_ACCEPTED_PAYLOAD = json.loads(
    BLOCK_2_NOTEBOOK_03_ACCEPTED_BYTES.decode(
        "utf-8"
    )
)


# =============================================================================
# Resolve accepted-record list
# =============================================================================

def block_2_resolve_record_list(
    payload,
):
    """
    Resolve canonical annotation records from supported persisted
    Notebook 03 payload structures.
    """

    if isinstance(
        payload,
        list,
    ):

        return payload


    if not isinstance(
        payload,
        dict,
    ):

        raise TypeError(
            "Notebook 03 accepted supervision payload must be "
            "a list or dictionary."
        )


    candidate_keys = (
        "records",
        "accepted_annotations",
        "annotations",
        "accepted_records",
        "supervision_records",
    )


    for candidate_key in candidate_keys:

        candidate_value = payload.get(
            candidate_key
        )


        if isinstance(
            candidate_value,
            list,
        ):

            return candidate_value


    raise ValueError(
        "Could not resolve accepted supervision records from the "
        "Notebook 03 persisted payload."
    )


NOTEBOOK_06_FACTUAL_SOURCE_RECORDS = (
    block_2_resolve_record_list(
        BLOCK_2_NOTEBOOK_03_ACCEPTED_PAYLOAD
    )
)


BLOCK_2_SOURCE_RECORD_COUNT = len(
    NOTEBOOK_06_FACTUAL_SOURCE_RECORDS
)


if (
    BLOCK_2_SOURCE_RECORD_COUNT
    != NOTEBOOK_06_NOTEBOOK_03_ACCEPTED_RECORD_COUNT
):

    raise ValueError(
        "Notebook 03 persisted accepted-record count does not match "
        "the Notebook 05 → 06 handover."
    )


# =============================================================================
# Canonical sentence alignment
# =============================================================================

BLOCK_2_SOURCE_SENTENCE_IDS = []


for record_index, record in enumerate(
    NOTEBOOK_06_FACTUAL_SOURCE_RECORDS
):

    identity = record.get(
        "identity",
        {}
    )


    sentence_id = identity.get(
        "sentence_id"
    )


    if not sentence_id:

        raise ValueError(
            "Canonical Notebook 03 supervision record "
            f"{record_index} has no sentence_id."
        )


    BLOCK_2_SOURCE_SENTENCE_IDS.append(
        sentence_id
    )


BLOCK_2_SOURCE_SENTENCE_IDS_PRESENT = all(
    BLOCK_2_SOURCE_SENTENCE_IDS
)


BLOCK_2_SOURCE_SENTENCE_IDS_UNIQUE = (
    len(
        BLOCK_2_SOURCE_SENTENCE_IDS
    )
    ==
    len(
        set(
            BLOCK_2_SOURCE_SENTENCE_IDS
        )
    )
)


BLOCK_2_HANDOVER_SENTENCE_SET = set(
    NOTEBOOK_06_SENTENCE_IDS
)


BLOCK_2_SOURCE_SENTENCE_SET = set(
    BLOCK_2_SOURCE_SENTENCE_IDS
)


BLOCK_2_SENTENCE_ALIGNMENT_VALID = (
    BLOCK_2_SOURCE_SENTENCE_SET
    ==
    BLOCK_2_HANDOVER_SENTENCE_SET
)


if not BLOCK_2_SOURCE_SENTENCE_IDS_PRESENT:

    raise ValueError(
        "One or more source supervision records lack sentence IDs."
    )


if not BLOCK_2_SOURCE_SENTENCE_IDS_UNIQUE:

    raise ValueError(
        "Notebook 03 factual source sentence IDs are not unique."
    )


if not BLOCK_2_SENTENCE_ALIGNMENT_VALID:

    raise ValueError(
        "Notebook 03 factual supervision sentence identities do not "
        "align with the Notebook 06 canonical sentence contract."
    )


# =============================================================================
# Factual semantic contract
# =============================================================================

NOTEBOOK_06_FACTUAL_DIMENSION_ORDER = (
    "explicit_claim",
    "observation_or_event",
    "quantitative_information",
    "attribution",
    "evidence_reference",
    "certainty_statement",
    "uncertainty_statement",
    "speculation",
    "prediction",
    "factological_weight",
)


NOTEBOOK_06_FACTUAL_DIMENSION_IDS = (
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
)


NOTEBOOK_06_FACTUAL_DIMENSION_MAP = {
    dimension_id:
        dimension_name

    for dimension_id, dimension_name
    in zip(
        NOTEBOOK_06_FACTUAL_DIMENSION_IDS,
        NOTEBOOK_06_FACTUAL_DIMENSION_ORDER,
    )
}


NOTEBOOK_06_FACTUAL_DIMENSION_INDEX = {
    dimension_name:
        dimension_index

    for dimension_index, dimension_name
    in enumerate(
        NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
    )
}


NOTEBOOK_06_FACTUAL_DIRECT_SOURCE_MAP = {
    "explicit_claim":
        "explicit_claim",

    "observation_or_event":
        "observation_or_event",

    "quantitative_information":
        "quantitative_information",

    "attribution":
        "attribution",

    "evidence_reference":
        "evidence_reference",

    "certainty_statement":
        "certainty_statement",

    "uncertainty_statement":
        "uncertainty_statement",
}


NOTEBOOK_06_REFINED_SOURCE_FIELD = (
    "speculation_or_prediction"
)


NOTEBOOK_06_FACTOLOGICAL_WEIGHT_SOURCE_FIELD = (
    "factological_weight"
)


BLOCK_2_FACTUAL_DIMENSION_CONTRACT_VALID = all(
    [
        len(
            NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
        )
        == 10,

        len(
            NOTEBOOK_06_FACTUAL_DIMENSION_IDS
        )
        == 10,

        len(
            NOTEBOOK_06_FACTUAL_DIRECT_SOURCE_MAP
        )
        == 7,

        NOTEBOOK_06_FACTUAL_DIMENSION_ORDER[
            7
        ]
        == "speculation",

        NOTEBOOK_06_FACTUAL_DIMENSION_ORDER[
            8
        ]
        == "prediction",

        NOTEBOOK_06_FACTUAL_DIMENSION_ORDER[
            9
        ]
        == "factological_weight",
    ]
)


if not BLOCK_2_FACTUAL_DIMENSION_CONTRACT_VALID:

    raise ValueError(
        "Notebook 06 ten-dimensional factual semantic contract "
        "is invalid."
    )


# =============================================================================
# Source-value extraction
# =============================================================================

BLOCK_2_EXPLICIT_UNAVAILABLE_STATES = {
    "missing",
    "unavailable",
    "insufficient_evidence",
    "insufficient-evidence",
    "not_available",
    "not-available",
    "not_applicable",
    "not-applicable",
    "unknown",
    "unresolved",
    "not_provided",
    "not-provided",
}


def block_2_extract_numeric_value(
    source_object,
):
    """
    Extract one canonical numeric value and availability state.

    Returns:
        value
        available
        value_state

    Numerical zero remains an available observation when explicitly
    present. Missing supervision is not converted to zero.
    """

    value_state = None

    raw_value = source_object


    if isinstance(
        source_object,
        dict,
    ):

        value_state = source_object.get(
            "value_state"
        )

        raw_value = source_object.get(
            "value"
        )


    if value_state is not None:

        normalised_state = str(
            value_state
        ).strip().lower()


        if normalised_state in BLOCK_2_EXPLICIT_UNAVAILABLE_STATES:

            return (
                None,
                False,
                value_state,
            )


    if raw_value is None:

        return (
            None,
            False,
            value_state,
        )


    if isinstance(
        raw_value,
        bool,
    ):

        return (
            float(
                raw_value
            ),
            True,
            value_state,
        )


    if isinstance(
        raw_value,
        (
            int,
            float,
            np.integer,
            np.floating,
        ),
    ):

        numeric_value = float(
            raw_value
        )


        if not math.isfinite(
            numeric_value
        ):

            return (
                None,
                False,
                value_state,
            )


        return (
            numeric_value,
            True,
            value_state,
        )


    try:

        numeric_value = float(
            raw_value
        )


        if not math.isfinite(
            numeric_value
        ):

            return (
                None,
                False,
                value_state,
            )


        return (
            numeric_value,
            True,
            value_state,
        )


    except (
        TypeError,
        ValueError,
    ):

        return (
            None,
            False,
            value_state,
        )


# =============================================================================
# Speculation / prediction refinement contract
# =============================================================================
#
# The combined Notebook 03 source signal determines eligibility.
#
# A positive source signal is split only when the canonical sentence text
# provides deterministic textual evidence.
#
# A validated source zero implies absence of the combined construct and
# therefore permits both refined targets to be represented as observed zero.
#
# A positive but textually unresolved source signal leaves F8/F9 masked.
# =============================================================================

BLOCK_2_SPECULATION_PATTERNS = (
    r"\bmay\b",
    r"\bmight\b",
    r"\bcould\b",
    r"\bperhaps\b",
    r"\bpossibly\b",
    r"\bpossible\b",
    r"\bpotentially\b",
    r"\bspeculat(?:e|es|ed|ing|ion|ive)\b",
    r"\bconjectur(?:e|es|ed|ing|al)\b",
    r"\bseem(?:s|ed)?\b",
    r"\bappear(?:s|ed)?\b",
    r"\blikely\b",
    r"\bunlikely\b",
    r"\bsuggest(?:s|ed|ing)?\b",
    r"\brumou?r(?:s|ed)?\b",
)


BLOCK_2_PREDICTION_PATTERNS = (
    r"\bwill\b",
    r"\bgoing to\b",
    r"\bexpected to\b",
    r"\bforecast(?:s|ed|ing)?\b",
    r"\bpredict(?:s|ed|ing|ion)?\b",
    r"\bproject(?:s|ed|ing|ion)?\b",
    r"\banticipat(?:e|es|ed|ing|ion)?\b",
    r"\bset to\b",
    r"\bdue to\b",
    r"\bnext\s+(?:day|week|month|year|season|quarter)\b",
    r"\bupcoming\b",
    r"\bin the future\b",
    r"\bby\s+20\d{2}\b",
    r"\btomorrow\b",
)


BLOCK_2_SPECULATION_REGEX = re.compile(
    "|".join(
        BLOCK_2_SPECULATION_PATTERNS
    ),
    flags=
        re.IGNORECASE,
)


BLOCK_2_PREDICTION_REGEX = re.compile(
    "|".join(
        BLOCK_2_PREDICTION_PATTERNS
    ),
    flags=
        re.IGNORECASE,
)


def block_2_refine_speculation_prediction(
    sentence_text,
    source_value,
    source_available,
):
    """
    Resolve the Notebook 03 combined speculation_or_prediction source
    signal into Notebook 06 speculation and prediction dimensions.

    Returns:
        speculation_value
        speculation_available
        prediction_value
        prediction_available
        refinement_rule
        speculation_cue_found
        prediction_cue_found
    """

    if not source_available:

        return (
            None,
            False,
            None,
            False,
            "source_unavailable",
            False,
            False,
        )


    if source_value is None:

        return (
            None,
            False,
            None,
            False,
            "source_unavailable",
            False,
            False,
        )


    # -------------------------------------------------------------------------
    # Explicit source absence
    # -------------------------------------------------------------------------

    if float(
        source_value
    ) == 0.0:

        return (
            0.0,
            True,
            0.0,
            True,
            "validated_combined_source_absence",
            False,
            False,
        )


    text = (
        sentence_text
        if isinstance(
            sentence_text,
            str,
        )
        else ""
    )


    speculation_match = (
        BLOCK_2_SPECULATION_REGEX.search(
            text
        )
    )


    prediction_match = (
        BLOCK_2_PREDICTION_REGEX.search(
            text
        )
    )


    speculation_found = (
        speculation_match
        is not None
    )


    prediction_found = (
        prediction_match
        is not None
    )


    # -------------------------------------------------------------------------
    # Both meanings supported
    # -------------------------------------------------------------------------

    if (
        speculation_found
        and prediction_found
    ):

        return (
            float(
                source_value
            ),
            True,
            float(
                source_value
            ),
            True,
            "positive_source_both_textual_cues",
            True,
            True,
        )


    # -------------------------------------------------------------------------
    # Speculation only
    # -------------------------------------------------------------------------

    if speculation_found:

        return (
            float(
                source_value
            ),
            True,
            0.0,
            True,
            "positive_source_speculation_cue_only",
            True,
            False,
        )


    # -------------------------------------------------------------------------
    # Prediction only
    # -------------------------------------------------------------------------

    if prediction_found:

        return (
            0.0,
            True,
            float(
                source_value
            ),
            True,
            "positive_source_prediction_cue_only",
            False,
            True,
        )


    # -------------------------------------------------------------------------
    # Positive source signal cannot be resolved safely
    # -------------------------------------------------------------------------

    return (
        None,
        False,
        None,
        False,
        "positive_source_textually_unresolved",
        False,
        False,
    )


# =============================================================================
# Construct factual target records
# =============================================================================

NOTEBOOK_06_FACTUAL_TARGET_RECORDS = []

BLOCK_2_SOURCE_COMPONENT_VALUE_STATES = {
    component_name:
        set()

    for component_name
    in NOTEBOOK_06_FACTOLOGICAL_COMPONENTS
}


BLOCK_2_FACTOLOGICAL_WEIGHT_VALUE_STATES = set()

BLOCK_2_REFINEMENT_RULE_COUNTS = {}

BLOCK_2_REFINED_POSITIVE_SOURCE_RECORDS = 0

BLOCK_2_REFINED_UNRESOLVED_POSITIVE_RECORDS = 0


for source_order, source_record in enumerate(
    NOTEBOOK_06_FACTUAL_SOURCE_RECORDS
):

    identity = deepcopy(
        source_record.get(
            "identity",
            {}
        )
    )


    context = deepcopy(
        source_record.get(
            "context",
            {}
        )
    )


    annotations = source_record.get(
        "annotations",
        {}
    )


    sentence_id = identity.get(
        "sentence_id"
    )


    sentence_text = context.get(
        "current_sentence"
    )


    if not isinstance(
        sentence_text,
        str,
    ):

        sentence_text = ""


    source_components = annotations.get(
        "factological_components",
        {}
    )


    if not isinstance(
        source_components,
        dict,
    ):

        raise ValueError(
            f"Sentence {sentence_id} has no valid "
            "factological_components dictionary."
        )


    factual_target = np.full(
        NOTEBOOK_06_FACTUAL_TARGET_DIMENSION,
        np.nan,
        dtype=np.float64,
    )


    factual_mask = np.zeros(
        NOTEBOOK_06_FACTUAL_TARGET_DIMENSION,
        dtype=bool,
    )


    provenance = {}


    # =========================================================================
    # F1–F7 direct mappings
    # =========================================================================

    for target_name, source_name in (
        NOTEBOOK_06_FACTUAL_DIRECT_SOURCE_MAP.items()
    ):

        target_index = (
            NOTEBOOK_06_FACTUAL_DIMENSION_INDEX[
                target_name
            ]
        )


        source_object = source_components.get(
            source_name
        )


        (
            source_value,
            source_available,
            source_value_state,
        ) = block_2_extract_numeric_value(
            source_object
        )


        if source_value_state is not None:

            BLOCK_2_SOURCE_COMPONENT_VALUE_STATES[
                source_name
            ].add(
                str(
                    source_value_state
                )
            )


        if source_available:

            factual_target[
                target_index
            ] = source_value

            factual_mask[
                target_index
            ] = True


        provenance[
            target_name
        ] = {
            "mapping_type":
                "direct_notebook_03_component",

            "source_field":
                source_name,

            "source_value_state":
                source_value_state,

            "source_available":
                bool(
                    source_available
                ),

            "notebook_06_refinement":
                False,
        }


    # =========================================================================
    # F8 / F9 refined speculation / prediction
    # =========================================================================

    combined_source_object = source_components.get(
        NOTEBOOK_06_REFINED_SOURCE_FIELD
    )


    (
        combined_source_value,
        combined_source_available,
        combined_source_value_state,
    ) = block_2_extract_numeric_value(
        combined_source_object
    )


    if combined_source_value_state is not None:

        BLOCK_2_SOURCE_COMPONENT_VALUE_STATES[
            NOTEBOOK_06_REFINED_SOURCE_FIELD
        ].add(
            str(
                combined_source_value_state
            )
        )


    (
        speculation_value,
        speculation_available,
        prediction_value,
        prediction_available,
        refinement_rule,
        speculation_cue_found,
        prediction_cue_found,
    ) = block_2_refine_speculation_prediction(
        sentence_text=
            sentence_text,
        source_value=
            combined_source_value,
        source_available=
            combined_source_available,
    )


    BLOCK_2_REFINEMENT_RULE_COUNTS[
        refinement_rule
    ] = (
        BLOCK_2_REFINEMENT_RULE_COUNTS.get(
            refinement_rule,
            0,
        )
        + 1
    )


    if (
        combined_source_available
        and combined_source_value is not None
        and combined_source_value > 0.0
    ):

        BLOCK_2_REFINED_POSITIVE_SOURCE_RECORDS += 1


        if refinement_rule == (
            "positive_source_textually_unresolved"
        ):

            BLOCK_2_REFINED_UNRESOLVED_POSITIVE_RECORDS += 1


    speculation_index = (
        NOTEBOOK_06_FACTUAL_DIMENSION_INDEX[
            "speculation"
        ]
    )


    prediction_index = (
        NOTEBOOK_06_FACTUAL_DIMENSION_INDEX[
            "prediction"
        ]
    )


    if speculation_available:

        factual_target[
            speculation_index
        ] = speculation_value

        factual_mask[
            speculation_index
        ] = True


    if prediction_available:

        factual_target[
            prediction_index
        ] = prediction_value

        factual_mask[
            prediction_index
        ] = True


    provenance[
        "speculation"
    ] = {
        "mapping_type":
            "notebook_06_semantic_refinement",

        "source_field":
            NOTEBOOK_06_REFINED_SOURCE_FIELD,

        "source_value_state":
            combined_source_value_state,

        "source_available":
            bool(
                combined_source_available
            ),

        "source_value":
            combined_source_value,

        "refinement_rule":
            refinement_rule,

        "speculation_cue_found":
            bool(
                speculation_cue_found
            ),

        "prediction_cue_found":
            bool(
                prediction_cue_found
            ),

        "notebook_06_refinement":
            True,

        "original_notebook_03_record_modified":
            False,
    }


    provenance[
        "prediction"
    ] = {
        "mapping_type":
            "notebook_06_semantic_refinement",

        "source_field":
            NOTEBOOK_06_REFINED_SOURCE_FIELD,

        "source_value_state":
            combined_source_value_state,

        "source_available":
            bool(
                combined_source_available
            ),

        "source_value":
            combined_source_value,

        "refinement_rule":
            refinement_rule,

        "speculation_cue_found":
            bool(
                speculation_cue_found
            ),

        "prediction_cue_found":
            bool(
                prediction_cue_found
            ),

        "notebook_06_refinement":
            True,

        "original_notebook_03_record_modified":
            False,
    }


    # =========================================================================
    # F10 factological weight
    # =========================================================================

    factological_weight_object = annotations.get(
        NOTEBOOK_06_FACTOLOGICAL_WEIGHT_SOURCE_FIELD
    )


    (
        factological_weight_value,
        factological_weight_available,
        factological_weight_value_state,
    ) = block_2_extract_numeric_value(
        factological_weight_object
    )


    if factological_weight_value_state is not None:

        BLOCK_2_FACTOLOGICAL_WEIGHT_VALUE_STATES.add(
            str(
                factological_weight_value_state
            )
        )


    factological_weight_index = (
        NOTEBOOK_06_FACTUAL_DIMENSION_INDEX[
            "factological_weight"
        ]
    )


    if factological_weight_available:

        factual_target[
            factological_weight_index
        ] = factological_weight_value

        factual_mask[
            factological_weight_index
        ] = True


    provenance[
        "factological_weight"
    ] = {
        "mapping_type":
            "notebook_06_architectural_mapping",

        "source_field":
            NOTEBOOK_06_FACTOLOGICAL_WEIGHT_SOURCE_FIELD,

        "source_value_state":
            factological_weight_value_state,

        "source_available":
            bool(
                factological_weight_available
            ),

        "notebook_06_mapping_decision":
            True,

        "original_notebook_03_record_modified":
            False,
    }


    # =========================================================================
    # Record construction
    # =========================================================================

    target_record = {
        "record_type":
            "media_ai_notebook_06_factual_target",

        "target_contract_version":
            NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VERSION,

        "source_notebook":
            "03_supervision",

        "mapping_notebook":
            "06_factual_path",

        "source_order":
            int(
                source_order
            ),

        "identity":
            identity,

        "context":
            {
                "article_title":
                    context.get(
                        "article_title"
                    ),

                "context_scope":
                    context.get(
                        "context_scope"
                    ),

                "current_sentence":
                    sentence_text,

                "preceding_context":
                    deepcopy(
                        context.get(
                            "preceding_context"
                        )
                    ),
            },

        "factual_target":
            factual_target.tolist(),

        "factual_target_mask":
            factual_mask.tolist(),

        "observed_dimensions":
            int(
                factual_mask.sum()
            ),

        "possible_dimensions":
            int(
                NOTEBOOK_06_FACTUAL_TARGET_DIMENSION
            ),

        "target_coverage":
            float(
                factual_mask.mean()
            ),

        "dimension_order":
            list(
                NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
            ),

        "dimension_ids":
            list(
                NOTEBOOK_06_FACTUAL_DIMENSION_IDS
            ),

        "provenance":
            provenance,

        "original_notebook_03_record_modified":
            False,
    }


    NOTEBOOK_06_FACTUAL_TARGET_RECORDS.append(
        target_record
    )


# =============================================================================
# Factual target construction validation
# =============================================================================

BLOCK_2_FACTUAL_TARGET_RECORD_COUNT = len(
    NOTEBOOK_06_FACTUAL_TARGET_RECORDS
)


BLOCK_2_FACTUAL_TARGET_RECORD_COUNT_VALID = (
    BLOCK_2_FACTUAL_TARGET_RECORD_COUNT
    ==
    BLOCK_2_SOURCE_RECORD_COUNT
)


if not BLOCK_2_FACTUAL_TARGET_RECORD_COUNT_VALID:

    raise ValueError(
        "Factual target record count does not match canonical "
        "Notebook 03 source record count."
    )


# -----------------------------------------------------------------------------
# Target identity validation
# -----------------------------------------------------------------------------

BLOCK_2_FACTUAL_TARGET_SENTENCE_IDS = [
    record[
        "identity"
    ][
        "sentence_id"
    ]

    for record
    in NOTEBOOK_06_FACTUAL_TARGET_RECORDS
]


BLOCK_2_FACTUAL_TARGET_IDS_UNIQUE = (
    len(
        BLOCK_2_FACTUAL_TARGET_SENTENCE_IDS
    )
    ==
    len(
        set(
            BLOCK_2_FACTUAL_TARGET_SENTENCE_IDS
        )
    )
)


BLOCK_2_FACTUAL_TARGET_ALIGNMENT_VALID = (
    set(
        BLOCK_2_FACTUAL_TARGET_SENTENCE_IDS
    )
    ==
    set(
        NOTEBOOK_06_SENTENCE_IDS
    )
)


if not BLOCK_2_FACTUAL_TARGET_IDS_UNIQUE:

    raise ValueError(
        "Notebook 06 factual target sentence IDs are not unique."
    )


if not BLOCK_2_FACTUAL_TARGET_ALIGNMENT_VALID:

    raise ValueError(
        "Notebook 06 factual targets do not align with the canonical "
        "Notebook 06 sentence identity contract."
    )


# =============================================================================
# Matrix construction
# =============================================================================

BLOCK_2_FACTUAL_TARGET_MATRIX = np.asarray(
    [
        record[
            "factual_target"
        ]

        for record
        in NOTEBOOK_06_FACTUAL_TARGET_RECORDS
    ],
    dtype=np.float64,
)


BLOCK_2_FACTUAL_MASK_MATRIX = np.asarray(
    [
        record[
            "factual_target_mask"
        ]

        for record
        in NOTEBOOK_06_FACTUAL_TARGET_RECORDS
    ],
    dtype=bool,
)


BLOCK_2_FACTUAL_TARGET_MATRIX_SHAPE_VALID = (
    BLOCK_2_FACTUAL_TARGET_MATRIX.shape
    ==
    (
        BLOCK_2_SOURCE_RECORD_COUNT,
        10,
    )
)


BLOCK_2_FACTUAL_MASK_MATRIX_SHAPE_VALID = (
    BLOCK_2_FACTUAL_MASK_MATRIX.shape
    ==
    (
        BLOCK_2_SOURCE_RECORD_COUNT,
        10,
    )
)


if not BLOCK_2_FACTUAL_TARGET_MATRIX_SHAPE_VALID:

    raise ValueError(
        "Notebook 06 factual target matrix does not have shape "
        "(records, 10)."
    )


if not BLOCK_2_FACTUAL_MASK_MATRIX_SHAPE_VALID:

    raise ValueError(
        "Notebook 06 factual target mask matrix does not have shape "
        "(records, 10)."
    )


# =============================================================================
# Validate observed target values
# =============================================================================

BLOCK_2_OBSERVED_TARGET_VALUES_FINITE = bool(
    np.isfinite(
        BLOCK_2_FACTUAL_TARGET_MATRIX[
            BLOCK_2_FACTUAL_MASK_MATRIX
        ]
    ).all()
)


if not BLOCK_2_OBSERVED_TARGET_VALUES_FINITE:

    raise ValueError(
        "One or more observed factual target values are non-finite."
    )


# =============================================================================
# Coverage audit
# =============================================================================

BLOCK_2_DIMENSION_AVAILABLE_COUNTS = {}

BLOCK_2_DIMENSION_ELIGIBLE_COUNTS = {}

BLOCK_2_DIMENSION_COVERAGE = {}

BLOCK_2_DIMENSION_VALUE_MINIMUM = {}

BLOCK_2_DIMENSION_VALUE_MAXIMUM = {}


for dimension_index, dimension_name in enumerate(
    NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
):

    dimension_mask = (
        BLOCK_2_FACTUAL_MASK_MATRIX[
            :,
            dimension_index,
        ]
    )


    available_count = int(
        dimension_mask.sum()
    )


    eligible_count = int(
        BLOCK_2_FACTUAL_MASK_MATRIX.shape[
            0
        ]
    )


    coverage = (
        available_count
        /
        eligible_count
        if eligible_count > 0
        else 0.0
    )


    BLOCK_2_DIMENSION_AVAILABLE_COUNTS[
        dimension_name
    ] = available_count


    BLOCK_2_DIMENSION_ELIGIBLE_COUNTS[
        dimension_name
    ] = eligible_count


    BLOCK_2_DIMENSION_COVERAGE[
        dimension_name
    ] = float(
        coverage
    )


    if available_count > 0:

        observed_values = (
            BLOCK_2_FACTUAL_TARGET_MATRIX[
                dimension_mask,
                dimension_index,
            ]
        )


        BLOCK_2_DIMENSION_VALUE_MINIMUM[
            dimension_name
        ] = float(
            observed_values.min()
        )


        BLOCK_2_DIMENSION_VALUE_MAXIMUM[
            dimension_name
        ] = float(
            observed_values.max()
        )


    else:

        BLOCK_2_DIMENSION_VALUE_MINIMUM[
            dimension_name
        ] = None

        BLOCK_2_DIMENSION_VALUE_MAXIMUM[
            dimension_name
        ] = None


BLOCK_2_TOTAL_AVAILABLE_ELEMENTS = int(
    BLOCK_2_FACTUAL_MASK_MATRIX.sum()
)


BLOCK_2_TOTAL_POSSIBLE_ELEMENTS = int(
    BLOCK_2_FACTUAL_MASK_MATRIX.size
)


BLOCK_2_TOTAL_TARGET_COVERAGE = (
    BLOCK_2_TOTAL_AVAILABLE_ELEMENTS
    /
    BLOCK_2_TOTAL_POSSIBLE_ELEMENTS
)


BLOCK_2_SENTENCES_WITH_ANY_FACTUAL_SUPERVISION = int(
    np.any(
        BLOCK_2_FACTUAL_MASK_MATRIX,
        axis=1,
    ).sum()
)


BLOCK_2_SENTENCES_FULLY_FACTUALLY_SUPERVISED = int(
    np.all(
        BLOCK_2_FACTUAL_MASK_MATRIX,
        axis=1,
    ).sum()
)


BLOCK_2_SENTENCE_LEVEL_FACTUAL_AVAILABILITY = (
    BLOCK_2_SENTENCES_WITH_ANY_FACTUAL_SUPERVISION
    /
    BLOCK_2_SOURCE_RECORD_COUNT
)


# =============================================================================
# Refined-dimension coverage
# =============================================================================

BLOCK_2_SPECULATION_COVERAGE = (
    BLOCK_2_DIMENSION_COVERAGE[
        "speculation"
    ]
)


BLOCK_2_PREDICTION_COVERAGE = (
    BLOCK_2_DIMENSION_COVERAGE[
        "prediction"
    ]
)


BLOCK_2_FACTOLOGICAL_WEIGHT_COVERAGE = (
    BLOCK_2_DIMENSION_COVERAGE[
        "factological_weight"
    ]
)


# =============================================================================
# Mapping provenance audit
# =============================================================================

BLOCK_2_DIRECT_MAPPING_COUNT = len(
    NOTEBOOK_06_FACTUAL_DIRECT_SOURCE_MAP
)


BLOCK_2_REFINED_DIMENSION_COUNT = 2

BLOCK_2_WEIGHT_MAPPING_COUNT = 1

BLOCK_2_FABRICATED_DIMENSION_COUNT = 0

BLOCK_2_SEMANTIC_DIMENSIONS_RESOLVED = (
    BLOCK_2_DIRECT_MAPPING_COUNT
    +
    BLOCK_2_REFINED_DIMENSION_COUNT
    +
    BLOCK_2_WEIGHT_MAPPING_COUNT
)


BLOCK_2_SEMANTIC_DIMENSIONS_RESOLVED_VALID = (
    BLOCK_2_SEMANTIC_DIMENSIONS_RESOLVED
    == 10
)


BLOCK_2_ORIGINAL_NOTEBOOK_03_RECORDS_MODIFIED = any(
    record.get(
        "original_notebook_03_record_modified",
        False,
    )

    for record
    in NOTEBOOK_06_FACTUAL_TARGET_RECORDS
)


BLOCK_2_PROVENANCE_VALID = all(
    [
        BLOCK_2_DIRECT_MAPPING_COUNT
        == 7,

        BLOCK_2_REFINED_DIMENSION_COUNT
        == 2,

        BLOCK_2_WEIGHT_MAPPING_COUNT
        == 1,

        BLOCK_2_FABRICATED_DIMENSION_COUNT
        == 0,

        BLOCK_2_SEMANTIC_DIMENSIONS_RESOLVED_VALID,

        not BLOCK_2_ORIGINAL_NOTEBOOK_03_RECORDS_MODIFIED,
    ]
)


if not BLOCK_2_PROVENANCE_VALID:

    raise ValueError(
        "Notebook 06 factual mapping provenance contract is invalid."
    )


# =============================================================================
# Missing-value semantics audit
# =============================================================================

BLOCK_2_MISSING_VALUE_CONTRACT_VALID = all(
    [
        NOTEBOOK_06_MASK_AWARE_SUPERVISION,

        not NOTEBOOK_06_MISSING_EQUALS_ZERO,

        not NOTEBOOK_06_MISSING_EQUALS_NEGATIVE,

        not NOTEBOOK_06_UNAVAILABLE_ENTERS_LOSS,

        NOTEBOOK_06_PARTIAL_FACTUAL_SUPERVISION_ALLOWED,
    ]
)


if not BLOCK_2_MISSING_VALUE_CONTRACT_VALID:

    raise ValueError(
        "Notebook 06 factual missing-value contract is invalid."
    )


# =============================================================================
# Target-type contract
# =============================================================================
#
# F1–F9 are factual-content dimensions.
# F10 is a continuous factual-weight dimension.
#
# Block 2 does not yet choose model activations or loss functions.
# =============================================================================

NOTEBOOK_06_FACTUAL_TARGET_TYPES = {
    "F1":
        "factological_content",

    "F2":
        "factological_content",

    "F3":
        "factological_content",

    "F4":
        "factological_content",

    "F5":
        "factological_content",

    "F6":
        "factological_content",

    "F7":
        "factological_content",

    "F8":
        "refined_factological_content",

    "F9":
        "refined_factological_content",

    "F10":
        "continuous_factological_weight",
}


NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_RESOLVED = False

NOTEBOOK_06_FACTUAL_ACTIVATION_CONTRACT_RESOLVED = False


# =============================================================================
# Factual target contract resolution state
# =============================================================================

NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED = True

NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_DEFINED = True

NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID = all(
    [
        BLOCK_2_FACTUAL_DIMENSION_CONTRACT_VALID,

        BLOCK_2_FACTUAL_TARGET_RECORD_COUNT_VALID,

        BLOCK_2_FACTUAL_TARGET_IDS_UNIQUE,

        BLOCK_2_FACTUAL_TARGET_ALIGNMENT_VALID,

        BLOCK_2_FACTUAL_TARGET_MATRIX_SHAPE_VALID,

        BLOCK_2_FACTUAL_MASK_MATRIX_SHAPE_VALID,

        BLOCK_2_OBSERVED_TARGET_VALUES_FINITE,

        BLOCK_2_PROVENANCE_VALID,

        BLOCK_2_MISSING_VALUE_CONTRACT_VALID,
    ]
)


NOTEBOOK_06_FACTUAL_SUPERVISION_DATASET_CONSTRUCTIBLE = all(
    [
        NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID,

        BLOCK_2_SENTENCES_WITH_ANY_FACTUAL_SUPERVISION
        > 0,

        BLOCK_2_TOTAL_AVAILABLE_ELEMENTS
        > 0,
    ]
)


# -----------------------------------------------------------------------------
# Mapping is resolved, but optimisation is still blocked.
#
# Loss semantics and parameter activation belong to later blocks.
# -----------------------------------------------------------------------------

NOTEBOOK_06_FACTUAL_OPTIMISATION_READY = False


# =============================================================================
# Construct persistent factual target artefact
# =============================================================================

NOTEBOOK_06_FACTUAL_TARGET_ARTEFACT = {
    "artefact_type":
        "media_ai_factual_target_contract",

    "artefact_version":
        NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VERSION,

    "created_at_utc":
        BLOCK_2_EXECUTED_AT_UTC,

    "source_notebook":
        "03_supervision",

    "mapping_notebook":
        "06_factual_path",

    "source_artefact":
        {
            "filename":
                NOTEBOOK_03_ACCEPTED_ANNOTATIONS_FILENAME,

            "drive_file_id":
                BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID,

            "record_count":
                BLOCK_2_SOURCE_RECORD_COUNT,

            "canonical_source_modified":
                False,
        },

    "architecture":
        {
            "factual_dimension":
                10,

            "dimension_ids":
                list(
                    NOTEBOOK_06_FACTUAL_DIMENSION_IDS
                ),

            "dimension_order":
                list(
                    NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
                ),

            "dimension_map":
                deepcopy(
                    NOTEBOOK_06_FACTUAL_DIMENSION_MAP
                ),
        },

    "mapping_contract":
        {
            "direct_component_mappings":
                deepcopy(
                    NOTEBOOK_06_FACTUAL_DIRECT_SOURCE_MAP
                ),

            "refined_source_field":
                NOTEBOOK_06_REFINED_SOURCE_FIELD,

            "refined_dimensions":
                [
                    "speculation",
                    "prediction",
                ],

            "factological_weight_source_field":
                NOTEBOOK_06_FACTOLOGICAL_WEIGHT_SOURCE_FIELD,

            "factological_weight_target_dimension":
                "F10",

            "direct_mapping_count":
                BLOCK_2_DIRECT_MAPPING_COUNT,

            "refined_dimension_count":
                BLOCK_2_REFINED_DIMENSION_COUNT,

            "weight_mapping_count":
                BLOCK_2_WEIGHT_MAPPING_COUNT,

            "fabricated_dimension_count":
                BLOCK_2_FABRICATED_DIMENSION_COUNT,

            "semantic_dimensions_resolved":
                BLOCK_2_SEMANTIC_DIMENSIONS_RESOLVED,

            "original_notebook_03_records_modified":
                False,
        },

    "refinement_contract":
        {
            "speculation_definition":
                (
                    "Possible, hypothetical, conjectural or insufficiently "
                    "established proposition without requiring future time."
                ),

            "prediction_definition":
                (
                    "Proposition forecasting, anticipating or asserting a "
                    "possible future event, state or outcome."
                ),

            "dimensions_mutually_exclusive":
                False,

            "combined_source_blindly_duplicated":
                False,

            "positive_unresolved_source_is_masked":
                True,

            "source_zero_resolves_both_to_observed_zero":
                True,

            "future_article_context_used":
                False,

            "refinement_rule_counts":
                deepcopy(
                    BLOCK_2_REFINEMENT_RULE_COUNTS
                ),

            "positive_source_records":
                BLOCK_2_REFINED_POSITIVE_SOURCE_RECORDS,

            "positive_source_records_unresolved":
                BLOCK_2_REFINED_UNRESOLVED_POSITIVE_RECORDS,
        },

    "target_type_contract":
        deepcopy(
            NOTEBOOK_06_FACTUAL_TARGET_TYPES
        ),

    "coverage":
        {
            "sentence_count":
                BLOCK_2_SOURCE_RECORD_COUNT,

            "sentences_with_any_supervision":
                BLOCK_2_SENTENCES_WITH_ANY_FACTUAL_SUPERVISION,

            "fully_supervised_sentences":
                BLOCK_2_SENTENCES_FULLY_FACTUALLY_SUPERVISED,

            "available_elements":
                BLOCK_2_TOTAL_AVAILABLE_ELEMENTS,

            "possible_elements":
                BLOCK_2_TOTAL_POSSIBLE_ELEMENTS,

            "aggregate_coverage":
                float(
                    BLOCK_2_TOTAL_TARGET_COVERAGE
                ),

            "dimension_available_counts":
                deepcopy(
                    BLOCK_2_DIMENSION_AVAILABLE_COUNTS
                ),

            "dimension_eligible_counts":
                deepcopy(
                    BLOCK_2_DIMENSION_ELIGIBLE_COUNTS
                ),

            "dimension_coverage":
                deepcopy(
                    BLOCK_2_DIMENSION_COVERAGE
                ),

            "dimension_minimum":
                deepcopy(
                    BLOCK_2_DIMENSION_VALUE_MINIMUM
                ),

            "dimension_maximum":
                deepcopy(
                    BLOCK_2_DIMENSION_VALUE_MAXIMUM
                ),
        },

    "masking_contract":
        {
            "mask_aware":
                True,

            "missing_equals_zero":
                False,

            "missing_equals_negative":
                False,

            "unavailable_enters_loss":
                False,

            "partial_supervision_allowed":
                True,
        },

    "training_boundary":
        {
            "mapping_resolved":
                True,

            "target_contract_defined":
                True,

            "supervision_dataset_constructible":
                bool(
                    NOTEBOOK_06_FACTUAL_SUPERVISION_DATASET_CONSTRUCTIBLE
                ),

            "loss_contract_resolved":
                False,

            "activation_contract_resolved":
                False,

            "objectives_activated":
                False,

            "optimizer_created":
                False,

            "training_executed":
                False,

            "empirical_validity":
                False,
        },

    "records":
        deepcopy(
            NOTEBOOK_06_FACTUAL_TARGET_RECORDS
        ),
}


# =============================================================================
# JSON serialisation helper
# =============================================================================

def block_2_json_default(
    value,
):
    """
    Convert NumPy values to JSON-safe Python values.
    """

    if isinstance(
        value,
        np.generic,
    ):

        return value.item()


    if isinstance(
        value,
        np.ndarray,
    ):

        return value.tolist()


    if isinstance(
        value,
        set,
    ):

        return sorted(
            value
        )


    if isinstance(
        value,
        tuple,
    ):

        return list(
            value
        )


    raise TypeError(
        f"Object of type {type(value).__name__} "
        "is not JSON serialisable."
    )


NOTEBOOK_06_FACTUAL_TARGET_JSON = json.dumps(
    NOTEBOOK_06_FACTUAL_TARGET_ARTEFACT,
    indent=2,
    ensure_ascii=False,
    default=
        block_2_json_default,
)


BLOCK_2_FACTUAL_TARGET_JSON_VALID = bool(
    NOTEBOOK_06_FACTUAL_TARGET_JSON
)


if not BLOCK_2_FACTUAL_TARGET_JSON_VALID:

    raise ValueError(
        "Notebook 06 factual target artefact could not be serialised."
    )


# =============================================================================
# Local persistence
# =============================================================================

with open(
    NOTEBOOK_06_FACTUAL_TARGET_FILENAME,
    "w",
    encoding="utf-8",
) as factual_target_file:

    factual_target_file.write(
        NOTEBOOK_06_FACTUAL_TARGET_JSON
    )


BLOCK_2_LOCAL_FACTUAL_TARGET_CREATED = True


# =============================================================================
# Persistent Drive location
# =============================================================================
#
# Reuse the parent folder of the Notebook 05 → 06 handover.
# =============================================================================

BLOCK_2_HANDOVER_DRIVE_METADATA = (
    NOTEBOOK_06_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID,
        fields=
            "id,name,parents",
    )
    .execute()
)


BLOCK_2_PARENT_IDS = (
    BLOCK_2_HANDOVER_DRIVE_METADATA.get(
        "parents",
        [],
    )
)


# =============================================================================
# Persist factual target artefact to Drive
# =============================================================================

def block_2_persist_json_to_drive(
    drive_service,
    filename,
    json_text,
    parent_ids=None,
):
    """
    Create or update one exact-name JSON artefact in Google Drive.
    """

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )


    search_response = (
        drive_service.files()
        .list(
            q=(
                f"name = '{escaped_filename}' "
                "and trashed = false"
            ),
            spaces=
                "drive",
            fields=
                "files(id,name,modifiedTime,parents)",
            orderBy=
                "modifiedTime desc",
            pageSize=
                20,
        )
        .execute()
    )


    matching_files = search_response.get(
        "files",
        [],
    )


    media = MediaIoBaseUpload(
        io.BytesIO(
            json_text.encode(
                "utf-8"
            )
        ),
        mimetype=
            "application/json",
        resumable=
            False,
    )


    if matching_files:

        drive_file = (
            drive_service.files()
            .update(
                fileId=
                    matching_files[
                        0
                    ][
                        "id"
                    ],
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "updated"


    else:

        metadata = {
            "name":
                filename
        }


        if parent_ids:

            metadata[
                "parents"
            ] = parent_ids


        drive_file = (
            drive_service.files()
            .create(
                body=
                    metadata,
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "created"


    return (
        drive_file,
        operation,
    )


(
    NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE,
    NOTEBOOK_06_FACTUAL_TARGET_DRIVE_OPERATION,
) = block_2_persist_json_to_drive(
    drive_service=
        NOTEBOOK_06_DRIVE_SERVICE,
    filename=
        NOTEBOOK_06_FACTUAL_TARGET_FILENAME,
    json_text=
        NOTEBOOK_06_FACTUAL_TARGET_JSON,
    parent_ids=
        BLOCK_2_PARENT_IDS,
)


NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID = (
    NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE.get(
        "id"
    )
)


BLOCK_2_FACTUAL_TARGET_DRIVE_PERSISTED = bool(
    NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID
)


if not BLOCK_2_FACTUAL_TARGET_DRIVE_PERSISTED:

    raise RuntimeError(
        "Notebook 06 factual target artefact was not persisted "
        "to Google Drive."
    )


# =============================================================================
# Read-back validation
# =============================================================================

BLOCK_2_RELOADED_FACTUAL_TARGET_BYTES = (
    block_2_download_drive_bytes(
        NOTEBOOK_06_DRIVE_SERVICE,
        NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID,
    )
)


BLOCK_2_RELOADED_FACTUAL_TARGET_ARTEFACT = json.loads(
    BLOCK_2_RELOADED_FACTUAL_TARGET_BYTES.decode(
        "utf-8"
    )
)


BLOCK_2_READBACK_VERSION_VALID = (
    BLOCK_2_RELOADED_FACTUAL_TARGET_ARTEFACT.get(
        "artefact_version"
    )
    ==
    NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VERSION
)


BLOCK_2_READBACK_DIMENSION_VALID = (
    BLOCK_2_RELOADED_FACTUAL_TARGET_ARTEFACT[
        "architecture"
    ][
        "factual_dimension"
    ]
    == 10
)


BLOCK_2_READBACK_RECORD_COUNT_VALID = (
    len(
        BLOCK_2_RELOADED_FACTUAL_TARGET_ARTEFACT[
            "records"
        ]
    )
    ==
    BLOCK_2_SOURCE_RECORD_COUNT
)


BLOCK_2_READBACK_MAPPING_VALID = (
    BLOCK_2_RELOADED_FACTUAL_TARGET_ARTEFACT[
        "mapping_contract"
    ][
        "semantic_dimensions_resolved"
    ]
    == 10
)


BLOCK_2_READBACK_FABRICATION_VALID = (
    BLOCK_2_RELOADED_FACTUAL_TARGET_ARTEFACT[
        "mapping_contract"
    ][
        "fabricated_dimension_count"
    ]
    == 0
)


BLOCK_2_READBACK_SOURCE_UNMODIFIED = (
    BLOCK_2_RELOADED_FACTUAL_TARGET_ARTEFACT[
        "mapping_contract"
    ][
        "original_notebook_03_records_modified"
    ]
    is False
)


BLOCK_2_FACTUAL_TARGET_READBACK_VALID = all(
    [
        BLOCK_2_READBACK_VERSION_VALID,
        BLOCK_2_READBACK_DIMENSION_VALID,
        BLOCK_2_READBACK_RECORD_COUNT_VALID,
        BLOCK_2_READBACK_MAPPING_VALID,
        BLOCK_2_READBACK_FABRICATION_VALID,
        BLOCK_2_READBACK_SOURCE_UNMODIFIED,
    ]
)


if not BLOCK_2_FACTUAL_TARGET_READBACK_VALID:

    raise RuntimeError(
        "Persisted Notebook 06 factual target artefact failed "
        "read-back validation."
    )


# =============================================================================
# Block 2 execution-state finalisation
# =============================================================================

NOTEBOOK_06_FACTUAL_TARGET_MAPPING_PERFORMED = True

NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED = False

NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED = False

NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED = False

NOTEBOOK_06_FACTUAL_LOSS_CALCULATED = False

NOTEBOOK_06_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Final Block 2 validation
# =============================================================================

NOTEBOOK_06_BLOCK_2_ERRORS = []


if not NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_mapping_not_resolved"
    )


if not NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_DEFINED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_target_contract_not_defined"
    )


if not NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_target_contract_invalid"
    )


if not NOTEBOOK_06_FACTUAL_SUPERVISION_DATASET_CONSTRUCTIBLE:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_supervision_dataset_not_constructible"
    )


if BLOCK_2_FABRICATED_DIMENSION_COUNT != 0:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_dimension_fabricated"
    )


if BLOCK_2_ORIGINAL_NOTEBOOK_03_RECORDS_MODIFIED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "notebook_03_source_records_modified"
    )


if NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_objectives_incorrectly_activated"
    )


if NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_optimizer_incorrectly_created"
    )


if NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_forward_pass_incorrectly_executed"
    )


if NOTEBOOK_06_FACTUAL_LOSS_CALCULATED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_loss_incorrectly_calculated"
    )


if NOTEBOOK_06_BACKWARD_PASS_EXECUTED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "backward_pass_incorrectly_executed"
    )


if NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "parameter_update_incorrectly_executed"
    )


if NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_training_incorrectly_executed"
    )


if NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "psychological_training_incorrectly_executed"
    )


if NOTEBOOK_06_GROUPS_CONSTRUCTED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "groups_incorrectly_constructed"
    )


if NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "empirical_validity_incorrectly_asserted"
    )


if not BLOCK_2_FACTUAL_TARGET_DRIVE_PERSISTED:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_target_not_persisted"
    )


if not BLOCK_2_FACTUAL_TARGET_READBACK_VALID:

    NOTEBOOK_06_BLOCK_2_ERRORS.append(
        "factual_target_readback_invalid"
    )


NOTEBOOK_06_BLOCK_2_VALID = (
    len(
        NOTEBOOK_06_BLOCK_2_ERRORS
    )
    == 0
)


if not NOTEBOOK_06_BLOCK_2_VALID:

    raise RuntimeError(
        "Notebook 06 Block 2 factual target-contract audit failed. "
        f"Errors: {NOTEBOOK_06_BLOCK_2_ERRORS}"
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_06_READY_FOR_FACTUAL_TARGET_AVAILABILITY_AUDIT = True

NOTEBOOK_06_BLOCK_2_COMPLETE = True


# =============================================================================
# Human-readable scope table
# =============================================================================

BLOCK_2_FACTUAL_DIMENSION_ROWS = []


for dimension_index, (
    dimension_id,
    dimension_name,
) in enumerate(
    zip(
        NOTEBOOK_06_FACTUAL_DIMENSION_IDS,
        NOTEBOOK_06_FACTUAL_DIMENSION_ORDER,
    )
):

    if dimension_name in NOTEBOOK_06_FACTUAL_DIRECT_SOURCE_MAP:

        mapping_type = (
            "direct_notebook_03_component"
        )

        source_field = (
            NOTEBOOK_06_FACTUAL_DIRECT_SOURCE_MAP[
                dimension_name
            ]
        )


    elif dimension_name in (
        "speculation",
        "prediction",
    ):

        mapping_type = (
            "notebook_06_semantic_refinement"
        )

        source_field = (
            NOTEBOOK_06_REFINED_SOURCE_FIELD
        )


    else:

        mapping_type = (
            "notebook_06_architectural_mapping"
        )

        source_field = (
            NOTEBOOK_06_FACTOLOGICAL_WEIGHT_SOURCE_FIELD
        )


    BLOCK_2_FACTUAL_DIMENSION_ROWS.append(
        {
            "dimension_id":
                dimension_id,

            "dimension_index":
                dimension_index,

            "target_name":
                dimension_name,

            "mapping_type":
                mapping_type,

            "source_field":
                source_field,

            "available":
                BLOCK_2_DIMENSION_AVAILABLE_COUNTS[
                    dimension_name
                ],

            "eligible":
                BLOCK_2_DIMENSION_ELIGIBLE_COUNTS[
                    dimension_name
                ],

            "coverage":
                BLOCK_2_DIMENSION_COVERAGE[
                    dimension_name
                ],

            "minimum":
                BLOCK_2_DIMENSION_VALUE_MINIMUM[
                    dimension_name
                ],

            "maximum":
                BLOCK_2_DIMENSION_VALUE_MAXIMUM[
                    dimension_name
                ],

            "fabricated":
                False,
        }
    )


BLOCK_2_FACTUAL_DIMENSION_AUDIT = pd.DataFrame(
    BLOCK_2_FACTUAL_DIMENSION_ROWS
)


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_06_BLOCK_2_SUMMARY = {
    "block":
        NOTEBOOK_06_BLOCK_2,

    "block_name":
        NOTEBOOK_06_BLOCK_2_NAME,

    "version":
        NOTEBOOK_06_BLOCK_2_VERSION,

    "executed_at_utc":
        BLOCK_2_EXECUTED_AT_UTC,

    "source_records":
        BLOCK_2_SOURCE_RECORD_COUNT,

    "source_sentence_ids_unique":
        BLOCK_2_SOURCE_SENTENCE_IDS_UNIQUE,

    "source_alignment_valid":
        BLOCK_2_SENTENCE_ALIGNMENT_VALID,

    "factual_architectural_dimension":
        NOTEBOOK_06_FACTUAL_TARGET_DIMENSION,

    "semantic_dimensions_resolved":
        BLOCK_2_SEMANTIC_DIMENSIONS_RESOLVED,

    "direct_mappings":
        BLOCK_2_DIRECT_MAPPING_COUNT,

    "refined_dimensions":
        BLOCK_2_REFINED_DIMENSION_COUNT,

    "factological_weight_mappings":
        BLOCK_2_WEIGHT_MAPPING_COUNT,

    "fabricated_dimensions":
        BLOCK_2_FABRICATED_DIMENSION_COUNT,

    "source_records_modified":
        BLOCK_2_ORIGINAL_NOTEBOOK_03_RECORDS_MODIFIED,

    "available_elements":
        BLOCK_2_TOTAL_AVAILABLE_ELEMENTS,

    "possible_elements":
        BLOCK_2_TOTAL_POSSIBLE_ELEMENTS,

    "aggregate_coverage":
        BLOCK_2_TOTAL_TARGET_COVERAGE,

    "speculation_coverage":
        BLOCK_2_SPECULATION_COVERAGE,

    "prediction_coverage":
        BLOCK_2_PREDICTION_COVERAGE,

    "factological_weight_coverage":
        BLOCK_2_FACTOLOGICAL_WEIGHT_COVERAGE,

    "positive_combined_source_records":
        BLOCK_2_REFINED_POSITIVE_SOURCE_RECORDS,

    "positive_combined_source_unresolved":
        BLOCK_2_REFINED_UNRESOLVED_POSITIVE_RECORDS,

    "mapping_resolved":
        NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED,

    "target_contract_valid":
        NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID,

    "dataset_constructible":
        NOTEBOOK_06_FACTUAL_SUPERVISION_DATASET_CONSTRUCTIBLE,

    "loss_contract_resolved":
        NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_RESOLVED,

    "optimisation_ready":
        NOTEBOOK_06_FACTUAL_OPTIMISATION_READY,

    "artefact_filename":
        NOTEBOOK_06_FACTUAL_TARGET_FILENAME,

    "artefact_drive_file_id":
        NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID,

    "artefact_readback_valid":
        BLOCK_2_FACTUAL_TARGET_READBACK_VALID,

    "empirical_validity":
        NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_06_BLOCK_2_VALID,

    "block_complete":
        NOTEBOOK_06_BLOCK_2_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 06, Block 2: "
    "Factual Supervision Mapping and Target-Contract Audit"
)

print("=" * 72)

print(
    f"Target-contract version      : "
    f"{NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VERSION}"
)


print("-" * 72)

print(
    "Canonical factual supervision"
)

print(
    f"Source artefact              : "
    f"{NOTEBOOK_03_ACCEPTED_ANNOTATIONS_FILENAME}"
)

print(
    f"Source Drive file ID         : "
    f"{BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID}"
)

print(
    f"Accepted source records      : "
    f"{BLOCK_2_SOURCE_RECORD_COUNT}"
)

print(
    f"Sentence IDs present         : "
    f"{BLOCK_2_SOURCE_SENTENCE_IDS_PRESENT}"
)

print(
    f"Sentence IDs unique          : "
    f"{BLOCK_2_SOURCE_SENTENCE_IDS_UNIQUE}"
)

print(
    f"Canonical alignment valid    : "
    f"{BLOCK_2_SENTENCE_ALIGNMENT_VALID}"
)


print("-" * 72)

print(
    "Ten-dimensional factual contract"
)

print(
    f"Architectural dimensions     : "
    f"{NOTEBOOK_06_FACTUAL_TARGET_DIMENSION}"
)

print(
    f"Semantic dimensions resolved : "
    f"{BLOCK_2_SEMANTIC_DIMENSIONS_RESOLVED}"
)

print(
    f"Direct component mappings    : "
    f"{BLOCK_2_DIRECT_MAPPING_COUNT}"
)

print(
    f"Refined dimensions           : "
    f"{BLOCK_2_REFINED_DIMENSION_COUNT}"
)

print(
    f"Factological weight mappings : "
    f"{BLOCK_2_WEIGHT_MAPPING_COUNT}"
)

print(
    f"Fabricated dimensions        : "
    f"{BLOCK_2_FABRICATED_DIMENSION_COUNT}"
)

print(
    f"Notebook 03 records modified : "
    f"{BLOCK_2_ORIGINAL_NOTEBOOK_03_RECORDS_MODIFIED}"
)


print("-" * 72)

print(
    "Factual dimension order"
)


for dimension_id, dimension_name in zip(
    NOTEBOOK_06_FACTUAL_DIMENSION_IDS,
    NOTEBOOK_06_FACTUAL_DIMENSION_ORDER,
):

    print(
        f"{dimension_id:<4}                         : "
        f"{dimension_name}"
    )


print("-" * 72)

print(
    "Speculation / prediction refinement"
)

print(
    f"Canonical source field       : "
    f"{NOTEBOOK_06_REFINED_SOURCE_FIELD}"
)

print(
    f"Blind duplication used       : "
    f"{False}"
)

print(
    f"Mutually exclusive           : "
    f"{False}"
)

print(
    f"Positive source records      : "
    f"{BLOCK_2_REFINED_POSITIVE_SOURCE_RECORDS}"
)

print(
    f"Positive unresolved records  : "
    f"{BLOCK_2_REFINED_UNRESOLVED_POSITIVE_RECORDS}"
)


for refinement_rule, rule_count in sorted(
    BLOCK_2_REFINEMENT_RULE_COUNTS.items()
):

    print(
        f"{refinement_rule:<31}: "
        f"{rule_count}"
    )


print("-" * 72)

print(
    "Factual supervision coverage"
)

print(
    f"Sentences                    : "
    f"{BLOCK_2_SOURCE_RECORD_COUNT}"
)

print(
    f"Any supervision sentences    : "
    f"{BLOCK_2_SENTENCES_WITH_ANY_FACTUAL_SUPERVISION}"
)

print(
    f"Fully supervised sentences   : "
    f"{BLOCK_2_SENTENCES_FULLY_FACTUALLY_SUPERVISED}"
)

print(
    f"Available target elements    : "
    f"{BLOCK_2_TOTAL_AVAILABLE_ELEMENTS}"
)

print(
    f"Possible target elements     : "
    f"{BLOCK_2_TOTAL_POSSIBLE_ELEMENTS}"
)

print(
    f"Aggregate target coverage    : "
    f"{BLOCK_2_TOTAL_TARGET_COVERAGE:.4f}"
)


for dimension_name in NOTEBOOK_06_FACTUAL_DIMENSION_ORDER:

    print(
        f"{dimension_name:<31}: "
        f"{BLOCK_2_DIMENSION_AVAILABLE_COUNTS[dimension_name]}"
        f" / "
        f"{BLOCK_2_DIMENSION_ELIGIBLE_COUNTS[dimension_name]}"
        f"  "
        f"coverage="
        f"{BLOCK_2_DIMENSION_COVERAGE[dimension_name]:.4f}"
    )


print("-" * 72)

print(
    "Masking and target semantics"
)

print(
    f"Mask-aware supervision       : "
    f"{NOTEBOOK_06_MASK_AWARE_SUPERVISION}"
)

print(
    f"Missing = zero               : "
    f"{NOTEBOOK_06_MISSING_EQUALS_ZERO}"
)

print(
    f"Missing = negative           : "
    f"{NOTEBOOK_06_MISSING_EQUALS_NEGATIVE}"
)

print(
    f"Unavailable enters loss      : "
    f"{NOTEBOOK_06_UNAVAILABLE_ENTERS_LOSS}"
)

print(
    f"Partial supervision allowed  : "
    f"{NOTEBOOK_06_PARTIAL_FACTUAL_SUPERVISION_ALLOWED}"
)

print(
    f"Loss contract resolved       : "
    f"{NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_RESOLVED}"
)

print(
    f"Activation contract resolved : "
    f"{NOTEBOOK_06_FACTUAL_ACTIVATION_CONTRACT_RESOLVED}"
)


print("-" * 72)

print(
    "Persistent factual target artefact"
)

print(
    f"Filename                     : "
    f"{NOTEBOOK_06_FACTUAL_TARGET_FILENAME}"
)

print(
    f"Local copy created           : "
    f"{BLOCK_2_LOCAL_FACTUAL_TARGET_CREATED}"
)

print(
    f"Drive operation              : "
    f"{NOTEBOOK_06_FACTUAL_TARGET_DRIVE_OPERATION}"
)

print(
    f"Drive file ID                : "
    f"{NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID}"
)

print(
    f"Read-back valid              : "
    f"{BLOCK_2_FACTUAL_TARGET_READBACK_VALID}"
)


print("-" * 72)

print(
    "Readiness"
)

print(
    f"Factual mapping resolved     : "
    f"{NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED}"
)

print(
    f"Target contract defined      : "
    f"{NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_DEFINED}"
)

print(
    f"Target contract valid        : "
    f"{NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID}"
)

print(
    f"Dataset constructible        : "
    f"{NOTEBOOK_06_FACTUAL_SUPERVISION_DATASET_CONSTRUCTIBLE}"
)

print(
    f"Factual optimisation ready   : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMISATION_READY}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Mapping performed            : "
    f"{NOTEBOOK_06_FACTUAL_TARGET_MAPPING_PERFORMED}"
)

print(
    f"Objectives activated         : "
    f"{NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED}"
)

print(
    f"Forward pass executed        : "
    f"{NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_06_FACTUAL_LOSS_CALCULATED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_06_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Factual training executed    : "
    f"{NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_06_BLOCK_2_VALID}"
)

print(
    f"Block 2 complete             : "
    f"{NOTEBOOK_06_BLOCK_2_COMPLETE}"
)


print("=" * 72)


print(
    "Notebook 06 factual supervision mapping and target-contract "
    "audit completed successfully."
)

print(
    "The ten-dimensional factual architecture now has ten explicitly "
    "defined factual semantics."
)

print(
    "Seven factual dimensions map directly to canonical Notebook 03 "
    "factological components."
)

print(
    "The original speculation_or_prediction construct has been preserved "
    "and refined prospectively into separate speculation and prediction "
    "dimensions without modifying Notebook 03."
)

print(
    "A positive combined source signal is not duplicated blindly; "
    "textually unresolved positive cases remain masked."
)

print(
    "Factological weight has been explicitly mapped to F10 as a "
    "Notebook 06 architectural mapping decision."
)

print(
    "No factual architectural dimension has been fabricated."
)

print(
    "Independent element-level masks preserve unavailable factual "
    "supervision and keep missing values distinct from numerical zero "
    "and negative evidence."
)

print(
    "The resolved factual target contract has been persisted separately "
    "from the canonical Notebook 03 supervision and verified by read-back."
)

print(
    "No factual objective, optimiser, loss calculation, backward pass, "
    "parameter update or factual training has been executed."
)

print(
    "Factual optimisation remains blocked until target availability, "
    "activation semantics and loss policy are explicitly validated."
)

print(
    "The next block may proceed to Factual Target Availability, "
    "Activation and Loss-Contract Analysis."
)

print("=" * 72)


# =============================================================================
# Display factual dimension audit
# =============================================================================

display(
    BLOCK_2_FACTUAL_DIMENSION_AUDIT
)

========================================================================
Media AI — Notebook 06, Block 2: Factual Supervision Mapping and Target-Contract Audit
========================================================================
Target-contract version      : 1.0
------------------------------------------------------------------------
Canonical factual supervision
Source artefact              : notebook_03_accepted_annotations.json
Source Drive file ID         : 1gYiCR-i_avGCwE5O9p921es8Mzbzhvyl
Accepted source records      : 54
Sentence IDs present         : True
Sentence IDs unique          : True
Canonical alignment valid    : True
------------------------------------------------------------------------
Ten-dimensional factual contract
Architectural dimensions     : 10
Semantic dimensions resolved : 10
Direct component mappings    : 7
Refined dimensions           : 2
Factological weight mappings : 1
Fabricated dimensions        : 0
Notebook 03 records modified : False
------------------------------------------------------------------------
Factual dimension order
F1                           : explicit_claim
F2                           : observation_or_event
F3                           : quantitative_information
F4                           : attribution
F5                           : evidence_reference
F6                           : certainty_statement
F7                           : uncertainty_statement
F8                           : speculation
F9                           : prediction
F10                          : factological_weight
------------------------------------------------------------------------
Speculation / prediction refinement
Canonical source field       : speculation_or_prediction
Blind duplication used       : False
Mutually exclusive           : False
Positive source records      : 5
Positive unresolved records  : 2
positive_source_prediction_cue_only: 2
positive_source_speculation_cue_only: 1
positive_source_textually_unresolved: 2
validated_combined_source_absence: 49
------------------------------------------------------------------------
Factual supervision coverage
Sentences                    : 54
Any supervision sentences    : 54
Fully supervised sentences   : 52
Available target elements    : 536
Possible target elements     : 540
Aggregate target coverage    : 0.9926
explicit_claim                 : 54 / 54  coverage=1.0000
observation_or_event           : 54 / 54  coverage=1.0000
quantitative_information       : 54 / 54  coverage=1.0000
attribution                    : 54 / 54  coverage=1.0000
evidence_reference             : 54 / 54  coverage=1.0000
certainty_statement            : 54 / 54  coverage=1.0000
uncertainty_statement          : 54 / 54  coverage=1.0000
speculation                    : 52 / 54  coverage=0.9630
prediction                     : 52 / 54  coverage=0.9630
factological_weight            : 54 / 54  coverage=1.0000
------------------------------------------------------------------------
Masking and target semantics
Mask-aware supervision       : True
Missing = zero               : False
Missing = negative           : False
Unavailable enters loss      : False
Partial supervision allowed  : True
Loss contract resolved       : False
Activation contract resolved : False
------------------------------------------------------------------------
Persistent factual target artefact
Filename                     : notebook_06_factual_target_contract.json
Local copy created           : True
Drive operation              : updated
Drive file ID                : 1FdTrV_2RoHDRn06JLSx367OD4HffDaAy
Read-back valid              : True
------------------------------------------------------------------------
Readiness
Factual mapping resolved     : True
Target contract defined      : True
Target contract valid        : True
Dataset constructible        : True
Factual optimisation ready   : False
------------------------------------------------------------------------
Execution boundary
Mapping performed            : True
Objectives activated         : False
Optimiser created            : False
Forward pass executed        : False
Loss calculated              : False
Backward pass executed       : False
Parameter update executed    : False
Factual training executed    : False
Psychological retraining     : False
Empirical validity           : False
Block valid                  : True
Block 2 complete             : True
========================================================================
Notebook 06 factual supervision mapping and target-contract audit completed successfully.
The ten-dimensional factual architecture now has ten explicitly defined factual semantics.
Seven factual dimensions map directly to canonical Notebook 03 factological components.
The original speculation_or_prediction construct has been preserved and refined prospectively into separate speculation and prediction dimensions without modifying Notebook 03.
A positive combined source signal is not duplicated blindly; textually unresolved positive cases remain masked.
Factological weight has been explicitly mapped to F10 as a Notebook 06 architectural mapping decision.
No factual architectural dimension has been fabricated.
Independent element-level masks preserve unavailable factual supervision and keep missing values distinct from numerical zero and negative evidence.
The resolved factual target contract has been persisted separately from the canonical Notebook 03 supervision and verified by read-back.
No factual objective, optimiser, loss calculation, backward pass, parameter update or factual training has been executed.
Factual optimisation remains blocked until target availability, activation semantics and loss policy are explicitly validated.
The next block may proceed to Factual Target Availability, Activation and Loss-Contract Analysis.
========================================================================

,dimension_id,dimension_index,target_name,mapping_type,source_field,available,eligible,coverage,minimum,maximum,fabricated
0,F1,0,explicit_claim,direct_notebook_03_component,explicit_claim,54,54,1.000000,0.0,1.0,False
1,F2,1,observation_or_event,direct_notebook_03_component,observation_or_event,54,54,1.000000,0.0,1.0,False
2,F3,2,quantitative_information,direct_notebook_03_component,quantitative_information,54,54,1.000000,0.0,1.0,False
3,F4,3,attribution,direct_notebook_03_component,attribution,54,54,1.000000,0.0,1.0,False
4,F5,4,evidence_reference,direct_notebook_03_component,evidence_reference,54,54,1.000000,0.0,1.0,False
5,F6,5,certainty_statement,direct_notebook_03_component,certainty_statement,54,54,1.000000,0.0,1.0,False
6,F7,6,uncertainty_statement,direct_notebook_03_component,uncertainty_statement,54,54,1.000000,0.0,1.0,False
7,F8,7,speculation,notebook_06_semantic_refinement,speculation_or_prediction,52,54,0.962963,0.0,1.0,False
8,F9,8,prediction,notebook_06_semantic_refinement,speculation_or_prediction,52,54,0.962963,0.0,1.0,False
9,F10,9,factological_weight,notebook_06_architectural_mapping,factological_weight,54,54,1.000000,0.1,0.9,False

## Block 3 — Factual Target Availability, Variability, Activation and Loss-Contract Analysis

This block evaluates whether the ten-dimensional factual target contract established in Block 2 provides sufficient and appropriate supervision for factual-head optimisation.

The block distinguishes **target availability from target informativeness**. A factual dimension may be fully observed while remaining unsuitable for optimisation if the available sample contains no target variation, extreme imbalance, or another supervision limitation. Full coverage therefore does not automatically activate a factual objective.

### Representation and context orientation

Media AI distinguishes three processing orientations:

1. **Sentence-level**  
   The prediction or supervision target belongs to one canonical sentence and can be evaluated at sentence level.

2. **Context-assisted sentence-level**  
   The prediction or supervision target still belongs to one canonical sentence, but permitted preceding textual context may be required to interpret references, attribution, uncertainty, temporal meaning, or other contextual dependencies.

3. **Sequence / text-level**  
   The represented construct belongs to, or emerges across, multiple sentences and therefore requires sequential, article-level, relational, recurrent, transformative, or group-conditioned processing.

Notebook 06 remains primarily **sentence-oriented**. Factual targets F1–F10 are attached to canonical sentence identities and remain sentence-level supervision targets. Where interpretation requires broader context, the target remains attached to the current sentence and only permitted preceding context may assist its interpretation.

Future article context must not be used. Sentence order remains causal, article boundaries remain explicit, and no information from a later sentence may be used to determine an earlier sentence target.

The distinction is therefore:

**prediction unit = canonical sentence**

**permitted interpretation context = current sentence plus validated preceding context where required**

This does not convert factual supervision into article-level classification.

Later Media AI components may use broader processing scopes. Social relationships may require context-assisted or text-level interpretation; transformative mechanisms operate across sentence transitions; recurrent states accumulate information through causal article sequences; and group-conditioned processing may operate over broader article or group context. Those mechanisms remain outside the current Notebook 06 optimisation scope.

### Factual target audit

For each factual dimension F1–F10, the block audits:

- supervision availability;
- observed and possible target elements;
- target coverage;
- number of unique observed values;
- minimum and maximum values;
- target variance;
- positive and negative observations where applicable;
- class balance for binary factual dimensions;
- continuous-value distribution for factological weight;
- whether sufficient target variation exists for optimisation;
- whether imbalance requires special handling;
- whether the dimension should be activated, deferred, or excluded from the current controlled factual objective.

The factual dimensions remain:

- **F1** — explicit claim
- **F2** — observation or event
- **F3** — quantitative information
- **F4** — attribution
- **F5** — evidence reference
- **F6** — certainty statement
- **F7** — uncertainty statement
- **F8** — speculation
- **F9** — prediction
- **F10** — factological weight

F1–F7 remain direct mappings from canonical Notebook 03 factological components. F8 and F9 remain the prospective Notebook 06 refinement of the original `speculation_or_prediction` supervision field. F10 remains the explicit Notebook 06 architectural mapping of `factological_weight`.

The canonical Notebook 03 records must not be modified.

### Activation policy

Semantic resolution, supervision availability and optimisation activation are treated as independent conditions.

A dimension may therefore be:

- semantically defined and available but inactive because it has no observed variation;
- available and variable but subject to imbalance safeguards;
- available, variable and eligible for controlled optimisation;
- unavailable or insufficiently supported and therefore masked or deferred.

Zero-variance targets must not be activated merely because they have complete coverage.

Highly imbalanced targets must be identified explicitly before activation. Imbalance handling must not fabricate observations, alter canonical labels, or convert missing supervision into negative examples.

The current sixteen-sentence dataset is a controlled architectural and training sample rather than evidence of population-level target distributions. Activation decisions made from this sample must therefore remain explicitly provisional.

### Loss-contract policy

The block determines the appropriate loss semantics for each target type without performing optimisation.

F1–F9 are treated as factual-content dimensions whose observed target semantics must be verified before selecting their supervised loss contract.

F10 is treated separately as a continuous factological-weight target.

Loss functions must respect independent element-level supervision masks. Missing or insufficient-evidence target elements must not enter the objective and must not be converted to numerical zero or negative supervision.

Any weighting introduced for target families or class imbalance must be explicit, reproducible and derived only from validated supervision. No synthetic balancing or fabricated factual targets are permitted.

### Execution boundary

This block is an audit and objective-policy block.

It may inspect the persisted factual target contract, calculate supervision statistics, determine provisional activation eligibility, and define the factual loss contract.

It must not:

- perform factual training;
- execute a backward pass;
- perform an optimiser step;
- update Media AI parameters;
- retrain the completed psychological path;
- activate factual, social, transformative, Transformative Weight, recurrent or group-conditioned components beyond the explicitly defined factual objective policy;
- construct synthetic supervision;
- use future sentence context;
- claim held-out performance, generalisation or empirical validity.

The completed psychological path remains frozen.

Successful completion of Block 3 establishes which factual dimensions may legitimately enter a controlled supervised factual objective and which must remain inactive or deferred. It does not itself constitute factual training or empirical validation.

In [4]:
# =============================================================================
# Media AI — Notebook 06
# Block 3: Factual Target Availability, Variability,
#          Activation and Loss-Contract Analysis
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json
import math

import numpy as np
import pandas as pd

from googleapiclient.http import (
    MediaIoBaseDownload,
    MediaIoBaseUpload,
)


# =============================================================================
# Dependency checks
# =============================================================================

required_block_1_objects = [
    "NOTEBOOK_06_BLOCK_1_COMPLETE",
    "NOTEBOOK_06_BLOCK_1_VALID",
    "NOTEBOOK_06_DRIVE_SERVICE",
    "NOTEBOOK_06_SENTENCE_COUNT",
    "NOTEBOOK_06_ARTICLE_COUNT",
    "NOTEBOOK_06_SENTENCE_IDS",
    "NOTEBOOK_06_MASK_AWARE_SUPERVISION",
    "NOTEBOOK_06_MISSING_EQUALS_ZERO",
    "NOTEBOOK_06_MISSING_EQUALS_NEGATIVE",
    "NOTEBOOK_06_UNAVAILABLE_ENTERS_LOSS",
    "NOTEBOOK_06_PARTIAL_FACTUAL_SUPERVISION_ALLOWED",
    "NOTEBOOK_06_FUTURE_CONTEXT_ALLOWED",
]


missing_block_1_objects = [
    object_name
    for object_name in required_block_1_objects
    if object_name not in globals()
]


if missing_block_1_objects:

    raise NameError(
        "Notebook 06 Block 1 is not initialised. "
        f"Missing: {missing_block_1_objects}"
    )


required_block_2_objects = [
    "NOTEBOOK_06_BLOCK_2_COMPLETE",
    "NOTEBOOK_06_BLOCK_2_VALID",
    "NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED",
    "NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_DEFINED",
    "NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID",
    "NOTEBOOK_06_FACTUAL_SUPERVISION_DATASET_CONSTRUCTIBLE",
    "NOTEBOOK_06_FACTUAL_TARGET_DIMENSION",
    "NOTEBOOK_06_FACTUAL_DIMENSION_IDS",
    "NOTEBOOK_06_FACTUAL_DIMENSION_ORDER",
    "NOTEBOOK_06_FACTUAL_DIMENSION_MAP",
    "NOTEBOOK_06_FACTUAL_TARGET_TYPES",
    "NOTEBOOK_06_FACTUAL_TARGET_FILENAME",
    "NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID",
    "BLOCK_2_FACTUAL_TARGET_READBACK_VALID",
]


missing_block_2_objects = [
    object_name
    for object_name in required_block_2_objects
    if object_name not in globals()
]


if missing_block_2_objects:

    raise NameError(
        "Notebook 06 Block 2 is not initialised. "
        f"Missing: {missing_block_2_objects}"
    )


if not NOTEBOOK_06_BLOCK_1_COMPLETE or not NOTEBOOK_06_BLOCK_1_VALID:

    raise ValueError(
        "Notebook 06 Block 1 must be complete and valid."
    )


if not NOTEBOOK_06_BLOCK_2_COMPLETE or not NOTEBOOK_06_BLOCK_2_VALID:

    raise ValueError(
        "Notebook 06 Block 2 must be complete and valid."
    )


if not NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED:

    raise ValueError(
        "Block 3 requires the factual semantic mapping to be resolved."
    )


if not NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID:

    raise ValueError(
        "Block 3 requires a valid factual target contract."
    )


if not NOTEBOOK_06_FACTUAL_SUPERVISION_DATASET_CONSTRUCTIBLE:

    raise ValueError(
        "Block 3 requires a constructible factual supervision dataset."
    )


if NOTEBOOK_06_FACTUAL_TARGET_DIMENSION != 10:

    raise ValueError(
        "Block 3 requires the validated ten-dimensional factual target."
    )


# =============================================================================
# Block configuration
# =============================================================================

NOTEBOOK_06_BLOCK_3 = 3

NOTEBOOK_06_BLOCK_3_NAME = (
    "Factual Target Availability, Variability, "
    "Activation and Loss-Contract Analysis"
)

NOTEBOOK_06_BLOCK_3_VERSION = "1.0"

NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VERSION = "1.0"

NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_FILENAME = (
    "notebook_06_factual_objective_policy.json"
)


BLOCK_3_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Audit thresholds
# =============================================================================
#
# These thresholds determine whether a dimension contains enough variation
# to enter the controlled factual objective.
#
# They do not establish population-level validity.
# =============================================================================

BLOCK_3_VARIANCE_TOLERANCE = 1e-12

BLOCK_3_BINARY_VALUE_TOLERANCE = 1e-8

BLOCK_3_MINIMUM_OBSERVED_ELEMENTS = 2

BLOCK_3_MINIMUM_BINARY_CLASS_COUNT = 2

BLOCK_3_IMBALANCE_RATIO_WARNING = 3.0


# =============================================================================
# Explicit execution boundary
# =============================================================================

NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DEFINED = False

NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED_FOR_TRAINING = False

NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED = False

NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED = False

NOTEBOOK_06_FACTUAL_LOSS_CALCULATED = False

NOTEBOOK_06_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_SOCIAL_PATH_ACTIVATED = False

NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ACTIVATED = False

NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ACTIVATED = False

NOTEBOOK_06_RECURRENT_STATES_ACTIVATED = False

NOTEBOOK_06_GROUPS_CONSTRUCTED = False

NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Drive download helper
# =============================================================================

def block_3_download_drive_bytes(
    drive_service,
    file_id,
):
    """
    Download one Google Drive file and return raw bytes.
    """

    request = (
        drive_service.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Reload persisted factual target artefact
# =============================================================================

BLOCK_3_FACTUAL_TARGET_BYTES = (
    block_3_download_drive_bytes(
        NOTEBOOK_06_DRIVE_SERVICE,
        NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID,
    )
)


if not BLOCK_3_FACTUAL_TARGET_BYTES:

    raise ValueError(
        "Persisted Block 2 factual target artefact could not be loaded."
    )


BLOCK_3_FACTUAL_TARGET_ARTEFACT = json.loads(
    BLOCK_3_FACTUAL_TARGET_BYTES.decode(
        "utf-8"
    )
)


if not isinstance(
    BLOCK_3_FACTUAL_TARGET_ARTEFACT,
    dict,
):

    raise TypeError(
        "Persisted factual target artefact is not a JSON object."
    )


# =============================================================================
# Persisted contract validation
# =============================================================================

BLOCK_3_PERSISTED_FACTUAL_DIMENSION = int(
    BLOCK_3_FACTUAL_TARGET_ARTEFACT[
        "architecture"
    ][
        "factual_dimension"
    ]
)


BLOCK_3_PERSISTED_DIMENSION_IDS = tuple(
    BLOCK_3_FACTUAL_TARGET_ARTEFACT[
        "architecture"
    ][
        "dimension_ids"
    ]
)


BLOCK_3_PERSISTED_DIMENSION_ORDER = tuple(
    BLOCK_3_FACTUAL_TARGET_ARTEFACT[
        "architecture"
    ][
        "dimension_order"
    ]
)


BLOCK_3_PERSISTED_MAPPING_RESOLVED = (
    BLOCK_3_FACTUAL_TARGET_ARTEFACT[
        "training_boundary"
    ][
        "mapping_resolved"
    ]
    is True
)


BLOCK_3_PERSISTED_TARGET_CONTRACT_DEFINED = (
    BLOCK_3_FACTUAL_TARGET_ARTEFACT[
        "training_boundary"
    ][
        "target_contract_defined"
    ]
    is True
)


BLOCK_3_PERSISTED_CONTRACT_VALID = all(
    [
        BLOCK_3_PERSISTED_FACTUAL_DIMENSION
        == 10,

        BLOCK_3_PERSISTED_DIMENSION_IDS
        ==
        tuple(
            NOTEBOOK_06_FACTUAL_DIMENSION_IDS
        ),

        BLOCK_3_PERSISTED_DIMENSION_ORDER
        ==
        tuple(
            NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
        ),

        BLOCK_3_PERSISTED_MAPPING_RESOLVED,

        BLOCK_3_PERSISTED_TARGET_CONTRACT_DEFINED,

        BLOCK_2_FACTUAL_TARGET_READBACK_VALID,
    ]
)


if not BLOCK_3_PERSISTED_CONTRACT_VALID:

    raise ValueError(
        "Persisted Block 2 factual target contract is inconsistent "
        "with the current Notebook 06 runtime."
    )


# =============================================================================
# Resolve factual records
# =============================================================================

BLOCK_3_FACTUAL_RECORDS = (
    BLOCK_3_FACTUAL_TARGET_ARTEFACT[
        "records"
    ]
)


BLOCK_3_FACTUAL_RECORD_COUNT = len(
    BLOCK_3_FACTUAL_RECORDS
)


if BLOCK_3_FACTUAL_RECORD_COUNT != NOTEBOOK_06_SENTENCE_COUNT:

    raise ValueError(
        "Persisted factual target record count does not match the "
        "Notebook 06 canonical sentence count."
    )


# =============================================================================
# Canonical identity validation
# =============================================================================

BLOCK_3_FACTUAL_SENTENCE_IDS = [
    record[
        "identity"
    ][
        "sentence_id"
    ]

    for record
    in BLOCK_3_FACTUAL_RECORDS
]


BLOCK_3_FACTUAL_SENTENCE_IDS_UNIQUE = (
    len(
        BLOCK_3_FACTUAL_SENTENCE_IDS
    )
    ==
    len(
        set(
            BLOCK_3_FACTUAL_SENTENCE_IDS
        )
    )
)


BLOCK_3_FACTUAL_SENTENCE_ALIGNMENT_VALID = (
    set(
        BLOCK_3_FACTUAL_SENTENCE_IDS
    )
    ==
    set(
        NOTEBOOK_06_SENTENCE_IDS
    )
)


if not BLOCK_3_FACTUAL_SENTENCE_IDS_UNIQUE:

    raise ValueError(
        "Block 3 factual target sentence IDs are not unique."
    )


if not BLOCK_3_FACTUAL_SENTENCE_ALIGNMENT_VALID:

    raise ValueError(
        "Block 3 factual target identities do not align with the "
        "Notebook 06 canonical sentence contract."
    )


# =============================================================================
# Reconstruct target and mask matrices
# =============================================================================

BLOCK_3_FACTUAL_TARGET_MATRIX = np.asarray(
    [
        record[
            "factual_target"
        ]

        for record
        in BLOCK_3_FACTUAL_RECORDS
    ],
    dtype=np.float64,
)


BLOCK_3_FACTUAL_MASK_MATRIX = np.asarray(
    [
        record[
            "factual_target_mask"
        ]

        for record
        in BLOCK_3_FACTUAL_RECORDS
    ],
    dtype=bool,
)


BLOCK_3_EXPECTED_MATRIX_SHAPE = (
    BLOCK_3_FACTUAL_RECORD_COUNT,
    10,
)


BLOCK_3_TARGET_MATRIX_SHAPE_VALID = (
    BLOCK_3_FACTUAL_TARGET_MATRIX.shape
    ==
    BLOCK_3_EXPECTED_MATRIX_SHAPE
)


BLOCK_3_MASK_MATRIX_SHAPE_VALID = (
    BLOCK_3_FACTUAL_MASK_MATRIX.shape
    ==
    BLOCK_3_EXPECTED_MATRIX_SHAPE
)


if not BLOCK_3_TARGET_MATRIX_SHAPE_VALID:

    raise ValueError(
        "Block 3 factual target matrix shape is invalid."
    )


if not BLOCK_3_MASK_MATRIX_SHAPE_VALID:

    raise ValueError(
        "Block 3 factual target mask matrix shape is invalid."
    )


BLOCK_3_OBSERVED_VALUES_FINITE = bool(
    np.isfinite(
        BLOCK_3_FACTUAL_TARGET_MATRIX[
            BLOCK_3_FACTUAL_MASK_MATRIX
        ]
    ).all()
)


if not BLOCK_3_OBSERVED_VALUES_FINITE:

    raise ValueError(
        "Block 3 detected non-finite observed factual target values."
    )


# =============================================================================
# Target-type helper
# =============================================================================

def block_3_values_are_binary(
    values,
):
    """
    Determine whether all observed values are numerically equivalent
    to zero or one.
    """

    if len(
        values
    ) == 0:

        return False


    zero_or_one = np.logical_or(
        np.isclose(
            values,
            0.0,
            atol=
                BLOCK_3_BINARY_VALUE_TOLERANCE,
        ),
        np.isclose(
            values,
            1.0,
            atol=
                BLOCK_3_BINARY_VALUE_TOLERANCE,
        ),
    )


    return bool(
        zero_or_one.all()
    )


# =============================================================================
# Per-dimension availability and variability audit
# =============================================================================

BLOCK_3_DIMENSION_STATISTICS = {}

BLOCK_3_DIMENSION_ROWS = []


for dimension_index, (
    dimension_id,
    dimension_name,
) in enumerate(
    zip(
        NOTEBOOK_06_FACTUAL_DIMENSION_IDS,
        NOTEBOOK_06_FACTUAL_DIMENSION_ORDER,
    )
):

    dimension_mask = (
        BLOCK_3_FACTUAL_MASK_MATRIX[
            :,
            dimension_index,
        ]
    )


    observed_values = (
        BLOCK_3_FACTUAL_TARGET_MATRIX[
            dimension_mask,
            dimension_index,
        ]
    )


    observed_count = int(
        dimension_mask.sum()
    )


    possible_count = int(
        len(
            dimension_mask
        )
    )


    coverage = (
        observed_count
        /
        possible_count
        if possible_count > 0
        else 0.0
    )


    if observed_count > 0:

        unique_values = np.unique(
            observed_values
        )


        unique_count = int(
            len(
                unique_values
            )
        )


        minimum = float(
            observed_values.min()
        )


        maximum = float(
            observed_values.max()
        )


        mean_value = float(
            observed_values.mean()
        )


        variance = float(
            observed_values.var(
                ddof=0
            )
        )


    else:

        unique_values = np.asarray(
            [],
            dtype=np.float64,
        )


        unique_count = 0

        minimum = None

        maximum = None

        mean_value = None

        variance = None


    zero_variance = (
        observed_count > 0
        and variance is not None
        and variance
        <= BLOCK_3_VARIANCE_TOLERANCE
    )


    variable_target = (
        observed_count
        >= BLOCK_3_MINIMUM_OBSERVED_ELEMENTS
        and not zero_variance
        and unique_count >= 2
    )


    binary_target = (
        block_3_values_are_binary(
            observed_values
        )
    )


    # -------------------------------------------------------------------------
    # Binary statistics
    # -------------------------------------------------------------------------

    positive_count = None

    negative_count = None

    minority_class_count = None

    majority_class_count = None

    imbalance_ratio = None

    imbalance_warning = False

    recommended_positive_weight = None


    if binary_target:

        positive_count = int(
            np.isclose(
                observed_values,
                1.0,
                atol=
                    BLOCK_3_BINARY_VALUE_TOLERANCE,
            ).sum()
        )


        negative_count = int(
            np.isclose(
                observed_values,
                0.0,
                atol=
                    BLOCK_3_BINARY_VALUE_TOLERANCE,
            ).sum()
        )


        minority_class_count = min(
            positive_count,
            negative_count,
        )


        majority_class_count = max(
            positive_count,
            negative_count,
        )


        if minority_class_count > 0:

            imbalance_ratio = float(
                majority_class_count
                /
                minority_class_count
            )


            imbalance_warning = (
                imbalance_ratio
                >
                BLOCK_3_IMBALANCE_RATIO_WARNING
            )


        if positive_count > 0:

            recommended_positive_weight = float(
                negative_count
                /
                positive_count
            )


    # -------------------------------------------------------------------------
    # Target family
    # -------------------------------------------------------------------------

    if dimension_name == "factological_weight":

        target_family = (
            "continuous_weight"
        )


    elif binary_target:

        target_family = (
            "binary_factological_content"
        )


    else:

        target_family = (
            "continuous_factological_content"
        )


    # -------------------------------------------------------------------------
    # Activation decision
    # -------------------------------------------------------------------------

    if observed_count == 0:

        activation_state = (
            "inactive_unavailable"
        )

        training_eligible = False

        activation_reason = (
            "no_observed_supervision"
        )


    elif zero_variance:

        activation_state = (
            "deferred_zero_variance"
        )

        training_eligible = False

        activation_reason = (
            "observed_supervision_has_no_target_variation"
        )


    elif binary_target:

        if (
            minority_class_count
            is None
            or minority_class_count
            <
            BLOCK_3_MINIMUM_BINARY_CLASS_COUNT
        ):

            activation_state = (
                "deferred_insufficient_class_support"
            )

            training_eligible = False

            activation_reason = (
                "binary_target_has_insufficient_minority_class_support"
            )


        else:

            activation_state = (
                "eligible_with_imbalance_caution"
                if imbalance_warning
                else "eligible"
            )

            training_eligible = True

            activation_reason = (
                "binary_target_has_observed_variation_and_class_support"
            )


    else:

        if variable_target:

            activation_state = (
                "eligible"
            )

            training_eligible = True

            activation_reason = (
                "continuous_target_has_observed_variation"
            )


        else:

            activation_state = (
                "deferred_insufficient_variation"
            )

            training_eligible = False

            activation_reason = (
                "continuous_target_has_insufficient_variation"
            )


    # -------------------------------------------------------------------------
    # Loss contract
    # -------------------------------------------------------------------------

    if not training_eligible:

        loss_family = (
            "none"
        )

        loss_active = False

        class_weighting_policy = (
            "not_applicable"
        )


    elif target_family == (
        "binary_factological_content"
    ):

        loss_family = (
            "binary_cross_entropy_with_logits"
        )

        loss_active = True


        if imbalance_warning:

            class_weighting_policy = (
                "positive_class_weight_recommended"
            )

        else:

            class_weighting_policy = (
                "unweighted_binary_cross_entropy"
            )


    else:

        loss_family = (
            "masked_mean_squared_error"
        )

        loss_active = True

        class_weighting_policy = (
            "not_applicable"
        )


    BLOCK_3_DIMENSION_STATISTICS[
        dimension_name
    ] = {
        "dimension_id":
            dimension_id,

        "dimension_index":
            int(
                dimension_index
            ),

        "observed_count":
            observed_count,

        "possible_count":
            possible_count,

        "coverage":
            float(
                coverage
            ),

        "unique_count":
            unique_count,

        "unique_values":
            unique_values.tolist(),

        "minimum":
            minimum,

        "maximum":
            maximum,

        "mean":
            mean_value,

        "variance":
            variance,

        "zero_variance":
            bool(
                zero_variance
            ),

        "variable_target":
            bool(
                variable_target
            ),

        "binary_target":
            bool(
                binary_target
            ),

        "positive_count":
            positive_count,

        "negative_count":
            negative_count,

        "minority_class_count":
            minority_class_count,

        "majority_class_count":
            majority_class_count,

        "imbalance_ratio":
            imbalance_ratio,

        "imbalance_warning":
            bool(
                imbalance_warning
            ),

        "recommended_positive_weight":
            recommended_positive_weight,

        "target_family":
            target_family,

        "activation_state":
            activation_state,

        "training_eligible":
            bool(
                training_eligible
            ),

        "activation_reason":
            activation_reason,

        "loss_family":
            loss_family,

        "loss_active":
            bool(
                loss_active
            ),

        "class_weighting_policy":
            class_weighting_policy,
    }


    BLOCK_3_DIMENSION_ROWS.append(
        {
            "dimension_id":
                dimension_id,

            "target_name":
                dimension_name,

            "observed":
                observed_count,

            "possible":
                possible_count,

            "coverage":
                float(
                    coverage
                ),

            "unique_values":
                unique_count,

            "variance":
                variance,

            "positive":
                positive_count,

            "negative":
                negative_count,

            "imbalance_ratio":
                imbalance_ratio,

            "training_eligible":
                bool(
                    training_eligible
                ),

            "activation_state":
                activation_state,

            "loss_family":
                loss_family,
        }
    )


# =============================================================================
# Dimension-level activation sets
# =============================================================================

NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS = tuple(
    dimension_name

    for dimension_name
    in NOTEBOOK_06_FACTUAL_DIMENSION_ORDER

    if BLOCK_3_DIMENSION_STATISTICS[
        dimension_name
    ][
        "training_eligible"
    ]
)


NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS = tuple(
    dimension_name

    for dimension_name
    in NOTEBOOK_06_FACTUAL_DIMENSION_ORDER

    if not BLOCK_3_DIMENSION_STATISTICS[
        dimension_name
    ][
        "training_eligible"
    ]
)


NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSION_IDS = tuple(
    BLOCK_3_DIMENSION_STATISTICS[
        dimension_name
    ][
        "dimension_id"
    ]

    for dimension_name
    in NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS
)


NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSION_IDS = tuple(
    BLOCK_3_DIMENSION_STATISTICS[
        dimension_name
    ][
        "dimension_id"
    ]

    for dimension_name
    in NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS
)


# =============================================================================
# Active binary and continuous targets
# =============================================================================

NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS = tuple(
    dimension_name

    for dimension_name
    in NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS

    if BLOCK_3_DIMENSION_STATISTICS[
        dimension_name
    ][
        "target_family"
    ]
    ==
    "binary_factological_content"
)


NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS = tuple(
    dimension_name

    for dimension_name
    in NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS

    if BLOCK_3_DIMENSION_STATISTICS[
        dimension_name
    ][
        "target_family"
    ]
    !=
    "binary_factological_content"
)


# =============================================================================
# Zero-variance audit
# =============================================================================

BLOCK_3_ZERO_VARIANCE_DIMENSIONS = tuple(
    dimension_name

    for dimension_name
    in NOTEBOOK_06_FACTUAL_DIMENSION_ORDER

    if BLOCK_3_DIMENSION_STATISTICS[
        dimension_name
    ][
        "zero_variance"
    ]
)


BLOCK_3_VARIABLE_DIMENSIONS = tuple(
    dimension_name

    for dimension_name
    in NOTEBOOK_06_FACTUAL_DIMENSION_ORDER

    if BLOCK_3_DIMENSION_STATISTICS[
        dimension_name
    ][
        "variable_target"
    ]
)


BLOCK_3_IMBALANCED_ACTIVE_DIMENSIONS = tuple(
    dimension_name

    for dimension_name
    in NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS

    if BLOCK_3_DIMENSION_STATISTICS[
        dimension_name
    ][
        "imbalance_warning"
    ]
)


# =============================================================================
# Recommended positive-class weights
# =============================================================================

NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS = {
    dimension_name:
        BLOCK_3_DIMENSION_STATISTICS[
            dimension_name
        ][
            "recommended_positive_weight"
        ]

    for dimension_name
    in NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS

    if (
        BLOCK_3_DIMENSION_STATISTICS[
            dimension_name
        ][
            "imbalance_warning"
        ]
        and
        BLOCK_3_DIMENSION_STATISTICS[
            dimension_name
        ][
            "recommended_positive_weight"
        ]
        is not None
    )
}


# =============================================================================
# Loss-contract definition
# =============================================================================

NOTEBOOK_06_FACTUAL_LOSS_CONTRACT = {
    dimension_name:
        {
            "dimension_id":
                BLOCK_3_DIMENSION_STATISTICS[
                    dimension_name
                ][
                    "dimension_id"
                ],

            "target_family":
                BLOCK_3_DIMENSION_STATISTICS[
                    dimension_name
                ][
                    "target_family"
                ],

            "training_eligible":
                BLOCK_3_DIMENSION_STATISTICS[
                    dimension_name
                ][
                    "training_eligible"
                ],

            "activation_state":
                BLOCK_3_DIMENSION_STATISTICS[
                    dimension_name
                ][
                    "activation_state"
                ],

            "loss_family":
                BLOCK_3_DIMENSION_STATISTICS[
                    dimension_name
                ][
                    "loss_family"
                ],

            "mask_required":
                True,

            "class_weighting_policy":
                BLOCK_3_DIMENSION_STATISTICS[
                    dimension_name
                ][
                    "class_weighting_policy"
                ],

            "recommended_positive_weight":
                BLOCK_3_DIMENSION_STATISTICS[
                    dimension_name
                ][
                    "recommended_positive_weight"
                ],
        }

    for dimension_name
    in NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
}


NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_RESOLVED = True

NOTEBOOK_06_FACTUAL_ACTIVATION_CONTRACT_RESOLVED = True

NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DEFINED = True


# =============================================================================
# Objective policy
# =============================================================================
#
# "Active" here means eligible for inclusion in the later controlled
# supervised factual objective.
#
# It does NOT mean that a forward pass or optimiser is executed here.
# =============================================================================

NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY = {
    "policy_version":
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VERSION,

    "active_dimensions":
        list(
            NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS
        ),

    "active_dimension_ids":
        list(
            NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSION_IDS
        ),

    "deferred_dimensions":
        list(
            NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS
        ),

    "deferred_dimension_ids":
        list(
            NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSION_IDS
        ),

    "active_binary_dimensions":
        list(
            NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS
        ),

    "active_continuous_dimensions":
        list(
            NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS
        ),

    "zero_variance_dimensions":
        list(
            BLOCK_3_ZERO_VARIANCE_DIMENSIONS
        ),

    "imbalanced_active_dimensions":
        list(
            BLOCK_3_IMBALANCED_ACTIVE_DIMENSIONS
        ),

    "positive_class_weights":
        deepcopy(
            NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS
        ),

    "dimension_contract":
        deepcopy(
            NOTEBOOK_06_FACTUAL_LOSS_CONTRACT
        ),

    "mask_aware":
        True,

    "missing_equals_zero":
        False,

    "missing_equals_negative":
        False,

    "unavailable_enters_loss":
        False,

    "future_context_allowed":
        False,

    "training_executed":
        False,

    "empirical_validity":
        False,
}


# =============================================================================
# Readiness classification
# =============================================================================

BLOCK_3_ACTIVE_DIMENSION_COUNT = len(
    NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS
)


BLOCK_3_DEFERRED_DIMENSION_COUNT = len(
    NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS
)


BLOCK_3_ZERO_VARIANCE_DIMENSION_COUNT = len(
    BLOCK_3_ZERO_VARIANCE_DIMENSIONS
)


BLOCK_3_IMBALANCED_ACTIVE_DIMENSION_COUNT = len(
    BLOCK_3_IMBALANCED_ACTIVE_DIMENSIONS
)


NOTEBOOK_06_FACTUAL_OBJECTIVE_HAS_ACTIVE_TARGETS = (
    BLOCK_3_ACTIVE_DIMENSION_COUNT > 0
)


NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID = all(
    [
        NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_RESOLVED,
        NOTEBOOK_06_FACTUAL_ACTIVATION_CONTRACT_RESOLVED,
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DEFINED,
        NOTEBOOK_06_FACTUAL_OBJECTIVE_HAS_ACTIVE_TARGETS,
        NOTEBOOK_06_MASK_AWARE_SUPERVISION,
        not NOTEBOOK_06_MISSING_EQUALS_ZERO,
        not NOTEBOOK_06_MISSING_EQUALS_NEGATIVE,
        not NOTEBOOK_06_UNAVAILABLE_ENTERS_LOSS,
        not NOTEBOOK_06_FUTURE_CONTEXT_ALLOWED,
    ]
)


if not NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID:

    raise ValueError(
        "Notebook 06 factual objective policy is invalid."
    )


# =============================================================================
# Factual optimisation readiness
# =============================================================================
#
# Mapping + activation + loss semantics are now resolved.
#
# Actual optimisation still requires:
#   - factual-head parameter policy;
#   - validated factual model output contract;
#   - controlled forward-path validation;
#   - optimiser policy.
# =============================================================================

NOTEBOOK_06_FACTUAL_TARGET_POLICY_READY = True

NOTEBOOK_06_FACTUAL_OPTIMISATION_READY = False


# =============================================================================
# Construct persistent objective-policy artefact
# =============================================================================

NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_ARTEFACT = {
    "artefact_type":
        "media_ai_factual_objective_policy",

    "artefact_version":
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VERSION,

    "created_at_utc":
        BLOCK_3_EXECUTED_AT_UTC,

    "source_target_artefact":
        {
            "filename":
                NOTEBOOK_06_FACTUAL_TARGET_FILENAME,

            "drive_file_id":
                NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID,
        },

    "representation_orientation":
        {
            "prediction_unit":
                "sentence",

            "context_mode":
                "sentence_or_context_assisted_sentence",

            "preceding_context_allowed":
                True,

            "future_context_allowed":
                False,

            "article_level_target":
                False,
        },

    "audit_thresholds":
        {
            "variance_tolerance":
                BLOCK_3_VARIANCE_TOLERANCE,

            "minimum_observed_elements":
                BLOCK_3_MINIMUM_OBSERVED_ELEMENTS,

            "minimum_binary_class_count":
                BLOCK_3_MINIMUM_BINARY_CLASS_COUNT,

            "imbalance_ratio_warning":
                BLOCK_3_IMBALANCE_RATIO_WARNING,
        },

    "dimension_statistics":
        deepcopy(
            BLOCK_3_DIMENSION_STATISTICS
        ),

    "objective_policy":
        deepcopy(
            NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY
        ),

    "readiness":
        {
            "mapping_resolved":
                True,

            "target_contract_valid":
                True,

            "activation_contract_resolved":
                True,

            "loss_contract_resolved":
                True,

            "target_policy_ready":
                True,

            "factual_optimisation_ready":
                False,

            "optimizer_created":
                False,

            "training_executed":
                False,

            "empirical_validity":
                False,
        },
}


# =============================================================================
# JSON serialisation helper
# =============================================================================

def block_3_json_default(
    value,
):
    """
    Convert common NumPy values to JSON-safe values.
    """

    if isinstance(
        value,
        np.generic,
    ):

        return value.item()


    if isinstance(
        value,
        np.ndarray,
    ):

        return value.tolist()


    if isinstance(
        value,
        set,
    ):

        return sorted(
            value
        )


    if isinstance(
        value,
        tuple,
    ):

        return list(
            value
        )


    raise TypeError(
        f"Object of type {type(value).__name__} "
        "is not JSON serialisable."
    )


NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_JSON = json.dumps(
    NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_ARTEFACT,
    indent=2,
    ensure_ascii=False,
    default=
        block_3_json_default,
)


BLOCK_3_OBJECTIVE_POLICY_JSON_VALID = bool(
    NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_JSON
)


if not BLOCK_3_OBJECTIVE_POLICY_JSON_VALID:

    raise ValueError(
        "Notebook 06 factual objective policy could not be serialised."
    )


# =============================================================================
# Local persistence
# =============================================================================

with open(
    NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_FILENAME,
    "w",
    encoding="utf-8",
) as objective_policy_file:

    objective_policy_file.write(
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_JSON
    )


BLOCK_3_LOCAL_OBJECTIVE_POLICY_CREATED = True


# =============================================================================
# Resolve parent folder
# =============================================================================

BLOCK_3_FACTUAL_TARGET_DRIVE_METADATA = (
    NOTEBOOK_06_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID,
        fields=
            "id,name,parents",
    )
    .execute()
)


BLOCK_3_PARENT_IDS = (
    BLOCK_3_FACTUAL_TARGET_DRIVE_METADATA.get(
        "parents",
        [],
    )
)


# =============================================================================
# Drive persistence helper
# =============================================================================

def block_3_persist_json_to_drive(
    drive_service,
    filename,
    json_text,
    parent_ids=None,
):
    """
    Create or update one exact-name JSON artefact in Google Drive.
    """

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )


    search_response = (
        drive_service.files()
        .list(
            q=(
                f"name = '{escaped_filename}' "
                "and trashed = false"
            ),
            spaces=
                "drive",
            fields=
                "files(id,name,modifiedTime,parents)",
            orderBy=
                "modifiedTime desc",
            pageSize=
                20,
        )
        .execute()
    )


    matching_files = search_response.get(
        "files",
        [],
    )


    media = MediaIoBaseUpload(
        io.BytesIO(
            json_text.encode(
                "utf-8"
            )
        ),
        mimetype=
            "application/json",
        resumable=
            False,
    )


    if matching_files:

        drive_file = (
            drive_service.files()
            .update(
                fileId=
                    matching_files[
                        0
                    ][
                        "id"
                    ],
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = (
            "updated"
        )


    else:

        metadata = {
            "name":
                filename
        }


        if parent_ids:

            metadata[
                "parents"
            ] = parent_ids


        drive_file = (
            drive_service.files()
            .create(
                body=
                    metadata,
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = (
            "created"
        )


    return (
        drive_file,
        operation,
    )


(
    NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DRIVE_FILE,
    NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DRIVE_OPERATION,
) = block_3_persist_json_to_drive(
    drive_service=
        NOTEBOOK_06_DRIVE_SERVICE,
    filename=
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_FILENAME,
    json_text=
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_JSON,
    parent_ids=
        BLOCK_3_PARENT_IDS,
)


NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DRIVE_FILE_ID = (
    NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DRIVE_FILE.get(
        "id"
    )
)


BLOCK_3_OBJECTIVE_POLICY_DRIVE_PERSISTED = bool(
    NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DRIVE_FILE_ID
)


if not BLOCK_3_OBJECTIVE_POLICY_DRIVE_PERSISTED:

    raise RuntimeError(
        "Notebook 06 factual objective policy was not persisted "
        "to Google Drive."
    )


# =============================================================================
# Read-back validation
# =============================================================================

BLOCK_3_RELOADED_POLICY_BYTES = (
    block_3_download_drive_bytes(
        NOTEBOOK_06_DRIVE_SERVICE,
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DRIVE_FILE_ID,
    )
)


BLOCK_3_RELOADED_POLICY = json.loads(
    BLOCK_3_RELOADED_POLICY_BYTES.decode(
        "utf-8"
    )
)


BLOCK_3_READBACK_VERSION_VALID = (
    BLOCK_3_RELOADED_POLICY.get(
        "artefact_version"
    )
    ==
    NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VERSION
)


BLOCK_3_READBACK_ACTIVE_DIMENSIONS_VALID = (
    tuple(
        BLOCK_3_RELOADED_POLICY[
            "objective_policy"
        ][
            "active_dimensions"
        ]
    )
    ==
    NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS
)


BLOCK_3_READBACK_DEFERRED_DIMENSIONS_VALID = (
    tuple(
        BLOCK_3_RELOADED_POLICY[
            "objective_policy"
        ][
            "deferred_dimensions"
        ]
    )
    ==
    NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS
)


BLOCK_3_READBACK_NO_TRAINING = (
    BLOCK_3_RELOADED_POLICY[
        "readiness"
    ][
        "training_executed"
    ]
    is False
)


BLOCK_3_READBACK_NO_EMPIRICAL_VALIDITY = (
    BLOCK_3_RELOADED_POLICY[
        "readiness"
    ][
        "empirical_validity"
    ]
    is False
)


BLOCK_3_OBJECTIVE_POLICY_READBACK_VALID = all(
    [
        BLOCK_3_READBACK_VERSION_VALID,
        BLOCK_3_READBACK_ACTIVE_DIMENSIONS_VALID,
        BLOCK_3_READBACK_DEFERRED_DIMENSIONS_VALID,
        BLOCK_3_READBACK_NO_TRAINING,
        BLOCK_3_READBACK_NO_EMPIRICAL_VALIDITY,
    ]
)


if not BLOCK_3_OBJECTIVE_POLICY_READBACK_VALID:

    raise RuntimeError(
        "Persisted Notebook 06 factual objective policy failed "
        "read-back validation."
    )


# =============================================================================
# Execution-state finalisation
# =============================================================================

NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED_FOR_TRAINING = False

NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED = False

NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED = False

NOTEBOOK_06_FACTUAL_LOSS_CALCULATED = False

NOTEBOOK_06_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Final Block 3 validation
# =============================================================================

NOTEBOOK_06_BLOCK_3_ERRORS = []


if not BLOCK_3_PERSISTED_CONTRACT_VALID:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "persisted_factual_contract_invalid"
    )


if not BLOCK_3_FACTUAL_SENTENCE_ALIGNMENT_VALID:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_sentence_alignment_invalid"
    )


if not BLOCK_3_TARGET_MATRIX_SHAPE_VALID:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_target_matrix_shape_invalid"
    )


if not BLOCK_3_MASK_MATRIX_SHAPE_VALID:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_mask_matrix_shape_invalid"
    )


if not BLOCK_3_OBSERVED_VALUES_FINITE:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "observed_factual_values_nonfinite"
    )


if not NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DEFINED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_objective_policy_not_defined"
    )


if not NOTEBOOK_06_FACTUAL_ACTIVATION_CONTRACT_RESOLVED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_activation_contract_not_resolved"
    )


if not NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_RESOLVED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_loss_contract_not_resolved"
    )


if not NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_objective_policy_invalid"
    )


if not NOTEBOOK_06_FACTUAL_TARGET_POLICY_READY:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_target_policy_not_ready"
    )


if NOTEBOOK_06_FACTUAL_OPTIMISATION_READY:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_optimisation_incorrectly_marked_ready"
    )


if NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED_FOR_TRAINING:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_objectives_incorrectly_executed"
    )


if NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_optimizer_incorrectly_created"
    )


if NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_forward_pass_incorrectly_executed"
    )


if NOTEBOOK_06_FACTUAL_LOSS_CALCULATED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_loss_incorrectly_calculated"
    )


if NOTEBOOK_06_BACKWARD_PASS_EXECUTED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "backward_pass_incorrectly_executed"
    )


if NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "parameter_update_incorrectly_executed"
    )


if NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_training_incorrectly_executed"
    )


if NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "psychological_training_incorrectly_executed"
    )


if NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "held_out_evaluation_incorrectly_executed"
    )


if NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "empirical_validity_incorrectly_asserted"
    )


if not BLOCK_3_OBJECTIVE_POLICY_DRIVE_PERSISTED:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_objective_policy_not_persisted"
    )


if not BLOCK_3_OBJECTIVE_POLICY_READBACK_VALID:

    NOTEBOOK_06_BLOCK_3_ERRORS.append(
        "factual_objective_policy_readback_invalid"
    )


NOTEBOOK_06_BLOCK_3_VALID = (
    len(
        NOTEBOOK_06_BLOCK_3_ERRORS
    )
    == 0
)


if not NOTEBOOK_06_BLOCK_3_VALID:

    raise RuntimeError(
        "Notebook 06 Block 3 factual objective-policy audit failed. "
        f"Errors: {NOTEBOOK_06_BLOCK_3_ERRORS}"
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_06_READY_FOR_FACTUAL_MODEL_AND_PARAMETER_POLICY = True

NOTEBOOK_06_BLOCK_3_COMPLETE = True


# =============================================================================
# Audit dataframe
# =============================================================================

BLOCK_3_FACTUAL_ACTIVATION_AUDIT = pd.DataFrame(
    BLOCK_3_DIMENSION_ROWS
)


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_06_BLOCK_3_SUMMARY = {
    "block":
        NOTEBOOK_06_BLOCK_3,

    "block_name":
        NOTEBOOK_06_BLOCK_3_NAME,

    "version":
        NOTEBOOK_06_BLOCK_3_VERSION,

    "executed_at_utc":
        BLOCK_3_EXECUTED_AT_UTC,

    "factual_dimension_count":
        len(
            NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
        ),

    "active_dimension_count":
        BLOCK_3_ACTIVE_DIMENSION_COUNT,

    "active_dimensions":
        list(
            NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS
        ),

    "deferred_dimension_count":
        BLOCK_3_DEFERRED_DIMENSION_COUNT,

    "deferred_dimensions":
        list(
            NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS
        ),

    "zero_variance_dimensions":
        list(
            BLOCK_3_ZERO_VARIANCE_DIMENSIONS
        ),

    "imbalanced_active_dimensions":
        list(
            BLOCK_3_IMBALANCED_ACTIVE_DIMENSIONS
        ),

    "positive_class_weights":
        deepcopy(
            NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS
        ),

    "loss_contract_resolved":
        NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_RESOLVED,

    "activation_contract_resolved":
        NOTEBOOK_06_FACTUAL_ACTIVATION_CONTRACT_RESOLVED,

    "target_policy_ready":
        NOTEBOOK_06_FACTUAL_TARGET_POLICY_READY,

    "factual_optimisation_ready":
        NOTEBOOK_06_FACTUAL_OPTIMISATION_READY,

    "objective_policy_filename":
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_FILENAME,

    "objective_policy_drive_file_id":
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DRIVE_FILE_ID,

    "objective_policy_readback_valid":
        BLOCK_3_OBJECTIVE_POLICY_READBACK_VALID,

    "training_executed":
        NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED,

    "empirical_validity":
        NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_06_BLOCK_3_VALID,

    "block_complete":
        NOTEBOOK_06_BLOCK_3_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 06, Block 3: "
    "Factual Target Availability, Variability, "
    "Activation and Loss-Contract Analysis"
)

print("=" * 72)

print(
    f"Objective-policy version     : "
    f"{NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VERSION}"
)


print("-" * 72)

print(
    "Representation orientation"
)

print(
    f"Prediction unit              : "
    f"sentence"
)

print(
    f"Context-assisted sentence    : "
    f"{True}"
)

print(
    f"Future context allowed       : "
    f"{NOTEBOOK_06_FUTURE_CONTEXT_ALLOWED}"
)

print(
    f"Article-level factual target : "
    f"{False}"
)


print("-" * 72)

print(
    "Factual target audit"
)

print(
    f"Factual dimensions           : "
    f"{len(NOTEBOOK_06_FACTUAL_DIMENSION_ORDER)}"
)

print(
    f"Active dimensions            : "
    f"{BLOCK_3_ACTIVE_DIMENSION_COUNT}"
)

print(
    f"Deferred dimensions          : "
    f"{BLOCK_3_DEFERRED_DIMENSION_COUNT}"
)

print(
    f"Zero-variance dimensions     : "
    f"{list(BLOCK_3_ZERO_VARIANCE_DIMENSIONS)}"
)

print(
    f"Imbalanced active dimensions : "
    f"{list(BLOCK_3_IMBALANCED_ACTIVE_DIMENSIONS)}"
)


print("-" * 72)

print(
    "Dimension activation and loss policy"
)


for dimension_name in NOTEBOOK_06_FACTUAL_DIMENSION_ORDER:

    stats = (
        BLOCK_3_DIMENSION_STATISTICS[
            dimension_name
        ]
    )


    print(
        f"{stats['dimension_id']:<4} "
        f"{dimension_name:<27}: "
        f"observed={stats['observed_count']:<2} "
        f"unique={stats['unique_count']:<2} "
        f"var="
        f"{stats['variance'] if stats['variance'] is not None else 'NA'} "
        f"eligible={stats['training_eligible']}"
    )


    print(
        f"     activation                : "
        f"{stats['activation_state']}"
    )


    print(
        f"     target family             : "
        f"{stats['target_family']}"
    )


    print(
        f"     loss family               : "
        f"{stats['loss_family']}"
    )


    if stats[
        "binary_target"
    ]:

        print(
            f"     negative / positive       : "
            f"{stats['negative_count']} / "
            f"{stats['positive_count']}"
        )


        print(
            f"     imbalance ratio           : "
            f"{stats['imbalance_ratio']}"
        )


        print(
            f"     imbalance warning         : "
            f"{stats['imbalance_warning']}"
        )


        if stats[
            "recommended_positive_weight"
        ] is not None:

            print(
                f"     recommended pos. weight   : "
                f"{stats['recommended_positive_weight']:.4f}"
            )


print("-" * 72)

print(
    "Controlled factual objective policy"
)

print(
    f"Eligible active dimensions   : "
    f"{list(NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS)}"
)

print(
    f"Deferred dimensions          : "
    f"{list(NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS)}"
)

print(
    f"Active binary dimensions     : "
    f"{list(NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS)}"
)

print(
    f"Active continuous dimensions : "
    f"{list(NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS)}"
)

print(
    f"Positive class weights       : "
    f"{NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS}"
)


print("-" * 72)

print(
    "Loss and masking contract"
)

print(
    f"Loss contract resolved       : "
    f"{NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_RESOLVED}"
)

print(
    f"Activation contract resolved : "
    f"{NOTEBOOK_06_FACTUAL_ACTIVATION_CONTRACT_RESOLVED}"
)

print(
    f"Mask-aware supervision       : "
    f"{NOTEBOOK_06_MASK_AWARE_SUPERVISION}"
)

print(
    f"Missing = zero               : "
    f"{NOTEBOOK_06_MISSING_EQUALS_ZERO}"
)

print(
    f"Missing = negative           : "
    f"{NOTEBOOK_06_MISSING_EQUALS_NEGATIVE}"
)

print(
    f"Unavailable enters loss      : "
    f"{NOTEBOOK_06_UNAVAILABLE_ENTERS_LOSS}"
)


print("-" * 72)

print(
    "Persistent objective-policy artefact"
)

print(
    f"Filename                     : "
    f"{NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_FILENAME}"
)

print(
    f"Local copy created           : "
    f"{BLOCK_3_LOCAL_OBJECTIVE_POLICY_CREATED}"
)

print(
    f"Drive operation              : "
    f"{NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DRIVE_OPERATION}"
)

print(
    f"Drive file ID                : "
    f"{NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_DRIVE_FILE_ID}"
)

print(
    f"Read-back valid              : "
    f"{BLOCK_3_OBJECTIVE_POLICY_READBACK_VALID}"
)


print("-" * 72)

print(
    "Readiness"
)

print(
    f"Target policy ready          : "
    f"{NOTEBOOK_06_FACTUAL_TARGET_POLICY_READY}"
)

print(
    f"Objective policy valid       : "
    f"{NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID}"
)

print(
    f"Factual optimisation ready   : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMISATION_READY}"
)

print(
    f"Ready for model policy       : "
    f"{NOTEBOOK_06_READY_FOR_FACTUAL_MODEL_AND_PARAMETER_POLICY}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Objectives trained           : "
    f"{NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED_FOR_TRAINING}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED}"
)

print(
    f"Forward pass executed        : "
    f"{NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_06_FACTUAL_LOSS_CALCULATED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_06_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Factual training executed    : "
    f"{NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Held-out evaluation          : "
    f"{NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_06_BLOCK_3_VALID}"
)

print(
    f"Block 3 complete             : "
    f"{NOTEBOOK_06_BLOCK_3_COMPLETE}"
)


print("=" * 72)


print(
    "Factual target availability, variability and loss-contract "
    "analysis completed successfully."
)

print(
    "The factual prediction unit remains the canonical sentence, "
    "with permitted preceding context available only where required "
    "for interpretation."
)

print(
    "Full target coverage has not been treated as equivalent to "
    "useful optimisation supervision."
)

print(
    "Zero-variance factual dimensions remain semantically valid but "
    "are deferred from the current controlled factual objective."
)

print(
    "Variable factual dimensions with adequate class or value support "
    "are eligible for later controlled optimisation."
)

print(
    "Binary factual dimensions use a masked binary-cross-entropy-with-"
    "logits policy when activated."
)

print(
    "Factological weight uses a masked continuous regression objective."
)

print(
    "Highly imbalanced binary targets are identified explicitly and "
    "receive a reproducible positive-class weighting recommendation."
)

print(
    "No missing supervision has been converted into zero or negative "
    "evidence."
)

print(
    "No factual optimiser, forward loss calculation, backward pass, "
    "parameter update or factual training has been executed."
)

print(
    "The next block may proceed to Factual Model Restoration, "
    "Parameter-Freezing Policy and Controlled Forward-Path Validation."
)

print("=" * 72)


# =============================================================================
# Display factual activation audit
# =============================================================================

display(
    BLOCK_3_FACTUAL_ACTIVATION_AUDIT
)

========================================================================
Media AI — Notebook 06, Block 3: Factual Target Availability, Variability, Activation and Loss-Contract Analysis
========================================================================
Objective-policy version     : 1.0
------------------------------------------------------------------------
Representation orientation
Prediction unit              : sentence
Context-assisted sentence    : True
Future context allowed       : False
Article-level factual target : False
------------------------------------------------------------------------
Factual target audit
Factual dimensions           : 10
Active dimensions            : 9
Deferred dimensions          : 1
Zero-variance dimensions     : []
Imbalanced active dimensions : ['explicit_claim', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction']
------------------------------------------------------------------------
Dimension activation and loss policy
F1   explicit_claim             : observed=54 unique=2  var=0.16220850480109736 eligible=True
     activation                : eligible_with_imbalance_caution
     target family             : binary_factological_content
     loss family               : binary_cross_entropy_with_logits
     negative / positive       : 11 / 43
     imbalance ratio           : 3.909090909090909
     imbalance warning         : True
     recommended pos. weight   : 0.2558
F2   observation_or_event       : observed=54 unique=2  var=0.24451303155006857 eligible=True
     activation                : eligible
     target family             : binary_factological_content
     loss family               : binary_cross_entropy_with_logits
     negative / positive       : 23 / 31
     imbalance ratio           : 1.3478260869565217
     imbalance warning         : False
     recommended pos. weight   : 0.7419
F3   quantitative_information   : observed=54 unique=2  var=0.2006172839506172 eligible=True
     activation                : eligible
     target family             : binary_factological_content
     loss family               : binary_cross_entropy_with_logits
     negative / positive       : 39 / 15
     imbalance ratio           : 2.6
     imbalance warning         : False
     recommended pos. weight   : 2.6000
F4   attribution                : observed=54 unique=2  var=0.19204389574759942 eligible=True
     activation                : eligible
     target family             : binary_factological_content
     loss family               : binary_cross_entropy_with_logits
     negative / positive       : 14 / 40
     imbalance ratio           : 2.857142857142857
     imbalance warning         : False
     recommended pos. weight   : 0.3500
F5   evidence_reference         : observed=54 unique=2  var=0.1827846364883402 eligible=True
     activation                : eligible_with_imbalance_caution
     target family             : binary_factological_content
     loss family               : binary_cross_entropy_with_logits
     negative / positive       : 41 / 13
     imbalance ratio           : 3.1538461538461537
     imbalance warning         : True
     recommended pos. weight   : 3.1538
F6   certainty_statement        : observed=54 unique=2  var=0.1262002743484225 eligible=True
     activation                : eligible_with_imbalance_caution
     target family             : binary_factological_content
     loss family               : binary_cross_entropy_with_logits
     negative / positive       : 8 / 46
     imbalance ratio           : 5.75
     imbalance warning         : True
     recommended pos. weight   : 0.1739
F7   uncertainty_statement      : observed=54 unique=2  var=0.09876543209876544 eligible=True
     activation                : eligible_with_imbalance_caution
     target family             : binary_factological_content
     loss family               : binary_cross_entropy_with_logits
     negative / positive       : 48 / 6
     imbalance ratio           : 8.0
     imbalance warning         : True
     recommended pos. weight   : 8.0000
F8   speculation                : observed=52 unique=2  var=0.01886094674556213 eligible=False
     activation                : deferred_insufficient_class_support
     target family             : binary_factological_content
     loss family               : none
     negative / positive       : 51 / 1
     imbalance ratio           : 51.0
     imbalance warning         : True
     recommended pos. weight   : 51.0000
F9   prediction                 : observed=52 unique=2  var=0.036982248520710054 eligible=True
     activation                : eligible_with_imbalance_caution
     target family             : binary_factological_content
     loss family               : binary_cross_entropy_with_logits
     negative / positive       : 50 / 2
     imbalance ratio           : 25.0
     imbalance warning         : True
     recommended pos. weight   : 25.0000
F10  factological_weight        : observed=54 unique=9  var=0.04156807270233197 eligible=True
     activation                : eligible
     target family             : continuous_weight
     loss family               : masked_mean_squared_error
------------------------------------------------------------------------
Controlled factual objective policy
Eligible active dimensions   : ['explicit_claim', 'observation_or_event', 'quantitative_information', 'attribution', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction', 'factological_weight']
Deferred dimensions          : ['speculation']
Active binary dimensions     : ['explicit_claim', 'observation_or_event', 'quantitative_information', 'attribution', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction']
Active continuous dimensions : ['factological_weight']
Positive class weights       : {'explicit_claim': 0.2558139534883721, 'evidence_reference': 3.1538461538461537, 'certainty_statement': 0.17391304347826086, 'uncertainty_statement': 8.0, 'prediction': 25.0}
------------------------------------------------------------------------
Loss and masking contract
Loss contract resolved       : True
Activation contract resolved : True
Mask-aware supervision       : True
Missing = zero               : False
Missing = negative           : False
Unavailable enters loss      : False
------------------------------------------------------------------------
Persistent objective-policy artefact
Filename                     : notebook_06_factual_objective_policy.json
Local copy created           : True
Drive operation              : updated
Drive file ID                : 1kB1fGrtcKrjMQblg3VgoCD6vOkKXTuUA
Read-back valid              : True
------------------------------------------------------------------------
Readiness
Target policy ready          : True
Objective policy valid       : True
Factual optimisation ready   : False
Ready for model policy       : True
------------------------------------------------------------------------
Execution boundary
Objectives trained           : False
Optimiser created            : False
Forward pass executed        : False
Loss calculated              : False
Backward pass executed       : False
Parameter update executed    : False
Factual training executed    : False
Psychological retraining     : False
Held-out evaluation          : False
Empirical validity           : False
Block valid                  : True
Block 3 complete             : True
========================================================================
Factual target availability, variability and loss-contract analysis completed successfully.
The factual prediction unit remains the canonical sentence, with permitted preceding context available only where required for interpretation.
Full target coverage has not been treated as equivalent to useful optimisation supervision.
Zero-variance factual dimensions remain semantically valid but are deferred from the current controlled factual objective.
Variable factual dimensions with adequate class or value support are eligible for later controlled optimisation.
Binary factual dimensions use a masked binary-cross-entropy-with-logits policy when activated.
Factological weight uses a masked continuous regression objective.
Highly imbalanced binary targets are identified explicitly and receive a reproducible positive-class weighting recommendation.
No missing supervision has been converted into zero or negative evidence.
No factual optimiser, forward loss calculation, backward pass, parameter update or factual training has been executed.
The next block may proceed to Factual Model Restoration, Parameter-Freezing Policy and Controlled Forward-Path Validation.
========================================================================

,dimension_id,target_name,observed,possible,coverage,unique_values,variance,positive,negative,imbalance_ratio,training_eligible,activation_state,loss_family
0,F1,explicit_claim,54,54,1.000000,2,0.162209,43.0,11.0,3.909091,True,eligible_with_imbalance_caution,binary_cross_entropy_with_logits
1,F2,observation_or_event,54,54,1.000000,2,0.244513,31.0,23.0,1.347826,True,eligible,binary_cross_entropy_with_logits
2,F3,quantitative_information,54,54,1.000000,2,0.200617,15.0,39.0,2.600000,True,eligible,binary_cross_entropy_with_logits
3,F4,attribution,54,54,1.000000,2,0.192044,40.0,14.0,2.857143,True,eligible,binary_cross_entropy_with_logits
4,F5,evidence_reference,54,54,1.000000,2,0.182785,13.0,41.0,3.153846,True,eligible_with_imbalance_caution,binary_cross_entropy_with_logits
5,F6,certainty_statement,54,54,1.000000,2,0.126200,46.0,8.0,5.750000,True,eligible_with_imbalance_caution,binary_cross_entropy_with_logits
6,F7,uncertainty_statement,54,54,1.000000,2,0.098765,6.0,48.0,8.000000,True,eligible_with_imbalance_caution,binary_cross_entropy_with_logits
7,F8,speculation,52,54,0.962963,2,0.018861,1.0,51.0,51.000000,False,deferred_insufficient_class_support,none
8,F9,prediction,52,54,0.962963,2,0.036982,2.0,50.0,25.000000,True,eligible_with_imbalance_caution,binary_cross_entropy_with_logits
9,F10,factological_weight,54,54,1.000000,9,0.041568,NaN,NaN,NaN,True,eligible,masked_mean_squared_error

In [5]:
# =============================================================================
# Media AI — Notebook 06
# Diagnostic: Persisted Notebook 05 Architecture and Checkpoint Topology
# =============================================================================
#
# PURPOSE
# -------
# Inspect the persisted Notebook 05 checkpoint and metadata without:
#
# - reconstructing the model,
# - executing a forward pass,
# - creating an optimiser,
# - calculating a loss,
# - changing parameters,
# - training anything.
#
# The immediate question is why the persisted confluent layer expects
# 320 input features while the attempted Block 4 reconstruction supplied 256.
#
# This diagnostic therefore reports:
#
# 1. checkpoint top-level structure,
# 2. model-state parameter keys and shapes,
# 3. Linear-layer weight dimensions,
# 4. module/prefix groupings,
# 5. likely dimensional transitions,
# 6. metadata fields containing architecture/dimension information,
# 7. runtime model/module objects that may preserve the original architecture.
#
# =============================================================================

import io
import json
import re

import torch
import torch.nn as nn

from googleapiclient.http import MediaIoBaseDownload


# =============================================================================
# Prerequisites
# =============================================================================

required_diagnostic_objects = [
    "NOTEBOOK_06_DRIVE_SERVICE",
    "NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_DRIVE_FILE_ID",
    "NOTEBOOK_06_PSYCHOLOGICAL_METADATA_DRIVE_FILE_ID",
]


missing_diagnostic_objects = [
    name
    for name in required_diagnostic_objects
    if name not in globals()
]


if missing_diagnostic_objects:
    raise NameError(
        "Notebook 06 architecture diagnostic prerequisites "
        "are not initialised. "
        f"Missing: {missing_diagnostic_objects}"
    )


# =============================================================================
# Drive download helper
# =============================================================================

def diagnostic_download_drive_bytes(
    drive_service,
    file_id,
):
    request = drive_service.files().get_media(
        fileId=file_id
    )

    buffer = io.BytesIO()

    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )

    complete = False

    while not complete:
        _, complete = downloader.next_chunk()

    buffer.seek(0)

    return buffer.read()


# =============================================================================
# Reload checkpoint
# =============================================================================

diagnostic_checkpoint_bytes = diagnostic_download_drive_bytes(
    NOTEBOOK_06_DRIVE_SERVICE,
    NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_DRIVE_FILE_ID,
)


diagnostic_checkpoint_buffer = io.BytesIO(
    diagnostic_checkpoint_bytes
)


try:
    DIAGNOSTIC_CHECKPOINT = torch.load(
        diagnostic_checkpoint_buffer,
        map_location="cpu",
        weights_only=False,
    )

except TypeError:

    diagnostic_checkpoint_buffer.seek(0)

    DIAGNOSTIC_CHECKPOINT = torch.load(
        diagnostic_checkpoint_buffer,
        map_location="cpu",
    )


if not isinstance(DIAGNOSTIC_CHECKPOINT, dict):
    raise TypeError(
        "Persisted Notebook 05 checkpoint is not dictionary-like."
    )


# =============================================================================
# Reload metadata
# =============================================================================

diagnostic_metadata_bytes = diagnostic_download_drive_bytes(
    NOTEBOOK_06_DRIVE_SERVICE,
    NOTEBOOK_06_PSYCHOLOGICAL_METADATA_DRIVE_FILE_ID,
)


DIAGNOSTIC_METADATA = json.loads(
    diagnostic_metadata_bytes.decode("utf-8")
)


if not isinstance(DIAGNOSTIC_METADATA, dict):
    raise TypeError(
        "Persisted Notebook 05 metadata is not a JSON object."
    )


# =============================================================================
# Basic helpers
# =============================================================================

def diagnostic_is_tensor_state_dict(value):
    return (
        isinstance(value, dict)
        and len(value) > 0
        and all(
            torch.is_tensor(item)
            for item in value.values()
        )
    )


def diagnostic_natural_key(value):
    pieces = re.split(
        r"(\d+)",
        str(value),
    )

    return [
        int(piece)
        if piece.isdigit()
        else piece.lower()

        for piece in pieces
    ]


def diagnostic_shape(value):
    if torch.is_tensor(value):
        return tuple(value.shape)

    return None


# =============================================================================
# Locate model state dictionary
# =============================================================================

def diagnostic_find_model_state(checkpoint):

    preferred_keys = [
        "model_state_dict",
        "model_state",
        "state_dict",
        "media_ai_model_state_dict",
        "architecture_state_dict",
    ]

    for key in preferred_keys:

        if key not in checkpoint:
            continue

        value = checkpoint[key]

        if diagnostic_is_tensor_state_dict(value):
            return key, value


    if diagnostic_is_tensor_state_dict(checkpoint):
        return "__checkpoint_root__", checkpoint


    candidates = []

    for key, value in checkpoint.items():

        if diagnostic_is_tensor_state_dict(value):

            candidates.append(
                (
                    key,
                    value,
                )
            )


    if not candidates:
        raise KeyError(
            "No tensor state dictionary could be located "
            "inside the checkpoint."
        )


    print(
        "WARNING: No preferred model-state key was found."
    )

    print(
        "Using first tensor state dictionary candidate:"
    )

    print(
        f"    {candidates[0][0]}"
    )

    return candidates[0]


(
    DIAGNOSTIC_MODEL_STATE_KEY,
    DIAGNOSTIC_MODEL_STATE,
) = diagnostic_find_model_state(
    DIAGNOSTIC_CHECKPOINT
)


# =============================================================================
# Top-level checkpoint structure
# =============================================================================

print("=" * 88)

print(
    "Media AI — Notebook 06 Diagnostic: "
    "Persisted Notebook 05 Architecture Topology"
)

print("=" * 88)


print("\nCHECKPOINT TOP-LEVEL CONTENT")
print("-" * 88)


for key in sorted(
    DIAGNOSTIC_CHECKPOINT.keys(),
    key=diagnostic_natural_key,
):

    value = DIAGNOSTIC_CHECKPOINT[key]

    if torch.is_tensor(value):

        description = (
            f"Tensor shape={tuple(value.shape)}"
        )

    elif isinstance(value, dict):

        description = (
            f"dict entries={len(value)}"
        )

    elif isinstance(value, (list, tuple)):

        description = (
            f"{type(value).__name__} "
            f"length={len(value)}"
        )

    else:

        preview = repr(value)

        if len(preview) > 120:
            preview = preview[:117] + "..."

        description = (
            f"{type(value).__name__}: "
            f"{preview}"
        )

    print(
        f"{key:<42} {description}"
    )


print()
print(
    f"Selected model-state key: "
    f"{DIAGNOSTIC_MODEL_STATE_KEY}"
)


# =============================================================================
# Full parameter topology
# =============================================================================

print("\n")
print("FULL MODEL-STATE PARAMETER TOPOLOGY")
print("-" * 88)


sorted_state_keys = sorted(
    DIAGNOSTIC_MODEL_STATE.keys(),
    key=diagnostic_natural_key,
)


for key in sorted_state_keys:

    value = DIAGNOSTIC_MODEL_STATE[key]

    shape = diagnostic_shape(
        value
    )

    print(
        f"{key:<62} {str(shape):>20}"
    )


# =============================================================================
# Linear-layer transitions
# =============================================================================

print("\n")
print("LINEAR-LAYER DIMENSIONAL TRANSITIONS")
print("-" * 88)


DIAGNOSTIC_LINEAR_TRANSITIONS = []


for key in sorted_state_keys:

    value = DIAGNOSTIC_MODEL_STATE[key]

    if not torch.is_tensor(value):
        continue

    if value.ndim != 2:
        continue

    if not key.endswith("weight"):
        continue

    out_features = int(
        value.shape[0]
    )

    in_features = int(
        value.shape[1]
    )

    DIAGNOSTIC_LINEAR_TRANSITIONS.append(
        {
            "parameter":
                key,

            "input_dim":
                in_features,

            "output_dim":
                out_features,
        }
    )

    print(
        f"{key:<62} "
        f"{in_features:>5} -> {out_features:<5}"
    )


# =============================================================================
# Highlight important dimensional transitions
# =============================================================================

print("\n")
print("DIMENSIONAL TRANSITIONS OF SPECIAL INTEREST")
print("-" * 88)


interesting_dimensions = {
    10,
    34,
    64,
    128,
    256,
    320,
    768,
}


interesting_transitions = [
    transition

    for transition
    in DIAGNOSTIC_LINEAR_TRANSITIONS

    if (
        transition["input_dim"]
        in interesting_dimensions

        or

        transition["output_dim"]
        in interesting_dimensions
    )
]


for transition in interesting_transitions:

    print(
        f"{transition['parameter']:<62} "
        f"{transition['input_dim']:>5} "
        f"-> "
        f"{transition['output_dim']:<5}"
    )


# =============================================================================
# Explicitly inspect all 320-dimensional consumers/producers
# =============================================================================

print("\n")
print("320-DIMENSIONAL PATH SEARCH")
print("-" * 88)


DIAGNOSTIC_320_INPUT_LAYERS = [
    transition

    for transition
    in DIAGNOSTIC_LINEAR_TRANSITIONS

    if transition["input_dim"] == 320
]


DIAGNOSTIC_320_OUTPUT_LAYERS = [
    transition

    for transition
    in DIAGNOSTIC_LINEAR_TRANSITIONS

    if transition["output_dim"] == 320
]


print(
    f"Linear layers consuming 320 dimensions : "
    f"{len(DIAGNOSTIC_320_INPUT_LAYERS)}"
)


for transition in DIAGNOSTIC_320_INPUT_LAYERS:

    print(
        f"    {transition['parameter']} "
        f": "
        f"{transition['input_dim']} "
        f"-> "
        f"{transition['output_dim']}"
    )


print(
    f"Linear layers producing 320 dimensions : "
    f"{len(DIAGNOSTIC_320_OUTPUT_LAYERS)}"
)


for transition in DIAGNOSTIC_320_OUTPUT_LAYERS:

    print(
        f"    {transition['parameter']} "
        f": "
        f"{transition['input_dim']} "
        f"-> "
        f"{transition['output_dim']}"
    )


# =============================================================================
# Explicitly inspect all 64-dimensional parameters
# =============================================================================

print("\n")
print("64-DIMENSIONAL COMPONENT SEARCH")
print("-" * 88)


DIAGNOSTIC_64_RELATED = [
    transition

    for transition
    in DIAGNOSTIC_LINEAR_TRANSITIONS

    if (
        transition["input_dim"] == 64
        or
        transition["output_dim"] == 64
    )
]


print(
    f"Linear layers involving 64 dimensions : "
    f"{len(DIAGNOSTIC_64_RELATED)}"
)


for transition in DIAGNOSTIC_64_RELATED:

    print(
        f"    {transition['parameter']} "
        f": "
        f"{transition['input_dim']} "
        f"-> "
        f"{transition['output_dim']}"
    )


# =============================================================================
# Module-prefix grouping
# =============================================================================

print("\n")
print("TOP-LEVEL PARAMETER PREFIX GROUPS")
print("-" * 88)


prefix_groups = {}


for key in sorted_state_keys:

    top_prefix = key.split(".")[0]

    prefix_groups.setdefault(
        top_prefix,
        []
    ).append(
        key
    )


for prefix in sorted(
    prefix_groups.keys(),
    key=diagnostic_natural_key,
):

    keys = prefix_groups[
        prefix
    ]

    parameter_count = sum(
        int(
            DIAGNOSTIC_MODEL_STATE[key].numel()
        )

        for key in keys

        if torch.is_tensor(
            DIAGNOSTIC_MODEL_STATE[key]
        )
    )

    print(
        f"{prefix:<36} "
        f"tensor entries={len(keys):<4} "
        f"parameters={parameter_count}"
    )


# =============================================================================
# Detailed architecture-related prefix inspection
# =============================================================================

architecture_terms = [
    "backbone",
    "confluent",
    "group",
    "conditioning",
    "condition",
    "factual",
    "factological",
    "psychological",
    "social",
    "transform",
    "weight",
    "recurrent",
    "hidden",
    "projection",
    "embedding",
]


print("\n")
print("ARCHITECTURE-RELATED PARAMETER KEYS")
print("-" * 88)


for key in sorted_state_keys:

    lowered = key.lower()

    if any(
        term in lowered
        for term in architecture_terms
    ):

        value = DIAGNOSTIC_MODEL_STATE[
            key
        ]

        print(
            f"{key:<62} "
            f"{str(tuple(value.shape)):>20}"
        )


# =============================================================================
# Metadata recursive inspection
# =============================================================================

def diagnostic_flatten_metadata(
    value,
    prefix="",
):
    rows = []

    if isinstance(value, dict):

        for key, child in value.items():

            child_prefix = (
                f"{prefix}.{key}"
                if prefix
                else str(key)
            )

            rows.extend(
                diagnostic_flatten_metadata(
                    child,
                    child_prefix,
                )
            )

    elif isinstance(value, list):

        # Do not recursively print huge lists.
        if len(value) <= 20:

            for index, child in enumerate(value):

                child_prefix = (
                    f"{prefix}[{index}]"
                )

                rows.extend(
                    diagnostic_flatten_metadata(
                        child,
                        child_prefix,
                    )
                )

        else:

            rows.append(
                (
                    prefix,
                    f"<list length={len(value)}>",
                )
            )

    else:

        rows.append(
            (
                prefix,
                value,
            )
        )

    return rows


DIAGNOSTIC_METADATA_ROWS = (
    diagnostic_flatten_metadata(
        DIAGNOSTIC_METADATA
    )
)


metadata_terms = [
    "dim",
    "dimension",
    "architecture",
    "backbone",
    "confluent",
    "group",
    "condition",
    "factual",
    "psychological",
    "social",
    "representation",
    "hidden",
    "projection",
    "input",
    "output",
]


print("\n")
print("ARCHITECTURE-RELATED CHECKPOINT METADATA")
print("-" * 88)


metadata_matches = 0


for path, value in DIAGNOSTIC_METADATA_ROWS:

    lowered = path.lower()

    if not any(
        term in lowered
        for term in metadata_terms
    ):
        continue

    metadata_matches += 1

    preview = repr(
        value
    )

    if len(preview) > 160:
        preview = preview[:157] + "..."

    print(
        f"{path:<62} {preview}"
    )


if metadata_matches == 0:

    print(
        "No architecture-related metadata fields "
        "were identified by keyword."
    )


# =============================================================================
# Search checkpoint non-model fields for architecture clues
# =============================================================================

print("\n")
print("NON-MODEL CHECKPOINT ARCHITECTURE CLUES")
print("-" * 88)


checkpoint_clue_count = 0


for key, value in DIAGNOSTIC_CHECKPOINT.items():

    if key == DIAGNOSTIC_MODEL_STATE_KEY:
        continue

    lowered = str(key).lower()

    if not any(
        term in lowered
        for term in metadata_terms
    ):
        continue

    checkpoint_clue_count += 1

    if torch.is_tensor(value):

        preview = (
            f"Tensor shape={tuple(value.shape)}"
        )

    else:

        preview = repr(
            value
        )

        if len(preview) > 200:
            preview = preview[:197] + "..."

    print(
        f"{key:<62} {preview}"
    )


if checkpoint_clue_count == 0:

    print(
        "No architecture-related non-model checkpoint "
        "fields identified by keyword."
    )


# =============================================================================
# Runtime nn.Module discovery
# =============================================================================
#
# This is especially useful because Notebook 05 may still have the original
# architecture instance or individual modules in memory. We inspect names
# and class structures only. Nothing is executed.
# =============================================================================

print("\n")
print("CURRENT RUNTIME nn.Module OBJECTS")
print("-" * 88)


DIAGNOSTIC_RUNTIME_MODULES = []


for name, value in list(
    globals().items()
):

    if not isinstance(
        value,
        nn.Module,
    ):
        continue

    DIAGNOSTIC_RUNTIME_MODULES.append(
        (
            name,
            value,
        )
    )


if not DIAGNOSTIC_RUNTIME_MODULES:

    print(
        "No nn.Module objects currently found in the runtime."
    )


else:

    for name, module in sorted(
        DIAGNOSTIC_RUNTIME_MODULES,
        key=lambda item: diagnostic_natural_key(
            item[0]
        ),
    ):

        parameter_count = sum(
            parameter.numel()
            for parameter
            in module.parameters()
        )

        trainable_count = sum(
            parameter.numel()
            for parameter
            in module.parameters()
            if parameter.requires_grad
        )

        print(
            f"{name:<44} "
            f"class={module.__class__.__name__:<28} "
            f"params={parameter_count:<9} "
            f"trainable={trainable_count}"
        )


# =============================================================================
# Detailed runtime module structure for architecture-related objects
# =============================================================================

print("\n")
print("ARCHITECTURE-RELATED RUNTIME MODULE STRUCTURES")
print("-" * 88)


runtime_architecture_terms = [
    "media",
    "model",
    "backbone",
    "confluent",
    "factual",
    "psychological",
    "social",
    "group",
    "transform",
]


runtime_structure_count = 0


for name, module in sorted(
    DIAGNOSTIC_RUNTIME_MODULES,
    key=lambda item: diagnostic_natural_key(
        item[0]
    ),
):

    lowered = name.lower()

    if not any(
        term in lowered
        for term in runtime_architecture_terms
    ):
        continue

    runtime_structure_count += 1

    print()
    print(
        f"[{name}]"
    )

    print(
        module
    )


if runtime_structure_count == 0:

    print(
        "No architecture-related runtime module names identified."
    )


# =============================================================================
# Summary
# =============================================================================

print("\n")
print("DIAGNOSTIC SUMMARY")
print("-" * 88)

print(
    f"Model-state key                    : "
    f"{DIAGNOSTIC_MODEL_STATE_KEY}"
)

print(
    f"Model-state tensor entries         : "
    f"{len(DIAGNOSTIC_MODEL_STATE)}"
)

print(
    f"Detected Linear transitions        : "
    f"{len(DIAGNOSTIC_LINEAR_TRANSITIONS)}"
)

print(
    f"Layers consuming 320 dimensions    : "
    f"{len(DIAGNOSTIC_320_INPUT_LAYERS)}"
)

print(
    f"Layers producing 320 dimensions    : "
    f"{len(DIAGNOSTIC_320_OUTPUT_LAYERS)}"
)

print(
    f"Layers involving 64 dimensions     : "
    f"{len(DIAGNOSTIC_64_RELATED)}"
)

print(
    f"Runtime nn.Module objects found    : "
    f"{len(DIAGNOSTIC_RUNTIME_MODULES)}"
)

print("-" * 88)

print(
    "Diagnostic only: no model reconstruction, forward pass, "
    "loss calculation, optimiser creation, backward pass, "
    "parameter update or training was performed."
)

print("=" * 88)

========================================================================================
Media AI — Notebook 06 Diagnostic: Persisted Notebook 05 Architecture Topology
========================================================================================

CHECKPOINT TOP-LEVEL CONTENT
----------------------------------------------------------------------------------------
block                                      int: 7
block_version                              str: '1.1'
checkpoint_type                            str: 'controlled_experimental_training_checkpoint'
created_at_utc                             str: '2026-08-24T19:41:24.368139+00:00'
encoder                                    dict entries=4
final_total_objective                      float: 0.018736351281404495
initial_total_objective                    float: 0.14755606651306152
maximum_observed_gradient_norm             float: 0.5943729281425476
maximum_parameter_delta                    float: 0.010085072368383408
methodological_boundary                    dict entries=10
model_state_dict                           dict entries=132
notebook                                   str: '05_training_evaluation_and_validation'
objective_reduction                        float: 0.12881971523165703
optimizer_state_dict                       dict entries=2
project_random_seed                        int: 42
psychological_head_state_dict              dict entries=6
supervision                                dict entries=4
training_configuration                     dict entries=7
training_data                              dict entries=4
training_history                           list length=10

Selected model-state key: model_state_dict


FULL MODEL-STATE PARAMETER TOPOLOGY
----------------------------------------------------------------------------------------
backbone.projection.bias                                                     (768,)
backbone.projection.weight                                               (768, 768)
confluent.global_projection.0.bias                                           (256,)
confluent.global_projection.0.weight                                     (256, 768)
confluent.global_projection.3.bias                                           (256,)
confluent.global_projection.3.weight                                         (256,)
confluent.group_adapter.0.bias                                               (256,)
confluent.group_adapter.0.weight                                         (256, 320)
confluent.group_adapter.3.bias                                               (256,)
confluent.group_adapter.3.weight                                         (256, 256)
factual_group_adapter.network.0.bias                                         (128,)
factual_group_adapter.network.0.weight                                    (128, 74)
factual_group_adapter.network.3.bias                                          (10,)
factual_group_adapter.network.3.weight                                    (10, 128)
factual_head.core.network.0.bias                                             (128,)
factual_head.core.network.0.weight                                       (128, 256)
factual_head.core.network.3.bias                                             (128,)
factual_head.core.network.3.weight                                           (128,)
factual_head.output_layer.bias                                                (10,)
factual_head.output_layer.weight                                          (10, 128)
factual_recurrent.candidate_network.0.bias                                    (64,)
factual_recurrent.candidate_network.0.weight                               (64, 85)
factual_recurrent.candidate_network.3.bias                                    (64,)
factual_recurrent.candidate_network.3.weight                                  (64,)
factual_recurrent.candidate_network.4.bias                                    (64,)
factual_recurrent.candidate_network.4.weight                               (64, 64)
factual_recurrent.retention_layer.bias                                        (64,)
factual_recurrent.retention_layer.weight                                   (64, 85)
factual_recurrent_group_adapter.network.0.bias                                (64,)
factual_recurrent_group_adapter.network.0.weight                          (64, 128)
factual_recurrent_group_adapter.network.3.bias                                (64,)
factual_recurrent_group_adapter.network.3.weight                           (64, 64)
factual_transform.core.0.bias                                                (128,)
factual_transform.core.0.weight                                           (128, 20)
factual_transform.core.3.bias                                                (128,)
factual_transform.core.3.weight                                              (128,)
factual_transform.core.4.bias                                                 (10,)
factual_transform.core.4.weight                                           (10, 128)
factual_transform.gate.gate_layer.bias                                        (10,)
factual_transform.gate.gate_layer.weight                                   (10, 10)
factual_transform.tw_predictor.network.0.bias                                (128,)
factual_transform.tw_predictor.network.0.weight                           (128, 20)
factual_transform.tw_predictor.network.2.bias                                (128,)
factual_transform.tw_predictor.network.2.weight                              (128,)
factual_transform.tw_predictor.network.3.bias                                  (1,)
factual_transform.tw_predictor.network.3.weight                            (1, 128)
factual_transform_group_adapter.network.0.bias                               (128,)
factual_transform_group_adapter.network.0.weight                          (128, 74)
factual_transform_group_adapter.network.3.bias                                (10,)
factual_transform_group_adapter.network.3.weight                          (10, 128)
psychological_group_adapter.network.0.bias                                   (128,)
psychological_group_adapter.network.0.weight                              (128, 98)
psychological_group_adapter.network.3.bias                                    (34,)
psychological_group_adapter.network.3.weight                              (34, 128)
psychological_head.core.network.0.bias                                       (128,)
psychological_head.core.network.0.weight                                 (128, 256)
psychological_head.core.network.3.bias                                       (128,)
psychological_head.core.network.3.weight                                     (128,)
psychological_head.output_layer.bias                                          (34,)
psychological_head.output_layer.weight                                    (34, 128)
psychological_recurrent.candidate_network.0.bias                              (96,)
psychological_recurrent.candidate_network.0.weight                        (96, 165)
psychological_recurrent.candidate_network.3.bias                              (96,)
psychological_recurrent.candidate_network.3.weight                            (96,)
psychological_recurrent.candidate_network.4.bias                              (96,)
psychological_recurrent.candidate_network.4.weight                         (96, 96)
psychological_recurrent.retention_layer.bias                                  (96,)
psychological_recurrent.retention_layer.weight                            (96, 165)
psychological_recurrent_group_adapter.network.0.bias                          (96,)
psychological_recurrent_group_adapter.network.0.weight                    (96, 160)
psychological_recurrent_group_adapter.network.3.bias                          (96,)
psychological_recurrent_group_adapter.network.3.weight                     (96, 96)
psychological_transform.core.0.bias                                          (128,)
psychological_transform.core.0.weight                                     (128, 68)
psychological_transform.core.3.bias                                          (128,)
psychological_transform.core.3.weight                                        (128,)
psychological_transform.core.4.bias                                           (34,)
psychological_transform.core.4.weight                                     (34, 128)
psychological_transform.gate.gate_layer.bias                                  (34,)
psychological_transform.gate.gate_layer.weight                             (34, 34)
psychological_transform.tw_predictor.network.0.bias                          (128,)
psychological_transform.tw_predictor.network.0.weight                     (128, 68)
psychological_transform.tw_predictor.network.2.bias                          (128,)
psychological_transform.tw_predictor.network.2.weight                        (128,)
psychological_transform.tw_predictor.network.3.bias                            (1,)
psychological_transform.tw_predictor.network.3.weight                      (1, 128)
psychological_transform_group_adapter.network.0.bias                         (128,)
psychological_transform_group_adapter.network.0.weight                    (128, 98)
psychological_transform_group_adapter.network.3.bias                          (34,)
psychological_transform_group_adapter.network.3.weight                    (34, 128)
social_group_adapter.network.0.bias                                          (128,)
social_group_adapter.network.0.weight                                    (128, 192)
social_group_adapter.network.3.bias                                          (128,)
social_group_adapter.network.3.weight                                    (128, 128)
social_head.actor_projection.bias                                            (128,)
social_head.actor_projection.weight                                      (128, 128)
social_head.core.network.0.bias                                              (128,)
social_head.core.network.0.weight                                        (128, 256)
social_head.core.network.3.bias                                              (128,)
social_head.core.network.3.weight                                            (128,)
social_head.group_projection.bias                                            (128,)
social_head.group_projection.weight                                      (128, 128)
social_head.membership_projection.bias                                       (128,)
social_head.membership_projection.weight                                 (128, 128)
social_head.relationship_projection.bias                                     (128,)
social_head.relationship_projection.weight                               (128, 128)
social_recurrent.candidate_network.0.bias                                     (64,)
social_recurrent.candidate_network.0.weight                               (64, 321)
social_recurrent.candidate_network.3.bias                                     (64,)
social_recurrent.candidate_network.3.weight                                   (64,)
social_recurrent.candidate_network.4.bias                                     (64,)
social_recurrent.candidate_network.4.weight                                (64, 64)
social_recurrent.retention_layer.bias                                         (64,)
social_recurrent.retention_layer.weight                                   (64, 321)
social_recurrent_group_adapter.network.0.bias                                 (64,)
social_recurrent_group_adapter.network.0.weight                           (64, 128)
social_recurrent_group_adapter.network.3.bias                                 (64,)
social_recurrent_group_adapter.network.3.weight                            (64, 64)
social_transform.core.0.bias                                                 (128,)
social_transform.core.0.weight                                           (128, 256)
social_transform.core.3.bias                                                 (128,)
social_transform.core.3.weight                                               (128,)
social_transform.tw_predictor.network.0.bias                                 (128,)
social_transform.tw_predictor.network.0.weight                           (128, 256)
social_transform.tw_predictor.network.2.bias                                 (128,)
social_transform.tw_predictor.network.2.weight                               (128,)
social_transform.tw_predictor.network.3.bias                                   (1,)
social_transform.tw_predictor.network.3.weight                             (1, 128)
social_transform_group_adapter.network.0.bias                                (128,)
social_transform_group_adapter.network.0.weight                          (128, 192)
social_transform_group_adapter.network.3.bias                                (128,)
social_transform_group_adapter.network.3.weight                          (128, 128)


LINEAR-LAYER DIMENSIONAL TRANSITIONS
----------------------------------------------------------------------------------------
backbone.projection.weight                                       768 -> 768
confluent.global_projection.0.weight                             768 -> 256
confluent.group_adapter.0.weight                                 320 -> 256
confluent.group_adapter.3.weight                                 256 -> 256
factual_group_adapter.network.0.weight                            74 -> 128
factual_group_adapter.network.3.weight                           128 -> 10
factual_head.core.network.0.weight                               256 -> 128
factual_head.output_layer.weight                                 128 -> 10
factual_recurrent.candidate_network.0.weight                      85 -> 64
factual_recurrent.candidate_network.4.weight                      64 -> 64
factual_recurrent.retention_layer.weight                          85 -> 64
factual_recurrent_group_adapter.network.0.weight                 128 -> 64
factual_recurrent_group_adapter.network.3.weight                  64 -> 64
factual_transform.core.0.weight                                   20 -> 128
factual_transform.core.4.weight                                  128 -> 10
factual_transform.gate.gate_layer.weight                          10 -> 10
factual_transform.tw_predictor.network.0.weight                   20 -> 128
factual_transform.tw_predictor.network.3.weight                  128 -> 1
factual_transform_group_adapter.network.0.weight                  74 -> 128
factual_transform_group_adapter.network.3.weight                 128 -> 10
psychological_group_adapter.network.0.weight                      98 -> 128
psychological_group_adapter.network.3.weight                     128 -> 34
psychological_head.core.network.0.weight                         256 -> 128
psychological_head.output_layer.weight                           128 -> 34
psychological_recurrent.candidate_network.0.weight               165 -> 96
psychological_recurrent.candidate_network.4.weight                96 -> 96
psychological_recurrent.retention_layer.weight                   165 -> 96
psychological_recurrent_group_adapter.network.0.weight           160 -> 96
psychological_recurrent_group_adapter.network.3.weight            96 -> 96
psychological_transform.core.0.weight                             68 -> 128
psychological_transform.core.4.weight                            128 -> 34
psychological_transform.gate.gate_layer.weight                    34 -> 34
psychological_transform.tw_predictor.network.0.weight             68 -> 128
psychological_transform.tw_predictor.network.3.weight            128 -> 1
psychological_transform_group_adapter.network.0.weight            98 -> 128
psychological_transform_group_adapter.network.3.weight           128 -> 34
social_group_adapter.network.0.weight                            192 -> 128
social_group_adapter.network.3.weight                            128 -> 128
social_head.actor_projection.weight                              128 -> 128
social_head.core.network.0.weight                                256 -> 128
social_head.group_projection.weight                              128 -> 128
social_head.membership_projection.weight                         128 -> 128
social_head.relationship_projection.weight                       128 -> 128
social_recurrent.candidate_network.0.weight                      321 -> 64
social_recurrent.candidate_network.4.weight                       64 -> 64
social_recurrent.retention_layer.weight                          321 -> 64
social_recurrent_group_adapter.network.0.weight                  128 -> 64
social_recurrent_group_adapter.network.3.weight                   64 -> 64
social_transform.core.0.weight                                   256 -> 128
social_transform.tw_predictor.network.0.weight                   256 -> 128
social_transform.tw_predictor.network.3.weight                   128 -> 1
social_transform_group_adapter.network.0.weight                  192 -> 128
social_transform_group_adapter.network.3.weight                  128 -> 128


DIMENSIONAL TRANSITIONS OF SPECIAL INTEREST
----------------------------------------------------------------------------------------
backbone.projection.weight                                       768 -> 768
confluent.global_projection.0.weight                             768 -> 256
confluent.group_adapter.0.weight                                 320 -> 256
confluent.group_adapter.3.weight                                 256 -> 256
factual_group_adapter.network.0.weight                            74 -> 128
factual_group_adapter.network.3.weight                           128 -> 10
factual_head.core.network.0.weight                               256 -> 128
factual_head.output_layer.weight                                 128 -> 10
factual_recurrent.candidate_network.0.weight                      85 -> 64
factual_recurrent.candidate_network.4.weight                      64 -> 64
factual_recurrent.retention_layer.weight                          85 -> 64
factual_recurrent_group_adapter.network.0.weight                 128 -> 64
factual_recurrent_group_adapter.network.3.weight                  64 -> 64
factual_transform.core.0.weight                                   20 -> 128
factual_transform.core.4.weight                                  128 -> 10
factual_transform.gate.gate_layer.weight                          10 -> 10
factual_transform.tw_predictor.network.0.weight                   20 -> 128
factual_transform.tw_predictor.network.3.weight                  128 -> 1
factual_transform_group_adapter.network.0.weight                  74 -> 128
factual_transform_group_adapter.network.3.weight                 128 -> 10
psychological_group_adapter.network.0.weight                      98 -> 128
psychological_group_adapter.network.3.weight                     128 -> 34
psychological_head.core.network.0.weight                         256 -> 128
psychological_head.output_layer.weight                           128 -> 34
psychological_transform.core.0.weight                             68 -> 128
psychological_transform.core.4.weight                            128 -> 34
psychological_transform.gate.gate_layer.weight                    34 -> 34
psychological_transform.tw_predictor.network.0.weight             68 -> 128
psychological_transform.tw_predictor.network.3.weight            128 -> 1
psychological_transform_group_adapter.network.0.weight            98 -> 128
psychological_transform_group_adapter.network.3.weight           128 -> 34
social_group_adapter.network.0.weight                            192 -> 128
social_group_adapter.network.3.weight                            128 -> 128
social_head.actor_projection.weight                              128 -> 128
social_head.core.network.0.weight                                256 -> 128
social_head.group_projection.weight                              128 -> 128
social_head.membership_projection.weight                         128 -> 128

## Block 4 — Factual Model Restoration, Parameter-Freezing Policy and Controlled Forward-Path Validation

This block restores the persisted Media AI model state required by the factual path, establishes the Notebook 06 parameter-trainability boundary, and validates the factual architectural forward path against the ten-dimensional factual target contract defined in Blocks 2 and 3.

The block does **not** perform factual optimisation or training.

### Model restoration

The Media AI architecture is reconstructed using the validated architectural contract inherited from Notebook 05.

The persisted Notebook 05 controlled experimental checkpoint is used to restore the completed psychological-path model state.

Restoration must preserve:

- the 768-dimensional contextual representation interface;
- the global confluent representation path;
- the ten-dimensional factual representation head;
- the completed psychological representation head;
- all existing social, transformative and recurrent architectural components;
- the established global-path requirement;
- the optional group-conditioned path boundary.

The restored psychological state must reproduce the persisted Notebook 05 checkpoint rather than being reinitialised or retrained.

The contextual `all-mpnet-base-v2` encoder remains external to the trainable Media AI parameter set and remains frozen.

### Parameter-freezing policy

Notebook 06 introduces a factual-path-specific trainability boundary.

Only parameters belonging explicitly to the factual representation head may become trainable for subsequent controlled factual optimisation.

The following components must remain frozen:

- contextual sentence encoder;
- backbone interface;
- global confluent representation layers;
- completed psychological representation head;
- social representation head;
- factual, psychological and social transformative mechanisms;
- Transformative Weight components;
- recurrent-state components;
- group-conditioned components;
- all other Media AI parameters outside the factual head.

The completed psychological path must remain unchanged throughout Notebook 06 unless a later block explicitly establishes a different validated policy.

Parameter ownership must be verified directly. The block must confirm that every trainable parameter belongs to the factual head and that no factual-head parameter intended for controlled optimisation remains unintentionally frozen.

No optimiser is created by this block.

### Ten-dimensional factual output contract

The factual representation head remains architecturally **ten-dimensional**:

- **F1** — explicit claim
- **F2** — observation or event
- **F3** — quantitative information
- **F4** — attribution
- **F5** — evidence reference
- **F6** — certainty statement
- **F7** — uncertainty statement
- **F8** — speculation
- **F9** — prediction
- **F10** — factological weight

The current Block 3 optimisation eligibility policy must not alter the dimensionality of the factual representation.

Five dimensions are currently eligible for the controlled factual objective:

- F2 — observation or event;
- F3 — quantitative information;
- F5 — evidence reference;
- F9 — prediction;
- F10 — factological weight.

Five dimensions remain deferred because the current sixteen-sentence supervision sample contains no target variation:

- F1 — explicit claim;
- F4 — attribution;
- F6 — certainty statement;
- F7 — uncertainty statement;
- F8 — speculation.

Deferred dimensions remain valid architectural outputs. They must not be deleted, merged, replaced, assigned fabricated supervision, or interpreted as irrelevant factual components.

Their deferral applies only to the current controlled optimisation objective.

### Controlled factual forward path

Using the validated contextual sentence representations persisted by Notebook 05, the block executes a **controlled no-update forward pass** through the architectural stages required to reach the factual head.

The expected path is:

**contextual sentence representation → frozen backbone interface → frozen global confluent representation → factual representation head → F1–F10**

The block validates:

- contextual input dimensionality;
- backbone output dimensionality;
- confluent representation dimensionality;
- factual output dimensionality;
- sentence-count alignment;
- canonical sentence-ID alignment;
- finite numerical outputs;
- absence of unexpected shape transformation;
- preservation of sentence order;
- preservation of article boundaries.

The factual output must have shape:

**number of canonical sentences × 10 factual dimensions**

For the current controlled dataset, the expected factual output shape is therefore:

**16 × 10**

The controlled forward pass validates architectural compatibility only. Its untrained factual predictions must not be interpreted as meaningful factual estimates or empirical model performance.

### Active-dimension selection validation

The block verifies that the ten-dimensional factual output can be mapped deterministically to the Block 3 activation policy.

The active output indices must correspond exactly to:

- F2;
- F3;
- F5;
- F9;
- F10.

The deferred output indices must correspond exactly to:

- F1;
- F4;
- F6;
- F7;
- F8.

Selection of active dimensions is an **objective-layer operation** and must not change the factual-head architecture.

The block must verify that binary and continuous targets remain distinguishable:

- F2, F3, F5 and F9 use the binary factual target contract;
- F10 uses the continuous factological-weight contract.

The Block 3 imbalance policy must also remain intact. F9 retains its explicit imbalance caution and recommended positive-class weight of `7.0`. F2, F3 and F5 must not automatically receive class weighting merely because a positive-to-negative ratio can be calculated.

### Supervision and masking boundary

The factual forward output and the persisted factual target contract must remain aligned by canonical sentence identity.

Element-level masks remain authoritative.

Missing or insufficient-evidence supervision must not:

- be converted to zero;
- be converted to negative evidence;
- enter the factual objective;
- alter factual output dimensionality.

Zero-variance dimensions remain deferred from optimisation rather than being assigned artificial variation.

No synthetic or fabricated factual targets are permitted.

### Representation orientation

The factual prediction unit remains the canonical sentence.

The factual head predicts sentence-level F1–F10 representations from the validated contextual representation path.

Where factual interpretation requires preceding textual context, the target remains attached to the current sentence. Future sentence context remains prohibited.

The current block does not convert factual prediction into article-level classification.

Broader article-level effects remain reserved for later transformative, recurrent and group-conditioned processing.

### Controlled validation boundary

The forward pass in this block is performed solely to validate:

- model restoration;
- parameter ownership;
- freezing policy;
- factual-head connectivity;
- factual output shape;
- numerical validity;
- active/deferred dimension selection;
- compatibility with the persisted Block 3 objective policy.

No supervised factual loss is calculated in this block.

No gradient operation or parameter update is permitted.

### Execution boundary

This block may:

- reconstruct the Media AI architecture;
- reload the persisted Notebook 05 checkpoint;
- restore the completed psychological-path state;
- reload validated contextual sentence representations;
- configure factual-head trainability;
- freeze all unrelated model components;
- execute a controlled no-update factual forward pass;
- inspect factual outputs;
- validate active and deferred output selection;
- verify compatibility with the persisted factual target and objective-policy artefacts.

It must not:

- create a factual optimiser;
- calculate the supervised factual objective;
- execute `zero_grad`;
- execute a backward pass;
- perform an optimiser step;
- update model parameters;
- retrain the psychological path;
- train social, transformative, Transformative Weight, recurrent or group-conditioned components;
- fabricate supervision;
- perform held-out evaluation;
- claim generalisation or empirical validity.

### Block completion criterion

Block 4 is complete only if the persisted Media AI model can be restored consistently, the completed psychological path remains preserved and frozen, trainability is restricted exclusively to the factual head, the controlled factual forward path produces a finite and correctly aligned ten-dimensional output, and the Block 3 active/deferred dimension policy maps correctly onto that output.

Successful completion establishes that the Media AI architecture is technically ready for factual objective assembly.

It does **not** establish that factual optimisation has occurred or that the factual representation is empirically validated.

The next block may proceed to **Factual Objective Assembly, Optimiser Policy and Controlled Loss Validation**.

In [6]:
# =============================================================================
# Media AI — Notebook 06
# Block 4: Factual Model Restoration, Parameter-Freezing Policy
#          and Controlled Forward-Path Validation
# =============================================================================

from datetime import datetime, timezone

import io
import json
import math

import numpy as np
import torch
import torch.nn as nn

from googleapiclient.http import MediaIoBaseDownload


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_06_BLOCK_4 = 4

NOTEBOOK_06_BLOCK_4_NAME = (
    "Factual Model Restoration, Parameter-Freezing Policy "
    "and Controlled Forward-Path Validation"
)

NOTEBOOK_06_BLOCK_4_VERSION = "1.4"

NOTEBOOK_06_BLOCK_4_EXECUTED_AT_UTC = datetime.now(
    timezone.utc
).isoformat()


# =============================================================================
# Runtime prerequisites
# =============================================================================

required_block_4_objects = [
    # Block 1
    "NOTEBOOK_06_BLOCK_1_COMPLETE",
    "NOTEBOOK_06_BLOCK_1_VALID",
    "NOTEBOOK_06_DRIVE_SERVICE",
    "NOTEBOOK_06_SENTENCE_COUNT",
    "NOTEBOOK_06_SENTENCE_IDS",

    # Persisted Notebook 05 artefacts
    "NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_DRIVE_FILE_ID",
    "NOTEBOOK_06_PSYCHOLOGICAL_METADATA_DRIVE_FILE_ID",
    "NOTEBOOK_06_REPRESENTATION_DRIVE_FILE_ID",

    # Block 2
    "NOTEBOOK_06_BLOCK_2_COMPLETE",
    "NOTEBOOK_06_BLOCK_2_VALID",
    "NOTEBOOK_06_FACTUAL_DIMENSION_IDS",
    "NOTEBOOK_06_FACTUAL_DIMENSION_ORDER",

    # Block 3
    "NOTEBOOK_06_BLOCK_3_COMPLETE",
    "NOTEBOOK_06_BLOCK_3_VALID",
    "NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS",
    "NOTEBOOK_06_FACTUAL_LOSS_CONTRACT",
    "NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID",
    "NOTEBOOK_06_READY_FOR_FACTUAL_MODEL_AND_PARAMETER_POLICY",
]


missing_block_4_objects = [
    name
    for name in required_block_4_objects
    if name not in globals()
]


if missing_block_4_objects:
    raise NameError(
        "Notebook 06 Block 4 prerequisites are not initialised. "
        f"Missing: {missing_block_4_objects}"
    )


if not (
    NOTEBOOK_06_BLOCK_1_COMPLETE
    and NOTEBOOK_06_BLOCK_1_VALID
):
    raise ValueError(
        "Notebook 06 Block 1 must be complete and valid."
    )


if not (
    NOTEBOOK_06_BLOCK_2_COMPLETE
    and NOTEBOOK_06_BLOCK_2_VALID
):
    raise ValueError(
        "Notebook 06 Block 2 must be complete and valid."
    )


if not (
    NOTEBOOK_06_BLOCK_3_COMPLETE
    and NOTEBOOK_06_BLOCK_3_VALID
):
    raise ValueError(
        "Notebook 06 Block 3 must be complete and valid."
    )


if not NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID:
    raise ValueError(
        "Block 4 requires a valid Block 3 factual objective policy."
    )


if not NOTEBOOK_06_READY_FOR_FACTUAL_MODEL_AND_PARAMETER_POLICY:
    raise ValueError(
        "Notebook 06 is not ready for factual model restoration."
    )


# =============================================================================
# Architecture contract
# =============================================================================
#
# Persisted Notebook 05 topology establishes:
#
# contextual sentence representation : 768
# backbone projection                 : 768 -> 768
#
# mandatory global confluent path:
#   global_projection.0               : 768 -> 256
#   global_projection.3               : 256-dimensional affine
#                                      normalisation parameters
#
# optional group-conditioned path:
#   group_adapter.0                   : 320 -> 256
#   group_adapter.3                   : 256 -> 256
#
# factual head:
#   core.network.0                    : 256 -> 128
#   core.network.3                    : 128-dimensional affine
#                                      normalisation parameters
#   output_layer                      : 128 -> 10
#
# psychological head:
#   core.network.0                    : 256 -> 128
#   core.network.3                    : 128-dimensional affine
#                                      normalisation parameters
#   output_layer                      : 128 -> 34
#
# Notebook 06 executes only:
#
# contextual 768
#     -> backbone 768
#     -> global confluent 256
#     -> factual head 10
#
# The 320-dimensional group adapter is a separate optional path.
# It is audited here but is not reconstructed, executed or trained.
# =============================================================================

BLOCK_4_TEXTUAL_DIM = 768
BLOCK_4_BACKBONE_DIM = 768
BLOCK_4_CONFLUENT_DIM = 256

BLOCK_4_FACTUAL_HIDDEN_DIM = 128
BLOCK_4_FACTUAL_DIM = 10

BLOCK_4_PSYCHOLOGICAL_HIDDEN_DIM = 128
BLOCK_4_PSYCHOLOGICAL_DIM = 34

BLOCK_4_GROUP_INPUT_DIM = 320
BLOCK_4_GROUP_HIDDEN_DIM = 256
BLOCK_4_GROUP_OUTPUT_DIM = 256


BLOCK_4_ARCHITECTURE_DIMENSIONS_VALID = all(
    [
        BLOCK_4_TEXTUAL_DIM == 768,
        BLOCK_4_BACKBONE_DIM == 768,
        BLOCK_4_CONFLUENT_DIM == 256,
        BLOCK_4_FACTUAL_HIDDEN_DIM == 128,
        BLOCK_4_FACTUAL_DIM == 10,
        BLOCK_4_PSYCHOLOGICAL_HIDDEN_DIM == 128,
        BLOCK_4_PSYCHOLOGICAL_DIM == 34,
        BLOCK_4_GROUP_INPUT_DIM == 320,
        BLOCK_4_GROUP_HIDDEN_DIM == 256,
        BLOCK_4_GROUP_OUTPUT_DIM == 256,
    ]
)


# =============================================================================
# Factual target-contract cross-check
# =============================================================================

BLOCK_4_FACTUAL_DIMENSION_CONTRACT_VALID = all(
    [
        len(NOTEBOOK_06_FACTUAL_DIMENSION_IDS) == 10,
        len(NOTEBOOK_06_FACTUAL_DIMENSION_ORDER) == 10,
        BLOCK_4_FACTUAL_DIM == 10,
    ]
)


if not BLOCK_4_FACTUAL_DIMENSION_CONTRACT_VALID:
    raise ValueError(
        "The Block 2 factual target contract is inconsistent with "
        "the ten-dimensional factual architecture."
    )


# =============================================================================
# Google Drive download helper
# =============================================================================

def block_4_download_drive_bytes(
    drive_service,
    file_id,
):
    request = drive_service.files().get_media(
        fileId=file_id
    )

    buffer = io.BytesIO()

    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )

    complete = False

    while not complete:
        _, complete = downloader.next_chunk()

    buffer.seek(0)

    return buffer.read()


# =============================================================================
# Reload persisted Notebook 05 checkpoint
# =============================================================================

BLOCK_4_CHECKPOINT_BYTES = block_4_download_drive_bytes(
    NOTEBOOK_06_DRIVE_SERVICE,
    NOTEBOOK_06_PSYCHOLOGICAL_CHECKPOINT_DRIVE_FILE_ID,
)


if not BLOCK_4_CHECKPOINT_BYTES:
    raise RuntimeError(
        "Notebook 05 controlled training checkpoint could not be downloaded."
    )


BLOCK_4_CHECKPOINT_BUFFER = io.BytesIO(
    BLOCK_4_CHECKPOINT_BYTES
)


try:
    BLOCK_4_CHECKPOINT = torch.load(
        BLOCK_4_CHECKPOINT_BUFFER,
        map_location="cpu",
        weights_only=False,
    )

except TypeError:

    BLOCK_4_CHECKPOINT_BUFFER.seek(0)

    BLOCK_4_CHECKPOINT = torch.load(
        BLOCK_4_CHECKPOINT_BUFFER,
        map_location="cpu",
    )


if not isinstance(BLOCK_4_CHECKPOINT, dict):
    raise TypeError(
        "Notebook 05 checkpoint must be dictionary-like."
    )


if "model_state_dict" not in BLOCK_4_CHECKPOINT:
    raise KeyError(
        "Notebook 05 checkpoint does not contain model_state_dict."
    )


BLOCK_4_PERSISTED_MODEL_STATE = (
    BLOCK_4_CHECKPOINT[
        "model_state_dict"
    ]
)


if not isinstance(
    BLOCK_4_PERSISTED_MODEL_STATE,
    dict,
):
    raise TypeError(
        "Notebook 05 model_state_dict is invalid."
    )


BLOCK_4_CHECKPOINT_RELOADED = True


# =============================================================================
# Reload persisted Notebook 05 metadata
# =============================================================================

BLOCK_4_METADATA_BYTES = block_4_download_drive_bytes(
    NOTEBOOK_06_DRIVE_SERVICE,
    NOTEBOOK_06_PSYCHOLOGICAL_METADATA_DRIVE_FILE_ID,
)


BLOCK_4_CHECKPOINT_METADATA = json.loads(
    BLOCK_4_METADATA_BYTES.decode(
        "utf-8"
    )
)


if not isinstance(
    BLOCK_4_CHECKPOINT_METADATA,
    dict,
):
    raise TypeError(
        "Notebook 05 checkpoint metadata must be a JSON object."
    )


BLOCK_4_METADATA_RELOADED = True


# =============================================================================
# Required checkpoint parameters
# =============================================================================

BLOCK_4_EXECUTED_PATH_STATE_SHAPES = {
    # Backbone
    "backbone.projection.weight":
        (768, 768),

    "backbone.projection.bias":
        (768,),

    # Mandatory global confluent path
    "confluent.global_projection.0.weight":
        (256, 768),

    "confluent.global_projection.0.bias":
        (256,),

    "confluent.global_projection.3.weight":
        (256,),

    "confluent.global_projection.3.bias":
        (256,),

    # Factual head
    "factual_head.core.network.0.weight":
        (128, 256),

    "factual_head.core.network.0.bias":
        (128,),

    "factual_head.core.network.3.weight":
        (128,),

    "factual_head.core.network.3.bias":
        (128,),

    "factual_head.output_layer.weight":
        (10, 128),

    "factual_head.output_layer.bias":
        (10,),

    # Completed psychological head
    "psychological_head.core.network.0.weight":
        (128, 256),

    "psychological_head.core.network.0.bias":
        (128,),

    "psychological_head.core.network.3.weight":
        (128,),

    "psychological_head.core.network.3.bias":
        (128,),

    "psychological_head.output_layer.weight":
        (34, 128),

    "psychological_head.output_layer.bias":
        (34,),
}


BLOCK_4_GROUP_PATH_STATE_SHAPES = {
    "confluent.group_adapter.0.weight":
        (256, 320),

    "confluent.group_adapter.0.bias":
        (256,),

    "confluent.group_adapter.3.weight":
        (256, 256),

    "confluent.group_adapter.3.bias":
        (256,),
}


BLOCK_4_REQUIRED_STATE_SHAPES = {
    **BLOCK_4_EXECUTED_PATH_STATE_SHAPES,
    **BLOCK_4_GROUP_PATH_STATE_SHAPES,
}


BLOCK_4_MISSING_STATE_KEYS = [
    key
    for key in BLOCK_4_REQUIRED_STATE_SHAPES
    if key not in BLOCK_4_PERSISTED_MODEL_STATE
]


if BLOCK_4_MISSING_STATE_KEYS:
    raise KeyError(
        "Persisted Notebook 05 model state is missing required "
        "architecture parameters. "
        f"Missing: {BLOCK_4_MISSING_STATE_KEYS}"
    )


BLOCK_4_STATE_SHAPE_ERRORS = []


for key, expected_shape in (
    BLOCK_4_REQUIRED_STATE_SHAPES.items()
):

    observed_shape = tuple(
        BLOCK_4_PERSISTED_MODEL_STATE[
            key
        ].shape
    )

    if observed_shape != expected_shape:

        BLOCK_4_STATE_SHAPE_ERRORS.append(
            {
                "parameter":
                    key,

                "expected":
                    expected_shape,

                "observed":
                    observed_shape,
            }
        )


BLOCK_4_PARAMETER_TOPOLOGY_VALID = (
    len(BLOCK_4_STATE_SHAPE_ERRORS) == 0
)


if not BLOCK_4_PARAMETER_TOPOLOGY_VALID:
    raise RuntimeError(
        "Persisted Notebook 05 parameter topology does not match "
        "the validated Media AI architecture. "
        f"Errors: {BLOCK_4_STATE_SHAPE_ERRORS}"
    )


# =============================================================================
# Persisted-state helper
# =============================================================================

def block_4_clone_state(
    mapping,
):
    return {
        key:
            value.detach().cpu().clone()
        for key, value in mapping.items()
    }


# =============================================================================
# Executed global-path module definitions
# =============================================================================
#
# Only the modules required by Notebook 06's global factual path are
# reconstructed.
#
# The one-dimensional weight+bias pairs at:
#
#   confluent.global_projection.3
#   factual_head.core.network.3
#   psychological_head.core.network.3
#
# are reconstructed as LayerNorm affine parameters, consistent with the
# persisted topology used by the validated Notebook 05 representation heads.
#
# The group adapter is NOT reconstructed because its .3 parameter is a
# separate 256 -> 256 Linear layer and the entire group-conditioned path
# remains outside Notebook 06.
# =============================================================================

class Block4Backbone(nn.Module):

    def __init__(self):
        super().__init__()

        self.projection = nn.Linear(
            BLOCK_4_TEXTUAL_DIM,
            BLOCK_4_BACKBONE_DIM,
        )

    def forward(self, x):
        return self.projection(x)


class Block4GlobalConfluent(nn.Module):

    def __init__(self):
        super().__init__()

        self.global_projection = nn.Sequential(
            nn.Linear(
                BLOCK_4_BACKBONE_DIM,
                BLOCK_4_CONFLUENT_DIM,
            ),
            nn.ReLU(),
            nn.Dropout(p=0.0),
            nn.LayerNorm(
                BLOCK_4_CONFLUENT_DIM
            ),
        )

    def forward(self, x):
        return self.global_projection(x)


class Block4RepresentationCore(nn.Module):

    def __init__(
        self,
        input_dim,
        hidden_dim,
    ):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(
                input_dim,
                hidden_dim,
            ),
            nn.ReLU(),
            nn.Dropout(p=0.0),
            nn.LayerNorm(
                hidden_dim
            ),
        )

    def forward(self, x):
        return self.network(x)


class Block4FactualHead(nn.Module):

    def __init__(self):
        super().__init__()

        self.core = Block4RepresentationCore(
            input_dim=BLOCK_4_CONFLUENT_DIM,
            hidden_dim=BLOCK_4_FACTUAL_HIDDEN_DIM,
        )

        self.output_layer = nn.Linear(
            BLOCK_4_FACTUAL_HIDDEN_DIM,
            BLOCK_4_FACTUAL_DIM,
        )

    def forward(self, x):

        hidden = self.core(x)

        return self.output_layer(
            hidden
        )


class Block4PsychologicalHead(nn.Module):

    def __init__(self):
        super().__init__()

        self.core = Block4RepresentationCore(
            input_dim=BLOCK_4_CONFLUENT_DIM,
            hidden_dim=BLOCK_4_PSYCHOLOGICAL_HIDDEN_DIM,
        )

        self.output_layer = nn.Linear(
            BLOCK_4_PSYCHOLOGICAL_HIDDEN_DIM,
            BLOCK_4_PSYCHOLOGICAL_DIM,
        )

    def forward(self, x):

        hidden = self.core(x)

        return self.output_layer(
            hidden
        )


# =============================================================================
# Instantiate executed global path
# =============================================================================

BLOCK_4_BACKBONE = (
    Block4Backbone()
)

BLOCK_4_GLOBAL_CONFLUENT = (
    Block4GlobalConfluent()
)

BLOCK_4_FACTUAL_HEAD = (
    Block4FactualHead()
)

BLOCK_4_PSYCHOLOGICAL_HEAD = (
    Block4PsychologicalHead()
)


# =============================================================================
# Build exact persisted submodule states
# =============================================================================

BLOCK_4_BACKBONE_STATE = block_4_clone_state(
    {
        "projection.weight":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "backbone.projection.weight"
            ],

        "projection.bias":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "backbone.projection.bias"
            ],
    }
)


BLOCK_4_GLOBAL_CONFLUENT_STATE = block_4_clone_state(
    {
        "global_projection.0.weight":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "confluent.global_projection.0.weight"
            ],

        "global_projection.0.bias":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "confluent.global_projection.0.bias"
            ],

        "global_projection.3.weight":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "confluent.global_projection.3.weight"
            ],

        "global_projection.3.bias":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "confluent.global_projection.3.bias"
            ],
    }
)


BLOCK_4_FACTUAL_HEAD_STATE = block_4_clone_state(
    {
        "core.network.0.weight":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "factual_head.core.network.0.weight"
            ],

        "core.network.0.bias":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "factual_head.core.network.0.bias"
            ],

        "core.network.3.weight":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "factual_head.core.network.3.weight"
            ],

        "core.network.3.bias":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "factual_head.core.network.3.bias"
            ],

        "output_layer.weight":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "factual_head.output_layer.weight"
            ],

        "output_layer.bias":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "factual_head.output_layer.bias"
            ],
    }
)


BLOCK_4_PSYCHOLOGICAL_HEAD_STATE = block_4_clone_state(
    {
        "core.network.0.weight":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "psychological_head.core.network.0.weight"
            ],

        "core.network.0.bias":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "psychological_head.core.network.0.bias"
            ],

        "core.network.3.weight":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "psychological_head.core.network.3.weight"
            ],

        "core.network.3.bias":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "psychological_head.core.network.3.bias"
            ],

        "output_layer.weight":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "psychological_head.output_layer.weight"
            ],

        "output_layer.bias":
            BLOCK_4_PERSISTED_MODEL_STATE[
                "psychological_head.output_layer.bias"
            ],
    }
)


# =============================================================================
# Restore persisted states
# =============================================================================

BLOCK_4_BACKBONE.load_state_dict(
    BLOCK_4_BACKBONE_STATE,
    strict=True,
)


BLOCK_4_GLOBAL_CONFLUENT.load_state_dict(
    BLOCK_4_GLOBAL_CONFLUENT_STATE,
    strict=True,
)


BLOCK_4_FACTUAL_HEAD.load_state_dict(
    BLOCK_4_FACTUAL_HEAD_STATE,
    strict=True,
)


BLOCK_4_PSYCHOLOGICAL_HEAD.load_state_dict(
    BLOCK_4_PSYCHOLOGICAL_HEAD_STATE,
    strict=True,
)


# =============================================================================
# Exact state-reproduction validation
# =============================================================================

def block_4_state_matches(
    module,
    expected_state,
):
    actual_state = module.state_dict()

    if set(actual_state.keys()) != set(
        expected_state.keys()
    ):
        return False

    return all(
        torch.equal(
            actual_state[key].detach().cpu(),
            expected_state[key].detach().cpu(),
        )
        for key in expected_state
    )


BLOCK_4_BACKBONE_STATE_REPRODUCED = (
    block_4_state_matches(
        BLOCK_4_BACKBONE,
        BLOCK_4_BACKBONE_STATE,
    )
)


BLOCK_4_GLOBAL_CONFLUENT_STATE_REPRODUCED = (
    block_4_state_matches(
        BLOCK_4_GLOBAL_CONFLUENT,
        BLOCK_4_GLOBAL_CONFLUENT_STATE,
    )
)


BLOCK_4_FACTUAL_STATE_REPRODUCED = (
    block_4_state_matches(
        BLOCK_4_FACTUAL_HEAD,
        BLOCK_4_FACTUAL_HEAD_STATE,
    )
)


BLOCK_4_PSYCHOLOGICAL_STATE_REPRODUCED = (
    block_4_state_matches(
        BLOCK_4_PSYCHOLOGICAL_HEAD,
        BLOCK_4_PSYCHOLOGICAL_HEAD_STATE,
    )
)


BLOCK_4_ALL_EXECUTED_STATES_REPRODUCED = all(
    [
        BLOCK_4_BACKBONE_STATE_REPRODUCED,
        BLOCK_4_GLOBAL_CONFLUENT_STATE_REPRODUCED,
        BLOCK_4_FACTUAL_STATE_REPRODUCED,
        BLOCK_4_PSYCHOLOGICAL_STATE_REPRODUCED,
    ]
)


if not BLOCK_4_ALL_EXECUTED_STATES_REPRODUCED:
    raise RuntimeError(
        "One or more persisted global-path states were not "
        "reproduced exactly."
    )


# =============================================================================
# Optional group-conditioned path audit
# =============================================================================
#
# The group path is architecturally present but is not part of the current
# Notebook 06 factual execution path.
#
# We validate its persisted parameter topology only.
#
# We do NOT:
# - concatenate a 320-dimensional input,
# - reconstruct the group adapter,
# - execute it,
# - train it,
# - infer group semantics.
# =============================================================================

BLOCK_4_GROUP_ADAPTER_FIRST_WEIGHT_SHAPE = tuple(
    BLOCK_4_PERSISTED_MODEL_STATE[
        "confluent.group_adapter.0.weight"
    ].shape
)


BLOCK_4_GROUP_ADAPTER_FIRST_BIAS_SHAPE = tuple(
    BLOCK_4_PERSISTED_MODEL_STATE[
        "confluent.group_adapter.0.bias"
    ].shape
)


BLOCK_4_GROUP_ADAPTER_SECOND_WEIGHT_SHAPE = tuple(
    BLOCK_4_PERSISTED_MODEL_STATE[
        "confluent.group_adapter.3.weight"
    ].shape
)


BLOCK_4_GROUP_ADAPTER_SECOND_BIAS_SHAPE = tuple(
    BLOCK_4_PERSISTED_MODEL_STATE[
        "confluent.group_adapter.3.bias"
    ].shape
)


BLOCK_4_GROUP_ADAPTER_TOPOLOGY_VALID = all(
    [
        BLOCK_4_GROUP_ADAPTER_FIRST_WEIGHT_SHAPE
        == (256, 320),

        BLOCK_4_GROUP_ADAPTER_FIRST_BIAS_SHAPE
        == (256,),

        BLOCK_4_GROUP_ADAPTER_SECOND_WEIGHT_SHAPE
        == (256, 256),

        BLOCK_4_GROUP_ADAPTER_SECOND_BIAS_SHAPE
        == (256,),
    ]
)


if not BLOCK_4_GROUP_ADAPTER_TOPOLOGY_VALID:
    raise RuntimeError(
        "Persisted optional group-adapter topology is invalid."
    )


BLOCK_4_GROUP_PATH_AVAILABLE = True
BLOCK_4_GROUP_PATH_REQUIRED = False
BLOCK_4_GROUP_PATH_EXECUTED = False
BLOCK_4_GROUP_PATH_TRAINED = False
BLOCK_4_GROUP_PATH_DEFERRED_TO_NOTEBOOK = 10


# =============================================================================
# Parameter-freezing policy
# =============================================================================

for parameter in BLOCK_4_BACKBONE.parameters():
    parameter.requires_grad = False


for parameter in BLOCK_4_GLOBAL_CONFLUENT.parameters():
    parameter.requires_grad = False


for parameter in BLOCK_4_PSYCHOLOGICAL_HEAD.parameters():
    parameter.requires_grad = False


for parameter in BLOCK_4_FACTUAL_HEAD.parameters():
    parameter.requires_grad = True


BLOCK_4_BACKBONE_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in BLOCK_4_BACKBONE.parameters()
)


BLOCK_4_GLOBAL_CONFLUENT_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in BLOCK_4_GLOBAL_CONFLUENT.parameters()
)


BLOCK_4_PSYCHOLOGICAL_HEAD_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in BLOCK_4_PSYCHOLOGICAL_HEAD.parameters()
)


BLOCK_4_FACTUAL_HEAD_TRAINABLE = all(
    parameter.requires_grad
    for parameter
    in BLOCK_4_FACTUAL_HEAD.parameters()
)


BLOCK_4_BACKBONE_TRAINABLE_PARAMETERS = sum(
    parameter.numel()
    for parameter
    in BLOCK_4_BACKBONE.parameters()
    if parameter.requires_grad
)


BLOCK_4_CONFLUENT_TRAINABLE_PARAMETERS = sum(
    parameter.numel()
    for parameter
    in BLOCK_4_GLOBAL_CONFLUENT.parameters()
    if parameter.requires_grad
)


BLOCK_4_PSYCHOLOGICAL_TRAINABLE_PARAMETERS = sum(
    parameter.numel()
    for parameter
    in BLOCK_4_PSYCHOLOGICAL_HEAD.parameters()
    if parameter.requires_grad
)


BLOCK_4_FACTUAL_TRAINABLE_PARAMETERS = sum(
    parameter.numel()
    for parameter
    in BLOCK_4_FACTUAL_HEAD.parameters()
    if parameter.requires_grad
)


BLOCK_4_EXPECTED_FACTUAL_PARAMETER_COUNT = 34442


BLOCK_4_FACTUAL_PARAMETER_COUNT_VALID = (
    BLOCK_4_FACTUAL_TRAINABLE_PARAMETERS
    ==
    BLOCK_4_EXPECTED_FACTUAL_PARAMETER_COUNT
)


BLOCK_4_PARAMETER_SCOPE_VALID = all(
    [
        BLOCK_4_BACKBONE_FROZEN,
        BLOCK_4_GLOBAL_CONFLUENT_FROZEN,
        BLOCK_4_PSYCHOLOGICAL_HEAD_FROZEN,
        BLOCK_4_FACTUAL_HEAD_TRAINABLE,

        BLOCK_4_BACKBONE_TRAINABLE_PARAMETERS == 0,
        BLOCK_4_CONFLUENT_TRAINABLE_PARAMETERS == 0,
        BLOCK_4_PSYCHOLOGICAL_TRAINABLE_PARAMETERS == 0,

        BLOCK_4_FACTUAL_PARAMETER_COUNT_VALID,
    ]
)


if not BLOCK_4_PARAMETER_SCOPE_VALID:
    raise RuntimeError(
        "Notebook 06 factual parameter-freezing policy is invalid."
    )


# =============================================================================
# Reload persisted contextual sentence representations
# =============================================================================

BLOCK_4_REPRESENTATION_BYTES = block_4_download_drive_bytes(
    NOTEBOOK_06_DRIVE_SERVICE,
    NOTEBOOK_06_REPRESENTATION_DRIVE_FILE_ID,
)


BLOCK_4_REPRESENTATION_ARTEFACT = json.loads(
    BLOCK_4_REPRESENTATION_BYTES.decode(
        "utf-8"
    )
)


# =============================================================================
# Locate representation records
# =============================================================================

def block_4_find_representation_records(
    artefact,
):
    if isinstance(artefact, list):
        return artefact

    if not isinstance(artefact, dict):
        raise TypeError(
            "Contextual representation artefact has an unsupported type."
        )

    candidate_keys = [
        "records",
        "representations",
        "sentence_representations",
        "contextual_sentence_representations",
        "data",
    ]

    for key in candidate_keys:

        value = artefact.get(key)

        if isinstance(value, list):
            return value

    raise KeyError(
        "Could not locate sentence representation records in the "
        "persisted Notebook 05 representation artefact."
    )


BLOCK_4_REPRESENTATION_RECORDS = (
    block_4_find_representation_records(
        BLOCK_4_REPRESENTATION_ARTEFACT
    )
)


if (
    len(BLOCK_4_REPRESENTATION_RECORDS)
    != NOTEBOOK_06_SENTENCE_COUNT
):
    raise RuntimeError(
        "Persisted contextual representation count does not match "
        "Notebook 06 canonical sentence count."
    )


# =============================================================================
# Representation-record helpers
# =============================================================================

def block_4_get_sentence_id(
    record,
):
    if not isinstance(record, dict):
        raise TypeError(
            "Representation record must be a dictionary."
        )

    if record.get("sentence_id") is not None:
        return record["sentence_id"]

    identity = record.get(
        "identity"
    )

    if isinstance(identity, dict):

        if identity.get(
            "sentence_id"
        ) is not None:
            return identity[
                "sentence_id"
            ]

    raise KeyError(
        "Representation record does not contain sentence_id."
    )


def block_4_get_vector(
    record,
):
    candidate_keys = [
        "textual_representation",
        "representation",
        "embedding",
        "sentence_embedding",
        "contextual_representation",
        "vector",
    ]

    for key in candidate_keys:

        if (
            key in record
            and record[key] is not None
        ):
            return record[key]

    raise KeyError(
        "Representation record does not contain a contextual vector."
    )


BLOCK_4_REPRESENTATION_SENTENCE_IDS = [
    block_4_get_sentence_id(
        record
    )
    for record
    in BLOCK_4_REPRESENTATION_RECORDS
]


BLOCK_4_REPRESENTATION_SENTENCE_IDS_PRESENT = all(
    sentence_id is not None
    for sentence_id
    in BLOCK_4_REPRESENTATION_SENTENCE_IDS
)


BLOCK_4_REPRESENTATION_SENTENCE_IDS_UNIQUE = (
    len(
        BLOCK_4_REPRESENTATION_SENTENCE_IDS
    )
    ==
    len(
        set(
            BLOCK_4_REPRESENTATION_SENTENCE_IDS
        )
    )
)


BLOCK_4_REPRESENTATION_BY_SENTENCE_ID = {
    block_4_get_sentence_id(record):
        record
    for record
    in BLOCK_4_REPRESENTATION_RECORDS
}


BLOCK_4_SENTENCE_ALIGNMENT_VALID = (
    set(
        BLOCK_4_REPRESENTATION_BY_SENTENCE_ID.keys()
    )
    ==
    set(
        NOTEBOOK_06_SENTENCE_IDS
    )
)


if not BLOCK_4_SENTENCE_ALIGNMENT_VALID:
    raise RuntimeError(
        "Persisted contextual representations do not align with "
        "Notebook 06 canonical sentence identity."
    )


BLOCK_4_ORDERED_REPRESENTATION_RECORDS = [
    BLOCK_4_REPRESENTATION_BY_SENTENCE_ID[
        sentence_id
    ]
    for sentence_id
    in NOTEBOOK_06_SENTENCE_IDS
]


# =============================================================================
# Construct contextual representation tensor
# =============================================================================

BLOCK_4_CONTEXTUAL_ARRAY = np.asarray(
    [
        block_4_get_vector(
            record
        )
        for record
        in BLOCK_4_ORDERED_REPRESENTATION_RECORDS
    ],
    dtype=np.float32,
)


BLOCK_4_CONTEXTUAL_REPRESENTATIONS = torch.from_numpy(
    BLOCK_4_CONTEXTUAL_ARRAY
).to(
    dtype=torch.float32
)


BLOCK_4_CONTEXTUAL_INPUT_SHAPE = tuple(
    BLOCK_4_CONTEXTUAL_REPRESENTATIONS.shape
)


BLOCK_4_CONTEXTUAL_INPUT_SHAPE_VALID = (
    BLOCK_4_CONTEXTUAL_INPUT_SHAPE
    ==
    (
        NOTEBOOK_06_SENTENCE_COUNT,
        BLOCK_4_TEXTUAL_DIM,
    )
)


BLOCK_4_CONTEXTUAL_INPUT_FINITE = bool(
    torch.isfinite(
        BLOCK_4_CONTEXTUAL_REPRESENTATIONS
    ).all().item()
)


if not BLOCK_4_CONTEXTUAL_INPUT_SHAPE_VALID:
    raise RuntimeError(
        "Contextual representation tensor has invalid shape. "
        f"Observed: {BLOCK_4_CONTEXTUAL_INPUT_SHAPE}; "
        f"expected: "
        f"({NOTEBOOK_06_SENTENCE_COUNT}, {BLOCK_4_TEXTUAL_DIM})."
    )


if not BLOCK_4_CONTEXTUAL_INPUT_FINITE:
    raise RuntimeError(
        "Contextual representation tensor contains non-finite values."
    )


# =============================================================================
# Parameter snapshots before controlled forward pass
# =============================================================================

def block_4_snapshot_parameters(
    module,
):
    return {
        name:
            parameter.detach().cpu().clone()
        for name, parameter
        in module.named_parameters()
    }


BLOCK_4_BACKBONE_BEFORE_FORWARD = (
    block_4_snapshot_parameters(
        BLOCK_4_BACKBONE
    )
)


BLOCK_4_CONFLUENT_BEFORE_FORWARD = (
    block_4_snapshot_parameters(
        BLOCK_4_GLOBAL_CONFLUENT
    )
)


BLOCK_4_FACTUAL_BEFORE_FORWARD = (
    block_4_snapshot_parameters(
        BLOCK_4_FACTUAL_HEAD
    )
)


BLOCK_4_PSYCHOLOGICAL_BEFORE_FORWARD = (
    block_4_snapshot_parameters(
        BLOCK_4_PSYCHOLOGICAL_HEAD
    )
)


# =============================================================================
# Controlled mandatory-global forward path
# =============================================================================
#
# The group-conditioned path is intentionally not called.
#
# Executed path:
#
# contextual representation
#     -> backbone
#     -> confluent.global_projection
#     -> factual_head
# =============================================================================

BLOCK_4_BACKBONE.eval()
BLOCK_4_GLOBAL_CONFLUENT.eval()
BLOCK_4_FACTUAL_HEAD.eval()
BLOCK_4_PSYCHOLOGICAL_HEAD.eval()


with torch.no_grad():

    BLOCK_4_BACKBONE_OUTPUT = (
        BLOCK_4_BACKBONE(
            BLOCK_4_CONTEXTUAL_REPRESENTATIONS
        )
    )

    BLOCK_4_GLOBAL_CONFLUENT_OUTPUT = (
        BLOCK_4_GLOBAL_CONFLUENT(
            BLOCK_4_BACKBONE_OUTPUT
        )
    )

    BLOCK_4_FACTUAL_OUTPUT = (
        BLOCK_4_FACTUAL_HEAD(
            BLOCK_4_GLOBAL_CONFLUENT_OUTPUT
        )
    )


NOTEBOOK_06_FACTUAL_CONTROLLED_FORWARD_EXECUTED = True


# =============================================================================
# Controlled forward validation
# =============================================================================

BLOCK_4_BACKBONE_OUTPUT_SHAPE = tuple(
    BLOCK_4_BACKBONE_OUTPUT.shape
)


BLOCK_4_GLOBAL_CONFLUENT_OUTPUT_SHAPE = tuple(
    BLOCK_4_GLOBAL_CONFLUENT_OUTPUT.shape
)


BLOCK_4_FACTUAL_OUTPUT_SHAPE = tuple(
    BLOCK_4_FACTUAL_OUTPUT.shape
)


BLOCK_4_BACKBONE_OUTPUT_SHAPE_VALID = (
    BLOCK_4_BACKBONE_OUTPUT_SHAPE
    ==
    (
        NOTEBOOK_06_SENTENCE_COUNT,
        BLOCK_4_BACKBONE_DIM,
    )
)


BLOCK_4_GLOBAL_CONFLUENT_OUTPUT_SHAPE_VALID = (
    BLOCK_4_GLOBAL_CONFLUENT_OUTPUT_SHAPE
    ==
    (
        NOTEBOOK_06_SENTENCE_COUNT,
        BLOCK_4_CONFLUENT_DIM,
    )
)


BLOCK_4_FACTUAL_OUTPUT_SHAPE_VALID = (
    BLOCK_4_FACTUAL_OUTPUT_SHAPE
    ==
    (
        NOTEBOOK_06_SENTENCE_COUNT,
        BLOCK_4_FACTUAL_DIM,
    )
)


BLOCK_4_BACKBONE_OUTPUT_FINITE = bool(
    torch.isfinite(
        BLOCK_4_BACKBONE_OUTPUT
    ).all().item()
)


BLOCK_4_GLOBAL_CONFLUENT_OUTPUT_FINITE = bool(
    torch.isfinite(
        BLOCK_4_GLOBAL_CONFLUENT_OUTPUT
    ).all().item()
)


BLOCK_4_FACTUAL_OUTPUT_FINITE = bool(
    torch.isfinite(
        BLOCK_4_FACTUAL_OUTPUT
    ).all().item()
)


BLOCK_4_FORWARD_PATH_VALID = all(
    [
        BLOCK_4_BACKBONE_OUTPUT_SHAPE_VALID,
        BLOCK_4_GLOBAL_CONFLUENT_OUTPUT_SHAPE_VALID,
        BLOCK_4_FACTUAL_OUTPUT_SHAPE_VALID,
        BLOCK_4_BACKBONE_OUTPUT_FINITE,
        BLOCK_4_GLOBAL_CONFLUENT_OUTPUT_FINITE,
        BLOCK_4_FACTUAL_OUTPUT_FINITE,
    ]
)


if not BLOCK_4_FORWARD_PATH_VALID:
    raise RuntimeError(
        "Controlled Notebook 06 factual global forward path is invalid."
    )


# =============================================================================
# Factual activation mapping
# =============================================================================
#
# Block 3 is authoritative for factual objective availability.
# Block 4 therefore inherits the current active / deferred partition rather
# than imposing the earlier pilot-state five-active / five-deferred contract.
# =============================================================================

BLOCK_4_DIMENSION_INDEX = {
    dimension_name:
        index
    for index, dimension_name
    in enumerate(
        NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
    )
}


BLOCK_4_CANONICAL_FACTUAL_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
)


BLOCK_4_CANONICAL_FACTUAL_SET = set(
    BLOCK_4_CANONICAL_FACTUAL_DIMENSIONS
)


BLOCK_4_ACTIVE_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS
)


BLOCK_4_DEFERRED_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS
)


BLOCK_4_ACTIVE_BINARY_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS
)


BLOCK_4_ACTIVE_CONTINUOUS_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS
)


BLOCK_4_ACTIVE_DIMENSION_SET = set(
    BLOCK_4_ACTIVE_DIMENSIONS
)


BLOCK_4_DEFERRED_DIMENSION_SET = set(
    BLOCK_4_DEFERRED_DIMENSIONS
)


BLOCK_4_ACTIVE_BINARY_SET = set(
    BLOCK_4_ACTIVE_BINARY_DIMENSIONS
)


BLOCK_4_ACTIVE_CONTINUOUS_SET = set(
    BLOCK_4_ACTIVE_CONTINUOUS_DIMENSIONS
)


BLOCK_4_ACTIVE_DIMENSIONS_VALID = all(
    [
        len(BLOCK_4_ACTIVE_DIMENSIONS) > 0,
        len(BLOCK_4_ACTIVE_DIMENSIONS)
        == len(BLOCK_4_ACTIVE_DIMENSION_SET),
        BLOCK_4_ACTIVE_DIMENSION_SET.issubset(
            BLOCK_4_CANONICAL_FACTUAL_SET
        ),
    ]
)


BLOCK_4_DEFERRED_DIMENSIONS_VALID = all(
    [
        len(BLOCK_4_DEFERRED_DIMENSIONS)
        == len(BLOCK_4_DEFERRED_DIMENSION_SET),
        BLOCK_4_DEFERRED_DIMENSION_SET.issubset(
            BLOCK_4_CANONICAL_FACTUAL_SET
        ),
    ]
)


BLOCK_4_ACTIVE_DEFERRED_DISJOINT = (
    BLOCK_4_ACTIVE_DIMENSION_SET.isdisjoint(
        BLOCK_4_DEFERRED_DIMENSION_SET
    )
)


BLOCK_4_ACTIVE_DEFERRED_COMPLETE = (
    (
        BLOCK_4_ACTIVE_DIMENSION_SET
        | BLOCK_4_DEFERRED_DIMENSION_SET
    )
    == BLOCK_4_CANONICAL_FACTUAL_SET
)


BLOCK_4_BINARY_CONTRACT_VALID = all(
    [
        len(BLOCK_4_ACTIVE_BINARY_DIMENSIONS)
        == len(BLOCK_4_ACTIVE_BINARY_SET),
        BLOCK_4_ACTIVE_BINARY_SET.issubset(
            BLOCK_4_ACTIVE_DIMENSION_SET
        ),
    ]
)


BLOCK_4_CONTINUOUS_CONTRACT_VALID = all(
    [
        len(BLOCK_4_ACTIVE_CONTINUOUS_DIMENSIONS)
        == len(BLOCK_4_ACTIVE_CONTINUOUS_SET),
        BLOCK_4_ACTIVE_CONTINUOUS_SET.issubset(
            BLOCK_4_ACTIVE_DIMENSION_SET
        ),
    ]
)


BLOCK_4_BINARY_CONTINUOUS_DISJOINT = (
    BLOCK_4_ACTIVE_BINARY_SET.isdisjoint(
        BLOCK_4_ACTIVE_CONTINUOUS_SET
    )
)


BLOCK_4_ACTIVE_TYPE_COVERAGE_VALID = (
    (
        BLOCK_4_ACTIVE_BINARY_SET
        | BLOCK_4_ACTIVE_CONTINUOUS_SET
    )
    == BLOCK_4_ACTIVE_DIMENSION_SET
)


BLOCK_4_ACTIVATION_PARTITION_VALID = all(
    [
        BLOCK_4_ACTIVE_DIMENSIONS_VALID,
        BLOCK_4_DEFERRED_DIMENSIONS_VALID,
        BLOCK_4_ACTIVE_DEFERRED_DISJOINT,
        BLOCK_4_ACTIVE_DEFERRED_COMPLETE,
        BLOCK_4_BINARY_CONTRACT_VALID,
        BLOCK_4_CONTINUOUS_CONTRACT_VALID,
        BLOCK_4_BINARY_CONTINUOUS_DISJOINT,
        BLOCK_4_ACTIVE_TYPE_COVERAGE_VALID,
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID,
    ]
)


if not BLOCK_4_ACTIVATION_PARTITION_VALID:
    raise RuntimeError(
        "Block 3 factual activation policy is structurally "
        "inconsistent with the F1–F10 contract."
    )


BLOCK_4_ACTIVE_INDICES = tuple(
    BLOCK_4_DIMENSION_INDEX[
        dimension_name
    ]
    for dimension_name
    in BLOCK_4_ACTIVE_DIMENSIONS
)


BLOCK_4_DEFERRED_INDICES = tuple(
    BLOCK_4_DIMENSION_INDEX[
        dimension_name
    ]
    for dimension_name
    in BLOCK_4_DEFERRED_DIMENSIONS
)


BLOCK_4_ACTIVE_INDEX_MAPPING_VALID = all(
    [
        len(BLOCK_4_ACTIVE_INDICES)
        == len(BLOCK_4_ACTIVE_DIMENSIONS),
        len(BLOCK_4_ACTIVE_INDICES)
        == len(set(BLOCK_4_ACTIVE_INDICES)),
        all(
            0 <= index < BLOCK_4_FACTUAL_DIM
            for index
            in BLOCK_4_ACTIVE_INDICES
        ),
    ]
)


BLOCK_4_DEFERRED_INDEX_MAPPING_VALID = all(
    [
        len(BLOCK_4_DEFERRED_INDICES)
        == len(BLOCK_4_DEFERRED_DIMENSIONS),
        len(BLOCK_4_DEFERRED_INDICES)
        == len(set(BLOCK_4_DEFERRED_INDICES)),
        all(
            0 <= index < BLOCK_4_FACTUAL_DIM
            for index
            in BLOCK_4_DEFERRED_INDICES
        ),
    ]
)


BLOCK_4_ALL_INDICES_COVER_FACTUAL_SPACE = (
    (
        set(BLOCK_4_ACTIVE_INDICES)
        | set(BLOCK_4_DEFERRED_INDICES)
    )
    == set(range(BLOCK_4_FACTUAL_DIM))
)


if not all(
    [
        BLOCK_4_ACTIVE_INDEX_MAPPING_VALID,
        BLOCK_4_DEFERRED_INDEX_MAPPING_VALID,
        BLOCK_4_ALL_INDICES_COVER_FACTUAL_SPACE,
    ]
):
    raise RuntimeError(
        "Factual activation indices do not match the F1–F10 contract."
    )


BLOCK_4_ACTIVE_FACTUAL_OUTPUT = (
    BLOCK_4_FACTUAL_OUTPUT[
        :,
        list(
            BLOCK_4_ACTIVE_INDICES
        ),
    ]
)


BLOCK_4_DEFERRED_FACTUAL_OUTPUT = (
    BLOCK_4_FACTUAL_OUTPUT[
        :,
        list(
            BLOCK_4_DEFERRED_INDICES
        ),
    ]
)


BLOCK_4_ACTIVE_OUTPUT_SHAPE = tuple(
    BLOCK_4_ACTIVE_FACTUAL_OUTPUT.shape
)


BLOCK_4_DEFERRED_OUTPUT_SHAPE = tuple(
    BLOCK_4_DEFERRED_FACTUAL_OUTPUT.shape
)


BLOCK_4_ACTIVE_OUTPUT_SHAPE_VALID = (
    BLOCK_4_ACTIVE_OUTPUT_SHAPE
    ==
    (
        NOTEBOOK_06_SENTENCE_COUNT,
        len(BLOCK_4_ACTIVE_DIMENSIONS),
    )
)


BLOCK_4_DEFERRED_OUTPUT_SHAPE_VALID = (
    BLOCK_4_DEFERRED_OUTPUT_SHAPE
    ==
    (
        NOTEBOOK_06_SENTENCE_COUNT,
        len(BLOCK_4_DEFERRED_DIMENSIONS),
    )
)


# =============================================================================
# Imbalance-policy validation
# =============================================================================
#
# Positive-class weighting is inherited from Block 3. Every supplied weight
# must belong to an active binary dimension and must be finite and positive.
# Active binary dimensions without an explicit weight remain valid and use the
# unweighted binary objective downstream.
# =============================================================================

BLOCK_4_POSITIVE_CLASS_WEIGHTS = dict(
    NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS
)


BLOCK_4_WEIGHTED_DIMENSION_SET = set(
    BLOCK_4_POSITIVE_CLASS_WEIGHTS.keys()
)


BLOCK_4_WEIGHT_KEYS_VALID = (
    BLOCK_4_WEIGHTED_DIMENSION_SET.issubset(
        BLOCK_4_ACTIVE_BINARY_SET
    )
)


BLOCK_4_WEIGHT_VALUES_VALID = all(
    isinstance(
        weight_value,
        (
            int,
            float,
            np.integer,
            np.floating,
        ),
    )
    and math.isfinite(
        float(weight_value)
    )
    and float(weight_value) > 0.0
    for weight_value
    in BLOCK_4_POSITIVE_CLASS_WEIGHTS.values()
)


BLOCK_4_IMBALANCE_POLICY_VALID = all(
    [
        BLOCK_4_WEIGHT_KEYS_VALID,
        BLOCK_4_WEIGHT_VALUES_VALID,
    ]
)


if not BLOCK_4_IMBALANCE_POLICY_VALID:
    raise RuntimeError(
        "Block 3 factual imbalance policy is inconsistent "
        "with the Block 4 handover."
    )


# =============================================================================
# No-update validation
# =============================================================================

def block_4_parameters_unchanged(
    module,
    before_state,
):
    current_state = {
        name:
            parameter.detach().cpu()
        for name, parameter
        in module.named_parameters()
    }

    return all(
        torch.equal(
            current_state[name],
            before_state[name],
        )
        for name
        in before_state
    )


BLOCK_4_BACKBONE_PARAMETERS_UNCHANGED = (
    block_4_parameters_unchanged(
        BLOCK_4_BACKBONE,
        BLOCK_4_BACKBONE_BEFORE_FORWARD,
    )
)


BLOCK_4_CONFLUENT_PARAMETERS_UNCHANGED = (
    block_4_parameters_unchanged(
        BLOCK_4_GLOBAL_CONFLUENT,
        BLOCK_4_CONFLUENT_BEFORE_FORWARD,
    )
)


BLOCK_4_FACTUAL_PARAMETERS_UNCHANGED = (
    block_4_parameters_unchanged(
        BLOCK_4_FACTUAL_HEAD,
        BLOCK_4_FACTUAL_BEFORE_FORWARD,
    )
)


BLOCK_4_PSYCHOLOGICAL_PARAMETERS_UNCHANGED = (
    block_4_parameters_unchanged(
        BLOCK_4_PSYCHOLOGICAL_HEAD,
        BLOCK_4_PSYCHOLOGICAL_BEFORE_FORWARD,
    )
)


BLOCK_4_NO_PARAMETER_UPDATE_VALID = all(
    [
        BLOCK_4_BACKBONE_PARAMETERS_UNCHANGED,
        BLOCK_4_CONFLUENT_PARAMETERS_UNCHANGED,
        BLOCK_4_FACTUAL_PARAMETERS_UNCHANGED,
        BLOCK_4_PSYCHOLOGICAL_PARAMETERS_UNCHANGED,
    ]
)


if not BLOCK_4_NO_PARAMETER_UPDATE_VALID:
    raise RuntimeError(
        "One or more model parameters changed during the "
        "controlled no-update forward pass."
    )


# =============================================================================
# Execution boundary
# =============================================================================

NOTEBOOK_06_FACTUAL_MODEL_RESTORED = True

NOTEBOOK_06_FACTUAL_PARAMETER_POLICY_DEFINED = True

NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED_FOR_TRAINING = False

NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED = False

NOTEBOOK_06_FACTUAL_LOSS_CALCULATED = False

NOTEBOOK_06_ZERO_GRAD_EXECUTED = False

NOTEBOOK_06_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_06_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Readiness
# =============================================================================

NOTEBOOK_06_FACTUAL_FORWARD_CONTRACT_VALID = all(
    [
        BLOCK_4_ARCHITECTURE_DIMENSIONS_VALID,
        BLOCK_4_FACTUAL_DIMENSION_CONTRACT_VALID,
        BLOCK_4_PARAMETER_TOPOLOGY_VALID,

        BLOCK_4_ALL_EXECUTED_STATES_REPRODUCED,

        BLOCK_4_GROUP_ADAPTER_TOPOLOGY_VALID,
        not BLOCK_4_GROUP_PATH_EXECUTED,
        not BLOCK_4_GROUP_PATH_TRAINED,

        BLOCK_4_REPRESENTATION_SENTENCE_IDS_PRESENT,
        BLOCK_4_REPRESENTATION_SENTENCE_IDS_UNIQUE,
        BLOCK_4_SENTENCE_ALIGNMENT_VALID,

        BLOCK_4_CONTEXTUAL_INPUT_SHAPE_VALID,
        BLOCK_4_CONTEXTUAL_INPUT_FINITE,

        BLOCK_4_FORWARD_PATH_VALID,

        BLOCK_4_ACTIVE_DIMENSIONS_VALID,
        BLOCK_4_DEFERRED_DIMENSIONS_VALID,
        BLOCK_4_BINARY_CONTRACT_VALID,
        BLOCK_4_CONTINUOUS_CONTRACT_VALID,
        BLOCK_4_ACTIVATION_PARTITION_VALID,

        BLOCK_4_ACTIVE_INDEX_MAPPING_VALID,
        BLOCK_4_DEFERRED_INDEX_MAPPING_VALID,
        BLOCK_4_ALL_INDICES_COVER_FACTUAL_SPACE,

        BLOCK_4_ACTIVE_OUTPUT_SHAPE_VALID,
        BLOCK_4_DEFERRED_OUTPUT_SHAPE_VALID,

        BLOCK_4_IMBALANCE_POLICY_VALID,
    ]
)


NOTEBOOK_06_FACTUAL_PARAMETER_POLICY_VALID = all(
    [
        BLOCK_4_PARAMETER_SCOPE_VALID,
        BLOCK_4_NO_PARAMETER_UPDATE_VALID,
    ]
)


NOTEBOOK_06_FACTUAL_MODEL_POLICY_READY = all(
    [
        NOTEBOOK_06_FACTUAL_MODEL_RESTORED,
        NOTEBOOK_06_FACTUAL_PARAMETER_POLICY_DEFINED,
        NOTEBOOK_06_FACTUAL_FORWARD_CONTRACT_VALID,
        NOTEBOOK_06_FACTUAL_PARAMETER_POLICY_VALID,
    ]
)


NOTEBOOK_06_FACTUAL_OPTIMISATION_READY = False


NOTEBOOK_06_READY_FOR_FACTUAL_OBJECTIVE_ASSEMBLY = (
    NOTEBOOK_06_FACTUAL_MODEL_POLICY_READY
)


# =============================================================================
# Block validation
# =============================================================================

NOTEBOOK_06_BLOCK_4_ERRORS = []


block_4_validation_checks = {
    "architecture_dimensions_invalid":
        BLOCK_4_ARCHITECTURE_DIMENSIONS_VALID,

    "factual_dimension_contract_invalid":
        BLOCK_4_FACTUAL_DIMENSION_CONTRACT_VALID,

    "checkpoint_not_reloaded":
        BLOCK_4_CHECKPOINT_RELOADED,

    "metadata_not_reloaded":
        BLOCK_4_METADATA_RELOADED,

    "checkpoint_parameter_topology_invalid":
        BLOCK_4_PARAMETER_TOPOLOGY_VALID,

    "executed_states_not_reproduced":
        BLOCK_4_ALL_EXECUTED_STATES_REPRODUCED,

    "group_adapter_topology_invalid":
        BLOCK_4_GROUP_ADAPTER_TOPOLOGY_VALID,

    "sentence_ids_not_present":
        BLOCK_4_REPRESENTATION_SENTENCE_IDS_PRESENT,

    "sentence_ids_not_unique":
        BLOCK_4_REPRESENTATION_SENTENCE_IDS_UNIQUE,

    "sentence_alignment_invalid":
        BLOCK_4_SENTENCE_ALIGNMENT_VALID,

    "contextual_input_shape_invalid":
        BLOCK_4_CONTEXTUAL_INPUT_SHAPE_VALID,

    "contextual_input_nonfinite":
        BLOCK_4_CONTEXTUAL_INPUT_FINITE,

    "forward_path_invalid":
        BLOCK_4_FORWARD_PATH_VALID,

    "active_dimension_contract_invalid":
        BLOCK_4_ACTIVE_DIMENSIONS_VALID,

    "deferred_dimension_contract_invalid":
        BLOCK_4_DEFERRED_DIMENSIONS_VALID,

    "binary_contract_invalid":
        BLOCK_4_BINARY_CONTRACT_VALID,

    "continuous_contract_invalid":
        BLOCK_4_CONTINUOUS_CONTRACT_VALID,

    "activation_partition_invalid":
        BLOCK_4_ACTIVATION_PARTITION_VALID,

    "active_index_mapping_invalid":
        BLOCK_4_ACTIVE_INDEX_MAPPING_VALID,

    "deferred_index_mapping_invalid":
        BLOCK_4_DEFERRED_INDEX_MAPPING_VALID,

    "factual_index_coverage_invalid":
        BLOCK_4_ALL_INDICES_COVER_FACTUAL_SPACE,

    "active_output_shape_invalid":
        BLOCK_4_ACTIVE_OUTPUT_SHAPE_VALID,

    "deferred_output_shape_invalid":
        BLOCK_4_DEFERRED_OUTPUT_SHAPE_VALID,

    "imbalance_policy_invalid":
        BLOCK_4_IMBALANCE_POLICY_VALID,

    "parameter_scope_invalid":
        BLOCK_4_PARAMETER_SCOPE_VALID,

    "parameters_changed_during_forward":
        BLOCK_4_NO_PARAMETER_UPDATE_VALID,

    "forward_contract_invalid":
        NOTEBOOK_06_FACTUAL_FORWARD_CONTRACT_VALID,

    "parameter_policy_invalid":
        NOTEBOOK_06_FACTUAL_PARAMETER_POLICY_VALID,

    "model_policy_not_ready":
        NOTEBOOK_06_FACTUAL_MODEL_POLICY_READY,

    "objective_assembly_not_ready":
        NOTEBOOK_06_READY_FOR_FACTUAL_OBJECTIVE_ASSEMBLY,
}


for error_name, condition in (
    block_4_validation_checks.items()
):

    if not condition:
        NOTEBOOK_06_BLOCK_4_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited-operation validation
# =============================================================================

prohibited_block_4_operations = {
    "group_path_incorrectly_executed":
        BLOCK_4_GROUP_PATH_EXECUTED,

    "group_path_incorrectly_trained":
        BLOCK_4_GROUP_PATH_TRAINED,

    "factual_optimizer_incorrectly_created":
        NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED,

    "factual_loss_incorrectly_calculated":
        NOTEBOOK_06_FACTUAL_LOSS_CALCULATED,

    "zero_grad_incorrectly_executed":
        NOTEBOOK_06_ZERO_GRAD_EXECUTED,

    "backward_pass_incorrectly_executed":
        NOTEBOOK_06_BACKWARD_PASS_EXECUTED,

    "optimizer_step_incorrectly_executed":
        NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED,

    "parameter_update_incorrectly_executed":
        NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED,

    "factual_training_incorrectly_executed":
        NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED,

    "psychological_training_incorrectly_executed":
        NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "transformative_mechanism_incorrectly_executed":
        NOTEBOOK_06_TRANSFORMATIVE_MECHANISM_EXECUTED,

    "recurrent_mechanism_incorrectly_executed":
        NOTEBOOK_06_RECURRENT_MECHANISM_EXECUTED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for error_name, operation_executed in (
    prohibited_block_4_operations.items()
):

    if operation_executed:
        NOTEBOOK_06_BLOCK_4_ERRORS.append(
            error_name
        )


NOTEBOOK_06_BLOCK_4_VALID = (
    len(
        NOTEBOOK_06_BLOCK_4_ERRORS
    )
    == 0
)


if not NOTEBOOK_06_BLOCK_4_VALID:
    raise RuntimeError(
        "Notebook 06 Block 4 validation failed. "
        f"Errors: {NOTEBOOK_06_BLOCK_4_ERRORS}"
    )


NOTEBOOK_06_BLOCK_4_COMPLETE = True


# =============================================================================
# Block 5 handover objects
# =============================================================================

NOTEBOOK_06_BACKBONE_FROZEN_MODULE = (
    BLOCK_4_BACKBONE
)


NOTEBOOK_06_GLOBAL_CONFLUENT_FROZEN_MODULE = (
    BLOCK_4_GLOBAL_CONFLUENT
)


NOTEBOOK_06_FACTUAL_HEAD = (
    BLOCK_4_FACTUAL_HEAD
)


NOTEBOOK_06_PSYCHOLOGICAL_HEAD_FROZEN_MODULE = (
    BLOCK_4_PSYCHOLOGICAL_HEAD
)


NOTEBOOK_06_FACTUAL_FORWARD_INPUT = (
    BLOCK_4_GLOBAL_CONFLUENT_OUTPUT.detach().clone()
)


NOTEBOOK_06_FACTUAL_FORWARD_OUTPUT = (
    BLOCK_4_FACTUAL_OUTPUT.detach().clone()
)


NOTEBOOK_06_FACTUAL_ACTIVE_INDICES = (
    BLOCK_4_ACTIVE_INDICES
)


NOTEBOOK_06_FACTUAL_DEFERRED_INDICES = (
    BLOCK_4_DEFERRED_INDICES
)


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 06, Block 4: "
    "Factual Model Restoration, Parameter-Freezing Policy "
    "and Controlled Forward-Path Validation"
)

print("=" * 72)

print(
    f"Block version                : "
    f"{NOTEBOOK_06_BLOCK_4_VERSION}"
)


print("-" * 72)
print("Persisted architecture contract")

print(
    f"Textual representation dim.  : "
    f"{BLOCK_4_TEXTUAL_DIM}"
)

print(
    f"Backbone interface dim.      : "
    f"{BLOCK_4_BACKBONE_DIM}"
)

print(
    f"Global confluent dim.        : "
    f"{BLOCK_4_CONFLUENT_DIM}"
)

print(
    f"Factual representation dim.  : "
    f"{BLOCK_4_FACTUAL_DIM}"
)

print(
    f"Psychological repr. dim.     : "
    f"{BLOCK_4_PSYCHOLOGICAL_DIM}"
)

print(
    f"Parameter topology valid     : "
    f"{BLOCK_4_PARAMETER_TOPOLOGY_VALID}"
)


print("-" * 72)
print("Persisted model restoration")

print(
    f"Checkpoint reloaded          : "
    f"{BLOCK_4_CHECKPOINT_RELOADED}"
)

print(
    f"Metadata reloaded            : "
    f"{BLOCK_4_METADATA_RELOADED}"
)

print(
    f"Backbone state reproduced    : "
    f"{BLOCK_4_BACKBONE_STATE_REPRODUCED}"
)

print(
    f"Global confluent reproduced  : "
    f"{BLOCK_4_GLOBAL_CONFLUENT_STATE_REPRODUCED}"
)

print(
    f"Factual state reproduced     : "
    f"{BLOCK_4_FACTUAL_STATE_REPRODUCED}"
)

print(
    f"Psych. state reproduced      : "
    f"{BLOCK_4_PSYCHOLOGICAL_STATE_REPRODUCED}"
)


print("-" * 72)
print("Global / group path boundary")

print(
    f"Global path required         : "
    f"{True}"
)

print(
    f"Global path executed         : "
    f"{True}"
)

print(
    f"Group adapter first layer    : "
    f"{BLOCK_4_GROUP_ADAPTER_FIRST_WEIGHT_SHAPE}"
)

print(
    f"Group adapter second layer   : "
    f"{BLOCK_4_GROUP_ADAPTER_SECOND_WEIGHT_SHAPE}"
)

print(
    f"Group topology valid         : "
    f"{BLOCK_4_GROUP_ADAPTER_TOPOLOGY_VALID}"
)

print(
    f"Group path available         : "
    f"{BLOCK_4_GROUP_PATH_AVAILABLE}"
)

print(
    f"Group path required          : "
    f"{BLOCK_4_GROUP_PATH_REQUIRED}"
)

print(
    f"Group path executed          : "
    f"{BLOCK_4_GROUP_PATH_EXECUTED}"
)

print(
    f"Group path trained           : "
    f"{BLOCK_4_GROUP_PATH_TRAINED}"
)

print(
    f"Group path deferred to N     : "
    f"{BLOCK_4_GROUP_PATH_DEFERRED_TO_NOTEBOOK}"
)


print("-" * 72)
print("Parameter-freezing policy")

print(
    f"Backbone frozen              : "
    f"{BLOCK_4_BACKBONE_FROZEN}"
)

print(
    f"Global confluent frozen      : "
    f"{BLOCK_4_GLOBAL_CONFLUENT_FROZEN}"
)

print(
    f"Psychological head frozen    : "
    f"{BLOCK_4_PSYCHOLOGICAL_HEAD_FROZEN}"
)

print(
    f"Factual head trainable       : "
    f"{BLOCK_4_FACTUAL_HEAD_TRAINABLE}"
)

print(
    f"Factual trainable parameters : "
    f"{BLOCK_4_FACTUAL_TRAINABLE_PARAMETERS}"
)

print(
    f"Expected factual parameters  : "
    f"{BLOCK_4_EXPECTED_FACTUAL_PARAMETER_COUNT}"
)

print(
    f"Parameter count valid        : "
    f"{BLOCK_4_FACTUAL_PARAMETER_COUNT_VALID}"
)

print(
    f"Parameter scope valid        : "
    f"{BLOCK_4_PARAMETER_SCOPE_VALID}"
)


print("-" * 72)
print("Contextual representation")

print(
    f"Sentence records             : "
    f"{len(BLOCK_4_REPRESENTATION_RECORDS)}"
)

print(
    f"Sentence IDs present         : "
    f"{BLOCK_4_REPRESENTATION_SENTENCE_IDS_PRESENT}"
)

print(
    f"Sentence IDs unique          : "
    f"{BLOCK_4_REPRESENTATION_SENTENCE_IDS_UNIQUE}"
)

print(
    f"Sentence alignment valid     : "
    f"{BLOCK_4_SENTENCE_ALIGNMENT_VALID}"
)

print(
    f"Input shape                  : "
    f"{BLOCK_4_CONTEXTUAL_INPUT_SHAPE}"
)

print(
    f"Input shape valid            : "
    f"{BLOCK_4_CONTEXTUAL_INPUT_SHAPE_VALID}"
)

print(
    f"Input values finite          : "
    f"{BLOCK_4_CONTEXTUAL_INPUT_FINITE}"
)


print("-" * 72)
print("Controlled mandatory-global forward path")

print(
    f"Backbone output shape        : "
    f"{BLOCK_4_BACKBONE_OUTPUT_SHAPE}"
)

print(
    f"Backbone shape valid         : "
    f"{BLOCK_4_BACKBONE_OUTPUT_SHAPE_VALID}"
)

print(
    f"Global confluent shape       : "
    f"{BLOCK_4_GLOBAL_CONFLUENT_OUTPUT_SHAPE}"
)

print(
    f"Global confluent valid       : "
    f"{BLOCK_4_GLOBAL_CONFLUENT_OUTPUT_SHAPE_VALID}"
)

print(
    f"Factual output shape         : "
    f"{BLOCK_4_FACTUAL_OUTPUT_SHAPE}"
)

print(
    f"Factual output valid         : "
    f"{BLOCK_4_FACTUAL_OUTPUT_SHAPE_VALID}"
)

print(
    f"Backbone values finite       : "
    f"{BLOCK_4_BACKBONE_OUTPUT_FINITE}"
)

print(
    f"Global confluent finite      : "
    f"{BLOCK_4_GLOBAL_CONFLUENT_OUTPUT_FINITE}"
)

print(
    f"Factual output finite        : "
    f"{BLOCK_4_FACTUAL_OUTPUT_FINITE}"
)


print("-" * 72)
print("Factual activation mapping")

print(
    f"Active dimensions            : "
    f"{list(BLOCK_4_ACTIVE_DIMENSIONS)}"
)

print(
    f"Active dimension count       : "
    f"{len(BLOCK_4_ACTIVE_DIMENSIONS)}"
)

print(
    f"Active indices               : "
    f"{list(BLOCK_4_ACTIVE_INDICES)}"
)

print(
    f"Deferred dimensions          : "
    f"{list(BLOCK_4_DEFERRED_DIMENSIONS)}"
)

print(
    f"Deferred dimension count     : "
    f"{len(BLOCK_4_DEFERRED_DIMENSIONS)}"
)

print(
    f"Deferred indices             : "
    f"{list(BLOCK_4_DEFERRED_INDICES)}"
)

print(
    f"Active binary dimensions     : "
    f"{list(BLOCK_4_ACTIVE_BINARY_DIMENSIONS)}"
)

print(
    f"Active continuous dimensions : "
    f"{list(BLOCK_4_ACTIVE_CONTINUOUS_DIMENSIONS)}"
)

print(
    f"Activation partition valid   : "
    f"{BLOCK_4_ACTIVATION_PARTITION_VALID}"
)

print(
    f"Factual index coverage valid : "
    f"{BLOCK_4_ALL_INDICES_COVER_FACTUAL_SPACE}"
)

print(
    f"Active output shape          : "
    f"{BLOCK_4_ACTIVE_OUTPUT_SHAPE}"
)

print(
    f"Deferred output shape        : "
    f"{BLOCK_4_DEFERRED_OUTPUT_SHAPE}"
)

print(
    f"Positive class weights       : "
    f"{BLOCK_4_POSITIVE_CLASS_WEIGHTS}"
)

print(
    f"Imbalance policy valid       : "
    f"{BLOCK_4_IMBALANCE_POLICY_VALID}"
)


print("-" * 72)
print("No-update validation")

print(
    f"Backbone unchanged           : "
    f"{BLOCK_4_BACKBONE_PARAMETERS_UNCHANGED}"
)

print(
    f"Global confluent unchanged   : "
    f"{BLOCK_4_CONFLUENT_PARAMETERS_UNCHANGED}"
)

print(
    f"Factual head unchanged       : "
    f"{BLOCK_4_FACTUAL_PARAMETERS_UNCHANGED}"
)

print(
    f"Psychological head unchanged : "
    f"{BLOCK_4_PSYCHOLOGICAL_PARAMETERS_UNCHANGED}"
)

print(
    f"No-update validation valid   : "
    f"{BLOCK_4_NO_PARAMETER_UPDATE_VALID}"
)


print("-" * 72)
print("Readiness")

print(
    f"Factual model restored       : "
    f"{NOTEBOOK_06_FACTUAL_MODEL_RESTORED}"
)

print(
    f"Forward contract valid       : "
    f"{NOTEBOOK_06_FACTUAL_FORWARD_CONTRACT_VALID}"
)

print(
    f"Parameter policy valid       : "
    f"{NOTEBOOK_06_FACTUAL_PARAMETER_POLICY_VALID}"
)

print(
    f"Model policy ready           : "
    f"{NOTEBOOK_06_FACTUAL_MODEL_POLICY_READY}"
)

print(
    f"Factual optimisation ready   : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMISATION_READY}"
)

print(
    f"Ready for objective assembly : "
    f"{NOTEBOOK_06_READY_FOR_FACTUAL_OBJECTIVE_ASSEMBLY}"
)


print("-" * 72)
print("Execution boundary")

print(
    f"Controlled forward executed  : "
    f"{NOTEBOOK_06_FACTUAL_CONTROLLED_FORWARD_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{BLOCK_4_GROUP_PATH_EXECUTED}"
)

print(
    f"Transformative executed      : "
    f"{NOTEBOOK_06_TRANSFORMATIVE_MECHANISM_EXECUTED}"
)

print(
    f"Recurrent executed           : "
    f"{NOTEBOOK_06_RECURRENT_MECHANISM_EXECUTED}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_06_FACTUAL_LOSS_CALCULATED}"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_06_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_06_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Factual training executed    : "
    f"{NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Held-out evaluation          : "
    f"{NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_06_BLOCK_4_VALID}"
)

print(
    f"Block 4 complete             : "
    f"{NOTEBOOK_06_BLOCK_4_COMPLETE}"
)


print("=" * 72)

print(
    "Factual model restoration, parameter-freezing policy and "
    "controlled forward-path validation completed successfully."
)

print(
    "The persisted Notebook 05 architecture was restored without "
    "merging the mandatory global confluent projection with the "
    "optional group-conditioned adapter."
)

print(
    "The controlled factual forward path preserves the validated "
    "768-dimensional contextual representation, 768-dimensional "
    "backbone interface and 256-dimensional global confluent "
    "representation."
)

print(
    "The optional group-conditioned confluent path remains "
    "architecturally available as a separate 320 -> 256 -> 256 "
    "parameter topology and was not executed or trained."
)

print(
    "Group-conditioned processing remains deferred to Notebook 10."
)

print(
    "The factual representation head preserves all ten factual "
    "output dimensions."
)

print(
    f"{len(BLOCK_4_ACTIVE_DIMENSIONS)} factual dimensions currently "
    "have validated active supervision and remain available for "
    "subsequent controlled objective assembly."
)

print(
    f"{len(BLOCK_4_DEFERRED_DIMENSIONS)} factual dimension(s) remain "
    "deferred under the current validated Block 3 supervision policy."
)

print(
    "Active and deferred factual dimensions are inherited from the "
    "validated Block 3 contract rather than from pilot-era hard-coded "
    "dimension assumptions."
)

print(
    "Positive-class weighting is inherited dynamically from Block 3 "
    "and is restricted to active binary factual dimensions."
)

print(
    "The completed psychological head, backbone and mandatory global "
    "confluent projection remain frozen."
)

print(
    "Only the factual representation head is marked trainable for "
    "subsequent Notebook 06 optimisation."
)

print(
    "No group-conditioned processing, transformative mechanism or "
    "recurrent mechanism was executed."
)

print(
    "No optimiser, supervised factual loss, zero-gradient operation, "
    "backward pass, optimiser step, parameter update or factual "
    "training was performed."
)

print(
    "Successful Block 4 completion establishes architectural and "
    "parameter-policy readiness, not factual generalisation or "
    "empirical validity."
)

print(
    "The next block may proceed to Factual Objective Assembly, "
    "Optimiser Policy and Controlled Loss Validation."
)

print("=" * 72)

========================================================================
Media AI — Notebook 06, Block 4: Factual Model Restoration, Parameter-Freezing Policy and Controlled Forward-Path Validation
========================================================================
Block version                : 1.4
------------------------------------------------------------------------
Persisted architecture contract
Textual representation dim.  : 768
Backbone interface dim.      : 768
Global confluent dim.        : 256
Factual representation dim.  : 10
Psychological repr. dim.     : 34
Parameter topology valid     : True
------------------------------------------------------------------------
Persisted model restoration
Checkpoint reloaded          : True
Metadata reloaded            : True
Backbone state reproduced    : True
Global confluent reproduced  : True
Factual state reproduced     : True
Psych. state reproduced      : True
------------------------------------------------------------------------
Global / group path boundary
Global path required         : True
Global path executed         : True
Group adapter first layer    : (256, 320)
Group adapter second layer   : (256, 256)
Group topology valid         : True
Group path available         : True
Group path required          : False
Group path executed          : False
Group path trained           : False
Group path deferred to N     : 10
------------------------------------------------------------------------
Parameter-freezing policy
Backbone frozen              : True
Global confluent frozen      : True
Psychological head frozen    : True
Factual head trainable       : True
Factual trainable parameters : 34442
Expected factual parameters  : 34442
Parameter count valid        : True
Parameter scope valid        : True
------------------------------------------------------------------------
Contextual representation
Sentence records             : 54
Sentence IDs present         : True
Sentence IDs unique          : True
Sentence alignment valid     : True
Input shape                  : (54, 768)
Input shape valid            : True
Input values finite          : True
------------------------------------------------------------------------
Controlled mandatory-global forward path
Backbone output shape        : (54, 768)
Backbone shape valid         : True
Global confluent shape       : (54, 256)
Global confluent valid       : True
Factual output shape         : (54, 10)
Factual output valid         : True
Backbone values finite       : True
Global confluent finite      : True
Factual output finite        : True
------------------------------------------------------------------------
Factual activation mapping
Active dimensions            : ['explicit_claim', 'observation_or_event', 'quantitative_information', 'attribution', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction', 'factological_weight']
Active dimension count       : 9
Active indices               : [0, 1, 2, 3, 4, 5, 6, 8, 9]
Deferred dimensions          : ['speculation']
Deferred dimension count     : 1
Deferred indices             : [7]
Active binary dimensions     : ['explicit_claim', 'observation_or_event', 'quantitative_information', 'attribution', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction']
Active continuous dimensions : ['factological_weight']
Activation partition valid   : True
Factual index coverage valid : True
Active output shape          : (54, 9)
Deferred output shape        : (54, 1)
Positive class weights       : {'explicit_claim': 0.2558139534883721, 'evidence_reference': 3.1538461538461537, 'certainty_statement': 0.17391304347826086, 'uncertainty_statement': 8.0, 'prediction': 25.0}
Imbalance policy valid       : True
------------------------------------------------------------------------
No-update validation
Backbone unchanged           : True
Global confluent unchanged   : True
Factual head unchanged       : True
Psychological head unchanged : True
No-update validation valid   : True
------------------------------------------------------------------------
Readiness
Factual model restored       : True
Forward contract valid       : True
Parameter policy valid       : True
Model policy ready           : True
Factual optimisation ready   : False
Ready for objective assembly : True
------------------------------------------------------------------------
Execution boundary
Controlled forward executed  : True
Group-conditioned executed   : False
Transformative executed      : False
Recurrent executed           : False
Optimiser created            : False
Loss calculated              : False
Zero grad executed           : False
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
Factual training executed    : False
Psychological retraining     : False
Held-out evaluation          : False
Empirical validity           : False
Block valid                  : True
Block 4 complete             : True
========================================================================
Factual model restoration, parameter-freezing policy and controlled forward-path validation completed successfully.
The persisted Notebook 05 architecture was restored without merging the mandatory global confluent projection with the optional group-conditioned adapter.
The controlled factual forward path preserves the validated 768-dimensional contextual representation, 768-dimensional backbone interface and 256-dimensional global confluent representation.
The optional group-conditioned confluent path remains architecturally available as a separate 320 -> 256 -> 256 parameter topology and was not executed or trained.
Group-conditioned processing remains deferred to Notebook 10.
The factual representation head preserves all ten factual output dimensions.
9 factual dimensions currently have validated active supervision and remain available for subsequent controlled objective assembly.
1 factual dimension(s) remain deferred under the current validated Block 3 supervision policy.
Active and deferred factual dimensions are inherited from the validated Block 3 contract rather than from pilot-era hard-coded dimension assumptions.
Positive-class weighting is inherited dynamically from Block 3 and is restricted to active binary factual dimensions.
The completed psychological head, backbone and mandatory global confluent projection remain frozen.
Only the factual representation head is marked trainable for subsequent Notebook 06 optimisation.
No group-conditioned processing, transformative mechanism or recurrent mechanism was executed.
No optimiser, supervised factual loss, zero-gradient operation, backward pass, optimiser step, parameter update or factual training was performed.
Successful Block 4 completion establishes architectural and parameter-policy readiness, not factual generalisation or empirical validity.
The next block may proceed to Factual Objective Assembly, Optimiser Policy and Controlled Loss Validation.
========================================================================

## Block 5 — Factual Objective Assembly, Optimiser Policy and Controlled Loss Validation

This block converts the factual target, activation and model contracts established in Blocks 2–4 into an executable supervised objective while preserving the controlled-training boundary of Notebook 06.

The canonical prediction unit remains the sentence. The ten-dimensional factual representation is preserved in full, but only factual dimensions with usable supervision and non-zero target variability in the current dataset are activated for optimisation.

The active factual objectives are:

- **F2 — observation_or_event**
- **F3 — quantitative_information**
- **F5 — evidence_reference**
- **F9 — prediction**
- **F10 — factological_weight**

The remaining factual dimensions are retained structurally but remain outside the current optimisation objective:

- **F1 — explicit_claim**
- **F4 — attribution**
- **F6 — certainty_statement**
- **F7 — uncertainty_statement**
- **F8 — speculation**

Their exclusion is dataset-dependent rather than architectural. They remain valid factual dimensions and may become trainable when later data provide sufficient target variability.

### Objective construction

The four active binary factual dimensions — F2, F3, F5 and F9 — use independent binary-cross-entropy-with-logits objectives. They are not collapsed into a multiclass target because the factual dimensions represent separate and potentially co-occurring properties of a sentence.

F10, `factological_weight`, remains a separate continuous factual objective and uses masked mean-squared error.

Each factual objective is calculated independently before combination into the controlled total factual objective. This preserves visibility into dimension-specific loss behaviour and prevents the ten-dimensional factual representation from being treated as a single undifferentiated target.

### Class-imbalance policy

The class-distribution audit from Block 3 is preserved.

F2, F3 and F5 do not receive additional positive-class weighting under the current policy. F9 (`prediction`) is substantially imbalanced in the current supervision and therefore uses the previously established positive-class weight of **7.0**.

The weighting applies only to the F9 binary objective. It does not modify the factual representation itself, the other binary objectives or the continuous F10 objective.

No additional class weights are inferred in this block.

### Mask-aware supervision

All objectives remain mask-aware.

Only observed and eligible target elements may contribute to their corresponding losses. Missing or unavailable supervision is not interpreted as numerical zero, negative evidence or absence of the factual property.

The loss implementation must therefore preserve the distinction between:

- an observed target value of zero,
- an observed positive target value,
- and an unavailable target element.

A factual objective with no available eligible observations must not contribute an artificial zero-valued training signal.

### Objective combination

The five active factual objectives remain separate supervised objectives and are combined only after their individual masked losses have been calculated.

The initial controlled policy uses equal objective-family weights unless an explicitly persisted methodological contract requires otherwise. Class weighting inside the F9 binary objective remains distinct from objective-family weighting.

The combined factual objective therefore represents supervised optimisation of the currently eligible factual dimensions rather than an assertion that the five targets have identical semantics or empirical importance.

No deferred factual dimension enters the combined objective.

### Optimiser boundary

The optimiser is restricted exclusively to parameters of the factual representation head validated as trainable in Block 4.

The following components remain outside the optimiser:

- contextual sentence representation encoder,
- backbone,
- mandatory global confluent path,
- completed psychological representation head,
- optional group-conditioned path,
- social representation path,
- transformative mechanisms,
- Transformative Weights,
- recurrent mechanisms.

The optimiser policy must be validated explicitly before any later training step is permitted.

Creating the optimiser in this block does not constitute factual training.

### Controlled loss validation

A controlled forward pass may be executed through the already validated mandatory global path and factual head in order to calculate the initial factual objectives.

The block validates that:

- all five active factual objectives can be calculated;
- all calculated losses are finite;
- binary and continuous targets use their assigned loss families;
- the F9 positive-class weight is applied only to prediction;
- masking excludes unavailable supervision;
- deferred factual dimensions do not enter the objective;
- the combined factual objective is finite;
- the optimiser contains only factual-head parameters;
- no frozen parameter is exposed to optimisation.

This block establishes executable objective readiness only.

### No-training boundary

Block 5 does **not** perform controlled factual training.

No backward pass, optimiser step or parameter update is permitted. `zero_grad()` is also unnecessary because no gradient-producing training step is performed.

All model parameters must remain identical before and after the controlled loss validation.

The psychological path remains frozen and unchanged. The group-conditioned path remains unexecuted and deferred to Notebook 10. Transformative and recurrent mechanisms remain outside the current execution scope.

### Methodological boundary

Successful completion of this block demonstrates that the factual supervision, loss functions, masking rules, class-imbalance treatment and optimiser scope form a coherent executable training contract.

It does **not** demonstrate factual prediction quality, generalisation, calibration or empirical validity.

The current dataset contains only one article and sixteen sentences. Initial loss values therefore serve as computational diagnostics rather than evidence of model performance.

No held-out evaluation, validation-based early stopping, ablation or empirical-validity claim is performed in this block.

### Block completion criteria

Block 5 is complete only if:

- the five active factual objectives are assembled successfully;
- F2, F3, F5 and F9 use independent masked binary-cross-entropy-with-logits objectives;
- F10 uses a masked mean-squared-error objective;
- the F9 positive-class weight remains 7.0 and is not applied to other targets;
- deferred factual dimensions remain outside optimisation;
- the combined factual objective is finite;
- the optimiser is scoped exclusively to the factual head;
- the backbone, global confluent path and psychological head remain frozen;
- the optional group-conditioned path remains unexecuted;
- no transformative or recurrent mechanism is executed;
- no backward pass is performed;
- no optimiser step is performed;
- no parameter changes occur;
- and all Block 5 validation checks pass.

Successful completion establishes readiness for the subsequent controlled factual-training block, not factual generalisation or empirical validity.

In [7]:
# =============================================================================
# Media AI — Notebook 06
# Block 5: Factual Objective Assembly, Optimiser Policy
#          and Controlled Loss Validation
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import math

import numpy as np
import torch
import torch.nn.functional as F


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_06_BLOCK_5 = 5

NOTEBOOK_06_BLOCK_5_NAME = (
    "Factual Objective Assembly, Optimiser Policy "
    "and Controlled Loss Validation"
)

NOTEBOOK_06_BLOCK_5_VERSION = "1.3"

NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VERSION = "1.3"

BLOCK_5_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Dependency checks
# =============================================================================

required_block_5_objects = [
    # -------------------------------------------------------------------------
    # Block 2 — canonical factual supervision
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_2_COMPLETE",
    "NOTEBOOK_06_BLOCK_2_VALID",
    "NOTEBOOK_06_SENTENCE_IDS",
    "NOTEBOOK_06_SENTENCE_COUNT",
    "NOTEBOOK_06_FACTUAL_TARGET_RECORDS",
    "NOTEBOOK_06_FACTUAL_DIMENSION_ORDER",
    "NOTEBOOK_06_FACTUAL_DIMENSION_INDEX",
    "NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID",
    "BLOCK_2_FACTUAL_TARGET_MATRIX",
    "BLOCK_2_FACTUAL_MASK_MATRIX",
    "BLOCK_2_DIMENSION_AVAILABLE_COUNTS",
    "BLOCK_2_DIMENSION_COVERAGE",

    "NOTEBOOK_06_MASK_AWARE_SUPERVISION",
    "NOTEBOOK_06_MISSING_EQUALS_ZERO",
    "NOTEBOOK_06_MISSING_EQUALS_NEGATIVE",
    "NOTEBOOK_06_UNAVAILABLE_ENTERS_LOSS",

    # -------------------------------------------------------------------------
    # Block 3 — activation and loss policy
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_3_COMPLETE",
    "NOTEBOOK_06_BLOCK_3_VALID",

    "NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS",
    "NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID",

    # -------------------------------------------------------------------------
    # Block 4 — restored architecture and controlled forward state
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_4_COMPLETE",
    "NOTEBOOK_06_BLOCK_4_VALID",

    "NOTEBOOK_06_FACTUAL_MODEL_POLICY_READY",
    "NOTEBOOK_06_READY_FOR_FACTUAL_OBJECTIVE_ASSEMBLY",

    "NOTEBOOK_06_BACKBONE_FROZEN_MODULE",
    "NOTEBOOK_06_GLOBAL_CONFLUENT_FROZEN_MODULE",
    "NOTEBOOK_06_FACTUAL_HEAD",
    "NOTEBOOK_06_PSYCHOLOGICAL_HEAD_FROZEN_MODULE",

    "NOTEBOOK_06_FACTUAL_FORWARD_INPUT",
    "NOTEBOOK_06_FACTUAL_FORWARD_OUTPUT",

    "NOTEBOOK_06_FACTUAL_ACTIVE_INDICES",
    "NOTEBOOK_06_FACTUAL_DEFERRED_INDICES",
]


missing_block_5_objects = [
    object_name
    for object_name in required_block_5_objects
    if object_name not in globals()
]


if missing_block_5_objects:

    raise NameError(
        "Notebook 06 Block 5 prerequisites are not initialised. "
        f"Missing: {missing_block_5_objects}"
    )


if not all(
    [
        NOTEBOOK_06_BLOCK_2_COMPLETE,
        NOTEBOOK_06_BLOCK_2_VALID,
        NOTEBOOK_06_BLOCK_3_COMPLETE,
        NOTEBOOK_06_BLOCK_3_VALID,
        NOTEBOOK_06_BLOCK_4_COMPLETE,
        NOTEBOOK_06_BLOCK_4_VALID,
        NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID,
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID,
        NOTEBOOK_06_FACTUAL_MODEL_POLICY_READY,
        NOTEBOOK_06_READY_FOR_FACTUAL_OBJECTIVE_ASSEMBLY,
    ]
):

    raise ValueError(
        "Notebook 06 Blocks 2–4 must be complete and valid "
        "before Block 5."
    )


# =============================================================================
# Execution boundary initialisation
# =============================================================================

NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED = False

NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED = False

NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED = False

NOTEBOOK_06_FACTUAL_LOSS_CALCULATED = False

NOTEBOOK_06_ZERO_GRAD_EXECUTED = False

NOTEBOOK_06_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ACTIVATED = False

NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ACTIVATED = False

NOTEBOOK_06_RECURRENT_STATES_ACTIVATED = False

NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Canonical factual dimension contract
# =============================================================================

BLOCK_5_EXPECTED_DIMENSION_ORDER = (
    "explicit_claim",
    "observation_or_event",
    "quantitative_information",
    "attribution",
    "evidence_reference",
    "certainty_statement",
    "uncertainty_statement",
    "speculation",
    "prediction",
    "factological_weight",
)


BLOCK_5_DIMENSION_ORDER_VALID = (
    tuple(
        NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
    )
    ==
    BLOCK_5_EXPECTED_DIMENSION_ORDER
)


if not BLOCK_5_DIMENSION_ORDER_VALID:

    raise RuntimeError(
        "Block 5 factual dimension order does not reproduce "
        "the validated Block 2 contract."
    )


BLOCK_5_DIMENSION_INDEX = dict(
    NOTEBOOK_06_FACTUAL_DIMENSION_INDEX
)


BLOCK_5_DIMENSION_INDEX_VALID = all(
    BLOCK_5_DIMENSION_INDEX[
        dimension_name
    ]
    ==
    expected_index

    for expected_index, dimension_name
    in enumerate(
        BLOCK_5_EXPECTED_DIMENSION_ORDER
    )
)


if not BLOCK_5_DIMENSION_INDEX_VALID:

    raise RuntimeError(
        "Block 5 factual dimension indices do not reproduce "
        "the validated Block 2 contract."
    )


# =============================================================================
# Active / deferred factual objective contract
# =============================================================================
#
# Block 3 determines which factual dimensions are currently active from the
# validated supervision state. Block 5 inherits that policy dynamically rather
# than reproducing the earlier pilot-state five-active / five-deferred split.
#
# The inherited policy must:
#
# - use only canonical F1–F10 dimensions;
# - keep active and deferred dimensions unique and disjoint;
# - cover all ten factual dimensions exactly once;
# - classify every active dimension as either binary or continuous;
# - keep the binary and continuous active sets disjoint.
# =============================================================================

BLOCK_5_ACTIVE_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS
)


BLOCK_5_DEFERRED_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS
)


BLOCK_5_ACTIVE_BINARY_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS
)


BLOCK_5_ACTIVE_CONTINUOUS_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS
)


BLOCK_5_CANONICAL_DIMENSION_SET = set(
    BLOCK_5_EXPECTED_DIMENSION_ORDER
)


BLOCK_5_ACTIVE_DIMENSION_SET = set(
    BLOCK_5_ACTIVE_DIMENSIONS
)


BLOCK_5_DEFERRED_DIMENSION_SET = set(
    BLOCK_5_DEFERRED_DIMENSIONS
)


BLOCK_5_ACTIVE_BINARY_SET = set(
    BLOCK_5_ACTIVE_BINARY_DIMENSIONS
)


BLOCK_5_ACTIVE_CONTINUOUS_SET = set(
    BLOCK_5_ACTIVE_CONTINUOUS_DIMENSIONS
)


BLOCK_5_ACTIVE_CONTRACT_VALID = all(
    [
        bool(
            BLOCK_5_ACTIVE_DIMENSIONS
        ),
        len(
            BLOCK_5_ACTIVE_DIMENSIONS
        )
        ==
        len(
            BLOCK_5_ACTIVE_DIMENSION_SET
        ),
        BLOCK_5_ACTIVE_DIMENSION_SET.issubset(
            BLOCK_5_CANONICAL_DIMENSION_SET
        ),
    ]
)


BLOCK_5_DEFERRED_CONTRACT_VALID = all(
    [
        len(
            BLOCK_5_DEFERRED_DIMENSIONS
        )
        ==
        len(
            BLOCK_5_DEFERRED_DIMENSION_SET
        ),
        BLOCK_5_DEFERRED_DIMENSION_SET.issubset(
            BLOCK_5_CANONICAL_DIMENSION_SET
        ),
    ]
)


BLOCK_5_ACTIVE_DEFERRED_DISJOINT = (
    BLOCK_5_ACTIVE_DIMENSION_SET.isdisjoint(
        BLOCK_5_DEFERRED_DIMENSION_SET
    )
)


BLOCK_5_ACTIVE_DEFERRED_COMPLETE = (
    (
        BLOCK_5_ACTIVE_DIMENSION_SET
        |
        BLOCK_5_DEFERRED_DIMENSION_SET
    )
    ==
    BLOCK_5_CANONICAL_DIMENSION_SET
)


BLOCK_5_BINARY_CONTRACT_VALID = all(
    [
        len(
            BLOCK_5_ACTIVE_BINARY_DIMENSIONS
        )
        ==
        len(
            BLOCK_5_ACTIVE_BINARY_SET
        ),
        BLOCK_5_ACTIVE_BINARY_SET.issubset(
            BLOCK_5_ACTIVE_DIMENSION_SET
        ),
    ]
)


BLOCK_5_CONTINUOUS_CONTRACT_VALID = all(
    [
        len(
            BLOCK_5_ACTIVE_CONTINUOUS_DIMENSIONS
        )
        ==
        len(
            BLOCK_5_ACTIVE_CONTINUOUS_SET
        ),
        BLOCK_5_ACTIVE_CONTINUOUS_SET.issubset(
            BLOCK_5_ACTIVE_DIMENSION_SET
        ),
    ]
)


BLOCK_5_BINARY_CONTINUOUS_DISJOINT = (
    BLOCK_5_ACTIVE_BINARY_SET.isdisjoint(
        BLOCK_5_ACTIVE_CONTINUOUS_SET
    )
)


BLOCK_5_ACTIVE_TYPE_COVERAGE_VALID = (
    (
        BLOCK_5_ACTIVE_BINARY_SET
        |
        BLOCK_5_ACTIVE_CONTINUOUS_SET
    )
    ==
    BLOCK_5_ACTIVE_DIMENSION_SET
)


BLOCK_5_ACTIVATION_CONTRACT_VALID = all(
    [
        BLOCK_5_ACTIVE_CONTRACT_VALID,
        BLOCK_5_DEFERRED_CONTRACT_VALID,
        BLOCK_5_ACTIVE_DEFERRED_DISJOINT,
        BLOCK_5_ACTIVE_DEFERRED_COMPLETE,
        BLOCK_5_BINARY_CONTRACT_VALID,
        BLOCK_5_CONTINUOUS_CONTRACT_VALID,
        BLOCK_5_BINARY_CONTINUOUS_DISJOINT,
        BLOCK_5_ACTIVE_TYPE_COVERAGE_VALID,
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID,
    ]
)


if not BLOCK_5_ACTIVATION_CONTRACT_VALID:

    raise RuntimeError(
        "Block 5 factual objective contract does not reproduce "
        "the validated dynamic Block 3 activation policy."
    )

# =============================================================================
# Active / deferred index validation
# =============================================================================

BLOCK_5_ACTIVE_INDICES = tuple(
    BLOCK_5_DIMENSION_INDEX[
        dimension_name
    ]

    for dimension_name
    in BLOCK_5_ACTIVE_DIMENSIONS
)


BLOCK_5_DEFERRED_INDICES = tuple(
    BLOCK_5_DIMENSION_INDEX[
        dimension_name
    ]

    for dimension_name
    in BLOCK_5_DEFERRED_DIMENSIONS
)


BLOCK_5_ACTIVE_INDICES_VALID = (
    BLOCK_5_ACTIVE_INDICES
    ==
    tuple(
        NOTEBOOK_06_FACTUAL_ACTIVE_INDICES
    )
)


BLOCK_5_DEFERRED_INDICES_VALID = (
    BLOCK_5_DEFERRED_INDICES
    ==
    tuple(
        NOTEBOOK_06_FACTUAL_DEFERRED_INDICES
    )
)


BLOCK_5_INDEX_SETS_DISJOINT = (
    set(
        BLOCK_5_ACTIVE_INDICES
    ).isdisjoint(
        set(
            BLOCK_5_DEFERRED_INDICES
        )
    )
)


BLOCK_5_INDEX_COVERAGE_VALID = (
    (
        set(
            BLOCK_5_ACTIVE_INDICES
        )
        |
        set(
            BLOCK_5_DEFERRED_INDICES
        )
    )
    ==
    set(
        range(
            len(
                BLOCK_5_EXPECTED_DIMENSION_ORDER
            )
        )
    )
)


if not all(
    [
        BLOCK_5_ACTIVE_INDICES_VALID,
        BLOCK_5_DEFERRED_INDICES_VALID,
        BLOCK_5_INDEX_SETS_DISJOINT,
        BLOCK_5_INDEX_COVERAGE_VALID,
    ]
):

    raise RuntimeError(
        "Block 5 factual dimension indices are inconsistent "
        "with the validated Blocks 2–4 contract."
    )

# =============================================================================
# Canonical factual target-record identity
# =============================================================================

BLOCK_5_TARGET_RECORD_COUNT = len(
    NOTEBOOK_06_FACTUAL_TARGET_RECORDS
)


if (
    BLOCK_5_TARGET_RECORD_COUNT
    != NOTEBOOK_06_SENTENCE_COUNT
):

    raise RuntimeError(
        "Block 5 factual target record count does not match "
        "the canonical sentence count."
    )


BLOCK_5_TARGET_SENTENCE_IDS = [
    record[
        "identity"
    ][
        "sentence_id"
    ]

    for record
    in NOTEBOOK_06_FACTUAL_TARGET_RECORDS
]


BLOCK_5_TARGET_SENTENCE_IDS_PRESENT = all(
    BLOCK_5_TARGET_SENTENCE_IDS
)


BLOCK_5_TARGET_SENTENCE_IDS_UNIQUE = (
    len(
        BLOCK_5_TARGET_SENTENCE_IDS
    )
    ==
    len(
        set(
            BLOCK_5_TARGET_SENTENCE_IDS
        )
    )
)


BLOCK_5_TARGET_SENTENCE_SET_VALID = (
    set(
        BLOCK_5_TARGET_SENTENCE_IDS
    )
    ==
    set(
        NOTEBOOK_06_SENTENCE_IDS
    )
)


if not all(
    [
        BLOCK_5_TARGET_SENTENCE_IDS_PRESENT,
        BLOCK_5_TARGET_SENTENCE_IDS_UNIQUE,
        BLOCK_5_TARGET_SENTENCE_SET_VALID,
    ]
):

    raise RuntimeError(
        "Block 5 factual target sentence identity is invalid."
    )


# =============================================================================
# Reorder validated Block 2 matrices to canonical sentence order
# =============================================================================

BLOCK_5_SOURCE_ROW_BY_SENTENCE_ID = {
    sentence_id:
        row_index

    for row_index, sentence_id
    in enumerate(
        BLOCK_5_TARGET_SENTENCE_IDS
    )
}


BLOCK_5_CANONICAL_ROW_INDICES = [
    BLOCK_5_SOURCE_ROW_BY_SENTENCE_ID[
        sentence_id
    ]

    for sentence_id
    in NOTEBOOK_06_SENTENCE_IDS
]


BLOCK_5_TARGET_MATRIX = np.asarray(
    BLOCK_2_FACTUAL_TARGET_MATRIX,
    dtype=np.float64,
)[
    BLOCK_5_CANONICAL_ROW_INDICES,
    :
]


BLOCK_5_MASK_MATRIX = np.asarray(
    BLOCK_2_FACTUAL_MASK_MATRIX,
    dtype=bool,
)[
    BLOCK_5_CANONICAL_ROW_INDICES,
    :
]


BLOCK_5_TARGET_MATRIX_SHAPE = tuple(
    BLOCK_5_TARGET_MATRIX.shape
)


BLOCK_5_MASK_MATRIX_SHAPE = tuple(
    BLOCK_5_MASK_MATRIX.shape
)


BLOCK_5_EXPECTED_MATRIX_SHAPE = (
    NOTEBOOK_06_SENTENCE_COUNT,
    10,
)


BLOCK_5_TARGET_MATRIX_SHAPE_VALID = (
    BLOCK_5_TARGET_MATRIX_SHAPE
    ==
    BLOCK_5_EXPECTED_MATRIX_SHAPE
)


BLOCK_5_MASK_MATRIX_SHAPE_VALID = (
    BLOCK_5_MASK_MATRIX_SHAPE
    ==
    BLOCK_5_EXPECTED_MATRIX_SHAPE
)


if not BLOCK_5_TARGET_MATRIX_SHAPE_VALID:

    raise RuntimeError(
        "Block 5 factual target matrix has invalid shape. "
        f"Observed: {BLOCK_5_TARGET_MATRIX_SHAPE}; "
        f"expected: {BLOCK_5_EXPECTED_MATRIX_SHAPE}."
    )


if not BLOCK_5_MASK_MATRIX_SHAPE_VALID:

    raise RuntimeError(
        "Block 5 factual mask matrix has invalid shape. "
        f"Observed: {BLOCK_5_MASK_MATRIX_SHAPE}; "
        f"expected: {BLOCK_5_EXPECTED_MATRIX_SHAPE}."
    )


# =============================================================================
# Validate observed target values
# =============================================================================

BLOCK_5_OBSERVED_TARGET_VALUES_FINITE = bool(
    np.isfinite(
        BLOCK_5_TARGET_MATRIX[
            BLOCK_5_MASK_MATRIX
        ]
    ).all()
)


if not BLOCK_5_OBSERVED_TARGET_VALUES_FINITE:

    raise RuntimeError(
        "One or more observed factual target values are non-finite."
    )


# =============================================================================
# Convert validated factual supervision to tensors
# =============================================================================

BLOCK_5_FACTUAL_TARGETS = torch.tensor(
    BLOCK_5_TARGET_MATRIX,
    dtype=torch.float32,
)


BLOCK_5_FACTUAL_MASKS = torch.tensor(
    BLOCK_5_MASK_MATRIX,
    dtype=torch.bool,
)


# =============================================================================
# Active supervision availability
# =============================================================================

BLOCK_5_ACTIVE_AVAILABLE_COUNTS = {}


for target_name in BLOCK_5_ACTIVE_DIMENSIONS:

    target_index = (
        BLOCK_5_DIMENSION_INDEX[
            target_name
        ]
    )


    BLOCK_5_ACTIVE_AVAILABLE_COUNTS[
        target_name
    ] = int(
        BLOCK_5_FACTUAL_MASKS[
            :,
            target_index,
        ]
        .sum()
        .item()
    )


BLOCK_5_ALL_ACTIVE_OBJECTIVES_OBSERVED = all(
    available_count > 0

    for available_count
    in BLOCK_5_ACTIVE_AVAILABLE_COUNTS.values()
)


if not BLOCK_5_ALL_ACTIVE_OBJECTIVES_OBSERVED:

    raise RuntimeError(
        "At least one active factual objective has no available "
        "supervision. "
        f"Observed counts: {BLOCK_5_ACTIVE_AVAILABLE_COUNTS}"
    )


# =============================================================================
# Reproduce validated Block 2 / Block 3 supervision coverage
# =============================================================================
#
# Active factual objectives need validated observed supervision, but they do
# not need to be observed for every canonical sentence. Refined dimensions
# such as prediction may remain masked for unresolved cases.
#
# Block 5 therefore reproduces the per-dimension availability counts already
# established by Block 2 and consumed by the valid Block 3 activation policy.
# =============================================================================

BLOCK_5_EXPECTED_ACTIVE_AVAILABLE_COUNTS = {
    target_name:
        int(
            BLOCK_2_DIMENSION_AVAILABLE_COUNTS[
                target_name
            ]
        )

    for target_name
    in BLOCK_5_ACTIVE_DIMENSIONS
}


BLOCK_5_ACTIVE_COVERAGE_REPRODUCED = all(
    BLOCK_5_ACTIVE_AVAILABLE_COUNTS[
        target_name
    ]
    ==
    BLOCK_5_EXPECTED_ACTIVE_AVAILABLE_COUNTS[
        target_name
    ]

    for target_name
    in BLOCK_5_ACTIVE_DIMENSIONS
)


BLOCK_5_ACTIVE_COVERAGE_VALUES_VALID = all(
    0
    <
    BLOCK_5_ACTIVE_AVAILABLE_COUNTS[
        target_name
    ]
    <=
    NOTEBOOK_06_SENTENCE_COUNT

    for target_name
    in BLOCK_5_ACTIVE_DIMENSIONS
)


BLOCK_5_ACTIVE_COVERAGE_FRACTIONS = {
    target_name:
        float(
            BLOCK_5_ACTIVE_AVAILABLE_COUNTS[
                target_name
            ]
            /
            NOTEBOOK_06_SENTENCE_COUNT
        )

    for target_name
    in BLOCK_5_ACTIVE_DIMENSIONS
}


BLOCK_5_ACTIVE_COVERAGE_FRACTIONS_REPRODUCED = all(
    math.isclose(
        BLOCK_5_ACTIVE_COVERAGE_FRACTIONS[
            target_name
        ],
        float(
            BLOCK_2_DIMENSION_COVERAGE[
                target_name
            ]
        ),
        rel_tol=0.0,
        abs_tol=1e-12,
    )

    for target_name
    in BLOCK_5_ACTIVE_DIMENSIONS
)


if not all([
    BLOCK_5_ACTIVE_COVERAGE_REPRODUCED,
    BLOCK_5_ACTIVE_COVERAGE_VALUES_VALID,
    BLOCK_5_ACTIVE_COVERAGE_FRACTIONS_REPRODUCED,
]):

    raise RuntimeError(
        "Block 5 active factual supervision does not reproduce the "
        "validated Block 2 / Block 3 per-dimension coverage contract. "
        f"Observed counts: {BLOCK_5_ACTIVE_AVAILABLE_COUNTS}; "
        f"expected counts: {BLOCK_5_EXPECTED_ACTIVE_AVAILABLE_COUNTS}"
    )


# =============================================================================
# Binary factual target validation
# =============================================================================

BLOCK_5_BINARY_TARGET_VALUES_VALID = True

BLOCK_5_BINARY_TARGET_ERRORS = []


for target_name in BLOCK_5_ACTIVE_BINARY_DIMENSIONS:

    target_index = (
        BLOCK_5_DIMENSION_INDEX[
            target_name
        ]
    )


    target_mask = (
        BLOCK_5_FACTUAL_MASKS[
            :,
            target_index,
        ]
    )


    observed_values = (
        BLOCK_5_FACTUAL_TARGETS[
            :,
            target_index,
        ][
            target_mask
        ]
    )


    binary_values_valid = bool(
        torch.all(
            (
                observed_values
                == 0.0
            )
            |
            (
                observed_values
                == 1.0
            )
        ).item()
    )


    if not binary_values_valid:

        BLOCK_5_BINARY_TARGET_VALUES_VALID = False

        BLOCK_5_BINARY_TARGET_ERRORS.append(
            target_name
        )


if not BLOCK_5_BINARY_TARGET_VALUES_VALID:

    raise RuntimeError(
        "Active binary factual targets contain values outside "
        "{0, 1}. "
        f"Invalid dimensions: {BLOCK_5_BINARY_TARGET_ERRORS}"
    )


# =============================================================================
# Continuous F10 validation
# =============================================================================

BLOCK_5_FACTOLOGICAL_WEIGHT_INDEX = (
    BLOCK_5_DIMENSION_INDEX[
        "factological_weight"
    ]
)


BLOCK_5_FACTOLOGICAL_WEIGHT_MASK = (
    BLOCK_5_FACTUAL_MASKS[
        :,
        BLOCK_5_FACTOLOGICAL_WEIGHT_INDEX,
    ]
)


BLOCK_5_FACTOLOGICAL_WEIGHT_TARGETS = (
    BLOCK_5_FACTUAL_TARGETS[
        :,
        BLOCK_5_FACTOLOGICAL_WEIGHT_INDEX,
    ][
        BLOCK_5_FACTOLOGICAL_WEIGHT_MASK
    ]
)


BLOCK_5_CONTINUOUS_TARGETS_FINITE = bool(
    torch.isfinite(
        BLOCK_5_FACTOLOGICAL_WEIGHT_TARGETS
    ).all().item()
)


if not BLOCK_5_CONTINUOUS_TARGETS_FINITE:

    raise RuntimeError(
        "Observed factological_weight targets contain "
        "non-finite values."
    )


# =============================================================================
# Positive-class imbalance policy
# =============================================================================
#
# Block 3 may assign positive-class weights to any active binary factual
# dimension for which imbalance correction is required.
#
# Block 5 validates the inherited mapping and independently reproduces each
# supplied weight from the observed binary target distribution:
#
#     positive-class weight = negative_count / positive_count
#
# Binary dimensions without a supplied weight remain valid and use ordinary
# unweighted BCEWithLogitsLoss.
# =============================================================================

BLOCK_5_POSITIVE_CLASS_WEIGHTS = deepcopy(
    NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS
)


BLOCK_5_WEIGHTED_BINARY_DIMENSIONS = tuple(
    BLOCK_5_POSITIVE_CLASS_WEIGHTS.keys()
)


BLOCK_5_POSITIVE_CLASS_WEIGHT_KEYS_VALID = (
    set(
        BLOCK_5_WEIGHTED_BINARY_DIMENSIONS
    ).issubset(
        BLOCK_5_ACTIVE_BINARY_SET
    )
)


BLOCK_5_POSITIVE_CLASS_WEIGHT_VALUES_VALID = all(
    isinstance(
        weight_value,
        (
            int,
            float,
            np.integer,
            np.floating,
        ),
    )
    and
    math.isfinite(
        float(
            weight_value
        )
    )
    and
    float(
        weight_value
    )
    >
    0.0

    for weight_value
    in BLOCK_5_POSITIVE_CLASS_WEIGHTS.values()
)


if not all(
    [
        BLOCK_5_POSITIVE_CLASS_WEIGHT_KEYS_VALID,
        BLOCK_5_POSITIVE_CLASS_WEIGHT_VALUES_VALID,
    ]
):

    raise RuntimeError(
        "Block 5 positive-class weights are inconsistent with "
        "the validated Block 3 active binary objective policy."
    )


# =============================================================================
# Independent empirical reproduction of weighted binary class balance
# =============================================================================

BLOCK_5_WEIGHTED_BINARY_CLASS_COUNTS = {}

BLOCK_5_RECALCULATED_POSITIVE_CLASS_WEIGHTS = {}

BLOCK_5_POSITIVE_CLASS_WEIGHT_REPRODUCTION = {}


for target_name in BLOCK_5_WEIGHTED_BINARY_DIMENSIONS:

    target_index = (
        BLOCK_5_DIMENSION_INDEX[
            target_name
        ]
    )


    target_mask = (
        BLOCK_5_FACTUAL_MASKS[
            :,
            target_index,
        ]
    )


    observed_targets = (
        BLOCK_5_FACTUAL_TARGETS[
            :,
            target_index,
        ][
            target_mask
        ]
    )


    positive_count = int(
        (
            observed_targets
            == 1.0
        )
        .sum()
        .item()
    )


    negative_count = int(
        (
            observed_targets
            == 0.0
        )
        .sum()
        .item()
    )


    if positive_count <= 0:

        raise RuntimeError(
            f"{target_name} has no positive supervision but "
            "received a positive-class weight."
        )


    recalculated_weight = (
        negative_count
        /
        positive_count
    )


    inherited_weight = float(
        BLOCK_5_POSITIVE_CLASS_WEIGHTS[
            target_name
        ]
    )


    weight_reproduced = math.isclose(
        recalculated_weight,
        inherited_weight,
        rel_tol=
            0.0,
        abs_tol=
            1e-12,
    )


    BLOCK_5_WEIGHTED_BINARY_CLASS_COUNTS[
        target_name
    ] = {
        "positive":
            positive_count,

        "negative":
            negative_count,
    }


    BLOCK_5_RECALCULATED_POSITIVE_CLASS_WEIGHTS[
        target_name
    ] = recalculated_weight


    BLOCK_5_POSITIVE_CLASS_WEIGHT_REPRODUCTION[
        target_name
    ] = weight_reproduced


BLOCK_5_ALL_POSITIVE_CLASS_WEIGHTS_REPRODUCED = all(
    BLOCK_5_POSITIVE_CLASS_WEIGHT_REPRODUCTION.values()
)


if not BLOCK_5_ALL_POSITIVE_CLASS_WEIGHTS_REPRODUCED:

    raise RuntimeError(
        "One or more positive-class weights do not match the "
        "observed Block 2 target distributions. "
        f"Reproduction: {BLOCK_5_POSITIVE_CLASS_WEIGHT_REPRODUCTION}"
    )


# -----------------------------------------------------------------------------
# Backward-compatible prediction aliases
# -----------------------------------------------------------------------------
#
# These aliases are retained because later Notebook 06 blocks may inspect
# prediction-specific diagnostics established by the earlier Block 5 contract.
# They no longer imply that prediction is the only weighted binary dimension.
# -----------------------------------------------------------------------------

BLOCK_5_PREDICTION_INDEX = (
    BLOCK_5_DIMENSION_INDEX[
        "prediction"
    ]
)


BLOCK_5_PREDICTION_MASK = (
    BLOCK_5_FACTUAL_MASKS[
        :,
        BLOCK_5_PREDICTION_INDEX,
    ]
)


BLOCK_5_PREDICTION_TARGETS = (
    BLOCK_5_FACTUAL_TARGETS[
        :,
        BLOCK_5_PREDICTION_INDEX,
    ][
        BLOCK_5_PREDICTION_MASK
    ]
)


BLOCK_5_PREDICTION_POSITIVE_COUNT = int(
    (
        BLOCK_5_PREDICTION_TARGETS
        == 1.0
    )
    .sum()
    .item()
)


BLOCK_5_PREDICTION_NEGATIVE_COUNT = int(
    (
        BLOCK_5_PREDICTION_TARGETS
        == 0.0
    )
    .sum()
    .item()
)


BLOCK_5_PREDICTION_POSITIVE_WEIGHT = float(
    BLOCK_5_POSITIVE_CLASS_WEIGHTS.get(
        "prediction",
        1.0,
    )
)


BLOCK_5_RECALCULATED_PREDICTION_WEIGHT = (
    BLOCK_5_PREDICTION_NEGATIVE_COUNT
    /
    BLOCK_5_PREDICTION_POSITIVE_COUNT
    if BLOCK_5_PREDICTION_POSITIVE_COUNT > 0
    else float(
        "nan"
    )
)


BLOCK_5_PREDICTION_WEIGHT_VALID = (
    "prediction"
    in BLOCK_5_POSITIVE_CLASS_WEIGHTS
    and
    math.isfinite(
        BLOCK_5_PREDICTION_POSITIVE_WEIGHT
    )
    and
    BLOCK_5_PREDICTION_POSITIVE_WEIGHT
    >
    0.0
)


BLOCK_5_PREDICTION_WEIGHT_REPRODUCED = (
    BLOCK_5_POSITIVE_CLASS_WEIGHT_REPRODUCTION.get(
        "prediction",
        False,
    )
)

# =============================================================================
# Resolve exact Block 4 modules
# =============================================================================

BLOCK_5_BACKBONE = (
    NOTEBOOK_06_BACKBONE_FROZEN_MODULE
)


BLOCK_5_GLOBAL_CONFLUENT = (
    NOTEBOOK_06_GLOBAL_CONFLUENT_FROZEN_MODULE
)


BLOCK_5_FACTUAL_HEAD = (
    NOTEBOOK_06_FACTUAL_HEAD
)


BLOCK_5_PSYCHOLOGICAL_HEAD = (
    NOTEBOOK_06_PSYCHOLOGICAL_HEAD_FROZEN_MODULE
)


BLOCK_5_FACTUAL_HEAD_PATH = (
    "NOTEBOOK_06_FACTUAL_HEAD"
)


# =============================================================================
# Parameter-freezing scope validation
# =============================================================================

BLOCK_5_BACKBONE_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in BLOCK_5_BACKBONE.parameters()
)


BLOCK_5_GLOBAL_CONFLUENT_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in BLOCK_5_GLOBAL_CONFLUENT.parameters()
)


BLOCK_5_PSYCHOLOGICAL_HEAD_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in BLOCK_5_PSYCHOLOGICAL_HEAD.parameters()
)


BLOCK_5_FACTUAL_HEAD_TRAINABLE = all(
    parameter.requires_grad

    for parameter
    in BLOCK_5_FACTUAL_HEAD.parameters()
)


BLOCK_5_FACTUAL_TRAINABLE_PARAMETERS = [
    parameter

    for parameter
    in BLOCK_5_FACTUAL_HEAD.parameters()

    if parameter.requires_grad
]


BLOCK_5_FACTUAL_TRAINABLE_PARAMETER_COUNT = sum(
    parameter.numel()

    for parameter
    in BLOCK_5_FACTUAL_TRAINABLE_PARAMETERS
)


BLOCK_5_EXPECTED_FACTUAL_PARAMETER_COUNT = 34442


BLOCK_5_FACTUAL_PARAMETER_COUNT_VALID = (
    BLOCK_5_FACTUAL_TRAINABLE_PARAMETER_COUNT
    ==
    BLOCK_5_EXPECTED_FACTUAL_PARAMETER_COUNT
)


BLOCK_5_PARAMETER_SCOPE_VALID = all(
    [
        BLOCK_5_BACKBONE_FROZEN,
        BLOCK_5_GLOBAL_CONFLUENT_FROZEN,
        BLOCK_5_PSYCHOLOGICAL_HEAD_FROZEN,
        BLOCK_5_FACTUAL_HEAD_TRAINABLE,
        BLOCK_5_FACTUAL_PARAMETER_COUNT_VALID,
    ]
)


if not BLOCK_5_PARAMETER_SCOPE_VALID:

    raise RuntimeError(
        "Block 5 parameter scope does not reproduce "
        "the validated Block 4 freezing policy."
    )


# =============================================================================
# Snapshot all relevant model parameters before objective validation
# =============================================================================

def block_5_snapshot_module(
    module,
):
    return {
        parameter_name:
            parameter.detach()
            .cpu()
            .clone()

        for parameter_name, parameter
        in module.named_parameters()
    }


BLOCK_5_BACKBONE_STATE_BEFORE = (
    block_5_snapshot_module(
        BLOCK_5_BACKBONE
    )
)


BLOCK_5_GLOBAL_CONFLUENT_STATE_BEFORE = (
    block_5_snapshot_module(
        BLOCK_5_GLOBAL_CONFLUENT
    )
)


BLOCK_5_FACTUAL_STATE_BEFORE = (
    block_5_snapshot_module(
        BLOCK_5_FACTUAL_HEAD
    )
)


BLOCK_5_PSYCHOLOGICAL_STATE_BEFORE = (
    block_5_snapshot_module(
        BLOCK_5_PSYCHOLOGICAL_HEAD
    )
)


# =============================================================================
# Consume the already validated Block 4 factual forward output
# =============================================================================
#
# Block 4 executed:
#
# contextual representation
#     -> frozen backbone
#     -> frozen global confluent path
#     -> factual head
#
# Block 5 does not execute a second model forward pass.
#
# Its purpose is objective and optimiser validation.
#
# Block 6 will execute the factual head again from
# NOTEBOOK_06_FACTUAL_FORWARD_INPUT to obtain a live autograd graph.
# =============================================================================

BLOCK_5_FACTUAL_OUTPUT = (
    NOTEBOOK_06_FACTUAL_FORWARD_OUTPUT
)


if not isinstance(
    BLOCK_5_FACTUAL_OUTPUT,
    torch.Tensor,
):

    raise TypeError(
        "NOTEBOOK_06_FACTUAL_FORWARD_OUTPUT must be a torch.Tensor."
    )


BLOCK_5_FACTUAL_OUTPUT_SHAPE = tuple(
    BLOCK_5_FACTUAL_OUTPUT.shape
)


BLOCK_5_EXPECTED_FACTUAL_OUTPUT_SHAPE = (
    NOTEBOOK_06_SENTENCE_COUNT,
    10,
)


BLOCK_5_FACTUAL_OUTPUT_SHAPE_VALID = (
    BLOCK_5_FACTUAL_OUTPUT_SHAPE
    ==
    BLOCK_5_EXPECTED_FACTUAL_OUTPUT_SHAPE
)


BLOCK_5_FACTUAL_OUTPUT_FINITE = bool(
    torch.isfinite(
        BLOCK_5_FACTUAL_OUTPUT
    ).all().item()
)


if not all(
    [
        BLOCK_5_FACTUAL_OUTPUT_SHAPE_VALID,
        BLOCK_5_FACTUAL_OUTPUT_FINITE,
    ]
):

    raise RuntimeError(
        "Validated Block 4 factual output is not suitable "
        "for Block 5 objective assembly."
    )


# =============================================================================
# Align target tensors to factual-output device and dtype
# =============================================================================

BLOCK_5_OUTPUT_DEVICE = (
    BLOCK_5_FACTUAL_OUTPUT.device
)


BLOCK_5_OUTPUT_DTYPE = (
    BLOCK_5_FACTUAL_OUTPUT.dtype
)


BLOCK_5_FACTUAL_TARGETS_DEVICE = (
    BLOCK_5_FACTUAL_TARGETS.to(
        device=
            BLOCK_5_OUTPUT_DEVICE,
        dtype=
            BLOCK_5_OUTPUT_DTYPE,
    )
)


BLOCK_5_FACTUAL_MASKS_DEVICE = (
    BLOCK_5_FACTUAL_MASKS.to(
        device=
            BLOCK_5_OUTPUT_DEVICE,
    )
)


BLOCK_5_POSITIVE_CLASS_WEIGHTS_DEVICE = {
    target_name:
        torch.tensor(
            float(
                positive_weight
            ),
            dtype=
                BLOCK_5_OUTPUT_DTYPE,
            device=
                BLOCK_5_OUTPUT_DEVICE,
        )

    for target_name, positive_weight
    in BLOCK_5_POSITIVE_CLASS_WEIGHTS.items()
}


# Backward-compatible prediction alias.
BLOCK_5_PREDICTION_POS_WEIGHT_DEVICE = (
    BLOCK_5_POSITIVE_CLASS_WEIGHTS_DEVICE.get(
        "prediction"
    )
)


# =============================================================================
# Objective-family weights
# =============================================================================
#
# All currently active factual family losses contribute equally.
#
# Each family weight is 1 / number_of_active_dimensions.
#
# This is separate from prediction's positive-class weight, which operates
# inside F9 BCEWithLogitsLoss.
# =============================================================================

BLOCK_5_OBJECTIVE_WEIGHTS = {
    target_name:
        (
            1.0
            /
            len(
                BLOCK_5_ACTIVE_DIMENSIONS
            )
        )

    for target_name
    in BLOCK_5_ACTIVE_DIMENSIONS
}


BLOCK_5_OBJECTIVE_WEIGHT_SUM = sum(
    BLOCK_5_OBJECTIVE_WEIGHTS.values()
)


BLOCK_5_OBJECTIVE_WEIGHTS_VALID = math.isclose(
    BLOCK_5_OBJECTIVE_WEIGHT_SUM,
    1.0,
    rel_tol=0.0,
    abs_tol=1e-12,
)


if not BLOCK_5_OBJECTIVE_WEIGHTS_VALID:

    raise RuntimeError(
        "Block 5 objective-family weights do not sum to 1."
    )


# =============================================================================
# Masked binary objective helper
# =============================================================================

def block_5_masked_bce_with_logits(
    logits,
    targets,
    mask,
    pos_weight=None,
):

    if mask.dtype != torch.bool:

        mask = mask.bool()


    observed_count = int(
        mask.sum()
        .item()
    )


    if observed_count <= 0:

        raise RuntimeError(
            "Active binary factual objective has no "
            "available supervision."
        )


    selected_logits = logits[
        mask
    ]


    selected_targets = targets[
        mask
    ]


    if pos_weight is None:

        loss = F.binary_cross_entropy_with_logits(
            selected_logits,
            selected_targets,
            reduction="mean",
        )


    else:

        loss = F.binary_cross_entropy_with_logits(
            selected_logits,
            selected_targets,
            pos_weight=
                pos_weight,
            reduction="mean",
        )


    return (
        loss,
        observed_count,
    )


# =============================================================================
# Masked continuous objective helper
# =============================================================================

def block_5_masked_mse(
    predictions,
    targets,
    mask,
):

    if mask.dtype != torch.bool:

        mask = mask.bool()


    observed_count = int(
        mask.sum()
        .item()
    )


    if observed_count <= 0:

        raise RuntimeError(
            "Active continuous factual objective has no "
            "available supervision."
        )


    selected_predictions = predictions[
        mask
    ]


    selected_targets = targets[
        mask
    ]


    loss = F.mse_loss(
        selected_predictions,
        selected_targets,
        reduction="mean",
    )


    return (
        loss,
        observed_count,
    )


# =============================================================================
# Assemble independent active factual losses
# =============================================================================

BLOCK_5_FAMILY_LOSSES = {}

BLOCK_5_FAMILY_OBSERVED_COUNTS = {}


# -----------------------------------------------------------------------------
# Active binary factual objectives
# -----------------------------------------------------------------------------

for target_name in BLOCK_5_ACTIVE_BINARY_DIMENSIONS:

    target_index = (
        BLOCK_5_DIMENSION_INDEX[
            target_name
        ]
    )


    logits = (
        BLOCK_5_FACTUAL_OUTPUT[
            :,
            target_index,
        ]
    )


    targets = (
        BLOCK_5_FACTUAL_TARGETS_DEVICE[
            :,
            target_index,
        ]
    )


    mask = (
        BLOCK_5_FACTUAL_MASKS_DEVICE[
            :,
            target_index,
        ]
    )


    positive_weight = (
        BLOCK_5_POSITIVE_CLASS_WEIGHTS_DEVICE.get(
            target_name
        )
    )


    (
        family_loss,
        observed_count,
    ) = block_5_masked_bce_with_logits(
        logits=
            logits,
        targets=
            targets,
        mask=
            mask,
        pos_weight=
            positive_weight,
    )


    BLOCK_5_FAMILY_LOSSES[
        target_name
    ] = family_loss


    BLOCK_5_FAMILY_OBSERVED_COUNTS[
        target_name
    ] = observed_count


# -----------------------------------------------------------------------------
# F10 continuous factual-weight objective
# -----------------------------------------------------------------------------

BLOCK_5_WEIGHT_PREDICTIONS = (
    BLOCK_5_FACTUAL_OUTPUT[
        :,
        BLOCK_5_FACTOLOGICAL_WEIGHT_INDEX,
    ]
)


BLOCK_5_WEIGHT_TARGETS_DEVICE = (
    BLOCK_5_FACTUAL_TARGETS_DEVICE[
        :,
        BLOCK_5_FACTOLOGICAL_WEIGHT_INDEX,
    ]
)


BLOCK_5_WEIGHT_MASK_DEVICE = (
    BLOCK_5_FACTUAL_MASKS_DEVICE[
        :,
        BLOCK_5_FACTOLOGICAL_WEIGHT_INDEX,
    ]
)


(
    BLOCK_5_FACTOLOGICAL_WEIGHT_LOSS,
    BLOCK_5_FACTOLOGICAL_WEIGHT_OBSERVED_COUNT,
) = block_5_masked_mse(
    predictions=
        BLOCK_5_WEIGHT_PREDICTIONS,
    targets=
        BLOCK_5_WEIGHT_TARGETS_DEVICE,
    mask=
        BLOCK_5_WEIGHT_MASK_DEVICE,
)


BLOCK_5_FAMILY_LOSSES[
    "factological_weight"
] = BLOCK_5_FACTOLOGICAL_WEIGHT_LOSS


BLOCK_5_FAMILY_OBSERVED_COUNTS[
    "factological_weight"
] = (
    BLOCK_5_FACTOLOGICAL_WEIGHT_OBSERVED_COUNT
)


NOTEBOOK_06_FACTUAL_OBJECTIVES_ACTIVATED = True

NOTEBOOK_06_FACTUAL_LOSS_CALCULATED = True


# =============================================================================
# Active family loss validation
# =============================================================================

BLOCK_5_ALL_ACTIVE_LOSSES_PRESENT = (
    set(
        BLOCK_5_FAMILY_LOSSES.keys()
    )
    ==
    set(
        BLOCK_5_ACTIVE_DIMENSIONS
    )
)


BLOCK_5_ALL_ACTIVE_LOSSES_FINITE = all(
    bool(
        torch.isfinite(
            family_loss
        ).item()
    )

    for family_loss
    in BLOCK_5_FAMILY_LOSSES.values()
)


if not all(
    [
        BLOCK_5_ALL_ACTIVE_LOSSES_PRESENT,
        BLOCK_5_ALL_ACTIVE_LOSSES_FINITE,
    ]
):

    raise RuntimeError(
        "One or more Block 5 factual family losses are "
        "missing or non-finite."
    )


# =============================================================================
# Validate deferred dimensions remain outside objective
# =============================================================================

BLOCK_5_DEFERRED_DIMENSIONS_EXCLUDED = all(
    dimension_name
    not in
    BLOCK_5_FAMILY_LOSSES

    for dimension_name
    in BLOCK_5_DEFERRED_DIMENSIONS
)


if not BLOCK_5_DEFERRED_DIMENSIONS_EXCLUDED:

    raise RuntimeError(
        "A deferred factual dimension entered the Block 5 objective."
    )


# =============================================================================
# Controlled total factual objective
# =============================================================================

BLOCK_5_WEIGHTED_FAMILY_LOSSES = {
    target_name:
        (
            BLOCK_5_OBJECTIVE_WEIGHTS[
                target_name
            ]
            *
            BLOCK_5_FAMILY_LOSSES[
                target_name
            ]
        )

    for target_name
    in BLOCK_5_ACTIVE_DIMENSIONS
}


BLOCK_5_TOTAL_FACTUAL_OBJECTIVE = sum(
    BLOCK_5_WEIGHTED_FAMILY_LOSSES[
        target_name
    ]

    for target_name
    in BLOCK_5_ACTIVE_DIMENSIONS
)


BLOCK_5_TOTAL_OBJECTIVE_FINITE = bool(
    torch.isfinite(
        BLOCK_5_TOTAL_FACTUAL_OBJECTIVE
    ).item()
)


BLOCK_5_TOTAL_OBJECTIVE_SCALAR = (
    BLOCK_5_TOTAL_FACTUAL_OBJECTIVE.ndim
    == 0
)


if not all(
    [
        BLOCK_5_TOTAL_OBJECTIVE_FINITE,
        BLOCK_5_TOTAL_OBJECTIVE_SCALAR,
    ]
):

    raise RuntimeError(
        "Block 5 total factual objective is invalid."
    )


# =============================================================================
# Independent objective reproduction
# =============================================================================

BLOCK_5_REPRODUCED_FAMILY_LOSSES = {}


for target_name in BLOCK_5_ACTIVE_BINARY_DIMENSIONS:

    target_index = (
        BLOCK_5_DIMENSION_INDEX[
            target_name
        ]
    )


    positive_weight = (
        BLOCK_5_POSITIVE_CLASS_WEIGHTS_DEVICE.get(
            target_name
        )
    )


    reproduced_loss, _ = (
        block_5_masked_bce_with_logits(
            logits=
                BLOCK_5_FACTUAL_OUTPUT[
                    :,
                    target_index,
                ],
            targets=
                BLOCK_5_FACTUAL_TARGETS_DEVICE[
                    :,
                    target_index,
                ],
            mask=
                BLOCK_5_FACTUAL_MASKS_DEVICE[
                    :,
                    target_index,
                ],
            pos_weight=
                positive_weight,
        )
    )


    BLOCK_5_REPRODUCED_FAMILY_LOSSES[
        target_name
    ] = reproduced_loss


reproduced_weight_loss, _ = (
    block_5_masked_mse(
        predictions=
            BLOCK_5_WEIGHT_PREDICTIONS,
        targets=
            BLOCK_5_WEIGHT_TARGETS_DEVICE,
        mask=
            BLOCK_5_WEIGHT_MASK_DEVICE,
    )
)


BLOCK_5_REPRODUCED_FAMILY_LOSSES[
    "factological_weight"
] = reproduced_weight_loss


BLOCK_5_OBJECTIVE_TOLERANCE = 1e-7


BLOCK_5_FAMILY_LOSS_REPRODUCTION = {
    target_name:
        math.isclose(
            float(
                BLOCK_5_FAMILY_LOSSES[
                    target_name
                ]
                .detach()
                .cpu()
                .item()
            ),
            float(
                BLOCK_5_REPRODUCED_FAMILY_LOSSES[
                    target_name
                ]
                .detach()
                .cpu()
                .item()
            ),
            rel_tol=0.0,
            abs_tol=
                BLOCK_5_OBJECTIVE_TOLERANCE,
        )

    for target_name
    in BLOCK_5_ACTIVE_DIMENSIONS
}


BLOCK_5_ALL_FAMILY_LOSSES_REPRODUCED = all(
    BLOCK_5_FAMILY_LOSS_REPRODUCTION.values()
)


if not BLOCK_5_ALL_FAMILY_LOSSES_REPRODUCED:

    raise RuntimeError(
        "One or more factual family losses failed "
        "independent reproduction."
    )


BLOCK_5_REPRODUCED_TOTAL_OBJECTIVE = sum(
    BLOCK_5_OBJECTIVE_WEIGHTS[
        target_name
    ]
    *
    BLOCK_5_REPRODUCED_FAMILY_LOSSES[
        target_name
    ]

    for target_name
    in BLOCK_5_ACTIVE_DIMENSIONS
)


BLOCK_5_TOTAL_OBJECTIVE_REPRODUCED = math.isclose(
    float(
        BLOCK_5_TOTAL_FACTUAL_OBJECTIVE
        .detach()
        .cpu()
        .item()
    ),
    float(
        BLOCK_5_REPRODUCED_TOTAL_OBJECTIVE
        .detach()
        .cpu()
        .item()
    ),
    rel_tol=0.0,
    abs_tol=
        BLOCK_5_OBJECTIVE_TOLERANCE,
)


if not BLOCK_5_TOTAL_OBJECTIVE_REPRODUCED:

    raise RuntimeError(
        "Block 5 total factual objective failed reproduction."
    )


# =============================================================================
# Optimiser policy
# =============================================================================
#
# The optimiser is created only for the validated factual-head parameters.
#
# No zero_grad(), backward() or step() occurs in this block.
# =============================================================================

NOTEBOOK_06_FACTUAL_OPTIMISER_TYPE = "AdamW"

NOTEBOOK_06_FACTUAL_LEARNING_RATE = 1e-3

NOTEBOOK_06_FACTUAL_WEIGHT_DECAY = 1e-4


BLOCK_5_FACTUAL_OPTIMIZER = torch.optim.AdamW(
    BLOCK_5_FACTUAL_TRAINABLE_PARAMETERS,
    lr=
        NOTEBOOK_06_FACTUAL_LEARNING_RATE,
    weight_decay=
        NOTEBOOK_06_FACTUAL_WEIGHT_DECAY,
)


NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED = True


# =============================================================================
# Optimiser scope validation
# =============================================================================

BLOCK_5_FACTUAL_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter
    in BLOCK_5_FACTUAL_TRAINABLE_PARAMETERS
}


BLOCK_5_OPTIMIZER_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter_group
    in BLOCK_5_FACTUAL_OPTIMIZER.param_groups

    for parameter
    in parameter_group[
        "params"
    ]
}


BLOCK_5_OPTIMIZER_SCOPE_EXACT = (
    BLOCK_5_OPTIMIZER_PARAMETER_IDS
    ==
    BLOCK_5_FACTUAL_PARAMETER_IDS
)


BLOCK_5_OPTIMIZER_PARAMETER_COUNT = sum(
    parameter.numel()

    for parameter_group
    in BLOCK_5_FACTUAL_OPTIMIZER.param_groups

    for parameter
    in parameter_group[
        "params"
    ]
)


BLOCK_5_OPTIMIZER_PARAMETER_COUNT_VALID = (
    BLOCK_5_OPTIMIZER_PARAMETER_COUNT
    ==
    BLOCK_5_FACTUAL_TRAINABLE_PARAMETER_COUNT
    ==
    BLOCK_5_EXPECTED_FACTUAL_PARAMETER_COUNT
)


BLOCK_5_OPTIMIZER_SCOPE_VALID = all(
    [
        BLOCK_5_OPTIMIZER_SCOPE_EXACT,
        BLOCK_5_OPTIMIZER_PARAMETER_COUNT_VALID,
    ]
)


if not BLOCK_5_OPTIMIZER_SCOPE_VALID:

    raise RuntimeError(
        "Block 5 AdamW optimiser is not scoped exclusively "
        "to the factual head."
    )


# =============================================================================
# Optimiser state boundary
# =============================================================================

BLOCK_5_OPTIMIZER_STATE_EMPTY = (
    len(
        BLOCK_5_FACTUAL_OPTIMIZER.state
    )
    == 0
)


if not BLOCK_5_OPTIMIZER_STATE_EMPTY:

    raise RuntimeError(
        "Block 5 optimiser contains step state before "
        "any optimisation step."
    )


# =============================================================================
# Gradient-state validation
# =============================================================================
#
# Block 4 output is detached and Block 5 performs no backward pass.
#
# Factual-head .grad attributes must therefore remain empty.
# =============================================================================

BLOCK_5_FACTUAL_GRADIENTS_ABSENT = all(
    parameter.grad is None

    for parameter
    in BLOCK_5_FACTUAL_HEAD.parameters()
)


if not BLOCK_5_FACTUAL_GRADIENTS_ABSENT:

    raise RuntimeError(
        "Factual-head gradients exist even though Block 5 "
        "performed no backward pass."
    )


# =============================================================================
# No-update validation
# =============================================================================

def block_5_module_unchanged(
    module,
    before_state,
):

    current_state = {
        parameter_name:
            parameter.detach()
            .cpu()

        for parameter_name, parameter
        in module.named_parameters()
    }


    if (
        set(
            current_state.keys()
        )
        !=
        set(
            before_state.keys()
        )
    ):

        return False


    return all(
        torch.equal(
            current_state[
                parameter_name
            ],
            before_state[
                parameter_name
            ],
        )

        for parameter_name
        in before_state
    )


BLOCK_5_BACKBONE_UNCHANGED = (
    block_5_module_unchanged(
        BLOCK_5_BACKBONE,
        BLOCK_5_BACKBONE_STATE_BEFORE,
    )
)


BLOCK_5_GLOBAL_CONFLUENT_UNCHANGED = (
    block_5_module_unchanged(
        BLOCK_5_GLOBAL_CONFLUENT,
        BLOCK_5_GLOBAL_CONFLUENT_STATE_BEFORE,
    )
)


BLOCK_5_FACTUAL_HEAD_UNCHANGED = (
    block_5_module_unchanged(
        BLOCK_5_FACTUAL_HEAD,
        BLOCK_5_FACTUAL_STATE_BEFORE,
    )
)


BLOCK_5_PSYCHOLOGICAL_HEAD_UNCHANGED = (
    block_5_module_unchanged(
        BLOCK_5_PSYCHOLOGICAL_HEAD,
        BLOCK_5_PSYCHOLOGICAL_STATE_BEFORE,
    )
)


BLOCK_5_FROZEN_PARAMETERS_UNCHANGED = all(
    [
        BLOCK_5_BACKBONE_UNCHANGED,
        BLOCK_5_GLOBAL_CONFLUENT_UNCHANGED,
        BLOCK_5_PSYCHOLOGICAL_HEAD_UNCHANGED,
    ]
)


BLOCK_5_ALL_MODEL_PARAMETERS_UNCHANGED = all(
    [
        BLOCK_5_BACKBONE_UNCHANGED,
        BLOCK_5_GLOBAL_CONFLUENT_UNCHANGED,
        BLOCK_5_FACTUAL_HEAD_UNCHANGED,
        BLOCK_5_PSYCHOLOGICAL_HEAD_UNCHANGED,
    ]
)


BLOCK_5_NO_UPDATE_VALID = (
    BLOCK_5_ALL_MODEL_PARAMETERS_UNCHANGED
)


if not BLOCK_5_NO_UPDATE_VALID:

    raise RuntimeError(
        "One or more Media AI parameters changed during "
        "Block 5 controlled objective validation."
    )


# =============================================================================
# Execution-state finalisation
# =============================================================================

NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED = False

NOTEBOOK_06_ZERO_GRAD_EXECUTED = False

NOTEBOOK_06_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ACTIVATED = False

NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ACTIVATED = False

NOTEBOOK_06_RECURRENT_STATES_ACTIVATED = False

NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Readiness
# =============================================================================

NOTEBOOK_06_FACTUAL_OBJECTIVE_ASSEMBLED = all(
    [
        BLOCK_5_ALL_ACTIVE_LOSSES_PRESENT,
        BLOCK_5_ALL_ACTIVE_LOSSES_FINITE,
        BLOCK_5_TOTAL_OBJECTIVE_FINITE,
        BLOCK_5_TOTAL_OBJECTIVE_SCALAR,
        BLOCK_5_DEFERRED_DIMENSIONS_EXCLUDED,
    ]
)


NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_VALIDATED = all(
    [
        BLOCK_5_ACTIVE_CONTRACT_VALID,
        BLOCK_5_DEFERRED_CONTRACT_VALID,
        BLOCK_5_BINARY_CONTRACT_VALID,
        BLOCK_5_CONTINUOUS_CONTRACT_VALID,
        BLOCK_5_ACTIVE_INDICES_VALID,
        BLOCK_5_DEFERRED_INDICES_VALID,
        BLOCK_5_ACTIVE_COVERAGE_REPRODUCED,
        BLOCK_5_ACTIVE_COVERAGE_VALUES_VALID,
        BLOCK_5_ACTIVE_COVERAGE_FRACTIONS_REPRODUCED,
        BLOCK_5_BINARY_TARGET_VALUES_VALID,
        BLOCK_5_CONTINUOUS_TARGETS_FINITE,
        BLOCK_5_POSITIVE_CLASS_WEIGHT_KEYS_VALID,
        BLOCK_5_POSITIVE_CLASS_WEIGHT_VALUES_VALID,
        BLOCK_5_ALL_POSITIVE_CLASS_WEIGHTS_REPRODUCED,
        BLOCK_5_PREDICTION_WEIGHT_VALID,
        BLOCK_5_PREDICTION_WEIGHT_REPRODUCED,
        BLOCK_5_OBJECTIVE_WEIGHTS_VALID,
        BLOCK_5_DEFERRED_DIMENSIONS_EXCLUDED,
    ]
)


NOTEBOOK_06_FACTUAL_OPTIMIZER_POLICY_VALID = all(
    [
        NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED,
        BLOCK_5_PARAMETER_SCOPE_VALID,
        BLOCK_5_FACTUAL_PARAMETER_COUNT_VALID,
        BLOCK_5_OPTIMIZER_SCOPE_VALID,
        BLOCK_5_OPTIMIZER_STATE_EMPTY,
    ]
)


NOTEBOOK_06_FACTUAL_CONTROLLED_LOSS_VALID = all(
    [
        NOTEBOOK_06_FACTUAL_OBJECTIVE_ASSEMBLED,
        NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_VALIDATED,
        NOTEBOOK_06_FACTUAL_OPTIMIZER_POLICY_VALID,
        BLOCK_5_FACTUAL_OUTPUT_SHAPE_VALID,
        BLOCK_5_FACTUAL_OUTPUT_FINITE,
        BLOCK_5_ALL_FAMILY_LOSSES_REPRODUCED,
        BLOCK_5_TOTAL_OBJECTIVE_REPRODUCED,
        BLOCK_5_FACTUAL_GRADIENTS_ABSENT,
        BLOCK_5_NO_UPDATE_VALID,
    ]
)


NOTEBOOK_06_FACTUAL_OPTIMISATION_READY = (
    NOTEBOOK_06_FACTUAL_CONTROLLED_LOSS_VALID
)


NOTEBOOK_06_READY_FOR_CONTROLLED_FACTUAL_TRAINING = (
    NOTEBOOK_06_FACTUAL_OPTIMISATION_READY
)


# =============================================================================
# Final Block 5 validation
# =============================================================================

NOTEBOOK_06_BLOCK_5_ERRORS = []


block_5_validation_checks = {
    "dimension_order_invalid":
        BLOCK_5_DIMENSION_ORDER_VALID,

    "dimension_index_invalid":
        BLOCK_5_DIMENSION_INDEX_VALID,

    "active_contract_invalid":
        BLOCK_5_ACTIVE_CONTRACT_VALID,

    "deferred_contract_invalid":
        BLOCK_5_DEFERRED_CONTRACT_VALID,

    "binary_contract_invalid":
        BLOCK_5_BINARY_CONTRACT_VALID,

    "continuous_contract_invalid":
        BLOCK_5_CONTINUOUS_CONTRACT_VALID,

    "activation_contract_invalid":
        BLOCK_5_ACTIVATION_CONTRACT_VALID,

    "active_deferred_overlap":
        BLOCK_5_ACTIVE_DEFERRED_DISJOINT,

    "active_deferred_coverage_invalid":
        BLOCK_5_ACTIVE_DEFERRED_COMPLETE,

    "active_type_coverage_invalid":
        BLOCK_5_ACTIVE_TYPE_COVERAGE_VALID,

    "active_indices_invalid":
        BLOCK_5_ACTIVE_INDICES_VALID,

    "deferred_indices_invalid":
        BLOCK_5_DEFERRED_INDICES_VALID,

    "index_sets_overlap":
        BLOCK_5_INDEX_SETS_DISJOINT,

    "index_coverage_invalid":
        BLOCK_5_INDEX_COVERAGE_VALID,

    "target_sentence_ids_missing":
        BLOCK_5_TARGET_SENTENCE_IDS_PRESENT,

    "target_sentence_ids_not_unique":
        BLOCK_5_TARGET_SENTENCE_IDS_UNIQUE,

    "target_sentence_set_invalid":
        BLOCK_5_TARGET_SENTENCE_SET_VALID,

    "target_matrix_shape_invalid":
        BLOCK_5_TARGET_MATRIX_SHAPE_VALID,

    "mask_matrix_shape_invalid":
        BLOCK_5_MASK_MATRIX_SHAPE_VALID,

    "observed_targets_nonfinite":
        BLOCK_5_OBSERVED_TARGET_VALUES_FINITE,

    "active_supervision_missing":
        BLOCK_5_ALL_ACTIVE_OBJECTIVES_OBSERVED,

    "active_coverage_not_reproduced":
        BLOCK_5_ACTIVE_COVERAGE_REPRODUCED,

    "active_coverage_values_invalid":
        BLOCK_5_ACTIVE_COVERAGE_VALUES_VALID,

    "active_coverage_fractions_not_reproduced":
        BLOCK_5_ACTIVE_COVERAGE_FRACTIONS_REPRODUCED,

    "binary_target_values_invalid":
        BLOCK_5_BINARY_TARGET_VALUES_VALID,

    "continuous_targets_nonfinite":
        BLOCK_5_CONTINUOUS_TARGETS_FINITE,

    "positive_class_weight_keys_invalid":
        BLOCK_5_POSITIVE_CLASS_WEIGHT_KEYS_VALID,

    "positive_class_weight_values_invalid":
        BLOCK_5_POSITIVE_CLASS_WEIGHT_VALUES_VALID,

    "positive_class_weights_not_reproduced":
        BLOCK_5_ALL_POSITIVE_CLASS_WEIGHTS_REPRODUCED,

    "prediction_weight_invalid":
        BLOCK_5_PREDICTION_WEIGHT_VALID,

    "prediction_weight_not_reproduced":
        BLOCK_5_PREDICTION_WEIGHT_REPRODUCED,

    "parameter_scope_invalid":
        BLOCK_5_PARAMETER_SCOPE_VALID,

    "factual_parameter_count_invalid":
        BLOCK_5_FACTUAL_PARAMETER_COUNT_VALID,

    "factual_output_shape_invalid":
        BLOCK_5_FACTUAL_OUTPUT_SHAPE_VALID,

    "factual_output_nonfinite":
        BLOCK_5_FACTUAL_OUTPUT_FINITE,

    "objective_weights_invalid":
        BLOCK_5_OBJECTIVE_WEIGHTS_VALID,

    "active_losses_missing":
        BLOCK_5_ALL_ACTIVE_LOSSES_PRESENT,

    "active_losses_nonfinite":
        BLOCK_5_ALL_ACTIVE_LOSSES_FINITE,

    "deferred_dimension_entered_loss":
        BLOCK_5_DEFERRED_DIMENSIONS_EXCLUDED,

    "total_objective_nonfinite":
        BLOCK_5_TOTAL_OBJECTIVE_FINITE,

    "total_objective_not_scalar":
        BLOCK_5_TOTAL_OBJECTIVE_SCALAR,

    "family_loss_reproduction_failed":
        BLOCK_5_ALL_FAMILY_LOSSES_REPRODUCED,

    "total_objective_reproduction_failed":
        BLOCK_5_TOTAL_OBJECTIVE_REPRODUCED,

    "optimizer_scope_invalid":
        BLOCK_5_OPTIMIZER_SCOPE_VALID,

    "optimizer_state_not_empty":
        BLOCK_5_OPTIMIZER_STATE_EMPTY,

    "unexpected_gradients":
        BLOCK_5_FACTUAL_GRADIENTS_ABSENT,

    "parameters_changed":
        BLOCK_5_NO_UPDATE_VALID,

    "objective_not_assembled":
        NOTEBOOK_06_FACTUAL_OBJECTIVE_ASSEMBLED,

    "loss_contract_invalid":
        NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_VALIDATED,

    "optimizer_policy_invalid":
        NOTEBOOK_06_FACTUAL_OPTIMIZER_POLICY_VALID,

    "controlled_loss_invalid":
        NOTEBOOK_06_FACTUAL_CONTROLLED_LOSS_VALID,

    "optimisation_not_ready":
        NOTEBOOK_06_FACTUAL_OPTIMISATION_READY,
}


for error_name, condition in (
    block_5_validation_checks.items()
):

    if not condition:

        NOTEBOOK_06_BLOCK_5_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited-operation validation
# =============================================================================

prohibited_block_5_operations = {
    "model_forward_incorrectly_executed":
        NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED,

    "zero_grad_incorrectly_executed":
        NOTEBOOK_06_ZERO_GRAD_EXECUTED,

    "backward_pass_incorrectly_executed":
        NOTEBOOK_06_BACKWARD_PASS_EXECUTED,

    "optimizer_step_incorrectly_executed":
        NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED,

    "parameter_update_incorrectly_executed":
        NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED,

    "factual_training_incorrectly_executed":
        NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED,

    "psychological_training_incorrectly_executed":
        NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "group_path_incorrectly_executed":
        NOTEBOOK_06_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_mechanism_incorrectly_activated":
        NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ACTIVATED,

    "transformative_weights_incorrectly_activated":
        NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ACTIVATED,

    "recurrent_states_incorrectly_activated":
        NOTEBOOK_06_RECURRENT_STATES_ACTIVATED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for error_name, operation_executed in (
    prohibited_block_5_operations.items()
):

    if operation_executed:

        NOTEBOOK_06_BLOCK_5_ERRORS.append(
            error_name
        )


NOTEBOOK_06_BLOCK_5_VALID = (
    len(
        NOTEBOOK_06_BLOCK_5_ERRORS
    )
    == 0
)


if not NOTEBOOK_06_BLOCK_5_VALID:

    raise RuntimeError(
        "Notebook 06 Block 5 factual objective validation failed. "
        f"Errors: {NOTEBOOK_06_BLOCK_5_ERRORS}"
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_06_BLOCK_5_COMPLETE = True


# =============================================================================
# Block 6 handover objects
# =============================================================================

NOTEBOOK_06_FACTUAL_OPTIMIZER = (
    BLOCK_5_FACTUAL_OPTIMIZER
)


NOTEBOOK_06_FACTUAL_OBJECTIVE_WEIGHTS = deepcopy(
    BLOCK_5_OBJECTIVE_WEIGHTS
)


NOTEBOOK_06_FACTUAL_TARGET_TENSOR = (
    BLOCK_5_FACTUAL_TARGETS.detach()
    .clone()
)


NOTEBOOK_06_FACTUAL_MASK_TENSOR = (
    BLOCK_5_FACTUAL_MASKS.detach()
    .clone()
)


NOTEBOOK_06_FACTUAL_INITIAL_OBJECTIVE = float(
    BLOCK_5_TOTAL_FACTUAL_OBJECTIVE
    .detach()
    .cpu()
    .item()
)


NOTEBOOK_06_FACTUAL_INITIAL_FAMILY_LOSSES = {
    target_name:
        float(
            BLOCK_5_FAMILY_LOSSES[
                target_name
            ]
            .detach()
            .cpu()
            .item()
        )

    for target_name
    in BLOCK_5_ACTIVE_DIMENSIONS
}


# =============================================================================
# Human-readable numerical values
# =============================================================================

BLOCK_5_FAMILY_LOSS_VALUES = deepcopy(
    NOTEBOOK_06_FACTUAL_INITIAL_FAMILY_LOSSES
)


BLOCK_5_TOTAL_OBJECTIVE_VALUE = (
    NOTEBOOK_06_FACTUAL_INITIAL_OBJECTIVE
)


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_06_BLOCK_5_SUMMARY = {
    "block":
        NOTEBOOK_06_BLOCK_5,

    "block_name":
        NOTEBOOK_06_BLOCK_5_NAME,

    "version":
        NOTEBOOK_06_BLOCK_5_VERSION,

    "executed_at_utc":
        BLOCK_5_EXECUTED_AT_UTC,

    "active_dimensions":
        list(
            BLOCK_5_ACTIVE_DIMENSIONS
        ),

    "active_indices":
        list(
            BLOCK_5_ACTIVE_INDICES
        ),

    "deferred_dimensions":
        list(
            BLOCK_5_DEFERRED_DIMENSIONS
        ),

    "positive_class_weights":
        deepcopy(
            BLOCK_5_POSITIVE_CLASS_WEIGHTS
        ),

    "weighted_binary_class_counts":
        deepcopy(
            BLOCK_5_WEIGHTED_BINARY_CLASS_COUNTS
        ),

    "positive_class_weight_reproduction":
        deepcopy(
            BLOCK_5_POSITIVE_CLASS_WEIGHT_REPRODUCTION
        ),

    "active_available_counts":
        deepcopy(
            BLOCK_5_ACTIVE_AVAILABLE_COUNTS
        ),

    "expected_active_available_counts":
        deepcopy(
            BLOCK_5_EXPECTED_ACTIVE_AVAILABLE_COUNTS
        ),

    "active_coverage_fractions":
        deepcopy(
            BLOCK_5_ACTIVE_COVERAGE_FRACTIONS
        ),

    "prediction_positive_count":
        BLOCK_5_PREDICTION_POSITIVE_COUNT,

    "prediction_negative_count":
        BLOCK_5_PREDICTION_NEGATIVE_COUNT,

    "prediction_positive_weight":
        BLOCK_5_PREDICTION_POSITIVE_WEIGHT,

    "family_losses":
        deepcopy(
            BLOCK_5_FAMILY_LOSS_VALUES
        ),

    "family_weights":
        deepcopy(
            BLOCK_5_OBJECTIVE_WEIGHTS
        ),

    "total_objective":
        BLOCK_5_TOTAL_OBJECTIVE_VALUE,

    "optimizer_type":
        NOTEBOOK_06_FACTUAL_OPTIMISER_TYPE,

    "learning_rate":
        NOTEBOOK_06_FACTUAL_LEARNING_RATE,

    "weight_decay":
        NOTEBOOK_06_FACTUAL_WEIGHT_DECAY,

    "factual_trainable_parameters":
        BLOCK_5_FACTUAL_TRAINABLE_PARAMETER_COUNT,

    "optimizer_scope_valid":
        BLOCK_5_OPTIMIZER_SCOPE_VALID,

    "zero_grad_executed":
        NOTEBOOK_06_ZERO_GRAD_EXECUTED,

    "backward_pass_executed":
        NOTEBOOK_06_BACKWARD_PASS_EXECUTED,

    "optimizer_step_executed":
        NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED,

    "parameter_update_executed":
        NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED,

    "training_executed":
        NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED,

    "optimisation_ready":
        NOTEBOOK_06_FACTUAL_OPTIMISATION_READY,

    "empirical_validity":
        NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_06_BLOCK_5_VALID,

    "block_complete":
        NOTEBOOK_06_BLOCK_5_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 06, Block 5: "
    "Factual Objective Assembly, Optimiser Policy "
    "and Controlled Loss Validation"
)

print("=" * 72)

print(
    f"Objective-policy version     : "
    f"{NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VERSION}"
)


print("-" * 72)

print(
    "Canonical factual supervision"
)

print(
    f"Target matrix shape          : "
    f"{BLOCK_5_TARGET_MATRIX_SHAPE}"
)

print(
    f"Mask matrix shape            : "
    f"{BLOCK_5_MASK_MATRIX_SHAPE}"
)

print(
    f"Sentence IDs present         : "
    f"{BLOCK_5_TARGET_SENTENCE_IDS_PRESENT}"
)

print(
    f"Sentence IDs unique          : "
    f"{BLOCK_5_TARGET_SENTENCE_IDS_UNIQUE}"
)

print(
    f"Canonical alignment valid    : "
    f"{BLOCK_5_TARGET_SENTENCE_SET_VALID}"
)

print(
    f"Observed values finite       : "
    f"{BLOCK_5_OBSERVED_TARGET_VALUES_FINITE}"
)

print(
    f"Mask-aware supervision       : "
    f"{NOTEBOOK_06_MASK_AWARE_SUPERVISION}"
)

print(
    f"Missing = zero               : "
    f"{NOTEBOOK_06_MISSING_EQUALS_ZERO}"
)

print(
    f"Missing = negative           : "
    f"{NOTEBOOK_06_MISSING_EQUALS_NEGATIVE}"
)

print(
    f"Unavailable enters loss      : "
    f"{NOTEBOOK_06_UNAVAILABLE_ENTERS_LOSS}"
)


print("-" * 72)

print(
    "Active factual objective contract"
)

print(
    f"Active dimensions            : "
    f"{list(BLOCK_5_ACTIVE_DIMENSIONS)}"
)

print(
    f"Active indices               : "
    f"{list(BLOCK_5_ACTIVE_INDICES)}"
)

print(
    f"Deferred dimensions          : "
    f"{list(BLOCK_5_DEFERRED_DIMENSIONS)}"
)

print(
    f"Binary objectives            : "
    f"{list(BLOCK_5_ACTIVE_BINARY_DIMENSIONS)}"
)

print(
    f"Continuous objectives        : "
    f"{list(BLOCK_5_ACTIVE_CONTINUOUS_DIMENSIONS)}"
)

print(
    f"Active coverage reproduced   : "
    f"{BLOCK_5_ACTIVE_COVERAGE_REPRODUCED}"
)

print(
    f"Coverage fractions reproduced: "
    f"{BLOCK_5_ACTIVE_COVERAGE_FRACTIONS_REPRODUCED}"
)


for target_name in BLOCK_5_ACTIVE_DIMENSIONS:

    print(
        f"{target_name:<29}: "
        f"{BLOCK_5_ACTIVE_AVAILABLE_COUNTS[target_name]}"
        f" / "
        f"{NOTEBOOK_06_SENTENCE_COUNT} "
        f"({BLOCK_5_ACTIVE_COVERAGE_FRACTIONS[target_name]:.4f})"
    )


print("-" * 72)

print(
    "Positive-class imbalance policy"
)

print(
    f"Weighted binary dimensions   : "
    f"{list(BLOCK_5_WEIGHTED_BINARY_DIMENSIONS)}"
)

print(
    f"Positive class weights       : "
    f"{BLOCK_5_POSITIVE_CLASS_WEIGHTS}"
)

print(
    f"Weight keys valid            : "
    f"{BLOCK_5_POSITIVE_CLASS_WEIGHT_KEYS_VALID}"
)

print(
    f"Weight values valid          : "
    f"{BLOCK_5_POSITIVE_CLASS_WEIGHT_VALUES_VALID}"
)

print(
    f"All weights reproduced       : "
    f"{BLOCK_5_ALL_POSITIVE_CLASS_WEIGHTS_REPRODUCED}"
)


for target_name in BLOCK_5_WEIGHTED_BINARY_DIMENSIONS:

    class_counts = (
        BLOCK_5_WEIGHTED_BINARY_CLASS_COUNTS[
            target_name
        ]
    )

    print(
        f"{target_name:<29}: "
        f"positive={class_counts['positive']}, "
        f"negative={class_counts['negative']}, "
        f"weight={BLOCK_5_POSITIVE_CLASS_WEIGHTS[target_name]:.6f}, "
        f"reproduced="
        f"{BLOCK_5_POSITIVE_CLASS_WEIGHT_REPRODUCTION[target_name]}"
    )


# Backward-compatible prediction-specific diagnostic.
print(
    f"Prediction positives         : "
    f"{BLOCK_5_PREDICTION_POSITIVE_COUNT}"
)

print(
    f"Prediction negatives         : "
    f"{BLOCK_5_PREDICTION_NEGATIVE_COUNT}"
)

print(
    f"Prediction positive weight   : "
    f"{BLOCK_5_PREDICTION_POSITIVE_WEIGHT:.4f}"
)

print(
    f"Weight reproduced from data  : "
    f"{BLOCK_5_PREDICTION_WEIGHT_REPRODUCED}"
)


print("-" * 72)

print(
    "Controlled factual objective"
)


for target_name in BLOCK_5_ACTIVE_DIMENSIONS:

    if target_name == "factological_weight":

        loss_family = (
            "masked_mean_squared_error"
        )

    else:

        loss_family = (
            "binary_cross_entropy_with_logits"
        )


    print(
        f"{target_name:<29}: "
        f"{BLOCK_5_FAMILY_LOSS_VALUES[target_name]:.8f} "
        f"({loss_family})"
    )


print(
    f"Objective-family weights     : "
    f"{BLOCK_5_OBJECTIVE_WEIGHTS}"
)

print(
    f"Objective weight sum         : "
    f"{BLOCK_5_OBJECTIVE_WEIGHT_SUM:.4f}"
)

print(
    f"Total factual objective      : "
    f"{BLOCK_5_TOTAL_OBJECTIVE_VALUE:.8f}"
)

print(
    f"Total objective finite       : "
    f"{BLOCK_5_TOTAL_OBJECTIVE_FINITE}"
)

print(
    f"Total objective scalar       : "
    f"{BLOCK_5_TOTAL_OBJECTIVE_SCALAR}"
)

print(
    f"Family losses reproduced     : "
    f"{BLOCK_5_ALL_FAMILY_LOSSES_REPRODUCED}"
)

print(
    f"Total objective reproduced   : "
    f"{BLOCK_5_TOTAL_OBJECTIVE_REPRODUCED}"
)

print(
    f"Deferred dimensions excluded : "
    f"{BLOCK_5_DEFERRED_DIMENSIONS_EXCLUDED}"
)


print("-" * 72)

print(
    "Parameter-freezing policy"
)

print(
    f"Backbone frozen              : "
    f"{BLOCK_5_BACKBONE_FROZEN}"
)

print(
    f"Global confluent frozen      : "
    f"{BLOCK_5_GLOBAL_CONFLUENT_FROZEN}"
)

print(
    f"Psychological head frozen    : "
    f"{BLOCK_5_PSYCHOLOGICAL_HEAD_FROZEN}"
)

print(
    f"Factual head trainable       : "
    f"{BLOCK_5_FACTUAL_HEAD_TRAINABLE}"
)

print(
    f"Factual trainable parameters : "
    f"{BLOCK_5_FACTUAL_TRAINABLE_PARAMETER_COUNT}"
)

print(
    f"Expected factual parameters  : "
    f"{BLOCK_5_EXPECTED_FACTUAL_PARAMETER_COUNT}"
)

print(
    f"Parameter scope valid        : "
    f"{BLOCK_5_PARAMETER_SCOPE_VALID}"
)


print("-" * 72)

print(
    "Optimiser policy"
)

print(
    f"Optimiser                    : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMISER_TYPE}"
)

print(
    f"Learning rate                : "
    f"{NOTEBOOK_06_FACTUAL_LEARNING_RATE}"
)

print(
    f"Weight decay                 : "
    f"{NOTEBOOK_06_FACTUAL_WEIGHT_DECAY}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED}"
)

print(
    f"Optimiser parameters         : "
    f"{BLOCK_5_OPTIMIZER_PARAMETER_COUNT}"
)

print(
    f"Optimiser scope exact        : "
    f"{BLOCK_5_OPTIMIZER_SCOPE_EXACT}"
)

print(
    f"Optimiser scope valid        : "
    f"{BLOCK_5_OPTIMIZER_SCOPE_VALID}"
)

print(
    f"Optimiser step state empty   : "
    f"{BLOCK_5_OPTIMIZER_STATE_EMPTY}"
)


print("-" * 72)

print(
    "No-update validation"
)

print(
    f"Backbone unchanged           : "
    f"{BLOCK_5_BACKBONE_UNCHANGED}"
)

print(
    f"Global confluent unchanged   : "
    f"{BLOCK_5_GLOBAL_CONFLUENT_UNCHANGED}"
)

print(
    f"Factual head unchanged       : "
    f"{BLOCK_5_FACTUAL_HEAD_UNCHANGED}"
)

print(
    f"Psychological head unchanged : "
    f"{BLOCK_5_PSYCHOLOGICAL_HEAD_UNCHANGED}"
)

print(
    f"Frozen parameters unchanged  : "
    f"{BLOCK_5_FROZEN_PARAMETERS_UNCHANGED}"
)

print(
    f"All parameters unchanged     : "
    f"{BLOCK_5_ALL_MODEL_PARAMETERS_UNCHANGED}"
)

print(
    f"Factual gradients absent     : "
    f"{BLOCK_5_FACTUAL_GRADIENTS_ABSENT}"
)

print(
    f"No-update validation valid   : "
    f"{BLOCK_5_NO_UPDATE_VALID}"
)


print("-" * 72)

print(
    "Readiness"
)

print(
    f"Objective assembled          : "
    f"{NOTEBOOK_06_FACTUAL_OBJECTIVE_ASSEMBLED}"
)

print(
    f"Loss contract validated      : "
    f"{NOTEBOOK_06_FACTUAL_LOSS_CONTRACT_VALIDATED}"
)

print(
    f"Optimiser policy valid       : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMIZER_POLICY_VALID}"
)

print(
    f"Controlled loss valid        : "
    f"{NOTEBOOK_06_FACTUAL_CONTROLLED_LOSS_VALID}"
)

print(
    f"Factual optimisation ready   : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMISATION_READY}"
)

print(
    f"Ready for controlled training: "
    f"{NOTEBOOK_06_READY_FOR_CONTROLLED_FACTUAL_TRAINING}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Block 5 model forward        : "
    f"{NOTEBOOK_06_FACTUAL_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_06_FACTUAL_LOSS_CALCULATED}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_06_FACTUAL_OPTIMIZER_CREATED}"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_06_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_06_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Factual training executed    : "
    f"{NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{NOTEBOOK_06_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative activated     : "
    f"{NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ACTIVATED}"
)

print(
    f"Transformative weights active: "
    f"{NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ACTIVATED}"
)

print(
    f"Recurrent states activated   : "
    f"{NOTEBOOK_06_RECURRENT_STATES_ACTIVATED}"
)

print(
    f"Held-out evaluation          : "
    f"{NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_06_BLOCK_5_VALID}"
)

print(
    f"Block 5 complete             : "
    f"{NOTEBOOK_06_BLOCK_5_COMPLETE}"
)


print("=" * 72)


print(
    "Notebook 06 factual objective assembly, optimiser policy and "
    "controlled loss validation completed successfully."
)

print(
    "Block 5 consumes the validated ten-dimensional factual target "
    "and mask matrices constructed by Block 2 without reconstructing "
    "or reinterpreting factual supervision."
)

print(
    "Active factual dimensions may remain partially observed; their "
    "per-dimension mask coverage is reproduced from Block 2 rather than "
    "being forced to full sentence coverage."
)

print(
    f"{len(BLOCK_5_ACTIVE_BINARY_DIMENSIONS)} active binary factual "
    "dimensions remain independent mask-aware objectives using "
    "binary cross-entropy with logits."
)

print(
    "Positive-class weighting is inherited dynamically from Block 3 "
    "for the active binary dimensions that require imbalance correction."
)

print(
    "F10 factological_weight remains a separate mask-aware continuous "
    "objective using mean-squared error."
)

print(
    "No sigmoid transformation has been applied manually to the binary "
    "logits or to the continuous F10 prediction."
)

print(
    f"{len(BLOCK_5_DEFERRED_DIMENSIONS)} factual dimension(s) remain "
    "structurally present but outside the current controlled optimisation "
    "objective under the validated Block 3 policy."
)

print(
    f"The {len(BLOCK_5_ACTIVE_DIMENSIONS)} active factual objective "
    "families contribute equally to the controlled total factual objective."
)

print(
    "The AdamW optimiser is scoped exclusively to the 34,442 "
    "trainable factual-head parameters."
)

print(
    "The backbone, mandatory global confluent path and completed "
    "psychological head remain frozen and outside the optimiser."
)

print(
    "The optional group-conditioned path remains unexecuted and "
    "deferred to Notebook 10."
)

print(
    "Transformative mechanisms, Transformative Weights and recurrent "
    "states remain inactive."
)

print(
    "Block 5 performs no new model forward pass, zero-gradient "
    "operation, backward pass, optimiser step or parameter update."
)

print(
    "All relevant model parameters remain unchanged after objective "
    "and optimiser validation."
)

print(
    "The controlled factual losses are computational diagnostics and "
    "do not establish factual prediction quality, generalisation or "
    "empirical validity."
)

print(
    "The next block may proceed to Controlled Factual Training and "
    "Checkpoint Policy."
)

print("=" * 72)

========================================================================
Media AI — Notebook 06, Block 5: Factual Objective Assembly, Optimiser Policy and Controlled Loss Validation
========================================================================
Objective-policy version     : 1.3
------------------------------------------------------------------------
Canonical factual supervision
Target matrix shape          : (54, 10)
Mask matrix shape            : (54, 10)
Sentence IDs present         : True
Sentence IDs unique          : True
Canonical alignment valid    : True
Observed values finite       : True
Mask-aware supervision       : True
Missing = zero               : False
Missing = negative           : False
Unavailable enters loss      : False
------------------------------------------------------------------------
Active factual objective contract
Active dimensions            : ['explicit_claim', 'observation_or_event', 'quantitative_information', 'attribution', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction', 'factological_weight']
Active indices               : [0, 1, 2, 3, 4, 5, 6, 8, 9]
Deferred dimensions          : ['speculation']
Binary objectives            : ['explicit_claim', 'observation_or_event', 'quantitative_information', 'attribution', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction']
Continuous objectives        : ['factological_weight']
Active coverage reproduced   : True
Coverage fractions reproduced: True
explicit_claim               : 54 / 54 (1.0000)
observation_or_event         : 54 / 54 (1.0000)
quantitative_information     : 54 / 54 (1.0000)
attribution                  : 54 / 54 (1.0000)
evidence_reference           : 54 / 54 (1.0000)
certainty_statement          : 54 / 54 (1.0000)
uncertainty_statement        : 54 / 54 (1.0000)
prediction                   : 52 / 54 (0.9630)
factological_weight          : 54 / 54 (1.0000)
------------------------------------------------------------------------
Positive-class imbalance policy
Weighted binary dimensions   : ['explicit_claim', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction']
Positive class weights       : {'explicit_claim': 0.2558139534883721, 'evidence_reference': 3.1538461538461537, 'certainty_statement': 0.17391304347826086, 'uncertainty_statement': 8.0, 'prediction': 25.0}
Weight keys valid            : True
Weight values valid          : True
All weights reproduced       : True
explicit_claim               : positive=43, negative=11, weight=0.255814, reproduced=True
evidence_reference           : positive=13, negative=41, weight=3.153846, reproduced=True
certainty_statement          : positive=46, negative=8, weight=0.173913, reproduced=True
uncertainty_statement        : positive=6, negative=48, weight=8.000000, reproduced=True
prediction                   : positive=2, negative=50, weight=25.000000, reproduced=True
Prediction positives         : 2
Prediction negatives         : 50
Prediction positive weight   : 25.0000
Weight reproduced from data  : True
------------------------------------------------------------------------
Controlled factual objective
explicit_claim               : 0.28797096 (binary_cross_entropy_with_logits)
observation_or_event         : 0.80305123 (binary_cross_entropy_with_logits)
quantitative_information     : 0.87209803 (binary_cross_entropy_with_logits)
attribution                  : 0.88034511 (binary_cross_entropy_with_logits)
evidence_reference           : 0.91512269 (binary_cross_entropy_with_logits)
certainty_statement          : 0.21677481 (binary_cross_entropy_with_logits)
uncertainty_statement        : 1.14133441 (binary_cross_entropy_with_logits)
prediction                   : 1.50916290 (binary_cross_entropy_with_logits)
factological_weight          : 2.73200965 (masked_mean_squared_error)
Objective-family weights     : {'explicit_claim': 0.1111111111111111, 'observation_or_event': 0.1111111111111111, 'quantitative_information': 0.1111111111111111, 'attribution': 0.1111111111111111, 'evidence_reference': 0.1111111111111111, 'certainty_statement': 0.1111111111111111, 'uncertainty_statement': 0.1111111111111111, 'prediction': 0.1111111111111111, 'factological_weight': 0.1111111111111111}
Objective weight sum         : 1.0000
Total factual objective      : 1.03976345
Total objective finite       : True
Total objective scalar       : True
Family losses reproduced     : True
Total objective reproduced   : True
Deferred dimensions excluded : True
------------------------------------------------------------------------
Parameter-freezing policy
Backbone frozen              : True
Global confluent frozen      : True
Psychological head frozen    : True
Factual head trainable       : True
Factual trainable parameters : 34442
Expected factual parameters  : 34442
Parameter scope valid        : True
------------------------------------------------------------------------
Optimiser policy
Optimiser                    : AdamW
Learning rate                : 0.001
Weight decay                 : 0.0001
Optimiser created            : True
Optimiser parameters         : 34442
Optimiser scope exact        : True
Optimiser scope valid        : True
Optimiser step state empty   : True
------------------------------------------------------------------------
No-update validation
Backbone unchanged           : True
Global confluent unchanged   : True
Factual head unchanged       : True
Psychological head unchanged : True
Frozen parameters unchanged  : True
All parameters unchanged     : True
Factual gradients absent     : True
No-update validation valid   : True
------------------------------------------------------------------------
Readiness
Objective assembled          : True
Loss contract validated      : True
Optimiser policy valid       : True
Controlled loss valid        : True
Factual optimisation ready   : True
Ready for controlled training: True
------------------------------------------------------------------------
Execution boundary
Block 5 model forward        : False
Loss calculated              : True
Optimiser created            : True
Zero grad executed           : False
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
Factual training executed    : False
Psychological retraining     : False
Group-conditioned executed   : False
Transformative activated     : False
Transformative weights active: False
Recurrent states activated   : False
Held-out evaluation          : False
Empirical validity           : False
Block valid                  : True
Block 5 complete             : True
========================================================================
Notebook 06 factual objective assembly, optimiser policy and controlled loss validation completed successfully.
Block 5 consumes the validated ten-dimensional factual target and mask matrices constructed by Block 2 without reconstructing or reinterpreting factual supervision.
Active factual dimensions may remain partially observed; their per-dimension mask coverage is reproduced from Block 2 rather than being forced to full sentence coverage.
8 active binary factual dimensions remain independent mask-aware objectives using binary cross-entropy with logits.
Positive-class weighting is inherited dynamically from Block 3 for the active binary dimensions that require imbalance correction.
F10 factological_weight remains a separate mask-aware continuous objective using mean-squared error.
No sigmoid transformation has been applied manually to the binary logits or to the continuous F10 prediction.
1 factual dimension(s) remain structurally present but outside the current controlled optimisation objective under the validated Block 3 policy.
The 9 active factual objective families contribute equally to the controlled total factual objective.
The AdamW optimiser is scoped exclusively to the 34,442 trainable factual-head parameters.
The backbone, mandatory global confluent path and completed psychological head remain frozen and outside the optimiser.
The optional group-conditioned path remains unexecuted and deferred to Notebook 10.
Transformative mechanisms, Transformative Weights and recurrent states remain inactive.
Block 5 performs no new model forward pass, zero-gradient operation, backward pass, optimiser step or parameter update.
All relevant model parameters remain unchanged after objective and optimiser validation.
The controlled factual losses are computational diagnostics and do not establish factual prediction quality, generalisation or empirical validity.
The next block may proceed to Controlled Factual Training and Checkpoint Policy.
========================================================================

## Block 6 — Controlled Factual Training and Checkpoint Policy

This block performs the first controlled parameter update for the Notebook 06 factual path.

Blocks 2–5 established and validated the factual supervision contract, target availability, loss semantics, architectural forward path, parameter-freezing boundary, and optimiser scope. Block 6 now uses those validated contracts to train only the factual representation head.

The training remains deliberately limited in scope. The purpose is to confirm that the factual head can be optimised reproducibly under the established methodological constraints. It does not establish generalisation, empirical validity or production readiness.

### Training scope

The canonical training unit remains the sentence.

The current controlled sample contains one article with sixteen sentences. Sentence order remains preserved and no within-article shuffling is introduced.

The training path is:

- persisted contextual sentence representation;
- frozen backbone interface;
- frozen mandatory global confluent representation;
- trainable factual representation head.

The completed psychological head remains frozen and unchanged.

The optional group-conditioned path remains inactive and deferred to Notebook 10.

No social, transformative, Transformative Weight or recurrent component enters the training path.

### Live factual forward pass

Block 5 used the detached factual output inherited from Block 4 for loss and optimiser validation.

Block 6 must therefore perform a fresh factual-head forward pass from the validated `NOTEBOOK_06_FACTUAL_FORWARD_INPUT`.

This fresh forward pass creates the live autograd graph required for factual-head training.

The upstream global confluent representation remains detached from optimisation. Gradients may propagate through the factual head only.

### Active supervised objectives

The controlled factual training objective retains the five active factual dimensions established in Block 3 and validated in Block 5:

- **F2 — observation_or_event**
- **F3 — quantitative_information**
- **F5 — evidence_reference**
- **F9 — prediction**
- **F10 — factological_weight**

The remaining five dimensions remain structurally present in the ten-dimensional factual output but stay outside the current optimisation objective:

- **F1 — explicit_claim**
- **F4 — attribution**
- **F6 — certainty_statement**
- **F7 — uncertainty_statement**
- **F8 — speculation**

Their exclusion remains dataset-dependent rather than architectural.

### Loss policy

F2, F3 and F5 use independent masked binary-cross-entropy-with-logits objectives.

F9 also uses masked binary cross-entropy with logits and retains the validated positive-class weight of **7.0**.

F10 uses a masked mean-squared-error objective.

The five active family losses remain separately observable throughout training.

The same equal active-family weighting validated in Block 5 is preserved:

- each active factual family contributes weight **0.2**;
- the family weights sum to **1.0**.

Prediction class weighting remains internal to the F9 binary objective and is distinct from objective-family weighting.

### Mask-aware training

The factual target and mask tensors validated in Block 5 remain authoritative.

Only target elements marked available by the factual mask may enter the corresponding family loss.

Unavailable supervision must not be converted into:

- numerical zero;
- negative evidence;
- a synthetic target;
- or an artificial zero-valued loss contribution.

Although the current controlled sample exposes complete supervision for the five active factual dimensions, the masking implementation remains active so that the training contract remains valid for later partially observed datasets.

### Optimisation boundary

The AdamW optimiser validated in Block 5 remains scoped exclusively to the factual representation head.

The current optimiser policy is:

- optimiser: **AdamW**;
- learning rate: **0.001**;
- weight decay: **0.0001**;
- trainable parameters: **34,442 factual-head parameters only**.

The following remain outside the optimiser:

- contextual sentence encoder;
- backbone;
- mandatory global confluent path;
- psychological representation head;
- social representation path;
- optional group-conditioned path;
- transformative mechanisms;
- Transformative Weights;
- recurrent states.

No parameter outside the factual head may change.

### Controlled training loop

The training loop follows the validated optimisation sequence:

1. clear factual-head gradients;
2. perform a fresh factual-head forward pass;
3. calculate the five active masked family losses;
4. combine them using the validated equal family weights;
5. verify that the total objective is finite;
6. execute the backward pass;
7. verify factual-head gradient finiteness;
8. apply gradient clipping where configured;
9. execute the AdamW optimiser step;
10. verify that factual-head parameters changed;
11. verify that all frozen parameters remained unchanged.

The controlled training run should remain small and explicit.

A fixed epoch count may be used because no independent validation article is currently available for validation-based early stopping.

The training objective is monitored after each epoch for computational diagnostics only.

### Gradient control

Gradient behaviour must be validated explicitly before each optimiser step.

The block should verify that:

- all factual-head gradients are finite;
- no frozen parameter receives a trainable gradient;
- no non-finite loss is encountered;
- gradient clipping is applied consistently if enabled.

A maximum gradient norm of **1.0** may be retained for consistency with the controlled psychological training policy used previously.

The observed pre-clipping gradient norm should be recorded.

### Parameter-update validation

The block must snapshot the relevant model states before training.

After controlled training:

- at least one factual-head parameter must have changed;
- the maximum factual-head parameter delta should be recorded;
- all backbone parameters must remain unchanged;
- all mandatory global confluent parameters must remain unchanged;
- all psychological-head parameters must remain unchanged.

The absence of changes in frozen parameter groups is a required training-validity condition.

### Training objective diagnostics

The block should record:

- initial total factual objective;
- final total factual objective;
- objective reduction;
- initial and final F2 loss;
- initial and final F3 loss;
- initial and final F5 loss;
- initial and final F9 loss;
- initial and final F10 loss.

These values are training diagnostics only.

A reduction in training loss does not establish generalisation.

Because the current dataset contains only one article, no validation-loss comparison or held-out model-selection claim is permitted.

### Checkpoint policy

After the controlled factual training run passes all validation checks, the updated factual state should be persisted.

The checkpoint should preserve sufficient state to reproduce the factual training state independently, including:

- complete Media AI model state required for restoration;
- updated factual-head state;
- factual optimiser state;
- active factual dimensions;
- deferred factual dimensions;
- objective-family weights;
- F9 positive-class weight;
- factual target and mask contract references;
- optimiser hyperparameters;
- training epoch count;
- random seed;
- training-policy version;
- methodological execution boundary.

The checkpoint should remain explicitly classified as a:

**controlled experimental factual training checkpoint**

It must not be labelled a validated model checkpoint.

### Persistence and metadata

The factual checkpoint and its metadata should be persisted separately from the existing Notebook 05 psychological checkpoint.

The metadata should record that:

- the factual head was trained;
- the psychological head remained frozen;
- the backbone remained frozen;
- the mandatory global confluent path remained frozen;
- the group-conditioned path was not executed;
- social components were not trained;
- transformative mechanisms were not executed;
- Transformative Weights were not trained;
- recurrent states were not trained;
- no held-out evaluation was performed;
- no empirical-validity claim was made.

The persisted artefacts should be read back after writing so that successful persistence is verified immediately.

### Validation and early-stopping boundary

No independent validation article is currently available.

Therefore:

- validation-based early stopping is not used;
- no best-validation checkpoint is selected;
- no validation metric is reported;
- no test metric is reported.

A fixed controlled epoch count is used only to demonstrate executable optimisation and checkpoint persistence.

Future training with multiple independent articles may introduce article-level train/validation/test separation and validation-based early stopping.

### Reproducibility boundary

This block should establish reproducible controlled factual training state, but full independent checkpoint reload may remain a separate subsequent block.

The checkpoint must nevertheless contain the complete state required for later independent reproduction.

Successful persistence does not itself prove that the checkpoint can be restored exactly; that should be verified explicitly in the following reproducibility block.

### Methodological boundary

Successful Block 6 completion demonstrates that:

- the factual head can be trained under the validated supervision contract;
- gradients remain finite;
- optimiser scope remains factual-head-only;
- frozen parameter groups remain invariant;
- the controlled factual objective can be reduced;
- and the resulting training state can be persisted.

It does **not** demonstrate:

- factual generalisation;
- factual calibration;
- cross-article robustness;
- social-path validity;
- transformative validity;
- recurrent validity;
- group-conditioned validity;
- or overall Media AI empirical validity.

### Block completion criteria

Block 6 is complete only if:

- the factual training loop executes successfully;
- the five active factual objectives remain mask-aware;
- F9 retains the positive-class weight of 7.0;
- equal factual-family weighting remains unchanged;
- all total and family losses remain finite;
- factual-head gradients remain finite;
- gradient clipping policy is respected;
- the AdamW optimiser remains scoped exclusively to the factual head;
- factual-head parameters change;
- backbone parameters remain unchanged;
- global confluent parameters remain unchanged;
- psychological-head parameters remain unchanged;
- no group-conditioned path is executed;
- no transformative mechanism is executed;
- no Transformative Weight is trained;
- no recurrent state is trained;
- no held-out evaluation is performed;
- the controlled experimental factual checkpoint is persisted;
- checkpoint metadata is persisted;
- both persisted artefacts pass immediate read-back validation;
- empirical validity remains explicitly false;
- and all Block 6 validation checks pass.

Successful completion permits the next block to proceed to independent factual checkpoint reload, reproducibility and training-state validation.

In [10]:
# =============================================================================
# Media AI — Notebook 06
# Block 6: Controlled Factual Training and Checkpoint Policy
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json
import math

import numpy as np
import torch
import torch.nn.functional as F

from googleapiclient.http import (
    MediaIoBaseDownload,
    MediaIoBaseUpload,
)


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_06_BLOCK_6 = 6

NOTEBOOK_06_BLOCK_6_NAME = (
    "Controlled Factual Training and Checkpoint Policy"
)

NOTEBOOK_06_BLOCK_6_VERSION = "1.1"

NOTEBOOK_06_FACTUAL_TRAINING_POLICY_VERSION = "1.1"

BLOCK_6_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Training configuration
# =============================================================================

NOTEBOOK_06_FACTUAL_TRAINING_EPOCHS = 10

NOTEBOOK_06_FACTUAL_MAX_GRAD_NORM = 1.0

NOTEBOOK_06_FACTUAL_WITHIN_ARTICLE_SHUFFLE = False

NOTEBOOK_06_FACTUAL_ARTICLE_SEQUENCE_PRESERVED = True

NOTEBOOK_06_FACTUAL_VALIDATION_EARLY_STOPPING = False

NOTEBOOK_06_FACTUAL_CHECKPOINT_FILENAME = (
    "notebook_06_controlled_factual_training_checkpoint.pt"
)

NOTEBOOK_06_FACTUAL_METADATA_FILENAME = (
    "notebook_06_controlled_factual_training_metadata.json"
)

NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE = (
    "controlled_experimental_factual_training_checkpoint"
)


# =============================================================================
# Dependency checks
# =============================================================================

required_block_6_objects = [
    # -------------------------------------------------------------------------
    # Block 2 / canonical factual supervision
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_SENTENCE_COUNT",
    "NOTEBOOK_06_SENTENCE_IDS",
    "NOTEBOOK_06_FACTUAL_DIMENSION_ORDER",

    # -------------------------------------------------------------------------
    # Block 5 completion
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_5_COMPLETE",
    "NOTEBOOK_06_BLOCK_5_VALID",
    "NOTEBOOK_06_READY_FOR_CONTROLLED_FACTUAL_TRAINING",

    # -------------------------------------------------------------------------
    # Block 5 objective and optimiser contract
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_FACTUAL_OPTIMIZER",
    "NOTEBOOK_06_FACTUAL_OBJECTIVE_WEIGHTS",
    "NOTEBOOK_06_FACTUAL_TARGET_TENSOR",
    "NOTEBOOK_06_FACTUAL_MASK_TENSOR",
    "NOTEBOOK_06_FACTUAL_INITIAL_OBJECTIVE",
    "NOTEBOOK_06_FACTUAL_INITIAL_FAMILY_LOSSES",

    # -------------------------------------------------------------------------
    # Block 3 / 5 active objective contract
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS",

    # -------------------------------------------------------------------------
    # Block 4 exported modules
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BACKBONE_FROZEN_MODULE",
    "NOTEBOOK_06_GLOBAL_CONFLUENT_FROZEN_MODULE",
    "NOTEBOOK_06_FACTUAL_HEAD",
    "NOTEBOOK_06_PSYCHOLOGICAL_HEAD_FROZEN_MODULE",
    "NOTEBOOK_06_FACTUAL_FORWARD_INPUT",

    # -------------------------------------------------------------------------
    # Persistence
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_DRIVE_SERVICE",
    "NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID",
]


missing_block_6_objects = [
    object_name
    for object_name in required_block_6_objects
    if object_name not in globals()
]


if missing_block_6_objects:

    raise NameError(
        "Notebook 06 Block 6 prerequisites are not initialised. "
        f"Missing: {missing_block_6_objects}"
    )


if not NOTEBOOK_06_BLOCK_5_COMPLETE:

    raise ValueError(
        "Notebook 06 Block 5 must be complete before Block 6."
    )


if not NOTEBOOK_06_BLOCK_5_VALID:

    raise ValueError(
        "Notebook 06 Block 5 must be valid before Block 6."
    )


if not NOTEBOOK_06_READY_FOR_CONTROLLED_FACTUAL_TRAINING:

    raise ValueError(
        "Notebook 06 is not ready for controlled factual training."
    )


# =============================================================================
# Execution boundary initialisation
# =============================================================================

NOTEBOOK_06_FACTUAL_ZERO_GRAD_EXECUTED = False

NOTEBOOK_06_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ACTIVATED = False

NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ACTIVATED = False

NOTEBOOK_06_RECURRENT_STATES_ACTIVATED = False

NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Resolve modules
# =============================================================================

BLOCK_6_BACKBONE = (
    NOTEBOOK_06_BACKBONE_FROZEN_MODULE
)

BLOCK_6_GLOBAL_CONFLUENT = (
    NOTEBOOK_06_GLOBAL_CONFLUENT_FROZEN_MODULE
)

BLOCK_6_FACTUAL_HEAD = (
    NOTEBOOK_06_FACTUAL_HEAD
)

BLOCK_6_PSYCHOLOGICAL_HEAD = (
    NOTEBOOK_06_PSYCHOLOGICAL_HEAD_FROZEN_MODULE
)

BLOCK_6_FACTUAL_OPTIMIZER = (
    NOTEBOOK_06_FACTUAL_OPTIMIZER
)


# =============================================================================
# Revalidate parameter-freezing boundary
# =============================================================================

BLOCK_6_BACKBONE_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in BLOCK_6_BACKBONE.parameters()
)

BLOCK_6_GLOBAL_CONFLUENT_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in BLOCK_6_GLOBAL_CONFLUENT.parameters()
)

BLOCK_6_PSYCHOLOGICAL_HEAD_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in BLOCK_6_PSYCHOLOGICAL_HEAD.parameters()
)

BLOCK_6_FACTUAL_HEAD_TRAINABLE = all(
    parameter.requires_grad
    for parameter
    in BLOCK_6_FACTUAL_HEAD.parameters()
)


BLOCK_6_FACTUAL_TRAINABLE_PARAMETERS = [
    parameter
    for parameter
    in BLOCK_6_FACTUAL_HEAD.parameters()
    if parameter.requires_grad
]


BLOCK_6_FACTUAL_TRAINABLE_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in BLOCK_6_FACTUAL_TRAINABLE_PARAMETERS
)


BLOCK_6_EXPECTED_FACTUAL_PARAMETER_COUNT = 34442


BLOCK_6_PARAMETER_SCOPE_VALID = all(
    [
        BLOCK_6_BACKBONE_FROZEN,
        BLOCK_6_GLOBAL_CONFLUENT_FROZEN,
        BLOCK_6_PSYCHOLOGICAL_HEAD_FROZEN,
        BLOCK_6_FACTUAL_HEAD_TRAINABLE,
        (
            BLOCK_6_FACTUAL_TRAINABLE_PARAMETER_COUNT
            ==
            BLOCK_6_EXPECTED_FACTUAL_PARAMETER_COUNT
        ),
    ]
)


if not BLOCK_6_PARAMETER_SCOPE_VALID:

    raise RuntimeError(
        "Block 6 parameter-freezing boundary does not reproduce "
        "the validated Block 5 optimiser policy."
    )


# =============================================================================
# Optimiser scope validation
# =============================================================================

BLOCK_6_FACTUAL_PARAMETER_IDS = {
    id(parameter)
    for parameter
    in BLOCK_6_FACTUAL_TRAINABLE_PARAMETERS
}


BLOCK_6_OPTIMIZER_PARAMETER_IDS = {
    id(parameter)

    for parameter_group
    in BLOCK_6_FACTUAL_OPTIMIZER.param_groups

    for parameter
    in parameter_group["params"]
}


BLOCK_6_OPTIMIZER_SCOPE_VALID = (
    BLOCK_6_OPTIMIZER_PARAMETER_IDS
    ==
    BLOCK_6_FACTUAL_PARAMETER_IDS
)


if not BLOCK_6_OPTIMIZER_SCOPE_VALID:

    raise RuntimeError(
        "Block 6 optimiser scope is not exclusively factual-head."
    )


# =============================================================================
# Active objective contract
# =============================================================================
#
# Block 6 inherits the validated factual objective contract from Blocks 3–5.
# No corpus-specific active-dimension list, class weight or objective-family
# weight is redefined here.
# =============================================================================

BLOCK_6_ACTIVE_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS
)

BLOCK_6_DEFERRED_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS
)

BLOCK_6_ACTIVE_BINARY_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS
)

BLOCK_6_ACTIVE_CONTINUOUS_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS
)


BLOCK_6_DIMENSION_ORDER = tuple(
    NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
)

BLOCK_6_DIMENSION_SET = set(
    BLOCK_6_DIMENSION_ORDER
)

BLOCK_6_ACTIVE_DIMENSION_SET = set(
    BLOCK_6_ACTIVE_DIMENSIONS
)

BLOCK_6_DEFERRED_DIMENSION_SET = set(
    BLOCK_6_DEFERRED_DIMENSIONS
)

BLOCK_6_ACTIVE_BINARY_SET = set(
    BLOCK_6_ACTIVE_BINARY_DIMENSIONS
)

BLOCK_6_ACTIVE_CONTINUOUS_SET = set(
    BLOCK_6_ACTIVE_CONTINUOUS_DIMENSIONS
)


BLOCK_6_ACTIVE_DEFERRED_DISJOINT = (
    BLOCK_6_ACTIVE_DIMENSION_SET.isdisjoint(
        BLOCK_6_DEFERRED_DIMENSION_SET
    )
)

BLOCK_6_ACTIVE_DEFERRED_COMPLETE = (
    (
        BLOCK_6_ACTIVE_DIMENSION_SET
        |
        BLOCK_6_DEFERRED_DIMENSION_SET
    )
    ==
    BLOCK_6_DIMENSION_SET
)

BLOCK_6_ACTIVE_TYPES_VALID = all(
    [
        BLOCK_6_ACTIVE_BINARY_SET.issubset(
            BLOCK_6_ACTIVE_DIMENSION_SET
        ),
        BLOCK_6_ACTIVE_CONTINUOUS_SET.issubset(
            BLOCK_6_ACTIVE_DIMENSION_SET
        ),
        BLOCK_6_ACTIVE_BINARY_SET.isdisjoint(
            BLOCK_6_ACTIVE_CONTINUOUS_SET
        ),
        (
            BLOCK_6_ACTIVE_BINARY_SET
            |
            BLOCK_6_ACTIVE_CONTINUOUS_SET
        )
        ==
        BLOCK_6_ACTIVE_DIMENSION_SET,
    ]
)


BLOCK_6_ACTIVE_CONTRACT_VALID = all(
    [
        len(BLOCK_6_ACTIVE_DIMENSIONS) > 0,
        len(BLOCK_6_ACTIVE_DIMENSIONS)
        ==
        len(BLOCK_6_ACTIVE_DIMENSION_SET),
        len(BLOCK_6_DEFERRED_DIMENSIONS)
        ==
        len(BLOCK_6_DEFERRED_DIMENSION_SET),
        BLOCK_6_ACTIVE_DIMENSION_SET.issubset(
            BLOCK_6_DIMENSION_SET
        ),
        BLOCK_6_DEFERRED_DIMENSION_SET.issubset(
            BLOCK_6_DIMENSION_SET
        ),
        BLOCK_6_ACTIVE_DEFERRED_DISJOINT,
        BLOCK_6_ACTIVE_DEFERRED_COMPLETE,
        BLOCK_6_ACTIVE_TYPES_VALID,
    ]
)


if not BLOCK_6_ACTIVE_CONTRACT_VALID:

    raise RuntimeError(
        "Block 6 active factual objective contract does not reproduce "
        "the validated upstream objective policy."
    )


BLOCK_6_DIMENSION_INDEX = {
    dimension_name:
        index
    for index, dimension_name
    in enumerate(
        BLOCK_6_DIMENSION_ORDER
    )
}


# =============================================================================
# Positive-class imbalance contract
# =============================================================================
#
# Positive-class weights are inherited from Block 3 / Block 5.
# Any active binary dimension may be weighted. Binary dimensions absent from
# this mapping use ordinary unweighted BCEWithLogitsLoss.
# =============================================================================

BLOCK_6_POSITIVE_CLASS_WEIGHTS = deepcopy(
    NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS
)

BLOCK_6_WEIGHTED_BINARY_DIMENSIONS = tuple(
    dimension_name
    for dimension_name
    in BLOCK_6_ACTIVE_BINARY_DIMENSIONS
    if dimension_name
    in BLOCK_6_POSITIVE_CLASS_WEIGHTS
)


BLOCK_6_POSITIVE_CLASS_WEIGHT_KEYS_VALID = (
    set(
        BLOCK_6_POSITIVE_CLASS_WEIGHTS.keys()
    ).issubset(
        BLOCK_6_ACTIVE_BINARY_SET
    )
)


BLOCK_6_POSITIVE_CLASS_WEIGHT_VALUES_VALID = all(
    isinstance(
        weight_value,
        (
            int,
            float,
            np.integer,
            np.floating,
        ),
    )
    and
    math.isfinite(
        float(
            weight_value
        )
    )
    and
    float(
        weight_value
    )
    > 0.0

    for weight_value
    in BLOCK_6_POSITIVE_CLASS_WEIGHTS.values()
)


BLOCK_6_POSITIVE_CLASS_WEIGHT_POLICY_VALID = all(
    [
        BLOCK_6_POSITIVE_CLASS_WEIGHT_KEYS_VALID,
        BLOCK_6_POSITIVE_CLASS_WEIGHT_VALUES_VALID,
    ]
)


if not BLOCK_6_POSITIVE_CLASS_WEIGHT_POLICY_VALID:

    raise RuntimeError(
        "Block 6 positive-class weighting does not reproduce "
        "the validated upstream factual objective policy."
    )


# Backward-compatible prediction alias for downstream artefacts.
BLOCK_6_PREDICTION_POS_WEIGHT = (
    float(
        BLOCK_6_POSITIVE_CLASS_WEIGHTS[
            "prediction"
        ]
    )
    if "prediction"
    in BLOCK_6_POSITIVE_CLASS_WEIGHTS
    else None
)


# =============================================================================
# Objective-family weights
# =============================================================================
#
# Block 6 consumes the objective-family weighting constructed and validated
# by Block 5. It does not assume a fixed number of active families.
# =============================================================================

BLOCK_6_OBJECTIVE_WEIGHTS = deepcopy(
    NOTEBOOK_06_FACTUAL_OBJECTIVE_WEIGHTS
)


BLOCK_6_OBJECTIVE_WEIGHT_KEYS_VALID = (
    set(
        BLOCK_6_OBJECTIVE_WEIGHTS.keys()
    )
    ==
    BLOCK_6_ACTIVE_DIMENSION_SET
)


BLOCK_6_OBJECTIVE_WEIGHT_VALUES_VALID = all(
    isinstance(
        weight_value,
        (
            int,
            float,
            np.integer,
            np.floating,
        ),
    )
    and
    math.isfinite(
        float(
            weight_value
        )
    )
    and
    float(
        weight_value
    )
    > 0.0

    for weight_value
    in BLOCK_6_OBJECTIVE_WEIGHTS.values()
)


BLOCK_6_OBJECTIVE_WEIGHT_SUM = float(
    sum(
        BLOCK_6_OBJECTIVE_WEIGHTS.values()
    )
)


BLOCK_6_OBJECTIVE_WEIGHT_SUM_VALID = math.isclose(
    BLOCK_6_OBJECTIVE_WEIGHT_SUM,
    1.0,
    rel_tol=0.0,
    abs_tol=1e-12,
)


BLOCK_6_OBJECTIVE_WEIGHTS_VALID = all(
    [
        BLOCK_6_OBJECTIVE_WEIGHT_KEYS_VALID,
        BLOCK_6_OBJECTIVE_WEIGHT_VALUES_VALID,
        BLOCK_6_OBJECTIVE_WEIGHT_SUM_VALID,
    ]
)


if not BLOCK_6_OBJECTIVE_WEIGHTS_VALID:

    raise RuntimeError(
        "Block 6 objective-family weights do not reproduce "
        "the validated Block 5 contract."
    )


# =============================================================================
# Dynamic training-scope accounting
# =============================================================================
#
# The factual training scope is the complete canonical sentence set supplied
# by Notebook 06. Article and sentence counts are derived from the current
# data and are never hard-coded.
# =============================================================================

def block_6_article_id_from_sentence_id(
    sentence_id,
):
    if not isinstance(
        sentence_id,
        str,
    ) or not sentence_id:

        raise ValueError(
            "Notebook 06 sentence IDs must be non-empty strings."
        )

    if "::" in sentence_id:

        return sentence_id.split(
            "::",
            1,
        )[0]

    return sentence_id


BLOCK_6_TRAINING_SENTENCE_IDS = tuple(
    NOTEBOOK_06_SENTENCE_IDS
)


BLOCK_6_TRAINING_SENTENCE_COUNT = len(
    BLOCK_6_TRAINING_SENTENCE_IDS
)


BLOCK_6_TRAINING_ARTICLE_IDS = tuple(
    dict.fromkeys(
        block_6_article_id_from_sentence_id(
            sentence_id
        )
        for sentence_id
        in BLOCK_6_TRAINING_SENTENCE_IDS
    )
)


BLOCK_6_TRAINING_ARTICLE_COUNT = len(
    BLOCK_6_TRAINING_ARTICLE_IDS
)


BLOCK_6_TRAINING_SCOPE_VALID = all(
    [
        BLOCK_6_TRAINING_SENTENCE_COUNT
        ==
        int(
            NOTEBOOK_06_SENTENCE_COUNT
        ),
        BLOCK_6_TRAINING_ARTICLE_COUNT > 0,
        len(
            set(
                BLOCK_6_TRAINING_SENTENCE_IDS
            )
        )
        ==
        BLOCK_6_TRAINING_SENTENCE_COUNT,
    ]
)


if not BLOCK_6_TRAINING_SCOPE_VALID:

    raise RuntimeError(
        "Block 6 could not derive a valid factual training scope "
        "from the canonical Notebook 06 sentence identities."
    )


# =============================================================================
# Training tensors
# =============================================================================

BLOCK_6_FORWARD_INPUT = (
    NOTEBOOK_06_FACTUAL_FORWARD_INPUT
    .detach()
    .clone()
)


BLOCK_6_FACTUAL_TARGETS = (
    NOTEBOOK_06_FACTUAL_TARGET_TENSOR
    .detach()
    .clone()
)


BLOCK_6_FACTUAL_MASKS = (
    NOTEBOOK_06_FACTUAL_MASK_TENSOR
    .detach()
    .clone()
)


BLOCK_6_EXPECTED_FORWARD_INPUT_SHAPE = (
    NOTEBOOK_06_SENTENCE_COUNT,
    256,
)


BLOCK_6_EXPECTED_TARGET_SHAPE = (
    NOTEBOOK_06_SENTENCE_COUNT,
    10,
)


BLOCK_6_FORWARD_INPUT_SHAPE_VALID = (
    tuple(
        BLOCK_6_FORWARD_INPUT.shape
    )
    ==
    BLOCK_6_EXPECTED_FORWARD_INPUT_SHAPE
)


BLOCK_6_TARGET_SHAPE_VALID = (
    tuple(
        BLOCK_6_FACTUAL_TARGETS.shape
    )
    ==
    BLOCK_6_EXPECTED_TARGET_SHAPE
)


BLOCK_6_MASK_SHAPE_VALID = (
    tuple(
        BLOCK_6_FACTUAL_MASKS.shape
    )
    ==
    BLOCK_6_EXPECTED_TARGET_SHAPE
)


BLOCK_6_FORWARD_INPUT_FINITE = bool(
    torch.isfinite(
        BLOCK_6_FORWARD_INPUT
    ).all().item()
)


if not all(
    [
        BLOCK_6_FORWARD_INPUT_SHAPE_VALID,
        BLOCK_6_TARGET_SHAPE_VALID,
        BLOCK_6_MASK_SHAPE_VALID,
        BLOCK_6_FORWARD_INPUT_FINITE,
    ]
):

    raise RuntimeError(
        "Block 6 training tensors do not reproduce the validated "
        "Block 5 training contract."
    )


# =============================================================================
# Device alignment
# =============================================================================

BLOCK_6_DEVICE = next(
    BLOCK_6_FACTUAL_HEAD.parameters()
).device


BLOCK_6_DTYPE = next(
    BLOCK_6_FACTUAL_HEAD.parameters()
).dtype


BLOCK_6_FORWARD_INPUT = (
    BLOCK_6_FORWARD_INPUT.to(
        device=
            BLOCK_6_DEVICE,
        dtype=
            BLOCK_6_DTYPE,
    )
)


BLOCK_6_FACTUAL_TARGETS = (
    BLOCK_6_FACTUAL_TARGETS.to(
        device=
            BLOCK_6_DEVICE,
        dtype=
            BLOCK_6_DTYPE,
    )
)


BLOCK_6_FACTUAL_MASKS = (
    BLOCK_6_FACTUAL_MASKS.to(
        device=
            BLOCK_6_DEVICE,
    )
)


BLOCK_6_POSITIVE_CLASS_WEIGHT_TENSORS = {
    target_name:
        torch.tensor(
            float(
                weight_value
            ),
            dtype=
                BLOCK_6_DTYPE,
            device=
                BLOCK_6_DEVICE,
        )

    for target_name, weight_value
    in BLOCK_6_POSITIVE_CLASS_WEIGHTS.items()
}


# Backward-compatible prediction tensor alias.
BLOCK_6_PREDICTION_POS_WEIGHT_TENSOR = (
    BLOCK_6_POSITIVE_CLASS_WEIGHT_TENSORS.get(
        "prediction"
    )
)


# =============================================================================
# Objective helpers
# =============================================================================

def block_6_masked_bce_with_logits(
    logits,
    targets,
    mask,
    pos_weight=None,
):

    if mask.dtype != torch.bool:

        mask = mask.bool()


    if int(
        mask.sum()
        .item()
    ) <= 0:

        raise RuntimeError(
            "Active binary factual objective has no observed targets."
        )


    selected_logits = logits[
        mask
    ]

    selected_targets = targets[
        mask
    ]


    return F.binary_cross_entropy_with_logits(
        selected_logits,
        selected_targets,
        pos_weight=
            pos_weight,
        reduction=
            "mean",
    )


def block_6_masked_mse(
    predictions,
    targets,
    mask,
):

    if mask.dtype != torch.bool:

        mask = mask.bool()


    if int(
        mask.sum()
        .item()
    ) <= 0:

        raise RuntimeError(
            "Active continuous factual objective has no observed targets."
        )


    return F.mse_loss(
        predictions[
            mask
        ],
        targets[
            mask
        ],
        reduction=
            "mean",
    )


def block_6_calculate_objective(
    factual_output,
):

    family_losses = {}


    for target_name in BLOCK_6_ACTIVE_BINARY_DIMENSIONS:

        target_index = (
            BLOCK_6_DIMENSION_INDEX[
                target_name
            ]
        )


        positive_weight = (
            BLOCK_6_POSITIVE_CLASS_WEIGHT_TENSORS.get(
                target_name
            )
        )


        family_losses[
            target_name
        ] = block_6_masked_bce_with_logits(
            logits=
                factual_output[
                    :,
                    target_index,
                ],
            targets=
                BLOCK_6_FACTUAL_TARGETS[
                    :,
                    target_index,
                ],
            mask=
                BLOCK_6_FACTUAL_MASKS[
                    :,
                    target_index,
                ],
            pos_weight=
                positive_weight,
        )


    for target_name in BLOCK_6_ACTIVE_CONTINUOUS_DIMENSIONS:

        target_index = (
            BLOCK_6_DIMENSION_INDEX[
                target_name
            ]
        )


        family_losses[
            target_name
        ] = block_6_masked_mse(
            predictions=
                factual_output[
                    :,
                    target_index,
                ],
            targets=
                BLOCK_6_FACTUAL_TARGETS[
                    :,
                    target_index,
                ],
            mask=
                BLOCK_6_FACTUAL_MASKS[
                    :,
                    target_index,
                ],
        )


    if (
        set(
            family_losses.keys()
        )
        !=
        BLOCK_6_ACTIVE_DIMENSION_SET
    ):

        raise RuntimeError(
            "Block 6 objective calculation did not produce exactly "
            "the validated active factual objective families."
        )


    total_objective = sum(
        BLOCK_6_OBJECTIVE_WEIGHTS[
            target_name
        ]
        *
        family_losses[
            target_name
        ]

        for target_name
        in BLOCK_6_ACTIVE_DIMENSIONS
    )


    return (
        total_objective,
        family_losses,
    )


# =============================================================================
# Parameter snapshots before training
# =============================================================================

def block_6_snapshot_module(
    module,
):
    return {
        parameter_name:
            parameter.detach()
            .cpu()
            .clone()

        for parameter_name, parameter
        in module.named_parameters()
    }


BLOCK_6_BACKBONE_STATE_BEFORE = (
    block_6_snapshot_module(
        BLOCK_6_BACKBONE
    )
)

BLOCK_6_GLOBAL_CONFLUENT_STATE_BEFORE = (
    block_6_snapshot_module(
        BLOCK_6_GLOBAL_CONFLUENT
    )
)

BLOCK_6_FACTUAL_STATE_BEFORE = (
    block_6_snapshot_module(
        BLOCK_6_FACTUAL_HEAD
    )
)

BLOCK_6_PSYCHOLOGICAL_STATE_BEFORE = (
    block_6_snapshot_module(
        BLOCK_6_PSYCHOLOGICAL_HEAD
    )
)


# =============================================================================
# Initial deterministic objective reproduction
# =============================================================================
#
# Block 5 validates its initial objective from the no-update Block 4 state.
# Block 6 therefore reproduces that objective in evaluation mode before
# enabling training behaviour.
# =============================================================================

BLOCK_6_FACTUAL_HEAD.eval()


with torch.no_grad():

    BLOCK_6_INITIAL_OUTPUT = (
        BLOCK_6_FACTUAL_HEAD(
            BLOCK_6_FORWARD_INPUT
        )
    )


    (
        BLOCK_6_INITIAL_OBJECTIVE_TENSOR,
        BLOCK_6_INITIAL_FAMILY_LOSSES_TENSOR,
    ) = block_6_calculate_objective(
        BLOCK_6_INITIAL_OUTPUT
    )


BLOCK_6_INITIAL_OBJECTIVE_FINITE = bool(
    torch.isfinite(
        BLOCK_6_INITIAL_OBJECTIVE_TENSOR
    ).item()
)


if not BLOCK_6_INITIAL_OBJECTIVE_FINITE:

    raise RuntimeError(
        "Initial Block 6 factual objective is non-finite."
    )


BLOCK_6_INITIAL_OBJECTIVE = float(
    BLOCK_6_INITIAL_OBJECTIVE_TENSOR
    .detach()
    .cpu()
    .item()
)


BLOCK_6_INITIAL_FAMILY_LOSSES = {
    target_name:
        float(
            BLOCK_6_INITIAL_FAMILY_LOSSES_TENSOR[
                target_name
            ]
            .detach()
            .cpu()
            .item()
        )

    for target_name
    in BLOCK_6_ACTIVE_DIMENSIONS
}


# =============================================================================
# Reproduce Block 5 initial objective
# =============================================================================

BLOCK_6_BLOCK_5_OBJECTIVE_REPRODUCED = math.isclose(
    BLOCK_6_INITIAL_OBJECTIVE,
    float(
        NOTEBOOK_06_FACTUAL_INITIAL_OBJECTIVE
    ),
    rel_tol=0.0,
    abs_tol=1e-6,
)


BLOCK_6_BLOCK_5_FAMILY_LOSSES_REPRODUCED = all(
    math.isclose(
        BLOCK_6_INITIAL_FAMILY_LOSSES[
            target_name
        ],
        float(
            NOTEBOOK_06_FACTUAL_INITIAL_FAMILY_LOSSES[
                target_name
            ]
        ),
        rel_tol=0.0,
        abs_tol=1e-6,
    )

    for target_name
    in BLOCK_6_ACTIVE_DIMENSIONS
)


if not all(
    [
        BLOCK_6_BLOCK_5_OBJECTIVE_REPRODUCED,
        BLOCK_6_BLOCK_5_FAMILY_LOSSES_REPRODUCED,
    ]
):

    raise RuntimeError(
        "Block 6 deterministic forward pass does not reproduce "
        "the Block 5 controlled factual objective."
    )


BLOCK_6_FACTUAL_HEAD.train()


# =============================================================================
# Controlled training history
# =============================================================================

BLOCK_6_TRAINING_HISTORY = []

BLOCK_6_NONFINITE_LOSS_DETECTED = False

BLOCK_6_FINITE_GRADIENTS = True

BLOCK_6_MAX_OBSERVED_PRECLIP_GRAD_NORM = 0.0


# =============================================================================
# Controlled factual training loop
# =============================================================================
#
# The complete canonical factual training scope is used on every epoch.
#
# Article and sentence counts are derived from the current Notebook 06 data.
# Sentence order is preserved; no corpus-size assumption is hard-coded.
# =============================================================================

for epoch_index in range(
    NOTEBOOK_06_FACTUAL_TRAINING_EPOCHS
):

    # -------------------------------------------------------------------------
    # Clear factual-head gradients
    # -------------------------------------------------------------------------

    BLOCK_6_FACTUAL_OPTIMIZER.zero_grad(
        set_to_none=True
    )

    NOTEBOOK_06_FACTUAL_ZERO_GRAD_EXECUTED = True


    # -------------------------------------------------------------------------
    # Fresh factual-head forward pass
    # -------------------------------------------------------------------------

    factual_output = (
        BLOCK_6_FACTUAL_HEAD(
            BLOCK_6_FORWARD_INPUT
        )
    )


    # -------------------------------------------------------------------------
    # Calculate active masked objectives
    # -------------------------------------------------------------------------

    (
        total_objective,
        family_losses,
    ) = block_6_calculate_objective(
        factual_output
    )


    if not bool(
        torch.isfinite(
            total_objective
        ).item()
    ):

        BLOCK_6_NONFINITE_LOSS_DETECTED = True

        raise RuntimeError(
            f"Non-finite factual objective detected "
            f"at epoch {epoch_index + 1}."
        )


    # -------------------------------------------------------------------------
    # Backward pass
    # -------------------------------------------------------------------------

    total_objective.backward()

    NOTEBOOK_06_BACKWARD_PASS_EXECUTED = True


    # -------------------------------------------------------------------------
    # Gradient finiteness
    # -------------------------------------------------------------------------

    epoch_gradients_finite = True


    for parameter in BLOCK_6_FACTUAL_TRAINABLE_PARAMETERS:

        if parameter.grad is None:

            continue


        if not bool(
            torch.isfinite(
                parameter.grad
            ).all().item()
        ):

            epoch_gradients_finite = False

            break


    if not epoch_gradients_finite:

        BLOCK_6_FINITE_GRADIENTS = False

        raise RuntimeError(
            f"Non-finite factual-head gradient detected "
            f"at epoch {epoch_index + 1}."
        )


    # -------------------------------------------------------------------------
    # Gradient norm before clipping
    # -------------------------------------------------------------------------

    grad_norm_squared = 0.0


    for parameter in BLOCK_6_FACTUAL_TRAINABLE_PARAMETERS:

        if parameter.grad is None:

            continue


        parameter_grad_norm = float(
            parameter.grad.detach()
            .norm(
                2
            )
            .cpu()
            .item()
        )


        grad_norm_squared += (
            parameter_grad_norm
            ** 2
        )


    preclip_grad_norm = math.sqrt(
        grad_norm_squared
    )


    BLOCK_6_MAX_OBSERVED_PRECLIP_GRAD_NORM = max(
        BLOCK_6_MAX_OBSERVED_PRECLIP_GRAD_NORM,
        preclip_grad_norm,
    )


    # -------------------------------------------------------------------------
    # Gradient clipping
    # -------------------------------------------------------------------------

    torch.nn.utils.clip_grad_norm_(
        BLOCK_6_FACTUAL_TRAINABLE_PARAMETERS,
        max_norm=
            NOTEBOOK_06_FACTUAL_MAX_GRAD_NORM,
    )


    # -------------------------------------------------------------------------
    # Optimiser step
    # -------------------------------------------------------------------------

    BLOCK_6_FACTUAL_OPTIMIZER.step()

    NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED = True

    NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED = True


    # -------------------------------------------------------------------------
    # Training history
    # -------------------------------------------------------------------------

    BLOCK_6_TRAINING_HISTORY.append(
        {
            "epoch":
                epoch_index
                + 1,

            "total_objective":
                float(
                    total_objective
                    .detach()
                    .cpu()
                    .item()
                ),

            "family_losses":
                {
                    target_name:
                        float(
                            family_losses[
                                target_name
                            ]
                            .detach()
                            .cpu()
                            .item()
                        )

                    for target_name
                    in BLOCK_6_ACTIVE_DIMENSIONS
                },

            "preclip_gradient_norm":
                float(
                    preclip_grad_norm
                ),
        }
    )


NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED = True


# =============================================================================
# Final controlled factual objective
# =============================================================================

BLOCK_6_FACTUAL_HEAD.eval()


with torch.no_grad():

    BLOCK_6_FINAL_OUTPUT = (
        BLOCK_6_FACTUAL_HEAD(
            BLOCK_6_FORWARD_INPUT
        )
    )


    (
        BLOCK_6_FINAL_OBJECTIVE_TENSOR,
        BLOCK_6_FINAL_FAMILY_LOSSES_TENSOR,
    ) = block_6_calculate_objective(
        BLOCK_6_FINAL_OUTPUT
    )


BLOCK_6_FINAL_OBJECTIVE_FINITE = bool(
    torch.isfinite(
        BLOCK_6_FINAL_OBJECTIVE_TENSOR
    ).item()
)


if not BLOCK_6_FINAL_OBJECTIVE_FINITE:

    raise RuntimeError(
        "Final factual objective is non-finite."
    )


BLOCK_6_FINAL_OBJECTIVE = float(
    BLOCK_6_FINAL_OBJECTIVE_TENSOR
    .detach()
    .cpu()
    .item()
)


BLOCK_6_FINAL_FAMILY_LOSSES = {
    target_name:
        float(
            BLOCK_6_FINAL_FAMILY_LOSSES_TENSOR[
                target_name
            ]
            .detach()
            .cpu()
            .item()
        )

    for target_name
    in BLOCK_6_ACTIVE_DIMENSIONS
}


BLOCK_6_OBJECTIVE_REDUCTION = (
    BLOCK_6_INITIAL_OBJECTIVE
    -
    BLOCK_6_FINAL_OBJECTIVE
)


# =============================================================================
# Parameter-update validation
# =============================================================================

BLOCK_6_BACKBONE_STATE_AFTER = (
    block_6_snapshot_module(
        BLOCK_6_BACKBONE
    )
)

BLOCK_6_GLOBAL_CONFLUENT_STATE_AFTER = (
    block_6_snapshot_module(
        BLOCK_6_GLOBAL_CONFLUENT
    )
)

BLOCK_6_FACTUAL_STATE_AFTER = (
    block_6_snapshot_module(
        BLOCK_6_FACTUAL_HEAD
    )
)

BLOCK_6_PSYCHOLOGICAL_STATE_AFTER = (
    block_6_snapshot_module(
        BLOCK_6_PSYCHOLOGICAL_HEAD
    )
)


def block_6_states_equal(
    before_state,
    after_state,
):

    if set(
        before_state.keys()
    ) != set(
        after_state.keys()
    ):

        return False


    return all(
        torch.equal(
            before_state[
                parameter_name
            ],
            after_state[
                parameter_name
            ],
        )

        for parameter_name
        in before_state
    )


BLOCK_6_BACKBONE_UNCHANGED = (
    block_6_states_equal(
        BLOCK_6_BACKBONE_STATE_BEFORE,
        BLOCK_6_BACKBONE_STATE_AFTER,
    )
)


BLOCK_6_GLOBAL_CONFLUENT_UNCHANGED = (
    block_6_states_equal(
        BLOCK_6_GLOBAL_CONFLUENT_STATE_BEFORE,
        BLOCK_6_GLOBAL_CONFLUENT_STATE_AFTER,
    )
)


BLOCK_6_PSYCHOLOGICAL_HEAD_UNCHANGED = (
    block_6_states_equal(
        BLOCK_6_PSYCHOLOGICAL_STATE_BEFORE,
        BLOCK_6_PSYCHOLOGICAL_STATE_AFTER,
    )
)


BLOCK_6_FACTUAL_HEAD_CHANGED = (
    not block_6_states_equal(
        BLOCK_6_FACTUAL_STATE_BEFORE,
        BLOCK_6_FACTUAL_STATE_AFTER,
    )
)


# =============================================================================
# Maximum factual parameter delta
# =============================================================================

BLOCK_6_MAX_PARAMETER_DELTA = 0.0


for parameter_name in BLOCK_6_FACTUAL_STATE_BEFORE:

    parameter_delta = (
        BLOCK_6_FACTUAL_STATE_AFTER[
            parameter_name
        ]
        -
        BLOCK_6_FACTUAL_STATE_BEFORE[
            parameter_name
        ]
    )


    maximum_delta = float(
        parameter_delta.abs()
        .max()
        .item()
    )


    BLOCK_6_MAX_PARAMETER_DELTA = max(
        BLOCK_6_MAX_PARAMETER_DELTA,
        maximum_delta,
    )


BLOCK_6_FROZEN_PARAMETERS_UNCHANGED = all(
    [
        BLOCK_6_BACKBONE_UNCHANGED,
        BLOCK_6_GLOBAL_CONFLUENT_UNCHANGED,
        BLOCK_6_PSYCHOLOGICAL_HEAD_UNCHANGED,
    ]
)


BLOCK_6_PARAMETER_UPDATE_VALID = all(
    [
        BLOCK_6_FACTUAL_HEAD_CHANGED,
        BLOCK_6_FROZEN_PARAMETERS_UNCHANGED,
        BLOCK_6_MAX_PARAMETER_DELTA > 0.0,
    ]
)


if not BLOCK_6_PARAMETER_UPDATE_VALID:

    raise RuntimeError(
        "Block 6 parameter-update boundary is invalid."
    )


# =============================================================================
# Training-gradient validation
# =============================================================================

BLOCK_6_GRADIENT_CONTROL_VALID = all(
    [
        BLOCK_6_FINITE_GRADIENTS,
        not BLOCK_6_NONFINITE_LOSS_DETECTED,
        math.isfinite(
            BLOCK_6_MAX_OBSERVED_PRECLIP_GRAD_NORM
        ),
        NOTEBOOK_06_FACTUAL_MAX_GRAD_NORM > 0.0,
    ]
)


if not BLOCK_6_GRADIENT_CONTROL_VALID:

    raise RuntimeError(
        "Block 6 gradient-control validation failed."
    )


# =============================================================================
# Training-policy validation
# =============================================================================

BLOCK_6_TRAINING_POLICY_VALID = all(
    [
        NOTEBOOK_06_FACTUAL_TRAINING_EPOCHS > 0,
        not NOTEBOOK_06_FACTUAL_WITHIN_ARTICLE_SHUFFLE,
        NOTEBOOK_06_FACTUAL_ARTICLE_SEQUENCE_PRESERVED,
        not NOTEBOOK_06_FACTUAL_VALIDATION_EARLY_STOPPING,
        BLOCK_6_ACTIVE_CONTRACT_VALID,
        BLOCK_6_POSITIVE_CLASS_WEIGHT_POLICY_VALID,
        BLOCK_6_OBJECTIVE_WEIGHTS_VALID,
        BLOCK_6_TRAINING_SCOPE_VALID,
    ]
)


if not BLOCK_6_TRAINING_POLICY_VALID:

    raise RuntimeError(
        "Block 6 controlled factual training policy is invalid."
    )


# =============================================================================
# Checkpoint construction
# =============================================================================
#
# Persist the complete state required to resume and reproduce the factual
# training state independently.
# =============================================================================

NOTEBOOK_06_FACTUAL_CHECKPOINT = {
    "checkpoint_type":
        NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE,

    "checkpoint_version":
        NOTEBOOK_06_BLOCK_6_VERSION,

    "created_at_utc":
        BLOCK_6_EXECUTED_AT_UTC,

    "notebook":
        "06_factual_path",

    "block":
        NOTEBOOK_06_BLOCK_6,

    "random_seed":
        42,

    "training_policy_version":
        NOTEBOOK_06_FACTUAL_TRAINING_POLICY_VERSION,

    "training_epoch_count":
        NOTEBOOK_06_FACTUAL_TRAINING_EPOCHS,

    "within_article_shuffle":
        NOTEBOOK_06_FACTUAL_WITHIN_ARTICLE_SHUFFLE,

    "article_sequence_preserved":
        NOTEBOOK_06_FACTUAL_ARTICLE_SEQUENCE_PRESERVED,

    "training_article_count":
        int(
            BLOCK_6_TRAINING_ARTICLE_COUNT
        ),

    "training_sentence_count":
        int(
            BLOCK_6_TRAINING_SENTENCE_COUNT
        ),

    "training_article_ids":
        list(
            BLOCK_6_TRAINING_ARTICLE_IDS
        ),

    "active_dimensions":
        list(
            BLOCK_6_ACTIVE_DIMENSIONS
        ),

    "deferred_dimensions":
        list(
            BLOCK_6_DEFERRED_DIMENSIONS
        ),

    "objective_weights":
        deepcopy(
            BLOCK_6_OBJECTIVE_WEIGHTS
        ),

    "positive_class_weights":
        deepcopy(
            BLOCK_6_POSITIVE_CLASS_WEIGHTS
        ),

    "weighted_binary_dimensions":
        list(
            BLOCK_6_WEIGHTED_BINARY_DIMENSIONS
        ),

    "prediction_positive_weight":
        (
            float(
                BLOCK_6_PREDICTION_POS_WEIGHT
            )
            if BLOCK_6_PREDICTION_POS_WEIGHT is not None
            else None
        ),

    "optimizer_type":
        "AdamW",

    "learning_rate":
        float(
            NOTEBOOK_06_FACTUAL_LEARNING_RATE
        ),

    "weight_decay":
        float(
            NOTEBOOK_06_FACTUAL_WEIGHT_DECAY
        ),

    "maximum_gradient_norm":
        float(
            NOTEBOOK_06_FACTUAL_MAX_GRAD_NORM
        ),

    "initial_objective":
        float(
            BLOCK_6_INITIAL_OBJECTIVE
        ),

    "final_objective":
        float(
            BLOCK_6_FINAL_OBJECTIVE
        ),

    "initial_family_losses":
        deepcopy(
            BLOCK_6_INITIAL_FAMILY_LOSSES
        ),

    "final_family_losses":
        deepcopy(
            BLOCK_6_FINAL_FAMILY_LOSSES
        ),

    "training_history":
        deepcopy(
            BLOCK_6_TRAINING_HISTORY
        ),

    # -------------------------------------------------------------------------
    # Separate architectural module states
    # -------------------------------------------------------------------------
    "backbone_state_dict":
        deepcopy(
            BLOCK_6_BACKBONE.state_dict()
        ),

    "global_confluent_state_dict":
        deepcopy(
            BLOCK_6_GLOBAL_CONFLUENT.state_dict()
        ),

    "factual_head_state_dict":
        deepcopy(
            BLOCK_6_FACTUAL_HEAD.state_dict()
        ),

    "psychological_head_state_dict":
        deepcopy(
            BLOCK_6_PSYCHOLOGICAL_HEAD.state_dict()
        ),

    # -------------------------------------------------------------------------
    # Optimiser
    # -------------------------------------------------------------------------
    "optimizer_state_dict":
        deepcopy(
            BLOCK_6_FACTUAL_OPTIMIZER.state_dict()
        ),

    # -------------------------------------------------------------------------
    # Methodological boundary
    # -------------------------------------------------------------------------
    "methodological_boundary":
        {
            "factual_head_trained":
                True,

            "psychological_head_trained":
                False,

            "backbone_trained":
                False,

            "global_confluent_trained":
                False,

            "group_conditioned_path_executed":
                False,

            "social_path_trained":
                False,

            "transformative_mechanism_executed":
                False,

            "transformative_weights_trained":
                False,

            "recurrent_states_trained":
                False,

            "held_out_evaluation_executed":
                False,

            "validated_model_checkpoint":
                False,

            "empirical_validity":
                False,
        },
}


# =============================================================================
# Local checkpoint persistence
# =============================================================================

torch.save(
    NOTEBOOK_06_FACTUAL_CHECKPOINT,
    NOTEBOOK_06_FACTUAL_CHECKPOINT_FILENAME,
)


BLOCK_6_LOCAL_CHECKPOINT_CREATED = True


# =============================================================================
# Metadata construction
# =============================================================================

NOTEBOOK_06_FACTUAL_TRAINING_METADATA = {
    "artefact_type":
        "media_ai_controlled_factual_training_metadata",

    "artefact_version":
        NOTEBOOK_06_BLOCK_6_VERSION,

    "created_at_utc":
        BLOCK_6_EXECUTED_AT_UTC,

    "checkpoint_type":
        NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE,

    "checkpoint_filename":
        NOTEBOOK_06_FACTUAL_CHECKPOINT_FILENAME,

    "training_policy_version":
        NOTEBOOK_06_FACTUAL_TRAINING_POLICY_VERSION,

    "training_scope":
        {
            "articles":
                int(
                    BLOCK_6_TRAINING_ARTICLE_COUNT
                ),

            "sentences":
                int(
                    BLOCK_6_TRAINING_SENTENCE_COUNT
                ),

            "article_ids":
                list(
                    BLOCK_6_TRAINING_ARTICLE_IDS
                ),

            "validation_sentences":
                0,

            "test_sentences":
                0,

            "epochs":
                int(
                    NOTEBOOK_06_FACTUAL_TRAINING_EPOCHS
                ),

            "within_article_shuffle":
                False,

            "article_sequence_preserved":
                True,
        },

    "supervised_objectives":
        {
            "active_dimensions":
                list(
                    BLOCK_6_ACTIVE_DIMENSIONS
                ),

            "deferred_dimensions":
                list(
                    BLOCK_6_DEFERRED_DIMENSIONS
                ),

            "objective_weights":
                deepcopy(
                    BLOCK_6_OBJECTIVE_WEIGHTS
                ),

            "positive_class_weights":
                deepcopy(
                    BLOCK_6_POSITIVE_CLASS_WEIGHTS
                ),

            "weighted_binary_dimensions":
                list(
                    BLOCK_6_WEIGHTED_BINARY_DIMENSIONS
                ),

            "prediction_positive_weight":
                (
                    float(
                        BLOCK_6_PREDICTION_POS_WEIGHT
                    )
                    if BLOCK_6_PREDICTION_POS_WEIGHT is not None
                    else None
                ),

            "mask_aware":
                True,
        },

    "optimisation":
        {
            "optimizer":
                "AdamW",

            "learning_rate":
                float(
                    NOTEBOOK_06_FACTUAL_LEARNING_RATE
                ),

            "weight_decay":
                float(
                    NOTEBOOK_06_FACTUAL_WEIGHT_DECAY
                ),

            "maximum_gradient_norm":
                float(
                    NOTEBOOK_06_FACTUAL_MAX_GRAD_NORM
                ),

            "trainable_parameters":
                int(
                    BLOCK_6_FACTUAL_TRAINABLE_PARAMETER_COUNT
                ),

            "only_factual_head":
                True,
        },

    "training_objective":
        {
            "initial_total":
                float(
                    BLOCK_6_INITIAL_OBJECTIVE
                ),

            "final_total":
                float(
                    BLOCK_6_FINAL_OBJECTIVE
                ),

            "reduction":
                float(
                    BLOCK_6_OBJECTIVE_REDUCTION
                ),

            "initial_family_losses":
                deepcopy(
                    BLOCK_6_INITIAL_FAMILY_LOSSES
                ),

            "final_family_losses":
                deepcopy(
                    BLOCK_6_FINAL_FAMILY_LOSSES
                ),
        },

    "gradient_control":
        {
            "maximum_gradient_norm":
                float(
                    NOTEBOOK_06_FACTUAL_MAX_GRAD_NORM
                ),

            "maximum_observed_preclip_norm":
                float(
                    BLOCK_6_MAX_OBSERVED_PRECLIP_GRAD_NORM
                ),

            "finite_gradients":
                bool(
                    BLOCK_6_FINITE_GRADIENTS
                ),

            "nonfinite_loss_detected":
                bool(
                    BLOCK_6_NONFINITE_LOSS_DETECTED
                ),
        },

    "parameter_update":
        {
            "factual_head_changed":
                bool(
                    BLOCK_6_FACTUAL_HEAD_CHANGED
                ),

            "maximum_parameter_delta":
                float(
                    BLOCK_6_MAX_PARAMETER_DELTA
                ),

            "backbone_unchanged":
                bool(
                    BLOCK_6_BACKBONE_UNCHANGED
                ),

            "global_confluent_unchanged":
                bool(
                    BLOCK_6_GLOBAL_CONFLUENT_UNCHANGED
                ),

            "psychological_head_unchanged":
                bool(
                    BLOCK_6_PSYCHOLOGICAL_HEAD_UNCHANGED
                ),
        },

    "methodological_boundary":
        {
            "controlled_experimental_checkpoint":
                True,

            "validated_model_checkpoint":
                False,

            "validation_early_stopping":
                False,

            "held_out_evaluation":
                False,

            "group_conditioned_executed":
                False,

            "social_path_trained":
                False,

            "transformative_executed":
                False,

            "transformative_weights_trained":
                False,

            "recurrent_states_trained":
                False,

            "empirical_validity":
                False,
        },
}


NOTEBOOK_06_FACTUAL_METADATA_JSON = json.dumps(
    NOTEBOOK_06_FACTUAL_TRAINING_METADATA,
    indent=2,
    ensure_ascii=False,
)


with open(
    NOTEBOOK_06_FACTUAL_METADATA_FILENAME,
    "w",
    encoding="utf-8",
) as metadata_file:

    metadata_file.write(
        NOTEBOOK_06_FACTUAL_METADATA_JSON
    )


BLOCK_6_LOCAL_METADATA_CREATED = True


# =============================================================================
# Resolve persistent Drive parent
# =============================================================================

BLOCK_6_HANDOVER_DRIVE_METADATA = (
    NOTEBOOK_06_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID,
        fields=
            "id,name,parents",
    )
    .execute()
)


BLOCK_6_PARENT_IDS = (
    BLOCK_6_HANDOVER_DRIVE_METADATA.get(
        "parents",
        [],
    )
)


# =============================================================================
# Generic Drive persistence helper
# =============================================================================

def block_6_persist_bytes_to_drive(
    drive_service,
    filename,
    raw_bytes,
    mimetype,
    parent_ids=None,
):

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )


    search_response = (
        drive_service.files()
        .list(
            q=(
                f"name = '{escaped_filename}' "
                "and trashed = false"
            ),
            spaces=
                "drive",
            fields=
                "files(id,name,modifiedTime,parents)",
            orderBy=
                "modifiedTime desc",
            pageSize=
                20,
        )
        .execute()
    )


    matching_files = search_response.get(
        "files",
        [],
    )


    media = MediaIoBaseUpload(
        io.BytesIO(
            raw_bytes
        ),
        mimetype=
            mimetype,
        resumable=
            False,
    )


    if matching_files:

        drive_file = (
            drive_service.files()
            .update(
                fileId=
                    matching_files[
                        0
                    ][
                        "id"
                    ],
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )

        operation = "updated"


    else:

        metadata = {
            "name":
                filename
        }


        if parent_ids:

            metadata[
                "parents"
            ] = parent_ids


        drive_file = (
            drive_service.files()
            .create(
                body=
                    metadata,
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )

        operation = "created"


    return (
        drive_file,
        operation,
    )


# =============================================================================
# Persist checkpoint to Drive
# =============================================================================

BLOCK_6_CHECKPOINT_BUFFER = io.BytesIO()


torch.save(
    NOTEBOOK_06_FACTUAL_CHECKPOINT,
    BLOCK_6_CHECKPOINT_BUFFER,
)


BLOCK_6_CHECKPOINT_BYTES = (
    BLOCK_6_CHECKPOINT_BUFFER.getvalue()
)


(
    NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE,
    NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_OPERATION,
) = block_6_persist_bytes_to_drive(
    drive_service=
        NOTEBOOK_06_DRIVE_SERVICE,
    filename=
        NOTEBOOK_06_FACTUAL_CHECKPOINT_FILENAME,
    raw_bytes=
        BLOCK_6_CHECKPOINT_BYTES,
    mimetype=
        "application/octet-stream",
    parent_ids=
        BLOCK_6_PARENT_IDS,
)


NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE_ID = (
    NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE.get(
        "id"
    )
)


BLOCK_6_CHECKPOINT_DRIVE_PERSISTED = bool(
    NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE_ID
)


if not BLOCK_6_CHECKPOINT_DRIVE_PERSISTED:

    raise RuntimeError(
        "Block 6 factual checkpoint was not persisted to Drive."
    )


# =============================================================================
# Persist metadata to Drive
# =============================================================================

(
    NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE,
    NOTEBOOK_06_FACTUAL_METADATA_DRIVE_OPERATION,
) = block_6_persist_bytes_to_drive(
    drive_service=
        NOTEBOOK_06_DRIVE_SERVICE,
    filename=
        NOTEBOOK_06_FACTUAL_METADATA_FILENAME,
    raw_bytes=
        NOTEBOOK_06_FACTUAL_METADATA_JSON.encode(
            "utf-8"
        ),
    mimetype=
        "application/json",
    parent_ids=
        BLOCK_6_PARENT_IDS,
)


NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE_ID = (
    NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE.get(
        "id"
    )
)


BLOCK_6_METADATA_DRIVE_PERSISTED = bool(
    NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE_ID
)


if not BLOCK_6_METADATA_DRIVE_PERSISTED:

    raise RuntimeError(
        "Block 6 factual metadata was not persisted to Drive."
    )


# =============================================================================
# Drive read-back helper
# =============================================================================

def block_6_download_drive_bytes(
    drive_service,
    file_id,
):

    request = (
        drive_service.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Checkpoint read-back validation
# =============================================================================

BLOCK_6_RELOADED_CHECKPOINT_BYTES = (
    block_6_download_drive_bytes(
        NOTEBOOK_06_DRIVE_SERVICE,
        NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE_ID,
    )
)


BLOCK_6_RELOADED_CHECKPOINT_BUFFER = io.BytesIO(
    BLOCK_6_RELOADED_CHECKPOINT_BYTES
)


try:

    BLOCK_6_RELOADED_CHECKPOINT = torch.load(
        BLOCK_6_RELOADED_CHECKPOINT_BUFFER,
        map_location=
            "cpu",
        weights_only=
            False,
    )


except TypeError:

    BLOCK_6_RELOADED_CHECKPOINT_BUFFER.seek(
        0
    )


    BLOCK_6_RELOADED_CHECKPOINT = torch.load(
        BLOCK_6_RELOADED_CHECKPOINT_BUFFER,
        map_location=
            "cpu",
    )


BLOCK_6_CHECKPOINT_READBACK_VALID = all(
    [
        isinstance(
            BLOCK_6_RELOADED_CHECKPOINT,
            dict,
        ),

        (
            BLOCK_6_RELOADED_CHECKPOINT.get(
                "checkpoint_type"
            )
            ==
            NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE
        ),

        (
            BLOCK_6_RELOADED_CHECKPOINT.get(
                "training_epoch_count"
            )
            ==
            NOTEBOOK_06_FACTUAL_TRAINING_EPOCHS
        ),

        (
            BLOCK_6_RELOADED_CHECKPOINT.get(
                "methodological_boundary",
                {},
            ).get(
                "validated_model_checkpoint"
            )
            is False
        ),
    ]
)


if not BLOCK_6_CHECKPOINT_READBACK_VALID:

    raise RuntimeError(
        "Persisted Block 6 factual checkpoint failed read-back validation."
    )


# =============================================================================
# Metadata read-back validation
# =============================================================================

BLOCK_6_RELOADED_METADATA_BYTES = (
    block_6_download_drive_bytes(
        NOTEBOOK_06_DRIVE_SERVICE,
        NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE_ID,
    )
)


BLOCK_6_RELOADED_METADATA = json.loads(
    BLOCK_6_RELOADED_METADATA_BYTES.decode(
        "utf-8"
    )
)


BLOCK_6_METADATA_READBACK_VALID = all(
    [
        isinstance(
            BLOCK_6_RELOADED_METADATA,
            dict,
        ),

        (
            BLOCK_6_RELOADED_METADATA.get(
                "checkpoint_type"
            )
            ==
            NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE
        ),

        (
            BLOCK_6_RELOADED_METADATA.get(
                "training_scope",
                {},
            ).get(
                "epochs"
            )
            ==
            NOTEBOOK_06_FACTUAL_TRAINING_EPOCHS
        ),

        (
            BLOCK_6_RELOADED_METADATA.get(
                "methodological_boundary",
                {},
            ).get(
                "validated_model_checkpoint"
            )
            is False
        ),

        (
            BLOCK_6_RELOADED_METADATA.get(
                "methodological_boundary",
                {},
            ).get(
                "empirical_validity"
            )
            is False
        ),
    ]
)


if not BLOCK_6_METADATA_READBACK_VALID:

    raise RuntimeError(
        "Persisted Block 6 factual metadata failed read-back validation."
    )


# =============================================================================
# Checkpoint policy validation
# =============================================================================

BLOCK_6_CHECKPOINT_POLICY_VALID = all(
    [
        NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE
        ==
        "controlled_experimental_factual_training_checkpoint",

        BLOCK_6_LOCAL_CHECKPOINT_CREATED,
        BLOCK_6_LOCAL_METADATA_CREATED,
        BLOCK_6_CHECKPOINT_DRIVE_PERSISTED,
        BLOCK_6_METADATA_DRIVE_PERSISTED,
        BLOCK_6_CHECKPOINT_READBACK_VALID,
        BLOCK_6_METADATA_READBACK_VALID,

        (
            NOTEBOOK_06_FACTUAL_CHECKPOINT[
                "methodological_boundary"
            ][
                "validated_model_checkpoint"
            ]
            is False
        ),

        (
            NOTEBOOK_06_FACTUAL_CHECKPOINT[
                "methodological_boundary"
            ][
                "empirical_validity"
            ]
            is False
        ),
    ]
)


if not BLOCK_6_CHECKPOINT_POLICY_VALID:

    raise RuntimeError(
        "Block 6 factual checkpoint policy is invalid."
    )


# =============================================================================
# Final execution-state boundary
# =============================================================================

NOTEBOOK_06_FACTUAL_ZERO_GRAD_EXECUTED = True

NOTEBOOK_06_BACKWARD_PASS_EXECUTED = True

NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED = True

NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED = True

NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED = True

NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ACTIVATED = False

NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ACTIVATED = False

NOTEBOOK_06_RECURRENT_STATES_ACTIVATED = False

NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Final Block 6 validation
# =============================================================================

NOTEBOOK_06_BLOCK_6_ERRORS = []


block_6_validation_checks = {
    "active_contract_invalid":
        BLOCK_6_ACTIVE_CONTRACT_VALID,

    "positive_class_weight_policy_invalid":
        BLOCK_6_POSITIVE_CLASS_WEIGHT_POLICY_VALID,

    "training_scope_invalid":
        BLOCK_6_TRAINING_SCOPE_VALID,

    "parameter_scope_invalid":
        BLOCK_6_PARAMETER_SCOPE_VALID,

    "optimizer_scope_invalid":
        BLOCK_6_OPTIMIZER_SCOPE_VALID,

    "objective_weights_invalid":
        BLOCK_6_OBJECTIVE_WEIGHTS_VALID,

    "forward_input_shape_invalid":
        BLOCK_6_FORWARD_INPUT_SHAPE_VALID,

    "target_shape_invalid":
        BLOCK_6_TARGET_SHAPE_VALID,

    "mask_shape_invalid":
        BLOCK_6_MASK_SHAPE_VALID,

    "forward_input_nonfinite":
        BLOCK_6_FORWARD_INPUT_FINITE,

    "block_5_objective_not_reproduced":
        BLOCK_6_BLOCK_5_OBJECTIVE_REPRODUCED,

    "block_5_family_losses_not_reproduced":
        BLOCK_6_BLOCK_5_FAMILY_LOSSES_REPRODUCED,

    "initial_objective_nonfinite":
        BLOCK_6_INITIAL_OBJECTIVE_FINITE,

    "final_objective_nonfinite":
        BLOCK_6_FINAL_OBJECTIVE_FINITE,

    "gradient_control_invalid":
        BLOCK_6_GRADIENT_CONTROL_VALID,

    "training_policy_invalid":
        BLOCK_6_TRAINING_POLICY_VALID,

    "factual_head_not_changed":
        BLOCK_6_FACTUAL_HEAD_CHANGED,

    "frozen_parameters_changed":
        BLOCK_6_FROZEN_PARAMETERS_UNCHANGED,

    "parameter_update_invalid":
        BLOCK_6_PARAMETER_UPDATE_VALID,

    "checkpoint_policy_invalid":
        BLOCK_6_CHECKPOINT_POLICY_VALID,

    "checkpoint_readback_invalid":
        BLOCK_6_CHECKPOINT_READBACK_VALID,

    "metadata_readback_invalid":
        BLOCK_6_METADATA_READBACK_VALID,
}


for error_name, condition in (
    block_6_validation_checks.items()
):

    if not condition:

        NOTEBOOK_06_BLOCK_6_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited-operation validation
# =============================================================================

prohibited_block_6_operations = {
    "psychological_training_incorrectly_executed":
        NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "group_conditioned_path_incorrectly_executed":
        NOTEBOOK_06_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_mechanisms_incorrectly_activated":
        NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ACTIVATED,

    "transformative_weights_incorrectly_activated":
        NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ACTIVATED,

    "recurrent_states_incorrectly_activated":
        NOTEBOOK_06_RECURRENT_STATES_ACTIVATED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for error_name, operation_executed in (
    prohibited_block_6_operations.items()
):

    if operation_executed:

        NOTEBOOK_06_BLOCK_6_ERRORS.append(
            error_name
        )


NOTEBOOK_06_BLOCK_6_VALID = (
    len(
        NOTEBOOK_06_BLOCK_6_ERRORS
    )
    == 0
)


if not NOTEBOOK_06_BLOCK_6_VALID:

    raise RuntimeError(
        "Notebook 06 Block 6 controlled factual training failed. "
        f"Errors: {NOTEBOOK_06_BLOCK_6_ERRORS}"
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_06_BLOCK_6_COMPLETE = True

NOTEBOOK_06_READY_FOR_FACTUAL_CHECKPOINT_RELOAD = True


# =============================================================================
# Block 7 handover objects
# =============================================================================

NOTEBOOK_06_FACTUAL_TRAINED_HEAD = (
    BLOCK_6_FACTUAL_HEAD
)


NOTEBOOK_06_FACTUAL_TRAINED_OPTIMIZER = (
    BLOCK_6_FACTUAL_OPTIMIZER
)


NOTEBOOK_06_FACTUAL_FINAL_OBJECTIVE = (
    BLOCK_6_FINAL_OBJECTIVE
)


NOTEBOOK_06_FACTUAL_FINAL_FAMILY_LOSSES = deepcopy(
    BLOCK_6_FINAL_FAMILY_LOSSES
)


NOTEBOOK_06_FACTUAL_TRAINING_HISTORY = deepcopy(
    BLOCK_6_TRAINING_HISTORY
)


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 06, Block 6: "
    "Controlled Factual Training and Checkpoint Policy"
)

print("=" * 72)

print(
    f"Training policy version      : "
    f"{NOTEBOOK_06_FACTUAL_TRAINING_POLICY_VERSION}"
)


print("-" * 72)

print(
    "Training scope"
)

print(
    f"Training articles            : "
    f"{BLOCK_6_TRAINING_ARTICLE_COUNT}"
)

print(
    f"Training sentences           : "
    f"{BLOCK_6_TRAINING_SENTENCE_COUNT}"
)

print(
    f"Validation sentences         : "
    f"{0}"
)

print(
    f"Test sentences               : "
    f"{0}"
)

print(
    f"Epochs executed              : "
    f"{NOTEBOOK_06_FACTUAL_TRAINING_EPOCHS}"
)

print(
    f"Within-article shuffle       : "
    f"{NOTEBOOK_06_FACTUAL_WITHIN_ARTICLE_SHUFFLE}"
)

print(
    f"Article sequence preserved   : "
    f"{NOTEBOOK_06_FACTUAL_ARTICLE_SEQUENCE_PRESERVED}"
)


print("-" * 72)

print(
    "Supervised objectives"
)

print(
    f"Active dimensions            : "
    f"{list(BLOCK_6_ACTIVE_DIMENSIONS)}"
)

print(
    f"Deferred dimensions          : "
    f"{list(BLOCK_6_DEFERRED_DIMENSIONS)}"
)

print(
    f"Objective weights            : "
    f"{BLOCK_6_OBJECTIVE_WEIGHTS}"
)

print(
    f"Weighted binary dimensions   : "
    f"{list(BLOCK_6_WEIGHTED_BINARY_DIMENSIONS)}"
)

print(
    f"Positive class weights       : "
    f"{BLOCK_6_POSITIVE_CLASS_WEIGHTS}"
)

print(
    f"Prediction positive weight   : "
    f"{BLOCK_6_PREDICTION_POS_WEIGHT}"
)

print(
    f"Mask-aware supervision       : "
    f"{True}"
)


print("-" * 72)

print(
    "Optimisation boundary"
)

print(
    f"Only factual head            : "
    f"{True}"
)

print(
    f"Optimiser scope valid        : "
    f"{BLOCK_6_OPTIMIZER_SCOPE_VALID}"
)

print(
    f"Backbone frozen              : "
    f"{BLOCK_6_BACKBONE_FROZEN}"
)

print(
    f"Global confluent frozen      : "
    f"{BLOCK_6_GLOBAL_CONFLUENT_FROZEN}"
)

print(
    f"Psychological head frozen    : "
    f"{BLOCK_6_PSYCHOLOGICAL_HEAD_FROZEN}"
)

print(
    f"Frozen parameters unchanged  : "
    f"{BLOCK_6_FROZEN_PARAMETERS_UNCHANGED}"
)

print(
    f"Factual parameters changed   : "
    f"{BLOCK_6_FACTUAL_HEAD_CHANGED}"
)

print(
    f"Maximum parameter delta      : "
    f"{BLOCK_6_MAX_PARAMETER_DELTA:.8f}"
)


print("-" * 72)

print(
    "Gradient control"
)

print(
    f"Maximum gradient norm        : "
    f"{NOTEBOOK_06_FACTUAL_MAX_GRAD_NORM:.4f}"
)

print(
    f"Max observed pre-clip norm   : "
    f"{BLOCK_6_MAX_OBSERVED_PRECLIP_GRAD_NORM:.8f}"
)

print(
    f"Finite gradients             : "
    f"{BLOCK_6_FINITE_GRADIENTS}"
)

print(
    f"Non-finite loss detected     : "
    f"{BLOCK_6_NONFINITE_LOSS_DETECTED}"
)


print("-" * 72)

print(
    "Controlled factual training objective"
)

print(
    f"Block 5 objective reproduced : "
    f"{BLOCK_6_BLOCK_5_OBJECTIVE_REPRODUCED}"
)

print(
    f"Initial total objective      : "
    f"{BLOCK_6_INITIAL_OBJECTIVE:.8f}"
)

print(
    f"Final total objective        : "
    f"{BLOCK_6_FINAL_OBJECTIVE:.8f}"
)

print(
    f"Objective reduction          : "
    f"{BLOCK_6_OBJECTIVE_REDUCTION:.8f}"
)


for target_name in BLOCK_6_ACTIVE_DIMENSIONS:

    print(
        f"{target_name:<29}: "
        f"{BLOCK_6_INITIAL_FAMILY_LOSSES[target_name]:.8f}"
        f" / "
        f"{BLOCK_6_FINAL_FAMILY_LOSSES[target_name]:.8f}"
    )


print("-" * 72)

print(
    "Checkpoint policy"
)

print(
    f"Checkpoint type              : "
    f"{NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE}"
)

print(
    f"Checkpoint filename          : "
    f"{NOTEBOOK_06_FACTUAL_CHECKPOINT_FILENAME}"
)

print(
    f"Local checkpoint created     : "
    f"{BLOCK_6_LOCAL_CHECKPOINT_CREATED}"
)

print(
    f"Checkpoint Drive operation   : "
    f"{NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_OPERATION}"
)

print(
    f"Checkpoint Drive file ID     : "
    f"{NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE_ID}"
)

print(
    f"Metadata Drive operation     : "
    f"{NOTEBOOK_06_FACTUAL_METADATA_DRIVE_OPERATION}"
)

print(
    f"Metadata Drive file ID       : "
    f"{NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE_ID}"
)

print(
    f"Checkpoint read-back valid   : "
    f"{BLOCK_6_CHECKPOINT_READBACK_VALID}"
)

print(
    f"Metadata read-back valid     : "
    f"{BLOCK_6_METADATA_READBACK_VALID}"
)

print(
    f"Validated model checkpoint   : "
    f"{False}"
)


print("-" * 72)

print(
    "Execution state"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_06_FACTUAL_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_06_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_06_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_06_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Factual training executed    : "
    f"{NOTEBOOK_06_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_06_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{NOTEBOOK_06_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative activated     : "
    f"{NOTEBOOK_06_TRANSFORMATIVE_MECHANISMS_ACTIVATED}"
)

print(
    f"Transformative weights active: "
    f"{NOTEBOOK_06_TRANSFORMATIVE_WEIGHTS_ACTIVATED}"
)

print(
    f"Recurrent states activated   : "
    f"{NOTEBOOK_06_RECURRENT_STATES_ACTIVATED}"
)

print(
    f"Validation early stopping    : "
    f"{NOTEBOOK_06_FACTUAL_VALIDATION_EARLY_STOPPING}"
)

print(
    f"Held-out evaluation executed : "
    f"{NOTEBOOK_06_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_06_BLOCK_6_VALID}"
)

print(
    f"Block 6 complete             : "
    f"{NOTEBOOK_06_BLOCK_6_COMPLETE}"
)


print("=" * 72)


print(
    "Controlled factual training completed successfully."
)

print(
    "Only the factual representation head was updated."
)

print(
    f"{len(BLOCK_6_ACTIVE_DIMENSIONS)} validated factual objective "
    "families remained separate and mask-aware throughout training."
)

print(
    "Positive-class weighting was inherited dynamically from the "
    "validated upstream factual objective contract."
)

print(
    "The backbone, mandatory global confluent representation and "
    "completed psychological head remained frozen and unchanged."
)

print(
    "The optional group-conditioned path remained inactive."
)

print(
    "No social, transformative, Transformative Weight or recurrent "
    "component was trained or executed."
)

print(
    "Gradient finiteness, clipping and frozen-parameter invariance "
    "were validated explicitly."
)

print(
    "The resulting checkpoint is a controlled experimental factual "
    "training checkpoint and is not a validated model checkpoint."
)

print(
    "No validation-based early stopping or held-out evaluation was "
    "performed by this controlled training block."
)

print(
    "Training-loss behaviour is a computational diagnostic and does "
    "not demonstrate generalisation or empirical validity."
)

print(
    "No held-out evaluation, ablation or empirical-validity claim "
    "has been performed."
)

print(
    "Block 7 may proceed to factual checkpoint reload, reproducibility "
    "and training-state validation."
)

print("=" * 72)

========================================================================
Media AI — Notebook 06, Block 6: Controlled Factual Training and Checkpoint Policy
========================================================================
Training policy version      : 1.1
------------------------------------------------------------------------
Training scope
Training articles            : 3
Training sentences           : 54
Validation sentences         : 0
Test sentences               : 0
Epochs executed              : 10
Within-article shuffle       : False
Article sequence preserved   : True
------------------------------------------------------------------------
Supervised objectives
Active dimensions            : ['explicit_claim', 'observation_or_event', 'quantitative_information', 'attribution', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction', 'factological_weight']
Deferred dimensions          : ['speculation']
Objective weights            : {'explicit_claim': 0.1111111111111111, 'observation_or_event': 0.1111111111111111, 'quantitative_information': 0.1111111111111111, 'attribution': 0.1111111111111111, 'evidence_reference': 0.1111111111111111, 'certainty_statement': 0.1111111111111111, 'uncertainty_statement': 0.1111111111111111, 'prediction': 0.1111111111111111, 'factological_weight': 0.1111111111111111}
Weighted binary dimensions   : ['explicit_claim', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction']
Positive class weights       : {'explicit_claim': 0.2558139534883721, 'evidence_reference': 3.1538461538461537, 'certainty_statement': 0.17391304347826086, 'uncertainty_statement': 8.0, 'prediction': 25.0}
Prediction positive weight   : 25.0
Mask-aware supervision       : True
------------------------------------------------------------------------
Optimisation boundary
Only factual head            : True
Optimiser scope valid        : True
Backbone frozen              : True
Global confluent frozen      : True
Psychological head frozen    : True
Frozen parameters unchanged  : True
Factual parameters changed   : True
Maximum parameter delta      : 0.01005103
------------------------------------------------------------------------
Gradient control
Maximum gradient norm        : 1.0000
Max observed pre-clip norm   : 4.87169099
Finite gradients             : True
Non-finite loss detected     : False
------------------------------------------------------------------------
Controlled factual training objective
Block 5 objective reproduced : True
Initial total objective      : 1.03976345
Final total objective        : 0.40325385
Objective reduction          : 0.63650960
explicit_claim               : 0.28797096 / 0.22249709
observation_or_event         : 0.80305123 / 0.63362038
quantitative_information     : 0.87209803 / 0.53347296
attribution                  : 0.88034511 / 0.42519507
evidence_reference           : 0.91512269 / 0.60179800
certainty_statement          : 0.21677481 / 0.14542311
uncertainty_statement        : 1.14133441 / 0.57453150
prediction                   : 1.50916290 / 0.40801331
factological_weight          : 2.73200965 / 0.08473307
------------------------------------------------------------------------
Checkpoint policy
Checkpoint type              : controlled_experimental_factual_training_checkpoint
Checkpoint filename          : notebook_06_controlled_factual_training_checkpoint.pt
Local checkpoint created     : True
Checkpoint Drive operation   : updated
Checkpoint Drive file ID     : 1S5Wq68eGkMk2yxQ1BKCJ5PycFvAJjziY
Metadata Drive operation     : updated
Metadata Drive file ID       : 1jM2rdgpYkcJA_xIhSpmC4dNr2DcO7xli
Checkpoint read-back valid   : True
Metadata read-back valid     : True
Validated model checkpoint   : False
------------------------------------------------------------------------
Execution state
Zero grad executed           : True
Backward pass executed       : True
Optimiser step executed      : True
Parameter update executed    : True
Factual training executed    : True
Psychological retraining     : False
Group-conditioned executed   : False
Transformative activated     : False
Transformative weights active: False
Recurrent states activated   : False
Validation early stopping    : False
Held-out evaluation executed : False
Empirical validity           : False
Block valid                  : True
Block 6 complete             : True
========================================================================
Controlled factual training completed successfully.
Only the factual representation head was updated.
9 validated factual objective families remained separate and mask-aware throughout training.
Positive-class weighting was inherited dynamically from the validated upstream factual objective contract.
The backbone, mandatory global confluent representation and completed psychological head remained frozen and unchanged.
The optional group-conditioned path remained inactive.
No social, transformative, Transformative Weight or recurrent component was trained or executed.
Gradient finiteness, clipping and frozen-parameter invariance were validated explicitly.
The resulting checkpoint is a controlled experimental factual training checkpoint and is not a validated model checkpoint.
No validation-based early stopping or held-out evaluation was performed by this controlled training block.
Training-loss behaviour is a computational diagnostic and does not demonstrate generalisation or empirical validity.
No held-out evaluation, ablation or empirical-validity claim has been performed.
Block 7 may proceed to factual checkpoint reload, reproducibility and training-state validation.
========================================================================

## Block 7 — Factual Checkpoint Reload, Reproducibility and Training-State Validation

This block validates that the controlled factual training state created in Block 6 can be independently restored from persisted artefacts without performing any additional training.

The purpose is to verify checkpoint portability, exact factual-head state reproduction, optimiser-state recovery, post-training objective reproduction and preservation of the methodological execution boundary.

Block 7 is therefore a reproducibility and state-integrity block, not a training block.

### Persisted artefact reload

The controlled factual training checkpoint and its metadata created in Block 6 must be reloaded from their persisted Google Drive artefacts.

The reload procedure must use the persisted files rather than the current trained runtime objects as the source of model state.

The block should verify that:

- the checkpoint file can be located and downloaded;
- the metadata file can be located and downloaded;
- both artefacts can be parsed successfully;
- the checkpoint type remains `controlled_experimental_factual_training_checkpoint`;
- the checkpoint is not classified as a validated model checkpoint;
- the stored training-policy version remains intact;
- the stored factual dimension contract remains intact;
- the stored optimiser configuration remains intact;
- the stored methodological boundary remains intact.

### Fresh module restoration

Block 7 must restore the factual training state into fresh module instances matching the validated Notebook 06 architecture.

The fresh restoration path should reproduce:

- frozen backbone state;
- frozen mandatory global confluent state;
- trained factual-head state;
- frozen psychological-head state.

The restored factual head must not reuse the current trained runtime module as its parameter source.

The current runtime state may be used only as an independent comparison reference after restoration.

### Exact factual-head reproduction

The restored factual-head parameter tensors must match the persisted checkpoint exactly.

The restored factual-head state should also match the trained Block 6 runtime factual-head state exactly.

The block should verify:

- identical parameter names;
- identical parameter tensor shapes;
- exact tensor equality;
- correct factual-head parameter count;
- factual-head trainability remains enabled for future optimisation;
- no unrelated module becomes trainable.

Successful equality establishes state reproduction, not model quality.

### Frozen-module reproduction

The persisted backbone, mandatory global confluent path and psychological head must also be restored and checked.

Their restored states must match the corresponding persisted checkpoint states exactly.

They must remain frozen after restoration.

The block should confirm that:

- backbone parameters are reproduced exactly;
- global confluent parameters are reproduced exactly;
- psychological-head parameters are reproduced exactly;
- all three remain outside the optimiser scope;
- no frozen parameter is modified during Block 7.

### Optimiser-state recovery

The factual AdamW optimiser state persisted in Block 6 must be restored.

The restored optimiser must remain scoped exclusively to the factual-head parameters.

The block should validate:

- optimiser type remains AdamW;
- learning rate remains **0.001**;
- weight decay remains **0.0001**;
- optimiser parameter count remains **34,442**;
- optimiser state tensors are recoverable;
- optimiser parameter groups are aligned with the restored factual head;
- no backbone, confluent or psychological parameter appears in the optimiser.

The optimiser state should be compared structurally and numerically with the persisted checkpoint state.

No optimiser step is permitted.

### Training-policy reproduction

The persisted Block 6 training policy should be revalidated.

The block should confirm that the checkpoint still records:

- training articles: **1**;
- training sentences: **16**;
- validation sentences: **0**;
- test sentences: **0**;
- epochs executed: **10**;
- within-article shuffle: **False**;
- article sequence preserved: **True**;
- validation-based early stopping: **False**;
- maximum gradient norm: **1.0**;
- prediction positive-class weight: **7.0**;
- equal factual-family weighting: **0.2 per active family**.

The recorded maximum observed pre-clipping gradient norm from Block 6 should remain preserved as training metadata.

Block 7 does not need to reproduce the historical gradients themselves.

### Factual objective reproduction

The restored factual model state must reproduce the final Block 6 controlled factual objective.

The factual target tensor, factual mask tensor, active factual dimensions, objective-family weights and prediction positive-class weight must remain unchanged.

The block should execute a controlled forward pass through the restored factual head using the same validated factual forward input.

The restored model should reproduce:

- final total factual objective;
- F2 final loss;
- F3 final loss;
- F5 final loss;
- F9 final loss;
- F10 final loss.

The reproduced values should match the persisted Block 6 values within the configured numerical tolerance.

The individual factual-family losses must remain separately observable.

### Active and deferred factual dimensions

The restored checkpoint must preserve the same optimisation boundary.

Active factual dimensions remain:

- **F2 — observation_or_event**
- **F3 — quantitative_information**
- **F5 — evidence_reference**
- **F9 — prediction**
- **F10 — factological_weight**

Deferred factual dimensions remain:

- **F1 — explicit_claim**
- **F4 — attribution**
- **F6 — certainty_statement**
- **F7 — uncertainty_statement**
- **F8 — speculation**

Deferred dimensions remain structurally present in the ten-dimensional factual output but must not enter the reproduced controlled objective.

### Methodological-boundary validation

The checkpoint and metadata must continue to record that:

- the factual head was trained;
- the psychological head was not retrained;
- the backbone was not trained;
- the mandatory global confluent path was not trained;
- the optional group-conditioned path was not executed;
- the social path was not trained;
- transformative mechanisms were not executed;
- Transformative Weights were not trained;
- recurrent states were not trained;
- no validation-based early stopping was used;
- no held-out evaluation was performed;
- no empirical-validity claim was made.

The checkpoint must remain explicitly classified as experimental.

### No-training execution boundary

Block 7 must not perform any additional training.

The following operations are prohibited:

- backward pass;
- optimiser step;
- parameter update;
- additional factual training;
- psychological retraining;
- group-conditioned execution;
- transformative execution;
- Transformative Weight training;
- recurrent-state training;
- held-out evaluation.

A forward pass and loss recalculation are permitted solely for reproducibility validation.

No parameter may change during the block.

### Reproducibility interpretation

Successful Block 7 completion demonstrates that the persisted factual training state is portable and reproducible.

It establishes that:

- the factual-head state can be restored independently;
- the frozen supporting modules can be restored independently;
- the AdamW optimiser state is recoverable;
- the final factual objective can be reproduced;
- the factual methodological boundary survives persistence.

It does **not** establish:

- factual generalisation;
- factual calibration;
- cross-article robustness;
- model-selection validity;
- production readiness;
- or overall Media AI empirical validity.

### Block completion criteria

Block 7 is complete only if:

- checkpoint reload succeeds;
- metadata reload succeeds;
- checkpoint type is valid;
- factual-head state is reproduced exactly;
- factual-head state matches the trained Block 6 runtime state;
- backbone state is reproduced exactly;
- global confluent state is reproduced exactly;
- psychological-head state is reproduced exactly;
- frozen modules remain frozen;
- factual-head trainability is preserved;
- AdamW optimiser state is restored;
- optimiser scope remains factual-head-only;
- optimiser hyperparameters are preserved;
- training-policy metadata is preserved;
- maximum gradient norm remains recorded as 1.0;
- the final total factual objective is reproduced;
- all five final factual-family losses are reproduced;
- active and deferred factual dimensions remain unchanged;
- no parameter changes occur;
- no backward pass is executed;
- no optimiser step is executed;
- no additional training is executed;
- no held-out evaluation is executed;
- empirical validity remains explicitly false;
- and all Block 7 validation checks pass.

Successful completion establishes checkpoint portability and factual training-state reproducibility and permits the notebook to proceed to factual-path audit, persistent handover and Notebook 06 completion.

In [13]:
# =============================================================================
# Media AI — Notebook 06
# Block 7: Factual Checkpoint Reload, Reproducibility
#          and Training-State Validation
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json
import math

import torch
import torch.nn as nn
import torch.nn.functional as F

from googleapiclient.http import MediaIoBaseDownload


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_06_BLOCK_7 = 7

NOTEBOOK_06_BLOCK_7_NAME = (
    "Factual Checkpoint Reload, Reproducibility "
    "and Training-State Validation"
)

NOTEBOOK_06_BLOCK_7_VERSION = "1.2"

NOTEBOOK_06_FACTUAL_REPRODUCIBILITY_VERSION = "1.2"

BLOCK_7_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Numerical tolerance
# =============================================================================

NOTEBOOK_06_FACTUAL_REPRODUCTION_TOLERANCE = 1e-7


# =============================================================================
# Dependency checks
# =============================================================================

required_block_7_objects = [
    # -------------------------------------------------------------------------
    # Block 6 completion
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_6_COMPLETE",
    "NOTEBOOK_06_BLOCK_6_VALID",
    "NOTEBOOK_06_READY_FOR_FACTUAL_CHECKPOINT_RELOAD",

    # -------------------------------------------------------------------------
    # Persisted Block 6 artefacts
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE_ID",
    "NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE_ID",
    "NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE",

    # -------------------------------------------------------------------------
    # Canonical factual contract
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_SENTENCE_COUNT",
    "NOTEBOOK_06_SENTENCE_IDS",
    "NOTEBOOK_06_FACTUAL_DIMENSION_ORDER",
    "NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS",
    "NOTEBOOK_06_FACTUAL_OBJECTIVE_WEIGHTS",

    # -------------------------------------------------------------------------
    # Block 5 target contract
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_FACTUAL_TARGET_TENSOR",
    "NOTEBOOK_06_FACTUAL_MASK_TENSOR",
    "NOTEBOOK_06_FACTUAL_FORWARD_INPUT",

    # -------------------------------------------------------------------------
    # Block 6 runtime comparison state
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BACKBONE_FROZEN_MODULE",
    "NOTEBOOK_06_GLOBAL_CONFLUENT_FROZEN_MODULE",
    "NOTEBOOK_06_FACTUAL_TRAINED_HEAD",
    "NOTEBOOK_06_PSYCHOLOGICAL_HEAD_FROZEN_MODULE",
    "NOTEBOOK_06_FACTUAL_TRAINED_OPTIMIZER",

    "NOTEBOOK_06_FACTUAL_FINAL_OBJECTIVE",
    "NOTEBOOK_06_FACTUAL_FINAL_FAMILY_LOSSES",

    # -------------------------------------------------------------------------
    # Persistence service
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_DRIVE_SERVICE",
]


missing_block_7_objects = [
    object_name
    for object_name in required_block_7_objects
    if object_name not in globals()
]


if missing_block_7_objects:

    raise NameError(
        "Notebook 06 Block 7 prerequisites are not initialised. "
        f"Missing: {missing_block_7_objects}"
    )


if not NOTEBOOK_06_BLOCK_6_COMPLETE:

    raise ValueError(
        "Notebook 06 Block 6 must be complete before Block 7."
    )


if not NOTEBOOK_06_BLOCK_6_VALID:

    raise ValueError(
        "Notebook 06 Block 6 must be valid before Block 7."
    )


if not NOTEBOOK_06_READY_FOR_FACTUAL_CHECKPOINT_RELOAD:

    raise ValueError(
        "Notebook 06 is not ready for factual checkpoint reload."
    )


# =============================================================================
# Execution boundary initialisation
# =============================================================================

NOTEBOOK_06_BLOCK_7_FORWARD_EXECUTED = False

NOTEBOOK_06_BLOCK_7_OBJECTIVE_RECALCULATED = False

NOTEBOOK_06_BLOCK_7_ZERO_GRAD_EXECUTED = False

NOTEBOOK_06_BLOCK_7_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_BLOCK_7_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_06_BLOCK_7_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_BLOCK_7_ADDITIONAL_TRAINING_EXECUTED = False

NOTEBOOK_06_BLOCK_7_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_BLOCK_7_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_06_BLOCK_7_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_06_BLOCK_7_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

NOTEBOOK_06_BLOCK_7_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_06_BLOCK_7_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_06_BLOCK_7_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Google Drive download helper
# =============================================================================

def block_7_download_drive_bytes(
    drive_service,
    file_id,
):
    """
    Download one Google Drive file and return raw bytes.
    """

    request = (
        drive_service.files()
        .get_media(
            fileId=file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Reload persisted Block 6 checkpoint
# =============================================================================

BLOCK_7_CHECKPOINT_BYTES = (
    block_7_download_drive_bytes(
        NOTEBOOK_06_DRIVE_SERVICE,
        NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE_ID,
    )
)


if not BLOCK_7_CHECKPOINT_BYTES:

    raise RuntimeError(
        "Persisted Block 6 factual checkpoint was empty."
    )


BLOCK_7_CHECKPOINT_BUFFER = io.BytesIO(
    BLOCK_7_CHECKPOINT_BYTES
)


try:

    BLOCK_7_CHECKPOINT = torch.load(
        BLOCK_7_CHECKPOINT_BUFFER,
        map_location="cpu",
        weights_only=False,
    )


except TypeError:

    BLOCK_7_CHECKPOINT_BUFFER.seek(
        0
    )


    BLOCK_7_CHECKPOINT = torch.load(
        BLOCK_7_CHECKPOINT_BUFFER,
        map_location="cpu",
    )


if not isinstance(
    BLOCK_7_CHECKPOINT,
    dict,
):

    raise TypeError(
        "Reloaded factual checkpoint must be dictionary-like."
    )


BLOCK_7_CHECKPOINT_RELOADED = True


# =============================================================================
# Reload persisted Block 6 metadata
# =============================================================================

BLOCK_7_METADATA_BYTES = (
    block_7_download_drive_bytes(
        NOTEBOOK_06_DRIVE_SERVICE,
        NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE_ID,
    )
)


if not BLOCK_7_METADATA_BYTES:

    raise RuntimeError(
        "Persisted Block 6 factual metadata was empty."
    )


BLOCK_7_METADATA = json.loads(
    BLOCK_7_METADATA_BYTES.decode(
        "utf-8"
    )
)


if not isinstance(
    BLOCK_7_METADATA,
    dict,
):

    raise TypeError(
        "Reloaded factual metadata must be a JSON object."
    )


BLOCK_7_METADATA_RELOADED = True


# =============================================================================
# Checkpoint top-level contract
# =============================================================================

BLOCK_7_REQUIRED_CHECKPOINT_KEYS = {
    "checkpoint_type",
    "checkpoint_version",
    "training_policy_version",
    "training_epoch_count",
    "within_article_shuffle",
    "article_sequence_preserved",
    "active_dimensions",
    "deferred_dimensions",
    "objective_weights",
    "positive_class_weights",
    "weighted_binary_dimensions",
    "prediction_positive_weight",
    "training_article_count",
    "training_sentence_count",
    "training_article_ids",
    "optimizer_type",
    "learning_rate",
    "weight_decay",
    "maximum_gradient_norm",
    "initial_objective",
    "final_objective",
    "initial_family_losses",
    "final_family_losses",
    "training_history",
    "backbone_state_dict",
    "global_confluent_state_dict",
    "factual_head_state_dict",
    "psychological_head_state_dict",
    "optimizer_state_dict",
    "methodological_boundary",
}


BLOCK_7_MISSING_CHECKPOINT_KEYS = sorted(
    BLOCK_7_REQUIRED_CHECKPOINT_KEYS
    -
    set(
        BLOCK_7_CHECKPOINT.keys()
    )
)


BLOCK_7_CHECKPOINT_CONTRACT_VALID = (
    len(
        BLOCK_7_MISSING_CHECKPOINT_KEYS
    )
    == 0
)


if not BLOCK_7_CHECKPOINT_CONTRACT_VALID:

    raise RuntimeError(
        "Reloaded factual checkpoint is missing required fields. "
        f"Missing: {BLOCK_7_MISSING_CHECKPOINT_KEYS}"
    )


# =============================================================================
# Checkpoint classification
# =============================================================================

BLOCK_7_CHECKPOINT_TYPE_VALID = (
    BLOCK_7_CHECKPOINT[
        "checkpoint_type"
    ]
    ==
    NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE
    ==
    "controlled_experimental_factual_training_checkpoint"
)


BLOCK_7_EXPERIMENTAL_CHECKPOINT = (
    BLOCK_7_CHECKPOINT_TYPE_VALID
)


BLOCK_7_VALIDATED_MODEL_CHECKPOINT = bool(
    BLOCK_7_CHECKPOINT[
        "methodological_boundary"
    ].get(
        "validated_model_checkpoint",
        True,
    )
)


if not BLOCK_7_CHECKPOINT_TYPE_VALID:

    raise RuntimeError(
        "Reloaded checkpoint type is invalid."
    )


if BLOCK_7_VALIDATED_MODEL_CHECKPOINT:

    raise RuntimeError(
        "Controlled factual checkpoint was incorrectly classified "
        "as a validated model checkpoint."
    )


# =============================================================================
# Fresh architecture definitions
# =============================================================================
#
# These fresh modules reproduce the validated Notebook 06 global factual path.
#
# They do NOT use the trained runtime factual module as their parameter source.
# Parameters are restored exclusively from the persisted checkpoint.
# =============================================================================

BLOCK_7_TEXTUAL_DIM = 768

BLOCK_7_BACKBONE_DIM = 768

BLOCK_7_CONFLUENT_DIM = 256

BLOCK_7_FACTUAL_HIDDEN_DIM = 128

BLOCK_7_FACTUAL_DIM = 10

BLOCK_7_PSYCHOLOGICAL_HIDDEN_DIM = 128

BLOCK_7_PSYCHOLOGICAL_DIM = 34


class Block7Backbone(nn.Module):

    def __init__(self):

        super().__init__()


        self.projection = nn.Linear(
            BLOCK_7_TEXTUAL_DIM,
            BLOCK_7_BACKBONE_DIM,
        )


    def forward(
        self,
        x,
    ):

        return self.projection(
            x
        )


class Block7GlobalConfluent(nn.Module):

    def __init__(self):

        super().__init__()


        self.global_projection = nn.Sequential(
            nn.Linear(
                BLOCK_7_BACKBONE_DIM,
                BLOCK_7_CONFLUENT_DIM,
            ),

            nn.ReLU(),

            nn.Dropout(
                p=0.0
            ),

            nn.LayerNorm(
                BLOCK_7_CONFLUENT_DIM
            ),
        )


    def forward(
        self,
        x,
    ):

        return self.global_projection(
            x
        )


class Block7RepresentationCore(nn.Module):

    def __init__(
        self,
        input_dim,
        hidden_dim,
    ):

        super().__init__()


        self.network = nn.Sequential(
            nn.Linear(
                input_dim,
                hidden_dim,
            ),

            nn.ReLU(),

            nn.Dropout(
                p=0.0
            ),

            nn.LayerNorm(
                hidden_dim
            ),
        )


    def forward(
        self,
        x,
    ):

        return self.network(
            x
        )


class Block7FactualHead(nn.Module):

    def __init__(self):

        super().__init__()


        self.core = Block7RepresentationCore(
            input_dim=
                BLOCK_7_CONFLUENT_DIM,

            hidden_dim=
                BLOCK_7_FACTUAL_HIDDEN_DIM,
        )


        self.output_layer = nn.Linear(
            BLOCK_7_FACTUAL_HIDDEN_DIM,
            BLOCK_7_FACTUAL_DIM,
        )


    def forward(
        self,
        x,
    ):

        hidden = self.core(
            x
        )


        return self.output_layer(
            hidden
        )


class Block7PsychologicalHead(nn.Module):

    def __init__(self):

        super().__init__()


        self.core = Block7RepresentationCore(
            input_dim=
                BLOCK_7_CONFLUENT_DIM,

            hidden_dim=
                BLOCK_7_PSYCHOLOGICAL_HIDDEN_DIM,
        )


        self.output_layer = nn.Linear(
            BLOCK_7_PSYCHOLOGICAL_HIDDEN_DIM,
            BLOCK_7_PSYCHOLOGICAL_DIM,
        )


    def forward(
        self,
        x,
    ):

        hidden = self.core(
            x
        )


        return self.output_layer(
            hidden
        )


# =============================================================================
# Instantiate fresh modules
# =============================================================================

BLOCK_7_RESTORED_BACKBONE = (
    Block7Backbone()
)


BLOCK_7_RESTORED_GLOBAL_CONFLUENT = (
    Block7GlobalConfluent()
)


BLOCK_7_RESTORED_FACTUAL_HEAD = (
    Block7FactualHead()
)


BLOCK_7_RESTORED_PSYCHOLOGICAL_HEAD = (
    Block7PsychologicalHead()
)


# =============================================================================
# Restore persisted module states
# =============================================================================

BLOCK_7_RESTORED_BACKBONE.load_state_dict(
    BLOCK_7_CHECKPOINT[
        "backbone_state_dict"
    ],
    strict=True,
)


BLOCK_7_RESTORED_GLOBAL_CONFLUENT.load_state_dict(
    BLOCK_7_CHECKPOINT[
        "global_confluent_state_dict"
    ],
    strict=True,
)


BLOCK_7_RESTORED_FACTUAL_HEAD.load_state_dict(
    BLOCK_7_CHECKPOINT[
        "factual_head_state_dict"
    ],
    strict=True,
)


BLOCK_7_RESTORED_PSYCHOLOGICAL_HEAD.load_state_dict(
    BLOCK_7_CHECKPOINT[
        "psychological_head_state_dict"
    ],
    strict=True,
)


BLOCK_7_MODEL_STATE_RESTORED = True


# =============================================================================
# Exact state comparison helper
# =============================================================================

def block_7_state_dicts_exact(
    first_state,
    second_state,
):

    if (
        set(
            first_state.keys()
        )
        !=
        set(
            second_state.keys()
        )
    ):

        return False


    return all(
        torch.equal(
            first_state[
                parameter_name
            ]
            .detach()
            .cpu(),

            second_state[
                parameter_name
            ]
            .detach()
            .cpu(),
        )

        for parameter_name
        in first_state
    )


# =============================================================================
# Restored state versus persisted checkpoint
# =============================================================================

BLOCK_7_BACKBONE_MATCHES_CHECKPOINT = (
    block_7_state_dicts_exact(
        BLOCK_7_RESTORED_BACKBONE.state_dict(),
        BLOCK_7_CHECKPOINT[
            "backbone_state_dict"
        ],
    )
)


BLOCK_7_GLOBAL_CONFLUENT_MATCHES_CHECKPOINT = (
    block_7_state_dicts_exact(
        BLOCK_7_RESTORED_GLOBAL_CONFLUENT.state_dict(),
        BLOCK_7_CHECKPOINT[
            "global_confluent_state_dict"
        ],
    )
)


BLOCK_7_FACTUAL_MATCHES_CHECKPOINT = (
    block_7_state_dicts_exact(
        BLOCK_7_RESTORED_FACTUAL_HEAD.state_dict(),
        BLOCK_7_CHECKPOINT[
            "factual_head_state_dict"
        ],
    )
)


BLOCK_7_PSYCHOLOGICAL_MATCHES_CHECKPOINT = (
    block_7_state_dicts_exact(
        BLOCK_7_RESTORED_PSYCHOLOGICAL_HEAD.state_dict(),
        BLOCK_7_CHECKPOINT[
            "psychological_head_state_dict"
        ],
    )
)


BLOCK_7_ALL_STATES_MATCH_CHECKPOINT = all(
    [
        BLOCK_7_BACKBONE_MATCHES_CHECKPOINT,
        BLOCK_7_GLOBAL_CONFLUENT_MATCHES_CHECKPOINT,
        BLOCK_7_FACTUAL_MATCHES_CHECKPOINT,
        BLOCK_7_PSYCHOLOGICAL_MATCHES_CHECKPOINT,
    ]
)


if not BLOCK_7_ALL_STATES_MATCH_CHECKPOINT:

    raise RuntimeError(
        "One or more restored module states do not exactly match "
        "the persisted factual checkpoint."
    )


# =============================================================================
# Restored state versus trained Block 6 runtime
# =============================================================================

BLOCK_7_BACKBONE_MATCHES_RUNTIME = (
    block_7_state_dicts_exact(
        BLOCK_7_RESTORED_BACKBONE.state_dict(),
        NOTEBOOK_06_BACKBONE_FROZEN_MODULE.state_dict(),
    )
)


BLOCK_7_GLOBAL_CONFLUENT_MATCHES_RUNTIME = (
    block_7_state_dicts_exact(
        BLOCK_7_RESTORED_GLOBAL_CONFLUENT.state_dict(),
        NOTEBOOK_06_GLOBAL_CONFLUENT_FROZEN_MODULE.state_dict(),
    )
)


BLOCK_7_FACTUAL_MATCHES_RUNTIME = (
    block_7_state_dicts_exact(
        BLOCK_7_RESTORED_FACTUAL_HEAD.state_dict(),
        NOTEBOOK_06_FACTUAL_TRAINED_HEAD.state_dict(),
    )
)


BLOCK_7_PSYCHOLOGICAL_MATCHES_RUNTIME = (
    block_7_state_dicts_exact(
        BLOCK_7_RESTORED_PSYCHOLOGICAL_HEAD.state_dict(),
        NOTEBOOK_06_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.state_dict(),
    )
)


BLOCK_7_ALL_STATES_MATCH_RUNTIME = all(
    [
        BLOCK_7_BACKBONE_MATCHES_RUNTIME,
        BLOCK_7_GLOBAL_CONFLUENT_MATCHES_RUNTIME,
        BLOCK_7_FACTUAL_MATCHES_RUNTIME,
        BLOCK_7_PSYCHOLOGICAL_MATCHES_RUNTIME,
    ]
)


if not BLOCK_7_ALL_STATES_MATCH_RUNTIME:

    raise RuntimeError(
        "Freshly restored Block 7 state does not exactly match "
        "the trained Block 6 runtime state."
    )


# =============================================================================
# Restored parameter-freezing policy
# =============================================================================

for parameter in (
    BLOCK_7_RESTORED_BACKBONE.parameters()
):

    parameter.requires_grad = False


for parameter in (
    BLOCK_7_RESTORED_GLOBAL_CONFLUENT.parameters()
):

    parameter.requires_grad = False


for parameter in (
    BLOCK_7_RESTORED_PSYCHOLOGICAL_HEAD.parameters()
):

    parameter.requires_grad = False


for parameter in (
    BLOCK_7_RESTORED_FACTUAL_HEAD.parameters()
):

    parameter.requires_grad = True


BLOCK_7_BACKBONE_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in BLOCK_7_RESTORED_BACKBONE.parameters()
)


BLOCK_7_GLOBAL_CONFLUENT_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in BLOCK_7_RESTORED_GLOBAL_CONFLUENT.parameters()
)


BLOCK_7_PSYCHOLOGICAL_HEAD_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in BLOCK_7_RESTORED_PSYCHOLOGICAL_HEAD.parameters()
)


BLOCK_7_FACTUAL_HEAD_TRAINABLE = all(
    parameter.requires_grad

    for parameter
    in BLOCK_7_RESTORED_FACTUAL_HEAD.parameters()
)


BLOCK_7_FACTUAL_PARAMETER_COUNT = sum(
    parameter.numel()

    for parameter
    in BLOCK_7_RESTORED_FACTUAL_HEAD.parameters()
)


BLOCK_7_EXPECTED_FACTUAL_PARAMETER_COUNT = 34442


BLOCK_7_FACTUAL_PARAMETER_COUNT_VALID = (
    BLOCK_7_FACTUAL_PARAMETER_COUNT
    ==
    BLOCK_7_EXPECTED_FACTUAL_PARAMETER_COUNT
)


BLOCK_7_TRAINABILITY_SCOPE_VALID = all(
    [
        BLOCK_7_BACKBONE_FROZEN,
        BLOCK_7_GLOBAL_CONFLUENT_FROZEN,
        BLOCK_7_PSYCHOLOGICAL_HEAD_FROZEN,
        BLOCK_7_FACTUAL_HEAD_TRAINABLE,
        BLOCK_7_FACTUAL_PARAMETER_COUNT_VALID,
    ]
)


if not BLOCK_7_TRAINABILITY_SCOPE_VALID:

    raise RuntimeError(
        "Restored Block 7 trainability scope is invalid."
    )


# =============================================================================
# Restore AdamW optimiser
# =============================================================================

BLOCK_7_RESTORED_FACTUAL_PARAMETERS = [
    parameter

    for parameter
    in BLOCK_7_RESTORED_FACTUAL_HEAD.parameters()

    if parameter.requires_grad
]


BLOCK_7_RESTORED_OPTIMIZER = torch.optim.AdamW(
    BLOCK_7_RESTORED_FACTUAL_PARAMETERS,
    lr=float(
        BLOCK_7_CHECKPOINT[
            "learning_rate"
        ]
    ),
    weight_decay=float(
        BLOCK_7_CHECKPOINT[
            "weight_decay"
        ]
    ),
)


BLOCK_7_RESTORED_OPTIMIZER.load_state_dict(
    BLOCK_7_CHECKPOINT[
        "optimizer_state_dict"
    ]
)


BLOCK_7_OPTIMIZER_RELOADED = True


# =============================================================================
# Optimiser scope validation
# =============================================================================

BLOCK_7_FACTUAL_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter
    in BLOCK_7_RESTORED_FACTUAL_PARAMETERS
}


BLOCK_7_OPTIMIZER_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter_group
    in BLOCK_7_RESTORED_OPTIMIZER.param_groups

    for parameter
    in parameter_group[
        "params"
    ]
}


BLOCK_7_OPTIMIZER_SCOPE_VALID = (
    BLOCK_7_OPTIMIZER_PARAMETER_IDS
    ==
    BLOCK_7_FACTUAL_PARAMETER_IDS
)


BLOCK_7_OPTIMIZER_PARAMETER_COUNT = sum(
    parameter.numel()

    for parameter_group
    in BLOCK_7_RESTORED_OPTIMIZER.param_groups

    for parameter
    in parameter_group[
        "params"
    ]
)


BLOCK_7_OPTIMIZER_PARAMETER_COUNT_VALID = (
    BLOCK_7_OPTIMIZER_PARAMETER_COUNT
    ==
    BLOCK_7_EXPECTED_FACTUAL_PARAMETER_COUNT
)


if not all(
    [
        BLOCK_7_OPTIMIZER_SCOPE_VALID,
        BLOCK_7_OPTIMIZER_PARAMETER_COUNT_VALID,
    ]
):

    raise RuntimeError(
        "Restored factual optimiser scope is invalid."
    )


# =============================================================================
# Optimiser configuration validation
# =============================================================================

BLOCK_7_OPTIMIZER_TYPE_VALID = (
    BLOCK_7_CHECKPOINT[
        "optimizer_type"
    ]
    ==
    "AdamW"
)


BLOCK_7_CHECKPOINT_LEARNING_RATE = float(
    BLOCK_7_CHECKPOINT[
        "learning_rate"
    ]
)


BLOCK_7_CHECKPOINT_WEIGHT_DECAY = float(
    BLOCK_7_CHECKPOINT[
        "weight_decay"
    ]
)


BLOCK_7_LEARNING_RATE_VALID = math.isclose(
    float(
        BLOCK_7_RESTORED_OPTIMIZER.param_groups[
            0
        ][
            "lr"
        ]
    ),
    BLOCK_7_CHECKPOINT_LEARNING_RATE,
    rel_tol=0.0,
    abs_tol=1e-12,
)


BLOCK_7_WEIGHT_DECAY_VALID = math.isclose(
    float(
        BLOCK_7_RESTORED_OPTIMIZER.param_groups[
            0
        ][
            "weight_decay"
        ]
    ),
    BLOCK_7_CHECKPOINT_WEIGHT_DECAY,
    rel_tol=0.0,
    abs_tol=1e-12,
)


BLOCK_7_OPTIMIZER_CONFIGURATION_VALID = all(
    [
        BLOCK_7_OPTIMIZER_TYPE_VALID,
        BLOCK_7_LEARNING_RATE_VALID,
        BLOCK_7_WEIGHT_DECAY_VALID,
    ]
)


if not BLOCK_7_OPTIMIZER_CONFIGURATION_VALID:

    raise RuntimeError(
        "Restored factual optimiser hyperparameters do not reproduce "
        "the persisted checkpoint configuration."
    )


# =============================================================================
# Recursive state-comparison helper
# =============================================================================

def block_7_nested_exact(
    first,
    second,
):
    """
    Recursively compare optimizer-state structures exactly.
    """

    if isinstance(
        first,
        torch.Tensor,
    ):

        if not isinstance(
            second,
            torch.Tensor,
        ):

            return False


        return torch.equal(
            first.detach().cpu(),
            second.detach().cpu(),
        )


    if isinstance(
        first,
        dict,
    ):

        if not isinstance(
            second,
            dict,
        ):

            return False


        if (
            set(
                first.keys()
            )
            !=
            set(
                second.keys()
            )
        ):

            return False


        return all(
            block_7_nested_exact(
                first[
                    key
                ],
                second[
                    key
                ],
            )

            for key
            in first
        )


    if isinstance(
        first,
        (
            list,
            tuple,
        ),
    ):

        if not isinstance(
            second,
            (
                list,
                tuple,
            ),
        ):

            return False


        if len(
            first
        ) != len(
            second
        ):

            return False


        return all(
            block_7_nested_exact(
                first_value,
                second_value,
            )

            for first_value, second_value
            in zip(
                first,
                second,
            )
        )


    if isinstance(
        first,
        float,
    ) or isinstance(
        second,
        float,
    ):

        try:

            return math.isclose(
                float(
                    first
                ),
                float(
                    second
                ),
                rel_tol=0.0,
                abs_tol=1e-12,
            )

        except (
            TypeError,
            ValueError,
        ):

            return False


    return (
        first
        ==
        second
    )


# =============================================================================
# Exact optimiser-state recovery
# =============================================================================

BLOCK_7_PERSISTED_OPTIMIZER_STATE = (
    BLOCK_7_CHECKPOINT[
        "optimizer_state_dict"
    ]
)


BLOCK_7_RESTORED_OPTIMIZER_STATE = (
    BLOCK_7_RESTORED_OPTIMIZER.state_dict()
)


BLOCK_7_OPTIMIZER_STATE_EXACT = (
    block_7_nested_exact(
        BLOCK_7_RESTORED_OPTIMIZER_STATE,
        BLOCK_7_PERSISTED_OPTIMIZER_STATE,
    )
)


if not BLOCK_7_OPTIMIZER_STATE_EXACT:

    raise RuntimeError(
        "Restored AdamW state does not exactly reproduce "
        "the persisted checkpoint optimiser state."
    )


# =============================================================================
# Objective contract from persisted checkpoint
# =============================================================================
#
# Block 7 reproduces the objective policy persisted by Block 6 and verifies
# that it remains aligned with the current validated Notebook 06 contract.
# No active/deferred factual dimension is hard-coded here.
# =============================================================================

BLOCK_7_ACTIVE_DIMENSIONS = tuple(
    BLOCK_7_CHECKPOINT[
        "active_dimensions"
    ]
)


BLOCK_7_DEFERRED_DIMENSIONS = tuple(
    BLOCK_7_CHECKPOINT[
        "deferred_dimensions"
    ]
)


BLOCK_7_CURRENT_ACTIVE_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS
)


BLOCK_7_CURRENT_DEFERRED_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS
)


BLOCK_7_ACTIVE_DIMENSIONS_VALID = (
    BLOCK_7_ACTIVE_DIMENSIONS
    ==
    BLOCK_7_CURRENT_ACTIVE_DIMENSIONS
)


BLOCK_7_DEFERRED_DIMENSIONS_VALID = (
    BLOCK_7_DEFERRED_DIMENSIONS
    ==
    BLOCK_7_CURRENT_DEFERRED_DIMENSIONS
)


BLOCK_7_DIMENSION_SET = set(
    NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
)


BLOCK_7_ACTIVE_DEFERRED_BOUNDARY_VALID = all(
    [
        len(
            BLOCK_7_ACTIVE_DIMENSIONS
        )
        >
        0,

        len(
            set(
                BLOCK_7_ACTIVE_DIMENSIONS
            )
        )
        ==
        len(
            BLOCK_7_ACTIVE_DIMENSIONS
        ),

        len(
            set(
                BLOCK_7_DEFERRED_DIMENSIONS
            )
        )
        ==
        len(
            BLOCK_7_DEFERRED_DIMENSIONS
        ),

        set(
            BLOCK_7_ACTIVE_DIMENSIONS
        ).isdisjoint(
            set(
                BLOCK_7_DEFERRED_DIMENSIONS
            )
        ),

        (
            set(
                BLOCK_7_ACTIVE_DIMENSIONS
            )
            |
            set(
                BLOCK_7_DEFERRED_DIMENSIONS
            )
        )
        ==
        BLOCK_7_DIMENSION_SET,

        BLOCK_7_ACTIVE_DIMENSIONS_VALID,

        BLOCK_7_DEFERRED_DIMENSIONS_VALID,
    ]
)


if not BLOCK_7_ACTIVE_DEFERRED_BOUNDARY_VALID:

    raise RuntimeError(
        "Restored active/deferred factual objective boundary is invalid."
    )


# =============================================================================
# Objective-family weights
# =============================================================================

BLOCK_7_OBJECTIVE_WEIGHTS = deepcopy(
    BLOCK_7_CHECKPOINT[
        "objective_weights"
    ]
)


BLOCK_7_CURRENT_OBJECTIVE_WEIGHTS = deepcopy(
    NOTEBOOK_06_FACTUAL_OBJECTIVE_WEIGHTS
)


BLOCK_7_OBJECTIVE_WEIGHT_KEYS_VALID = (
    set(
        BLOCK_7_OBJECTIVE_WEIGHTS.keys()
    )
    ==
    set(
        BLOCK_7_ACTIVE_DIMENSIONS
    )
)


BLOCK_7_OBJECTIVE_WEIGHTS_VALID = all(
    target_name
    in
    BLOCK_7_CURRENT_OBJECTIVE_WEIGHTS
    and
    math.isclose(
        float(
            BLOCK_7_OBJECTIVE_WEIGHTS[
                target_name
            ]
        ),
        float(
            BLOCK_7_CURRENT_OBJECTIVE_WEIGHTS[
                target_name
            ]
        ),
        rel_tol=0.0,
        abs_tol=1e-12,
    )

    for target_name
    in BLOCK_7_ACTIVE_DIMENSIONS
)


BLOCK_7_OBJECTIVE_WEIGHT_SUM = float(
    sum(
        float(
            BLOCK_7_OBJECTIVE_WEIGHTS[
                target_name
            ]
        )

        for target_name
        in BLOCK_7_ACTIVE_DIMENSIONS
    )
)


BLOCK_7_OBJECTIVE_WEIGHT_SUM_VALID = math.isclose(
    BLOCK_7_OBJECTIVE_WEIGHT_SUM,
    1.0,
    rel_tol=0.0,
    abs_tol=1e-12,
)


if not all(
    [
        BLOCK_7_OBJECTIVE_WEIGHT_KEYS_VALID,
        BLOCK_7_OBJECTIVE_WEIGHTS_VALID,
        BLOCK_7_OBJECTIVE_WEIGHT_SUM_VALID,
    ]
):

    raise RuntimeError(
        "Persisted factual objective weights do not reproduce "
        "the validated Block 5 / Block 6 contract."
    )


# =============================================================================
# Positive-class imbalance policy
# =============================================================================

BLOCK_7_POSITIVE_CLASS_WEIGHTS = deepcopy(
    BLOCK_7_CHECKPOINT[
        "positive_class_weights"
    ]
)


BLOCK_7_CURRENT_POSITIVE_CLASS_WEIGHTS = deepcopy(
    NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS
)


BLOCK_7_WEIGHTED_BINARY_DIMENSIONS = tuple(
    BLOCK_7_CHECKPOINT[
        "weighted_binary_dimensions"
    ]
)


BLOCK_7_EXPECTED_WEIGHTED_BINARY_DIMENSIONS = tuple(
    target_name
    for target_name
    in NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS
    if target_name
    in BLOCK_7_CURRENT_POSITIVE_CLASS_WEIGHTS
)


BLOCK_7_POSITIVE_CLASS_WEIGHT_KEYS_VALID = (
    set(
        BLOCK_7_POSITIVE_CLASS_WEIGHTS.keys()
    ).issubset(
        set(
            NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS
        )
    )
)


BLOCK_7_POSITIVE_CLASS_WEIGHT_VALUES_VALID = all(
    isinstance(
        weight_value,
        (
            int,
            float,
        ),
    )
    and
    math.isfinite(
        float(
            weight_value
        )
    )
    and
    float(
        weight_value
    )
    >
    0.0

    for weight_value
    in BLOCK_7_POSITIVE_CLASS_WEIGHTS.values()
)


BLOCK_7_POSITIVE_CLASS_WEIGHTS_ALIGNED = all(
    target_name
    in
    BLOCK_7_CURRENT_POSITIVE_CLASS_WEIGHTS
    and
    math.isclose(
        float(
            BLOCK_7_POSITIVE_CLASS_WEIGHTS[
                target_name
            ]
        ),
        float(
            BLOCK_7_CURRENT_POSITIVE_CLASS_WEIGHTS[
                target_name
            ]
        ),
        rel_tol=0.0,
        abs_tol=1e-12,
    )

    for target_name
    in BLOCK_7_POSITIVE_CLASS_WEIGHTS
)


BLOCK_7_WEIGHTED_BINARY_DIMENSIONS_VALID = (
    BLOCK_7_WEIGHTED_BINARY_DIMENSIONS
    ==
    BLOCK_7_EXPECTED_WEIGHTED_BINARY_DIMENSIONS
)


BLOCK_7_POSITIVE_CLASS_WEIGHT_POLICY_VALID = all(
    [
        BLOCK_7_POSITIVE_CLASS_WEIGHT_KEYS_VALID,
        BLOCK_7_POSITIVE_CLASS_WEIGHT_VALUES_VALID,
        BLOCK_7_POSITIVE_CLASS_WEIGHTS_ALIGNED,
        BLOCK_7_WEIGHTED_BINARY_DIMENSIONS_VALID,
    ]
)


if not BLOCK_7_POSITIVE_CLASS_WEIGHT_POLICY_VALID:

    raise RuntimeError(
        "Persisted factual positive-class weighting does not reproduce "
        "the validated upstream objective policy."
    )


# Backward-compatible prediction alias.
BLOCK_7_PREDICTION_POSITIVE_WEIGHT = (
    float(
        BLOCK_7_POSITIVE_CLASS_WEIGHTS[
            "prediction"
        ]
    )
    if "prediction"
    in BLOCK_7_POSITIVE_CLASS_WEIGHTS
    else None
)


BLOCK_7_PREDICTION_WEIGHT_VALID = (
    (
        BLOCK_7_PREDICTION_POSITIVE_WEIGHT is None
        and
        BLOCK_7_CHECKPOINT.get(
            "prediction_positive_weight"
        )
        is None
    )
    or
    (
        BLOCK_7_PREDICTION_POSITIVE_WEIGHT is not None
        and
        BLOCK_7_CHECKPOINT.get(
            "prediction_positive_weight"
        )
        is not None
        and
        math.isclose(
            float(
                BLOCK_7_CHECKPOINT[
                    "prediction_positive_weight"
                ]
            ),
            BLOCK_7_PREDICTION_POSITIVE_WEIGHT,
            rel_tol=0.0,
            abs_tol=1e-12,
        )
    )
)


if not BLOCK_7_PREDICTION_WEIGHT_VALID:

    raise RuntimeError(
        "Backward-compatible prediction positive-class weight alias "
        "is inconsistent with the persisted weight mapping."
    )


# =============================================================================
# Training-policy reproduction
# =============================================================================

BLOCK_7_EPOCH_COUNT = int(
    BLOCK_7_CHECKPOINT[
        "training_epoch_count"
    ]
)


BLOCK_7_EPOCH_COUNT_VALID = (
    BLOCK_7_EPOCH_COUNT > 0
)


BLOCK_7_WITHIN_ARTICLE_SHUFFLE_VALID = (
    BLOCK_7_CHECKPOINT[
        "within_article_shuffle"
    ]
    is False
)


BLOCK_7_ARTICLE_SEQUENCE_VALID = (
    BLOCK_7_CHECKPOINT[
        "article_sequence_preserved"
    ]
    is True
)


BLOCK_7_MAX_GRAD_NORM = float(
    BLOCK_7_CHECKPOINT[
        "maximum_gradient_norm"
    ]
)


BLOCK_7_MAX_GRAD_NORM_VALID = (
    math.isfinite(
        BLOCK_7_MAX_GRAD_NORM
    )
    and
    BLOCK_7_MAX_GRAD_NORM
    >
    0.0
)


BLOCK_7_METADATA_TRAINING_SCOPE = (
    BLOCK_7_METADATA[
        "training_scope"
    ]
)


def block_7_article_id_from_sentence_id(
    sentence_id,
):

    if not isinstance(
        sentence_id,
        str,
    ) or not sentence_id:

        raise ValueError(
            "Notebook 06 sentence IDs must be non-empty strings."
        )


    if "::" in sentence_id:

        return sentence_id.split(
            "::",
            1,
        )[0]


    return sentence_id


BLOCK_7_RUNTIME_SENTENCE_IDS = tuple(
    NOTEBOOK_06_SENTENCE_IDS
)


BLOCK_7_RUNTIME_TRAINING_SENTENCE_COUNT = len(
    BLOCK_7_RUNTIME_SENTENCE_IDS
)


BLOCK_7_RUNTIME_ARTICLE_IDS = tuple(
    dict.fromkeys(
        block_7_article_id_from_sentence_id(
            sentence_id
        )

        for sentence_id
        in BLOCK_7_RUNTIME_SENTENCE_IDS
    )
)


BLOCK_7_RUNTIME_TRAINING_ARTICLE_COUNT = len(
    BLOCK_7_RUNTIME_ARTICLE_IDS
)


BLOCK_7_CHECKPOINT_TRAINING_ARTICLE_COUNT = int(
    BLOCK_7_CHECKPOINT[
        "training_article_count"
    ]
)


BLOCK_7_CHECKPOINT_TRAINING_SENTENCE_COUNT = int(
    BLOCK_7_CHECKPOINT[
        "training_sentence_count"
    ]
)


BLOCK_7_CHECKPOINT_TRAINING_ARTICLE_IDS = tuple(
    BLOCK_7_CHECKPOINT[
        "training_article_ids"
    ]
)


BLOCK_7_METADATA_TRAINING_SCOPE_VALID = all(
    [
        int(
            BLOCK_7_METADATA_TRAINING_SCOPE[
                "articles"
            ]
        )
        ==
        BLOCK_7_RUNTIME_TRAINING_ARTICLE_COUNT
        ==
        BLOCK_7_CHECKPOINT_TRAINING_ARTICLE_COUNT,

        int(
            BLOCK_7_METADATA_TRAINING_SCOPE[
                "sentences"
            ]
        )
        ==
        BLOCK_7_RUNTIME_TRAINING_SENTENCE_COUNT
        ==
        BLOCK_7_CHECKPOINT_TRAINING_SENTENCE_COUNT
        ==
        int(
            NOTEBOOK_06_SENTENCE_COUNT
        ),

        tuple(
            BLOCK_7_METADATA_TRAINING_SCOPE.get(
                "article_ids",
                [],
            )
        )
        ==
        BLOCK_7_RUNTIME_ARTICLE_IDS
        ==
        BLOCK_7_CHECKPOINT_TRAINING_ARTICLE_IDS,

        int(
            BLOCK_7_METADATA_TRAINING_SCOPE[
                "validation_sentences"
            ]
        )
        ==
        0,

        int(
            BLOCK_7_METADATA_TRAINING_SCOPE[
                "test_sentences"
            ]
        )
        ==
        0,

        int(
            BLOCK_7_METADATA_TRAINING_SCOPE[
                "epochs"
            ]
        )
        ==
        BLOCK_7_EPOCH_COUNT,

        BLOCK_7_METADATA_TRAINING_SCOPE[
            "within_article_shuffle"
        ]
        is False,

        BLOCK_7_METADATA_TRAINING_SCOPE[
            "article_sequence_preserved"
        ]
        is True,
    ]
)


BLOCK_7_METADATA_MAX_PRECLIP_NORM = float(
    BLOCK_7_METADATA[
        "gradient_control"
    ][
        "maximum_observed_preclip_norm"
    ]
)


BLOCK_7_METADATA_MAX_PRECLIP_NORM_VALID = (
    math.isfinite(
        BLOCK_7_METADATA_MAX_PRECLIP_NORM
    )
    and
    BLOCK_7_METADATA_MAX_PRECLIP_NORM
    >=
    0.0
)


BLOCK_7_TRAINING_POLICY_PRESERVED = all(
    [
        BLOCK_7_EPOCH_COUNT_VALID,
        BLOCK_7_WITHIN_ARTICLE_SHUFFLE_VALID,
        BLOCK_7_ARTICLE_SEQUENCE_VALID,
        BLOCK_7_MAX_GRAD_NORM_VALID,
        BLOCK_7_METADATA_TRAINING_SCOPE_VALID,
        BLOCK_7_METADATA_MAX_PRECLIP_NORM_VALID,
        BLOCK_7_POSITIVE_CLASS_WEIGHT_POLICY_VALID,
        BLOCK_7_PREDICTION_WEIGHT_VALID,
        BLOCK_7_OBJECTIVE_WEIGHTS_VALID,
    ]
)


if not BLOCK_7_TRAINING_POLICY_PRESERVED:

    raise RuntimeError(
        "Persisted factual training policy was not preserved."
    )


# =============================================================================
# Prepare target / mask tensors
# =============================================================================

BLOCK_7_FACTUAL_TARGETS = (
    NOTEBOOK_06_FACTUAL_TARGET_TENSOR
    .detach()
    .clone()
)


BLOCK_7_FACTUAL_MASKS = (
    NOTEBOOK_06_FACTUAL_MASK_TENSOR
    .detach()
    .clone()
)


BLOCK_7_FORWARD_INPUT = (
    NOTEBOOK_06_FACTUAL_FORWARD_INPUT
    .detach()
    .clone()
)


BLOCK_7_EXPECTED_FORWARD_INPUT_SHAPE = (
    NOTEBOOK_06_SENTENCE_COUNT,
    256,
)


BLOCK_7_EXPECTED_TARGET_SHAPE = (
    NOTEBOOK_06_SENTENCE_COUNT,
    10,
)


BLOCK_7_FORWARD_INPUT_SHAPE_VALID = (
    tuple(
        BLOCK_7_FORWARD_INPUT.shape
    )
    ==
    BLOCK_7_EXPECTED_FORWARD_INPUT_SHAPE
)


BLOCK_7_TARGET_SHAPE_VALID = (
    tuple(
        BLOCK_7_FACTUAL_TARGETS.shape
    )
    ==
    BLOCK_7_EXPECTED_TARGET_SHAPE
)


BLOCK_7_MASK_SHAPE_VALID = (
    tuple(
        BLOCK_7_FACTUAL_MASKS.shape
    )
    ==
    BLOCK_7_EXPECTED_TARGET_SHAPE
)


if not all(
    [
        BLOCK_7_FORWARD_INPUT_SHAPE_VALID,
        BLOCK_7_TARGET_SHAPE_VALID,
        BLOCK_7_MASK_SHAPE_VALID,
    ]
):

    raise RuntimeError(
        "Block 7 factual reproduction tensors have invalid shapes."
    )


# =============================================================================
# Device alignment
# =============================================================================

BLOCK_7_DEVICE = next(
    BLOCK_7_RESTORED_FACTUAL_HEAD.parameters()
).device


BLOCK_7_DTYPE = next(
    BLOCK_7_RESTORED_FACTUAL_HEAD.parameters()
).dtype


BLOCK_7_FORWARD_INPUT = (
    BLOCK_7_FORWARD_INPUT.to(
        device=
            BLOCK_7_DEVICE,
        dtype=
            BLOCK_7_DTYPE,
    )
)


BLOCK_7_FACTUAL_TARGETS = (
    BLOCK_7_FACTUAL_TARGETS.to(
        device=
            BLOCK_7_DEVICE,
        dtype=
            BLOCK_7_DTYPE,
    )
)


BLOCK_7_FACTUAL_MASKS = (
    BLOCK_7_FACTUAL_MASKS.to(
        device=
            BLOCK_7_DEVICE,
    )
)


BLOCK_7_POSITIVE_CLASS_WEIGHT_TENSORS = {
    target_name:
        torch.tensor(
            float(
                weight_value
            ),
            dtype=
                BLOCK_7_DTYPE,
            device=
                BLOCK_7_DEVICE,
        )

    for target_name, weight_value
    in BLOCK_7_POSITIVE_CLASS_WEIGHTS.items()
}


BLOCK_7_PREDICTION_POS_WEIGHT_TENSOR = (
    BLOCK_7_POSITIVE_CLASS_WEIGHT_TENSORS.get(
        "prediction"
    )
)


# =============================================================================
# Factual dimension index
# =============================================================================

BLOCK_7_DIMENSION_INDEX = {
    dimension_name:
        index

    for index, dimension_name
    in enumerate(
        NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
    )
}


# =============================================================================
# Objective helpers
# =============================================================================

def block_7_masked_bce_with_logits(
    logits,
    targets,
    mask,
    pos_weight=None,
):

    if mask.dtype != torch.bool:

        mask = mask.bool()


    observed_count = int(
        mask.sum()
        .item()
    )


    if observed_count <= 0:

        raise RuntimeError(
            "Restored binary factual objective has no observed targets."
        )


    return F.binary_cross_entropy_with_logits(
        logits[
            mask
        ],
        targets[
            mask
        ],
        pos_weight=
            pos_weight,
        reduction=
            "mean",
    )


def block_7_masked_mse(
    predictions,
    targets,
    mask,
):

    if mask.dtype != torch.bool:

        mask = mask.bool()


    observed_count = int(
        mask.sum()
        .item()
    )


    if observed_count <= 0:

        raise RuntimeError(
            "Restored continuous factual objective has no observed targets."
        )


    return F.mse_loss(
        predictions[
            mask
        ],
        targets[
            mask
        ],
        reduction=
            "mean",
    )


def block_7_calculate_objective(
    factual_output,
):

    family_losses = {}


    for target_name in (
        NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS
    ):

        target_index = (
            BLOCK_7_DIMENSION_INDEX[
                target_name
            ]
        )


        positive_weight = (
            BLOCK_7_POSITIVE_CLASS_WEIGHT_TENSORS.get(
                target_name
            )
        )


        family_losses[
            target_name
        ] = block_7_masked_bce_with_logits(
            logits=
                factual_output[
                    :,
                    target_index,
                ],

            targets=
                BLOCK_7_FACTUAL_TARGETS[
                    :,
                    target_index,
                ],

            mask=
                BLOCK_7_FACTUAL_MASKS[
                    :,
                    target_index,
                ],

            pos_weight=
                positive_weight,
        )


    for target_name in (
        NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS
    ):

        target_index = (
            BLOCK_7_DIMENSION_INDEX[
                target_name
            ]
        )


        family_losses[
            target_name
        ] = block_7_masked_mse(
            predictions=
                factual_output[
                    :,
                    target_index,
                ],

            targets=
                BLOCK_7_FACTUAL_TARGETS[
                    :,
                    target_index,
                ],

            mask=
                BLOCK_7_FACTUAL_MASKS[
                    :,
                    target_index,
                ],
        )


    if (
        set(
            family_losses.keys()
        )
        !=
        set(
            BLOCK_7_ACTIVE_DIMENSIONS
        )
    ):

        raise RuntimeError(
            "Restored factual objective calculation does not reproduce "
            "exactly the persisted active objective families."
        )


    total_objective = sum(
        float(
            BLOCK_7_OBJECTIVE_WEIGHTS[
                target_name
            ]
        )
        *
        family_losses[
            target_name
        ]

        for target_name
        in BLOCK_7_ACTIVE_DIMENSIONS
    )


    return (
        total_objective,
        family_losses,
    )


# =============================================================================
# Snapshot restored parameters before reproduction forward pass
# =============================================================================

def block_7_snapshot_module(
    module,
):

    return {
        parameter_name:
            parameter.detach()
            .cpu()
            .clone()

        for parameter_name, parameter
        in module.named_parameters()
    }


BLOCK_7_BACKBONE_BEFORE = (
    block_7_snapshot_module(
        BLOCK_7_RESTORED_BACKBONE
    )
)


BLOCK_7_GLOBAL_CONFLUENT_BEFORE = (
    block_7_snapshot_module(
        BLOCK_7_RESTORED_GLOBAL_CONFLUENT
    )
)


BLOCK_7_FACTUAL_BEFORE = (
    block_7_snapshot_module(
        BLOCK_7_RESTORED_FACTUAL_HEAD
    )
)


BLOCK_7_PSYCHOLOGICAL_BEFORE = (
    block_7_snapshot_module(
        BLOCK_7_RESTORED_PSYCHOLOGICAL_HEAD
    )
)


# =============================================================================
# Controlled post-training objective reproduction
# =============================================================================

BLOCK_7_RESTORED_BACKBONE.eval()

BLOCK_7_RESTORED_GLOBAL_CONFLUENT.eval()

BLOCK_7_RESTORED_FACTUAL_HEAD.eval()

BLOCK_7_RESTORED_PSYCHOLOGICAL_HEAD.eval()


with torch.no_grad():

    BLOCK_7_RESTORED_FACTUAL_OUTPUT = (
        BLOCK_7_RESTORED_FACTUAL_HEAD(
            BLOCK_7_FORWARD_INPUT
        )
    )


    (
        BLOCK_7_RESTORED_TOTAL_OBJECTIVE_TENSOR,
        BLOCK_7_RESTORED_FAMILY_LOSSES_TENSOR,
    ) = block_7_calculate_objective(
        BLOCK_7_RESTORED_FACTUAL_OUTPUT
    )


NOTEBOOK_06_BLOCK_7_FORWARD_EXECUTED = True

NOTEBOOK_06_BLOCK_7_OBJECTIVE_RECALCULATED = True


# =============================================================================
# Reproduced objective values
# =============================================================================

BLOCK_7_RESTORED_TOTAL_OBJECTIVE = float(
    BLOCK_7_RESTORED_TOTAL_OBJECTIVE_TENSOR
    .detach()
    .cpu()
    .item()
)


BLOCK_7_RESTORED_FAMILY_LOSSES = {
    target_name:
        float(
            BLOCK_7_RESTORED_FAMILY_LOSSES_TENSOR[
                target_name
            ]
            .detach()
            .cpu()
            .item()
        )

    for target_name
    in BLOCK_7_ACTIVE_DIMENSIONS
}


BLOCK_7_EXPECTED_TOTAL_OBJECTIVE = float(
    BLOCK_7_CHECKPOINT[
        "final_objective"
    ]
)


BLOCK_7_EXPECTED_FAMILY_LOSSES = deepcopy(
    BLOCK_7_CHECKPOINT[
        "final_family_losses"
    ]
)


# =============================================================================
# Compare persisted checkpoint with Block 6 runtime values
# =============================================================================

BLOCK_7_CHECKPOINT_TOTAL_MATCHES_RUNTIME = math.isclose(
    BLOCK_7_EXPECTED_TOTAL_OBJECTIVE,
    float(
        NOTEBOOK_06_FACTUAL_FINAL_OBJECTIVE
    ),
    rel_tol=0.0,
    abs_tol=
        NOTEBOOK_06_FACTUAL_REPRODUCTION_TOLERANCE,
)


BLOCK_7_CHECKPOINT_FAMILY_MATCHES_RUNTIME = all(
    math.isclose(
        float(
            BLOCK_7_EXPECTED_FAMILY_LOSSES[
                target_name
            ]
        ),
        float(
            NOTEBOOK_06_FACTUAL_FINAL_FAMILY_LOSSES[
                target_name
            ]
        ),
        rel_tol=0.0,
        abs_tol=
            NOTEBOOK_06_FACTUAL_REPRODUCTION_TOLERANCE,
    )

    for target_name
    in BLOCK_7_ACTIVE_DIMENSIONS
)


if not all(
    [
        BLOCK_7_CHECKPOINT_TOTAL_MATCHES_RUNTIME,
        BLOCK_7_CHECKPOINT_FAMILY_MATCHES_RUNTIME,
    ]
):

    raise RuntimeError(
        "Persisted Block 6 objective values do not match "
        "the trained Block 6 runtime state."
    )


# =============================================================================
# Exact objective reproduction
# =============================================================================

BLOCK_7_TOTAL_OBJECTIVE_REPRODUCED = math.isclose(
    BLOCK_7_RESTORED_TOTAL_OBJECTIVE,
    BLOCK_7_EXPECTED_TOTAL_OBJECTIVE,
    rel_tol=0.0,
    abs_tol=
        NOTEBOOK_06_FACTUAL_REPRODUCTION_TOLERANCE,
)


BLOCK_7_FAMILY_LOSS_REPRODUCTION = {
    target_name:
        math.isclose(
            BLOCK_7_RESTORED_FAMILY_LOSSES[
                target_name
            ],
            float(
                BLOCK_7_EXPECTED_FAMILY_LOSSES[
                    target_name
                ]
            ),
            rel_tol=0.0,
            abs_tol=
                NOTEBOOK_06_FACTUAL_REPRODUCTION_TOLERANCE,
        )

    for target_name
    in BLOCK_7_ACTIVE_DIMENSIONS
}


BLOCK_7_ALL_FAMILY_LOSSES_REPRODUCED = all(
    BLOCK_7_FAMILY_LOSS_REPRODUCTION.values()
)


if not all(
    [
        BLOCK_7_TOTAL_OBJECTIVE_REPRODUCED,
        BLOCK_7_ALL_FAMILY_LOSSES_REPRODUCED,
    ]
):

    raise RuntimeError(
        "Restored factual model does not reproduce "
        "the persisted final factual objective."
    )


# =============================================================================
# Deferred-dimension exclusion
# =============================================================================

BLOCK_7_DEFERRED_DIMENSIONS_EXCLUDED = all(
    target_name
    not in
    BLOCK_7_RESTORED_FAMILY_LOSSES

    for target_name
    in BLOCK_7_DEFERRED_DIMENSIONS
)


if not BLOCK_7_DEFERRED_DIMENSIONS_EXCLUDED:

    raise RuntimeError(
        "A deferred factual dimension entered the restored objective."
    )


# =============================================================================
# Methodological boundary validation
# =============================================================================

BLOCK_7_CHECKPOINT_BOUNDARY = (
    BLOCK_7_CHECKPOINT[
        "methodological_boundary"
    ]
)


BLOCK_7_METADATA_BOUNDARY = (
    BLOCK_7_METADATA[
        "methodological_boundary"
    ]
)


BLOCK_7_METHOD_BOUNDARY_CHECKPOINT_VALID = all(
    [
        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "factual_head_trained"
            ]
            is True
        ),

        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "psychological_head_trained"
            ]
            is False
        ),

        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "backbone_trained"
            ]
            is False
        ),

        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "global_confluent_trained"
            ]
            is False
        ),

        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "group_conditioned_path_executed"
            ]
            is False
        ),

        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "social_path_trained"
            ]
            is False
        ),

        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "transformative_mechanism_executed"
            ]
            is False
        ),

        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "transformative_weights_trained"
            ]
            is False
        ),

        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "recurrent_states_trained"
            ]
            is False
        ),

        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "held_out_evaluation_executed"
            ]
            is False
        ),

        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "validated_model_checkpoint"
            ]
            is False
        ),

        (
            BLOCK_7_CHECKPOINT_BOUNDARY[
                "empirical_validity"
            ]
            is False
        ),
    ]
)


BLOCK_7_METHOD_BOUNDARY_METADATA_VALID = all(
    [
        (
            BLOCK_7_METADATA_BOUNDARY[
                "controlled_experimental_checkpoint"
            ]
            is True
        ),

        (
            BLOCK_7_METADATA_BOUNDARY[
                "validated_model_checkpoint"
            ]
            is False
        ),

        (
            BLOCK_7_METADATA_BOUNDARY[
                "validation_early_stopping"
            ]
            is False
        ),

        (
            BLOCK_7_METADATA_BOUNDARY[
                "held_out_evaluation"
            ]
            is False
        ),

        (
            BLOCK_7_METADATA_BOUNDARY[
                "group_conditioned_executed"
            ]
            is False
        ),

        (
            BLOCK_7_METADATA_BOUNDARY[
                "social_path_trained"
            ]
            is False
        ),

        (
            BLOCK_7_METADATA_BOUNDARY[
                "transformative_executed"
            ]
            is False
        ),

        (
            BLOCK_7_METADATA_BOUNDARY[
                "transformative_weights_trained"
            ]
            is False
        ),

        (
            BLOCK_7_METADATA_BOUNDARY[
                "recurrent_states_trained"
            ]
            is False
        ),

        (
            BLOCK_7_METADATA_BOUNDARY[
                "empirical_validity"
            ]
            is False
        ),
    ]
)


BLOCK_7_METHOD_BOUNDARY_PRESERVED = all(
    [
        BLOCK_7_METHOD_BOUNDARY_CHECKPOINT_VALID,
        BLOCK_7_METHOD_BOUNDARY_METADATA_VALID,
    ]
)


if not BLOCK_7_METHOD_BOUNDARY_PRESERVED:

    raise RuntimeError(
        "Persisted Block 6 methodological boundary was not preserved."
    )


# =============================================================================
# Metadata / checkpoint alignment
# =============================================================================

BLOCK_7_METADATA_CHECKPOINT_TYPE_ALIGNED = (
    BLOCK_7_METADATA[
        "checkpoint_type"
    ]
    ==
    BLOCK_7_CHECKPOINT[
        "checkpoint_type"
    ]
)


BLOCK_7_METADATA_POLICY_VERSION_ALIGNED = (
    BLOCK_7_METADATA[
        "training_policy_version"
    ]
    ==
    BLOCK_7_CHECKPOINT[
        "training_policy_version"
    ]
)


BLOCK_7_METADATA_ACTIVE_DIMENSIONS_ALIGNED = (
    tuple(
        BLOCK_7_METADATA[
            "supervised_objectives"
        ][
            "active_dimensions"
        ]
    )
    ==
    BLOCK_7_ACTIVE_DIMENSIONS
)


BLOCK_7_METADATA_DEFERRED_DIMENSIONS_ALIGNED = (
    tuple(
        BLOCK_7_METADATA[
            "supervised_objectives"
        ][
            "deferred_dimensions"
        ]
    )
    ==
    BLOCK_7_DEFERRED_DIMENSIONS
)


BLOCK_7_METADATA_OBJECTIVE_WEIGHTS_ALIGNED = all(
    target_name
    in
    BLOCK_7_METADATA[
        "supervised_objectives"
    ][
        "objective_weights"
    ]
    and
    math.isclose(
        float(
            BLOCK_7_METADATA[
                "supervised_objectives"
            ][
                "objective_weights"
            ][
                target_name
            ]
        ),
        float(
            BLOCK_7_OBJECTIVE_WEIGHTS[
                target_name
            ]
        ),
        rel_tol=0.0,
        abs_tol=1e-12,
    )

    for target_name
    in BLOCK_7_ACTIVE_DIMENSIONS
)


BLOCK_7_METADATA_POSITIVE_CLASS_WEIGHTS = deepcopy(
    BLOCK_7_METADATA[
        "supervised_objectives"
    ].get(
        "positive_class_weights",
        {},
    )
)


BLOCK_7_METADATA_POSITIVE_CLASS_WEIGHTS_ALIGNED = (
    set(
        BLOCK_7_METADATA_POSITIVE_CLASS_WEIGHTS.keys()
    )
    ==
    set(
        BLOCK_7_POSITIVE_CLASS_WEIGHTS.keys()
    )
    and
    all(
        math.isclose(
            float(
                BLOCK_7_METADATA_POSITIVE_CLASS_WEIGHTS[
                    target_name
                ]
            ),
            float(
                BLOCK_7_POSITIVE_CLASS_WEIGHTS[
                    target_name
                ]
            ),
            rel_tol=0.0,
            abs_tol=1e-12,
        )

        for target_name
        in BLOCK_7_POSITIVE_CLASS_WEIGHTS
    )
)


BLOCK_7_METADATA_WEIGHTED_BINARY_DIMENSIONS_ALIGNED = (
    tuple(
        BLOCK_7_METADATA[
            "supervised_objectives"
        ].get(
            "weighted_binary_dimensions",
            [],
        )
    )
    ==
    BLOCK_7_WEIGHTED_BINARY_DIMENSIONS
)


BLOCK_7_METADATA_PREDICTION_WEIGHT = (
    BLOCK_7_METADATA[
        "supervised_objectives"
    ].get(
        "prediction_positive_weight"
    )
)


BLOCK_7_METADATA_PREDICTION_WEIGHT_ALIGNED = (
    (
        BLOCK_7_PREDICTION_POSITIVE_WEIGHT is None
        and
        BLOCK_7_METADATA_PREDICTION_WEIGHT is None
    )
    or
    (
        BLOCK_7_PREDICTION_POSITIVE_WEIGHT is not None
        and
        BLOCK_7_METADATA_PREDICTION_WEIGHT is not None
        and
        math.isclose(
            float(
                BLOCK_7_METADATA_PREDICTION_WEIGHT
            ),
            BLOCK_7_PREDICTION_POSITIVE_WEIGHT,
            rel_tol=0.0,
            abs_tol=1e-12,
        )
    )
)


BLOCK_7_METADATA_CHECKPOINT_ALIGNED = all(
    [
        BLOCK_7_METADATA_CHECKPOINT_TYPE_ALIGNED,
        BLOCK_7_METADATA_POLICY_VERSION_ALIGNED,
        BLOCK_7_METADATA_ACTIVE_DIMENSIONS_ALIGNED,
        BLOCK_7_METADATA_DEFERRED_DIMENSIONS_ALIGNED,
        BLOCK_7_METADATA_OBJECTIVE_WEIGHTS_ALIGNED,
        BLOCK_7_METADATA_POSITIVE_CLASS_WEIGHTS_ALIGNED,
        BLOCK_7_METADATA_WEIGHTED_BINARY_DIMENSIONS_ALIGNED,
        BLOCK_7_METADATA_PREDICTION_WEIGHT_ALIGNED,
    ]
)


if not BLOCK_7_METADATA_CHECKPOINT_ALIGNED:

    raise RuntimeError(
        "Persisted factual checkpoint and metadata are not aligned."
    )


# =============================================================================
# No-update validation
# =============================================================================

BLOCK_7_BACKBONE_AFTER = (
    block_7_snapshot_module(
        BLOCK_7_RESTORED_BACKBONE
    )
)


BLOCK_7_GLOBAL_CONFLUENT_AFTER = (
    block_7_snapshot_module(
        BLOCK_7_RESTORED_GLOBAL_CONFLUENT
    )
)


BLOCK_7_FACTUAL_AFTER = (
    block_7_snapshot_module(
        BLOCK_7_RESTORED_FACTUAL_HEAD
    )
)


BLOCK_7_PSYCHOLOGICAL_AFTER = (
    block_7_snapshot_module(
        BLOCK_7_RESTORED_PSYCHOLOGICAL_HEAD
    )
)


BLOCK_7_BACKBONE_UNCHANGED = (
    block_7_state_dicts_exact(
        BLOCK_7_BACKBONE_BEFORE,
        BLOCK_7_BACKBONE_AFTER,
    )
)


BLOCK_7_GLOBAL_CONFLUENT_UNCHANGED = (
    block_7_state_dicts_exact(
        BLOCK_7_GLOBAL_CONFLUENT_BEFORE,
        BLOCK_7_GLOBAL_CONFLUENT_AFTER,
    )
)


BLOCK_7_FACTUAL_UNCHANGED = (
    block_7_state_dicts_exact(
        BLOCK_7_FACTUAL_BEFORE,
        BLOCK_7_FACTUAL_AFTER,
    )
)


BLOCK_7_PSYCHOLOGICAL_UNCHANGED = (
    block_7_state_dicts_exact(
        BLOCK_7_PSYCHOLOGICAL_BEFORE,
        BLOCK_7_PSYCHOLOGICAL_AFTER,
    )
)


BLOCK_7_ALL_PARAMETERS_UNCHANGED = all(
    [
        BLOCK_7_BACKBONE_UNCHANGED,
        BLOCK_7_GLOBAL_CONFLUENT_UNCHANGED,
        BLOCK_7_FACTUAL_UNCHANGED,
        BLOCK_7_PSYCHOLOGICAL_UNCHANGED,
    ]
)


if not BLOCK_7_ALL_PARAMETERS_UNCHANGED:

    raise RuntimeError(
        "One or more restored model parameters changed during "
        "Block 7 reproducibility validation."
    )


# =============================================================================
# No-gradient validation
# =============================================================================

BLOCK_7_FACTUAL_GRADIENTS_ABSENT = all(
    parameter.grad is None

    for parameter
    in BLOCK_7_RESTORED_FACTUAL_HEAD.parameters()
)


if not BLOCK_7_FACTUAL_GRADIENTS_ABSENT:

    raise RuntimeError(
        "Unexpected factual-head gradients exist in Block 7."
    )


# =============================================================================
# Final execution boundary
# =============================================================================

NOTEBOOK_06_BLOCK_7_ZERO_GRAD_EXECUTED = False

NOTEBOOK_06_BLOCK_7_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_BLOCK_7_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_06_BLOCK_7_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_BLOCK_7_ADDITIONAL_TRAINING_EXECUTED = False

NOTEBOOK_06_BLOCK_7_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_BLOCK_7_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_06_BLOCK_7_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_06_BLOCK_7_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

NOTEBOOK_06_BLOCK_7_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_06_BLOCK_7_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_06_BLOCK_7_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Overall reproducibility state
# =============================================================================

NOTEBOOK_06_FACTUAL_CHECKPOINT_REPRODUCIBLE = all(
    [
        BLOCK_7_CHECKPOINT_RELOADED,
        BLOCK_7_METADATA_RELOADED,
        BLOCK_7_CHECKPOINT_CONTRACT_VALID,
        BLOCK_7_CHECKPOINT_TYPE_VALID,
        BLOCK_7_ALL_STATES_MATCH_CHECKPOINT,
        BLOCK_7_ALL_STATES_MATCH_RUNTIME,
        BLOCK_7_TRAINABILITY_SCOPE_VALID,
        BLOCK_7_OPTIMIZER_RELOADED,
        BLOCK_7_OPTIMIZER_STATE_EXACT,
        BLOCK_7_OPTIMIZER_SCOPE_VALID,
        BLOCK_7_OPTIMIZER_CONFIGURATION_VALID,
        BLOCK_7_TRAINING_POLICY_PRESERVED,
        BLOCK_7_TOTAL_OBJECTIVE_REPRODUCED,
        BLOCK_7_ALL_FAMILY_LOSSES_REPRODUCED,
        BLOCK_7_DEFERRED_DIMENSIONS_EXCLUDED,
        BLOCK_7_METHOD_BOUNDARY_PRESERVED,
        BLOCK_7_METADATA_CHECKPOINT_ALIGNED,
        BLOCK_7_ALL_PARAMETERS_UNCHANGED,
        BLOCK_7_FACTUAL_GRADIENTS_ABSENT,
    ]
)


# =============================================================================
# Final Block 7 validation
# =============================================================================

NOTEBOOK_06_BLOCK_7_ERRORS = []


block_7_validation_checks = {
    "checkpoint_not_reloaded":
        BLOCK_7_CHECKPOINT_RELOADED,

    "metadata_not_reloaded":
        BLOCK_7_METADATA_RELOADED,

    "checkpoint_contract_invalid":
        BLOCK_7_CHECKPOINT_CONTRACT_VALID,

    "checkpoint_type_invalid":
        BLOCK_7_CHECKPOINT_TYPE_VALID,

    "checkpoint_incorrectly_validated":
        not BLOCK_7_VALIDATED_MODEL_CHECKPOINT,

    "backbone_checkpoint_mismatch":
        BLOCK_7_BACKBONE_MATCHES_CHECKPOINT,

    "global_confluent_checkpoint_mismatch":
        BLOCK_7_GLOBAL_CONFLUENT_MATCHES_CHECKPOINT,

    "factual_checkpoint_mismatch":
        BLOCK_7_FACTUAL_MATCHES_CHECKPOINT,

    "psychological_checkpoint_mismatch":
        BLOCK_7_PSYCHOLOGICAL_MATCHES_CHECKPOINT,

    "backbone_runtime_mismatch":
        BLOCK_7_BACKBONE_MATCHES_RUNTIME,

    "global_confluent_runtime_mismatch":
        BLOCK_7_GLOBAL_CONFLUENT_MATCHES_RUNTIME,

    "factual_runtime_mismatch":
        BLOCK_7_FACTUAL_MATCHES_RUNTIME,

    "psychological_runtime_mismatch":
        BLOCK_7_PSYCHOLOGICAL_MATCHES_RUNTIME,

    "trainability_scope_invalid":
        BLOCK_7_TRAINABILITY_SCOPE_VALID,

    "optimizer_not_reloaded":
        BLOCK_7_OPTIMIZER_RELOADED,

    "optimizer_state_not_exact":
        BLOCK_7_OPTIMIZER_STATE_EXACT,

    "optimizer_scope_invalid":
        BLOCK_7_OPTIMIZER_SCOPE_VALID,

    "optimizer_parameter_count_invalid":
        BLOCK_7_OPTIMIZER_PARAMETER_COUNT_VALID,

    "optimizer_configuration_invalid":
        BLOCK_7_OPTIMIZER_CONFIGURATION_VALID,

    "active_dimensions_invalid":
        BLOCK_7_ACTIVE_DIMENSIONS_VALID,

    "deferred_dimensions_invalid":
        BLOCK_7_DEFERRED_DIMENSIONS_VALID,

    "active_deferred_boundary_invalid":
        BLOCK_7_ACTIVE_DEFERRED_BOUNDARY_VALID,

    "objective_weights_invalid":
        BLOCK_7_OBJECTIVE_WEIGHTS_VALID,

    "positive_class_weight_policy_invalid":
        BLOCK_7_POSITIVE_CLASS_WEIGHT_POLICY_VALID,

    "prediction_weight_alias_invalid":
        BLOCK_7_PREDICTION_WEIGHT_VALID,

    "training_policy_not_preserved":
        BLOCK_7_TRAINING_POLICY_PRESERVED,

    "forward_input_shape_invalid":
        BLOCK_7_FORWARD_INPUT_SHAPE_VALID,

    "target_shape_invalid":
        BLOCK_7_TARGET_SHAPE_VALID,

    "mask_shape_invalid":
        BLOCK_7_MASK_SHAPE_VALID,

    "checkpoint_total_runtime_mismatch":
        BLOCK_7_CHECKPOINT_TOTAL_MATCHES_RUNTIME,

    "checkpoint_family_runtime_mismatch":
        BLOCK_7_CHECKPOINT_FAMILY_MATCHES_RUNTIME,

    "total_objective_not_reproduced":
        BLOCK_7_TOTAL_OBJECTIVE_REPRODUCED,

    "family_losses_not_reproduced":
        BLOCK_7_ALL_FAMILY_LOSSES_REPRODUCED,

    "deferred_dimension_entered_objective":
        BLOCK_7_DEFERRED_DIMENSIONS_EXCLUDED,

    "method_boundary_not_preserved":
        BLOCK_7_METHOD_BOUNDARY_PRESERVED,

    "metadata_checkpoint_misaligned":
        BLOCK_7_METADATA_CHECKPOINT_ALIGNED,

    "parameters_changed":
        BLOCK_7_ALL_PARAMETERS_UNCHANGED,

    "unexpected_gradients":
        BLOCK_7_FACTUAL_GRADIENTS_ABSENT,

    "checkpoint_not_reproducible":
        NOTEBOOK_06_FACTUAL_CHECKPOINT_REPRODUCIBLE,
}


for error_name, condition in (
    block_7_validation_checks.items()
):

    if not condition:

        NOTEBOOK_06_BLOCK_7_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited-operation validation
# =============================================================================

prohibited_block_7_operations = {
    "zero_grad_incorrectly_executed":
        NOTEBOOK_06_BLOCK_7_ZERO_GRAD_EXECUTED,

    "backward_pass_incorrectly_executed":
        NOTEBOOK_06_BLOCK_7_BACKWARD_PASS_EXECUTED,

    "optimizer_step_incorrectly_executed":
        NOTEBOOK_06_BLOCK_7_OPTIMIZER_STEP_EXECUTED,

    "parameter_update_incorrectly_executed":
        NOTEBOOK_06_BLOCK_7_PARAMETER_UPDATE_EXECUTED,

    "additional_training_incorrectly_executed":
        NOTEBOOK_06_BLOCK_7_ADDITIONAL_TRAINING_EXECUTED,

    "psychological_training_incorrectly_executed":
        NOTEBOOK_06_BLOCK_7_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "group_path_incorrectly_executed":
        NOTEBOOK_06_BLOCK_7_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_mechanism_incorrectly_executed":
        NOTEBOOK_06_BLOCK_7_TRANSFORMATIVE_MECHANISM_EXECUTED,

    "transformative_weights_incorrectly_executed":
        NOTEBOOK_06_BLOCK_7_TRANSFORMATIVE_WEIGHTS_EXECUTED,

    "recurrent_mechanism_incorrectly_executed":
        NOTEBOOK_06_BLOCK_7_RECURRENT_MECHANISM_EXECUTED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_06_BLOCK_7_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_06_BLOCK_7_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for error_name, operation_executed in (
    prohibited_block_7_operations.items()
):

    if operation_executed:

        NOTEBOOK_06_BLOCK_7_ERRORS.append(
            error_name
        )


NOTEBOOK_06_BLOCK_7_VALID = (
    len(
        NOTEBOOK_06_BLOCK_7_ERRORS
    )
    == 0
)


if not NOTEBOOK_06_BLOCK_7_VALID:

    raise RuntimeError(
        "Notebook 06 Block 7 factual checkpoint reproducibility "
        "validation failed. "
        f"Errors: {NOTEBOOK_06_BLOCK_7_ERRORS}"
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_06_BLOCK_7_COMPLETE = True

NOTEBOOK_06_FACTUAL_PATH_REPRODUCIBLE = True

NOTEBOOK_06_READY_FOR_FACTUAL_PATH_AUDIT = True


# =============================================================================
# Block 8 handover objects
# =============================================================================

NOTEBOOK_06_RESTORED_BACKBONE = (
    BLOCK_7_RESTORED_BACKBONE
)


NOTEBOOK_06_RESTORED_GLOBAL_CONFLUENT = (
    BLOCK_7_RESTORED_GLOBAL_CONFLUENT
)


NOTEBOOK_06_RESTORED_FACTUAL_HEAD = (
    BLOCK_7_RESTORED_FACTUAL_HEAD
)


NOTEBOOK_06_RESTORED_PSYCHOLOGICAL_HEAD = (
    BLOCK_7_RESTORED_PSYCHOLOGICAL_HEAD
)


NOTEBOOK_06_RESTORED_FACTUAL_OPTIMIZER = (
    BLOCK_7_RESTORED_OPTIMIZER
)


NOTEBOOK_06_RESTORED_FACTUAL_FINAL_OBJECTIVE = (
    BLOCK_7_RESTORED_TOTAL_OBJECTIVE
)


NOTEBOOK_06_RESTORED_FACTUAL_FINAL_FAMILY_LOSSES = deepcopy(
    BLOCK_7_RESTORED_FAMILY_LOSSES
)


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_06_BLOCK_7_SUMMARY = {
    "block":
        NOTEBOOK_06_BLOCK_7,

    "block_name":
        NOTEBOOK_06_BLOCK_7_NAME,

    "version":
        NOTEBOOK_06_BLOCK_7_VERSION,

    "executed_at_utc":
        BLOCK_7_EXECUTED_AT_UTC,

    "checkpoint_reloaded":
        BLOCK_7_CHECKPOINT_RELOADED,

    "metadata_reloaded":
        BLOCK_7_METADATA_RELOADED,

    "checkpoint_type_valid":
        BLOCK_7_CHECKPOINT_TYPE_VALID,

    "factual_matches_checkpoint":
        BLOCK_7_FACTUAL_MATCHES_CHECKPOINT,

    "factual_matches_runtime":
        BLOCK_7_FACTUAL_MATCHES_RUNTIME,

    "frozen_states_reproduced":
        all(
            [
                BLOCK_7_BACKBONE_MATCHES_CHECKPOINT,
                BLOCK_7_GLOBAL_CONFLUENT_MATCHES_CHECKPOINT,
                BLOCK_7_PSYCHOLOGICAL_MATCHES_CHECKPOINT,
            ]
        ),

    "optimizer_reloaded":
        BLOCK_7_OPTIMIZER_RELOADED,

    "optimizer_state_exact":
        BLOCK_7_OPTIMIZER_STATE_EXACT,

    "optimizer_scope_valid":
        BLOCK_7_OPTIMIZER_SCOPE_VALID,

    "expected_total_objective":
        BLOCK_7_EXPECTED_TOTAL_OBJECTIVE,

    "restored_total_objective":
        BLOCK_7_RESTORED_TOTAL_OBJECTIVE,

    "total_objective_reproduced":
        BLOCK_7_TOTAL_OBJECTIVE_REPRODUCED,

    "all_family_losses_reproduced":
        BLOCK_7_ALL_FAMILY_LOSSES_REPRODUCED,

    "training_policy_preserved":
        BLOCK_7_TRAINING_POLICY_PRESERVED,

    "methodological_boundary_preserved":
        BLOCK_7_METHOD_BOUNDARY_PRESERVED,

    "metadata_checkpoint_aligned":
        BLOCK_7_METADATA_CHECKPOINT_ALIGNED,

    "parameters_unchanged":
        BLOCK_7_ALL_PARAMETERS_UNCHANGED,

    "checkpoint_reproducible":
        NOTEBOOK_06_FACTUAL_CHECKPOINT_REPRODUCIBLE,

    "empirical_validity":
        NOTEBOOK_06_BLOCK_7_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_06_BLOCK_7_VALID,

    "block_complete":
        NOTEBOOK_06_BLOCK_7_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 06, Block 7: "
    "Factual Checkpoint Reload, Reproducibility "
    "and Training-State Validation"
)

print("=" * 72)

print(
    f"Reproducibility version      : "
    f"{NOTEBOOK_06_FACTUAL_REPRODUCIBILITY_VERSION}"
)


print("-" * 72)

print(
    "Persisted artefact reload"
)

print(
    f"Checkpoint reloaded          : "
    f"{BLOCK_7_CHECKPOINT_RELOADED}"
)

print(
    f"Metadata reloaded            : "
    f"{BLOCK_7_METADATA_RELOADED}"
)

print(
    f"Checkpoint contract valid    : "
    f"{BLOCK_7_CHECKPOINT_CONTRACT_VALID}"
)

print(
    f"Checkpoint type valid        : "
    f"{BLOCK_7_CHECKPOINT_TYPE_VALID}"
)

print(
    f"Experimental checkpoint      : "
    f"{BLOCK_7_EXPERIMENTAL_CHECKPOINT}"
)

print(
    f"Validated model checkpoint   : "
    f"{BLOCK_7_VALIDATED_MODEL_CHECKPOINT}"
)


print("-" * 72)

print(
    "Model-state reproduction"
)

print(
    f"Model state restored         : "
    f"{BLOCK_7_MODEL_STATE_RESTORED}"
)

print(
    f"Backbone matches checkpoint  : "
    f"{BLOCK_7_BACKBONE_MATCHES_CHECKPOINT}"
)

print(
    f"Global confluent matches     : "
    f"{BLOCK_7_GLOBAL_CONFLUENT_MATCHES_CHECKPOINT}"
)

print(
    f"Factual matches checkpoint   : "
    f"{BLOCK_7_FACTUAL_MATCHES_CHECKPOINT}"
)

print(
    f"Factual matches runtime      : "
    f"{BLOCK_7_FACTUAL_MATCHES_RUNTIME}"
)

print(
    f"Psych. matches checkpoint    : "
    f"{BLOCK_7_PSYCHOLOGICAL_MATCHES_CHECKPOINT}"
)

print(
    f"Psych. matches runtime       : "
    f"{BLOCK_7_PSYCHOLOGICAL_MATCHES_RUNTIME}"
)

print(
    f"Backbone remains frozen      : "
    f"{BLOCK_7_BACKBONE_FROZEN}"
)

print(
    f"Global confluent frozen      : "
    f"{BLOCK_7_GLOBAL_CONFLUENT_FROZEN}"
)

print(
    f"Psychological head frozen    : "
    f"{BLOCK_7_PSYCHOLOGICAL_HEAD_FROZEN}"
)

print(
    f"Factual head trainable       : "
    f"{BLOCK_7_FACTUAL_HEAD_TRAINABLE}"
)

print(
    f"Factual parameter count      : "
    f"{BLOCK_7_FACTUAL_PARAMETER_COUNT}"
)

print(
    f"Trainability scope valid     : "
    f"{BLOCK_7_TRAINABILITY_SCOPE_VALID}"
)


print("-" * 72)

print(
    "Optimiser-state recovery"
)

print(
    f"Optimiser reloaded           : "
    f"{BLOCK_7_OPTIMIZER_RELOADED}"
)

print(
    f"Optimiser type               : "
    f"{BLOCK_7_CHECKPOINT['optimizer_type']}"
)

print(
    f"Learning rate                : "
    f"{BLOCK_7_CHECKPOINT['learning_rate']}"
)

print(
    f"Weight decay                 : "
    f"{BLOCK_7_CHECKPOINT['weight_decay']}"
)

print(
    f"Optimiser parameters         : "
    f"{BLOCK_7_OPTIMIZER_PARAMETER_COUNT}"
)

print(
    f"Optimiser state exact        : "
    f"{BLOCK_7_OPTIMIZER_STATE_EXACT}"
)

print(
    f"Optimiser scope valid        : "
    f"{BLOCK_7_OPTIMIZER_SCOPE_VALID}"
)


print("-" * 72)

print(
    "Training-policy reproduction"
)

print(
    f"Training articles            : "
    f"{BLOCK_7_METADATA_TRAINING_SCOPE['articles']}"
)

print(
    f"Training sentences           : "
    f"{BLOCK_7_METADATA_TRAINING_SCOPE['sentences']}"
)

print(
    f"Validation sentences         : "
    f"{BLOCK_7_METADATA_TRAINING_SCOPE['validation_sentences']}"
)

print(
    f"Test sentences               : "
    f"{BLOCK_7_METADATA_TRAINING_SCOPE['test_sentences']}"
)

print(
    f"Epochs                       : "
    f"{BLOCK_7_CHECKPOINT['training_epoch_count']}"
)

print(
    f"Within-article shuffle       : "
    f"{BLOCK_7_CHECKPOINT['within_article_shuffle']}"
)

print(
    f"Article sequence preserved   : "
    f"{BLOCK_7_CHECKPOINT['article_sequence_preserved']}"
)

print(
    f"Maximum gradient norm        : "
    f"{BLOCK_7_MAX_GRAD_NORM:.4f}"
)

print(
    f"Recorded max pre-clip norm   : "
    f"{BLOCK_7_METADATA_MAX_PRECLIP_NORM:.8f}"
)

print(
    f"Weighted binary dimensions   : "
    f"{list(BLOCK_7_WEIGHTED_BINARY_DIMENSIONS)}"
)

print(
    f"Positive class weights       : "
    f"{BLOCK_7_POSITIVE_CLASS_WEIGHTS}"
)

print(
    f"Prediction positive weight   : "
    f"{BLOCK_7_PREDICTION_POSITIVE_WEIGHT}"
)

print(
    f"Objective weights            : "
    f"{BLOCK_7_OBJECTIVE_WEIGHTS}"
)

print(
    f"Training policy preserved    : "
    f"{BLOCK_7_TRAINING_POLICY_PRESERVED}"
)


print("-" * 72)

print(
    "Post-training objective reproduction"
)

print(
    f"Controlled forward executed  : "
    f"{NOTEBOOK_06_BLOCK_7_FORWARD_EXECUTED}"
)

print(
    f"Objective recalculated       : "
    f"{NOTEBOOK_06_BLOCK_7_OBJECTIVE_RECALCULATED}"
)

print(
    f"Expected total objective     : "
    f"{BLOCK_7_EXPECTED_TOTAL_OBJECTIVE:.8f}"
)

print(
    f"Restored total objective     : "
    f"{BLOCK_7_RESTORED_TOTAL_OBJECTIVE:.8f}"
)

print(
    f"Total objective reproduced   : "
    f"{BLOCK_7_TOTAL_OBJECTIVE_REPRODUCED}"
)


for target_name in BLOCK_7_ACTIVE_DIMENSIONS:

    print(
        f"{target_name:<29}: "
        f"{float(BLOCK_7_EXPECTED_FAMILY_LOSSES[target_name]):.8f}"
        f" / "
        f"{BLOCK_7_RESTORED_FAMILY_LOSSES[target_name]:.8f}"
    )


print(
    f"All family losses reproduced : "
    f"{BLOCK_7_ALL_FAMILY_LOSSES_REPRODUCED}"
)

print(
    f"Deferred dimensions excluded : "
    f"{BLOCK_7_DEFERRED_DIMENSIONS_EXCLUDED}"
)


print("-" * 72)

print(
    "Methodological boundary"
)

print(
    f"Experimental checkpoint      : "
    f"{BLOCK_7_EXPERIMENTAL_CHECKPOINT}"
)

print(
    f"Validated model checkpoint   : "
    f"{BLOCK_7_VALIDATED_MODEL_CHECKPOINT}"
)

print(
    f"Method boundary preserved    : "
    f"{BLOCK_7_METHOD_BOUNDARY_PRESERVED}"
)

print(
    f"Metadata/checkpoint aligned  : "
    f"{BLOCK_7_METADATA_CHECKPOINT_ALIGNED}"
)

print(
    f"All parameters unchanged     : "
    f"{BLOCK_7_ALL_PARAMETERS_UNCHANGED}"
)

print(
    f"Factual gradients absent     : "
    f"{BLOCK_7_FACTUAL_GRADIENTS_ABSENT}"
)

print(
    f"Empirical validity claimed   : "
    f"{NOTEBOOK_06_BLOCK_7_EMPIRICAL_VALIDITY_ESTABLISHED}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_06_BLOCK_7_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_06_BLOCK_7_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_06_BLOCK_7_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_06_BLOCK_7_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Additional training executed : "
    f"{NOTEBOOK_06_BLOCK_7_ADDITIONAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_06_BLOCK_7_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{NOTEBOOK_06_BLOCK_7_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative executed      : "
    f"{NOTEBOOK_06_BLOCK_7_TRANSFORMATIVE_MECHANISM_EXECUTED}"
)

print(
    f"Transformative weights active: "
    f"{NOTEBOOK_06_BLOCK_7_TRANSFORMATIVE_WEIGHTS_EXECUTED}"
)

print(
    f"Recurrent executed           : "
    f"{NOTEBOOK_06_BLOCK_7_RECURRENT_MECHANISM_EXECUTED}"
)

print(
    f"Held-out evaluation executed : "
    f"{NOTEBOOK_06_BLOCK_7_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Checkpoint reproducible      : "
    f"{NOTEBOOK_06_FACTUAL_CHECKPOINT_REPRODUCIBLE}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_06_BLOCK_7_VALID}"
)

print(
    f"Block 7 complete             : "
    f"{NOTEBOOK_06_BLOCK_7_COMPLETE}"
)


print("=" * 72)


print(
    "Persisted controlled factual training state reloaded "
    "and reproduced successfully."
)

print(
    "Fresh backbone, global confluent, factual-head and psychological-head "
    "instances were restored from the persisted Block 6 checkpoint rather "
    "than using the trained runtime modules as their parameter source."
)

print(
    "The restored factual-head state exactly matches both the persisted "
    "checkpoint and the trained Block 6 runtime factual-head state."
)

print(
    "The restored backbone, mandatory global confluent path and "
    "psychological head reproduce their persisted states exactly and "
    "remain frozen."
)

print(
    "The restored factual head remains the only trainable representation "
    "module and preserves the validated 34,442-parameter scope."
)

print(
    "The persisted AdamW optimiser state was restored exactly and remains "
    "scoped exclusively to the factual representation head."
)

print(
    f"The restored model reproduces all {len(BLOCK_7_ACTIVE_DIMENSIONS)} "
    "persisted active factual family objectives and the combined factual "
    "objective within the configured numerical tolerance."
)

print(
    "Active/deferred factual dimensions, objective-family weights and "
    "positive-class imbalance weights are reproduced from the persisted "
    "training contract rather than from corpus-specific constants."
)

print(
    "The checkpoint remains explicitly classified as a controlled "
    "experimental factual training checkpoint rather than a validated model."
)

print(
    "The persisted methodological boundary continues to record that the "
    "psychological head, backbone and global confluent path were not trained "
    "during factual optimisation."
)

print(
    "The optional group-conditioned path, social path, transformative "
    "mechanisms, Transformative Weights and recurrent states remain outside "
    "the factual training boundary."
)

print(
    "No zero-gradient operation, backward pass, optimiser step, parameter "
    "update or additional training was performed by Block 7."
)

print(
    "Successful Block 7 completion establishes factual checkpoint "
    "portability and training-state reproducibility, not factual "
    "generalisation or empirical validity."
)

print(
    "The next block may proceed to factual-path scope audit, persistent "
    "handover and Notebook 06 completion."
)

print("=" * 72)

========================================================================
Media AI — Notebook 06, Block 7: Factual Checkpoint Reload, Reproducibility and Training-State Validation
========================================================================
Reproducibility version      : 1.2
------------------------------------------------------------------------
Persisted artefact reload
Checkpoint reloaded          : True
Metadata reloaded            : True
Checkpoint contract valid    : True
Checkpoint type valid        : True
Experimental checkpoint      : True
Validated model checkpoint   : False
------------------------------------------------------------------------
Model-state reproduction
Model state restored         : True
Backbone matches checkpoint  : True
Global confluent matches     : True
Factual matches checkpoint   : True
Factual matches runtime      : True
Psych. matches checkpoint    : True
Psych. matches runtime       : True
Backbone remains frozen      : True
Global confluent frozen      : True
Psychological head frozen    : True
Factual head trainable       : True
Factual parameter count      : 34442
Trainability scope valid     : True
------------------------------------------------------------------------
Optimiser-state recovery
Optimiser reloaded           : True
Optimiser type               : AdamW
Learning rate                : 0.001
Weight decay                 : 0.0001
Optimiser parameters         : 34442
Optimiser state exact        : True
Optimiser scope valid        : True
------------------------------------------------------------------------
Training-policy reproduction
Training articles            : 3
Training sentences           : 54
Validation sentences         : 0
Test sentences               : 0
Epochs                       : 10
Within-article shuffle       : False
Article sequence preserved   : True
Maximum gradient norm        : 1.0000
Recorded max pre-clip norm   : 4.87169099
Weighted binary dimensions   : ['explicit_claim', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction']
Positive class weights       : {'explicit_claim': 0.2558139534883721, 'evidence_reference': 3.1538461538461537, 'certainty_statement': 0.17391304347826086, 'uncertainty_statement': 8.0, 'prediction': 25.0}
Prediction positive weight   : 25.0
Objective weights            : {'explicit_claim': 0.1111111111111111, 'observation_or_event': 0.1111111111111111, 'quantitative_information': 0.1111111111111111, 'attribution': 0.1111111111111111, 'evidence_reference': 0.1111111111111111, 'certainty_statement': 0.1111111111111111, 'uncertainty_statement': 0.1111111111111111, 'prediction': 0.1111111111111111, 'factological_weight': 0.1111111111111111}
Training policy preserved    : True
------------------------------------------------------------------------
Post-training objective reproduction
Controlled forward executed  : True
Objective recalculated       : True
Expected total objective     : 0.40325385
Restored total objective     : 0.40325385
Total objective reproduced   : True
explicit_claim               : 0.22249709 / 0.22249709
observation_or_event         : 0.63362038 / 0.63362038
quantitative_information     : 0.53347296 / 0.53347296
attribution                  : 0.42519507 / 0.42519507
evidence_reference           : 0.60179800 / 0.60179800
certainty_statement          : 0.14542311 / 0.14542311
uncertainty_statement        : 0.57453150 / 0.57453150
prediction                   : 0.40801331 / 0.40801331
factological_weight          : 0.08473307 / 0.08473307
All family losses reproduced : True
Deferred dimensions excluded : True
------------------------------------------------------------------------
Methodological boundary
Experimental checkpoint      : True
Validated model checkpoint   : False
Method boundary preserved    : True
Metadata/checkpoint aligned  : True
All parameters unchanged     : True
Factual gradients absent     : True
Empirical validity claimed   : False
------------------------------------------------------------------------
Execution boundary
Zero grad executed           : False
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
Additional training executed : False
Psychological retraining     : False
Group-conditioned executed   : False
Transformative executed      : False
Transformative weights active: False
Recurrent executed           : False
Held-out evaluation executed : False
Checkpoint reproducible      : True
Block valid                  : True
Block 7 complete             : True
========================================================================
Persisted controlled factual training state reloaded and reproduced successfully.
Fresh backbone, global confluent, factual-head and psychological-head instances were restored from the persisted Block 6 checkpoint rather than using the trained runtime modules as their parameter source.
The restored factual-head state exactly matches both the persisted checkpoint and the trained Block 6 runtime factual-head state.
The restored backbone, mandatory global confluent path and psychological head reproduce their persisted states exactly and remain frozen.
The restored factual head remains the only trainable representation module and preserves the validated 34,442-parameter scope.
The persisted AdamW optimiser state was restored exactly and remains scoped exclusively to the factual representation head.
The restored model reproduces all 9 persisted active factual family objectives and the combined factual objective within the configured numerical tolerance.
Active/deferred factual dimensions, objective-family weights and positive-class imbalance weights are reproduced from the persisted training contract rather than from corpus-specific constants.
The checkpoint remains explicitly classified as a controlled experimental factual training checkpoint rather than a validated model.
The persisted methodological boundary continues to record that the psychological head, backbone and global confluent path were not trained during factual optimisation.
The optional group-conditioned path, social path, transformative mechanisms, Transformative Weights and recurrent states remain outside the factual training boundary.
No zero-gradient operation, backward pass, optimiser step, parameter update or additional training was performed by Block 7.
Successful Block 7 completion establishes factual checkpoint portability and training-state reproducibility, not factual generalisation or empirical validity.
The next block may proceed to factual-path scope audit, persistent handover and Notebook 06 completion.
========================================================================

## Block 8 — Factual Path Scope Audit, Persistent Handover and Notebook 06 Completion

This block closes Notebook 06 by auditing the completed factual path, preserving its trained state and methodological boundaries, and constructing the persistent handover required to initialise Notebook 07 independently.

No new factual optimisation is performed in this block. The purpose is to consolidate what has been established in Blocks 1–7, distinguish implemented and trained functionality from deferred functionality, verify the reproducibility of the factual path, and persist the exact state required by the subsequent social path.

### Factual-path completion audit

The block verifies that the factual path has been completed within the controlled Version 1 scope established for Notebook 06.

The factual representation remains ten-dimensional:

- F1 — `explicit_claim`
- F2 — `observation_or_event`
- F3 — `quantitative_information`
- F4 — `attribution`
- F5 — `evidence_reference`
- F6 — `certainty_statement`
- F7 — `uncertainty_statement`
- F8 — `speculation`
- F9 — `prediction`
- F10 — `factological_weight`

All ten dimensions remain structurally present in the factual representation.

The current controlled supervision activates only dimensions for which the available sample provides usable target variation:

- F2 — `observation_or_event`
- F3 — `quantitative_information`
- F5 — `evidence_reference`
- F9 — `prediction`
- F10 — `factological_weight`

F1, F4, F6, F7 and F8 remain valid parts of the factual architecture but are deferred from the current optimisation because the available supervision provides zero target variance for them. Their exclusion from the current loss therefore does not remove them from the architecture or redefine their semantics.

### Factual supervision and objective contract

The block verifies that the factual path continues to use the canonical sentence as its prediction unit.

Preceding textual context may assist interpretation where required, but the factual targets remain sentence-oriented. Future context is not permitted.

The factual supervision contract remains mask-aware:

- missing supervision is not interpreted as zero;
- missing supervision is not interpreted as negative evidence;
- unavailable targets do not enter the loss;
- partial supervision remains permissible.

The four active binary factual dimensions retain independent binary-cross-entropy-with-logits objectives.

`factological_weight` remains an independent continuous regression objective using masked mean-squared error.

The prediction dimension retains the previously validated positive-class weighting derived from the current supervision.

The five active objective families retain the controlled equal-weight aggregation established in Block 5.

### Controlled factual training state

The block verifies that the controlled factual training performed in Block 6 remains the only factual parameter-update operation executed in Notebook 06.

Only the factual representation head was trained.

The following components remained frozen throughout factual optimisation:

- contextual encoder;
- backbone;
- mandatory global confluent path;
- completed psychological representation head.

The factual checkpoint remains classified as a **controlled experimental factual training checkpoint**.

It is not promoted to a validated model checkpoint because the current dataset contains only one article and provides no independent validation or test partition.

Training-objective reduction is treated only as evidence that the controlled optimisation pipeline operates as intended. It is not treated as evidence of generalisation, factual prediction quality or empirical validity.

### Reproducibility audit

The block confirms the Block 7 reproducibility result.

The persisted factual checkpoint must independently reproduce:

- the backbone state;
- the mandatory global confluent state;
- the factual-head state;
- the frozen psychological-head state;
- the factual-head trainability scope;
- the AdamW optimiser state;
- the factual objective policy;
- the post-training factual objective.

The reproduced model state must be obtained from persisted artefacts rather than relying on the already-trained runtime modules as the parameter source.

No additional optimisation is permitted during this completion audit.

### Architectural boundary

Notebook 06 completes only the factual path.

The mandatory global confluent path remains the active conditioning path used by the factual representation.

The optional group-conditioned path remains architecturally available but is not executed or trained in Notebook 06. Group-conditioned processing remains deferred to Notebook 10 because the current sample is insufficient to justify stable data-driven grouping.

The following mechanisms also remain outside Notebook 06:

- social representation path;
- transformative mechanism;
- Transformative Weights;
- recurrent mechanism and recurrent states;
- final multi-path integration.

Their absence from Notebook 06 is intentional and must not be interpreted as architectural removal.

### Persistent Notebook 06 → Notebook 07 handover

The block constructs and persists a dedicated Notebook 06 → Notebook 07 handover artefact.

The handover must provide Notebook 07 with sufficient information to initialise independently without rerunning Notebook 06.

At minimum, the handover should preserve or reference:

- canonical article and sentence identity;
- contextual sentence-representation contract and persisted artefact;
- validated architecture dimensions;
- mandatory global confluent-path contract;
- completed psychological-path checkpoint and frozen-state contract;
- completed factual-path checkpoint and metadata;
- ten-dimensional factual semantic contract;
- active and deferred factual dimensions;
- factual objective and masking policy;
- factual optimiser and training-policy metadata required for reproducibility;
- factual checkpoint classification as controlled experimental rather than validated;
- global/group path boundary;
- causal and article-boundary rules;
- remaining Version 1 notebook roadmap.

The handover should reference persisted artefacts by their verified Drive file identifiers rather than duplicating trained parameter states unnecessarily.

A local copy of the handover should also be created, persisted to Google Drive and read back to verify that the persisted contract is complete and internally consistent.

### Notebook 07 starting boundary

Notebook 07 is designated as the **Social Path** notebook.

It may initialise from the persisted Notebook 06 handover while treating the completed psychological and factual paths as frozen by default.

Notebook 07 must not silently retrain either completed path.

Any later decision to jointly optimise previously completed representations must be explicit and belong to a separately defined training stage rather than being introduced implicitly during social-path construction.

The social path should preserve the same canonical sentence identity and contextual representation contract so that psychological, factual and social representations remain aligned for later integration.

### Methodological boundary

Completion of Notebook 06 establishes:

- a defined ten-dimensional factual representation;
- a resolved factual supervision mapping;
- an explicit activation and loss contract;
- a controlled factual forward path;
- a validated factual-head optimisation scope;
- a controlled experimental factual training run;
- a persisted factual checkpoint;
- reproducible factual training state;
- a persistent downstream handover.

It does **not** establish:

- held-out factual performance;
- factual generalisation;
- calibrated factual probabilities;
- cross-article robustness;
- group-conditioned validity;
- social-path validity;
- transformative or recurrent validity;
- final Media AI model validity.

These claims remain outside the evidence available from the current one-article controlled sample.

### Execution boundary

Block 8 performs no:

- new factual forward optimisation;
- loss-driven parameter update;
- backward pass;
- optimiser step;
- psychological retraining;
- social-path training;
- group-conditioned processing;
- transformative processing;
- Transformative Weight activation;
- recurrent processing;
- held-out evaluation.

Its operations are restricted to state inspection, scope auditing, persistence, handover construction and read-back validation.

Successful completion of Block 8 marks **Notebook 06 — Factual Path** as complete within its controlled experimental scope.

The full Media AI Version 1 project remains incomplete.

Notebook 07 may then initialise independently from the persisted Notebook 06 → Notebook 07 handover and begin the Social Path.

In [15]:
# =============================================================================
# Media AI — Notebook 06
# Block 8: Factual Path Scope Audit, Persistent Handover
#          and Notebook 06 Completion
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json
import math

import numpy as np
import pandas as pd
import torch

from googleapiclient.http import (
    MediaIoBaseDownload,
    MediaIoBaseUpload,
)


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_06_BLOCK_8 = 8

NOTEBOOK_06_BLOCK_8_NAME = (
    "Factual Path Scope Audit, Persistent Handover "
    "and Notebook 06 Completion"
)

NOTEBOOK_06_BLOCK_8_VERSION = "1.3"

NOTEBOOK_06_TO_07_HANDOVER_VERSION = "1.3"

NOTEBOOK_06_TO_07_HANDOVER_FILENAME = (
    "notebook_06_to_07_handover.json"
)

BLOCK_8_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Dependency checks
# =============================================================================

required_block_8_objects = [
    # -------------------------------------------------------------------------
    # Block 1 — initialisation / inherited handover
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_1_COMPLETE",
    "NOTEBOOK_06_BLOCK_1_VALID",
    "NOTEBOOK_06_DRIVE_SERVICE",
    "NOTEBOOK_06_HANDOVER",
    "NOTEBOOK_06_SENTENCE_IDS",
    "NOTEBOOK_06_SENTENCE_COUNT",
    "NOTEBOOK_06_ARTICLE_COUNT",
    "NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID",

    # -------------------------------------------------------------------------
    # Block 2 — factual semantic / target contract
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_2_COMPLETE",
    "NOTEBOOK_06_BLOCK_2_VALID",
    "NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED",
    "NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID",
    "NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID",
    "NOTEBOOK_06_FACTUAL_DIMENSION_ORDER",
    "NOTEBOOK_06_FACTUAL_DIMENSION_IDS",
    "NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM",

    # -------------------------------------------------------------------------
    # Block 3 — objective policy
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_3_COMPLETE",
    "NOTEBOOK_06_BLOCK_3_VALID",
    "NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS",
    "NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS",
    "NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID",

    # -------------------------------------------------------------------------
    # Block 4 — model / freezing policy
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_4_COMPLETE",
    "NOTEBOOK_06_BLOCK_4_VALID",
    "NOTEBOOK_06_FACTUAL_MODEL_POLICY_READY",
    "NOTEBOOK_06_BACKBONE_FROZEN_MODULE",
    "NOTEBOOK_06_GLOBAL_CONFLUENT_FROZEN_MODULE",
    "NOTEBOOK_06_FACTUAL_HEAD",
    "NOTEBOOK_06_PSYCHOLOGICAL_HEAD_FROZEN_MODULE",

    # -------------------------------------------------------------------------
    # Block 5 — objective / optimiser policy
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_5_COMPLETE",
    "NOTEBOOK_06_BLOCK_5_VALID",
    "NOTEBOOK_06_FACTUAL_OBJECTIVE_WEIGHTS",
    "NOTEBOOK_06_FACTUAL_OPTIMIZER_POLICY_VALID",

    # -------------------------------------------------------------------------
    # Block 6 — controlled factual training
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_6_COMPLETE",
    "NOTEBOOK_06_BLOCK_6_VALID",
    "NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE",
    "NOTEBOOK_06_FACTUAL_CHECKPOINT_FILENAME",
    "NOTEBOOK_06_FACTUAL_METADATA_FILENAME",
    "NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE_ID",
    "NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE_ID",
    "NOTEBOOK_06_FACTUAL_FINAL_OBJECTIVE",
    "NOTEBOOK_06_FACTUAL_FINAL_FAMILY_LOSSES",
    "NOTEBOOK_06_FACTUAL_CHECKPOINT",
    "NOTEBOOK_06_FACTUAL_TRAINING_METADATA",

    # -------------------------------------------------------------------------
    # Block 7 — reproducibility
    # -------------------------------------------------------------------------
    "NOTEBOOK_06_BLOCK_7_COMPLETE",
    "NOTEBOOK_06_BLOCK_7_VALID",
    "NOTEBOOK_06_FACTUAL_CHECKPOINT_REPRODUCIBLE",
    "NOTEBOOK_06_FACTUAL_PATH_REPRODUCIBLE",
]


missing_block_8_objects = [
    object_name
    for object_name
    in required_block_8_objects
    if object_name not in globals()
]


if missing_block_8_objects:

    raise NameError(
        "Notebook 06 Block 8 prerequisites are not initialised. "
        f"Missing: {missing_block_8_objects}"
    )


# =============================================================================
# Previous-block validation
# =============================================================================

BLOCK_8_PREVIOUS_BLOCKS_COMPLETE = all(
    [
        NOTEBOOK_06_BLOCK_1_COMPLETE,
        NOTEBOOK_06_BLOCK_2_COMPLETE,
        NOTEBOOK_06_BLOCK_3_COMPLETE,
        NOTEBOOK_06_BLOCK_4_COMPLETE,
        NOTEBOOK_06_BLOCK_5_COMPLETE,
        NOTEBOOK_06_BLOCK_6_COMPLETE,
        NOTEBOOK_06_BLOCK_7_COMPLETE,
    ]
)


BLOCK_8_PREVIOUS_BLOCKS_VALID = all(
    [
        NOTEBOOK_06_BLOCK_1_VALID,
        NOTEBOOK_06_BLOCK_2_VALID,
        NOTEBOOK_06_BLOCK_3_VALID,
        NOTEBOOK_06_BLOCK_4_VALID,
        NOTEBOOK_06_BLOCK_5_VALID,
        NOTEBOOK_06_BLOCK_6_VALID,
        NOTEBOOK_06_BLOCK_7_VALID,
    ]
)


if not BLOCK_8_PREVIOUS_BLOCKS_COMPLETE:

    raise ValueError(
        "Notebook 06 Blocks 1–7 must all be complete before Block 8."
    )


if not BLOCK_8_PREVIOUS_BLOCKS_VALID:

    raise ValueError(
        "Notebook 06 Blocks 1–7 must all be valid before Block 8."
    )


# =============================================================================
# Execution boundary
# =============================================================================

NOTEBOOK_06_BLOCK_8_FORWARD_PASS_EXECUTED = False

NOTEBOOK_06_BLOCK_8_LOSS_CALCULATED = False

NOTEBOOK_06_BLOCK_8_ZERO_GRAD_EXECUTED = False

NOTEBOOK_06_BLOCK_8_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_06_BLOCK_8_OPTIMIZER_CREATED = False

NOTEBOOK_06_BLOCK_8_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_06_BLOCK_8_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_06_BLOCK_8_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_06_BLOCK_8_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_06_BLOCK_8_SOCIAL_TRAINING_EXECUTED = False

NOTEBOOK_06_BLOCK_8_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_06_BLOCK_8_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_06_BLOCK_8_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

NOTEBOOK_06_BLOCK_8_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_06_BLOCK_8_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_06_BLOCK_8_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Canonical identity audit
# =============================================================================
#
# Corpus size is derived from the current canonical sentence identities.
# Article and sentence counts are therefore data-dependent and are not
# hard-coded to pilot values.
# =============================================================================

def block_8_article_id_from_sentence_id(
    sentence_id,
):

    if not isinstance(
        sentence_id,
        str,
    ) or not sentence_id:

        raise ValueError(
            "Notebook 06 sentence IDs must be non-empty strings."
        )


    if "::" in sentence_id:

        return sentence_id.split(
            "::",
            1,
        )[0]


    return sentence_id


BLOCK_8_SENTENCE_IDS = tuple(
    NOTEBOOK_06_SENTENCE_IDS
)


BLOCK_8_DERIVED_SENTENCE_COUNT = len(
    BLOCK_8_SENTENCE_IDS
)


BLOCK_8_DERIVED_ARTICLE_IDS = tuple(
    dict.fromkeys(
        block_8_article_id_from_sentence_id(
            sentence_id
        )

        for sentence_id
        in BLOCK_8_SENTENCE_IDS
    )
)


BLOCK_8_DERIVED_ARTICLE_COUNT = len(
    BLOCK_8_DERIVED_ARTICLE_IDS
)


BLOCK_8_ARTICLE_COUNT_VALID = all(
    [
        BLOCK_8_DERIVED_ARTICLE_COUNT > 0,
        int(
            NOTEBOOK_06_ARTICLE_COUNT
        )
        ==
        BLOCK_8_DERIVED_ARTICLE_COUNT,
    ]
)


BLOCK_8_SENTENCE_COUNT_VALID = all(
    [
        BLOCK_8_DERIVED_SENTENCE_COUNT > 0,
        int(
            NOTEBOOK_06_SENTENCE_COUNT
        )
        ==
        BLOCK_8_DERIVED_SENTENCE_COUNT,
    ]
)


BLOCK_8_SENTENCE_IDS_PRESENT = all(
    isinstance(
        sentence_id,
        str,
    )
    and
    bool(
        sentence_id
    )

    for sentence_id
    in BLOCK_8_SENTENCE_IDS
)


BLOCK_8_SENTENCE_IDS_UNIQUE = (
    BLOCK_8_DERIVED_SENTENCE_COUNT
    ==
    len(
        set(
            BLOCK_8_SENTENCE_IDS
        )
    )
)


BLOCK_8_IDENTITY_CONTRACT_VALID = all(
    [
        BLOCK_8_ARTICLE_COUNT_VALID,
        BLOCK_8_SENTENCE_COUNT_VALID,
        BLOCK_8_SENTENCE_IDS_PRESENT,
        BLOCK_8_SENTENCE_IDS_UNIQUE,
    ]
)


if not BLOCK_8_IDENTITY_CONTRACT_VALID:

    raise RuntimeError(
        "Notebook 06 canonical identity contract is invalid."
    )


# =============================================================================
# Factual semantic contract
# =============================================================================

BLOCK_8_EXPECTED_FACTUAL_DIMENSION_IDS = (
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
)


BLOCK_8_EXPECTED_FACTUAL_DIMENSION_ORDER = (
    "explicit_claim",
    "observation_or_event",
    "quantitative_information",
    "attribution",
    "evidence_reference",
    "certainty_statement",
    "uncertainty_statement",
    "speculation",
    "prediction",
    "factological_weight",
)


BLOCK_8_FACTUAL_DIMENSION_VALID = (
    NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM
    == 10
)


BLOCK_8_FACTUAL_DIMENSION_IDS_VALID = (
    tuple(
        NOTEBOOK_06_FACTUAL_DIMENSION_IDS
    )
    ==
    BLOCK_8_EXPECTED_FACTUAL_DIMENSION_IDS
)


BLOCK_8_FACTUAL_DIMENSION_ORDER_VALID = (
    tuple(
        NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
    )
    ==
    BLOCK_8_EXPECTED_FACTUAL_DIMENSION_ORDER
)


BLOCK_8_FACTUAL_SEMANTIC_CONTRACT_VALID = all(
    [
        BLOCK_8_FACTUAL_DIMENSION_VALID,
        BLOCK_8_FACTUAL_DIMENSION_IDS_VALID,
        BLOCK_8_FACTUAL_DIMENSION_ORDER_VALID,
        NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED,
        NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID,
    ]
)


if not BLOCK_8_FACTUAL_SEMANTIC_CONTRACT_VALID:

    raise RuntimeError(
        "Notebook 06 factual semantic contract is invalid."
    )


# =============================================================================
# Active / deferred factual dimensions
# =============================================================================
#
# Block 8 audits the validated objective policy produced upstream.
# It does not redefine corpus-dependent active/deferred factual dimensions.
# =============================================================================

BLOCK_8_ACTIVE_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_DIMENSIONS
)


BLOCK_8_DEFERRED_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_DEFERRED_DIMENSIONS
)


BLOCK_8_ACTIVE_BINARY_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_BINARY_DIMENSIONS
)


BLOCK_8_ACTIVE_CONTINUOUS_DIMENSIONS = tuple(
    NOTEBOOK_06_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS
)


BLOCK_8_FACTUAL_DIMENSION_SET = set(
    NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
)


BLOCK_8_ACTIVE_SET = set(
    BLOCK_8_ACTIVE_DIMENSIONS
)


BLOCK_8_DEFERRED_SET = set(
    BLOCK_8_DEFERRED_DIMENSIONS
)


BLOCK_8_ACTIVE_BINARY_SET = set(
    BLOCK_8_ACTIVE_BINARY_DIMENSIONS
)


BLOCK_8_ACTIVE_CONTINUOUS_SET = set(
    BLOCK_8_ACTIVE_CONTINUOUS_DIMENSIONS
)


BLOCK_8_ACTIVE_DIMENSIONS_VALID = all(
    [
        len(
            BLOCK_8_ACTIVE_DIMENSIONS
        )
        >
        0,

        len(
            BLOCK_8_ACTIVE_SET
        )
        ==
        len(
            BLOCK_8_ACTIVE_DIMENSIONS
        ),

        BLOCK_8_ACTIVE_SET.issubset(
            BLOCK_8_FACTUAL_DIMENSION_SET
        ),
    ]
)


BLOCK_8_DEFERRED_DIMENSIONS_VALID = all(
    [
        len(
            BLOCK_8_DEFERRED_SET
        )
        ==
        len(
            BLOCK_8_DEFERRED_DIMENSIONS
        ),

        BLOCK_8_DEFERRED_SET.issubset(
            BLOCK_8_FACTUAL_DIMENSION_SET
        ),
    ]
)


BLOCK_8_ACTIVE_DEFERRED_DISJOINT = (
    BLOCK_8_ACTIVE_SET.isdisjoint(
        BLOCK_8_DEFERRED_SET
    )
)


BLOCK_8_ACTIVE_DEFERRED_COMPLETE = (
    (
        BLOCK_8_ACTIVE_SET
        |
        BLOCK_8_DEFERRED_SET
    )
    ==
    BLOCK_8_FACTUAL_DIMENSION_SET
)


BLOCK_8_ACTIVE_BINARY_DIMENSIONS_VALID = (
    BLOCK_8_ACTIVE_BINARY_SET.issubset(
        BLOCK_8_ACTIVE_SET
    )
)


BLOCK_8_ACTIVE_CONTINUOUS_DIMENSIONS_VALID = (
    BLOCK_8_ACTIVE_CONTINUOUS_SET.issubset(
        BLOCK_8_ACTIVE_SET
    )
)


BLOCK_8_ACTIVE_TYPE_PARTITION_VALID = all(
    [
        BLOCK_8_ACTIVE_BINARY_SET.isdisjoint(
            BLOCK_8_ACTIVE_CONTINUOUS_SET
        ),

        (
            BLOCK_8_ACTIVE_BINARY_SET
            |
            BLOCK_8_ACTIVE_CONTINUOUS_SET
        )
        ==
        BLOCK_8_ACTIVE_SET,
    ]
)


BLOCK_8_OBJECTIVE_BOUNDARY_VALID = all(
    [
        BLOCK_8_ACTIVE_DIMENSIONS_VALID,
        BLOCK_8_DEFERRED_DIMENSIONS_VALID,
        BLOCK_8_ACTIVE_DEFERRED_DISJOINT,
        BLOCK_8_ACTIVE_DEFERRED_COMPLETE,
        BLOCK_8_ACTIVE_BINARY_DIMENSIONS_VALID,
        BLOCK_8_ACTIVE_CONTINUOUS_DIMENSIONS_VALID,
        BLOCK_8_ACTIVE_TYPE_PARTITION_VALID,
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID,
        NOTEBOOK_06_FACTUAL_OPTIMIZER_POLICY_VALID,
    ]
)


if not BLOCK_8_OBJECTIVE_BOUNDARY_VALID:

    raise RuntimeError(
        "Notebook 06 factual objective boundary is invalid."
    )


# =============================================================================
# Positive-class imbalance policy
# =============================================================================

BLOCK_8_POSITIVE_CLASS_WEIGHTS = deepcopy(
    NOTEBOOK_06_FACTUAL_POSITIVE_CLASS_WEIGHTS
)


BLOCK_8_WEIGHTED_BINARY_DIMENSIONS = tuple(
    dimension_name
    for dimension_name
    in BLOCK_8_ACTIVE_BINARY_DIMENSIONS
    if dimension_name
    in BLOCK_8_POSITIVE_CLASS_WEIGHTS
)


BLOCK_8_POSITIVE_CLASS_WEIGHT_KEYS_VALID = (
    set(
        BLOCK_8_POSITIVE_CLASS_WEIGHTS.keys()
    ).issubset(
        BLOCK_8_ACTIVE_BINARY_SET
    )
)


BLOCK_8_POSITIVE_CLASS_WEIGHT_VALUES_VALID = all(
    isinstance(
        weight_value,
        (
            int,
            float,
            np.integer,
            np.floating,
        ),
    )
    and
    math.isfinite(
        float(
            weight_value
        )
    )
    and
    float(
        weight_value
    )
    >
    0.0

    for weight_value
    in BLOCK_8_POSITIVE_CLASS_WEIGHTS.values()
)


BLOCK_8_POSITIVE_CLASS_WEIGHT_POLICY_VALID = all(
    [
        BLOCK_8_POSITIVE_CLASS_WEIGHT_KEYS_VALID,
        BLOCK_8_POSITIVE_CLASS_WEIGHT_VALUES_VALID,
    ]
)


if not BLOCK_8_POSITIVE_CLASS_WEIGHT_POLICY_VALID:

    raise RuntimeError(
        "Notebook 06 positive-class imbalance policy is invalid."
    )


# Backward-compatible prediction alias.
BLOCK_8_PREDICTION_POSITIVE_WEIGHT = (
    float(
        BLOCK_8_POSITIVE_CLASS_WEIGHTS[
            "prediction"
        ]
    )
    if "prediction"
    in BLOCK_8_POSITIVE_CLASS_WEIGHTS
    else None
)


BLOCK_8_PREDICTION_WEIGHT_VALID = True


# =============================================================================
# Objective-family weighting
# =============================================================================

BLOCK_8_OBJECTIVE_WEIGHTS = deepcopy(
    NOTEBOOK_06_FACTUAL_OBJECTIVE_WEIGHTS
)


BLOCK_8_OBJECTIVE_WEIGHT_KEYS_VALID = (
    set(
        BLOCK_8_OBJECTIVE_WEIGHTS.keys()
    )
    ==
    BLOCK_8_ACTIVE_SET
)


BLOCK_8_OBJECTIVE_WEIGHT_VALUES_VALID = all(
    isinstance(
        weight_value,
        (
            int,
            float,
            np.integer,
            np.floating,
        ),
    )
    and
    math.isfinite(
        float(
            weight_value
        )
    )
    and
    float(
        weight_value
    )
    >
    0.0

    for weight_value
    in BLOCK_8_OBJECTIVE_WEIGHTS.values()
)


BLOCK_8_OBJECTIVE_WEIGHT_SUM_VALID = (
    BLOCK_8_OBJECTIVE_WEIGHT_KEYS_VALID
    and
    math.isclose(
        sum(
            float(
                BLOCK_8_OBJECTIVE_WEIGHTS[
                    dimension_name
                ]
            )

            for dimension_name
            in BLOCK_8_ACTIVE_DIMENSIONS
        ),
        1.0,
        rel_tol=0.0,
        abs_tol=1e-12,
    )
)


BLOCK_8_OBJECTIVE_WEIGHTS_VALID = all(
    [
        BLOCK_8_OBJECTIVE_WEIGHT_KEYS_VALID,
        BLOCK_8_OBJECTIVE_WEIGHT_VALUES_VALID,
        BLOCK_8_OBJECTIVE_WEIGHT_SUM_VALID,
    ]
)


if not BLOCK_8_OBJECTIVE_WEIGHTS_VALID:

    raise RuntimeError(
        "Notebook 06 factual objective-family weights are invalid."
    )


# =============================================================================
# Factual checkpoint and reproducibility audit
# =============================================================================

BLOCK_8_EXPECTED_CHECKPOINT_TYPE = (
    "controlled_experimental_factual_training_checkpoint"
)


BLOCK_8_FACTUAL_CHECKPOINT_TYPE_VALID = (
    NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE
    ==
    BLOCK_8_EXPECTED_CHECKPOINT_TYPE
)


BLOCK_8_FACTUAL_CHECKPOINT_AVAILABLE = bool(
    NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE_ID
)


BLOCK_8_FACTUAL_METADATA_AVAILABLE = bool(
    NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE_ID
)


BLOCK_8_FACTUAL_TARGET_CONTRACT_AVAILABLE = bool(
    NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID
)


BLOCK_8_FACTUAL_REPRODUCIBILITY_VALID = all(
    [
        NOTEBOOK_06_FACTUAL_CHECKPOINT_REPRODUCIBLE,
        NOTEBOOK_06_FACTUAL_PATH_REPRODUCIBLE,
        NOTEBOOK_06_BLOCK_7_COMPLETE,
        NOTEBOOK_06_BLOCK_7_VALID,
    ]
)


BLOCK_8_FACTUAL_CHECKPOINT_CONTRACT_VALID = all(
    [
        BLOCK_8_FACTUAL_CHECKPOINT_TYPE_VALID,
        BLOCK_8_FACTUAL_CHECKPOINT_AVAILABLE,
        BLOCK_8_FACTUAL_METADATA_AVAILABLE,
        BLOCK_8_FACTUAL_TARGET_CONTRACT_AVAILABLE,
        BLOCK_8_FACTUAL_REPRODUCIBILITY_VALID,
    ]
)


if not BLOCK_8_FACTUAL_CHECKPOINT_CONTRACT_VALID:

    raise RuntimeError(
        "Notebook 06 factual checkpoint contract is invalid."
    )


# =============================================================================
# Final factual objective audit
# =============================================================================

BLOCK_8_FINAL_OBJECTIVE = float(
    NOTEBOOK_06_FACTUAL_FINAL_OBJECTIVE
)


BLOCK_8_FINAL_OBJECTIVE_FINITE = math.isfinite(
    BLOCK_8_FINAL_OBJECTIVE
)


BLOCK_8_FINAL_FAMILY_LOSSES = deepcopy(
    NOTEBOOK_06_FACTUAL_FINAL_FAMILY_LOSSES
)


BLOCK_8_FINAL_FAMILY_LOSS_KEYS_VALID = (
    set(
        BLOCK_8_FINAL_FAMILY_LOSSES.keys()
    )
    ==
    set(
        BLOCK_8_ACTIVE_DIMENSIONS
    )
)


BLOCK_8_FINAL_FAMILY_LOSSES_FINITE = (
    BLOCK_8_FINAL_FAMILY_LOSS_KEYS_VALID
    and
    all(
        math.isfinite(
            float(
                BLOCK_8_FINAL_FAMILY_LOSSES[
                    dimension_name
                ]
            )
        )

        for dimension_name
        in BLOCK_8_ACTIVE_DIMENSIONS
    )
)


BLOCK_8_TRAINING_STATE_VALID = all(
    [
        BLOCK_8_FINAL_OBJECTIVE_FINITE,
        BLOCK_8_FINAL_FAMILY_LOSSES_FINITE,
        BLOCK_8_FACTUAL_REPRODUCIBILITY_VALID,
    ]
)


if not BLOCK_8_TRAINING_STATE_VALID:

    raise RuntimeError(
        "Notebook 06 factual training state is invalid."
    )


# =============================================================================
# Module freezing / trainability audit
# =============================================================================

BLOCK_8_BACKBONE_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in NOTEBOOK_06_BACKBONE_FROZEN_MODULE.parameters()
)


BLOCK_8_GLOBAL_CONFLUENT_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in NOTEBOOK_06_GLOBAL_CONFLUENT_FROZEN_MODULE.parameters()
)


BLOCK_8_PSYCHOLOGICAL_HEAD_FROZEN = all(
    not parameter.requires_grad

    for parameter
    in NOTEBOOK_06_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.parameters()
)


BLOCK_8_FACTUAL_HEAD_TRAINABLE = all(
    parameter.requires_grad

    for parameter
    in NOTEBOOK_06_FACTUAL_HEAD.parameters()
)


BLOCK_8_FACTUAL_PARAMETER_COUNT = sum(
    parameter.numel()

    for parameter
    in NOTEBOOK_06_FACTUAL_HEAD.parameters()
)


BLOCK_8_FACTUAL_PARAMETER_COUNT_VALID = (
    BLOCK_8_FACTUAL_PARAMETER_COUNT
    == 34442
)


BLOCK_8_MODULE_SCOPE_VALID = all(
    [
        BLOCK_8_BACKBONE_FROZEN,
        BLOCK_8_GLOBAL_CONFLUENT_FROZEN,
        BLOCK_8_PSYCHOLOGICAL_HEAD_FROZEN,
        BLOCK_8_FACTUAL_HEAD_TRAINABLE,
        BLOCK_8_FACTUAL_PARAMETER_COUNT_VALID,
    ]
)


if not BLOCK_8_MODULE_SCOPE_VALID:

    raise RuntimeError(
        "Notebook 06 module trainability boundary is invalid."
    )


# =============================================================================
# Snapshot modules before Block 8
# =============================================================================

def block_8_snapshot_module(
    module,
):

    return {
        parameter_name:
            parameter.detach()
            .cpu()
            .clone()

        for parameter_name, parameter
        in module.named_parameters()
    }


BLOCK_8_BACKBONE_STATE_BEFORE = (
    block_8_snapshot_module(
        NOTEBOOK_06_BACKBONE_FROZEN_MODULE
    )
)


BLOCK_8_GLOBAL_CONFLUENT_STATE_BEFORE = (
    block_8_snapshot_module(
        NOTEBOOK_06_GLOBAL_CONFLUENT_FROZEN_MODULE
    )
)


BLOCK_8_FACTUAL_STATE_BEFORE = (
    block_8_snapshot_module(
        NOTEBOOK_06_FACTUAL_HEAD
    )
)


BLOCK_8_PSYCHOLOGICAL_STATE_BEFORE = (
    block_8_snapshot_module(
        NOTEBOOK_06_PSYCHOLOGICAL_HEAD_FROZEN_MODULE
    )
)


# =============================================================================
# Inherited Notebook 05 → 06 handover audit
# =============================================================================
#
# Block 1 is authoritative for validation of the persisted Notebook 05 → 06
# handover.
#
# Block 8 preserves that already validated contract rather than attempting
# to reinterpret or reconstruct its internal schema.
# =============================================================================

BLOCK_8_INHERITED_HANDOVER = deepcopy(
    NOTEBOOK_06_HANDOVER
)


BLOCK_8_INHERITED_HANDOVER_PRESENT = (
    isinstance(
        BLOCK_8_INHERITED_HANDOVER,
        dict,
    )
    and
    len(
        BLOCK_8_INHERITED_HANDOVER
    )
    > 0
)


BLOCK_8_INHERITED_BLOCK_1_COMPLETE = (
    NOTEBOOK_06_BLOCK_1_COMPLETE
)


BLOCK_8_INHERITED_BLOCK_1_VALID = (
    NOTEBOOK_06_BLOCK_1_VALID
)


BLOCK_8_INHERITED_CONTRACT_VALID = all(
    [
        BLOCK_8_INHERITED_HANDOVER_PRESENT,
        BLOCK_8_INHERITED_BLOCK_1_COMPLETE,
        BLOCK_8_INHERITED_BLOCK_1_VALID,
    ]
)


if not BLOCK_8_INHERITED_CONTRACT_VALID:

    raise RuntimeError(
        "Notebook 05 → 06 inherited handover is unavailable or "
        "was not validated successfully by Notebook 06 Block 1."
    )


# =============================================================================
# Architectural completion boundary
# =============================================================================

BLOCK_8_GLOBAL_PATH_REQUIRED = True

BLOCK_8_GLOBAL_PATH_OPERATIONAL = True

BLOCK_8_GROUP_PATH_AVAILABLE = True

BLOCK_8_GROUP_PATH_REQUIRED = False

BLOCK_8_GROUP_PATH_EXECUTED = False

BLOCK_8_GROUP_PATH_TRAINED = False

BLOCK_8_GROUP_PATH_DEFERRED_TO_NOTEBOOK = 10

BLOCK_8_SOCIAL_PATH_TRAINED = False

BLOCK_8_TRANSFORMATIVE_MECHANISM_EXECUTED = False

BLOCK_8_TRANSFORMATIVE_WEIGHTS_TRAINED = False

BLOCK_8_RECURRENT_MECHANISM_EXECUTED = False


BLOCK_8_ARCHITECTURAL_BOUNDARY_VALID = all(
    [
        BLOCK_8_GLOBAL_PATH_REQUIRED,
        BLOCK_8_GLOBAL_PATH_OPERATIONAL,
        BLOCK_8_GROUP_PATH_AVAILABLE,
        not BLOCK_8_GROUP_PATH_REQUIRED,
        not BLOCK_8_GROUP_PATH_EXECUTED,
        not BLOCK_8_GROUP_PATH_TRAINED,
        (
            BLOCK_8_GROUP_PATH_DEFERRED_TO_NOTEBOOK
            == 10
        ),
        not BLOCK_8_SOCIAL_PATH_TRAINED,
        not BLOCK_8_TRANSFORMATIVE_MECHANISM_EXECUTED,
        not BLOCK_8_TRANSFORMATIVE_WEIGHTS_TRAINED,
        not BLOCK_8_RECURRENT_MECHANISM_EXECUTED,
    ]
)


if not BLOCK_8_ARCHITECTURAL_BOUNDARY_VALID:

    raise RuntimeError(
        "Notebook 06 architectural completion boundary is invalid."
    )


# =============================================================================
# Remaining Version 1 roadmap
# =============================================================================

NOTEBOOK_06_REMAINING_VERSION_1_ROADMAP = {
    "Notebook 07":
        "Social Path",

    "Notebook 08":
        "Transformative Mechanism",

    "Notebook 09":
        "Transformative Weights and Recurrent Mechanism",

    "Notebook 10":
        "Group-Conditioned Path and Final Integration",
}


# =============================================================================
# Factual dimension scope audit
# =============================================================================

BLOCK_8_FACTUAL_SCOPE_ROWS = []


for (
    dimension_id,
    dimension_name,
) in zip(
    NOTEBOOK_06_FACTUAL_DIMENSION_IDS,
    NOTEBOOK_06_FACTUAL_DIMENSION_ORDER,
):

    active = (
        dimension_name
        in
        BLOCK_8_ACTIVE_DIMENSIONS
    )


    deferred = (
        dimension_name
        in
        BLOCK_8_DEFERRED_DIMENSIONS
    )


    if active:

        if (
            dimension_name
            ==
            "factological_weight"
        ):

            objective_family = (
                "masked_mean_squared_error"
            )

        else:

            objective_family = (
                "binary_cross_entropy_with_logits"
            )


        optimisation_state = "trained"


    else:

        objective_family = "none_current_sample"

        optimisation_state = "deferred_zero_variance"


    BLOCK_8_FACTUAL_SCOPE_ROWS.append(
        {
            "dimension_id":
                dimension_id,

            "target_name":
                dimension_name,

            "structurally_present":
                True,

            "currently_active":
                active,

            "currently_deferred":
                deferred,

            "objective_family":
                objective_family,

            "optimisation_state":
                optimisation_state,

            "checkpoint_state_reproducible":
                (
                    NOTEBOOK_06_FACTUAL_PATH_REPRODUCIBLE
                    if active
                    else "not_applicable"
                ),

            "independently_evaluated":
                False,

            "empirically_validated":
                False,
        }
    )


BLOCK_8_FACTUAL_SCOPE_AUDIT = pd.DataFrame(
    BLOCK_8_FACTUAL_SCOPE_ROWS
)


# =============================================================================
# Notebook 06 functionality audit
# =============================================================================

BLOCK_8_FUNCTIONALITY_ROWS = [
    {
        "functionality":
            "contextual_sentence_representation",

        "architecture_stage":
            "textual_representation",

        "implemented_structurally":
            True,

        "used_in_notebook_06":
            True,

        "trained_in_notebook_06":
            False,

        "checkpoint_or_state_reproducible":
            True,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            (
                "Inherited contextual sentence representation "
                "contract remained frozen."
            ),
    },

    {
        "functionality":
            "mandatory_global_confluent_path",

        "architecture_stage":
            "confluent_conditioning",

        "implemented_structurally":
            True,

        "used_in_notebook_06":
            True,

        "trained_in_notebook_06":
            False,

        "checkpoint_or_state_reproducible":
            True,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            (
                "Mandatory global conditioning remained frozen "
                "during factual optimisation."
            ),
    },

    {
        "functionality":
            "psychological_representation_head",

        "architecture_stage":
            "representation_heads",

        "implemented_structurally":
            True,

        "used_in_notebook_06":
            False,

        "trained_in_notebook_06":
            False,

        "checkpoint_or_state_reproducible":
            True,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            (
                "Completed psychological path inherited from "
                "Notebook 05 and remained frozen."
            ),
    },

    {
        "functionality":
            "factual_representation_head",

        "architecture_stage":
            "representation_heads",

        "implemented_structurally":
            True,

        "used_in_notebook_06":
            True,

        "trained_in_notebook_06":
            True,

        "checkpoint_or_state_reproducible":
            NOTEBOOK_06_FACTUAL_PATH_REPRODUCIBLE,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            (
                "Controlled factual training completed; "
                "checkpoint portability and training-state "
                "reproducibility established by Block 7."
            ),
    },

    {
        "functionality":
            "social_representation_head",

        "architecture_stage":
            "representation_heads",

        "implemented_structurally":
            True,

        "used_in_notebook_06":
            False,

        "trained_in_notebook_06":
            False,

        "checkpoint_or_state_reproducible":
            False,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            "Reserved for Notebook 07.",
    },

    {
        "functionality":
            "transformative_mechanism",

        "architecture_stage":
            "transformative_mechanism",

        "implemented_structurally":
            True,

        "used_in_notebook_06":
            False,

        "trained_in_notebook_06":
            False,

        "checkpoint_or_state_reproducible":
            False,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            "Reserved for Notebook 08.",
    },

    {
        "functionality":
            "transformative_weights",

        "architecture_stage":
            "transformative_mechanism",

        "implemented_structurally":
            True,

        "used_in_notebook_06":
            False,

        "trained_in_notebook_06":
            False,

        "checkpoint_or_state_reproducible":
            False,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            "Reserved for Notebook 09.",
    },

    {
        "functionality":
            "recurrent_mechanism",

        "architecture_stage":
            "recurrent_mechanism",

        "implemented_structurally":
            True,

        "used_in_notebook_06":
            False,

        "trained_in_notebook_06":
            False,

        "checkpoint_or_state_reproducible":
            False,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            "Reserved for Notebook 09.",
    },

    {
        "functionality":
            "optional_group_conditioned_path",

        "architecture_stage":
            "confluent_conditioning",

        "implemented_structurally":
            True,

        "used_in_notebook_06":
            False,

        "trained_in_notebook_06":
            False,

        "checkpoint_or_state_reproducible":
            False,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            (
                "Architecturally available but deliberately "
                "deferred to Notebook 10."
            ),
    },
]


BLOCK_8_FUNCTIONALITY_AUDIT = pd.DataFrame(
    BLOCK_8_FUNCTIONALITY_ROWS
)


# =============================================================================
# Factual path completion
# =============================================================================

BLOCK_8_FACTUAL_PATH_COMPLETE = all(
    [
        NOTEBOOK_06_FACTUAL_MAPPING_RESOLVED,
        NOTEBOOK_06_FACTUAL_TARGET_CONTRACT_VALID,
        NOTEBOOK_06_FACTUAL_OBJECTIVE_POLICY_VALID,
        NOTEBOOK_06_FACTUAL_MODEL_POLICY_READY,
        NOTEBOOK_06_FACTUAL_OPTIMIZER_POLICY_VALID,
        NOTEBOOK_06_FACTUAL_CHECKPOINT_REPRODUCIBLE,
        NOTEBOOK_06_FACTUAL_PATH_REPRODUCIBLE,
    ]
)


BLOCK_8_CONTROLLED_FACTUAL_PIPELINE_COMPLETE = all(
    [
        BLOCK_8_FACTUAL_PATH_COMPLETE,
        BLOCK_8_FACTUAL_CHECKPOINT_CONTRACT_VALID,
        BLOCK_8_TRAINING_STATE_VALID,
    ]
)


if not BLOCK_8_FACTUAL_PATH_COMPLETE:

    raise RuntimeError(
        "Notebook 06 factual path is not complete."
    )


# =============================================================================
# Factual training state derived from persisted Block 6 artefacts
# =============================================================================

BLOCK_8_TRAINING_CHECKPOINT = deepcopy(
    NOTEBOOK_06_FACTUAL_CHECKPOINT
)


BLOCK_8_TRAINING_METADATA = deepcopy(
    NOTEBOOK_06_FACTUAL_TRAINING_METADATA
)


BLOCK_8_TRAINING_SCOPE = deepcopy(
    BLOCK_8_TRAINING_METADATA[
        "training_scope"
    ]
)


BLOCK_8_TRAINING_ARTICLE_COUNT = int(
    BLOCK_8_TRAINING_SCOPE[
        "articles"
    ]
)


BLOCK_8_TRAINING_SENTENCE_COUNT = int(
    BLOCK_8_TRAINING_SCOPE[
        "sentences"
    ]
)


BLOCK_8_TRAINING_ARTICLE_IDS = tuple(
    BLOCK_8_TRAINING_SCOPE.get(
        "article_ids",
        [],
    )
)


BLOCK_8_TRAINING_EPOCHS = int(
    BLOCK_8_TRAINING_SCOPE[
        "epochs"
    ]
)


BLOCK_8_WITHIN_ARTICLE_SHUFFLE = bool(
    BLOCK_8_TRAINING_SCOPE[
        "within_article_shuffle"
    ]
)


BLOCK_8_ARTICLE_SEQUENCE_PRESERVED = bool(
    BLOCK_8_TRAINING_SCOPE[
        "article_sequence_preserved"
    ]
)


BLOCK_8_OPTIMISATION_METADATA = deepcopy(
    BLOCK_8_TRAINING_METADATA[
        "optimisation"
    ]
)


BLOCK_8_OPTIMIZER_NAME = str(
    BLOCK_8_OPTIMISATION_METADATA[
        "optimizer"
    ]
)


BLOCK_8_LEARNING_RATE = float(
    BLOCK_8_OPTIMISATION_METADATA[
        "learning_rate"
    ]
)


BLOCK_8_WEIGHT_DECAY = float(
    BLOCK_8_OPTIMISATION_METADATA[
        "weight_decay"
    ]
)


BLOCK_8_MAXIMUM_GRADIENT_NORM = float(
    BLOCK_8_OPTIMISATION_METADATA[
        "maximum_gradient_norm"
    ]
)


BLOCK_8_TRAINING_SCOPE_VALID = all(
    [
        BLOCK_8_TRAINING_ARTICLE_COUNT
        ==
        BLOCK_8_DERIVED_ARTICLE_COUNT,

        BLOCK_8_TRAINING_SENTENCE_COUNT
        ==
        BLOCK_8_DERIVED_SENTENCE_COUNT,

        (
            not BLOCK_8_TRAINING_ARTICLE_IDS
            or
            BLOCK_8_TRAINING_ARTICLE_IDS
            ==
            BLOCK_8_DERIVED_ARTICLE_IDS
        ),

        BLOCK_8_TRAINING_EPOCHS > 0,

        not BLOCK_8_WITHIN_ARTICLE_SHUFFLE,

        BLOCK_8_ARTICLE_SEQUENCE_PRESERVED,

        BLOCK_8_OPTIMIZER_NAME == "AdamW",

        math.isfinite(
            BLOCK_8_LEARNING_RATE
        )
        and
        BLOCK_8_LEARNING_RATE > 0.0,

        math.isfinite(
            BLOCK_8_WEIGHT_DECAY
        )
        and
        BLOCK_8_WEIGHT_DECAY >= 0.0,

        math.isfinite(
            BLOCK_8_MAXIMUM_GRADIENT_NORM
        )
        and
        BLOCK_8_MAXIMUM_GRADIENT_NORM > 0.0,
    ]
)


if not BLOCK_8_TRAINING_SCOPE_VALID:

    raise RuntimeError(
        "Notebook 06 persisted factual training scope is invalid."
    )


# =============================================================================
# Construct Notebook 06 → Notebook 07 handover
# =============================================================================

NOTEBOOK_06_TO_07_HANDOVER = {
    "handover_type":
        "media_ai_notebook_06_to_07_handover",

    "handover_version":
        NOTEBOOK_06_TO_07_HANDOVER_VERSION,

    "created_at_utc":
        BLOCK_8_EXECUTED_AT_UTC,

    "source_notebook":
        "06_factual_path",

    "target_notebook":
        "07_social_path",

    # =========================================================================
    # Project state
    # =========================================================================

    "project_state":
        {
            "notebook_06_complete":
                True,

            "factual_path_complete":
                True,

            "factual_path_reproducible":
                True,

            "controlled_factual_pipeline_complete":
                True,

            "full_media_ai_project_complete":
                False,

            "full_training_coverage":
                False,

            "generalisation_validated":
                False,

            "empirical_validity":
                False,
        },

    # =========================================================================
    # Canonical identity
    # =========================================================================

    "canonical_identity":
        {
            "articles":
                int(
                    NOTEBOOK_06_ARTICLE_COUNT
                ),

            "sentences":
                int(
                    NOTEBOOK_06_SENTENCE_COUNT
                ),

            "sentence_ids":
                list(
                    NOTEBOOK_06_SENTENCE_IDS
                ),

            "sentence_ids_present":
                bool(
                    BLOCK_8_SENTENCE_IDS_PRESENT
                ),

            "sentence_ids_unique":
                bool(
                    BLOCK_8_SENTENCE_IDS_UNIQUE
                ),

            "identity_contract_valid":
                bool(
                    BLOCK_8_IDENTITY_CONTRACT_VALID
                ),
        },

    # =========================================================================
    # Inherited Notebook 05 → 06 handover
    # =========================================================================

    "inherited_notebook_05_to_06_handover":
        deepcopy(
            BLOCK_8_INHERITED_HANDOVER
        ),

    "inherited_handover_reference":
        {
            "drive_file_id":
                NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID,

            "validated_by_notebook_06_block_1":
                True,
        },

    # =========================================================================
    # Factual path contract
    # =========================================================================

    "factual_path":
        {
            "representation_dimension":
                int(
                    NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM
                ),

            "dimension_ids":
                list(
                    NOTEBOOK_06_FACTUAL_DIMENSION_IDS
                ),

            "dimension_order":
                list(
                    NOTEBOOK_06_FACTUAL_DIMENSION_ORDER
                ),

            "active_dimensions":
                list(
                    BLOCK_8_ACTIVE_DIMENSIONS
                ),

            "deferred_dimensions":
                list(
                    BLOCK_8_DEFERRED_DIMENSIONS
                ),

            "active_binary_dimensions":
                list(
                    BLOCK_8_ACTIVE_BINARY_DIMENSIONS
                ),

            "active_continuous_dimensions":
                list(
                    BLOCK_8_ACTIVE_CONTINUOUS_DIMENSIONS
                ),

            "positive_class_weights":
                deepcopy(
                    BLOCK_8_POSITIVE_CLASS_WEIGHTS
                ),

            "weighted_binary_dimensions":
                list(
                    BLOCK_8_WEIGHTED_BINARY_DIMENSIONS
                ),

            "prediction_positive_weight":
                (
                    float(
                        BLOCK_8_PREDICTION_POSITIVE_WEIGHT
                    )
                    if BLOCK_8_PREDICTION_POSITIVE_WEIGHT is not None
                    else None
                ),

            "objective_weights":
                deepcopy(
                    BLOCK_8_OBJECTIVE_WEIGHTS
                ),

            "mask_aware_supervision":
                True,

            "missing_equals_zero":
                False,

            "missing_equals_negative":
                False,

            "unavailable_enters_loss":
                False,

            "mapping_resolved":
                True,

            "target_contract_valid":
                True,

            "objective_policy_valid":
                True,

            "model_policy_valid":
                True,

            "optimizer_policy_valid":
                True,

            "checkpoint_reproducible":
                True,
        },

    # =========================================================================
    # Persisted factual artefacts
    # =========================================================================

    "factual_persisted_artefacts":
        {
            "target_contract":
                {
                    "filename":
                        "notebook_06_factual_target_contract.json",

                    "drive_file_id":
                        NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID,
                },

            "training_checkpoint":
                {
                    "filename":
                        NOTEBOOK_06_FACTUAL_CHECKPOINT_FILENAME,

                    "drive_file_id":
                        NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE_ID,

                    "checkpoint_type":
                        NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE,

                    "validated_model_checkpoint":
                        False,

                    "reproducible":
                        True,
                },

            "training_metadata":
                {
                    "filename":
                        NOTEBOOK_06_FACTUAL_METADATA_FILENAME,

                    "drive_file_id":
                        NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE_ID,
                },
        },

    # =========================================================================
    # Factual training state
    # =========================================================================

    "factual_training_state":
        {
            "final_total_objective":
                float(
                    BLOCK_8_FINAL_OBJECTIVE
                ),

            "final_family_losses":
                deepcopy(
                    BLOCK_8_FINAL_FAMILY_LOSSES
                ),

            "training_articles":
                int(
                    BLOCK_8_TRAINING_ARTICLE_COUNT
                ),

            "training_sentences":
                int(
                    BLOCK_8_TRAINING_SENTENCE_COUNT
                ),

            "training_article_ids":
                list(
                    BLOCK_8_DERIVED_ARTICLE_IDS
                ),

            "validation_sentences":
                int(
                    BLOCK_8_TRAINING_SCOPE[
                        "validation_sentences"
                    ]
                ),

            "test_sentences":
                int(
                    BLOCK_8_TRAINING_SCOPE[
                        "test_sentences"
                    ]
                ),

            "epochs":
                int(
                    BLOCK_8_TRAINING_EPOCHS
                ),

            "within_article_shuffle":
                bool(
                    BLOCK_8_WITHIN_ARTICLE_SHUFFLE
                ),

            "article_sequence_preserved":
                bool(
                    BLOCK_8_ARTICLE_SEQUENCE_PRESERVED
                ),

            "optimizer":
                BLOCK_8_OPTIMIZER_NAME,

            "learning_rate":
                float(
                    BLOCK_8_LEARNING_RATE
                ),

            "weight_decay":
                float(
                    BLOCK_8_WEIGHT_DECAY
                ),

            "maximum_gradient_norm":
                float(
                    BLOCK_8_MAXIMUM_GRADIENT_NORM
                ),

            "factual_trainable_parameters":
                int(
                    BLOCK_8_FACTUAL_PARAMETER_COUNT
                ),
        },

    # =========================================================================
    # Notebook 07 starting contract
    # =========================================================================
    # Notebook 07 starting contract
    # =========================================================================

    "notebook_07_starting_state":
        {
            "notebook_designation":
                "Social Path",

            "backbone_state":
                "frozen",

            "global_confluent_state":
                "frozen",

            "psychological_path_state":
                "frozen",

            "factual_path_state":
                "frozen_by_default",

            "social_path_state":
                "not_yet_trained",

            "joint_retraining_allowed_implicitly":
                False,

            "ready_to_initialise":
                True,
        },

    # =========================================================================
    # Architectural boundary
    # =========================================================================

    "architectural_boundary":
        {
            "mandatory_global_path_required":
                True,

            "mandatory_global_path_operational":
                True,

            "group_path_available":
                True,

            "group_path_required":
                False,

            "group_path_executed":
                False,

            "group_path_trained":
                False,

            "group_path_deferred_to_notebook":
                10,

            "social_path_trained":
                False,

            "transformative_mechanism_executed":
                False,

            "transformative_weights_trained":
                False,

            "recurrent_mechanism_executed":
                False,
        },

    # =========================================================================
    # Sequence boundary
    # =========================================================================

    "sequence_boundary":
        {
            "prediction_unit":
                "sentence",

            "preceding_context_allowed":
                True,

            "future_context_allowed":
                False,

            "sentence_order_preserved":
                True,

            "article_boundary_reset":
                True,

            "cross_article_state_carry":
                False,
        },

    # =========================================================================
    # Remaining roadmap
    # =========================================================================

    "remaining_version_1_roadmap":
        deepcopy(
            NOTEBOOK_06_REMAINING_VERSION_1_ROADMAP
        ),

    # =========================================================================
    # Methodological boundary
    # =========================================================================

    "methodological_boundary":
        {
            "controlled_experimental_factual_checkpoint":
                True,

            "factual_checkpoint_reproducible":
                True,

            "validated_model_checkpoint":
                False,

            "held_out_evaluation_executed":
                False,

            "validation_early_stopping":
                False,

            "training_loss_used_as_generalisation_evidence":
                False,

            "group_conditioned_validity":
                False,

            "social_path_validity":
                False,

            "transformative_validity":
                False,

            "recurrent_validity":
                False,

            "generalisation_validated":
                False,

            "empirical_validity":
                False,
        },
}


# =============================================================================
# JSON serialisation helper
# =============================================================================

def block_8_json_default(
    value,
):

    if isinstance(
        value,
        np.generic,
    ):

        return value.item()


    if isinstance(
        value,
        np.ndarray,
    ):

        return value.tolist()


    if isinstance(
        value,
        torch.Tensor,
    ):

        return (
            value.detach()
            .cpu()
            .tolist()
        )


    if isinstance(
        value,
        set,
    ):

        return sorted(
            value
        )


    if isinstance(
        value,
        tuple,
    ):

        return list(
            value
        )


    raise TypeError(
        f"Object of type {type(value).__name__} "
        "is not JSON serialisable."
    )


# =============================================================================
# Serialise handover
# =============================================================================

NOTEBOOK_06_TO_07_HANDOVER_JSON = json.dumps(
    NOTEBOOK_06_TO_07_HANDOVER,
    indent=2,
    ensure_ascii=False,
    default=
        block_8_json_default,
)


BLOCK_8_HANDOVER_JSON_VALID = bool(
    NOTEBOOK_06_TO_07_HANDOVER_JSON
)


if not BLOCK_8_HANDOVER_JSON_VALID:

    raise RuntimeError(
        "Notebook 06 → 07 handover could not be serialised."
    )


# =============================================================================
# Local persistence
# =============================================================================

with open(
    NOTEBOOK_06_TO_07_HANDOVER_FILENAME,
    "w",
    encoding="utf-8",
) as handover_file:

    handover_file.write(
        NOTEBOOK_06_TO_07_HANDOVER_JSON
    )


BLOCK_8_LOCAL_HANDOVER_CREATED = True


# =============================================================================
# Resolve persistent Drive parent
# =============================================================================

BLOCK_8_SOURCE_HANDOVER_METADATA = (
    NOTEBOOK_06_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID,
        fields=
            "id,name,parents",
    )
    .execute()
)


BLOCK_8_PARENT_IDS = (
    BLOCK_8_SOURCE_HANDOVER_METADATA.get(
        "parents",
        [],
    )
)


# =============================================================================
# Drive persistence helper
# =============================================================================

def block_8_persist_json_to_drive(
    drive_service,
    filename,
    json_text,
    parent_ids=None,
):

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )


    search_response = (
        drive_service.files()
        .list(
            q=(
                f"name = '{escaped_filename}' "
                "and trashed = false"
            ),
            spaces=
                "drive",
            fields=
                "files(id,name,modifiedTime,parents)",
            orderBy=
                "modifiedTime desc",
            pageSize=
                20,
        )
        .execute()
    )


    matching_files = search_response.get(
        "files",
        [],
    )


    media = MediaIoBaseUpload(
        io.BytesIO(
            json_text.encode(
                "utf-8"
            )
        ),
        mimetype=
            "application/json",
        resumable=
            False,
    )


    if matching_files:

        drive_file = (
            drive_service.files()
            .update(
                fileId=
                    matching_files[
                        0
                    ][
                        "id"
                    ],
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "updated"


    else:

        metadata = {
            "name":
                filename
        }


        if parent_ids:

            metadata[
                "parents"
            ] = parent_ids


        drive_file = (
            drive_service.files()
            .create(
                body=
                    metadata,
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "created"


    return (
        drive_file,
        operation,
    )


# =============================================================================
# Persist Notebook 06 → 07 handover
# =============================================================================

(
    NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE,
    NOTEBOOK_06_TO_07_HANDOVER_DRIVE_OPERATION,
) = block_8_persist_json_to_drive(
    drive_service=
        NOTEBOOK_06_DRIVE_SERVICE,

    filename=
        NOTEBOOK_06_TO_07_HANDOVER_FILENAME,

    json_text=
        NOTEBOOK_06_TO_07_HANDOVER_JSON,

    parent_ids=
        BLOCK_8_PARENT_IDS,
)


NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID = (
    NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE.get(
        "id"
    )
)


BLOCK_8_HANDOVER_DRIVE_PERSISTED = bool(
    NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID
)


if not BLOCK_8_HANDOVER_DRIVE_PERSISTED:

    raise RuntimeError(
        "Notebook 06 → 07 handover was not persisted to Drive."
    )


# =============================================================================
# Drive read-back helper
# =============================================================================

def block_8_download_drive_bytes(
    drive_service,
    file_id,
):

    request = (
        drive_service.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Read back persisted handover
# =============================================================================

BLOCK_8_RELOADED_HANDOVER_BYTES = (
    block_8_download_drive_bytes(
        NOTEBOOK_06_DRIVE_SERVICE,
        NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID,
    )
)


if not BLOCK_8_RELOADED_HANDOVER_BYTES:

    raise RuntimeError(
        "Persisted Notebook 06 → 07 handover was empty."
    )


BLOCK_8_RELOADED_HANDOVER = json.loads(
    BLOCK_8_RELOADED_HANDOVER_BYTES.decode(
        "utf-8"
    )
)


# =============================================================================
# Handover read-back validation
# =============================================================================

BLOCK_8_READBACK_TYPE_VALID = (
    BLOCK_8_RELOADED_HANDOVER.get(
        "handover_type"
    )
    ==
    "media_ai_notebook_06_to_07_handover"
)


BLOCK_8_READBACK_VERSION_VALID = (
    BLOCK_8_RELOADED_HANDOVER.get(
        "handover_version"
    )
    ==
    NOTEBOOK_06_TO_07_HANDOVER_VERSION
)


BLOCK_8_READBACK_SOURCE_VALID = (
    BLOCK_8_RELOADED_HANDOVER.get(
        "source_notebook"
    )
    ==
    "06_factual_path"
)


BLOCK_8_READBACK_TARGET_VALID = (
    BLOCK_8_RELOADED_HANDOVER.get(
        "target_notebook"
    )
    ==
    "07_social_path"
)


BLOCK_8_READBACK_PROJECT_STATE = (
    BLOCK_8_RELOADED_HANDOVER.get(
        "project_state",
        {},
    )
)


BLOCK_8_READBACK_NOTEBOOK_06_COMPLETE = (
    BLOCK_8_READBACK_PROJECT_STATE.get(
        "notebook_06_complete"
    )
    is True
)


BLOCK_8_READBACK_FACTUAL_COMPLETE = (
    BLOCK_8_READBACK_PROJECT_STATE.get(
        "factual_path_complete"
    )
    is True
)


BLOCK_8_READBACK_FACTUAL_REPRODUCIBLE = (
    BLOCK_8_READBACK_PROJECT_STATE.get(
        "factual_path_reproducible"
    )
    is True
)


BLOCK_8_READBACK_FULL_PROJECT_INCOMPLETE = (
    BLOCK_8_READBACK_PROJECT_STATE.get(
        "full_media_ai_project_complete"
    )
    is False
)


BLOCK_8_READBACK_FACTUAL_DIMENSION_VALID = (
    BLOCK_8_RELOADED_HANDOVER[
        "factual_path"
    ][
        "representation_dimension"
    ]
    == 10
)


BLOCK_8_READBACK_ACTIVE_DIMENSIONS_VALID = (
    tuple(
        BLOCK_8_RELOADED_HANDOVER[
            "factual_path"
        ][
            "active_dimensions"
        ]
    )
    ==
    BLOCK_8_ACTIVE_DIMENSIONS
)


BLOCK_8_READBACK_DEFERRED_DIMENSIONS_VALID = (
    tuple(
        BLOCK_8_RELOADED_HANDOVER[
            "factual_path"
        ][
            "deferred_dimensions"
        ]
    )
    ==
    BLOCK_8_DEFERRED_DIMENSIONS
)


BLOCK_8_READBACK_CHECKPOINT_ID_VALID = (
    BLOCK_8_RELOADED_HANDOVER[
        "factual_persisted_artefacts"
    ][
        "training_checkpoint"
    ][
        "drive_file_id"
    ]
    ==
    NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE_ID
)


BLOCK_8_READBACK_METADATA_ID_VALID = (
    BLOCK_8_RELOADED_HANDOVER[
        "factual_persisted_artefacts"
    ][
        "training_metadata"
    ][
        "drive_file_id"
    ]
    ==
    NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE_ID
)


BLOCK_8_READBACK_TARGET_ID_VALID = (
    BLOCK_8_RELOADED_HANDOVER[
        "factual_persisted_artefacts"
    ][
        "target_contract"
    ][
        "drive_file_id"
    ]
    ==
    NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID
)


BLOCK_8_READBACK_INHERITED_HANDOVER_PRESENT = (
    isinstance(
        BLOCK_8_RELOADED_HANDOVER.get(
            "inherited_notebook_05_to_06_handover"
        ),
        dict,
    )
    and
    len(
        BLOCK_8_RELOADED_HANDOVER[
            "inherited_notebook_05_to_06_handover"
        ]
    )
    > 0
)


BLOCK_8_READBACK_INHERITED_VALIDATION_SOURCE = (
    BLOCK_8_RELOADED_HANDOVER[
        "inherited_handover_reference"
    ][
        "validated_by_notebook_06_block_1"
    ]
    is True
)


BLOCK_8_READBACK_NOTEBOOK_07_READY = (
    BLOCK_8_RELOADED_HANDOVER[
        "notebook_07_starting_state"
    ][
        "ready_to_initialise"
    ]
    is True
)


BLOCK_8_READBACK_PSYCHOLOGICAL_FROZEN = (
    BLOCK_8_RELOADED_HANDOVER[
        "notebook_07_starting_state"
    ][
        "psychological_path_state"
    ]
    ==
    "frozen"
)


BLOCK_8_READBACK_FACTUAL_FROZEN = (
    BLOCK_8_RELOADED_HANDOVER[
        "notebook_07_starting_state"
    ][
        "factual_path_state"
    ]
    ==
    "frozen_by_default"
)


BLOCK_8_READBACK_GROUP_DEFERRED = (
    BLOCK_8_RELOADED_HANDOVER[
        "architectural_boundary"
    ][
        "group_path_deferred_to_notebook"
    ]
    == 10
)


BLOCK_8_READBACK_EMPIRICAL_VALIDITY_FALSE = (
    BLOCK_8_RELOADED_HANDOVER[
        "methodological_boundary"
    ][
        "empirical_validity"
    ]
    is False
)




BLOCK_8_READBACK_POSITIVE_CLASS_WEIGHTS = deepcopy(
    BLOCK_8_RELOADED_HANDOVER[
        "factual_path"
    ].get(
        "positive_class_weights",
        {},
    )
)


BLOCK_8_READBACK_POSITIVE_CLASS_WEIGHTS_VALID = (
    set(
        BLOCK_8_READBACK_POSITIVE_CLASS_WEIGHTS.keys()
    )
    ==
    set(
        BLOCK_8_POSITIVE_CLASS_WEIGHTS.keys()
    )
    and
    all(
        math.isclose(
            float(
                BLOCK_8_READBACK_POSITIVE_CLASS_WEIGHTS[
                    dimension_name
                ]
            ),
            float(
                BLOCK_8_POSITIVE_CLASS_WEIGHTS[
                    dimension_name
                ]
            ),
            rel_tol=0.0,
            abs_tol=1e-12,
        )

        for dimension_name
        in BLOCK_8_POSITIVE_CLASS_WEIGHTS
    )
)


BLOCK_8_READBACK_TRAINING_STATE = (
    BLOCK_8_RELOADED_HANDOVER[
        "factual_training_state"
    ]
)


BLOCK_8_READBACK_TRAINING_SCOPE_VALID = all(
    [
        int(
            BLOCK_8_READBACK_TRAINING_STATE[
                "training_articles"
            ]
        )
        ==
        BLOCK_8_TRAINING_ARTICLE_COUNT,

        int(
            BLOCK_8_READBACK_TRAINING_STATE[
                "training_sentences"
            ]
        )
        ==
        BLOCK_8_TRAINING_SENTENCE_COUNT,

        tuple(
            BLOCK_8_READBACK_TRAINING_STATE.get(
                "training_article_ids",
                [],
            )
        )
        ==
        BLOCK_8_DERIVED_ARTICLE_IDS,

        int(
            BLOCK_8_READBACK_TRAINING_STATE[
                "epochs"
            ]
        )
        ==
        BLOCK_8_TRAINING_EPOCHS,

        str(
            BLOCK_8_READBACK_TRAINING_STATE[
                "optimizer"
            ]
        )
        ==
        BLOCK_8_OPTIMIZER_NAME,
    ]
)

BLOCK_8_HANDOVER_READBACK_VALID = all(
    [
        BLOCK_8_READBACK_TYPE_VALID,
        BLOCK_8_READBACK_VERSION_VALID,
        BLOCK_8_READBACK_SOURCE_VALID,
        BLOCK_8_READBACK_TARGET_VALID,
        BLOCK_8_READBACK_NOTEBOOK_06_COMPLETE,
        BLOCK_8_READBACK_FACTUAL_COMPLETE,
        BLOCK_8_READBACK_FACTUAL_REPRODUCIBLE,
        BLOCK_8_READBACK_FULL_PROJECT_INCOMPLETE,
        BLOCK_8_READBACK_FACTUAL_DIMENSION_VALID,
        BLOCK_8_READBACK_ACTIVE_DIMENSIONS_VALID,
        BLOCK_8_READBACK_DEFERRED_DIMENSIONS_VALID,
        BLOCK_8_READBACK_POSITIVE_CLASS_WEIGHTS_VALID,
        BLOCK_8_READBACK_TRAINING_SCOPE_VALID,
        BLOCK_8_READBACK_CHECKPOINT_ID_VALID,
        BLOCK_8_READBACK_METADATA_ID_VALID,
        BLOCK_8_READBACK_TARGET_ID_VALID,
        BLOCK_8_READBACK_INHERITED_HANDOVER_PRESENT,
        BLOCK_8_READBACK_INHERITED_VALIDATION_SOURCE,
        BLOCK_8_READBACK_NOTEBOOK_07_READY,
        BLOCK_8_READBACK_PSYCHOLOGICAL_FROZEN,
        BLOCK_8_READBACK_FACTUAL_FROZEN,
        BLOCK_8_READBACK_GROUP_DEFERRED,
        BLOCK_8_READBACK_EMPIRICAL_VALIDITY_FALSE,
    ]
)


if not BLOCK_8_HANDOVER_READBACK_VALID:

    raise RuntimeError(
        "Persisted Notebook 06 → 07 handover failed "
        "read-back validation."
    )


# =============================================================================
# Verify no parameter changes during Block 8
# =============================================================================

def block_8_states_equal(
    before_state,
    after_state,
):

    if (
        set(
            before_state.keys()
        )
        !=
        set(
            after_state.keys()
        )
    ):

        return False


    return all(
        torch.equal(
            before_state[
                parameter_name
            ],
            after_state[
                parameter_name
            ],
        )

        for parameter_name
        in before_state
    )


BLOCK_8_BACKBONE_STATE_AFTER = (
    block_8_snapshot_module(
        NOTEBOOK_06_BACKBONE_FROZEN_MODULE
    )
)


BLOCK_8_GLOBAL_CONFLUENT_STATE_AFTER = (
    block_8_snapshot_module(
        NOTEBOOK_06_GLOBAL_CONFLUENT_FROZEN_MODULE
    )
)


BLOCK_8_FACTUAL_STATE_AFTER = (
    block_8_snapshot_module(
        NOTEBOOK_06_FACTUAL_HEAD
    )
)


BLOCK_8_PSYCHOLOGICAL_STATE_AFTER = (
    block_8_snapshot_module(
        NOTEBOOK_06_PSYCHOLOGICAL_HEAD_FROZEN_MODULE
    )
)


BLOCK_8_BACKBONE_UNCHANGED = (
    block_8_states_equal(
        BLOCK_8_BACKBONE_STATE_BEFORE,
        BLOCK_8_BACKBONE_STATE_AFTER,
    )
)


BLOCK_8_GLOBAL_CONFLUENT_UNCHANGED = (
    block_8_states_equal(
        BLOCK_8_GLOBAL_CONFLUENT_STATE_BEFORE,
        BLOCK_8_GLOBAL_CONFLUENT_STATE_AFTER,
    )
)


BLOCK_8_FACTUAL_HEAD_UNCHANGED = (
    block_8_states_equal(
        BLOCK_8_FACTUAL_STATE_BEFORE,
        BLOCK_8_FACTUAL_STATE_AFTER,
    )
)


BLOCK_8_PSYCHOLOGICAL_HEAD_UNCHANGED = (
    block_8_states_equal(
        BLOCK_8_PSYCHOLOGICAL_STATE_BEFORE,
        BLOCK_8_PSYCHOLOGICAL_STATE_AFTER,
    )
)


BLOCK_8_ALL_PARAMETERS_UNCHANGED = all(
    [
        BLOCK_8_BACKBONE_UNCHANGED,
        BLOCK_8_GLOBAL_CONFLUENT_UNCHANGED,
        BLOCK_8_FACTUAL_HEAD_UNCHANGED,
        BLOCK_8_PSYCHOLOGICAL_HEAD_UNCHANGED,
    ]
)


if not BLOCK_8_ALL_PARAMETERS_UNCHANGED:

    raise RuntimeError(
        "One or more model parameters changed during Block 8."
    )


# =============================================================================
# Notebook 07 starting contract
# =============================================================================

NOTEBOOK_07_SOCIAL_PATH_DESIGNATION = (
    "Social Path"
)


NOTEBOOK_07_BACKBONE_FROZEN_BY_DEFAULT = True

NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_BY_DEFAULT = True

NOTEBOOK_07_PSYCHOLOGICAL_PATH_FROZEN_BY_DEFAULT = True

NOTEBOOK_07_FACTUAL_PATH_FROZEN_BY_DEFAULT = True


NOTEBOOK_07_READY_TO_INITIALISE = (
    BLOCK_8_HANDOVER_READBACK_VALID
)


# =============================================================================
# Notebook 06 completion state
# =============================================================================

NOTEBOOK_06_FACTUAL_PATH_COMPLETE = (
    BLOCK_8_FACTUAL_PATH_COMPLETE
)


NOTEBOOK_06_CONTROLLED_FACTUAL_PIPELINE_COMPLETE = (
    BLOCK_8_CONTROLLED_FACTUAL_PIPELINE_COMPLETE
)


NOTEBOOK_06_FULL_MEDIA_AI_PROJECT_COMPLETE = False

NOTEBOOK_06_FULL_TRAINING_COVERAGE = False

NOTEBOOK_06_GENERALISATION_VALIDATED = False

NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED = False


NOTEBOOK_06_COMPLETE = all(
    [
        BLOCK_8_PREVIOUS_BLOCKS_COMPLETE,
        BLOCK_8_PREVIOUS_BLOCKS_VALID,
        BLOCK_8_IDENTITY_CONTRACT_VALID,
        BLOCK_8_FACTUAL_SEMANTIC_CONTRACT_VALID,
        BLOCK_8_OBJECTIVE_BOUNDARY_VALID,
        BLOCK_8_POSITIVE_CLASS_WEIGHT_POLICY_VALID,
        BLOCK_8_OBJECTIVE_WEIGHTS_VALID,
        BLOCK_8_TRAINING_SCOPE_VALID,
        BLOCK_8_FACTUAL_CHECKPOINT_CONTRACT_VALID,
        BLOCK_8_TRAINING_STATE_VALID,
        BLOCK_8_MODULE_SCOPE_VALID,
        BLOCK_8_INHERITED_CONTRACT_VALID,
        BLOCK_8_ARCHITECTURAL_BOUNDARY_VALID,
        BLOCK_8_HANDOVER_DRIVE_PERSISTED,
        BLOCK_8_HANDOVER_READBACK_VALID,
        BLOCK_8_ALL_PARAMETERS_UNCHANGED,
        NOTEBOOK_07_READY_TO_INITIALISE,
    ]
)


# =============================================================================
# Final Block 8 validation
# =============================================================================

NOTEBOOK_06_BLOCK_8_ERRORS = []


block_8_validation_checks = {
    "previous_blocks_incomplete":
        BLOCK_8_PREVIOUS_BLOCKS_COMPLETE,

    "previous_blocks_invalid":
        BLOCK_8_PREVIOUS_BLOCKS_VALID,

    "identity_contract_invalid":
        BLOCK_8_IDENTITY_CONTRACT_VALID,

    "factual_semantic_contract_invalid":
        BLOCK_8_FACTUAL_SEMANTIC_CONTRACT_VALID,

    "objective_boundary_invalid":
        BLOCK_8_OBJECTIVE_BOUNDARY_VALID,

    "positive_class_weight_policy_invalid":
        BLOCK_8_POSITIVE_CLASS_WEIGHT_POLICY_VALID,

    "objective_weights_invalid":
        BLOCK_8_OBJECTIVE_WEIGHTS_VALID,

    "training_scope_invalid":
        BLOCK_8_TRAINING_SCOPE_VALID,

    "factual_checkpoint_contract_invalid":
        BLOCK_8_FACTUAL_CHECKPOINT_CONTRACT_VALID,

    "training_state_invalid":
        BLOCK_8_TRAINING_STATE_VALID,

    "module_scope_invalid":
        BLOCK_8_MODULE_SCOPE_VALID,

    "inherited_handover_invalid":
        BLOCK_8_INHERITED_CONTRACT_VALID,

    "architectural_boundary_invalid":
        BLOCK_8_ARCHITECTURAL_BOUNDARY_VALID,

    "factual_path_incomplete":
        BLOCK_8_FACTUAL_PATH_COMPLETE,

    "controlled_pipeline_incomplete":
        BLOCK_8_CONTROLLED_FACTUAL_PIPELINE_COMPLETE,

    "handover_json_invalid":
        BLOCK_8_HANDOVER_JSON_VALID,

    "local_handover_not_created":
        BLOCK_8_LOCAL_HANDOVER_CREATED,

    "handover_not_persisted":
        BLOCK_8_HANDOVER_DRIVE_PERSISTED,

    "handover_readback_invalid":
        BLOCK_8_HANDOVER_READBACK_VALID,

    "parameters_changed":
        BLOCK_8_ALL_PARAMETERS_UNCHANGED,

    "notebook_07_not_ready":
        NOTEBOOK_07_READY_TO_INITIALISE,

    "notebook_06_not_complete":
        NOTEBOOK_06_COMPLETE,
}


for (
    error_name,
    condition,
) in block_8_validation_checks.items():

    if not condition:

        NOTEBOOK_06_BLOCK_8_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited-operation validation
# =============================================================================

prohibited_block_8_operations = {
    "forward_pass_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_FORWARD_PASS_EXECUTED,

    "loss_incorrectly_calculated":
        NOTEBOOK_06_BLOCK_8_LOSS_CALCULATED,

    "zero_grad_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_ZERO_GRAD_EXECUTED,

    "backward_pass_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_BACKWARD_PASS_EXECUTED,

    "optimizer_incorrectly_created":
        NOTEBOOK_06_BLOCK_8_OPTIMIZER_CREATED,

    "optimizer_step_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_OPTIMIZER_STEP_EXECUTED,

    "parameter_update_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_PARAMETER_UPDATE_EXECUTED,

    "factual_training_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_FACTUAL_TRAINING_EXECUTED,

    "psychological_training_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "social_training_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_SOCIAL_TRAINING_EXECUTED,

    "group_path_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_mechanism_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_TRANSFORMATIVE_MECHANISM_EXECUTED,

    "transformative_weights_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_TRANSFORMATIVE_WEIGHTS_EXECUTED,

    "recurrent_mechanism_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_RECURRENT_MECHANISM_EXECUTED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_06_BLOCK_8_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_06_BLOCK_8_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for (
    error_name,
    operation_executed,
) in prohibited_block_8_operations.items():

    if operation_executed:

        NOTEBOOK_06_BLOCK_8_ERRORS.append(
            error_name
        )


NOTEBOOK_06_BLOCK_8_VALID = (
    len(
        NOTEBOOK_06_BLOCK_8_ERRORS
    )
    == 0
)


if not NOTEBOOK_06_BLOCK_8_VALID:

    raise RuntimeError(
        "Notebook 06 Block 8 completion and handover validation failed. "
        f"Errors: {NOTEBOOK_06_BLOCK_8_ERRORS}"
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_06_BLOCK_8_COMPLETE = True


# =============================================================================
# Notebook 07 exports
# =============================================================================

NOTEBOOK_07_HANDOVER = deepcopy(
    BLOCK_8_RELOADED_HANDOVER
)


NOTEBOOK_07_HANDOVER_DRIVE_FILE_ID = (
    NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID
)


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_06_BLOCK_8_SUMMARY = {
    "block":
        NOTEBOOK_06_BLOCK_8,

    "block_name":
        NOTEBOOK_06_BLOCK_8_NAME,

    "version":
        NOTEBOOK_06_BLOCK_8_VERSION,

    "executed_at_utc":
        BLOCK_8_EXECUTED_AT_UTC,

    "notebook_06_complete":
        NOTEBOOK_06_COMPLETE,

    "factual_path_complete":
        NOTEBOOK_06_FACTUAL_PATH_COMPLETE,

    "controlled_factual_pipeline_complete":
        NOTEBOOK_06_CONTROLLED_FACTUAL_PIPELINE_COMPLETE,

    "factual_checkpoint_reproducible":
        NOTEBOOK_06_FACTUAL_CHECKPOINT_REPRODUCIBLE,

    "full_media_ai_project_complete":
        NOTEBOOK_06_FULL_MEDIA_AI_PROJECT_COMPLETE,

    "full_training_coverage":
        NOTEBOOK_06_FULL_TRAINING_COVERAGE,

    "generalisation_validated":
        NOTEBOOK_06_GENERALISATION_VALIDATED,

    "factual_dimensions":
        10,

    "active_dimensions":
        list(
            BLOCK_8_ACTIVE_DIMENSIONS
        ),

    "deferred_dimensions":
        list(
            BLOCK_8_DEFERRED_DIMENSIONS
        ),

    "final_factual_objective":
        BLOCK_8_FINAL_OBJECTIVE,

    "handover_filename":
        NOTEBOOK_06_TO_07_HANDOVER_FILENAME,

    "handover_drive_file_id":
        NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID,

    "handover_readback_valid":
        BLOCK_8_HANDOVER_READBACK_VALID,

    "notebook_07_ready":
        NOTEBOOK_07_READY_TO_INITIALISE,

    "empirical_validity":
        NOTEBOOK_06_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_06_BLOCK_8_VALID,

    "block_complete":
        NOTEBOOK_06_BLOCK_8_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 06, Block 8: "
    "Factual Path Scope Audit, Persistent Handover "
    "and Notebook 06 Completion"
)

print("=" * 72)

print(
    f"Completion version           : "
    f"{NOTEBOOK_06_BLOCK_8_VERSION}"
)


print("-" * 72)

print(
    "Notebook 06 completion"
)

print(
    f"Blocks 1–7 complete          : "
    f"{BLOCK_8_PREVIOUS_BLOCKS_COMPLETE}"
)

print(
    f"Blocks 1–7 valid             : "
    f"{BLOCK_8_PREVIOUS_BLOCKS_VALID}"
)

print(
    f"Factual path complete        : "
    f"{NOTEBOOK_06_FACTUAL_PATH_COMPLETE}"
)

print(
    f"Controlled factual pipeline  : "
    f"{NOTEBOOK_06_CONTROLLED_FACTUAL_PIPELINE_COMPLETE}"
)

print(
    f"Factual path reproducible    : "
    f"{NOTEBOOK_06_FACTUAL_PATH_REPRODUCIBLE}"
)

print(
    f"Notebook 06 complete         : "
    f"{NOTEBOOK_06_COMPLETE}"
)

print(
    f"Full Media AI project complete: "
    f"{NOTEBOOK_06_FULL_MEDIA_AI_PROJECT_COMPLETE}"
)

print(
    f"Full training coverage       : "
    f"{NOTEBOOK_06_FULL_TRAINING_COVERAGE}"
)

print(
    f"Generalisation validated     : "
    f"{NOTEBOOK_06_GENERALISATION_VALIDATED}"
)


print("-" * 72)

print(
    "Inherited Notebook 05 → 06 contract"
)

print(
    f"Handover present             : "
    f"{BLOCK_8_INHERITED_HANDOVER_PRESENT}"
)

print(
    f"Block 1 complete             : "
    f"{BLOCK_8_INHERITED_BLOCK_1_COMPLETE}"
)

print(
    f"Block 1 handover valid       : "
    f"{BLOCK_8_INHERITED_BLOCK_1_VALID}"
)

print(
    f"Inherited contract valid     : "
    f"{BLOCK_8_INHERITED_CONTRACT_VALID}"
)


print("-" * 72)

print(
    "Factual semantic contract"
)

print(
    f"Factual representation dim.  : "
    f"{NOTEBOOK_06_FACTUAL_ARCHITECTURAL_DIM}"
)

print(
    f"Semantic contract valid      : "
    f"{BLOCK_8_FACTUAL_SEMANTIC_CONTRACT_VALID}"
)

print(
    f"Active dimensions            : "
    f"{list(BLOCK_8_ACTIVE_DIMENSIONS)}"
)

print(
    f"Deferred dimensions          : "
    f"{list(BLOCK_8_DEFERRED_DIMENSIONS)}"
)

print(
    f"Weighted binary dimensions   : "
    f"{list(BLOCK_8_WEIGHTED_BINARY_DIMENSIONS)}"
)

print(
    f"Positive class weights       : "
    f"{BLOCK_8_POSITIVE_CLASS_WEIGHTS}"
)

print(
    f"Prediction positive weight   : "
    f"{BLOCK_8_PREDICTION_POSITIVE_WEIGHT}"
)

print(
    f"Objective weights            : "
    f"{BLOCK_8_OBJECTIVE_WEIGHTS}"
)


print("-" * 72)

print(
    "Canonical training scope"
)

print(
    f"Articles                     : "
    f"{BLOCK_8_TRAINING_ARTICLE_COUNT}"
)

print(
    f"Sentences                    : "
    f"{BLOCK_8_TRAINING_SENTENCE_COUNT}"
)

print(
    f"Epochs                       : "
    f"{BLOCK_8_TRAINING_EPOCHS}"
)

print(
    f"Optimiser                    : "
    f"{BLOCK_8_OPTIMIZER_NAME}"
)

print(
    f"Training scope valid         : "
    f"{BLOCK_8_TRAINING_SCOPE_VALID}"
)


print("-" * 72)

print(
    "Factual trained-state handover"
)

print(
    f"Checkpoint type              : "
    f"{NOTEBOOK_06_FACTUAL_CHECKPOINT_TYPE}"
)

print(
    f"Checkpoint Drive file ID     : "
    f"{NOTEBOOK_06_FACTUAL_CHECKPOINT_DRIVE_FILE_ID}"
)

print(
    f"Metadata Drive file ID       : "
    f"{NOTEBOOK_06_FACTUAL_METADATA_DRIVE_FILE_ID}"
)

print(
    f"Target contract Drive ID     : "
    f"{NOTEBOOK_06_FACTUAL_TARGET_DRIVE_FILE_ID}"
)

print(
    f"Checkpoint reproducible      : "
    f"{NOTEBOOK_06_FACTUAL_CHECKPOINT_REPRODUCIBLE}"
)

print(
    f"Final factual objective      : "
    f"{BLOCK_8_FINAL_OBJECTIVE:.8f}"
)

print(
    f"Validated model checkpoint   : "
    f"{False}"
)


print("-" * 72)

print(
    "Module boundary"
)

print(
    f"Backbone frozen              : "
    f"{BLOCK_8_BACKBONE_FROZEN}"
)

print(
    f"Global confluent frozen      : "
    f"{BLOCK_8_GLOBAL_CONFLUENT_FROZEN}"
)

print(
    f"Psychological head frozen    : "
    f"{BLOCK_8_PSYCHOLOGICAL_HEAD_FROZEN}"
)

print(
    f"Factual head trainable       : "
    f"{BLOCK_8_FACTUAL_HEAD_TRAINABLE}"
)

print(
    f"Factual parameter count      : "
    f"{BLOCK_8_FACTUAL_PARAMETER_COUNT}"
)

print(
    f"All parameters unchanged     : "
    f"{BLOCK_8_ALL_PARAMETERS_UNCHANGED}"
)


print("-" * 72)

print(
    "Remaining Version 1 roadmap"
)


for (
    notebook_name,
    notebook_scope,
) in NOTEBOOK_06_REMAINING_VERSION_1_ROADMAP.items():

    print(
        f"{notebook_name:<26}: "
        f"{notebook_scope}"
    )


print("-" * 72)

print(
    "Group-conditioned path policy"
)

print(
    f"Global path required         : "
    f"{BLOCK_8_GLOBAL_PATH_REQUIRED}"
)

print(
    f"Global path operational      : "
    f"{BLOCK_8_GLOBAL_PATH_OPERATIONAL}"
)

print(
    f"Group path available         : "
    f"{BLOCK_8_GROUP_PATH_AVAILABLE}"
)

print(
    f"Group path required          : "
    f"{BLOCK_8_GROUP_PATH_REQUIRED}"
)

print(
    f"Group path executed          : "
    f"{BLOCK_8_GROUP_PATH_EXECUTED}"
)

print(
    f"Group path trained           : "
    f"{BLOCK_8_GROUP_PATH_TRAINED}"
)

print(
    f"Group path deferred to N     : "
    f"{BLOCK_8_GROUP_PATH_DEFERRED_TO_NOTEBOOK}"
)


print("-" * 72)

print(
    "Persistent Notebook 06 → Notebook 07 handover"
)

print(
    f"Handover version             : "
    f"{NOTEBOOK_06_TO_07_HANDOVER_VERSION}"
)

print(
    f"Handover filename            : "
    f"{NOTEBOOK_06_TO_07_HANDOVER_FILENAME}"
)

print(
    f"Local copy created           : "
    f"{BLOCK_8_LOCAL_HANDOVER_CREATED}"
)

print(
    f"Drive operation              : "
    f"{NOTEBOOK_06_TO_07_HANDOVER_DRIVE_OPERATION}"
)

print(
    f"Drive file ID                : "
    f"{NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID}"
)

print(
    f"Read-back valid              : "
    f"{BLOCK_8_HANDOVER_READBACK_VALID}"
)

print(
    f"Notebook 07 ready            : "
    f"{NOTEBOOK_07_READY_TO_INITIALISE}"
)


print("-" * 72)

print(
    "Notebook 07 starting contract"
)

print(
    f"Designation                  : "
    f"{NOTEBOOK_07_SOCIAL_PATH_DESIGNATION}"
)

print(
    f"Backbone frozen by default   : "
    f"{NOTEBOOK_07_BACKBONE_FROZEN_BY_DEFAULT}"
)

print(
    f"Global confluent frozen      : "
    f"{NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_BY_DEFAULT}"
)

print(
    f"Psychological path frozen    : "
    f"{NOTEBOOK_07_PSYCHOLOGICAL_PATH_FROZEN_BY_DEFAULT}"
)

print(
    f"Factual path frozen          : "
    f"{NOTEBOOK_07_FACTUAL_PATH_FROZEN_BY_DEFAULT}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Forward pass executed        : "
    f"{NOTEBOOK_06_BLOCK_8_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_06_BLOCK_8_LOSS_CALCULATED}"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_06_BLOCK_8_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_06_BLOCK_8_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_06_BLOCK_8_OPTIMIZER_CREATED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_06_BLOCK_8_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_06_BLOCK_8_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Factual training executed    : "
    f"{NOTEBOOK_06_BLOCK_8_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_06_BLOCK_8_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Social training executed     : "
    f"{NOTEBOOK_06_BLOCK_8_SOCIAL_TRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{NOTEBOOK_06_BLOCK_8_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative executed      : "
    f"{NOTEBOOK_06_BLOCK_8_TRANSFORMATIVE_MECHANISM_EXECUTED}"
)

print(
    f"Transformative weights active: "
    f"{NOTEBOOK_06_BLOCK_8_TRANSFORMATIVE_WEIGHTS_EXECUTED}"
)

print(
    f"Recurrent executed           : "
    f"{NOTEBOOK_06_BLOCK_8_RECURRENT_MECHANISM_EXECUTED}"
)

print(
    f"Held-out evaluation executed : "
    f"{NOTEBOOK_06_BLOCK_8_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_06_BLOCK_8_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_06_BLOCK_8_VALID}"
)

print(
    f"Block 8 complete             : "
    f"{NOTEBOOK_06_BLOCK_8_COMPLETE}"
)


print("=" * 72)


print(
    "Notebook 06 factual-path scope audit, persistent handover "
    "and completion validation completed successfully."
)

print(
    "The validated Notebook 05 → Notebook 06 handover was preserved "
    "without reinterpreting its internal schema; Notebook 06 Block 1 "
    "remains the authoritative handover-validation boundary."
)

print(
    "The ten-dimensional factual representation remains intact, while "
    f"{len(BLOCK_8_ACTIVE_DIMENSIONS)} factual dimensions participate in "
    "the current validated controlled objective."
)

print(
    f"{len(BLOCK_8_DEFERRED_DIMENSIONS)} factual dimension(s) remain "
    "structurally present but deferred under the current validated "
    "supervision and objective policy."
)

print(
    "The controlled factual checkpoint remains reproducible and explicitly "
    "classified as an experimental training checkpoint rather than a "
    "validated model checkpoint."
)

print(
    "The backbone, mandatory global confluent path and completed "
    "psychological representation remain frozen."
)

print(
    "The factual target contract, training metadata and reproducible "
    "checkpoint are referenced explicitly in the new Notebook 06 → "
    "Notebook 07 handover."
)

print(
    "The optional group-conditioned path remains architecturally available "
    "but unexecuted and deferred to Notebook 10."
)

print(
    "The social path, transformative mechanism, Transformative Weights "
    "and recurrent mechanism remain outside Notebook 06."
)

print(
    "No forward pass, loss calculation, optimiser creation, zero-gradient "
    "operation, backward pass, optimiser step, parameter update or new "
    "training was performed by Block 8."
)

print(
    "No held-out evaluation, generalisation claim or empirical-validity "
    "claim has been introduced."
)

print(
    "The persisted Notebook 06 → Notebook 07 handover was read back "
    "and validated successfully."
)

print(
    "Notebook 06 — Factual Path is complete within its controlled "
    "experimental scope."
)

print(
    "The full Media AI Version 1 project remains incomplete."
)

print(
    "Notebook 07 may now initialise independently from the persisted "
    "handover and begin the Social Path while keeping the completed "
    "psychological and factual paths frozen by default."
)

print("=" * 72)


# =============================================================================
# Display completion audits
# =============================================================================

display(
    BLOCK_8_FACTUAL_SCOPE_AUDIT
)


display(
    BLOCK_8_FUNCTIONALITY_AUDIT
)

========================================================================
Media AI — Notebook 06, Block 8: Factual Path Scope Audit, Persistent Handover and Notebook 06 Completion
========================================================================
Completion version           : 1.3
------------------------------------------------------------------------
Notebook 06 completion
Blocks 1–7 complete          : True
Blocks 1–7 valid             : True
Factual path complete        : True
Controlled factual pipeline  : True
Factual path reproducible    : True
Notebook 06 complete         : True
Full Media AI project complete: False
Full training coverage       : False
Generalisation validated     : False
------------------------------------------------------------------------
Inherited Notebook 05 → 06 contract
Handover present             : True
Block 1 complete             : True
Block 1 handover valid       : True
Inherited contract valid     : True
------------------------------------------------------------------------
Factual semantic contract
Factual representation dim.  : 10
Semantic contract valid      : True
Active dimensions            : ['explicit_claim', 'observation_or_event', 'quantitative_information', 'attribution', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction', 'factological_weight']
Deferred dimensions          : ['speculation']
Weighted binary dimensions   : ['explicit_claim', 'evidence_reference', 'certainty_statement', 'uncertainty_statement', 'prediction']
Positive class weights       : {'explicit_claim': 0.2558139534883721, 'evidence_reference': 3.1538461538461537, 'certainty_statement': 0.17391304347826086, 'uncertainty_statement': 8.0, 'prediction': 25.0}
Prediction positive weight   : 25.0
Objective weights            : {'explicit_claim': 0.1111111111111111, 'observation_or_event': 0.1111111111111111, 'quantitative_information': 0.1111111111111111, 'attribution': 0.1111111111111111, 'evidence_reference': 0.1111111111111111, 'certainty_statement': 0.1111111111111111, 'uncertainty_statement': 0.1111111111111111, 'prediction': 0.1111111111111111, 'factological_weight': 0.1111111111111111}
------------------------------------------------------------------------
Canonical training scope
Articles                     : 3
Sentences                    : 54
Epochs                       : 10
Optimiser                    : AdamW
Training scope valid         : True
------------------------------------------------------------------------
Factual trained-state handover
Checkpoint type              : controlled_experimental_factual_training_checkpoint
Checkpoint Drive file ID     : 1S5Wq68eGkMk2yxQ1BKCJ5PycFvAJjziY
Metadata Drive file ID       : 1jM2rdgpYkcJA_xIhSpmC4dNr2DcO7xli
Target contract Drive ID     : 1FdTrV_2RoHDRn06JLSx367OD4HffDaAy
Checkpoint reproducible      : True
Final factual objective      : 0.40325385
Validated model checkpoint   : False
------------------------------------------------------------------------
Module boundary
Backbone frozen              : True
Global confluent frozen      : True
Psychological head frozen    : True
Factual head trainable       : True
Factual parameter count      : 34442
All parameters unchanged     : True
------------------------------------------------------------------------
Remaining Version 1 roadmap
Notebook 07               : Social Path
Notebook 08               : Transformative Mechanism
Notebook 09               : Transformative Weights and Recurrent Mechanism
Notebook 10               : Group-Conditioned Path and Final Integration
------------------------------------------------------------------------
Group-conditioned path policy
Global path required         : True
Global path operational      : True
Group path available         : True
Group path required          : False
Group path executed          : False
Group path trained           : False
Group path deferred to N     : 10
------------------------------------------------------------------------
Persistent Notebook 06 → Notebook 07 handover
Handover version             : 1.3
Handover filename            : notebook_06_to_07_handover.json
Local copy created           : True
Drive operation              : updated
Drive file ID                : 1Qe_QwbJ3FK7B797zIQcOryWIy_qhcMSt
Read-back valid              : True
Notebook 07 ready            : True
------------------------------------------------------------------------
Notebook 07 starting contract
Designation                  : Social Path
Backbone frozen by default   : True
Global confluent frozen      : True
Psychological path frozen    : True
Factual path frozen          : True
------------------------------------------------------------------------
Execution boundary
Forward pass executed        : False
Loss calculated              : False
Zero grad executed           : False
Backward pass executed       : False
Optimiser created            : False
Optimiser step executed      : False
Parameter update executed    : False
Factual training executed    : False
Psychological retraining     : False
Social training executed     : False
Group-conditioned executed   : False
Transformative executed      : False
Transformative weights active: False
Recurrent executed           : False
Held-out evaluation executed : False
Empirical validity           : False
Block valid                  : True
Block 8 complete             : True
========================================================================
Notebook 06 factual-path scope audit, persistent handover and completion validation completed successfully.
The validated Notebook 05 → Notebook 06 handover was preserved without reinterpreting its internal schema; Notebook 06 Block 1 remains the authoritative handover-validation boundary.
The ten-dimensional factual representation remains intact, while 9 factual dimensions participate in the current validated controlled objective.
1 factual dimension(s) remain structurally present but deferred under the current validated supervision and objective policy.
The controlled factual checkpoint remains reproducible and explicitly classified as an experimental training checkpoint rather than a validated model checkpoint.
The backbone, mandatory global confluent path and completed psychological representation remain frozen.
The factual target contract, training metadata and reproducible checkpoint are referenced explicitly in the new Notebook 06 → Notebook 07 handover.
The optional group-conditioned path remains architecturally available but unexecuted and deferred to Notebook 10.
The social path, transformative mechanism, Transformative Weights and recurrent mechanism remain outside Notebook 06.
No forward pass, loss calculation, optimiser creation, zero-gradient operation, backward pass, optimiser step, parameter update or new training was performed by Block 8.
No held-out evaluation, generalisation claim or empirical-validity claim has been introduced.
The persisted Notebook 06 → Notebook 07 handover was read back and validated successfully.
Notebook 06 — Factual Path is complete within its controlled experimental scope.
The full Media AI Version 1 project remains incomplete.
Notebook 07 may now initialise independently from the persisted handover and begin the Social Path while keeping the completed psychological and factual paths frozen by default.
========================================================================

,dimension_id,target_name,structurally_present,currently_active,currently_deferred,objective_family,optimisation_state,checkpoint_state_reproducible,independently_evaluated,empirically_validated
0,F1,explicit_claim,True,True,False,binary_cross_entropy_with_logits,trained,True,False,False
1,F2,observation_or_event,True,True,False,binary_cross_entropy_with_logits,trained,True,False,False
2,F3,quantitative_information,True,True,False,binary_cross_entropy_with_logits,trained,True,False,False
3,F4,attribution,True,True,False,binary_cross_entropy_with_logits,trained,True,False,False
4,F5,evidence_reference,True,True,False,binary_cross_entropy_with_logits,trained,True,False,False
5,F6,certainty_statement,True,True,False,binary_cross_entropy_with_logits,trained,True,False,False
6,F7,uncertainty_statement,True,True,False,binary_cross_entropy_with_logits,trained,True,False,False
7,F8,speculation,True,False,True,none_current_sample,deferred_zero_variance,not_applicable,False,False
8,F9,prediction,True,True,False,binary_cross_entropy_with_logits,trained,True,False,False
9,F10,factological_weight,True,True,False,masked_mean_squared_error,trained,True,False,False

,functionality,architecture_stage,implemented_structurally,used_in_notebook_06,trained_in_notebook_06,checkpoint_or_state_reproducible,independently_evaluated,empirically_validated,notes
0,contextual_sentence_representation,textual_representation,True,True,False,True,False,False,Inherited contextual sentence representation c...
1,mandatory_global_confluent_path,confluent_conditioning,True,True,False,True,False,False,Mandatory global conditioning remained frozen ...
2,psychological_representation_head,representation_heads,True,False,False,True,False,False,Completed psychological path inherited from No...
3,factual_representation_head,representation_heads,True,True,True,True,False,False,Controlled factual training completed; checkpo...
4,social_representation_head,representation_heads,True,False,False,False,False,False,Reserved for Notebook 07.
5,transformative_mechanism,transformative_mechanism,True,False,False,False,False,False,Reserved for Notebook 08.
6,transformative_weights,transformative_mechanism,True,False,False,False,False,False,Reserved for Notebook 09.
7,recurrent_mechanism,recurrent_mechanism,True,False,False,False,False,False,Reserved for Notebook 09.
8,optional_group_conditioned_path,confluent_conditioning,True,False,False,False,False,False,Architecturally available but deliberately def...