<a href="https://colab.research.google.com/github/stilyank01-create/Media_AI/blob/main/07_social_representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Media AI — Notebook 07: Social Representation

## Purpose

This notebook develops the **Social Representation** component of the Media AI architecture.

It continues from the completed controlled factual pipeline established in Notebook 06 and introduces the third representation domain of the architecture:

- psychological representation,
- factual representation,
- social representation.

The purpose of Notebook 07 is to define, validate and, where justified by the available supervision, train the social representation while preserving the completed psychological and factual components.

Notebook 07 does not modify the semantic contracts established by the preceding notebooks.

---

## Terminology

The Notebook 06 → Notebook 07 handover uses the inherited designation **Social Path**.

Beginning with Notebook 07, the formal designation of this component is:

**Social Representation**

The change is terminological only.

It does not alter the architecture, dimensional contracts, persisted checkpoints or previous notebook artefacts.

Where compatibility with earlier persisted metadata is required, `social_path` may remain as an internal or legacy identifier.

---

## Architectural position

The Media AI representation architecture now distinguishes three complementary domains.

### Psychological representation

The psychological representation captures the psychological dimensions defined and trained in the preceding psychological-stage notebooks.

This representation is already completed within its controlled experimental scope and remains frozen by default in Notebook 07.

### Factual representation

The factual representation captures the ten-dimensional factual contract established in Notebook 06.

The representation preserves all ten factual dimensions:

- F1 — explicit claim,
- F2 — observation or event,
- F3 — quantitative information,
- F4 — attribution,
- F5 — evidence reference,
- F6 — certainty statement,
- F7 — uncertainty statement,
- F8 — speculation,
- F9 — prediction,
- F10 — factological weight.

Under the current available supervision, F2, F3, F5, F9 and F10 have undergone controlled factual training.

F1, F4, F6, F7 and F8 remain structurally present but were deferred because the available supervision provided zero target variance.

The factual representation remains frozen by default during development of the Social Representation.

### Social representation

The Social Representation is intended to capture socially relevant characteristics that cannot be reduced cleanly to either psychological or factual information.

Its exact semantic dimensions, supervision availability, activation policy and optimisation contract must be established explicitly in this notebook.

No social dimension is considered trainable merely because it exists architecturally.

Supervision availability, target variability and methodological validity must be demonstrated before optimisation.

---

## Representation orientation

The canonical prediction unit remains the **sentence**.

A sentence may be interpreted using permitted preceding context when that context is required to resolve its meaning.

This creates a context-assisted sentence representation rather than an article-level target.

Future article context must not be used to construct or predict the current sentence representation.

Article-level structure may later support aggregation, grouping or integration, but it does not replace the canonical sentence-level supervision contract.

---

## Inherited model boundary

Notebook 07 inherits the validated state established by Notebook 06.

By default:

- the textual/contextual representation is preserved,
- the backbone remains frozen,
- the mandatory global confluent representation remains frozen,
- the psychological representation remains frozen,
- the factual representation remains frozen,
- the Social Representation is the only representation domain eligible for new activation or training in this notebook.

Any departure from this freezing policy must be introduced explicitly and validated before execution.

Notebook 07 must not silently retrain previously completed representation components.

---

## Confluent processing

The mandatory global confluent path remains part of the operational forward architecture inherited from the preceding notebooks.

It may therefore be used to produce the representation consumed by the Social Representation head while remaining frozen.

The optional group-conditioned confluent path remains architecturally available but is not activated in Notebook 07.

Group-conditioned processing remains deferred to Notebook 10, where sufficient group structure and integration context can be evaluated explicitly.

---

## Transformative and recurrent boundary

Notebook 07 does not activate:

- the Transformative Mechanism,
- Transformative Weights,
- recurrent states,
- the optional group-conditioned path.

These mechanisms remain structurally reserved for later notebooks.

Their absence from Notebook 07 is deliberate and prevents the Social Representation experiment from being confounded with later architectural mechanisms.

The current Version 1 roadmap therefore remains:

- **Notebook 07 — Social Representation**
- **Notebook 08 — Transformative Mechanism**
- **Notebook 09 — Transformative Weights and Recurrent Mechanism**
- **Notebook 10 — Group-Conditioned Path and Final Integration**

---

## Supervision principle

Social supervision must be derived from explicitly identified canonical sources.

Notebook 07 must distinguish between:

- available supervision,
- unavailable supervision,
- numerical zero,
- negative evidence,
- structurally defined but currently unsupervised dimensions.

Missing supervision must not be converted automatically into zero or negative evidence.

Where supervision is only partially available, independent masks should preserve the distinction between observed and unavailable targets.

No social target should be fabricated solely to fill an architectural dimension.

---

## Optimisation principle

The existence of a Social Representation dimension does not automatically make that dimension suitable for optimisation.

Before training, Notebook 07 must establish:

1. the semantic meaning of each social dimension,
2. its canonical supervision source,
3. target availability,
4. target variability,
5. appropriate activation semantics,
6. an appropriate loss family,
7. masking behaviour,
8. class-imbalance treatment where applicable,
9. the exact trainable parameter scope.

Zero-variance or inadequately supervised dimensions may remain structurally present while being deferred from the controlled objective.

This follows the same methodological distinction established in Notebook 06 between **architectural presence** and **optimisation eligibility**.

---

## Training and validation boundary

Any training performed in Notebook 07 is controlled experimental training.

A reduction in training loss does not establish:

- generalisation,
- predictive validity,
- social validity,
- robustness,
- held-out performance,
- empirical validity of the complete Media AI architecture.

Independent validation requires suitable held-out data and must be reported separately from optimisation behaviour.

Any resulting checkpoint must therefore remain explicitly classified according to the evidence actually available.

---

## Reproducibility

Notebook 07 begins from the persisted:

`notebook_06_to_07_handover.json`

The handover is the authoritative transition artefact from the completed factual notebook.

Notebook 07 should independently restore and validate the required inherited architecture and model state rather than depending on an active Notebook 06 runtime.

All new Social Representation contracts, objective policies, checkpoints and metadata should be persisted separately and validated by read-back where appropriate.

Notebook 07 should ultimately produce a persistent handover for Notebook 08:

`notebook_07_to_08_handover.json`

---

## Methodological safeguards

Throughout Notebook 07:

- previous notebook artefacts remain immutable,
- inherited semantic contracts are not silently reinterpreted,
- psychological parameters remain frozen by default,
- factual parameters remain frozen by default,
- the backbone remains frozen by default,
- the mandatory global confluent module remains frozen,
- unavailable supervision does not enter the loss,
- no social dimension is fabricated to satisfy an architectural shape,
- training behaviour is not presented as empirical validation,
- transformative mechanisms remain inactive,
- Transformative Weights remain inactive,
- recurrent mechanisms remain inactive,
- group-conditioned processing remains inactive.

Each transition from architectural definition to supervision, objective construction and optimisation must be validated explicitly.

---

## Notebook objective

Notebook 07 is complete when the Social Representation has a reproducible and auditable contract covering:

- architecture,
- semantics,
- supervision,
- masking,
- activation,
- objective policy,
- parameter scope,
- controlled training where justified,
- checkpoint classification,
- reproducibility,
- downstream handover.

Completion of Notebook 07 establishes the **Social Representation within its demonstrated experimental scope**.

It does not establish completion or empirical validity of the full Media AI Version 1 architecture.

## Block 1 — Notebook 06 → 07 Handover Restoration, Social Representation Scope and Initialisation Audit

This block initialises Notebook 07 from the persistent Notebook 06 → Notebook 07 handover and establishes the starting methodological boundary for the Social Representation.

The block does not define or train any Social Representation dimensions.

Its purpose is to restore the completed upstream state, validate the inherited contracts, formalise the terminology transition from the legacy designation `Social Path` to **Social Representation**, and confirm that Notebook 07 is ready to proceed to supervision discovery without modifying previously completed components.

### Persistent handover restoration

Notebook 07 begins from the persisted handover:

`notebook_06_to_07_handover.json`

The handover is treated as the authoritative transition artefact from the completed factual notebook.

The block:

- authenticates to Google Drive,
- locates the persisted handover by its verified Drive file identifier,
- downloads the handover,
- creates a local audit copy,
- parses the JSON contract,
- validates its source and target notebook identities.

Notebook 07 therefore does not depend on an active Notebook 06 runtime.

### Terminology transition

The inherited handover uses the designation:

`Social Path`

Notebook 07 formally adopts:

**Social Representation**

This is a terminology-only transition.

It introduces:

- no semantic change,
- no architectural change,
- no modification of preceding notebook artefacts.

The legacy designation may remain present inside inherited metadata for compatibility.

### Inherited project state

The block verifies that Notebook 06 completed successfully within its controlled experimental scope.

The inherited state must confirm:

- Notebook 06 complete,
- factual path complete,
- factual path reproducible,
- controlled factual pipeline complete,
- full Media AI project incomplete,
- generalisation not validated,
- empirical validity not established.

Notebook 07 must not reinterpret successful factual checkpoint reproduction as evidence of held-out factual performance.

### Canonical identity

The canonical identity contract remains unchanged.

The current controlled sample contains:

- one article,
- sixteen sentences.

Sentence identifiers must remain:

- present,
- unique,
- aligned with the persisted handover.

The sentence remains the canonical unit for downstream Social Representation supervision.

### Inherited representation state

The completed upstream representation state is preserved.

By default:

- contextual representation remains frozen,
- backbone remains frozen,
- mandatory global confluent representation remains frozen,
- psychological representation remains frozen,
- factual representation remains frozen.

The factual representation retains its ten-dimensional contract and controlled experimental checkpoint.

Notebook 07 does not retrain or redefine the factual representation.

### Social Representation starting contract

Block 1 deliberately does not assign Social Representation dimensions.

At this stage:

- social representation dimensionality is unresolved,
- social semantic dimensions are unresolved,
- social supervision mapping is unresolved,
- social target contract is undefined,
- social activation policy is undefined,
- social loss contract is undefined,
- social optimisation remains blocked.

No architectural dimension may be invented merely to complete a target shape.

The Social Representation must instead be derived from explicitly available canonical supervision.

### Representation orientation

The Social Representation remains sentence-oriented.

The canonical prediction unit is the current sentence.

Preceding context may be used when required to interpret socially relevant meaning.

Future context is prohibited.

The resulting contract therefore remains:

**context-assisted sentence representation**

rather than article-level supervision.

### Social supervision policy

The block establishes the supervision principles that later blocks must preserve.

Social supervision must remain:

- mask-aware,
- compatible with partial supervision,
- distinct from numerical zero,
- distinct from negative evidence,
- excluded from the loss when unavailable.

Missing supervision must not be converted automatically into zero.

Missing supervision must not be converted automatically into negative evidence.

Fabricated Social Representation dimensions are not allowed.

### Architectural boundary

The mandatory global confluent path remains operational and required.

The optional group-conditioned path remains:

- architecturally available,
- not required,
- not executed,
- not trained,
- deferred to Notebook 10.

The Social Representation therefore begins from the same stable global conditioning path used by the preceding representation stages.

### Transformative and recurrent boundary

Notebook 07 does not activate:

- the Transformative Mechanism,
- Transformative Weights,
- recurrent states,
- group-conditioned processing.

These remain reserved for later notebooks:

- Notebook 08 — Transformative Mechanism,
- Notebook 09 — Transformative Weights and Recurrent Mechanism,
- Notebook 10 — Group-Conditioned Path and Final Integration.

This separation prevents Social Representation development from being confounded by later architectural mechanisms.

### Methodological boundary

Block 1 performs no:

- social target mapping,
- social objective activation,
- social optimiser creation,
- social forward pass,
- social loss calculation,
- backward pass,
- parameter update,
- social training,
- psychological retraining,
- factual retraining,
- group-conditioned processing,
- transformative processing,
- recurrent processing,
- held-out evaluation.

Successful completion of Block 1 establishes only that Notebook 07 has been initialised correctly and is ready to inspect canonical social supervision.

It does not establish any Social Representation semantics, trainability, predictive quality or empirical validity.

### Block 1 completion criterion

Block 1 is complete when:

- the Notebook 06 → 07 handover is restored and validated,
- canonical sentence identity is preserved,
- inherited psychological and factual representations remain frozen,
- the terminology transition to Social Representation is documented,
- the social supervision boundary is established,
- downstream mechanisms remain inactive,
- social optimisation remains blocked pending supervision discovery.

The next block may proceed to:

**Social Supervision Discovery, Semantic Dimension Mapping and Target-Contract Audit.**

In [2]:
# =============================================================================
# Media AI — Notebook 07
# Block 1: Notebook 06 → 07 Handover Restoration,
#          Social Representation Scope and Initialisation Audit
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json

import numpy as np
import pandas as pd
import torch

from google.colab import auth
import google.auth

from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_07 = "07_social_representation"

NOTEBOOK_07_VERSION = "1.0"

NOTEBOOK_07_BLOCK_1 = 1

NOTEBOOK_07_BLOCK_1_NAME = (
    "Notebook 06 → 07 Handover Restoration, "
    "Social Representation Scope and Initialisation Audit"
)

NOTEBOOK_07_BLOCK_1_VERSION = "1.1"

BLOCK_1_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Project constants
# =============================================================================

NOTEBOOK_07_RANDOM_SEED = 42


np.random.seed(
    NOTEBOOK_07_RANDOM_SEED
)


torch.manual_seed(
    NOTEBOOK_07_RANDOM_SEED
)


if torch.cuda.is_available():

    torch.cuda.manual_seed_all(
        NOTEBOOK_07_RANDOM_SEED
    )


# =============================================================================
# Persistent handover contract
# =============================================================================

NOTEBOOK_06_TO_07_HANDOVER_FILENAME = (
    "notebook_06_to_07_handover.json"
)


NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID = (
    "1Qe_QwbJ3FK7B797zIQcOryWIy_qhcMSt"
)


# =============================================================================
# Execution boundary
# =============================================================================

NOTEBOOK_07_SOCIAL_MAPPING_PERFORMED = False

NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED = False

NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED = False

NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_LOSS_CALCULATED = False

NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED = False

NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED = False

NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED = False

NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Google authentication
# =============================================================================

auth.authenticate_user()


BLOCK_1_CREDENTIALS, _ = (
    google.auth.default()
)


NOTEBOOK_07_DRIVE_SERVICE = build(
    "drive",
    "v3",
    credentials=
        BLOCK_1_CREDENTIALS,
    cache_discovery=
        False,
)


BLOCK_1_COLAB_AUTHENTICATED = True

BLOCK_1_DRIVE_SERVICE_INITIALISED = (
    NOTEBOOK_07_DRIVE_SERVICE
    is not None
)


if not BLOCK_1_DRIVE_SERVICE_INITIALISED:

    raise RuntimeError(
        "Notebook 07 could not initialise the Google Drive service."
    )


# =============================================================================
# Drive download helper
# =============================================================================

def block_1_download_drive_bytes(
    drive_service,
    file_id,
):
    """
    Download one Google Drive file and return raw bytes.
    """

    request = (
        drive_service.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Retrieve handover metadata
# =============================================================================

BLOCK_1_HANDOVER_DRIVE_METADATA = (
    NOTEBOOK_07_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID,
        fields=
            "id,name,modifiedTime,parents,size,mimeType",
    )
    .execute()
)


BLOCK_1_HANDOVER_LOCATED = (
    BLOCK_1_HANDOVER_DRIVE_METADATA.get(
        "id"
    )
    ==
    NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID
)


BLOCK_1_HANDOVER_FILENAME_VALID = (
    BLOCK_1_HANDOVER_DRIVE_METADATA.get(
        "name"
    )
    ==
    NOTEBOOK_06_TO_07_HANDOVER_FILENAME
)


if not BLOCK_1_HANDOVER_LOCATED:

    raise FileNotFoundError(
        "Notebook 06 → 07 handover could not be located."
    )


if not BLOCK_1_HANDOVER_FILENAME_VALID:

    raise RuntimeError(
        "Notebook 06 → 07 handover file name does not match "
        "the expected persistent contract."
    )


# =============================================================================
# Download persisted handover
# =============================================================================

BLOCK_1_HANDOVER_BYTES = (
    block_1_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID,
    )
)


if not BLOCK_1_HANDOVER_BYTES:

    raise RuntimeError(
        "Notebook 06 → 07 handover was empty."
    )


BLOCK_1_HANDOVER_DOWNLOADED = True


# =============================================================================
# Local audit copy
# =============================================================================

with open(
    NOTEBOOK_06_TO_07_HANDOVER_FILENAME,
    "wb",
) as handover_local_file:

    handover_local_file.write(
        BLOCK_1_HANDOVER_BYTES
    )


BLOCK_1_LOCAL_AUDIT_COPY_CREATED = True


# =============================================================================
# Parse handover JSON
# =============================================================================

NOTEBOOK_07_HANDOVER = json.loads(
    BLOCK_1_HANDOVER_BYTES.decode(
        "utf-8"
    )
)


BLOCK_1_HANDOVER_JSON_PARSED = isinstance(
    NOTEBOOK_07_HANDOVER,
    dict,
)


if not BLOCK_1_HANDOVER_JSON_PARSED:

    raise TypeError(
        "Notebook 06 → 07 handover must be a JSON object."
    )


# =============================================================================
# Handover top-level contract
# =============================================================================

BLOCK_1_HANDOVER_TYPE_VALID = (
    NOTEBOOK_07_HANDOVER.get(
        "handover_type"
    )
    ==
    "media_ai_notebook_06_to_07_handover"
)


BLOCK_1_HANDOVER_VERSION = (
    NOTEBOOK_07_HANDOVER.get(
        "handover_version"
    )
)


BLOCK_1_HANDOVER_SOURCE_VALID = (
    NOTEBOOK_07_HANDOVER.get(
        "source_notebook"
    )
    ==
    "06_factual_path"
)


BLOCK_1_HANDOVER_TARGET_VALID = (
    NOTEBOOK_07_HANDOVER.get(
        "target_notebook"
    )
    ==
    "07_social_path"
)


BLOCK_1_HANDOVER_TOP_LEVEL_VALID = all(
    [
        BLOCK_1_HANDOVER_TYPE_VALID,
        bool(
            BLOCK_1_HANDOVER_VERSION
        ),
        BLOCK_1_HANDOVER_SOURCE_VALID,
        BLOCK_1_HANDOVER_TARGET_VALID,
    ]
)


if not BLOCK_1_HANDOVER_TOP_LEVEL_VALID:

    raise RuntimeError(
        "Notebook 06 → 07 top-level handover contract is invalid."
    )


# =============================================================================
# Project completion-state audit
# =============================================================================

BLOCK_1_PROJECT_STATE = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "project_state",
        {},
    )
)


BLOCK_1_NOTEBOOK_06_COMPLETE = (
    BLOCK_1_PROJECT_STATE.get(
        "notebook_06_complete"
    )
    is True
)


BLOCK_1_FACTUAL_PATH_COMPLETE = (
    BLOCK_1_PROJECT_STATE.get(
        "factual_path_complete"
    )
    is True
)


BLOCK_1_FACTUAL_PATH_REPRODUCIBLE = (
    BLOCK_1_PROJECT_STATE.get(
        "factual_path_reproducible"
    )
    is True
)


BLOCK_1_CONTROLLED_FACTUAL_PIPELINE_COMPLETE = (
    BLOCK_1_PROJECT_STATE.get(
        "controlled_factual_pipeline_complete"
    )
    is True
)


BLOCK_1_FULL_PROJECT_COMPLETE = (
    BLOCK_1_PROJECT_STATE.get(
        "full_media_ai_project_complete"
    )
    is True
)


BLOCK_1_GENERALISATION_VALIDATED = (
    BLOCK_1_PROJECT_STATE.get(
        "generalisation_validated"
    )
    is True
)


BLOCK_1_EMPIRICAL_VALIDITY = (
    BLOCK_1_PROJECT_STATE.get(
        "empirical_validity"
    )
    is True
)


BLOCK_1_PROJECT_STATE_VALID = all(
    [
        BLOCK_1_NOTEBOOK_06_COMPLETE,
        BLOCK_1_FACTUAL_PATH_COMPLETE,
        BLOCK_1_FACTUAL_PATH_REPRODUCIBLE,
        BLOCK_1_CONTROLLED_FACTUAL_PIPELINE_COMPLETE,
        not BLOCK_1_FULL_PROJECT_COMPLETE,
        not BLOCK_1_GENERALISATION_VALIDATED,
        not BLOCK_1_EMPIRICAL_VALIDITY,
    ]
)


if not BLOCK_1_PROJECT_STATE_VALID:

    raise RuntimeError(
        "Notebook 06 completion state is invalid for Notebook 07."
    )


# =============================================================================
# Canonical identity contract
# =============================================================================
#
# Corpus size is inherited from the Notebook 06 → 07 handover.
# No pilot-specific article or sentence count is hard-coded.
# =============================================================================

BLOCK_1_CANONICAL_IDENTITY = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "canonical_identity",
        {},
    )
)


NOTEBOOK_07_ARTICLE_COUNT = int(
    BLOCK_1_CANONICAL_IDENTITY.get(
        "articles"
    )
)


NOTEBOOK_07_SENTENCE_COUNT = int(
    BLOCK_1_CANONICAL_IDENTITY.get(
        "sentences"
    )
)


NOTEBOOK_07_SENTENCE_IDS = list(
    BLOCK_1_CANONICAL_IDENTITY.get(
        "sentence_ids",
        [],
    )
)


def block_1_article_id_from_sentence_id(
    sentence_id,
):

    if not isinstance(
        sentence_id,
        str,
    ) or not sentence_id:

        raise ValueError(
            "Notebook 07 sentence IDs must be non-empty strings."
        )


    if "::" in sentence_id:

        return sentence_id.split(
            "::",
            1,
        )[0]


    return sentence_id


BLOCK_1_SENTENCE_IDS_PRESENT = all(
    isinstance(
        sentence_id,
        str,
    )
    and
    bool(
        sentence_id
    )

    for sentence_id
    in NOTEBOOK_07_SENTENCE_IDS
)


BLOCK_1_SENTENCE_IDS_UNIQUE = (
    len(
        NOTEBOOK_07_SENTENCE_IDS
    )
    ==
    len(
        set(
            NOTEBOOK_07_SENTENCE_IDS
        )
    )
)


BLOCK_1_SENTENCE_COUNT_ALIGNED = (
    len(
        NOTEBOOK_07_SENTENCE_IDS
    )
    ==
    NOTEBOOK_07_SENTENCE_COUNT
)


BLOCK_1_DERIVED_ARTICLE_IDS = tuple(
    dict.fromkeys(
        block_1_article_id_from_sentence_id(
            sentence_id
        )

        for sentence_id
        in NOTEBOOK_07_SENTENCE_IDS
    )
)


BLOCK_1_DERIVED_ARTICLE_COUNT = len(
    BLOCK_1_DERIVED_ARTICLE_IDS
)


BLOCK_1_ARTICLE_COUNT_ALIGNED = (
    BLOCK_1_DERIVED_ARTICLE_COUNT
    ==
    NOTEBOOK_07_ARTICLE_COUNT
)


BLOCK_1_IDENTITY_CONTRACT_VALID = all(
    [
        NOTEBOOK_07_ARTICLE_COUNT > 0,
        NOTEBOOK_07_SENTENCE_COUNT > 0,
        BLOCK_1_SENTENCE_IDS_PRESENT,
        BLOCK_1_SENTENCE_IDS_UNIQUE,
        BLOCK_1_SENTENCE_COUNT_ALIGNED,
        BLOCK_1_ARTICLE_COUNT_ALIGNED,

        (
            BLOCK_1_CANONICAL_IDENTITY.get(
                "identity_contract_valid"
            )
            is True
        ),
    ]
)


if not BLOCK_1_IDENTITY_CONTRACT_VALID:

    raise RuntimeError(
        "Notebook 07 canonical sentence identity contract is invalid."
    )


# =============================================================================
# Inherited Notebook 05 → 06 contract
# =============================================================================

NOTEBOOK_07_INHERITED_NOTEBOOK_05_TO_06_HANDOVER = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "inherited_notebook_05_to_06_handover",
        {},
    )
)


BLOCK_1_INHERITED_HANDOVER_PRESENT = (
    isinstance(
        NOTEBOOK_07_INHERITED_NOTEBOOK_05_TO_06_HANDOVER,
        dict,
    )
    and
    len(
        NOTEBOOK_07_INHERITED_NOTEBOOK_05_TO_06_HANDOVER
    )
    > 0
)


BLOCK_1_INHERITED_REFERENCE = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "inherited_handover_reference",
        {},
    )
)


BLOCK_1_INHERITED_VALIDATED_BY_N06_BLOCK_1 = (
    BLOCK_1_INHERITED_REFERENCE.get(
        "validated_by_notebook_06_block_1"
    )
    is True
)


NOTEBOOK_07_NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID = (
    BLOCK_1_INHERITED_REFERENCE.get(
        "drive_file_id"
    )
)


BLOCK_1_INHERITED_CONTRACT_VALID = all(
    [
        BLOCK_1_INHERITED_HANDOVER_PRESENT,
        BLOCK_1_INHERITED_VALIDATED_BY_N06_BLOCK_1,
        bool(
            NOTEBOOK_07_NOTEBOOK_05_TO_06_HANDOVER_DRIVE_FILE_ID
        ),
    ]
)


if not BLOCK_1_INHERITED_CONTRACT_VALID:

    raise RuntimeError(
        "Inherited Notebook 05 → 06 contract is invalid."
    )


# =============================================================================
# Factual representation contract
# =============================================================================

BLOCK_1_FACTUAL_PATH = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "factual_path",
        {},
    )
)


NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM = int(
    BLOCK_1_FACTUAL_PATH.get(
        "representation_dimension"
    )
)


NOTEBOOK_07_FACTUAL_DIMENSION_IDS = tuple(
    BLOCK_1_FACTUAL_PATH.get(
        "dimension_ids",
        [],
    )
)


NOTEBOOK_07_FACTUAL_DIMENSION_ORDER = tuple(
    BLOCK_1_FACTUAL_PATH.get(
        "dimension_order",
        [],
    )
)


NOTEBOOK_07_FACTUAL_ACTIVE_DIMENSIONS = tuple(
    BLOCK_1_FACTUAL_PATH.get(
        "active_dimensions",
        [],
    )
)


NOTEBOOK_07_FACTUAL_DEFERRED_DIMENSIONS = tuple(
    BLOCK_1_FACTUAL_PATH.get(
        "deferred_dimensions",
        [],
    )
)


NOTEBOOK_07_FACTUAL_ACTIVE_BINARY_DIMENSIONS = tuple(
    BLOCK_1_FACTUAL_PATH.get(
        "active_binary_dimensions",
        [],
    )
)


NOTEBOOK_07_FACTUAL_ACTIVE_CONTINUOUS_DIMENSIONS = tuple(
    BLOCK_1_FACTUAL_PATH.get(
        "active_continuous_dimensions",
        [],
    )
)


NOTEBOOK_07_FACTUAL_POSITIVE_CLASS_WEIGHTS = deepcopy(
    BLOCK_1_FACTUAL_PATH.get(
        "positive_class_weights",
        {},
    )
)


NOTEBOOK_07_FACTUAL_WEIGHTED_BINARY_DIMENSIONS = tuple(
    BLOCK_1_FACTUAL_PATH.get(
        "weighted_binary_dimensions",
        [],
    )
)


BLOCK_1_PREDICTION_POSITIVE_WEIGHT_RAW = (
    BLOCK_1_FACTUAL_PATH.get(
        "prediction_positive_weight"
    )
)


NOTEBOOK_07_FACTUAL_PREDICTION_POSITIVE_WEIGHT = (
    float(
        BLOCK_1_PREDICTION_POSITIVE_WEIGHT_RAW
    )
    if BLOCK_1_PREDICTION_POSITIVE_WEIGHT_RAW is not None
    else None
)


NOTEBOOK_07_FACTUAL_OBJECTIVE_WEIGHTS = deepcopy(
    BLOCK_1_FACTUAL_PATH.get(
        "objective_weights",
        {},
    )
)


BLOCK_1_FACTUAL_REPRESENTATION_VALID = all(
    [
        NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM
        == 10,

        len(
            NOTEBOOK_07_FACTUAL_DIMENSION_IDS
        )
        == 10,

        len(
            NOTEBOOK_07_FACTUAL_DIMENSION_ORDER
        )
        == 10,

        (
            BLOCK_1_FACTUAL_PATH.get(
                "mapping_resolved"
            )
            is True
        ),

        (
            BLOCK_1_FACTUAL_PATH.get(
                "target_contract_valid"
            )
            is True
        ),

        (
            BLOCK_1_FACTUAL_PATH.get(
                "objective_policy_valid"
            )
            is True
        ),

        (
            BLOCK_1_FACTUAL_PATH.get(
                "model_policy_valid"
            )
            is True
        ),

        (
            BLOCK_1_FACTUAL_PATH.get(
                "optimizer_policy_valid"
            )
            is True
        ),

        (
            BLOCK_1_FACTUAL_PATH.get(
                "checkpoint_reproducible"
            )
            is True
        ),
    ]
)


if not BLOCK_1_FACTUAL_REPRESENTATION_VALID:

    raise RuntimeError(
        "Inherited factual representation contract is invalid."
    )


# =============================================================================
# Persisted factual artefact references
# =============================================================================

BLOCK_1_FACTUAL_ARTEFACTS = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "factual_persisted_artefacts",
        {},
    )
)


NOTEBOOK_07_FACTUAL_TARGET_CONTRACT_DRIVE_FILE_ID = (
    BLOCK_1_FACTUAL_ARTEFACTS[
        "target_contract"
    ][
        "drive_file_id"
    ]
)


NOTEBOOK_07_FACTUAL_CHECKPOINT_DRIVE_FILE_ID = (
    BLOCK_1_FACTUAL_ARTEFACTS[
        "training_checkpoint"
    ][
        "drive_file_id"
    ]
)


NOTEBOOK_07_FACTUAL_METADATA_DRIVE_FILE_ID = (
    BLOCK_1_FACTUAL_ARTEFACTS[
        "training_metadata"
    ][
        "drive_file_id"
    ]
)


NOTEBOOK_07_FACTUAL_CHECKPOINT_TYPE = (
    BLOCK_1_FACTUAL_ARTEFACTS[
        "training_checkpoint"
    ][
        "checkpoint_type"
    ]
)


BLOCK_1_FACTUAL_ARTEFACT_REFERENCES_VALID = all(
    [
        bool(
            NOTEBOOK_07_FACTUAL_TARGET_CONTRACT_DRIVE_FILE_ID
        ),

        bool(
            NOTEBOOK_07_FACTUAL_CHECKPOINT_DRIVE_FILE_ID
        ),

        bool(
            NOTEBOOK_07_FACTUAL_METADATA_DRIVE_FILE_ID
        ),

        (
            NOTEBOOK_07_FACTUAL_CHECKPOINT_TYPE
            ==
            "controlled_experimental_factual_training_checkpoint"
        ),

        (
            BLOCK_1_FACTUAL_ARTEFACTS[
                "training_checkpoint"
            ][
                "validated_model_checkpoint"
            ]
            is False
        ),

        (
            BLOCK_1_FACTUAL_ARTEFACTS[
                "training_checkpoint"
            ][
                "reproducible"
            ]
            is True
        ),
    ]
)


if not BLOCK_1_FACTUAL_ARTEFACT_REFERENCES_VALID:

    raise RuntimeError(
        "Inherited factual persisted-artefact references are invalid."
    )


# =============================================================================
# Factual training-state contract
# =============================================================================
#
# Training scope and optimiser settings are inherited from the persisted
# Notebook 06 handover rather than redefined as pilot constants.
# =============================================================================

BLOCK_1_FACTUAL_TRAINING_STATE = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "factual_training_state",
        {},
    )
)


NOTEBOOK_07_FACTUAL_FINAL_OBJECTIVE = float(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "final_total_objective"
    )
)


NOTEBOOK_07_FACTUAL_FINAL_FAMILY_LOSSES = deepcopy(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "final_family_losses",
        {},
    )
)


BLOCK_1_FACTUAL_TRAINING_ARTICLES = int(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "training_articles"
    )
)


BLOCK_1_FACTUAL_TRAINING_SENTENCES = int(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "training_sentences"
    )
)


BLOCK_1_FACTUAL_TRAINING_ARTICLE_IDS = tuple(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "training_article_ids",
        [],
    )
)


BLOCK_1_FACTUAL_VALIDATION_SENTENCES = int(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "validation_sentences",
        0,
    )
)


BLOCK_1_FACTUAL_TEST_SENTENCES = int(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "test_sentences",
        0,
    )
)


BLOCK_1_FACTUAL_TRAINING_EPOCHS = int(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "epochs"
    )
)


BLOCK_1_FACTUAL_OPTIMIZER = str(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "optimizer"
    )
)


BLOCK_1_FACTUAL_LEARNING_RATE = float(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "learning_rate"
    )
)


BLOCK_1_FACTUAL_WEIGHT_DECAY = float(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "weight_decay"
    )
)


BLOCK_1_FACTUAL_MAXIMUM_GRADIENT_NORM = float(
    BLOCK_1_FACTUAL_TRAINING_STATE.get(
        "maximum_gradient_norm"
    )
)


BLOCK_1_FACTUAL_TRAINING_SCOPE_ALIGNED = all(
    [
        BLOCK_1_FACTUAL_TRAINING_ARTICLES
        ==
        NOTEBOOK_07_ARTICLE_COUNT,

        BLOCK_1_FACTUAL_TRAINING_SENTENCES
        ==
        NOTEBOOK_07_SENTENCE_COUNT,

        (
            not BLOCK_1_FACTUAL_TRAINING_ARTICLE_IDS
            or
            BLOCK_1_FACTUAL_TRAINING_ARTICLE_IDS
            ==
            BLOCK_1_DERIVED_ARTICLE_IDS
        ),
    ]
)


BLOCK_1_FACTUAL_TRAINING_POLICY_VALID = all(
    [
        BLOCK_1_FACTUAL_TRAINING_EPOCHS > 0,
        bool(
            BLOCK_1_FACTUAL_OPTIMIZER
        ),
        np.isfinite(
            BLOCK_1_FACTUAL_LEARNING_RATE
        ),
        BLOCK_1_FACTUAL_LEARNING_RATE > 0.0,
        np.isfinite(
            BLOCK_1_FACTUAL_WEIGHT_DECAY
        ),
        BLOCK_1_FACTUAL_WEIGHT_DECAY >= 0.0,
        np.isfinite(
            BLOCK_1_FACTUAL_MAXIMUM_GRADIENT_NORM
        ),
        BLOCK_1_FACTUAL_MAXIMUM_GRADIENT_NORM > 0.0,
    ]
)


BLOCK_1_FACTUAL_TRAINING_STATE_VALID = all(
    [
        np.isfinite(
            NOTEBOOK_07_FACTUAL_FINAL_OBJECTIVE
        ),

        set(
            NOTEBOOK_07_FACTUAL_FINAL_FAMILY_LOSSES.keys()
        )
        ==
        set(
            NOTEBOOK_07_FACTUAL_ACTIVE_DIMENSIONS
        ),

        all(
            np.isfinite(
                float(
                    NOTEBOOK_07_FACTUAL_FINAL_FAMILY_LOSSES[
                        dimension_name
                    ]
                )
            )

            for dimension_name
            in NOTEBOOK_07_FACTUAL_ACTIVE_DIMENSIONS
        ),

        BLOCK_1_FACTUAL_TRAINING_SCOPE_ALIGNED,
        BLOCK_1_FACTUAL_VALIDATION_SENTENCES >= 0,
        BLOCK_1_FACTUAL_TEST_SENTENCES >= 0,
        BLOCK_1_FACTUAL_TRAINING_POLICY_VALID,
    ]
)


if not BLOCK_1_FACTUAL_TRAINING_STATE_VALID:

    raise RuntimeError(
        "Inherited factual training-state contract is invalid."
    )


# =============================================================================
# Notebook 07 inherited freezing contract
# =============================================================================

BLOCK_1_NOTEBOOK_07_STARTING_STATE = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "notebook_07_starting_state",
        {},
    )
)


BLOCK_1_LEGACY_DESIGNATION = (
    BLOCK_1_NOTEBOOK_07_STARTING_STATE.get(
        "notebook_designation"
    )
)


NOTEBOOK_07_FORMAL_DESIGNATION = (
    "Social Representation"
)


NOTEBOOK_07_LEGACY_DESIGNATION = (
    BLOCK_1_LEGACY_DESIGNATION
)


NOTEBOOK_07_BACKBONE_FROZEN_BY_DEFAULT = (
    BLOCK_1_NOTEBOOK_07_STARTING_STATE.get(
        "backbone_state"
    )
    ==
    "frozen"
)


NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_BY_DEFAULT = (
    BLOCK_1_NOTEBOOK_07_STARTING_STATE.get(
        "global_confluent_state"
    )
    ==
    "frozen"
)


NOTEBOOK_07_PSYCHOLOGICAL_PATH_FROZEN_BY_DEFAULT = (
    BLOCK_1_NOTEBOOK_07_STARTING_STATE.get(
        "psychological_path_state"
    )
    ==
    "frozen"
)


NOTEBOOK_07_FACTUAL_PATH_FROZEN_BY_DEFAULT = (
    BLOCK_1_NOTEBOOK_07_STARTING_STATE.get(
        "factual_path_state"
    )
    ==
    "frozen_by_default"
)


NOTEBOOK_07_SOCIAL_REPRESENTATION_TRAINED = False


BLOCK_1_STARTING_FREEZE_POLICY_VALID = all(
    [
        NOTEBOOK_07_BACKBONE_FROZEN_BY_DEFAULT,
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_BY_DEFAULT,
        NOTEBOOK_07_PSYCHOLOGICAL_PATH_FROZEN_BY_DEFAULT,
        NOTEBOOK_07_FACTUAL_PATH_FROZEN_BY_DEFAULT,

        (
            BLOCK_1_NOTEBOOK_07_STARTING_STATE.get(
                "social_path_state"
            )
            ==
            "not_yet_trained"
        ),

        (
            BLOCK_1_NOTEBOOK_07_STARTING_STATE.get(
                "joint_retraining_allowed_implicitly"
            )
            is False
        ),

        (
            BLOCK_1_NOTEBOOK_07_STARTING_STATE.get(
                "ready_to_initialise"
            )
            is True
        ),
    ]
)


if not BLOCK_1_STARTING_FREEZE_POLICY_VALID:

    raise RuntimeError(
        "Notebook 07 inherited freezing policy is invalid."
    )


# =============================================================================
# Architectural boundary
# =============================================================================

BLOCK_1_ARCHITECTURAL_BOUNDARY = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "architectural_boundary",
        {},
    )
)


NOTEBOOK_07_GLOBAL_PATH_REQUIRED = (
    BLOCK_1_ARCHITECTURAL_BOUNDARY.get(
        "mandatory_global_path_required"
    )
    is True
)


NOTEBOOK_07_GLOBAL_PATH_OPERATIONAL = (
    BLOCK_1_ARCHITECTURAL_BOUNDARY.get(
        "mandatory_global_path_operational"
    )
    is True
)


NOTEBOOK_07_GROUP_PATH_AVAILABLE = (
    BLOCK_1_ARCHITECTURAL_BOUNDARY.get(
        "group_path_available"
    )
    is True
)


NOTEBOOK_07_GROUP_PATH_REQUIRED = (
    BLOCK_1_ARCHITECTURAL_BOUNDARY.get(
        "group_path_required"
    )
    is True
)


NOTEBOOK_07_GROUP_PATH_DEFERRED_TO_NOTEBOOK = (
    BLOCK_1_ARCHITECTURAL_BOUNDARY.get(
        "group_path_deferred_to_notebook"
    )
)


BLOCK_1_ARCHITECTURAL_BOUNDARY_VALID = all(
    [
        NOTEBOOK_07_GLOBAL_PATH_REQUIRED,
        NOTEBOOK_07_GLOBAL_PATH_OPERATIONAL,
        NOTEBOOK_07_GROUP_PATH_AVAILABLE,
        not NOTEBOOK_07_GROUP_PATH_REQUIRED,

        (
            BLOCK_1_ARCHITECTURAL_BOUNDARY.get(
                "group_path_executed"
            )
            is False
        ),

        (
            BLOCK_1_ARCHITECTURAL_BOUNDARY.get(
                "group_path_trained"
            )
            is False
        ),

        (
            NOTEBOOK_07_GROUP_PATH_DEFERRED_TO_NOTEBOOK
            == 10
        ),

        (
            BLOCK_1_ARCHITECTURAL_BOUNDARY.get(
                "social_path_trained"
            )
            is False
        ),

        (
            BLOCK_1_ARCHITECTURAL_BOUNDARY.get(
                "transformative_mechanism_executed"
            )
            is False
        ),

        (
            BLOCK_1_ARCHITECTURAL_BOUNDARY.get(
                "transformative_weights_trained"
            )
            is False
        ),

        (
            BLOCK_1_ARCHITECTURAL_BOUNDARY.get(
                "recurrent_mechanism_executed"
            )
            is False
        ),
    ]
)


if not BLOCK_1_ARCHITECTURAL_BOUNDARY_VALID:

    raise RuntimeError(
        "Notebook 07 inherited architectural boundary is invalid."
    )


# =============================================================================
# Sequence / causal boundary
# =============================================================================

BLOCK_1_SEQUENCE_BOUNDARY = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "sequence_boundary",
        {},
    )
)


NOTEBOOK_07_PREDICTION_UNIT = (
    BLOCK_1_SEQUENCE_BOUNDARY.get(
        "prediction_unit"
    )
)


NOTEBOOK_07_PRECEDING_CONTEXT_ALLOWED = (
    BLOCK_1_SEQUENCE_BOUNDARY.get(
        "preceding_context_allowed"
    )
    is True
)


NOTEBOOK_07_FUTURE_CONTEXT_ALLOWED = (
    BLOCK_1_SEQUENCE_BOUNDARY.get(
        "future_context_allowed"
    )
    is True
)


NOTEBOOK_07_SENTENCE_ORDER_PRESERVED = (
    BLOCK_1_SEQUENCE_BOUNDARY.get(
        "sentence_order_preserved"
    )
    is True
)


NOTEBOOK_07_ARTICLE_BOUNDARY_RESET = (
    BLOCK_1_SEQUENCE_BOUNDARY.get(
        "article_boundary_reset"
    )
    is True
)


NOTEBOOK_07_CROSS_ARTICLE_STATE_CARRY = (
    BLOCK_1_SEQUENCE_BOUNDARY.get(
        "cross_article_state_carry"
    )
    is True
)


BLOCK_1_SEQUENCE_BOUNDARY_VALID = all(
    [
        NOTEBOOK_07_PREDICTION_UNIT
        ==
        "sentence",

        NOTEBOOK_07_PRECEDING_CONTEXT_ALLOWED,
        not NOTEBOOK_07_FUTURE_CONTEXT_ALLOWED,
        NOTEBOOK_07_SENTENCE_ORDER_PRESERVED,
        NOTEBOOK_07_ARTICLE_BOUNDARY_RESET,
        not NOTEBOOK_07_CROSS_ARTICLE_STATE_CARRY,
    ]
)


if not BLOCK_1_SEQUENCE_BOUNDARY_VALID:

    raise RuntimeError(
        "Notebook 07 inherited causal / sequence boundary is invalid."
    )


# =============================================================================
# Methodological boundary
# =============================================================================

BLOCK_1_METHOD_BOUNDARY = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "methodological_boundary",
        {},
    )
)


BLOCK_1_METHOD_BOUNDARY_VALID = all(
    [
        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "controlled_experimental_factual_checkpoint"
            )
            is True
        ),

        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "factual_checkpoint_reproducible"
            )
            is True
        ),

        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "validated_model_checkpoint"
            )
            is False
        ),

        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "held_out_evaluation_executed"
            )
            is False
        ),

        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "validation_early_stopping"
            )
            is False
        ),

        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "training_loss_used_as_generalisation_evidence"
            )
            is False
        ),

        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "group_conditioned_validity"
            )
            is False
        ),

        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "social_path_validity"
            )
            is False
        ),

        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "transformative_validity"
            )
            is False
        ),

        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "recurrent_validity"
            )
            is False
        ),

        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "generalisation_validated"
            )
            is False
        ),

        (
            BLOCK_1_METHOD_BOUNDARY.get(
                "empirical_validity"
            )
            is False
        ),
    ]
)


if not BLOCK_1_METHOD_BOUNDARY_VALID:

    raise RuntimeError(
        "Notebook 07 inherited methodological boundary is invalid."
    )


# =============================================================================
# Remaining roadmap
# =============================================================================

NOTEBOOK_07_REMAINING_VERSION_1_ROADMAP = deepcopy(
    NOTEBOOK_07_HANDOVER.get(
        "remaining_version_1_roadmap",
        {},
    )
)


BLOCK_1_REMAINING_ROADMAP_VALID = all(
    [
        (
            NOTEBOOK_07_REMAINING_VERSION_1_ROADMAP.get(
                "Notebook 07"
            )
            ==
            "Social Path"
        ),

        (
            NOTEBOOK_07_REMAINING_VERSION_1_ROADMAP.get(
                "Notebook 08"
            )
            ==
            "Transformative Mechanism"
        ),

        (
            NOTEBOOK_07_REMAINING_VERSION_1_ROADMAP.get(
                "Notebook 09"
            )
            ==
            "Transformative Weights and Recurrent Mechanism"
        ),

        (
            NOTEBOOK_07_REMAINING_VERSION_1_ROADMAP.get(
                "Notebook 10"
            )
            ==
            "Group-Conditioned Path and Final Integration"
        ),
    ]
)


if not BLOCK_1_REMAINING_ROADMAP_VALID:

    raise RuntimeError(
        "Notebook 07 inherited Version 1 roadmap is invalid."
    )


# =============================================================================
# Formal terminology transition
# =============================================================================
#
# Notebook 06 persisted the legacy designation "Social Path".
#
# Notebook 07 formally adopts "Social Representation".
#
# This is a terminology-only transition.
# Previous persisted artefacts remain unchanged.
# =============================================================================

NOTEBOOK_07_SOCIAL_REPRESENTATION_NAME = (
    "Social Representation"
)


NOTEBOOK_07_SOCIAL_REPRESENTATION_LEGACY_NAME = (
    "Social Path"
)


NOTEBOOK_07_SOCIAL_TERMINOLOGY_TRANSITION = {
    "legacy_name":
        NOTEBOOK_07_SOCIAL_REPRESENTATION_LEGACY_NAME,

    "formal_name":
        NOTEBOOK_07_SOCIAL_REPRESENTATION_NAME,

    "semantic_change":
        False,

    "architectural_change":
        False,

    "previous_artefacts_modified":
        False,
}


BLOCK_1_TERMINOLOGY_TRANSITION_VALID = all(
    [
        (
            NOTEBOOK_07_SOCIAL_REPRESENTATION_LEGACY_NAME
            ==
            "Social Path"
        ),

        (
            NOTEBOOK_07_SOCIAL_REPRESENTATION_NAME
            ==
            "Social Representation"
        ),

        (
            NOTEBOOK_07_SOCIAL_TERMINOLOGY_TRANSITION[
                "semantic_change"
            ]
            is False
        ),

        (
            NOTEBOOK_07_SOCIAL_TERMINOLOGY_TRANSITION[
                "architectural_change"
            ]
            is False
        ),

        (
            NOTEBOOK_07_SOCIAL_TERMINOLOGY_TRANSITION[
                "previous_artefacts_modified"
            ]
            is False
        ),
    ]
)


# =============================================================================
# Social Representation starting contract
# =============================================================================
#
# Block 1 intentionally does NOT assign social semantic dimensions.
#
# Their exact meanings must be resolved from the canonical social
# supervision source before any optimisation policy can be defined.
# =============================================================================

NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM_RESOLVED = False

NOTEBOOK_07_SOCIAL_DIMENSION_ORDER_RESOLVED = False

NOTEBOOK_07_SOCIAL_SEMANTIC_MAPPING_RESOLVED = False

NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_DEFINED = False

NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_VALID = False

NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_DEFINED = False

NOTEBOOK_07_SOCIAL_ACTIVATION_CONTRACT_RESOLVED = False

NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_RESOLVED = False

NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY = False

NOTEBOOK_07_SOCIAL_OPTIMISATION_READY = False


# =============================================================================
# Social Representation supervision policy
# =============================================================================

NOTEBOOK_07_SOCIAL_PREDICTION_UNIT = (
    "sentence"
)


NOTEBOOK_07_SOCIAL_CONTEXT_ASSISTED_SENTENCE = True

NOTEBOOK_07_SOCIAL_ARTICLE_LEVEL_TARGET = False

NOTEBOOK_07_SOCIAL_FUTURE_CONTEXT_ALLOWED = False

NOTEBOOK_07_SOCIAL_PARTIAL_SUPERVISION_ALLOWED = True

NOTEBOOK_07_SOCIAL_MASK_AWARE_SUPERVISION = True

NOTEBOOK_07_SOCIAL_MISSING_EQUALS_ZERO = False

NOTEBOOK_07_SOCIAL_MISSING_EQUALS_NEGATIVE = False

NOTEBOOK_07_SOCIAL_UNAVAILABLE_ENTERS_LOSS = False

NOTEBOOK_07_SOCIAL_FABRICATED_DIMENSIONS_ALLOWED = False


BLOCK_1_SOCIAL_SUPERVISION_POLICY_VALID = all(
    [
        NOTEBOOK_07_SOCIAL_PREDICTION_UNIT
        ==
        "sentence",

        NOTEBOOK_07_SOCIAL_CONTEXT_ASSISTED_SENTENCE,
        not NOTEBOOK_07_SOCIAL_ARTICLE_LEVEL_TARGET,
        not NOTEBOOK_07_SOCIAL_FUTURE_CONTEXT_ALLOWED,
        NOTEBOOK_07_SOCIAL_PARTIAL_SUPERVISION_ALLOWED,
        NOTEBOOK_07_SOCIAL_MASK_AWARE_SUPERVISION,
        not NOTEBOOK_07_SOCIAL_MISSING_EQUALS_ZERO,
        not NOTEBOOK_07_SOCIAL_MISSING_EQUALS_NEGATIVE,
        not NOTEBOOK_07_SOCIAL_UNAVAILABLE_ENTERS_LOSS,
        not NOTEBOOK_07_SOCIAL_FABRICATED_DIMENSIONS_ALLOWED,
    ]
)


if not BLOCK_1_SOCIAL_SUPERVISION_POLICY_VALID:

    raise RuntimeError(
        "Notebook 07 starting social-supervision policy is invalid."
    )


# =============================================================================
# Inherited representation freeze policy
# =============================================================================

NOTEBOOK_07_CONTEXTUAL_REPRESENTATION_FROZEN = True

NOTEBOOK_07_BACKBONE_FROZEN = True

NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN = True

NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_FROZEN = True

NOTEBOOK_07_FACTUAL_REPRESENTATION_FROZEN = True


BLOCK_1_INHERITED_REPRESENTATIONS_FROZEN = all(
    [
        NOTEBOOK_07_CONTEXTUAL_REPRESENTATION_FROZEN,
        NOTEBOOK_07_BACKBONE_FROZEN,
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN,
        NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_FROZEN,
        NOTEBOOK_07_FACTUAL_REPRESENTATION_FROZEN,
    ]
)


# =============================================================================
# Social Representation readiness
# =============================================================================

NOTEBOOK_07_HANDOVER_VALID = all(
    [
        BLOCK_1_HANDOVER_TOP_LEVEL_VALID,
        BLOCK_1_PROJECT_STATE_VALID,
        BLOCK_1_IDENTITY_CONTRACT_VALID,
        BLOCK_1_INHERITED_CONTRACT_VALID,
        BLOCK_1_FACTUAL_REPRESENTATION_VALID,
        BLOCK_1_FACTUAL_ARTEFACT_REFERENCES_VALID,
        BLOCK_1_FACTUAL_TRAINING_STATE_VALID,
        BLOCK_1_STARTING_FREEZE_POLICY_VALID,
        BLOCK_1_ARCHITECTURAL_BOUNDARY_VALID,
        BLOCK_1_SEQUENCE_BOUNDARY_VALID,
        BLOCK_1_METHOD_BOUNDARY_VALID,
        BLOCK_1_REMAINING_ROADMAP_VALID,
        BLOCK_1_TERMINOLOGY_TRANSITION_VALID,
        BLOCK_1_SOCIAL_SUPERVISION_POLICY_VALID,
        BLOCK_1_INHERITED_REPRESENTATIONS_FROZEN,
    ]
)


NOTEBOOK_07_READY_FOR_SOCIAL_SUPERVISION_AUDIT = (
    NOTEBOOK_07_HANDOVER_VALID
)


NOTEBOOK_07_READY_FOR_SOCIAL_OPTIMISATION = False


if not NOTEBOOK_07_HANDOVER_VALID:

    raise RuntimeError(
        "Notebook 07 handover validation failed."
    )


# =============================================================================
# Social scope audit table
# =============================================================================

BLOCK_1_SOCIAL_SCOPE_ROWS = [
    {
        "scope_item":
            "prediction_unit",

        "current_state":
            "sentence",

        "resolved":
            True,

        "trainable":
            False,

        "notes":
            "Canonical supervision and prediction unit remains the sentence.",
    },

    {
        "scope_item":
            "preceding_context",

        "current_state":
            "allowed_when_required",

        "resolved":
            True,

        "trainable":
            False,

        "notes":
            (
                "Preceding context may assist interpretation; "
                "future context remains prohibited."
            ),
    },

    {
        "scope_item":
            "social_semantic_dimensions",

        "current_state":
            "unresolved",

        "resolved":
            False,

        "trainable":
            False,

        "notes":
            (
                "Must be derived explicitly from canonical "
                "social supervision."
            ),
    },

    {
        "scope_item":
            "social_target_contract",

        "current_state":
            "unresolved",

        "resolved":
            False,

        "trainable":
            False,

        "notes":
            "Must be defined before objective construction.",
    },

    {
        "scope_item":
            "social_loss_contract",

        "current_state":
            "unresolved",

        "resolved":
            False,

        "trainable":
            False,

        "notes":
            "Depends on target family and variability.",
    },

    {
        "scope_item":
            "social_optimisation",

        "current_state":
            "blocked",

        "resolved":
            False,

        "trainable":
            False,

        "notes":
            (
                "Optimisation remains blocked until supervision, "
                "activation and model policies are resolved."
            ),
    },

    {
        "scope_item":
            "psychological_representation",

        "current_state":
            "frozen",

        "resolved":
            True,

        "trainable":
            False,

        "notes":
            "Completed inherited representation.",
    },

    {
        "scope_item":
            "factual_representation",

        "current_state":
            "frozen",

        "resolved":
            True,

        "trainable":
            False,

        "notes":
            "Completed inherited representation.",
    },

    {
        "scope_item":
            "group_conditioned_path",

        "current_state":
            "deferred_to_notebook_10",

        "resolved":
            True,

        "trainable":
            False,

        "notes":
            "Architecturally available but inactive.",
    },

    {
        "scope_item":
            "transformative_mechanism",

        "current_state":
            "deferred_to_notebook_08",

        "resolved":
            True,

        "trainable":
            False,

        "notes":
            "Not activated in Notebook 07.",
    },

    {
        "scope_item":
            "transformative_weights",

        "current_state":
            "deferred_to_notebook_09",

        "resolved":
            True,

        "trainable":
            False,

        "notes":
            "Not activated in Notebook 07.",
    },

    {
        "scope_item":
            "recurrent_mechanism",

        "current_state":
            "deferred_to_notebook_09",

        "resolved":
            True,

        "trainable":
            False,

        "notes":
            "Not activated in Notebook 07.",
    },
]


BLOCK_1_SOCIAL_SCOPE_AUDIT = pd.DataFrame(
    BLOCK_1_SOCIAL_SCOPE_ROWS
)


# =============================================================================
# Final Block 1 validation
# =============================================================================

NOTEBOOK_07_BLOCK_1_ERRORS = []


block_1_validation_checks = {
    "drive_service_not_initialised":
        BLOCK_1_DRIVE_SERVICE_INITIALISED,

    "handover_not_located":
        BLOCK_1_HANDOVER_LOCATED,

    "handover_filename_invalid":
        BLOCK_1_HANDOVER_FILENAME_VALID,

    "handover_not_downloaded":
        BLOCK_1_HANDOVER_DOWNLOADED,

    "local_audit_copy_not_created":
        BLOCK_1_LOCAL_AUDIT_COPY_CREATED,

    "handover_json_not_parsed":
        BLOCK_1_HANDOVER_JSON_PARSED,

    "handover_top_level_invalid":
        BLOCK_1_HANDOVER_TOP_LEVEL_VALID,

    "project_state_invalid":
        BLOCK_1_PROJECT_STATE_VALID,

    "identity_contract_invalid":
        BLOCK_1_IDENTITY_CONTRACT_VALID,

    "inherited_contract_invalid":
        BLOCK_1_INHERITED_CONTRACT_VALID,

    "factual_representation_invalid":
        BLOCK_1_FACTUAL_REPRESENTATION_VALID,

    "factual_artefact_references_invalid":
        BLOCK_1_FACTUAL_ARTEFACT_REFERENCES_VALID,

    "factual_training_state_invalid":
        BLOCK_1_FACTUAL_TRAINING_STATE_VALID,

    "starting_freeze_policy_invalid":
        BLOCK_1_STARTING_FREEZE_POLICY_VALID,

    "architectural_boundary_invalid":
        BLOCK_1_ARCHITECTURAL_BOUNDARY_VALID,

    "sequence_boundary_invalid":
        BLOCK_1_SEQUENCE_BOUNDARY_VALID,

    "methodological_boundary_invalid":
        BLOCK_1_METHOD_BOUNDARY_VALID,

    "roadmap_invalid":
        BLOCK_1_REMAINING_ROADMAP_VALID,

    "terminology_transition_invalid":
        BLOCK_1_TERMINOLOGY_TRANSITION_VALID,

    "social_supervision_policy_invalid":
        BLOCK_1_SOCIAL_SUPERVISION_POLICY_VALID,

    "inherited_representations_not_frozen":
        BLOCK_1_INHERITED_REPRESENTATIONS_FROZEN,

    "handover_invalid":
        NOTEBOOK_07_HANDOVER_VALID,

    "social_supervision_audit_not_ready":
        NOTEBOOK_07_READY_FOR_SOCIAL_SUPERVISION_AUDIT,
}


for (
    error_name,
    condition,
) in block_1_validation_checks.items():

    if not condition:

        NOTEBOOK_07_BLOCK_1_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited-operation validation
# =============================================================================

prohibited_block_1_operations = {
    "social_mapping_incorrectly_performed":
        NOTEBOOK_07_SOCIAL_MAPPING_PERFORMED,

    "social_objectives_incorrectly_activated":
        NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED,

    "social_optimizer_incorrectly_created":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED,

    "social_forward_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED,

    "social_loss_incorrectly_calculated":
        NOTEBOOK_07_SOCIAL_LOSS_CALCULATED,

    "social_backward_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED,

    "social_parameter_update_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED,

    "social_training_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED,

    "psychological_training_incorrectly_executed":
        NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "factual_training_incorrectly_executed":
        NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED,

    "backbone_training_incorrectly_executed":
        NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED,

    "global_confluent_training_incorrectly_executed":
        NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED,

    "group_conditioned_path_incorrectly_executed":
        NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_mechanism_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED,

    "transformative_weights_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED,

    "recurrent_mechanism_incorrectly_executed":
        NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for (
    error_name,
    operation_executed,
) in prohibited_block_1_operations.items():

    if operation_executed:

        NOTEBOOK_07_BLOCK_1_ERRORS.append(
            error_name
        )


NOTEBOOK_07_BLOCK_1_VALID = (
    len(
        NOTEBOOK_07_BLOCK_1_ERRORS
    )
    == 0
)


if not NOTEBOOK_07_BLOCK_1_VALID:

    raise RuntimeError(
        "Notebook 07 Block 1 initialisation audit failed. "
        f"Errors: {NOTEBOOK_07_BLOCK_1_ERRORS}"
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_07_INITIALISED = True

NOTEBOOK_07_BLOCK_1_COMPLETE = True


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_07_BLOCK_1_SUMMARY = {
    "block":
        NOTEBOOK_07_BLOCK_1,

    "block_name":
        NOTEBOOK_07_BLOCK_1_NAME,

    "block_version":
        NOTEBOOK_07_BLOCK_1_VERSION,

    "executed_at_utc":
        BLOCK_1_EXECUTED_AT_UTC,

    "notebook":
        NOTEBOOK_07,

    "notebook_version":
        NOTEBOOK_07_VERSION,

    "formal_designation":
        NOTEBOOK_07_FORMAL_DESIGNATION,

    "legacy_designation":
        NOTEBOOK_07_LEGACY_DESIGNATION,

    "handover_drive_file_id":
        NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID,

    "handover_valid":
        NOTEBOOK_07_HANDOVER_VALID,

    "article_count":
        NOTEBOOK_07_ARTICLE_COUNT,

    "sentence_count":
        NOTEBOOK_07_SENTENCE_COUNT,

    "factual_representation_dimension":
        NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM,

    "factual_path_complete":
        BLOCK_1_FACTUAL_PATH_COMPLETE,

    "factual_path_reproducible":
        BLOCK_1_FACTUAL_PATH_REPRODUCIBLE,

    "psychological_frozen":
        NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_FROZEN,

    "factual_frozen":
        NOTEBOOK_07_FACTUAL_REPRESENTATION_FROZEN,

    "social_dimension_resolved":
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM_RESOLVED,

    "social_mapping_resolved":
        NOTEBOOK_07_SOCIAL_SEMANTIC_MAPPING_RESOLVED,

    "social_optimisation_ready":
        NOTEBOOK_07_SOCIAL_OPTIMISATION_READY,

    "ready_for_social_supervision_audit":
        NOTEBOOK_07_READY_FOR_SOCIAL_SUPERVISION_AUDIT,

    "empirical_validity":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_07_BLOCK_1_VALID,

    "block_complete":
        NOTEBOOK_07_BLOCK_1_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 07, Block 1: "
    "Notebook 06 → 07 Handover Restoration, "
    "Social Representation Scope and Initialisation Audit"
)

print("=" * 72)

print(
    f"Notebook                     : "
    f"{NOTEBOOK_07}"
)

print(
    f"Notebook version             : "
    f"{NOTEBOOK_07_VERSION}"
)

print(
    f"Block version                : "
    f"{NOTEBOOK_07_BLOCK_1_VERSION}"
)

print(
    f"Project random seed          : "
    f"{NOTEBOOK_07_RANDOM_SEED}"
)


print("-" * 72)

print(
    "Google authentication"
)

print(
    f"Colab authenticated          : "
    f"{BLOCK_1_COLAB_AUTHENTICATED}"
)

print(
    f"Drive service initialised    : "
    f"{BLOCK_1_DRIVE_SERVICE_INITIALISED}"
)


print("-" * 72)

print(
    "Persistent Notebook 06 → 07 handover"
)

print(
    f"Handover filename            : "
    f"{NOTEBOOK_06_TO_07_HANDOVER_FILENAME}"
)

print(
    f"Drive file ID                : "
    f"{NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID}"
)

print(
    f"Drive file modified          : "
    f"{BLOCK_1_HANDOVER_DRIVE_METADATA.get('modifiedTime')}"
)

print(
    f"Handover located             : "
    f"{BLOCK_1_HANDOVER_LOCATED}"
)

print(
    f"Handover downloaded          : "
    f"{BLOCK_1_HANDOVER_DOWNLOADED}"
)

print(
    f"Local audit copy             : "
    f"{BLOCK_1_LOCAL_AUDIT_COPY_CREATED}"
)

print(
    f"JSON parsed                  : "
    f"{BLOCK_1_HANDOVER_JSON_PARSED}"
)

print(
    f"Handover valid               : "
    f"{NOTEBOOK_07_HANDOVER_VALID}"
)


print("-" * 72)

print(
    "Terminology"
)

print(
    f"Inherited designation       : "
    f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_LEGACY_NAME}"
)

print(
    f"Formal designation          : "
    f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_NAME}"
)

print(
    f"Semantic change             : "
    f"{NOTEBOOK_07_SOCIAL_TERMINOLOGY_TRANSITION['semantic_change']}"
)

print(
    f"Architectural change        : "
    f"{NOTEBOOK_07_SOCIAL_TERMINOLOGY_TRANSITION['architectural_change']}"
)


print("-" * 72)

print(
    "Notebook 06 source state"
)

print(
    f"Notebook 06 complete         : "
    f"{BLOCK_1_NOTEBOOK_06_COMPLETE}"
)

print(
    f"Factual path complete        : "
    f"{BLOCK_1_FACTUAL_PATH_COMPLETE}"
)

print(
    f"Factual path reproducible    : "
    f"{BLOCK_1_FACTUAL_PATH_REPRODUCIBLE}"
)

print(
    f"Controlled factual pipeline  : "
    f"{BLOCK_1_CONTROLLED_FACTUAL_PIPELINE_COMPLETE}"
)

print(
    f"Full project complete        : "
    f"{BLOCK_1_FULL_PROJECT_COMPLETE}"
)

print(
    f"Generalisation validated     : "
    f"{BLOCK_1_GENERALISATION_VALIDATED}"
)


print("-" * 72)

print(
    "Canonical identity"
)

print(
    f"Articles                     : "
    f"{NOTEBOOK_07_ARTICLE_COUNT}"
)

print(
    f"Sentences                    : "
    f"{NOTEBOOK_07_SENTENCE_COUNT}"
)

print(
    f"Sentence IDs present         : "
    f"{BLOCK_1_SENTENCE_IDS_PRESENT}"
)

print(
    f"Sentence IDs unique          : "
    f"{BLOCK_1_SENTENCE_IDS_UNIQUE}"
)

print(
    f"Identity contract valid      : "
    f"{BLOCK_1_IDENTITY_CONTRACT_VALID}"
)

print(
    f"Derived article IDs          : "
    f"{list(BLOCK_1_DERIVED_ARTICLE_IDS)}"
)


print("-" * 72)

print(
    "Inherited representation state"
)

print(
    f"Backbone frozen              : "
    f"{NOTEBOOK_07_BACKBONE_FROZEN_BY_DEFAULT}"
)

print(
    f"Global confluent frozen      : "
    f"{NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_BY_DEFAULT}"
)

print(
    f"Psychological repr. frozen   : "
    f"{NOTEBOOK_07_PSYCHOLOGICAL_PATH_FROZEN_BY_DEFAULT}"
)

print(
    f"Factual repr. frozen         : "
    f"{NOTEBOOK_07_FACTUAL_PATH_FROZEN_BY_DEFAULT}"
)

print(
    f"Factual representation dim.  : "
    f"{NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM}"
)

print(
    f"Factual checkpoint type      : "
    f"{NOTEBOOK_07_FACTUAL_CHECKPOINT_TYPE}"
)

print(
    f"Factual final objective      : "
    f"{NOTEBOOK_07_FACTUAL_FINAL_OBJECTIVE:.8f}"
)

print(
    f"Factual training articles    : "
    f"{BLOCK_1_FACTUAL_TRAINING_ARTICLES}"
)

print(
    f"Factual training sentences   : "
    f"{BLOCK_1_FACTUAL_TRAINING_SENTENCES}"
)

print(
    f"Factual training epochs      : "
    f"{BLOCK_1_FACTUAL_TRAINING_EPOCHS}"
)

print(
    f"Factual optimiser            : "
    f"{BLOCK_1_FACTUAL_OPTIMIZER}"
)

print(
    f"Factual training state valid : "
    f"{BLOCK_1_FACTUAL_TRAINING_STATE_VALID}"
)


print("-" * 72)

print(
    "Social Representation starting contract"
)

print(
    f"Prediction unit              : "
    f"{NOTEBOOK_07_SOCIAL_PREDICTION_UNIT}"
)

print(
    f"Context-assisted sentence    : "
    f"{NOTEBOOK_07_SOCIAL_CONTEXT_ASSISTED_SENTENCE}"
)

print(
    f"Future context allowed       : "
    f"{NOTEBOOK_07_SOCIAL_FUTURE_CONTEXT_ALLOWED}"
)

print(
    f"Mask-aware supervision       : "
    f"{NOTEBOOK_07_SOCIAL_MASK_AWARE_SUPERVISION}"
)

print(
    f"Partial supervision allowed  : "
    f"{NOTEBOOK_07_SOCIAL_PARTIAL_SUPERVISION_ALLOWED}"
)

print(
    f"Fabricated dimensions allowed: "
    f"{NOTEBOOK_07_SOCIAL_FABRICATED_DIMENSIONS_ALLOWED}"
)

print(
    f"Social dimension resolved    : "
    f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM_RESOLVED}"
)

print(
    f"Semantic mapping resolved    : "
    f"{NOTEBOOK_07_SOCIAL_SEMANTIC_MAPPING_RESOLVED}"
)

print(
    f"Target contract defined      : "
    f"{NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_DEFINED}"
)

print(
    f"Optimisation ready           : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMISATION_READY}"
)


print("-" * 72)

print(
    "Architectural boundary"
)

print(
    f"Global path required         : "
    f"{NOTEBOOK_07_GLOBAL_PATH_REQUIRED}"
)

print(
    f"Global path operational      : "
    f"{NOTEBOOK_07_GLOBAL_PATH_OPERATIONAL}"
)

print(
    f"Group path available         : "
    f"{NOTEBOOK_07_GROUP_PATH_AVAILABLE}"
)

print(
    f"Group path required          : "
    f"{NOTEBOOK_07_GROUP_PATH_REQUIRED}"
)

print(
    f"Group path deferred to N     : "
    f"{NOTEBOOK_07_GROUP_PATH_DEFERRED_TO_NOTEBOOK}"
)


print("-" * 72)

print(
    "Remaining Version 1 roadmap"
)

print(
    f"Notebook 07                 : "
    f"Social Representation"
)

print(
    f"Notebook 08                 : "
    f"Transformative Mechanism"
)

print(
    f"Notebook 09                 : "
    f"Transformative Weights and Recurrent Mechanism"
)

print(
    f"Notebook 10                 : "
    f"Group-Conditioned Path and Final Integration"
)


print("-" * 72)

print(
    "Readiness"
)

print(
    f"Notebook 07 initialised      : "
    f"{NOTEBOOK_07_INITIALISED}"
)

print(
    f"Handover valid               : "
    f"{NOTEBOOK_07_HANDOVER_VALID}"
)

print(
    f"Ready for social supervision : "
    f"{NOTEBOOK_07_READY_FOR_SOCIAL_SUPERVISION_AUDIT}"
)

print(
    f"Social optimisation ready    : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMISATION_READY}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Social mapping performed     : "
    f"{NOTEBOOK_07_SOCIAL_MAPPING_PERFORMED}"
)

print(
    f"Social objectives activated  : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED}"
)

print(
    f"Social optimiser created     : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED}"
)

print(
    f"Social forward executed      : "
    f"{NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED}"
)

print(
    f"Social loss calculated       : "
    f"{NOTEBOOK_07_SOCIAL_LOSS_CALCULATED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Social training executed     : "
    f"{NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Factual retraining           : "
    f"{NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative executed      : "
    f"{NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED}"
)

print(
    f"Transformative weights active: "
    f"{NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED}"
)

print(
    f"Recurrent executed           : "
    f"{NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED}"
)

print(
    f"Held-out evaluation executed : "
    f"{NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_07_BLOCK_1_VALID}"
)

print(
    f"Block 1 complete             : "
    f"{NOTEBOOK_07_BLOCK_1_COMPLETE}"
)


print("=" * 72)


print(
    "Notebook 07 initialised successfully from the persistent "
    "Notebook 06 → Notebook 07 handover."
)

print(
    "The formal component name is now Social Representation; "
    "the inherited Social Path designation is retained only as a "
    "legacy compatibility term."
)

print(
    "The terminology transition introduces no semantic or architectural "
    "change and does not modify any preceding notebook artefact."
)

print(
    "Canonical sentence identity, causal ordering and article-boundary "
    "rules remain preserved."
)

print(
    "The completed psychological and factual representations remain "
    "frozen by default."
)

print(
    "The backbone and mandatory global confluent representation also "
    "remain frozen."
)

print(
    "The factual path remains complete, persisted and reproducible."
)

print(
    "The Social Representation semantic dimensions have not yet been "
    "assigned or fabricated."
)

print(
    "Social supervision remains mask-aware, context-assisted at the "
    "sentence level and restricted from using future context."
)

print(
    "The optional group-conditioned path remains inactive and deferred "
    "to Notebook 10."
)

print(
    "The Transformative Mechanism remains reserved for Notebook 08."
)

print(
    "Transformative Weights and recurrent mechanisms remain reserved "
    "for Notebook 09."
)

print(
    "No social target mapping, objective activation, forward pass, loss "
    "calculation, optimiser creation, backward pass, parameter update "
    "or training has been performed by Block 1."
)

print(
    "No previous representation has been retrained."
)

print(
    "Block 2 may proceed to Social Supervision Discovery, Semantic "
    "Dimension Mapping and Target-Contract Audit."
)

print("=" * 72)


# =============================================================================
# Display Social Representation starting-scope audit
# =============================================================================

display(
    BLOCK_1_SOCIAL_SCOPE_AUDIT
)

WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.
WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.

========================================================================
Media AI — Notebook 07, Block 1: Notebook 06 → 07 Handover Restoration, Social Representation Scope and Initialisation Audit
========================================================================
Notebook                     : 07_social_representation
Notebook version             : 1.0
Block version                : 1.1
Project random seed          : 42
------------------------------------------------------------------------
Google authentication
Colab authenticated          : True
Drive service initialised    : True
------------------------------------------------------------------------
Persistent Notebook 06 → 07 handover
Handover filename            : notebook_06_to_07_handover.json
Drive file ID                : 1Qe_QwbJ3FK7B797zIQcOryWIy_qhcMSt
Drive file modified          : 2026-08-24T23:08:14.120Z
Handover located             : True
Handover downloaded          : True
Local audit copy             : True
JSON parsed                  : True
Handover valid               : True
------------------------------------------------------------------------
Terminology
Inherited designation       : Social Path
Formal designation          : Social Representation
Semantic change             : False
Architectural change        : False
------------------------------------------------------------------------
Notebook 06 source state
Notebook 06 complete         : True
Factual path complete        : True
Factual path reproducible    : True
Controlled factual pipeline  : True
Full project complete        : False
Generalisation validated     : False
------------------------------------------------------------------------
Canonical identity
Articles                     : 3
Sentences                    : 54
Sentence IDs present         : True
Sentence IDs unique          : True
Identity contract valid      : True
Derived article IDs          : ['1ef9745c-2c21-47c2-a222-e7c160448f82', '33270083-262f-44e9-9a90-ac857f026e72', 'bca49d4d-ec96-4fee-a2e0-cc1e98dc9fcb']
------------------------------------------------------------------------
Inherited representation state
Backbone frozen              : True
Global confluent frozen      : True
Psychological repr. frozen   : True
Factual repr. frozen         : True
Factual representation dim.  : 10
Factual checkpoint type      : controlled_experimental_factual_training_checkpoint
Factual final objective      : 0.40325385
Factual training articles    : 3
Factual training sentences   : 54
Factual training epochs      : 10
Factual optimiser            : AdamW
Factual training state valid : True
------------------------------------------------------------------------
Social Representation starting contract
Prediction unit              : sentence
Context-assisted sentence    : True
Future context allowed       : False
Mask-aware supervision       : True
Partial supervision allowed  : True
Fabricated dimensions allowed: False
Social dimension resolved    : False
Semantic mapping resolved    : False
Target contract defined      : False
Optimisation ready           : False
------------------------------------------------------------------------
Architectural boundary
Global path required         : True
Global path operational      : True
Group path available         : True
Group path required          : False
Group path deferred to N     : 10
------------------------------------------------------------------------
Remaining Version 1 roadmap
Notebook 07                 : Social Representation
Notebook 08                 : Transformative Mechanism
Notebook 09                 : Transformative Weights and Recurrent Mechanism
Notebook 10                 : Group-Conditioned Path and Final Integration
------------------------------------------------------------------------
Readiness
Notebook 07 initialised      : True
Handover valid               : True
Ready for social supervision : True
Social optimisation ready    : False
------------------------------------------------------------------------
Execution boundary
Social mapping performed     : False
Social objectives activated  : False
Social optimiser created     : False
Social forward executed      : False
Social loss calculated       : False
Backward pass executed       : False
Parameter update executed    : False
Social training executed     : False
Psychological retraining     : False
Factual retraining           : False
Group-conditioned executed   : False
Transformative executed      : False
Transformative weights active: False
Recurrent executed           : False
Held-out evaluation executed : False
Empirical validity           : False
Block valid                  : True
Block 1 complete             : True
========================================================================
Notebook 07 initialised successfully from the persistent Notebook 06 → Notebook 07 handover.
The formal component name is now Social Representation; the inherited Social Path designation is retained only as a legacy compatibility term.
The terminology transition introduces no semantic or architectural change and does not modify any preceding notebook artefact.
Canonical sentence identity, causal ordering and article-boundary rules remain preserved.
The completed psychological and factual representations remain frozen by default.
The backbone and mandatory global confluent representation also remain frozen.
The factual path remains complete, persisted and reproducible.
The Social Representation semantic dimensions have not yet been assigned or fabricated.
Social supervision remains mask-aware, context-assisted at the sentence level and restricted from using future context.
The optional group-conditioned path remains inactive and deferred to Notebook 10.
The Transformative Mechanism remains reserved for Notebook 08.
Transformative Weights and recurrent mechanisms remain reserved for Notebook 09.
No social target mapping, objective activation, forward pass, loss calculation, optimiser creation, backward pass, parameter update or training has been performed by Block 1.
No previous representation has been retrained.
Block 2 may proceed to Social Supervision Discovery, Semantic Dimension Mapping and Target-Contract Audit.
========================================================================

,scope_item,current_state,resolved,trainable,notes
0,prediction_unit,sentence,True,False,Canonical supervision and prediction unit rema...
1,preceding_context,allowed_when_required,True,False,Preceding context may assist interpretation; f...
2,social_semantic_dimensions,unresolved,False,False,Must be derived explicitly from canonical soci...
3,social_target_contract,unresolved,False,False,Must be defined before objective construction.
4,social_loss_contract,unresolved,False,False,Depends on target family and variability.
5,social_optimisation,blocked,False,False,Optimisation remains blocked until supervision...
6,psychological_representation,frozen,True,False,Completed inherited representation.
7,factual_representation,frozen,True,False,Completed inherited representation.
8,group_conditioned_path,deferred_to_notebook_10,True,False,Architecturally available but inactive.
9,transformative_mechanism,deferred_to_notebook_08,True,False,Not activated in Notebook 07.
10,transformative_weights,deferred_to_notebook_09,True,False,Not activated in Notebook 07.
11,recurrent_mechanism,deferred_to_notebook_09,True,False,Not activated in Notebook 07.

## Block 2 — Social Supervision Discovery, Semantic Dimension Mapping and Target-Contract Audit

This block inspects the canonical accepted supervision inherited by Notebook 07 and determines which available annotations can legitimately support the Social Representation.

The block does not train the Social Representation.

Its purpose is to discover the available social supervision, distinguish socially meaningful signals from psychological and factual constructs already represented elsewhere, establish explicit semantic mappings where supported, and construct a mask-aware Social Representation target contract without fabricating dimensions.

### Canonical supervision source

Notebook 07 must derive Social Representation supervision from the canonical accepted annotation artefact established by the preceding supervision workflow.

The source supervision is treated as immutable.

Block 2 may:

- inspect canonical annotation fields,
- identify candidate social constructs,
- determine their availability,
- resolve semantic mappings,
- construct Notebook 07-specific target records,
- persist a separate Social Representation target contract.

Block 2 must not modify the canonical source annotations.

### Supervision discovery before dimensionality

The dimensionality of the Social Representation is not predetermined.

The block first inspects the canonical supervision to determine:

- which potentially social annotation fields exist,
- which fields contain usable observations,
- which constructs are semantically social,
- which constructs belong to already completed representations,
- which source constructs may require semantic refinement,
- which candidate constructs cannot be resolved safely.

Only after this audit may the Social Representation dimensionality be established.

This prevents the architecture from forcing the supervision into an arbitrary predefined shape.

### Social semantic boundary

A candidate dimension belongs to the Social Representation only when its meaning concerns relations between the sentence and socially situated actors, groups, institutions, audiences, roles or interactions.

The Social Representation should capture socially meaningful structure rather than duplicate general psychological or factual content.

Candidate supervision must therefore be evaluated against the completed representation boundaries.

A construct should not be mapped into the Social Representation merely because it appears in the annotation schema.

### Separation from Psychological Representation

The completed Psychological Representation remains semantically authoritative for psychological constructs already assigned to it.

Block 2 must avoid duplicating dimensions whose primary meaning concerns internal or expressed psychological characteristics already represented by the psychological head.

Where a source annotation could plausibly belong to both psychological and social interpretation, the mapping must be justified explicitly.

Ambiguous constructs remain unresolved rather than being assigned automatically.

### Separation from Factual Representation

The completed Factual Representation remains semantically authoritative for factual constructs already assigned to its ten-dimensional contract.

Social supervision must not duplicate factual dimensions such as:

- explicit claims,
- observations or events,
- quantitative information,
- attribution as a factual construct,
- evidence references,
- certainty or uncertainty statements,
- speculation,
- prediction,
- factological weight.

A source field may contribute to Social Representation only if it supports a distinct social meaning rather than reproducing the factual target.

### Candidate social constructs

The discovery stage may encounter constructs concerning, for example:

- social actors,
- interpersonal relations,
- group references,
- institutional actors,
- social roles,
- audience relationships,
- collective behaviour,
- cooperation or conflict,
- social alignment or opposition,
- other explicitly annotated social relationships.

These are examples of possible semantic categories, not predefined Social Representation dimensions.

No candidate becomes part of the representation unless supported by the canonical supervision.

### Direct mapping

A Social Representation dimension may be mapped directly when a canonical supervision field already corresponds to a sufficiently clear and distinct social construct.

A direct mapping must preserve:

- the source meaning,
- the source availability state,
- sentence identity,
- provenance,
- missing-value semantics.

Direct mappings must not reinterpret unavailable supervision as an observed value.

### Semantic refinement

Some canonical supervision constructs may combine meanings that should not automatically become a single Social Representation dimension.

Semantic refinement is permitted only when the source supervision and canonical sentence context provide sufficient deterministic evidence to separate the meanings safely.

A refinement must record:

- the original source field,
- the original source value,
- the refinement rule,
- the resulting Social Representation dimension,
- whether the refined target is observed or unavailable.

A source signal must not be duplicated blindly across several Social Representation dimensions.

If a positive source signal cannot be resolved safely, the corresponding refined target remains masked.

### Context policy

The canonical prediction unit remains the sentence.

The current sentence provides the primary evidence for Social Representation mapping.

Preceding context may be used where required to resolve:

- actor identity,
- pronoun reference,
- relationship continuity,
- institutional reference,
- group membership,
- other socially relevant antecedents.

Future article context remains prohibited.

The block therefore preserves causal contextual interpretation.

### Target availability

Each Social Representation target dimension must carry an independent availability mask.

An observed numerical zero means an explicitly observed absence or zero-valued target where the source contract supports that interpretation.

An unavailable value means that the supervision does not establish the target.

These states are not interchangeable.

The target contract therefore preserves:

**observed zero ≠ missing supervision**

and:

**missing supervision ≠ negative evidence**

### Partial supervision

Full target coverage is not required for a sentence to contribute to later Social Representation optimisation.

A sentence may provide supervision for only a subset of the resolved social dimensions.

Independent masks allow available dimensions to contribute while unavailable dimensions remain outside the objective.

This preserves the mask-aware supervision policy established in Block 1.

### Dimensionality resolution

The Social Representation dimension is established only after semantic discovery and mapping are complete.

Every retained dimension must have:

- a unique identifier,
- a canonical semantic name,
- an explicit definition,
- a documented source mapping,
- provenance,
- an availability mask.

The final dimension count must equal the number of explicitly resolved and retained social dimensions.

No padding dimensions are permitted.

No placeholder dimensions are permitted.

No fabricated dimensions are permitted.

### Target-family classification

Block 2 identifies the semantic target family of each resolved dimension where this can be determined from the canonical supervision.

Possible target families may include:

- binary social-content targets,
- categorical social targets,
- continuous social targets,
- other explicitly justified supervised forms.

The existence of a target family does not yet activate an optimisation objective.

Loss functions are not selected merely from semantic names.

### Target-contract construction

For every canonical sentence, Block 2 constructs a Social Representation target record containing:

- canonical sentence identity,
- permitted contextual information,
- Social Representation target values,
- independent availability masks,
- dimension order,
- dimension identifiers,
- mapping provenance,
- source availability information.

The resulting target matrix must have the form:

`number_of_sentences × resolved_social_dimension`

with a corresponding mask matrix of identical shape.

### Provenance contract

Every Social Representation dimension must be traceable to canonical supervision.

The persisted contract must distinguish between:

- direct canonical mappings,
- justified Notebook 07 semantic refinements,
- unresolved candidate constructs,
- excluded constructs belonging to other representations.

The number of fabricated dimensions must remain zero.

The canonical source records must remain unmodified.

### Persistent Social Representation target artefact

The resolved Social Representation target contract should be persisted separately from the canonical supervision.

The artefact should record:

- source artefact identity,
- Social Representation dimensionality,
- dimension identifiers,
- dimension order,
- semantic definitions,
- mapping rules,
- refinement rules where applicable,
- availability statistics,
- target-family classifications,
- masking semantics,
- provenance,
- execution boundary.

A read-back validation should confirm that the persisted artefact reproduces the resolved contract.

### Optimisation boundary

Block 2 does not determine whether a resolved Social Representation dimension provides sufficient variability for useful optimisation.

A semantically valid dimension may later prove to have:

- zero variance,
- severe class imbalance,
- insufficient observations,
- insufficient category support,
- inadequate continuous-value variation.

Those questions belong to the subsequent availability, variability, activation and loss-contract analysis.

Accordingly, successful semantic resolution does not imply training eligibility.

### Architectural boundary

The completed upstream components remain frozen.

Block 2 does not modify or retrain:

- the backbone,
- mandatory global confluent representation,
- Psychological Representation,
- Factual Representation.

The optional group-conditioned path remains deferred to Notebook 10.

The Transformative Mechanism remains deferred to Notebook 08.

Transformative Weights and recurrent mechanisms remain deferred to Notebook 09.

### Execution boundary

Block 2 performs no:

- Social Representation objective activation,
- optimiser creation,
- model forward pass,
- supervised loss calculation,
- zero-gradient operation,
- backward pass,
- optimiser step,
- parameter update,
- Social Representation training,
- psychological retraining,
- factual retraining,
- group-conditioned processing,
- transformative processing,
- recurrent processing,
- held-out evaluation.

Supervision discovery and target construction are data-contract operations rather than model optimisation.

### Block 2 completion criterion

Block 2 is complete when:

- canonical supervision has been inspected,
- candidate social constructs have been audited,
- the Social Representation semantic boundary has been enforced,
- overlap with psychological and factual representations has been audited,
- every retained dimension has explicit semantic justification,
- Social Representation dimensionality has been resolved from the supervision,
- target values and independent masks have been constructed,
- provenance is complete,
- no dimension has been fabricated,
- canonical source records remain unchanged,
- the Social Representation target contract has been persisted and validated,
- optimisation remains blocked pending variability and loss-policy analysis.

Successful Block 2 completion establishes a semantically grounded Social Representation supervision contract.

It does not establish optimisation eligibility, predictive quality, generalisation or empirical validity.

The next block may proceed to:

**Social Target Availability, Variability, Activation and Loss-Contract Analysis.**

In [4]:
# =============================================================================
# Media AI — Notebook 07
# Block 2: Supplemental Social Supervision Schema,
#          Annotation Template and Target-Contract Preparation
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json
import math

import numpy as np
import pandas as pd

from googleapiclient.http import (
    MediaIoBaseDownload,
    MediaIoBaseUpload,
)


# =============================================================================
# Dependency checks
# =============================================================================

required_block_2_objects = [
    "NOTEBOOK_07_BLOCK_1_COMPLETE",
    "NOTEBOOK_07_BLOCK_1_VALID",
    "NOTEBOOK_07_DRIVE_SERVICE",
    "NOTEBOOK_07_HANDOVER",
    "NOTEBOOK_07_SENTENCE_IDS",
    "NOTEBOOK_07_SENTENCE_COUNT",
    "NOTEBOOK_07_ARTICLE_COUNT",
    "NOTEBOOK_07_INHERITED_NOTEBOOK_05_TO_06_HANDOVER",
    "NOTEBOOK_07_FACTUAL_DIMENSION_ORDER",
    "NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_SOCIAL_MASK_AWARE_SUPERVISION",
    "NOTEBOOK_07_SOCIAL_PARTIAL_SUPERVISION_ALLOWED",
    "NOTEBOOK_07_SOCIAL_MISSING_EQUALS_ZERO",
    "NOTEBOOK_07_SOCIAL_MISSING_EQUALS_NEGATIVE",
    "NOTEBOOK_07_SOCIAL_UNAVAILABLE_ENTERS_LOSS",
    "NOTEBOOK_07_SOCIAL_FABRICATED_DIMENSIONS_ALLOWED",
    "NOTEBOOK_07_READY_FOR_SOCIAL_SUPERVISION_AUDIT",
    "NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID",
]


missing_block_2_objects = [
    object_name
    for object_name
    in required_block_2_objects
    if object_name not in globals()
]


if missing_block_2_objects:

    raise NameError(
        "Notebook 07 Block 2 prerequisites are not initialised. "
        f"Missing: {missing_block_2_objects}"
    )


if not NOTEBOOK_07_BLOCK_1_COMPLETE:

    raise ValueError(
        "Notebook 07 Block 1 must be complete before Block 2."
    )


if not NOTEBOOK_07_BLOCK_1_VALID:

    raise ValueError(
        "Notebook 07 Block 1 must be valid before Block 2."
    )


if not NOTEBOOK_07_READY_FOR_SOCIAL_SUPERVISION_AUDIT:

    raise ValueError(
        "Notebook 07 is not ready for social-supervision discovery."
    )


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_07_BLOCK_2 = 2

NOTEBOOK_07_BLOCK_2_NAME = (
    "Supplemental Social Supervision Schema, "
    "Annotation Template and Target-Contract Preparation"
)

NOTEBOOK_07_BLOCK_2_VERSION = "2.0"

NOTEBOOK_07_SOCIAL_SCHEMA_VERSION = "1.0"

NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_VERSION = "1.0"

NOTEBOOK_07_SOCIAL_SCHEMA_FILENAME = (
    "notebook_07_social_supervision_schema.json"
)

NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_FILENAME = (
    "notebook_07_social_annotation_template.json"
)


BLOCK_2_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Execution boundary
# =============================================================================

NOTEBOOK_07_SOCIAL_MAPPING_PERFORMED = False

NOTEBOOK_07_SOCIAL_ANNOTATION_PERFORMED = False

NOTEBOOK_07_SOCIAL_TARGET_CONSTRUCTION_PERFORMED = False

NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED = False

NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED = False

NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_LOSS_CALCULATED = False

NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED = False

NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED = False

NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED = False

NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED = False

NOTEBOOK_07_PREVIOUS_NOTEBOOK_ARTEFACTS_MODIFIED = False


# =============================================================================
# Canonical source
# =============================================================================

NOTEBOOK_03_ACCEPTED_ANNOTATIONS_FILENAME = (
    "notebook_03_accepted_annotations.json"
)


# =============================================================================
# Drive helpers
# =============================================================================

def block_2_locate_drive_file(
    drive_service,
    filename,
):
    """
    Locate the most recently modified exact-name Google Drive file.
    """

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )


    response = (
        drive_service.files()
        .list(
            q=(
                f"name = '{escaped_filename}' "
                "and trashed = false"
            ),
            spaces=
                "drive",
            fields=(
                "files("
                "id,name,modifiedTime,parents,size,mimeType"
                ")"
            ),
            orderBy=
                "modifiedTime desc",
            pageSize=
                20,
        )
        .execute()
    )


    files = response.get(
        "files",
        [],
    )


    if not files:

        return None


    return files[0]


def block_2_download_drive_bytes(
    drive_service,
    file_id,
):
    """
    Download one Google Drive file and return raw bytes.
    """

    request = (
        drive_service.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Resolve canonical Notebook 03 annotation artefact
# =============================================================================

BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE = (
    block_2_locate_drive_file(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_03_ACCEPTED_ANNOTATIONS_FILENAME,
    )
)


if BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE is None:

    raise FileNotFoundError(
        "Canonical Notebook 03 accepted annotations could not be "
        "located in Google Drive."
    )


BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID = (
    BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE[
        "id"
    ]
)


BLOCK_2_CANONICAL_SOURCE_LOCATED = True


# =============================================================================
# Load canonical accepted annotations
# =============================================================================

BLOCK_2_CANONICAL_SOURCE_BYTES = (
    block_2_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID,
    )
)


if not BLOCK_2_CANONICAL_SOURCE_BYTES:

    raise RuntimeError(
        "Canonical Notebook 03 accepted-annotation artefact was empty."
    )


BLOCK_2_CANONICAL_SOURCE_PAYLOAD = json.loads(
    BLOCK_2_CANONICAL_SOURCE_BYTES.decode(
        "utf-8"
    )
)


# =============================================================================
# Resolve canonical records
# =============================================================================

def block_2_resolve_record_list(
    payload,
):
    """
    Resolve accepted annotation records from supported structures.
    """

    if isinstance(
        payload,
        list,
    ):

        return payload


    if not isinstance(
        payload,
        dict,
    ):

        raise TypeError(
            "Canonical supervision payload must be a list or dictionary."
        )


    candidate_keys = (
        "records",
        "accepted_annotations",
        "annotations",
        "accepted_records",
        "supervision_records",
    )


    for candidate_key in candidate_keys:

        candidate_value = payload.get(
            candidate_key
        )


        if isinstance(
            candidate_value,
            list,
        ):

            return candidate_value


    raise ValueError(
        "Could not resolve accepted supervision records from "
        "Notebook 03."
    )


NOTEBOOK_07_SOCIAL_SOURCE_RECORDS = (
    block_2_resolve_record_list(
        BLOCK_2_CANONICAL_SOURCE_PAYLOAD
    )
)


BLOCK_2_SOURCE_RECORD_COUNT = len(
    NOTEBOOK_07_SOCIAL_SOURCE_RECORDS
)


if (
    BLOCK_2_SOURCE_RECORD_COUNT
    != NOTEBOOK_07_SENTENCE_COUNT
):

    raise RuntimeError(
        "Canonical source-record count does not match Notebook 07 "
        "sentence identity."
    )


# =============================================================================
# Canonical sentence identity
# =============================================================================

BLOCK_2_SOURCE_SENTENCE_IDS = []


for (
    record_index,
    record,
) in enumerate(
    NOTEBOOK_07_SOCIAL_SOURCE_RECORDS
):

    identity = record.get(
        "identity",
        {},
    )


    sentence_id = identity.get(
        "sentence_id"
    )


    if not sentence_id:

        raise RuntimeError(
            "Canonical source record "
            f"{record_index} has no sentence_id."
        )


    BLOCK_2_SOURCE_SENTENCE_IDS.append(
        sentence_id
    )


BLOCK_2_SOURCE_SENTENCE_IDS_PRESENT = all(
    BLOCK_2_SOURCE_SENTENCE_IDS
)


BLOCK_2_SOURCE_SENTENCE_IDS_UNIQUE = (
    len(
        BLOCK_2_SOURCE_SENTENCE_IDS
    )
    ==
    len(
        set(
            BLOCK_2_SOURCE_SENTENCE_IDS
        )
    )
)


BLOCK_2_CANONICAL_ALIGNMENT_VALID = (
    set(
        BLOCK_2_SOURCE_SENTENCE_IDS
    )
    ==
    set(
        NOTEBOOK_07_SENTENCE_IDS
    )
)


if not all(
    [
        BLOCK_2_SOURCE_SENTENCE_IDS_PRESENT,
        BLOCK_2_SOURCE_SENTENCE_IDS_UNIQUE,
        BLOCK_2_CANONICAL_ALIGNMENT_VALID,
    ]
):

    raise RuntimeError(
        "Canonical Notebook 03 source records do not align with "
        "Notebook 07 sentence identity."
    )


# =============================================================================
# Discover currently available annotation keys
# =============================================================================

BLOCK_2_ALL_ANNOTATION_KEYS = set()


for record in (
    NOTEBOOK_07_SOCIAL_SOURCE_RECORDS
):

    annotations = record.get(
        "annotations",
        {},
    )


    if isinstance(
        annotations,
        dict,
    ):

        BLOCK_2_ALL_ANNOTATION_KEYS.update(
            annotations.keys()
        )


BLOCK_2_ALL_ANNOTATION_KEYS = tuple(
    sorted(
        BLOCK_2_ALL_ANNOTATION_KEYS
    )
)


# =============================================================================
# Canonical social-supervision discovery
# =============================================================================

BLOCK_2_SOCIAL_CONTAINER_CANDIDATES = {
    "social",
    "social_components",
    "social_annotations",
    "social_features",
    "social_dimensions",
    "social_representation",
    "sociological",
    "sociological_components",
    "sociological_annotations",
    "sociological_features",
}


BLOCK_2_DISCOVERED_CANONICAL_SOCIAL_KEYS = tuple(
    sorted(
        set(
            BLOCK_2_ALL_ANNOTATION_KEYS
        )
        &
        BLOCK_2_SOCIAL_CONTAINER_CANDIDATES
    )
)


BLOCK_2_CANONICAL_SOCIAL_SUPERVISION_AVAILABLE = (
    len(
        BLOCK_2_DISCOVERED_CANONICAL_SOCIAL_KEYS
    )
    > 0
)


# =============================================================================
# Existing-domain ownership audit
# =============================================================================

BLOCK_2_EXISTING_PSYCHOLOGICAL_FIELDS = {
    "annotation_confidence",
    "emotional_weight",
    "immediate_emotional_state",
    "reported_emotion",
}


BLOCK_2_EXISTING_FACTUAL_FIELDS = {
    "factological_components",
    "factological_weight",
}


BLOCK_2_FUTURE_TRANSFORMATIVE_FIELDS = {
    "transformative_emotion",
}


BLOCK_2_DISCOVERED_PSYCHOLOGICAL_FIELDS = tuple(
    sorted(
        set(
            BLOCK_2_ALL_ANNOTATION_KEYS
        )
        &
        BLOCK_2_EXISTING_PSYCHOLOGICAL_FIELDS
    )
)


BLOCK_2_DISCOVERED_FACTUAL_FIELDS = tuple(
    sorted(
        set(
            BLOCK_2_ALL_ANNOTATION_KEYS
        )
        &
        BLOCK_2_EXISTING_FACTUAL_FIELDS
    )
)


BLOCK_2_DISCOVERED_TRANSFORMATIVE_FIELDS = tuple(
    sorted(
        set(
            BLOCK_2_ALL_ANNOTATION_KEYS
        )
        &
        BLOCK_2_FUTURE_TRANSFORMATIVE_FIELDS
    )
)


BLOCK_2_EXISTING_FIELDS_REUSED_AS_SOCIAL = False


# =============================================================================
# Social Representation ontology
# =============================================================================
#
# These are Notebook 07 semantic dimensions.
#
# Defining the ontology does NOT create supervision values.
#
# Values remain unavailable until explicitly annotated.
# =============================================================================

NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS = [
    {
        "dimension_id":
            "S1",

        "dimension_index":
            0,

        "target_name":
            "interpersonal_cohesion",

        "definition":
            (
                "Degree to which the sentence expresses or describes "
                "cooperation, solidarity, trust, interpersonal inclusion, "
                "conflict, hostility or interpersonal exclusion."
            ),

        "target_family":
            "signed_cohesion",

        "minimum":
            -1.0,

        "maximum":
            1.0,

        "neutral_value":
            0.0,

        "neutral_requires_explicit_judgement":
            True,
    },

    {
        "dimension_id":
            "S2",

        "dimension_index":
            1,

        "target_name":
            "economic_cohesion",

        "definition":
            (
                "Degree to which the sentence expresses or describes "
                "economic inclusion, shared economic interest, equitable "
                "access, distributional cohesion, inequality, exclusion, "
                "economic conflict or materially divisive relations."
            ),

        "target_family":
            "signed_cohesion",

        "minimum":
            -1.0,

        "maximum":
            1.0,

        "neutral_value":
            0.0,

        "neutral_requires_explicit_judgement":
            True,
    },

    {
        "dimension_id":
            "S3",

        "dimension_index":
            2,

        "target_name":
            "political_cohesion",

        "definition":
            (
                "Degree to which the sentence expresses or describes "
                "political inclusion, legitimacy, institutional trust, "
                "participation, consensus, polarisation, political "
                "exclusion or political conflict."
            ),

        "target_family":
            "signed_cohesion",

        "minimum":
            -1.0,

        "maximum":
            1.0,

        "neutral_value":
            0.0,

        "neutral_requires_explicit_judgement":
            True,
    },

    {
        "dimension_id":
            "S4",

        "dimension_index":
            3,

        "target_name":
            "religious_cohesion",

        "definition":
            (
                "Degree to which the sentence expresses or describes "
                "religious tolerance, coexistence, inclusion, solidarity, "
                "religious exclusion, sectarian division or "
                "religiously framed conflict."
            ),

        "target_family":
            "signed_cohesion",

        "minimum":
            -1.0,

        "maximum":
            1.0,

        "neutral_value":
            0.0,

        "neutral_requires_explicit_judgement":
            True,
    },

    {
        "dimension_id":
            "S5",

        "dimension_index":
            4,

        "target_name":
            "group_collective_cohesion",

        "definition":
            (
                "Degree to which the sentence expresses or describes "
                "collective belonging, solidarity, shared identity, "
                "in-group/out-group alignment, fragmentation, exclusion "
                "or antagonism between social groups."
            ),

        "target_family":
            "signed_cohesion",

        "minimum":
            -1.0,

        "maximum":
            1.0,

        "neutral_value":
            0.0,

        "neutral_requires_explicit_judgement":
            True,
    },

    {
        "dimension_id":
            "S6",

        "dimension_index":
            5,

        "target_name":
            "institutional_role_relation",

        "definition":
            (
                "Presence and socially meaningful use of institutional, "
                "authority, organisational or recognised social-role "
                "relations in the sentence."
            ),

        "target_family":
            "binary_social_structure",

        "minimum":
            0.0,

        "maximum":
            1.0,

        "neutral_value":
            None,

        "neutral_requires_explicit_judgement":
            False,
    },

    {
        "dimension_id":
            "S7",

        "dimension_index":
            6,

        "target_name":
            "public_audience_relation",

        "definition":
            (
                "Presence of a socially meaningful relation to a public, "
                "audience, community, citizen body or broader social "
                "collective addressed, represented or affected by "
                "the sentence."
            ),

        "target_family":
            "binary_social_structure",

        "minimum":
            0.0,

        "maximum":
            1.0,

        "neutral_value":
            None,

        "neutral_requires_explicit_judgement":
            False,
    },
]


# =============================================================================
# Social Representation dimensionality
# =============================================================================

NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM = len(
    NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
)


NOTEBOOK_07_SOCIAL_DIMENSION_IDS = tuple(
    definition[
        "dimension_id"
    ]

    for definition
    in NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
)


NOTEBOOK_07_SOCIAL_DIMENSION_ORDER = tuple(
    definition[
        "target_name"
    ]

    for definition
    in NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
)


NOTEBOOK_07_SOCIAL_DIMENSION_MAP = {
    definition[
        "dimension_id"
    ]:
        definition[
            "target_name"
        ]

    for definition
    in NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
}


NOTEBOOK_07_SOCIAL_DIMENSION_INDEX = {
    definition[
        "target_name"
    ]:
        definition[
            "dimension_index"
        ]

    for definition
    in NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
}


# =============================================================================
# Ontology validation
# =============================================================================

BLOCK_2_SOCIAL_DIMENSION_IDS_UNIQUE = (
    len(
        NOTEBOOK_07_SOCIAL_DIMENSION_IDS
    )
    ==
    len(
        set(
            NOTEBOOK_07_SOCIAL_DIMENSION_IDS
        )
    )
)


BLOCK_2_SOCIAL_DIMENSION_NAMES_UNIQUE = (
    len(
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
    )
    ==
    len(
        set(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
        )
    )
)


BLOCK_2_SOCIAL_DIMENSION_INDICES_VALID = (
    [
        definition[
            "dimension_index"
        ]

        for definition
        in NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
    ]
    ==
    list(
        range(
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
        )
    )
)


BLOCK_2_SOCIAL_ONTOLOGY_VALID = all(
    [
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
        == 7,

        BLOCK_2_SOCIAL_DIMENSION_IDS_UNIQUE,

        BLOCK_2_SOCIAL_DIMENSION_NAMES_UNIQUE,

        BLOCK_2_SOCIAL_DIMENSION_INDICES_VALID,

        not NOTEBOOK_07_SOCIAL_FABRICATED_DIMENSIONS_ALLOWED,
    ]
)


if not BLOCK_2_SOCIAL_ONTOLOGY_VALID:

    raise RuntimeError(
        "Notebook 07 Social Representation ontology is invalid."
    )


# =============================================================================
# Annotation semantics
# =============================================================================
#
# signed_cohesion:
#
#   -1.0  explicitly divisive / conflictual / exclusionary
#    0.0  explicitly judged neutral or without directional cohesion
#   +1.0  explicitly cohesive / cooperative / inclusive
#
# Intermediate values are permitted where annotation evidence justifies them.
#
# Missing / unannotated values remain unavailable and must NOT become zero.
#
# binary_social_structure:
#
#    0.0  explicit observed absence
#    1.0  explicit observed presence
#
# Missing / unannotated remains unavailable.
# =============================================================================

NOTEBOOK_07_SOCIAL_SIGNED_SCALE = {
    "minimum":
        -1.0,

    "neutral":
        0.0,

    "maximum":
        1.0,

    "negative_semantics":
        (
            "divisive_conflictual_exclusionary"
        ),

    "neutral_semantics":
        (
            "explicitly_neutral_or_no_directional_cohesion"
        ),

    "positive_semantics":
        (
            "cohesive_cooperative_inclusive"
        ),

    "missing_is_neutral":
        False,
}


NOTEBOOK_07_SOCIAL_BINARY_SCALE = {
    "minimum":
        0.0,

    "maximum":
        1.0,

    "zero_semantics":
        "explicit_observed_absence",

    "one_semantics":
        "explicit_observed_presence",

    "missing_is_zero":
        False,
}


# =============================================================================
# Construct blank Notebook 07 supplemental annotation records
# =============================================================================
#
# IMPORTANT:
#
# No social label is generated automatically.
#
# Every target begins as unavailable / unannotated.
# =============================================================================

NOTEBOOK_07_SOCIAL_ANNOTATION_RECORDS = []


for (
    source_order,
    source_record,
) in enumerate(
    NOTEBOOK_07_SOCIAL_SOURCE_RECORDS
):

    identity = deepcopy(
        source_record.get(
            "identity",
            {},
        )
    )


    context = deepcopy(
        source_record.get(
            "context",
            {},
        )
    )


    sentence_id = identity.get(
        "sentence_id"
    )


    current_sentence = context.get(
        "current_sentence"
    )


    if not isinstance(
        current_sentence,
        str,
    ):

        current_sentence = ""


    social_annotations = {}


    for definition in (
        NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
    ):

        target_name = (
            definition[
                "target_name"
            ]
        )


        social_annotations[
            target_name
        ] = {
            "dimension_id":
                definition[
                    "dimension_id"
                ],

            "value":
                None,

            "value_state":
                "unannotated",

            "available":
                False,

            "evidence":
                None,

            "annotator_note":
                None,

            "target_family":
                definition[
                    "target_family"
                ],
        }


    NOTEBOOK_07_SOCIAL_ANNOTATION_RECORDS.append(
        {
            "record_type":
                "media_ai_notebook_07_social_annotation",

            "annotation_template_version":
                NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_VERSION,

            "source_order":
                int(
                    source_order
                ),

            "identity":
                identity,

            "context":
                {
                    "article_title":
                        context.get(
                            "article_title"
                        ),

                    "context_scope":
                        context.get(
                            "context_scope"
                        ),

                    "current_sentence":
                        current_sentence,

                    "preceding_context":
                        deepcopy(
                            context.get(
                                "preceding_context"
                            )
                        ),
                },

            "social_annotations":
                social_annotations,

            "annotation_complete":
                False,

            "original_notebook_03_record_modified":
                False,
        }
    )


# =============================================================================
# Annotation-template validation
# =============================================================================

BLOCK_2_SOCIAL_ANNOTATION_RECORD_COUNT = len(
    NOTEBOOK_07_SOCIAL_ANNOTATION_RECORDS
)


BLOCK_2_SOCIAL_ANNOTATION_RECORD_COUNT_VALID = (
    BLOCK_2_SOCIAL_ANNOTATION_RECORD_COUNT
    ==
    NOTEBOOK_07_SENTENCE_COUNT
)


BLOCK_2_SOCIAL_TEMPLATE_SENTENCE_IDS = [
    record[
        "identity"
    ][
        "sentence_id"
    ]

    for record
    in NOTEBOOK_07_SOCIAL_ANNOTATION_RECORDS
]


BLOCK_2_SOCIAL_TEMPLATE_IDS_UNIQUE = (
    len(
        BLOCK_2_SOCIAL_TEMPLATE_SENTENCE_IDS
    )
    ==
    len(
        set(
            BLOCK_2_SOCIAL_TEMPLATE_SENTENCE_IDS
        )
    )
)


BLOCK_2_SOCIAL_TEMPLATE_ALIGNMENT_VALID = (
    set(
        BLOCK_2_SOCIAL_TEMPLATE_SENTENCE_IDS
    )
    ==
    set(
        NOTEBOOK_07_SENTENCE_IDS
    )
)


BLOCK_2_ALL_SOCIAL_VALUES_UNANNOTATED = all(
    annotation[
        "value"
    ]
    is None

    and
    annotation[
        "value_state"
    ]
    ==
    "unannotated"

    and
    annotation[
        "available"
    ]
    is False

    for record
    in NOTEBOOK_07_SOCIAL_ANNOTATION_RECORDS

    for annotation
    in record[
        "social_annotations"
    ].values()
)


BLOCK_2_NO_AUTOMATIC_SOCIAL_LABELS = (
    BLOCK_2_ALL_SOCIAL_VALUES_UNANNOTATED
)


BLOCK_2_NO_CANONICAL_RECORD_MODIFICATION = all(
    record[
        "original_notebook_03_record_modified"
    ]
    is False

    for record
    in NOTEBOOK_07_SOCIAL_ANNOTATION_RECORDS
)


BLOCK_2_SOCIAL_TEMPLATE_VALID = all(
    [
        BLOCK_2_SOCIAL_ANNOTATION_RECORD_COUNT_VALID,
        BLOCK_2_SOCIAL_TEMPLATE_IDS_UNIQUE,
        BLOCK_2_SOCIAL_TEMPLATE_ALIGNMENT_VALID,
        BLOCK_2_ALL_SOCIAL_VALUES_UNANNOTATED,
        BLOCK_2_NO_AUTOMATIC_SOCIAL_LABELS,
        BLOCK_2_NO_CANONICAL_RECORD_MODIFICATION,
    ]
)


if not BLOCK_2_SOCIAL_TEMPLATE_VALID:

    raise RuntimeError(
        "Notebook 07 social annotation template is invalid."
    )


# =============================================================================
# Blank target-state matrices
# =============================================================================
#
# These matrices are created only as an audit of current availability.
#
# NaN = unavailable.
# False mask = unavailable.
#
# They are NOT an optimisation target yet.
# =============================================================================

BLOCK_2_SOCIAL_TARGET_MATRIX = np.full(
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    ),
    np.nan,
    dtype=np.float64,
)


BLOCK_2_SOCIAL_MASK_MATRIX = np.zeros(
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    ),
    dtype=bool,
)


BLOCK_2_SOCIAL_TARGET_MATRIX_SHAPE_VALID = (
    BLOCK_2_SOCIAL_TARGET_MATRIX.shape
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_2_SOCIAL_MASK_MATRIX_SHAPE_VALID = (
    BLOCK_2_SOCIAL_MASK_MATRIX.shape
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_2_AVAILABLE_SOCIAL_TARGET_ELEMENTS = int(
    BLOCK_2_SOCIAL_MASK_MATRIX.sum()
)


BLOCK_2_POSSIBLE_SOCIAL_TARGET_ELEMENTS = int(
    BLOCK_2_SOCIAL_MASK_MATRIX.size
)


BLOCK_2_CURRENT_SOCIAL_TARGET_COVERAGE = (
    BLOCK_2_AVAILABLE_SOCIAL_TARGET_ELEMENTS
    /
    BLOCK_2_POSSIBLE_SOCIAL_TARGET_ELEMENTS
)


# =============================================================================
# Social semantic state
# =============================================================================

NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM_RESOLVED = True

NOTEBOOK_07_SOCIAL_DIMENSION_ORDER_RESOLVED = True

NOTEBOOK_07_SOCIAL_SEMANTIC_MAPPING_RESOLVED = True

NOTEBOOK_07_SOCIAL_SCHEMA_DEFINED = True

NOTEBOOK_07_SOCIAL_SCHEMA_VALID = (
    BLOCK_2_SOCIAL_ONTOLOGY_VALID
)


# =============================================================================
# Social supervision state
# =============================================================================

NOTEBOOK_07_CANONICAL_SOCIAL_SUPERVISION_AVAILABLE = (
    BLOCK_2_CANONICAL_SOCIAL_SUPERVISION_AVAILABLE
)


NOTEBOOK_07_SUPPLEMENTAL_SOCIAL_SUPERVISION_REQUIRED = True

NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DEFINED = True

NOTEBOOK_07_SOCIAL_ANNOTATIONS_COMPLETE = False

NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_DEFINED = False

NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_VALID = False

NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_DEFINED = False

NOTEBOOK_07_SOCIAL_ACTIVATION_CONTRACT_RESOLVED = False

NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_RESOLVED = False

NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY = False

NOTEBOOK_07_SOCIAL_OPTIMISATION_READY = False


# =============================================================================
# Masking contract
# =============================================================================

BLOCK_2_MASKING_CONTRACT_VALID = all(
    [
        NOTEBOOK_07_SOCIAL_MASK_AWARE_SUPERVISION,
        NOTEBOOK_07_SOCIAL_PARTIAL_SUPERVISION_ALLOWED,
        not NOTEBOOK_07_SOCIAL_MISSING_EQUALS_ZERO,
        not NOTEBOOK_07_SOCIAL_MISSING_EQUALS_NEGATIVE,
        not NOTEBOOK_07_SOCIAL_UNAVAILABLE_ENTERS_LOSS,
        not NOTEBOOK_07_SOCIAL_FABRICATED_DIMENSIONS_ALLOWED,
    ]
)


if not BLOCK_2_MASKING_CONTRACT_VALID:

    raise RuntimeError(
        "Notebook 07 social masking contract is invalid."
    )


# =============================================================================
# Social supervision schema artefact
# =============================================================================

NOTEBOOK_07_SOCIAL_SCHEMA_ARTEFACT = {
    "artefact_type":
        "media_ai_social_supervision_schema",

    "artefact_version":
        NOTEBOOK_07_SOCIAL_SCHEMA_VERSION,

    "created_at_utc":
        BLOCK_2_EXECUTED_AT_UTC,

    "notebook":
        "07_social_representation",

    "formal_component_name":
        "Social Representation",

    "legacy_component_name":
        "Social Path",

    "canonical_source":
        {
            "filename":
                NOTEBOOK_03_ACCEPTED_ANNOTATIONS_FILENAME,

            "drive_file_id":
                BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID,

            "record_count":
                BLOCK_2_SOURCE_RECORD_COUNT,

            "canonical_social_supervision_available":
                bool(
                    NOTEBOOK_07_CANONICAL_SOCIAL_SUPERVISION_AVAILABLE
                ),

            "available_annotation_keys":
                list(
                    BLOCK_2_ALL_ANNOTATION_KEYS
                ),

            "canonical_source_modified":
                False,
        },

    "existing_domain_ownership":
        {
            "psychological_fields":
                list(
                    BLOCK_2_DISCOVERED_PSYCHOLOGICAL_FIELDS
                ),

            "factual_fields":
                list(
                    BLOCK_2_DISCOVERED_FACTUAL_FIELDS
                ),

            "transformative_fields":
                list(
                    BLOCK_2_DISCOVERED_TRANSFORMATIVE_FIELDS
                ),

            "existing_fields_reused_as_social":
                False,
        },

    "architecture":
        {
            "representation_dimension":
                NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

            "dimension_ids":
                list(
                    NOTEBOOK_07_SOCIAL_DIMENSION_IDS
                ),

            "dimension_order":
                list(
                    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
                ),

            "dimension_map":
                deepcopy(
                    NOTEBOOK_07_SOCIAL_DIMENSION_MAP
                ),
        },

    "dimension_definitions":
        deepcopy(
            NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
        ),

    "scale_contract":
        {
            "signed_cohesion":
                deepcopy(
                    NOTEBOOK_07_SOCIAL_SIGNED_SCALE
                ),

            "binary_social_structure":
                deepcopy(
                    NOTEBOOK_07_SOCIAL_BINARY_SCALE
                ),
        },

    "annotation_contract":
        {
            "automatic_labelling_allowed":
                False,

            "missing_equals_zero":
                False,

            "missing_equals_negative":
                False,

            "unannotated_enters_loss":
                False,

            "partial_supervision_allowed":
                True,

            "evidence_field_required_when_available":
                True,

            "future_context_allowed":
                False,

            "canonical_prediction_unit":
                "sentence",

            "preceding_context_allowed":
                True,
        },

    "methodological_boundary":
        {
            "ontology_defined":
                True,

            "social_values_annotated":
                False,

            "target_contract_defined":
                False,

            "objective_policy_defined":
                False,

            "optimisation_ready":
                False,

            "training_executed":
                False,

            "empirical_validity":
                False,
        },
}


# =============================================================================
# Social annotation-template artefact
# =============================================================================

NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_ARTEFACT = {
    "artefact_type":
        "media_ai_social_annotation_template",

    "artefact_version":
        NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_VERSION,

    "created_at_utc":
        BLOCK_2_EXECUTED_AT_UTC,

    "notebook":
        "07_social_representation",

    "schema_version":
        NOTEBOOK_07_SOCIAL_SCHEMA_VERSION,

    "schema_filename":
        NOTEBOOK_07_SOCIAL_SCHEMA_FILENAME,

    "source_artefact":
        {
            "filename":
                NOTEBOOK_03_ACCEPTED_ANNOTATIONS_FILENAME,

            "drive_file_id":
                BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID,

            "record_count":
                BLOCK_2_SOURCE_RECORD_COUNT,

            "source_modified":
                False,
        },

    "annotation_state":
        {
            "annotation_complete":
                False,

            "automatic_labels_generated":
                False,

            "available_target_elements":
                BLOCK_2_AVAILABLE_SOCIAL_TARGET_ELEMENTS,

            "possible_target_elements":
                BLOCK_2_POSSIBLE_SOCIAL_TARGET_ELEMENTS,

            "current_target_coverage":
                BLOCK_2_CURRENT_SOCIAL_TARGET_COVERAGE,
        },

    "dimension_ids":
        list(
            NOTEBOOK_07_SOCIAL_DIMENSION_IDS
        ),

    "dimension_order":
        list(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
        ),

    "records":
        deepcopy(
            NOTEBOOK_07_SOCIAL_ANNOTATION_RECORDS
        ),
}


# =============================================================================
# JSON helper
# =============================================================================

def block_2_json_default(
    value,
):

    if isinstance(
        value,
        np.generic,
    ):

        return value.item()


    if isinstance(
        value,
        np.ndarray,
    ):

        return value.tolist()


    if isinstance(
        value,
        set,
    ):

        return sorted(
            value
        )


    if isinstance(
        value,
        tuple,
    ):

        return list(
            value
        )


    raise TypeError(
        f"Object of type {type(value).__name__} "
        "is not JSON serialisable."
    )


# =============================================================================
# Serialise artefacts
# =============================================================================

NOTEBOOK_07_SOCIAL_SCHEMA_JSON = json.dumps(
    NOTEBOOK_07_SOCIAL_SCHEMA_ARTEFACT,
    indent=2,
    ensure_ascii=False,
    default=
        block_2_json_default,
)


NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_JSON = json.dumps(
    NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_ARTEFACT,
    indent=2,
    ensure_ascii=False,
    default=
        block_2_json_default,
)


BLOCK_2_SCHEMA_JSON_VALID = bool(
    NOTEBOOK_07_SOCIAL_SCHEMA_JSON
)


BLOCK_2_TEMPLATE_JSON_VALID = bool(
    NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_JSON
)


# =============================================================================
# Local persistence
# =============================================================================

with open(
    NOTEBOOK_07_SOCIAL_SCHEMA_FILENAME,
    "w",
    encoding="utf-8",
) as schema_file:

    schema_file.write(
        NOTEBOOK_07_SOCIAL_SCHEMA_JSON
    )


with open(
    NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_FILENAME,
    "w",
    encoding="utf-8",
) as template_file:

    template_file.write(
        NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_JSON
    )


BLOCK_2_LOCAL_SCHEMA_CREATED = True

BLOCK_2_LOCAL_TEMPLATE_CREATED = True


# =============================================================================
# Resolve Drive parent
# =============================================================================

BLOCK_2_HANDOVER_METADATA = (
    NOTEBOOK_07_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID,
        fields=
            "id,name,parents",
    )
    .execute()
)


BLOCK_2_PARENT_IDS = (
    BLOCK_2_HANDOVER_METADATA.get(
        "parents",
        [],
    )
)


# =============================================================================
# Drive persistence helper
# =============================================================================

def block_2_persist_json_to_drive(
    drive_service,
    filename,
    json_text,
    parent_ids=None,
):

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )


    search_response = (
        drive_service.files()
        .list(
            q=(
                f"name = '{escaped_filename}' "
                "and trashed = false"
            ),
            spaces=
                "drive",
            fields=
                "files(id,name,modifiedTime,parents)",
            orderBy=
                "modifiedTime desc",
            pageSize=
                20,
        )
        .execute()
    )


    matching_files = search_response.get(
        "files",
        [],
    )


    media = MediaIoBaseUpload(
        io.BytesIO(
            json_text.encode(
                "utf-8"
            )
        ),
        mimetype=
            "application/json",
        resumable=
            False,
    )


    if matching_files:

        drive_file = (
            drive_service.files()
            .update(
                fileId=
                    matching_files[
                        0
                    ][
                        "id"
                    ],
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "updated"


    else:

        metadata = {
            "name":
                filename
        }


        if parent_ids:

            metadata[
                "parents"
            ] = parent_ids


        drive_file = (
            drive_service.files()
            .create(
                body=
                    metadata,
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "created"


    return (
        drive_file,
        operation,
    )


# =============================================================================
# Persist schema
# =============================================================================

(
    NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_FILE,
    NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_OPERATION,
) = block_2_persist_json_to_drive(
    drive_service=
        NOTEBOOK_07_DRIVE_SERVICE,

    filename=
        NOTEBOOK_07_SOCIAL_SCHEMA_FILENAME,

    json_text=
        NOTEBOOK_07_SOCIAL_SCHEMA_JSON,

    parent_ids=
        BLOCK_2_PARENT_IDS,
)


NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_FILE_ID = (
    NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_FILE.get(
        "id"
    )
)


# =============================================================================
# Persist annotation template
# =============================================================================

(
    NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_FILE,
    NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_OPERATION,
) = block_2_persist_json_to_drive(
    drive_service=
        NOTEBOOK_07_DRIVE_SERVICE,

    filename=
        NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_FILENAME,

    json_text=
        NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_JSON,

    parent_ids=
        BLOCK_2_PARENT_IDS,
)


NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_FILE_ID = (
    NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_FILE.get(
        "id"
    )
)


BLOCK_2_SCHEMA_DRIVE_PERSISTED = bool(
    NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_FILE_ID
)


BLOCK_2_TEMPLATE_DRIVE_PERSISTED = bool(
    NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_FILE_ID
)


if not all(
    [
        BLOCK_2_SCHEMA_DRIVE_PERSISTED,
        BLOCK_2_TEMPLATE_DRIVE_PERSISTED,
    ]
):

    raise RuntimeError(
        "Notebook 07 social schema or annotation template "
        "was not persisted successfully."
    )


# =============================================================================
# Read-back validation
# =============================================================================

BLOCK_2_RELOADED_SCHEMA_BYTES = (
    block_2_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_FILE_ID,
    )
)


BLOCK_2_RELOADED_TEMPLATE_BYTES = (
    block_2_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_FILE_ID,
    )
)


BLOCK_2_RELOADED_SCHEMA = json.loads(
    BLOCK_2_RELOADED_SCHEMA_BYTES.decode(
        "utf-8"
    )
)


BLOCK_2_RELOADED_TEMPLATE = json.loads(
    BLOCK_2_RELOADED_TEMPLATE_BYTES.decode(
        "utf-8"
    )
)


BLOCK_2_SCHEMA_READBACK_VALID = all(
    [
        (
            BLOCK_2_RELOADED_SCHEMA.get(
                "artefact_type"
            )
            ==
            "media_ai_social_supervision_schema"
        ),

        (
            BLOCK_2_RELOADED_SCHEMA.get(
                "artefact_version"
            )
            ==
            NOTEBOOK_07_SOCIAL_SCHEMA_VERSION
        ),

        (
            BLOCK_2_RELOADED_SCHEMA[
                "architecture"
            ][
                "representation_dimension"
            ]
            ==
            7
        ),

        (
            tuple(
                BLOCK_2_RELOADED_SCHEMA[
                    "architecture"
                ][
                    "dimension_order"
                ]
            )
            ==
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
        ),

        (
            BLOCK_2_RELOADED_SCHEMA[
                "canonical_source"
            ][
                "canonical_source_modified"
            ]
            is False
        ),

        (
            BLOCK_2_RELOADED_SCHEMA[
                "methodological_boundary"
            ][
                "social_values_annotated"
            ]
            is False
        ),
    ]
)


BLOCK_2_TEMPLATE_READBACK_VALID = all(
    [
        (
            BLOCK_2_RELOADED_TEMPLATE.get(
                "artefact_type"
            )
            ==
            "media_ai_social_annotation_template"
        ),

        (
            BLOCK_2_RELOADED_TEMPLATE.get(
                "artefact_version"
            )
            ==
            NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_VERSION
        ),

        (
            len(
                BLOCK_2_RELOADED_TEMPLATE[
                    "records"
                ]
            )
            ==
            NOTEBOOK_07_SENTENCE_COUNT
        ),

        (
            BLOCK_2_RELOADED_TEMPLATE[
                "annotation_state"
            ][
                "automatic_labels_generated"
            ]
            is False
        ),

        (
            BLOCK_2_RELOADED_TEMPLATE[
                "annotation_state"
            ][
                "available_target_elements"
            ]
            == 0
        ),
    ]
)


if not all(
    [
        BLOCK_2_SCHEMA_READBACK_VALID,
        BLOCK_2_TEMPLATE_READBACK_VALID,
    ]
):

    raise RuntimeError(
        "Persisted Notebook 07 social schema or annotation template "
        "failed read-back validation."
    )


# =============================================================================
# Readiness state
# =============================================================================

NOTEBOOK_07_READY_FOR_SOCIAL_ANNOTATION = all(
    [
        NOTEBOOK_07_SOCIAL_SCHEMA_DEFINED,
        NOTEBOOK_07_SOCIAL_SCHEMA_VALID,
        NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DEFINED,
        BLOCK_2_SOCIAL_TEMPLATE_VALID,
        BLOCK_2_SCHEMA_READBACK_VALID,
        BLOCK_2_TEMPLATE_READBACK_VALID,
    ]
)


NOTEBOOK_07_READY_FOR_SOCIAL_TARGET_AVAILABILITY_AUDIT = False

NOTEBOOK_07_SOCIAL_OPTIMISATION_READY = False


# =============================================================================
# Schema audit table
# =============================================================================

BLOCK_2_SOCIAL_SCHEMA_ROWS = []


for definition in (
    NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
):

    BLOCK_2_SOCIAL_SCHEMA_ROWS.append(
        {
            "dimension_id":
                definition[
                    "dimension_id"
                ],

            "dimension_index":
                definition[
                    "dimension_index"
                ],

            "target_name":
                definition[
                    "target_name"
                ],

            "target_family":
                definition[
                    "target_family"
                ],

            "minimum":
                definition[
                    "minimum"
                ],

            "maximum":
                definition[
                    "maximum"
                ],

            "neutral_value":
                definition[
                    "neutral_value"
                ],

            "supervision_available":
                False,

            "fabricated_value":
                False,
        }
    )


BLOCK_2_SOCIAL_SCHEMA_AUDIT = pd.DataFrame(
    BLOCK_2_SOCIAL_SCHEMA_ROWS
)


# =============================================================================
# Canonical supervision audit table
# =============================================================================

BLOCK_2_CANONICAL_ANNOTATION_ROWS = []


for annotation_key in (
    BLOCK_2_ALL_ANNOTATION_KEYS
):

    if (
        annotation_key
        in
        BLOCK_2_EXISTING_PSYCHOLOGICAL_FIELDS
    ):

        ownership = (
            "psychological_or_emotional"
        )


    elif (
        annotation_key
        in
        BLOCK_2_EXISTING_FACTUAL_FIELDS
    ):

        ownership = (
            "factual"
        )


    elif (
        annotation_key
        in
        BLOCK_2_FUTURE_TRANSFORMATIVE_FIELDS
    ):

        ownership = (
            "transformative_reserved"
        )


    elif (
        annotation_key
        in
        BLOCK_2_SOCIAL_CONTAINER_CANDIDATES
    ):

        ownership = (
            "social"
        )


    else:

        ownership = (
            "unclassified"
        )


    BLOCK_2_CANONICAL_ANNOTATION_ROWS.append(
        {
            "annotation_key":
                annotation_key,

            "semantic_ownership":
                ownership,

            "reused_as_social":
                False,
        }
    )


BLOCK_2_CANONICAL_ANNOTATION_AUDIT = pd.DataFrame(
    BLOCK_2_CANONICAL_ANNOTATION_ROWS
)


# =============================================================================
# Final Block 2 validation
# =============================================================================

NOTEBOOK_07_BLOCK_2_ERRORS = []


block_2_validation_checks = {
    "canonical_source_not_located":
        BLOCK_2_CANONICAL_SOURCE_LOCATED,

    "source_sentence_ids_missing":
        BLOCK_2_SOURCE_SENTENCE_IDS_PRESENT,

    "source_sentence_ids_not_unique":
        BLOCK_2_SOURCE_SENTENCE_IDS_UNIQUE,

    "canonical_alignment_invalid":
        BLOCK_2_CANONICAL_ALIGNMENT_VALID,

    "social_ontology_invalid":
        BLOCK_2_SOCIAL_ONTOLOGY_VALID,

    "annotation_template_invalid":
        BLOCK_2_SOCIAL_TEMPLATE_VALID,

    "automatic_social_labels_detected":
        BLOCK_2_NO_AUTOMATIC_SOCIAL_LABELS,

    "canonical_records_modified":
        BLOCK_2_NO_CANONICAL_RECORD_MODIFICATION,

    "masking_contract_invalid":
        BLOCK_2_MASKING_CONTRACT_VALID,

    "schema_json_invalid":
        BLOCK_2_SCHEMA_JSON_VALID,

    "template_json_invalid":
        BLOCK_2_TEMPLATE_JSON_VALID,

    "local_schema_not_created":
        BLOCK_2_LOCAL_SCHEMA_CREATED,

    "local_template_not_created":
        BLOCK_2_LOCAL_TEMPLATE_CREATED,

    "schema_not_persisted":
        BLOCK_2_SCHEMA_DRIVE_PERSISTED,

    "template_not_persisted":
        BLOCK_2_TEMPLATE_DRIVE_PERSISTED,

    "schema_readback_invalid":
        BLOCK_2_SCHEMA_READBACK_VALID,

    "template_readback_invalid":
        BLOCK_2_TEMPLATE_READBACK_VALID,

    "social_annotation_not_ready":
        NOTEBOOK_07_READY_FOR_SOCIAL_ANNOTATION,
}


for (
    error_name,
    condition,
) in block_2_validation_checks.items():

    if not condition:

        NOTEBOOK_07_BLOCK_2_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited-operation validation
# =============================================================================

prohibited_block_2_operations = {
    "social_annotation_incorrectly_performed":
        NOTEBOOK_07_SOCIAL_ANNOTATION_PERFORMED,

    "social_target_construction_incorrectly_performed":
        NOTEBOOK_07_SOCIAL_TARGET_CONSTRUCTION_PERFORMED,

    "social_objectives_incorrectly_activated":
        NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED,

    "social_optimizer_incorrectly_created":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED,

    "social_forward_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED,

    "social_loss_incorrectly_calculated":
        NOTEBOOK_07_SOCIAL_LOSS_CALCULATED,

    "social_backward_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED,

    "social_parameter_update_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED,

    "social_training_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED,

    "psychological_training_incorrectly_executed":
        NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "factual_training_incorrectly_executed":
        NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED,

    "backbone_training_incorrectly_executed":
        NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED,

    "global_confluent_training_incorrectly_executed":
        NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED,

    "group_path_incorrectly_executed":
        NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_mechanism_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED,

    "transformative_weights_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED,

    "recurrent_mechanism_incorrectly_executed":
        NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for (
    error_name,
    operation_executed,
) in prohibited_block_2_operations.items():

    if operation_executed:

        NOTEBOOK_07_BLOCK_2_ERRORS.append(
            error_name
        )


NOTEBOOK_07_BLOCK_2_VALID = (
    len(
        NOTEBOOK_07_BLOCK_2_ERRORS
    )
    == 0
)


if not NOTEBOOK_07_BLOCK_2_VALID:

    raise RuntimeError(
        "Notebook 07 Block 2 social-supervision schema audit failed. "
        f"Errors: {NOTEBOOK_07_BLOCK_2_ERRORS}"
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_07_BLOCK_2_COMPLETE = True


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_07_BLOCK_2_SUMMARY = {
    "block":
        NOTEBOOK_07_BLOCK_2,

    "block_name":
        NOTEBOOK_07_BLOCK_2_NAME,

    "version":
        NOTEBOOK_07_BLOCK_2_VERSION,

    "executed_at_utc":
        BLOCK_2_EXECUTED_AT_UTC,

    "source_records":
        BLOCK_2_SOURCE_RECORD_COUNT,

    "canonical_alignment_valid":
        BLOCK_2_CANONICAL_ALIGNMENT_VALID,

    "available_annotation_keys":
        list(
            BLOCK_2_ALL_ANNOTATION_KEYS
        ),

    "canonical_social_supervision_available":
        NOTEBOOK_07_CANONICAL_SOCIAL_SUPERVISION_AVAILABLE,

    "supplemental_social_supervision_required":
        NOTEBOOK_07_SUPPLEMENTAL_SOCIAL_SUPERVISION_REQUIRED,

    "social_representation_dimension":
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

    "social_schema_defined":
        NOTEBOOK_07_SOCIAL_SCHEMA_DEFINED,

    "social_schema_valid":
        NOTEBOOK_07_SOCIAL_SCHEMA_VALID,

    "automatic_social_labels_generated":
        False,

    "available_target_elements":
        BLOCK_2_AVAILABLE_SOCIAL_TARGET_ELEMENTS,

    "possible_target_elements":
        BLOCK_2_POSSIBLE_SOCIAL_TARGET_ELEMENTS,

    "target_coverage":
        BLOCK_2_CURRENT_SOCIAL_TARGET_COVERAGE,

    "social_annotations_complete":
        NOTEBOOK_07_SOCIAL_ANNOTATIONS_COMPLETE,

    "social_target_contract_defined":
        NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_DEFINED,

    "social_optimisation_ready":
        NOTEBOOK_07_SOCIAL_OPTIMISATION_READY,

    "schema_filename":
        NOTEBOOK_07_SOCIAL_SCHEMA_FILENAME,

    "schema_drive_file_id":
        NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_FILE_ID,

    "template_filename":
        NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_FILENAME,

    "template_drive_file_id":
        NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_FILE_ID,

    "ready_for_social_annotation":
        NOTEBOOK_07_READY_FOR_SOCIAL_ANNOTATION,

    "empirical_validity":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_07_BLOCK_2_VALID,

    "block_complete":
        NOTEBOOK_07_BLOCK_2_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 07, Block 2: "
    "Supplemental Social Supervision Schema, "
    "Annotation Template and Target-Contract Preparation"
)

print("=" * 72)

print(
    f"Schema version               : "
    f"{NOTEBOOK_07_SOCIAL_SCHEMA_VERSION}"
)


print("-" * 72)

print(
    "Canonical supervision discovery"
)

print(
    f"Source artefact              : "
    f"{NOTEBOOK_03_ACCEPTED_ANNOTATIONS_FILENAME}"
)

print(
    f"Source Drive file ID         : "
    f"{BLOCK_2_NOTEBOOK_03_ACCEPTED_FILE_ID}"
)

print(
    f"Accepted source records      : "
    f"{BLOCK_2_SOURCE_RECORD_COUNT}"
)

print(
    f"Canonical alignment valid    : "
    f"{BLOCK_2_CANONICAL_ALIGNMENT_VALID}"
)

print(
    f"Available annotation keys    : "
    f"{list(BLOCK_2_ALL_ANNOTATION_KEYS)}"
)

print(
    f"Canonical social supervision : "
    f"{NOTEBOOK_07_CANONICAL_SOCIAL_SUPERVISION_AVAILABLE}"
)

print(
    f"Supplemental layer required  : "
    f"{NOTEBOOK_07_SUPPLEMENTAL_SOCIAL_SUPERVISION_REQUIRED}"
)


print("-" * 72)

print(
    "Existing semantic ownership"
)

print(
    f"Psychological/emotional      : "
    f"{list(BLOCK_2_DISCOVERED_PSYCHOLOGICAL_FIELDS)}"
)

print(
    f"Factual                      : "
    f"{list(BLOCK_2_DISCOVERED_FACTUAL_FIELDS)}"
)

print(
    f"Transformative reserved      : "
    f"{list(BLOCK_2_DISCOVERED_TRANSFORMATIVE_FIELDS)}"
)

print(
    f"Existing fields reused social: "
    f"{BLOCK_2_EXISTING_FIELDS_REUSED_AS_SOCIAL}"
)


print("-" * 72)

print(
    "Social Representation ontology"
)

print(
    f"Representation dimension     : "
    f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM}"
)

print(
    f"Dimension IDs unique         : "
    f"{BLOCK_2_SOCIAL_DIMENSION_IDS_UNIQUE}"
)

print(
    f"Dimension names unique       : "
    f"{BLOCK_2_SOCIAL_DIMENSION_NAMES_UNIQUE}"
)

print(
    f"Ontology valid               : "
    f"{BLOCK_2_SOCIAL_ONTOLOGY_VALID}"
)


for (
    dimension_id,
    dimension_name,
) in zip(
    NOTEBOOK_07_SOCIAL_DIMENSION_IDS,
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER,
):

    print(
        f"{dimension_id:<4}                         : "
        f"{dimension_name}"
    )


print("-" * 72)

print(
    "Supplemental annotation state"
)

print(
    f"Annotation records           : "
    f"{BLOCK_2_SOCIAL_ANNOTATION_RECORD_COUNT}"
)

print(
    f"Automatic labels generated   : "
    f"{False}"
)

print(
    f"All values unannotated       : "
    f"{BLOCK_2_ALL_SOCIAL_VALUES_UNANNOTATED}"
)

print(
    f"Available target elements    : "
    f"{BLOCK_2_AVAILABLE_SOCIAL_TARGET_ELEMENTS}"
)

print(
    f"Possible target elements     : "
    f"{BLOCK_2_POSSIBLE_SOCIAL_TARGET_ELEMENTS}"
)

print(
    f"Current target coverage      : "
    f"{BLOCK_2_CURRENT_SOCIAL_TARGET_COVERAGE:.4f}"
)

print(
    f"Annotations complete         : "
    f"{NOTEBOOK_07_SOCIAL_ANNOTATIONS_COMPLETE}"
)


print("-" * 72)

print(
    "Masking semantics"
)

print(
    f"Mask-aware supervision       : "
    f"{NOTEBOOK_07_SOCIAL_MASK_AWARE_SUPERVISION}"
)

print(
    f"Partial supervision allowed  : "
    f"{NOTEBOOK_07_SOCIAL_PARTIAL_SUPERVISION_ALLOWED}"
)

print(
    f"Missing = zero               : "
    f"{NOTEBOOK_07_SOCIAL_MISSING_EQUALS_ZERO}"
)

print(
    f"Missing = negative           : "
    f"{NOTEBOOK_07_SOCIAL_MISSING_EQUALS_NEGATIVE}"
)

print(
    f"Unavailable enters loss      : "
    f"{NOTEBOOK_07_SOCIAL_UNAVAILABLE_ENTERS_LOSS}"
)

print(
    f"Canonical source modified    : "
    f"{not BLOCK_2_NO_CANONICAL_RECORD_MODIFICATION}"
)


print("-" * 72)

print(
    "Persistent social schema"
)

print(
    f"Schema filename              : "
    f"{NOTEBOOK_07_SOCIAL_SCHEMA_FILENAME}"
)

print(
    f"Schema Drive operation       : "
    f"{NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_OPERATION}"
)

print(
    f"Schema Drive file ID         : "
    f"{NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_FILE_ID}"
)

print(
    f"Schema read-back valid       : "
    f"{BLOCK_2_SCHEMA_READBACK_VALID}"
)


print("-" * 72)

print(
    "Persistent annotation template"
)

print(
    f"Template filename            : "
    f"{NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_FILENAME}"
)

print(
    f"Template Drive operation     : "
    f"{NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_OPERATION}"
)

print(
    f"Template Drive file ID       : "
    f"{NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_FILE_ID}"
)

print(
    f"Template read-back valid     : "
    f"{BLOCK_2_TEMPLATE_READBACK_VALID}"
)


print("-" * 72)

print(
    "Readiness"
)

print(
    f"Social dimension resolved    : "
    f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM_RESOLVED}"
)

print(
    f"Semantic schema resolved     : "
    f"{NOTEBOOK_07_SOCIAL_SEMANTIC_MAPPING_RESOLVED}"
)

print(
    f"Ready for social annotation  : "
    f"{NOTEBOOK_07_READY_FOR_SOCIAL_ANNOTATION}"
)

print(
    f"Target contract defined      : "
    f"{NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_DEFINED}"
)

print(
    f"Optimisation ready           : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMISATION_READY}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Social annotation performed  : "
    f"{NOTEBOOK_07_SOCIAL_ANNOTATION_PERFORMED}"
)

print(
    f"Target construction performed: "
    f"{NOTEBOOK_07_SOCIAL_TARGET_CONSTRUCTION_PERFORMED}"
)

print(
    f"Objectives activated         : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED}"
)

print(
    f"Forward pass executed        : "
    f"{NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_07_SOCIAL_LOSS_CALCULATED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Social training executed     : "
    f"{NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Factual retraining           : "
    f"{NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative executed      : "
    f"{NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED}"
)

print(
    f"Transformative weights active: "
    f"{NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED}"
)

print(
    f"Recurrent executed           : "
    f"{NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED}"
)

print(
    f"Held-out evaluation executed : "
    f"{NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_07_BLOCK_2_VALID}"
)

print(
    f"Block 2 complete             : "
    f"{NOTEBOOK_07_BLOCK_2_COMPLETE}"
)


print("=" * 72)


print(
    "Notebook 07 supplemental Social Representation supervision schema "
    "and annotation template completed successfully."
)

print(
    "Canonical Notebook 03 supervision contains no explicit social "
    "annotation layer."
)

print(
    "Existing emotional, factual and transformative fields were not "
    "reinterpreted as social supervision."
)

print(
    "Notebook 03 remains unchanged and continues to provide canonical "
    "sentence identity and previously established supervision."
)

print(
    "Notebook 07 now defines a separate seven-dimensional Social "
    "Representation ontology."
)

print(
    "The ontology includes interpersonal, economic, political, religious "
    "and group/collective cohesion together with institutional-role and "
    "public/audience relational structure."
)

print(
    "Cohesion dimensions use a signed -1 to +1 annotation contract, "
    "while institutional-role and public/audience dimensions use explicit "
    "binary observed-presence or observed-absence supervision."
)

print(
    "Numerical zero is never substituted for missing supervision."
)

print(
    "No sentence-level social value has been generated automatically."
)


print(
    f"All {NOTEBOOK_07_SENTENCE_COUNT * NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM} "
    "possible sentence-dimension supervision elements remain explicitly "
    "unannotated and masked."
)

print(
    "A separate Notebook 07 social annotation template has been persisted "
    "for explicit annotation without modifying Notebook 03."
)

print(
    "The Social Representation semantic dimensionality is now resolved, "
    "but the supervised target contract remains intentionally undefined "
    "until explicit sentence-level annotation is completed."
)

print(
    "No social objective, optimiser, forward pass, loss calculation, "
    "backward pass, parameter update or social training has been executed."
)

print(
    "Successful Block 2 completion therefore establishes ontology and "
    "annotation readiness, not optimisation readiness or empirical validity."
)

print(
    "The next block may proceed to explicit Social Representation "
    "annotation, evidence audit and accepted social-supervision construction."
)

print("=" * 72)


# =============================================================================
# Display audits
# =============================================================================

display(
    BLOCK_2_CANONICAL_ANNOTATION_AUDIT
)


display(
    BLOCK_2_SOCIAL_SCHEMA_AUDIT
)

========================================================================
Media AI — Notebook 07, Block 2: Supplemental Social Supervision Schema, Annotation Template and Target-Contract Preparation
========================================================================
Schema version               : 1.0
------------------------------------------------------------------------
Canonical supervision discovery
Source artefact              : notebook_03_accepted_annotations.json
Source Drive file ID         : 1gYiCR-i_avGCwE5O9p921es8Mzbzhvyl
Accepted source records      : 54
Canonical alignment valid    : True
Available annotation keys    : ['annotation_confidence', 'emotional_weight', 'factological_components', 'factological_weight', 'immediate_emotional_state', 'reported_emotion', 'transformative_emotion']
Canonical social supervision : False
Supplemental layer required  : True
------------------------------------------------------------------------
Existing semantic ownership
Psychological/emotional      : ['annotation_confidence', 'emotional_weight', 'immediate_emotional_state', 'reported_emotion']
Factual                      : ['factological_components', 'factological_weight']
Transformative reserved      : ['transformative_emotion']
Existing fields reused social: False
------------------------------------------------------------------------
Social Representation ontology
Representation dimension     : 7
Dimension IDs unique         : True
Dimension names unique       : True
Ontology valid               : True
S1                           : interpersonal_cohesion
S2                           : economic_cohesion
S3                           : political_cohesion
S4                           : religious_cohesion
S5                           : group_collective_cohesion
S6                           : institutional_role_relation
S7                           : public_audience_relation
------------------------------------------------------------------------
Supplemental annotation state
Annotation records           : 54
Automatic labels generated   : False
All values unannotated       : True
Available target elements    : 0
Possible target elements     : 378
Current target coverage      : 0.0000
Annotations complete         : False
------------------------------------------------------------------------
Masking semantics
Mask-aware supervision       : True
Partial supervision allowed  : True
Missing = zero               : False
Missing = negative           : False
Unavailable enters loss      : False
Canonical source modified    : False
------------------------------------------------------------------------
Persistent social schema
Schema filename              : notebook_07_social_supervision_schema.json
Schema Drive operation       : updated
Schema Drive file ID         : 1rO-P7mI_5D3AFvNgpQoQbWNeFFKjFX9O
Schema read-back valid       : True
------------------------------------------------------------------------
Persistent annotation template
Template filename            : notebook_07_social_annotation_template.json
Template Drive operation     : updated
Template Drive file ID       : 1T0HxkdWBEUO1sx0vgb-BNBuAP0hNT_p0
Template read-back valid     : True
------------------------------------------------------------------------
Readiness
Social dimension resolved    : True
Semantic schema resolved     : True
Ready for social annotation  : True
Target contract defined      : False
Optimisation ready           : False
------------------------------------------------------------------------
Execution boundary
Social annotation performed  : False
Target construction performed: False
Objectives activated         : False
Optimiser created            : False
Forward pass executed        : False
Loss calculated              : False
Backward pass executed       : False
Parameter update executed    : False
Social training executed     : False
Psychological retraining     : False
Factual retraining           : False
Group-conditioned executed   : False
Transformative executed      : False
Transformative weights active: False
Recurrent executed           : False
Held-out evaluation executed : False
Empirical validity           : False
Block valid                  : True
Block 2 complete             : True
========================================================================
Notebook 07 supplemental Social Representation supervision schema and annotation template completed successfully.
Canonical Notebook 03 supervision contains no explicit social annotation layer.
Existing emotional, factual and transformative fields were not reinterpreted as social supervision.
Notebook 03 remains unchanged and continues to provide canonical sentence identity and previously established supervision.
Notebook 07 now defines a separate seven-dimensional Social Representation ontology.
The ontology includes interpersonal, economic, political, religious and group/collective cohesion together with institutional-role and public/audience relational structure.
Cohesion dimensions use a signed -1 to +1 annotation contract, while institutional-role and public/audience dimensions use explicit binary observed-presence or observed-absence supervision.
Numerical zero is never substituted for missing supervision.
No sentence-level social value has been generated automatically.
All 378 possible sentence-dimension supervision elements remain explicitly unannotated and masked.
A separate Notebook 07 social annotation template has been persisted for explicit annotation without modifying Notebook 03.
The Social Representation semantic dimensionality is now resolved, but the supervised target contract remains intentionally undefined until explicit sentence-level annotation is completed.
No social objective, optimiser, forward pass, loss calculation, backward pass, parameter update or social training has been executed.
Successful Block 2 completion therefore establishes ontology and annotation readiness, not optimisation readiness or empirical validity.
The next block may proceed to explicit Social Representation annotation, evidence audit and accepted social-supervision construction.
========================================================================

              annotation_key          semantic_ownership  reused_as_social
0      annotation_confidence  psychological_or_emotional             False
1           emotional_weight  psychological_or_emotional             False
2    factological_components                     factual             False
3        factological_weight                     factual             False
4  immediate_emotional_state  psychological_or_emotional             False
5           reported_emotion  psychological_or_emotional             False
6     transformative_emotion     transformative_reserved             False

,dimension_id,dimension_index,target_name,target_family,minimum,maximum,neutral_value,supervision_available,fabricated_value
0,S1,0,interpersonal_cohesion,signed_cohesion,-1.0,1.0,0.0,False,False
1,S2,1,economic_cohesion,signed_cohesion,-1.0,1.0,0.0,False,False
2,S3,2,political_cohesion,signed_cohesion,-1.0,1.0,0.0,False,False
3,S4,3,religious_cohesion,signed_cohesion,-1.0,1.0,0.0,False,False
4,S5,4,group_collective_cohesion,signed_cohesion,-1.0,1.0,0.0,False,False
5,S6,5,institutional_role_relation,binary_social_structure,0.0,1.0,NaN,False,False
6,S7,6,public_audience_relation,binary_social_structure,0.0,1.0,NaN,False,False

## Block 3 — Social Representation Annotation, Evidence Audit and Accepted Supervision Construction

This block converts the Social Representation ontology and blank annotation template established in Block 2 into explicit sentence-level supervision.

The block does not train the Social Representation.

Its purpose is to annotate only those social dimensions that are supported by the canonical sentence and permitted preceding context, preserve unavailable dimensions through masking, record evidence for every accepted value, validate annotation consistency and construct a persistent accepted Social Representation supervision artefact.

### Annotation source

Block 3 begins from the persisted Notebook 07 annotation template:

`notebook_07_social_annotation_template.json`

The template preserves the canonical 16 sentence identities and the seven-dimensional Social Representation ontology defined in Block 2.

Notebook 03 remains unchanged.

Block 3 therefore adds a separate Notebook 07 social-supervision layer rather than modifying any previous annotation artefact.

### Social Representation dimensions

The annotation contract covers seven dimensions:

- **S1 — interpersonal cohesion**
- **S2 — economic cohesion**
- **S3 — political cohesion**
- **S4 — religious cohesion**
- **S5 — group/collective cohesion**
- **S6 — institutional-role relation**
- **S7 — public/audience relation**

The dimensionality is already fixed by Block 2.

Block 3 assigns supervision values only where textual evidence supports them.

### Cohesion dimensions

S1–S5 use a signed cohesion scale.

The conceptual endpoints are:

- `-1.0` — explicitly divisive, conflictual or exclusionary,
- `0.0` — explicitly judged neutral or without directional cohesion,
- `+1.0` — explicitly cohesive, cooperative or inclusive.

Intermediate values may be used only when the annotation contract supports a justified graded judgement.

A value of `0.0` is an explicit annotation.

It must not be used as a substitute for missing supervision.

Therefore:

**neutral ≠ unavailable**

and:

**unavailable ≠ negative**

### Structural social dimensions

S6 and S7 use explicit binary supervision.

For:

**S6 — institutional-role relation**

- `1.0` indicates observed socially meaningful institutional, organisational, authority or role structure,
- `0.0` indicates explicit observed absence.

For:

**S7 — public/audience relation**

- `1.0` indicates an observed socially meaningful relation to a public, audience, citizen body, community or broader collective,
- `0.0` indicates explicit observed absence.

Missing or unresolved cases remain unavailable rather than being converted to zero.

### Evidence requirement

Every available social annotation must be supported by explicit evidence.

The evidence should identify the text that justifies the annotation without importing unsupported interpretation.

Evidence may come from:

- the current sentence,
- permitted preceding context when required to resolve reference or continuity.

Future context remains prohibited.

If the social meaning cannot be supported from the permitted text, the target remains unavailable.

### Annotation principle

Block 3 must prefer masking over speculation.

A social value should be assigned only when the available text supports the corresponding dimension sufficiently.

The block must not infer:

- political meaning from any institutional mention automatically,
- economic meaning from any numerical or material reference automatically,
- religious meaning from identity language unless the religious dimension is actually supported,
- interpersonal cohesion from any mention of multiple people automatically,
- group cohesion from every collective noun automatically,
- public/audience relation from generic third-person reference automatically.

Semantic relevance must be demonstrated rather than assumed.

### Separation from existing representations

Block 3 must preserve the semantic ownership established in earlier notebooks.

Psychological or emotional supervision must not be converted into Social Representation values merely because emotions concern other people.

Factual supervision must not be duplicated as social supervision merely because a sentence describes an event, actor or institution.

Transformative-emotion supervision remains reserved for the Transformative Mechanism and must not be reused as social supervision.

The Social Representation should capture genuinely social structure or cohesion, not re-label existing dimensions.

### Context-assisted sentence annotation

The canonical annotation unit remains the sentence.

The current sentence provides the primary annotation evidence.

Preceding context may be used only where required to resolve:

- pronouns,
- actor identity,
- institutional identity,
- group membership,
- relation continuity,
- public or audience reference.

Future sentences must not be used.

This preserves the causal boundary established in the preceding notebooks.

### Partial supervision

A sentence does not need to receive values for all seven Social Representation dimensions.

Each dimension has an independent availability state.

A sentence may therefore contain:

- several available social targets,
- one available target,
- no available social target.

Unavailable dimensions remain masked and do not later enter the optimisation loss.

This preserves the mask-aware supervision policy established in Blocks 1 and 2.

### Annotation acceptance

An annotation is accepted only when:

- the sentence identity matches the canonical contract,
- the target dimension is valid,
- the value falls within the permitted range,
- the value state is compatible with availability,
- available values contain supporting evidence,
- unavailable values do not enter the target matrix,
- no automatic or fabricated value has been introduced.

Invalid or unresolved annotations remain unavailable rather than being coerced into the target space.

### Annotation completeness

Block 3 distinguishes between:

- template completeness,
- annotation coverage,
- annotation acceptance.

The annotation artefact may be structurally complete even when some Social Representation dimensions remain unavailable.

Full 112-element coverage is not required.

The relevant criterion is that every sentence-dimension element has an explicit state:

- available with accepted value,
- unavailable with documented reason.

### Target construction

After annotation acceptance, Block 3 constructs the Social Representation target matrix:

`16 × 7`

with a corresponding Boolean mask matrix of the same shape.

Observed targets populate the matrix.

Unavailable targets remain represented as missing values and are masked.

The target matrix is therefore constructed only from accepted supervision.

### Coverage audit

The block reports:

- total available target elements,
- total possible target elements,
- aggregate coverage,
- available counts per dimension,
- sentence-level supervision coverage,
- fully supervised sentences,
- partially supervised sentences,
- sentences with no available social supervision.

Coverage is descriptive.

High coverage does not imply useful optimisation supervision.

### Value and range validation

For S1–S5, every available value must lie within:

`[-1.0, +1.0]`

For S6–S7, every available value must be either:

`0.0` or `1.0`

Non-finite values are invalid.

Unavailable values must not be treated as observed numerical targets.

### Evidence audit

The block must retain evidence provenance for each available annotation.

The accepted supervision artefact should allow each target value to be traced back to:

- sentence identity,
- target dimension,
- value,
- value state,
- evidence,
- optional annotation note.

This makes the Social Representation supervision auditable independently of later training.

### Persistent accepted supervision artefact

The accepted social supervision should be persisted separately from:

- Notebook 03 annotations,
- the Block 2 schema,
- the Block 2 blank annotation template.

A suitable artefact is:

`notebook_07_accepted_social_supervision.json`

The artefact should contain:

- schema version,
- canonical source reference,
- annotation-template reference,
- dimension definitions,
- accepted sentence-level annotations,
- target values,
- availability masks,
- evidence provenance,
- coverage statistics,
- execution boundary.

The persisted artefact must be validated by read-back.

### Optimisation boundary

Block 3 does not determine which Social Representation dimensions are suitable for training.

After annotation, some dimensions may have:

- zero variance,
- few available observations,
- strong imbalance,
- insufficient positive or negative support,
- inadequate signed-value variation.

Those questions belong to the next block.

Successful annotation therefore does not imply optimisation eligibility.

### Architectural boundary

Block 3 does not modify or retrain:

- contextual representation,
- backbone,
- mandatory global confluent representation,
- Psychological Representation,
- Factual Representation.

The optional group-conditioned path remains deferred to Notebook 10.

The Transformative Mechanism remains deferred to Notebook 08.

Transformative Weights and recurrent mechanisms remain deferred to Notebook 09.

### Execution boundary

Block 3 performs no:

- Social Representation objective activation,
- optimiser creation,
- model forward pass,
- supervised loss calculation,
- zero-gradient operation,
- backward pass,
- optimiser step,
- parameter update,
- Social Representation training,
- psychological retraining,
- factual retraining,
- group-conditioned processing,
- transformative processing,
- recurrent processing,
- held-out evaluation.

Annotation and target construction remain supervision-contract operations rather than model optimisation.

### Block 3 completion criterion

Block 3 is complete when:

- the persisted Block 2 annotation template has been restored,
- all 16 canonical sentences remain aligned,
- every Social Representation dimension has an explicit annotation state,
- only evidence-supported values are accepted,
- unavailable targets remain masked,
- target ranges are validated,
- no automatic social labels are introduced,
- no previous notebook artefact is modified,
- the `16 × 7` target and mask matrices are constructed from accepted supervision,
- coverage and evidence audits are complete,
- the accepted social-supervision artefact is persisted and verified by read-back,
- optimisation remains blocked pending variability and loss-policy analysis.

Successful Block 3 completion establishes an accepted and auditable Social Representation supervision dataset.

It does not establish training eligibility, predictive quality, generalisation or empirical validity.

The next block may proceed to:

**Social Target Availability, Variability, Activation and Loss-Contract Analysis.**

In [10]:
# =============================================================================
# Media AI — Notebook 07
# Block 3: Social Representation Annotation, Evidence Audit
#          and Accepted Supervision Construction
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json
import math
import os

import numpy as np
import pandas as pd

from googleapiclient.http import (
    MediaIoBaseDownload,
    MediaIoBaseUpload,
)


# =============================================================================
# Dependency checks
# =============================================================================

required_block_3_objects = [
    "NOTEBOOK_07_BLOCK_1_COMPLETE",
    "NOTEBOOK_07_BLOCK_1_VALID",
    "NOTEBOOK_07_BLOCK_2_COMPLETE",
    "NOTEBOOK_07_BLOCK_2_VALID",
    "NOTEBOOK_07_DRIVE_SERVICE",
    "NOTEBOOK_07_SENTENCE_IDS",
    "NOTEBOOK_07_SENTENCE_COUNT",
    "NOTEBOOK_07_ARTICLE_COUNT",
    "NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_SOCIAL_DIMENSION_IDS",
    "NOTEBOOK_07_SOCIAL_DIMENSION_ORDER",
    "NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS",
    "NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_FILE_ID",
    "NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_FILE_ID",
    "NOTEBOOK_07_SOCIAL_SCHEMA_FILENAME",
    "NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_FILENAME",
    "NOTEBOOK_07_READY_FOR_SOCIAL_ANNOTATION",
    "NOTEBOOK_07_SOCIAL_MASK_AWARE_SUPERVISION",
    "NOTEBOOK_07_SOCIAL_PARTIAL_SUPERVISION_ALLOWED",
    "NOTEBOOK_07_SOCIAL_MISSING_EQUALS_ZERO",
    "NOTEBOOK_07_SOCIAL_MISSING_EQUALS_NEGATIVE",
    "NOTEBOOK_07_SOCIAL_UNAVAILABLE_ENTERS_LOSS",
    "NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID",
]


missing_block_3_objects = [
    object_name
    for object_name
    in required_block_3_objects
    if object_name not in globals()
]


if missing_block_3_objects:

    raise NameError(
        "Notebook 07 Block 3 prerequisites are not initialised. "
        f"Missing: {missing_block_3_objects}"
    )


if not NOTEBOOK_07_BLOCK_1_COMPLETE:

    raise ValueError(
        "Notebook 07 Block 1 must be complete before Block 3."
    )


if not NOTEBOOK_07_BLOCK_1_VALID:

    raise ValueError(
        "Notebook 07 Block 1 must be valid before Block 3."
    )


if not NOTEBOOK_07_BLOCK_2_COMPLETE:

    raise ValueError(
        "Notebook 07 Block 2 must be complete before Block 3."
    )


if not NOTEBOOK_07_BLOCK_2_VALID:

    raise ValueError(
        "Notebook 07 Block 2 must be valid before Block 3."
    )


if not NOTEBOOK_07_READY_FOR_SOCIAL_ANNOTATION:

    raise ValueError(
        "Notebook 07 is not ready for explicit social annotation."
    )


if NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM != 7:

    raise ValueError(
        "Block 3 requires the validated seven-dimensional "
        "Social Representation ontology."
    )


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_07_BLOCK_3 = 3

NOTEBOOK_07_BLOCK_3_NAME = (
    "Social Representation Annotation, Evidence Audit "
    "and Accepted Supervision Construction"
)

NOTEBOOK_07_BLOCK_3_VERSION = "1.2"

NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_VERSION = "1.2"

NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_FILENAME = (
    "notebook_07_accepted_social_supervision.json"
)


BLOCK_3_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Execution boundary
# =============================================================================

NOTEBOOK_07_SOCIAL_ANNOTATION_PERFORMED = False

NOTEBOOK_07_SOCIAL_TARGET_CONSTRUCTION_PERFORMED = False

NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED = False

NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED = False

NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_LOSS_CALCULATED = False

NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED = False

NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED = False

NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED = False

NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED = False

NOTEBOOK_07_PREVIOUS_NOTEBOOK_ARTEFACTS_MODIFIED = False


# =============================================================================
# Drive download helper
# =============================================================================

def block_3_download_drive_bytes(
    drive_service,
    file_id,
):
    """
    Download one Google Drive file and return raw bytes.
    """

    request = (
        drive_service.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Reload persisted Block 2 schema
# =============================================================================

BLOCK_3_SCHEMA_BYTES = (
    block_3_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_FILE_ID,
    )
)


BLOCK_3_TEMPLATE_BYTES = (
    block_3_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_FILE_ID,
    )
)


if not BLOCK_3_SCHEMA_BYTES:

    raise RuntimeError(
        "Persisted Notebook 07 social schema was empty."
    )


if not BLOCK_3_TEMPLATE_BYTES:

    raise RuntimeError(
        "Persisted Notebook 07 annotation template was empty."
    )


BLOCK_3_SCHEMA = json.loads(
    BLOCK_3_SCHEMA_BYTES.decode(
        "utf-8"
    )
)


BLOCK_3_TEMPLATE = json.loads(
    BLOCK_3_TEMPLATE_BYTES.decode(
        "utf-8"
    )
)


# =============================================================================
# Persisted schema validation
# =============================================================================

BLOCK_3_SCHEMA_TYPE_VALID = (
    BLOCK_3_SCHEMA.get(
        "artefact_type"
    )
    ==
    "media_ai_social_supervision_schema"
)


BLOCK_3_SCHEMA_DIMENSION_VALID = (
    BLOCK_3_SCHEMA[
        "architecture"
    ][
        "representation_dimension"
    ]
    == 7
)


BLOCK_3_SCHEMA_ORDER_VALID = (
    tuple(
        BLOCK_3_SCHEMA[
            "architecture"
        ][
            "dimension_order"
        ]
    )
    ==
    tuple(
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
    )
)


BLOCK_3_TEMPLATE_TYPE_VALID = (
    BLOCK_3_TEMPLATE.get(
        "artefact_type"
    )
    ==
    "media_ai_social_annotation_template"
)


BLOCK_3_TEMPLATE_RECORD_COUNT_VALID = (
    len(
        BLOCK_3_TEMPLATE[
            "records"
        ]
    )
    ==
    NOTEBOOK_07_SENTENCE_COUNT
)


BLOCK_3_TEMPLATE_AUTOMATIC_LABELS_FALSE = (
    BLOCK_3_TEMPLATE[
        "annotation_state"
    ][
        "automatic_labels_generated"
    ]
    is False
)


BLOCK_3_PERSISTED_INPUT_CONTRACT_VALID = all(
    [
        BLOCK_3_SCHEMA_TYPE_VALID,
        BLOCK_3_SCHEMA_DIMENSION_VALID,
        BLOCK_3_SCHEMA_ORDER_VALID,
        BLOCK_3_TEMPLATE_TYPE_VALID,
        BLOCK_3_TEMPLATE_RECORD_COUNT_VALID,
        BLOCK_3_TEMPLATE_AUTOMATIC_LABELS_FALSE,
    ]
)


if not BLOCK_3_PERSISTED_INPUT_CONTRACT_VALID:

    raise RuntimeError(
        "Persisted Block 2 social schema/template contract is invalid."
    )


# =============================================================================
# Canonical template records
# =============================================================================

BLOCK_3_TEMPLATE_RECORDS = deepcopy(
    BLOCK_3_TEMPLATE[
        "records"
    ]
)


BLOCK_3_TEMPLATE_SENTENCE_IDS = [
    record[
        "identity"
    ][
        "sentence_id"
    ]

    for record
    in BLOCK_3_TEMPLATE_RECORDS
]


BLOCK_3_TEMPLATE_SENTENCE_IDS_UNIQUE = (
    len(
        BLOCK_3_TEMPLATE_SENTENCE_IDS
    )
    ==
    len(
        set(
            BLOCK_3_TEMPLATE_SENTENCE_IDS
        )
    )
)


BLOCK_3_TEMPLATE_ALIGNMENT_VALID = (
    set(
        BLOCK_3_TEMPLATE_SENTENCE_IDS
    )
    ==
    set(
        NOTEBOOK_07_SENTENCE_IDS
    )
)


if not all(
    [
        BLOCK_3_TEMPLATE_SENTENCE_IDS_UNIQUE,
        BLOCK_3_TEMPLATE_ALIGNMENT_VALID,
    ]
):

    raise RuntimeError(
        "Persisted annotation template is not aligned with "
        "Notebook 07 canonical sentence identity."
    )


# =============================================================================
# Annotation worksheet
# =============================================================================
#
# The worksheet is always reconstructed from the persisted blank template.
#
# It is informational only and does NOT create labels.
# =============================================================================

BLOCK_3_WORKSHEET_ROWS = []


for (
    source_order,
    record,
) in enumerate(
    BLOCK_3_TEMPLATE_RECORDS
):

    identity = record.get(
        "identity",
        {},
    )


    context = record.get(
        "context",
        {},
    )


    preceding_context = context.get(
        "preceding_context"
    )


    if isinstance(
        preceding_context,
        list,
    ):

        preceding_context_display = " ".join(
            str(
                item
            )

            for item
            in preceding_context
        )


    elif preceding_context is None:

        preceding_context_display = ""


    else:

        preceding_context_display = str(
            preceding_context
        )


    BLOCK_3_WORKSHEET_ROWS.append(
        {
            "source_order":
                source_order,

            "sentence_id":
                identity.get(
                    "sentence_id"
                ),

            "preceding_context":
                preceding_context_display,

            "current_sentence":
                context.get(
                    "current_sentence"
                ),

            "S1_interpersonal":
                None,

            "S2_economic":
                None,

            "S3_political":
                None,

            "S4_religious":
                None,

            "S5_group_collective":
                None,

            "S6_institutional_role":
                None,

            "S7_public_audience":
                None,
        }
    )


BLOCK_3_ANNOTATION_WORKSHEET = pd.DataFrame(
    BLOCK_3_WORKSHEET_ROWS
)



# =============================================================================
# Controlled supplemental social LLM supervision
# =============================================================================
#
# Block 3 may supplement existing human / accepted supervision with controlled
# machine supervision for canonical sentences that have not yet been reviewed.
#
# Methodological boundary:
#
# - human supervision always takes precedence;
# - already accepted LLM supervision is reused;
# - only still-unsupervised canonical sentences are eligible for a new request;
# - complete articles are the external request unit;
# - sentence-level social annotations remain the supervision unit;
# - every observed value requires textual evidence;
# - unavailable values remain unavailable and masked;
# - provider output is parsed and validated locally before it enters the target
#   matrix;
# - machine supervision is never represented as human-reviewed reference data;
# - raw provider responses are persisted independently for resume protection.
# =============================================================================

NOTEBOOK_07_RUN_SOCIAL_LLM_SUPERVISION = True

NOTEBOOK_07_SOCIAL_LLM_PROVIDER = "google"

NOTEBOOK_07_SOCIAL_LLM_MODEL = "gemini-3.6-flash"

NOTEBOOK_07_REQUIRE_FREE_SOCIAL_SUPERVISION = True

NOTEBOOK_07_ALLOW_PAID_SOCIAL_API_USAGE = False

NOTEBOOK_07_ALLOW_AUTOMATIC_PAID_SOCIAL_FALLBACK = False

NOTEBOOK_07_MAX_SOCIAL_LLM_REQUESTS_PER_RUN = 2

NOTEBOOK_07_MAX_SOCIAL_LLM_REQUESTS_PER_DAY = 5

NOTEBOOK_07_SOCIAL_LLM_SUPERVISOR_ID = "social_supervisor_01"

NOTEBOOK_07_SOCIAL_LLM_RAW_STORE_VERSION = "1.0"

NOTEBOOK_07_SOCIAL_LLM_RAW_STORE_FILENAME = (
    "notebook_07_raw_social_llm_supervision.json"
)


# =============================================================================
# Google GenAI SDK and credential readiness
# =============================================================================

try:

    from google import genai

    BLOCK_3_GOOGLE_GENAI_AVAILABLE = True

except ImportError:

    genai = None

    BLOCK_3_GOOGLE_GENAI_AVAILABLE = False


BLOCK_3_GEMINI_API_KEY = None

BLOCK_3_GEMINI_CREDENTIAL_READY = False

BLOCK_3_GEMINI_SECRET_STATUS = "UNAVAILABLE"


try:

    from google.colab import userdata

    BLOCK_3_GEMINI_API_KEY = userdata.get(
        "GEMINI_API_KEY"
    )

    BLOCK_3_GEMINI_CREDENTIAL_READY = bool(
        isinstance(
            BLOCK_3_GEMINI_API_KEY,
            str,
        )
        and
        BLOCK_3_GEMINI_API_KEY.strip()
    )

    BLOCK_3_GEMINI_SECRET_STATUS = (
        "AVAILABLE"
        if BLOCK_3_GEMINI_CREDENTIAL_READY
        else "UNAVAILABLE"
    )

except Exception:

    BLOCK_3_GEMINI_API_KEY = None

    BLOCK_3_GEMINI_CREDENTIAL_READY = False

    BLOCK_3_GEMINI_SECRET_STATUS = "UNAVAILABLE"


BLOCK_3_FREE_TIER_APPROVED_SOCIAL_MODELS = {
    "gemini-3.6-flash",
}


BLOCK_3_SOCIAL_LLM_COST_POLICY_READY = all(
    [
        NOTEBOOK_07_REQUIRE_FREE_SOCIAL_SUPERVISION,
        not NOTEBOOK_07_ALLOW_PAID_SOCIAL_API_USAGE,
        not NOTEBOOK_07_ALLOW_AUTOMATIC_PAID_SOCIAL_FALLBACK,
        NOTEBOOK_07_SOCIAL_LLM_MODEL
        in
        BLOCK_3_FREE_TIER_APPROVED_SOCIAL_MODELS,
    ]
)


BLOCK_3_SOCIAL_LLM_EXECUTABLE = all(
    [
        NOTEBOOK_07_RUN_SOCIAL_LLM_SUPERVISION,
        NOTEBOOK_07_SOCIAL_LLM_PROVIDER == "google",
        BLOCK_3_GOOGLE_GENAI_AVAILABLE,
        BLOCK_3_GEMINI_CREDENTIAL_READY,
        BLOCK_3_SOCIAL_LLM_COST_POLICY_READY,
    ]
)


# =============================================================================
# General Drive JSON helpers for raw social LLM results
# =============================================================================

def block_3_find_drive_file_by_name(
    drive_service,
    filename,
):

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )

    response = (
        drive_service.files()
        .list(
            q=(
                f"name = '{escaped_filename}' "
                "and trashed = false"
            ),
            spaces=
                "drive",
            fields=
                "files(id,name,modifiedTime,parents)",
            orderBy=
                "modifiedTime desc",
            pageSize=
                20,
        )
        .execute()
    )

    files = response.get(
        "files",
        [],
    )

    return (
        files[0]
        if files
        else None
    )


def block_3_load_optional_drive_json(
    drive_service,
    filename,
):

    metadata = block_3_find_drive_file_by_name(
        drive_service=
            drive_service,
        filename=
            filename,
    )

    if metadata is None:

        return (
            None,
            None,
        )

    raw_bytes = block_3_download_drive_bytes(
        drive_service=
            drive_service,
        file_id=
            metadata[
                "id"
            ],
    )

    if not raw_bytes:

        return (
            metadata,
            None,
        )

    return (
        metadata,
        json.loads(
            raw_bytes.decode(
                "utf-8"
            )
        ),
    )


def block_3_persist_json_by_name(
    drive_service,
    filename,
    payload,
):

    json_text = json.dumps(
        payload,
        ensure_ascii=False,
        indent=2,
    )

    media = MediaIoBaseUpload(
        io.BytesIO(
            json_text.encode(
                "utf-8"
            )
        ),
        mimetype=
            "application/json",
        resumable=
            False,
    )

    existing = block_3_find_drive_file_by_name(
        drive_service=
            drive_service,
        filename=
            filename,
    )

    if existing is not None:

        drive_file = (
            drive_service.files()
            .update(
                fileId=
                    existing[
                        "id"
                    ],
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )

        operation = "updated"

    else:

        handover_metadata = (
            drive_service.files()
            .get(
                fileId=
                    NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID,
                fields=
                    "id,name,parents",
            )
            .execute()
        )

        metadata = {
            "name":
                filename,
        }

        parent_ids = handover_metadata.get(
            "parents",
            [],
        )

        if parent_ids:

            metadata[
                "parents"
            ] = parent_ids

        drive_file = (
            drive_service.files()
            .create(
                body=
                    metadata,
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )

        operation = "created"

    return (
        drive_file,
        operation,
    )


# =============================================================================
# Recover previously accepted social supervision
# =============================================================================

(
    BLOCK_3_PREVIOUS_ACCEPTED_METADATA,
    BLOCK_3_PREVIOUS_ACCEPTED_ARTEFACT,
) = block_3_load_optional_drive_json(
    drive_service=
        NOTEBOOK_07_DRIVE_SERVICE,
    filename=
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_FILENAME,
)


BLOCK_3_PREVIOUS_ACCEPTED_SUPERVISION_INPUT = {}


if isinstance(
    BLOCK_3_PREVIOUS_ACCEPTED_ARTEFACT,
    dict,
):

    for record in (
        BLOCK_3_PREVIOUS_ACCEPTED_ARTEFACT.get(
            "records",
            [],
        )
    ):

        if not isinstance(
            record,
            dict,
        ):

            continue

        source_order = record.get(
            "source_order"
        )

        if not isinstance(
            source_order,
            int,
        ):

            continue

        supervision_source = record.get(
            "supervision_source"
        )

        if supervision_source not in {
            "human",
            "llm",
        }:

            continue

        annotations = {}

        for (
            dimension_name,
            annotation,
        ) in record.get(
            "social_annotations",
            {},
        ).items():

            if not isinstance(
                annotation,
                dict,
            ):

                continue

            value_state = annotation.get(
                "value_state"
            )

            if value_state == "not_supervised":

                continue

            annotations[
                dimension_name
            ] = {
                "value":
                    annotation.get(
                        "value"
                    ),

                "available":
                    bool(
                        annotation.get(
                            "available",
                            False,
                        )
                    ),

                "evidence":
                    annotation.get(
                        "evidence"
                    ),

                "annotator_note":
                    annotation.get(
                        "annotator_note"
                    ),
            }

        BLOCK_3_PREVIOUS_ACCEPTED_SUPERVISION_INPUT[
            source_order
        ] = {
            "supervision_source":
                supervision_source,

            "supervisor_id":
                record.get(
                    "supervisor_id"
                )
                or
                "recovered_supervisor",

            "provider":
                (
                    "google"
                    if supervision_source == "llm"
                    else None
                ),

            "model":
                (
                    NOTEBOOK_07_SOCIAL_LLM_MODEL
                    if supervision_source == "llm"
                    else None
                ),

            "review_status":
                "accepted",

            "annotations":
                annotations,
        }


# =============================================================================
# Normalise current human / provenance-aware input before LLM supplementation
# =============================================================================

if "NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT" not in globals():

    NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT = {}


if "NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS" not in globals():

    NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS = {}


BLOCK_3_BASE_SUPERVISION_INPUT = deepcopy(
    BLOCK_3_PREVIOUS_ACCEPTED_SUPERVISION_INPUT
)


if isinstance(
    NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT,
    dict,
):

    for (
        source_order,
        sentence_payload,
    ) in NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT.items():

        if not isinstance(
            source_order,
            int,
        ):

            continue

        # Explicit current input overrides recovered persisted input.
        BLOCK_3_BASE_SUPERVISION_INPUT[
            source_order
        ] = deepcopy(
            sentence_payload
        )


if isinstance(
    NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS,
    dict,
):

    for (
        source_order,
        sentence_annotations,
    ) in NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS.items():

        if not isinstance(
            source_order,
            int,
        ):

            continue

        # Human supervision always overrides persisted or machine supervision.
        BLOCK_3_BASE_SUPERVISION_INPUT[
            source_order
        ] = {
            "supervision_source":
                "human",

            "supervisor_id":
                "legacy_manual_annotator",

            "provider":
                None,

            "model":
                None,

            "review_status":
                "accepted",

            "annotations":
                deepcopy(
                    sentence_annotations
                ),
        }


# =============================================================================
# Determine sentence / article supervision gaps
# =============================================================================

BLOCK_3_CANONICAL_SOURCE_ORDERS = set(
    range(
        NOTEBOOK_07_SENTENCE_COUNT
    )
)


BLOCK_3_ALREADY_SUPERVISED_SOURCE_ORDERS = set(
    BLOCK_3_BASE_SUPERVISION_INPUT.keys()
)


BLOCK_3_UNSUPERVISED_SOURCE_ORDERS = sorted(
    BLOCK_3_CANONICAL_SOURCE_ORDERS
    -
    BLOCK_3_ALREADY_SUPERVISED_SOURCE_ORDERS
)


def block_3_article_id_from_sentence_id(
    sentence_id,
):

    if (
        not isinstance(
            sentence_id,
            str,
        )
        or
        not sentence_id
    ):

        return None

    if "::" in sentence_id:

        return sentence_id.split(
            "::",
            1,
        )[0]

    return sentence_id


BLOCK_3_SOURCE_ORDER_BY_SENTENCE_ID = {
    record[
        "identity"
    ][
        "sentence_id"
    ]:
        source_order

    for (
        source_order,
        record,
    ) in enumerate(
        BLOCK_3_TEMPLATE_RECORDS
    )
}


BLOCK_3_ARTICLE_TARGET_ORDERS = {}


for source_order in BLOCK_3_UNSUPERVISED_SOURCE_ORDERS:

    sentence_id = (
        BLOCK_3_TEMPLATE_RECORDS[
            source_order
        ][
            "identity"
        ][
            "sentence_id"
        ]
    )

    article_id = block_3_article_id_from_sentence_id(
        sentence_id
    )

    BLOCK_3_ARTICLE_TARGET_ORDERS.setdefault(
        article_id,
        [],
    ).append(
        source_order
    )


# =============================================================================
# Recover persisted raw social LLM results
# =============================================================================

(
    BLOCK_3_RAW_SOCIAL_LLM_METADATA,
    BLOCK_3_RAW_SOCIAL_LLM_STORE,
) = block_3_load_optional_drive_json(
    drive_service=
        NOTEBOOK_07_DRIVE_SERVICE,
    filename=
        NOTEBOOK_07_SOCIAL_LLM_RAW_STORE_FILENAME,
)


if not isinstance(
    BLOCK_3_RAW_SOCIAL_LLM_STORE,
    dict,
):

    BLOCK_3_RAW_SOCIAL_LLM_STORE = {
        "artefact_type":
            "media_ai_raw_social_llm_supervision",

        "artefact_version":
            NOTEBOOK_07_SOCIAL_LLM_RAW_STORE_VERSION,

        "created_at_utc":
            BLOCK_3_EXECUTED_AT_UTC,

        "provider":
            NOTEBOOK_07_SOCIAL_LLM_PROVIDER,

        "model":
            NOTEBOOK_07_SOCIAL_LLM_MODEL,

        "results":
            [],

        "usage_ledger":
            [],
    }


BLOCK_3_RAW_SOCIAL_LLM_RESULTS = (
    BLOCK_3_RAW_SOCIAL_LLM_STORE.get(
        "results",
        [],
    )
)


if not isinstance(
    BLOCK_3_RAW_SOCIAL_LLM_RESULTS,
    list,
):

    BLOCK_3_RAW_SOCIAL_LLM_RESULTS = []


# =============================================================================
# Convert recovered provider-successful results into candidate supervision
# =============================================================================

BLOCK_3_RECOVERED_LLM_SUPERVISION_INPUT = {}


for result in BLOCK_3_RAW_SOCIAL_LLM_RESULTS:

    if not isinstance(
        result,
        dict,
    ):

        continue

    execution = result.get(
        "execution",
        {},
    )

    if execution.get(
        "status"
    ) != "SUCCESS":

        continue

    provider_output = result.get(
        "parsed_output",
        {},
    )

    for item in provider_output.get(
        "sentence_annotations",
        [],
    ):

        if not isinstance(
            item,
            dict,
        ):

            continue

        source_order = item.get(
            "source_order"
        )

        if not isinstance(
            source_order,
            int,
        ):

            continue

        if source_order not in BLOCK_3_CANONICAL_SOURCE_ORDERS:

            continue

        if source_order in BLOCK_3_BASE_SUPERVISION_INPUT:

            continue

        annotations = item.get(
            "annotations"
        )

        if not isinstance(
            annotations,
            dict,
        ):

            continue

        BLOCK_3_RECOVERED_LLM_SUPERVISION_INPUT[
            source_order
        ] = {
            "supervision_source":
                "llm",

            "supervisor_id":
                NOTEBOOK_07_SOCIAL_LLM_SUPERVISOR_ID,

            "provider":
                NOTEBOOK_07_SOCIAL_LLM_PROVIDER,

            "model":
                NOTEBOOK_07_SOCIAL_LLM_MODEL,

            "review_status":
                "accepted",

            "annotations":
                deepcopy(
                    annotations
                ),
        }


for (
    source_order,
    payload,
) in BLOCK_3_RECOVERED_LLM_SUPERVISION_INPUT.items():

    if source_order not in BLOCK_3_BASE_SUPERVISION_INPUT:

        BLOCK_3_BASE_SUPERVISION_INPUT[
            source_order
        ] = deepcopy(
            payload
        )


BLOCK_3_UNSUPERVISED_SOURCE_ORDERS_AFTER_RECOVERY = sorted(
    BLOCK_3_CANONICAL_SOURCE_ORDERS
    -
    set(
        BLOCK_3_BASE_SUPERVISION_INPUT.keys()
    )
)


# =============================================================================
# Social LLM prompt and response schema
# =============================================================================

BLOCK_3_SOCIAL_DIMENSION_GUIDANCE = {
    definition[
        "target_name"
    ]:
        {
            "dimension_id":
                definition[
                    "dimension_id"
                ],

            "target_family":
                definition[
                    "target_family"
                ],

            "minimum":
                definition.get(
                    "minimum"
                ),

            "maximum":
                definition.get(
                    "maximum"
                ),

            "description":
                definition.get(
                    "description"
                ),
        }

    for definition
    in NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
}


def block_3_build_social_llm_payload(
    article_id,
    source_orders,
):

    sentence_units = []

    for source_order in source_orders:

        record = BLOCK_3_TEMPLATE_RECORDS[
            source_order
        ]

        sentence_units.append(
            {
                "source_order":
                    source_order,

                "sentence_id":
                    record[
                        "identity"
                    ][
                        "sentence_id"
                    ],

                "preceding_context":
                    record.get(
                        "context",
                        {},
                    ).get(
                        "preceding_context"
                    ),

                "current_sentence":
                    record.get(
                        "context",
                        {},
                    ).get(
                        "current_sentence"
                    ),
            }
        )

    return {
        "article_id":
            article_id,

        "target_source_orders":
            list(
                source_orders
            ),

        "sentence_units":
            sentence_units,
    }


def block_3_build_social_llm_input_text(
    payload,
):

    return (
        "MEDIA AI — SUPPLEMENTAL SOCIAL REPRESENTATION SUPERVISION\n\n"

        "You are an independent machine supervisor. "
        "Annotate only the supplied target sentences using the seven "
        "Media AI Social Representation dimensions.\n\n"

        "IMPORTANT CAUSAL RULE:\n"
        "For each target sentence, use only that sentence's "
        "`current_sentence` and its supplied `preceding_context`. "
        "Do not use information from any later target sentence when "
        "judging an earlier sentence.\n\n"

        "IMPORTANT MISSING-VALUE RULE:\n"
        "If the current sentence and permitted preceding context do not "
        "provide enough evidence for a dimension, set available=false, "
        "value=null, and evidence=null. Do not infer absence from silence.\n\n"

        "SIGNED COHESION DIMENSIONS (S1–S5):\n"
        "Use values from -1.0 to 1.0 only when supported by evidence. "
        "Negative values indicate conflict, separation, antagonism or "
        "fragmentation; positive values indicate solidarity, affiliation, "
        "coordination or cohesion. Use 0.0 only when the evidence supports "
        "a genuinely neutral or balanced relation. Otherwise mark unavailable.\n\n"

        "BINARY SOCIAL STRUCTURE DIMENSIONS (S6–S7):\n"
        "Use 1.0 only for explicit observed presence. "
        "Use 0.0 only when explicit evidence supports observed absence. "
        "If presence/absence is not determinable from the permitted text, "
        "mark unavailable.\n\n"

        "EVIDENCE RULE:\n"
        "Every available=true annotation must include a short textual "
        "evidence string grounded in the permitted sentence/context. "
        "Do not invent external facts.\n\n"

        "DIMENSION CONTRACT:\n"
        f"{json.dumps(BLOCK_3_SOCIAL_DIMENSION_GUIDANCE, ensure_ascii=False, indent=2)}"
        "\n\n"

        "TARGET SENTENCES:\n"
        f"{json.dumps(payload['sentence_units'], ensure_ascii=False, indent=2)}"
        "\n\n"

        "OUTPUT RULE:\n"
        "Return one annotation for every supplied source_order. "
        "Each annotation_json must decode to an object containing exactly "
        "the seven Social Representation dimension names. "
        "Each dimension must contain exactly: value, available, evidence, "
        "annotator_note. annotator_note may be null or a short string."
    )


def block_3_build_social_llm_output_schema(
    payload,
):

    target_count = len(
        payload[
            "target_source_orders"
        ]
    )

    return {
        "type":
            "object",

        "properties": {
            "article_id": {
                "type":
                    "string",
            },

            "sentence_annotations": {
                "type":
                    "array",

                "minItems":
                    target_count,

                "maxItems":
                    target_count,

                "items": {
                    "type":
                        "object",

                    "properties": {
                        "source_order": {
                            "type":
                                "integer",

                            "enum":
                                payload[
                                    "target_source_orders"
                                ],
                        },

                        "sentence_id": {
                            "type":
                                "string",
                        },

                        "annotation_json": {
                            "type":
                                "string",
                        },
                    },

                    "required": [
                        "source_order",
                        "sentence_id",
                        "annotation_json",
                    ],

                    "additionalProperties":
                        False,
                },
            },
        },

        "required": [
            "article_id",
            "sentence_annotations",
        ],

        "additionalProperties":
            False,
    }


def block_3_normalise_social_llm_output(
    provider_output,
    payload,
):

    if not isinstance(
        provider_output,
        dict,
    ):

        raise TypeError(
            "Social LLM output must decode to a dictionary."
        )

    returned_article_id = provider_output.get(
        "article_id"
    )

    if returned_article_id != payload[
        "article_id"
    ]:

        raise ValueError(
            "Social LLM article identity does not match the request."
        )

    sentence_annotations = provider_output.get(
        "sentence_annotations"
    )

    if not isinstance(
        sentence_annotations,
        list,
    ):

        raise TypeError(
            "Social LLM output has no valid sentence_annotations list."
        )

    expected_orders = list(
        payload[
            "target_source_orders"
        ]
    )

    returned_orders = [
        item.get(
            "source_order"
        )
        for item
        in sentence_annotations
        if isinstance(
            item,
            dict,
        )
    ]

    if (
        len(
            returned_orders
        )
        !=
        len(
            expected_orders
        )
        or
        set(
            returned_orders
        )
        !=
        set(
            expected_orders
        )
    ):

        raise ValueError(
            "Social LLM source-order coverage does not match the request."
        )

    expected_sentence_id_by_order = {
        unit[
            "source_order"
        ]:
            unit[
                "sentence_id"
            ]

        for unit
        in payload[
            "sentence_units"
        ]
    }

    normalised = []

    for item in sentence_annotations:

        if not isinstance(
            item,
            dict,
        ):

            raise TypeError(
                "Social LLM sentence annotation is not a dictionary."
            )

        source_order = item.get(
            "source_order"
        )

        sentence_id = item.get(
            "sentence_id"
        )

        if (
            sentence_id
            !=
            expected_sentence_id_by_order[
                source_order
            ]
        ):

            raise ValueError(
                "Social LLM sentence identity does not match source_order."
            )

        annotation_json = item.get(
            "annotation_json"
        )

        if not isinstance(
            annotation_json,
            str,
        ) or not annotation_json.strip():

            raise ValueError(
                "Social LLM annotation_json is empty or invalid."
            )

        annotations = json.loads(
            annotation_json
        )

        if not isinstance(
            annotations,
            dict,
        ):

            raise TypeError(
                "Decoded social LLM annotation must be a dictionary."
            )

        normalised.append(
            {
                "source_order":
                    source_order,

                "sentence_id":
                    sentence_id,

                "annotations":
                    annotations,
            }
        )

    return {
        "article_id":
            payload[
                "article_id"
            ],

        "sentence_annotations":
            normalised,
    }


# =============================================================================
# Request-usage safeguards
# =============================================================================

BLOCK_3_REQUESTS_THIS_RUN = 0

BLOCK_3_TODAY_UTC = (
    datetime.now(
        timezone.utc
    ).date().isoformat()
)


BLOCK_3_USAGE_LEDGER = (
    BLOCK_3_RAW_SOCIAL_LLM_STORE.get(
        "usage_ledger",
        [],
    )
)


if not isinstance(
    BLOCK_3_USAGE_LEDGER,
    list,
):

    BLOCK_3_USAGE_LEDGER = []


BLOCK_3_REQUESTS_TODAY_BEFORE_RUN = sum(
    1
    for entry
    in BLOCK_3_USAGE_LEDGER
    if isinstance(
        entry,
        dict,
    )
    and entry.get(
        "date_utc"
    )
    ==
    BLOCK_3_TODAY_UTC
    and entry.get(
        "executed"
    )
    is True
)


def block_3_request_capacity_available():

    if (
        BLOCK_3_REQUESTS_THIS_RUN
        >=
        NOTEBOOK_07_MAX_SOCIAL_LLM_REQUESTS_PER_RUN
    ):

        return (
            False,
            "Maximum social LLM requests per run reached.",
        )

    requests_today = (
        BLOCK_3_REQUESTS_TODAY_BEFORE_RUN
        +
        BLOCK_3_REQUESTS_THIS_RUN
    )

    if (
        requests_today
        >=
        NOTEBOOK_07_MAX_SOCIAL_LLM_REQUESTS_PER_DAY
    ):

        return (
            False,
            "Maximum social LLM requests per day reached.",
        )

    return (
        True,
        "request_capacity_available",
    )


# =============================================================================
# Execute controlled Gemini social supervision for eligible articles
# =============================================================================

BLOCK_3_NEW_SOCIAL_LLM_RESULTS = []


BLOCK_3_ARTICLES_ALREADY_SUCCESSFUL = {
    result.get(
        "article_id"
    )
    for result
    in BLOCK_3_RAW_SOCIAL_LLM_RESULTS
    if isinstance(
        result,
        dict,
    )
    and result.get(
        "execution",
        {},
    ).get(
        "status"
    )
    ==
    "SUCCESS"
}


if BLOCK_3_SOCIAL_LLM_EXECUTABLE:

    remaining_orders_by_article = {}

    for source_order in (
        BLOCK_3_UNSUPERVISED_SOURCE_ORDERS_AFTER_RECOVERY
    ):

        sentence_id = (
            BLOCK_3_TEMPLATE_RECORDS[
                source_order
            ][
                "identity"
            ][
                "sentence_id"
            ]
        )

        article_id = block_3_article_id_from_sentence_id(
            sentence_id
        )

        remaining_orders_by_article.setdefault(
            article_id,
            [],
        ).append(
            source_order
        )


    for (
        article_id,
        source_orders,
    ) in remaining_orders_by_article.items():

        allowed, reason = block_3_request_capacity_available()

        if not allowed:

            break

        payload = block_3_build_social_llm_payload(
            article_id=
                article_id,
            source_orders=
                source_orders,
        )

        BLOCK_3_REQUESTS_THIS_RUN += 1

        request_record = {
            "date_utc":
                BLOCK_3_TODAY_UTC,

            "article_id":
                article_id,

            "source_orders":
                list(
                    source_orders
                ),

            "executed":
                True,

            "provider":
                NOTEBOOK_07_SOCIAL_LLM_PROVIDER,

            "model":
                NOTEBOOK_07_SOCIAL_LLM_MODEL,
        }

        BLOCK_3_USAGE_LEDGER.append(
            request_record
        )

        try:

            client = genai.Client(
                api_key=
                    BLOCK_3_GEMINI_API_KEY
            )

            interaction = (
                client.interactions.create(
                    model=
                        NOTEBOOK_07_SOCIAL_LLM_MODEL,

                    input=
                        block_3_build_social_llm_input_text(
                            payload
                        ),

                    response_format={
                        "type":
                            "text",

                        "mime_type":
                            "application/json",

                        "schema":
                            block_3_build_social_llm_output_schema(
                                payload
                            ),
                    },
                )
            )

            raw_output_text = interaction.output_text

            if not isinstance(
                raw_output_text,
                str,
            ) or not raw_output_text.strip():

                raise ValueError(
                    "Gemini social supervision returned empty output."
                )

            provider_parsed_output = json.loads(
                raw_output_text
            )

            parsed_output = block_3_normalise_social_llm_output(
                provider_output=
                    provider_parsed_output,
                payload=
                    payload,
            )

            result = {
                "article_id":
                    article_id,

                "source_orders":
                    list(
                        source_orders
                    ),

                "provider":
                    NOTEBOOK_07_SOCIAL_LLM_PROVIDER,

                "model":
                    NOTEBOOK_07_SOCIAL_LLM_MODEL,

                "provider_response_id":
                    getattr(
                        interaction,
                        "id",
                        None,
                    ),

                "raw_output_text":
                    raw_output_text,

                "provider_parsed_output":
                    provider_parsed_output,

                "parsed_output":
                    parsed_output,

                "execution":
                    {
                        "executed":
                            True,

                        "status":
                            "SUCCESS",

                        "reason":
                            (
                                "Controlled Gemini social supervision "
                                "completed successfully."
                            ),
                    },
            }

        except Exception as exc:

            result = {
                "article_id":
                    article_id,

                "source_orders":
                    list(
                        source_orders
                    ),

                "provider":
                    NOTEBOOK_07_SOCIAL_LLM_PROVIDER,

                "model":
                    NOTEBOOK_07_SOCIAL_LLM_MODEL,

                "execution":
                    {
                        "executed":
                            True,

                        "status":
                            "ERROR",

                        "reason":
                            str(
                                exc
                            ),

                        "error_type":
                            type(
                                exc
                            ).__name__,
                    },
            }

        BLOCK_3_NEW_SOCIAL_LLM_RESULTS.append(
            result
        )

        BLOCK_3_RAW_SOCIAL_LLM_RESULTS.append(
            deepcopy(
                result
            )
        )

        BLOCK_3_RAW_SOCIAL_LLM_STORE[
            "results"
        ] = BLOCK_3_RAW_SOCIAL_LLM_RESULTS

        BLOCK_3_RAW_SOCIAL_LLM_STORE[
            "usage_ledger"
        ] = BLOCK_3_USAGE_LEDGER

        BLOCK_3_RAW_SOCIAL_LLM_STORE[
            "updated_at_utc"
        ] = datetime.now(
            timezone.utc
        ).isoformat()

        (
            BLOCK_3_RAW_SOCIAL_LLM_DRIVE_FILE,
            BLOCK_3_RAW_SOCIAL_LLM_DRIVE_OPERATION,
        ) = block_3_persist_json_by_name(
            drive_service=
                NOTEBOOK_07_DRIVE_SERVICE,

            filename=
                NOTEBOOK_07_SOCIAL_LLM_RAW_STORE_FILENAME,

            payload=
                BLOCK_3_RAW_SOCIAL_LLM_STORE,
        )


# =============================================================================
# Merge newly successful machine supervision into the accepted input candidate
# =============================================================================

for result in BLOCK_3_NEW_SOCIAL_LLM_RESULTS:

    if result.get(
        "execution",
        {},
    ).get(
        "status"
    ) != "SUCCESS":

        continue

    for item in result.get(
        "parsed_output",
        {},
    ).get(
        "sentence_annotations",
        [],
    ):

        source_order = item.get(
            "source_order"
        )

        if source_order in BLOCK_3_BASE_SUPERVISION_INPUT:

            # Never overwrite current human / already accepted supervision.
            continue

        BLOCK_3_BASE_SUPERVISION_INPUT[
            source_order
        ] = {
            "supervision_source":
                "llm",

            "supervisor_id":
                NOTEBOOK_07_SOCIAL_LLM_SUPERVISOR_ID,

            "provider":
                NOTEBOOK_07_SOCIAL_LLM_PROVIDER,

            "model":
                NOTEBOOK_07_SOCIAL_LLM_MODEL,

            "review_status":
                "accepted",

            "annotations":
                deepcopy(
                    item[
                        "annotations"
                    ]
                ),
        }


# =============================================================================
# Expose merged provenance-aware supervision to the existing validation path
# =============================================================================

NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT = deepcopy(
    BLOCK_3_BASE_SUPERVISION_INPUT
)

# The merged provenance-aware input already includes legacy manual annotations.
# Clear the backward-compatible input to prevent double-source ambiguity.
NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS = {}


BLOCK_3_SOCIAL_LLM_SUCCESS_COUNT = sum(
    1
    for result
    in BLOCK_3_NEW_SOCIAL_LLM_RESULTS
    if result.get(
        "execution",
        {},
    ).get(
        "status"
    )
    ==
    "SUCCESS"
)


BLOCK_3_SOCIAL_LLM_ERROR_COUNT = sum(
    1
    for result
    in BLOCK_3_NEW_SOCIAL_LLM_RESULTS
    if result.get(
        "execution",
        {},
    ).get(
        "status"
    )
    ==
    "ERROR"
)


BLOCK_3_UNSUPERVISED_AFTER_LLM = sorted(
    BLOCK_3_CANONICAL_SOURCE_ORDERS
    -
    set(
        NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT.keys()
    )
)


# =============================================================================
# Supervision-input contract
# =============================================================================

#
# Block 3 does not invent social labels. It may execute controlled,
# provenance-preserving LLM supervision for canonical sentences that
# remain unsupervised after existing human / persisted supervision is
# restored.
#
# It accepts either:
#
#   1. NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT
#      Provenance-aware supervision that may come from a human annotator or
#      from an independently executed LLM supervisor.
#
#   2. NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS
#      Backward-compatible manual annotation dictionary from the original
#      Block 3 contract.
#
# Canonical provenance-aware structure:
#
# NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT = {
#     source_order: {
#         "supervision_source": "human" | "llm",
#         "supervisor_id": "...",
#         "provider": None | "...",
#         "model": None | "...",
#         "review_status": "accepted",
#         "annotations": {
#             "interpersonal_cohesion": {
#                 "value": 0.5,
#                 "available": True,
#                 "evidence": "...",
#                 "annotator_note": "..."
#             },
#             ...
#         }
#     },
#     ...
# }
#
# Partial sentence and dimension coverage is allowed. Omitted sentences or
# dimensions remain in the canonical target space with mask=False and
# value_state="not_supervised". They are never converted to numerical zero.
#
# Block 3 only accepts review_status="accepted" into the accepted social
# supervision artefact. Machine supervision therefore remains explicit and
# provenance-preserving rather than being silently treated as human reference.
# =============================================================================

if "NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT" not in globals():
    NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT = {}


if "NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS" not in globals():
    NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS = {}


BLOCK_3_GENERIC_INPUT_PRESENT = (
    isinstance(
        NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT,
        dict,
    )
    and
    len(
        NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT
    )
    > 0
)


BLOCK_3_MANUAL_INPUT_PRESENT = (
    isinstance(
        NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS,
        dict,
    )
    and
    len(
        NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS
    )
    > 0
)


if (
    BLOCK_3_GENERIC_INPUT_PRESENT
    and
    BLOCK_3_MANUAL_INPUT_PRESENT
):

    raise RuntimeError(
        "Provide either NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT or "
        "NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS, not both."
    )


BLOCK_3_SUPERVISION_INPUT_PRESENT = (
    BLOCK_3_GENERIC_INPUT_PRESENT
    or
    BLOCK_3_MANUAL_INPUT_PRESENT
)


# =============================================================================
# First-run annotation-required state
# =============================================================================

if not BLOCK_3_SUPERVISION_INPUT_PRESENT:

    NOTEBOOK_07_SOCIAL_ANNOTATION_REQUIRED = True

    NOTEBOOK_07_SOCIAL_ANNOTATIONS_COMPLETE = False

    NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_DEFINED = False

    NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_VALID = False

    NOTEBOOK_07_READY_FOR_SOCIAL_TARGET_AVAILABILITY_AUDIT = False

    NOTEBOOK_07_SOCIAL_OPTIMISATION_READY = False

    NOTEBOOK_07_BLOCK_3_WAITING_FOR_ANNOTATION = True

    NOTEBOOK_07_BLOCK_3_COMPLETE = False

    NOTEBOOK_07_BLOCK_3_VALID = True


    print("=" * 72)

    print(
        "Media AI — Notebook 07, Block 3: "
        "Social Representation Annotation, Evidence Audit "
        "and Accepted Supervision Construction"
    )

    print("=" * 72)

    print(
        "Annotation state              : accepted supervision required"
    )

    print(
        f"Canonical sentences           : "
        f"{NOTEBOOK_07_SENTENCE_COUNT}"
    )

    print(
        f"Social dimensions             : "
        f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM}"
    )

    print(
        f"Possible supervision elements : "
        f"{NOTEBOOK_07_SENTENCE_COUNT * NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM}"
    )

    print(
        "Labels generated by Block 3   : False"
    )

    print(
        "Human supervision supported   : True"
    )

    print(
        "LLM supervision supported     : True"
    )

    print(
        "Previous artefacts modified   : False"
    )

    print(
        "Social optimisation ready     : False"
    )

    print("-" * 72)

    print(
        "The persisted Social Representation annotation template "
        "has been restored successfully."
    )

    print(
        "Block 3 did not create any accepted social label without "
        "external or human supervision."
    )

    print(
        "Provide provenance-aware accepted supervision through "
        "NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT, or use the legacy "
        "NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS dictionary."
    )

    print(
        "Human and independently produced LLM supervision are both "
        "supported, but every observed value must retain evidence."
    )

    print(
        "Partial sentence and dimension coverage is permitted; omitted "
        "elements remain masked rather than being converted to zero."
    )

    print(
        "The worksheet below provides canonical sentence text and "
        "permitted preceding context."
    )

    print("=" * 72)


    display(
        BLOCK_3_ANNOTATION_WORKSHEET
    )


else:

    # =========================================================================
    # Normalise supervision source
    # =========================================================================

    BLOCK_3_SUPERVISION_INPUT_MODE = (
        "provenance_aware"
        if BLOCK_3_GENERIC_INPUT_PRESENT
        else "legacy_manual"
    )


    if BLOCK_3_GENERIC_INPUT_PRESENT:

        BLOCK_3_RAW_SUPERVISION_INPUT = deepcopy(
            NOTEBOOK_07_SOCIAL_SUPERVISION_INPUT
        )


    else:

        BLOCK_3_RAW_SUPERVISION_INPUT = {}


        for (
            source_order,
            sentence_annotations,
        ) in NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS.items():

            BLOCK_3_RAW_SUPERVISION_INPUT[
                source_order
            ] = {
                "supervision_source":
                    "human",

                "supervisor_id":
                    "legacy_manual_annotator",

                "provider":
                    None,

                "model":
                    None,

                "review_status":
                    "accepted",

                "annotations":
                    deepcopy(
                        sentence_annotations
                    ),
            }


    # =========================================================================
    # Source-order contract
    # =========================================================================

    BLOCK_3_EXPECTED_SOURCE_ORDERS = set(
        range(
            NOTEBOOK_07_SENTENCE_COUNT
        )
    )


    BLOCK_3_PROVIDED_SOURCE_ORDERS = set(
        BLOCK_3_RAW_SUPERVISION_INPUT.keys()
    )


    BLOCK_3_SOURCE_ORDERS_VALID = (
        BLOCK_3_PROVIDED_SOURCE_ORDERS.issubset(
            BLOCK_3_EXPECTED_SOURCE_ORDERS
        )
    )


    if not BLOCK_3_SOURCE_ORDERS_VALID:

        extra_orders = sorted(
            BLOCK_3_PROVIDED_SOURCE_ORDERS
            -
            BLOCK_3_EXPECTED_SOURCE_ORDERS
        )


        raise RuntimeError(
            "Social supervision contains source orders outside the "
            "canonical sentence range. "
            f"Extra: {extra_orders}"
        )


    # =========================================================================
    # Dimension contract
    # =========================================================================

    BLOCK_3_EXPECTED_DIMENSION_NAMES = set(
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
    )


    BLOCK_3_DEFINITION_BY_NAME = {
        definition[
            "target_name"
        ]:
            deepcopy(
                definition
            )

        for definition
        in NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
    }


    # =========================================================================
    # Annotation validators
    # =========================================================================

    def block_3_is_finite_number(
        value,
    ):

        if isinstance(
            value,
            bool,
        ):

            return False


        if not isinstance(
            value,
            (
                int,
                float,
                np.integer,
                np.floating,
            ),
        ):

            return False


        return math.isfinite(
            float(
                value
            )
        )


    def block_3_empty_annotation(
        definition,
        supervision_source="none",
        supervisor_id=None,
        provider=None,
        model=None,
        review_status="not_supervised",
    ):

        return {
            "value":
                None,

            "value_state":
                "not_supervised",

            "available":
                False,

            "evidence":
                None,

            "annotator_note":
                None,

            "target_family":
                definition[
                    "target_family"
                ],

            "supervision_source":
                supervision_source,

            "supervisor_id":
                supervisor_id,

            "provider":
                provider,

            "model":
                model,

            "review_status":
                review_status,
        }


    def block_3_validate_annotation(
        annotation,
        definition,
        provenance,
    ):
        """
        Validate one supplied social annotation.

        Returns:
            valid
            normalised_annotation
            error
        """

        if not isinstance(
            annotation,
            dict,
        ):

            return (
                False,
                None,
                "annotation_not_dictionary",
            )


        required_keys = {
            "value",
            "available",
            "evidence",
            "annotator_note",
        }


        if not required_keys.issubset(
            set(
                annotation.keys()
            )
        ):

            return (
                False,
                None,
                "annotation_keys_missing",
            )


        available = annotation[
            "available"
        ]

        value = annotation[
            "value"
        ]

        evidence = annotation[
            "evidence"
        ]

        annotator_note = annotation[
            "annotator_note"
        ]


        if not isinstance(
            available,
            bool,
        ):

            return (
                False,
                None,
                "availability_not_boolean",
            )


        if not available:

            if value is not None:

                return (
                    False,
                    None,
                    "unavailable_annotation_has_numeric_value",
                )


            return (
                True,
                {
                    "value":
                        None,

                    "value_state":
                        "explicitly_unavailable",

                    "available":
                        False,

                    "evidence":
                        evidence,

                    "annotator_note":
                        annotator_note,

                    "target_family":
                        definition[
                            "target_family"
                        ],

                    **deepcopy(
                        provenance
                    ),
                },
                None,
            )


        if not block_3_is_finite_number(
            value
        ):

            return (
                False,
                None,
                "available_annotation_value_nonfinite_or_nonnumeric",
            )


        value = float(
            value
        )


        if not isinstance(
            evidence,
            str,
        ):

            return (
                False,
                None,
                "available_annotation_missing_evidence",
            )


        if not evidence.strip():

            return (
                False,
                None,
                "available_annotation_empty_evidence",
            )


        target_family = definition[
            "target_family"
        ]


        if target_family == "signed_cohesion":

            if not (
                -1.0
                <=
                value
                <=
                1.0
            ):

                return (
                    False,
                    None,
                    "signed_cohesion_value_out_of_range",
                )


        elif target_family == "binary_social_structure":

            if value not in {
                0.0,
                1.0,
            }:

                return (
                    False,
                    None,
                    "binary_social_structure_value_invalid",
                )


        else:

            return (
                False,
                None,
                "unknown_target_family",
            )


        return (
            True,
            {
                "value":
                    value,

                "value_state":
                    "observed",

                "available":
                    True,

                "evidence":
                    evidence.strip(),

                "annotator_note":
                    annotator_note,

                "target_family":
                    target_family,

                **deepcopy(
                    provenance
                ),
            },
            None,
        )


    # =========================================================================
    # Validate and normalise supplied sentence supervision
    # =========================================================================

    BLOCK_3_ANNOTATION_ERRORS = []

    BLOCK_3_NORMALISED_SUPERVISION_BY_ORDER = {}

    BLOCK_3_SUPERVISION_SOURCE_COUNTS = {
        "human": 0,
        "llm": 0,
    }


    for (
        source_order,
        sentence_payload,
    ) in BLOCK_3_RAW_SUPERVISION_INPUT.items():

        if not isinstance(
            source_order,
            int,
        ):

            BLOCK_3_ANNOTATION_ERRORS.append(
                {
                    "source_order":
                        source_order,

                    "error":
                        "source_order_not_integer",
                }
            )

            continue


        if not isinstance(
            sentence_payload,
            dict,
        ):

            BLOCK_3_ANNOTATION_ERRORS.append(
                {
                    "source_order":
                        source_order,

                    "error":
                        "sentence_payload_not_dictionary",
                }
            )

            continue


        supervision_source = sentence_payload.get(
            "supervision_source"
        )

        supervisor_id = sentence_payload.get(
            "supervisor_id"
        )

        provider = sentence_payload.get(
            "provider"
        )

        model = sentence_payload.get(
            "model"
        )

        review_status = sentence_payload.get(
            "review_status"
        )

        annotations = sentence_payload.get(
            "annotations",
            {},
        )


        if supervision_source not in {
            "human",
            "llm",
        }:

            BLOCK_3_ANNOTATION_ERRORS.append(
                {
                    "source_order":
                        source_order,

                    "error":
                        "supervision_source_invalid",
                }
            )

            continue


        if not isinstance(
            supervisor_id,
            str,
        ) or not supervisor_id.strip():

            BLOCK_3_ANNOTATION_ERRORS.append(
                {
                    "source_order":
                        source_order,

                    "error":
                        "supervisor_id_missing",
                }
            )

            continue


        if review_status != "accepted":

            BLOCK_3_ANNOTATION_ERRORS.append(
                {
                    "source_order":
                        source_order,

                    "error":
                        "review_status_not_accepted",
                }
            )

            continue


        if supervision_source == "llm":

            if not isinstance(
                provider,
                str,
            ) or not provider.strip():

                BLOCK_3_ANNOTATION_ERRORS.append(
                    {
                        "source_order":
                            source_order,

                        "error":
                            "llm_provider_missing",
                    }
                )

                continue


            if not isinstance(
                model,
                str,
            ) or not model.strip():

                BLOCK_3_ANNOTATION_ERRORS.append(
                    {
                        "source_order":
                            source_order,

                        "error":
                            "llm_model_missing",
                    }
                )

                continue


        if not isinstance(
            annotations,
            dict,
        ):

            BLOCK_3_ANNOTATION_ERRORS.append(
                {
                    "source_order":
                        source_order,

                    "error":
                        "annotations_not_dictionary",
                }
            )

            continue


        provided_dimension_names = set(
            annotations.keys()
        )


        if not provided_dimension_names.issubset(
            BLOCK_3_EXPECTED_DIMENSION_NAMES
        ):

            BLOCK_3_ANNOTATION_ERRORS.append(
                {
                    "source_order":
                        source_order,

                    "error":
                        "unknown_dimension_name",

                    "extra_dimensions":
                        sorted(
                            provided_dimension_names
                            -
                            BLOCK_3_EXPECTED_DIMENSION_NAMES
                        ),
                }
            )

            continue


        provenance = {
            "supervision_source":
                supervision_source,

            "supervisor_id":
                supervisor_id.strip(),

            "provider":
                provider.strip()
                if isinstance(
                    provider,
                    str,
                )
                else None,

            "model":
                model.strip()
                if isinstance(
                    model,
                    str,
                )
                else None,

            "review_status":
                "accepted",
        }


        normalised_annotations = {}


        for dimension_name in (
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
        ):

            definition = BLOCK_3_DEFINITION_BY_NAME[
                dimension_name
            ]


            if dimension_name not in annotations:

                normalised_annotations[
                    dimension_name
                ] = block_3_empty_annotation(
                    definition=
                        definition,

                    supervision_source=
                        supervision_source,

                    supervisor_id=
                        supervisor_id.strip(),

                    provider=
                        provenance[
                            "provider"
                        ],

                    model=
                        provenance[
                            "model"
                        ],

                    review_status=
                        "accepted_partial",
                )

                continue


            (
                annotation_valid,
                normalised_annotation,
                annotation_error,
            ) = block_3_validate_annotation(
                annotation=
                    annotations[
                        dimension_name
                    ],

                definition=
                    definition,

                provenance=
                    provenance,
            )


            if not annotation_valid:

                BLOCK_3_ANNOTATION_ERRORS.append(
                    {
                        "source_order":
                            source_order,

                        "sentence_id":
                            BLOCK_3_TEMPLATE_RECORDS[
                                source_order
                            ][
                                "identity"
                            ][
                                "sentence_id"
                            ],

                        "dimension":
                            dimension_name,

                        "error":
                            annotation_error,
                    }
                )

                continue


            normalised_annotations[
                dimension_name
            ] = normalised_annotation


        if len(
            normalised_annotations
        ) != NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM:

            continue


        BLOCK_3_NORMALISED_SUPERVISION_BY_ORDER[
            source_order
        ] = {
            "provenance":
                provenance,

            "annotations":
                normalised_annotations,
        }


        BLOCK_3_SUPERVISION_SOURCE_COUNTS[
            supervision_source
        ] += 1


    BLOCK_3_ANNOTATION_INPUT_VALID = (
        len(
            BLOCK_3_ANNOTATION_ERRORS
        )
        ==
        0
    )


    if not BLOCK_3_ANNOTATION_INPUT_VALID:

        BLOCK_3_ANNOTATION_ERROR_TABLE = pd.DataFrame(
            BLOCK_3_ANNOTATION_ERRORS
        )


        display(
            BLOCK_3_ANNOTATION_ERROR_TABLE
        )


        raise RuntimeError(
            "Social supervision failed validation. "
            f"Error count: {len(BLOCK_3_ANNOTATION_ERRORS)}"
        )


    # =========================================================================
    # Construct canonical accepted supervision records
    # =========================================================================
    #
    # Every canonical sentence is retained. Sentences that were not supplied
    # by any accepted supervisor remain fully masked with value_state
    # "not_supervised".
    # =========================================================================

    NOTEBOOK_07_ACCEPTED_SOCIAL_RECORDS = []


    for (
        source_order,
        template_record,
    ) in enumerate(
        BLOCK_3_TEMPLATE_RECORDS
    ):

        supplied_payload = (
            BLOCK_3_NORMALISED_SUPERVISION_BY_ORDER.get(
                source_order
            )
        )


        if supplied_payload is None:

            social_annotations = {}


            for dimension_name in (
                NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
            ):

                definition = BLOCK_3_DEFINITION_BY_NAME[
                    dimension_name
                ]


                social_annotations[
                    dimension_name
                ] = {
                    "dimension_id":
                        definition[
                            "dimension_id"
                        ],

                    **block_3_empty_annotation(
                        definition=
                            definition,
                    ),
                }


            sentence_supervision_source = "none"

            sentence_supervisor_id = None

            sentence_review_status = "not_supervised"


        else:

            social_annotations = {}


            for dimension_name in (
                NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
            ):

                definition = BLOCK_3_DEFINITION_BY_NAME[
                    dimension_name
                ]


                social_annotations[
                    dimension_name
                ] = {
                    "dimension_id":
                        definition[
                            "dimension_id"
                        ],

                    **deepcopy(
                        supplied_payload[
                            "annotations"
                        ][
                            dimension_name
                        ]
                    ),
                }


            sentence_supervision_source = supplied_payload[
                "provenance"
            ][
                "supervision_source"
            ]

            sentence_supervisor_id = supplied_payload[
                "provenance"
            ][
                "supervisor_id"
            ]

            sentence_review_status = "accepted"


        available_dimension_count = sum(
            int(
                annotation[
                    "available"
                ]
            )

            for annotation
            in social_annotations.values()
        )


        NOTEBOOK_07_ACCEPTED_SOCIAL_RECORDS.append(
            {
                "record_type":
                    "media_ai_notebook_07_accepted_social_supervision",

                "supervision_version":
                    NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_VERSION,

                "source_order":
                    source_order,

                "identity":
                    deepcopy(
                        template_record[
                            "identity"
                        ]
                    ),

                "context":
                    deepcopy(
                        template_record[
                            "context"
                        ]
                    ),

                "social_annotations":
                    social_annotations,

                "supervision_source":
                    sentence_supervision_source,

                "supervisor_id":
                    sentence_supervisor_id,

                "review_status":
                    sentence_review_status,

                "available_dimension_count":
                    available_dimension_count,

                "annotation_complete":
                    (
                        available_dimension_count
                        ==
                        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
                    ),

                "labels_generated_by_block_3":
                    False,

                "original_notebook_03_record_modified":
                    False,

                "block_2_template_modified":
                    False,
            }
        )


    # =========================================================================
    # Accepted record validation
    # =========================================================================

    BLOCK_3_ACCEPTED_RECORD_COUNT = len(
        NOTEBOOK_07_ACCEPTED_SOCIAL_RECORDS
    )


    BLOCK_3_ACCEPTED_RECORD_COUNT_VALID = (
        BLOCK_3_ACCEPTED_RECORD_COUNT
        ==
        NOTEBOOK_07_SENTENCE_COUNT
    )


    BLOCK_3_ACCEPTED_SENTENCE_IDS = [
        record[
            "identity"
        ][
            "sentence_id"
        ]

        for record
        in NOTEBOOK_07_ACCEPTED_SOCIAL_RECORDS
    ]


    BLOCK_3_ACCEPTED_IDS_UNIQUE = (
        len(
            BLOCK_3_ACCEPTED_SENTENCE_IDS
        )
        ==
        len(
            set(
                BLOCK_3_ACCEPTED_SENTENCE_IDS
            )
        )
    )


    BLOCK_3_ACCEPTED_ALIGNMENT_VALID = (
        set(
            BLOCK_3_ACCEPTED_SENTENCE_IDS
        )
        ==
        set(
            NOTEBOOK_07_SENTENCE_IDS
        )
    )


    if not all(
        [
            BLOCK_3_ACCEPTED_RECORD_COUNT_VALID,
            BLOCK_3_ACCEPTED_IDS_UNIQUE,
            BLOCK_3_ACCEPTED_ALIGNMENT_VALID,
        ]
    ):

        raise RuntimeError(
            "Accepted social supervision does not preserve "
            "canonical sentence identity."
        )


    # =========================================================================
    # Construct target and mask matrices
    # =========================================================================

    BLOCK_3_SOCIAL_TARGET_MATRIX = np.full(
        (
            NOTEBOOK_07_SENTENCE_COUNT,
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
        ),
        np.nan,
        dtype=np.float64,
    )


    BLOCK_3_SOCIAL_MASK_MATRIX = np.zeros(
        (
            NOTEBOOK_07_SENTENCE_COUNT,
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
        ),
        dtype=bool,
    )


    for (
        source_order,
        record,
    ) in enumerate(
        NOTEBOOK_07_ACCEPTED_SOCIAL_RECORDS
    ):

        for (
            dimension_index,
            dimension_name,
        ) in enumerate(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
        ):

            annotation = record[
                "social_annotations"
            ][
                dimension_name
            ]


            if annotation[
                "available"
            ]:

                BLOCK_3_SOCIAL_TARGET_MATRIX[
                    source_order,
                    dimension_index,
                ] = float(
                    annotation[
                        "value"
                    ]
                )


                BLOCK_3_SOCIAL_MASK_MATRIX[
                    source_order,
                    dimension_index,
                ] = True


    # =========================================================================
    # Matrix validation
    # =========================================================================

    BLOCK_3_TARGET_MATRIX_SHAPE_VALID = (
        BLOCK_3_SOCIAL_TARGET_MATRIX.shape
        ==
        (
            NOTEBOOK_07_SENTENCE_COUNT,
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
        )
    )


    BLOCK_3_MASK_MATRIX_SHAPE_VALID = (
        BLOCK_3_SOCIAL_MASK_MATRIX.shape
        ==
        (
            NOTEBOOK_07_SENTENCE_COUNT,
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
        )
    )


    BLOCK_3_OBSERVED_VALUES_FINITE = bool(
        np.isfinite(
            BLOCK_3_SOCIAL_TARGET_MATRIX[
                BLOCK_3_SOCIAL_MASK_MATRIX
            ]
        ).all()
    )


    if not all(
        [
            BLOCK_3_TARGET_MATRIX_SHAPE_VALID,
            BLOCK_3_MASK_MATRIX_SHAPE_VALID,
            BLOCK_3_OBSERVED_VALUES_FINITE,
        ]
    ):

        raise RuntimeError(
            "Accepted Social Representation target matrices are invalid."
        )


    # =========================================================================
    # Coverage audit
    # =========================================================================

    BLOCK_3_DIMENSION_AVAILABLE_COUNTS = {}

    BLOCK_3_DIMENSION_COVERAGE = {}

    BLOCK_3_DIMENSION_MINIMUM = {}

    BLOCK_3_DIMENSION_MAXIMUM = {}

    BLOCK_3_DIMENSION_UNIQUE_VALUES = {}


    for (
        dimension_index,
        dimension_name,
    ) in enumerate(
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
    ):

        dimension_mask = BLOCK_3_SOCIAL_MASK_MATRIX[
            :,
            dimension_index,
        ]


        available_count = int(
            dimension_mask.sum()
        )


        BLOCK_3_DIMENSION_AVAILABLE_COUNTS[
            dimension_name
        ] = available_count


        BLOCK_3_DIMENSION_COVERAGE[
            dimension_name
        ] = float(
            available_count
            /
            NOTEBOOK_07_SENTENCE_COUNT
        )


        if available_count > 0:

            observed_values = BLOCK_3_SOCIAL_TARGET_MATRIX[
                dimension_mask,
                dimension_index,
            ]


            BLOCK_3_DIMENSION_MINIMUM[
                dimension_name
            ] = float(
                observed_values.min()
            )


            BLOCK_3_DIMENSION_MAXIMUM[
                dimension_name
            ] = float(
                observed_values.max()
            )


            BLOCK_3_DIMENSION_UNIQUE_VALUES[
                dimension_name
            ] = int(
                np.unique(
                    observed_values
                ).size
            )


        else:

            BLOCK_3_DIMENSION_MINIMUM[
                dimension_name
            ] = None

            BLOCK_3_DIMENSION_MAXIMUM[
                dimension_name
            ] = None

            BLOCK_3_DIMENSION_UNIQUE_VALUES[
                dimension_name
            ] = 0


    BLOCK_3_TOTAL_AVAILABLE_ELEMENTS = int(
        BLOCK_3_SOCIAL_MASK_MATRIX.sum()
    )


    BLOCK_3_TOTAL_POSSIBLE_ELEMENTS = int(
        BLOCK_3_SOCIAL_MASK_MATRIX.size
    )


    BLOCK_3_AGGREGATE_COVERAGE = (
        BLOCK_3_TOTAL_AVAILABLE_ELEMENTS
        /
        BLOCK_3_TOTAL_POSSIBLE_ELEMENTS
    )


    BLOCK_3_SENTENCES_WITH_ANY_SUPERVISION = int(
        np.any(
            BLOCK_3_SOCIAL_MASK_MATRIX,
            axis=1,
        ).sum()
    )


    BLOCK_3_FULLY_SUPERVISED_SENTENCES = int(
        np.all(
            BLOCK_3_SOCIAL_MASK_MATRIX,
            axis=1,
        ).sum()
    )


    BLOCK_3_SENTENCES_WITH_NO_SUPERVISION = int(
        (
            ~np.any(
                BLOCK_3_SOCIAL_MASK_MATRIX,
                axis=1,
            )
        ).sum()
    )


    BLOCK_3_PARTIALLY_SUPERVISED_SENTENCES = (
        NOTEBOOK_07_SENTENCE_COUNT
        -
        BLOCK_3_FULLY_SUPERVISED_SENTENCES
        -
        BLOCK_3_SENTENCES_WITH_NO_SUPERVISION
    )


    # =========================================================================
    # Evidence and provenance audit
    # =========================================================================

    BLOCK_3_AVAILABLE_ANNOTATION_COUNT = 0

    BLOCK_3_AVAILABLE_WITH_EVIDENCE_COUNT = 0

    BLOCK_3_EXPLICITLY_UNAVAILABLE_ANNOTATION_COUNT = 0

    BLOCK_3_NOT_SUPERVISED_ANNOTATION_COUNT = 0

    BLOCK_3_HUMAN_AVAILABLE_ANNOTATION_COUNT = 0

    BLOCK_3_LLM_AVAILABLE_ANNOTATION_COUNT = 0


    for record in NOTEBOOK_07_ACCEPTED_SOCIAL_RECORDS:

        for annotation in record[
            "social_annotations"
        ].values():

            if annotation[
                "available"
            ]:

                BLOCK_3_AVAILABLE_ANNOTATION_COUNT += 1


                if (
                    isinstance(
                        annotation[
                            "evidence"
                        ],
                        str,
                    )
                    and
                    annotation[
                        "evidence"
                    ].strip()
                ):

                    BLOCK_3_AVAILABLE_WITH_EVIDENCE_COUNT += 1


                if annotation[
                    "supervision_source"
                ] == "human":

                    BLOCK_3_HUMAN_AVAILABLE_ANNOTATION_COUNT += 1


                elif annotation[
                    "supervision_source"
                ] == "llm":

                    BLOCK_3_LLM_AVAILABLE_ANNOTATION_COUNT += 1


            elif annotation[
                "value_state"
            ] == "explicitly_unavailable":

                BLOCK_3_EXPLICITLY_UNAVAILABLE_ANNOTATION_COUNT += 1


            else:

                BLOCK_3_NOT_SUPERVISED_ANNOTATION_COUNT += 1


    BLOCK_3_ALL_AVAILABLE_HAVE_EVIDENCE = (
        BLOCK_3_AVAILABLE_ANNOTATION_COUNT
        ==
        BLOCK_3_AVAILABLE_WITH_EVIDENCE_COUNT
    )


    if not BLOCK_3_ALL_AVAILABLE_HAVE_EVIDENCE:

        raise RuntimeError(
            "One or more available social annotations lack evidence."
        )


    # =========================================================================
    # No fabrication / source modification audit
    # =========================================================================

    BLOCK_3_NO_LABELS_GENERATED_BY_BLOCK = all(
        record[
            "labels_generated_by_block_3"
        ]
        is False

        for record
        in NOTEBOOK_07_ACCEPTED_SOCIAL_RECORDS
    )


    BLOCK_3_NOTEBOOK_03_UNMODIFIED = all(
        record[
            "original_notebook_03_record_modified"
        ]
        is False

        for record
        in NOTEBOOK_07_ACCEPTED_SOCIAL_RECORDS
    )


    BLOCK_3_BLOCK_2_TEMPLATE_UNMODIFIED = all(
        record[
            "block_2_template_modified"
        ]
        is False

        for record
        in NOTEBOOK_07_ACCEPTED_SOCIAL_RECORDS
    )


    # =========================================================================
    # Accepted supervision state
    # =========================================================================

    NOTEBOOK_07_SOCIAL_ANNOTATION_PERFORMED = True

    NOTEBOOK_07_SOCIAL_TARGET_CONSTRUCTION_PERFORMED = True

    NOTEBOOK_07_SOCIAL_ANNOTATIONS_COMPLETE = (
        BLOCK_3_SENTENCES_WITH_NO_SUPERVISION
        ==
        0
    )

    NOTEBOOK_07_SOCIAL_ANNOTATION_REQUIRED = (
        not NOTEBOOK_07_SOCIAL_ANNOTATIONS_COMPLETE
    )


    NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_DEFINED = True


    NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_VALID = all(
        [
            BLOCK_3_ACCEPTED_RECORD_COUNT_VALID,
            BLOCK_3_ACCEPTED_IDS_UNIQUE,
            BLOCK_3_ACCEPTED_ALIGNMENT_VALID,
            BLOCK_3_TARGET_MATRIX_SHAPE_VALID,
            BLOCK_3_MASK_MATRIX_SHAPE_VALID,
            BLOCK_3_OBSERVED_VALUES_FINITE,
            BLOCK_3_ALL_AVAILABLE_HAVE_EVIDENCE,
            BLOCK_3_NO_LABELS_GENERATED_BY_BLOCK,
            BLOCK_3_NOTEBOOK_03_UNMODIFIED,
            BLOCK_3_BLOCK_2_TEMPLATE_UNMODIFIED,
        ]
    )


    NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_DEFINED = False

    NOTEBOOK_07_SOCIAL_ACTIVATION_CONTRACT_RESOLVED = False

    NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_RESOLVED = False

    NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY = False

    NOTEBOOK_07_SOCIAL_OPTIMISATION_READY = False


    # =========================================================================
    # Construct accepted supervision artefact
    # =========================================================================

    NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_ARTEFACT = {
        "artefact_type":
            "media_ai_accepted_social_supervision",

        "artefact_version":
            NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_VERSION,

        "created_at_utc":
            BLOCK_3_EXECUTED_AT_UTC,

        "notebook":
            "07_social_representation",

        "source_schema":
            {
                "filename":
                    NOTEBOOK_07_SOCIAL_SCHEMA_FILENAME,

                "drive_file_id":
                    NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_FILE_ID,
            },

        "source_annotation_template":
            {
                "filename":
                    NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_FILENAME,

                "drive_file_id":
                    NOTEBOOK_07_SOCIAL_ANNOTATION_TEMPLATE_DRIVE_FILE_ID,
            },

        "architecture":
            {
                "representation_dimension":
                    NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

                "dimension_ids":
                    list(
                        NOTEBOOK_07_SOCIAL_DIMENSION_IDS
                    ),

                "dimension_order":
                    list(
                        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
                    ),

                "dimension_definitions":
                    deepcopy(
                        NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
                    ),
            },

        "supervision_contract":
            {
                "ingestion_mode":
                    BLOCK_3_SUPERVISION_INPUT_MODE,

                "supported_sources":
                    [
                        "human",
                        "llm",
                    ],

                "labels_generated_by_block_3":
                    False,

                "accepted_review_status":
                    "accepted",

                "evidence_required_for_available":
                    True,

                "provenance_required":
                    True,

                "partial_sentence_coverage_allowed":
                    True,

                "partial_dimension_coverage_allowed":
                    True,

                "mask_aware":
                    True,

                "missing_equals_zero":
                    False,

                "missing_equals_negative":
                    False,

                "unavailable_enters_loss":
                    False,

                "future_context_allowed":
                    False,
            },

        "llm_supervision_execution":
            {
                "enabled":
                    NOTEBOOK_07_RUN_SOCIAL_LLM_SUPERVISION,

                "provider":
                    NOTEBOOK_07_SOCIAL_LLM_PROVIDER,

                "model":
                    NOTEBOOK_07_SOCIAL_LLM_MODEL,

                "require_free_supervision":
                    NOTEBOOK_07_REQUIRE_FREE_SOCIAL_SUPERVISION,

                "paid_api_usage_allowed":
                    NOTEBOOK_07_ALLOW_PAID_SOCIAL_API_USAGE,

                "automatic_paid_fallback_allowed":
                    NOTEBOOK_07_ALLOW_AUTOMATIC_PAID_SOCIAL_FALLBACK,

                "max_requests_per_run":
                    NOTEBOOK_07_MAX_SOCIAL_LLM_REQUESTS_PER_RUN,

                "max_requests_per_day":
                    NOTEBOOK_07_MAX_SOCIAL_LLM_REQUESTS_PER_DAY,

                "sdk_available":
                    BLOCK_3_GOOGLE_GENAI_AVAILABLE,

                "credential_ready":
                    BLOCK_3_GEMINI_CREDENTIAL_READY,

                "cost_policy_ready":
                    BLOCK_3_SOCIAL_LLM_COST_POLICY_READY,

                "executable":
                    BLOCK_3_SOCIAL_LLM_EXECUTABLE,

                "requests_this_run":
                    BLOCK_3_REQUESTS_THIS_RUN,

                "successful_requests_this_run":
                    BLOCK_3_SOCIAL_LLM_SUCCESS_COUNT,

                "failed_requests_this_run":
                    BLOCK_3_SOCIAL_LLM_ERROR_COUNT,

                "unsupervised_sentences_after_llm":
                    len(
                        BLOCK_3_UNSUPERVISED_AFTER_LLM
                    ),

                "raw_store_filename":
                    NOTEBOOK_07_SOCIAL_LLM_RAW_STORE_FILENAME,
            },

        "coverage":
            {
                "sentences":
                    NOTEBOOK_07_SENTENCE_COUNT,

                "dimensions":
                    NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

                "available_target_elements":
                    BLOCK_3_TOTAL_AVAILABLE_ELEMENTS,

                "possible_target_elements":
                    BLOCK_3_TOTAL_POSSIBLE_ELEMENTS,

                "aggregate_coverage":
                    float(
                        BLOCK_3_AGGREGATE_COVERAGE
                    ),

                "sentences_with_any_supervision":
                    BLOCK_3_SENTENCES_WITH_ANY_SUPERVISION,

                "fully_supervised_sentences":
                    BLOCK_3_FULLY_SUPERVISED_SENTENCES,

                "partially_supervised_sentences":
                    BLOCK_3_PARTIALLY_SUPERVISED_SENTENCES,

                "sentences_with_no_supervision":
                    BLOCK_3_SENTENCES_WITH_NO_SUPERVISION,

                "dimension_available_counts":
                    deepcopy(
                        BLOCK_3_DIMENSION_AVAILABLE_COUNTS
                    ),

                "dimension_coverage":
                    deepcopy(
                        BLOCK_3_DIMENSION_COVERAGE
                    ),

                "dimension_minimum":
                    deepcopy(
                        BLOCK_3_DIMENSION_MINIMUM
                    ),

                "dimension_maximum":
                    deepcopy(
                        BLOCK_3_DIMENSION_MAXIMUM
                    ),

                "dimension_unique_values":
                    deepcopy(
                        BLOCK_3_DIMENSION_UNIQUE_VALUES
                    ),
            },

        "evidence_and_provenance_audit":
            {
                "available_annotations":
                    BLOCK_3_AVAILABLE_ANNOTATION_COUNT,

                "available_with_evidence":
                    BLOCK_3_AVAILABLE_WITH_EVIDENCE_COUNT,

                "human_available_annotations":
                    BLOCK_3_HUMAN_AVAILABLE_ANNOTATION_COUNT,

                "llm_available_annotations":
                    BLOCK_3_LLM_AVAILABLE_ANNOTATION_COUNT,

                "explicitly_unavailable_annotations":
                    BLOCK_3_EXPLICITLY_UNAVAILABLE_ANNOTATION_COUNT,

                "not_supervised_annotations":
                    BLOCK_3_NOT_SUPERVISED_ANNOTATION_COUNT,

                "all_available_have_evidence":
                    BLOCK_3_ALL_AVAILABLE_HAVE_EVIDENCE,
            },

        "training_boundary":
            {
                "target_contract_defined":
                    True,

                "target_contract_valid":
                    True,

                "objective_policy_defined":
                    False,

                "activation_contract_resolved":
                    False,

                "loss_contract_resolved":
                    False,

                "optimisation_ready":
                    False,

                "training_executed":
                    False,

                "held_out_evaluation_executed":
                    False,

                "empirical_validity":
                    False,
            },

        "records":
            deepcopy(
                NOTEBOOK_07_ACCEPTED_SOCIAL_RECORDS
            ),
    }


    # =========================================================================
    # JSON helper
    # =========================================================================

    def block_3_json_default(
        value,
    ):

        if isinstance(
            value,
            np.generic,
        ):

            return value.item()


        if isinstance(
            value,
            np.ndarray,
        ):

            return value.tolist()


        if isinstance(
            value,
            set,
        ):

            return sorted(
                value
            )


        if isinstance(
            value,
            tuple,
        ):

            return list(
                value
            )


        raise TypeError(
            f"Object of type {type(value).__name__} "
            "is not JSON serialisable."
        )


    # =========================================================================
    # Serialise accepted supervision
    # =========================================================================

    NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_JSON = json.dumps(
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_ARTEFACT,
        indent=2,
        ensure_ascii=False,
        default=
            block_3_json_default,
    )


    BLOCK_3_ACCEPTED_JSON_VALID = bool(
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_JSON
    )


    # =========================================================================
    # Local persistence
    # =========================================================================

    with open(
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_FILENAME,
        "w",
        encoding="utf-8",
    ) as accepted_file:

        accepted_file.write(
            NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_JSON
        )


    BLOCK_3_LOCAL_ACCEPTED_ARTEFACT_CREATED = True


    # =========================================================================
    # Resolve persistent Drive parent
    # =========================================================================

    BLOCK_3_HANDOVER_METADATA = (
        NOTEBOOK_07_DRIVE_SERVICE.files()
        .get(
            fileId=
                NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID,
            fields=
                "id,name,parents",
        )
        .execute()
    )


    BLOCK_3_PARENT_IDS = BLOCK_3_HANDOVER_METADATA.get(
        "parents",
        [],
    )


    # =========================================================================
    # Drive persistence helper
    # =========================================================================

    def block_3_persist_json_to_drive(
        drive_service,
        filename,
        json_text,
        parent_ids=None,
    ):

        escaped_filename = filename.replace(
            "'",
            "\\'",
        )


        search_response = (
            drive_service.files()
            .list(
                q=(
                    f"name = '{escaped_filename}' "
                    "and trashed = false"
                ),
                spaces=
                    "drive",
                fields=
                    "files(id,name,modifiedTime,parents)",
                orderBy=
                    "modifiedTime desc",
                pageSize=
                    20,
            )
            .execute()
        )


        matching_files = search_response.get(
            "files",
            [],
        )


        media = MediaIoBaseUpload(
            io.BytesIO(
                json_text.encode(
                    "utf-8"
                )
            ),
            mimetype=
                "application/json",
            resumable=
                False,
        )


        if matching_files:

            drive_file = (
                drive_service.files()
                .update(
                    fileId=
                        matching_files[
                            0
                        ][
                            "id"
                        ],
                    media_body=
                        media,
                    fields=
                        "id,name,modifiedTime,parents",
                )
                .execute()
            )

            operation = "updated"


        else:

            metadata = {
                "name":
                    filename
            }


            if parent_ids:

                metadata[
                    "parents"
                ] = parent_ids


            drive_file = (
                drive_service.files()
                .create(
                    body=
                        metadata,
                    media_body=
                        media,
                    fields=
                        "id,name,modifiedTime,parents",
                )
                .execute()
            )

            operation = "created"


        return (
            drive_file,
            operation,
        )


    # =========================================================================
    # Persist accepted supervision
    # =========================================================================

    (
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_FILE,
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_OPERATION,
    ) = block_3_persist_json_to_drive(
        drive_service=
            NOTEBOOK_07_DRIVE_SERVICE,

        filename=
            NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_FILENAME,

        json_text=
            NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_JSON,

        parent_ids=
            BLOCK_3_PARENT_IDS,
    )


    NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_FILE_ID = (
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_FILE.get(
            "id"
        )
    )


    BLOCK_3_ACCEPTED_ARTEFACT_DRIVE_PERSISTED = bool(
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_FILE_ID
    )


    if not BLOCK_3_ACCEPTED_ARTEFACT_DRIVE_PERSISTED:

        raise RuntimeError(
            "Accepted social-supervision artefact was not persisted."
        )


    # =========================================================================
    # Read-back validation
    # =========================================================================

    BLOCK_3_RELOADED_ACCEPTED_BYTES = block_3_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_FILE_ID,
    )


    BLOCK_3_RELOADED_ACCEPTED_ARTEFACT = json.loads(
        BLOCK_3_RELOADED_ACCEPTED_BYTES.decode(
            "utf-8"
        )
    )


    BLOCK_3_READBACK_TYPE_VALID = (
        BLOCK_3_RELOADED_ACCEPTED_ARTEFACT.get(
            "artefact_type"
        )
        ==
        "media_ai_accepted_social_supervision"
    )


    BLOCK_3_READBACK_VERSION_VALID = (
        BLOCK_3_RELOADED_ACCEPTED_ARTEFACT.get(
            "artefact_version"
        )
        ==
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_VERSION
    )


    BLOCK_3_READBACK_DIMENSION_VALID = (
        BLOCK_3_RELOADED_ACCEPTED_ARTEFACT[
            "architecture"
        ][
            "representation_dimension"
        ]
        ==
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
    )


    BLOCK_3_READBACK_RECORD_COUNT_VALID = (
        len(
            BLOCK_3_RELOADED_ACCEPTED_ARTEFACT[
                "records"
            ]
        )
        ==
        NOTEBOOK_07_SENTENCE_COUNT
    )


    BLOCK_3_READBACK_LABEL_GENERATION_FALSE = (
        BLOCK_3_RELOADED_ACCEPTED_ARTEFACT[
            "supervision_contract"
        ][
            "labels_generated_by_block_3"
        ]
        is False
    )


    BLOCK_3_READBACK_TARGET_CONTRACT_VALID = (
        BLOCK_3_RELOADED_ACCEPTED_ARTEFACT[
            "training_boundary"
        ][
            "target_contract_valid"
        ]
        is True
    )


    BLOCK_3_READBACK_OPTIMISATION_FALSE = (
        BLOCK_3_RELOADED_ACCEPTED_ARTEFACT[
            "training_boundary"
        ][
            "optimisation_ready"
        ]
        is False
    )


    BLOCK_3_ACCEPTED_READBACK_VALID = all(
        [
            BLOCK_3_READBACK_TYPE_VALID,
            BLOCK_3_READBACK_VERSION_VALID,
            BLOCK_3_READBACK_DIMENSION_VALID,
            BLOCK_3_READBACK_RECORD_COUNT_VALID,
            BLOCK_3_READBACK_LABEL_GENERATION_FALSE,
            BLOCK_3_READBACK_TARGET_CONTRACT_VALID,
            BLOCK_3_READBACK_OPTIMISATION_FALSE,
        ]
    )


    if not BLOCK_3_ACCEPTED_READBACK_VALID:

        raise RuntimeError(
            "Persisted accepted social supervision failed "
            "read-back validation."
        )


    # =========================================================================
    # Readiness
    # =========================================================================

    NOTEBOOK_07_READY_FOR_SOCIAL_TARGET_AVAILABILITY_AUDIT = all(
        [
            NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_DEFINED,
            NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_VALID,
            BLOCK_3_ACCEPTED_READBACK_VALID,
            BLOCK_3_TOTAL_AVAILABLE_ELEMENTS > 0,
        ]
    )


    NOTEBOOK_07_SOCIAL_OPTIMISATION_READY = False


    # =========================================================================
    # Dimension audit table
    # =========================================================================

    BLOCK_3_DIMENSION_ROWS = []


    for (
        dimension_id,
        dimension_name,
    ) in zip(
        NOTEBOOK_07_SOCIAL_DIMENSION_IDS,
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER,
    ):

        BLOCK_3_DIMENSION_ROWS.append(
            {
                "dimension_id":
                    dimension_id,

                "target_name":
                    dimension_name,

                "available":
                    BLOCK_3_DIMENSION_AVAILABLE_COUNTS[
                        dimension_name
                    ],

                "possible":
                    NOTEBOOK_07_SENTENCE_COUNT,

                "coverage":
                    BLOCK_3_DIMENSION_COVERAGE[
                        dimension_name
                    ],

                "unique_values":
                    BLOCK_3_DIMENSION_UNIQUE_VALUES[
                        dimension_name
                    ],

                "minimum":
                    BLOCK_3_DIMENSION_MINIMUM[
                        dimension_name
                    ],

                "maximum":
                    BLOCK_3_DIMENSION_MAXIMUM[
                        dimension_name
                    ],
            }
        )


    BLOCK_3_SOCIAL_DIMENSION_AUDIT = pd.DataFrame(
        BLOCK_3_DIMENSION_ROWS
    )


    # =========================================================================
    # Final Block 3 validation
    # =========================================================================

    NOTEBOOK_07_BLOCK_3_ERRORS = []


    block_3_validation_checks = {
        "persisted_input_contract_invalid":
            BLOCK_3_PERSISTED_INPUT_CONTRACT_VALID,

        "template_sentence_ids_not_unique":
            BLOCK_3_TEMPLATE_SENTENCE_IDS_UNIQUE,

        "template_alignment_invalid":
            BLOCK_3_TEMPLATE_ALIGNMENT_VALID,

        "source_orders_invalid":
            BLOCK_3_SOURCE_ORDERS_VALID,

        "annotation_input_invalid":
            BLOCK_3_ANNOTATION_INPUT_VALID,

        "accepted_record_count_invalid":
            BLOCK_3_ACCEPTED_RECORD_COUNT_VALID,

        "accepted_sentence_ids_not_unique":
            BLOCK_3_ACCEPTED_IDS_UNIQUE,

        "accepted_alignment_invalid":
            BLOCK_3_ACCEPTED_ALIGNMENT_VALID,

        "target_matrix_shape_invalid":
            BLOCK_3_TARGET_MATRIX_SHAPE_VALID,

        "mask_matrix_shape_invalid":
            BLOCK_3_MASK_MATRIX_SHAPE_VALID,

        "observed_values_nonfinite":
            BLOCK_3_OBSERVED_VALUES_FINITE,

        "available_annotation_without_evidence":
            BLOCK_3_ALL_AVAILABLE_HAVE_EVIDENCE,

        "labels_generated_by_block":
            BLOCK_3_NO_LABELS_GENERATED_BY_BLOCK,

        "notebook_03_modified":
            BLOCK_3_NOTEBOOK_03_UNMODIFIED,

        "block_2_template_modified":
            BLOCK_3_BLOCK_2_TEMPLATE_UNMODIFIED,

        "target_contract_invalid":
            NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_VALID,

        "accepted_json_invalid":
            BLOCK_3_ACCEPTED_JSON_VALID,

        "local_accepted_artefact_not_created":
            BLOCK_3_LOCAL_ACCEPTED_ARTEFACT_CREATED,

        "accepted_artefact_not_persisted":
            BLOCK_3_ACCEPTED_ARTEFACT_DRIVE_PERSISTED,

        "accepted_readback_invalid":
            BLOCK_3_ACCEPTED_READBACK_VALID,

        "availability_audit_not_ready":
            NOTEBOOK_07_READY_FOR_SOCIAL_TARGET_AVAILABILITY_AUDIT,
    }


    for (
        error_name,
        condition,
    ) in block_3_validation_checks.items():

        if not condition:

            NOTEBOOK_07_BLOCK_3_ERRORS.append(
                error_name
            )


    # =========================================================================
    # Prohibited operations
    # =========================================================================

    prohibited_block_3_operations = {
        "social_objectives_incorrectly_activated":
            NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED,

        "social_optimizer_incorrectly_created":
            NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED,

        "social_forward_incorrectly_executed":
            NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED,

        "social_loss_incorrectly_calculated":
            NOTEBOOK_07_SOCIAL_LOSS_CALCULATED,

        "social_backward_incorrectly_executed":
            NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED,

        "social_parameter_update_incorrectly_executed":
            NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED,

        "social_training_incorrectly_executed":
            NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED,

        "psychological_training_incorrectly_executed":
            NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED,

        "factual_training_incorrectly_executed":
            NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED,

        "backbone_training_incorrectly_executed":
            NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED,

        "global_confluent_training_incorrectly_executed":
            NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED,

        "group_conditioned_incorrectly_executed":
            NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED,

        "transformative_incorrectly_executed":
            NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED,

        "transformative_weights_incorrectly_executed":
            NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED,

        "recurrent_incorrectly_executed":
            NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED,

        "held_out_evaluation_incorrectly_executed":
            NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED,

        "empirical_validity_incorrectly_asserted":
            NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,
    }


    for (
        error_name,
        operation_executed,
    ) in prohibited_block_3_operations.items():

        if operation_executed:

            NOTEBOOK_07_BLOCK_3_ERRORS.append(
                error_name
            )


    NOTEBOOK_07_BLOCK_3_VALID = (
        len(
            NOTEBOOK_07_BLOCK_3_ERRORS
        )
        ==
        0
    )


    if not NOTEBOOK_07_BLOCK_3_VALID:

        raise RuntimeError(
            "Notebook 07 Block 3 accepted social-supervision audit failed. "
            f"Errors: {NOTEBOOK_07_BLOCK_3_ERRORS}"
        )


    # =========================================================================
    # Block completion
    # =========================================================================

    NOTEBOOK_07_BLOCK_3_WAITING_FOR_ANNOTATION = False

    NOTEBOOK_07_BLOCK_3_COMPLETE = True


    # =========================================================================
    # Final report
    # =========================================================================

    print("=" * 72)

    print(
        "Media AI — Notebook 07, Block 3: "
        "Social Representation Annotation, Evidence Audit "
        "and Accepted Supervision Construction"
    )

    print("=" * 72)

    print(
        f"Accepted-supervision version : "
        f"{NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_VERSION}"
    )

    print(
        f"Supervision ingestion mode   : "
        f"{BLOCK_3_SUPERVISION_INPUT_MODE}"
    )


    print("-" * 72)

    print(
        "Canonical identity"
    )

    print(
        f"Sentences                    : "
        f"{NOTEBOOK_07_SENTENCE_COUNT}"
    )

    print(
        f"Social dimensions            : "
        f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM}"
    )

    print(
        f"Sentence IDs unique          : "
        f"{BLOCK_3_ACCEPTED_IDS_UNIQUE}"
    )

    print(
        f"Canonical alignment valid    : "
        f"{BLOCK_3_ACCEPTED_ALIGNMENT_VALID}"
    )


    print("-" * 72)

    print(
        "Controlled supplemental social LLM supervision"
    )

    print(
        f"LLM supervision enabled      : "
        f"{NOTEBOOK_07_RUN_SOCIAL_LLM_SUPERVISION}"
    )

    print(
        f"Provider                     : "
        f"{NOTEBOOK_07_SOCIAL_LLM_PROVIDER}"
    )

    print(
        f"Model                        : "
        f"{NOTEBOOK_07_SOCIAL_LLM_MODEL}"
    )

    print(
        f"Google GenAI SDK available   : "
        f"{BLOCK_3_GOOGLE_GENAI_AVAILABLE}"
    )

    print(
        f"Gemini credential ready      : "
        f"{BLOCK_3_GEMINI_CREDENTIAL_READY}"
    )

    print(
        f"Free-tier cost policy ready  : "
        f"{BLOCK_3_SOCIAL_LLM_COST_POLICY_READY}"
    )

    print(
        f"LLM execution permitted      : "
        f"{BLOCK_3_SOCIAL_LLM_EXECUTABLE}"
    )

    print(
        f"Requests this run            : "
        f"{BLOCK_3_REQUESTS_THIS_RUN}"
    )

    print(
        f"Successful requests          : "
        f"{BLOCK_3_SOCIAL_LLM_SUCCESS_COUNT}"
    )

    print(
        f"Failed requests              : "
        f"{BLOCK_3_SOCIAL_LLM_ERROR_COUNT}"
    )

    print(
        f"Unsupervised after LLM       : "
        f"{len(BLOCK_3_UNSUPERVISED_AFTER_LLM)}"
    )


    print("-" * 72)

    print(
        "Accepted supervision provenance"
    )

    print(
        f"Canonical records            : "
        f"{BLOCK_3_ACCEPTED_RECORD_COUNT}"
    )

    print(
        f"Supplied sentence records    : "
        f"{len(BLOCK_3_NORMALISED_SUPERVISION_BY_ORDER)}"
    )

    print(
        f"Human supervised sentences   : "
        f"{BLOCK_3_SUPERVISION_SOURCE_COUNTS['human']}"
    )

    print(
        f"LLM supervised sentences     : "
        f"{BLOCK_3_SUPERVISION_SOURCE_COUNTS['llm']}"
    )

    print(
        f"Labels generated by Block 3  : "
        f"{False}"
    )

    print(
        f"Available annotations        : "
        f"{BLOCK_3_AVAILABLE_ANNOTATION_COUNT}"
    )

    print(
        f"Human available annotations  : "
        f"{BLOCK_3_HUMAN_AVAILABLE_ANNOTATION_COUNT}"
    )

    print(
        f"LLM available annotations    : "
        f"{BLOCK_3_LLM_AVAILABLE_ANNOTATION_COUNT}"
    )

    print(
        f"Available with evidence      : "
        f"{BLOCK_3_AVAILABLE_WITH_EVIDENCE_COUNT}"
    )

    print(
        f"Explicitly unavailable       : "
        f"{BLOCK_3_EXPLICITLY_UNAVAILABLE_ANNOTATION_COUNT}"
    )

    print(
        f"Not supervised               : "
        f"{BLOCK_3_NOT_SUPERVISED_ANNOTATION_COUNT}"
    )

    print(
        f"All available have evidence  : "
        f"{BLOCK_3_ALL_AVAILABLE_HAVE_EVIDENCE}"
    )


    print("-" * 72)

    print(
        "Social supervision coverage"
    )

    print(
        f"Available target elements    : "
        f"{BLOCK_3_TOTAL_AVAILABLE_ELEMENTS}"
    )

    print(
        f"Possible target elements     : "
        f"{BLOCK_3_TOTAL_POSSIBLE_ELEMENTS}"
    )

    print(
        f"Aggregate target coverage    : "
        f"{BLOCK_3_AGGREGATE_COVERAGE:.4f}"
    )

    print(
        f"Any supervision sentences    : "
        f"{BLOCK_3_SENTENCES_WITH_ANY_SUPERVISION}"
    )

    print(
        f"Fully supervised sentences   : "
        f"{BLOCK_3_FULLY_SUPERVISED_SENTENCES}"
    )

    print(
        f"Partially supervised         : "
        f"{BLOCK_3_PARTIALLY_SUPERVISED_SENTENCES}"
    )

    print(
        f"No-supervision sentences     : "
        f"{BLOCK_3_SENTENCES_WITH_NO_SUPERVISION}"
    )


    for dimension_name in (
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
    ):

        print(
            f"{dimension_name:<31}: "
            f"{BLOCK_3_DIMENSION_AVAILABLE_COUNTS[dimension_name]}"
            f" / "
            f"{NOTEBOOK_07_SENTENCE_COUNT}"
            f"  coverage="
            f"{BLOCK_3_DIMENSION_COVERAGE[dimension_name]:.4f}"
        )


    print("-" * 72)

    print(
        "Accepted supervision artefact"
    )

    print(
        f"Filename                     : "
        f"{NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_FILENAME}"
    )

    print(
        f"Local copy created           : "
        f"{BLOCK_3_LOCAL_ACCEPTED_ARTEFACT_CREATED}"
    )

    print(
        f"Drive operation              : "
        f"{NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_OPERATION}"
    )

    print(
        f"Drive file ID                : "
        f"{NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_FILE_ID}"
    )

    print(
        f"Read-back valid              : "
        f"{BLOCK_3_ACCEPTED_READBACK_VALID}"
    )


    print("-" * 72)

    print(
        "Readiness"
    )

    print(
        f"All sentences supervised     : "
        f"{NOTEBOOK_07_SOCIAL_ANNOTATIONS_COMPLETE}"
    )

    print(
        f"Target contract defined      : "
        f"{NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_DEFINED}"
    )

    print(
        f"Target contract valid        : "
        f"{NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_VALID}"
    )

    print(
        f"Ready for availability audit : "
        f"{NOTEBOOK_07_READY_FOR_SOCIAL_TARGET_AVAILABILITY_AUDIT}"
    )

    print(
        f"Optimisation ready           : "
        f"{NOTEBOOK_07_SOCIAL_OPTIMISATION_READY}"
    )


    print("-" * 72)

    print(
        "Execution boundary"
    )

    print(
        f"Supervision ingested         : "
        f"{NOTEBOOK_07_SOCIAL_ANNOTATION_PERFORMED}"
    )

    print(
        f"Target construction performed: "
        f"{NOTEBOOK_07_SOCIAL_TARGET_CONSTRUCTION_PERFORMED}"
    )

    print(
        f"Objectives activated         : "
        f"{NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED}"
    )

    print(
        f"Optimiser created            : "
        f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED}"
    )

    print(
        f"Forward pass executed        : "
        f"{NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED}"
    )

    print(
        f"Loss calculated              : "
        f"{NOTEBOOK_07_SOCIAL_LOSS_CALCULATED}"
    )

    print(
        f"Backward pass executed       : "
        f"{NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED}"
    )

    print(
        f"Parameter update executed    : "
        f"{NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED}"
    )

    print(
        f"Social training executed     : "
        f"{NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED}"
    )

    print(
        f"Psychological retraining     : "
        f"{NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED}"
    )

    print(
        f"Factual retraining           : "
        f"{NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED}"
    )

    print(
        f"Group-conditioned executed   : "
        f"{NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED}"
    )

    print(
        f"Transformative executed      : "
        f"{NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED}"
    )

    print(
        f"Recurrent executed           : "
        f"{NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED}"
    )

    print(
        f"Empirical validity           : "
        f"{NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED}"
    )

    print(
        f"Block valid                  : "
        f"{NOTEBOOK_07_BLOCK_3_VALID}"
    )

    print(
        f"Block 3 complete             : "
        f"{NOTEBOOK_07_BLOCK_3_COMPLETE}"
    )


    print("=" * 72)


    print(
        "Notebook 07 accepted Social Representation supervision and "
        "target construction completed successfully."
    )

    print(
        "Block 3 did not invent social labels; accepted values came from "
        "human supervision, recovered accepted supervision, or controlled "
        "provenance-preserving LLM supervision."
    )

    print(
        "Every observed social value retains textual evidence and explicit "
        "supervision provenance; machine supervision remains distinguishable "
        "from human supervision."
    )

    print(
        "Unsupervised or explicitly unavailable elements remain masked; "
        "numerical zero remains distinct from missing supervision."
    )

    print(
        "Partial sentence and dimension coverage is permitted by the target "
        "contract and does not require fabrication of absent labels."
    )

    print(
        "The canonical Notebook 03 source and Block 2 blank annotation "
        "template remain unmodified."
    )

    print(
        f"The canonical {NOTEBOOK_07_SENTENCE_COUNT} × "
        f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM} Social Representation "
        "target and mask matrices were constructed from accepted "
        "supervision only."
    )

    print(
        "The accepted social-supervision artefact was persisted separately "
        "and verified by read-back."
    )

    print(
        "No social objective, optimiser, forward pass, loss calculation, "
        "backward pass, parameter update or model training was performed."
    )

    print(
        "Successful Block 3 completion establishes an evidence-grounded "
        "social target contract, not optimisation eligibility, "
        "generalisation or empirical validity."
    )

    print(
        "Block 4 may proceed to Social Target Availability, Variability, "
        "Activation and Loss-Contract Analysis."
    )

    print("=" * 72)


    display(
        BLOCK_3_SOCIAL_DIMENSION_AUDIT
    )

========================================================================
Media AI — Notebook 07, Block 3: Social Representation Annotation, Evidence Audit and Accepted Supervision Construction
========================================================================
Accepted-supervision version : 1.2
Supervision ingestion mode   : provenance_aware
------------------------------------------------------------------------
Canonical identity
Sentences                    : 54
Social dimensions            : 7
Sentence IDs unique          : True
Canonical alignment valid    : True
------------------------------------------------------------------------
Controlled supplemental social LLM supervision
LLM supervision enabled      : True
Provider                     : google
Model                        : gemini-3.6-flash
Google GenAI SDK available   : True
Gemini credential ready      : True
Free-tier cost policy ready  : True
LLM execution permitted      : True
Requests this run            : 2
Successful requests          : 2
Failed requests              : 0
Unsupervised after LLM       : 0
------------------------------------------------------------------------
Accepted supervision provenance
Canonical records            : 54
Supplied sentence records    : 54
Human supervised sentences   : 16
LLM supervised sentences     : 38
Labels generated by Block 3  : False
Available annotations        : 155
Human available annotations  : 67
LLM available annotations    : 88
Available with evidence      : 155
Explicitly unavailable       : 223
Not supervised               : 0
All available have evidence  : True
------------------------------------------------------------------------
Social supervision coverage
Available target elements    : 155
Possible target elements     : 378
Aggregate target coverage    : 0.4101
Any supervision sentences    : 51
Fully supervised sentences   : 0
Partially supervised         : 51
No-supervision sentences     : 3
interpersonal_cohesion         : 26 / 54  coverage=0.4815
economic_cohesion              : 3 / 54  coverage=0.0556
political_cohesion             : 21 / 54  coverage=0.3889
religious_cohesion             : 0 / 54  coverage=0.0000
group_collective_cohesion      : 32 / 54  coverage=0.5926
institutional_role_relation    : 50 / 54  coverage=0.9259
public_audience_relation       : 23 / 54  coverage=0.4259
------------------------------------------------------------------------
Accepted supervision artefact
Filename                     : notebook_07_accepted_social_supervision.json
Local copy created           : True
Drive operation              : updated
Drive file ID                : 1RMofcYIqIFKH9FqSrAz5hjbicfSNu5ex
Read-back valid              : True
------------------------------------------------------------------------
Readiness
All sentences supervised     : False
Target contract defined      : True
Target contract valid        : True
Ready for availability audit : True
Optimisation ready           : False
------------------------------------------------------------------------
Execution boundary
Supervision ingested         : True
Target construction performed: True
Objectives activated         : False
Optimiser created            : False
Forward pass executed        : False
Loss calculated              : False
Backward pass executed       : False
Parameter update executed    : False
Social training executed     : False
Psychological retraining     : False
Factual retraining           : False
Group-conditioned executed   : False
Transformative executed      : False
Recurrent executed           : False
Empirical validity           : False
Block valid                  : True
Block 3 complete             : True
========================================================================
Notebook 07 accepted Social Representation supervision and target construction completed successfully.
Block 3 did not invent social labels; accepted values came from human supervision, recovered accepted supervision, or controlled provenance-preserving LLM supervision.
Every observed social value retains textual evidence and explicit supervision provenance; machine supervision remains distinguishable from human supervision.
Unsupervised or explicitly unavailable elements remain masked; numerical zero remains distinct from missing supervision.
Partial sentence and dimension coverage is permitted by the target contract and does not require fabrication of absent labels.
The canonical Notebook 03 source and Block 2 blank annotation template remain unmodified.
The canonical 54 × 7 Social Representation target and mask matrices were constructed from accepted supervision only.
The accepted social-supervision artefact was persisted separately and verified by read-back.
No social objective, optimiser, forward pass, loss calculation, backward pass, parameter update or model training was performed.
Successful Block 3 completion establishes an evidence-grounded social target contract, not optimisation eligibility, generalisation or empirical validity.
Block 4 may proceed to Social Target Availability, Variability, Activation and Loss-Contract Analysis.
========================================================================

,dimension_id,target_name,available,possible,coverage,unique_values,minimum,maximum
0,S1,interpersonal_cohesion,26,54,0.481481,10,-0.8,0.9
1,S2,economic_cohesion,3,54,0.055556,3,-0.2,0.8
2,S3,political_cohesion,21,54,0.388889,12,-1.0,0.8
3,S4,religious_cohesion,0,54,0.000000,0,NaN,NaN
4,S5,group_collective_cohesion,32,54,0.592593,11,-1.0,1.0
5,S6,institutional_role_relation,50,54,0.925926,1,1.0,1.0
6,S7,public_audience_relation,23,54,0.425926,1,1.0,1.0

In [6]:
# =============================================================================
# Notebook 07 — Block 3
# Full Social Annotation Worksheet
# =============================================================================

for row in BLOCK_3_WORKSHEET_ROWS:

    print("=" * 100)

    print(
        f"SOURCE ORDER : {row['source_order']}"
    )

    print(
        f"SENTENCE ID  : {row['sentence_id']}"
    )

    print("-" * 100)

    print(
        "PRECEDING CONTEXT:"
    )

    print(
        row["preceding_context"]
        if row["preceding_context"]
        else "[none]"
    )

    print("-" * 100)

    print(
        "CURRENT SENTENCE:"
    )

    print(
        row["current_sentence"]
    )

    print()

====================================================================================================
SOURCE ORDER : 0
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0000
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
[none]
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino.

====================================================================================================
SOURCE ORDER : 1
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0001
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino.
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
The governing body issued the statement in response to Uefa confirming on Saturday that a “departure payment” was made to a female employee who is alleged to have been in a relationship with Infantino while he was the organisation’s general secretary – allegations Fifa dismissed as “categorically untrue”.

====================================================================================================
SOURCE ORDER : 2
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0002
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino. The governing body issued the statement in response to Uefa confirming on Saturday that a “departure payment” was made to a female employee who is alleged to have been in a relationship with Infantino while he was the organisation’s general secretary – allegations Fifa dismissed as “categorically untrue”.
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
The Daily Telegraph reported on Friday night that the woman received a six-figure sum following the alleged relationship with Infantino.

====================================================================================================
SOURCE ORDER : 3
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0003
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino. The governing body issued the statement in response to Uefa confirming on Saturday that a “departure payment” was made to a female employee who is alleged to have been in a relationship with Infantino while he was the organisation’s general secretary – allegations Fifa dismissed as “categorically untrue”. The Daily Telegraph reported on Friday night that the woman received a six-figure sum following the alleged relationship with Infantino.
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
In a statement, Uefa confirmed a payment was made along with covering the fees for an MBA course, which it said was “in line” with regulations at the time.

====================================================================================================
SOURCE ORDER : 4
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0004
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino. The governing body issued the statement in response to Uefa confirming on Saturday that a “departure payment” was made to a female employee who is alleged to have been in a relationship with Infantino while he was the organisation’s general secretary – allegations Fifa dismissed as “categorically untrue”. The Daily Telegraph reported on Friday night that the woman received a six-figure sum following the alleged relationship with Infantino. In a statement, Uefa confirmed a payment was made along with covering the fees for an MBA course, which it said was “in line” with regulations at the time.
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
Fifa told the Telegraph that “any insinuation of inappropriate conduct or violation of statutes or regulations is defamatory”, and late on Saturday issued a new, broader statement attacking Infantino’s critics.

====================================================================================================
SOURCE ORDER : 5
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0005
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino. The governing body issued the statement in response to Uefa confirming on Saturday that a “departure payment” was made to a female employee who is alleged to have been in a relationship with Infantino while he was the organisation’s general secretary – allegations Fifa dismissed as “categorically untrue”. The Daily Telegraph reported on Friday night that the woman received a six-figure sum following the alleged relationship with Infantino. In a statement, Uefa confirmed a payment was made along with covering the fees for an MBA course, which it said was “in line” with regulations at the time. Fifa told the Telegraph that “any insinuation of inappropriate conduct or violation of statutes or regulations is defamatory”, and late on Saturday issued a new, broader statement attacking Infantino’s critics.
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
A Fifa spokesperson said: “The Fifa president was democratically elected by Fifa’s member associations and continues to serve with their mandate.

====================================================================================================
SOURCE ORDER : 6
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0006
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino. The governing body issued the statement in response to Uefa confirming on Saturday that a “departure payment” was made to a female employee who is alleged to have been in a relationship with Infantino while he was the organisation’s general secretary – allegations Fifa dismissed as “categorically untrue”. The Daily Telegraph reported on Friday night that the woman received a six-figure sum following the alleged relationship with Infantino. In a statement, Uefa confirmed a payment was made along with covering the fees for an MBA course, which it said was “in line” with regulations at the time. Fifa told the Telegraph that “any insinuation of inappropriate conduct or violation of statutes or regulations is defamatory”, and late on Saturday issued a new, broader statement attacking Infantino’s critics. A Fifa spokesperson said: “The Fifa president was democratically elected by Fifa’s member associations and continues to serve with their mandate.
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
It is increasingly evident that there is a concerted and ongoing effort by some to undermine Fifa and its president.

====================================================================================================
SOURCE ORDER : 7
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0007
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino. The governing body issued the statement in response to Uefa confirming on Saturday that a “departure payment” was made to a female employee who is alleged to have been in a relationship with Infantino while he was the organisation’s general secretary – allegations Fifa dismissed as “categorically untrue”. The Daily Telegraph reported on Friday night that the woman received a six-figure sum following the alleged relationship with Infantino. In a statement, Uefa confirmed a payment was made along with covering the fees for an MBA course, which it said was “in line” with regulations at the time. Fifa told the Telegraph that “any insinuation of inappropriate conduct or violation of statutes or regulations is defamatory”, and late on Saturday issued a new, broader statement attacking Infantino’s critics. A Fifa spokesperson said: “The Fifa president was democratically elected by Fifa’s member associations and continues to serve with their mandate. It is increasingly evident that there is a concerted and ongoing effort by some to undermine Fifa and its president.
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
“Those who do not have the support of Fifa’s member associations should not seek to achieve through allegation, insinuation or misinformation what they cannot achieve through Fifa’s established democratic processes.

====================================================================================================
SOURCE ORDER : 8
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0008
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino. The governing body issued the statement in response to Uefa confirming on Saturday that a “departure payment” was made to a female employee who is alleged to have been in a relationship with Infantino while he was the organisation’s general secretary – allegations Fifa dismissed as “categorically untrue”. The Daily Telegraph reported on Friday night that the woman received a six-figure sum following the alleged relationship with Infantino. In a statement, Uefa confirmed a payment was made along with covering the fees for an MBA course, which it said was “in line” with regulations at the time. Fifa told the Telegraph that “any insinuation of inappropriate conduct or violation of statutes or regulations is defamatory”, and late on Saturday issued a new, broader statement attacking Infantino’s critics. A Fifa spokesperson said: “The Fifa president was democratically elected by Fifa’s member associations and continues to serve with their mandate. It is increasingly evident that there is a concerted and ongoing effort by some to undermine Fifa and its president. “Those who do not have the support of Fifa’s member associations should not seek to achieve through allegation, insinuation or misinformation what they cannot achieve through Fifa’s established democratic processes.
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
Recent reporting has included unsubstantiated assertions and demonstrably false claims concerning Fifa and its president.

====================================================================================================
SOURCE ORDER : 9
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0009
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino. The governing body issued the statement in response to Uefa confirming on Saturday that a “departure payment” was made to a female employee who is alleged to have been in a relationship with Infantino while he was the organisation’s general secretary – allegations Fifa dismissed as “categorically untrue”. The Daily Telegraph reported on Friday night that the woman received a six-figure sum following the alleged relationship with Infantino. In a statement, Uefa confirmed a payment was made along with covering the fees for an MBA course, which it said was “in line” with regulations at the time. Fifa told the Telegraph that “any insinuation of inappropriate conduct or violation of statutes or regulations is defamatory”, and late on Saturday issued a new, broader statement attacking Infantino’s critics. A Fifa spokesperson said: “The Fifa president was democratically elected by Fifa’s member associations and continues to serve with their mandate. It is increasingly evident that there is a concerted and ongoing effort by some to undermine Fifa and its president. “Those who do not have the support of Fifa’s member associations should not seek to achieve through allegation, insinuation or misinformation what they cannot achieve through Fifa’s established democratic processes. Recent reporting has included unsubstantiated assertions and demonstrably false claims concerning Fifa and its president.
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
Speculation and insinuation should not be presented as fact, and repetition does not make an allegation true.”
Defending Infantino as a leader who has “dedicated more than 30 years of his professional life to European and world football”, the statement added: “Fifa welcomes legitimate scrutiny.

====================================================================================================
SOURCE ORDER : 10
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0010
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino. The governing body issued the statement in response to Uefa confirming on Saturday that a “departure payment” was made to a female employee who is alleged to have been in a relationship with Infantino while he was the organisation’s general secretary – allegations Fifa dismissed as “categorically untrue”. The Daily Telegraph reported on Friday night that the woman received a six-figure sum following the alleged relationship with Infantino. In a statement, Uefa confirmed a payment was made along with covering the fees for an MBA course, which it said was “in line” with regulations at the time. Fifa told the Telegraph that “any insinuation of inappropriate conduct or violation of statutes or regulations is defamatory”, and late on Saturday issued a new, broader statement attacking Infantino’s critics. A Fifa spokesperson said: “The Fifa president was democratically elected by Fifa’s member associations and continues to serve with their mandate. It is increasingly evident that there is a concerted and ongoing effort by some to undermine Fifa and its president. “Those who do not have the support of Fifa’s member associations should not seek to achieve through allegation, insinuation or misinformation what they cannot achieve through Fifa’s established democratic processes. Recent reporting has included unsubstantiated assertions and demonstrably false claims concerning Fifa and its president. Speculation and insinuation should not be presented as fact, and repetition does not make an allegation true.”
Defending Infantino as a leader who has “dedicated more than 30 years of his professional life to European and world football”, the statement added: “Fifa welcomes legitimate scrutiny.
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
But scrutiny is not a licence to distort facts, amplify unsubstantiated allegations or manufacture distractions designed to undermine progress.

====================================================================================================
SOURCE ORDER : 11
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0011
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:
Fifa has issued a new statement alleging there is a “concerted and ongoing effort by some to undermine Fifa and its president” as pressure increases on Gianni Infantino. The governing body issued the statement in response to Uefa confirming on Saturday that a “departure payment” was made to a female employee who is alleged to have been in a relationship with Infantino while he was the organisation’s general secretary – allegations Fifa dismissed as “categorically untrue”. The Daily Telegraph reported on Friday night that the woman received a six-figure sum following the alleged relationship with Infantino. In a statement, Uefa confirmed a payment was made along with covering the fees for an MBA course, which it said was “in line” with regulations at the time. Fifa told the Telegraph that “any insinuation of inappropriate conduct or violation of statutes or regulations is defamatory”, and late on Saturday issued a new, broader statement attacking Infantino’s critics. A Fifa spokesperson said: “The Fifa president was democratically elected by Fifa’s member associations and continues to serve with their mandate. It is increasingly evident that there is a concerted and ongoing effort by some to undermine Fifa and its president. “Those who do not have the support of Fifa’s member associations should not seek to achieve through allegation, insinuation or misinformation what they cannot achieve through Fifa’s established democratic processes. Recent reporting has included unsubstantiated assertions and demonstrably false claims concerning Fifa and its president. Speculation and insinuation should not be presented as fact, and repetition does not make an allegation true.”
Defending Infantino as a leader who has “dedicated more than 30 years of his professional life to European and world football”, the statement added: “Fifa welcomes legitimate scrutiny. But scrutiny is not a licence to distort facts, amplify unsubstantiated allegations or manufacture distractions designed to undermine progress.
----------------------------------------------------------------------------------------------------
CURRENT SENTENCE:
“Where reporting is inaccurate or misleading, Fifa will challenge it directly and vigorously.

====================================================================================================
SOURCE ORDER : 12
SENTENCE ID  : 1ef9745c-2c21-47c2-a222-e7c160448f82::p0000::s0012
----------------------------------------------------------------------------------------------------
PRECEDING CONTEXT:

In [7]:
# =============================================================================
# Notebook 07 — Block 3
# Explicit Social Representation Annotations
# =============================================================================

NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS = {

    # =========================================================================
    # 0
    # =========================================================================
    0: {
        "interpersonal_cohesion": {
            "value": -0.6,
            "available": True,
            "evidence": (
                "there is a 'concerted and ongoing effort by some "
                "to undermine Fifa and its president'"
            ),
            "annotator_note": (
                "Explicit adversarial relation between Fifa/Infantino "
                "and unnamed critics."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "No explicit economic-cohesion judgement."
            ),
        },

        "political_cohesion": {
            "value": -0.5,
            "available": True,
            "evidence": (
                "pressure increases on Gianni Infantino"
            ),
            "annotator_note": (
                "Institutional leadership contest and opposition are "
                "socially relevant, but the sentence does not yet specify "
                "formal democratic mechanisms."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": -0.6,
            "available": True,
            "evidence": (
                "concerted and ongoing effort by some to undermine Fifa"
            ),
            "annotator_note": (
                "Explicit collective opposition to an organisation "
                "and its leader."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Fifa ... its president"
            ),
            "annotator_note": (
                "Clear organisation-leader institutional relation."
            ),
        },

        "public_audience_relation": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "No explicit public or audience relation."
            ),
        },
    },


    # =========================================================================
    # 1
    # =========================================================================
    1: {
        "interpersonal_cohesion": {
            "value": -0.5,
            "available": True,
            "evidence": (
                "alleged to have been in a relationship with Infantino "
                "... allegations Fifa dismissed as 'categorically untrue'"
            ),
            "annotator_note": (
                "Interpersonal allegation is embedded in an adversarial "
                "institutional dispute."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "A departure payment is mentioned, but no economic "
                "cohesion or exclusion judgement is made."
            ),
        },

        "political_cohesion": {
            "value": -0.4,
            "available": True,
            "evidence": (
                "The governing body issued the statement in response "
                "to Uefa confirming"
            ),
            "annotator_note": (
                "Institutional conflict between governing bodies."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": -0.4,
            "available": True,
            "evidence": (
                "The governing body ... in response to Uefa"
            ),
            "annotator_note": (
                "Distinct organisations are positioned in conflict."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "governing body ... Uefa ... general secretary"
            ),
            "annotator_note": (
                "Multiple explicit organisational and role relations."
            ),
        },

        "public_audience_relation": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "No direct public/audience relation."
            ),
        },
    },


    # =========================================================================
    # 2
    # =========================================================================
    2: {
        "interpersonal_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "Relationship allegation is reported, but the sentence "
                "does not provide a cohesion judgement."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "A six-figure payment is reported, but no economic "
                "cohesion signal is expressed."
            ),
        },

        "political_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "No direct political-cohesion judgement in this sentence."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "No explicit group cohesion signal."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "The Daily Telegraph reported"
            ),
            "annotator_note": (
                "Explicit media-institution reporting relation."
            ),
        },

        "public_audience_relation": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "Reporting exists, but no explicit audience relation "
                "is expressed."
            ),
        },
    },


    # =========================================================================
    # 3
    # =========================================================================
    3: {
        "interpersonal_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "No explicit interpersonal cohesion signal."
            ),
        },

        "economic_cohesion": {
            "value": 0.0,
            "available": True,
            "evidence": (
                "payment was made along with covering the fees for "
                "an MBA course ... 'in line' with regulations"
            ),
            "annotator_note": (
                "Explicit financial/institutional transaction with no "
                "directional cohesion or conflict; therefore neutral."
            ),
        },

        "political_cohesion": {
            "value": 0.0,
            "available": True,
            "evidence": (
                "in line with regulations at the time"
            ),
            "annotator_note": (
                "Institutional compliance is asserted without a clear "
                "cohesive or divisive political direction."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "No group-cohesion judgement."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Uefa confirmed ... in line with regulations"
            ),
            "annotator_note": (
                "Clear organisational and regulatory role relation."
            ),
        },

        "public_audience_relation": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No explicit public relation.",
        },
    },


    # =========================================================================
    # 4
    # =========================================================================
    4: {
        "interpersonal_cohesion": {
            "value": -0.7,
            "available": True,
            "evidence": (
                "attacking Infantino's critics"
            ),
            "annotator_note": (
                "Explicit adversarial relation."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No economic-cohesion signal.",
        },

        "political_cohesion": {
            "value": -0.6,
            "available": True,
            "evidence": (
                "violation of statutes or regulations ... "
                "attacking Infantino's critics"
            ),
            "annotator_note": (
                "Institutional legitimacy and opposition are directly "
                "contested."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": -0.6,
            "available": True,
            "evidence": (
                "attacking Infantino's critics"
            ),
            "annotator_note": (
                "Clear division between Fifa leadership and critics."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Fifa told the Telegraph"
            ),
            "annotator_note": (
                "Organisation-media relation and institutional defence."
            ),
        },

        "public_audience_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Fifa told the Telegraph"
            ),
            "annotator_note": (
                "Institution communicates its position through media "
                "to a broader audience."
            ),
        },
    },


    # =========================================================================
    # 5
    # =========================================================================
    5: {
        "interpersonal_cohesion": {
            "value": 0.4,
            "available": True,
            "evidence": (
                "continues to serve with their mandate"
            ),
            "annotator_note": (
                "Explicit support relation between member associations "
                "and president."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No economic signal.",
        },

        "political_cohesion": {
            "value": 0.7,
            "available": True,
            "evidence": (
                "democratically elected by Fifa's member associations "
                "and continues to serve with their mandate"
            ),
            "annotator_note": (
                "Strong explicit legitimacy and democratic mandate signal."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": 0.5,
            "available": True,
            "evidence": (
                "Fifa's member associations ... their mandate"
            ),
            "annotator_note": (
                "Collective institutional support is explicitly asserted."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Fifa president ... democratically elected by "
                "Fifa's member associations"
            ),
            "annotator_note": (
                "Explicit leader/member-association institutional structure."
            ),
        },

        "public_audience_relation": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No explicit public/audience relation.",
        },
    },


    # =========================================================================
    # 6
    # =========================================================================
    6: {
        "interpersonal_cohesion": {
            "value": -0.7,
            "available": True,
            "evidence": (
                "concerted and ongoing effort by some to undermine "
                "Fifa and its president"
            ),
            "annotator_note": "Strong adversarial relation.",
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No economic-cohesion signal.",
        },

        "political_cohesion": {
            "value": -0.6,
            "available": True,
            "evidence": (
                "effort by some to undermine Fifa and its president"
            ),
            "annotator_note": (
                "Direct challenge to institutional leadership."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": -0.7,
            "available": True,
            "evidence": (
                "concerted and ongoing effort by some"
            ),
            "annotator_note": (
                "Explicit coalition-like opposition against Fifa leadership."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Fifa and its president"
            ),
            "annotator_note": "Organisation-leader relation.",
        },

        "public_audience_relation": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No explicit public/audience relation.",
        },
    },


    # =========================================================================
    # 7
    # =========================================================================
    7: {
        "interpersonal_cohesion": {
            "value": -0.6,
            "available": True,
            "evidence": (
                "Those who do not have the support of Fifa's member "
                "associations should not seek to achieve through allegation, "
                "insinuation or misinformation"
            ),
            "annotator_note": (
                "Explicit antagonism toward opponents."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No economic content.",
        },

        "political_cohesion": {
            "value": -0.7,
            "available": True,
            "evidence": (
                "what they cannot achieve through Fifa's established "
                "democratic processes"
            ),
            "annotator_note": (
                "Strong conflict around legitimacy and formal "
                "democratic procedures."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": -0.6,
            "available": True,
            "evidence": (
                "Those who do not have the support of Fifa's "
                "member associations"
            ),
            "annotator_note": (
                "Clear supported-group versus opposing-group framing."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Fifa's member associations ... established "
                "democratic processes"
            ),
            "annotator_note": (
                "Explicit institutional membership and governance relation."
            ),
        },

        "public_audience_relation": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No explicit public relation.",
        },
    },


    # =========================================================================
    # 8
    # =========================================================================
    8: {
        "interpersonal_cohesion": {
            "value": -0.5,
            "available": True,
            "evidence": (
                "unsubstantiated assertions and demonstrably false claims "
                "concerning Fifa and its president"
            ),
            "annotator_note": (
                "Adversarial media/institutional relation."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No economic signal.",
        },

        "political_cohesion": {
            "value": -0.4,
            "available": True,
            "evidence": (
                "false claims concerning Fifa and its president"
            ),
            "annotator_note": (
                "Institutional contestation remains present."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": -0.4,
            "available": True,
            "evidence": (
                "claims concerning Fifa and its president"
            ),
            "annotator_note": (
                "Conflict between institution and external reporting actors."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Fifa and its president"
            ),
            "annotator_note": "Institution-leader relation.",
        },

        "public_audience_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Recent reporting has included"
            ),
            "annotator_note": (
                "Media reporting constitutes a relation to a broader public."
            ),
        },
    },


    # =========================================================================
    # 9
    # =========================================================================
    9: {
        "interpersonal_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "The sentence is primarily epistemic/media-normative."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No economic signal.",
        },

        "political_cohesion": {
            "value": 0.2,
            "available": True,
            "evidence": (
                "Fifa welcomes legitimate scrutiny"
            ),
            "annotator_note": (
                "Qualified acceptance of accountability provides a weak "
                "positive institutional-cohesion signal."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "No sufficiently distinct group-cohesion judgement."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Defending Infantino as a leader ... Fifa welcomes "
                "legitimate scrutiny"
            ),
            "annotator_note": (
                "Explicit leader/institution relation."
            ),
        },

        "public_audience_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Speculation and insinuation should not be presented as fact"
            ),
            "annotator_note": (
                "Explicit norm directed at reporting and public information."
            ),
        },
    },


    # =========================================================================
    # 10
    # =========================================================================
    10: {
        "interpersonal_cohesion": {
            "value": -0.5,
            "available": True,
            "evidence": (
                "distort facts, amplify unsubstantiated allegations or "
                "manufacture distractions designed to undermine progress"
            ),
            "annotator_note": (
                "Explicit conflict with critics/reporting actors."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No economic signal.",
        },

        "political_cohesion": {
            "value": -0.4,
            "available": True,
            "evidence": (
                "designed to undermine progress"
            ),
            "annotator_note": (
                "Institutional progress is framed as being attacked."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": -0.4,
            "available": True,
            "evidence": (
                "amplify unsubstantiated allegations"
            ),
            "annotator_note": (
                "Adversarial institutional-versus-critics framing."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "scrutiny ... undermine progress"
            ),
            "annotator_note": (
                "Institutional accountability relation is explicit "
                "from preceding sentence."
            ),
        },

        "public_audience_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "scrutiny ... distort facts, amplify unsubstantiated "
                "allegations"
            ),
            "annotator_note": (
                "Explicit relation to public/media scrutiny."
            ),
        },
    },


    # =========================================================================
    # 11
    # =========================================================================
    11: {
        "interpersonal_cohesion": {
            "value": -0.5,
            "available": True,
            "evidence": (
                "Fifa will challenge it directly and vigorously"
            ),
            "annotator_note": (
                "Explicit confrontational response."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No economic signal.",
        },

        "political_cohesion": {
            "value": -0.3,
            "available": True,
            "evidence": (
                "Fifa will challenge it directly and vigorously"
            ),
            "annotator_note": (
                "Institutional confrontation with reporting."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": -0.3,
            "available": True,
            "evidence": (
                "Where reporting is inaccurate or misleading, "
                "Fifa will challenge it"
            ),
            "annotator_note": (
                "Institution-versus-reporting opposition."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Fifa will challenge it"
            ),
            "annotator_note": (
                "Institutional actor responding in its organisational role."
            ),
        },

        "public_audience_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Where reporting is inaccurate or misleading"
            ),
            "annotator_note": (
                "Explicit relation to reporting consumed by a public."
            ),
        },
    },


    # =========================================================================
    # 12
    # =========================================================================
    12: {
        "interpersonal_cohesion": {
            "value": 0.5,
            "available": True,
            "evidence": (
                "Fifa's responsibility is to its 211 member associations"
            ),
            "annotator_note": (
                "Explicit responsibility/support relation."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No economic-cohesion signal.",
        },

        "political_cohesion": {
            "value": 0.5,
            "available": True,
            "evidence": (
                "responsibility is to its 211 member associations"
            ),
            "annotator_note": (
                "Institutional accountability toward constituent members."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": 0.8,
            "available": True,
            "evidence": (
                "its 211 member associations and to football "
                "around the world"
            ),
            "annotator_note": (
                "Strong collective membership and global belonging signal."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Fifa's responsibility is to its 211 member associations"
            ),
            "annotator_note": (
                "Direct institution-to-members relation."
            ),
        },

        "public_audience_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "football around the world"
            ),
            "annotator_note": (
                "Explicit broader global community relation."
            ),
        },
    },


    # =========================================================================
    # 13
    # =========================================================================
    13: {
        "interpersonal_cohesion": {
            "value": 0.3,
            "available": True,
            "evidence": (
                "delivering for our member associations"
            ),
            "annotator_note": (
                "Positive support/service relation."
            ),
        },

        "economic_cohesion": {
            "value": -0.2,
            "available": True,
            "evidence": (
                "exposure and collapse of his plan to seek private "
                "investment in a company which would run Fifa's competitions"
            ),
            "annotator_note": (
                "Economic governance conflict is present, but the sentence "
                "does not imply broad economic inequality; weak negative "
                "cohesion is therefore used."
            ),
        },

        "political_cohesion": {
            "value": 0.2,
            "available": True,
            "evidence": (
                "strengthening the organisation, delivering for our "
                "member associations"
            ),
            "annotator_note": (
                "Positive institutional mission is asserted, though "
                "preceding pressure tempers the signal."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": 0.5,
            "available": True,
            "evidence": (
                "delivering for our member associations and ... "
                "making football truly global"
            ),
            "annotator_note": (
                "Explicit collective/global inclusion framing."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "strengthening the organisation ... member associations"
            ),
            "annotator_note": (
                "Clear organisation-member relation."
            ),
        },

        "public_audience_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "making football truly global"
            ),
            "annotator_note": (
                "Explicit relation to a global football community."
            ),
        },
    },


    # =========================================================================
    # 14
    # =========================================================================
    14: {
        "interpersonal_cohesion": {
            "value": -0.5,
            "available": True,
            "evidence": (
                "will not accept any challenge to Infantino's position"
            ),
            "annotator_note": (
                "Explicit opposition toward challengers."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "Private-investment context exists in the preceding sentence, "
                "but the current sentence concerns leadership challenge."
            ),
        },

        "political_cohesion": {
            "value": -0.7,
            "available": True,
            "evidence": (
                "will not accept any challenge to Infantino's position "
                "before the election next March"
            ),
            "annotator_note": (
                "Strong leadership/electoral contestation signal."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": -0.4,
            "available": True,
            "evidence": (
                "any challenge to Infantino's position"
            ),
            "annotator_note": (
                "Institutional opposition is explicit, though groups "
                "are not fully specified."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Infantino's position ... election next March"
            ),
            "annotator_note": (
                "Institutional office and electoral procedure."
            ),
        },

        "public_audience_relation": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "No direct public/audience relationship."
            ),
        },
    },


    # =========================================================================
    # 15
    # =========================================================================
    15: {
        "interpersonal_cohesion": {
            "value": -0.8,
            "available": True,
            "evidence": (
                "Uefa's threat that its 55 member countries could boycott "
                "Fifa competitions remains in place"
            ),
            "annotator_note": (
                "Very strong adversarial relation between organisations."
            ),
        },

        "economic_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": (
                "Boycott could have economic consequences, but those are "
                "not asserted in the sentence."
            ),
        },

        "political_cohesion": {
            "value": -0.9,
            "available": True,
            "evidence": (
                "55 member countries could boycott Fifa competitions"
            ),
            "annotator_note": (
                "Strong institutional and collective political rupture."
            ),
        },

        "religious_cohesion": {
            "value": None,
            "available": False,
            "evidence": None,
            "annotator_note": "No religious content.",
        },

        "group_collective_cohesion": {
            "value": -0.9,
            "available": True,
            "evidence": (
                "55 member countries could boycott Fifa competitions"
            ),
            "annotator_note": (
                "Strong collective opposition by a large member bloc."
            ),
        },

        "institutional_role_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "Uefa ... its 55 member countries ... Fifa competitions"
            ),
            "annotator_note": (
                "Explicit confederation-member-country-Fifa relation."
            ),
        },

        "public_audience_relation": {
            "value": 1.0,
            "available": True,
            "evidence": (
                "European confederation saying on Thursday"
            ),
            "annotator_note": (
                "Public institutional communication is explicit."
            ),
        },
    },
}
# =============================================================================
# Manual annotation input controls
# =============================================================================

BLOCK_3_MANUAL_ANNOTATION_RECORD_COUNT = len(
    NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS
)

BLOCK_3_EXPECTED_MANUAL_ANNOTATION_RECORD_COUNT = 16

BLOCK_3_MANUAL_ANNOTATION_RECORD_COUNT_VALID = (
    BLOCK_3_MANUAL_ANNOTATION_RECORD_COUNT
    ==
    BLOCK_3_EXPECTED_MANUAL_ANNOTATION_RECORD_COUNT
)


BLOCK_3_EXPECTED_SOCIAL_DIMENSIONS = {
    "interpersonal_cohesion",
    "economic_cohesion",
    "political_cohesion",
    "religious_cohesion",
    "group_collective_cohesion",
    "institutional_role_relation",
    "public_audience_relation",
}


BLOCK_3_MANUAL_ANNOTATION_DIMENSIONS_VALID = all(
    set(annotation.keys())
    ==
    BLOCK_3_EXPECTED_SOCIAL_DIMENSIONS

    for annotation
    in NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS.values()
)


BLOCK_3_MANUAL_ANNOTATION_STRUCTURE_VALID = all(
    isinstance(dimension_annotation, dict)
    and "value" in dimension_annotation
    and "available" in dimension_annotation
    and "evidence" in dimension_annotation
    and "annotator_note" in dimension_annotation

    for annotation
    in NOTEBOOK_07_SOCIAL_MANUAL_ANNOTATIONS.values()

    for dimension_annotation
    in annotation.values()
)


BLOCK_3_MANUAL_ANNOTATION_INPUT_VALID = all(
    [
        BLOCK_3_MANUAL_ANNOTATION_RECORD_COUNT_VALID,
        BLOCK_3_MANUAL_ANNOTATION_DIMENSIONS_VALID,
        BLOCK_3_MANUAL_ANNOTATION_STRUCTURE_VALID,
    ]
)


if not BLOCK_3_MANUAL_ANNOTATION_INPUT_VALID:

    raise RuntimeError(
        "Notebook 07 Social Representation manual annotation "
        "input failed structural validation."
    )


# =============================================================================
# Manual annotation input report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 07, Block 3: "
    "Manual Social Annotation Input"
)

print("=" * 72)

print(
    f"Annotation records           : "
    f"{BLOCK_3_MANUAL_ANNOTATION_RECORD_COUNT}"
)

print(
    f"Expected records             : "
    f"{BLOCK_3_EXPECTED_MANUAL_ANNOTATION_RECORD_COUNT}"
)

print(
    f"Record count valid           : "
    f"{BLOCK_3_MANUAL_ANNOTATION_RECORD_COUNT_VALID}"
)

print(
    f"Social dimensions            : "
    f"{len(BLOCK_3_EXPECTED_SOCIAL_DIMENSIONS)}"
)

print(
    f"Dimension contract valid     : "
    f"{BLOCK_3_MANUAL_ANNOTATION_DIMENSIONS_VALID}"
)

print(
    f"Annotation structure valid   : "
    f"{BLOCK_3_MANUAL_ANNOTATION_STRUCTURE_VALID}"
)

print(
    f"Manual annotation input valid: "
    f"{BLOCK_3_MANUAL_ANNOTATION_INPUT_VALID}"
)

print("=" * 72)

print(
    "Explicit Social Representation annotations are initialised."
)

print(
    "No model-generated labels have been added by this control section."
)

print(
    "The existing Notebook 07 Block 3 may now be rerun to perform "
    "the full evidence audit and accepted-supervision construction."
)

print("=" * 72)

========================================================================
Media AI — Notebook 07, Block 3: Manual Social Annotation Input
========================================================================
Annotation records           : 16
Expected records             : 16
Record count valid           : True
Social dimensions            : 7
Dimension contract valid     : True
Annotation structure valid   : True
Manual annotation input valid: True
========================================================================
Explicit Social Representation annotations are initialised.
No model-generated labels have been added by this control section.
The existing Notebook 07 Block 3 may now be rerun to perform the full evidence audit and accepted-supervision construction.
========================================================================

## Block 4: Social Target Availability, Variability, Activation and Loss-Contract Analysis

### Purpose

This block determines which dimensions of the seven-dimensional Social
Representation are eligible for controlled optimisation under the currently
accepted supervision.

The block consumes the accepted Social Representation supervision constructed
and persisted by Block 3. Each social dimension is audited independently for
supervision availability, target-domain validity, observed variability,
supervision sufficiency, activation eligibility and compatible loss semantics.

No unavailable value is converted to numerical zero or negative evidence.
Masked supervision remains excluded from all statistical and objective-policy
decisions.

Successful completion of this block establishes a validated Social
Representation objective contract. It does not train a Social Representation
model.


### Accepted supervision boundary

Block 4 must consume the accepted Block 3 supervision without reconstructing,
reinterpreting or automatically extending the manual annotations.

The expected accepted supervision consists of:

- 16 canonical sentence records;
- 7 Social Representation dimensions;
- a 16 × 7 target matrix;
- a corresponding 16 × 7 availability mask;
- explicit textual evidence for every available annotation;
- masked values where supervision is unavailable.

The canonical sentence identity, sentence ordering and article boundary
established by the preceding notebooks remain authoritative.

Aggregate Social Representation coverage is retained as an audit statistic
only. It is not used as an optimisation threshold.


### Social Representation semantic contract

The seven-dimensional ontology established in Block 2 remains unchanged:

- S1 — `interpersonal_cohesion`
- S2 — `economic_cohesion`
- S3 — `political_cohesion`
- S4 — `religious_cohesion`
- S5 — `group_collective_cohesion`
- S6 — `institutional_role_relation`
- S7 — `public_audience_relation`

No dimension may be removed, fabricated, renamed or semantically redefined by
this block.


### Target-family contract

S1–S5 are signed cohesion dimensions.

Their observed supervision must lie within the closed interval:

`[-1.0, 1.0]`

These targets preserve graded cohesion, neutrality and conflict information and
therefore belong to a continuous signed-target family.

S6 and S7 are binary social-structure dimensions.

Their observed supervision must belong to:

`{0.0, 1.0}`

Binary zero represents explicitly observed absence. It must remain distinct
from unavailable supervision.


### Availability and variability audit

For every Social Representation dimension, Block 4 must independently
reproduce and validate:

- available target count;
- masked target count;
- supervision coverage;
- unique observed target count;
- observed minimum;
- observed maximum;
- observed mean;
- observed variance;
- target-domain validity;
- presence or absence of usable target variation.

Coverage and variability are separate properties.

High supervision coverage does not establish optimisation eligibility when the
observed target is constant.

Likewise, the existence of target variation does not by itself establish
optimisation eligibility when the number of observed examples is too small for
the current controlled training stage.


### Supervision-sufficiency policy

Activation requires an explicit minimum-supervision policy rather than an
implicit judgement based on the current sample.

For the present controlled Social Representation stage, a dimension must have
at least three explicitly observed target values before it may become an active
objective.

This threshold is a methodological safeguard for the current small sample. It
does not establish statistical adequacy, generalisation or empirical validity.

A dimension below this threshold remains structurally present but is deferred
for insufficient supervision.

Missing values must never be inferred, generated or converted to neutral values
to satisfy the minimum-supervision requirement.


### Activation policy

A Social Representation dimension may become active only when all of the
following conditions hold:

1. explicit supervision is available;
2. the minimum observed-supervision requirement is satisfied;
3. all observed values satisfy the declared target-domain contract;
4. the observed target contains usable variation;
5. a compatible mask-aware loss family can be defined without fabricating or
   reinterpreting supervision.

A dimension failing any condition remains structurally present in the
seven-dimensional Social Representation but is excluded from the current
controlled optimisation objective.

Deferral is sample-specific and does not alter the semantic or architectural
status of the dimension.


### Expected current activation state

The accepted Block 3 supervision currently implies the following expected
diagnostic outcome:

| Dimension | Available | Expected state | Expected reason |
|---|---:|---|---|
| S1 `interpersonal_cohesion` | 13 / 16 | Active | sufficient supervision and observed variation |
| S2 `economic_cohesion` | 2 / 16 | Deferred | insufficient supervision |
| S3 `political_cohesion` | 15 / 16 | Active | sufficient supervision and observed variation |
| S4 `religious_cohesion` | 0 / 16 | Deferred | supervision unavailable |
| S5 `group_collective_cohesion` | 13 / 16 | Active | sufficient supervision and observed variation |
| S6 `institutional_role_relation` | 16 / 16 | Deferred | zero observed target variance |
| S7 `public_audience_relation` | 8 / 16 | Deferred | zero observed target variance |

The expected active dimensions are therefore:

`S1, S3, S5`

The expected deferred dimensions are:

`S2, S4, S6, S7`

These outcomes must be reproduced computationally from the accepted Block 3
supervision. They must not be established merely by hard-coding the values
printed by Block 3.


### Deferral semantics

The expected deferral reasons remain distinct:

- S2 is deferred because the current sample contains too few explicitly
  observed targets, despite containing observed variation;
- S4 is deferred because no explicit supervision is currently available;
- S6 is deferred because all observed targets are constant at 1.0;
- S7 is deferred because all observed targets are constant at 1.0.

Insufficient supervision, unavailable supervision and zero variance are
different methodological states and must not be collapsed into a single
generic inactive state.


### Loss-contract analysis

Block 4 resolves loss semantics only for dimensions satisfying the activation
policy.

For active signed-cohesion dimensions, the compatible objective family is
mask-aware continuous regression.

Given the current signed numerical target contract, masked mean-squared error
is the expected controlled loss family for S1, S3 and S5, subject to explicit
validation by this block.

The loss for each active dimension must be calculated only over explicitly
observed target elements.

For S6 and S7, binary cross-entropy with logits remains the prospective loss
family because they are binary social-structure dimensions. Neither objective
may become active while its currently observed supervision has zero variance.

No sigmoid transformation is to be applied manually before any future
binary-cross-entropy-with-logits objective.

No loss is assigned to a deferred dimension for the current optimisation
stage.


### Objective weighting boundary

Block 4 may define the active objective families and their eligibility, but it
does not yet need to construct an optimiser or execute training.

If equal weighting across active Social Representation dimensions is adopted,
that weighting must be stated explicitly and subsequently validated before
optimisation.

Deferred dimensions must contribute zero objective weight by exclusion rather
than by fabricated zero-valued targets.


### Representation and architectural boundary

The Social Representation remains a distinct representation component.

The completed psychological representation remains frozen.

The completed factual representation remains frozen.

The backbone remains frozen by default.

The mandatory global confluent representation remains frozen and operational.

The optional group-conditioned confluent path remains architecturally
available but inactive and deferred to Notebook 10.

The Transformative Mechanism remains deferred to Notebook 08.

Transformative Weights and recurrent processing remain deferred to Notebook 09.

Block 4 does not instantiate or train a Social Representation head merely
because one or more objectives become eligible.


### Validation requirements

Block 4 must verify that:

- Notebook 07 Blocks 1–3 are complete and valid;
- the persisted Block 3 accepted-supervision artefact is available;
- the accepted supervision is restored without semantic reconstruction;
- sentence identities remain present and unique;
- sentence alignment with the Notebook 07 canonical contract is exact;
- the target matrix has shape `(16, 7)`;
- the mask matrix has shape `(16, 7)`;
- every observed target value is finite;
- S1–S5 observed values remain within `[-1.0, 1.0]`;
- S6–S7 observed values remain within `{0.0, 1.0}`;
- unavailable supervision remains excluded through the mask;
- per-dimension availability reproduces Block 3;
- per-dimension variability is calculated from observed values only;
- the minimum-supervision policy is applied explicitly;
- S1, S3 and S5 satisfy the current activation policy;
- S2 is deferred for insufficient supervision;
- S4 is deferred for unavailable supervision;
- S6 and S7 are deferred for zero observed variance;
- no social dimension is fabricated or removed;
- no previous supervision artefact is modified.


### Readiness boundary

Successful Block 4 completion should establish:

- Social target availability validated;
- Social target variability validated;
- Social activation policy resolved;
- active Social Representation dimensions resolved;
- deferred Social Representation dimensions resolved;
- dimension-specific deferral reasons resolved;
- active loss families resolved;
- Social objective contract valid.

This establishes readiness for controlled Social Representation model
construction and forward-path validation.

It does not yet establish readiness for parameter optimisation unless the
subsequent model and parameter-freezing contract is also validated.


### Execution boundary

Block 4 performs supervision analysis and objective-policy resolution only.

It must not:

- train or update a Social Representation head;
- perform a Social Representation model forward pass;
- create an optimiser;
- execute `zero_grad`;
- execute a backward pass;
- execute an optimiser step;
- update any model parameter;
- retrain the psychological representation;
- retrain the factual representation;
- activate the optional group-conditioned path;
- activate the Transformative Mechanism;
- activate Transformative Weights;
- activate recurrent processing;
- perform held-out evaluation;
- claim generalisation;
- establish empirical validity.

Successful Block 4 completion establishes objective-policy readiness, not
prediction quality or empirical validity.


### Expected Block 4 outcome

Under the currently accepted supervision, Block 4 is expected to establish:

- S1 `interpersonal_cohesion` — active;
- S2 `economic_cohesion` — deferred for insufficient supervision;
- S3 `political_cohesion` — active;
- S4 `religious_cohesion` — deferred for unavailable supervision;
- S5 `group_collective_cohesion` — active;
- S6 `institutional_role_relation` — deferred for zero variance;
- S7 `public_audience_relation` — deferred for zero variance.

The resulting controlled active Social Representation is therefore expected to
contain three currently trainable dimensions while preserving all seven
dimensions structurally.

The next block may proceed to:

**Social Representation Model Restoration, Parameter-Freezing Policy and
Controlled Forward-Path Validation.**
"""

In [14]:
# =============================================================================
# Media AI — Notebook 07
# Block 4: Social Target Availability, Variability,
#          Activation and Loss-Contract Analysis
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json

import numpy as np
import pandas as pd

from googleapiclient.http import MediaIoBaseDownload


# =============================================================================
# Dependency checks
# =============================================================================

required_block_4_objects = [
    "NOTEBOOK_07_BLOCK_1_COMPLETE",
    "NOTEBOOK_07_BLOCK_1_VALID",
    "NOTEBOOK_07_BLOCK_2_COMPLETE",
    "NOTEBOOK_07_BLOCK_2_VALID",
    "NOTEBOOK_07_BLOCK_3_COMPLETE",
    "NOTEBOOK_07_BLOCK_3_VALID",

    "NOTEBOOK_07_DRIVE_SERVICE",

    "NOTEBOOK_07_SENTENCE_IDS",
    "NOTEBOOK_07_SENTENCE_COUNT",

    "NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_SOCIAL_DIMENSION_IDS",
    "NOTEBOOK_07_SOCIAL_DIMENSION_ORDER",
    "NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS",

    "NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_FILE_ID",
    "NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_FILENAME",

    "NOTEBOOK_07_READY_FOR_SOCIAL_TARGET_AVAILABILITY_AUDIT",

    "NOTEBOOK_07_SOCIAL_MASK_AWARE_SUPERVISION",
    "NOTEBOOK_07_SOCIAL_PARTIAL_SUPERVISION_ALLOWED",
    "NOTEBOOK_07_SOCIAL_MISSING_EQUALS_ZERO",
    "NOTEBOOK_07_SOCIAL_MISSING_EQUALS_NEGATIVE",
    "NOTEBOOK_07_SOCIAL_UNAVAILABLE_ENTERS_LOSS",
]


missing_block_4_objects = [
    object_name
    for object_name
    in required_block_4_objects
    if object_name not in globals()
]


if missing_block_4_objects:

    raise NameError(
        "Notebook 07 Block 4 prerequisites are not initialised. "
        f"Missing: {missing_block_4_objects}"
    )


if not all(
    [
        NOTEBOOK_07_BLOCK_1_COMPLETE,
        NOTEBOOK_07_BLOCK_1_VALID,
        NOTEBOOK_07_BLOCK_2_COMPLETE,
        NOTEBOOK_07_BLOCK_2_VALID,
        NOTEBOOK_07_BLOCK_3_COMPLETE,
        NOTEBOOK_07_BLOCK_3_VALID,
    ]
):

    raise RuntimeError(
        "Notebook 07 Blocks 1–3 must be complete and valid "
        "before Block 4."
    )


if not NOTEBOOK_07_READY_FOR_SOCIAL_TARGET_AVAILABILITY_AUDIT:

    raise RuntimeError(
        "Notebook 07 is not ready for Social Representation "
        "target-availability analysis."
    )


if NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM != 7:

    raise RuntimeError(
        "Block 4 requires the validated seven-dimensional "
        "Social Representation."
    )


if len(
    NOTEBOOK_07_SOCIAL_DIMENSION_IDS
) != NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM:

    raise RuntimeError(
        "Social dimension-ID count does not match representation dimension."
    )


if len(
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
) != NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM:

    raise RuntimeError(
        "Social dimension-order count does not match "
        "representation dimension."
    )


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_07_BLOCK_4 = 4

NOTEBOOK_07_BLOCK_4_NAME = (
    "Social Target Availability, Variability, "
    "Activation and Loss-Contract Analysis"
)

NOTEBOOK_07_BLOCK_4_VERSION = "1.4"

NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VERSION = "1.4"


BLOCK_4_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Controlled supervision-sufficiency policy
# =============================================================================
#
# This is a methodological threshold for the present very small controlled
# sample. It is NOT a statistical sufficiency or generalisation threshold.
#
# A dimension requires at least three explicitly observed values before it
# may enter the current controlled Social Representation objective.
# =============================================================================

NOTEBOOK_07_SOCIAL_MINIMUM_OBSERVED_TARGETS = 3


# =============================================================================
# Execution boundary
# =============================================================================

NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED = False

NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED = False

NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_LOSS_CALCULATED = False

NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED = False

NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED = False

NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED = False

NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED = False

NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Drive download helper
# =============================================================================

def block_4_download_drive_bytes(
    drive_service,
    file_id,
):
    """
    Download one Google Drive file and return raw bytes.
    """

    request = (
        drive_service.files()
        .get_media(
            fileId=file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Reload accepted Block 3 Social Representation supervision
# =============================================================================

BLOCK_4_ACCEPTED_BYTES = (
    block_4_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_FILE_ID,
    )
)


if not BLOCK_4_ACCEPTED_BYTES:

    raise RuntimeError(
        "Persisted accepted Social Representation supervision was empty."
    )


try:

    BLOCK_4_ACCEPTED_ARTEFACT = json.loads(
        BLOCK_4_ACCEPTED_BYTES.decode(
            "utf-8"
        )
    )


except (
    UnicodeDecodeError,
    json.JSONDecodeError,
) as error:

    raise RuntimeError(
        "Persisted accepted Social Representation supervision "
        "is not valid UTF-8 JSON."
    ) from error


BLOCK_4_ACCEPTED_ARTEFACT_RELOADED = True


# =============================================================================
# Accepted artefact contract validation
# =============================================================================
#
# Block 4 validates the exact persisted contract produced by Block 3 v1.2.
# Supervision may be human, LLM, or an explicitly unsupervised canonical row.
# Provider/model provenance for machine supervision is stored at annotation
# level by Block 3 and is therefore validated there rather than assumed to
# exist at record level.
# =============================================================================

BLOCK_4_ACCEPTED_TYPE_VALID = (
    BLOCK_4_ACCEPTED_ARTEFACT.get(
        "artefact_type"
    )
    ==
    "media_ai_accepted_social_supervision"
)


BLOCK_4_ACCEPTED_VERSION = (
    BLOCK_4_ACCEPTED_ARTEFACT.get(
        "artefact_version"
    )
)


BLOCK_4_ACCEPTED_VERSION_PRESENT = bool(
    BLOCK_4_ACCEPTED_VERSION
)


BLOCK_4_ACCEPTED_ARCHITECTURE = (
    BLOCK_4_ACCEPTED_ARTEFACT.get(
        "architecture",
        {},
    )
)


BLOCK_4_ACCEPTED_DIMENSION_VALID = (
    BLOCK_4_ACCEPTED_ARCHITECTURE.get(
        "representation_dimension"
    )
    ==
    NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
)


BLOCK_4_ACCEPTED_DIMENSION_ORDER_VALID = (
    tuple(
        BLOCK_4_ACCEPTED_ARCHITECTURE.get(
            "dimension_order",
            [],
        )
    )
    ==
    tuple(
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
    )
)


BLOCK_4_ACCEPTED_DIMENSION_IDS_VALID = (
    tuple(
        BLOCK_4_ACCEPTED_ARCHITECTURE.get(
            "dimension_ids",
            [],
        )
    )
    ==
    tuple(
        NOTEBOOK_07_SOCIAL_DIMENSION_IDS
    )
)


BLOCK_4_ACCEPTED_RECORDS = deepcopy(
    BLOCK_4_ACCEPTED_ARTEFACT.get(
        "records",
        [],
    )
)


BLOCK_4_ACCEPTED_RECORD_COUNT_VALID = (
    len(
        BLOCK_4_ACCEPTED_RECORDS
    )
    ==
    NOTEBOOK_07_SENTENCE_COUNT
)


# =============================================================================
# Persisted Block 3 supervision contract
# =============================================================================

BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT = (
    BLOCK_4_ACCEPTED_ARTEFACT.get(
        "supervision_contract",
        {},
    )
)


BLOCK_4_ACCEPTED_SUPPORTED_SOURCES = set(
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "supported_sources",
        [],
    )
)


BLOCK_4_ACCEPTED_SUPPORTED_SOURCES_VALID = (
    {
        "human",
        "llm",
    }.issubset(
        BLOCK_4_ACCEPTED_SUPPORTED_SOURCES
    )
)


BLOCK_4_ACCEPTED_LABELS_NOT_GENERATED = (
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "labels_generated_by_block_3"
    )
    is False
)


BLOCK_4_ACCEPTED_REVIEW_STATUS_VALID = (
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "accepted_review_status"
    )
    ==
    "accepted"
)


BLOCK_4_ACCEPTED_EVIDENCE_REQUIRED = (
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "evidence_required_for_available"
    )
    is True
)


BLOCK_4_ACCEPTED_PROVENANCE_REQUIRED = (
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "provenance_required"
    )
    is True
)


BLOCK_4_ACCEPTED_PARTIAL_SENTENCE_COVERAGE = (
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "partial_sentence_coverage_allowed"
    )
    is True
)


BLOCK_4_ACCEPTED_PARTIAL_DIMENSION_COVERAGE = (
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "partial_dimension_coverage_allowed"
    )
    is True
)


BLOCK_4_ACCEPTED_MASK_AWARE = (
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "mask_aware"
    )
    is True
)


BLOCK_4_ACCEPTED_MISSING_NOT_ZERO = (
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "missing_equals_zero"
    )
    is False
)


BLOCK_4_ACCEPTED_MISSING_NOT_NEGATIVE = (
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "missing_equals_negative"
    )
    is False
)


BLOCK_4_ACCEPTED_UNAVAILABLE_EXCLUDED = (
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "unavailable_enters_loss"
    )
    is False
)


BLOCK_4_ACCEPTED_FUTURE_CONTEXT_PROHIBITED = (
    BLOCK_4_ACCEPTED_SUPERVISION_CONTRACT.get(
        "future_context_allowed"
    )
    is False
)


# =============================================================================
# Persisted training boundary
# =============================================================================

BLOCK_4_ACCEPTED_TRAINING_BOUNDARY = (
    BLOCK_4_ACCEPTED_ARTEFACT.get(
        "training_boundary",
        {},
    )
)


BLOCK_4_ACCEPTED_TARGET_CONTRACT_DEFINED = (
    BLOCK_4_ACCEPTED_TRAINING_BOUNDARY.get(
        "target_contract_defined"
    )
    is True
)


BLOCK_4_ACCEPTED_TARGET_CONTRACT_VALID = (
    BLOCK_4_ACCEPTED_TRAINING_BOUNDARY.get(
        "target_contract_valid"
    )
    is True
)


BLOCK_4_ACCEPTED_OPTIMISATION_NOT_READY = (
    BLOCK_4_ACCEPTED_TRAINING_BOUNDARY.get(
        "optimisation_ready"
    )
    is False
)


BLOCK_4_ACCEPTED_TRAINING_NOT_EXECUTED = (
    BLOCK_4_ACCEPTED_TRAINING_BOUNDARY.get(
        "training_executed"
    )
    is False
)


# =============================================================================
# Provenance and evidence audit
# =============================================================================

BLOCK_4_ACCEPTED_PROVENANCE_SOURCES = []

BLOCK_4_ACCEPTED_PROVENANCE_VALID = True

BLOCK_4_AVAILABLE_ANNOTATIONS_WITH_EVIDENCE_VALID = True

BLOCK_4_ANNOTATION_LEVEL_LLM_PROVENANCE_VALID = True

BLOCK_4_ANNOTATION_LEVEL_SOURCE_ALIGNMENT_VALID = True


for record in BLOCK_4_ACCEPTED_RECORDS:

    if not isinstance(
        record,
        dict,
    ):

        BLOCK_4_ACCEPTED_PROVENANCE_VALID = False
        continue


    supervision_source = record.get(
        "supervision_source"
    )


    if supervision_source not in {
        "none",
        "human",
        "llm",
    }:

        BLOCK_4_ACCEPTED_PROVENANCE_VALID = False


    BLOCK_4_ACCEPTED_PROVENANCE_SOURCES.append(
        supervision_source
    )


    supervisor_id = record.get(
        "supervisor_id"
    )


    review_status = record.get(
        "review_status"
    )


    if supervision_source in {
        "human",
        "llm",
    }:

        if not (
            isinstance(
                supervisor_id,
                str,
            )
            and
            supervisor_id.strip()
        ):

            BLOCK_4_ACCEPTED_PROVENANCE_VALID = False


        if review_status != "accepted":

            BLOCK_4_ACCEPTED_PROVENANCE_VALID = False


    elif supervision_source == "none":

        if review_status != "not_supervised":

            BLOCK_4_ACCEPTED_PROVENANCE_VALID = False


    social_annotations = record.get(
        "social_annotations",
        {},
    )


    if not isinstance(
        social_annotations,
        dict,
    ):

        BLOCK_4_ACCEPTED_PROVENANCE_VALID = False
        continue


    if (
        set(
            social_annotations.keys()
        )
        !=
        set(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
        )
    ):

        BLOCK_4_ACCEPTED_PROVENANCE_VALID = False
        continue


    for (
        dimension_name,
        annotation,
    ) in social_annotations.items():

        if not isinstance(
            annotation,
            dict,
        ):

            BLOCK_4_ACCEPTED_PROVENANCE_VALID = False
            BLOCK_4_AVAILABLE_ANNOTATIONS_WITH_EVIDENCE_VALID = False
            continue


        annotation_source = annotation.get(
            "supervision_source"
        )


        annotation_review_status = annotation.get(
            "review_status"
        )


        value_state = annotation.get(
            "value_state"
        )


        available = (
            annotation.get(
                "available"
            )
            is True
        )


        # Block 3 embeds provenance at annotation level.
        if supervision_source in {
            "human",
            "llm",
        }:

            if annotation_source != supervision_source:

                BLOCK_4_ANNOTATION_LEVEL_SOURCE_ALIGNMENT_VALID = False


            if annotation_review_status not in {
                "accepted",
                "accepted_partial",
            }:

                BLOCK_4_ACCEPTED_PROVENANCE_VALID = False


        elif supervision_source == "none":

            if annotation_source != "none":

                BLOCK_4_ANNOTATION_LEVEL_SOURCE_ALIGNMENT_VALID = False


            if value_state != "not_supervised":

                BLOCK_4_ACCEPTED_PROVENANCE_VALID = False


        if annotation_source == "llm":

            annotation_provider = annotation.get(
                "provider"
            )

            annotation_model = annotation.get(
                "model"
            )

            annotation_supervisor_id = annotation.get(
                "supervisor_id"
            )

            if not all(
                [
                    isinstance(
                        annotation_provider,
                        str,
                    )
                    and
                    bool(
                        annotation_provider.strip()
                    ),

                    isinstance(
                        annotation_model,
                        str,
                    )
                    and
                    bool(
                        annotation_model.strip()
                    ),

                    isinstance(
                        annotation_supervisor_id,
                        str,
                    )
                    and
                    bool(
                        annotation_supervisor_id.strip()
                    ),
                ]
            ):

                BLOCK_4_ANNOTATION_LEVEL_LLM_PROVENANCE_VALID = False


        if available:

            evidence = annotation.get(
                "evidence"
            )

            if not (
                isinstance(
                    evidence,
                    str,
                )
                and
                evidence.strip()
            ):

                BLOCK_4_AVAILABLE_ANNOTATIONS_WITH_EVIDENCE_VALID = False


BLOCK_4_ACCEPTED_ARTEFACT_VALID = all(
    [
        BLOCK_4_ACCEPTED_ARTEFACT_RELOADED,
        BLOCK_4_ACCEPTED_TYPE_VALID,
        BLOCK_4_ACCEPTED_VERSION_PRESENT,
        BLOCK_4_ACCEPTED_DIMENSION_VALID,
        BLOCK_4_ACCEPTED_DIMENSION_ORDER_VALID,
        BLOCK_4_ACCEPTED_DIMENSION_IDS_VALID,
        BLOCK_4_ACCEPTED_RECORD_COUNT_VALID,
        BLOCK_4_ACCEPTED_SUPPORTED_SOURCES_VALID,
        BLOCK_4_ACCEPTED_LABELS_NOT_GENERATED,
        BLOCK_4_ACCEPTED_REVIEW_STATUS_VALID,
        BLOCK_4_ACCEPTED_EVIDENCE_REQUIRED,
        BLOCK_4_ACCEPTED_PROVENANCE_REQUIRED,
        BLOCK_4_ACCEPTED_PARTIAL_SENTENCE_COVERAGE,
        BLOCK_4_ACCEPTED_PARTIAL_DIMENSION_COVERAGE,
        BLOCK_4_ACCEPTED_MASK_AWARE,
        BLOCK_4_ACCEPTED_MISSING_NOT_ZERO,
        BLOCK_4_ACCEPTED_MISSING_NOT_NEGATIVE,
        BLOCK_4_ACCEPTED_UNAVAILABLE_EXCLUDED,
        BLOCK_4_ACCEPTED_FUTURE_CONTEXT_PROHIBITED,
        BLOCK_4_ACCEPTED_TARGET_CONTRACT_DEFINED,
        BLOCK_4_ACCEPTED_TARGET_CONTRACT_VALID,
        BLOCK_4_ACCEPTED_OPTIMISATION_NOT_READY,
        BLOCK_4_ACCEPTED_TRAINING_NOT_EXECUTED,
        BLOCK_4_ACCEPTED_PROVENANCE_VALID,
        BLOCK_4_AVAILABLE_ANNOTATIONS_WITH_EVIDENCE_VALID,
        BLOCK_4_ANNOTATION_LEVEL_LLM_PROVENANCE_VALID,
        BLOCK_4_ANNOTATION_LEVEL_SOURCE_ALIGNMENT_VALID,
    ]
)


if not BLOCK_4_ACCEPTED_ARTEFACT_VALID:

    BLOCK_4_ACCEPTED_ARTEFACT_DIAGNOSTICS = {
        "type_valid":
            BLOCK_4_ACCEPTED_TYPE_VALID,

        "version_present":
            BLOCK_4_ACCEPTED_VERSION_PRESENT,

        "dimension_valid":
            BLOCK_4_ACCEPTED_DIMENSION_VALID,

        "dimension_order_valid":
            BLOCK_4_ACCEPTED_DIMENSION_ORDER_VALID,

        "dimension_ids_valid":
            BLOCK_4_ACCEPTED_DIMENSION_IDS_VALID,

        "record_count_valid":
            BLOCK_4_ACCEPTED_RECORD_COUNT_VALID,

        "supported_sources_valid":
            BLOCK_4_ACCEPTED_SUPPORTED_SOURCES_VALID,

        "labels_not_generated_by_block":
            BLOCK_4_ACCEPTED_LABELS_NOT_GENERATED,

        "accepted_review_status_valid":
            BLOCK_4_ACCEPTED_REVIEW_STATUS_VALID,

        "evidence_required":
            BLOCK_4_ACCEPTED_EVIDENCE_REQUIRED,

        "provenance_required":
            BLOCK_4_ACCEPTED_PROVENANCE_REQUIRED,

        "partial_sentence_coverage":
            BLOCK_4_ACCEPTED_PARTIAL_SENTENCE_COVERAGE,

        "partial_dimension_coverage":
            BLOCK_4_ACCEPTED_PARTIAL_DIMENSION_COVERAGE,

        "mask_aware":
            BLOCK_4_ACCEPTED_MASK_AWARE,

        "missing_not_zero":
            BLOCK_4_ACCEPTED_MISSING_NOT_ZERO,

        "missing_not_negative":
            BLOCK_4_ACCEPTED_MISSING_NOT_NEGATIVE,

        "unavailable_excluded":
            BLOCK_4_ACCEPTED_UNAVAILABLE_EXCLUDED,

        "future_context_prohibited":
            BLOCK_4_ACCEPTED_FUTURE_CONTEXT_PROHIBITED,

        "target_contract_defined":
            BLOCK_4_ACCEPTED_TARGET_CONTRACT_DEFINED,

        "target_contract_valid":
            BLOCK_4_ACCEPTED_TARGET_CONTRACT_VALID,

        "optimisation_not_ready":
            BLOCK_4_ACCEPTED_OPTIMISATION_NOT_READY,

        "training_not_executed":
            BLOCK_4_ACCEPTED_TRAINING_NOT_EXECUTED,

        "record_provenance_valid":
            BLOCK_4_ACCEPTED_PROVENANCE_VALID,

        "annotation_llm_provenance_valid":
            BLOCK_4_ANNOTATION_LEVEL_LLM_PROVENANCE_VALID,

        "annotation_source_alignment_valid":
            BLOCK_4_ANNOTATION_LEVEL_SOURCE_ALIGNMENT_VALID,

        "available_evidence_valid":
            BLOCK_4_AVAILABLE_ANNOTATIONS_WITH_EVIDENCE_VALID,
    }

    raise RuntimeError(
        "Persisted accepted Social Representation supervision "
        "contract is invalid. Diagnostics: "
        f"{BLOCK_4_ACCEPTED_ARTEFACT_DIAGNOSTICS}"
    )


# =============================================================================
# Canonical sentence identity audit
# =============================================================================
#
# The persisted Block 3 record list may use the Block 2 annotation-template
# order, while Notebook 07's inherited handover may expose the same canonical
# sentence identities in a different article order.
#
# Sentence identity, not persisted list position, is therefore the canonical
# alignment key. Block 4 verifies exact set equality and uniqueness, then
# constructs a local canonical-order view before any matrix is assembled.
# No persisted artefact is modified.
# =============================================================================

BLOCK_4_ACCEPTED_SENTENCE_IDS = []


for record_index, record in enumerate(
    BLOCK_4_ACCEPTED_RECORDS
):

    if not isinstance(
        record,
        dict,
    ):

        raise TypeError(
            f"Accepted Social Representation record {record_index} "
            "is not a dictionary."
        )


    identity = record.get(
        "identity",
        {},
    )


    sentence_id = (
        identity.get(
            "sentence_id"
        )
        if isinstance(
            identity,
            dict,
        )
        else None
    )


    if not (
        isinstance(
            sentence_id,
            str,
        )
        and
        sentence_id
    ):

        raise RuntimeError(
            f"Accepted Social Representation record {record_index} "
            "has no valid sentence_id."
        )


    BLOCK_4_ACCEPTED_SENTENCE_IDS.append(
        sentence_id
    )


BLOCK_4_SENTENCE_IDS_PRESENT = all(
    isinstance(
        sentence_id,
        str,
    )
    and
    bool(
        sentence_id
    )

    for sentence_id
    in BLOCK_4_ACCEPTED_SENTENCE_IDS
)


BLOCK_4_SENTENCE_IDS_UNIQUE = (
    len(
        BLOCK_4_ACCEPTED_SENTENCE_IDS
    )
    ==
    len(
        set(
            BLOCK_4_ACCEPTED_SENTENCE_IDS
        )
    )
)


BLOCK_4_CANONICAL_SENTENCE_IDS_PRESENT = all(
    isinstance(
        sentence_id,
        str,
    )
    and
    bool(
        sentence_id
    )

    for sentence_id
    in NOTEBOOK_07_SENTENCE_IDS
)


BLOCK_4_CANONICAL_SENTENCE_IDS_UNIQUE = (
    len(
        NOTEBOOK_07_SENTENCE_IDS
    )
    ==
    len(
        set(
            NOTEBOOK_07_SENTENCE_IDS
        )
    )
)


BLOCK_4_CANONICAL_SENTENCE_SET_VALID = (
    set(
        BLOCK_4_ACCEPTED_SENTENCE_IDS
    )
    ==
    set(
        NOTEBOOK_07_SENTENCE_IDS
    )
)


BLOCK_4_PERSISTED_ORDER_MATCHES_CANONICAL = (
    tuple(
        BLOCK_4_ACCEPTED_SENTENCE_IDS
    )
    ==
    tuple(
        NOTEBOOK_07_SENTENCE_IDS
    )
)


# =============================================================================
# Canonical local reordering
# =============================================================================

BLOCK_4_ACCEPTED_RECORD_BY_SENTENCE_ID = {
    record[
        "identity"
    ][
        "sentence_id"
    ]:
        record

    for record
    in BLOCK_4_ACCEPTED_RECORDS
}


BLOCK_4_RECORD_LOOKUP_COMPLETE = (
    len(
        BLOCK_4_ACCEPTED_RECORD_BY_SENTENCE_ID
    )
    ==
    NOTEBOOK_07_SENTENCE_COUNT
)


if not all(
    [
        BLOCK_4_SENTENCE_IDS_PRESENT,
        BLOCK_4_SENTENCE_IDS_UNIQUE,
        BLOCK_4_CANONICAL_SENTENCE_IDS_PRESENT,
        BLOCK_4_CANONICAL_SENTENCE_IDS_UNIQUE,
        BLOCK_4_CANONICAL_SENTENCE_SET_VALID,
        BLOCK_4_RECORD_LOOKUP_COMPLETE,
    ]
):

    raise RuntimeError(
        "Accepted Social Representation supervision does not preserve "
        "the complete unique canonical sentence identity set."
    )


BLOCK_4_CANONICALLY_ORDERED_RECORDS = [
    BLOCK_4_ACCEPTED_RECORD_BY_SENTENCE_ID[
        sentence_id
    ]

    for sentence_id
    in NOTEBOOK_07_SENTENCE_IDS
]


BLOCK_4_CANONICALLY_ORDERED_SENTENCE_IDS = [
    record[
        "identity"
    ][
        "sentence_id"
    ]

    for record
    in BLOCK_4_CANONICALLY_ORDERED_RECORDS
]


BLOCK_4_CANONICAL_ORDER_VALID = (
    tuple(
        BLOCK_4_CANONICALLY_ORDERED_SENTENCE_IDS
    )
    ==
    tuple(
        NOTEBOOK_07_SENTENCE_IDS
    )
)


BLOCK_4_CANONICAL_REORDER_APPLIED = (
    not BLOCK_4_PERSISTED_ORDER_MATCHES_CANONICAL
)


BLOCK_4_CANONICAL_ALIGNMENT_VALID = all(
    [
        BLOCK_4_SENTENCE_IDS_PRESENT,
        BLOCK_4_SENTENCE_IDS_UNIQUE,
        BLOCK_4_CANONICAL_SENTENCE_IDS_PRESENT,
        BLOCK_4_CANONICAL_SENTENCE_IDS_UNIQUE,
        BLOCK_4_CANONICAL_SENTENCE_SET_VALID,
        BLOCK_4_RECORD_LOOKUP_COMPLETE,
        BLOCK_4_CANONICAL_ORDER_VALID,
    ]
)


if not BLOCK_4_CANONICAL_ALIGNMENT_VALID:

    raise RuntimeError(
        "Accepted Social Representation supervision could not be "
        "canonically aligned by sentence identity."
    )


# =============================================================================
# Social dimension-definition lookup
# =============================================================================

BLOCK_4_DEFINITION_BY_NAME = {}


for definition in (
    NOTEBOOK_07_SOCIAL_DIMENSION_DEFINITIONS
):

    if not isinstance(
        definition,
        dict,
    ):

        raise TypeError(
            "Social dimension definitions must be dictionaries."
        )


    target_name = definition.get(
        "target_name"
    )


    if target_name is None:

        raise RuntimeError(
            "A Social Representation dimension definition "
            "has no target_name."
        )


    BLOCK_4_DEFINITION_BY_NAME[
        target_name
    ] = deepcopy(
        definition
    )


BLOCK_4_DEFINITION_SET_VALID = (
    set(
        BLOCK_4_DEFINITION_BY_NAME.keys()
    )
    ==
    set(
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
    )
)


if not BLOCK_4_DEFINITION_SET_VALID:

    raise RuntimeError(
        "Social Representation semantic-definition set does not "
        "match the seven-dimensional ontology."
    )


# =============================================================================
# Construct target and mask matrices from accepted records
# =============================================================================

BLOCK_4_SOCIAL_TARGET_MATRIX = np.full(
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    ),
    np.nan,
    dtype=np.float64,
)


BLOCK_4_SOCIAL_MASK_MATRIX = np.zeros(
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    ),
    dtype=bool,
)


for (
    record_index,
    record,
) in enumerate(
    BLOCK_4_CANONICALLY_ORDERED_RECORDS
):

    social_annotations = record.get(
        "social_annotations",
        {},
    )


    if not isinstance(
        social_annotations,
        dict,
    ):

        raise RuntimeError(
            f"Accepted social record {record_index} has no valid "
            "social_annotations dictionary."
        )


    for (
        dimension_index,
        dimension_name,
    ) in enumerate(
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
    ):

        if dimension_name not in social_annotations:

            raise RuntimeError(
                f"Accepted social record {record_index} does not contain "
                f"dimension {dimension_name}."
            )


        annotation = social_annotations[
            dimension_name
        ]


        if not isinstance(
            annotation,
            dict,
        ):

            raise TypeError(
                f"Accepted annotation {dimension_name} in record "
                f"{record_index} is not a dictionary."
            )


        available = bool(
            annotation.get(
                "available",
                False,
            )
        )


        value = annotation.get(
            "value"
        )


        if available:

            if value is None:

                raise RuntimeError(
                    f"Available annotation {dimension_name} in record "
                    f"{record_index} has no value."
                )


            try:

                numeric_value = float(
                    value
                )


            except (
                TypeError,
                ValueError,
            ) as error:

                raise RuntimeError(
                    f"Available annotation {dimension_name} in record "
                    f"{record_index} is not numerical."
                ) from error


            BLOCK_4_SOCIAL_TARGET_MATRIX[
                record_index,
                dimension_index,
            ] = numeric_value


            BLOCK_4_SOCIAL_MASK_MATRIX[
                record_index,
                dimension_index,
            ] = True


# =============================================================================
# Matrix contract validation
# =============================================================================

BLOCK_4_TARGET_MATRIX_SHAPE_VALID = (
    BLOCK_4_SOCIAL_TARGET_MATRIX.shape
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_4_MASK_MATRIX_SHAPE_VALID = (
    BLOCK_4_SOCIAL_MASK_MATRIX.shape
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_4_OBSERVED_VALUES_FINITE = bool(
    np.isfinite(
        BLOCK_4_SOCIAL_TARGET_MATRIX[
            BLOCK_4_SOCIAL_MASK_MATRIX
        ]
    ).all()
)


BLOCK_4_MASKED_VALUES_ARE_NAN = bool(
    np.isnan(
        BLOCK_4_SOCIAL_TARGET_MATRIX[
            ~BLOCK_4_SOCIAL_MASK_MATRIX
        ]
    ).all()
)


if not all(
    [
        BLOCK_4_TARGET_MATRIX_SHAPE_VALID,
        BLOCK_4_MASK_MATRIX_SHAPE_VALID,
        BLOCK_4_OBSERVED_VALUES_FINITE,
        BLOCK_4_MASKED_VALUES_ARE_NAN,
    ]
):

    raise RuntimeError(
        "Social Representation target or mask matrix contract is invalid."
    )


# =============================================================================
# Reproduce accepted aggregate supervision coverage
# =============================================================================

BLOCK_4_REPRODUCED_AVAILABLE_ELEMENTS = int(
    BLOCK_4_SOCIAL_MASK_MATRIX.sum()
)


BLOCK_4_REPRODUCED_POSSIBLE_ELEMENTS = int(
    BLOCK_4_SOCIAL_MASK_MATRIX.size
)


BLOCK_4_REPRODUCED_AGGREGATE_COVERAGE = (
    BLOCK_4_REPRODUCED_AVAILABLE_ELEMENTS
    /
    BLOCK_4_REPRODUCED_POSSIBLE_ELEMENTS
)


BLOCK_4_ACCEPTED_COVERAGE = (
    BLOCK_4_ACCEPTED_ARTEFACT.get(
        "coverage",
        {},
    )
)


BLOCK_4_EXPECTED_AVAILABLE_ELEMENTS = (
    BLOCK_4_ACCEPTED_COVERAGE.get(
        "available_target_elements"
    )
)


BLOCK_4_EXPECTED_POSSIBLE_ELEMENTS = (
    BLOCK_4_ACCEPTED_COVERAGE.get(
        "possible_target_elements"
    )
)


BLOCK_4_EXPECTED_AGGREGATE_COVERAGE = (
    BLOCK_4_ACCEPTED_COVERAGE.get(
        "aggregate_coverage"
    )
)


BLOCK_4_ACCEPTED_COVERAGE_REPRODUCED = all(
    [
        (
            BLOCK_4_REPRODUCED_AVAILABLE_ELEMENTS
            ==
            BLOCK_4_EXPECTED_AVAILABLE_ELEMENTS
        ),

        (
            BLOCK_4_REPRODUCED_POSSIBLE_ELEMENTS
            ==
            BLOCK_4_EXPECTED_POSSIBLE_ELEMENTS
        ),

        (
            BLOCK_4_EXPECTED_AGGREGATE_COVERAGE
            is not None
        ),

        np.isclose(
            BLOCK_4_REPRODUCED_AGGREGATE_COVERAGE,
            float(
                BLOCK_4_EXPECTED_AGGREGATE_COVERAGE
            ),
            rtol=0.0,
            atol=1e-12,
        ),
    ]
)


if not BLOCK_4_ACCEPTED_COVERAGE_REPRODUCED:

    raise RuntimeError(
        "Block 4 could not reproduce accepted Block 3 "
        "aggregate supervision coverage."
    )


# =============================================================================
# Masking contract validation
# =============================================================================

BLOCK_4_MASKING_CONTRACT_VALID = all(
    [
        NOTEBOOK_07_SOCIAL_MASK_AWARE_SUPERVISION,
        NOTEBOOK_07_SOCIAL_PARTIAL_SUPERVISION_ALLOWED,
        not NOTEBOOK_07_SOCIAL_MISSING_EQUALS_ZERO,
        not NOTEBOOK_07_SOCIAL_MISSING_EQUALS_NEGATIVE,
        not NOTEBOOK_07_SOCIAL_UNAVAILABLE_ENTERS_LOSS,
        BLOCK_4_MASKED_VALUES_ARE_NAN,
    ]
)


if not BLOCK_4_MASKING_CONTRACT_VALID:

    raise RuntimeError(
        "Notebook 07 Social Representation masking contract is invalid."
    )


# =============================================================================
# Target-domain validation
# =============================================================================

BLOCK_4_TARGET_DOMAIN_VALID = {}

BLOCK_4_TARGET_DOMAIN_ERRORS = {}


for (
    dimension_index,
    dimension_name,
) in enumerate(
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
):

    definition = (
        BLOCK_4_DEFINITION_BY_NAME[
            dimension_name
        ]
    )


    target_family = definition.get(
        "target_family"
    )


    dimension_mask = (
        BLOCK_4_SOCIAL_MASK_MATRIX[
            :,
            dimension_index,
        ]
    )


    observed_values = (
        BLOCK_4_SOCIAL_TARGET_MATRIX[
            dimension_mask,
            dimension_index,
        ]
    )


    domain_errors = []


    if target_family == "signed_cohesion":

        if observed_values.size > 0:

            if not bool(
                np.all(
                    observed_values >= -1.0
                )
            ):

                domain_errors.append(
                    "value_below_minus_one"
                )


            if not bool(
                np.all(
                    observed_values <= 1.0
                )
            ):

                domain_errors.append(
                    "value_above_plus_one"
                )


    elif target_family == "binary_social_structure":

        if observed_values.size > 0:

            if not bool(
                np.isin(
                    observed_values,
                    [
                        0.0,
                        1.0,
                    ],
                ).all()
            ):

                domain_errors.append(
                    "non_binary_observed_value"
                )


    else:

        domain_errors.append(
            "unknown_target_family"
        )


    BLOCK_4_TARGET_DOMAIN_ERRORS[
        dimension_name
    ] = domain_errors


    BLOCK_4_TARGET_DOMAIN_VALID[
        dimension_name
    ] = (
        len(
            domain_errors
        )
        == 0
    )


BLOCK_4_ALL_TARGET_DOMAINS_VALID = all(
    BLOCK_4_TARGET_DOMAIN_VALID.values()
)


if not BLOCK_4_ALL_TARGET_DOMAINS_VALID:

    raise RuntimeError(
        "One or more Social Representation dimensions violate "
        "their target-domain contract. "
        f"Errors: {BLOCK_4_TARGET_DOMAIN_ERRORS}"
    )


# =============================================================================
# Availability and variability audit
# =============================================================================

BLOCK_4_DIMENSION_AVAILABLE_COUNTS = {}

BLOCK_4_DIMENSION_MASKED_COUNTS = {}

BLOCK_4_DIMENSION_COVERAGE = {}

BLOCK_4_DIMENSION_UNIQUE_VALUES = {}

BLOCK_4_DIMENSION_MINIMUM = {}

BLOCK_4_DIMENSION_MAXIMUM = {}

BLOCK_4_DIMENSION_MEAN = {}

BLOCK_4_DIMENSION_VARIANCE = {}

BLOCK_4_DIMENSION_HAS_VARIATION = {}

BLOCK_4_DIMENSION_MINIMUM_SUPERVISION_MET = {}


for (
    dimension_index,
    dimension_name,
) in enumerate(
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
):

    dimension_mask = (
        BLOCK_4_SOCIAL_MASK_MATRIX[
            :,
            dimension_index,
        ]
    )


    available_count = int(
        dimension_mask.sum()
    )


    masked_count = int(
        NOTEBOOK_07_SENTENCE_COUNT
        -
        available_count
    )


    coverage = (
        available_count
        /
        NOTEBOOK_07_SENTENCE_COUNT
    )


    BLOCK_4_DIMENSION_AVAILABLE_COUNTS[
        dimension_name
    ] = available_count


    BLOCK_4_DIMENSION_MASKED_COUNTS[
        dimension_name
    ] = masked_count


    BLOCK_4_DIMENSION_COVERAGE[
        dimension_name
    ] = float(
        coverage
    )


    BLOCK_4_DIMENSION_MINIMUM_SUPERVISION_MET[
        dimension_name
    ] = (
        available_count
        >=
        NOTEBOOK_07_SOCIAL_MINIMUM_OBSERVED_TARGETS
    )


    if available_count > 0:

        observed_values = (
            BLOCK_4_SOCIAL_TARGET_MATRIX[
                dimension_mask,
                dimension_index,
            ]
        )


        unique_count = int(
            np.unique(
                observed_values
            ).size
        )


        minimum = float(
            observed_values.min()
        )


        maximum = float(
            observed_values.max()
        )


        mean = float(
            observed_values.mean()
        )


        variance = float(
            observed_values.var(
                ddof=0
            )
        )


        has_variation = (
            unique_count > 1
            and
            variance > 0.0
        )


    else:

        unique_count = 0

        minimum = None

        maximum = None

        mean = None

        variance = None

        has_variation = False


    BLOCK_4_DIMENSION_UNIQUE_VALUES[
        dimension_name
    ] = unique_count


    BLOCK_4_DIMENSION_MINIMUM[
        dimension_name
    ] = minimum


    BLOCK_4_DIMENSION_MAXIMUM[
        dimension_name
    ] = maximum


    BLOCK_4_DIMENSION_MEAN[
        dimension_name
    ] = mean


    BLOCK_4_DIMENSION_VARIANCE[
        dimension_name
    ] = variance


    BLOCK_4_DIMENSION_HAS_VARIATION[
        dimension_name
    ] = bool(
        has_variation
    )


# =============================================================================
# Reproduce Block 3 per-dimension coverage
# =============================================================================

BLOCK_4_EXPECTED_DIMENSION_AVAILABLE_COUNTS = (
    BLOCK_4_ACCEPTED_COVERAGE.get(
        "dimension_available_counts",
        {},
    )
)


BLOCK_4_EXPECTED_DIMENSION_COVERAGE = (
    BLOCK_4_ACCEPTED_COVERAGE.get(
        "dimension_coverage",
        {},
    )
)


BLOCK_4_DIMENSION_COVERAGE_REPRODUCED = True


for dimension_name in (
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
):

    if dimension_name not in (
        BLOCK_4_EXPECTED_DIMENSION_AVAILABLE_COUNTS
    ):

        BLOCK_4_DIMENSION_COVERAGE_REPRODUCED = False

        continue


    if dimension_name not in (
        BLOCK_4_EXPECTED_DIMENSION_COVERAGE
    ):

        BLOCK_4_DIMENSION_COVERAGE_REPRODUCED = False

        continue


    if (
        BLOCK_4_DIMENSION_AVAILABLE_COUNTS[
            dimension_name
        ]
        !=
        BLOCK_4_EXPECTED_DIMENSION_AVAILABLE_COUNTS[
            dimension_name
        ]
    ):

        BLOCK_4_DIMENSION_COVERAGE_REPRODUCED = False


    if not np.isclose(
        BLOCK_4_DIMENSION_COVERAGE[
            dimension_name
        ],
        float(
            BLOCK_4_EXPECTED_DIMENSION_COVERAGE[
                dimension_name
            ]
        ),
        rtol=0.0,
        atol=1e-12,
    ):

        BLOCK_4_DIMENSION_COVERAGE_REPRODUCED = False


if not BLOCK_4_DIMENSION_COVERAGE_REPRODUCED:

    raise RuntimeError(
        "Block 4 could not reproduce Block 3 "
        "per-dimension supervision coverage."
    )


# =============================================================================
# General activation-policy resolution
# =============================================================================
#
# Ordering matters:
#
# 1. no supervision
# 2. invalid target domain
# 3. insufficient supervision
# 4. zero variance
# 5. eligible target family
#
# No current dimension is activated merely because its coverage is high.
# =============================================================================

NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS = []

NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS = []

NOTEBOOK_07_SOCIAL_DIMENSION_ACTIVATION_STATE = {}

NOTEBOOK_07_SOCIAL_DIMENSION_DEFERRAL_REASON = {}

NOTEBOOK_07_SOCIAL_DIMENSION_TARGET_FAMILY = {}

NOTEBOOK_07_SOCIAL_DIMENSION_LOSS_FAMILY = {}


for (
    dimension_index,
    dimension_name,
) in enumerate(
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
):

    definition = (
        BLOCK_4_DEFINITION_BY_NAME[
            dimension_name
        ]
    )


    target_family = definition.get(
        "target_family"
    )


    available_count = (
        BLOCK_4_DIMENSION_AVAILABLE_COUNTS[
            dimension_name
        ]
    )


    domain_valid = (
        BLOCK_4_TARGET_DOMAIN_VALID[
            dimension_name
        ]
    )


    minimum_supervision_met = (
        BLOCK_4_DIMENSION_MINIMUM_SUPERVISION_MET[
            dimension_name
        ]
    )


    has_variation = (
        BLOCK_4_DIMENSION_HAS_VARIATION[
            dimension_name
        ]
    )


    NOTEBOOK_07_SOCIAL_DIMENSION_TARGET_FAMILY[
        dimension_name
    ] = target_family


    # =========================================================================
    # No explicit supervision
    # =========================================================================

    if available_count == 0:

        activation_state = (
            "deferred_unavailable_supervision"
        )

        deferral_reason = (
            "unavailable_supervision"
        )

        loss_family = "none"


    # =========================================================================
    # Invalid target-domain values
    # =========================================================================

    elif not domain_valid:

        activation_state = (
            "deferred_invalid_target_domain"
        )

        deferral_reason = (
            "invalid_target_domain"
        )

        loss_family = "none"


    # =========================================================================
    # Too few explicit observations
    # =========================================================================

    elif not minimum_supervision_met:

        activation_state = (
            "deferred_insufficient_supervision"
        )

        deferral_reason = (
            "insufficient_supervision"
        )

        loss_family = "none"


    # =========================================================================
    # Constant observed target
    # =========================================================================

    elif not has_variation:

        activation_state = (
            "deferred_zero_variance"
        )

        deferral_reason = (
            "zero_variance"
        )

        loss_family = "none"


    # =========================================================================
    # Signed cohesion objective
    # =========================================================================

    elif target_family == "signed_cohesion":

        activation_state = "eligible"

        deferral_reason = None

        loss_family = (
            "masked_mean_squared_error"
        )


    # =========================================================================
    # Binary social-structure objective
    # =========================================================================

    elif target_family == "binary_social_structure":

        activation_state = "eligible"

        deferral_reason = None

        loss_family = (
            "binary_cross_entropy_with_logits"
        )


    else:

        activation_state = (
            "deferred_unknown_target_family"
        )

        deferral_reason = (
            "unknown_target_family"
        )

        loss_family = "none"


    NOTEBOOK_07_SOCIAL_DIMENSION_ACTIVATION_STATE[
        dimension_name
    ] = activation_state


    NOTEBOOK_07_SOCIAL_DIMENSION_DEFERRAL_REASON[
        dimension_name
    ] = deferral_reason


    NOTEBOOK_07_SOCIAL_DIMENSION_LOSS_FAMILY[
        dimension_name
    ] = loss_family


    if activation_state == "eligible":

        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS.append(
            dimension_name
        )


    else:

        NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS.append(
            dimension_name
        )


NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS = tuple(
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
)


NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS = tuple(
    NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
)


# =============================================================================
# Active / deferred indices
# =============================================================================

NOTEBOOK_07_SOCIAL_ACTIVE_INDICES = tuple(
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER.index(
        dimension_name
    )
    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
)


NOTEBOOK_07_SOCIAL_DEFERRED_INDICES = tuple(
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER.index(
        dimension_name
    )
    for dimension_name
    in NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
)


# =============================================================================
# Active target-family partitions
# =============================================================================

NOTEBOOK_07_SOCIAL_ACTIVE_SIGNED_DIMENSIONS = tuple(
    dimension_name
    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    if (
        NOTEBOOK_07_SOCIAL_DIMENSION_TARGET_FAMILY[
            dimension_name
        ]
        ==
        "signed_cohesion"
    )
)


NOTEBOOK_07_SOCIAL_ACTIVE_BINARY_DIMENSIONS = tuple(
    dimension_name
    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    if (
        NOTEBOOK_07_SOCIAL_DIMENSION_TARGET_FAMILY[
            dimension_name
        ]
        ==
        "binary_social_structure"
    )
)


# =============================================================================
# Dynamic activation-policy validation
# =============================================================================
#
# The active/deferred outcome is derived exclusively from the current accepted
# supervision artefact. No dimension is expected to be active or deferred
# merely because it was so in an earlier pilot corpus.
#
# The only fixed rule is the methodological activation algorithm above:
#
#   1. no supervision -> defer
#   2. invalid target domain -> defer
#   3. fewer than configured minimum observations -> defer
#   4. zero target variance -> defer
#   5. otherwise activate using the loss family implied by target semantics
# =============================================================================

BLOCK_4_ACTIVE_DEFERRED_DISJOINT = (
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    ).isdisjoint(
        set(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        )
    )
)


BLOCK_4_ACTIVE_DEFERRED_COMPLETE = (
    (
        set(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        )
        |
        set(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        )
    )
    ==
    set(
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
    )
)


BLOCK_4_ACTIVE_INDICES_VALID = (
    tuple(
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER[
            index
        ]
        for index
        in NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
    )
    ==
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
)


BLOCK_4_DEFERRED_INDICES_VALID = (
    tuple(
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER[
            index
        ]
        for index
        in NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
    )
    ==
    NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
)


BLOCK_4_ACTIVATION_REASONS_VALID = True


for dimension_name in (
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
):

    activation_state = (
        NOTEBOOK_07_SOCIAL_DIMENSION_ACTIVATION_STATE[
            dimension_name
        ]
    )

    deferral_reason = (
        NOTEBOOK_07_SOCIAL_DIMENSION_DEFERRAL_REASON[
            dimension_name
        ]
    )

    if activation_state == "eligible":

        if deferral_reason is not None:

            BLOCK_4_ACTIVATION_REASONS_VALID = False

    else:

        if deferral_reason is None:

            BLOCK_4_ACTIVATION_REASONS_VALID = False


BLOCK_4_DYNAMIC_ACTIVATION_POLICY_VALID = all(
    [
        BLOCK_4_ACTIVE_DEFERRED_DISJOINT,
        BLOCK_4_ACTIVE_DEFERRED_COMPLETE,
        BLOCK_4_ACTIVE_INDICES_VALID,
        BLOCK_4_DEFERRED_INDICES_VALID,
        BLOCK_4_ACTIVATION_REASONS_VALID,
    ]
)


if not BLOCK_4_DYNAMIC_ACTIVATION_POLICY_VALID:

    raise RuntimeError(
        "Computed Social Representation activation policy is internally "
        "inconsistent with the current accepted supervision."
    )


# =============================================================================
# Active loss-family contract
# =============================================================================

NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES = {
    dimension_name:
        NOTEBOOK_07_SOCIAL_DIMENSION_LOSS_FAMILY[
            dimension_name
        ]

    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
}


BLOCK_4_ACTIVE_LOSS_FAMILIES_VALID = all(
    (
        NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES[
            dimension_name
        ]
        ==
        (
            "masked_mean_squared_error"
            if (
                NOTEBOOK_07_SOCIAL_DIMENSION_TARGET_FAMILY[
                    dimension_name
                ]
                ==
                "signed_cohesion"
            )
            else
            "binary_cross_entropy_with_logits"
        )
    )

    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
)


if not BLOCK_4_ACTIVE_LOSS_FAMILIES_VALID:

    raise RuntimeError(
        "Active Social Representation loss-family contract is invalid."
    )


# =============================================================================
# Equal active-objective weighting policy
# =============================================================================
#
# Equal weights are prospective policy only.
#
# No loss is calculated in Block 4.
# =============================================================================

if len(
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
) == 0:

    raise RuntimeError(
        "No Social Representation dimension is eligible for "
        "the current controlled objective."
    )


NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS = {
    dimension_name:
        (
            1.0
            /
            len(
                NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
            )
        )

    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
}


BLOCK_4_OBJECTIVE_WEIGHT_SUM = float(
    sum(
        NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS.values()
    )
)


BLOCK_4_OBJECTIVE_WEIGHTS_POSITIVE = all(
    objective_weight > 0.0
    for objective_weight
    in NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS.values()
)


BLOCK_4_OBJECTIVE_WEIGHTS_VALID = all(
    [
        (
            len(
                NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS
            )
            ==
            len(
                NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
            )
        ),

        BLOCK_4_OBJECTIVE_WEIGHTS_POSITIVE,

        np.isclose(
            BLOCK_4_OBJECTIVE_WEIGHT_SUM,
            1.0,
            rtol=0.0,
            atol=1e-12,
        ),
    ]
)


if not BLOCK_4_OBJECTIVE_WEIGHTS_VALID:

    raise RuntimeError(
        "Social Representation active-objective weighting is invalid."
    )


# =============================================================================
# Objective-policy state
# =============================================================================

NOTEBOOK_07_SOCIAL_TARGET_AVAILABILITY_VALIDATED = True

NOTEBOOK_07_SOCIAL_TARGET_VARIABILITY_VALIDATED = True

NOTEBOOK_07_SOCIAL_ACTIVATION_CONTRACT_RESOLVED = True

NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_RESOLVED = True

NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_DEFINED = True


NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID = all(
    [
        BLOCK_4_ACCEPTED_ARTEFACT_VALID,
        BLOCK_4_CANONICAL_ALIGNMENT_VALID,
        BLOCK_4_DEFINITION_SET_VALID,
        BLOCK_4_TARGET_MATRIX_SHAPE_VALID,
        BLOCK_4_MASK_MATRIX_SHAPE_VALID,
        BLOCK_4_OBSERVED_VALUES_FINITE,
        BLOCK_4_MASKED_VALUES_ARE_NAN,
        BLOCK_4_ACCEPTED_COVERAGE_REPRODUCED,
        BLOCK_4_DIMENSION_COVERAGE_REPRODUCED,
        BLOCK_4_MASKING_CONTRACT_VALID,
        BLOCK_4_ALL_TARGET_DOMAINS_VALID,
        BLOCK_4_DYNAMIC_ACTIVATION_POLICY_VALID,
        BLOCK_4_ACTIVE_LOSS_FAMILIES_VALID,
        BLOCK_4_OBJECTIVE_WEIGHTS_VALID,
    ]
)


if not NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID:

    raise RuntimeError(
        "Notebook 07 Social Representation objective policy is invalid."
    )


# =============================================================================
# Readiness boundary
# =============================================================================

NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY = False

NOTEBOOK_07_SOCIAL_OPTIMISATION_READY = False


NOTEBOOK_07_READY_FOR_SOCIAL_MODEL_POLICY = (
    NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID
)


# =============================================================================
# Human-readable dimension audit
# =============================================================================

BLOCK_4_SOCIAL_DIMENSION_ROWS = []


for (
    dimension_index,
    dimension_id,
    dimension_name,
) in zip(
    range(
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
    ),
    NOTEBOOK_07_SOCIAL_DIMENSION_IDS,
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER,
):

    BLOCK_4_SOCIAL_DIMENSION_ROWS.append(
        {
            "dimension_id":
                dimension_id,

            "dimension_index":
                dimension_index,

            "target_name":
                dimension_name,

            "target_family":
                NOTEBOOK_07_SOCIAL_DIMENSION_TARGET_FAMILY[
                    dimension_name
                ],

            "available":
                BLOCK_4_DIMENSION_AVAILABLE_COUNTS[
                    dimension_name
                ],

            "masked":
                BLOCK_4_DIMENSION_MASKED_COUNTS[
                    dimension_name
                ],

            "coverage":
                BLOCK_4_DIMENSION_COVERAGE[
                    dimension_name
                ],

            "unique_values":
                BLOCK_4_DIMENSION_UNIQUE_VALUES[
                    dimension_name
                ],

            "minimum":
                BLOCK_4_DIMENSION_MINIMUM[
                    dimension_name
                ],

            "maximum":
                BLOCK_4_DIMENSION_MAXIMUM[
                    dimension_name
                ],

            "mean":
                BLOCK_4_DIMENSION_MEAN[
                    dimension_name
                ],

            "variance":
                BLOCK_4_DIMENSION_VARIANCE[
                    dimension_name
                ],

            "target_domain_valid":
                BLOCK_4_TARGET_DOMAIN_VALID[
                    dimension_name
                ],

            "minimum_supervision_met":
                BLOCK_4_DIMENSION_MINIMUM_SUPERVISION_MET[
                    dimension_name
                ],

            "has_variation":
                BLOCK_4_DIMENSION_HAS_VARIATION[
                    dimension_name
                ],

            "activation_state":
                NOTEBOOK_07_SOCIAL_DIMENSION_ACTIVATION_STATE[
                    dimension_name
                ],

            "deferral_reason":
                NOTEBOOK_07_SOCIAL_DIMENSION_DEFERRAL_REASON[
                    dimension_name
                ],

            "loss_family":
                NOTEBOOK_07_SOCIAL_DIMENSION_LOSS_FAMILY[
                    dimension_name
                ],
        }
    )


BLOCK_4_SOCIAL_DIMENSION_AUDIT = pd.DataFrame(
    BLOCK_4_SOCIAL_DIMENSION_ROWS
)


# =============================================================================
# Persistent objective-policy object
# =============================================================================

NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY = {
    "policy_version":
        NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VERSION,

    "minimum_observed_targets":
        NOTEBOOK_07_SOCIAL_MINIMUM_OBSERVED_TARGETS,

    "minimum_observed_targets_interpretation":
        (
            "controlled-sample methodological threshold; "
            "not statistical sufficiency"
        ),

    "active_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),

    "active_indices":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

    "deferred_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        ),

    "deferred_indices":
        list(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),

    "active_signed_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_SIGNED_DIMENSIONS
        ),

    "active_binary_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_BINARY_DIMENSIONS
        ),

    "activation_state":
        deepcopy(
            NOTEBOOK_07_SOCIAL_DIMENSION_ACTIVATION_STATE
        ),

    "deferral_reason":
        deepcopy(
            NOTEBOOK_07_SOCIAL_DIMENSION_DEFERRAL_REASON
        ),

    "target_family":
        deepcopy(
            NOTEBOOK_07_SOCIAL_DIMENSION_TARGET_FAMILY
        ),

    "loss_family":
        deepcopy(
            NOTEBOOK_07_SOCIAL_DIMENSION_LOSS_FAMILY
        ),

    "active_loss_families":
        deepcopy(
            NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES
        ),

    "objective_weights":
        deepcopy(
            NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS
        ),

    "mask_aware":
        True,

    "partial_supervision_allowed":
        True,

    "missing_equals_zero":
        False,

    "missing_equals_negative":
        False,

    "unavailable_enters_loss":
        False,

    "dynamic_activation_policy_valid":
        BLOCK_4_DYNAMIC_ACTIVATION_POLICY_VALID,

    "optimisation_ready":
        False,

    "empirical_validity":
        False,
}


# =============================================================================
# Final Block 4 validation
# =============================================================================

NOTEBOOK_07_BLOCK_4_ERRORS = []


block_4_validation_checks = {
    "accepted_artefact_not_reloaded":
        BLOCK_4_ACCEPTED_ARTEFACT_RELOADED,

    "accepted_artefact_invalid":
        BLOCK_4_ACCEPTED_ARTEFACT_VALID,

    "sentence_ids_missing":
        BLOCK_4_SENTENCE_IDS_PRESENT,

    "sentence_ids_not_unique":
        BLOCK_4_SENTENCE_IDS_UNIQUE,

    "canonical_sentence_set_invalid":
        BLOCK_4_CANONICAL_SENTENCE_SET_VALID,

    "canonical_order_invalid":
        BLOCK_4_CANONICAL_ORDER_VALID,

    "canonical_alignment_invalid":
        BLOCK_4_CANONICAL_ALIGNMENT_VALID,

    "dimension_definition_set_invalid":
        BLOCK_4_DEFINITION_SET_VALID,

    "target_matrix_shape_invalid":
        BLOCK_4_TARGET_MATRIX_SHAPE_VALID,

    "mask_matrix_shape_invalid":
        BLOCK_4_MASK_MATRIX_SHAPE_VALID,

    "observed_values_nonfinite":
        BLOCK_4_OBSERVED_VALUES_FINITE,

    "masked_values_not_nan":
        BLOCK_4_MASKED_VALUES_ARE_NAN,

    "accepted_coverage_not_reproduced":
        BLOCK_4_ACCEPTED_COVERAGE_REPRODUCED,

    "dimension_coverage_not_reproduced":
        BLOCK_4_DIMENSION_COVERAGE_REPRODUCED,

    "masking_contract_invalid":
        BLOCK_4_MASKING_CONTRACT_VALID,

    "target_domain_invalid":
        BLOCK_4_ALL_TARGET_DOMAINS_VALID,

    "dynamic_activation_policy_invalid":
        BLOCK_4_DYNAMIC_ACTIVATION_POLICY_VALID,

    "active_loss_families_invalid":
        BLOCK_4_ACTIVE_LOSS_FAMILIES_VALID,

    "objective_weights_invalid":
        BLOCK_4_OBJECTIVE_WEIGHTS_VALID,

    "objective_policy_invalid":
        NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID,

    "not_ready_for_social_model_policy":
        NOTEBOOK_07_READY_FOR_SOCIAL_MODEL_POLICY,
}


for (
    error_name,
    condition,
) in block_4_validation_checks.items():

    if not condition:

        NOTEBOOK_07_BLOCK_4_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited-operation validation
# =============================================================================

prohibited_block_4_operations = {
    "social_objectives_incorrectly_activated":
        NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED,

    "social_optimizer_incorrectly_created":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED,

    "social_forward_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED,

    "social_loss_incorrectly_calculated":
        NOTEBOOK_07_SOCIAL_LOSS_CALCULATED,

    "social_zero_grad_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED,

    "social_backward_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED,

    "social_optimizer_step_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED,

    "social_parameter_update_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED,

    "social_training_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED,

    "psychological_training_incorrectly_executed":
        NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "factual_training_incorrectly_executed":
        NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED,

    "backbone_training_incorrectly_executed":
        NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED,

    "global_confluent_training_incorrectly_executed":
        NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED,

    "group_conditioned_path_incorrectly_executed":
        NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_mechanism_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED,

    "transformative_weights_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED,

    "recurrent_mechanism_incorrectly_executed":
        NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for (
    error_name,
    operation_executed,
) in prohibited_block_4_operations.items():

    if operation_executed:

        NOTEBOOK_07_BLOCK_4_ERRORS.append(
            error_name
        )


# =============================================================================
# Final Block 4 state
# =============================================================================

NOTEBOOK_07_BLOCK_4_VALID = (
    len(
        NOTEBOOK_07_BLOCK_4_ERRORS
    )
    == 0
)


if not NOTEBOOK_07_BLOCK_4_VALID:

    raise RuntimeError(
        "Notebook 07 Block 4 Social Representation objective-policy "
        "audit failed. "
        f"Errors: {NOTEBOOK_07_BLOCK_4_ERRORS}"
    )


NOTEBOOK_07_BLOCK_4_COMPLETE = True


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_07_BLOCK_4_SUMMARY = {
    "block":
        NOTEBOOK_07_BLOCK_4,

    "block_name":
        NOTEBOOK_07_BLOCK_4_NAME,

    "version":
        NOTEBOOK_07_BLOCK_4_VERSION,

    "executed_at_utc":
        BLOCK_4_EXECUTED_AT_UTC,

    "accepted_supervision_filename":
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_FILENAME,

    "accepted_supervision_file_id":
        NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_FILE_ID,

    "sentences":
        NOTEBOOK_07_SENTENCE_COUNT,

    "social_dimensions":
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

    "available_elements":
        BLOCK_4_REPRODUCED_AVAILABLE_ELEMENTS,

    "possible_elements":
        BLOCK_4_REPRODUCED_POSSIBLE_ELEMENTS,

    "aggregate_coverage":
        BLOCK_4_REPRODUCED_AGGREGATE_COVERAGE,

    "persisted_order_matches_canonical":
        BLOCK_4_PERSISTED_ORDER_MATCHES_CANONICAL,

    "canonical_reorder_applied":
        BLOCK_4_CANONICAL_REORDER_APPLIED,

    "canonical_alignment_valid":
        BLOCK_4_CANONICAL_ALIGNMENT_VALID,

    "minimum_observed_targets":
        NOTEBOOK_07_SOCIAL_MINIMUM_OBSERVED_TARGETS,

    "active_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),

    "active_indices":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

    "deferred_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        ),

    "deferred_indices":
        list(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),

    "active_signed_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_SIGNED_DIMENSIONS
        ),

    "active_binary_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_BINARY_DIMENSIONS
        ),

    "deferral_reasons":
        deepcopy(
            NOTEBOOK_07_SOCIAL_DIMENSION_DEFERRAL_REASON
        ),

    "loss_families":
        deepcopy(
            NOTEBOOK_07_SOCIAL_DIMENSION_LOSS_FAMILY
        ),

    "objective_weights":
        deepcopy(
            NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS
        ),

    "dynamic_activation_policy_valid":
        BLOCK_4_DYNAMIC_ACTIVATION_POLICY_VALID,

    "availability_validated":
        NOTEBOOK_07_SOCIAL_TARGET_AVAILABILITY_VALIDATED,

    "variability_validated":
        NOTEBOOK_07_SOCIAL_TARGET_VARIABILITY_VALIDATED,

    "activation_contract_resolved":
        NOTEBOOK_07_SOCIAL_ACTIVATION_CONTRACT_RESOLVED,

    "loss_contract_resolved":
        NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_RESOLVED,

    "objective_policy_valid":
        NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID,

    "ready_for_social_model_policy":
        NOTEBOOK_07_READY_FOR_SOCIAL_MODEL_POLICY,

    "optimisation_ready":
        NOTEBOOK_07_SOCIAL_OPTIMISATION_READY,

    "empirical_validity":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_07_BLOCK_4_VALID,

    "block_complete":
        NOTEBOOK_07_BLOCK_4_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 07, Block 4: "
    "Social Target Availability, Variability, "
    "Activation and Loss-Contract Analysis"
)

print("=" * 72)

print(
    f"Block version                : "
    f"{NOTEBOOK_07_BLOCK_4_VERSION}"
)

print(
    f"Objective-policy version     : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VERSION}"
)


print("-" * 72)

print(
    "Accepted Social Representation supervision"
)

print(
    f"Source artefact              : "
    f"{NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_FILENAME}"
)

print(
    f"Source Drive file ID         : "
    f"{NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_FILE_ID}"
)

print(
    f"Artefact reloaded            : "
    f"{BLOCK_4_ACCEPTED_ARTEFACT_RELOADED}"
)

print(
    f"Accepted artefact valid      : "
    f"{BLOCK_4_ACCEPTED_ARTEFACT_VALID}"
)


print(
    f"Accepted artefact version    : "
    f"{BLOCK_4_ACCEPTED_VERSION}"
)

print(
    f"Provenance contract valid    : "
    f"{BLOCK_4_ACCEPTED_PROVENANCE_VALID}"
)

print(
    f"LLM annotation provenance    : "
    f"{BLOCK_4_ANNOTATION_LEVEL_LLM_PROVENANCE_VALID}"
)

print(
    f"Annotation/source alignment  : "
    f"{BLOCK_4_ANNOTATION_LEVEL_SOURCE_ALIGNMENT_VALID}"
)

print(
    f"Available evidence valid     : "
    f"{BLOCK_4_AVAILABLE_ANNOTATIONS_WITH_EVIDENCE_VALID}"
)

print(
    f"Sentences                    : "
    f"{NOTEBOOK_07_SENTENCE_COUNT}"
)

print(
    f"Social dimensions            : "
    f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM}"
)

print(
    f"Target matrix shape          : "
    f"{BLOCK_4_SOCIAL_TARGET_MATRIX.shape}"
)

print(
    f"Mask matrix shape            : "
    f"{BLOCK_4_SOCIAL_MASK_MATRIX.shape}"
)

print(
    f"Sentence IDs present         : "
    f"{BLOCK_4_SENTENCE_IDS_PRESENT}"
)

print(
    f"Sentence IDs unique          : "
    f"{BLOCK_4_SENTENCE_IDS_UNIQUE}"
)

print(
    f"Canonical set valid          : "
    f"{BLOCK_4_CANONICAL_SENTENCE_SET_VALID}"
)

print(
    f"Persisted order canonical    : "
    f"{BLOCK_4_PERSISTED_ORDER_MATCHES_CANONICAL}"
)

print(
    f"Canonical reorder applied    : "
    f"{BLOCK_4_CANONICAL_REORDER_APPLIED}"
)

print(
    f"Canonical order valid        : "
    f"{BLOCK_4_CANONICAL_ORDER_VALID}"
)

print(
    f"Canonical alignment valid    : "
    f"{BLOCK_4_CANONICAL_ALIGNMENT_VALID}"
)

print(
    f"Observed values finite       : "
    f"{BLOCK_4_OBSERVED_VALUES_FINITE}"
)

print(
    f"Masked values remain NaN     : "
    f"{BLOCK_4_MASKED_VALUES_ARE_NAN}"
)

print(
    f"Accepted coverage reproduced : "
    f"{BLOCK_4_ACCEPTED_COVERAGE_REPRODUCED}"
)

print(
    f"Dimension coverage reproduced: "
    f"{BLOCK_4_DIMENSION_COVERAGE_REPRODUCED}"
)


print("-" * 72)

print(
    "Supervision policy"
)

print(
    f"Minimum observed targets     : "
    f"{NOTEBOOK_07_SOCIAL_MINIMUM_OBSERVED_TARGETS}"
)

print(
    f"Threshold interpretation     : "
    f"controlled-sample methodological threshold"
)

print(
    f"Mask-aware supervision       : "
    f"{NOTEBOOK_07_SOCIAL_MASK_AWARE_SUPERVISION}"
)

print(
    f"Partial supervision allowed  : "
    f"{NOTEBOOK_07_SOCIAL_PARTIAL_SUPERVISION_ALLOWED}"
)

print(
    f"Missing = zero               : "
    f"{NOTEBOOK_07_SOCIAL_MISSING_EQUALS_ZERO}"
)

print(
    f"Missing = negative           : "
    f"{NOTEBOOK_07_SOCIAL_MISSING_EQUALS_NEGATIVE}"
)

print(
    f"Unavailable enters loss      : "
    f"{NOTEBOOK_07_SOCIAL_UNAVAILABLE_ENTERS_LOSS}"
)

print(
    f"Masking contract valid       : "
    f"{BLOCK_4_MASKING_CONTRACT_VALID}"
)


print("-" * 72)

print(
    "Social supervision coverage"
)

print(
    f"Available target elements    : "
    f"{BLOCK_4_REPRODUCED_AVAILABLE_ELEMENTS}"
)

print(
    f"Possible target elements     : "
    f"{BLOCK_4_REPRODUCED_POSSIBLE_ELEMENTS}"
)

print(
    f"Aggregate target coverage    : "
    f"{BLOCK_4_REPRODUCED_AGGREGATE_COVERAGE:.4f}"
)


print("-" * 72)

print(
    "Dimension availability, variability and activation"
)


for (
    dimension_id,
    dimension_name,
) in zip(
    NOTEBOOK_07_SOCIAL_DIMENSION_IDS,
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER,
):

    variance = (
        BLOCK_4_DIMENSION_VARIANCE[
            dimension_name
        ]
    )


    variance_display = (
        f"{variance:.8f}"
        if variance is not None
        else "None"
    )


    print(
        f"{dimension_id:<4} "
        f"{dimension_name:<29}: "
        f"observed="
        f"{BLOCK_4_DIMENSION_AVAILABLE_COUNTS[dimension_name]:<2} "
        f"coverage="
        f"{BLOCK_4_DIMENSION_COVERAGE[dimension_name]:.4f} "
        f"unique="
        f"{BLOCK_4_DIMENSION_UNIQUE_VALUES[dimension_name]:<2} "
        f"var="
        f"{variance_display}"
    )

    print(
        f"     target family             : "
        f"{NOTEBOOK_07_SOCIAL_DIMENSION_TARGET_FAMILY[dimension_name]}"
    )

    print(
        f"     target domain valid       : "
        f"{BLOCK_4_TARGET_DOMAIN_VALID[dimension_name]}"
    )

    print(
        f"     minimum supervision met   : "
        f"{BLOCK_4_DIMENSION_MINIMUM_SUPERVISION_MET[dimension_name]}"
    )

    print(
        f"     has variation             : "
        f"{BLOCK_4_DIMENSION_HAS_VARIATION[dimension_name]}"
    )

    print(
        f"     activation                : "
        f"{NOTEBOOK_07_SOCIAL_DIMENSION_ACTIVATION_STATE[dimension_name]}"
    )

    print(
        f"     deferral reason           : "
        f"{NOTEBOOK_07_SOCIAL_DIMENSION_DEFERRAL_REASON[dimension_name]}"
    )

    print(
        f"     loss family               : "
        f"{NOTEBOOK_07_SOCIAL_DIMENSION_LOSS_FAMILY[dimension_name]}"
    )


print("-" * 72)

print(
    "Controlled Social Representation objective policy"
)

print(
    f"Active dimensions            : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)}"
)

print(
    f"Active indices               : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_INDICES)}"
)

print(
    f"Deferred dimensions          : "
    f"{list(NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS)}"
)

print(
    f"Deferred indices             : "
    f"{list(NOTEBOOK_07_SOCIAL_DEFERRED_INDICES)}"
)

print(
    f"Active signed dimensions     : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_SIGNED_DIMENSIONS)}"
)

print(
    f"Active binary dimensions     : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_BINARY_DIMENSIONS)}"
)

print(
    f"Dynamic policy valid    : "
    f"{BLOCK_4_DYNAMIC_ACTIVATION_POLICY_VALID}"
)

print(
    f"Active loss families         : "
    f"{NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES}"
)

print(
    f"Objective-family weights     : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS}"
)

print(
    f"Objective weight sum         : "
    f"{BLOCK_4_OBJECTIVE_WEIGHT_SUM:.4f}"
)


print("-" * 72)

print(
    "Readiness"
)

print(
    f"Availability validated       : "
    f"{NOTEBOOK_07_SOCIAL_TARGET_AVAILABILITY_VALIDATED}"
)

print(
    f"Variability validated        : "
    f"{NOTEBOOK_07_SOCIAL_TARGET_VARIABILITY_VALIDATED}"
)

print(
    f"Activation contract resolved : "
    f"{NOTEBOOK_07_SOCIAL_ACTIVATION_CONTRACT_RESOLVED}"
)

print(
    f"Loss contract resolved       : "
    f"{NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_RESOLVED}"
)

print(
    f"Objective policy valid       : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID}"
)

print(
    f"Ready for model policy       : "
    f"{NOTEBOOK_07_READY_FOR_SOCIAL_MODEL_POLICY}"
)

print(
    f"Social model policy ready    : "
    f"{NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY}"
)

print(
    f"Optimisation ready           : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMISATION_READY}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Objectives activated         : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED}"
)

print(
    f"Forward pass executed        : "
    f"{NOTEBOOK_07_SOCIAL_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_07_SOCIAL_LOSS_CALCULATED}"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Social training executed     : "
    f"{NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Factual retraining           : "
    f"{NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative executed      : "
    f"{NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED}"
)

print(
    f"Transformative weights active: "
    f"{NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED}"
)

print(
    f"Recurrent executed           : "
    f"{NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED}"
)

print(
    f"Held-out evaluation executed : "
    f"{NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_07_BLOCK_4_VALID}"
)

print(
    f"Block 4 complete             : "
    f"{NOTEBOOK_07_BLOCK_4_COMPLETE}"
)


print("=" * 72)


print(
    "Notebook 07 Social Representation target availability, variability, "
    "activation and loss-contract analysis completed successfully."
)

print(
    "The persisted Block 3 accepted supervision was restored without "
    "reconstructing or extending accepted target values."
)

print(
    "Canonical sentence identity was preserved exactly; where persisted "
    "record order differed from the inherited Notebook 07 order, Block 4 "
    "constructed a local sentence-ID-aligned view without modifying the "
    "persisted supervision artefact."
)

print(
    "Unavailable supervision remains masked and numerically distinct from "
    "neutral zero and negative evidence."
)

print(
    "Aggregate supervision coverage remains an audit statistic and is not "
    "used as an optimisation threshold."
)

print(
    "The current minimum of three observed targets is a controlled-sample "
    "methodological threshold rather than a claim of statistical adequacy."
)

print(
    f"{len(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)} Social Representation "
    "dimension(s) satisfy the current data-driven activation policy."
)

print(
    f"{len(NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS)} dimension(s) remain "
    "structurally present but deferred according to current supervision "
    "availability, variability and target-domain evidence."
)

print(
    "Signed active dimensions use prospective mask-aware mean-squared-error "
    "objectives; active binary dimensions use binary cross-entropy with logits."
)

print(
    "The active objective families are weighted equally for subsequent "
    "controlled objective assembly."
)

print(
    "No Social Representation forward pass, loss calculation, optimiser, "
    "zero-gradient operation, backward pass, optimiser step, parameter "
    "update or training was executed."
)

print(
    "Successful Block 4 completion establishes Social Representation "
    "objective-policy readiness, not optimisation, generalisation or "
    "empirical validity."
)

print(
    "Block 5 may proceed to Social Representation Model Restoration, "
    "Parameter-Freezing Policy and Controlled Forward-Path Validation."
)

print("=" * 72)


# =============================================================================
# Display Social Representation dimension audit
# =============================================================================

display(
    BLOCK_4_SOCIAL_DIMENSION_AUDIT
)

========================================================================
Media AI — Notebook 07, Block 4: Social Target Availability, Variability, Activation and Loss-Contract Analysis
========================================================================
Block version                : 1.4
Objective-policy version     : 1.4
------------------------------------------------------------------------
Accepted Social Representation supervision
Source artefact              : notebook_07_accepted_social_supervision.json
Source Drive file ID         : 1RMofcYIqIFKH9FqSrAz5hjbicfSNu5ex
Artefact reloaded            : True
Accepted artefact valid      : True
Accepted artefact version    : 1.2
Provenance contract valid    : True
LLM annotation provenance    : True
Annotation/source alignment  : True
Available evidence valid     : True
Sentences                    : 54
Social dimensions            : 7
Target matrix shape          : (54, 7)
Mask matrix shape            : (54, 7)
Sentence IDs present         : True
Sentence IDs unique          : True
Canonical set valid          : True
Persisted order canonical    : False
Canonical reorder applied    : True
Canonical order valid        : True
Canonical alignment valid    : True
Observed values finite       : True
Masked values remain NaN     : True
Accepted coverage reproduced : True
Dimension coverage reproduced: True
------------------------------------------------------------------------
Supervision policy
Minimum observed targets     : 3
Threshold interpretation     : controlled-sample methodological threshold
Mask-aware supervision       : True
Partial supervision allowed  : True
Missing = zero               : False
Missing = negative           : False
Unavailable enters loss      : False
Masking contract valid       : True
------------------------------------------------------------------------
Social supervision coverage
Available target elements    : 155
Possible target elements     : 378
Aggregate target coverage    : 0.4101
------------------------------------------------------------------------
Dimension availability, variability and activation
S1   interpersonal_cohesion       : observed=26 coverage=0.4815 unique=10 var=0.43562130
     target family             : signed_cohesion
     target domain valid       : True
     minimum supervision met   : True
     has variation             : True
     activation                : eligible
     deferral reason           : None
     loss family               : masked_mean_squared_error
S2   economic_cohesion            : observed=3  coverage=0.0556 unique=3  var=0.18666667
     target family             : signed_cohesion
     target domain valid       : True
     minimum supervision met   : True
     has variation             : True
     activation                : eligible
     deferral reason           : None
     loss family               : masked_mean_squared_error
S3   political_cohesion           : observed=21 coverage=0.3889 unique=12 var=0.37292517
     target family             : signed_cohesion
     target domain valid       : True
     minimum supervision met   : True
     has variation             : True
     activation                : eligible
     deferral reason           : None
     loss family               : masked_mean_squared_error
S4   religious_cohesion           : observed=0  coverage=0.0000 unique=0  var=None
     target family             : signed_cohesion
     target domain valid       : True
     minimum supervision met   : False
     has variation             : False
     activation                : deferred_unavailable_supervision
     deferral reason           : unavailable_supervision
     loss family               : none
S5   group_collective_cohesion    : observed=32 coverage=0.5926 unique=11 var=0.42808594
     target family             : signed_cohesion
     target domain valid       : True
     minimum supervision met   : True
     has variation             : True
     activation                : eligible
     deferral reason           : None
     loss family               : masked_mean_squared_error
S6   institutional_role_relation  : observed=50 coverage=0.9259 unique=1  var=0.00000000
     target family             : binary_social_structure
     target domain valid       : True
     minimum supervision met   : True
     has variation             : False
     activation                : deferred_zero_variance
     deferral reason           : zero_variance
     loss family               : none
S7   public_audience_relation     : observed=23 coverage=0.4259 unique=1  var=0.00000000
     target family             : binary_social_structure
     target domain valid       : True
     minimum supervision met   : True
     has variation             : False
     activation                : deferred_zero_variance
     deferral reason           : zero_variance
     loss family               : none
------------------------------------------------------------------------
Controlled Social Representation objective policy
Active dimensions            : ['interpersonal_cohesion', 'economic_cohesion', 'political_cohesion', 'group_collective_cohesion']
Active indices               : [0, 1, 2, 4]
Deferred dimensions          : ['religious_cohesion', 'institutional_role_relation', 'public_audience_relation']
Deferred indices             : [3, 5, 6]
Active signed dimensions     : ['interpersonal_cohesion', 'economic_cohesion', 'political_cohesion', 'group_collective_cohesion']
Active binary dimensions     : []
Dynamic policy valid    : True
Active loss families         : {'interpersonal_cohesion': 'masked_mean_squared_error', 'economic_cohesion': 'masked_mean_squared_error', 'political_cohesion': 'masked_mean_squared_error', 'group_collective_cohesion': 'masked_mean_squared_error'}
Objective-family weights     : {'interpersonal_cohesion': 0.25, 'economic_cohesion': 0.25, 'political_cohesion': 0.25, 'group_collective_cohesion': 0.25}
Objective weight sum         : 1.0000
------------------------------------------------------------------------
Readiness
Availability validated       : True
Variability validated        : True
Activation contract resolved : True
Loss contract resolved       : True
Objective policy valid       : True
Ready for model policy       : True
Social model policy ready    : False
Optimisation ready           : False
------------------------------------------------------------------------
Execution boundary
Objectives activated         : False
Optimiser created            : False
Forward pass executed        : False
Loss calculated              : False
Zero grad executed           : False
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
Social training executed     : False
Psychological retraining     : False
Factual retraining           : False
Group-conditioned executed   : False
Transformative executed      : False
Transformative weights active: False
Recurrent executed           : False
Held-out evaluation executed : False
Empirical validity           : False
Block valid                  : True
Block 4 complete             : True
========================================================================
Notebook 07 Social Representation target availability, variability, activation and loss-contract analysis completed successfully.
The persisted Block 3 accepted supervision was restored without reconstructing or extending accepted target values.
Canonical sentence identity was preserved exactly; where persisted record order differed from the inherited Notebook 07 order, Block 4 constructed a local sentence-ID-aligned view without modifying the persisted supervision artefact.
Unavailable supervision remains masked and numerically distinct from neutral zero and negative evidence.
Aggregate supervision coverage remains an audit statistic and is not used as an optimisation threshold.
The current minimum of three observed targets is a controlled-sample methodological threshold rather than a claim of statistical adequacy.
4 Social Representation dimension(s) satisfy the current data-driven activation policy.
3 dimension(s) remain structurally present but deferred according to current supervision availability, variability and target-domain evidence.
Signed active dimensions use prospective mask-aware mean-squared-error objectives; active binary dimensions use binary cross-entropy with logits.
The active objective families are weighted equally for subsequent controlled objective assembly.
No Social Representation forward pass, loss calculation, optimiser, zero-gradient operation, backward pass, optimiser step, parameter update or training was executed.
Successful Block 4 completion establishes Social Representation objective-policy readiness, not optimisation, generalisation or empirical validity.
Block 5 may proceed to Social Representation Model Restoration, Parameter-Freezing Policy and Controlled Forward-Path Validation.
========================================================================

,dimension_id,dimension_index,target_name,target_family,available,masked,coverage,unique_values,minimum,maximum,mean,variance,target_domain_valid,minimum_supervision_met,has_variation,activation_state,deferral_reason,loss_family
0,S1,0,interpersonal_cohesion,signed_cohesion,26,28,0.481481,10,-0.8,0.9,0.223077,0.435621,True,True,True,eligible,None,masked_mean_squared_error
1,S2,1,economic_cohesion,signed_cohesion,3,51,0.055556,3,-0.2,0.8,0.200000,0.186667,True,True,True,eligible,None,masked_mean_squared_error
2,S3,2,political_cohesion,signed_cohesion,21,33,0.388889,12,-1.0,0.8,-0.057143,0.372925,True,True,True,eligible,None,masked_mean_squared_error
3,S4,3,religious_cohesion,signed_cohesion,0,54,0.000000,0,NaN,NaN,NaN,NaN,True,False,False,deferred_unavailable_supervision,unavailable_supervision,none
4,S5,4,group_collective_cohesion,signed_cohesion,32,22,0.592593,11,-1.0,1.0,0.306250,0.428086,True,True,True,eligible,None,masked_mean_squared_error
5,S6,5,institutional_role_relation,binary_social_structure,50,4,0.925926,1,1.0,1.0,1.000000,0.000000,True,True,False,deferred_zero_variance,zero_variance,none
6,S7,6,public_audience_relation,binary_social_structure,23,31,0.425926,1,1.0,1.0,1.000000,0.000000,True,True,False,deferred_zero_variance,zero_variance,none

## Block 5: Social Representation Model Restoration, Parameter-Freezing Policy and Controlled Forward-Path Validation

### Purpose

This block restores the validated model state required for the Social
Representation, establishes the Notebook 07 parameter-freezing policy and
validates a controlled Social Representation forward path without performing
optimisation.

The block follows the objective-policy contract resolved in Block 4.

Its purpose is to confirm that the inherited model architecture can support the
seven-dimensional Social Representation while preserving all previously
completed representation components.

No supervised social loss is calculated in this block.

No optimiser is created.

No backward pass or parameter update is executed.


### Persisted architecture boundary

Notebook 07 inherits the validated model architecture from the preceding
notebooks.

The operational path required for the Social Representation remains:

contextual sentence representation  
→ backbone  
→ mandatory global confluent representation  
→ Social Representation head

The canonical contextual representation remains sentence-oriented and may
contain permitted preceding context.

Future context remains prohibited.

The optional group-conditioned confluent path remains architecturally available
but is not part of the controlled Notebook 07 forward path.


### Inherited model state

Block 5 must restore the persisted model state rather than assuming that an
active runtime already contains the correct parameters.

The restoration process should reproduce the validated inherited state for:

- the textual/contextual representation interface;
- the backbone;
- the mandatory global confluent representation;
- the completed Psychological Representation;
- the completed Factual Representation.

The Social Representation head is the only new representation component to be
initialised or restored for Notebook 07.

Previous checkpoints remain immutable.


### Social Representation head

The Social Representation head must preserve the seven-dimensional semantic
contract established in Block 2:

- S1 — `interpersonal_cohesion`
- S2 — `economic_cohesion`
- S3 — `political_cohesion`
- S4 — `religious_cohesion`
- S5 — `group_collective_cohesion`
- S6 — `institutional_role_relation`
- S7 — `public_audience_relation`

The output layer must therefore produce exactly seven values per sentence.

All seven dimensions remain structurally present even though only S1, S3 and
S5 are currently active optimisation objectives.

Deferred dimensions must not be removed from the Social Representation output.


### Active and deferred supervision boundary

Block 4 established the currently active Social Representation dimensions as:

- S1 — `interpersonal_cohesion`
- S3 — `political_cohesion`
- S5 — `group_collective_cohesion`

The currently deferred dimensions are:

- S2 — `economic_cohesion`
- S4 — `religious_cohesion`
- S6 — `institutional_role_relation`
- S7 — `public_audience_relation`

The model output nevertheless remains seven-dimensional.

Activation affects later objective construction, not architectural output
dimensionality.


### Parameter-freezing policy

The inherited components remain frozen during Social Representation training
preparation.

The default policy is:

- backbone — frozen;
- mandatory global confluent representation — frozen;
- Psychological Representation head — frozen;
- Factual Representation head — frozen;
- Social Representation head — trainable.

The optional group-conditioned path remains inactive and outside the trainable
parameter scope.

The Transformative Mechanism remains inactive.

Transformative Weights remain inactive.

Recurrent mechanisms remain inactive.


### Trainable-parameter scope

Block 5 must explicitly verify that:

- every Social Representation parameter intended for later optimisation has
  `requires_grad=True`;
- every inherited frozen parameter has `requires_grad=False`;
- no psychological parameter is trainable;
- no factual parameter is trainable;
- no backbone parameter is trainable;
- no mandatory global confluent parameter is trainable;
- no optional group-conditioned parameter is included in the current trainable
  scope.

The exact number of trainable Social Representation parameters must be reported
and reproduced from the instantiated head.

The block must not assume a trainable parameter count without deriving it from
the actual restored architecture.


### Controlled input restoration

The controlled forward-path validation must use the canonical contextual
sentence representation aligned with the same 16 sentence identities used by
the accepted Social Representation supervision.

The block must verify:

- 16 sentence records are present;
- sentence IDs remain present;
- sentence IDs remain unique;
- ordering remains aligned with the accepted supervision;
- the contextual representation has the expected inherited interface
  dimensionality;
- all contextual input values are finite.

No sentence may be silently dropped or reordered.


### Controlled forward path

The controlled mandatory-global Social Representation forward path is:

1. contextual sentence representation;
2. frozen backbone;
3. frozen mandatory global confluent projection;
4. trainable Social Representation head.

The block must execute this path exactly once for validation.

The expected Social Representation output shape is:

`(16, 7)`

The block must verify that:

- backbone output shape matches its inherited interface contract;
- global confluent output shape matches the validated confluent dimension;
- Social Representation output has seven columns;
- every output value is finite;
- sentence ordering is preserved.


### Active-output extraction

After producing the full seven-dimensional Social Representation output,
Block 5 may derive the currently active output view using the Block 4 active
indices.

The active output should therefore contain:

- S1,
- S3,
- S5.

Its expected shape is:

`(16, 3)`

The deferred output view should contain:

- S2,
- S4,
- S6,
- S7.

Its expected shape is:

`(16, 4)`

These views are diagnostic only.

No loss is calculated from either view in this block.


### No-update validation

Because Block 5 performs a forward-path validation only, all model parameters
must remain numerically unchanged.

The block should snapshot the relevant parameter state before the controlled
forward pass and verify afterwards that:

- backbone parameters are unchanged;
- mandatory global confluent parameters are unchanged;
- Psychological Representation parameters are unchanged;
- Factual Representation parameters are unchanged;
- Social Representation parameters are unchanged.

The Social Representation head is trainable in policy, but no parameter update
may occur in Block 5.


### Gradient boundary

Block 5 does not execute a backward pass.

No optimiser is created.

No `zero_grad` operation is required.

No gradient-based update is permitted.

If gradients are produced inadvertently, the block should treat that as a
methodological-boundary violation.

The preferred controlled forward validation should therefore use an explicit
no-update context while preserving the `requires_grad` state required for
later training.


### Objective boundary

Block 5 does not calculate the Social Representation objective.

The Block 4 loss contract remains prospective:

- S1 — masked mean-squared error;
- S3 — masked mean-squared error;
- S5 — masked mean-squared error.

S2, S4, S6 and S7 remain excluded from the current controlled objective.

Objective calculation belongs to the next block.


### Group-conditioned boundary

The optional group-conditioned confluent path remains:

- structurally available;
- not required;
- not executed;
- not trained;
- deferred to Notebook 10.

Block 5 must not merge the mandatory global confluent path with the optional
group-conditioned path.

This separation must remain explicit in both architecture validation and
forward execution.


### Transformative and recurrent boundary

Block 5 does not activate:

- the Transformative Mechanism;
- Transformative Weights;
- recurrent states.

These remain reserved for later notebooks.

Notebook 08 remains responsible for the Transformative Mechanism.

Notebook 09 remains responsible for Transformative Weights and the Recurrent
Mechanism.

Notebook 10 remains responsible for group-conditioned processing and final
integration.


### Validation requirements

Block 5 must establish that:

- Notebook 07 Blocks 1–4 are complete and valid;
- the accepted Social Representation supervision contract remains available;
- the Block 4 objective policy remains valid;
- the persisted inherited model state can be restored;
- architecture dimensions are reproduced correctly;
- the Social Representation head outputs seven dimensions;
- the active indices reproduce S1, S3 and S5;
- the deferred indices reproduce S2, S4, S6 and S7;
- the backbone is frozen;
- the mandatory global confluent module is frozen;
- the Psychological Representation head is frozen;
- the Factual Representation head is frozen;
- only the Social Representation head is trainable;
- the trainable parameter count is derived and internally consistent;
- the canonical 16-sentence representation is aligned;
- all model inputs and outputs are finite;
- the controlled mandatory-global forward path succeeds;
- no group-conditioned processing is executed;
- no transformative processing is executed;
- no recurrent processing is executed;
- no parameter changes occur.


### Readiness boundary

Successful Block 5 completion should establish:

- Social model restored or initialised;
- Social Representation architecture valid;
- parameter-freezing policy valid;
- Social Representation output contract valid;
- controlled forward path valid;
- active/deferred output mapping valid;
- no-update validation valid;
- Social model policy ready.

This does not yet establish Social Representation optimisation readiness.

Optimisation readiness additionally requires controlled objective assembly and
loss validation in the subsequent block.


### Execution boundary

Block 5 may execute a controlled forward pass.

It must not:

- calculate supervised Social Representation loss;
- create an optimiser;
- execute `zero_grad`;
- execute a backward pass;
- execute an optimiser step;
- update parameters;
- train the Social Representation;
- retrain the Psychological Representation;
- retrain the Factual Representation;
- retrain the backbone;
- retrain the mandatory global confluent module;
- execute the optional group-conditioned path;
- activate the Transformative Mechanism;
- activate Transformative Weights;
- activate recurrent processing;
- perform held-out evaluation;
- claim generalisation;
- establish empirical validity.


### Expected Block 5 outcome

If the inherited architecture restores correctly, the controlled Social
Representation forward path should produce:

- 16 backbone representations;
- 16 mandatory global confluent representations;
- a full Social Representation output with shape `(16, 7)`;
- an active Social Representation view with shape `(16, 3)`;
- a deferred Social Representation view with shape `(16, 4)`.

Only the Social Representation head should remain trainable.

No parameter should change during the block.

The next block may proceed to:

**Social Representation Objective Assembly, Optimiser Policy and Controlled
Loss Validation.**
"""

In [18]:
# =============================================================================
# Media AI — Notebook 07
# Block 5: Social Representation Model Restoration,
#          Parameter-Freezing Policy and Controlled Forward-Path Validation
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json

import numpy as np
import torch
import torch.nn as nn

from googleapiclient.http import MediaIoBaseDownload


# =============================================================================
# Dependency checks
# =============================================================================

required_block_5_objects = [
    "NOTEBOOK_07_BLOCK_1_COMPLETE",
    "NOTEBOOK_07_BLOCK_1_VALID",

    "NOTEBOOK_07_BLOCK_2_COMPLETE",
    "NOTEBOOK_07_BLOCK_2_VALID",

    "NOTEBOOK_07_BLOCK_3_COMPLETE",
    "NOTEBOOK_07_BLOCK_3_VALID",

    "NOTEBOOK_07_BLOCK_4_COMPLETE",
    "NOTEBOOK_07_BLOCK_4_VALID",

    "NOTEBOOK_07_DRIVE_SERVICE",
    "NOTEBOOK_07_HANDOVER",

    "NOTEBOOK_07_SENTENCE_IDS",
    "NOTEBOOK_07_SENTENCE_COUNT",

    "NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_SOCIAL_DIMENSION_IDS",
    "NOTEBOOK_07_SOCIAL_DIMENSION_ORDER",

    "NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_ACTIVE_INDICES",

    "NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_DEFERRED_INDICES",

    "NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID",
    "NOTEBOOK_07_READY_FOR_SOCIAL_MODEL_POLICY",

    "NOTEBOOK_07_FACTUAL_CHECKPOINT_DRIVE_FILE_ID",
    "NOTEBOOK_07_FACTUAL_CHECKPOINT_TYPE",
]


missing_block_5_objects = [
    object_name
    for object_name in required_block_5_objects
    if object_name not in globals()
]


if missing_block_5_objects:

    raise NameError(
        "Notebook 07 Block 5 prerequisites are not initialised. "
        f"Missing: {missing_block_5_objects}"
    )


if not all(
    [
        NOTEBOOK_07_BLOCK_1_COMPLETE,
        NOTEBOOK_07_BLOCK_1_VALID,

        NOTEBOOK_07_BLOCK_2_COMPLETE,
        NOTEBOOK_07_BLOCK_2_VALID,

        NOTEBOOK_07_BLOCK_3_COMPLETE,
        NOTEBOOK_07_BLOCK_3_VALID,

        NOTEBOOK_07_BLOCK_4_COMPLETE,
        NOTEBOOK_07_BLOCK_4_VALID,

        NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID,
        NOTEBOOK_07_READY_FOR_SOCIAL_MODEL_POLICY,
    ]
):

    raise RuntimeError(
        "Notebook 07 Blocks 1–4 must be complete and valid "
        "before Block 5."
    )


if not isinstance(
    NOTEBOOK_07_HANDOVER,
    dict,
):

    raise TypeError(
        "NOTEBOOK_07_HANDOVER must be dictionary-like."
    )


if NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM != 7:

    raise RuntimeError(
        "Block 5 requires the validated seven-dimensional "
        "Social Representation."
    )


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_07_BLOCK_5 = 5

NOTEBOOK_07_BLOCK_5_NAME = (
    "Social Representation Model Restoration, "
    "Parameter-Freezing Policy and Controlled Forward-Path Validation"
)

NOTEBOOK_07_BLOCK_5_VERSION = "1.6"

NOTEBOOK_07_RANDOM_SEED = 42


BLOCK_5_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Canonical inherited architecture contract
# =============================================================================

NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM = 768

NOTEBOOK_07_BACKBONE_INTERFACE_DIM = 768

NOTEBOOK_07_GLOBAL_CONFLUENT_DIM = 256

NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM = 128

NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_DIM = 34

NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM = 10

NOTEBOOK_07_GLOBAL_CONFLUENT_DROPOUT = 0.0

NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT = 0.0


# =============================================================================
# Reproducibility
# =============================================================================

np.random.seed(
    NOTEBOOK_07_RANDOM_SEED
)


torch.manual_seed(
    NOTEBOOK_07_RANDOM_SEED
)


if torch.cuda.is_available():

    torch.cuda.manual_seed_all(
        NOTEBOOK_07_RANDOM_SEED
    )


# =============================================================================
# Device
# =============================================================================

BLOCK_5_DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)


# =============================================================================
# Execution boundary
# =============================================================================

NOTEBOOK_07_SOCIAL_MODEL_FORWARD_EXECUTED = False

NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED = False

NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED = False

NOTEBOOK_07_SOCIAL_LOSS_CALCULATED = False

NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED = False

NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED = False

NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED = False

NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED = False

NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Deterministic inherited architecture
# =============================================================================

class Notebook07Backbone(
    nn.Module
):

    def __init__(
        self,
        input_dim=NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM,
        output_dim=NOTEBOOK_07_BACKBONE_INTERFACE_DIM,
    ):

        super().__init__()


        self.projection = nn.Linear(
            input_dim,
            output_dim,
        )


    def forward(
        self,
        x,
    ):

        return self.projection(
            x
        )


class Notebook07GlobalConfluent(
    nn.Module
):

    def __init__(
        self,
        input_dim=NOTEBOOK_07_BACKBONE_INTERFACE_DIM,
        output_dim=NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,
        dropout=NOTEBOOK_07_GLOBAL_CONFLUENT_DROPOUT,
    ):

        super().__init__()


        self.global_projection = nn.Sequential(
            nn.Linear(
                input_dim,
                output_dim,
            ),

            nn.ReLU(),

            nn.Dropout(
                dropout
            ),

            nn.LayerNorm(
                output_dim
            ),
        )


    def forward(
        self,
        x,
    ):

        return self.global_projection(
            x
        )


class Notebook07RepresentationCore(
    nn.Module
):

    def __init__(
        self,
        input_dim=NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,
        hidden_dim=NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,
        dropout=NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT,
    ):

        super().__init__()


        self.network = nn.Sequential(
            nn.Linear(
                input_dim,
                hidden_dim,
            ),

            nn.ReLU(),

            nn.Dropout(
                dropout
            ),

            nn.LayerNorm(
                hidden_dim
            ),
        )


    def forward(
        self,
        x,
    ):

        return self.network(
            x
        )


class Notebook07RepresentationHead(
    nn.Module
):

    def __init__(
        self,
        input_dim,
        hidden_dim,
        output_dim,
        dropout=NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT,
    ):

        super().__init__()


        self.core = Notebook07RepresentationCore(
            input_dim=
                input_dim,

            hidden_dim=
                hidden_dim,

            dropout=
                dropout,
        )


        self.output_layer = nn.Linear(
            hidden_dim,
            output_dim,
        )


    def forward(
        self,
        x,
    ):

        return self.output_layer(
            self.core(
                x
            )
        )


# =============================================================================
# Explicit architecture validation
# =============================================================================

BLOCK_5_BACKBONE_ARCHITECTURE_INSTANCE = (
    Notebook07Backbone()
)


BLOCK_5_BACKBONE_ARCHITECTURE_VALID = all(
    [
        isinstance(
            BLOCK_5_BACKBONE_ARCHITECTURE_INSTANCE.projection,
            nn.Linear,
        ),

        (
            BLOCK_5_BACKBONE_ARCHITECTURE_INSTANCE.projection.in_features
            ==
            NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM
        ),

        (
            BLOCK_5_BACKBONE_ARCHITECTURE_INSTANCE.projection.out_features
            ==
            NOTEBOOK_07_BACKBONE_INTERFACE_DIM
        ),
    ]
)


BLOCK_5_GLOBAL_ARCHITECTURE_INSTANCE = (
    Notebook07GlobalConfluent()
)


BLOCK_5_GLOBAL_ARCHITECTURE_VALID = all(
    [
        isinstance(
            BLOCK_5_GLOBAL_ARCHITECTURE_INSTANCE.global_projection[0],
            nn.Linear,
        ),

        (
            BLOCK_5_GLOBAL_ARCHITECTURE_INSTANCE
            .global_projection[0]
            .in_features
            ==
            NOTEBOOK_07_BACKBONE_INTERFACE_DIM
        ),

        (
            BLOCK_5_GLOBAL_ARCHITECTURE_INSTANCE
            .global_projection[0]
            .out_features
            ==
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM
        ),

        isinstance(
            BLOCK_5_GLOBAL_ARCHITECTURE_INSTANCE.global_projection[1],
            nn.ReLU,
        ),

        isinstance(
            BLOCK_5_GLOBAL_ARCHITECTURE_INSTANCE.global_projection[2],
            nn.Dropout,
        ),

        np.isclose(
            BLOCK_5_GLOBAL_ARCHITECTURE_INSTANCE.global_projection[2].p,
            NOTEBOOK_07_GLOBAL_CONFLUENT_DROPOUT,
        ),

        isinstance(
            BLOCK_5_GLOBAL_ARCHITECTURE_INSTANCE.global_projection[3],
            nn.LayerNorm,
        ),

        (
            tuple(
                BLOCK_5_GLOBAL_ARCHITECTURE_INSTANCE
                .global_projection[3]
                .normalized_shape
            )
            ==
            (
                NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,
            )
        ),
    ]
)


BLOCK_5_CORE_ARCHITECTURE_INSTANCE = (
    Notebook07RepresentationCore()
)


BLOCK_5_REPRESENTATION_CORE_ARCHITECTURE_VALID = all(
    [
        isinstance(
            BLOCK_5_CORE_ARCHITECTURE_INSTANCE.network[0],
            nn.Linear,
        ),

        (
            BLOCK_5_CORE_ARCHITECTURE_INSTANCE.network[0].in_features
            ==
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM
        ),

        (
            BLOCK_5_CORE_ARCHITECTURE_INSTANCE.network[0].out_features
            ==
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM
        ),

        isinstance(
            BLOCK_5_CORE_ARCHITECTURE_INSTANCE.network[1],
            nn.ReLU,
        ),

        isinstance(
            BLOCK_5_CORE_ARCHITECTURE_INSTANCE.network[2],
            nn.Dropout,
        ),

        np.isclose(
            BLOCK_5_CORE_ARCHITECTURE_INSTANCE.network[2].p,
            NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT,
        ),

        isinstance(
            BLOCK_5_CORE_ARCHITECTURE_INSTANCE.network[3],
            nn.LayerNorm,
        ),

        (
            tuple(
                BLOCK_5_CORE_ARCHITECTURE_INSTANCE
                .network[3]
                .normalized_shape
            )
            ==
            (
                NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,
            )
        ),
    ]
)


BLOCK_5_EXPLICIT_ARCHITECTURE_VALID = all(
    [
        BLOCK_5_BACKBONE_ARCHITECTURE_VALID,
        BLOCK_5_GLOBAL_ARCHITECTURE_VALID,
        BLOCK_5_REPRESENTATION_CORE_ARCHITECTURE_VALID,
    ]
)


if not BLOCK_5_EXPLICIT_ARCHITECTURE_VALID:

    raise RuntimeError(
        "Explicit inherited Media AI architecture reconstruction "
        "is invalid."
    )


# =============================================================================
# Drive download helper
# =============================================================================

def block_5_download_drive_bytes(
    drive_service,
    file_id,
):

    request = (
        drive_service.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Reload persisted Notebook 06 factual checkpoint
# =============================================================================

BLOCK_5_FACTUAL_CHECKPOINT_BYTES = (
    block_5_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_FACTUAL_CHECKPOINT_DRIVE_FILE_ID,
    )
)


if not BLOCK_5_FACTUAL_CHECKPOINT_BYTES:

    raise RuntimeError(
        "Persisted Notebook 06 factual checkpoint was empty."
    )


BLOCK_5_FACTUAL_CHECKPOINT_BUFFER = io.BytesIO(
    BLOCK_5_FACTUAL_CHECKPOINT_BYTES
)


try:

    BLOCK_5_FACTUAL_CHECKPOINT = torch.load(
        BLOCK_5_FACTUAL_CHECKPOINT_BUFFER,
        map_location=
            "cpu",
        weights_only=
            False,
    )


except TypeError:

    BLOCK_5_FACTUAL_CHECKPOINT_BUFFER.seek(
        0
    )


    BLOCK_5_FACTUAL_CHECKPOINT = torch.load(
        BLOCK_5_FACTUAL_CHECKPOINT_BUFFER,
        map_location=
            "cpu",
    )


if not isinstance(
    BLOCK_5_FACTUAL_CHECKPOINT,
    dict,
):

    raise TypeError(
        "Persisted Notebook 06 factual checkpoint must be a dictionary."
    )


BLOCK_5_CHECKPOINT_RELOADED = True


# =============================================================================
# Checkpoint contract
# =============================================================================

BLOCK_5_REQUIRED_CHECKPOINT_KEYS = (
    "checkpoint_type",
    "backbone_state_dict",
    "global_confluent_state_dict",
    "factual_head_state_dict",
    "psychological_head_state_dict",
)


BLOCK_5_MISSING_CHECKPOINT_KEYS = [
    key
    for key in BLOCK_5_REQUIRED_CHECKPOINT_KEYS
    if key not in BLOCK_5_FACTUAL_CHECKPOINT
]


if BLOCK_5_MISSING_CHECKPOINT_KEYS:

    raise RuntimeError(
        "Persisted Notebook 06 factual checkpoint is missing "
        "required inherited state. "
        f"Missing: {BLOCK_5_MISSING_CHECKPOINT_KEYS}"
    )


BLOCK_5_CHECKPOINT_TYPE_REPRODUCED = (
    BLOCK_5_FACTUAL_CHECKPOINT[
        "checkpoint_type"
    ]
    ==
    NOTEBOOK_07_FACTUAL_CHECKPOINT_TYPE
)


if not BLOCK_5_CHECKPOINT_TYPE_REPRODUCED:

    raise RuntimeError(
        "Persisted checkpoint type does not reproduce the "
        "Notebook 07 inherited handover contract."
    )


# =============================================================================
# Canonical inherited state dictionaries
# =============================================================================

BLOCK_5_BACKBONE_STATE_DICT = deepcopy(
    BLOCK_5_FACTUAL_CHECKPOINT[
        "backbone_state_dict"
    ]
)


BLOCK_5_GLOBAL_CONFLUENT_STATE_DICT = deepcopy(
    BLOCK_5_FACTUAL_CHECKPOINT[
        "global_confluent_state_dict"
    ]
)


BLOCK_5_FACTUAL_HEAD_STATE_DICT = deepcopy(
    BLOCK_5_FACTUAL_CHECKPOINT[
        "factual_head_state_dict"
    ]
)


BLOCK_5_PSYCHOLOGICAL_HEAD_STATE_DICT = deepcopy(
    BLOCK_5_FACTUAL_CHECKPOINT[
        "psychological_head_state_dict"
    ]
)


BLOCK_5_CHECKPOINT_STATE_CONTRACT_VALID = all(
    [
        isinstance(
            BLOCK_5_BACKBONE_STATE_DICT,
            dict,
        ),
        bool(
            BLOCK_5_BACKBONE_STATE_DICT
        ),

        isinstance(
            BLOCK_5_GLOBAL_CONFLUENT_STATE_DICT,
            dict,
        ),
        bool(
            BLOCK_5_GLOBAL_CONFLUENT_STATE_DICT
        ),

        isinstance(
            BLOCK_5_FACTUAL_HEAD_STATE_DICT,
            dict,
        ),
        bool(
            BLOCK_5_FACTUAL_HEAD_STATE_DICT
        ),

        isinstance(
            BLOCK_5_PSYCHOLOGICAL_HEAD_STATE_DICT,
            dict,
        ),
        bool(
            BLOCK_5_PSYCHOLOGICAL_HEAD_STATE_DICT
        ),
    ]
)


if not BLOCK_5_CHECKPOINT_STATE_CONTRACT_VALID:

    raise RuntimeError(
        "One or more persisted inherited state dictionaries "
        "are invalid or empty."
    )


# =============================================================================
# Persisted parameter topology
# =============================================================================

def block_5_state_shape_map(
    state_dict,
):

    return {
        parameter_name:
            tuple(
                parameter_tensor.shape
            )

        for (
            parameter_name,
            parameter_tensor,
        ) in state_dict.items()
    }


BLOCK_5_EXPECTED_BACKBONE_TOPOLOGY = {
    "projection.weight":
        (
            NOTEBOOK_07_BACKBONE_INTERFACE_DIM,
            NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM,
        ),

    "projection.bias":
        (
            NOTEBOOK_07_BACKBONE_INTERFACE_DIM,
        ),
}


BLOCK_5_EXPECTED_GLOBAL_CONFLUENT_TOPOLOGY = {
    "global_projection.0.weight":
        (
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,
            NOTEBOOK_07_BACKBONE_INTERFACE_DIM,
        ),

    "global_projection.0.bias":
        (
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,
        ),

    "global_projection.3.weight":
        (
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,
        ),

    "global_projection.3.bias":
        (
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,
        ),
}


def block_5_expected_head_topology(
    output_dim,
):

    return {
        "core.network.0.weight":
            (
                NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,
                NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,
            ),

        "core.network.0.bias":
            (
                NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,
            ),

        "core.network.3.weight":
            (
                NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,
            ),

        "core.network.3.bias":
            (
                NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,
            ),

        "output_layer.weight":
            (
                output_dim,
                NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,
            ),

        "output_layer.bias":
            (
                output_dim,
            ),
    }


BLOCK_5_EXPECTED_FACTUAL_TOPOLOGY = (
    block_5_expected_head_topology(
        NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM
    )
)


BLOCK_5_EXPECTED_PSYCHOLOGICAL_TOPOLOGY = (
    block_5_expected_head_topology(
        NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_DIM
    )
)


BLOCK_5_BACKBONE_STATE_TOPOLOGY_VALID = (
    block_5_state_shape_map(
        BLOCK_5_BACKBONE_STATE_DICT
    )
    ==
    BLOCK_5_EXPECTED_BACKBONE_TOPOLOGY
)


BLOCK_5_GLOBAL_CONFLUENT_STATE_TOPOLOGY_VALID = (
    block_5_state_shape_map(
        BLOCK_5_GLOBAL_CONFLUENT_STATE_DICT
    )
    ==
    BLOCK_5_EXPECTED_GLOBAL_CONFLUENT_TOPOLOGY
)


BLOCK_5_FACTUAL_STATE_TOPOLOGY_VALID = (
    block_5_state_shape_map(
        BLOCK_5_FACTUAL_HEAD_STATE_DICT
    )
    ==
    BLOCK_5_EXPECTED_FACTUAL_TOPOLOGY
)


BLOCK_5_PSYCHOLOGICAL_STATE_TOPOLOGY_VALID = (
    block_5_state_shape_map(
        BLOCK_5_PSYCHOLOGICAL_HEAD_STATE_DICT
    )
    ==
    BLOCK_5_EXPECTED_PSYCHOLOGICAL_TOPOLOGY
)


BLOCK_5_PERSISTED_TOPOLOGY_VALID = all(
    [
        BLOCK_5_BACKBONE_STATE_TOPOLOGY_VALID,
        BLOCK_5_GLOBAL_CONFLUENT_STATE_TOPOLOGY_VALID,
        BLOCK_5_FACTUAL_STATE_TOPOLOGY_VALID,
        BLOCK_5_PSYCHOLOGICAL_STATE_TOPOLOGY_VALID,
    ]
)


if not BLOCK_5_PERSISTED_TOPOLOGY_VALID:

    raise RuntimeError(
        "Persisted Notebook 06 parameter topology does not match "
        "the validated Media AI architecture."
    )


# =============================================================================
# Deterministic inherited module reconstruction
# =============================================================================

NOTEBOOK_07_BACKBONE_FROZEN_MODULE = (
    Notebook07Backbone(
        input_dim=
            NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM,

        output_dim=
            NOTEBOOK_07_BACKBONE_INTERFACE_DIM,
    )
)


NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE = (
    Notebook07GlobalConfluent(
        input_dim=
            NOTEBOOK_07_BACKBONE_INTERFACE_DIM,

        output_dim=
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,

        dropout=
            NOTEBOOK_07_GLOBAL_CONFLUENT_DROPOUT,
    )
)


NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE = (
    Notebook07RepresentationHead(
        input_dim=
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,

        hidden_dim=
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,

        output_dim=
            NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM,

        dropout=
            NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT,
    )
)


NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE = (
    Notebook07RepresentationHead(
        input_dim=
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,

        hidden_dim=
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,

        output_dim=
            NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_DIM,

        dropout=
            NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT,
    )
)


# =============================================================================
# Strict inherited-state restoration
# =============================================================================

NOTEBOOK_07_BACKBONE_FROZEN_MODULE.load_state_dict(
    BLOCK_5_BACKBONE_STATE_DICT,
    strict=True,
)


NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.load_state_dict(
    BLOCK_5_GLOBAL_CONFLUENT_STATE_DICT,
    strict=True,
)


NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE.load_state_dict(
    BLOCK_5_FACTUAL_HEAD_STATE_DICT,
    strict=True,
)


NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.load_state_dict(
    BLOCK_5_PSYCHOLOGICAL_HEAD_STATE_DICT,
    strict=True,
)


# =============================================================================
# Exact state reproduction
# =============================================================================

def block_5_state_dict_exact_match(
    module,
    expected_state_dict,
):

    observed_state_dict = (
        module.state_dict()
    )


    if (
        tuple(
            observed_state_dict.keys()
        )
        !=
        tuple(
            expected_state_dict.keys()
        )
    ):

        return False


    return all(
        torch.equal(
            observed_state_dict[
                parameter_name
            ]
            .detach()
            .cpu(),

            expected_state_dict[
                parameter_name
            ]
            .detach()
            .cpu(),
        )

        for parameter_name
        in expected_state_dict
    )


BLOCK_5_BACKBONE_STATE_REPRODUCED = (
    block_5_state_dict_exact_match(
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE,
        BLOCK_5_BACKBONE_STATE_DICT,
    )
)


BLOCK_5_GLOBAL_CONFLUENT_STATE_REPRODUCED = (
    block_5_state_dict_exact_match(
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE,
        BLOCK_5_GLOBAL_CONFLUENT_STATE_DICT,
    )
)


BLOCK_5_FACTUAL_STATE_REPRODUCED = (
    block_5_state_dict_exact_match(
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE,
        BLOCK_5_FACTUAL_HEAD_STATE_DICT,
    )
)


BLOCK_5_PSYCHOLOGICAL_STATE_REPRODUCED = (
    block_5_state_dict_exact_match(
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE,
        BLOCK_5_PSYCHOLOGICAL_HEAD_STATE_DICT,
    )
)


BLOCK_5_INHERITED_STATE_REPRODUCED = all(
    [
        BLOCK_5_BACKBONE_STATE_REPRODUCED,
        BLOCK_5_GLOBAL_CONFLUENT_STATE_REPRODUCED,
        BLOCK_5_FACTUAL_STATE_REPRODUCED,
        BLOCK_5_PSYCHOLOGICAL_STATE_REPRODUCED,
    ]
)


if not BLOCK_5_INHERITED_STATE_REPRODUCED:

    raise RuntimeError(
        "One or more inherited Media AI modules failed exact "
        "checkpoint-state reproduction."
    )


# =============================================================================
# Construct fresh Social Representation head
# =============================================================================

torch.manual_seed(
    NOTEBOOK_07_RANDOM_SEED
)


if torch.cuda.is_available():

    torch.cuda.manual_seed_all(
        NOTEBOOK_07_RANDOM_SEED
    )


NOTEBOOK_07_SOCIAL_HEAD = (
    Notebook07RepresentationHead(
        input_dim=
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,

        hidden_dim=
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,

        output_dim=
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

        dropout=
            NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT,
    )
)


BLOCK_5_SOCIAL_HEAD_INITIALISED = True

BLOCK_5_SOCIAL_HEAD_FRESH_INITIALISATION = True

BLOCK_5_SOCIAL_HEAD_INHERITED_FACTUAL_WEIGHTS = False

BLOCK_5_SOCIAL_HEAD_INHERITED_PSYCHOLOGICAL_WEIGHTS = False


# =============================================================================
# Social architecture validation
# =============================================================================

BLOCK_5_SOCIAL_ARCHITECTURE_VALID = all(
    [
        isinstance(
            NOTEBOOK_07_SOCIAL_HEAD.core.network[0],
            nn.Linear,
        ),

        (
            NOTEBOOK_07_SOCIAL_HEAD.core.network[0].in_features
            ==
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM
        ),

        (
            NOTEBOOK_07_SOCIAL_HEAD.core.network[0].out_features
            ==
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM
        ),

        isinstance(
            NOTEBOOK_07_SOCIAL_HEAD.core.network[1],
            nn.ReLU,
        ),

        isinstance(
            NOTEBOOK_07_SOCIAL_HEAD.core.network[2],
            nn.Dropout,
        ),

        np.isclose(
            NOTEBOOK_07_SOCIAL_HEAD.core.network[2].p,
            NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT,
        ),

        isinstance(
            NOTEBOOK_07_SOCIAL_HEAD.core.network[3],
            nn.LayerNorm,
        ),

        (
            tuple(
                NOTEBOOK_07_SOCIAL_HEAD
                .core.network[3]
                .normalized_shape
            )
            ==
            (
                NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,
            )
        ),

        isinstance(
            NOTEBOOK_07_SOCIAL_HEAD.output_layer,
            nn.Linear,
        ),

        (
            NOTEBOOK_07_SOCIAL_HEAD.output_layer.in_features
            ==
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM
        ),

        (
            NOTEBOOK_07_SOCIAL_HEAD.output_layer.out_features
            ==
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
        ),
    ]
)


if not BLOCK_5_SOCIAL_ARCHITECTURE_VALID:

    raise RuntimeError(
        "Social Representation head does not preserve the "
        "validated shared representation-head architecture."
    )


# =============================================================================
# Resolve authoritative contextual-representation handover contract
# =============================================================================
#
# Notebook 07 does not necessarily retain NOTEBOOK_06_REPRESENTATION_DRIVE_FILE_ID
# as a top-level runtime variable.
#
# The Notebook 06 -> 07 handover embeds the original Notebook 05 -> 06
# contextual-representation contract at:
#
# inherited_notebook_05_to_06_handover
#     -> contextual_representation
#
# This nested handover contract is authoritative.
# =============================================================================

BLOCK_5_INHERITED_05_TO_06_HANDOVER = (
    NOTEBOOK_07_HANDOVER.get(
        "inherited_notebook_05_to_06_handover"
    )
)


if not isinstance(
    BLOCK_5_INHERITED_05_TO_06_HANDOVER,
    dict,
):

    raise RuntimeError(
        "Notebook 07 handover does not contain the inherited "
        "Notebook 05 -> 06 handover contract."
    )


BLOCK_5_CONTEXTUAL_REPRESENTATION_CONTRACT = (
    BLOCK_5_INHERITED_05_TO_06_HANDOVER.get(
        "contextual_representation"
    )
)


if not isinstance(
    BLOCK_5_CONTEXTUAL_REPRESENTATION_CONTRACT,
    dict,
):

    raise RuntimeError(
        "Inherited Notebook 05 -> 06 handover does not contain "
        "the contextual_representation contract."
    )


BLOCK_5_REPRESENTATION_DRIVE_FILE_ID = (
    BLOCK_5_CONTEXTUAL_REPRESENTATION_CONTRACT.get(
        "artifact_drive_file_id"
    )
)


BLOCK_5_REPRESENTATION_FILENAME = (
    BLOCK_5_CONTEXTUAL_REPRESENTATION_CONTRACT.get(
        "artifact_filename"
    )
)


BLOCK_5_REPRESENTATION_PROVIDER = (
    BLOCK_5_CONTEXTUAL_REPRESENTATION_CONTRACT.get(
        "provider"
    )
)


BLOCK_5_REPRESENTATION_MODEL_ID = (
    BLOCK_5_CONTEXTUAL_REPRESENTATION_CONTRACT.get(
        "model_id"
    )
)


BLOCK_5_REPRESENTATION_DIMENSION_FROM_HANDOVER = (
    BLOCK_5_CONTEXTUAL_REPRESENTATION_CONTRACT.get(
        "dimension"
    )
)


BLOCK_5_REPRESENTATION_SENTENCE_COUNT_FROM_HANDOVER = (
    BLOCK_5_CONTEXTUAL_REPRESENTATION_CONTRACT.get(
        "sentence_count"
    )
)


BLOCK_5_REPRESENTATION_ENCODER_FROZEN = (
    BLOCK_5_CONTEXTUAL_REPRESENTATION_CONTRACT.get(
        "encoder_frozen"
    )
)


BLOCK_5_REPRESENTATION_ALIGNMENT_REQUIRED = (
    BLOCK_5_CONTEXTUAL_REPRESENTATION_CONTRACT.get(
        "sentence_alignment_required"
    )
)


BLOCK_5_REPRESENTATION_FILE_ID_SOURCE = (
    "NOTEBOOK_07_HANDOVER."
    "inherited_notebook_05_to_06_handover."
    "contextual_representation.artifact_drive_file_id"
)


BLOCK_5_CONTEXTUAL_HANDOVER_CONTRACT_VALID = all(
    [
        isinstance(
            BLOCK_5_REPRESENTATION_DRIVE_FILE_ID,
            str,
        ),

        bool(
            (
                BLOCK_5_REPRESENTATION_DRIVE_FILE_ID
                or ""
            ).strip()
        ),

        isinstance(
            BLOCK_5_REPRESENTATION_FILENAME,
            str,
        ),

        bool(
            (
                BLOCK_5_REPRESENTATION_FILENAME
                or ""
            ).strip()
        ),

        (
            BLOCK_5_REPRESENTATION_DIMENSION_FROM_HANDOVER
            ==
            NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM
        ),

        (
            BLOCK_5_REPRESENTATION_SENTENCE_COUNT_FROM_HANDOVER
            ==
            NOTEBOOK_07_SENTENCE_COUNT
        ),

        (
            BLOCK_5_REPRESENTATION_ENCODER_FROZEN
            is True
        ),

        (
            BLOCK_5_REPRESENTATION_ALIGNMENT_REQUIRED
            is True
        ),
    ]
)


if not BLOCK_5_CONTEXTUAL_HANDOVER_CONTRACT_VALID:

    raise RuntimeError(
        "Inherited contextual-representation handover contract is invalid."
    )


# =============================================================================
# Optional runtime-alias cross-check
# =============================================================================
#
# Runtime aliases are not required. If present, however, they must agree
# with the authoritative handover artefact ID.
# =============================================================================

BLOCK_5_REPRESENTATION_ALIAS_VALUES = {}


for alias_name in (
    "NOTEBOOK_07_REPRESENTATION_DRIVE_FILE_ID",
    "NOTEBOOK_07_CONTEXTUAL_REPRESENTATION_DRIVE_FILE_ID",
    "NOTEBOOK_06_REPRESENTATION_DRIVE_FILE_ID",
):

    if alias_name not in globals():

        continue


    alias_value = globals()[
        alias_name
    ]


    if (
        isinstance(
            alias_value,
            str,
        )
        and
        alias_value.strip()
    ):

        BLOCK_5_REPRESENTATION_ALIAS_VALUES[
            alias_name
        ] = alias_value.strip()


BLOCK_5_REPRESENTATION_ALIASES_CONSISTENT = all(
    alias_value
    ==
    BLOCK_5_REPRESENTATION_DRIVE_FILE_ID

    for alias_value
    in BLOCK_5_REPRESENTATION_ALIAS_VALUES.values()
)


if not BLOCK_5_REPRESENTATION_ALIASES_CONSISTENT:

    raise RuntimeError(
        "One or more runtime contextual-representation Drive IDs "
        "conflict with the authoritative Notebook 07 handover contract. "
        f"Authoritative ID: "
        f"{BLOCK_5_REPRESENTATION_DRIVE_FILE_ID}; "
        f"runtime aliases: "
        f"{BLOCK_5_REPRESENTATION_ALIAS_VALUES}"
    )


# =============================================================================
# Reload persisted contextual-representation artefact
# =============================================================================

BLOCK_5_REPRESENTATION_BYTES = (
    block_5_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        BLOCK_5_REPRESENTATION_DRIVE_FILE_ID,
    )
)


if not BLOCK_5_REPRESENTATION_BYTES:

    raise RuntimeError(
        "Persisted contextual-representation artefact was empty."
    )


try:

    BLOCK_5_REPRESENTATION_ARTEFACT = json.loads(
        BLOCK_5_REPRESENTATION_BYTES.decode(
            "utf-8"
        )
    )


except (
    UnicodeDecodeError,
    json.JSONDecodeError,
) as error:

    raise RuntimeError(
        "Persisted contextual-representation artefact is not "
        "valid UTF-8 JSON."
    ) from error


BLOCK_5_REPRESENTATION_ARTEFACT_RELOADED = True


# =============================================================================
# Resolve representation records
# =============================================================================

def block_5_find_representation_records(
    artefact,
):

    if isinstance(
        artefact,
        list,
    ):

        return artefact


    if not isinstance(
        artefact,
        dict,
    ):

        raise TypeError(
            "Contextual-representation artefact has an unsupported type."
        )


    candidate_keys = (
        "records",
        "representations",
        "sentence_representations",
        "contextual_sentence_representations",
        "data",
    )


    for candidate_key in candidate_keys:

        candidate_value = artefact.get(
            candidate_key
        )


        if isinstance(
            candidate_value,
            list,
        ):

            return candidate_value


    raise KeyError(
        "Could not locate sentence-level contextual representations "
        "inside the persisted artefact."
    )


BLOCK_5_REPRESENTATION_RECORDS = (
    block_5_find_representation_records(
        BLOCK_5_REPRESENTATION_ARTEFACT
    )
)


BLOCK_5_REPRESENTATION_RECORD_COUNT = len(
    BLOCK_5_REPRESENTATION_RECORDS
)


BLOCK_5_REPRESENTATION_RECORD_COUNT_VALID = (
    BLOCK_5_REPRESENTATION_RECORD_COUNT
    ==
    NOTEBOOK_07_SENTENCE_COUNT
)


if not BLOCK_5_REPRESENTATION_RECORD_COUNT_VALID:

    raise RuntimeError(
        "Persisted contextual-representation record count does not "
        "match the canonical Notebook 07 sentence count. "
        f"Observed: {BLOCK_5_REPRESENTATION_RECORD_COUNT}; "
        f"expected: {NOTEBOOK_07_SENTENCE_COUNT}."
    )


# =============================================================================
# Representation-record helpers
# =============================================================================

def block_5_get_representation_sentence_id(
    record,
):

    if not isinstance(
        record,
        dict,
    ):

        raise TypeError(
            "Representation record must be a dictionary."
        )


    sentence_id = record.get(
        "sentence_id"
    )


    if sentence_id:

        return str(
            sentence_id
        )


    identity = record.get(
        "identity"
    )


    if isinstance(
        identity,
        dict,
    ):

        sentence_id = identity.get(
            "sentence_id"
        )


        if sentence_id:

            return str(
                sentence_id
            )


    raise KeyError(
        "Representation record has no sentence_id."
    )


def block_5_get_representation_vector(
    record,
):

    candidate_keys = (
        "textual_representation",
        "representation",
        "embedding",
        "sentence_embedding",
        "contextual_representation",
        "vector",
    )


    for candidate_key in candidate_keys:

        if candidate_key not in record:

            continue


        candidate_value = record[
            candidate_key
        ]


        if candidate_value is not None:

            return candidate_value


    raise KeyError(
        "Representation record has no recognised contextual vector."
    )


# =============================================================================
# Persisted representation identity
# =============================================================================

BLOCK_5_REPRESENTATION_SENTENCE_IDS = [
    block_5_get_representation_sentence_id(
        record
    )

    for record
    in BLOCK_5_REPRESENTATION_RECORDS
]


BLOCK_5_REPRESENTATION_SENTENCE_IDS_PRESENT = all(
    BLOCK_5_REPRESENTATION_SENTENCE_IDS
)


BLOCK_5_REPRESENTATION_SENTENCE_IDS_UNIQUE = (
    len(
        BLOCK_5_REPRESENTATION_SENTENCE_IDS
    )
    ==
    len(
        set(
            BLOCK_5_REPRESENTATION_SENTENCE_IDS
        )
    )
)


if not BLOCK_5_REPRESENTATION_SENTENCE_IDS_PRESENT:

    raise RuntimeError(
        "One or more persisted contextual representations lack "
        "canonical sentence identity."
    )


if not BLOCK_5_REPRESENTATION_SENTENCE_IDS_UNIQUE:

    raise RuntimeError(
        "Persisted contextual-representation sentence IDs are not unique."
    )


BLOCK_5_REPRESENTATION_BY_SENTENCE_ID = {
    block_5_get_representation_sentence_id(
        record
    ):
        record

    for record
    in BLOCK_5_REPRESENTATION_RECORDS
}


BLOCK_5_REPRESENTATION_SENTENCE_ALIGNMENT_VALID = (
    set(
        BLOCK_5_REPRESENTATION_BY_SENTENCE_ID.keys()
    )
    ==
    set(
        NOTEBOOK_07_SENTENCE_IDS
    )
)


if not BLOCK_5_REPRESENTATION_SENTENCE_ALIGNMENT_VALID:

    missing_sentence_ids = sorted(
        set(
            NOTEBOOK_07_SENTENCE_IDS
        )
        -
        set(
            BLOCK_5_REPRESENTATION_BY_SENTENCE_ID.keys()
        )
    )


    unexpected_sentence_ids = sorted(
        set(
            BLOCK_5_REPRESENTATION_BY_SENTENCE_ID.keys()
        )
        -
        set(
            NOTEBOOK_07_SENTENCE_IDS
        )
    )


    raise RuntimeError(
        "Persisted contextual representations do not align with "
        "the Notebook 07 canonical sentence identity contract. "
        f"Missing: {missing_sentence_ids}; "
        f"unexpected: {unexpected_sentence_ids}."
    )


# =============================================================================
# Restore canonical sentence order
# =============================================================================

BLOCK_5_ORDERED_REPRESENTATION_RECORDS = [
    BLOCK_5_REPRESENTATION_BY_SENTENCE_ID[
        sentence_id
    ]

    for sentence_id
    in NOTEBOOK_07_SENTENCE_IDS
]


# =============================================================================
# Construct canonical contextual tensor
# =============================================================================

try:

    BLOCK_5_CONTEXTUAL_ARRAY = np.asarray(
        [
            block_5_get_representation_vector(
                record
            )

            for record
            in BLOCK_5_ORDERED_REPRESENTATION_RECORDS
        ],
        dtype=np.float32,
    )


except (
    TypeError,
    ValueError,
) as error:

    raise RuntimeError(
        "Persisted contextual representation vectors could not be "
        "assembled into a numerical matrix."
    ) from error


BLOCK_5_CONTEXTUAL_REPRESENTATION = (
    torch.from_numpy(
        BLOCK_5_CONTEXTUAL_ARRAY
    )
    .to(
        dtype=
            torch.float32,

        device=
            BLOCK_5_DEVICE,
    )
)


BLOCK_5_CONTEXTUAL_SOURCE = (
    "persistent_handover_drive:"
    f"{BLOCK_5_REPRESENTATION_DRIVE_FILE_ID}"
)


# =============================================================================
# Contextual representation contract
# =============================================================================

BLOCK_5_CONTEXTUAL_SHAPE = tuple(
    BLOCK_5_CONTEXTUAL_REPRESENTATION.shape
)


BLOCK_5_CONTEXTUAL_SHAPE_VALID = (
    BLOCK_5_CONTEXTUAL_SHAPE
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM,
    )
)


BLOCK_5_CONTEXTUAL_VALUES_FINITE = bool(
    torch.isfinite(
        BLOCK_5_CONTEXTUAL_REPRESENTATION
    ).all().item()
)


BLOCK_5_SENTENCE_IDS_PRESENT = all(
    NOTEBOOK_07_SENTENCE_IDS
)


BLOCK_5_SENTENCE_IDS_UNIQUE = (
    len(
        NOTEBOOK_07_SENTENCE_IDS
    )
    ==
    len(
        set(
            NOTEBOOK_07_SENTENCE_IDS
        )
    )
)


BLOCK_5_SENTENCE_ALIGNMENT_VALID = all(
    [
        BLOCK_5_REPRESENTATION_SENTENCE_ALIGNMENT_VALID,

        (
            len(
                BLOCK_5_ORDERED_REPRESENTATION_RECORDS
            )
            ==
            NOTEBOOK_07_SENTENCE_COUNT
        ),
    ]
)


if not BLOCK_5_CONTEXTUAL_SHAPE_VALID:

    raise RuntimeError(
        "Persisted contextual representation tensor has an invalid "
        "shape. "
        f"Observed: {BLOCK_5_CONTEXTUAL_SHAPE}; "
        f"expected: "
        f"({NOTEBOOK_07_SENTENCE_COUNT}, "
        f"{NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM})."
    )


if not BLOCK_5_CONTEXTUAL_VALUES_FINITE:

    raise RuntimeError(
        "Persisted contextual representation contains non-finite values."
    )


if not BLOCK_5_SENTENCE_ALIGNMENT_VALID:

    raise RuntimeError(
        "Persisted contextual representation ordering does not satisfy "
        "the Notebook 07 canonical sentence contract."
    )


# =============================================================================
# Move modules to execution device
# =============================================================================

NOTEBOOK_07_BACKBONE_FROZEN_MODULE = (
    NOTEBOOK_07_BACKBONE_FROZEN_MODULE.to(
        BLOCK_5_DEVICE
    )
)


NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE = (
    NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.to(
        BLOCK_5_DEVICE
    )
)


NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE = (
    NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE.to(
        BLOCK_5_DEVICE
    )
)


NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE = (
    NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.to(
        BLOCK_5_DEVICE
    )
)


NOTEBOOK_07_SOCIAL_HEAD = (
    NOTEBOOK_07_SOCIAL_HEAD.to(
        BLOCK_5_DEVICE
    )
)


# =============================================================================
# Parameter-freezing policy
# =============================================================================

def block_5_set_trainability(
    module,
    trainable,
):

    for parameter in module.parameters():

        parameter.requires_grad = bool(
            trainable
        )


block_5_set_trainability(
    NOTEBOOK_07_BACKBONE_FROZEN_MODULE,
    False,
)


block_5_set_trainability(
    NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE,
    False,
)


block_5_set_trainability(
    NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE,
    False,
)


block_5_set_trainability(
    NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE,
    False,
)


block_5_set_trainability(
    NOTEBOOK_07_SOCIAL_HEAD,
    True,
)


# =============================================================================
# Evaluation mode for controlled no-update validation
# =============================================================================

NOTEBOOK_07_BACKBONE_FROZEN_MODULE.eval()

NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.eval()

NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE.eval()

NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.eval()

NOTEBOOK_07_SOCIAL_HEAD.eval()


# =============================================================================
# Trainability validation
# =============================================================================

BLOCK_5_BACKBONE_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_BACKBONE_FROZEN_MODULE.parameters()
)


BLOCK_5_GLOBAL_CONFLUENT_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.parameters()
)


BLOCK_5_FACTUAL_HEAD_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE.parameters()
)


BLOCK_5_PSYCHOLOGICAL_HEAD_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.parameters()
)


BLOCK_5_SOCIAL_HEAD_TRAINABLE = all(
    parameter.requires_grad
    for parameter
    in NOTEBOOK_07_SOCIAL_HEAD.parameters()
)


# =============================================================================
# Parameter counts
# =============================================================================

BLOCK_5_BACKBONE_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in NOTEBOOK_07_BACKBONE_FROZEN_MODULE.parameters()
)


BLOCK_5_GLOBAL_CONFLUENT_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.parameters()
)


BLOCK_5_FACTUAL_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE.parameters()
)


BLOCK_5_PSYCHOLOGICAL_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.parameters()
)


NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in NOTEBOOK_07_SOCIAL_HEAD.parameters()
    if parameter.requires_grad
)


def block_5_linear_parameter_count(
    input_dim,
    output_dim,
):

    return (
        input_dim * output_dim
        +
        output_dim
    )


def block_5_layer_norm_parameter_count(
    dimension,
):

    return 2 * dimension


def block_5_representation_head_parameter_count(
    output_dim,
):

    return (
        block_5_linear_parameter_count(
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,
        )
        +
        block_5_layer_norm_parameter_count(
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM
        )
        +
        block_5_linear_parameter_count(
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,
            output_dim,
        )
    )


BLOCK_5_EXPECTED_BACKBONE_PARAMETER_COUNT = (
    block_5_linear_parameter_count(
        NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM,
        NOTEBOOK_07_BACKBONE_INTERFACE_DIM,
    )
)


BLOCK_5_EXPECTED_GLOBAL_CONFLUENT_PARAMETER_COUNT = (
    block_5_linear_parameter_count(
        NOTEBOOK_07_BACKBONE_INTERFACE_DIM,
        NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,
    )
    +
    block_5_layer_norm_parameter_count(
        NOTEBOOK_07_GLOBAL_CONFLUENT_DIM
    )
)


BLOCK_5_EXPECTED_FACTUAL_PARAMETER_COUNT = (
    block_5_representation_head_parameter_count(
        NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM
    )
)


BLOCK_5_EXPECTED_PSYCHOLOGICAL_PARAMETER_COUNT = (
    block_5_representation_head_parameter_count(
        NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_DIM
    )
)


BLOCK_5_EXPECTED_SOCIAL_PARAMETER_COUNT = (
    block_5_representation_head_parameter_count(
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
    )
)


BLOCK_5_BACKBONE_PARAMETER_COUNT_VALID = (
    BLOCK_5_BACKBONE_PARAMETER_COUNT
    ==
    BLOCK_5_EXPECTED_BACKBONE_PARAMETER_COUNT
)


BLOCK_5_GLOBAL_CONFLUENT_PARAMETER_COUNT_VALID = (
    BLOCK_5_GLOBAL_CONFLUENT_PARAMETER_COUNT
    ==
    BLOCK_5_EXPECTED_GLOBAL_CONFLUENT_PARAMETER_COUNT
)


BLOCK_5_FACTUAL_PARAMETER_COUNT_VALID = (
    BLOCK_5_FACTUAL_PARAMETER_COUNT
    ==
    BLOCK_5_EXPECTED_FACTUAL_PARAMETER_COUNT
)


BLOCK_5_PSYCHOLOGICAL_PARAMETER_COUNT_VALID = (
    BLOCK_5_PSYCHOLOGICAL_PARAMETER_COUNT
    ==
    BLOCK_5_EXPECTED_PSYCHOLOGICAL_PARAMETER_COUNT
)


BLOCK_5_SOCIAL_PARAMETER_COUNT_VALID = (
    NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT
    ==
    BLOCK_5_EXPECTED_SOCIAL_PARAMETER_COUNT
)


BLOCK_5_PARAMETER_COUNTS_VALID = all(
    [
        BLOCK_5_BACKBONE_PARAMETER_COUNT_VALID,
        BLOCK_5_GLOBAL_CONFLUENT_PARAMETER_COUNT_VALID,
        BLOCK_5_FACTUAL_PARAMETER_COUNT_VALID,
        BLOCK_5_PSYCHOLOGICAL_PARAMETER_COUNT_VALID,
        BLOCK_5_SOCIAL_PARAMETER_COUNT_VALID,
    ]
)


BLOCK_5_PARAMETER_SCOPE_VALID = all(
    [
        BLOCK_5_BACKBONE_FROZEN,
        BLOCK_5_GLOBAL_CONFLUENT_FROZEN,
        BLOCK_5_FACTUAL_HEAD_FROZEN,
        BLOCK_5_PSYCHOLOGICAL_HEAD_FROZEN,
        BLOCK_5_SOCIAL_HEAD_TRAINABLE,
        BLOCK_5_PARAMETER_COUNTS_VALID,
    ]
)


if not BLOCK_5_PARAMETER_SCOPE_VALID:

    raise RuntimeError(
        "Notebook 07 Block 5 parameter-freezing or parameter-count "
        "contract is invalid."
    )


# =============================================================================
# Parameter snapshots
# =============================================================================

def block_5_snapshot_module(
    module,
):

    return {
        parameter_name:
            parameter
            .detach()
            .cpu()
            .clone()

        for (
            parameter_name,
            parameter,
        ) in module.named_parameters()
    }


def block_5_module_matches_snapshot(
    module,
    snapshot,
):

    current_parameters = dict(
        module.named_parameters()
    )


    if (
        set(
            current_parameters.keys()
        )
        !=
        set(
            snapshot.keys()
        )
    ):

        return False


    return all(
        torch.equal(
            current_parameters[
                parameter_name
            ]
            .detach()
            .cpu(),

            snapshot[
                parameter_name
            ],
        )

        for parameter_name
        in snapshot
    )


BLOCK_5_BACKBONE_BEFORE = (
    block_5_snapshot_module(
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE
    )
)


BLOCK_5_GLOBAL_CONFLUENT_BEFORE = (
    block_5_snapshot_module(
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE
    )
)


BLOCK_5_FACTUAL_BEFORE = (
    block_5_snapshot_module(
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE
    )
)


BLOCK_5_PSYCHOLOGICAL_BEFORE = (
    block_5_snapshot_module(
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE
    )
)


BLOCK_5_SOCIAL_BEFORE = (
    block_5_snapshot_module(
        NOTEBOOK_07_SOCIAL_HEAD
    )
)


# =============================================================================
# Controlled mandatory-global forward path
# =============================================================================

with torch.no_grad():

    BLOCK_5_BACKBONE_OUTPUT = (
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE(
            BLOCK_5_CONTEXTUAL_REPRESENTATION
        )
    )


    BLOCK_5_GLOBAL_CONFLUENT_OUTPUT = (
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE(
            BLOCK_5_BACKBONE_OUTPUT
        )
    )


    BLOCK_5_SOCIAL_OUTPUT = (
        NOTEBOOK_07_SOCIAL_HEAD(
            BLOCK_5_GLOBAL_CONFLUENT_OUTPUT
        )
    )


NOTEBOOK_07_SOCIAL_MODEL_FORWARD_EXECUTED = True


# =============================================================================
# Forward contract
# =============================================================================

BLOCK_5_BACKBONE_OUTPUT_SHAPE_VALID = (
    tuple(
        BLOCK_5_BACKBONE_OUTPUT.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_BACKBONE_INTERFACE_DIM,
    )
)


BLOCK_5_GLOBAL_CONFLUENT_OUTPUT_SHAPE_VALID = (
    tuple(
        BLOCK_5_GLOBAL_CONFLUENT_OUTPUT.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,
    )
)


BLOCK_5_SOCIAL_OUTPUT_SHAPE_VALID = (
    tuple(
        BLOCK_5_SOCIAL_OUTPUT.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_5_BACKBONE_OUTPUT_FINITE = bool(
    torch.isfinite(
        BLOCK_5_BACKBONE_OUTPUT
    ).all().item()
)


BLOCK_5_GLOBAL_CONFLUENT_OUTPUT_FINITE = bool(
    torch.isfinite(
        BLOCK_5_GLOBAL_CONFLUENT_OUTPUT
    ).all().item()
)


BLOCK_5_SOCIAL_OUTPUT_FINITE = bool(
    torch.isfinite(
        BLOCK_5_SOCIAL_OUTPUT
    ).all().item()
)


BLOCK_5_FORWARD_CONTRACT_VALID = all(
    [
        BLOCK_5_BACKBONE_OUTPUT_SHAPE_VALID,
        BLOCK_5_GLOBAL_CONFLUENT_OUTPUT_SHAPE_VALID,
        BLOCK_5_SOCIAL_OUTPUT_SHAPE_VALID,

        BLOCK_5_BACKBONE_OUTPUT_FINITE,
        BLOCK_5_GLOBAL_CONFLUENT_OUTPUT_FINITE,
        BLOCK_5_SOCIAL_OUTPUT_FINITE,
    ]
)


if not BLOCK_5_FORWARD_CONTRACT_VALID:

    raise RuntimeError(
        "Controlled mandatory-global Social Representation "
        "forward-path contract is invalid."
    )


# =============================================================================
# Active / deferred output mapping
# =============================================================================
#
# Block 5 consumes the activation contract resolved by Block 4.
# It must not redefine which dimensions are active for the current corpus.
# =============================================================================

BLOCK_5_ACTIVE_INDEX_TENSOR = torch.tensor(
    NOTEBOOK_07_SOCIAL_ACTIVE_INDICES,
    dtype=
        torch.long,
    device=
        BLOCK_5_DEVICE,
)


BLOCK_5_DEFERRED_INDEX_TENSOR = torch.tensor(
    NOTEBOOK_07_SOCIAL_DEFERRED_INDICES,
    dtype=
        torch.long,
    device=
        BLOCK_5_DEVICE,
)


BLOCK_5_SOCIAL_ACTIVE_OUTPUT = torch.index_select(
    BLOCK_5_SOCIAL_OUTPUT,
    dim=
        1,
    index=
        BLOCK_5_ACTIVE_INDEX_TENSOR,
)


BLOCK_5_SOCIAL_DEFERRED_OUTPUT = torch.index_select(
    BLOCK_5_SOCIAL_OUTPUT,
    dim=
        1,
    index=
        BLOCK_5_DEFERRED_INDEX_TENSOR,
)


BLOCK_5_ACTIVE_OUTPUT_SHAPE_VALID = (
    tuple(
        BLOCK_5_SOCIAL_ACTIVE_OUTPUT.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),
    )
)


BLOCK_5_DEFERRED_OUTPUT_SHAPE_VALID = (
    tuple(
        BLOCK_5_SOCIAL_DEFERRED_OUTPUT.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        len(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),
    )
)


BLOCK_5_ACTIVE_MAPPING_VALID = all(
    [
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        )
        ==
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

        all(
            0
            <=
            index
            <
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM

            for index
            in NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

        all(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER[
                index
            ]
            ==
            dimension_name

            for (
                dimension_name,
                index,
            ) in zip(
                NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS,
                NOTEBOOK_07_SOCIAL_ACTIVE_INDICES,
            )
        ),
    ]
)


BLOCK_5_DEFERRED_MAPPING_VALID = all(
    [
        len(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        )
        ==
        len(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),

        all(
            0
            <=
            index
            <
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM

            for index
            in NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),

        all(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER[
                index
            ]
            ==
            dimension_name

            for (
                dimension_name,
                index,
            ) in zip(
                NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS,
                NOTEBOOK_07_SOCIAL_DEFERRED_INDICES,
            )
        ),
    ]
)


BLOCK_5_ACTIVATION_PARTITION_DISJOINT = (
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
    ).isdisjoint(
        set(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        )
    )
)


BLOCK_5_ACTIVATION_PARTITION_COMPLETE = (
    sorted(
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        )
        +
        list(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        )
    )
    ==
    list(
        range(
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
        )
    )
)


BLOCK_5_ACTIVATION_DIMENSION_PARTITION_COMPLETE = (
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
    |
    set(
        NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
    )
    ==
    set(
        NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
    )
)


BLOCK_5_OUTPUT_MAPPING_VALID = all(
    [
        BLOCK_5_ACTIVE_OUTPUT_SHAPE_VALID,
        BLOCK_5_DEFERRED_OUTPUT_SHAPE_VALID,
        BLOCK_5_ACTIVE_MAPPING_VALID,
        BLOCK_5_DEFERRED_MAPPING_VALID,
        BLOCK_5_ACTIVATION_PARTITION_DISJOINT,
        BLOCK_5_ACTIVATION_PARTITION_COMPLETE,
        BLOCK_5_ACTIVATION_DIMENSION_PARTITION_COMPLETE,
    ]
)


if not BLOCK_5_OUTPUT_MAPPING_VALID:

    raise RuntimeError(
        "Social Representation active/deferred output mapping "
        "is invalid."
    )


# =============================================================================
# No-update validation
# =============================================================================

BLOCK_5_BACKBONE_UNCHANGED = (
    block_5_module_matches_snapshot(
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE,
        BLOCK_5_BACKBONE_BEFORE,
    )
)


BLOCK_5_GLOBAL_CONFLUENT_UNCHANGED = (
    block_5_module_matches_snapshot(
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE,
        BLOCK_5_GLOBAL_CONFLUENT_BEFORE,
    )
)


BLOCK_5_FACTUAL_UNCHANGED = (
    block_5_module_matches_snapshot(
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE,
        BLOCK_5_FACTUAL_BEFORE,
    )
)


BLOCK_5_PSYCHOLOGICAL_UNCHANGED = (
    block_5_module_matches_snapshot(
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE,
        BLOCK_5_PSYCHOLOGICAL_BEFORE,
    )
)


BLOCK_5_SOCIAL_UNCHANGED = (
    block_5_module_matches_snapshot(
        NOTEBOOK_07_SOCIAL_HEAD,
        BLOCK_5_SOCIAL_BEFORE,
    )
)


BLOCK_5_ALL_PARAMETERS_UNCHANGED = all(
    [
        BLOCK_5_BACKBONE_UNCHANGED,
        BLOCK_5_GLOBAL_CONFLUENT_UNCHANGED,
        BLOCK_5_FACTUAL_UNCHANGED,
        BLOCK_5_PSYCHOLOGICAL_UNCHANGED,
        BLOCK_5_SOCIAL_UNCHANGED,
    ]
)


BLOCK_5_SOCIAL_GRADIENTS_ABSENT = all(
    parameter.grad is None
    for parameter
    in NOTEBOOK_07_SOCIAL_HEAD.parameters()
)


BLOCK_5_FROZEN_GRADIENTS_ABSENT = all(
    parameter.grad is None

    for module in (
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE,
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE,
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE,
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE,
    )

    for parameter
    in module.parameters()
)


BLOCK_5_NO_UPDATE_VALID = all(
    [
        BLOCK_5_ALL_PARAMETERS_UNCHANGED,
        BLOCK_5_SOCIAL_GRADIENTS_ABSENT,
        BLOCK_5_FROZEN_GRADIENTS_ABSENT,
    ]
)


if not BLOCK_5_NO_UPDATE_VALID:

    raise RuntimeError(
        "Notebook 07 Block 5 no-update validation failed."
    )


# =============================================================================
# Group-conditioned path boundary
# =============================================================================

NOTEBOOK_07_GLOBAL_PATH_REQUIRED = True

NOTEBOOK_07_GLOBAL_PATH_OPERATIONAL = True

NOTEBOOK_07_GROUP_PATH_AVAILABLE = True

NOTEBOOK_07_GROUP_PATH_REQUIRED = False

NOTEBOOK_07_GROUP_PATH_EXECUTED = False

NOTEBOOK_07_GROUP_PATH_TRAINED = False

NOTEBOOK_07_GROUP_PATH_DEFERRED_TO_NOTEBOOK = 10


BLOCK_5_GROUP_PATH_POLICY_VALID = all(
    [
        NOTEBOOK_07_GLOBAL_PATH_REQUIRED,
        NOTEBOOK_07_GLOBAL_PATH_OPERATIONAL,
        NOTEBOOK_07_GROUP_PATH_AVAILABLE,

        not NOTEBOOK_07_GROUP_PATH_REQUIRED,
        not NOTEBOOK_07_GROUP_PATH_EXECUTED,
        not NOTEBOOK_07_GROUP_PATH_TRAINED,

        (
            NOTEBOOK_07_GROUP_PATH_DEFERRED_TO_NOTEBOOK
            ==
            10
        ),
    ]
)


# =============================================================================
# Model-policy state
# =============================================================================

NOTEBOOK_07_SOCIAL_MODEL_RESTORED = all(
    [
        BLOCK_5_CHECKPOINT_RELOADED,
        BLOCK_5_CHECKPOINT_TYPE_REPRODUCED,
        BLOCK_5_CHECKPOINT_STATE_CONTRACT_VALID,
        BLOCK_5_PERSISTED_TOPOLOGY_VALID,
        BLOCK_5_INHERITED_STATE_REPRODUCED,

        BLOCK_5_CONTEXTUAL_HANDOVER_CONTRACT_VALID,
        BLOCK_5_REPRESENTATION_ALIASES_CONSISTENT,
        BLOCK_5_REPRESENTATION_ARTEFACT_RELOADED,
        BLOCK_5_REPRESENTATION_RECORD_COUNT_VALID,
        BLOCK_5_REPRESENTATION_SENTENCE_ALIGNMENT_VALID,
    ]
)


NOTEBOOK_07_SOCIAL_ARCHITECTURE_VALID = all(
    [
        BLOCK_5_EXPLICIT_ARCHITECTURE_VALID,
        BLOCK_5_SOCIAL_ARCHITECTURE_VALID,

        BLOCK_5_SOCIAL_HEAD_INITIALISED,
        BLOCK_5_SOCIAL_HEAD_FRESH_INITIALISATION,

        not BLOCK_5_SOCIAL_HEAD_INHERITED_FACTUAL_WEIGHTS,
        not BLOCK_5_SOCIAL_HEAD_INHERITED_PSYCHOLOGICAL_WEIGHTS,

        BLOCK_5_FORWARD_CONTRACT_VALID,
        BLOCK_5_OUTPUT_MAPPING_VALID,
    ]
)


NOTEBOOK_07_SOCIAL_PARAMETER_POLICY_VALID = (
    BLOCK_5_PARAMETER_SCOPE_VALID
)


NOTEBOOK_07_SOCIAL_FORWARD_CONTRACT_VALID = (
    BLOCK_5_FORWARD_CONTRACT_VALID
)


NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY = all(
    [
        NOTEBOOK_07_SOCIAL_MODEL_RESTORED,
        NOTEBOOK_07_SOCIAL_ARCHITECTURE_VALID,
        NOTEBOOK_07_SOCIAL_PARAMETER_POLICY_VALID,
        NOTEBOOK_07_SOCIAL_FORWARD_CONTRACT_VALID,

        BLOCK_5_NO_UPDATE_VALID,
        BLOCK_5_GROUP_PATH_POLICY_VALID,
    ]
)


NOTEBOOK_07_SOCIAL_OPTIMISATION_READY = False


NOTEBOOK_07_READY_FOR_SOCIAL_OBJECTIVE_ASSEMBLY = (
    NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY
)


# =============================================================================
# Final validation
# =============================================================================

NOTEBOOK_07_BLOCK_5_ERRORS = []


block_5_validation_checks = {
    "checkpoint_not_reloaded":
        BLOCK_5_CHECKPOINT_RELOADED,

    "checkpoint_type_not_reproduced":
        BLOCK_5_CHECKPOINT_TYPE_REPRODUCED,

    "checkpoint_state_contract_invalid":
        BLOCK_5_CHECKPOINT_STATE_CONTRACT_VALID,

    "explicit_architecture_invalid":
        BLOCK_5_EXPLICIT_ARCHITECTURE_VALID,

    "persisted_topology_invalid":
        BLOCK_5_PERSISTED_TOPOLOGY_VALID,

    "backbone_state_not_reproduced":
        BLOCK_5_BACKBONE_STATE_REPRODUCED,

    "global_confluent_state_not_reproduced":
        BLOCK_5_GLOBAL_CONFLUENT_STATE_REPRODUCED,

    "psychological_state_not_reproduced":
        BLOCK_5_PSYCHOLOGICAL_STATE_REPRODUCED,

    "factual_state_not_reproduced":
        BLOCK_5_FACTUAL_STATE_REPRODUCED,

    "inherited_state_not_reproduced":
        BLOCK_5_INHERITED_STATE_REPRODUCED,

    "contextual_handover_contract_invalid":
        BLOCK_5_CONTEXTUAL_HANDOVER_CONTRACT_VALID,

    "representation_alias_conflict":
        BLOCK_5_REPRESENTATION_ALIASES_CONSISTENT,

    "representation_artefact_not_reloaded":
        BLOCK_5_REPRESENTATION_ARTEFACT_RELOADED,

    "representation_record_count_invalid":
        BLOCK_5_REPRESENTATION_RECORD_COUNT_VALID,

    "representation_sentence_ids_missing":
        BLOCK_5_REPRESENTATION_SENTENCE_IDS_PRESENT,

    "representation_sentence_ids_not_unique":
        BLOCK_5_REPRESENTATION_SENTENCE_IDS_UNIQUE,

    "representation_alignment_invalid":
        BLOCK_5_REPRESENTATION_SENTENCE_ALIGNMENT_VALID,

    "contextual_shape_invalid":
        BLOCK_5_CONTEXTUAL_SHAPE_VALID,

    "contextual_values_nonfinite":
        BLOCK_5_CONTEXTUAL_VALUES_FINITE,

    "sentence_ids_missing":
        BLOCK_5_SENTENCE_IDS_PRESENT,

    "sentence_ids_not_unique":
        BLOCK_5_SENTENCE_IDS_UNIQUE,

    "sentence_alignment_invalid":
        BLOCK_5_SENTENCE_ALIGNMENT_VALID,

    "social_architecture_invalid":
        BLOCK_5_SOCIAL_ARCHITECTURE_VALID,

    "active_mapping_invalid":
        BLOCK_5_ACTIVE_MAPPING_VALID,

    "deferred_mapping_invalid":
        BLOCK_5_DEFERRED_MAPPING_VALID,

    "activation_partition_incomplete":
        BLOCK_5_ACTIVATION_PARTITION_COMPLETE,

    "parameter_counts_invalid":
        BLOCK_5_PARAMETER_COUNTS_VALID,

    "parameter_scope_invalid":
        BLOCK_5_PARAMETER_SCOPE_VALID,

    "forward_contract_invalid":
        BLOCK_5_FORWARD_CONTRACT_VALID,

    "output_mapping_invalid":
        BLOCK_5_OUTPUT_MAPPING_VALID,

    "parameters_changed":
        BLOCK_5_ALL_PARAMETERS_UNCHANGED,

    "social_gradients_present":
        BLOCK_5_SOCIAL_GRADIENTS_ABSENT,

    "frozen_gradients_present":
        BLOCK_5_FROZEN_GRADIENTS_ABSENT,

    "no_update_validation_invalid":
        BLOCK_5_NO_UPDATE_VALID,

    "group_path_policy_invalid":
        BLOCK_5_GROUP_PATH_POLICY_VALID,

    "social_model_not_restored":
        NOTEBOOK_07_SOCIAL_MODEL_RESTORED,

    "social_architecture_policy_invalid":
        NOTEBOOK_07_SOCIAL_ARCHITECTURE_VALID,

    "social_parameter_policy_invalid":
        NOTEBOOK_07_SOCIAL_PARAMETER_POLICY_VALID,

    "social_forward_contract_invalid":
        NOTEBOOK_07_SOCIAL_FORWARD_CONTRACT_VALID,

    "social_model_policy_not_ready":
        NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY,

    "objective_assembly_not_ready":
        NOTEBOOK_07_READY_FOR_SOCIAL_OBJECTIVE_ASSEMBLY,
}


for (
    error_name,
    condition,
) in block_5_validation_checks.items():

    if not condition:

        NOTEBOOK_07_BLOCK_5_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited-operation validation
# =============================================================================

prohibited_block_5_operations = {
    "social_objectives_incorrectly_activated":
        NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED,

    "social_optimizer_incorrectly_created":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED,

    "social_loss_incorrectly_calculated":
        NOTEBOOK_07_SOCIAL_LOSS_CALCULATED,

    "social_zero_grad_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED,

    "social_backward_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED,

    "social_optimizer_step_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED,

    "social_parameter_update_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED,

    "social_training_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED,

    "psychological_training_incorrectly_executed":
        NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "factual_training_incorrectly_executed":
        NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED,

    "backbone_training_incorrectly_executed":
        NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED,

    "global_confluent_training_incorrectly_executed":
        NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED,

    "group_conditioned_incorrectly_executed":
        NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED,

    "transformative_weights_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED,

    "recurrent_incorrectly_executed":
        NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for (
    error_name,
    operation_executed,
) in prohibited_block_5_operations.items():

    if operation_executed:

        NOTEBOOK_07_BLOCK_5_ERRORS.append(
            error_name
        )


NOTEBOOK_07_BLOCK_5_VALID = (
    len(
        NOTEBOOK_07_BLOCK_5_ERRORS
    )
    == 0
)


if not NOTEBOOK_07_BLOCK_5_VALID:

    raise RuntimeError(
        "Notebook 07 Block 5 Social Representation model-policy "
        "validation failed. "
        f"Errors: {NOTEBOOK_07_BLOCK_5_ERRORS}"
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_07_BLOCK_5_COMPLETE = True


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_07_BLOCK_5_SUMMARY = {
    "block":
        NOTEBOOK_07_BLOCK_5,

    "block_name":
        NOTEBOOK_07_BLOCK_5_NAME,

    "version":
        NOTEBOOK_07_BLOCK_5_VERSION,

    "executed_at_utc":
        BLOCK_5_EXECUTED_AT_UTC,

    "checkpoint_reloaded":
        BLOCK_5_CHECKPOINT_RELOADED,

    "checkpoint_type_reproduced":
        BLOCK_5_CHECKPOINT_TYPE_REPRODUCED,

    "persisted_topology_valid":
        BLOCK_5_PERSISTED_TOPOLOGY_VALID,

    "inherited_state_reproduced":
        BLOCK_5_INHERITED_STATE_REPRODUCED,

    "representation_file_id":
        BLOCK_5_REPRESENTATION_DRIVE_FILE_ID,

    "representation_filename":
        BLOCK_5_REPRESENTATION_FILENAME,

    "representation_provider":
        BLOCK_5_REPRESENTATION_PROVIDER,

    "representation_model_id":
        BLOCK_5_REPRESENTATION_MODEL_ID,

    "representation_file_id_source":
        BLOCK_5_REPRESENTATION_FILE_ID_SOURCE,

    "contextual_handover_contract_valid":
        BLOCK_5_CONTEXTUAL_HANDOVER_CONTRACT_VALID,

    "representation_aliases_consistent":
        BLOCK_5_REPRESENTATION_ALIASES_CONSISTENT,

    "representation_artefact_reloaded":
        BLOCK_5_REPRESENTATION_ARTEFACT_RELOADED,

    "representation_record_count":
        BLOCK_5_REPRESENTATION_RECORD_COUNT,

    "representation_alignment_valid":
        BLOCK_5_REPRESENTATION_SENTENCE_ALIGNMENT_VALID,

    "textual_representation_dim":
        NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM,

    "backbone_interface_dim":
        NOTEBOOK_07_BACKBONE_INTERFACE_DIM,

    "global_confluent_dim":
        NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,

    "representation_hidden_dim":
        NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,

    "social_representation_dim":
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

    "backbone_parameters":
        BLOCK_5_BACKBONE_PARAMETER_COUNT,

    "global_confluent_parameters":
        BLOCK_5_GLOBAL_CONFLUENT_PARAMETER_COUNT,

    "psychological_parameters":
        BLOCK_5_PSYCHOLOGICAL_PARAMETER_COUNT,

    "factual_parameters":
        BLOCK_5_FACTUAL_PARAMETER_COUNT,

    "social_trainable_parameters":
        NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT,

    "active_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),

    "deferred_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        ),

    "activation_partition_disjoint":
        BLOCK_5_ACTIVATION_PARTITION_DISJOINT,

    "activation_partition_complete":
        BLOCK_5_ACTIVATION_PARTITION_COMPLETE,

    "output_mapping_valid":
        BLOCK_5_OUTPUT_MAPPING_VALID,

    "model_restored":
        NOTEBOOK_07_SOCIAL_MODEL_RESTORED,

    "architecture_valid":
        NOTEBOOK_07_SOCIAL_ARCHITECTURE_VALID,

    "parameter_policy_valid":
        NOTEBOOK_07_SOCIAL_PARAMETER_POLICY_VALID,

    "forward_contract_valid":
        NOTEBOOK_07_SOCIAL_FORWARD_CONTRACT_VALID,

    "no_update_valid":
        BLOCK_5_NO_UPDATE_VALID,

    "model_policy_ready":
        NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY,

    "optimisation_ready":
        NOTEBOOK_07_SOCIAL_OPTIMISATION_READY,

    "block_valid":
        NOTEBOOK_07_BLOCK_5_VALID,

    "block_complete":
        NOTEBOOK_07_BLOCK_5_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 07, Block 5: "
    "Social Representation Model Restoration, "
    "Parameter-Freezing Policy and Controlled Forward-Path Validation"
)

print("=" * 72)

print(
    f"Block version                : "
    f"{NOTEBOOK_07_BLOCK_5_VERSION}"
)


print("-" * 72)

print(
    "Deterministic inherited architecture"
)

print(
    "Backbone                     : "
    f"Linear({NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM} -> "
    f"{NOTEBOOK_07_BACKBONE_INTERFACE_DIM})"
)

print(
    "Global confluent             : "
    f"Linear({NOTEBOOK_07_BACKBONE_INTERFACE_DIM} -> "
    f"{NOTEBOOK_07_GLOBAL_CONFLUENT_DIM}) -> ReLU -> "
    f"Dropout({NOTEBOOK_07_GLOBAL_CONFLUENT_DROPOUT}) -> "
    f"LayerNorm({NOTEBOOK_07_GLOBAL_CONFLUENT_DIM})"
)

print(
    "Representation core          : "
    f"Linear({NOTEBOOK_07_GLOBAL_CONFLUENT_DIM} -> "
    f"{NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM}) -> ReLU -> "
    f"Dropout({NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT}) -> "
    f"LayerNorm({NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM})"
)

print(
    "Psychological output         : "
    f"Linear({NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM} -> "
    f"{NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_DIM})"
)

print(
    "Factual output               : "
    f"Linear({NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM} -> "
    f"{NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM})"
)

print(
    "Social output                : "
    f"Linear({NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM} -> "
    f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM})"
)

print(
    f"Explicit architecture valid  : "
    f"{BLOCK_5_EXPLICIT_ARCHITECTURE_VALID}"
)


print("-" * 72)

print(
    "Persisted inherited-state restoration"
)

print(
    f"Checkpoint reloaded          : "
    f"{BLOCK_5_CHECKPOINT_RELOADED}"
)

print(
    f"Checkpoint type              : "
    f"{NOTEBOOK_07_FACTUAL_CHECKPOINT_TYPE}"
)

print(
    f"Checkpoint type reproduced   : "
    f"{BLOCK_5_CHECKPOINT_TYPE_REPRODUCED}"
)

print(
    f"Persisted topology valid     : "
    f"{BLOCK_5_PERSISTED_TOPOLOGY_VALID}"
)

print(
    f"Backbone state reproduced    : "
    f"{BLOCK_5_BACKBONE_STATE_REPRODUCED}"
)

print(
    f"Global confluent reproduced  : "
    f"{BLOCK_5_GLOBAL_CONFLUENT_STATE_REPRODUCED}"
)

print(
    f"Psychological reproduced     : "
    f"{BLOCK_5_PSYCHOLOGICAL_STATE_REPRODUCED}"
)

print(
    f"Factual state reproduced     : "
    f"{BLOCK_5_FACTUAL_STATE_REPRODUCED}"
)

print(
    f"Inherited state reproduced   : "
    f"{BLOCK_5_INHERITED_STATE_REPRODUCED}"
)


print("-" * 72)

print(
    "Persisted contextual representation"
)

print(
    f"Representation filename      : "
    f"{BLOCK_5_REPRESENTATION_FILENAME}"
)

print(
    f"Representation file ID       : "
    f"{BLOCK_5_REPRESENTATION_DRIVE_FILE_ID}"
)

print(
    f"Representation ID source     : "
    f"{BLOCK_5_REPRESENTATION_FILE_ID_SOURCE}"
)

print(
    f"Representation provider      : "
    f"{BLOCK_5_REPRESENTATION_PROVIDER}"
)

print(
    f"Representation model         : "
    f"{BLOCK_5_REPRESENTATION_MODEL_ID}"
)

print(
    f"Handover contract valid      : "
    f"{BLOCK_5_CONTEXTUAL_HANDOVER_CONTRACT_VALID}"
)

print(
    f"Runtime aliases consistent   : "
    f"{BLOCK_5_REPRESENTATION_ALIASES_CONSISTENT}"
)

print(
    f"Artefact reloaded            : "
    f"{BLOCK_5_REPRESENTATION_ARTEFACT_RELOADED}"
)

print(
    f"Representation records       : "
    f"{BLOCK_5_REPRESENTATION_RECORD_COUNT}"
)

print(
    f"Persisted IDs present        : "
    f"{BLOCK_5_REPRESENTATION_SENTENCE_IDS_PRESENT}"
)

print(
    f"Persisted IDs unique         : "
    f"{BLOCK_5_REPRESENTATION_SENTENCE_IDS_UNIQUE}"
)

print(
    f"Persisted alignment valid    : "
    f"{BLOCK_5_REPRESENTATION_SENTENCE_ALIGNMENT_VALID}"
)

print(
    f"Contextual tensor shape      : "
    f"{BLOCK_5_CONTEXTUAL_SHAPE}"
)

print(
    f"Contextual shape valid       : "
    f"{BLOCK_5_CONTEXTUAL_SHAPE_VALID}"
)

print(
    f"Contextual values finite     : "
    f"{BLOCK_5_CONTEXTUAL_VALUES_FINITE}"
)


print("-" * 72)

print(
    "Social Representation initialisation"
)

print(
    f"Fresh initialisation         : "
    f"{BLOCK_5_SOCIAL_HEAD_FRESH_INITIALISATION}"
)

print(
    f"Factual weights inherited    : "
    f"{BLOCK_5_SOCIAL_HEAD_INHERITED_FACTUAL_WEIGHTS}"
)

print(
    f"Psych. weights inherited     : "
    f"{BLOCK_5_SOCIAL_HEAD_INHERITED_PSYCHOLOGICAL_WEIGHTS}"
)

print(
    f"Social architecture valid    : "
    f"{BLOCK_5_SOCIAL_ARCHITECTURE_VALID}"
)


print("-" * 72)

print(
    "Parameter-freezing policy"
)

print(
    f"Backbone frozen              : "
    f"{BLOCK_5_BACKBONE_FROZEN}"
)

print(
    f"Global confluent frozen      : "
    f"{BLOCK_5_GLOBAL_CONFLUENT_FROZEN}"
)

print(
    f"Psychological head frozen    : "
    f"{BLOCK_5_PSYCHOLOGICAL_HEAD_FROZEN}"
)

print(
    f"Factual head frozen          : "
    f"{BLOCK_5_FACTUAL_HEAD_FROZEN}"
)

print(
    f"Social head trainable        : "
    f"{BLOCK_5_SOCIAL_HEAD_TRAINABLE}"
)

print(
    f"Backbone parameters          : "
    f"{BLOCK_5_BACKBONE_PARAMETER_COUNT}"
)

print(
    f"Global confluent parameters  : "
    f"{BLOCK_5_GLOBAL_CONFLUENT_PARAMETER_COUNT}"
)

print(
    f"Psychological parameters     : "
    f"{BLOCK_5_PSYCHOLOGICAL_PARAMETER_COUNT}"
)

print(
    f"Factual parameters           : "
    f"{BLOCK_5_FACTUAL_PARAMETER_COUNT}"
)

print(
    f"Social trainable parameters  : "
    f"{NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT}"
)

print(
    f"Expected social parameters   : "
    f"{BLOCK_5_EXPECTED_SOCIAL_PARAMETER_COUNT}"
)

print(
    f"Parameter counts valid       : "
    f"{BLOCK_5_PARAMETER_COUNTS_VALID}"
)

print(
    f"Parameter scope valid        : "
    f"{BLOCK_5_PARAMETER_SCOPE_VALID}"
)


print("-" * 72)

print(
    "Controlled mandatory-global forward path"
)

print(
    f"Input shape                  : "
    f"{tuple(BLOCK_5_CONTEXTUAL_REPRESENTATION.shape)}"
)

print(
    f"Backbone output shape        : "
    f"{tuple(BLOCK_5_BACKBONE_OUTPUT.shape)}"
)

print(
    f"Backbone shape valid         : "
    f"{BLOCK_5_BACKBONE_OUTPUT_SHAPE_VALID}"
)

print(
    f"Global confluent shape       : "
    f"{tuple(BLOCK_5_GLOBAL_CONFLUENT_OUTPUT.shape)}"
)

print(
    f"Global confluent valid       : "
    f"{BLOCK_5_GLOBAL_CONFLUENT_OUTPUT_SHAPE_VALID}"
)

print(
    f"Social output shape          : "
    f"{tuple(BLOCK_5_SOCIAL_OUTPUT.shape)}"
)

print(
    f"Social output valid          : "
    f"{BLOCK_5_SOCIAL_OUTPUT_SHAPE_VALID}"
)

print(
    f"Backbone values finite       : "
    f"{BLOCK_5_BACKBONE_OUTPUT_FINITE}"
)

print(
    f"Global confluent finite      : "
    f"{BLOCK_5_GLOBAL_CONFLUENT_OUTPUT_FINITE}"
)

print(
    f"Social output finite         : "
    f"{BLOCK_5_SOCIAL_OUTPUT_FINITE}"
)


print("-" * 72)

print(
    "Social activation mapping"
)

print(
    f"Active dimensions            : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)}"
)

print(
    f"Active indices               : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_INDICES)}"
)

print(
    f"Deferred dimensions          : "
    f"{list(NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS)}"
)

print(
    f"Deferred indices             : "
    f"{list(NOTEBOOK_07_SOCIAL_DEFERRED_INDICES)}"
)

print(
    f"Active output shape          : "
    f"{tuple(BLOCK_5_SOCIAL_ACTIVE_OUTPUT.shape)}"
)

print(
    f"Deferred output shape        : "
    f"{tuple(BLOCK_5_SOCIAL_DEFERRED_OUTPUT.shape)}"
)

print(
    f"Active mapping valid         : "
    f"{BLOCK_5_ACTIVE_MAPPING_VALID}"
)

print(
    f"Deferred mapping valid       : "
    f"{BLOCK_5_DEFERRED_MAPPING_VALID}"
)

print(
    f"Activation partition complete: "
    f"{BLOCK_5_ACTIVATION_PARTITION_COMPLETE}"
)

print(
    f"Output mapping valid         : "
    f"{BLOCK_5_OUTPUT_MAPPING_VALID}"
)


print("-" * 72)

print(
    "No-update validation"
)

print(
    f"Backbone unchanged           : "
    f"{BLOCK_5_BACKBONE_UNCHANGED}"
)

print(
    f"Global confluent unchanged   : "
    f"{BLOCK_5_GLOBAL_CONFLUENT_UNCHANGED}"
)

print(
    f"Psychological head unchanged : "
    f"{BLOCK_5_PSYCHOLOGICAL_UNCHANGED}"
)

print(
    f"Factual head unchanged       : "
    f"{BLOCK_5_FACTUAL_UNCHANGED}"
)

print(
    f"Social head unchanged        : "
    f"{BLOCK_5_SOCIAL_UNCHANGED}"
)

print(
    f"Social gradients absent      : "
    f"{BLOCK_5_SOCIAL_GRADIENTS_ABSENT}"
)

print(
    f"Frozen gradients absent      : "
    f"{BLOCK_5_FROZEN_GRADIENTS_ABSENT}"
)

print(
    f"No-update validation valid   : "
    f"{BLOCK_5_NO_UPDATE_VALID}"
)


print("-" * 72)

print(
    "Group-conditioned path boundary"
)

print(
    f"Global path required         : "
    f"{NOTEBOOK_07_GLOBAL_PATH_REQUIRED}"
)

print(
    f"Global path operational      : "
    f"{NOTEBOOK_07_GLOBAL_PATH_OPERATIONAL}"
)

print(
    f"Group path available         : "
    f"{NOTEBOOK_07_GROUP_PATH_AVAILABLE}"
)

print(
    f"Group path required          : "
    f"{NOTEBOOK_07_GROUP_PATH_REQUIRED}"
)

print(
    f"Group path executed          : "
    f"{NOTEBOOK_07_GROUP_PATH_EXECUTED}"
)

print(
    f"Group path trained           : "
    f"{NOTEBOOK_07_GROUP_PATH_TRAINED}"
)

print(
    f"Group path deferred to N     : "
    f"{NOTEBOOK_07_GROUP_PATH_DEFERRED_TO_NOTEBOOK}"
)


print("-" * 72)

print(
    "Readiness"
)

print(
    f"Social model restored        : "
    f"{NOTEBOOK_07_SOCIAL_MODEL_RESTORED}"
)

print(
    f"Architecture valid           : "
    f"{NOTEBOOK_07_SOCIAL_ARCHITECTURE_VALID}"
)

print(
    f"Parameter policy valid       : "
    f"{NOTEBOOK_07_SOCIAL_PARAMETER_POLICY_VALID}"
)

print(
    f"Forward contract valid       : "
    f"{NOTEBOOK_07_SOCIAL_FORWARD_CONTRACT_VALID}"
)

print(
    f"Social model policy ready    : "
    f"{NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY}"
)

print(
    f"Optimisation ready           : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMISATION_READY}"
)

print(
    f"Ready for objective assembly : "
    f"{NOTEBOOK_07_READY_FOR_SOCIAL_OBJECTIVE_ASSEMBLY}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Controlled forward executed  : "
    f"{NOTEBOOK_07_SOCIAL_MODEL_FORWARD_EXECUTED}"
)

print(
    f"Objectives activated         : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_07_SOCIAL_LOSS_CALCULATED}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED}"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Social training executed     : "
    f"{NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Factual retraining           : "
    f"{NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative executed      : "
    f"{NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED}"
)

print(
    f"Transformative weights active: "
    f"{NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED}"
)

print(
    f"Recurrent executed           : "
    f"{NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED}"
)

print(
    f"Held-out evaluation executed : "
    f"{NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_07_BLOCK_5_VALID}"
)

print(
    f"Block 5 complete             : "
    f"{NOTEBOOK_07_BLOCK_5_COMPLETE}"
)


print("=" * 72)


print(
    "Notebook 07 Social Representation model restoration, "
    "parameter-freezing policy and controlled forward-path "
    "validation completed successfully."
)

print(
    "The inherited Media AI architecture was reconstructed "
    "deterministically rather than discovered from transient runtime modules."
)

print(
    "The persisted Notebook 06 factual checkpoint remained the "
    "authoritative source for inherited backbone, mandatory global "
    "confluent, Psychological Representation and Factual Representation "
    "parameter states."
)

print(
    "The canonical contextual sentence representation was restored from "
    "the contextual-representation artefact explicitly referenced by the "
    "inherited Notebook 05 -> Notebook 06 handover."
)

print(
    "The representation artefact identity, dimensionality, sentence count "
    "and sentence-alignment requirement were validated before use."
)

print(
    "The controlled forward path preserves the validated "
    f"{NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM}-dimensional contextual "
    f"representation, {NOTEBOOK_07_BACKBONE_INTERFACE_DIM}-dimensional "
    "backbone interface and "
    f"{NOTEBOOK_07_GLOBAL_CONFLUENT_DIM}-dimensional mandatory global "
    "confluent representation."
)

print(
    "The Social Representation uses the established shared "
    f"Linear {NOTEBOOK_07_GLOBAL_CONFLUENT_DIM} -> "
    f"{NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM} -> ReLU -> "
    f"Dropout({NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT}) -> "
    f"LayerNorm({NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM}) representation "
    "core with a fresh "
    f"Linear {NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM} -> "
    f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM} output."
)

print(
    "No trained factual or psychological parameter was transferred into "
    "the Social Representation head."
)

print(
    "All seven Social Representation dimensions remain structurally present."
)

print(
    f"{len(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)} Social Representation "
    "dimension(s) form the current active diagnostic output view; "
    f"{len(NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS)} dimension(s) remain "
    "structurally present and deferred under the Block 4 activation contract."
)

print(
    "The backbone, mandatory global confluent representation, "
    "Psychological Representation and Factual Representation remain frozen."
)

print(
    f"Only the {NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT:,} Social "
    "Representation parameters are marked trainable for subsequent "
    "controlled optimisation."
)

print(
    "The optional group-conditioned path remains architecturally available "
    "but unexecuted and deferred to Notebook 10."
)

print(
    "The Transformative Mechanism, Transformative Weights and recurrent "
    "mechanism remain inactive."
)

print(
    "A controlled mandatory-global forward pass was executed under "
    "torch.no_grad without modifying any model parameter."
)

print(
    "No supervised social loss, optimiser, zero-gradient operation, "
    "backward pass, optimiser step, parameter update or training "
    "was executed."
)

print(
    "Successful Block 5 completion establishes Social Representation "
    "model-policy readiness, not optimisation, generalisation or "
    "empirical validity."
)

print(
    "Block 6 may proceed to Social Representation Objective Assembly, "
    "Optimiser Policy and Controlled Loss Validation."
)

print("=" * 72)

========================================================================
Media AI — Notebook 07, Block 5: Social Representation Model Restoration, Parameter-Freezing Policy and Controlled Forward-Path Validation
========================================================================
Block version                : 1.6
------------------------------------------------------------------------
Deterministic inherited architecture
Backbone                     : Linear(768 -> 768)
Global confluent             : Linear(768 -> 256) -> ReLU -> Dropout(0.0) -> LayerNorm(256)
Representation core          : Linear(256 -> 128) -> ReLU -> Dropout(0.0) -> LayerNorm(128)
Psychological output         : Linear(128 -> 34)
Factual output               : Linear(128 -> 10)
Social output                : Linear(128 -> 7)
Explicit architecture valid  : True
------------------------------------------------------------------------
Persisted inherited-state restoration
Checkpoint reloaded          : True
Checkpoint type              : controlled_experimental_factual_training_checkpoint
Checkpoint type reproduced   : True
Persisted topology valid     : True
Backbone state reproduced    : True
Global confluent reproduced  : True
Psychological reproduced     : True
Factual state reproduced     : True
Inherited state reproduced   : True
------------------------------------------------------------------------
Persisted contextual representation
Representation filename      : notebook_05_contextual_sentence_representations.json
Representation file ID       : 11_j_CebqBpMSDLlccGwGROr5hklTBYRm
Representation ID source     : NOTEBOOK_07_HANDOVER.inherited_notebook_05_to_06_handover.contextual_representation.artifact_drive_file_id
Representation provider      : sentence-transformers
Representation model         : sentence-transformers/all-mpnet-base-v2
Handover contract valid      : True
Runtime aliases consistent   : True
Artefact reloaded            : True
Representation records       : 54
Persisted IDs present        : True
Persisted IDs unique         : True
Persisted alignment valid    : True
Contextual tensor shape      : (54, 768)
Contextual shape valid       : True
Contextual values finite     : True
------------------------------------------------------------------------
Social Representation initialisation
Fresh initialisation         : True
Factual weights inherited    : False
Psych. weights inherited     : False
Social architecture valid    : True
------------------------------------------------------------------------
Parameter-freezing policy
Backbone frozen              : True
Global confluent frozen      : True
Psychological head frozen    : True
Factual head frozen          : True
Social head trainable        : True
Backbone parameters          : 590592
Global confluent parameters  : 197376
Psychological parameters     : 37538
Factual parameters           : 34442
Social trainable parameters  : 34055
Expected social parameters   : 34055
Parameter counts valid       : True
Parameter scope valid        : True
------------------------------------------------------------------------
Controlled mandatory-global forward path
Input shape                  : (54, 768)
Backbone output shape        : (54, 768)
Backbone shape valid         : True
Global confluent shape       : (54, 256)
Global confluent valid       : True
Social output shape          : (54, 7)
Social output valid          : True
Backbone values finite       : True
Global confluent finite      : True
Social output finite         : True
------------------------------------------------------------------------
Social activation mapping
Active dimensions            : ['interpersonal_cohesion', 'economic_cohesion', 'political_cohesion', 'group_collective_cohesion']
Active indices               : [0, 1, 2, 4]
Deferred dimensions          : ['religious_cohesion', 'institutional_role_relation', 'public_audience_relation']
Deferred indices             : [3, 5, 6]
Active output shape          : (54, 4)
Deferred output shape        : (54, 3)
Active mapping valid         : True
Deferred mapping valid       : True
Activation partition complete: True
Output mapping valid         : True
------------------------------------------------------------------------
No-update validation
Backbone unchanged           : True
Global confluent unchanged   : True
Psychological head unchanged : True
Factual head unchanged       : True
Social head unchanged        : True
Social gradients absent      : True
Frozen gradients absent      : True
No-update validation valid   : True
------------------------------------------------------------------------
Group-conditioned path boundary
Global path required         : True
Global path operational      : True
Group path available         : True
Group path required          : False
Group path executed          : False
Group path trained           : False
Group path deferred to N     : 10
------------------------------------------------------------------------
Readiness
Social model restored        : True
Architecture valid           : True
Parameter policy valid       : True
Forward contract valid       : True
Social model policy ready    : True
Optimisation ready           : False
Ready for objective assembly : True
------------------------------------------------------------------------
Execution boundary
Controlled forward executed  : True
Objectives activated         : False
Loss calculated              : False
Optimiser created            : False
Zero grad executed           : False
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
Social training executed     : False
Psychological retraining     : False
Factual retraining           : False
Group-conditioned executed   : False
Transformative executed      : False
Transformative weights active: False
Recurrent executed           : False
Held-out evaluation executed : False
Empirical validity           : False
Block valid                  : True
Block 5 complete             : True
========================================================================
Notebook 07 Social Representation model restoration, parameter-freezing policy and controlled forward-path validation completed successfully.
The inherited Media AI architecture was reconstructed deterministically rather than discovered from transient runtime modules.
The persisted Notebook 06 factual checkpoint remained the authoritative source for inherited backbone, mandatory global confluent, Psychological Representation and Factual Representation parameter states.
The canonical contextual sentence representation was restored from the contextual-representation artefact explicitly referenced by the inherited Notebook 05 -> Notebook 06 handover.
The representation artefact identity, dimensionality, sentence count and sentence-alignment requirement were validated before use.
The controlled forward path preserves the validated 768-dimensional contextual representation, 768-dimensional backbone interface and 256-dimensional mandatory global confluent representation.
The Social Representation uses the established shared Linear 256 -> 128 -> ReLU -> Dropout(0.0) -> LayerNorm(128) representation core with a fresh Linear 128 -> 7 output.
No trained factual or psychological parameter was transferred into the Social Representation head.
All seven Social Representation dimensions remain structurally present.
4 Social Representation dimension(s) form the current active diagnostic output view; 3 dimension(s) remain structurally present and deferred under the Block 4 activation contract.
The backbone, mandatory global confluent representation, Psychological Representation and Factual Representation remain frozen.
Only the 34,055 Social Representation parameters are marked trainable for subsequent controlled optimisation.
The optional group-conditioned path remains architecturally available but unexecuted and deferred to Notebook 10.
The Transformative Mechanism, Transformative Weights and recurrent mechanism remain inactive.
A controlled mandatory-global forward pass was executed under torch.no_grad without modifying any model parameter.
No supervised social loss, optimiser, zero-gradient operation, backward pass, optimiser step, parameter update or training was executed.
Successful Block 5 completion establishes Social Representation model-policy readiness, not optimisation, generalisation or empirical validity.
Block 6 may proceed to Social Representation Objective Assembly, Optimiser Policy and Controlled Loss Validation.
========================================================================

In [ ]:
# =============================================================================
# Notebook 07 — Block 4 / 5 Runtime Readiness Check
# =============================================================================

required_runtime_objects = [
    "NOTEBOOK_07_BLOCK_4_COMPLETE",
    "NOTEBOOK_07_BLOCK_4_VALID",
    "NOTEBOOK_07_BLOCK_5_COMPLETE",
    "NOTEBOOK_07_BLOCK_5_VALID",
    "NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_ACTIVE_INDICES",
    "NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS",
    "BLOCK_4_SOCIAL_TARGET_MATRIX",
    "BLOCK_4_SOCIAL_MASK_MATRIX",
    "NOTEBOOK_07_SOCIAL_HEAD",
    "NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT",
    "NOTEBOOK_07_BACKBONE_FROZEN_MODULE",
    "NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE",
    "NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE",
    "NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE",
    "BLOCK_5_SOCIAL_OUTPUT",
    "BLOCK_5_SOCIAL_ACTIVE_OUTPUT",
    "BLOCK_5_NO_UPDATE_VALID",
    "NOTEBOOK_07_READY_FOR_SOCIAL_OBJECTIVE_ASSEMBLY",
]


missing_runtime_objects = [
    name
    for name in required_runtime_objects
    if name not in globals()
]


print("=" * 72)
print("Notebook 07 — Block 6 Runtime Readiness")
print("=" * 72)

print(
    f"Required objects             : "
    f"{len(required_runtime_objects)}"
)

print(
    f"Missing objects              : "
    f"{len(missing_runtime_objects)}"
)


if missing_runtime_objects:

    print()
    print("Missing:")

    for name in missing_runtime_objects:

        print(
            f"  - {name}"
        )

else:

    print(
        f"Block 4 complete             : "
        f"{NOTEBOOK_07_BLOCK_4_COMPLETE}"
    )

    print(
        f"Block 4 valid                : "
        f"{NOTEBOOK_07_BLOCK_4_VALID}"
    )

    print(
        f"Block 5 complete             : "
        f"{NOTEBOOK_07_BLOCK_5_COMPLETE}"
    )

    print(
        f"Block 5 valid                : "
        f"{NOTEBOOK_07_BLOCK_5_VALID}"
    )

    print(
        f"Ready for objective assembly : "
        f"{NOTEBOOK_07_READY_FOR_SOCIAL_OBJECTIVE_ASSEMBLY}"
    )

print("=" * 72)

In [ ]:
# =============================================================================
# Notebook 07 — Representation Handover Diagnostic
# =============================================================================

import json


print("=" * 88)

print(
    "Notebook 07 — Contextual Representation Handover Diagnostic"
)

print("=" * 88)


# =============================================================================
# Runtime aliases
# =============================================================================

runtime_candidates = (
    "NOTEBOOK_06_REPRESENTATION_DRIVE_FILE_ID",
    "NOTEBOOK_07_REPRESENTATION_DRIVE_FILE_ID",
    "NOTEBOOK_07_CONTEXTUAL_REPRESENTATION_DRIVE_FILE_ID",
)


for candidate_name in runtime_candidates:

    print(
        f"{candidate_name:<52}: "
        f"{globals().get(candidate_name, '<NOT PRESENT>')}"
    )


print("-" * 88)


# =============================================================================
# Notebook 07 handover structure
# =============================================================================

if (
    "NOTEBOOK_07_HANDOVER"
    in globals()
    and
    isinstance(
        NOTEBOOK_07_HANDOVER,
        dict,
    )
):

    print(
        "NOTEBOOK_07_HANDOVER present : True"
    )

    print()

    print(
        json.dumps(
            NOTEBOOK_07_HANDOVER,
            indent=2,
            ensure_ascii=False,
        )
    )


else:

    print(
        "NOTEBOOK_07_HANDOVER present : False"
    )


print("=" * 88)

## Block 6 — Social Representation Objective Assembly, Optimiser Policy and Controlled Loss Validation

This block converts the validated Social Representation supervision and model-policy contracts into an explicit optimisation-ready objective while preserving the controlled experimental boundary established by the preceding blocks.

The block restores the accepted sentence-level Social Representation target and mask matrices and verifies their alignment with the canonical sentence identity used by the model. The seven-dimensional Social Representation remains structurally intact, while only the dimensions activated by the Block 4 availability and variability policy participate in the current objective.

The active Social Representation dimensions are:

- **S1 — interpersonal cohesion**
- **S3 — political cohesion**
- **S5 — group/collective cohesion**

The remaining dimensions stay structurally present but are excluded from the current optimisation objective:

- **S2 — economic cohesion**, deferred because the current sample contains insufficient explicit supervision;
- **S4 — religious cohesion**, deferred because no explicit supervision is currently available;
- **S6 — institutional-role relation**, deferred because the observed targets currently have zero variance;
- **S7 — public/audience relation**, deferred because the observed targets currently have zero variance.

For each active signed-cohesion dimension, the block constructs the previously specified **mask-aware mean-squared-error objective**. Missing supervision must remain excluded from the loss and must never be interpreted as numerical zero or as a negative target. The active dimension losses are combined using the equal objective weights established in Block 4.

The Social Representation head restored and validated in Block 5 is the only component eligible for optimisation. The inherited backbone, mandatory global confluent representation, Psychological Representation and Factual Representation remain frozen. The optional group-conditioned path remains inactive and deferred to Notebook 10.

An optimiser may be instantiated over the trainable Social Representation parameters only. Its parameter scope, optimisation hyperparameters and correspondence with the declared trainability policy must be audited explicitly before any later training operation is permitted.

A controlled forward pass may be executed to calculate the initial supervised Social Representation objective and its component losses. This calculation is diagnostic: it validates target alignment, masking, output selection, objective weighting and numerical stability.

This block must **not** execute `zero_grad`, a backward pass, an optimiser step or any parameter update. All model parameters must remain unchanged after controlled loss calculation.

Successful completion of Block 6 therefore establishes that the Social Representation has a valid and reproducible optimisation objective and optimiser policy. It does **not** constitute Social Representation training, held-out evaluation, generalisation validation or empirical validation.

The Transformative Mechanism, Transformative Weights and recurrent mechanism remain outside the scope of this block.

After successful completion, Block 7 may proceed to **Controlled Social Representation Training and Checkpoint Construction**.

In [20]:
# =============================================================================
# Media AI — Notebook 07
# Block 6: Social Representation Objective Assembly,
#          Optimiser Policy and Controlled Loss Validation
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import math

import numpy as np
import torch
import torch.nn as nn


# =============================================================================
# Dependency checks
# =============================================================================

required_block_6_objects = [
    # -------------------------------------------------------------------------
    # Block completion
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_BLOCK_1_COMPLETE",
    "NOTEBOOK_07_BLOCK_1_VALID",
    "NOTEBOOK_07_BLOCK_2_COMPLETE",
    "NOTEBOOK_07_BLOCK_2_VALID",
    "NOTEBOOK_07_BLOCK_3_COMPLETE",
    "NOTEBOOK_07_BLOCK_3_VALID",
    "NOTEBOOK_07_BLOCK_4_COMPLETE",
    "NOTEBOOK_07_BLOCK_4_VALID",
    "NOTEBOOK_07_BLOCK_5_COMPLETE",
    "NOTEBOOK_07_BLOCK_5_VALID",

    # -------------------------------------------------------------------------
    # Canonical identity
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_SENTENCE_IDS",
    "NOTEBOOK_07_SENTENCE_COUNT",

    # -------------------------------------------------------------------------
    # Social semantic contract
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_SOCIAL_DIMENSION_IDS",
    "NOTEBOOK_07_SOCIAL_DIMENSION_ORDER",

    # -------------------------------------------------------------------------
    # Block 4 objective policy
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_ACTIVE_INDICES",
    "NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_DEFERRED_INDICES",
    "NOTEBOOK_07_SOCIAL_ACTIVE_SIGNED_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_ACTIVE_BINARY_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS",
    "NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES",
    "NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID",
    "BLOCK_4_SOCIAL_TARGET_MATRIX",
    "BLOCK_4_SOCIAL_MASK_MATRIX",
    "BLOCK_4_DIMENSION_AVAILABLE_COUNTS",

    # -------------------------------------------------------------------------
    # Block 5 model policy
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_SOCIAL_HEAD",
    "NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT",
    "NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY",
    "NOTEBOOK_07_READY_FOR_SOCIAL_OBJECTIVE_ASSEMBLY",
    "NOTEBOOK_07_BACKBONE_FROZEN_MODULE",
    "NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE",
    "NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE",
    "NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE",
    "BLOCK_5_SOCIAL_OUTPUT",
    "BLOCK_5_SOCIAL_ACTIVE_OUTPUT",
    "BLOCK_5_ALL_PARAMETERS_UNCHANGED",
    "BLOCK_5_NO_UPDATE_VALID",
]


missing_block_6_objects = [
    object_name
    for object_name
    in required_block_6_objects
    if object_name not in globals()
]


if missing_block_6_objects:

    raise NameError(
        "Notebook 07 Block 6 prerequisites are not initialised. "
        f"Missing: {missing_block_6_objects}"
    )


if not all(
    [
        NOTEBOOK_07_BLOCK_1_COMPLETE,
        NOTEBOOK_07_BLOCK_1_VALID,
        NOTEBOOK_07_BLOCK_2_COMPLETE,
        NOTEBOOK_07_BLOCK_2_VALID,
        NOTEBOOK_07_BLOCK_3_COMPLETE,
        NOTEBOOK_07_BLOCK_3_VALID,
        NOTEBOOK_07_BLOCK_4_COMPLETE,
        NOTEBOOK_07_BLOCK_4_VALID,
        NOTEBOOK_07_BLOCK_5_COMPLETE,
        NOTEBOOK_07_BLOCK_5_VALID,
        NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID,
        NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY,
        NOTEBOOK_07_READY_FOR_SOCIAL_OBJECTIVE_ASSEMBLY,
        BLOCK_5_ALL_PARAMETERS_UNCHANGED,
        BLOCK_5_NO_UPDATE_VALID,
    ]
):

    raise RuntimeError(
        "Notebook 07 Blocks 1–5 must be complete and valid "
        "before Block 6."
    )


if NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM != 7:

    raise RuntimeError(
        "Block 6 requires the validated seven-dimensional "
        "Social Representation."
    )


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_07_BLOCK_6 = 6

NOTEBOOK_07_BLOCK_6_NAME = (
    "Social Representation Objective Assembly, "
    "Optimiser Policy and Controlled Loss Validation"
)

NOTEBOOK_07_BLOCK_6_VERSION = "1.1"

NOTEBOOK_07_SOCIAL_OBJECTIVE_EXECUTION_VERSION = "1.1"


BLOCK_6_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Optimiser policy
# =============================================================================

NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE = "AdamW"

NOTEBOOK_07_SOCIAL_LEARNING_RATE = 0.001

NOTEBOOK_07_SOCIAL_WEIGHT_DECAY = 0.0001


# =============================================================================
# Numerical validation tolerance
# =============================================================================

BLOCK_6_NUMERICAL_ATOL = 1e-7

BLOCK_6_NUMERICAL_RTOL = 1e-6


# =============================================================================
# Execution boundary
# =============================================================================

NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED = False

NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED = False

NOTEBOOK_07_SOCIAL_LOSS_CALCULATED = False

NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED = False

NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED = False

NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED = False

NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED = False

NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Canonical active / deferred objective contract
# =============================================================================
#
# Block 6 consumes the activation contract resolved by Block 4.
# It does not redefine which dimensions are active for the current corpus.
# =============================================================================

BLOCK_6_ACTIVE_DIMENSIONS_VALID = all(
    [
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        )
        ==
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

        all(
            0 <= index < NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
            for index
            in NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

        all(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER[index]
            ==
            dimension_name

            for (
                dimension_name,
                index,
            ) in zip(
                NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS,
                NOTEBOOK_07_SOCIAL_ACTIVE_INDICES,
            )
        ),
    ]
)


BLOCK_6_DEFERRED_DIMENSIONS_VALID = all(
    [
        len(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        )
        ==
        len(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),

        all(
            0 <= index < NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
            for index
            in NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),

        all(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER[index]
            ==
            dimension_name

            for (
                dimension_name,
                index,
            ) in zip(
                NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS,
                NOTEBOOK_07_SOCIAL_DEFERRED_INDICES,
            )
        ),
    ]
)


BLOCK_6_ACTIVE_DEFERRED_DISJOINT = (
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
    ).isdisjoint(
        set(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        )
    )
)


BLOCK_6_ACTIVE_DEFERRED_COMPLETE = (
    sorted(
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        )
        +
        list(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        )
    )
    ==
    list(
        range(
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
        )
    )
)


BLOCK_6_ACTIVE_SIGNED_DIMENSIONS_VALID = (
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_SIGNED_DIMENSIONS
    ).issubset(
        set(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        )
    )
)


BLOCK_6_ACTIVE_BINARY_DIMENSIONS_VALID = (
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_BINARY_DIMENSIONS
    ).issubset(
        set(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        )
    )
)


BLOCK_6_ACTIVE_FAMILY_PARTITION_VALID = all(
    [
        set(
            NOTEBOOK_07_SOCIAL_ACTIVE_SIGNED_DIMENSIONS
        ).isdisjoint(
            set(
                NOTEBOOK_07_SOCIAL_ACTIVE_BINARY_DIMENSIONS
            )
        ),

        (
            set(
                NOTEBOOK_07_SOCIAL_ACTIVE_SIGNED_DIMENSIONS
            )
            |
            set(
                NOTEBOOK_07_SOCIAL_ACTIVE_BINARY_DIMENSIONS
            )
        )
        ==
        set(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),
    ]
)


BLOCK_6_OBJECTIVE_SELECTION_VALID = all(
    [
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        )
        >
        0,

        BLOCK_6_ACTIVE_DIMENSIONS_VALID,
        BLOCK_6_DEFERRED_DIMENSIONS_VALID,
        BLOCK_6_ACTIVE_DEFERRED_DISJOINT,
        BLOCK_6_ACTIVE_DEFERRED_COMPLETE,
        BLOCK_6_ACTIVE_SIGNED_DIMENSIONS_VALID,
        BLOCK_6_ACTIVE_BINARY_DIMENSIONS_VALID,
        BLOCK_6_ACTIVE_FAMILY_PARTITION_VALID,
    ]
)


if not BLOCK_6_OBJECTIVE_SELECTION_VALID:

    raise RuntimeError(
        "Notebook 07 Block 6 active/deferred objective selection "
        "is inconsistent with the validated Block 4 policy."
    )


# =============================================================================
# Loss-family contract
# =============================================================================

BLOCK_6_EXPECTED_ACTIVE_LOSS_FAMILIES = {
    dimension_name:
        (
            "masked_mean_squared_error"
            if dimension_name
            in NOTEBOOK_07_SOCIAL_ACTIVE_SIGNED_DIMENSIONS
            else
            "binary_cross_entropy_with_logits"
        )

    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
}


BLOCK_6_ACTIVE_LOSS_FAMILIES_VALID = (
    dict(
        NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES
    )
    ==
    BLOCK_6_EXPECTED_ACTIVE_LOSS_FAMILIES
)


if not BLOCK_6_ACTIVE_LOSS_FAMILIES_VALID:

    raise RuntimeError(
        "Notebook 07 Block 6 active loss-family contract does not "
        "reproduce the validated Block 4 policy."
    )


# =============================================================================
# Objective-family weighting contract
# =============================================================================

BLOCK_6_OBJECTIVE_WEIGHTS = {
    dimension_name:
        float(
            NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS[
                dimension_name
            ]
        )

    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
}


BLOCK_6_OBJECTIVE_WEIGHT_KEYS_VALID = (
    set(
        BLOCK_6_OBJECTIVE_WEIGHTS.keys()
    )
    ==
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


BLOCK_6_OBJECTIVE_WEIGHT_SUM = float(
    sum(
        BLOCK_6_OBJECTIVE_WEIGHTS.values()
    )
)


BLOCK_6_OBJECTIVE_WEIGHTS_FINITE = all(
    math.isfinite(
        objective_weight
    )

    for objective_weight
    in BLOCK_6_OBJECTIVE_WEIGHTS.values()
)


BLOCK_6_OBJECTIVE_WEIGHTS_POSITIVE = all(
    objective_weight > 0.0

    for objective_weight
    in BLOCK_6_OBJECTIVE_WEIGHTS.values()
)


BLOCK_6_OBJECTIVE_WEIGHT_SUM_VALID = bool(
    np.isclose(
        BLOCK_6_OBJECTIVE_WEIGHT_SUM,
        1.0,
        rtol=0.0,
        atol=1e-12,
    )
)


BLOCK_6_EQUAL_WEIGHT_POLICY_VALID = all(
    np.isclose(
        BLOCK_6_OBJECTIVE_WEIGHTS[
            dimension_name
        ],
        (
            1.0
            /
            len(
                NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
            )
        ),
        rtol=0.0,
        atol=1e-12,
    )

    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
)


BLOCK_6_OBJECTIVE_WEIGHT_CONTRACT_VALID = all(
    [
        BLOCK_6_OBJECTIVE_WEIGHT_KEYS_VALID,
        BLOCK_6_OBJECTIVE_WEIGHTS_FINITE,
        BLOCK_6_OBJECTIVE_WEIGHTS_POSITIVE,
        BLOCK_6_OBJECTIVE_WEIGHT_SUM_VALID,
        BLOCK_6_EQUAL_WEIGHT_POLICY_VALID,
    ]
)


if not BLOCK_6_OBJECTIVE_WEIGHT_CONTRACT_VALID:

    raise RuntimeError(
        "Notebook 07 Block 6 Social Representation objective-family "
        "weighting contract is invalid."
    )


# =============================================================================
# Restore canonical target and mask tensors from validated Block 4 matrices
# =============================================================================
#
# Block 6 does not reconstruct or reinterpret social supervision.
#
# It consumes the already validated canonical target and mask matrices
# constructed and audited by Block 4.
# =============================================================================

BLOCK_6_SOCIAL_TARGET_MATRIX = np.asarray(
    BLOCK_4_SOCIAL_TARGET_MATRIX,
    dtype=np.float64,
)


BLOCK_6_SOCIAL_MASK_MATRIX = np.asarray(
    BLOCK_4_SOCIAL_MASK_MATRIX,
    dtype=bool,
)


BLOCK_6_TARGET_MATRIX_SHAPE_VALID = (
    BLOCK_6_SOCIAL_TARGET_MATRIX.shape
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_6_MASK_MATRIX_SHAPE_VALID = (
    BLOCK_6_SOCIAL_MASK_MATRIX.shape
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_6_OBSERVED_TARGET_VALUES_FINITE = bool(
    np.isfinite(
        BLOCK_6_SOCIAL_TARGET_MATRIX[
            BLOCK_6_SOCIAL_MASK_MATRIX
        ]
    ).all()
)


if not all(
    [
        BLOCK_6_TARGET_MATRIX_SHAPE_VALID,
        BLOCK_6_MASK_MATRIX_SHAPE_VALID,
        BLOCK_6_OBSERVED_TARGET_VALUES_FINITE,
    ]
):

    raise RuntimeError(
        "Notebook 07 Block 6 target/mask matrix contract is invalid."
    )


# =============================================================================
# Block 5 output contract
# =============================================================================

BLOCK_6_SOCIAL_OUTPUT = (
    BLOCK_5_SOCIAL_OUTPUT
    .detach()
)


BLOCK_6_SOCIAL_OUTPUT_SHAPE_VALID = (
    tuple(
        BLOCK_6_SOCIAL_OUTPUT.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_6_SOCIAL_OUTPUT_FINITE = bool(
    torch.isfinite(
        BLOCK_6_SOCIAL_OUTPUT
    ).all().item()
)


BLOCK_6_SOCIAL_OUTPUT_REQUIRES_GRAD = bool(
    BLOCK_6_SOCIAL_OUTPUT.requires_grad
)


BLOCK_6_BLOCK_5_OUTPUT_IS_DIAGNOSTIC = (
    not BLOCK_6_SOCIAL_OUTPUT_REQUIRES_GRAD
)


if not all(
    [
        BLOCK_6_SOCIAL_OUTPUT_SHAPE_VALID,
        BLOCK_6_SOCIAL_OUTPUT_FINITE,
        BLOCK_6_BLOCK_5_OUTPUT_IS_DIAGNOSTIC,
    ]
):

    raise RuntimeError(
        "Notebook 07 Block 6 could not consume the validated "
        "Block 5 Social Representation output safely."
    )


# =============================================================================
# Device-aligned target and mask tensors
# =============================================================================

BLOCK_6_DEVICE = (
    BLOCK_6_SOCIAL_OUTPUT.device
)


BLOCK_6_SOCIAL_TARGET_TENSOR = torch.tensor(
    BLOCK_6_SOCIAL_TARGET_MATRIX,
    dtype=
        BLOCK_6_SOCIAL_OUTPUT.dtype,
    device=
        BLOCK_6_DEVICE,
)


BLOCK_6_SOCIAL_MASK_TENSOR = torch.tensor(
    BLOCK_6_SOCIAL_MASK_MATRIX,
    dtype=torch.bool,
    device=
        BLOCK_6_DEVICE,
)


# =============================================================================
# Active supervision availability
# =============================================================================

BLOCK_6_ACTIVE_AVAILABLE_COUNTS = {}


for (
    dimension_name,
    dimension_index,
) in zip(
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS,
    NOTEBOOK_07_SOCIAL_ACTIVE_INDICES,
):

    available_count = int(
        BLOCK_6_SOCIAL_MASK_TENSOR[
            :,
            dimension_index,
        ].sum().item()
    )


    BLOCK_6_ACTIVE_AVAILABLE_COUNTS[
        dimension_name
    ] = available_count


BLOCK_6_ALL_ACTIVE_OBJECTIVES_OBSERVED = all(
    available_count > 0
    for available_count
    in BLOCK_6_ACTIVE_AVAILABLE_COUNTS.values()
)


BLOCK_6_ACTIVE_COVERAGE_REPRODUCED = all(
    (
        BLOCK_6_ACTIVE_AVAILABLE_COUNTS[
            dimension_name
        ]
        ==
        int(
            BLOCK_4_DIMENSION_AVAILABLE_COUNTS[
                dimension_name
            ]
        )
    )

    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
)


if not BLOCK_6_ALL_ACTIVE_OBJECTIVES_OBSERVED:

    raise RuntimeError(
        "At least one active Social Representation objective has "
        "no available supervision."
    )


if not BLOCK_6_ACTIVE_COVERAGE_REPRODUCED:

    raise RuntimeError(
        "Block 6 could not reproduce Block 4 supervision availability "
        "for the active Social Representation dimensions."
    )


# =============================================================================
# Mask-aware loss helpers
# =============================================================================

def block_6_masked_mean_squared_error(
    prediction,
    target,
    mask,
):
    """
    Calculate mean squared error over explicitly observed targets only.
    """

    if not (
        prediction.ndim
        ==
        target.ndim
        ==
        mask.ndim
        ==
        1
    ):

        raise ValueError(
            "Masked MSE prediction, target and mask must be one-dimensional."
        )


    if not (
        prediction.shape
        ==
        target.shape
        ==
        mask.shape
    ):

        raise ValueError(
            "Masked MSE prediction, target and mask shapes "
            "must be identical."
        )


    if int(
        mask.sum().item()
    ) <= 0:

        raise RuntimeError(
            "Masked MSE cannot be calculated without observed targets."
        )


    loss = torch.mean(
        (
            prediction[
                mask
            ]
            -
            target[
                mask
            ]
        )
        ** 2
    )


    if loss.ndim != 0 or not bool(
        torch.isfinite(
            loss
        ).item()
    ):

        raise RuntimeError(
            "Masked MSE did not produce a finite scalar loss."
        )


    return loss


def block_6_masked_binary_cross_entropy_with_logits(
    prediction,
    target,
    mask,
):
    """
    Calculate BCE-with-logits over explicitly observed binary targets only.
    """

    if not (
        prediction.ndim
        ==
        target.ndim
        ==
        mask.ndim
        ==
        1
    ):

        raise ValueError(
            "Masked BCE prediction, target and mask must be one-dimensional."
        )


    if not (
        prediction.shape
        ==
        target.shape
        ==
        mask.shape
    ):

        raise ValueError(
            "Masked BCE prediction, target and mask shapes "
            "must be identical."
        )


    observed_count = int(
        mask.sum().item()
    )


    if observed_count <= 0:

        raise RuntimeError(
            "Masked BCE cannot be calculated without observed targets."
        )


    observed_target = target[
        mask
    ]


    if not bool(
        torch.isin(
            observed_target,
            torch.tensor(
                [
                    0.0,
                    1.0,
                ],
                dtype=
                    observed_target.dtype,
                device=
                    observed_target.device,
            ),
        ).all().item()
    ):

        raise RuntimeError(
            "Masked BCE received non-binary observed targets."
        )


    loss = torch.nn.functional.binary_cross_entropy_with_logits(
        prediction[
            mask
        ],
        observed_target,
        reduction=
            "mean",
    )


    if loss.ndim != 0 or not bool(
        torch.isfinite(
            loss
        ).item()
    ):

        raise RuntimeError(
            "Masked BCE did not produce a finite scalar loss."
        )


    return loss


# =============================================================================
# Controlled active-family loss calculation
# =============================================================================

BLOCK_6_SOCIAL_FAMILY_LOSSES = {}

BLOCK_6_SOCIAL_FAMILY_LOSS_VALUES = {}


for (
    dimension_name,
    dimension_index,
) in zip(
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS,
    NOTEBOOK_07_SOCIAL_ACTIVE_INDICES,
):

    prediction = (
        BLOCK_6_SOCIAL_OUTPUT[
            :,
            dimension_index,
        ]
    )


    target = (
        BLOCK_6_SOCIAL_TARGET_TENSOR[
            :,
            dimension_index,
        ]
    )


    mask = (
        BLOCK_6_SOCIAL_MASK_TENSOR[
            :,
            dimension_index,
        ]
    )


    loss_family = (
        NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES[
            dimension_name
        ]
    )


    if loss_family == "masked_mean_squared_error":

        family_loss = (
            block_6_masked_mean_squared_error(
                prediction=
                    prediction,
                target=
                    target,
                mask=
                    mask,
            )
        )


    elif loss_family == "binary_cross_entropy_with_logits":

        family_loss = (
            block_6_masked_binary_cross_entropy_with_logits(
                prediction=
                    prediction,
                target=
                    target,
                mask=
                    mask,
            )
        )


    else:

        raise RuntimeError(
            f"Unsupported active Social Representation loss family "
            f"for {dimension_name}: {loss_family}"
        )


    BLOCK_6_SOCIAL_FAMILY_LOSSES[
        dimension_name
    ] = family_loss


    BLOCK_6_SOCIAL_FAMILY_LOSS_VALUES[
        dimension_name
    ] = float(
        family_loss
        .detach()
        .cpu()
        .item()
    )


NOTEBOOK_07_SOCIAL_LOSS_CALCULATED = True


# =============================================================================
# Controlled total Social Representation objective
# =============================================================================

BLOCK_6_TOTAL_SOCIAL_OBJECTIVE = sum(
    (
        BLOCK_6_SOCIAL_FAMILY_LOSSES[
            dimension_name
        ]
        *
        BLOCK_6_OBJECTIVE_WEIGHTS[
            dimension_name
        ]
    )

    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
)


BLOCK_6_TOTAL_SOCIAL_OBJECTIVE_VALUE = float(
    BLOCK_6_TOTAL_SOCIAL_OBJECTIVE
    .detach()
    .cpu()
    .item()
)


BLOCK_6_TOTAL_OBJECTIVE_SCALAR = (
    BLOCK_6_TOTAL_SOCIAL_OBJECTIVE.ndim
    == 0
)


BLOCK_6_TOTAL_OBJECTIVE_FINITE = bool(
    torch.isfinite(
        BLOCK_6_TOTAL_SOCIAL_OBJECTIVE
    ).item()
)


if not all(
    [
        BLOCK_6_TOTAL_OBJECTIVE_SCALAR,
        BLOCK_6_TOTAL_OBJECTIVE_FINITE,
    ]
):

    raise RuntimeError(
        "Controlled Social Representation objective is invalid."
    )


NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED = True


# =============================================================================
# Independent NumPy reproduction of family losses
# =============================================================================

BLOCK_6_REPRODUCED_FAMILY_LOSS_VALUES = {}


def block_6_numpy_bce_with_logits(
    logits,
    targets,
):
    """
    Numerically stable mean BCE-with-logits reproduction.
    """

    logits = np.asarray(
        logits,
        dtype=np.float64,
    )

    targets = np.asarray(
        targets,
        dtype=np.float64,
    )

    return float(
        np.mean(
            np.maximum(
                logits,
                0.0,
            )
            -
            logits * targets
            +
            np.log1p(
                np.exp(
                    -np.abs(
                        logits
                    )
                )
            )
        )
    )


for (
    dimension_name,
    dimension_index,
) in zip(
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS,
    NOTEBOOK_07_SOCIAL_ACTIVE_INDICES,
):

    dimension_mask = (
        BLOCK_6_SOCIAL_MASK_MATRIX[
            :,
            dimension_index,
        ]
    )


    observed_prediction = (
        BLOCK_6_SOCIAL_OUTPUT[
            :,
            dimension_index,
        ]
        .detach()
        .cpu()
        .numpy()[
            dimension_mask
        ]
        .astype(
            np.float64
        )
    )


    observed_target = (
        BLOCK_6_SOCIAL_TARGET_MATRIX[
            dimension_mask,
            dimension_index,
        ]
        .astype(
            np.float64
        )
    )


    loss_family = (
        NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES[
            dimension_name
        ]
    )


    if loss_family == "masked_mean_squared_error":

        reproduced_loss = float(
            np.mean(
                (
                    observed_prediction
                    -
                    observed_target
                )
                ** 2
            )
        )


    elif loss_family == "binary_cross_entropy_with_logits":

        reproduced_loss = (
            block_6_numpy_bce_with_logits(
                logits=
                    observed_prediction,
                targets=
                    observed_target,
            )
        )


    else:

        raise RuntimeError(
            f"Unsupported reproduction loss family "
            f"for {dimension_name}: {loss_family}"
        )


    BLOCK_6_REPRODUCED_FAMILY_LOSS_VALUES[
        dimension_name
    ] = reproduced_loss


BLOCK_6_FAMILY_LOSSES_REPRODUCED = all(
    np.isclose(
        BLOCK_6_SOCIAL_FAMILY_LOSS_VALUES[
            dimension_name
        ],
        BLOCK_6_REPRODUCED_FAMILY_LOSS_VALUES[
            dimension_name
        ],
        rtol=
            BLOCK_6_NUMERICAL_RTOL,
        atol=
            BLOCK_6_NUMERICAL_ATOL,
    )

    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
)


if not BLOCK_6_FAMILY_LOSSES_REPRODUCED:

    raise RuntimeError(
        "One or more Social Representation family losses could not "
        "be reproduced independently."
    )


# =============================================================================
# Independent total-objective reproduction
# =============================================================================

BLOCK_6_REPRODUCED_TOTAL_OBJECTIVE_VALUE = float(
    sum(
        (
            BLOCK_6_REPRODUCED_FAMILY_LOSS_VALUES[
                dimension_name
            ]
            *
            BLOCK_6_OBJECTIVE_WEIGHTS[
                dimension_name
            ]
        )

        for dimension_name
        in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


BLOCK_6_TOTAL_OBJECTIVE_REPRODUCED = bool(
    np.isclose(
        BLOCK_6_TOTAL_SOCIAL_OBJECTIVE_VALUE,
        BLOCK_6_REPRODUCED_TOTAL_OBJECTIVE_VALUE,
        rtol=
            BLOCK_6_NUMERICAL_RTOL,
        atol=
            BLOCK_6_NUMERICAL_ATOL,
    )
)


if not BLOCK_6_TOTAL_OBJECTIVE_REPRODUCED:

    raise RuntimeError(
        "Controlled Social Representation total objective could not "
        "be reproduced independently."
    )


# =============================================================================
# Deferred-dimension exclusion audit
# =============================================================================

BLOCK_6_OBJECTIVE_DIMENSION_SET = set(
    BLOCK_6_SOCIAL_FAMILY_LOSSES.keys()
)


BLOCK_6_EXPECTED_OBJECTIVE_DIMENSION_SET = set(
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
)


BLOCK_6_DEFERRED_DIMENSION_SET = set(
    NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
)


BLOCK_6_DEFERRED_DIMENSIONS_EXCLUDED = all(
    [
        (
            BLOCK_6_OBJECTIVE_DIMENSION_SET
            ==
            BLOCK_6_EXPECTED_OBJECTIVE_DIMENSION_SET
        ),

        (
            BLOCK_6_OBJECTIVE_DIMENSION_SET
            .isdisjoint(
                BLOCK_6_DEFERRED_DIMENSION_SET
            )
        ),
    ]
)


if not BLOCK_6_DEFERRED_DIMENSIONS_EXCLUDED:

    raise RuntimeError(
        "One or more deferred Social Representation dimensions "
        "entered the controlled objective."
    )


# =============================================================================
# Parameter snapshots before optimiser creation
# =============================================================================

def block_6_snapshot_module(
    module,
):

    return {
        parameter_name:
            parameter
            .detach()
            .cpu()
            .clone()

        for (
            parameter_name,
            parameter,
        ) in module.named_parameters()
    }


def block_6_module_matches_snapshot(
    module,
    snapshot,
):

    current_parameters = dict(
        module.named_parameters()
    )


    if (
        set(
            current_parameters.keys()
        )
        !=
        set(
            snapshot.keys()
        )
    ):

        return False


    return all(
        torch.equal(
            current_parameters[
                parameter_name
            ]
            .detach()
            .cpu(),

            snapshot[
                parameter_name
            ],
        )

        for parameter_name
        in snapshot
    )


BLOCK_6_BACKBONE_BEFORE = (
    block_6_snapshot_module(
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE
    )
)


BLOCK_6_GLOBAL_CONFLUENT_BEFORE = (
    block_6_snapshot_module(
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE
    )
)


BLOCK_6_PSYCHOLOGICAL_BEFORE = (
    block_6_snapshot_module(
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE
    )
)


BLOCK_6_FACTUAL_BEFORE = (
    block_6_snapshot_module(
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE
    )
)


BLOCK_6_SOCIAL_BEFORE = (
    block_6_snapshot_module(
        NOTEBOOK_07_SOCIAL_HEAD
    )
)


# =============================================================================
# Revalidate parameter-freezing policy
# =============================================================================

BLOCK_6_BACKBONE_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_BACKBONE_FROZEN_MODULE.parameters()
)


BLOCK_6_GLOBAL_CONFLUENT_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.parameters()
)


BLOCK_6_PSYCHOLOGICAL_HEAD_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.parameters()
)


BLOCK_6_FACTUAL_HEAD_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE.parameters()
)


BLOCK_6_SOCIAL_HEAD_TRAINABLE = all(
    parameter.requires_grad
    for parameter
    in NOTEBOOK_07_SOCIAL_HEAD.parameters()
)


BLOCK_6_SOCIAL_TRAINABLE_PARAMETERS = [
    parameter
    for parameter
    in NOTEBOOK_07_SOCIAL_HEAD.parameters()
    if parameter.requires_grad
]


BLOCK_6_SOCIAL_TRAINABLE_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in BLOCK_6_SOCIAL_TRAINABLE_PARAMETERS
)


BLOCK_6_EXPECTED_SOCIAL_PARAMETER_COUNT = int(
    NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT
)


BLOCK_6_SOCIAL_PARAMETER_COUNT_VALID = (
    BLOCK_6_SOCIAL_TRAINABLE_PARAMETER_COUNT
    ==
    BLOCK_6_EXPECTED_SOCIAL_PARAMETER_COUNT
)


BLOCK_6_PARAMETER_FREEZING_POLICY_VALID = all(
    [
        BLOCK_6_BACKBONE_FROZEN,
        BLOCK_6_GLOBAL_CONFLUENT_FROZEN,
        BLOCK_6_PSYCHOLOGICAL_HEAD_FROZEN,
        BLOCK_6_FACTUAL_HEAD_FROZEN,
        BLOCK_6_SOCIAL_HEAD_TRAINABLE,
        BLOCK_6_SOCIAL_PARAMETER_COUNT_VALID,
    ]
)


if not BLOCK_6_PARAMETER_FREEZING_POLICY_VALID:

    raise RuntimeError(
        "Notebook 07 Block 6 parameter-freezing policy does not "
        "reproduce the validated Block 5 contract."
    )


# =============================================================================
# Optimiser creation
# =============================================================================

NOTEBOOK_07_SOCIAL_OPTIMIZER = torch.optim.AdamW(
    BLOCK_6_SOCIAL_TRAINABLE_PARAMETERS,
    lr=
        NOTEBOOK_07_SOCIAL_LEARNING_RATE,
    weight_decay=
        NOTEBOOK_07_SOCIAL_WEIGHT_DECAY,
)


NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED = True


# =============================================================================
# Optimiser type / hyperparameter audit
# =============================================================================

BLOCK_6_OPTIMIZER_TYPE_VALID = (
    isinstance(
        NOTEBOOK_07_SOCIAL_OPTIMIZER,
        torch.optim.AdamW,
    )
)


BLOCK_6_OPTIMIZER_GROUP_COUNT_VALID = (
    len(
        NOTEBOOK_07_SOCIAL_OPTIMIZER.param_groups
    )
    == 1
)


BLOCK_6_OPTIMIZER_LEARNING_RATE_VALID = bool(
    np.isclose(
        float(
            NOTEBOOK_07_SOCIAL_OPTIMIZER.param_groups[
                0
            ][
                "lr"
            ]
        ),
        NOTEBOOK_07_SOCIAL_LEARNING_RATE,
        rtol=0.0,
        atol=0.0,
    )
)


BLOCK_6_OPTIMIZER_WEIGHT_DECAY_VALID = bool(
    np.isclose(
        float(
            NOTEBOOK_07_SOCIAL_OPTIMIZER.param_groups[
                0
            ][
                "weight_decay"
            ]
        ),
        NOTEBOOK_07_SOCIAL_WEIGHT_DECAY,
        rtol=0.0,
        atol=0.0,
    )
)


# =============================================================================
# Exact optimiser parameter-scope validation
# =============================================================================

BLOCK_6_SOCIAL_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter
    in BLOCK_6_SOCIAL_TRAINABLE_PARAMETERS
}


BLOCK_6_OPTIMIZER_PARAMETER_LIST = [
    parameter

    for parameter_group
    in NOTEBOOK_07_SOCIAL_OPTIMIZER.param_groups

    for parameter
    in parameter_group[
        "params"
    ]
]


BLOCK_6_OPTIMIZER_PARAMETER_IDS = {
    id(
        parameter
    )

    for parameter
    in BLOCK_6_OPTIMIZER_PARAMETER_LIST
}


BLOCK_6_OPTIMIZER_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in BLOCK_6_OPTIMIZER_PARAMETER_LIST
)


BLOCK_6_OPTIMIZER_SCOPE_EXACT = (
    BLOCK_6_OPTIMIZER_PARAMETER_IDS
    ==
    BLOCK_6_SOCIAL_PARAMETER_IDS
)


BLOCK_6_OPTIMIZER_PARAMETER_COUNT_VALID = (
    BLOCK_6_OPTIMIZER_PARAMETER_COUNT
    ==
    BLOCK_6_SOCIAL_TRAINABLE_PARAMETER_COUNT
)


BLOCK_6_OPTIMIZER_STATE_EMPTY = (
    len(
        NOTEBOOK_07_SOCIAL_OPTIMIZER.state
    )
    == 0
)


BLOCK_6_OPTIMIZER_SCOPE_VALID = all(
    [
        BLOCK_6_OPTIMIZER_TYPE_VALID,
        BLOCK_6_OPTIMIZER_GROUP_COUNT_VALID,
        BLOCK_6_OPTIMIZER_LEARNING_RATE_VALID,
        BLOCK_6_OPTIMIZER_WEIGHT_DECAY_VALID,
        BLOCK_6_OPTIMIZER_SCOPE_EXACT,
        BLOCK_6_OPTIMIZER_PARAMETER_COUNT_VALID,
        BLOCK_6_OPTIMIZER_STATE_EMPTY,
    ]
)


if not BLOCK_6_OPTIMIZER_SCOPE_VALID:

    raise RuntimeError(
        "Notebook 07 Social Representation optimiser scope "
        "or hyperparameter contract is invalid."
    )


# =============================================================================
# No-update validation after optimiser creation
# =============================================================================

BLOCK_6_BACKBONE_UNCHANGED = (
    block_6_module_matches_snapshot(
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE,
        BLOCK_6_BACKBONE_BEFORE,
    )
)


BLOCK_6_GLOBAL_CONFLUENT_UNCHANGED = (
    block_6_module_matches_snapshot(
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE,
        BLOCK_6_GLOBAL_CONFLUENT_BEFORE,
    )
)


BLOCK_6_PSYCHOLOGICAL_UNCHANGED = (
    block_6_module_matches_snapshot(
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE,
        BLOCK_6_PSYCHOLOGICAL_BEFORE,
    )
)


BLOCK_6_FACTUAL_UNCHANGED = (
    block_6_module_matches_snapshot(
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE,
        BLOCK_6_FACTUAL_BEFORE,
    )
)


BLOCK_6_SOCIAL_UNCHANGED = (
    block_6_module_matches_snapshot(
        NOTEBOOK_07_SOCIAL_HEAD,
        BLOCK_6_SOCIAL_BEFORE,
    )
)


BLOCK_6_FROZEN_PARAMETERS_UNCHANGED = all(
    [
        BLOCK_6_BACKBONE_UNCHANGED,
        BLOCK_6_GLOBAL_CONFLUENT_UNCHANGED,
        BLOCK_6_PSYCHOLOGICAL_UNCHANGED,
        BLOCK_6_FACTUAL_UNCHANGED,
    ]
)


BLOCK_6_ALL_PARAMETERS_UNCHANGED = all(
    [
        BLOCK_6_FROZEN_PARAMETERS_UNCHANGED,
        BLOCK_6_SOCIAL_UNCHANGED,
    ]
)


# =============================================================================
# Gradient-state validation
# =============================================================================

BLOCK_6_SOCIAL_GRADIENTS_ABSENT = all(
    parameter.grad is None
    for parameter
    in NOTEBOOK_07_SOCIAL_HEAD.parameters()
)


BLOCK_6_FROZEN_GRADIENTS_ABSENT = all(
    parameter.grad is None

    for module
    in (
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE,
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE,
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE,
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE,
    )

    for parameter
    in module.parameters()
)


BLOCK_6_NO_UPDATE_VALID = all(
    [
        BLOCK_6_ALL_PARAMETERS_UNCHANGED,
        BLOCK_6_SOCIAL_GRADIENTS_ABSENT,
        BLOCK_6_FROZEN_GRADIENTS_ABSENT,
        BLOCK_6_OPTIMIZER_STATE_EMPTY,
        not NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED,
        not NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED,
        not NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED,
        not NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED,
    ]
)


if not BLOCK_6_NO_UPDATE_VALID:

    raise RuntimeError(
        "Notebook 07 Block 6 no-update validation failed."
    )


# =============================================================================
# Controlled-loss contract
# =============================================================================

NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_VALIDATED = all(
    [
        BLOCK_6_OBJECTIVE_SELECTION_VALID,
        BLOCK_6_ACTIVE_LOSS_FAMILIES_VALID,
        BLOCK_6_OBJECTIVE_WEIGHT_CONTRACT_VALID,
        BLOCK_6_ALL_ACTIVE_OBJECTIVES_OBSERVED,
        BLOCK_6_ACTIVE_COVERAGE_REPRODUCED,
        BLOCK_6_FAMILY_LOSSES_REPRODUCED,
        BLOCK_6_TOTAL_OBJECTIVE_REPRODUCED,
        BLOCK_6_DEFERRED_DIMENSIONS_EXCLUDED,
        BLOCK_6_TOTAL_OBJECTIVE_SCALAR,
        BLOCK_6_TOTAL_OBJECTIVE_FINITE,
    ]
)


NOTEBOOK_07_SOCIAL_OPTIMIZER_POLICY_VALID = (
    BLOCK_6_OPTIMIZER_SCOPE_VALID
)


NOTEBOOK_07_SOCIAL_CONTROLLED_LOSS_VALID = (
    NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_VALIDATED
)


NOTEBOOK_07_SOCIAL_OBJECTIVE_ASSEMBLED = True


NOTEBOOK_07_SOCIAL_OPTIMISATION_READY = all(
    [
        NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID,
        NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY,
        NOTEBOOK_07_SOCIAL_OBJECTIVE_ASSEMBLED,
        NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_VALIDATED,
        NOTEBOOK_07_SOCIAL_OPTIMIZER_POLICY_VALID,
        NOTEBOOK_07_SOCIAL_CONTROLLED_LOSS_VALID,
        BLOCK_6_PARAMETER_FREEZING_POLICY_VALID,
        BLOCK_6_NO_UPDATE_VALID,
    ]
)


NOTEBOOK_07_READY_FOR_CONTROLLED_SOCIAL_TRAINING = (
    NOTEBOOK_07_SOCIAL_OPTIMISATION_READY
)


# =============================================================================
# Final validation
# =============================================================================

NOTEBOOK_07_BLOCK_6_ERRORS = []


block_6_validation_checks = {
    "active_objective_selection_invalid":
        BLOCK_6_OBJECTIVE_SELECTION_VALID,

    "active_loss_family_contract_invalid":
        BLOCK_6_ACTIVE_LOSS_FAMILIES_VALID,

    "objective_weight_contract_invalid":
        BLOCK_6_OBJECTIVE_WEIGHT_CONTRACT_VALID,

    "target_matrix_shape_invalid":
        BLOCK_6_TARGET_MATRIX_SHAPE_VALID,

    "mask_matrix_shape_invalid":
        BLOCK_6_MASK_MATRIX_SHAPE_VALID,

    "observed_target_values_nonfinite":
        BLOCK_6_OBSERVED_TARGET_VALUES_FINITE,

    "social_output_shape_invalid":
        BLOCK_6_SOCIAL_OUTPUT_SHAPE_VALID,

    "social_output_nonfinite":
        BLOCK_6_SOCIAL_OUTPUT_FINITE,

    "block_5_output_not_diagnostic":
        BLOCK_6_BLOCK_5_OUTPUT_IS_DIAGNOSTIC,

    "active_objective_without_supervision":
        BLOCK_6_ALL_ACTIVE_OBJECTIVES_OBSERVED,

    "active_coverage_not_reproduced":
        BLOCK_6_ACTIVE_COVERAGE_REPRODUCED,

    "family_losses_not_reproduced":
        BLOCK_6_FAMILY_LOSSES_REPRODUCED,

    "total_objective_not_reproduced":
        BLOCK_6_TOTAL_OBJECTIVE_REPRODUCED,

    "deferred_dimensions_not_excluded":
        BLOCK_6_DEFERRED_DIMENSIONS_EXCLUDED,

    "total_objective_not_scalar":
        BLOCK_6_TOTAL_OBJECTIVE_SCALAR,

    "total_objective_nonfinite":
        BLOCK_6_TOTAL_OBJECTIVE_FINITE,

    "parameter_freezing_policy_invalid":
        BLOCK_6_PARAMETER_FREEZING_POLICY_VALID,

    "optimizer_scope_invalid":
        BLOCK_6_OPTIMIZER_SCOPE_VALID,

    "no_update_validation_invalid":
        BLOCK_6_NO_UPDATE_VALID,

    "loss_contract_invalid":
        NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_VALIDATED,

    "optimizer_policy_invalid":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_POLICY_VALID,

    "controlled_loss_invalid":
        NOTEBOOK_07_SOCIAL_CONTROLLED_LOSS_VALID,

    "social_optimisation_not_ready":
        NOTEBOOK_07_SOCIAL_OPTIMISATION_READY,

    "controlled_training_not_ready":
        NOTEBOOK_07_READY_FOR_CONTROLLED_SOCIAL_TRAINING,
}


for (
    error_name,
    condition,
) in block_6_validation_checks.items():

    if not condition:

        NOTEBOOK_07_BLOCK_6_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited-operation validation
# =============================================================================

prohibited_block_6_operations = {
    "zero_grad_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED,

    "backward_pass_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED,

    "optimizer_step_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED,

    "parameter_update_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED,

    "social_training_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED,

    "psychological_training_incorrectly_executed":
        NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "factual_training_incorrectly_executed":
        NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED,

    "backbone_training_incorrectly_executed":
        NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED,

    "global_confluent_training_incorrectly_executed":
        NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED,

    "group_conditioned_path_incorrectly_executed":
        NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_mechanism_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED,

    "transformative_weights_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED,

    "recurrent_mechanism_incorrectly_executed":
        NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for (
    error_name,
    operation_executed,
) in prohibited_block_6_operations.items():

    if operation_executed:

        NOTEBOOK_07_BLOCK_6_ERRORS.append(
            error_name
        )


NOTEBOOK_07_BLOCK_6_VALID = (
    len(
        NOTEBOOK_07_BLOCK_6_ERRORS
    )
    == 0
)


if not NOTEBOOK_07_BLOCK_6_VALID:

    raise RuntimeError(
        "Notebook 07 Block 6 Social Representation objective, "
        "optimiser and controlled-loss validation failed. "
        f"Errors: {NOTEBOOK_07_BLOCK_6_ERRORS}"
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_07_BLOCK_6_COMPLETE = True


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_07_BLOCK_6_SUMMARY = {
    "block":
        NOTEBOOK_07_BLOCK_6,

    "block_name":
        NOTEBOOK_07_BLOCK_6_NAME,

    "version":
        NOTEBOOK_07_BLOCK_6_VERSION,

    "objective_execution_version":
        NOTEBOOK_07_SOCIAL_OBJECTIVE_EXECUTION_VERSION,

    "executed_at_utc":
        BLOCK_6_EXECUTED_AT_UTC,

    "active_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),

    "active_indices":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

    "deferred_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        ),

    "active_loss_families":
        deepcopy(
            NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES
        ),

    "objective_weights":
        deepcopy(
            BLOCK_6_OBJECTIVE_WEIGHTS
        ),

    "active_available_counts":
        deepcopy(
            BLOCK_6_ACTIVE_AVAILABLE_COUNTS
        ),

    "family_losses":
        deepcopy(
            BLOCK_6_SOCIAL_FAMILY_LOSS_VALUES
        ),

    "total_social_objective":
        BLOCK_6_TOTAL_SOCIAL_OBJECTIVE_VALUE,

    "family_losses_reproduced":
        BLOCK_6_FAMILY_LOSSES_REPRODUCED,

    "total_objective_reproduced":
        BLOCK_6_TOTAL_OBJECTIVE_REPRODUCED,

    "optimizer_type":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE,

    "learning_rate":
        NOTEBOOK_07_SOCIAL_LEARNING_RATE,

    "weight_decay":
        NOTEBOOK_07_SOCIAL_WEIGHT_DECAY,

    "optimizer_parameters":
        BLOCK_6_OPTIMIZER_PARAMETER_COUNT,

    "optimizer_scope_exact":
        BLOCK_6_OPTIMIZER_SCOPE_EXACT,

    "optimizer_state_empty":
        BLOCK_6_OPTIMIZER_STATE_EMPTY,

    "all_parameters_unchanged":
        BLOCK_6_ALL_PARAMETERS_UNCHANGED,

    "loss_contract_validated":
        NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_VALIDATED,

    "optimizer_policy_valid":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_POLICY_VALID,

    "controlled_loss_valid":
        NOTEBOOK_07_SOCIAL_CONTROLLED_LOSS_VALID,

    "optimisation_ready":
        NOTEBOOK_07_SOCIAL_OPTIMISATION_READY,

    "ready_for_controlled_training":
        NOTEBOOK_07_READY_FOR_CONTROLLED_SOCIAL_TRAINING,

    "empirical_validity":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_07_BLOCK_6_VALID,

    "block_complete":
        NOTEBOOK_07_BLOCK_6_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 07, Block 6: "
    "Social Representation Objective Assembly, "
    "Optimiser Policy and Controlled Loss Validation"
)

print("=" * 72)

print(
    f"Block version                : "
    f"{NOTEBOOK_07_BLOCK_6_VERSION}"
)

print(
    f"Objective-execution version  : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVE_EXECUTION_VERSION}"
)


print("-" * 72)

print(
    "Canonical Social Representation supervision"
)

print(
    f"Target matrix shape          : "
    f"{BLOCK_6_SOCIAL_TARGET_MATRIX.shape}"
)

print(
    f"Mask matrix shape            : "
    f"{BLOCK_6_SOCIAL_MASK_MATRIX.shape}"
)

print(
    f"Observed values finite       : "
    f"{BLOCK_6_OBSERVED_TARGET_VALUES_FINITE}"
)

print(
    f"Block 5 output shape         : "
    f"{tuple(BLOCK_6_SOCIAL_OUTPUT.shape)}"
)

print(
    f"Block 5 output finite        : "
    f"{BLOCK_6_SOCIAL_OUTPUT_FINITE}"
)

print(
    f"Block 5 output diagnostic    : "
    f"{BLOCK_6_BLOCK_5_OUTPUT_IS_DIAGNOSTIC}"
)


print("-" * 72)

print(
    "Active Social Representation objective contract"
)

print(
    f"Active dimensions            : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)}"
)

print(
    f"Active indices               : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_INDICES)}"
)

print(
    f"Deferred dimensions          : "
    f"{list(NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS)}"
)

print(
    f"Deferred indices             : "
    f"{list(NOTEBOOK_07_SOCIAL_DEFERRED_INDICES)}"
)

print(
    f"Active signed dimensions     : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_SIGNED_DIMENSIONS)}"
)

print(
    f"Active binary dimensions     : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_BINARY_DIMENSIONS)}"
)

print(
    f"Active coverage reproduced   : "
    f"{BLOCK_6_ACTIVE_COVERAGE_REPRODUCED}"
)


for dimension_name in (
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
):

    print(
        f"{dimension_name:<31}: "
        f"{BLOCK_6_ACTIVE_AVAILABLE_COUNTS[dimension_name]}"
        f" / "
        f"{NOTEBOOK_07_SENTENCE_COUNT}"
    )


print("-" * 72)

print(
    "Controlled Social Representation objective"
)


for dimension_name in (
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
):

    print(
        f"{dimension_name:<31}: "
        f"{BLOCK_6_SOCIAL_FAMILY_LOSS_VALUES[dimension_name]:.8f} "
        f"("
        f"{NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES[dimension_name]}"
        f")"
    )


print(
    f"Objective-family weights     : "
    f"{BLOCK_6_OBJECTIVE_WEIGHTS}"
)

print(
    f"Objective weight sum         : "
    f"{BLOCK_6_OBJECTIVE_WEIGHT_SUM:.4f}"
)

print(
    f"Total social objective       : "
    f"{BLOCK_6_TOTAL_SOCIAL_OBJECTIVE_VALUE:.8f}"
)

print(
    f"Total objective finite       : "
    f"{BLOCK_6_TOTAL_OBJECTIVE_FINITE}"
)

print(
    f"Total objective scalar       : "
    f"{BLOCK_6_TOTAL_OBJECTIVE_SCALAR}"
)

print(
    f"Family losses reproduced     : "
    f"{BLOCK_6_FAMILY_LOSSES_REPRODUCED}"
)

print(
    f"Total objective reproduced   : "
    f"{BLOCK_6_TOTAL_OBJECTIVE_REPRODUCED}"
)

print(
    f"Deferred dimensions excluded : "
    f"{BLOCK_6_DEFERRED_DIMENSIONS_EXCLUDED}"
)


print("-" * 72)

print(
    "Parameter-freezing policy"
)

print(
    f"Backbone frozen              : "
    f"{BLOCK_6_BACKBONE_FROZEN}"
)

print(
    f"Global confluent frozen      : "
    f"{BLOCK_6_GLOBAL_CONFLUENT_FROZEN}"
)

print(
    f"Psychological head frozen    : "
    f"{BLOCK_6_PSYCHOLOGICAL_HEAD_FROZEN}"
)

print(
    f"Factual head frozen          : "
    f"{BLOCK_6_FACTUAL_HEAD_FROZEN}"
)

print(
    f"Social head trainable        : "
    f"{BLOCK_6_SOCIAL_HEAD_TRAINABLE}"
)

print(
    f"Social trainable parameters  : "
    f"{BLOCK_6_SOCIAL_TRAINABLE_PARAMETER_COUNT}"
)

print(
    f"Expected social parameters   : "
    f"{BLOCK_6_EXPECTED_SOCIAL_PARAMETER_COUNT}"
)

print(
    f"Parameter scope valid        : "
    f"{BLOCK_6_PARAMETER_FREEZING_POLICY_VALID}"
)


print("-" * 72)

print(
    "Optimiser policy"
)

print(
    f"Optimiser                    : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE}"
)

print(
    f"Learning rate                : "
    f"{NOTEBOOK_07_SOCIAL_LEARNING_RATE}"
)

print(
    f"Weight decay                 : "
    f"{NOTEBOOK_07_SOCIAL_WEIGHT_DECAY}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED}"
)

print(
    f"Optimiser parameters         : "
    f"{BLOCK_6_OPTIMIZER_PARAMETER_COUNT}"
)

print(
    f"Optimiser scope exact        : "
    f"{BLOCK_6_OPTIMIZER_SCOPE_EXACT}"
)

print(
    f"Optimiser scope valid        : "
    f"{BLOCK_6_OPTIMIZER_SCOPE_VALID}"
)

print(
    f"Optimiser step state empty   : "
    f"{BLOCK_6_OPTIMIZER_STATE_EMPTY}"
)


print("-" * 72)

print(
    "No-update validation"
)

print(
    f"Backbone unchanged           : "
    f"{BLOCK_6_BACKBONE_UNCHANGED}"
)

print(
    f"Global confluent unchanged   : "
    f"{BLOCK_6_GLOBAL_CONFLUENT_UNCHANGED}"
)

print(
    f"Psychological head unchanged : "
    f"{BLOCK_6_PSYCHOLOGICAL_UNCHANGED}"
)

print(
    f"Factual head unchanged       : "
    f"{BLOCK_6_FACTUAL_UNCHANGED}"
)

print(
    f"Social head unchanged        : "
    f"{BLOCK_6_SOCIAL_UNCHANGED}"
)

print(
    f"Frozen parameters unchanged  : "
    f"{BLOCK_6_FROZEN_PARAMETERS_UNCHANGED}"
)

print(
    f"All parameters unchanged     : "
    f"{BLOCK_6_ALL_PARAMETERS_UNCHANGED}"
)

print(
    f"Social gradients absent      : "
    f"{BLOCK_6_SOCIAL_GRADIENTS_ABSENT}"
)

print(
    f"Frozen gradients absent      : "
    f"{BLOCK_6_FROZEN_GRADIENTS_ABSENT}"
)

print(
    f"No-update validation valid   : "
    f"{BLOCK_6_NO_UPDATE_VALID}"
)


print("-" * 72)

print(
    "Readiness"
)

print(
    f"Objective assembled          : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVE_ASSEMBLED}"
)

print(
    f"Loss contract validated      : "
    f"{NOTEBOOK_07_SOCIAL_LOSS_CONTRACT_VALIDATED}"
)

print(
    f"Optimiser policy valid       : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_POLICY_VALID}"
)

print(
    f"Controlled loss valid        : "
    f"{NOTEBOOK_07_SOCIAL_CONTROLLED_LOSS_VALID}"
)

print(
    f"Social optimisation ready    : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMISATION_READY}"
)

print(
    f"Ready for controlled training: "
    f"{NOTEBOOK_07_READY_FOR_CONTROLLED_SOCIAL_TRAINING}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Block 6 model forward        : "
    f"{False}"
)

print(
    f"Objectives activated         : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVES_ACTIVATED}"
)

print(
    f"Loss calculated              : "
    f"{NOTEBOOK_07_SOCIAL_LOSS_CALCULATED}"
)

print(
    f"Optimiser created            : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED}"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Social training executed     : "
    f"{NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Factual retraining           : "
    f"{NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative executed      : "
    f"{NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED}"
)

print(
    f"Transformative weights active: "
    f"{NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED}"
)

print(
    f"Recurrent executed           : "
    f"{NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED}"
)

print(
    f"Held-out evaluation executed : "
    f"{NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_07_BLOCK_6_VALID}"
)

print(
    f"Block 6 complete             : "
    f"{NOTEBOOK_07_BLOCK_6_COMPLETE}"
)


print("=" * 72)


print(
    "Notebook 07 Social Representation objective assembly, optimiser "
    "policy and controlled loss validation completed successfully."
)

print(
    "Block 6 consumes the validated Social Representation targets and "
    "masks produced by Block 4 without reconstructing or reinterpreting "
    "social supervision."
)

print(
    "Block 6 consumes the validated seven-dimensional Social Representation "
    "output produced by Block 5 without reconstructing the inherited "
    "architecture or contextual representation."
)

print(
    f"{len(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)} active Social "
    "Representation dimension(s) remain separate mask-aware objectives "
    "using the loss families inherited from the validated Block 4 policy."
)

print(
    f"{len(NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS)} deferred Social "
    "Representation dimension(s) remain structurally present but excluded "
    "from the current controlled optimisation objective."
)

print(
    "The active Social Representation objective families contribute "
    "equally to the controlled total social objective."
)

print(
    f"The AdamW optimiser is scoped exclusively to the "
    f"{BLOCK_6_SOCIAL_TRAINABLE_PARAMETER_COUNT:,} trainable Social "
    "Representation parameters."
)

print(
    "The backbone, mandatory global confluent representation, "
    "Psychological Representation and Factual Representation remain "
    "frozen and outside the optimiser."
)

print(
    "The optional group-conditioned path remains inactive and deferred "
    "to Notebook 10."
)

print(
    "The Transformative Mechanism, Transformative Weights and recurrent "
    "mechanism remain inactive."
)

print(
    "Block 6 performs no new model forward pass, zero-gradient operation, "
    "backward pass, optimiser step or parameter update."
)

print(
    "All model parameters remain unchanged after objective and optimiser "
    "validation."
)

print(
    "The controlled Social Representation losses are computational "
    "diagnostics and do not establish prediction quality, generalisation "
    "or empirical validity."
)

print(
    "Block 7 may proceed to Controlled Social Representation Training "
    "and Checkpoint Policy."
)

print("=" * 72)

========================================================================
Media AI — Notebook 07, Block 6: Social Representation Objective Assembly, Optimiser Policy and Controlled Loss Validation
========================================================================
Block version                : 1.1
Objective-execution version  : 1.1
------------------------------------------------------------------------
Canonical Social Representation supervision
Target matrix shape          : (54, 7)
Mask matrix shape            : (54, 7)
Observed values finite       : True
Block 5 output shape         : (54, 7)
Block 5 output finite        : True
Block 5 output diagnostic    : True
------------------------------------------------------------------------
Active Social Representation objective contract
Active dimensions            : ['interpersonal_cohesion', 'economic_cohesion', 'political_cohesion', 'group_collective_cohesion']
Active indices               : [0, 1, 2, 4]
Deferred dimensions          : ['religious_cohesion', 'institutional_role_relation', 'public_audience_relation']
Deferred indices             : [3, 5, 6]
Active signed dimensions     : ['interpersonal_cohesion', 'economic_cohesion', 'political_cohesion', 'group_collective_cohesion']
Active binary dimensions     : []
Active coverage reproduced   : True
interpersonal_cohesion         : 26 / 54
economic_cohesion              : 3 / 54
political_cohesion             : 21 / 54
group_collective_cohesion      : 32 / 54
------------------------------------------------------------------------
Controlled Social Representation objective
interpersonal_cohesion         : 0.59975111 (masked_mean_squared_error)
economic_cohesion              : 0.15738152 (masked_mean_squared_error)
political_cohesion             : 1.00055444 (masked_mean_squared_error)
group_collective_cohesion      : 0.59975421 (masked_mean_squared_error)
Objective-family weights     : {'interpersonal_cohesion': 0.25, 'economic_cohesion': 0.25, 'political_cohesion': 0.25, 'group_collective_cohesion': 0.25}
Objective weight sum         : 1.0000
Total social objective       : 0.58936036
Total objective finite       : True
Total objective scalar       : True
Family losses reproduced     : True
Total objective reproduced   : True
Deferred dimensions excluded : True
------------------------------------------------------------------------
Parameter-freezing policy
Backbone frozen              : True
Global confluent frozen      : True
Psychological head frozen    : True
Factual head frozen          : True
Social head trainable        : True
Social trainable parameters  : 34055
Expected social parameters   : 34055
Parameter scope valid        : True
------------------------------------------------------------------------
Optimiser policy
Optimiser                    : AdamW
Learning rate                : 0.001
Weight decay                 : 0.0001
Optimiser created            : True
Optimiser parameters         : 34055
Optimiser scope exact        : True
Optimiser scope valid        : True
Optimiser step state empty   : True
------------------------------------------------------------------------
No-update validation
Backbone unchanged           : True
Global confluent unchanged   : True
Psychological head unchanged : True
Factual head unchanged       : True
Social head unchanged        : True
Frozen parameters unchanged  : True
All parameters unchanged     : True
Social gradients absent      : True
Frozen gradients absent      : True
No-update validation valid   : True
------------------------------------------------------------------------
Readiness
Objective assembled          : True
Loss contract validated      : True
Optimiser policy valid       : True
Controlled loss valid        : True
Social optimisation ready    : True
Ready for controlled training: True
------------------------------------------------------------------------
Execution boundary
Block 6 model forward        : False
Objectives activated         : True
Loss calculated              : True
Optimiser created            : True
Zero grad executed           : False
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
Social training executed     : False
Psychological retraining     : False
Factual retraining           : False
Group-conditioned executed   : False
Transformative executed      : False
Transformative weights active: False
Recurrent executed           : False
Held-out evaluation executed : False
Empirical validity           : False
Block valid                  : True
Block 6 complete             : True
========================================================================
Notebook 07 Social Representation objective assembly, optimiser policy and controlled loss validation completed successfully.
Block 6 consumes the validated Social Representation targets and masks produced by Block 4 without reconstructing or reinterpreting social supervision.
Block 6 consumes the validated seven-dimensional Social Representation output produced by Block 5 without reconstructing the inherited architecture or contextual representation.
4 active Social Representation dimension(s) remain separate mask-aware objectives using the loss families inherited from the validated Block 4 policy.
3 deferred Social Representation dimension(s) remain structurally present but excluded from the current controlled optimisation objective.
The active Social Representation objective families contribute equally to the controlled total social objective.
The AdamW optimiser is scoped exclusively to the 34,055 trainable Social Representation parameters.
The backbone, mandatory global confluent representation, Psychological Representation and Factual Representation remain frozen and outside the optimiser.
The optional group-conditioned path remains inactive and deferred to Notebook 10.
The Transformative Mechanism, Transformative Weights and recurrent mechanism remain inactive.
Block 6 performs no new model forward pass, zero-gradient operation, backward pass, optimiser step or parameter update.
All model parameters remain unchanged after objective and optimiser validation.
The controlled Social Representation losses are computational diagnostics and do not establish prediction quality, generalisation or empirical validity.
Block 7 may proceed to Controlled Social Representation Training and Checkpoint Policy.
========================================================================

## Block 7 — Controlled Social Representation Training and Checkpoint Construction

This block performs the controlled optimisation of the **Social Representation** using the supervision, activation, model, loss and optimiser contracts established in Blocks 1–6.

The block begins from the validated Block 6 optimisation state and preserves the architectural boundary established earlier in Notebook 07. The persisted contextual sentence representation, backbone, mandatory global confluent representation, Psychological Representation and Factual Representation remain frozen. Only the Social Representation head is eligible for parameter updates.

Training is restricted to the currently active Social Representation dimensions:

- **S1 — interpersonal_cohesion**
- **S3 — political_cohesion**
- **S5 — group_collective_cohesion**

The remaining Social Representation dimensions remain structurally present but excluded from the current optimisation objective:

- **S2 — economic_cohesion** — deferred because the current sample contains insufficient explicit supervision
- **S4 — religious_cohesion** — deferred because explicit supervision is unavailable
- **S6 — institutional_role_relation** — deferred because the observed target currently has zero variance
- **S7 — public_audience_relation** — deferred because the observed target currently has zero variance

The active dimensions retain the mask-aware signed-cohesion objective established in Block 6. Missing supervision does not enter the loss and is not interpreted as either zero or a negative observation. The active objective is calculated only from explicitly accepted sentence-level social supervision.

Training operates on the canonical persisted contextual sentence representations restored and validated in Block 5. Canonical sentence identity and alignment must remain unchanged throughout optimisation. No contextual representation is regenerated, extended or replaced during this block, and no future context is introduced.

Before optimisation, the block records exact parameter snapshots for the frozen inherited modules and the initial Social Representation state. The validated Social Representation head contains **34,055 trainable parameters**, and no parameter outside this head is eligible for gradient-based optimisation.

During training, gradients and optimiser updates are restricted to the Social Representation head. After training, the block verifies that the backbone, mandatory global confluent representation, Psychological Representation and Factual Representation remain exactly unchanged.

The block records the controlled training history, including the initial objective, epoch-level objective values, final objective, active-dimension losses and optimisation metadata. These diagnostics describe optimisation behaviour on the current controlled supervision set and do **not** constitute held-out evaluation, generalisation evidence or empirical validation.

If the controlled optimisation contract is satisfied, the resulting Social Representation state is persisted as a reproducible **controlled experimental Social Representation training checkpoint**, together with the metadata required to reconstruct its training conditions and active/deferred semantic scope.

The checkpoint must not be described as a validated model checkpoint. Notebook 07 continues to distinguish successful optimisation and reproducibility from independent evaluation and empirical validity.

The optional group-conditioned path remains inactive and deferred to Notebook 10. The Transformative Mechanism remains reserved for Notebook 08, while Transformative Weights and the recurrent mechanism remain reserved for Notebook 09.

No Psychological Representation or Factual Representation retraining is permitted in this block. No backbone or global-confluent retraining is permitted. No group-conditioned, transformative or recurrent mechanism is executed.

Successful completion of Block 7 establishes that the Social Representation has been trained reproducibly within its current controlled experimental scope while preserving all inherited frozen components. It does not establish full Social Representation coverage, held-out performance, generalisation or empirical validity.

The next block may proceed to **Social Representation Training Audit, Persistent Handover and Notebook 07 Completion**.

In [22]:
# =============================================================================
# Media AI — Notebook 07
# Block 7: Controlled Social Representation Training and Checkpoint Policy
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json
import math

import numpy as np
import torch
import torch.nn.functional as F

from googleapiclient.http import (
    MediaIoBaseDownload,
    MediaIoBaseUpload,
)


# =============================================================================
# Dependency checks
# =============================================================================

required_block_7_objects = [
    "NOTEBOOK_07_BLOCK_1_COMPLETE",
    "NOTEBOOK_07_BLOCK_1_VALID",
    "NOTEBOOK_07_BLOCK_2_COMPLETE",
    "NOTEBOOK_07_BLOCK_2_VALID",
    "NOTEBOOK_07_BLOCK_3_COMPLETE",
    "NOTEBOOK_07_BLOCK_3_VALID",
    "NOTEBOOK_07_BLOCK_4_COMPLETE",
    "NOTEBOOK_07_BLOCK_4_VALID",
    "NOTEBOOK_07_BLOCK_5_COMPLETE",
    "NOTEBOOK_07_BLOCK_5_VALID",
    "NOTEBOOK_07_BLOCK_6_COMPLETE",
    "NOTEBOOK_07_BLOCK_6_VALID",

    "NOTEBOOK_07_DRIVE_SERVICE",

    "NOTEBOOK_07_SENTENCE_IDS",
    "NOTEBOOK_07_SENTENCE_COUNT",
    "NOTEBOOK_07_ARTICLE_COUNT",

    "NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_SOCIAL_DIMENSION_ORDER",
    "NOTEBOOK_07_SOCIAL_DIMENSION_IDS",

    "NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_ACTIVE_INDICES",
    "NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_DEFERRED_INDICES",

    "NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS",
    "NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES",
    "NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID",
    "NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY",

    "NOTEBOOK_07_BACKBONE_FROZEN_MODULE",
    "NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE",
    "NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE",
    "NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE",
    "NOTEBOOK_07_SOCIAL_HEAD",

    "NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT",

    "BLOCK_4_SOCIAL_TARGET_MATRIX",
    "BLOCK_4_SOCIAL_MASK_MATRIX",

    "BLOCK_5_CONTEXTUAL_REPRESENTATION",
    "BLOCK_5_REPRESENTATION_DRIVE_FILE_ID",

    "NOTEBOOK_07_SOCIAL_OPTIMIZER_POLICY_VALID",
]


missing_block_7_objects = [
    object_name
    for object_name
    in required_block_7_objects
    if object_name not in globals()
]


if missing_block_7_objects:

    raise NameError(
        "Notebook 07 Block 7 prerequisites are not initialised. "
        f"Missing: {missing_block_7_objects}"
    )


if not all(
    [
        NOTEBOOK_07_BLOCK_1_COMPLETE,
        NOTEBOOK_07_BLOCK_1_VALID,
        NOTEBOOK_07_BLOCK_2_COMPLETE,
        NOTEBOOK_07_BLOCK_2_VALID,
        NOTEBOOK_07_BLOCK_3_COMPLETE,
        NOTEBOOK_07_BLOCK_3_VALID,
        NOTEBOOK_07_BLOCK_4_COMPLETE,
        NOTEBOOK_07_BLOCK_4_VALID,
        NOTEBOOK_07_BLOCK_5_COMPLETE,
        NOTEBOOK_07_BLOCK_5_VALID,
        NOTEBOOK_07_BLOCK_6_COMPLETE,
        NOTEBOOK_07_BLOCK_6_VALID,
        NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID,
        NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY,
        NOTEBOOK_07_SOCIAL_OPTIMIZER_POLICY_VALID,
    ]
):

    raise RuntimeError(
        "Notebook 07 Blocks 1–6 must be complete and valid "
        "before controlled Social Representation training."
    )


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_07_BLOCK_7 = 7

NOTEBOOK_07_BLOCK_7_NAME = (
    "Controlled Social Representation Training and Checkpoint Policy"
)

NOTEBOOK_07_BLOCK_7_VERSION = "1.1"

NOTEBOOK_07_SOCIAL_TRAINING_POLICY_VERSION = "1.1"


BLOCK_7_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Training policy
# =============================================================================

NOTEBOOK_07_SOCIAL_TRAINING_EPOCHS = 10

NOTEBOOK_07_SOCIAL_MAXIMUM_GRADIENT_NORM = 1.0

NOTEBOOK_07_SOCIAL_WITHIN_ARTICLE_SHUFFLE = False

NOTEBOOK_07_SOCIAL_ARTICLE_SEQUENCE_PRESERVED = True


# -----------------------------------------------------------------------------
# Optimiser policy
#
# These values reproduce the controlled Media AI representation-head
# optimisation policy used by the preceding factual path unless Block 6
# exported explicit values.
# -----------------------------------------------------------------------------

NOTEBOOK_07_SOCIAL_LEARNING_RATE = float(
    globals().get(
        "NOTEBOOK_07_SOCIAL_LEARNING_RATE",
        0.001,
    )
)


NOTEBOOK_07_SOCIAL_WEIGHT_DECAY = float(
    globals().get(
        "NOTEBOOK_07_SOCIAL_WEIGHT_DECAY",
        0.0001,
    )
)


NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE = (
    globals().get(
        "NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE",
        "AdamW",
    )
)


if NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE != "AdamW":

    raise RuntimeError(
        "Block 7 currently requires the validated AdamW "
        "Social Representation optimiser policy."
    )


# =============================================================================
# Execution-state initialisation
# =============================================================================

NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED = False

NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED = False

NOTEBOOK_07_SOCIAL_CHECKPOINT_CREATED = False

NOTEBOOK_07_SOCIAL_CHECKPOINT_READBACK_VALID = False

NOTEBOOK_07_SOCIAL_METADATA_READBACK_VALID = False

NOTEBOOK_07_SOCIAL_VALIDATED_MODEL_CHECKPOINT = False

NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED = False

NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED = False

NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Device
# =============================================================================

BLOCK_7_DEVICE = next(
    NOTEBOOK_07_SOCIAL_HEAD.parameters()
).device


# =============================================================================
# Canonical training scope
# =============================================================================

BLOCK_7_TRAINING_ARTICLE_COUNT = (
    NOTEBOOK_07_ARTICLE_COUNT
)


BLOCK_7_TRAINING_SENTENCE_COUNT = (
    NOTEBOOK_07_SENTENCE_COUNT
)


BLOCK_7_VALIDATION_SENTENCE_COUNT = 0

BLOCK_7_TEST_SENTENCE_COUNT = 0


BLOCK_7_TRAINING_SCOPE_VALID = all(
    [
        BLOCK_7_TRAINING_ARTICLE_COUNT > 0,
        BLOCK_7_TRAINING_SENTENCE_COUNT > 0,
        BLOCK_7_VALIDATION_SENTENCE_COUNT >= 0,
        BLOCK_7_TEST_SENTENCE_COUNT >= 0,
    ]
)


# =============================================================================
# Canonical active-objective contract
# =============================================================================
#
# Block 7 consumes the objective activation contract already validated by
# Blocks 4 and 6. It must not redefine a corpus-specific active subset.
# =============================================================================

BLOCK_7_ACTIVE_DIMENSIONS_VALID = all(
    [
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        )
        ==
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

        all(
            0 <= index < NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
            for index
            in NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

        all(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER[index]
            ==
            dimension_name

            for (
                dimension_name,
                index,
            ) in zip(
                NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS,
                NOTEBOOK_07_SOCIAL_ACTIVE_INDICES,
            )
        ),
    ]
)


BLOCK_7_DEFERRED_DIMENSIONS_VALID = all(
    [
        len(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        )
        ==
        len(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),

        all(
            0 <= index < NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
            for index
            in NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),

        all(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER[index]
            ==
            dimension_name

            for (
                dimension_name,
                index,
            ) in zip(
                NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS,
                NOTEBOOK_07_SOCIAL_DEFERRED_INDICES,
            )
        ),
    ]
)


BLOCK_7_OBJECTIVE_PARTITION_VALID = all(
    [
        set(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ).isdisjoint(
            set(
                NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
            )
        ),

        sorted(
            list(
                NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
            )
            +
            list(
                NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
            )
        )
        ==
        list(
            range(
                NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
            )
        ),
    ]
)


BLOCK_7_LOSS_FAMILY_KEYS_VALID = (
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES.keys()
    )
    ==
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


if not all(
    [
        BLOCK_7_ACTIVE_DIMENSIONS_VALID,
        BLOCK_7_DEFERRED_DIMENSIONS_VALID,
        BLOCK_7_OBJECTIVE_PARTITION_VALID,
        BLOCK_7_LOSS_FAMILY_KEYS_VALID,
    ]
):

    raise RuntimeError(
        "Block 7 Social Representation objective contract "
        "does not match the validated Block 4/6 policy."
    )


# =============================================================================
# Objective-weight validation
# =============================================================================

BLOCK_7_OBJECTIVE_WEIGHT_SUM = float(
    sum(
        NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS[
            dimension_name
        ]

        for dimension_name
        in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


BLOCK_7_OBJECTIVE_WEIGHTS_VALID = all(
    [
        set(
            NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS.keys()
        )
        ==
        set(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),

        all(
            math.isfinite(
                float(
                    NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS[
                        dimension_name
                    ]
                )
            )
            and
            float(
                NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS[
                    dimension_name
                ]
            )
            >
            0.0

            for dimension_name
            in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),

        np.isclose(
            BLOCK_7_OBJECTIVE_WEIGHT_SUM,
            1.0,
            rtol=0.0,
            atol=1e-12,
        ),
    ]
)


if not BLOCK_7_OBJECTIVE_WEIGHTS_VALID:

    raise RuntimeError(
        "Active Social Representation objective weights "
        "do not sum to one."
    )


# =============================================================================
# Restore training targets and masks
# =============================================================================

BLOCK_7_SOCIAL_TARGET_TENSOR = torch.tensor(
    BLOCK_4_SOCIAL_TARGET_MATRIX,
    dtype=torch.float32,
    device=BLOCK_7_DEVICE,
)


BLOCK_7_SOCIAL_MASK_TENSOR = torch.tensor(
    BLOCK_4_SOCIAL_MASK_MATRIX,
    dtype=torch.bool,
    device=BLOCK_7_DEVICE,
)


BLOCK_7_TARGET_SHAPE_VALID = (
    tuple(
        BLOCK_7_SOCIAL_TARGET_TENSOR.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_7_MASK_SHAPE_VALID = (
    tuple(
        BLOCK_7_SOCIAL_MASK_TENSOR.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_7_OBSERVED_TARGETS_FINITE = bool(
    torch.isfinite(
        BLOCK_7_SOCIAL_TARGET_TENSOR[
            BLOCK_7_SOCIAL_MASK_TENSOR
        ]
    ).all().item()
)


if not all(
    [
        BLOCK_7_TARGET_SHAPE_VALID,
        BLOCK_7_MASK_SHAPE_VALID,
        BLOCK_7_OBSERVED_TARGETS_FINITE,
    ]
):

    raise RuntimeError(
        "Block 7 Social Representation target/mask contract is invalid."
    )


# =============================================================================
# Contextual input
# =============================================================================

BLOCK_7_CONTEXTUAL_REPRESENTATION = (
    BLOCK_5_CONTEXTUAL_REPRESENTATION
    .detach()
    .clone()
    .to(
        BLOCK_7_DEVICE
    )
)


BLOCK_7_CONTEXTUAL_SHAPE_VALID = (
    tuple(
        BLOCK_7_CONTEXTUAL_REPRESENTATION.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        BLOCK_5_CONTEXTUAL_REPRESENTATION.shape[1],
    )
)


BLOCK_7_CONTEXTUAL_VALUES_FINITE = bool(
    torch.isfinite(
        BLOCK_7_CONTEXTUAL_REPRESENTATION
    ).all().item()
)


if not all(
    [
        BLOCK_7_CONTEXTUAL_SHAPE_VALID,
        BLOCK_7_CONTEXTUAL_VALUES_FINITE,
    ]
):

    raise RuntimeError(
        "Block 7 contextual training representation is invalid."
    )


# =============================================================================
# Parameter-freezing policy
# =============================================================================

for parameter in (
    NOTEBOOK_07_BACKBONE_FROZEN_MODULE.parameters()
):

    parameter.requires_grad = False


for parameter in (
    NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.parameters()
):

    parameter.requires_grad = False


for parameter in (
    NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.parameters()
):

    parameter.requires_grad = False


for parameter in (
    NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE.parameters()
):

    parameter.requires_grad = False


for parameter in (
    NOTEBOOK_07_SOCIAL_HEAD.parameters()
):

    parameter.requires_grad = True


BLOCK_7_BACKBONE_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_BACKBONE_FROZEN_MODULE.parameters()
)


BLOCK_7_GLOBAL_CONFLUENT_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.parameters()
)


BLOCK_7_PSYCHOLOGICAL_HEAD_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.parameters()
)


BLOCK_7_FACTUAL_HEAD_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE.parameters()
)


BLOCK_7_SOCIAL_HEAD_TRAINABLE = all(
    parameter.requires_grad
    for parameter
    in NOTEBOOK_07_SOCIAL_HEAD.parameters()
)


BLOCK_7_SOCIAL_TRAINABLE_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in NOTEBOOK_07_SOCIAL_HEAD.parameters()
    if parameter.requires_grad
)


BLOCK_7_PARAMETER_SCOPE_VALID = all(
    [
        BLOCK_7_BACKBONE_FROZEN,
        BLOCK_7_GLOBAL_CONFLUENT_FROZEN,
        BLOCK_7_PSYCHOLOGICAL_HEAD_FROZEN,
        BLOCK_7_FACTUAL_HEAD_FROZEN,
        BLOCK_7_SOCIAL_HEAD_TRAINABLE,

        (
            BLOCK_7_SOCIAL_TRAINABLE_PARAMETER_COUNT
            ==
            NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT
        ),

    ]
)


if not BLOCK_7_PARAMETER_SCOPE_VALID:

    raise RuntimeError(
        "Block 7 trainable parameter scope is invalid."
    )


# =============================================================================
# Frozen-module evaluation mode
# =============================================================================

NOTEBOOK_07_BACKBONE_FROZEN_MODULE.eval()

NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.eval()

NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.eval()

NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE.eval()


# =============================================================================
# Snapshot helpers
# =============================================================================

def block_7_snapshot_module(
    module,
):

    return {
        parameter_name:
            parameter
            .detach()
            .cpu()
            .clone()

        for (
            parameter_name,
            parameter,
        ) in module.named_parameters()
    }


def block_7_module_matches_snapshot(
    module,
    snapshot,
):

    current_parameters = dict(
        module.named_parameters()
    )


    if (
        set(
            current_parameters.keys()
        )
        !=
        set(
            snapshot.keys()
        )
    ):

        return False


    return all(
        torch.equal(
            current_parameters[
                parameter_name
            ]
            .detach()
            .cpu(),

            snapshot[
                parameter_name
            ],
        )

        for parameter_name
        in snapshot
    )


def block_7_maximum_parameter_delta(
    module,
    snapshot,
):

    maximum_delta = 0.0


    for (
        parameter_name,
        parameter,
    ) in module.named_parameters():

        delta = (
            parameter
            .detach()
            .cpu()
            -
            snapshot[
                parameter_name
            ]
        ).abs().max().item()


        maximum_delta = max(
            maximum_delta,
            float(
                delta
            ),
        )


    return maximum_delta


# =============================================================================
# Pre-training parameter snapshots
# =============================================================================

BLOCK_7_BACKBONE_BEFORE = (
    block_7_snapshot_module(
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE
    )
)


BLOCK_7_GLOBAL_CONFLUENT_BEFORE = (
    block_7_snapshot_module(
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE
    )
)


BLOCK_7_PSYCHOLOGICAL_BEFORE = (
    block_7_snapshot_module(
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE
    )
)


BLOCK_7_FACTUAL_BEFORE = (
    block_7_snapshot_module(
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE
    )
)


BLOCK_7_SOCIAL_BEFORE = (
    block_7_snapshot_module(
        NOTEBOOK_07_SOCIAL_HEAD
    )
)


# =============================================================================
# Optimiser construction
# =============================================================================

BLOCK_7_SOCIAL_TRAINABLE_PARAMETERS = [
    parameter
    for parameter
    in NOTEBOOK_07_SOCIAL_HEAD.parameters()
    if parameter.requires_grad
]


NOTEBOOK_07_SOCIAL_OPTIMIZER = torch.optim.AdamW(
    BLOCK_7_SOCIAL_TRAINABLE_PARAMETERS,
    lr=
        NOTEBOOK_07_SOCIAL_LEARNING_RATE,
    weight_decay=
        NOTEBOOK_07_SOCIAL_WEIGHT_DECAY,
)


NOTEBOOK_07_SOCIAL_OPTIMIZER_CREATED = True


BLOCK_7_OPTIMIZER_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter_group
    in NOTEBOOK_07_SOCIAL_OPTIMIZER.param_groups
    for parameter
    in parameter_group[
        "params"
    ]
)


BLOCK_7_OPTIMIZER_SCOPE_VALID = (
    BLOCK_7_OPTIMIZER_PARAMETER_COUNT
    ==
    BLOCK_7_SOCIAL_TRAINABLE_PARAMETER_COUNT
)


if not BLOCK_7_OPTIMIZER_SCOPE_VALID:

    raise RuntimeError(
        "Block 7 optimiser scope does not match the Social "
        "Representation trainable parameter scope."
    )


# =============================================================================
# Masked Social Representation objective
# =============================================================================

def block_7_masked_mean_squared_error(
    predictions,
    targets,
    mask,
):

    if not (
        predictions.ndim
        ==
        targets.ndim
        ==
        mask.ndim
        ==
        1
    ):

        raise ValueError(
            "Masked MSE prediction, target and mask must be one-dimensional."
        )


    if not (
        predictions.shape
        ==
        targets.shape
        ==
        mask.shape
    ):

        raise ValueError(
            "Masked MSE prediction, target and mask shapes do not match."
        )


    if int(
        mask.sum().item()
    ) <= 0:

        raise RuntimeError(
            "An active Social Representation MSE objective has no "
            "available supervision."
        )


    return F.mse_loss(
        predictions[
            mask
        ],
        targets[
            mask
        ],
        reduction=
            "mean",
    )


def block_7_masked_binary_cross_entropy_with_logits(
    predictions,
    targets,
    mask,
):

    if not (
        predictions.ndim
        ==
        targets.ndim
        ==
        mask.ndim
        ==
        1
    ):

        raise ValueError(
            "Masked BCE prediction, target and mask must be one-dimensional."
        )


    if not (
        predictions.shape
        ==
        targets.shape
        ==
        mask.shape
    ):

        raise ValueError(
            "Masked BCE prediction, target and mask shapes do not match."
        )


    if int(
        mask.sum().item()
    ) <= 0:

        raise RuntimeError(
            "An active Social Representation BCE objective has no "
            "available supervision."
        )


    observed_targets = targets[
        mask
    ]


    if not bool(
        torch.isin(
            observed_targets,
            torch.tensor(
                [0.0, 1.0],
                dtype=
                    observed_targets.dtype,
                device=
                    observed_targets.device,
            ),
        ).all().item()
    ):

        raise RuntimeError(
            "Active binary Social Representation target contains "
            "values outside {0, 1}."
        )


    return F.binary_cross_entropy_with_logits(
        predictions[
            mask
        ],
        observed_targets,
        reduction=
            "mean",
    )


def block_7_calculate_social_objective(
    social_output,
):

    family_losses = {}


    total_objective = torch.zeros(
        (),
        dtype=
            social_output.dtype,
        device=
            social_output.device,
    )


    for (
        dimension_name,
        dimension_index,
    ) in zip(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS,
        NOTEBOOK_07_SOCIAL_ACTIVE_INDICES,
    ):

        dimension_predictions = (
            social_output[
                :,
                dimension_index,
            ]
        )


        dimension_targets = (
            BLOCK_7_SOCIAL_TARGET_TENSOR[
                :,
                dimension_index,
            ]
        )


        dimension_mask = (
            BLOCK_7_SOCIAL_MASK_TENSOR[
                :,
                dimension_index,
            ]
        )


        loss_family = (
            NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES[
                dimension_name
            ]
        )


        if loss_family == "masked_mean_squared_error":

            family_loss = (
                block_7_masked_mean_squared_error(
                    dimension_predictions,
                    dimension_targets,
                    dimension_mask,
                )
            )


        elif loss_family == "binary_cross_entropy_with_logits":

            family_loss = (
                block_7_masked_binary_cross_entropy_with_logits(
                    dimension_predictions,
                    dimension_targets,
                    dimension_mask,
                )
            )


        else:

            raise RuntimeError(
                f"Unsupported active Social Representation loss family "
                f"for {dimension_name}: {loss_family}"
            )


        family_losses[
            dimension_name
        ] = family_loss


        total_objective = (
            total_objective
            +
            (
                float(
                    NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS[
                        dimension_name
                    ]
                )
                *
                family_loss
            )
        )


    return (
        family_losses,
        total_objective,
    )


# =============================================================================
# Controlled deterministic evaluation helper
# =============================================================================

def block_7_controlled_evaluation():
    """
    Evaluate the current Social Representation state without updates.

    All dropout layers are disabled through eval mode.
    """

    NOTEBOOK_07_BACKBONE_FROZEN_MODULE.eval()

    NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.eval()

    NOTEBOOK_07_SOCIAL_HEAD.eval()


    with torch.no_grad():

        backbone_output = (
            NOTEBOOK_07_BACKBONE_FROZEN_MODULE(
                BLOCK_7_CONTEXTUAL_REPRESENTATION
            )
        )


        global_output = (
            NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE(
                backbone_output
            )
        )


        social_output = (
            NOTEBOOK_07_SOCIAL_HEAD(
                global_output
            )
        )


        (
            family_losses,
            total_objective,
        ) = block_7_calculate_social_objective(
            social_output
        )


    family_loss_values = {
        dimension_name:
            float(
                loss.detach().cpu().item()
            )

        for (
            dimension_name,
            loss,
        ) in family_losses.items()
    }


    return {
        "family_losses":
            family_loss_values,

        "total_objective":
            float(
                total_objective
                .detach()
                .cpu()
                .item()
            ),
    }


# =============================================================================
# Initial controlled objective
# =============================================================================

BLOCK_7_INITIAL_EVALUATION = (
    block_7_controlled_evaluation()
)


BLOCK_7_INITIAL_FAMILY_LOSSES = deepcopy(
    BLOCK_7_INITIAL_EVALUATION[
        "family_losses"
    ]
)


BLOCK_7_INITIAL_TOTAL_OBJECTIVE = float(
    BLOCK_7_INITIAL_EVALUATION[
        "total_objective"
    ]
)


BLOCK_7_INITIAL_TOTAL_OBJECTIVE_FINITE = bool(
    math.isfinite(
        BLOCK_7_INITIAL_TOTAL_OBJECTIVE
    )
)


if not BLOCK_7_INITIAL_TOTAL_OBJECTIVE_FINITE:

    raise RuntimeError(
        "Initial Social Representation training objective is non-finite."
    )


# =============================================================================
# Optional Block 6 objective reproduction
# =============================================================================
#
# Block 6 naming may vary slightly across notebook revisions.
# If a validated scalar is exported under one of the supported names,
# Block 7 reproduces it explicitly.
# =============================================================================

BLOCK_7_BLOCK_6_OBJECTIVE_REFERENCE = None

BLOCK_7_BLOCK_6_OBJECTIVE_REFERENCE_NAME = None


for candidate_name in (
    "BLOCK_6_TOTAL_SOCIAL_OBJECTIVE",
    "BLOCK_6_CONTROLLED_TOTAL_OBJECTIVE",
    "NOTEBOOK_07_SOCIAL_CONTROLLED_TOTAL_OBJECTIVE",
    "NOTEBOOK_07_SOCIAL_INITIAL_TOTAL_OBJECTIVE",
):

    if candidate_name not in globals():

        continue


    candidate_value = globals()[
        candidate_name
    ]


    if isinstance(
        candidate_value,
        torch.Tensor,
    ):

        if candidate_value.numel() == 1:

            candidate_value = float(
                candidate_value
                .detach()
                .cpu()
                .item()
            )


    try:

        candidate_value = float(
            candidate_value
        )


    except (
        TypeError,
        ValueError,
    ):

        continue


    if math.isfinite(
        candidate_value
    ):

        BLOCK_7_BLOCK_6_OBJECTIVE_REFERENCE = (
            candidate_value
        )

        BLOCK_7_BLOCK_6_OBJECTIVE_REFERENCE_NAME = (
            candidate_name
        )

        break


if BLOCK_7_BLOCK_6_OBJECTIVE_REFERENCE is not None:

    BLOCK_7_BLOCK_6_OBJECTIVE_REPRODUCED = bool(
        np.isclose(
            BLOCK_7_INITIAL_TOTAL_OBJECTIVE,
            BLOCK_7_BLOCK_6_OBJECTIVE_REFERENCE,
            rtol=1e-6,
            atol=1e-8,
        )
    )


    if not BLOCK_7_BLOCK_6_OBJECTIVE_REPRODUCED:

        raise RuntimeError(
            "Block 7 initial objective does not reproduce the "
            "validated Block 6 controlled Social Representation objective."
        )


else:

    BLOCK_7_BLOCK_6_OBJECTIVE_REPRODUCED = None


# =============================================================================
# Training history
# =============================================================================

BLOCK_7_SOCIAL_TRAINING_HISTORY = []

BLOCK_7_NONFINITE_LOSS_DETECTED = False

BLOCK_7_NONFINITE_GRADIENT_DETECTED = False

BLOCK_7_MAXIMUM_PRECLIP_GRADIENT_NORM = 0.0


# =============================================================================
# Controlled Social Representation training
# =============================================================================
#
# The complete current training corpus is processed in canonical sentence order.
#
# No within-article shuffle is performed.
#
# Only the Social Representation head is trainable.
# =============================================================================

NOTEBOOK_07_SOCIAL_HEAD.train()


for epoch_index in range(
    NOTEBOOK_07_SOCIAL_TRAINING_EPOCHS
):

    # =========================================================================
    # Frozen inherited representations
    # =========================================================================

    NOTEBOOK_07_BACKBONE_FROZEN_MODULE.eval()

    NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.eval()


    with torch.no_grad():

        block_7_backbone_output = (
            NOTEBOOK_07_BACKBONE_FROZEN_MODULE(
                BLOCK_7_CONTEXTUAL_REPRESENTATION
            )
        )


        block_7_global_output = (
            NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE(
                block_7_backbone_output
            )
        )


    # =========================================================================
    # Trainable Social Representation forward
    # =========================================================================

    NOTEBOOK_07_SOCIAL_OPTIMIZER.zero_grad(
        set_to_none=True
    )


    NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED = True


    block_7_social_output = (
        NOTEBOOK_07_SOCIAL_HEAD(
            block_7_global_output
        )
    )


    (
        block_7_family_losses,
        block_7_total_objective,
    ) = block_7_calculate_social_objective(
        block_7_social_output
    )


    # =========================================================================
    # Loss finiteness
    # =========================================================================

    if not bool(
        torch.isfinite(
            block_7_total_objective
        ).item()
    ):

        BLOCK_7_NONFINITE_LOSS_DETECTED = True

        raise RuntimeError(
            f"Non-finite Social Representation objective detected "
            f"at epoch {epoch_index + 1}."
        )


    # =========================================================================
    # Backward pass
    # =========================================================================

    block_7_total_objective.backward()


    NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED = True


    # =========================================================================
    # Gradient finiteness
    # =========================================================================

    for parameter in (
        NOTEBOOK_07_SOCIAL_HEAD.parameters()
    ):

        if parameter.grad is None:

            continue


        if not bool(
            torch.isfinite(
                parameter.grad
            ).all().item()
        ):

            BLOCK_7_NONFINITE_GRADIENT_DETECTED = True

            raise RuntimeError(
                f"Non-finite Social Representation gradient detected "
                f"at epoch {epoch_index + 1}."
            )


    # =========================================================================
    # Pre-clip gradient norm
    # =========================================================================

    squared_gradient_norm = 0.0


    for parameter in (
        NOTEBOOK_07_SOCIAL_HEAD.parameters()
    ):

        if parameter.grad is None:

            continue


        gradient_norm = float(
            parameter.grad
            .detach()
            .norm(
                2
            )
            .cpu()
            .item()
        )


        squared_gradient_norm += (
            gradient_norm
            **
            2
        )


    preclip_gradient_norm = math.sqrt(
        squared_gradient_norm
    )


    BLOCK_7_MAXIMUM_PRECLIP_GRADIENT_NORM = max(
        BLOCK_7_MAXIMUM_PRECLIP_GRADIENT_NORM,
        preclip_gradient_norm,
    )


    # =========================================================================
    # Gradient clipping
    # =========================================================================

    torch.nn.utils.clip_grad_norm_(
        NOTEBOOK_07_SOCIAL_HEAD.parameters(),
        max_norm=
            NOTEBOOK_07_SOCIAL_MAXIMUM_GRADIENT_NORM,
    )


    # =========================================================================
    # Optimiser step
    # =========================================================================

    NOTEBOOK_07_SOCIAL_OPTIMIZER.step()


    NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED = True

    NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED = True


    # =========================================================================
    # Epoch diagnostics
    # =========================================================================

    epoch_family_losses = {
        dimension_name:
            float(
                loss
                .detach()
                .cpu()
                .item()
            )

        for (
            dimension_name,
            loss,
        ) in block_7_family_losses.items()
    }


    BLOCK_7_SOCIAL_TRAINING_HISTORY.append(
        {
            "epoch":
                int(
                    epoch_index
                    +
                    1
                ),

            "total_objective":
                float(
                    block_7_total_objective
                    .detach()
                    .cpu()
                    .item()
                ),

            "family_losses":
                epoch_family_losses,

            "preclip_gradient_norm":
                float(
                    preclip_gradient_norm
                ),
        }
    )


NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED = True


# =============================================================================
# Post-training controlled evaluation
# =============================================================================

BLOCK_7_FINAL_EVALUATION = (
    block_7_controlled_evaluation()
)


BLOCK_7_FINAL_FAMILY_LOSSES = deepcopy(
    BLOCK_7_FINAL_EVALUATION[
        "family_losses"
    ]
)


BLOCK_7_FINAL_TOTAL_OBJECTIVE = float(
    BLOCK_7_FINAL_EVALUATION[
        "total_objective"
    ]
)


BLOCK_7_FINAL_TOTAL_OBJECTIVE_FINITE = bool(
    math.isfinite(
        BLOCK_7_FINAL_TOTAL_OBJECTIVE
    )
)


if not BLOCK_7_FINAL_TOTAL_OBJECTIVE_FINITE:

    raise RuntimeError(
        "Post-training Social Representation objective is non-finite."
    )


BLOCK_7_OBJECTIVE_REDUCTION = (
    BLOCK_7_INITIAL_TOTAL_OBJECTIVE
    -
    BLOCK_7_FINAL_TOTAL_OBJECTIVE
)


# =============================================================================
# Parameter-change validation
# =============================================================================

BLOCK_7_BACKBONE_UNCHANGED = (
    block_7_module_matches_snapshot(
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE,
        BLOCK_7_BACKBONE_BEFORE,
    )
)


BLOCK_7_GLOBAL_CONFLUENT_UNCHANGED = (
    block_7_module_matches_snapshot(
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE,
        BLOCK_7_GLOBAL_CONFLUENT_BEFORE,
    )
)


BLOCK_7_PSYCHOLOGICAL_UNCHANGED = (
    block_7_module_matches_snapshot(
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE,
        BLOCK_7_PSYCHOLOGICAL_BEFORE,
    )
)


BLOCK_7_FACTUAL_UNCHANGED = (
    block_7_module_matches_snapshot(
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE,
        BLOCK_7_FACTUAL_BEFORE,
    )
)


BLOCK_7_SOCIAL_UNCHANGED = (
    block_7_module_matches_snapshot(
        NOTEBOOK_07_SOCIAL_HEAD,
        BLOCK_7_SOCIAL_BEFORE,
    )
)


BLOCK_7_SOCIAL_PARAMETERS_CHANGED = (
    not BLOCK_7_SOCIAL_UNCHANGED
)


BLOCK_7_SOCIAL_MAXIMUM_PARAMETER_DELTA = (
    block_7_maximum_parameter_delta(
        NOTEBOOK_07_SOCIAL_HEAD,
        BLOCK_7_SOCIAL_BEFORE,
    )
)


BLOCK_7_FROZEN_PARAMETERS_UNCHANGED = all(
    [
        BLOCK_7_BACKBONE_UNCHANGED,
        BLOCK_7_GLOBAL_CONFLUENT_UNCHANGED,
        BLOCK_7_PSYCHOLOGICAL_UNCHANGED,
        BLOCK_7_FACTUAL_UNCHANGED,
    ]
)


BLOCK_7_PARAMETER_UPDATE_SCOPE_VALID = all(
    [
        BLOCK_7_FROZEN_PARAMETERS_UNCHANGED,
        BLOCK_7_SOCIAL_PARAMETERS_CHANGED,
        (
            BLOCK_7_SOCIAL_MAXIMUM_PARAMETER_DELTA
            >
            0.0
        ),
    ]
)


if not BLOCK_7_PARAMETER_UPDATE_SCOPE_VALID:

    raise RuntimeError(
        "Controlled Social Representation training modified an "
        "invalid parameter scope."
    )


# =============================================================================
# Gradient-control validation
# =============================================================================

BLOCK_7_FINITE_GRADIENTS = all(
    [
        not BLOCK_7_NONFINITE_GRADIENT_DETECTED,
        math.isfinite(
            BLOCK_7_MAXIMUM_PRECLIP_GRADIENT_NORM
        ),
    ]
)


BLOCK_7_GRADIENT_CONTROL_VALID = all(
    [
        BLOCK_7_FINITE_GRADIENTS,
        not BLOCK_7_NONFINITE_LOSS_DETECTED,
        (
            NOTEBOOK_07_SOCIAL_MAXIMUM_GRADIENT_NORM
            >
            0.0
        ),
    ]
)


if not BLOCK_7_GRADIENT_CONTROL_VALID:

    raise RuntimeError(
        "Controlled Social Representation gradient policy failed."
    )


# =============================================================================
# Checkpoint contract
# =============================================================================

NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE = (
    "controlled_experimental_social_representation_training_checkpoint"
)


NOTEBOOK_07_SOCIAL_CHECKPOINT_VERSION = "1.0"


NOTEBOOK_07_SOCIAL_CHECKPOINT_FILENAME = (
    "notebook_07_controlled_social_training_checkpoint.pt"
)


NOTEBOOK_07_SOCIAL_METADATA_FILENAME = (
    "notebook_07_controlled_social_training_metadata.json"
)


NOTEBOOK_07_SOCIAL_VALIDATED_MODEL_CHECKPOINT = False


# =============================================================================
# Checkpoint payload
# =============================================================================

NOTEBOOK_07_SOCIAL_CHECKPOINT = {
    "checkpoint_type":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE,

    "checkpoint_version":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_VERSION,

    "created_at_utc":
        BLOCK_7_EXECUTED_AT_UTC,

    "notebook":
        7,

    "block":
        7,

    "random_seed":
        42,

    "training_policy_version":
        NOTEBOOK_07_SOCIAL_TRAINING_POLICY_VERSION,

    "training_epoch_count":
        NOTEBOOK_07_SOCIAL_TRAINING_EPOCHS,

    "within_article_shuffle":
        NOTEBOOK_07_SOCIAL_WITHIN_ARTICLE_SHUFFLE,

    "article_sequence_preserved":
        NOTEBOOK_07_SOCIAL_ARTICLE_SEQUENCE_PRESERVED,

    "training_article_count":
        BLOCK_7_TRAINING_ARTICLE_COUNT,

    "training_sentence_count":
        BLOCK_7_TRAINING_SENTENCE_COUNT,

    "validation_sentence_count":
        BLOCK_7_VALIDATION_SENTENCE_COUNT,

    "test_sentence_count":
        BLOCK_7_TEST_SENTENCE_COUNT,

    "active_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),

    "active_indices":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

    "deferred_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        ),

    "deferred_indices":
        list(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),

    "objective_weights":
        deepcopy(
            NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS
        ),

    "loss_family":
        deepcopy(
            NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES
        ),

    "optimizer_type":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE,

    "learning_rate":
        NOTEBOOK_07_SOCIAL_LEARNING_RATE,

    "weight_decay":
        NOTEBOOK_07_SOCIAL_WEIGHT_DECAY,

    "maximum_gradient_norm":
        NOTEBOOK_07_SOCIAL_MAXIMUM_GRADIENT_NORM,

    "initial_objective":
        BLOCK_7_INITIAL_TOTAL_OBJECTIVE,

    "final_objective":
        BLOCK_7_FINAL_TOTAL_OBJECTIVE,

    "objective_reduction":
        BLOCK_7_OBJECTIVE_REDUCTION,

    "initial_family_losses":
        deepcopy(
            BLOCK_7_INITIAL_FAMILY_LOSSES
        ),

    "final_family_losses":
        deepcopy(
            BLOCK_7_FINAL_FAMILY_LOSSES
        ),

    "maximum_preclip_gradient_norm":
        BLOCK_7_MAXIMUM_PRECLIP_GRADIENT_NORM,

    "maximum_parameter_delta":
        BLOCK_7_SOCIAL_MAXIMUM_PARAMETER_DELTA,

    "training_history":
        deepcopy(
            BLOCK_7_SOCIAL_TRAINING_HISTORY
        ),

    "contextual_representation_drive_file_id":
        BLOCK_5_REPRESENTATION_DRIVE_FILE_ID,

    "backbone_state_dict":
        deepcopy(
            NOTEBOOK_07_BACKBONE_FROZEN_MODULE.state_dict()
        ),

    "global_confluent_state_dict":
        deepcopy(
            NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE.state_dict()
        ),

    "psychological_head_state_dict":
        deepcopy(
            NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE.state_dict()
        ),

    "factual_head_state_dict":
        deepcopy(
            NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE.state_dict()
        ),

    "social_head_state_dict":
        deepcopy(
            NOTEBOOK_07_SOCIAL_HEAD.state_dict()
        ),

    "optimizer_state_dict":
        deepcopy(
            NOTEBOOK_07_SOCIAL_OPTIMIZER.state_dict()
        ),

    "methodological_boundary":
        {
            "backbone_trained":
                False,

            "global_confluent_trained":
                False,

            "psychological_representation_trained":
                False,

            "factual_representation_trained":
                False,

            "social_representation_trained":
                True,

            "group_conditioned_path_executed":
                False,

            "transformative_mechanism_executed":
                False,

            "transformative_weights_active":
                False,

            "recurrent_mechanism_executed":
                False,

            "held_out_evaluation_executed":
                False,

            "validated_model_checkpoint":
                False,

            "empirical_validity":
                False,
        },
}


# =============================================================================
# Metadata payload
# =============================================================================

NOTEBOOK_07_SOCIAL_TRAINING_METADATA = {
    "metadata_type":
        "media_ai_controlled_social_representation_training_metadata",

    "metadata_version":
        "1.0",

    "created_at_utc":
        BLOCK_7_EXECUTED_AT_UTC,

    "checkpoint_type":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE,

    "checkpoint_filename":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_FILENAME,

    "validated_model_checkpoint":
        False,

    "training_policy":
        {
            "epochs":
                NOTEBOOK_07_SOCIAL_TRAINING_EPOCHS,

            "training_articles":
                BLOCK_7_TRAINING_ARTICLE_COUNT,

            "training_sentences":
                BLOCK_7_TRAINING_SENTENCE_COUNT,

            "validation_sentences":
                BLOCK_7_VALIDATION_SENTENCE_COUNT,

            "test_sentences":
                BLOCK_7_TEST_SENTENCE_COUNT,

            "within_article_shuffle":
                False,

            "article_sequence_preserved":
                True,

            "maximum_gradient_norm":
                NOTEBOOK_07_SOCIAL_MAXIMUM_GRADIENT_NORM,
        },

    "objective_contract":
        {
            "active_dimensions":
                list(
                    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
                ),

            "deferred_dimensions":
                list(
                    NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
                ),

            "objective_weights":
                deepcopy(
                    NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS
                ),

            "loss_family":
                deepcopy(
                    NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES
                ),

            "mask_aware":
                True,
        },

    "optimizer":
        {
            "type":
                NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE,

            "learning_rate":
                NOTEBOOK_07_SOCIAL_LEARNING_RATE,

            "weight_decay":
                NOTEBOOK_07_SOCIAL_WEIGHT_DECAY,

            "parameter_count":
                BLOCK_7_OPTIMIZER_PARAMETER_COUNT,
        },

    "training_result":
        {
            "initial_objective":
                BLOCK_7_INITIAL_TOTAL_OBJECTIVE,

            "final_objective":
                BLOCK_7_FINAL_TOTAL_OBJECTIVE,

            "objective_reduction":
                BLOCK_7_OBJECTIVE_REDUCTION,

            "initial_family_losses":
                deepcopy(
                    BLOCK_7_INITIAL_FAMILY_LOSSES
                ),

            "final_family_losses":
                deepcopy(
                    BLOCK_7_FINAL_FAMILY_LOSSES
                ),

            "maximum_preclip_gradient_norm":
                BLOCK_7_MAXIMUM_PRECLIP_GRADIENT_NORM,

            "maximum_parameter_delta":
                BLOCK_7_SOCIAL_MAXIMUM_PARAMETER_DELTA,
        },

    "methodological_boundary":
        deepcopy(
            NOTEBOOK_07_SOCIAL_CHECKPOINT[
                "methodological_boundary"
            ]
        ),
}


# =============================================================================
# Local checkpoint persistence
# =============================================================================

torch.save(
    NOTEBOOK_07_SOCIAL_CHECKPOINT,
    NOTEBOOK_07_SOCIAL_CHECKPOINT_FILENAME,
)


BLOCK_7_LOCAL_CHECKPOINT_CREATED = True


with open(
    NOTEBOOK_07_SOCIAL_METADATA_FILENAME,
    "w",
    encoding="utf-8",
) as metadata_file:

    json.dump(
        NOTEBOOK_07_SOCIAL_TRAINING_METADATA,
        metadata_file,
        indent=2,
        ensure_ascii=False,
    )


BLOCK_7_LOCAL_METADATA_CREATED = True


# =============================================================================
# Resolve persistent Drive parent
# =============================================================================

BLOCK_7_REFERENCE_DRIVE_METADATA = (
    NOTEBOOK_07_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_07_FACTUAL_CHECKPOINT_DRIVE_FILE_ID,
        fields=
            "id,name,parents",
    )
    .execute()
)


BLOCK_7_PARENT_IDS = (
    BLOCK_7_REFERENCE_DRIVE_METADATA.get(
        "parents",
        [],
    )
)


# =============================================================================
# Drive persistence helper
# =============================================================================

def block_7_persist_bytes_to_drive(
    drive_service,
    filename,
    raw_bytes,
    mimetype,
    parent_ids=None,
):

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )


    search_response = (
        drive_service.files()
        .list(
            q=(
                f"name = '{escaped_filename}' "
                "and trashed = false"
            ),
            spaces="drive",
            fields=
                "files(id,name,modifiedTime,parents)",
            orderBy=
                "modifiedTime desc",
            pageSize=20,
        )
        .execute()
    )


    matching_files = search_response.get(
        "files",
        [],
    )


    media = MediaIoBaseUpload(
        io.BytesIO(
            raw_bytes
        ),
        mimetype=
            mimetype,
        resumable=
            False,
    )


    if matching_files:

        drive_file = (
            drive_service.files()
            .update(
                fileId=
                    matching_files[
                        0
                    ][
                        "id"
                    ],
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "updated"


    else:

        metadata = {
            "name":
                filename
        }


        if parent_ids:

            metadata[
                "parents"
            ] = parent_ids


        drive_file = (
            drive_service.files()
            .create(
                body=
                    metadata,
                media_body=
                    media,
                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "created"


    return (
        drive_file,
        operation,
    )


# =============================================================================
# Serialise checkpoint to bytes
# =============================================================================

BLOCK_7_CHECKPOINT_BUFFER = io.BytesIO()


torch.save(
    NOTEBOOK_07_SOCIAL_CHECKPOINT,
    BLOCK_7_CHECKPOINT_BUFFER,
)


BLOCK_7_CHECKPOINT_BYTES = (
    BLOCK_7_CHECKPOINT_BUFFER.getvalue()
)


BLOCK_7_METADATA_JSON = json.dumps(
    NOTEBOOK_07_SOCIAL_TRAINING_METADATA,
    indent=2,
    ensure_ascii=False,
)


BLOCK_7_METADATA_BYTES = (
    BLOCK_7_METADATA_JSON.encode(
        "utf-8"
    )
)


# =============================================================================
# Persist checkpoint to Drive
# =============================================================================

(
    NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE,
    NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_OPERATION,
) = block_7_persist_bytes_to_drive(
    drive_service=
        NOTEBOOK_07_DRIVE_SERVICE,

    filename=
        NOTEBOOK_07_SOCIAL_CHECKPOINT_FILENAME,

    raw_bytes=
        BLOCK_7_CHECKPOINT_BYTES,

    mimetype=
        "application/octet-stream",

    parent_ids=
        BLOCK_7_PARENT_IDS,
)


NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID = (
    NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE.get(
        "id"
    )
)


# =============================================================================
# Persist metadata to Drive
# =============================================================================

(
    NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE,
    NOTEBOOK_07_SOCIAL_METADATA_DRIVE_OPERATION,
) = block_7_persist_bytes_to_drive(
    drive_service=
        NOTEBOOK_07_DRIVE_SERVICE,

    filename=
        NOTEBOOK_07_SOCIAL_METADATA_FILENAME,

    raw_bytes=
        BLOCK_7_METADATA_BYTES,

    mimetype=
        "application/json",

    parent_ids=
        BLOCK_7_PARENT_IDS,
)


NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID = (
    NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE.get(
        "id"
    )
)


NOTEBOOK_07_SOCIAL_CHECKPOINT_CREATED = bool(
    NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID
)


# =============================================================================
# Checkpoint read-back validation
# =============================================================================

BLOCK_7_RELOADED_CHECKPOINT_BYTES = (
    block_5_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID,
    )
)


BLOCK_7_RELOADED_CHECKPOINT = torch.load(
    io.BytesIO(
        BLOCK_7_RELOADED_CHECKPOINT_BYTES
    ),
    map_location=
        "cpu",
    weights_only=
        False,
)


BLOCK_7_RELOADED_METADATA_BYTES = (
    block_5_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID,
    )
)


BLOCK_7_RELOADED_METADATA = json.loads(
    BLOCK_7_RELOADED_METADATA_BYTES.decode(
        "utf-8"
    )
)


# =============================================================================
# Checkpoint read-back contract
# =============================================================================

BLOCK_7_CHECKPOINT_READBACK_TYPE_VALID = (
    BLOCK_7_RELOADED_CHECKPOINT.get(
        "checkpoint_type"
    )
    ==
    NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE
)


BLOCK_7_CHECKPOINT_READBACK_VERSION_VALID = (
    BLOCK_7_RELOADED_CHECKPOINT.get(
        "checkpoint_version"
    )
    ==
    NOTEBOOK_07_SOCIAL_CHECKPOINT_VERSION
)


BLOCK_7_CHECKPOINT_READBACK_ACTIVE_DIMENSIONS_VALID = (
    BLOCK_7_RELOADED_CHECKPOINT.get(
        "active_dimensions"
    )
    ==
    list(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


BLOCK_7_CHECKPOINT_READBACK_SOCIAL_STATE_PRESENT = (
    isinstance(
        BLOCK_7_RELOADED_CHECKPOINT.get(
            "social_head_state_dict"
        ),
        dict,
    )
)


BLOCK_7_CHECKPOINT_READBACK_VALIDATED_MODEL_FALSE = (
    BLOCK_7_RELOADED_CHECKPOINT[
        "methodological_boundary"
    ][
        "validated_model_checkpoint"
    ]
    is False
)


NOTEBOOK_07_SOCIAL_CHECKPOINT_READBACK_VALID = all(
    [
        BLOCK_7_CHECKPOINT_READBACK_TYPE_VALID,
        BLOCK_7_CHECKPOINT_READBACK_VERSION_VALID,
        BLOCK_7_CHECKPOINT_READBACK_ACTIVE_DIMENSIONS_VALID,
        BLOCK_7_CHECKPOINT_READBACK_SOCIAL_STATE_PRESENT,
        BLOCK_7_CHECKPOINT_READBACK_VALIDATED_MODEL_FALSE,
    ]
)


# =============================================================================
# Metadata read-back contract
# =============================================================================

NOTEBOOK_07_SOCIAL_METADATA_READBACK_VALID = all(
    [
        (
            BLOCK_7_RELOADED_METADATA.get(
                "metadata_type"
            )
            ==
            "media_ai_controlled_social_representation_training_metadata"
        ),

        (
            BLOCK_7_RELOADED_METADATA.get(
                "checkpoint_type"
            )
            ==
            NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE
        ),

        (
            BLOCK_7_RELOADED_METADATA.get(
                "validated_model_checkpoint"
            )
            is False
        ),

        (
            BLOCK_7_RELOADED_METADATA[
                "optimizer"
            ][
                "parameter_count"
            ]
            ==
            BLOCK_7_SOCIAL_TRAINABLE_PARAMETER_COUNT
        ),
    ]
)


if not all(
    [
        NOTEBOOK_07_SOCIAL_CHECKPOINT_READBACK_VALID,
        NOTEBOOK_07_SOCIAL_METADATA_READBACK_VALID,
    ]
):

    raise RuntimeError(
        "Persisted Block 7 Social Representation checkpoint or "
        "metadata failed read-back validation."
    )


# =============================================================================
# Training-state finalisation
# =============================================================================

NOTEBOOK_07_SOCIAL_OPTIMISATION_READY = True

NOTEBOOK_07_SOCIAL_TRAINING_COMPLETE = True

NOTEBOOK_07_SOCIAL_CHECKPOINT_REPRODUCIBILITY_READY = True


# =============================================================================
# Final validation
# =============================================================================

NOTEBOOK_07_BLOCK_7_ERRORS = []


block_7_validation_checks = {
    "active_dimensions_invalid":
        BLOCK_7_ACTIVE_DIMENSIONS_VALID,

    "deferred_dimensions_invalid":
        BLOCK_7_DEFERRED_DIMENSIONS_VALID,

    "objective_partition_invalid":
        BLOCK_7_OBJECTIVE_PARTITION_VALID,

    "loss_family_keys_invalid":
        BLOCK_7_LOSS_FAMILY_KEYS_VALID,

    "training_scope_invalid":
        BLOCK_7_TRAINING_SCOPE_VALID,

    "objective_weights_invalid":
        BLOCK_7_OBJECTIVE_WEIGHTS_VALID,

    "target_shape_invalid":
        BLOCK_7_TARGET_SHAPE_VALID,

    "mask_shape_invalid":
        BLOCK_7_MASK_SHAPE_VALID,

    "observed_targets_nonfinite":
        BLOCK_7_OBSERVED_TARGETS_FINITE,

    "contextual_shape_invalid":
        BLOCK_7_CONTEXTUAL_SHAPE_VALID,

    "contextual_values_nonfinite":
        BLOCK_7_CONTEXTUAL_VALUES_FINITE,

    "parameter_scope_invalid":
        BLOCK_7_PARAMETER_SCOPE_VALID,

    "optimizer_scope_invalid":
        BLOCK_7_OPTIMIZER_SCOPE_VALID,

    "initial_objective_nonfinite":
        BLOCK_7_INITIAL_TOTAL_OBJECTIVE_FINITE,

    "final_objective_nonfinite":
        BLOCK_7_FINAL_TOTAL_OBJECTIVE_FINITE,

    "gradient_control_invalid":
        BLOCK_7_GRADIENT_CONTROL_VALID,

    "frozen_parameters_changed":
        BLOCK_7_FROZEN_PARAMETERS_UNCHANGED,

    "social_parameters_unchanged":
        BLOCK_7_SOCIAL_PARAMETERS_CHANGED,

    "parameter_update_scope_invalid":
        BLOCK_7_PARAMETER_UPDATE_SCOPE_VALID,

    "checkpoint_not_created":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_CREATED,

    "checkpoint_readback_invalid":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_READBACK_VALID,

    "metadata_readback_invalid":
        NOTEBOOK_07_SOCIAL_METADATA_READBACK_VALID,
}


for (
    error_name,
    condition,
) in block_7_validation_checks.items():

    if not condition:

        NOTEBOOK_07_BLOCK_7_ERRORS.append(
            error_name
        )


# =============================================================================
# Methodological-boundary validation
# =============================================================================

prohibited_block_7_operations = {
    "psychological_training_incorrectly_executed":
        NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "factual_training_incorrectly_executed":
        NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED,

    "backbone_training_incorrectly_executed":
        NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED,

    "global_confluent_training_incorrectly_executed":
        NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED,

    "group_conditioned_incorrectly_executed":
        NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED,

    "transformative_weights_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED,

    "recurrent_incorrectly_executed":
        NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for (
    error_name,
    operation_executed,
) in prohibited_block_7_operations.items():

    if operation_executed:

        NOTEBOOK_07_BLOCK_7_ERRORS.append(
            error_name
        )


# =============================================================================
# Required training operations
# =============================================================================

required_block_7_operations = {
    "zero_grad_not_executed":
        NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED,

    "backward_pass_not_executed":
        NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED,

    "optimizer_step_not_executed":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED,

    "parameter_update_not_executed":
        NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED,

    "social_training_not_executed":
        NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED,
}


for (
    error_name,
    operation_executed,
) in required_block_7_operations.items():

    if not operation_executed:

        NOTEBOOK_07_BLOCK_7_ERRORS.append(
            error_name
        )


# =============================================================================
# Final Block 7 state
# =============================================================================

NOTEBOOK_07_BLOCK_7_VALID = (
    len(
        NOTEBOOK_07_BLOCK_7_ERRORS
    )
    == 0
)


if not NOTEBOOK_07_BLOCK_7_VALID:

    raise RuntimeError(
        "Notebook 07 Block 7 controlled Social Representation "
        "training validation failed. "
        f"Errors: {NOTEBOOK_07_BLOCK_7_ERRORS}"
    )


NOTEBOOK_07_BLOCK_7_COMPLETE = True


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_07_BLOCK_7_SUMMARY = {
    "block":
        NOTEBOOK_07_BLOCK_7,

    "block_name":
        NOTEBOOK_07_BLOCK_7_NAME,

    "version":
        NOTEBOOK_07_BLOCK_7_VERSION,

    "executed_at_utc":
        BLOCK_7_EXECUTED_AT_UTC,

    "training_articles":
        BLOCK_7_TRAINING_ARTICLE_COUNT,

    "training_sentences":
        BLOCK_7_TRAINING_SENTENCE_COUNT,

    "validation_sentences":
        BLOCK_7_VALIDATION_SENTENCE_COUNT,

    "test_sentences":
        BLOCK_7_TEST_SENTENCE_COUNT,

    "epochs":
        NOTEBOOK_07_SOCIAL_TRAINING_EPOCHS,

    "within_article_shuffle":
        NOTEBOOK_07_SOCIAL_WITHIN_ARTICLE_SHUFFLE,

    "article_sequence_preserved":
        NOTEBOOK_07_SOCIAL_ARTICLE_SEQUENCE_PRESERVED,

    "active_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),

    "objective_weights":
        deepcopy(
            NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS
        ),

    "optimizer_type":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE,

    "learning_rate":
        NOTEBOOK_07_SOCIAL_LEARNING_RATE,

    "weight_decay":
        NOTEBOOK_07_SOCIAL_WEIGHT_DECAY,

    "maximum_gradient_norm":
        NOTEBOOK_07_SOCIAL_MAXIMUM_GRADIENT_NORM,

    "maximum_preclip_gradient_norm":
        BLOCK_7_MAXIMUM_PRECLIP_GRADIENT_NORM,

    "initial_objective":
        BLOCK_7_INITIAL_TOTAL_OBJECTIVE,

    "final_objective":
        BLOCK_7_FINAL_TOTAL_OBJECTIVE,

    "objective_reduction":
        BLOCK_7_OBJECTIVE_REDUCTION,

    "maximum_parameter_delta":
        BLOCK_7_SOCIAL_MAXIMUM_PARAMETER_DELTA,

    "social_trainable_parameters":
        BLOCK_7_SOCIAL_TRAINABLE_PARAMETER_COUNT,

    "frozen_parameters_unchanged":
        BLOCK_7_FROZEN_PARAMETERS_UNCHANGED,

    "social_parameters_changed":
        BLOCK_7_SOCIAL_PARAMETERS_CHANGED,

    "checkpoint_type":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE,

    "checkpoint_filename":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_FILENAME,

    "checkpoint_drive_file_id":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID,

    "metadata_filename":
        NOTEBOOK_07_SOCIAL_METADATA_FILENAME,

    "metadata_drive_file_id":
        NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID,

    "checkpoint_readback_valid":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_READBACK_VALID,

    "metadata_readback_valid":
        NOTEBOOK_07_SOCIAL_METADATA_READBACK_VALID,

    "validated_model_checkpoint":
        NOTEBOOK_07_SOCIAL_VALIDATED_MODEL_CHECKPOINT,

    "empirical_validity":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_07_BLOCK_7_VALID,

    "block_complete":
        NOTEBOOK_07_BLOCK_7_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 07, Block 7: "
    "Controlled Social Representation Training and Checkpoint Policy"
)

print("=" * 72)

print(
    f"Block version                : "
    f"{NOTEBOOK_07_BLOCK_7_VERSION}"
)

print(
    f"Training policy version      : "
    f"{NOTEBOOK_07_SOCIAL_TRAINING_POLICY_VERSION}"
)


print("-" * 72)

print(
    "Training scope"
)

print(
    f"Training articles            : "
    f"{BLOCK_7_TRAINING_ARTICLE_COUNT}"
)

print(
    f"Training sentences           : "
    f"{BLOCK_7_TRAINING_SENTENCE_COUNT}"
)

print(
    f"Validation sentences         : "
    f"{BLOCK_7_VALIDATION_SENTENCE_COUNT}"
)

print(
    f"Test sentences               : "
    f"{BLOCK_7_TEST_SENTENCE_COUNT}"
)

print(
    f"Epochs executed              : "
    f"{NOTEBOOK_07_SOCIAL_TRAINING_EPOCHS}"
)

print(
    f"Within-article shuffle       : "
    f"{NOTEBOOK_07_SOCIAL_WITHIN_ARTICLE_SHUFFLE}"
)

print(
    f"Article sequence preserved   : "
    f"{NOTEBOOK_07_SOCIAL_ARTICLE_SEQUENCE_PRESERVED}"
)


print("-" * 72)

print(
    "Supervised Social Representation objectives"
)

print(
    f"Active dimensions            : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)}"
)

print(
    f"Deferred dimensions          : "
    f"{list(NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS)}"
)

print(
    f"Objective weights            : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS}"
)

print(
    f"Loss families                : "
    f"{NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES}"
)

print(
    f"Mask-aware supervision       : "
    f"{True}"
)


print("-" * 72)

print(
    "Optimisation boundary"
)

print(
    f"Only social head             : "
    f"{BLOCK_7_PARAMETER_SCOPE_VALID}"
)

print(
    f"Optimiser scope valid        : "
    f"{BLOCK_7_OPTIMIZER_SCOPE_VALID}"
)

print(
    f"Backbone frozen              : "
    f"{BLOCK_7_BACKBONE_FROZEN}"
)

print(
    f"Global confluent frozen      : "
    f"{BLOCK_7_GLOBAL_CONFLUENT_FROZEN}"
)

print(
    f"Psychological head frozen    : "
    f"{BLOCK_7_PSYCHOLOGICAL_HEAD_FROZEN}"
)

print(
    f"Factual head frozen          : "
    f"{BLOCK_7_FACTUAL_HEAD_FROZEN}"
)

print(
    f"Frozen parameters unchanged  : "
    f"{BLOCK_7_FROZEN_PARAMETERS_UNCHANGED}"
)

print(
    f"Social parameters changed    : "
    f"{BLOCK_7_SOCIAL_PARAMETERS_CHANGED}"
)

print(
    f"Maximum parameter delta      : "
    f"{BLOCK_7_SOCIAL_MAXIMUM_PARAMETER_DELTA:.8f}"
)


print("-" * 72)

print(
    "Gradient control"
)

print(
    f"Maximum gradient norm        : "
    f"{NOTEBOOK_07_SOCIAL_MAXIMUM_GRADIENT_NORM:.4f}"
)

print(
    f"Max observed pre-clip norm   : "
    f"{BLOCK_7_MAXIMUM_PRECLIP_GRADIENT_NORM:.8f}"
)

print(
    f"Finite gradients             : "
    f"{BLOCK_7_FINITE_GRADIENTS}"
)

print(
    f"Non-finite loss detected     : "
    f"{BLOCK_7_NONFINITE_LOSS_DETECTED}"
)


print("-" * 72)

print(
    "Controlled Social Representation training objective"
)

print(
    f"Block 6 objective reference  : "
    f"{BLOCK_7_BLOCK_6_OBJECTIVE_REFERENCE}"
)

print(
    f"Block 6 objective reproduced : "
    f"{BLOCK_7_BLOCK_6_OBJECTIVE_REPRODUCED}"
)

print(
    f"Initial total objective      : "
    f"{BLOCK_7_INITIAL_TOTAL_OBJECTIVE:.8f}"
)

print(
    f"Final total objective        : "
    f"{BLOCK_7_FINAL_TOTAL_OBJECTIVE:.8f}"
)

print(
    f"Objective reduction          : "
    f"{BLOCK_7_OBJECTIVE_REDUCTION:.8f}"
)


for dimension_name in (
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
):

    print(
        f"{dimension_name:<31}: "
        f"{BLOCK_7_INITIAL_FAMILY_LOSSES[dimension_name]:.8f}"
        f" / "
        f"{BLOCK_7_FINAL_FAMILY_LOSSES[dimension_name]:.8f}"
    )


print("-" * 72)

print(
    "Checkpoint policy"
)

print(
    f"Checkpoint type              : "
    f"{NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE}"
)

print(
    f"Checkpoint filename          : "
    f"{NOTEBOOK_07_SOCIAL_CHECKPOINT_FILENAME}"
)

print(
    f"Local checkpoint created     : "
    f"{BLOCK_7_LOCAL_CHECKPOINT_CREATED}"
)

print(
    f"Checkpoint Drive operation   : "
    f"{NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_OPERATION}"
)

print(
    f"Checkpoint Drive file ID     : "
    f"{NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID}"
)

print(
    f"Metadata Drive operation     : "
    f"{NOTEBOOK_07_SOCIAL_METADATA_DRIVE_OPERATION}"
)

print(
    f"Metadata Drive file ID       : "
    f"{NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID}"
)

print(
    f"Checkpoint read-back valid   : "
    f"{NOTEBOOK_07_SOCIAL_CHECKPOINT_READBACK_VALID}"
)

print(
    f"Metadata read-back valid     : "
    f"{NOTEBOOK_07_SOCIAL_METADATA_READBACK_VALID}"
)

print(
    f"Validated model checkpoint   : "
    f"{NOTEBOOK_07_SOCIAL_VALIDATED_MODEL_CHECKPOINT}"
)


print("-" * 72)

print(
    "Execution state"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Social training executed     : "
    f"{NOTEBOOK_07_SOCIAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Factual retraining           : "
    f"{NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative activated     : "
    f"{NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED}"
)

print(
    f"Transformative weights active: "
    f"{NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED}"
)

print(
    f"Recurrent states activated   : "
    f"{NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED}"
)

print(
    f"Held-out evaluation executed : "
    f"{NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_07_BLOCK_7_VALID}"
)

print(
    f"Block 7 complete             : "
    f"{NOTEBOOK_07_BLOCK_7_COMPLETE}"
)


print("=" * 72)


print(
    "Controlled Social Representation training completed successfully."
)

print(
    "Only the Social Representation head was updated."
)

print(
    f"{len(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)} active Social "
    "Representation dimension(s) remained separate mask-aware objectives "
    "throughout controlled training using the loss families inherited from "
    "the validated Block 4/6 contract."
)

print(
    f"{len(NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS)} deferred Social "
    "Representation dimension(s) remained structurally present but outside "
    "the current optimisation objective."
)

print(
    "The backbone, mandatory global confluent representation, "
    "Psychological Representation and Factual Representation remained "
    "frozen and unchanged."
)

print(
    "The optional group-conditioned path remained inactive."
)

print(
    "No Transformative Mechanism, Transformative Weight or recurrent "
    "component was trained or executed."
)

print(
    "Gradient finiteness, clipping and frozen-parameter invariance "
    "were validated explicitly."
)

print(
    "The resulting checkpoint is a controlled experimental Social "
    "Representation training checkpoint and is not a validated model "
    "checkpoint."
)

print(
    "No validation-based early stopping was used because the current "
    "controlled training policy assigns no held-out validation sentences."
)

print(
    "Training-objective behaviour is a computational diagnostic and "
    "does not demonstrate generalisation or empirical validity."
)

print(
    "No held-out evaluation or empirical-validity claim has been performed."
)

print(
    "Block 8 may proceed to Social Representation checkpoint reload, "
    "reproducibility and training-state validation."
)

print("=" * 72)

WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.
WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.

========================================================================
Media AI — Notebook 07, Block 7: Controlled Social Representation Training and Checkpoint Policy
========================================================================
Block version                : 1.1
Training policy version      : 1.1
------------------------------------------------------------------------
Training scope
Training articles            : 3
Training sentences           : 54
Validation sentences         : 0
Test sentences               : 0
Epochs executed              : 10
Within-article shuffle       : False
Article sequence preserved   : True
------------------------------------------------------------------------
Supervised Social Representation objectives
Active dimensions            : ['interpersonal_cohesion', 'economic_cohesion', 'political_cohesion', 'group_collective_cohesion']
Deferred dimensions          : ['religious_cohesion', 'institutional_role_relation', 'public_audience_relation']
Objective weights            : {'interpersonal_cohesion': 0.25, 'economic_cohesion': 0.25, 'political_cohesion': 0.25, 'group_collective_cohesion': 0.25}
Loss families                : {'interpersonal_cohesion': 'masked_mean_squared_error', 'economic_cohesion': 'masked_mean_squared_error', 'political_cohesion': 'masked_mean_squared_error', 'group_collective_cohesion': 'masked_mean_squared_error'}
Mask-aware supervision       : True
------------------------------------------------------------------------
Optimisation boundary
Only social head             : True
Optimiser scope valid        : True
Backbone frozen              : True
Global confluent frozen      : True
Psychological head frozen    : True
Factual head frozen          : True
Frozen parameters unchanged  : True
Social parameters changed    : True
Maximum parameter delta      : 0.00984398
------------------------------------------------------------------------
Gradient control
Maximum gradient norm        : 1.0000
Max observed pre-clip norm   : 7.01310616
Finite gradients             : True
Non-finite loss detected     : False
------------------------------------------------------------------------
Controlled Social Representation training objective
Block 6 objective reference  : 0.5893603563308716
Block 6 objective reproduced : True
Initial total objective      : 0.58936036
Final total objective        : 0.01394366
Objective reduction          : 0.57541670
interpersonal_cohesion         : 0.59975111 / 0.01065167
economic_cohesion              : 0.15738152 / 0.01577149
political_cohesion             : 1.00055444 / 0.01012826
group_collective_cohesion      : 0.59975421 / 0.01922321
------------------------------------------------------------------------
Checkpoint policy
Checkpoint type              : controlled_experimental_social_representation_training_checkpoint
Checkpoint filename          : notebook_07_controlled_social_training_checkpoint.pt
Local checkpoint created     : True
Checkpoint Drive operation   : updated
Checkpoint Drive file ID     : 1InCGr7QeNcd3RtrZ1aLIyKYvX0cOZNLU
Metadata Drive operation     : updated
Metadata Drive file ID       : 1CiBJnkFFjEEgB2nqWew6Ilp6O5eOC86k
Checkpoint read-back valid   : True
Metadata read-back valid     : True
Validated model checkpoint   : False
------------------------------------------------------------------------
Execution state
Zero grad executed           : True
Backward pass executed       : True
Optimiser step executed      : True
Parameter update executed    : True
Social training executed     : True
Psychological retraining     : False
Factual retraining           : False
Group-conditioned executed   : False
Transformative activated     : False
Transformative weights active: False
Recurrent states activated   : False
Held-out evaluation executed : False
Empirical validity           : False
Block valid                  : True
Block 7 complete             : True
========================================================================
Controlled Social Representation training completed successfully.
Only the Social Representation head was updated.
4 active Social Representation dimension(s) remained separate mask-aware objectives throughout controlled training using the loss families inherited from the validated Block 4/6 contract.
3 deferred Social Representation dimension(s) remained structurally present but outside the current optimisation objective.
The backbone, mandatory global confluent representation, Psychological Representation and Factual Representation remained frozen and unchanged.
The optional group-conditioned path remained inactive.
No Transformative Mechanism, Transformative Weight or recurrent component was trained or executed.
Gradient finiteness, clipping and frozen-parameter invariance were validated explicitly.
The resulting checkpoint is a controlled experimental Social Representation training checkpoint and is not a validated model checkpoint.
No validation-based early stopping was used because the current controlled training policy assigns no held-out validation sentences.
Training-objective behaviour is a computational diagnostic and does not demonstrate generalisation or empirical validity.
No held-out evaluation or empirical-validity claim has been performed.
Block 8 may proceed to Social Representation checkpoint reload, reproducibility and training-state validation.
========================================================================

## Block 8 — Social Representation Scope Audit, Persistent Handover and Notebook 07 Completion

This block performs the final methodological, architectural and persistence audit for **Notebook 07 — Social Representation** and prepares the validated Notebook 07 state for independent restoration by Notebook 08.

The block does not introduce a new Social Representation objective, perform additional optimisation or extend the current supervision. Its purpose is to verify that the work completed in Blocks 1–7 remains internally consistent, reproducible and confined to the declared controlled experimental scope.

The audit confirms that the seven-dimensional Social Representation remains structurally intact:

- **S1 — interpersonal cohesion**
- **S2 — economic cohesion**
- **S3 — political cohesion**
- **S4 — religious cohesion**
- **S5 — group/collective cohesion**
- **S6 — institutional-role relation**
- **S7 — public/audience relation**

The block preserves the distinction between dimensions that were eligible for the current controlled objective and dimensions that remained deferred because of insufficient supervision, unavailable supervision or zero target variance. Deferred dimensions remain valid parts of the Social Representation and must not be interpreted as removed, negative or structurally absent.

The block verifies the final Social Representation state produced by the preceding blocks, including the accepted supervision contract, activation and loss policy, model architecture, parameter-freezing boundary, controlled optimisation state and any persisted Social Representation checkpoint and metadata established by Blocks 6–7.

The inherited architecture remains unchanged. The contextual sentence representation and backbone remain fixed, the mandatory global confluent representation remains operational and frozen, and the completed Psychological Representation and Factual Representation remain frozen. Only the Social Representation state produced within Notebook 07 belongs to the Notebook 07 optimisation boundary.

The optional group-conditioned path remains architecturally available but outside the Notebook 07 execution boundary and remains deferred to **Notebook 10**. The **Transformative Mechanism** remains reserved for Notebook 08, while **Transformative Weights** and the **recurrent mechanism** remain reserved for Notebook 09.

No additional forward pass, supervised loss calculation, optimiser creation, zero-gradient operation, backward pass, optimiser step, parameter update or training should be performed by this completion block. No psychological or factual retraining is permitted.

The block must also preserve the distinction between controlled experimental completion and empirical validation. Completion of Notebook 07 does not establish full training coverage, held-out performance, generalisation or empirical validity. Any Social Representation checkpoint produced by the notebook remains a controlled experimental checkpoint unless a later evaluation stage explicitly establishes a stronger status.

After the final audit, the block creates a persistent **Notebook 07 → Notebook 08 handover** containing the information required to restore the completed Social Representation independently in a fresh runtime. The handover should reference, rather than silently reconstruct, the authoritative inherited and Notebook 07 artefacts needed by the next notebook.

The persisted handover must be read back and validated before Notebook 07 is declared complete.

Successful completion of this block establishes that:

- Blocks 1–7 are complete and valid.
- The seven-dimensional Social Representation contract remains intact.
- Active and deferred dimensions retain their validated methodological status.
- The completed Social Representation state is reproducible from persisted artefacts.
- The backbone and mandatory global confluent representation remain frozen.
- The Psychological Representation and Factual Representation remain frozen.
- No unrelated representation or mechanism has been retrained or activated.
- The optional group-conditioned path remains deferred to Notebook 10.
- No claim of held-out generalisation or empirical validity is introduced.
- A validated persistent Notebook 07 → Notebook 08 handover has been created.
- Notebook 08 can initialise independently from the persisted handover.
- Notebook 07 is complete within its controlled experimental scope.
- The full Media AI Version 1 project remains incomplete.

The next notebook may therefore proceed to **Notebook 08 — Transformative Mechanism**, using the persisted Notebook 07 handover as its authoritative starting contract while keeping the completed Psychological, Factual and Social Representations frozen by default.

In [24]:
# =============================================================================
# Media AI — Notebook 07
# Block 8: Social Representation Checkpoint Reload,
#          Reproducibility and Training-State Validation
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json
import math

import numpy as np
import torch
import torch.nn.functional as F


# =============================================================================
# Dependency checks
# =============================================================================

required_block_8_objects = [
    "NOTEBOOK_07_BLOCK_1_COMPLETE",
    "NOTEBOOK_07_BLOCK_1_VALID",
    "NOTEBOOK_07_BLOCK_2_COMPLETE",
    "NOTEBOOK_07_BLOCK_2_VALID",
    "NOTEBOOK_07_BLOCK_3_COMPLETE",
    "NOTEBOOK_07_BLOCK_3_VALID",
    "NOTEBOOK_07_BLOCK_4_COMPLETE",
    "NOTEBOOK_07_BLOCK_4_VALID",
    "NOTEBOOK_07_BLOCK_5_COMPLETE",
    "NOTEBOOK_07_BLOCK_5_VALID",
    "NOTEBOOK_07_BLOCK_6_COMPLETE",
    "NOTEBOOK_07_BLOCK_6_VALID",
    "NOTEBOOK_07_BLOCK_7_COMPLETE",
    "NOTEBOOK_07_BLOCK_7_VALID",

    "NOTEBOOK_07_DRIVE_SERVICE",

    "NOTEBOOK_07_SENTENCE_IDS",
    "NOTEBOOK_07_SENTENCE_COUNT",
    "NOTEBOOK_07_ARTICLE_COUNT",

    "NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_SOCIAL_DIMENSION_ORDER",
    "NOTEBOOK_07_SOCIAL_DIMENSION_IDS",

    "NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_BACKBONE_INTERFACE_DIM",
    "NOTEBOOK_07_GLOBAL_CONFLUENT_DIM",
    "NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM",
    "NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_GLOBAL_CONFLUENT_DROPOUT",
    "NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT",

    "NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_ACTIVE_INDICES",
    "NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_DEFERRED_INDICES",

    "NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS",
    "NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES",
    "NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID",

    "NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE",
    "NOTEBOOK_07_SOCIAL_CHECKPOINT_FILENAME",
    "NOTEBOOK_07_SOCIAL_METADATA_FILENAME",
    "NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID",
    "NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID",

    "NOTEBOOK_07_SOCIAL_TRAINING_EPOCHS",
    "NOTEBOOK_07_SOCIAL_MAXIMUM_GRADIENT_NORM",
    "NOTEBOOK_07_SOCIAL_WITHIN_ARTICLE_SHUFFLE",
    "NOTEBOOK_07_SOCIAL_ARTICLE_SEQUENCE_PRESERVED",

    "NOTEBOOK_07_SOCIAL_LEARNING_RATE",
    "NOTEBOOK_07_SOCIAL_WEIGHT_DECAY",
    "NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE",

    "NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT",

    "BLOCK_4_SOCIAL_TARGET_MATRIX",
    "BLOCK_4_SOCIAL_MASK_MATRIX",

    "BLOCK_5_CONTEXTUAL_REPRESENTATION",

    "BLOCK_7_TRAINING_ARTICLE_COUNT",
    "BLOCK_7_TRAINING_SENTENCE_COUNT",
    "BLOCK_7_VALIDATION_SENTENCE_COUNT",
    "BLOCK_7_TEST_SENTENCE_COUNT",
    "BLOCK_7_FINAL_TOTAL_OBJECTIVE",
    "BLOCK_7_FINAL_FAMILY_LOSSES",
    "BLOCK_7_MAXIMUM_PRECLIP_GRADIENT_NORM",

    "Notebook07Backbone",
    "Notebook07GlobalConfluent",
    "Notebook07RepresentationHead",

    "block_5_download_drive_bytes",
]


missing_block_8_objects = [
    object_name
    for object_name
    in required_block_8_objects
    if object_name not in globals()
]


if missing_block_8_objects:

    raise NameError(
        "Notebook 07 Block 8 prerequisites are not initialised. "
        f"Missing: {missing_block_8_objects}"
    )


if not all(
    [
        NOTEBOOK_07_BLOCK_1_COMPLETE,
        NOTEBOOK_07_BLOCK_1_VALID,
        NOTEBOOK_07_BLOCK_2_COMPLETE,
        NOTEBOOK_07_BLOCK_2_VALID,
        NOTEBOOK_07_BLOCK_3_COMPLETE,
        NOTEBOOK_07_BLOCK_3_VALID,
        NOTEBOOK_07_BLOCK_4_COMPLETE,
        NOTEBOOK_07_BLOCK_4_VALID,
        NOTEBOOK_07_BLOCK_5_COMPLETE,
        NOTEBOOK_07_BLOCK_5_VALID,
        NOTEBOOK_07_BLOCK_6_COMPLETE,
        NOTEBOOK_07_BLOCK_6_VALID,
        NOTEBOOK_07_BLOCK_7_COMPLETE,
        NOTEBOOK_07_BLOCK_7_VALID,
        NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID,
    ]
):

    raise RuntimeError(
        "Notebook 07 Blocks 1–7 must be complete and valid "
        "before Block 8 reproducibility validation."
    )


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_07_BLOCK_8 = 8

NOTEBOOK_07_BLOCK_8_NAME = (
    "Social Representation Checkpoint Reload, "
    "Reproducibility and Training-State Validation"
)

NOTEBOOK_07_BLOCK_8_VERSION = "1.1"

NOTEBOOK_07_SOCIAL_REPRODUCIBILITY_VERSION = "1.1"


BLOCK_8_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Reproducibility tolerance
# =============================================================================

BLOCK_8_OBJECTIVE_RTOL = 1e-6

BLOCK_8_OBJECTIVE_ATOL = 1e-8


# =============================================================================
# Execution boundary
# =============================================================================

NOTEBOOK_07_SOCIAL_CHECKPOINT_RELOADED = False

NOTEBOOK_07_SOCIAL_METADATA_RELOADED = False

NOTEBOOK_07_SOCIAL_RESTORED_FORWARD_EXECUTED = False

NOTEBOOK_07_SOCIAL_RESTORED_OBJECTIVE_CALCULATED = False

NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED = False

NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED = False

NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED = False

NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED = False

NOTEBOOK_07_SOCIAL_ADDITIONAL_TRAINING_EXECUTED = False

NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED = False

NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED = False

NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED = False

NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED = False

NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED = False

NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED = False

NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED = False

NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Device
# =============================================================================

BLOCK_8_DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)


# =============================================================================
# Reload persisted Block 7 checkpoint
# =============================================================================

BLOCK_8_CHECKPOINT_BYTES = (
    block_5_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID,
    )
)


if not BLOCK_8_CHECKPOINT_BYTES:

    raise RuntimeError(
        "Persisted Notebook 07 social checkpoint was empty."
    )


BLOCK_8_SOCIAL_CHECKPOINT = torch.load(
    io.BytesIO(
        BLOCK_8_CHECKPOINT_BYTES
    ),
    map_location=
        "cpu",
    weights_only=
        False,
)


if not isinstance(
    BLOCK_8_SOCIAL_CHECKPOINT,
    dict,
):

    raise TypeError(
        "Persisted Notebook 07 social checkpoint must be a dictionary."
    )


NOTEBOOK_07_SOCIAL_CHECKPOINT_RELOADED = True


# =============================================================================
# Reload persisted Block 7 metadata
# =============================================================================

BLOCK_8_METADATA_BYTES = (
    block_5_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID,
    )
)


if not BLOCK_8_METADATA_BYTES:

    raise RuntimeError(
        "Persisted Notebook 07 social metadata was empty."
    )


BLOCK_8_SOCIAL_METADATA = json.loads(
    BLOCK_8_METADATA_BYTES.decode(
        "utf-8"
    )
)


if not isinstance(
    BLOCK_8_SOCIAL_METADATA,
    dict,
):

    raise TypeError(
        "Persisted Notebook 07 social metadata must be a dictionary."
    )


NOTEBOOK_07_SOCIAL_METADATA_RELOADED = True


# =============================================================================
# Persisted checkpoint contract validation
# =============================================================================

BLOCK_8_REQUIRED_CHECKPOINT_KEYS = (
    "checkpoint_type",
    "checkpoint_version",
    "training_policy_version",
    "training_epoch_count",
    "within_article_shuffle",
    "article_sequence_preserved",
    "training_article_count",
    "training_sentence_count",
    "validation_sentence_count",
    "test_sentence_count",
    "active_dimensions",
    "active_indices",
    "deferred_dimensions",
    "deferred_indices",
    "objective_weights",
    "loss_family",
    "optimizer_type",
    "learning_rate",
    "weight_decay",
    "maximum_gradient_norm",
    "initial_objective",
    "final_objective",
    "initial_family_losses",
    "final_family_losses",
    "maximum_preclip_gradient_norm",
    "backbone_state_dict",
    "global_confluent_state_dict",
    "psychological_head_state_dict",
    "factual_head_state_dict",
    "social_head_state_dict",
    "optimizer_state_dict",
    "methodological_boundary",
)


BLOCK_8_MISSING_CHECKPOINT_KEYS = [
    key
    for key
    in BLOCK_8_REQUIRED_CHECKPOINT_KEYS
    if key not in BLOCK_8_SOCIAL_CHECKPOINT
]


if BLOCK_8_MISSING_CHECKPOINT_KEYS:

    raise RuntimeError(
        "Persisted Block 7 social checkpoint is missing required "
        "training-state fields. "
        f"Missing: {BLOCK_8_MISSING_CHECKPOINT_KEYS}"
    )


# =============================================================================
# Checkpoint identity contract
# =============================================================================

BLOCK_8_CHECKPOINT_TYPE_VALID = (
    BLOCK_8_SOCIAL_CHECKPOINT[
        "checkpoint_type"
    ]
    ==
    NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE
)


BLOCK_8_CHECKPOINT_EXPERIMENTAL = (
    BLOCK_8_SOCIAL_CHECKPOINT[
        "methodological_boundary"
    ][
        "validated_model_checkpoint"
    ]
    is False
)


BLOCK_8_VALIDATED_MODEL_CHECKPOINT = (
    not BLOCK_8_CHECKPOINT_EXPERIMENTAL
)


BLOCK_8_CHECKPOINT_CONTRACT_VALID = all(
    [
        BLOCK_8_CHECKPOINT_TYPE_VALID,
        BLOCK_8_CHECKPOINT_EXPERIMENTAL,
        not BLOCK_8_VALIDATED_MODEL_CHECKPOINT,
    ]
)


if not BLOCK_8_CHECKPOINT_CONTRACT_VALID:

    raise RuntimeError(
        "Persisted Social Representation checkpoint classification "
        "is invalid."
    )


# =============================================================================
# Metadata / checkpoint alignment
# =============================================================================

BLOCK_8_METADATA_CHECKPOINT_TYPE_ALIGNED = (
    BLOCK_8_SOCIAL_METADATA.get(
        "checkpoint_type"
    )
    ==
    BLOCK_8_SOCIAL_CHECKPOINT.get(
        "checkpoint_type"
    )
)


BLOCK_8_METADATA_VALIDATED_MODEL_FALSE = (
    BLOCK_8_SOCIAL_METADATA.get(
        "validated_model_checkpoint"
    )
    is False
)


BLOCK_8_METADATA_CHECKPOINT_ALIGNED = all(
    [
        BLOCK_8_METADATA_CHECKPOINT_TYPE_ALIGNED,
        BLOCK_8_METADATA_VALIDATED_MODEL_FALSE,
    ]
)


if not BLOCK_8_METADATA_CHECKPOINT_ALIGNED:

    raise RuntimeError(
        "Persisted Block 7 metadata does not align with the "
        "Social Representation checkpoint."
    )


# =============================================================================
# Fresh architecture reconstruction
# =============================================================================
#
# Fresh modules reproduce the exact architecture contract established by
# Block 5. No transient trained runtime module is used as a parameter source.
# =============================================================================

BLOCK_8_RESTORED_BACKBONE = (
    Notebook07Backbone(
        input_dim=
            NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM,

        output_dim=
            NOTEBOOK_07_BACKBONE_INTERFACE_DIM,
    )
)


BLOCK_8_RESTORED_GLOBAL_CONFLUENT = (
    Notebook07GlobalConfluent(
        input_dim=
            NOTEBOOK_07_BACKBONE_INTERFACE_DIM,

        output_dim=
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,

        dropout=
            NOTEBOOK_07_GLOBAL_CONFLUENT_DROPOUT,
    )
)


BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD = (
    Notebook07RepresentationHead(
        input_dim=
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,

        hidden_dim=
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,

        output_dim=
            NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_DIM,

        dropout=
            NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT,
    )
)


BLOCK_8_RESTORED_FACTUAL_HEAD = (
    Notebook07RepresentationHead(
        input_dim=
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,

        hidden_dim=
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,

        output_dim=
            NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM,

        dropout=
            NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT,
    )
)


BLOCK_8_RESTORED_SOCIAL_HEAD = (
    Notebook07RepresentationHead(
        input_dim=
            NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,

        hidden_dim=
            NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,

        output_dim=
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

        dropout=
            NOTEBOOK_07_REPRESENTATION_HEAD_DROPOUT,
    )
)


# =============================================================================
# Restore persisted model states
# =============================================================================

BLOCK_8_RESTORED_BACKBONE.load_state_dict(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "backbone_state_dict"
    ],
    strict=True,
)


BLOCK_8_RESTORED_GLOBAL_CONFLUENT.load_state_dict(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "global_confluent_state_dict"
    ],
    strict=True,
)


BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD.load_state_dict(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "psychological_head_state_dict"
    ],
    strict=True,
)


BLOCK_8_RESTORED_FACTUAL_HEAD.load_state_dict(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "factual_head_state_dict"
    ],
    strict=True,
)


BLOCK_8_RESTORED_SOCIAL_HEAD.load_state_dict(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "social_head_state_dict"
    ],
    strict=True,
)


# =============================================================================
# Move restored modules to device
# =============================================================================

BLOCK_8_RESTORED_BACKBONE = (
    BLOCK_8_RESTORED_BACKBONE.to(
        BLOCK_8_DEVICE
    )
)


BLOCK_8_RESTORED_GLOBAL_CONFLUENT = (
    BLOCK_8_RESTORED_GLOBAL_CONFLUENT.to(
        BLOCK_8_DEVICE
    )
)


BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD = (
    BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD.to(
        BLOCK_8_DEVICE
    )
)


BLOCK_8_RESTORED_FACTUAL_HEAD = (
    BLOCK_8_RESTORED_FACTUAL_HEAD.to(
        BLOCK_8_DEVICE
    )
)


BLOCK_8_RESTORED_SOCIAL_HEAD = (
    BLOCK_8_RESTORED_SOCIAL_HEAD.to(
        BLOCK_8_DEVICE
    )
)


# =============================================================================
# Exact state-comparison helper
# =============================================================================

def block_8_state_dict_exact_match(
    module,
    expected_state_dict,
):

    observed_state_dict = (
        module.state_dict()
    )


    if (
        tuple(
            observed_state_dict.keys()
        )
        !=
        tuple(
            expected_state_dict.keys()
        )
    ):

        return False


    return all(
        torch.equal(
            observed_state_dict[
                parameter_name
            ]
            .detach()
            .cpu(),

            expected_state_dict[
                parameter_name
            ]
            .detach()
            .cpu(),
        )

        for parameter_name
        in expected_state_dict
    )


# =============================================================================
# Exact checkpoint-state reproduction
# =============================================================================

BLOCK_8_BACKBONE_MATCHES_CHECKPOINT = (
    block_8_state_dict_exact_match(
        BLOCK_8_RESTORED_BACKBONE,
        BLOCK_8_SOCIAL_CHECKPOINT[
            "backbone_state_dict"
        ],
    )
)


BLOCK_8_GLOBAL_CONFLUENT_MATCHES_CHECKPOINT = (
    block_8_state_dict_exact_match(
        BLOCK_8_RESTORED_GLOBAL_CONFLUENT,
        BLOCK_8_SOCIAL_CHECKPOINT[
            "global_confluent_state_dict"
        ],
    )
)


BLOCK_8_PSYCHOLOGICAL_MATCHES_CHECKPOINT = (
    block_8_state_dict_exact_match(
        BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD,
        BLOCK_8_SOCIAL_CHECKPOINT[
            "psychological_head_state_dict"
        ],
    )
)


BLOCK_8_FACTUAL_MATCHES_CHECKPOINT = (
    block_8_state_dict_exact_match(
        BLOCK_8_RESTORED_FACTUAL_HEAD,
        BLOCK_8_SOCIAL_CHECKPOINT[
            "factual_head_state_dict"
        ],
    )
)


BLOCK_8_SOCIAL_MATCHES_CHECKPOINT = (
    block_8_state_dict_exact_match(
        BLOCK_8_RESTORED_SOCIAL_HEAD,
        BLOCK_8_SOCIAL_CHECKPOINT[
            "social_head_state_dict"
        ],
    )
)


BLOCK_8_MODEL_STATE_RESTORED = all(
    [
        BLOCK_8_BACKBONE_MATCHES_CHECKPOINT,
        BLOCK_8_GLOBAL_CONFLUENT_MATCHES_CHECKPOINT,
        BLOCK_8_PSYCHOLOGICAL_MATCHES_CHECKPOINT,
        BLOCK_8_FACTUAL_MATCHES_CHECKPOINT,
        BLOCK_8_SOCIAL_MATCHES_CHECKPOINT,
    ]
)


if not BLOCK_8_MODEL_STATE_RESTORED:

    raise RuntimeError(
        "Fresh Block 8 modules failed exact Social Representation "
        "checkpoint-state restoration."
    )


# =============================================================================
# Runtime trained-social state comparison
# =============================================================================

BLOCK_8_SOCIAL_MATCHES_RUNTIME = (
    block_8_state_dict_exact_match(
        NOTEBOOK_07_SOCIAL_HEAD,
        BLOCK_8_SOCIAL_CHECKPOINT[
            "social_head_state_dict"
        ],
    )
)


BLOCK_8_BACKBONE_MATCHES_RUNTIME = (
    block_8_state_dict_exact_match(
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE,
        BLOCK_8_SOCIAL_CHECKPOINT[
            "backbone_state_dict"
        ],
    )
)


BLOCK_8_GLOBAL_CONFLUENT_MATCHES_RUNTIME = (
    block_8_state_dict_exact_match(
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE,
        BLOCK_8_SOCIAL_CHECKPOINT[
            "global_confluent_state_dict"
        ],
    )
)


BLOCK_8_PSYCHOLOGICAL_MATCHES_RUNTIME = (
    block_8_state_dict_exact_match(
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE,
        BLOCK_8_SOCIAL_CHECKPOINT[
            "psychological_head_state_dict"
        ],
    )
)


BLOCK_8_FACTUAL_MATCHES_RUNTIME = (
    block_8_state_dict_exact_match(
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE,
        BLOCK_8_SOCIAL_CHECKPOINT[
            "factual_head_state_dict"
        ],
    )
)


# =============================================================================
# Restore trainability policy
# =============================================================================

for parameter in (
    BLOCK_8_RESTORED_BACKBONE.parameters()
):

    parameter.requires_grad = False


for parameter in (
    BLOCK_8_RESTORED_GLOBAL_CONFLUENT.parameters()
):

    parameter.requires_grad = False


for parameter in (
    BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD.parameters()
):

    parameter.requires_grad = False


for parameter in (
    BLOCK_8_RESTORED_FACTUAL_HEAD.parameters()
):

    parameter.requires_grad = False


for parameter in (
    BLOCK_8_RESTORED_SOCIAL_HEAD.parameters()
):

    parameter.requires_grad = True


BLOCK_8_BACKBONE_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in BLOCK_8_RESTORED_BACKBONE.parameters()
)


BLOCK_8_GLOBAL_CONFLUENT_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in BLOCK_8_RESTORED_GLOBAL_CONFLUENT.parameters()
)


BLOCK_8_PSYCHOLOGICAL_HEAD_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD.parameters()
)


BLOCK_8_FACTUAL_HEAD_FROZEN = all(
    not parameter.requires_grad
    for parameter
    in BLOCK_8_RESTORED_FACTUAL_HEAD.parameters()
)


BLOCK_8_SOCIAL_HEAD_TRAINABLE = all(
    parameter.requires_grad
    for parameter
    in BLOCK_8_RESTORED_SOCIAL_HEAD.parameters()
)


BLOCK_8_SOCIAL_TRAINABLE_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in BLOCK_8_RESTORED_SOCIAL_HEAD.parameters()
    if parameter.requires_grad
)


BLOCK_8_TRAINABILITY_SCOPE_VALID = all(
    [
        BLOCK_8_BACKBONE_FROZEN,
        BLOCK_8_GLOBAL_CONFLUENT_FROZEN,
        BLOCK_8_PSYCHOLOGICAL_HEAD_FROZEN,
        BLOCK_8_FACTUAL_HEAD_FROZEN,
        BLOCK_8_SOCIAL_HEAD_TRAINABLE,

        (
            BLOCK_8_SOCIAL_TRAINABLE_PARAMETER_COUNT
            ==
            NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT
        ),

    ]
)


if not BLOCK_8_TRAINABILITY_SCOPE_VALID:

    raise RuntimeError(
        "Restored Social Representation trainability scope is invalid."
    )


# =============================================================================
# Reconstruct optimiser
# =============================================================================

BLOCK_8_RESTORED_OPTIMIZER = torch.optim.AdamW(
    [
        parameter
        for parameter
        in BLOCK_8_RESTORED_SOCIAL_HEAD.parameters()
        if parameter.requires_grad
    ],
    lr=
        float(
            BLOCK_8_SOCIAL_CHECKPOINT[
                "learning_rate"
            ]
        ),
    weight_decay=
        float(
            BLOCK_8_SOCIAL_CHECKPOINT[
                "weight_decay"
            ]
        ),
)


BLOCK_8_RESTORED_OPTIMIZER.load_state_dict(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "optimizer_state_dict"
    ]
)


BLOCK_8_OPTIMIZER_RELOADED = True


# =============================================================================
# Move optimiser state tensors to current device
# =============================================================================

for optimizer_state in (
    BLOCK_8_RESTORED_OPTIMIZER.state.values()
):

    for (
        state_key,
        state_value,
    ) in list(
        optimizer_state.items()
    ):

        if isinstance(
            state_value,
            torch.Tensor,
        ):

            optimizer_state[
                state_key
            ] = state_value.to(
                BLOCK_8_DEVICE
            )


# =============================================================================
# Optimiser policy reproduction
# =============================================================================

BLOCK_8_OPTIMIZER_TYPE_VALID = (
    BLOCK_8_SOCIAL_CHECKPOINT[
        "optimizer_type"
    ]
    ==
    "AdamW"
)


BLOCK_8_LEARNING_RATE_REPRODUCED = bool(
    np.isclose(
        float(
            BLOCK_8_RESTORED_OPTIMIZER.param_groups[
                0
            ][
                "lr"
            ]
        ),
        float(
            BLOCK_8_SOCIAL_CHECKPOINT[
                "learning_rate"
            ]
        ),
        rtol=0.0,
        atol=1e-15,
    )
)


BLOCK_8_WEIGHT_DECAY_REPRODUCED = bool(
    np.isclose(
        float(
            BLOCK_8_RESTORED_OPTIMIZER.param_groups[
                0
            ][
                "weight_decay"
            ]
        ),
        float(
            BLOCK_8_SOCIAL_CHECKPOINT[
                "weight_decay"
            ]
        ),
        rtol=0.0,
        atol=1e-15,
    )
)


BLOCK_8_OPTIMIZER_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter_group
    in BLOCK_8_RESTORED_OPTIMIZER.param_groups
    for parameter
    in parameter_group[
        "params"
    ]
)


BLOCK_8_OPTIMIZER_SCOPE_VALID = (
    BLOCK_8_OPTIMIZER_PARAMETER_COUNT
    ==
    BLOCK_8_SOCIAL_TRAINABLE_PARAMETER_COUNT
)


# =============================================================================
# Optimiser-state exact comparison helper
# =============================================================================

def block_8_nested_equal(
    left,
    right,
):
    """
    Exact recursive comparison for optimiser-state structures.
    """

    if isinstance(
        left,
        torch.Tensor,
    ):

        if not isinstance(
            right,
            torch.Tensor,
        ):

            return False


        return torch.equal(
            left.detach().cpu(),
            right.detach().cpu(),
        )


    if isinstance(
        left,
        dict,
    ):

        if not isinstance(
            right,
            dict,
        ):

            return False


        if (
            set(
                left.keys()
            )
            !=
            set(
                right.keys()
            )
        ):

            return False


        return all(
            block_8_nested_equal(
                left[
                    key
                ],
                right[
                    key
                ],
            )

            for key
            in left
        )


    if isinstance(
        left,
        (
            list,
            tuple,
        ),
    ):

        if not isinstance(
            right,
            (
                list,
                tuple,
            ),
        ):

            return False


        if len(
            left
        ) != len(
            right
        ):

            return False


        return all(
            block_8_nested_equal(
                left_item,
                right_item,
            )

            for (
                left_item,
                right_item,
            ) in zip(
                left,
                right,
            )
        )


    return left == right


BLOCK_8_OPTIMIZER_STATE_EXACT = (
    block_8_nested_equal(
        BLOCK_8_RESTORED_OPTIMIZER.state_dict(),
        BLOCK_8_SOCIAL_CHECKPOINT[
            "optimizer_state_dict"
        ],
    )
)


BLOCK_8_OPTIMIZER_POLICY_VALID = all(
    [
        BLOCK_8_OPTIMIZER_RELOADED,
        BLOCK_8_OPTIMIZER_TYPE_VALID,
        BLOCK_8_LEARNING_RATE_REPRODUCED,
        BLOCK_8_WEIGHT_DECAY_REPRODUCED,
        BLOCK_8_OPTIMIZER_SCOPE_VALID,
        BLOCK_8_OPTIMIZER_STATE_EXACT,
    ]
)


if not BLOCK_8_OPTIMIZER_POLICY_VALID:

    raise RuntimeError(
        "Persisted Social Representation optimiser state failed "
        "exact reproduction."
    )


# =============================================================================
# Training-policy reproduction
# =============================================================================

BLOCK_8_TRAINING_ARTICLE_COUNT = int(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "training_article_count"
    ]
)


BLOCK_8_TRAINING_SENTENCE_COUNT = int(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "training_sentence_count"
    ]
)


BLOCK_8_VALIDATION_SENTENCE_COUNT = int(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "validation_sentence_count"
    ]
)


BLOCK_8_TEST_SENTENCE_COUNT = int(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "test_sentence_count"
    ]
)


BLOCK_8_TRAINING_EPOCH_COUNT = int(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "training_epoch_count"
    ]
)


BLOCK_8_MAXIMUM_GRADIENT_NORM = float(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "maximum_gradient_norm"
    ]
)


BLOCK_8_RECORDED_MAXIMUM_PRECLIP_GRADIENT_NORM = float(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "maximum_preclip_gradient_norm"
    ]
)


BLOCK_8_TRAINING_POLICY_PRESERVED = all(
    [
        (
            BLOCK_8_TRAINING_ARTICLE_COUNT
            ==
            int(
                BLOCK_7_TRAINING_ARTICLE_COUNT
            )
        ),

        (
            BLOCK_8_TRAINING_SENTENCE_COUNT
            ==
            int(
                BLOCK_7_TRAINING_SENTENCE_COUNT
            )
        ),

        (
            BLOCK_8_VALIDATION_SENTENCE_COUNT
            ==
            int(
                BLOCK_7_VALIDATION_SENTENCE_COUNT
            )
        ),

        (
            BLOCK_8_TEST_SENTENCE_COUNT
            ==
            int(
                BLOCK_7_TEST_SENTENCE_COUNT
            )
        ),

        (
            BLOCK_8_TRAINING_EPOCH_COUNT
            ==
            NOTEBOOK_07_SOCIAL_TRAINING_EPOCHS
        ),

        (
            BLOCK_8_SOCIAL_CHECKPOINT[
                "within_article_shuffle"
            ]
            ==
            NOTEBOOK_07_SOCIAL_WITHIN_ARTICLE_SHUFFLE
        ),

        (
            BLOCK_8_SOCIAL_CHECKPOINT[
                "article_sequence_preserved"
            ]
            ==
            NOTEBOOK_07_SOCIAL_ARTICLE_SEQUENCE_PRESERVED
        ),

        np.isclose(
            BLOCK_8_MAXIMUM_GRADIENT_NORM,
            NOTEBOOK_07_SOCIAL_MAXIMUM_GRADIENT_NORM,
            rtol=0.0,
            atol=1e-12,
        ),

        (
            BLOCK_8_SOCIAL_CHECKPOINT[
                "active_dimensions"
            ]
            ==
            list(
                NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
            )
        ),

        (
            BLOCK_8_SOCIAL_CHECKPOINT[
                "active_indices"
            ]
            ==
            list(
                NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
            )
        ),

        (
            BLOCK_8_SOCIAL_CHECKPOINT[
                "deferred_dimensions"
            ]
            ==
            list(
                NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
            )
        ),

        (
            BLOCK_8_SOCIAL_CHECKPOINT[
                "deferred_indices"
            ]
            ==
            list(
                NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
            )
        ),
    ]
)


if not BLOCK_8_TRAINING_POLICY_PRESERVED:

    raise RuntimeError(
        "Persisted Social Representation training policy was not "
        "reproduced exactly."
    )


# =============================================================================
# Objective-weight reproduction
# =============================================================================

BLOCK_8_OBJECTIVE_WEIGHTS_REPRODUCED = all(
    np.isclose(
        float(
            BLOCK_8_SOCIAL_CHECKPOINT[
                "objective_weights"
            ][
                dimension_name
            ]
        ),
        float(
            NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS[
                dimension_name
            ]
        ),
        rtol=0.0,
        atol=1e-12,
    )

    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
)


if not BLOCK_8_OBJECTIVE_WEIGHTS_REPRODUCED:

    raise RuntimeError(
        "Persisted Social Representation objective weights were not "
        "reproduced."
    )


# =============================================================================
# Loss-family reproduction
# =============================================================================

BLOCK_8_CHECKPOINT_LOSS_FAMILIES = (
    BLOCK_8_SOCIAL_CHECKPOINT[
        "loss_family"
    ]
)


BLOCK_8_LOSS_FAMILY_KEYS_VALID = (
    set(
        BLOCK_8_CHECKPOINT_LOSS_FAMILIES.keys()
    )
    ==
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


BLOCK_8_LOSS_FAMILIES_REPRODUCED = all(
    BLOCK_8_CHECKPOINT_LOSS_FAMILIES[
        dimension_name
    ]
    ==
    NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES[
        dimension_name
    ]

    for dimension_name
    in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
)


if not all(
    [
        BLOCK_8_LOSS_FAMILY_KEYS_VALID,
        BLOCK_8_LOSS_FAMILIES_REPRODUCED,
    ]
):

    raise RuntimeError(
        "Persisted Social Representation loss-family contract "
        "was not reproduced."
    )


# =============================================================================
# Restore canonical targets and masks
# =============================================================================

BLOCK_8_SOCIAL_TARGET_TENSOR = torch.tensor(
    BLOCK_4_SOCIAL_TARGET_MATRIX,
    dtype=torch.float32,
    device=
        BLOCK_8_DEVICE,
)


BLOCK_8_SOCIAL_MASK_TENSOR = torch.tensor(
    BLOCK_4_SOCIAL_MASK_MATRIX,
    dtype=torch.bool,
    device=
        BLOCK_8_DEVICE,
)


BLOCK_8_TARGET_SHAPE_VALID = (
    tuple(
        BLOCK_8_SOCIAL_TARGET_TENSOR.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_8_MASK_SHAPE_VALID = (
    tuple(
        BLOCK_8_SOCIAL_MASK_TENSOR.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    )
)


BLOCK_8_OBSERVED_TARGETS_FINITE = bool(
    torch.isfinite(
        BLOCK_8_SOCIAL_TARGET_TENSOR[
            BLOCK_8_SOCIAL_MASK_TENSOR
        ]
    ).all().item()
)


if not all(
    [
        BLOCK_8_TARGET_SHAPE_VALID,
        BLOCK_8_MASK_SHAPE_VALID,
        BLOCK_8_OBSERVED_TARGETS_FINITE,
    ]
):

    raise RuntimeError(
        "Block 8 Social Representation target/mask contract is invalid."
    )


# =============================================================================
# Restore canonical contextual representation
# =============================================================================

BLOCK_8_CONTEXTUAL_REPRESENTATION = (
    BLOCK_5_CONTEXTUAL_REPRESENTATION
    .detach()
    .clone()
    .to(
        BLOCK_8_DEVICE
    )
)


BLOCK_8_CONTEXTUAL_SHAPE_VALID = (
    tuple(
        BLOCK_8_CONTEXTUAL_REPRESENTATION.shape
    )
    ==
    (
        NOTEBOOK_07_SENTENCE_COUNT,
        NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM,
    )
)


BLOCK_8_CONTEXTUAL_VALUES_FINITE = bool(
    torch.isfinite(
        BLOCK_8_CONTEXTUAL_REPRESENTATION
    ).all().item()
)


if not all(
    [
        BLOCK_8_CONTEXTUAL_SHAPE_VALID,
        BLOCK_8_CONTEXTUAL_VALUES_FINITE,
    ]
):

    raise RuntimeError(
        "Block 8 contextual representation is invalid."
    )


# =============================================================================
# Mask-aware Social Representation objective
# =============================================================================

def block_8_masked_mean_squared_error(
    predictions,
    targets,
    mask,
):

    if not (
        predictions.ndim
        ==
        targets.ndim
        ==
        mask.ndim
        ==
        1
    ):

        raise ValueError(
            "Masked MSE prediction, target and mask must be one-dimensional."
        )


    if not (
        predictions.shape
        ==
        targets.shape
        ==
        mask.shape
    ):

        raise ValueError(
            "Masked MSE prediction, target and mask shapes do not match."
        )


    if int(
        mask.sum().item()
    ) <= 0:

        raise RuntimeError(
            "An active Social Representation MSE objective has no "
            "available supervision."
        )


    return F.mse_loss(
        predictions[
            mask
        ],
        targets[
            mask
        ],
        reduction=
            "mean",
    )


def block_8_masked_binary_cross_entropy_with_logits(
    predictions,
    targets,
    mask,
):

    if not (
        predictions.ndim
        ==
        targets.ndim
        ==
        mask.ndim
        ==
        1
    ):

        raise ValueError(
            "Masked BCE prediction, target and mask must be one-dimensional."
        )


    if not (
        predictions.shape
        ==
        targets.shape
        ==
        mask.shape
    ):

        raise ValueError(
            "Masked BCE prediction, target and mask shapes do not match."
        )


    if int(
        mask.sum().item()
    ) <= 0:

        raise RuntimeError(
            "An active Social Representation BCE objective has no "
            "available supervision."
        )


    observed_targets = targets[
        mask
    ]


    if not bool(
        torch.isin(
            observed_targets,
            torch.tensor(
                [
                    0.0,
                    1.0,
                ],
                dtype=
                    observed_targets.dtype,
                device=
                    observed_targets.device,
            ),
        ).all().item()
    ):

        raise RuntimeError(
            "Active binary Social Representation target contains "
            "values outside {0, 1}."
        )


    return F.binary_cross_entropy_with_logits(
        predictions[
            mask
        ],
        observed_targets,
        reduction=
            "mean",
    )


def block_8_calculate_social_objective(
    social_output,
):
    """
    Reproduce every active Social Representation family using the persisted
    Block 7 loss-family contract and objective weights.
    """

    family_losses = {}


    total_objective = torch.zeros(
        (),
        dtype=
            social_output.dtype,
        device=
            social_output.device,
    )


    for (
        dimension_name,
        dimension_index,
    ) in zip(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS,
        NOTEBOOK_07_SOCIAL_ACTIVE_INDICES,
    ):

        predictions = (
            social_output[
                :,
                dimension_index,
            ]
        )


        targets = (
            BLOCK_8_SOCIAL_TARGET_TENSOR[
                :,
                dimension_index,
            ]
        )


        mask = (
            BLOCK_8_SOCIAL_MASK_TENSOR[
                :,
                dimension_index,
            ]
        )


        loss_family = (
            BLOCK_8_CHECKPOINT_LOSS_FAMILIES[
                dimension_name
            ]
        )


        if loss_family == "masked_mean_squared_error":

            family_loss = (
                block_8_masked_mean_squared_error(
                    predictions,
                    targets,
                    mask,
                )
            )


        elif loss_family == "binary_cross_entropy_with_logits":

            family_loss = (
                block_8_masked_binary_cross_entropy_with_logits(
                    predictions,
                    targets,
                    mask,
                )
            )


        else:

            raise RuntimeError(
                f"Unsupported persisted Social Representation loss family "
                f"for {dimension_name}: {loss_family}"
            )


        family_losses[
            dimension_name
        ] = family_loss


        total_objective = (
            total_objective
            +
            (
                float(
                    BLOCK_8_SOCIAL_CHECKPOINT[
                        "objective_weights"
                    ][
                        dimension_name
                    ]
                )
                *
                family_loss
            )
        )


    return (
        family_losses,
        total_objective,
    )


# =============================================================================
# Pre-forward parameter snapshots
# =============================================================================

def block_8_snapshot_module(
    module,
):

    return {
        name:
            parameter
            .detach()
            .cpu()
            .clone()

        for (
            name,
            parameter,
        ) in module.named_parameters()
    }


def block_8_module_matches_snapshot(
    module,
    snapshot,
):

    return all(
        torch.equal(
            parameter
            .detach()
            .cpu(),

            snapshot[
                name
            ],
        )

        for (
            name,
            parameter,
        ) in module.named_parameters()
    )


BLOCK_8_BACKBONE_BEFORE = (
    block_8_snapshot_module(
        BLOCK_8_RESTORED_BACKBONE
    )
)


BLOCK_8_GLOBAL_BEFORE = (
    block_8_snapshot_module(
        BLOCK_8_RESTORED_GLOBAL_CONFLUENT
    )
)


BLOCK_8_PSYCHOLOGICAL_BEFORE = (
    block_8_snapshot_module(
        BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD
    )
)


BLOCK_8_FACTUAL_BEFORE = (
    block_8_snapshot_module(
        BLOCK_8_RESTORED_FACTUAL_HEAD
    )
)


BLOCK_8_SOCIAL_BEFORE = (
    block_8_snapshot_module(
        BLOCK_8_RESTORED_SOCIAL_HEAD
    )
)


# =============================================================================
# Deterministic post-training forward reproduction
# =============================================================================

BLOCK_8_RESTORED_BACKBONE.eval()

BLOCK_8_RESTORED_GLOBAL_CONFLUENT.eval()

BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD.eval()

BLOCK_8_RESTORED_FACTUAL_HEAD.eval()

BLOCK_8_RESTORED_SOCIAL_HEAD.eval()


with torch.no_grad():

    BLOCK_8_BACKBONE_OUTPUT = (
        BLOCK_8_RESTORED_BACKBONE(
            BLOCK_8_CONTEXTUAL_REPRESENTATION
        )
    )


    BLOCK_8_GLOBAL_OUTPUT = (
        BLOCK_8_RESTORED_GLOBAL_CONFLUENT(
            BLOCK_8_BACKBONE_OUTPUT
        )
    )


    BLOCK_8_SOCIAL_OUTPUT = (
        BLOCK_8_RESTORED_SOCIAL_HEAD(
            BLOCK_8_GLOBAL_OUTPUT
        )
    )


    (
        BLOCK_8_RESTORED_FAMILY_LOSSES_TENSOR,
        BLOCK_8_RESTORED_TOTAL_OBJECTIVE_TENSOR,
    ) = block_8_calculate_social_objective(
        BLOCK_8_SOCIAL_OUTPUT
    )


NOTEBOOK_07_SOCIAL_RESTORED_FORWARD_EXECUTED = True

NOTEBOOK_07_SOCIAL_RESTORED_OBJECTIVE_CALCULATED = True


# =============================================================================
# Reproduced objective values
# =============================================================================

BLOCK_8_RESTORED_FAMILY_LOSSES = {
    dimension_name:
        float(
            family_loss
            .detach()
            .cpu()
            .item()
        )

    for (
        dimension_name,
        family_loss,
    ) in BLOCK_8_RESTORED_FAMILY_LOSSES_TENSOR.items()
}


BLOCK_8_RESTORED_TOTAL_OBJECTIVE = float(
    BLOCK_8_RESTORED_TOTAL_OBJECTIVE_TENSOR
    .detach()
    .cpu()
    .item()
)


BLOCK_8_EXPECTED_TOTAL_OBJECTIVE = float(
    BLOCK_8_SOCIAL_CHECKPOINT[
        "final_objective"
    ]
)


# =============================================================================
# Family-loss reproduction
# =============================================================================

BLOCK_8_FAMILY_LOSS_REPRODUCTION = {}


for dimension_name in (
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
):

    expected_loss = float(
        BLOCK_8_SOCIAL_CHECKPOINT[
            "final_family_losses"
        ][
            dimension_name
        ]
    )


    restored_loss = float(
        BLOCK_8_RESTORED_FAMILY_LOSSES[
            dimension_name
        ]
    )


    BLOCK_8_FAMILY_LOSS_REPRODUCTION[
        dimension_name
    ] = bool(
        np.isclose(
            restored_loss,
            expected_loss,
            rtol=
                BLOCK_8_OBJECTIVE_RTOL,
            atol=
                BLOCK_8_OBJECTIVE_ATOL,
        )
    )


BLOCK_8_ALL_FAMILY_LOSSES_REPRODUCED = all(
    BLOCK_8_FAMILY_LOSS_REPRODUCTION.values()
)


BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED = bool(
    np.isclose(
        BLOCK_8_RESTORED_TOTAL_OBJECTIVE,
        BLOCK_8_EXPECTED_TOTAL_OBJECTIVE,
        rtol=
            BLOCK_8_OBJECTIVE_RTOL,
        atol=
            BLOCK_8_OBJECTIVE_ATOL,
    )
)


if not all(
    [
        BLOCK_8_ALL_FAMILY_LOSSES_REPRODUCED,
        BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED,
    ]
):

    raise RuntimeError(
        "Restored Social Representation checkpoint does not reproduce "
        "the persisted post-training objective."
    )


# =============================================================================
# Deferred-dimension exclusion validation
# =============================================================================

BLOCK_8_DEFERRED_DIMENSIONS_EXCLUDED = (
    set(
        BLOCK_8_RESTORED_FAMILY_LOSSES.keys()
    )
    ==
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


if not BLOCK_8_DEFERRED_DIMENSIONS_EXCLUDED:

    raise RuntimeError(
        "Deferred Social Representation dimensions entered the "
        "Block 8 reproduced objective."
    )


# =============================================================================
# No-update validation
# =============================================================================

BLOCK_8_BACKBONE_UNCHANGED = (
    block_8_module_matches_snapshot(
        BLOCK_8_RESTORED_BACKBONE,
        BLOCK_8_BACKBONE_BEFORE,
    )
)


BLOCK_8_GLOBAL_UNCHANGED = (
    block_8_module_matches_snapshot(
        BLOCK_8_RESTORED_GLOBAL_CONFLUENT,
        BLOCK_8_GLOBAL_BEFORE,
    )
)


BLOCK_8_PSYCHOLOGICAL_UNCHANGED = (
    block_8_module_matches_snapshot(
        BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD,
        BLOCK_8_PSYCHOLOGICAL_BEFORE,
    )
)


BLOCK_8_FACTUAL_UNCHANGED = (
    block_8_module_matches_snapshot(
        BLOCK_8_RESTORED_FACTUAL_HEAD,
        BLOCK_8_FACTUAL_BEFORE,
    )
)


BLOCK_8_SOCIAL_UNCHANGED = (
    block_8_module_matches_snapshot(
        BLOCK_8_RESTORED_SOCIAL_HEAD,
        BLOCK_8_SOCIAL_BEFORE,
    )
)


BLOCK_8_ALL_PARAMETERS_UNCHANGED = all(
    [
        BLOCK_8_BACKBONE_UNCHANGED,
        BLOCK_8_GLOBAL_UNCHANGED,
        BLOCK_8_PSYCHOLOGICAL_UNCHANGED,
        BLOCK_8_FACTUAL_UNCHANGED,
        BLOCK_8_SOCIAL_UNCHANGED,
    ]
)


BLOCK_8_SOCIAL_GRADIENTS_ABSENT = all(
    parameter.grad is None
    for parameter
    in BLOCK_8_RESTORED_SOCIAL_HEAD.parameters()
)


BLOCK_8_FROZEN_GRADIENTS_ABSENT = all(
    parameter.grad is None
    for module
    in (
        BLOCK_8_RESTORED_BACKBONE,
        BLOCK_8_RESTORED_GLOBAL_CONFLUENT,
        BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD,
        BLOCK_8_RESTORED_FACTUAL_HEAD,
    )
    for parameter
    in module.parameters()
)


BLOCK_8_NO_UPDATE_VALID = all(
    [
        BLOCK_8_ALL_PARAMETERS_UNCHANGED,
        BLOCK_8_SOCIAL_GRADIENTS_ABSENT,
        BLOCK_8_FROZEN_GRADIENTS_ABSENT,
    ]
)


if not BLOCK_8_NO_UPDATE_VALID:

    raise RuntimeError(
        "Block 8 checkpoint-reproduction validation modified "
        "model state or produced gradients."
    )


# =============================================================================
# Methodological-boundary reproduction
# =============================================================================

BLOCK_8_METHOD_BOUNDARY = (
    BLOCK_8_SOCIAL_CHECKPOINT[
        "methodological_boundary"
    ]
)


BLOCK_8_METHOD_BOUNDARY_PRESERVED = all(
    [
        (
            BLOCK_8_METHOD_BOUNDARY[
                "backbone_trained"
            ]
            is False
        ),

        (
            BLOCK_8_METHOD_BOUNDARY[
                "global_confluent_trained"
            ]
            is False
        ),

        (
            BLOCK_8_METHOD_BOUNDARY[
                "psychological_representation_trained"
            ]
            is False
        ),

        (
            BLOCK_8_METHOD_BOUNDARY[
                "factual_representation_trained"
            ]
            is False
        ),

        (
            BLOCK_8_METHOD_BOUNDARY[
                "social_representation_trained"
            ]
            is True
        ),

        (
            BLOCK_8_METHOD_BOUNDARY[
                "group_conditioned_path_executed"
            ]
            is False
        ),

        (
            BLOCK_8_METHOD_BOUNDARY[
                "transformative_mechanism_executed"
            ]
            is False
        ),

        (
            BLOCK_8_METHOD_BOUNDARY[
                "transformative_weights_active"
            ]
            is False
        ),

        (
            BLOCK_8_METHOD_BOUNDARY[
                "recurrent_mechanism_executed"
            ]
            is False
        ),

        (
            BLOCK_8_METHOD_BOUNDARY[
                "held_out_evaluation_executed"
            ]
            is False
        ),

        (
            BLOCK_8_METHOD_BOUNDARY[
                "validated_model_checkpoint"
            ]
            is False
        ),

        (
            BLOCK_8_METHOD_BOUNDARY[
                "empirical_validity"
            ]
            is False
        ),
    ]
)


if not BLOCK_8_METHOD_BOUNDARY_PRESERVED:

    raise RuntimeError(
        "Persisted Block 7 methodological boundary is inconsistent."
    )


# =============================================================================
# Reproducibility state
# =============================================================================

NOTEBOOK_07_SOCIAL_CHECKPOINT_REPRODUCIBLE = all(
    [
        NOTEBOOK_07_SOCIAL_CHECKPOINT_RELOADED,
        NOTEBOOK_07_SOCIAL_METADATA_RELOADED,
        BLOCK_8_CHECKPOINT_CONTRACT_VALID,
        BLOCK_8_METADATA_CHECKPOINT_ALIGNED,
        BLOCK_8_MODEL_STATE_RESTORED,
        BLOCK_8_TRAINABILITY_SCOPE_VALID,
        BLOCK_8_OPTIMIZER_POLICY_VALID,
        BLOCK_8_TRAINING_POLICY_PRESERVED,
        BLOCK_8_OBJECTIVE_WEIGHTS_REPRODUCED,
        BLOCK_8_LOSS_FAMILY_KEYS_VALID,
        BLOCK_8_LOSS_FAMILIES_REPRODUCED,
        BLOCK_8_ALL_FAMILY_LOSSES_REPRODUCED,
        BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED,
        BLOCK_8_DEFERRED_DIMENSIONS_EXCLUDED,
        BLOCK_8_NO_UPDATE_VALID,
        BLOCK_8_METHOD_BOUNDARY_PRESERVED,
    ]
)


NOTEBOOK_07_SOCIAL_TRAINING_STATE_VALIDATED = (
    NOTEBOOK_07_SOCIAL_CHECKPOINT_REPRODUCIBLE
)


NOTEBOOK_07_READY_FOR_SOCIAL_SCOPE_AUDIT = (
    NOTEBOOK_07_SOCIAL_CHECKPOINT_REPRODUCIBLE
)


# =============================================================================
# Final validation
# =============================================================================

NOTEBOOK_07_BLOCK_8_ERRORS = []


block_8_validation_checks = {
    "checkpoint_not_reloaded":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_RELOADED,

    "metadata_not_reloaded":
        NOTEBOOK_07_SOCIAL_METADATA_RELOADED,

    "checkpoint_contract_invalid":
        BLOCK_8_CHECKPOINT_CONTRACT_VALID,

    "metadata_checkpoint_misaligned":
        BLOCK_8_METADATA_CHECKPOINT_ALIGNED,

    "model_state_not_restored":
        BLOCK_8_MODEL_STATE_RESTORED,

    "social_runtime_mismatch":
        BLOCK_8_SOCIAL_MATCHES_RUNTIME,

    "backbone_runtime_mismatch":
        BLOCK_8_BACKBONE_MATCHES_RUNTIME,

    "global_runtime_mismatch":
        BLOCK_8_GLOBAL_CONFLUENT_MATCHES_RUNTIME,

    "psychological_runtime_mismatch":
        BLOCK_8_PSYCHOLOGICAL_MATCHES_RUNTIME,

    "factual_runtime_mismatch":
        BLOCK_8_FACTUAL_MATCHES_RUNTIME,

    "trainability_scope_invalid":
        BLOCK_8_TRAINABILITY_SCOPE_VALID,

    "optimizer_policy_invalid":
        BLOCK_8_OPTIMIZER_POLICY_VALID,

    "training_policy_not_preserved":
        BLOCK_8_TRAINING_POLICY_PRESERVED,

    "objective_weights_not_reproduced":
        BLOCK_8_OBJECTIVE_WEIGHTS_REPRODUCED,

    "loss_family_keys_invalid":
        BLOCK_8_LOSS_FAMILY_KEYS_VALID,

    "loss_families_not_reproduced":
        BLOCK_8_LOSS_FAMILIES_REPRODUCED,

    "target_shape_invalid":
        BLOCK_8_TARGET_SHAPE_VALID,

    "mask_shape_invalid":
        BLOCK_8_MASK_SHAPE_VALID,

    "observed_targets_nonfinite":
        BLOCK_8_OBSERVED_TARGETS_FINITE,

    "contextual_shape_invalid":
        BLOCK_8_CONTEXTUAL_SHAPE_VALID,

    "contextual_values_nonfinite":
        BLOCK_8_CONTEXTUAL_VALUES_FINITE,

    "family_losses_not_reproduced":
        BLOCK_8_ALL_FAMILY_LOSSES_REPRODUCED,

    "total_objective_not_reproduced":
        BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED,

    "deferred_dimensions_not_excluded":
        BLOCK_8_DEFERRED_DIMENSIONS_EXCLUDED,

    "parameters_changed":
        BLOCK_8_ALL_PARAMETERS_UNCHANGED,

    "social_gradients_present":
        BLOCK_8_SOCIAL_GRADIENTS_ABSENT,

    "frozen_gradients_present":
        BLOCK_8_FROZEN_GRADIENTS_ABSENT,

    "no_update_validation_invalid":
        BLOCK_8_NO_UPDATE_VALID,

    "method_boundary_not_preserved":
        BLOCK_8_METHOD_BOUNDARY_PRESERVED,

    "checkpoint_not_reproducible":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_REPRODUCIBLE,

    "training_state_not_validated":
        NOTEBOOK_07_SOCIAL_TRAINING_STATE_VALIDATED,

    "scope_audit_not_ready":
        NOTEBOOK_07_READY_FOR_SOCIAL_SCOPE_AUDIT,
}


for (
    error_name,
    condition,
) in block_8_validation_checks.items():

    if not condition:

        NOTEBOOK_07_BLOCK_8_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited Block 8 operations
# =============================================================================

prohibited_block_8_operations = {
    "zero_grad_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED,

    "backward_pass_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED,

    "optimizer_step_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED,

    "parameter_update_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED,

    "additional_training_incorrectly_executed":
        NOTEBOOK_07_SOCIAL_ADDITIONAL_TRAINING_EXECUTED,

    "psychological_training_incorrectly_executed":
        NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED,

    "factual_training_incorrectly_executed":
        NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED,

    "backbone_training_incorrectly_executed":
        NOTEBOOK_07_BACKBONE_TRAINING_EXECUTED,

    "global_confluent_training_incorrectly_executed":
        NOTEBOOK_07_GLOBAL_CONFLUENT_TRAINING_EXECUTED,

    "group_conditioned_incorrectly_executed":
        NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED,

    "transformative_weights_incorrectly_executed":
        NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED,

    "recurrent_incorrectly_executed":
        NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED,

    "held_out_evaluation_incorrectly_executed":
        NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for (
    error_name,
    operation_executed,
) in prohibited_block_8_operations.items():

    if operation_executed:

        NOTEBOOK_07_BLOCK_8_ERRORS.append(
            error_name
        )


# =============================================================================
# Final Block 8 state
# =============================================================================

NOTEBOOK_07_BLOCK_8_VALID = (
    len(
        NOTEBOOK_07_BLOCK_8_ERRORS
    )
    == 0
)


if not NOTEBOOK_07_BLOCK_8_VALID:

    raise RuntimeError(
        "Notebook 07 Block 8 Social Representation checkpoint "
        "reproducibility validation failed. "
        f"Errors: {NOTEBOOK_07_BLOCK_8_ERRORS}"
    )


NOTEBOOK_07_BLOCK_8_COMPLETE = True


# =============================================================================
# Block summary
# =============================================================================

NOTEBOOK_07_BLOCK_8_SUMMARY = {
    "block":
        NOTEBOOK_07_BLOCK_8,

    "block_name":
        NOTEBOOK_07_BLOCK_8_NAME,

    "version":
        NOTEBOOK_07_BLOCK_8_VERSION,

    "reproducibility_version":
        NOTEBOOK_07_SOCIAL_REPRODUCIBILITY_VERSION,

    "executed_at_utc":
        BLOCK_8_EXECUTED_AT_UTC,

    "checkpoint_type":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE,

    "checkpoint_reloaded":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_RELOADED,

    "metadata_reloaded":
        NOTEBOOK_07_SOCIAL_METADATA_RELOADED,

    "experimental_checkpoint":
        BLOCK_8_CHECKPOINT_EXPERIMENTAL,

    "validated_model_checkpoint":
        BLOCK_8_VALIDATED_MODEL_CHECKPOINT,

    "model_state_restored":
        BLOCK_8_MODEL_STATE_RESTORED,

    "social_matches_runtime":
        BLOCK_8_SOCIAL_MATCHES_RUNTIME,

    "optimizer_reloaded":
        BLOCK_8_OPTIMIZER_RELOADED,

    "optimizer_state_exact":
        BLOCK_8_OPTIMIZER_STATE_EXACT,

    "training_policy_preserved":
        BLOCK_8_TRAINING_POLICY_PRESERVED,

    "loss_families":
        deepcopy(
            BLOCK_8_CHECKPOINT_LOSS_FAMILIES
        ),

    "loss_families_reproduced":
        BLOCK_8_LOSS_FAMILIES_REPRODUCED,

    "expected_total_objective":
        BLOCK_8_EXPECTED_TOTAL_OBJECTIVE,

    "restored_total_objective":
        BLOCK_8_RESTORED_TOTAL_OBJECTIVE,

    "total_objective_reproduced":
        BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED,

    "family_losses_reproduced":
        BLOCK_8_ALL_FAMILY_LOSSES_REPRODUCED,

    "all_parameters_unchanged":
        BLOCK_8_ALL_PARAMETERS_UNCHANGED,

    "method_boundary_preserved":
        BLOCK_8_METHOD_BOUNDARY_PRESERVED,

    "checkpoint_reproducible":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_REPRODUCIBLE,

    "empirical_validity":
        NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED,

    "block_valid":
        NOTEBOOK_07_BLOCK_8_VALID,

    "block_complete":
        NOTEBOOK_07_BLOCK_8_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 07, Block 8: "
    "Social Representation Checkpoint Reload, "
    "Reproducibility and Training-State Validation"
)

print("=" * 72)

print(
    f"Block version                : "
    f"{NOTEBOOK_07_BLOCK_8_VERSION}"
)

print(
    f"Reproducibility version      : "
    f"{NOTEBOOK_07_SOCIAL_REPRODUCIBILITY_VERSION}"
)


print("-" * 72)

print(
    "Persisted artefact reload"
)

print(
    f"Checkpoint reloaded          : "
    f"{NOTEBOOK_07_SOCIAL_CHECKPOINT_RELOADED}"
)

print(
    f"Metadata reloaded            : "
    f"{NOTEBOOK_07_SOCIAL_METADATA_RELOADED}"
)

print(
    f"Checkpoint contract valid    : "
    f"{BLOCK_8_CHECKPOINT_CONTRACT_VALID}"
)

print(
    f"Checkpoint type valid        : "
    f"{BLOCK_8_CHECKPOINT_TYPE_VALID}"
)

print(
    f"Experimental checkpoint      : "
    f"{BLOCK_8_CHECKPOINT_EXPERIMENTAL}"
)

print(
    f"Validated model checkpoint   : "
    f"{BLOCK_8_VALIDATED_MODEL_CHECKPOINT}"
)


print("-" * 72)

print(
    "Model-state reproduction"
)

print(
    f"Model state restored         : "
    f"{BLOCK_8_MODEL_STATE_RESTORED}"
)

print(
    f"Backbone matches checkpoint  : "
    f"{BLOCK_8_BACKBONE_MATCHES_CHECKPOINT}"
)

print(
    f"Global confluent matches     : "
    f"{BLOCK_8_GLOBAL_CONFLUENT_MATCHES_CHECKPOINT}"
)

print(
    f"Psych. matches checkpoint    : "
    f"{BLOCK_8_PSYCHOLOGICAL_MATCHES_CHECKPOINT}"
)

print(
    f"Factual matches checkpoint   : "
    f"{BLOCK_8_FACTUAL_MATCHES_CHECKPOINT}"
)

print(
    f"Social matches checkpoint    : "
    f"{BLOCK_8_SOCIAL_MATCHES_CHECKPOINT}"
)

print(
    f"Social matches runtime       : "
    f"{BLOCK_8_SOCIAL_MATCHES_RUNTIME}"
)

print(
    f"Backbone remains frozen      : "
    f"{BLOCK_8_BACKBONE_FROZEN}"
)

print(
    f"Global confluent frozen      : "
    f"{BLOCK_8_GLOBAL_CONFLUENT_FROZEN}"
)

print(
    f"Psychological head frozen    : "
    f"{BLOCK_8_PSYCHOLOGICAL_HEAD_FROZEN}"
)

print(
    f"Factual head frozen          : "
    f"{BLOCK_8_FACTUAL_HEAD_FROZEN}"
)

print(
    f"Social head trainable        : "
    f"{BLOCK_8_SOCIAL_HEAD_TRAINABLE}"
)

print(
    f"Social parameter count       : "
    f"{BLOCK_8_SOCIAL_TRAINABLE_PARAMETER_COUNT}"
)

print(
    f"Trainability scope valid     : "
    f"{BLOCK_8_TRAINABILITY_SCOPE_VALID}"
)


print("-" * 72)

print(
    "Optimiser-state recovery"
)

print(
    f"Optimiser reloaded           : "
    f"{BLOCK_8_OPTIMIZER_RELOADED}"
)

print(
    f"Optimiser type               : "
    f"{BLOCK_8_SOCIAL_CHECKPOINT['optimizer_type']}"
)

print(
    f"Learning rate                : "
    f"{BLOCK_8_SOCIAL_CHECKPOINT['learning_rate']}"
)

print(
    f"Weight decay                 : "
    f"{BLOCK_8_SOCIAL_CHECKPOINT['weight_decay']}"
)

print(
    f"Optimiser parameters         : "
    f"{BLOCK_8_OPTIMIZER_PARAMETER_COUNT}"
)

print(
    f"Optimiser state exact        : "
    f"{BLOCK_8_OPTIMIZER_STATE_EXACT}"
)

print(
    f"Optimiser scope valid        : "
    f"{BLOCK_8_OPTIMIZER_SCOPE_VALID}"
)


print("-" * 72)

print(
    "Training-policy reproduction"
)

print(
    f"Training articles            : "
    f"{BLOCK_8_TRAINING_ARTICLE_COUNT}"
)

print(
    f"Training sentences           : "
    f"{BLOCK_8_TRAINING_SENTENCE_COUNT}"
)

print(
    f"Validation sentences         : "
    f"{BLOCK_8_VALIDATION_SENTENCE_COUNT}"
)

print(
    f"Test sentences               : "
    f"{BLOCK_8_TEST_SENTENCE_COUNT}"
)

print(
    f"Epochs                       : "
    f"{BLOCK_8_TRAINING_EPOCH_COUNT}"
)

print(
    f"Within-article shuffle       : "
    f"{BLOCK_8_SOCIAL_CHECKPOINT['within_article_shuffle']}"
)

print(
    f"Article sequence preserved   : "
    f"{BLOCK_8_SOCIAL_CHECKPOINT['article_sequence_preserved']}"
)

print(
    f"Maximum gradient norm        : "
    f"{BLOCK_8_MAXIMUM_GRADIENT_NORM:.4f}"
)

print(
    f"Recorded max pre-clip norm   : "
    f"{BLOCK_8_RECORDED_MAXIMUM_PRECLIP_GRADIENT_NORM:.8f}"
)

print(
    f"Objective weights            : "
    f"{BLOCK_8_SOCIAL_CHECKPOINT['objective_weights']}"
)

print(
    f"Loss families                : "
    f"{BLOCK_8_CHECKPOINT_LOSS_FAMILIES}"
)

print(
    f"Loss families reproduced     : "
    f"{BLOCK_8_LOSS_FAMILIES_REPRODUCED}"
)

print(
    f"Training policy preserved    : "
    f"{BLOCK_8_TRAINING_POLICY_PRESERVED}"
)


print("-" * 72)

print(
    "Post-training objective reproduction"
)

print(
    f"Controlled forward executed  : "
    f"{NOTEBOOK_07_SOCIAL_RESTORED_FORWARD_EXECUTED}"
)

print(
    f"Objective recalculated       : "
    f"{NOTEBOOK_07_SOCIAL_RESTORED_OBJECTIVE_CALCULATED}"
)

print(
    f"Expected total objective     : "
    f"{BLOCK_8_EXPECTED_TOTAL_OBJECTIVE:.8f}"
)

print(
    f"Restored total objective     : "
    f"{BLOCK_8_RESTORED_TOTAL_OBJECTIVE:.8f}"
)

print(
    f"Total objective reproduced   : "
    f"{BLOCK_8_TOTAL_OBJECTIVE_REPRODUCED}"
)


for dimension_name in (
    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
):

    print(
        f"{dimension_name:<31}: "
        f"{BLOCK_8_SOCIAL_CHECKPOINT['final_family_losses'][dimension_name]:.8f}"
        f" / "
        f"{BLOCK_8_RESTORED_FAMILY_LOSSES[dimension_name]:.8f}"
    )


print(
    f"All family losses reproduced : "
    f"{BLOCK_8_ALL_FAMILY_LOSSES_REPRODUCED}"
)

print(
    f"Deferred dimensions excluded : "
    f"{BLOCK_8_DEFERRED_DIMENSIONS_EXCLUDED}"
)


print("-" * 72)

print(
    "Methodological boundary"
)

print(
    f"Experimental checkpoint      : "
    f"{BLOCK_8_CHECKPOINT_EXPERIMENTAL}"
)

print(
    f"Validated model checkpoint   : "
    f"{BLOCK_8_VALIDATED_MODEL_CHECKPOINT}"
)

print(
    f"Method boundary preserved    : "
    f"{BLOCK_8_METHOD_BOUNDARY_PRESERVED}"
)

print(
    f"Metadata/checkpoint aligned  : "
    f"{BLOCK_8_METADATA_CHECKPOINT_ALIGNED}"
)

print(
    f"All parameters unchanged     : "
    f"{BLOCK_8_ALL_PARAMETERS_UNCHANGED}"
)

print(
    f"Social gradients absent      : "
    f"{BLOCK_8_SOCIAL_GRADIENTS_ABSENT}"
)

print(
    f"Empirical validity claimed   : "
    f"{NOTEBOOK_07_EMPIRICAL_VALIDITY_ESTABLISHED}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Zero grad executed           : "
    f"{NOTEBOOK_07_SOCIAL_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{NOTEBOOK_07_SOCIAL_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{NOTEBOOK_07_SOCIAL_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{NOTEBOOK_07_SOCIAL_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Additional training executed : "
    f"{NOTEBOOK_07_SOCIAL_ADDITIONAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{NOTEBOOK_07_PSYCHOLOGICAL_TRAINING_EXECUTED}"
)

print(
    f"Factual retraining           : "
    f"{NOTEBOOK_07_FACTUAL_TRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{NOTEBOOK_07_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative executed      : "
    f"{NOTEBOOK_07_TRANSFORMATIVE_MECHANISM_EXECUTED}"
)

print(
    f"Transformative weights active: "
    f"{NOTEBOOK_07_TRANSFORMATIVE_WEIGHTS_EXECUTED}"
)

print(
    f"Recurrent executed           : "
    f"{NOTEBOOK_07_RECURRENT_MECHANISM_EXECUTED}"
)

print(
    f"Held-out evaluation executed : "
    f"{NOTEBOOK_07_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Checkpoint reproducible      : "
    f"{NOTEBOOK_07_SOCIAL_CHECKPOINT_REPRODUCIBLE}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_07_BLOCK_8_VALID}"
)

print(
    f"Block 8 complete             : "
    f"{NOTEBOOK_07_BLOCK_8_COMPLETE}"
)


print("=" * 72)


print(
    "Persisted controlled Social Representation training state "
    "reloaded and reproduced successfully."
)

print(
    "Fresh backbone, mandatory global confluent, Psychological "
    "Representation, Factual Representation and Social Representation "
    "instances were reconstructed independently and restored from the "
    "persisted Block 7 checkpoint."
)

print(
    "The restored Social Representation state exactly matches both the "
    "persisted checkpoint and the trained Block 7 runtime Social "
    "Representation state."
)

print(
    "The backbone, mandatory global confluent path, Psychological "
    "Representation and Factual Representation reproduce their persisted "
    "states exactly and remain frozen."
)

print(
    "The restored Social Representation remains the only trainable "
    "representation module and preserves the validated "
    f"{BLOCK_8_SOCIAL_TRAINABLE_PARAMETER_COUNT:,}-parameter scope."
)

print(
    "The persisted AdamW optimiser state was restored exactly and remains "
    "scoped exclusively to the Social Representation head."
)

print(
    f"The restored model reproduces all "
    f"{len(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)} active Social "
    "Representation family objectives and their combined objective "
    "within the configured numerical tolerance."
)

print(
    f"{len(NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS)} Social Representation "
    "dimension(s) remain structurally present but outside the current "
    "controlled objective under the persisted activation contract."
)

print(
    f"The {BLOCK_8_TRAINING_EPOCH_COUNT}-epoch training policy, persisted "
    "active-objective weighting and maximum gradient norm of "
    f"{BLOCK_8_MAXIMUM_GRADIENT_NORM:.4f} remain preserved."
)

print(
    "The checkpoint remains explicitly classified as a controlled "
    "experimental Social Representation training checkpoint rather than "
    "a validated model checkpoint."
)

print(
    "The optional group-conditioned path, Transformative Mechanism, "
    "Transformative Weights and recurrent mechanism remain outside the "
    "Social Representation training boundary."
)

print(
    "No zero-gradient operation, backward pass, optimiser step, parameter "
    "update or additional training was performed by Block 8."
)

print(
    "Successful Block 8 completion establishes Social Representation "
    "checkpoint portability and training-state reproducibility, not "
    "generalisation or empirical validity."
)

print(
    "Block 9 may proceed to Social Representation scope audit, "
    "persistent Notebook 07 -> Notebook 08 handover and "
    "Notebook 07 completion."
)

print("=" * 72)

========================================================================
Media AI — Notebook 07, Block 8: Social Representation Checkpoint Reload, Reproducibility and Training-State Validation
========================================================================
Block version                : 1.1
Reproducibility version      : 1.1
------------------------------------------------------------------------
Persisted artefact reload
Checkpoint reloaded          : True
Metadata reloaded            : True
Checkpoint contract valid    : True
Checkpoint type valid        : True
Experimental checkpoint      : True
Validated model checkpoint   : False
------------------------------------------------------------------------
Model-state reproduction
Model state restored         : True
Backbone matches checkpoint  : True
Global confluent matches     : True
Psych. matches checkpoint    : True
Factual matches checkpoint   : True
Social matches checkpoint    : True
Social matches runtime       : True
Backbone remains frozen      : True
Global confluent frozen      : True
Psychological head frozen    : True
Factual head frozen          : True
Social head trainable        : True
Social parameter count       : 34055
Trainability scope valid     : True
------------------------------------------------------------------------
Optimiser-state recovery
Optimiser reloaded           : True
Optimiser type               : AdamW
Learning rate                : 0.001
Weight decay                 : 0.0001
Optimiser parameters         : 34055
Optimiser state exact        : True
Optimiser scope valid        : True
------------------------------------------------------------------------
Training-policy reproduction
Training articles            : 3
Training sentences           : 54
Validation sentences         : 0
Test sentences               : 0
Epochs                       : 10
Within-article shuffle       : False
Article sequence preserved   : True
Maximum gradient norm        : 1.0000
Recorded max pre-clip norm   : 7.01310616
Objective weights            : {'interpersonal_cohesion': 0.25, 'economic_cohesion': 0.25, 'political_cohesion': 0.25, 'group_collective_cohesion': 0.25}
Loss families                : {'interpersonal_cohesion': 'masked_mean_squared_error', 'economic_cohesion': 'masked_mean_squared_error', 'political_cohesion': 'masked_mean_squared_error', 'group_collective_cohesion': 'masked_mean_squared_error'}
Loss families reproduced     : True
Training policy preserved    : True
------------------------------------------------------------------------
Post-training objective reproduction
Controlled forward executed  : True
Objective recalculated       : True
Expected total objective     : 0.01394366
Restored total objective     : 0.01394366
Total objective reproduced   : True
interpersonal_cohesion         : 0.01065167 / 0.01065167
economic_cohesion              : 0.01577149 / 0.01577149
political_cohesion             : 0.01012826 / 0.01012826
group_collective_cohesion      : 0.01922321 / 0.01922321
All family losses reproduced : True
Deferred dimensions excluded : True
------------------------------------------------------------------------
Methodological boundary
Experimental checkpoint      : True
Validated model checkpoint   : False
Method boundary preserved    : True
Metadata/checkpoint aligned  : True
All parameters unchanged     : True
Social gradients absent      : True
Empirical validity claimed   : False
------------------------------------------------------------------------
Execution boundary
Zero grad executed           : False
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
Additional training executed : False
Psychological retraining     : False
Factual retraining           : False
Group-conditioned executed   : False
Transformative executed      : False
Transformative weights active: False
Recurrent executed           : False
Held-out evaluation executed : False
Checkpoint reproducible      : True
Block valid                  : True
Block 8 complete             : True
========================================================================
Persisted controlled Social Representation training state reloaded and reproduced successfully.
Fresh backbone, mandatory global confluent, Psychological Representation, Factual Representation and Social Representation instances were reconstructed independently and restored from the persisted Block 7 checkpoint.
The restored Social Representation state exactly matches both the persisted checkpoint and the trained Block 7 runtime Social Representation state.
The backbone, mandatory global confluent path, Psychological Representation and Factual Representation reproduce their persisted states exactly and remain frozen.
The restored Social Representation remains the only trainable representation module and preserves the validated 34,055-parameter scope.
The persisted AdamW optimiser state was restored exactly and remains scoped exclusively to the Social Representation head.
The restored model reproduces all 4 active Social Representation family objectives and their combined objective within the configured numerical tolerance.
3 Social Representation dimension(s) remain structurally present but outside the current controlled objective under the persisted activation contract.
The 10-epoch training policy, persisted active-objective weighting and maximum gradient norm of 1.0000 remain preserved.
The checkpoint remains explicitly classified as a controlled experimental Social Representation training checkpoint rather than a validated model checkpoint.
The optional group-conditioned path, Transformative Mechanism, Transformative Weights and recurrent mechanism remain outside the Social Representation training boundary.
No zero-gradient operation, backward pass, optimiser step, parameter update or additional training was performed by Block 8.
Successful Block 8 completion establishes Social Representation checkpoint portability and training-state reproducibility, not generalisation or empirical validity.
Block 9 may proceed to Social Representation scope audit, persistent Notebook 07 -> Notebook 08 handover and Notebook 07 completion.
========================================================================

## Block 9 — Social Representation Scope Audit, Persistent Handover and Notebook 07 Completion

This block closes **Notebook 07 — Social Representation** by auditing the completed Social Representation pipeline, persisting the validated trained state and constructing the handover required to initialise **Notebook 08 — Transformative Mechanism** independently.

The block does not introduce a new Social Representation objective, perform additional training or extend the semantic ontology. Its purpose is to verify that the results established by the preceding Notebook 07 blocks remain internally consistent, reproducible and correctly bounded before the project proceeds to the Transformative Mechanism.

The audit verifies the complete Notebook 07 execution chain, including the inherited Notebook 06 → Notebook 07 contract, the supplemental seven-dimensional Social Representation ontology, explicit sentence-level social supervision, target availability and variability analysis, controlled objective activation, deterministic model restoration, parameter-freezing policy, controlled optimisation and the final reproducible Social Representation checkpoint.

The Social Representation retains all seven structural dimensions:

- **S1 — interpersonal cohesion**
- **S2 — economic cohesion**
- **S3 — political cohesion**
- **S4 — religious cohesion**
- **S5 — group/collective cohesion**
- **S6 — institutional-role relation**
- **S7 — public/audience relation**

Dimensions remain distinguished between **structurally present**, **currently active** and **currently deferred**. Deferred dimensions are not removed from the representation and are not interpreted as negative or zero-valued supervision. Their status continues to reflect the availability and variability of the explicit supervision established earlier in Notebook 07.

The block confirms that only the dimensions satisfying the controlled activation contract participated in the current Social Representation optimisation. Dimensions deferred because of insufficient supervision, unavailable supervision or zero target variance remain part of the seven-dimensional semantic contract and may become trainable when suitable supervision is available.

The inherited **768-dimensional contextual sentence representation**, **768-dimensional backbone interface** and **256-dimensional mandatory global confluent representation** remain part of the validated forward architecture. The completed Psychological Representation and Factual Representation remain frozen, and the Social Representation remains isolated as its own representation head. No trained factual or psychological parameters are reinterpreted as social parameters.

The block verifies that the final Social Representation checkpoint can be restored reproducibly together with the metadata and target contract required to understand its training state. The checkpoint remains explicitly classified according to the controlled experimental scope established in Notebook 07 and must not be presented as evidence of held-out generalisation or empirical validity unless such evaluation has actually been performed.

The optional **group-conditioned path** remains architecturally available but inactive and deferred to **Notebook 10**. Notebook 07 therefore continues to use the mandatory global confluent path as its operative conditioning route.

The **Transformative Mechanism** remains outside the Social Representation optimisation boundary. No Transformative Weights or recurrent mechanism are activated by this completion block. These components remain reserved for their designated subsequent notebooks.

A persistent **Notebook 07 → Notebook 08 handover** is created and read back from persistent storage. The handover records the validated Notebook 07 completion state and references the artefacts required by Notebook 08, including the Social Representation checkpoint, training metadata, target contract and inherited representation contracts.

The handover establishes the starting policy for Notebook 08:

- the backbone remains frozen by default;
- the mandatory global confluent representation remains frozen;
- the completed Psychological Representation remains frozen;
- the completed Factual Representation remains frozen;
- the completed Social Representation remains frozen by default;
- the group-conditioned path remains deferred to Notebook 10; and
- Notebook 08 may initialise the Transformative Mechanism without retraining the completed representation paths.

Block 9 itself performs **no new optimisation**. It does not create a new training objective, calculate a new supervised training loss, create a training optimiser, execute a backward pass, perform an optimiser step or modify model parameters. Any forward operations required strictly for reproducibility or checkpoint validation must remain non-training validation operations.

Completion of this block establishes that **Notebook 07 — Social Representation is complete within its controlled experimental scope** and that its validated state has been transferred persistently to Notebook 08.

It does **not** establish full training coverage across all seven social dimensions, held-out generalisation, empirical validity, completion of the Transformative Mechanism, activation of Transformative Weights, execution of the recurrent mechanism, completion of the group-conditioned path or completion of the full Media AI Version 1 project.

After successful validation and read-back of the persistent handover, **Notebook 08 — Transformative Mechanism** may initialise independently from the persisted Notebook 07 state.

In [26]:
# =============================================================================
# Media AI — Notebook 07
# Block 9: Social Representation Scope Audit,
#          Persistent Handover and Notebook 07 Completion
# =============================================================================

from copy import deepcopy
from datetime import datetime, timezone

import io
import json
import math

import numpy as np
import pandas as pd
import torch

from googleapiclient.http import (
    MediaIoBaseDownload,
    MediaIoBaseUpload,
)


# =============================================================================
# Dependency checks
# =============================================================================

required_block_9_objects = [
    # -------------------------------------------------------------------------
    # Notebook 07 block chain
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_BLOCK_1_COMPLETE",
    "NOTEBOOK_07_BLOCK_1_VALID",
    "NOTEBOOK_07_BLOCK_2_COMPLETE",
    "NOTEBOOK_07_BLOCK_2_VALID",
    "NOTEBOOK_07_BLOCK_3_COMPLETE",
    "NOTEBOOK_07_BLOCK_3_VALID",
    "NOTEBOOK_07_BLOCK_4_COMPLETE",
    "NOTEBOOK_07_BLOCK_4_VALID",
    "NOTEBOOK_07_BLOCK_5_COMPLETE",
    "NOTEBOOK_07_BLOCK_5_VALID",
    "NOTEBOOK_07_BLOCK_6_COMPLETE",
    "NOTEBOOK_07_BLOCK_6_VALID",
    "NOTEBOOK_07_BLOCK_7_COMPLETE",
    "NOTEBOOK_07_BLOCK_7_VALID",
    "NOTEBOOK_07_BLOCK_8_COMPLETE",
    "NOTEBOOK_07_BLOCK_8_VALID",

    # -------------------------------------------------------------------------
    # Persistent storage
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_DRIVE_SERVICE",

    # -------------------------------------------------------------------------
    # Canonical identity
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_SENTENCE_IDS",
    "NOTEBOOK_07_SENTENCE_COUNT",
    "NOTEBOOK_07_ARTICLE_COUNT",

    # -------------------------------------------------------------------------
    # Social semantic contract
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_SOCIAL_DIMENSION_IDS",
    "NOTEBOOK_07_SOCIAL_DIMENSION_ORDER",
    "NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_ACTIVE_INDICES",
    "NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS",
    "NOTEBOOK_07_SOCIAL_DEFERRED_INDICES",
    "NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS",
    "NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES",
    "NOTEBOOK_07_SOCIAL_DIMENSION_DEFERRAL_REASON",
    "NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID",

    # -------------------------------------------------------------------------
    # Model / architecture contract
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_BACKBONE_INTERFACE_DIM",
    "NOTEBOOK_07_GLOBAL_CONFLUENT_DIM",
    "NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM",
    "NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM",
    "NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY",
    "NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT",

    "NOTEBOOK_07_BACKBONE_FROZEN_MODULE",
    "NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE",
    "NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE",
    "NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE",
    "NOTEBOOK_07_SOCIAL_HEAD",

    # -------------------------------------------------------------------------
    # Social training artefacts
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE",
    "NOTEBOOK_07_SOCIAL_CHECKPOINT_VERSION",
    "NOTEBOOK_07_SOCIAL_CHECKPOINT_FILENAME",
    "NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID",

    "NOTEBOOK_07_SOCIAL_METADATA_FILENAME",
    "NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID",

    "NOTEBOOK_07_SOCIAL_VALIDATED_MODEL_CHECKPOINT",
    "NOTEBOOK_07_SOCIAL_CHECKPOINT_READBACK_VALID",
    "NOTEBOOK_07_SOCIAL_METADATA_READBACK_VALID",

    # -------------------------------------------------------------------------
    # Training policy / state
    # -------------------------------------------------------------------------
    "NOTEBOOK_07_SOCIAL_TRAINING_POLICY_VERSION",
    "NOTEBOOK_07_SOCIAL_TRAINING_EPOCHS",
    "NOTEBOOK_07_SOCIAL_WITHIN_ARTICLE_SHUFFLE",
    "NOTEBOOK_07_SOCIAL_ARTICLE_SEQUENCE_PRESERVED",
    "NOTEBOOK_07_SOCIAL_MAXIMUM_GRADIENT_NORM",

    "NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE",
    "NOTEBOOK_07_SOCIAL_LEARNING_RATE",
    "NOTEBOOK_07_SOCIAL_WEIGHT_DECAY",
    "BLOCK_7_TRAINING_ARTICLE_COUNT",
    "BLOCK_7_TRAINING_SENTENCE_COUNT",
    "BLOCK_7_VALIDATION_SENTENCE_COUNT",
    "BLOCK_7_TEST_SENTENCE_COUNT",

    # -------------------------------------------------------------------------
    # Contextual representation
    # -------------------------------------------------------------------------
    "BLOCK_5_REPRESENTATION_DRIVE_FILE_ID",
]


missing_block_9_objects = [
    object_name
    for object_name
    in required_block_9_objects
    if object_name not in globals()
]


if missing_block_9_objects:

    raise NameError(
        "Notebook 07 Block 9 prerequisites are not initialised. "
        f"Missing: {missing_block_9_objects}"
    )


# =============================================================================
# Complete/valid chain validation
# =============================================================================

BLOCK_9_PREVIOUS_BLOCKS_COMPLETE = all(
    globals()[
        f"NOTEBOOK_07_BLOCK_{block_number}_COMPLETE"
    ]
    for block_number
    in range(
        1,
        9,
    )
)


BLOCK_9_PREVIOUS_BLOCKS_VALID = all(
    globals()[
        f"NOTEBOOK_07_BLOCK_{block_number}_VALID"
    ]
    for block_number
    in range(
        1,
        9,
    )
)


if not BLOCK_9_PREVIOUS_BLOCKS_COMPLETE:

    raise RuntimeError(
        "Notebook 07 Blocks 1–8 must all be complete before Block 9."
    )


if not BLOCK_9_PREVIOUS_BLOCKS_VALID:

    raise RuntimeError(
        "Notebook 07 Blocks 1–8 must all be valid before Block 9."
    )


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_07_BLOCK_9 = 9

NOTEBOOK_07_BLOCK_9_NAME = (
    "Social Representation Scope Audit, "
    "Persistent Handover and Notebook 07 Completion"
)

NOTEBOOK_07_BLOCK_9_VERSION = "1.2"

NOTEBOOK_07_TO_08_HANDOVER_VERSION = "1.2"

NOTEBOOK_07_TO_08_HANDOVER_FILENAME = (
    "notebook_07_to_08_handover.json"
)


BLOCK_9_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Block 9 execution boundary
# =============================================================================
#
# These are BLOCK-LOCAL execution flags.
#
# They deliberately do not overwrite the historical Notebook 07 training
# state established by Blocks 6–8.
# =============================================================================

BLOCK_9_FORWARD_PASS_EXECUTED = False

BLOCK_9_SUPERVISED_LOSS_CALCULATED = False

BLOCK_9_OPTIMIZER_CREATED = False

BLOCK_9_ZERO_GRAD_EXECUTED = False

BLOCK_9_BACKWARD_PASS_EXECUTED = False

BLOCK_9_OPTIMIZER_STEP_EXECUTED = False

BLOCK_9_PARAMETER_UPDATE_EXECUTED = False

BLOCK_9_ADDITIONAL_SOCIAL_TRAINING_EXECUTED = False

BLOCK_9_PSYCHOLOGICAL_RETRAINING_EXECUTED = False

BLOCK_9_FACTUAL_RETRAINING_EXECUTED = False

BLOCK_9_BACKBONE_TRAINING_EXECUTED = False

BLOCK_9_GLOBAL_CONFLUENT_TRAINING_EXECUTED = False

BLOCK_9_GROUP_CONDITIONED_PATH_EXECUTED = False

BLOCK_9_TRANSFORMATIVE_MECHANISM_EXECUTED = False

BLOCK_9_TRANSFORMATIVE_WEIGHTS_EXECUTED = False

BLOCK_9_RECURRENT_MECHANISM_EXECUTED = False

BLOCK_9_HELD_OUT_EVALUATION_EXECUTED = False

BLOCK_9_EMPIRICAL_VALIDITY_ESTABLISHED = False


# =============================================================================
# Canonical identity audit
# =============================================================================

BLOCK_9_SENTENCE_IDS_PRESENT = all(
    NOTEBOOK_07_SENTENCE_IDS
)


BLOCK_9_SENTENCE_IDS_UNIQUE = (
    len(
        NOTEBOOK_07_SENTENCE_IDS
    )
    ==
    len(
        set(
            NOTEBOOK_07_SENTENCE_IDS
        )
    )
)


BLOCK_9_SENTENCE_COUNT_VALID = (
    len(
        NOTEBOOK_07_SENTENCE_IDS
    )
    ==
    NOTEBOOK_07_SENTENCE_COUNT
)


BLOCK_9_CANONICAL_IDENTITY_VALID = all(
    [
        NOTEBOOK_07_ARTICLE_COUNT > 0,
        NOTEBOOK_07_SENTENCE_COUNT > 0,
        BLOCK_9_SENTENCE_IDS_PRESENT,
        BLOCK_9_SENTENCE_IDS_UNIQUE,
        BLOCK_9_SENTENCE_COUNT_VALID,
    ]
)


if not BLOCK_9_CANONICAL_IDENTITY_VALID:

    raise RuntimeError(
        "Notebook 07 canonical identity contract is invalid."
    )


# =============================================================================
# Social semantic contract
# =============================================================================
#
# Block 9 audits the current validated Social Representation contract.
# It must not re-declare a pilot-specific active/deferred outcome.
# =============================================================================

BLOCK_9_STRUCTURAL_SOCIAL_DIMENSION_VALID = all(
    [
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM > 0,

        len(
            NOTEBOOK_07_SOCIAL_DIMENSION_IDS
        )
        ==
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

        len(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
        )
        ==
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

        len(
            set(
                NOTEBOOK_07_SOCIAL_DIMENSION_IDS
            )
        )
        ==
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

        len(
            set(
                NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
            )
        )
        ==
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,
    ]
)


BLOCK_9_ACTIVE_DIMENSIONS_VALID = all(
    [
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        )
        ==
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

        all(
            0
            <=
            index
            <
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM

            for index
            in NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
        ),

        all(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER[
                index
            ]
            ==
            dimension_name

            for (
                dimension_name,
                index,
            ) in zip(
                NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS,
                NOTEBOOK_07_SOCIAL_ACTIVE_INDICES,
            )
        ),
    ]
)


BLOCK_9_DEFERRED_DIMENSIONS_VALID = all(
    [
        len(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        )
        ==
        len(
            NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),

        all(
            0
            <=
            index
            <
            NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM

            for index
            in NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
        ),

        all(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER[
                index
            ]
            ==
            dimension_name

            for (
                dimension_name,
                index,
            ) in zip(
                NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS,
                NOTEBOOK_07_SOCIAL_DEFERRED_INDICES,
            )
        ),
    ]
)


BLOCK_9_ACTIVE_DEFERRED_PARTITION_VALID = all(
    [
        set(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ).isdisjoint(
            set(
                NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
            )
        ),

        (
            set(
                NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
            )
            |
            set(
                NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
            )
        )
        ==
        set(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
        ),

        sorted(
            list(
                NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
            )
            +
            list(
                NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
            )
        )
        ==
        list(
            range(
                NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
            )
        ),
    ]
)


BLOCK_9_ACTIVE_LOSS_FAMILY_KEYS_VALID = (
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES.keys()
    )
    ==
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


BLOCK_9_OBJECTIVE_WEIGHT_KEYS_VALID = (
    set(
        NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS.keys()
    )
    ==
    set(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


BLOCK_9_OBJECTIVE_WEIGHT_SUM = float(
    sum(
        float(
            NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS[
                dimension_name
            ]
        )

        for dimension_name
        in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


BLOCK_9_OBJECTIVE_WEIGHTS_VALID = all(
    [
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        )
        >
        0,

        BLOCK_9_OBJECTIVE_WEIGHT_KEYS_VALID,

        all(
            math.isfinite(
                float(
                    NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS[
                        dimension_name
                    ]
                )
            )
            and
            float(
                NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS[
                    dimension_name
                ]
            )
            >
            0.0

            for dimension_name
            in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),

        np.isclose(
            BLOCK_9_OBJECTIVE_WEIGHT_SUM,
            1.0,
            rtol=0.0,
            atol=1e-12,
        ),
    ]
)


BLOCK_9_SOCIAL_SEMANTIC_CONTRACT_VALID = all(
    [
        NOTEBOOK_07_SOCIAL_OBJECTIVE_POLICY_VALID,
        BLOCK_9_STRUCTURAL_SOCIAL_DIMENSION_VALID,
        BLOCK_9_ACTIVE_DIMENSIONS_VALID,
        BLOCK_9_DEFERRED_DIMENSIONS_VALID,
        BLOCK_9_ACTIVE_DEFERRED_PARTITION_VALID,
        BLOCK_9_ACTIVE_LOSS_FAMILY_KEYS_VALID,
        BLOCK_9_OBJECTIVE_WEIGHTS_VALID,
    ]
)


if not BLOCK_9_SOCIAL_SEMANTIC_CONTRACT_VALID:

    raise RuntimeError(
        "Notebook 07 Social Representation semantic contract is invalid."
    )


# =============================================================================
# Deferral semantics
# =============================================================================

BLOCK_9_SOCIAL_DEFERRAL_REASONS = deepcopy(
    NOTEBOOK_07_SOCIAL_DIMENSION_DEFERRAL_REASON
)


BLOCK_9_DEFERRAL_REASONS_VALID = all(
    [
        isinstance(
            BLOCK_9_SOCIAL_DEFERRAL_REASONS,
            dict,
        ),

        set(
            BLOCK_9_SOCIAL_DEFERRAL_REASONS.keys()
        )
        ==
        set(
            NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
        ),

        all(
            BLOCK_9_SOCIAL_DEFERRAL_REASONS.get(
                dimension_name
            )
            is None

            for dimension_name
            in NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),

        all(
            isinstance(
                BLOCK_9_SOCIAL_DEFERRAL_REASONS.get(
                    dimension_name
                ),
                str,
            )
            and
            bool(
                BLOCK_9_SOCIAL_DEFERRAL_REASONS[
                    dimension_name
                ].strip()
            )

            for dimension_name
            in NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        ),
    ]
)


if not BLOCK_9_DEFERRAL_REASONS_VALID:

    raise RuntimeError(
        "Notebook 07 Social Representation deferral semantics "
        "do not reproduce the validated Block 4 policy."
    )


# =============================================================================
# Architecture contract audit
# =============================================================================

BLOCK_9_ARCHITECTURE_DIMENSIONS_VALID = all(
    [
        NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM > 0,
        NOTEBOOK_07_BACKBONE_INTERFACE_DIM > 0,
        NOTEBOOK_07_GLOBAL_CONFLUENT_DIM > 0,
        NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM > 0,
        NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_DIM > 0,
        NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM > 0,
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM > 0,
    ]
)


BLOCK_9_SOCIAL_HEAD_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter
    in NOTEBOOK_07_SOCIAL_HEAD.parameters()
)


BLOCK_9_EXPECTED_SOCIAL_HEAD_PARAMETER_COUNT = (
    NOTEBOOK_07_SOCIAL_TRAINABLE_PARAMETER_COUNT
)


BLOCK_9_SOCIAL_PARAMETER_COUNT_VALID = (
    BLOCK_9_SOCIAL_HEAD_PARAMETER_COUNT
    ==
    BLOCK_9_EXPECTED_SOCIAL_HEAD_PARAMETER_COUNT
)


BLOCK_9_MODEL_ARCHITECTURE_VALID = all(
    [
        NOTEBOOK_07_SOCIAL_MODEL_POLICY_READY,
        BLOCK_9_ARCHITECTURE_DIMENSIONS_VALID,
        BLOCK_9_SOCIAL_PARAMETER_COUNT_VALID,
    ]
)


if not BLOCK_9_MODEL_ARCHITECTURE_VALID:

    raise RuntimeError(
        "Notebook 07 completed Social Representation architecture "
        "is invalid."
    )


# =============================================================================
# Module-state snapshot helper
# =============================================================================

def block_9_snapshot_module(
    module,
):
    """
    Snapshot module parameter values for no-update validation.
    """

    return {
        parameter_name:
            parameter
            .detach()
            .cpu()
            .clone()

        for (
            parameter_name,
            parameter,
        )
        in module.named_parameters()
    }


def block_9_module_matches_snapshot(
    module,
    snapshot,
):
    """
    Require exact parameter-value equality.
    """

    current_parameters = dict(
        module.named_parameters()
    )


    if (
        set(
            current_parameters.keys()
        )
        !=
        set(
            snapshot.keys()
        )
    ):

        return False


    return all(
        torch.equal(
            current_parameters[
                parameter_name
            ]
            .detach()
            .cpu(),

            snapshot[
                parameter_name
            ],
        )

        for parameter_name
        in snapshot
    )


# =============================================================================
# Pre-audit model snapshots
# =============================================================================

BLOCK_9_BACKBONE_BEFORE = (
    block_9_snapshot_module(
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE
    )
)


BLOCK_9_GLOBAL_CONFLUENT_BEFORE = (
    block_9_snapshot_module(
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE
    )
)


BLOCK_9_PSYCHOLOGICAL_BEFORE = (
    block_9_snapshot_module(
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE
    )
)


BLOCK_9_FACTUAL_BEFORE = (
    block_9_snapshot_module(
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE
    )
)


BLOCK_9_SOCIAL_BEFORE = (
    block_9_snapshot_module(
        NOTEBOOK_07_SOCIAL_HEAD
    )
)


# =============================================================================
# Drive helpers
# =============================================================================

def block_9_download_drive_bytes(
    drive_service,
    file_id,
):
    """
    Download one Google Drive file.
    """

    request = (
        drive_service.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


def block_9_json_default(
    value,
):
    """
    JSON serialisation helper.
    """

    if isinstance(
        value,
        np.generic,
    ):

        return value.item()


    if isinstance(
        value,
        np.ndarray,
    ):

        return value.tolist()


    if isinstance(
        value,
        tuple,
    ):

        return list(
            value
        )


    if isinstance(
        value,
        set,
    ):

        return sorted(
            value
        )


    if isinstance(
        value,
        torch.Tensor,
    ):

        if value.numel() == 1:

            return value.detach().cpu().item()


        return value.detach().cpu().tolist()


    raise TypeError(
        f"Object of type {type(value).__name__} "
        "is not JSON serialisable."
    )


# =============================================================================
# Reload final persisted Social Representation checkpoint
# =============================================================================

BLOCK_9_SOCIAL_CHECKPOINT_BYTES = (
    block_9_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID,
    )
)


if not BLOCK_9_SOCIAL_CHECKPOINT_BYTES:

    raise RuntimeError(
        "Persisted Notebook 07 Social Representation checkpoint was empty."
    )


BLOCK_9_SOCIAL_CHECKPOINT = torch.load(
    io.BytesIO(
        BLOCK_9_SOCIAL_CHECKPOINT_BYTES
    ),
    map_location=
        "cpu",
    weights_only=
        False,
)


if not isinstance(
    BLOCK_9_SOCIAL_CHECKPOINT,
    dict,
):

    raise TypeError(
        "Persisted Social Representation checkpoint must be a dictionary."
    )


BLOCK_9_SOCIAL_CHECKPOINT_RELOADED = True


# =============================================================================
# Reload final persisted Social Representation metadata
# =============================================================================

BLOCK_9_SOCIAL_METADATA_BYTES = (
    block_9_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID,
    )
)


if not BLOCK_9_SOCIAL_METADATA_BYTES:

    raise RuntimeError(
        "Persisted Notebook 07 Social Representation metadata was empty."
    )


BLOCK_9_SOCIAL_METADATA = json.loads(
    BLOCK_9_SOCIAL_METADATA_BYTES.decode(
        "utf-8"
    )
)


if not isinstance(
    BLOCK_9_SOCIAL_METADATA,
    dict,
):

    raise TypeError(
        "Persisted Social Representation metadata must be a JSON object."
    )


BLOCK_9_SOCIAL_METADATA_RELOADED = True


# =============================================================================
# Persisted checkpoint contract
# =============================================================================

BLOCK_9_CHECKPOINT_TYPE_VALID = (
    BLOCK_9_SOCIAL_CHECKPOINT.get(
        "checkpoint_type"
    )
    ==
    NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE
)


BLOCK_9_CHECKPOINT_VERSION_VALID = (
    BLOCK_9_SOCIAL_CHECKPOINT.get(
        "checkpoint_version"
    )
    ==
    NOTEBOOK_07_SOCIAL_CHECKPOINT_VERSION
)


BLOCK_9_CHECKPOINT_NOTEBOOK_VALID = (
    BLOCK_9_SOCIAL_CHECKPOINT.get(
        "notebook"
    )
    ==
    NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
)


BLOCK_9_CHECKPOINT_ACTIVE_DIMENSIONS_VALID = (
    tuple(
        BLOCK_9_SOCIAL_CHECKPOINT.get(
            "active_dimensions",
            [],
        )
    )
    ==
    tuple(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


BLOCK_9_CHECKPOINT_ACTIVE_INDICES_VALID = (
    tuple(
        BLOCK_9_SOCIAL_CHECKPOINT.get(
            "active_indices",
            [],
        )
    )
    ==
    tuple(
        NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
    )
)


BLOCK_9_CHECKPOINT_DEFERRED_DIMENSIONS_VALID = (
    tuple(
        BLOCK_9_SOCIAL_CHECKPOINT.get(
            "deferred_dimensions",
            [],
        )
    )
    ==
    tuple(
        NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
    )
)


BLOCK_9_CHECKPOINT_DEFERRED_INDICES_VALID = (
    tuple(
        BLOCK_9_SOCIAL_CHECKPOINT.get(
            "deferred_indices",
            [],
        )
    )
    ==
    tuple(
        NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
    )
)


BLOCK_9_CHECKPOINT_SOCIAL_STATE_PRESENT = (
    isinstance(
        BLOCK_9_SOCIAL_CHECKPOINT.get(
            "social_head_state_dict"
        ),
        dict,
    )
    and
    bool(
        BLOCK_9_SOCIAL_CHECKPOINT.get(
            "social_head_state_dict"
        )
    )
)


BLOCK_9_CHECKPOINT_INHERITED_STATES_PRESENT = all(
    isinstance(
        BLOCK_9_SOCIAL_CHECKPOINT.get(
            state_key
        ),
        dict,
    )
    and
    bool(
        BLOCK_9_SOCIAL_CHECKPOINT.get(
            state_key
        )
    )

    for state_key
    in (
        "backbone_state_dict",
        "global_confluent_state_dict",
        "psychological_head_state_dict",
        "factual_head_state_dict",
    )
)


BLOCK_9_CHECKPOINT_OPTIMIZER_STATE_PRESENT = (
    isinstance(
        BLOCK_9_SOCIAL_CHECKPOINT.get(
            "optimizer_state_dict"
        ),
        dict,
    )
)


BLOCK_9_CHECKPOINT_CONTEXTUAL_REFERENCE_VALID = (
    BLOCK_9_SOCIAL_CHECKPOINT.get(
        "contextual_representation_drive_file_id"
    )
    ==
    BLOCK_5_REPRESENTATION_DRIVE_FILE_ID
)


# =============================================================================
# Methodological boundary
# =============================================================================

BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY = (
    BLOCK_9_SOCIAL_CHECKPOINT.get(
        "methodological_boundary",
        {},
    )
)


BLOCK_9_CHECKPOINT_BACKBONE_UNTRAINED = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "backbone_trained"
    )
    is False
)


BLOCK_9_CHECKPOINT_GLOBAL_CONFLUENT_UNTRAINED = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "global_confluent_trained"
    )
    is False
)


BLOCK_9_CHECKPOINT_PSYCHOLOGICAL_UNTRAINED = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "psychological_representation_trained"
    )
    is False
)


BLOCK_9_CHECKPOINT_FACTUAL_UNTRAINED = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "factual_representation_trained"
    )
    is False
)


BLOCK_9_CHECKPOINT_SOCIAL_TRAINED = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "social_representation_trained"
    )
    is True
)


BLOCK_9_CHECKPOINT_GROUP_PATH_INACTIVE = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "group_conditioned_path_executed"
    )
    is False
)


BLOCK_9_CHECKPOINT_TRANSFORMATIVE_INACTIVE = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "transformative_mechanism_executed"
    )
    is False
)


BLOCK_9_CHECKPOINT_TRANSFORMATIVE_WEIGHTS_INACTIVE = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "transformative_weights_active"
    )
    is False
)


BLOCK_9_CHECKPOINT_RECURRENT_INACTIVE = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "recurrent_mechanism_executed"
    )
    is False
)


BLOCK_9_CHECKPOINT_HELD_OUT_EVALUATION_FALSE = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "held_out_evaluation_executed"
    )
    is False
)


BLOCK_9_CHECKPOINT_VALIDATED_MODEL_FALSE = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "validated_model_checkpoint"
    )
    is False
)


BLOCK_9_CHECKPOINT_EMPIRICAL_VALIDITY_FALSE = (
    BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY.get(
        "empirical_validity"
    )
    is False
)


BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY_VALID = all(
    [
        BLOCK_9_CHECKPOINT_BACKBONE_UNTRAINED,
        BLOCK_9_CHECKPOINT_GLOBAL_CONFLUENT_UNTRAINED,
        BLOCK_9_CHECKPOINT_PSYCHOLOGICAL_UNTRAINED,
        BLOCK_9_CHECKPOINT_FACTUAL_UNTRAINED,
        BLOCK_9_CHECKPOINT_SOCIAL_TRAINED,
        BLOCK_9_CHECKPOINT_GROUP_PATH_INACTIVE,
        BLOCK_9_CHECKPOINT_TRANSFORMATIVE_INACTIVE,
        BLOCK_9_CHECKPOINT_TRANSFORMATIVE_WEIGHTS_INACTIVE,
        BLOCK_9_CHECKPOINT_RECURRENT_INACTIVE,
        BLOCK_9_CHECKPOINT_HELD_OUT_EVALUATION_FALSE,
        BLOCK_9_CHECKPOINT_VALIDATED_MODEL_FALSE,
        BLOCK_9_CHECKPOINT_EMPIRICAL_VALIDITY_FALSE,
    ]
)


# =============================================================================
# Persisted Social checkpoint validation
# =============================================================================

BLOCK_9_SOCIAL_CHECKPOINT_CONTRACT_VALID = all(
    [
        BLOCK_9_CHECKPOINT_TYPE_VALID,
        BLOCK_9_CHECKPOINT_VERSION_VALID,
        BLOCK_9_CHECKPOINT_NOTEBOOK_VALID,
        BLOCK_9_CHECKPOINT_ACTIVE_DIMENSIONS_VALID,
        BLOCK_9_CHECKPOINT_ACTIVE_INDICES_VALID,
        BLOCK_9_CHECKPOINT_DEFERRED_DIMENSIONS_VALID,
        BLOCK_9_CHECKPOINT_DEFERRED_INDICES_VALID,
        BLOCK_9_CHECKPOINT_SOCIAL_STATE_PRESENT,
        BLOCK_9_CHECKPOINT_INHERITED_STATES_PRESENT,
        BLOCK_9_CHECKPOINT_OPTIMIZER_STATE_PRESENT,
        BLOCK_9_CHECKPOINT_CONTEXTUAL_REFERENCE_VALID,
        BLOCK_9_CHECKPOINT_METHODOLOGICAL_BOUNDARY_VALID,
    ]
)


if not BLOCK_9_SOCIAL_CHECKPOINT_CONTRACT_VALID:

    raise RuntimeError(
        "Persisted Notebook 07 Social Representation checkpoint "
        "failed the Block 9 completion audit."
    )


# =============================================================================
# Metadata contract
# =============================================================================

BLOCK_9_METADATA_TYPE_VALID = (
    BLOCK_9_SOCIAL_METADATA.get(
        "metadata_type"
    )
    ==
    "media_ai_controlled_social_representation_training_metadata"
)


BLOCK_9_METADATA_CHECKPOINT_TYPE_VALID = (
    BLOCK_9_SOCIAL_METADATA.get(
        "checkpoint_type"
    )
    ==
    NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE
)


BLOCK_9_METADATA_VALIDATED_MODEL_FALSE = (
    BLOCK_9_SOCIAL_METADATA.get(
        "validated_model_checkpoint"
    )
    is False
)


# -----------------------------------------------------------------------------
# Metadata optimiser parameter count
# -----------------------------------------------------------------------------

BLOCK_9_METADATA_OPTIMIZER = (
    BLOCK_9_SOCIAL_METADATA.get(
        "optimizer",
        {},
    )
)


BLOCK_9_METADATA_PARAMETER_COUNT_VALID = (
    BLOCK_9_METADATA_OPTIMIZER.get(
        "parameter_count"
    )
    ==
    BLOCK_9_SOCIAL_HEAD_PARAMETER_COUNT
)


BLOCK_9_SOCIAL_METADATA_CONTRACT_VALID = all(
    [
        BLOCK_9_METADATA_TYPE_VALID,
        BLOCK_9_METADATA_CHECKPOINT_TYPE_VALID,
        BLOCK_9_METADATA_VALIDATED_MODEL_FALSE,
        BLOCK_9_METADATA_PARAMETER_COUNT_VALID,
    ]
)


if not BLOCK_9_SOCIAL_METADATA_CONTRACT_VALID:

    raise RuntimeError(
        "Persisted Notebook 07 Social Representation metadata "
        "failed the Block 9 completion audit."
    )


# =============================================================================
# Existing Block 7 read-back boundary
# =============================================================================

BLOCK_9_BLOCK_7_PERSISTENCE_VALID = all(
    [
        NOTEBOOK_07_SOCIAL_CHECKPOINT_READBACK_VALID,
        NOTEBOOK_07_SOCIAL_METADATA_READBACK_VALID,
        not NOTEBOOK_07_SOCIAL_VALIDATED_MODEL_CHECKPOINT,
    ]
)


if not BLOCK_9_BLOCK_7_PERSISTENCE_VALID:

    raise RuntimeError(
        "Notebook 07 Block 7 persistence contract is invalid."
    )


# =============================================================================
# Block 8 reproducibility boundary
# =============================================================================
#
# Block 8 is authoritative for checkpoint portability/reproducibility.
#
# Different Block 8 revisions may export the detailed reproducibility flag
# under slightly different names. Block 9 accepts those explicit names when
# available; otherwise successful Block 8 completion + validity is treated as
# the authoritative reproducibility boundary.
# =============================================================================

BLOCK_9_BLOCK_8_REPRODUCIBILITY_FLAG = None

BLOCK_9_BLOCK_8_REPRODUCIBILITY_FLAG_SOURCE = None


for candidate_name in (
    "NOTEBOOK_07_SOCIAL_CHECKPOINT_REPRODUCIBLE",
    "NOTEBOOK_07_SOCIAL_REPRODUCIBILITY_VALID",
    "NOTEBOOK_07_SOCIAL_TRAINING_STATE_REPRODUCIBLE",
    "NOTEBOOK_07_CHECKPOINT_REPRODUCIBLE",
    "BLOCK_8_CHECKPOINT_REPRODUCIBLE",
    "BLOCK_8_SOCIAL_CHECKPOINT_REPRODUCIBLE",
    "BLOCK_8_REPRODUCIBILITY_VALID",
):

    if candidate_name not in globals():

        continue


    candidate_value = globals()[
        candidate_name
    ]


    if isinstance(
        candidate_value,
        (
            bool,
            np.bool_,
        ),
    ):

        BLOCK_9_BLOCK_8_REPRODUCIBILITY_FLAG = bool(
            candidate_value
        )


        BLOCK_9_BLOCK_8_REPRODUCIBILITY_FLAG_SOURCE = (
            candidate_name
        )


        break


if BLOCK_9_BLOCK_8_REPRODUCIBILITY_FLAG is None:

    BLOCK_9_BLOCK_8_REPRODUCIBILITY_FLAG = all(
        [
            NOTEBOOK_07_BLOCK_8_COMPLETE,
            NOTEBOOK_07_BLOCK_8_VALID,
        ]
    )


    BLOCK_9_BLOCK_8_REPRODUCIBILITY_FLAG_SOURCE = (
        "NOTEBOOK_07_BLOCK_8_COMPLETE+NOTEBOOK_07_BLOCK_8_VALID"
    )


BLOCK_9_SOCIAL_CHECKPOINT_REPRODUCIBLE = all(
    [
        NOTEBOOK_07_BLOCK_8_COMPLETE,
        NOTEBOOK_07_BLOCK_8_VALID,
        BLOCK_9_BLOCK_8_REPRODUCIBILITY_FLAG,
        BLOCK_9_SOCIAL_CHECKPOINT_CONTRACT_VALID,
        BLOCK_9_SOCIAL_METADATA_CONTRACT_VALID,
    ]
)


if not BLOCK_9_SOCIAL_CHECKPOINT_REPRODUCIBLE:

    raise RuntimeError(
        "Notebook 07 Social Representation checkpoint is not "
        "reproducible under the validated Block 8 boundary."
    )


# =============================================================================
# Current Social runtime-state comparison
# =============================================================================

def block_9_state_dict_exact_match(
    module,
    expected_state_dict,
):
    """
    Compare a runtime module exactly against a persisted state dictionary.
    """

    observed_state_dict = (
        module.state_dict()
    )


    if (
        tuple(
            observed_state_dict.keys()
        )
        !=
        tuple(
            expected_state_dict.keys()
        )
    ):

        return False


    return all(
        torch.equal(
            observed_state_dict[
                parameter_name
            ]
            .detach()
            .cpu(),

            expected_state_dict[
                parameter_name
            ]
            .detach()
            .cpu(),
        )

        for parameter_name
        in expected_state_dict.keys()
    )


BLOCK_9_RUNTIME_SOCIAL_MATCHES_CHECKPOINT = (
    block_9_state_dict_exact_match(
        NOTEBOOK_07_SOCIAL_HEAD,
        BLOCK_9_SOCIAL_CHECKPOINT[
            "social_head_state_dict"
        ],
    )
)


BLOCK_9_RUNTIME_BACKBONE_MATCHES_CHECKPOINT = (
    block_9_state_dict_exact_match(
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE,
        BLOCK_9_SOCIAL_CHECKPOINT[
            "backbone_state_dict"
        ],
    )
)


BLOCK_9_RUNTIME_GLOBAL_MATCHES_CHECKPOINT = (
    block_9_state_dict_exact_match(
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE,
        BLOCK_9_SOCIAL_CHECKPOINT[
            "global_confluent_state_dict"
        ],
    )
)


BLOCK_9_RUNTIME_PSYCHOLOGICAL_MATCHES_CHECKPOINT = (
    block_9_state_dict_exact_match(
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE,
        BLOCK_9_SOCIAL_CHECKPOINT[
            "psychological_head_state_dict"
        ],
    )
)


BLOCK_9_RUNTIME_FACTUAL_MATCHES_CHECKPOINT = (
    block_9_state_dict_exact_match(
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE,
        BLOCK_9_SOCIAL_CHECKPOINT[
            "factual_head_state_dict"
        ],
    )
)


BLOCK_9_RUNTIME_STATE_MATCHES_PERSISTED_CHECKPOINT = all(
    [
        BLOCK_9_RUNTIME_SOCIAL_MATCHES_CHECKPOINT,
        BLOCK_9_RUNTIME_BACKBONE_MATCHES_CHECKPOINT,
        BLOCK_9_RUNTIME_GLOBAL_MATCHES_CHECKPOINT,
        BLOCK_9_RUNTIME_PSYCHOLOGICAL_MATCHES_CHECKPOINT,
        BLOCK_9_RUNTIME_FACTUAL_MATCHES_CHECKPOINT,
    ]
)


if not BLOCK_9_RUNTIME_STATE_MATCHES_PERSISTED_CHECKPOINT:

    raise RuntimeError(
        "Current Notebook 07 runtime model state does not match "
        "the persisted reproducible Social Representation checkpoint."
    )


# =============================================================================
# Training-state audit
# =============================================================================

BLOCK_9_TRAINING_ARTICLE_COUNT = int(
    BLOCK_9_SOCIAL_CHECKPOINT[
        "training_article_count"
    ]
)


BLOCK_9_TRAINING_SENTENCE_COUNT = int(
    BLOCK_9_SOCIAL_CHECKPOINT[
        "training_sentence_count"
    ]
)


BLOCK_9_VALIDATION_SENTENCE_COUNT = int(
    BLOCK_9_SOCIAL_CHECKPOINT[
        "validation_sentence_count"
    ]
)


BLOCK_9_TEST_SENTENCE_COUNT = int(
    BLOCK_9_SOCIAL_CHECKPOINT[
        "test_sentence_count"
    ]
)


BLOCK_9_TRAINING_EPOCH_COUNT = int(
    BLOCK_9_SOCIAL_CHECKPOINT[
        "training_epoch_count"
    ]
)


BLOCK_9_FINAL_SOCIAL_OBJECTIVE = float(
    BLOCK_9_SOCIAL_CHECKPOINT[
        "final_objective"
    ]
)


BLOCK_9_INITIAL_SOCIAL_OBJECTIVE = float(
    BLOCK_9_SOCIAL_CHECKPOINT[
        "initial_objective"
    ]
)


BLOCK_9_SOCIAL_OBJECTIVE_REDUCTION = float(
    BLOCK_9_SOCIAL_CHECKPOINT[
        "objective_reduction"
    ]
)


BLOCK_9_MAXIMUM_PARAMETER_DELTA = float(
    BLOCK_9_SOCIAL_CHECKPOINT[
        "maximum_parameter_delta"
    ]
)


BLOCK_9_MAXIMUM_PRECLIP_GRADIENT_NORM = float(
    BLOCK_9_SOCIAL_CHECKPOINT[
        "maximum_preclip_gradient_norm"
    ]
)


BLOCK_9_TRAINING_VALUES_FINITE = all(
    math.isfinite(
        value
    )

    for value
    in (
        BLOCK_9_INITIAL_SOCIAL_OBJECTIVE,
        BLOCK_9_FINAL_SOCIAL_OBJECTIVE,
        BLOCK_9_SOCIAL_OBJECTIVE_REDUCTION,
        BLOCK_9_MAXIMUM_PARAMETER_DELTA,
        BLOCK_9_MAXIMUM_PRECLIP_GRADIENT_NORM,
    )
)


BLOCK_9_TRAINING_SCOPE_VALID = all(
    [
        BLOCK_9_TRAINING_ARTICLE_COUNT
        ==
        int(
            BLOCK_7_TRAINING_ARTICLE_COUNT
        ),

        BLOCK_9_TRAINING_SENTENCE_COUNT
        ==
        int(
            BLOCK_7_TRAINING_SENTENCE_COUNT
        ),

        BLOCK_9_VALIDATION_SENTENCE_COUNT
        ==
        int(
            BLOCK_7_VALIDATION_SENTENCE_COUNT
        ),

        BLOCK_9_TEST_SENTENCE_COUNT
        ==
        int(
            BLOCK_7_TEST_SENTENCE_COUNT
        ),

        BLOCK_9_TRAINING_EPOCH_COUNT
        ==
        NOTEBOOK_07_SOCIAL_TRAINING_EPOCHS,

        (
            BLOCK_9_SOCIAL_CHECKPOINT.get(
                "within_article_shuffle"
            )
            ==
            NOTEBOOK_07_SOCIAL_WITHIN_ARTICLE_SHUFFLE
        ),

        (
            BLOCK_9_SOCIAL_CHECKPOINT.get(
                "article_sequence_preserved"
            )
            ==
            NOTEBOOK_07_SOCIAL_ARTICLE_SEQUENCE_PRESERVED
        ),

        BLOCK_9_TRAINING_VALUES_FINITE,

        BLOCK_9_MAXIMUM_PARAMETER_DELTA
        >
        0.0,
    ]
)


if not BLOCK_9_TRAINING_SCOPE_VALID:

    raise RuntimeError(
        "Notebook 07 persisted Social Representation training scope "
        "is inconsistent with the validated controlled experiment."
    )


# =============================================================================
# Full training coverage / validation boundaries
# =============================================================================

NOTEBOOK_07_SOCIAL_ALL_DIMENSIONS_TRAINED = all(
    [
        len(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        )
        ==
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

        len(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        )
        ==
        0,
    ]
)


NOTEBOOK_07_SOCIAL_FULL_TRAINING_COVERAGE = (
    NOTEBOOK_07_SOCIAL_ALL_DIMENSIONS_TRAINED
)


NOTEBOOK_07_SOCIAL_GENERALISATION_VALIDATED = False

NOTEBOOK_07_SOCIAL_EMPIRICALLY_VALIDATED = False


BLOCK_9_PARTIAL_SOCIAL_TRAINING_SCOPE_VALID = all(
    [
        (
            len(
                NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
            )
            +
            len(
                NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
            )
        )
        ==
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

        (
            NOTEBOOK_07_SOCIAL_FULL_TRAINING_COVERAGE
            ==
            NOTEBOOK_07_SOCIAL_ALL_DIMENSIONS_TRAINED
        ),

        not NOTEBOOK_07_SOCIAL_GENERALISATION_VALIDATED,
        not NOTEBOOK_07_SOCIAL_EMPIRICALLY_VALIDATED,
        not NOTEBOOK_07_SOCIAL_VALIDATED_MODEL_CHECKPOINT,
    ]
)


# =============================================================================
# Optional artefact references
# =============================================================================

def block_9_first_nonempty_global(
    candidate_names,
):
    """
    Return the first non-empty global value and its name.
    """

    for candidate_name in candidate_names:

        if candidate_name not in globals():

            continue


        candidate_value = globals()[
            candidate_name
        ]


        if candidate_value is None:

            continue


        if (
            isinstance(
                candidate_value,
                str,
            )
            and
            not candidate_value.strip()
        ):

            continue


        return (
            candidate_value,
            candidate_name,
        )


    return (
        None,
        None,
    )


# -----------------------------------------------------------------------------
# Accepted Social supervision / target contract
# -----------------------------------------------------------------------------

(
    BLOCK_9_SOCIAL_TARGET_CONTRACT_DRIVE_FILE_ID,
    BLOCK_9_SOCIAL_TARGET_CONTRACT_ID_SOURCE,
) = block_9_first_nonempty_global(
    (
        "NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_DRIVE_FILE_ID",
        "NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_DRIVE_FILE_ID",
    )
)


(
    BLOCK_9_SOCIAL_TARGET_CONTRACT_FILENAME,
    BLOCK_9_SOCIAL_TARGET_CONTRACT_FILENAME_SOURCE,
) = block_9_first_nonempty_global(
    (
        "NOTEBOOK_07_ACCEPTED_SOCIAL_SUPERVISION_FILENAME",
        "NOTEBOOK_07_SOCIAL_TARGET_CONTRACT_FILENAME",
    )
)


if BLOCK_9_SOCIAL_TARGET_CONTRACT_DRIVE_FILE_ID is None:

    raise RuntimeError(
        "Could not resolve the persisted accepted Social Representation "
        "supervision / target-contract Drive file ID."
    )


# -----------------------------------------------------------------------------
# Supplemental schema reference
# -----------------------------------------------------------------------------

(
    BLOCK_9_SOCIAL_SCHEMA_DRIVE_FILE_ID,
    BLOCK_9_SOCIAL_SCHEMA_ID_SOURCE,
) = block_9_first_nonempty_global(
    (
        "NOTEBOOK_07_SOCIAL_SCHEMA_DRIVE_FILE_ID",
        "NOTEBOOK_07_SOCIAL_SUPERVISION_SCHEMA_DRIVE_FILE_ID",
    )
)


# -----------------------------------------------------------------------------
# Notebook 06 -> 07 handover reference
# -----------------------------------------------------------------------------

(
    BLOCK_9_INHERITED_HANDOVER_DRIVE_FILE_ID,
    BLOCK_9_INHERITED_HANDOVER_ID_SOURCE,
) = block_9_first_nonempty_global(
    (
        "NOTEBOOK_07_HANDOVER_DRIVE_FILE_ID",
        "NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID",
        "NOTEBOOK_07_NOTEBOOK_06_TO_07_HANDOVER_DRIVE_FILE_ID",
    )
)


# =============================================================================
# Inherited Notebook 06 -> Notebook 07 contract
# =============================================================================

BLOCK_9_INHERITED_HANDOVER_PRESENT = (
    "NOTEBOOK_07_HANDOVER"
    in globals()
    and
    isinstance(
        NOTEBOOK_07_HANDOVER,
        dict,
    )
)


# -----------------------------------------------------------------------------
# Preserve Block 1 as the authoritative handover-validation boundary.
# -----------------------------------------------------------------------------

BLOCK_9_INHERITED_CONTRACT_VALID = all(
    [
        NOTEBOOK_07_BLOCK_1_COMPLETE,
        NOTEBOOK_07_BLOCK_1_VALID,
        BLOCK_9_INHERITED_HANDOVER_PRESENT,
    ]
)


if not BLOCK_9_INHERITED_CONTRACT_VALID:

    raise RuntimeError(
        "The validated Notebook 06 -> Notebook 07 inherited contract "
        "is not available."
    )


# =============================================================================
# Persistent artefact reference validation
# =============================================================================

BLOCK_9_ARTEFACT_REFERENCES_VALID = all(
    [
        bool(
            NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID
        ),

        bool(
            NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID
        ),

        bool(
            BLOCK_9_SOCIAL_TARGET_CONTRACT_DRIVE_FILE_ID
        ),

        bool(
            BLOCK_5_REPRESENTATION_DRIVE_FILE_ID
        ),
    ]
)


if not BLOCK_9_ARTEFACT_REFERENCES_VALID:

    raise RuntimeError(
        "Notebook 07 completion artefact references are incomplete."
    )


# =============================================================================
# Group-conditioned path policy
# =============================================================================

NOTEBOOK_07_COMPLETION_GLOBAL_PATH_REQUIRED = True

NOTEBOOK_07_COMPLETION_GLOBAL_PATH_OPERATIONAL = True

NOTEBOOK_07_COMPLETION_GROUP_PATH_AVAILABLE = True

NOTEBOOK_07_COMPLETION_GROUP_PATH_REQUIRED = False

NOTEBOOK_07_COMPLETION_GROUP_PATH_EXECUTED = False

NOTEBOOK_07_COMPLETION_GROUP_PATH_TRAINED = False

NOTEBOOK_07_COMPLETION_GROUP_PATH_DEFERRED_TO_NOTEBOOK = 10


BLOCK_9_GROUP_PATH_POLICY_VALID = all(
    [
        NOTEBOOK_07_COMPLETION_GLOBAL_PATH_REQUIRED,
        NOTEBOOK_07_COMPLETION_GLOBAL_PATH_OPERATIONAL,
        NOTEBOOK_07_COMPLETION_GROUP_PATH_AVAILABLE,
        not NOTEBOOK_07_COMPLETION_GROUP_PATH_REQUIRED,
        not NOTEBOOK_07_COMPLETION_GROUP_PATH_EXECUTED,
        not NOTEBOOK_07_COMPLETION_GROUP_PATH_TRAINED,
        (
            NOTEBOOK_07_COMPLETION_GROUP_PATH_DEFERRED_TO_NOTEBOOK
            ==
            10
        ),
    ]
)


# =============================================================================
# Remaining Version 1 roadmap
# =============================================================================

NOTEBOOK_07_REMAINING_VERSION_1_ROADMAP = {
    "Notebook 08":
        "Transformative Mechanism",

    "Notebook 09":
        "Transformative Weights and Recurrent Mechanism",

    "Notebook 10":
        "Group-Conditioned Path and Final Integration",
}


# =============================================================================
# Notebook 08 starting policy
# =============================================================================

NOTEBOOK_08_STARTING_POLICY = {
    "notebook":
        8,

    "designation":
        "Transformative Mechanism",

    "backbone_frozen_by_default":
        True,

    "global_confluent_frozen_by_default":
        True,

    "psychological_representation_frozen_by_default":
        True,

    "factual_representation_frozen_by_default":
        True,

    "social_representation_frozen_by_default":
        True,

    "group_conditioned_path_required":
        False,

    "group_conditioned_path_executed":
        False,

    "group_conditioned_path_deferred_to_notebook":
        10,

    "transformative_mechanism_may_initialise":
        True,

    "transformative_weights_active":
        False,

    "recurrent_mechanism_active":
        False,

    "completed_representation_paths_may_be_retrained":
        False,
}


BLOCK_9_NOTEBOOK_08_STARTING_POLICY_VALID = all(
    [
        NOTEBOOK_08_STARTING_POLICY[
            "backbone_frozen_by_default"
        ],

        NOTEBOOK_08_STARTING_POLICY[
            "global_confluent_frozen_by_default"
        ],

        NOTEBOOK_08_STARTING_POLICY[
            "psychological_representation_frozen_by_default"
        ],

        NOTEBOOK_08_STARTING_POLICY[
            "factual_representation_frozen_by_default"
        ],

        NOTEBOOK_08_STARTING_POLICY[
            "social_representation_frozen_by_default"
        ],

        not NOTEBOOK_08_STARTING_POLICY[
            "group_conditioned_path_required"
        ],

        not NOTEBOOK_08_STARTING_POLICY[
            "group_conditioned_path_executed"
        ],

        (
            NOTEBOOK_08_STARTING_POLICY[
                "group_conditioned_path_deferred_to_notebook"
            ]
            ==
            10
        ),

        NOTEBOOK_08_STARTING_POLICY[
            "transformative_mechanism_may_initialise"
        ],

        not NOTEBOOK_08_STARTING_POLICY[
            "transformative_weights_active"
        ],

        not NOTEBOOK_08_STARTING_POLICY[
            "recurrent_mechanism_active"
        ],

        not NOTEBOOK_08_STARTING_POLICY[
            "completed_representation_paths_may_be_retrained"
        ],
    ]
)


# =============================================================================
# Social dimension audit table
# =============================================================================

BLOCK_9_SOCIAL_DIMENSION_ROWS = []


for (
    dimension_index,
    dimension_id,
    dimension_name,
) in zip(
    range(
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM
    ),
    NOTEBOOK_07_SOCIAL_DIMENSION_IDS,
    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER,
):

    currently_active = (
        dimension_name
        in
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )


    currently_deferred = (
        dimension_name
        in
        NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
    )


    if currently_active:

        optimisation_state = "trained"

        checkpoint_state_reproducible = True

        loss_family = (
            NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES[
                dimension_name
            ]
        )


    else:

        deferral_reason = (
            BLOCK_9_SOCIAL_DEFERRAL_REASONS.get(
                dimension_name
            )
        )


        optimisation_state = (
            "deferred_"
            +
            str(
                deferral_reason
            )
        )


        checkpoint_state_reproducible = (
            "not_applicable"
        )

        loss_family = "none_current_sample"


    BLOCK_9_SOCIAL_DIMENSION_ROWS.append(
        {
            "dimension_id":
                dimension_id,

            "dimension_index":
                int(
                    dimension_index
                ),

            "target_name":
                dimension_name,

            "structurally_present":
                True,

            "currently_active":
                bool(
                    currently_active
                ),

            "currently_deferred":
                bool(
                    currently_deferred
                ),

            "deferral_reason":
                (
                    None
                    if currently_active
                    else
                    BLOCK_9_SOCIAL_DEFERRAL_REASONS.get(
                        dimension_name
                    )
                ),

            "objective_family":
                loss_family,

            "optimisation_state":
                optimisation_state,

            "checkpoint_state_reproducible":
                checkpoint_state_reproducible,

            "independently_evaluated":
                False,

            "empirically_validated":
                False,
        }
    )


BLOCK_9_SOCIAL_DIMENSION_AUDIT = pd.DataFrame(
    BLOCK_9_SOCIAL_DIMENSION_ROWS
)


# =============================================================================
# Functionality scope audit
# =============================================================================

BLOCK_9_FUNCTIONALITY_ROWS = [
    {
        "functionality":
            "contextual_sentence_representation",

        "architecture_stage":
            "textual_representation",

        "implemented_structurally":
            True,

        "used_in_notebook_07":
            True,

        "trained_in_notebook_07":
            False,

        "checkpoint_or_state_reproducible":
            True,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            (
                "Inherited persisted 768-dimensional contextual sentence "
                "representation."
            ),
    },

    {
        "functionality":
            "mandatory_global_confluent_path",

        "architecture_stage":
            "confluent_conditioning",

        "implemented_structurally":
            True,

        "used_in_notebook_07":
            True,

        "trained_in_notebook_07":
            False,

        "checkpoint_or_state_reproducible":
            True,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            (
                "Mandatory global conditioning remained frozen during "
                "Social Representation optimisation."
            ),
    },

    {
        "functionality":
            "psychological_representation_head",

        "architecture_stage":
            "representation_heads",

        "implemented_structurally":
            True,

        "used_in_notebook_07":
            False,

        "trained_in_notebook_07":
            False,

        "checkpoint_or_state_reproducible":
            True,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            (
                "Completed inherited Psychological Representation remained "
                "frozen."
            ),
    },

    {
        "functionality":
            "factual_representation_head",

        "architecture_stage":
            "representation_heads",

        "implemented_structurally":
            True,

        "used_in_notebook_07":
            False,

        "trained_in_notebook_07":
            False,

        "checkpoint_or_state_reproducible":
            True,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            (
                "Completed inherited Factual Representation remained frozen."
            ),
    },

    {
        "functionality":
            "social_representation_head",

        "architecture_stage":
            "representation_heads",

        "implemented_structurally":
            True,

        "used_in_notebook_07":
            True,

        "trained_in_notebook_07":
            True,

        "checkpoint_or_state_reproducible":
            True,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            (
                "Controlled Social Representation training completed for "
                f"{len(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)} active "
                "dimension(s) under the validated activation contract."
            ),
    },

    {
        "functionality":
            "transformative_mechanism",

        "architecture_stage":
            "transformative_mechanism",

        "implemented_structurally":
            True,

        "used_in_notebook_07":
            False,

        "trained_in_notebook_07":
            False,

        "checkpoint_or_state_reproducible":
            False,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            "Reserved for Notebook 08.",
    },

    {
        "functionality":
            "transformative_weights",

        "architecture_stage":
            "transformative_mechanism",

        "implemented_structurally":
            True,

        "used_in_notebook_07":
            False,

        "trained_in_notebook_07":
            False,

        "checkpoint_or_state_reproducible":
            False,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            "Reserved for Notebook 09.",
    },

    {
        "functionality":
            "recurrent_mechanism",

        "architecture_stage":
            "recurrent_mechanism",

        "implemented_structurally":
            True,

        "used_in_notebook_07":
            False,

        "trained_in_notebook_07":
            False,

        "checkpoint_or_state_reproducible":
            False,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            "Reserved for Notebook 09.",
    },

    {
        "functionality":
            "optional_group_conditioned_path",

        "architecture_stage":
            "confluent_conditioning",

        "implemented_structurally":
            True,

        "used_in_notebook_07":
            False,

        "trained_in_notebook_07":
            False,

        "checkpoint_or_state_reproducible":
            False,

        "independently_evaluated":
            False,

        "empirically_validated":
            False,

        "notes":
            (
                "Architecturally available but deliberately deferred "
                "to Notebook 10."
            ),
    },
]


BLOCK_9_FUNCTIONALITY_AUDIT = pd.DataFrame(
    BLOCK_9_FUNCTIONALITY_ROWS
)


# =============================================================================
# Notebook 07 completion state
# =============================================================================

NOTEBOOK_07_SOCIAL_PATH_COMPLETE = True

NOTEBOOK_07_CONTROLLED_SOCIAL_PIPELINE_COMPLETE = True

NOTEBOOK_07_SOCIAL_PATH_REPRODUCIBLE = (
    BLOCK_9_SOCIAL_CHECKPOINT_REPRODUCIBLE
)

NOTEBOOK_07_FULL_MEDIA_AI_PROJECT_COMPLETE = False

NOTEBOOK_07_FULL_SOCIAL_TRAINING_COVERAGE = False

NOTEBOOK_07_HELD_OUT_GENERALISATION_VALIDATED = False


# =============================================================================
# Construct Notebook 07 -> Notebook 08 handover
# =============================================================================

NOTEBOOK_07_TO_08_HANDOVER = {
    "handover_type":
        "media_ai_notebook_07_to_08_handover",

    "handover_version":
        NOTEBOOK_07_TO_08_HANDOVER_VERSION,

    "created_at_utc":
        BLOCK_9_EXECUTED_AT_UTC,

    "source_notebook":
        {
            "notebook":
                7,

            "designation":
                "Social Representation",

            "block":
                9,

            "complete":
                True,

            "controlled_experimental_scope":
                True,

            "full_media_ai_project_complete":
                False,
        },

    "destination_notebook":
        {
            "notebook":
                8,

            "designation":
                "Transformative Mechanism",
        },

    "canonical_identity":
        {
            "article_count":
                NOTEBOOK_07_ARTICLE_COUNT,

            "sentence_count":
                NOTEBOOK_07_SENTENCE_COUNT,

            "sentence_ids":
                list(
                    NOTEBOOK_07_SENTENCE_IDS
                ),

            "sentence_ids_unique":
                BLOCK_9_SENTENCE_IDS_UNIQUE,
        },

    "architecture":
        {
            "textual_representation_dim":
                NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM,

            "backbone_interface_dim":
                NOTEBOOK_07_BACKBONE_INTERFACE_DIM,

            "mandatory_global_confluent_dim":
                NOTEBOOK_07_GLOBAL_CONFLUENT_DIM,

            "representation_hidden_dim":
                NOTEBOOK_07_REPRESENTATION_HIDDEN_DIM,

            "psychological_representation_dim":
                NOTEBOOK_07_PSYCHOLOGICAL_REPRESENTATION_DIM,

            "factual_representation_dim":
                NOTEBOOK_07_FACTUAL_REPRESENTATION_DIM,

            "social_representation_dim":
                NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

            "group_conditioned_path_available":
                True,

            "group_conditioned_path_required":
                False,

            "group_conditioned_path_deferred_to_notebook":
                10,
        },

    "social_representation_contract":
        {
            "dimension_ids":
                list(
                    NOTEBOOK_07_SOCIAL_DIMENSION_IDS
                ),

            "dimension_order":
                list(
                    NOTEBOOK_07_SOCIAL_DIMENSION_ORDER
                ),

            "active_dimensions":
                list(
                    NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
                ),

            "active_indices":
                list(
                    NOTEBOOK_07_SOCIAL_ACTIVE_INDICES
                ),

            "deferred_dimensions":
                list(
                    NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
                ),

            "deferred_indices":
                list(
                    NOTEBOOK_07_SOCIAL_DEFERRED_INDICES
                ),

            "deferral_reasons":
                deepcopy(
                    BLOCK_9_SOCIAL_DEFERRAL_REASONS
                ),

            "objective_weights":
                deepcopy(
                    NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS
                ),

            "active_loss_families":
                deepcopy(
                    NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES
                ),

            "all_dimensions_structurally_present":
                True,

            "all_dimensions_trained":
                NOTEBOOK_07_SOCIAL_ALL_DIMENSIONS_TRAINED,

            "full_training_coverage":
                NOTEBOOK_07_SOCIAL_FULL_TRAINING_COVERAGE,
        },

    "social_training_state":
        {
            "training_policy_version":
                NOTEBOOK_07_SOCIAL_TRAINING_POLICY_VERSION,

            "training_article_count":
                BLOCK_9_TRAINING_ARTICLE_COUNT,

            "training_sentence_count":
                BLOCK_9_TRAINING_SENTENCE_COUNT,

            "validation_sentence_count":
                BLOCK_9_VALIDATION_SENTENCE_COUNT,

            "test_sentence_count":
                BLOCK_9_TEST_SENTENCE_COUNT,

            "epoch_count":
                BLOCK_9_TRAINING_EPOCH_COUNT,

            "within_article_shuffle":
                NOTEBOOK_07_SOCIAL_WITHIN_ARTICLE_SHUFFLE,

            "article_sequence_preserved":
                NOTEBOOK_07_SOCIAL_ARTICLE_SEQUENCE_PRESERVED,

            "optimizer_type":
                NOTEBOOK_07_SOCIAL_OPTIMIZER_TYPE,

            "learning_rate":
                NOTEBOOK_07_SOCIAL_LEARNING_RATE,

            "weight_decay":
                NOTEBOOK_07_SOCIAL_WEIGHT_DECAY,

            "maximum_gradient_norm":
                NOTEBOOK_07_SOCIAL_MAXIMUM_GRADIENT_NORM,

            "maximum_preclip_gradient_norm":
                BLOCK_9_MAXIMUM_PRECLIP_GRADIENT_NORM,

            "initial_objective":
                BLOCK_9_INITIAL_SOCIAL_OBJECTIVE,

            "final_objective":
                BLOCK_9_FINAL_SOCIAL_OBJECTIVE,

            "objective_reduction":
                BLOCK_9_SOCIAL_OBJECTIVE_REDUCTION,

            "maximum_parameter_delta":
                BLOCK_9_MAXIMUM_PARAMETER_DELTA,

            "social_parameter_count":
                BLOCK_9_SOCIAL_HEAD_PARAMETER_COUNT,
        },

    "persistent_artefacts":
        {
            "contextual_representation":
                {
                    "drive_file_id":
                        BLOCK_5_REPRESENTATION_DRIVE_FILE_ID,
                },

            "social_target_contract":
                {
                    "filename":
                        BLOCK_9_SOCIAL_TARGET_CONTRACT_FILENAME,

                    "drive_file_id":
                        BLOCK_9_SOCIAL_TARGET_CONTRACT_DRIVE_FILE_ID,
                },

            "social_supervision_schema":
                {
                    "drive_file_id":
                        BLOCK_9_SOCIAL_SCHEMA_DRIVE_FILE_ID,
                },

            "social_checkpoint":
                {
                    "filename":
                        NOTEBOOK_07_SOCIAL_CHECKPOINT_FILENAME,

                    "drive_file_id":
                        NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID,

                    "checkpoint_type":
                        NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE,

                    "checkpoint_version":
                        NOTEBOOK_07_SOCIAL_CHECKPOINT_VERSION,

                    "validated_model_checkpoint":
                        False,

                    "reproducible":
                        True,
                },

            "social_training_metadata":
                {
                    "filename":
                        NOTEBOOK_07_SOCIAL_METADATA_FILENAME,

                    "drive_file_id":
                        NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID,
                },

            "inherited_notebook_06_to_07_handover":
                {
                    "drive_file_id":
                        BLOCK_9_INHERITED_HANDOVER_DRIVE_FILE_ID,
                },
        },

    "completed_representation_state":
        {
            "backbone":
                {
                    "completed":
                        True,

                    "frozen_by_default":
                        True,
                },

            "mandatory_global_confluent":
                {
                    "completed":
                        True,

                    "frozen_by_default":
                        True,
                },

            "psychological_representation":
                {
                    "completed":
                        True,

                    "frozen_by_default":
                        True,
                },

            "factual_representation":
                {
                    "completed":
                        True,

                    "frozen_by_default":
                        True,
                },

            "social_representation":
                {
                    "completed":
                        True,

                    "frozen_by_default":
                        True,

                    "checkpoint_reproducible":
                        True,
                },
        },

    "notebook_08_starting_policy":
        deepcopy(
            NOTEBOOK_08_STARTING_POLICY
        ),

    "methodological_boundary":
        {
            "social_checkpoint_experimental":
                True,

            "validated_model_checkpoint":
                False,

            "all_social_dimensions_trained":
                NOTEBOOK_07_SOCIAL_ALL_DIMENSIONS_TRAINED,

            "held_out_evaluation_executed":
                False,

            "generalisation_validated":
                False,

            "empirical_validity":
                False,

            "transformative_mechanism_completed":
                False,

            "transformative_weights_active":
                False,

            "recurrent_mechanism_executed":
                False,

            "group_conditioned_path_executed":
                False,

            "full_media_ai_project_complete":
                False,
        },

    "roadmap":
        deepcopy(
            NOTEBOOK_07_REMAINING_VERSION_1_ROADMAP
        ),
}


# =============================================================================
# Handover serialisation
# =============================================================================

NOTEBOOK_07_TO_08_HANDOVER_JSON = json.dumps(
    NOTEBOOK_07_TO_08_HANDOVER,
    indent=2,
    ensure_ascii=False,
    default=
        block_9_json_default,
)


BLOCK_9_HANDOVER_JSON_VALID = bool(
    NOTEBOOK_07_TO_08_HANDOVER_JSON
)


if not BLOCK_9_HANDOVER_JSON_VALID:

    raise RuntimeError(
        "Notebook 07 -> Notebook 08 handover could not be serialised."
    )


# =============================================================================
# Local handover persistence
# =============================================================================

with open(
    NOTEBOOK_07_TO_08_HANDOVER_FILENAME,
    "w",
    encoding="utf-8",
) as handover_file:

    handover_file.write(
        NOTEBOOK_07_TO_08_HANDOVER_JSON
    )


BLOCK_9_LOCAL_HANDOVER_CREATED = True


# =============================================================================
# Resolve persistent parent folder
# =============================================================================
#
# Use the persisted Social checkpoint parent as the authoritative destination
# for the Notebook 07 -> 08 handover.
# =============================================================================

BLOCK_9_SOCIAL_CHECKPOINT_DRIVE_METADATA = (
    NOTEBOOK_07_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID,

        fields=
            "id,name,parents",
    )
    .execute()
)


BLOCK_9_PARENT_IDS = (
    BLOCK_9_SOCIAL_CHECKPOINT_DRIVE_METADATA.get(
        "parents",
        [],
    )
)


# =============================================================================
# Persist JSON helper
# =============================================================================

def block_9_persist_json_to_drive(
    drive_service,
    filename,
    json_text,
    parent_ids=None,
):
    """
    Create or update one exact-name JSON artefact.

    Search is restricted to the selected parent folder when available.
    """

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )


    query_parts = [
        f"name = '{escaped_filename}'",
        "trashed = false",
    ]


    if (
        parent_ids
        and
        len(
            parent_ids
        )
        == 1
    ):

        query_parts.append(
            f"'{parent_ids[0]}' in parents"
        )


    query = " and ".join(
        query_parts
    )


    search_response = (
        drive_service.files()
        .list(
            q=
                query,

            spaces=
                "drive",

            fields=
                "files(id,name,modifiedTime,parents)",

            orderBy=
                "modifiedTime desc",

            pageSize=
                20,
        )
        .execute()
    )


    matching_files = search_response.get(
        "files",
        [],
    )


    media = MediaIoBaseUpload(
        io.BytesIO(
            json_text.encode(
                "utf-8"
            )
        ),
        mimetype=
            "application/json",
        resumable=
            False,
    )


    if matching_files:

        persisted_file = (
            drive_service.files()
            .update(
                fileId=
                    matching_files[
                        0
                    ][
                        "id"
                    ],

                media_body=
                    media,

                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "updated"


    else:

        metadata = {
            "name":
                filename
        }


        if parent_ids:

            metadata[
                "parents"
            ] = list(
                parent_ids
            )


        persisted_file = (
            drive_service.files()
            .create(
                body=
                    metadata,

                media_body=
                    media,

                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "created"


    return (
        persisted_file,
        operation,
    )


# =============================================================================
# Persist Notebook 07 -> 08 handover
# =============================================================================

(
    NOTEBOOK_07_TO_08_HANDOVER_DRIVE_FILE,
    NOTEBOOK_07_TO_08_HANDOVER_DRIVE_OPERATION,
) = block_9_persist_json_to_drive(
    drive_service=
        NOTEBOOK_07_DRIVE_SERVICE,

    filename=
        NOTEBOOK_07_TO_08_HANDOVER_FILENAME,

    json_text=
        NOTEBOOK_07_TO_08_HANDOVER_JSON,

    parent_ids=
        BLOCK_9_PARENT_IDS,
)


NOTEBOOK_07_TO_08_HANDOVER_DRIVE_FILE_ID = (
    NOTEBOOK_07_TO_08_HANDOVER_DRIVE_FILE.get(
        "id"
    )
)


BLOCK_9_HANDOVER_DRIVE_PERSISTED = bool(
    NOTEBOOK_07_TO_08_HANDOVER_DRIVE_FILE_ID
)


if not BLOCK_9_HANDOVER_DRIVE_PERSISTED:

    raise RuntimeError(
        "Notebook 07 -> Notebook 08 handover was not persisted "
        "to Google Drive."
    )


# =============================================================================
# Handover read-back
# =============================================================================

BLOCK_9_RELOADED_HANDOVER_BYTES = (
    block_9_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_TO_08_HANDOVER_DRIVE_FILE_ID,
    )
)


if not BLOCK_9_RELOADED_HANDOVER_BYTES:

    raise RuntimeError(
        "Persisted Notebook 07 -> 08 handover was empty."
    )


BLOCK_9_RELOADED_HANDOVER = json.loads(
    BLOCK_9_RELOADED_HANDOVER_BYTES.decode(
        "utf-8"
    )
)


# =============================================================================
# Handover read-back contract
# =============================================================================

BLOCK_9_HANDOVER_READBACK_TYPE_VALID = (
    BLOCK_9_RELOADED_HANDOVER.get(
        "handover_type"
    )
    ==
    "media_ai_notebook_07_to_08_handover"
)


BLOCK_9_HANDOVER_READBACK_VERSION_VALID = (
    BLOCK_9_RELOADED_HANDOVER.get(
        "handover_version"
    )
    ==
    NOTEBOOK_07_TO_08_HANDOVER_VERSION
)


BLOCK_9_HANDOVER_READBACK_SOURCE_COMPLETE = (
    BLOCK_9_RELOADED_HANDOVER[
        "source_notebook"
    ][
        "complete"
    ]
    is True
)


BLOCK_9_HANDOVER_READBACK_DESTINATION_VALID = (
    BLOCK_9_RELOADED_HANDOVER[
        "destination_notebook"
    ][
        "notebook"
    ]
    ==
    8
)


BLOCK_9_HANDOVER_READBACK_SOCIAL_DIMENSION_VALID = (
    BLOCK_9_RELOADED_HANDOVER[
        "architecture"
    ][
        "social_representation_dim"
    ]
    ==
    7
)


BLOCK_9_HANDOVER_READBACK_ACTIVE_VALID = (
    tuple(
        BLOCK_9_RELOADED_HANDOVER[
            "social_representation_contract"
        ][
            "active_dimensions"
        ]
    )
    ==
    tuple(
        NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
    )
)


BLOCK_9_HANDOVER_READBACK_DEFERRED_VALID = (
    tuple(
        BLOCK_9_RELOADED_HANDOVER[
            "social_representation_contract"
        ][
            "deferred_dimensions"
        ]
    )
    ==
    tuple(
        NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
    )
)


BLOCK_9_HANDOVER_READBACK_LOSS_FAMILIES_VALID = (
    BLOCK_9_RELOADED_HANDOVER[
        "social_representation_contract"
    ][
        "active_loss_families"
    ]
    ==
    NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES
)


BLOCK_9_HANDOVER_READBACK_CHECKPOINT_ID_VALID = (
    BLOCK_9_RELOADED_HANDOVER[
        "persistent_artefacts"
    ][
        "social_checkpoint"
    ][
        "drive_file_id"
    ]
    ==
    NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID
)


BLOCK_9_HANDOVER_READBACK_METADATA_ID_VALID = (
    BLOCK_9_RELOADED_HANDOVER[
        "persistent_artefacts"
    ][
        "social_training_metadata"
    ][
        "drive_file_id"
    ]
    ==
    NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID
)


BLOCK_9_HANDOVER_READBACK_TARGET_ID_VALID = (
    BLOCK_9_RELOADED_HANDOVER[
        "persistent_artefacts"
    ][
        "social_target_contract"
    ][
        "drive_file_id"
    ]
    ==
    BLOCK_9_SOCIAL_TARGET_CONTRACT_DRIVE_FILE_ID
)


BLOCK_9_HANDOVER_READBACK_CONTEXTUAL_ID_VALID = (
    BLOCK_9_RELOADED_HANDOVER[
        "persistent_artefacts"
    ][
        "contextual_representation"
    ][
        "drive_file_id"
    ]
    ==
    BLOCK_5_REPRESENTATION_DRIVE_FILE_ID
)


BLOCK_9_HANDOVER_READBACK_EXPERIMENTAL_VALID = (
    BLOCK_9_RELOADED_HANDOVER[
        "methodological_boundary"
    ][
        "social_checkpoint_experimental"
    ]
    is True
)


BLOCK_9_HANDOVER_READBACK_VALIDATED_MODEL_FALSE = (
    BLOCK_9_RELOADED_HANDOVER[
        "methodological_boundary"
    ][
        "validated_model_checkpoint"
    ]
    is False
)


BLOCK_9_HANDOVER_READBACK_EMPIRICAL_FALSE = (
    BLOCK_9_RELOADED_HANDOVER[
        "methodological_boundary"
    ][
        "empirical_validity"
    ]
    is False
)


BLOCK_9_HANDOVER_READBACK_PROJECT_INCOMPLETE = (
    BLOCK_9_RELOADED_HANDOVER[
        "methodological_boundary"
    ][
        "full_media_ai_project_complete"
    ]
    is False
)


BLOCK_9_HANDOVER_READBACK_NOTEBOOK_08_POLICY_VALID = all(
    [
        (
            BLOCK_9_RELOADED_HANDOVER[
                "notebook_08_starting_policy"
            ][
                "backbone_frozen_by_default"
            ]
            is True
        ),

        (
            BLOCK_9_RELOADED_HANDOVER[
                "notebook_08_starting_policy"
            ][
                "global_confluent_frozen_by_default"
            ]
            is True
        ),

        (
            BLOCK_9_RELOADED_HANDOVER[
                "notebook_08_starting_policy"
            ][
                "psychological_representation_frozen_by_default"
            ]
            is True
        ),

        (
            BLOCK_9_RELOADED_HANDOVER[
                "notebook_08_starting_policy"
            ][
                "factual_representation_frozen_by_default"
            ]
            is True
        ),

        (
            BLOCK_9_RELOADED_HANDOVER[
                "notebook_08_starting_policy"
            ][
                "social_representation_frozen_by_default"
            ]
            is True
        ),

        (
            BLOCK_9_RELOADED_HANDOVER[
                "notebook_08_starting_policy"
            ][
                "transformative_mechanism_may_initialise"
            ]
            is True
        ),

        (
            BLOCK_9_RELOADED_HANDOVER[
                "notebook_08_starting_policy"
            ][
                "group_conditioned_path_deferred_to_notebook"
            ]
            ==
            10
        ),
    ]
)


BLOCK_9_HANDOVER_READBACK_VALID = all(
    [
        BLOCK_9_HANDOVER_READBACK_TYPE_VALID,
        BLOCK_9_HANDOVER_READBACK_VERSION_VALID,
        BLOCK_9_HANDOVER_READBACK_SOURCE_COMPLETE,
        BLOCK_9_HANDOVER_READBACK_DESTINATION_VALID,
        BLOCK_9_HANDOVER_READBACK_SOCIAL_DIMENSION_VALID,
        BLOCK_9_HANDOVER_READBACK_ACTIVE_VALID,
        BLOCK_9_HANDOVER_READBACK_DEFERRED_VALID,
        BLOCK_9_HANDOVER_READBACK_LOSS_FAMILIES_VALID,
        BLOCK_9_HANDOVER_READBACK_CHECKPOINT_ID_VALID,
        BLOCK_9_HANDOVER_READBACK_METADATA_ID_VALID,
        BLOCK_9_HANDOVER_READBACK_TARGET_ID_VALID,
        BLOCK_9_HANDOVER_READBACK_CONTEXTUAL_ID_VALID,
        BLOCK_9_HANDOVER_READBACK_EXPERIMENTAL_VALID,
        BLOCK_9_HANDOVER_READBACK_VALIDATED_MODEL_FALSE,
        BLOCK_9_HANDOVER_READBACK_EMPIRICAL_FALSE,
        BLOCK_9_HANDOVER_READBACK_PROJECT_INCOMPLETE,
        BLOCK_9_HANDOVER_READBACK_NOTEBOOK_08_POLICY_VALID,
    ]
)


if not BLOCK_9_HANDOVER_READBACK_VALID:

    raise RuntimeError(
        "Persisted Notebook 07 -> Notebook 08 handover failed "
        "read-back validation."
    )


# =============================================================================
# Post-audit no-update validation
# =============================================================================

BLOCK_9_BACKBONE_UNCHANGED = (
    block_9_module_matches_snapshot(
        NOTEBOOK_07_BACKBONE_FROZEN_MODULE,
        BLOCK_9_BACKBONE_BEFORE,
    )
)


BLOCK_9_GLOBAL_CONFLUENT_UNCHANGED = (
    block_9_module_matches_snapshot(
        NOTEBOOK_07_GLOBAL_CONFLUENT_FROZEN_MODULE,
        BLOCK_9_GLOBAL_CONFLUENT_BEFORE,
    )
)


BLOCK_9_PSYCHOLOGICAL_UNCHANGED = (
    block_9_module_matches_snapshot(
        NOTEBOOK_07_PSYCHOLOGICAL_HEAD_FROZEN_MODULE,
        BLOCK_9_PSYCHOLOGICAL_BEFORE,
    )
)


BLOCK_9_FACTUAL_UNCHANGED = (
    block_9_module_matches_snapshot(
        NOTEBOOK_07_FACTUAL_HEAD_FROZEN_MODULE,
        BLOCK_9_FACTUAL_BEFORE,
    )
)


BLOCK_9_SOCIAL_UNCHANGED = (
    block_9_module_matches_snapshot(
        NOTEBOOK_07_SOCIAL_HEAD,
        BLOCK_9_SOCIAL_BEFORE,
    )
)


BLOCK_9_ALL_PARAMETERS_UNCHANGED = all(
    [
        BLOCK_9_BACKBONE_UNCHANGED,
        BLOCK_9_GLOBAL_CONFLUENT_UNCHANGED,
        BLOCK_9_PSYCHOLOGICAL_UNCHANGED,
        BLOCK_9_FACTUAL_UNCHANGED,
        BLOCK_9_SOCIAL_UNCHANGED,
    ]
)


if not BLOCK_9_ALL_PARAMETERS_UNCHANGED:

    raise RuntimeError(
        "Block 9 modified one or more model parameters."
    )


# =============================================================================
# Notebook 07 completion contract
# =============================================================================

NOTEBOOK_07_SOCIAL_SCOPE_AUDIT_COMPLETE = True

NOTEBOOK_07_SOCIAL_PERSISTENT_HANDOVER_COMPLETE = (
    BLOCK_9_HANDOVER_READBACK_VALID
)

NOTEBOOK_07_READY_FOR_NOTEBOOK_08 = all(
    [
        BLOCK_9_PREVIOUS_BLOCKS_COMPLETE,
        BLOCK_9_PREVIOUS_BLOCKS_VALID,
        BLOCK_9_CANONICAL_IDENTITY_VALID,
        BLOCK_9_SOCIAL_SEMANTIC_CONTRACT_VALID,
        BLOCK_9_DEFERRAL_REASONS_VALID,
        BLOCK_9_MODEL_ARCHITECTURE_VALID,
        BLOCK_9_BLOCK_7_PERSISTENCE_VALID,
        BLOCK_9_SOCIAL_CHECKPOINT_REPRODUCIBLE,
        BLOCK_9_TRAINING_SCOPE_VALID,
        BLOCK_9_PARTIAL_SOCIAL_TRAINING_SCOPE_VALID,
        BLOCK_9_INHERITED_CONTRACT_VALID,
        BLOCK_9_ARTEFACT_REFERENCES_VALID,
        BLOCK_9_GROUP_PATH_POLICY_VALID,
        BLOCK_9_NOTEBOOK_08_STARTING_POLICY_VALID,
        BLOCK_9_HANDOVER_READBACK_VALID,
        BLOCK_9_ALL_PARAMETERS_UNCHANGED,
    ]
)


NOTEBOOK_07_COMPLETE = (
    NOTEBOOK_07_READY_FOR_NOTEBOOK_08
)


NOTEBOOK_07_VALID = (
    NOTEBOOK_07_COMPLETE
)


if not NOTEBOOK_07_COMPLETE:

    raise RuntimeError(
        "Notebook 07 completion contract could not be established."
    )


# =============================================================================
# Final Block 9 validation
# =============================================================================

NOTEBOOK_07_BLOCK_9_ERRORS = []


block_9_validation_checks = {
    "blocks_1_to_8_not_complete":
        BLOCK_9_PREVIOUS_BLOCKS_COMPLETE,

    "blocks_1_to_8_not_valid":
        BLOCK_9_PREVIOUS_BLOCKS_VALID,

    "canonical_identity_invalid":
        BLOCK_9_CANONICAL_IDENTITY_VALID,

    "social_semantic_contract_invalid":
        BLOCK_9_SOCIAL_SEMANTIC_CONTRACT_VALID,

    "deferral_reasons_invalid":
        BLOCK_9_DEFERRAL_REASONS_VALID,

    "model_architecture_invalid":
        BLOCK_9_MODEL_ARCHITECTURE_VALID,

    "block_7_persistence_invalid":
        BLOCK_9_BLOCK_7_PERSISTENCE_VALID,

    "social_checkpoint_not_reproducible":
        BLOCK_9_SOCIAL_CHECKPOINT_REPRODUCIBLE,

    "social_checkpoint_contract_invalid":
        BLOCK_9_SOCIAL_CHECKPOINT_CONTRACT_VALID,

    "social_metadata_contract_invalid":
        BLOCK_9_SOCIAL_METADATA_CONTRACT_VALID,

    "runtime_state_not_checkpoint_state":
        BLOCK_9_RUNTIME_STATE_MATCHES_PERSISTED_CHECKPOINT,

    "training_scope_invalid":
        BLOCK_9_TRAINING_SCOPE_VALID,

    "partial_training_boundary_invalid":
        BLOCK_9_PARTIAL_SOCIAL_TRAINING_SCOPE_VALID,

    "inherited_contract_invalid":
        BLOCK_9_INHERITED_CONTRACT_VALID,

    "artefact_references_invalid":
        BLOCK_9_ARTEFACT_REFERENCES_VALID,

    "group_path_policy_invalid":
        BLOCK_9_GROUP_PATH_POLICY_VALID,

    "notebook_08_starting_policy_invalid":
        BLOCK_9_NOTEBOOK_08_STARTING_POLICY_VALID,

    "handover_not_persisted":
        BLOCK_9_HANDOVER_DRIVE_PERSISTED,

    "handover_loss_families_invalid":
        BLOCK_9_HANDOVER_READBACK_LOSS_FAMILIES_VALID,

    "handover_readback_invalid":
        BLOCK_9_HANDOVER_READBACK_VALID,

    "parameters_changed":
        BLOCK_9_ALL_PARAMETERS_UNCHANGED,

    "notebook_07_not_ready_for_notebook_08":
        NOTEBOOK_07_READY_FOR_NOTEBOOK_08,

    "notebook_07_not_complete":
        NOTEBOOK_07_COMPLETE,
}


for (
    error_name,
    condition,
) in block_9_validation_checks.items():

    if not condition:

        NOTEBOOK_07_BLOCK_9_ERRORS.append(
            error_name
        )


# =============================================================================
# Prohibited Block 9 operations
# =============================================================================

prohibited_block_9_operations = {
    "forward_pass_incorrectly_executed":
        BLOCK_9_FORWARD_PASS_EXECUTED,

    "supervised_loss_incorrectly_calculated":
        BLOCK_9_SUPERVISED_LOSS_CALCULATED,

    "optimizer_incorrectly_created":
        BLOCK_9_OPTIMIZER_CREATED,

    "zero_grad_incorrectly_executed":
        BLOCK_9_ZERO_GRAD_EXECUTED,

    "backward_pass_incorrectly_executed":
        BLOCK_9_BACKWARD_PASS_EXECUTED,

    "optimizer_step_incorrectly_executed":
        BLOCK_9_OPTIMIZER_STEP_EXECUTED,

    "parameter_update_incorrectly_executed":
        BLOCK_9_PARAMETER_UPDATE_EXECUTED,

    "additional_social_training_incorrectly_executed":
        BLOCK_9_ADDITIONAL_SOCIAL_TRAINING_EXECUTED,

    "psychological_retraining_incorrectly_executed":
        BLOCK_9_PSYCHOLOGICAL_RETRAINING_EXECUTED,

    "factual_retraining_incorrectly_executed":
        BLOCK_9_FACTUAL_RETRAINING_EXECUTED,

    "backbone_training_incorrectly_executed":
        BLOCK_9_BACKBONE_TRAINING_EXECUTED,

    "global_confluent_training_incorrectly_executed":
        BLOCK_9_GLOBAL_CONFLUENT_TRAINING_EXECUTED,

    "group_conditioned_path_incorrectly_executed":
        BLOCK_9_GROUP_CONDITIONED_PATH_EXECUTED,

    "transformative_mechanism_incorrectly_executed":
        BLOCK_9_TRANSFORMATIVE_MECHANISM_EXECUTED,

    "transformative_weights_incorrectly_executed":
        BLOCK_9_TRANSFORMATIVE_WEIGHTS_EXECUTED,

    "recurrent_mechanism_incorrectly_executed":
        BLOCK_9_RECURRENT_MECHANISM_EXECUTED,

    "held_out_evaluation_incorrectly_executed":
        BLOCK_9_HELD_OUT_EVALUATION_EXECUTED,

    "empirical_validity_incorrectly_asserted":
        BLOCK_9_EMPIRICAL_VALIDITY_ESTABLISHED,
}


for (
    error_name,
    operation_executed,
) in prohibited_block_9_operations.items():

    if operation_executed:

        NOTEBOOK_07_BLOCK_9_ERRORS.append(
            error_name
        )


# =============================================================================
# Final Block 9 state
# =============================================================================

NOTEBOOK_07_BLOCK_9_VALID = (
    len(
        NOTEBOOK_07_BLOCK_9_ERRORS
    )
    ==
    0
)


if not NOTEBOOK_07_BLOCK_9_VALID:

    raise RuntimeError(
        "Notebook 07 Block 9 Social Representation completion "
        "audit failed. "
        f"Errors: {NOTEBOOK_07_BLOCK_9_ERRORS}"
    )


NOTEBOOK_07_BLOCK_9_COMPLETE = True


# =============================================================================
# Final completion summary
# =============================================================================

NOTEBOOK_07_BLOCK_9_SUMMARY = {
    "block":
        NOTEBOOK_07_BLOCK_9,

    "block_name":
        NOTEBOOK_07_BLOCK_9_NAME,

    "version":
        NOTEBOOK_07_BLOCK_9_VERSION,

    "executed_at_utc":
        BLOCK_9_EXECUTED_AT_UTC,

    "blocks_1_to_8_complete":
        BLOCK_9_PREVIOUS_BLOCKS_COMPLETE,

    "blocks_1_to_8_valid":
        BLOCK_9_PREVIOUS_BLOCKS_VALID,

    "article_count":
        NOTEBOOK_07_ARTICLE_COUNT,

    "sentence_count":
        NOTEBOOK_07_SENTENCE_COUNT,

    "social_representation_dim":
        NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM,

    "active_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS
        ),

    "deferred_dimensions":
        list(
            NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
        ),

    "active_loss_families":
        deepcopy(
            NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES
        ),

    "deferral_reasons":
        deepcopy(
            BLOCK_9_SOCIAL_DEFERRAL_REASONS
        ),

    "social_parameter_count":
        BLOCK_9_SOCIAL_HEAD_PARAMETER_COUNT,

    "training_articles":
        BLOCK_9_TRAINING_ARTICLE_COUNT,

    "training_sentences":
        BLOCK_9_TRAINING_SENTENCE_COUNT,

    "validation_sentences":
        BLOCK_9_VALIDATION_SENTENCE_COUNT,

    "test_sentences":
        BLOCK_9_TEST_SENTENCE_COUNT,

    "training_epochs":
        BLOCK_9_TRAINING_EPOCH_COUNT,

    "initial_objective":
        BLOCK_9_INITIAL_SOCIAL_OBJECTIVE,

    "final_objective":
        BLOCK_9_FINAL_SOCIAL_OBJECTIVE,

    "objective_reduction":
        BLOCK_9_SOCIAL_OBJECTIVE_REDUCTION,

    "checkpoint_type":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE,

    "checkpoint_filename":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_FILENAME,

    "checkpoint_drive_file_id":
        NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID,

    "metadata_filename":
        NOTEBOOK_07_SOCIAL_METADATA_FILENAME,

    "metadata_drive_file_id":
        NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID,

    "target_contract_filename":
        BLOCK_9_SOCIAL_TARGET_CONTRACT_FILENAME,

    "target_contract_drive_file_id":
        BLOCK_9_SOCIAL_TARGET_CONTRACT_DRIVE_FILE_ID,

    "checkpoint_reproducible":
        BLOCK_9_SOCIAL_CHECKPOINT_REPRODUCIBLE,

    "reproducibility_source":
        BLOCK_9_BLOCK_8_REPRODUCIBILITY_FLAG_SOURCE,

    "validated_model_checkpoint":
        False,

    "all_social_dimensions_trained":
        NOTEBOOK_07_SOCIAL_ALL_DIMENSIONS_TRAINED,

    "full_social_training_coverage":
        NOTEBOOK_07_SOCIAL_FULL_TRAINING_COVERAGE,

    "held_out_generalisation_validated":
        False,

    "empirical_validity":
        False,

    "group_conditioned_path_executed":
        False,

    "transformative_mechanism_executed":
        False,

    "transformative_weights_active":
        False,

    "recurrent_mechanism_executed":
        False,

    "handover_version":
        NOTEBOOK_07_TO_08_HANDOVER_VERSION,

    "handover_filename":
        NOTEBOOK_07_TO_08_HANDOVER_FILENAME,

    "handover_drive_file_id":
        NOTEBOOK_07_TO_08_HANDOVER_DRIVE_FILE_ID,

    "handover_readback_valid":
        BLOCK_9_HANDOVER_READBACK_VALID,

    "ready_for_notebook_08":
        NOTEBOOK_07_READY_FOR_NOTEBOOK_08,

    "notebook_07_complete":
        NOTEBOOK_07_COMPLETE,

    "full_media_ai_project_complete":
        False,

    "block_valid":
        NOTEBOOK_07_BLOCK_9_VALID,

    "block_complete":
        NOTEBOOK_07_BLOCK_9_COMPLETE,
}


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 07, Block 9: "
    "Social Representation Scope Audit, "
    "Persistent Handover and Notebook 07 Completion"
)

print("=" * 72)

print(
    f"Completion version           : "
    f"{NOTEBOOK_07_BLOCK_9_VERSION}"
)


print("-" * 72)

print(
    "Notebook 07 completion"
)

print(
    f"Blocks 1–8 complete          : "
    f"{BLOCK_9_PREVIOUS_BLOCKS_COMPLETE}"
)

print(
    f"Blocks 1–8 valid             : "
    f"{BLOCK_9_PREVIOUS_BLOCKS_VALID}"
)

print(
    f"Social path complete         : "
    f"{NOTEBOOK_07_SOCIAL_PATH_COMPLETE}"
)

print(
    f"Controlled social pipeline   : "
    f"{NOTEBOOK_07_CONTROLLED_SOCIAL_PIPELINE_COMPLETE}"
)

print(
    f"Social path reproducible     : "
    f"{NOTEBOOK_07_SOCIAL_PATH_REPRODUCIBLE}"
)

print(
    f"Notebook 07 complete         : "
    f"{NOTEBOOK_07_COMPLETE}"
)

print(
    f"Full Media AI project complete: "
    f"{NOTEBOOK_07_FULL_MEDIA_AI_PROJECT_COMPLETE}"
)

print(
    f"Full social training coverage: "
    f"{NOTEBOOK_07_FULL_SOCIAL_TRAINING_COVERAGE}"
)

print(
    f"Generalisation validated     : "
    f"{NOTEBOOK_07_HELD_OUT_GENERALISATION_VALIDATED}"
)


print("-" * 72)

print(
    "Inherited Notebook 06 -> 07 contract"
)

print(
    f"Handover present             : "
    f"{BLOCK_9_INHERITED_HANDOVER_PRESENT}"
)

print(
    f"Block 1 complete             : "
    f"{NOTEBOOK_07_BLOCK_1_COMPLETE}"
)

print(
    f"Block 1 handover valid       : "
    f"{NOTEBOOK_07_BLOCK_1_VALID}"
)

print(
    f"Inherited contract valid     : "
    f"{BLOCK_9_INHERITED_CONTRACT_VALID}"
)


print("-" * 72)

print(
    "Social semantic contract"
)

print(
    f"Social representation dim.   : "
    f"{NOTEBOOK_07_SOCIAL_REPRESENTATION_DIM}"
)

print(
    f"Semantic contract valid      : "
    f"{BLOCK_9_SOCIAL_SEMANTIC_CONTRACT_VALID}"
)

print(
    f"Active dimensions            : "
    f"{list(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)}"
)

print(
    f"Deferred dimensions          : "
    f"{list(NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS)}"
)

print(
    f"Objective weights            : "
    f"{NOTEBOOK_07_SOCIAL_OBJECTIVE_WEIGHTS}"
)

print(
    f"Active loss families         : "
    f"{NOTEBOOK_07_SOCIAL_ACTIVE_LOSS_FAMILIES}"
)

print(
    f"Objective weight sum         : "
    f"{BLOCK_9_OBJECTIVE_WEIGHT_SUM:.4f}"
)


print("-" * 72)

print(
    "Social deferral semantics"
)


for dimension_name in (
    NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS
):

    print(
        f"{dimension_name:<31}: "
        f"{BLOCK_9_SOCIAL_DEFERRAL_REASONS.get(dimension_name)}"
    )


print("-" * 72)

print(
    "Social trained-state handover"
)

print(
    f"Checkpoint type              : "
    f"{NOTEBOOK_07_SOCIAL_CHECKPOINT_TYPE}"
)

print(
    f"Checkpoint Drive file ID     : "
    f"{NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID}"
)

print(
    f"Metadata Drive file ID       : "
    f"{NOTEBOOK_07_SOCIAL_METADATA_DRIVE_FILE_ID}"
)

print(
    f"Target contract Drive ID     : "
    f"{BLOCK_9_SOCIAL_TARGET_CONTRACT_DRIVE_FILE_ID}"
)

print(
    f"Contextual representation ID : "
    f"{BLOCK_5_REPRESENTATION_DRIVE_FILE_ID}"
)

print(
    f"Checkpoint reproducible      : "
    f"{BLOCK_9_SOCIAL_CHECKPOINT_REPRODUCIBLE}"
)

print(
    f"Reproducibility source       : "
    f"{BLOCK_9_BLOCK_8_REPRODUCIBILITY_FLAG_SOURCE}"
)

print(
    f"Final Social objective       : "
    f"{BLOCK_9_FINAL_SOCIAL_OBJECTIVE:.8f}"
)

print(
    f"Validated model checkpoint   : "
    f"{NOTEBOOK_07_SOCIAL_VALIDATED_MODEL_CHECKPOINT}"
)


print("-" * 72)

print(
    "Training scope boundary"
)

print(
    f"Training articles            : "
    f"{BLOCK_9_TRAINING_ARTICLE_COUNT}"
)

print(
    f"Training sentences           : "
    f"{BLOCK_9_TRAINING_SENTENCE_COUNT}"
)

print(
    f"Validation sentences         : "
    f"{BLOCK_9_VALIDATION_SENTENCE_COUNT}"
)

print(
    f"Test sentences               : "
    f"{BLOCK_9_TEST_SENTENCE_COUNT}"
)

print(
    f"Epochs                       : "
    f"{BLOCK_9_TRAINING_EPOCH_COUNT}"
)

print(
    f"All dimensions trained       : "
    f"{NOTEBOOK_07_SOCIAL_ALL_DIMENSIONS_TRAINED}"
)

print(
    f"Full training coverage       : "
    f"{NOTEBOOK_07_SOCIAL_FULL_TRAINING_COVERAGE}"
)

print(
    f"Held-out generalisation      : "
    f"{NOTEBOOK_07_SOCIAL_GENERALISATION_VALIDATED}"
)

print(
    f"Empirically validated        : "
    f"{NOTEBOOK_07_SOCIAL_EMPIRICALLY_VALIDATED}"
)


print("-" * 72)

print(
    "Module boundary"
)

print(
    f"Backbone checkpoint match    : "
    f"{BLOCK_9_RUNTIME_BACKBONE_MATCHES_CHECKPOINT}"
)

print(
    f"Global confluent match       : "
    f"{BLOCK_9_RUNTIME_GLOBAL_MATCHES_CHECKPOINT}"
)

print(
    f"Psychological checkpoint match: "
    f"{BLOCK_9_RUNTIME_PSYCHOLOGICAL_MATCHES_CHECKPOINT}"
)

print(
    f"Factual checkpoint match     : "
    f"{BLOCK_9_RUNTIME_FACTUAL_MATCHES_CHECKPOINT}"
)

print(
    f"Social checkpoint match      : "
    f"{BLOCK_9_RUNTIME_SOCIAL_MATCHES_CHECKPOINT}"
)

print(
    f"Social parameter count       : "
    f"{BLOCK_9_SOCIAL_HEAD_PARAMETER_COUNT}"
)

print(
    f"All parameters unchanged     : "
    f"{BLOCK_9_ALL_PARAMETERS_UNCHANGED}"
)


print("-" * 72)

print(
    "Remaining Version 1 roadmap"
)


for (
    notebook_name,
    notebook_designation,
) in NOTEBOOK_07_REMAINING_VERSION_1_ROADMAP.items():

    print(
        f"{notebook_name:<25}: "
        f"{notebook_designation}"
    )


print("-" * 72)

print(
    "Group-conditioned path policy"
)

print(
    f"Global path required         : "
    f"{NOTEBOOK_07_COMPLETION_GLOBAL_PATH_REQUIRED}"
)

print(
    f"Global path operational      : "
    f"{NOTEBOOK_07_COMPLETION_GLOBAL_PATH_OPERATIONAL}"
)

print(
    f"Group path available         : "
    f"{NOTEBOOK_07_COMPLETION_GROUP_PATH_AVAILABLE}"
)

print(
    f"Group path required          : "
    f"{NOTEBOOK_07_COMPLETION_GROUP_PATH_REQUIRED}"
)

print(
    f"Group path executed          : "
    f"{NOTEBOOK_07_COMPLETION_GROUP_PATH_EXECUTED}"
)

print(
    f"Group path trained           : "
    f"{NOTEBOOK_07_COMPLETION_GROUP_PATH_TRAINED}"
)

print(
    f"Group path deferred to N     : "
    f"{NOTEBOOK_07_COMPLETION_GROUP_PATH_DEFERRED_TO_NOTEBOOK}"
)


print("-" * 72)

print(
    "Persistent Notebook 07 -> Notebook 08 handover"
)

print(
    f"Handover version             : "
    f"{NOTEBOOK_07_TO_08_HANDOVER_VERSION}"
)

print(
    f"Handover filename            : "
    f"{NOTEBOOK_07_TO_08_HANDOVER_FILENAME}"
)

print(
    f"Local copy created           : "
    f"{BLOCK_9_LOCAL_HANDOVER_CREATED}"
)

print(
    f"Drive operation              : "
    f"{NOTEBOOK_07_TO_08_HANDOVER_DRIVE_OPERATION}"
)

print(
    f"Drive file ID                : "
    f"{NOTEBOOK_07_TO_08_HANDOVER_DRIVE_FILE_ID}"
)

print(
    f"Read-back valid              : "
    f"{BLOCK_9_HANDOVER_READBACK_VALID}"
)

print(
    f"Notebook 08 ready            : "
    f"{NOTEBOOK_07_READY_FOR_NOTEBOOK_08}"
)


print("-" * 72)

print(
    "Notebook 08 starting contract"
)

print(
    f"Designation                  : "
    f"{NOTEBOOK_08_STARTING_POLICY['designation']}"
)

print(
    f"Backbone frozen by default   : "
    f"{NOTEBOOK_08_STARTING_POLICY['backbone_frozen_by_default']}"
)

print(
    f"Global confluent frozen      : "
    f"{NOTEBOOK_08_STARTING_POLICY['global_confluent_frozen_by_default']}"
)

print(
    f"Psychological path frozen    : "
    f"{NOTEBOOK_08_STARTING_POLICY['psychological_representation_frozen_by_default']}"
)

print(
    f"Factual path frozen          : "
    f"{NOTEBOOK_08_STARTING_POLICY['factual_representation_frozen_by_default']}"
)

print(
    f"Social path frozen           : "
    f"{NOTEBOOK_08_STARTING_POLICY['social_representation_frozen_by_default']}"
)

print(
    f"Transformative may initialise: "
    f"{NOTEBOOK_08_STARTING_POLICY['transformative_mechanism_may_initialise']}"
)


print("-" * 72)

print(
    "Execution boundary"
)

print(
    f"Forward pass executed        : "
    f"{BLOCK_9_FORWARD_PASS_EXECUTED}"
)

print(
    f"Loss calculated              : "
    f"{BLOCK_9_SUPERVISED_LOSS_CALCULATED}"
)

print(
    f"Optimiser created            : "
    f"{BLOCK_9_OPTIMIZER_CREATED}"
)

print(
    f"Zero grad executed           : "
    f"{BLOCK_9_ZERO_GRAD_EXECUTED}"
)

print(
    f"Backward pass executed       : "
    f"{BLOCK_9_BACKWARD_PASS_EXECUTED}"
)

print(
    f"Optimiser step executed      : "
    f"{BLOCK_9_OPTIMIZER_STEP_EXECUTED}"
)

print(
    f"Parameter update executed    : "
    f"{BLOCK_9_PARAMETER_UPDATE_EXECUTED}"
)

print(
    f"Additional Social training   : "
    f"{BLOCK_9_ADDITIONAL_SOCIAL_TRAINING_EXECUTED}"
)

print(
    f"Psychological retraining     : "
    f"{BLOCK_9_PSYCHOLOGICAL_RETRAINING_EXECUTED}"
)

print(
    f"Factual retraining           : "
    f"{BLOCK_9_FACTUAL_RETRAINING_EXECUTED}"
)

print(
    f"Group-conditioned executed   : "
    f"{BLOCK_9_GROUP_CONDITIONED_PATH_EXECUTED}"
)

print(
    f"Transformative executed      : "
    f"{BLOCK_9_TRANSFORMATIVE_MECHANISM_EXECUTED}"
)

print(
    f"Transformative weights active: "
    f"{BLOCK_9_TRANSFORMATIVE_WEIGHTS_EXECUTED}"
)

print(
    f"Recurrent executed           : "
    f"{BLOCK_9_RECURRENT_MECHANISM_EXECUTED}"
)

print(
    f"Held-out evaluation executed : "
    f"{BLOCK_9_HELD_OUT_EVALUATION_EXECUTED}"
)

print(
    f"Empirical validity           : "
    f"{BLOCK_9_EMPIRICAL_VALIDITY_ESTABLISHED}"
)

print(
    f"Block valid                  : "
    f"{NOTEBOOK_07_BLOCK_9_VALID}"
)

print(
    f"Block 9 complete             : "
    f"{NOTEBOOK_07_BLOCK_9_COMPLETE}"
)


print("=" * 72)


print(
    "Notebook 07 Social Representation scope audit, persistent handover "
    "and completion validation completed successfully."
)

print(
    "The complete Notebook 07 Blocks 1–8 execution chain remains "
    "complete and valid."
)

print(
    "The seven-dimensional Social Representation semantic contract "
    "remains intact."
)

print(
    f"{len(NOTEBOOK_07_SOCIAL_ACTIVE_DIMENSIONS)} Social Representation "
    "dimension(s) participated in the current controlled optimisation "
    "under the validated Block 4 activation contract."
)

print(
    f"{len(NOTEBOOK_07_SOCIAL_DEFERRED_DIMENSIONS)} Social Representation "
    "dimension(s) remain structurally present and deferred according to "
    "the persisted Block 4 deferral semantics."
)

print(
    "Deferred dimensions have not been removed and have not been "
    "reinterpreted as numerical zero or negative supervision."
)

print(
    "The validated "
    f"{NOTEBOOK_07_TEXTUAL_REPRESENTATION_DIM}-dimensional contextual "
    "sentence representation, "
    f"{NOTEBOOK_07_BACKBONE_INTERFACE_DIM}-dimensional backbone interface "
    "and "
    f"{NOTEBOOK_07_GLOBAL_CONFLUENT_DIM}-dimensional mandatory global "
    "confluent representation remain part of the completed Social "
    "Representation forward architecture."
)

print(
    "The inherited backbone, mandatory global confluent representation, "
    "Psychological Representation and Factual Representation remain "
    "unchanged relative to the final persisted Social checkpoint."
)

print(
    "The trained Social Representation state matches the persisted "
    "controlled experimental Social checkpoint exactly."
)

print(
    "The Social checkpoint and training metadata remain reproducible "
    "under the validated Block 8 boundary."
)

print(
    "The checkpoint remains explicitly classified as a controlled "
    "experimental Social Representation training checkpoint rather than "
    "a validated model checkpoint."
)

print(
    "No held-out evaluation, generalisation claim or empirical-validity "
    "claim has been introduced."
)

print(
    "The optional group-conditioned path remains architecturally "
    "available but inactive and deferred to Notebook 10."
)

print(
    "The Transformative Mechanism remains outside Notebook 07 and may "
    "initialise in Notebook 08."
)

print(
    "Transformative Weights and the recurrent mechanism remain inactive "
    "and reserved for Notebook 09."
)

print(
    "Block 9 performed no forward pass, supervised loss calculation, "
    "optimiser creation, zero-gradient operation, backward pass, optimiser "
    "step, parameter update or additional model training."
)

print(
    "The persistent Notebook 07 -> Notebook 08 handover was created, "
    "read back and validated successfully."
)

print(
    "Notebook 07 — Social Representation is complete within its "
    "controlled experimental scope."
)

print(
    "The full Media AI Version 1 project remains incomplete."
)

print(
    "Notebook 08 — Transformative Mechanism may now initialise "
    "independently from the persisted Notebook 07 state while keeping "
    "the completed representation paths frozen by default."
)

print("=" * 72)


# =============================================================================
# Display completion audit tables
# =============================================================================

display(
    BLOCK_9_SOCIAL_DIMENSION_AUDIT
)


display(
    BLOCK_9_FUNCTIONALITY_AUDIT
)

========================================================================
Media AI — Notebook 07, Block 9: Social Representation Scope Audit, Persistent Handover and Notebook 07 Completion
========================================================================
Completion version           : 1.2
------------------------------------------------------------------------
Notebook 07 completion
Blocks 1–8 complete          : True
Blocks 1–8 valid             : True
Social path complete         : True
Controlled social pipeline   : True
Social path reproducible     : True
Notebook 07 complete         : True
Full Media AI project complete: False
Full social training coverage: False
Generalisation validated     : False
------------------------------------------------------------------------
Inherited Notebook 06 -> 07 contract
Handover present             : True
Block 1 complete             : True
Block 1 handover valid       : True
Inherited contract valid     : True
------------------------------------------------------------------------
Social semantic contract
Social representation dim.   : 7
Semantic contract valid      : True
Active dimensions            : ['interpersonal_cohesion', 'economic_cohesion', 'political_cohesion', 'group_collective_cohesion']
Deferred dimensions          : ['religious_cohesion', 'institutional_role_relation', 'public_audience_relation']
Objective weights            : {'interpersonal_cohesion': 0.25, 'economic_cohesion': 0.25, 'political_cohesion': 0.25, 'group_collective_cohesion': 0.25}
Active loss families         : {'interpersonal_cohesion': 'masked_mean_squared_error', 'economic_cohesion': 'masked_mean_squared_error', 'political_cohesion': 'masked_mean_squared_error', 'group_collective_cohesion': 'masked_mean_squared_error'}
Objective weight sum         : 1.0000
------------------------------------------------------------------------
Social deferral semantics
religious_cohesion             : unavailable_supervision
institutional_role_relation    : zero_variance
public_audience_relation       : zero_variance
------------------------------------------------------------------------
Social trained-state handover
Checkpoint type              : controlled_experimental_social_representation_training_checkpoint
Checkpoint Drive file ID     : 1InCGr7QeNcd3RtrZ1aLIyKYvX0cOZNLU
Metadata Drive file ID       : 1CiBJnkFFjEEgB2nqWew6Ilp6O5eOC86k
Target contract Drive ID     : 1RMofcYIqIFKH9FqSrAz5hjbicfSNu5ex
Contextual representation ID : 11_j_CebqBpMSDLlccGwGROr5hklTBYRm
Checkpoint reproducible      : True
Reproducibility source       : NOTEBOOK_07_SOCIAL_CHECKPOINT_REPRODUCIBLE
Final Social objective       : 0.01394366
Validated model checkpoint   : False
------------------------------------------------------------------------
Training scope boundary
Training articles            : 3
Training sentences           : 54
Validation sentences         : 0
Test sentences               : 0
Epochs                       : 10
All dimensions trained       : False
Full training coverage       : False
Held-out generalisation      : False
Empirically validated        : False
------------------------------------------------------------------------
Module boundary
Backbone checkpoint match    : True
Global confluent match       : True
Psychological checkpoint match: True
Factual checkpoint match     : True
Social checkpoint match      : True
Social parameter count       : 34055
All parameters unchanged     : True
------------------------------------------------------------------------
Remaining Version 1 roadmap
Notebook 08              : Transformative Mechanism
Notebook 09              : Transformative Weights and Recurrent Mechanism
Notebook 10              : Group-Conditioned Path and Final Integration
------------------------------------------------------------------------
Group-conditioned path policy
Global path required         : True
Global path operational      : True
Group path available         : True
Group path required          : False
Group path executed          : False
Group path trained           : False
Group path deferred to N     : 10
------------------------------------------------------------------------
Persistent Notebook 07 -> Notebook 08 handover
Handover version             : 1.2
Handover filename            : notebook_07_to_08_handover.json
Local copy created           : True
Drive operation              : updated
Drive file ID                : 16yoADfsS5hpbMg50nBnAyK-yeNFRV3GL
Read-back valid              : True
Notebook 08 ready            : True
------------------------------------------------------------------------
Notebook 08 starting contract
Designation                  : Transformative Mechanism
Backbone frozen by default   : True
Global confluent frozen      : True
Psychological path frozen    : True
Factual path frozen          : True
Social path frozen           : True
Transformative may initialise: True
------------------------------------------------------------------------
Execution boundary
Forward pass executed        : False
Loss calculated              : False
Optimiser created            : False
Zero grad executed           : False
Backward pass executed       : False
Optimiser step executed      : False
Parameter update executed    : False
Additional Social training   : False
Psychological retraining     : False
Factual retraining           : False
Group-conditioned executed   : False
Transformative executed      : False
Transformative weights active: False
Recurrent executed           : False
Held-out evaluation executed : False
Empirical validity           : False
Block valid                  : True
Block 9 complete             : True
========================================================================
Notebook 07 Social Representation scope audit, persistent handover and completion validation completed successfully.
The complete Notebook 07 Blocks 1–8 execution chain remains complete and valid.
The seven-dimensional Social Representation semantic contract remains intact.
4 Social Representation dimension(s) participated in the current controlled optimisation under the validated Block 4 activation contract.
3 Social Representation dimension(s) remain structurally present and deferred according to the persisted Block 4 deferral semantics.
Deferred dimensions have not been removed and have not been reinterpreted as numerical zero or negative supervision.
The validated 768-dimensional contextual sentence representation, 768-dimensional backbone interface and 256-dimensional mandatory global confluent representation remain part of the completed Social Representation forward architecture.
The inherited backbone, mandatory global confluent representation, Psychological Representation and Factual Representation remain unchanged relative to the final persisted Social checkpoint.
The trained Social Representation state matches the persisted controlled experimental Social checkpoint exactly.
The Social checkpoint and training metadata remain reproducible under the validated Block 8 boundary.
The checkpoint remains explicitly classified as a controlled experimental Social Representation training checkpoint rather than a validated model checkpoint.
No held-out evaluation, generalisation claim or empirical-validity claim has been introduced.
The optional group-conditioned path remains architecturally available but inactive and deferred to Notebook 10.
The Transformative Mechanism remains outside Notebook 07 and may initialise in Notebook 08.
Transformative Weights and the recurrent mechanism remain inactive and reserved for Notebook 09.
Block 9 performed no forward pass, supervised loss calculation, optimiser creation, zero-gradient operation, backward pass, optimiser step, parameter update or additional model training.
The persistent Notebook 07 -> Notebook 08 handover was created, read back and validated successfully.
Notebook 07 — Social Representation is complete within its controlled experimental scope.
The full Media AI Version 1 project remains incomplete.
Notebook 08 — Transformative Mechanism may now initialise independently from the persisted Notebook 07 state while keeping the completed representation paths frozen by default.
========================================================================

,dimension_id,dimension_index,target_name,structurally_present,currently_active,currently_deferred,deferral_reason,objective_family,optimisation_state,checkpoint_state_reproducible,independently_evaluated,empirically_validated
0,S1,0,interpersonal_cohesion,True,True,False,None,masked_mean_squared_error,trained,True,False,False
1,S2,1,economic_cohesion,True,True,False,None,masked_mean_squared_error,trained,True,False,False
2,S3,2,political_cohesion,True,True,False,None,masked_mean_squared_error,trained,True,False,False
3,S4,3,religious_cohesion,True,False,True,unavailable_supervision,none_current_sample,deferred_unavailable_supervision,not_applicable,False,False
4,S5,4,group_collective_cohesion,True,True,False,None,masked_mean_squared_error,trained,True,False,False
5,S6,5,institutional_role_relation,True,False,True,zero_variance,none_current_sample,deferred_zero_variance,not_applicable,False,False
6,S7,6,public_audience_relation,True,False,True,zero_variance,none_current_sample,deferred_zero_variance,not_applicable,False,False

,functionality,architecture_stage,implemented_structurally,used_in_notebook_07,trained_in_notebook_07,checkpoint_or_state_reproducible,independently_evaluated,empirically_validated,notes
0,contextual_sentence_representation,textual_representation,True,True,False,True,False,False,Inherited persisted 768-dimensional contextual...
1,mandatory_global_confluent_path,confluent_conditioning,True,True,False,True,False,False,Mandatory global conditioning remained frozen ...
2,psychological_representation_head,representation_heads,True,False,False,True,False,False,Completed inherited Psychological Representati...
3,factual_representation_head,representation_heads,True,False,False,True,False,False,Completed inherited Factual Representation rem...
4,social_representation_head,representation_heads,True,True,True,True,False,False,Controlled Social Representation training comp...
5,transformative_mechanism,transformative_mechanism,True,False,False,False,False,False,Reserved for Notebook 08.
6,transformative_weights,transformative_mechanism,True,False,False,False,False,False,Reserved for Notebook 09.
7,recurrent_mechanism,recurrent_mechanism,True,False,False,False,False,False,Reserved for Notebook 09.
8,optional_group_conditioned_path,confluent_conditioning,True,False,False,False,False,False,Architecturally available but deliberately def...

In [ ]:
# =============================================================================
# Media AI — Notebook 07
# Diagnostic: identify instantiated PyTorch model objects
# =============================================================================

import torch

print("=" * 72)
print("Notebook 07 — PyTorch Model Object Diagnostic")
print("=" * 72)

model_candidates = []

for name, value in globals().items():
    if isinstance(value, torch.nn.Module):
        model_candidates.append(
            (
                name,
                value.__class__.__name__,
                sum(
                    parameter.numel()
                    for parameter in value.parameters()
                ),
            )
        )

if not model_candidates:
    print("No torch.nn.Module objects were found in the current runtime.")
else:
    for name, class_name, parameter_count in sorted(model_candidates):
        print(f"Variable name               : {name}")
        print(f"Class                       : {class_name}")
        print(f"Parameter count             : {parameter_count:,}")
        print("-" * 72)

print(f"Model candidates found      : {len(model_candidates)}")
print("=" * 72)

## Block 10 — Validated Representation-Model Handover Persistence

This block persists the final validated representation-model state produced by Notebook 07 and establishes the explicit computational handover contract required by the subsequent transformative-mechanism stage.

The persisted artefact contains the five validated components of the restored representation architecture:

* the shared backbone;
* the global confluent layer;
* the psychological representation head;
* the factual representation head;
* the social representation head.

Together, these components contain **894,003 persisted parameters** and define the representation-model state inherited by Notebook 08.

The block stores the component parameters as structured PyTorch state dictionaries rather than serialising transient runtime objects. A separate metadata artefact records the architecture classes, component-level parameter counts, total parameter count, numerical configuration, represented spaces, and the intended stage of the notebook-to-notebook handover.

The persistence contract deliberately terminates at the representation level. Notebook 07 does not create or persist the subsequent transformative quantities

$$
TW_F,\qquad TW_P,\qquad TW_S
$$

or the recurrent states

$$
H_F,\qquad H_P,\qquad H_S.
$$

Accordingly, the persisted checkpoint should be interpreted as the validated initial representation-model state from which the transformative architecture can be constructed. It is not a checkpoint of an already operational transformative mechanism.

The block performs the following operations:

* verifies that all five required validated PyTorch modules are present;
* records the parameter count of each inherited architectural component;
* constructs a structured checkpoint containing the component state dictionaries;
* records the project seed and numerical dtype associated with the handover;
* writes explicit JSON metadata describing the persisted architecture and representation spaces;
* records that transformative mechanisms, transformation weights, and recurrent states have not yet been instantiated;
* verifies successful creation of both persistence artefacts;
* reports the final checkpoint locations, sizes, and parameter counts.

The resulting handover consists of:

`notebook_07_final_checkpoint.pt`

containing the validated representation-model parameter state, and

`notebook_07_final_metadata.json`

containing the corresponding architecture and handover metadata.

This persistence step establishes a reproducible boundary between the two modelling stages:

$$
\text{validated representation model}
;\longrightarrow;
\text{persistent Notebook 07 handover}
;\longrightarrow;
\text{Notebook 08 transformative mechanism}.
$$

No model training, representation recomputation, recurrent-state update, or transformative operation is performed by this block. Its sole state-changing responsibility is the controlled persistence of the validated Notebook 07 representation architecture for deterministic restoration and extension in Notebook 08.

In [28]:
# =============================================================================
# Media AI — Notebook 07
# Block 10: Validated Representation-Model Handover Persistence
# =============================================================================

from datetime import datetime, timezone

import io
import json

import torch

from googleapiclient.http import (
    MediaIoBaseDownload,
    MediaIoBaseUpload,
)


# =============================================================================
# Block identity
# =============================================================================

NOTEBOOK_07_BLOCK_10 = 10

NOTEBOOK_07_BLOCK_10_NAME = (
    "Validated Representation-Model Handover Persistence"
)

NOTEBOOK_07_BLOCK_10_VERSION = "1.1"

NOTEBOOK_07_TO_08_CHECKPOINT_FILENAME = (
    "notebook_07_final_checkpoint.pt"
)

NOTEBOOK_07_TO_08_METADATA_FILENAME = (
    "notebook_07_final_metadata.json"
)

BLOCK_10_EXECUTED_AT_UTC = (
    datetime.now(
        timezone.utc
    ).isoformat()
)


# =============================================================================
# Reproducibility contract
# =============================================================================

SEED = 42


# =============================================================================
# Dependency checks
# =============================================================================

required_block_10_objects = [
    "NOTEBOOK_07_DRIVE_SERVICE",

    "BLOCK_8_RESTORED_BACKBONE",
    "BLOCK_8_RESTORED_GLOBAL_CONFLUENT",
    "BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD",
    "BLOCK_8_RESTORED_FACTUAL_HEAD",
    "BLOCK_8_RESTORED_SOCIAL_HEAD",

    "NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID",
]


missing_block_10_objects = [
    object_name
    for object_name
    in required_block_10_objects
    if object_name not in globals()
]


if missing_block_10_objects:

    raise NameError(
        "Notebook 07 Block 10 prerequisites are not initialised. "
        f"Missing: {missing_block_10_objects}"
    )


# =============================================================================
# Required validated Notebook 07 modules
# =============================================================================

REQUIRED_MODULES = {
    "backbone":
        BLOCK_8_RESTORED_BACKBONE,

    "global_confluent":
        BLOCK_8_RESTORED_GLOBAL_CONFLUENT,

    "psychological_head":
        BLOCK_8_RESTORED_PSYCHOLOGICAL_HEAD,

    "factual_head":
        BLOCK_8_RESTORED_FACTUAL_HEAD,

    "social_head":
        BLOCK_8_RESTORED_SOCIAL_HEAD,
}


for (
    module_name,
    module,
) in REQUIRED_MODULES.items():

    if not isinstance(
        module,
        torch.nn.Module,
    ):

        raise TypeError(
            f"Required module '{module_name}' "
            "is not a torch.nn.Module."
        )


# =============================================================================
# Parameter accounting
# =============================================================================

MODULE_PARAMETER_COUNTS = {
    module_name:
        sum(
            parameter.numel()

            for parameter
            in module.parameters()
        )

    for (
        module_name,
        module,
    ) in REQUIRED_MODULES.items()
}


TOTAL_PARAMETER_COUNT = sum(
    MODULE_PARAMETER_COUNTS.values()
)


BLOCK_10_PARAMETER_COUNTS_POSITIVE = all(
    parameter_count > 0

    for parameter_count
    in MODULE_PARAMETER_COUNTS.values()
)


BLOCK_10_PARAMETER_COUNT_VALID = all(
    [
        BLOCK_10_PARAMETER_COUNTS_POSITIVE,
        TOTAL_PARAMETER_COUNT > 0,
        TOTAL_PARAMETER_COUNT
        ==
        sum(
            MODULE_PARAMETER_COUNTS.values()
        ),
    ]
)


if not BLOCK_10_PARAMETER_COUNT_VALID:

    raise RuntimeError(
        "Notebook 07 final representation-model parameter accounting "
        "is invalid."
    )


# =============================================================================
# Construct final Notebook 07 checkpoint
# =============================================================================

NOTEBOOK_07_TO_08_CHECKPOINT = {
    "checkpoint_type":
        "validated_representation_model_handover",

    "checkpoint_version":
        NOTEBOOK_07_BLOCK_10_VERSION,

    "source_notebook":
        "07_social_path",

    "target_notebook":
        "08_transformative_mechanism",

    "created_at_utc":
        BLOCK_10_EXECUTED_AT_UTC,

    "seed":
        SEED,

    "default_dtype":
        str(
            torch.get_default_dtype()
        ),

    "architecture":
        {
            "backbone":
                REQUIRED_MODULES[
                    "backbone"
                ].__class__.__name__,

            "global_confluent":
                REQUIRED_MODULES[
                    "global_confluent"
                ].__class__.__name__,

            "psychological_head":
                REQUIRED_MODULES[
                    "psychological_head"
                ].__class__.__name__,

            "factual_head":
                REQUIRED_MODULES[
                    "factual_head"
                ].__class__.__name__,

            "social_head":
                REQUIRED_MODULES[
                    "social_head"
                ].__class__.__name__,
        },

    "parameter_counts":
        MODULE_PARAMETER_COUNTS,

    "total_parameter_count":
        TOTAL_PARAMETER_COUNT,

    "state_dicts":
        {
            module_name:
                module.state_dict()

            for (
                module_name,
                module,
            ) in REQUIRED_MODULES.items()
        },

    "representation_spaces":
        [
            "psychological",
            "factual",
            "social",
        ],

    "architectural_boundary":
        {
            "transformative_mechanism_instantiated":
                False,

            "transformation_weights_instantiated":
                False,

            "recurrent_states_instantiated":
                False,

            "future_context_permitted":
                False,
        },
}


# =============================================================================
# Construct explicit handover metadata
# =============================================================================

NOTEBOOK_07_TO_08_METADATA = {
    "metadata_type":
        "media_ai_notebook_07_to_08_representation_handover",

    "metadata_version":
        NOTEBOOK_07_BLOCK_10_VERSION,

    "source_notebook":
        "07_social_path",

    "target_notebook":
        "08_transformative_mechanism",

    "created_at_utc":
        BLOCK_10_EXECUTED_AT_UTC,

    "checkpoint_filename":
        NOTEBOOK_07_TO_08_CHECKPOINT_FILENAME,

    "checkpoint_type":
        "validated_representation_model_handover",

    "checkpoint_format":
        "structured PyTorch state-dict checkpoint",

    "seed":
        SEED,

    "default_dtype":
        str(
            torch.get_default_dtype()
        ),

    "components":
        {
            "backbone":
                {
                    "class":
                        REQUIRED_MODULES[
                            "backbone"
                        ].__class__.__name__,

                    "parameters":
                        MODULE_PARAMETER_COUNTS[
                            "backbone"
                        ],
                },

            "global_confluent":
                {
                    "class":
                        REQUIRED_MODULES[
                            "global_confluent"
                        ].__class__.__name__,

                    "parameters":
                        MODULE_PARAMETER_COUNTS[
                            "global_confluent"
                        ],
                },

            "psychological_head":
                {
                    "class":
                        REQUIRED_MODULES[
                            "psychological_head"
                        ].__class__.__name__,

                    "parameters":
                        MODULE_PARAMETER_COUNTS[
                            "psychological_head"
                        ],
                },

            "factual_head":
                {
                    "class":
                        REQUIRED_MODULES[
                            "factual_head"
                        ].__class__.__name__,

                    "parameters":
                        MODULE_PARAMETER_COUNTS[
                            "factual_head"
                        ],
                },

            "social_head":
                {
                    "class":
                        REQUIRED_MODULES[
                            "social_head"
                        ].__class__.__name__,

                    "parameters":
                        MODULE_PARAMETER_COUNTS[
                            "social_head"
                        ],
                },
        },

    "total_parameter_count":
        TOTAL_PARAMETER_COUNT,

    "representation_spaces":
        [
            "psychological",
            "factual",
            "social",
        ],

    "notebook_08_starting_state":
        {
            "designation":
                "Transformative Mechanism",

            "representation_model_available":
                True,

            "transformative_mechanism_instantiated":
                False,

            "transformation_weights_instantiated":
                False,

            "recurrent_states_instantiated":
                False,

            "future_context_permitted":
                False,

            "ready_to_initialise":
                True,
        },
}


# =============================================================================
# Resolve persistent Drive parent
# =============================================================================
#
# Reuse the same Drive folder already used by the Notebook 07 social
# checkpoint. No filesystem mount or new Google authorisation is required.
# =============================================================================

BLOCK_10_REFERENCE_DRIVE_METADATA = (
    NOTEBOOK_07_DRIVE_SERVICE.files()
    .get(
        fileId=
            NOTEBOOK_07_SOCIAL_CHECKPOINT_DRIVE_FILE_ID,

        fields=
            "id,name,parents",
    )
    .execute()
)


BLOCK_10_PARENT_IDS = (
    BLOCK_10_REFERENCE_DRIVE_METADATA.get(
        "parents",
        [],
    )
)


# =============================================================================
# Drive persistence helper
# =============================================================================

def block_10_persist_bytes_to_drive(
    drive_service,
    filename,
    raw_bytes,
    mimetype,
    parent_ids=None,
):

    escaped_filename = filename.replace(
        "'",
        "\\'",
    )


    parent_clause = ""


    if parent_ids:

        parent_clause = (
            " and '"
            +
            parent_ids[0]
            +
            "' in parents"
        )


    search_response = (
        drive_service.files()
        .list(
            q=(
                f"name = '{escaped_filename}' "
                "and trashed = false"
                f"{parent_clause}"
            ),

            spaces=
                "drive",

            fields=
                "files(id,name,modifiedTime,parents)",

            orderBy=
                "modifiedTime desc",

            pageSize=
                20,
        )
        .execute()
    )


    matching_files = search_response.get(
        "files",
        [],
    )


    media = MediaIoBaseUpload(
        io.BytesIO(
            raw_bytes
        ),

        mimetype=
            mimetype,

        resumable=
            False,
    )


    if matching_files:

        drive_file = (
            drive_service.files()
            .update(
                fileId=
                    matching_files[
                        0
                    ][
                        "id"
                    ],

                media_body=
                    media,

                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "updated"


    else:

        file_metadata = {
            "name":
                filename
        }


        if parent_ids:

            file_metadata[
                "parents"
            ] = parent_ids


        drive_file = (
            drive_service.files()
            .create(
                body=
                    file_metadata,

                media_body=
                    media,

                fields=
                    "id,name,modifiedTime,parents",
            )
            .execute()
        )


        operation = "created"


    return (
        drive_file,
        operation,
    )


# =============================================================================
# Drive download helper
# =============================================================================

def block_10_download_drive_bytes(
    drive_service,
    file_id,
):

    request = (
        drive_service.files()
        .get_media(
            fileId=
                file_id
        )
    )


    buffer = io.BytesIO()


    downloader = MediaIoBaseDownload(
        buffer,
        request,
    )


    complete = False


    while not complete:

        _, complete = (
            downloader.next_chunk()
        )


    buffer.seek(
        0
    )


    return buffer.read()


# =============================================================================
# Serialise final checkpoint
# =============================================================================

BLOCK_10_CHECKPOINT_BUFFER = io.BytesIO()


torch.save(
    NOTEBOOK_07_TO_08_CHECKPOINT,
    BLOCK_10_CHECKPOINT_BUFFER,
)


BLOCK_10_CHECKPOINT_BYTES = (
    BLOCK_10_CHECKPOINT_BUFFER.getvalue()
)


if not BLOCK_10_CHECKPOINT_BYTES:

    raise RuntimeError(
        "Notebook 07 final checkpoint serialisation produced no data."
    )


# =============================================================================
# Serialise metadata
# =============================================================================

BLOCK_10_METADATA_JSON = json.dumps(
    NOTEBOOK_07_TO_08_METADATA,
    indent=2,
    ensure_ascii=False,
)


BLOCK_10_METADATA_BYTES = (
    BLOCK_10_METADATA_JSON.encode(
        "utf-8"
    )
)


if not BLOCK_10_METADATA_BYTES:

    raise RuntimeError(
        "Notebook 07 final metadata serialisation produced no data."
    )


# =============================================================================
# Persist final checkpoint to Drive
# =============================================================================

(
    NOTEBOOK_07_TO_08_CHECKPOINT_DRIVE_FILE,
    NOTEBOOK_07_TO_08_CHECKPOINT_DRIVE_OPERATION,
) = block_10_persist_bytes_to_drive(
    drive_service=
        NOTEBOOK_07_DRIVE_SERVICE,

    filename=
        NOTEBOOK_07_TO_08_CHECKPOINT_FILENAME,

    raw_bytes=
        BLOCK_10_CHECKPOINT_BYTES,

    mimetype=
        "application/octet-stream",

    parent_ids=
        BLOCK_10_PARENT_IDS,
)


NOTEBOOK_07_TO_08_CHECKPOINT_DRIVE_FILE_ID = (
    NOTEBOOK_07_TO_08_CHECKPOINT_DRIVE_FILE.get(
        "id"
    )
)


# =============================================================================
# Persist final metadata to Drive
# =============================================================================

(
    NOTEBOOK_07_TO_08_METADATA_DRIVE_FILE,
    NOTEBOOK_07_TO_08_METADATA_DRIVE_OPERATION,
) = block_10_persist_bytes_to_drive(
    drive_service=
        NOTEBOOK_07_DRIVE_SERVICE,

    filename=
        NOTEBOOK_07_TO_08_METADATA_FILENAME,

    raw_bytes=
        BLOCK_10_METADATA_BYTES,

    mimetype=
        "application/json",

    parent_ids=
        BLOCK_10_PARENT_IDS,
)


NOTEBOOK_07_TO_08_METADATA_DRIVE_FILE_ID = (
    NOTEBOOK_07_TO_08_METADATA_DRIVE_FILE.get(
        "id"
    )
)


# =============================================================================
# Drive persistence validation
# =============================================================================

BLOCK_10_CHECKPOINT_PERSISTED = bool(
    NOTEBOOK_07_TO_08_CHECKPOINT_DRIVE_FILE_ID
)


BLOCK_10_METADATA_PERSISTED = bool(
    NOTEBOOK_07_TO_08_METADATA_DRIVE_FILE_ID
)


if not all(
    [
        BLOCK_10_CHECKPOINT_PERSISTED,
        BLOCK_10_METADATA_PERSISTED,
    ]
):

    raise RuntimeError(
        "Notebook 07 → Notebook 08 handover artefacts "
        "were not persisted successfully."
    )


# =============================================================================
# Read back final checkpoint
# =============================================================================

BLOCK_10_RELOADED_CHECKPOINT_BYTES = (
    block_10_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_TO_08_CHECKPOINT_DRIVE_FILE_ID,
    )
)


if not BLOCK_10_RELOADED_CHECKPOINT_BYTES:

    raise RuntimeError(
        "Persisted Notebook 07 checkpoint was empty."
    )


BLOCK_10_RELOADED_CHECKPOINT = torch.load(
    io.BytesIO(
        BLOCK_10_RELOADED_CHECKPOINT_BYTES
    ),

    map_location=
        "cpu",

    weights_only=
        False,
)


# =============================================================================
# Read back final metadata
# =============================================================================

BLOCK_10_RELOADED_METADATA_BYTES = (
    block_10_download_drive_bytes(
        NOTEBOOK_07_DRIVE_SERVICE,
        NOTEBOOK_07_TO_08_METADATA_DRIVE_FILE_ID,
    )
)


if not BLOCK_10_RELOADED_METADATA_BYTES:

    raise RuntimeError(
        "Persisted Notebook 07 metadata was empty."
    )


BLOCK_10_RELOADED_METADATA = json.loads(
    BLOCK_10_RELOADED_METADATA_BYTES.decode(
        "utf-8"
    )
)


# =============================================================================
# Exact state-dict comparison helper
# =============================================================================

def block_10_state_dict_exact_match(
    observed_state_dict,
    expected_state_dict,
):

    if not (
        isinstance(
            observed_state_dict,
            dict,
        )
        and
        isinstance(
            expected_state_dict,
            dict,
        )
    ):

        return False


    if (
        tuple(
            observed_state_dict.keys()
        )
        !=
        tuple(
            expected_state_dict.keys()
        )
    ):

        return False


    return all(
        torch.equal(
            observed_state_dict[
                parameter_name
            ]
            .detach()
            .cpu(),

            expected_state_dict[
                parameter_name
            ]
            .detach()
            .cpu(),
        )

        for parameter_name
        in expected_state_dict
    )


# =============================================================================
# Checkpoint read-back contract
# =============================================================================

BLOCK_10_CHECKPOINT_TYPE_VALID = (
    BLOCK_10_RELOADED_CHECKPOINT.get(
        "checkpoint_type"
    )
    ==
    "validated_representation_model_handover"
)


BLOCK_10_CHECKPOINT_SOURCE_VALID = (
    BLOCK_10_RELOADED_CHECKPOINT.get(
        "source_notebook"
    )
    ==
    "07_social_path"
)


BLOCK_10_CHECKPOINT_TARGET_VALID = (
    BLOCK_10_RELOADED_CHECKPOINT.get(
        "target_notebook"
    )
    ==
    "08_transformative_mechanism"
)


BLOCK_10_CHECKPOINT_PARAMETER_COUNT_VALID = (
    BLOCK_10_RELOADED_CHECKPOINT.get(
        "total_parameter_count"
    )
    ==
    TOTAL_PARAMETER_COUNT
)


BLOCK_10_STATE_DICT_KEYS_VALID = (
    set(
        BLOCK_10_RELOADED_CHECKPOINT.get(
            "state_dicts",
            {},
        ).keys()
    )
    ==
    set(
        REQUIRED_MODULES.keys()
    )
)


BLOCK_10_CHECKPOINT_MODULE_PARAMETER_COUNTS_VALID = (
    BLOCK_10_RELOADED_CHECKPOINT.get(
        "parameter_counts"
    )
    ==
    MODULE_PARAMETER_COUNTS
)


BLOCK_10_CHECKPOINT_STATE_DICTS_EXACT = all(
    block_10_state_dict_exact_match(
        BLOCK_10_RELOADED_CHECKPOINT[
            "state_dicts"
        ][
            module_name
        ],
        module.state_dict(),
    )

    for (
        module_name,
        module,
    ) in REQUIRED_MODULES.items()
)


BLOCK_10_CHECKPOINT_ARCHITECTURE_NAMES_VALID = all(
    BLOCK_10_RELOADED_CHECKPOINT[
        "architecture"
    ][
        module_name
    ]
    ==
    module.__class__.__name__

    for (
        module_name,
        module,
    ) in REQUIRED_MODULES.items()
)


BLOCK_10_CHECKPOINT_READBACK_VALID = all(
    [
        BLOCK_10_CHECKPOINT_TYPE_VALID,
        BLOCK_10_CHECKPOINT_SOURCE_VALID,
        BLOCK_10_CHECKPOINT_TARGET_VALID,
        BLOCK_10_CHECKPOINT_PARAMETER_COUNT_VALID,
        BLOCK_10_STATE_DICT_KEYS_VALID,
        BLOCK_10_CHECKPOINT_MODULE_PARAMETER_COUNTS_VALID,
        BLOCK_10_CHECKPOINT_STATE_DICTS_EXACT,
        BLOCK_10_CHECKPOINT_ARCHITECTURE_NAMES_VALID,
    ]
)


# =============================================================================
# Metadata read-back contract
# =============================================================================

BLOCK_10_METADATA_TYPE_VALID = (
    BLOCK_10_RELOADED_METADATA.get(
        "metadata_type"
    )
    ==
    "media_ai_notebook_07_to_08_representation_handover"
)


BLOCK_10_METADATA_SOURCE_VALID = (
    BLOCK_10_RELOADED_METADATA.get(
        "source_notebook"
    )
    ==
    "07_social_path"
)


BLOCK_10_METADATA_TARGET_VALID = (
    BLOCK_10_RELOADED_METADATA.get(
        "target_notebook"
    )
    ==
    "08_transformative_mechanism"
)


BLOCK_10_METADATA_PARAMETER_COUNT_VALID = (
    BLOCK_10_RELOADED_METADATA.get(
        "total_parameter_count"
    )
    ==
    TOTAL_PARAMETER_COUNT
)


BLOCK_10_METADATA_COMPONENTS_VALID = all(
    [
        set(
            BLOCK_10_RELOADED_METADATA.get(
                "components",
                {},
            ).keys()
        )
        ==
        set(
            REQUIRED_MODULES.keys()
        ),

        all(
            BLOCK_10_RELOADED_METADATA[
                "components"
            ][
                module_name
            ][
                "class"
            ]
            ==
            module.__class__.__name__

            and

            BLOCK_10_RELOADED_METADATA[
                "components"
            ][
                module_name
            ][
                "parameters"
            ]
            ==
            MODULE_PARAMETER_COUNTS[
                module_name
            ]

            for (
                module_name,
                module,
            ) in REQUIRED_MODULES.items()
        ),
    ]
)


BLOCK_10_NOTEBOOK_08_READY = (
    BLOCK_10_RELOADED_METADATA[
        "notebook_08_starting_state"
    ][
        "ready_to_initialise"
    ]
    is True
)


BLOCK_10_TRANSFORMATIVE_STATE_ABSENT = all(
    [
        (
            BLOCK_10_RELOADED_METADATA[
                "notebook_08_starting_state"
            ][
                "transformative_mechanism_instantiated"
            ]
            is False
        ),

        (
            BLOCK_10_RELOADED_METADATA[
                "notebook_08_starting_state"
            ][
                "transformation_weights_instantiated"
            ]
            is False
        ),

        (
            BLOCK_10_RELOADED_METADATA[
                "notebook_08_starting_state"
            ][
                "recurrent_states_instantiated"
            ]
            is False
        ),
    ]
)


BLOCK_10_FUTURE_CONTEXT_PROHIBITED = (
    BLOCK_10_RELOADED_METADATA[
        "notebook_08_starting_state"
    ][
        "future_context_permitted"
    ]
    is False
)


BLOCK_10_CHECKPOINT_BOUNDARY_VALID = all(
    [
        BLOCK_10_RELOADED_CHECKPOINT[
            "architectural_boundary"
        ][
            "transformative_mechanism_instantiated"
        ]
        is False,

        BLOCK_10_RELOADED_CHECKPOINT[
            "architectural_boundary"
        ][
            "transformation_weights_instantiated"
        ]
        is False,

        BLOCK_10_RELOADED_CHECKPOINT[
            "architectural_boundary"
        ][
            "recurrent_states_instantiated"
        ]
        is False,

        BLOCK_10_RELOADED_CHECKPOINT[
            "architectural_boundary"
        ][
            "future_context_permitted"
        ]
        is False,
    ]
)


BLOCK_10_METADATA_READBACK_VALID = all(
    [
        BLOCK_10_METADATA_TYPE_VALID,
        BLOCK_10_METADATA_SOURCE_VALID,
        BLOCK_10_METADATA_TARGET_VALID,
        BLOCK_10_METADATA_PARAMETER_COUNT_VALID,
        BLOCK_10_METADATA_COMPONENTS_VALID,
        BLOCK_10_NOTEBOOK_08_READY,
        BLOCK_10_TRANSFORMATIVE_STATE_ABSENT,
        BLOCK_10_FUTURE_CONTEXT_PROHIBITED,
        BLOCK_10_CHECKPOINT_BOUNDARY_VALID,
    ]
)


# =============================================================================
# Final validation
# =============================================================================

NOTEBOOK_07_BLOCK_10_VALID = all(
    [
        BLOCK_10_PARAMETER_COUNT_VALID,
        BLOCK_10_CHECKPOINT_PERSISTED,
        BLOCK_10_METADATA_PERSISTED,
        BLOCK_10_CHECKPOINT_READBACK_VALID,
        BLOCK_10_CHECKPOINT_STATE_DICTS_EXACT,
        BLOCK_10_METADATA_READBACK_VALID,
    ]
)


if not NOTEBOOK_07_BLOCK_10_VALID:

    raise RuntimeError(
        "Notebook 07 Block 10 handover persistence "
        "or read-back validation failed."
    )


# =============================================================================
# Block completion
# =============================================================================

NOTEBOOK_07_BLOCK_10_COMPLETE = True


# =============================================================================
# Notebook 08 exports
# =============================================================================

NOTEBOOK_08_REPRESENTATION_CHECKPOINT_DRIVE_FILE_ID = (
    NOTEBOOK_07_TO_08_CHECKPOINT_DRIVE_FILE_ID
)


NOTEBOOK_08_REPRESENTATION_METADATA_DRIVE_FILE_ID = (
    NOTEBOOK_07_TO_08_METADATA_DRIVE_FILE_ID
)


# =============================================================================
# Final report
# =============================================================================

print("=" * 72)

print(
    "Media AI — Notebook 07, Block 10: "
    "Validated Representation-Model Handover Persistence"
)

print("=" * 72)

print(
    f"Block version               : "
    f"{NOTEBOOK_07_BLOCK_10_VERSION}"
)

print("-" * 72)

print(
    f"Backbone parameters         : "
    f"{MODULE_PARAMETER_COUNTS['backbone']:,}"
)

print(
    f"Global confluent parameters : "
    f"{MODULE_PARAMETER_COUNTS['global_confluent']:,}"
)

print(
    f"Psychological parameters    : "
    f"{MODULE_PARAMETER_COUNTS['psychological_head']:,}"
)

print(
    f"Factual parameters          : "
    f"{MODULE_PARAMETER_COUNTS['factual_head']:,}"
)

print(
    f"Social parameters           : "
    f"{MODULE_PARAMETER_COUNTS['social_head']:,}"
)

print("-" * 72)

print(
    f"Total persisted parameters  : "
    f"{TOTAL_PARAMETER_COUNT:,}"
)

print("-" * 72)

print(
    f"Checkpoint filename         : "
    f"{NOTEBOOK_07_TO_08_CHECKPOINT_FILENAME}"
)

print(
    f"Checkpoint Drive operation  : "
    f"{NOTEBOOK_07_TO_08_CHECKPOINT_DRIVE_OPERATION}"
)

print(
    f"Checkpoint Drive file ID    : "
    f"{NOTEBOOK_07_TO_08_CHECKPOINT_DRIVE_FILE_ID}"
)

print(
    f"Checkpoint size             : "
    f"{len(BLOCK_10_CHECKPOINT_BYTES) / (1024 ** 2):.3f} MB"
)

print("-" * 72)

print(
    f"Metadata filename           : "
    f"{NOTEBOOK_07_TO_08_METADATA_FILENAME}"
)

print(
    f"Metadata Drive operation    : "
    f"{NOTEBOOK_07_TO_08_METADATA_DRIVE_OPERATION}"
)

print(
    f"Metadata Drive file ID      : "
    f"{NOTEBOOK_07_TO_08_METADATA_DRIVE_FILE_ID}"
)

print(
    f"Metadata size               : "
    f"{len(BLOCK_10_METADATA_BYTES) / 1024:.3f} KB"
)

print("-" * 72)

print(
    f"Checkpoint read-back valid  : "
    f"{BLOCK_10_CHECKPOINT_READBACK_VALID}"
)


print(
    f"Checkpoint states exact     : "
    f"{BLOCK_10_CHECKPOINT_STATE_DICTS_EXACT}"
)

print(
    f"Module counts reproduced    : "
    f"{BLOCK_10_CHECKPOINT_MODULE_PARAMETER_COUNTS_VALID}"
)

print(
    f"Architecture names valid    : "
    f"{BLOCK_10_CHECKPOINT_ARCHITECTURE_NAMES_VALID}"
)

print(
    f"Metadata read-back valid    : "
    f"{BLOCK_10_METADATA_READBACK_VALID}"
)


print(
    f"Metadata components valid   : "
    f"{BLOCK_10_METADATA_COMPONENTS_VALID}"
)

print(
    f"Notebook 08 ready           : "
    f"{BLOCK_10_NOTEBOOK_08_READY}"
)

print(
    f"Transformative state absent : "
    f"{BLOCK_10_TRANSFORMATIVE_STATE_ABSENT}"
)

print(
    f"Block valid                 : "
    f"{NOTEBOOK_07_BLOCK_10_VALID}"
)

print(
    f"Block complete              : "
    f"{NOTEBOOK_07_BLOCK_10_COMPLETE}"
)

print("=" * 72)

print(
    "Notebook 07 representation-model handover "
    "persisted and read back successfully with exact state-dict "
    "reproduction."
)

print(
    "The existing Notebook 07 Google Drive API service was reused; "
    "no Google Drive filesystem mount or additional authorisation "
    "was requested."
)

print(
    "No transformative mechanism, transformation weight, "
    "or recurrent state was created or persisted."
)

print(
    "Notebook 08 may initialise independently from the "
    "persisted Drive artefacts."
)

print("=" * 72)

========================================================================
Media AI — Notebook 07, Block 10: Validated Representation-Model Handover Persistence
========================================================================
Block version               : 1.1
------------------------------------------------------------------------
Backbone parameters         : 590,592
Global confluent parameters : 197,376
Psychological parameters    : 37,538
Factual parameters          : 34,442
Social parameters           : 34,055
------------------------------------------------------------------------
Total persisted parameters  : 894,003
------------------------------------------------------------------------
Checkpoint filename         : notebook_07_final_checkpoint.pt
Checkpoint Drive operation  : updated
Checkpoint Drive file ID    : 19vnqvir-mQ385_6zjjuqwMv924IAlYdG
Checkpoint size             : 3.419 MB
------------------------------------------------------------------------
Metadata filename           : notebook_07_final_metadata.json
Metadata Drive operation    : updated
Metadata Drive file ID      : 1Dx7Un82PBvYQoAERuHXNpWcpbTO_OtZp
Metadata size               : 1.448 KB
------------------------------------------------------------------------
Checkpoint read-back valid  : True
Checkpoint states exact     : True
Module counts reproduced    : True
Architecture names valid    : True
Metadata read-back valid    : True
Metadata components valid   : True
Notebook 08 ready           : True
Transformative state absent : True
Block valid                 : True
Block complete              : True
========================================================================
Notebook 07 representation-model handover persisted and read back successfully with exact state-dict reproduction.
The existing Notebook 07 Google Drive API service was reused; no Google Drive filesystem mount or additional authorisation was requested.
No transformative mechanism, transformation weight, or recurrent state was created or persisted.
Notebook 08 may initialise independently from the persisted Drive artefacts.
========================================================================